### ISSUE TITLE
Which version(s) of Apache license?

### ISSUE THREAD

**Issue by RyDroid** [termux/termux-app#10]
Hi.

In README.md, it is written that "Contains code from Terminal Emulator for Android which is released under the Apache License". But is it under version 1.0, version 2.0, version 1.0 and 2.0, version 1.0 or at your option any later, version 2.0 or at your option any later?

Regards.

**Comment by fornwall** [comment]
Thanks, I clarified that Terminal Emulator for Android (https://github.com/jackpal/Android-Terminal-Emulator) uses Apache License 2.0 now!

**Comment by RyDroid** [comment]
Thanks.
