### ISSUE TITLE
Alias command chaining not working from ~./bash_profile

### ISSUE THREAD

**Issue by ni554n** [termux/termux-app#100]
I've added an `alias uu='apt update && apt upgrade'`
on `~/.bash_profile`.
But termux doesn't seem to execute the `apt upgrade` command.

![Screenshot](http://i.imgur.com/fuaCvKa.png)

**Comment by sunziping2016** [comment]
maybe you can try putting the alias in ~/.bashrc

**Comment by tinydynamite00** [comment]
@ni554n I don't know how you typed the alias in <code>~/.bash_profile</code> but it looks as though unneeded whitespace is appended after the <code>= </code> sign, before the first quoting character <code>' </code> in your example. I believe the <code>shopt</code> built-in has alias expansion, <code>expand_aliases  on</code>, by default but you can double-check by running <code>shopt</code> without any arguments. One other suggestion, if you want bash to read then run this aliased compound command automagically in the event upgrades are available, add <code>-y </code> as the option to the second command before  the final quoting character. 

I should mention this chain does work for me under the same version of <code>apt</code> as you have installed.

**Comment by fornwall** [comment]
@ni554n Can you paste the output of running `alias uu`?

**Comment by ni554n** [comment]
I just removed the `~/.bash_profile` that has been created with **_nano_**. Then I've created a new file with **_vi_**; added this line:
`alias uu='apt update && apt upgrade'`
and voila. It's working.

But here's the thing. I removed that and tried to reproduce the issue. But I failed. File created with **_nano_** works as expected.

**Comment by Subhash3** [comment]
Bro how to run and edit vi. bashrc

**Comment by Quasic** [comment]
@Subhash3 https://wiki.termux.com/wiki/Text_Editors#Vim
