### ISSUE TITLE
Sqlmap location

### ISSUE THREAD

**Issue by Switjoseph** [termux/termux-app#1000]
Hello, i recently installed termux together with sqlmap and i have been using it but the problem is i can't even use File Manager to navigate to where the sqlmap is stored or termux 
I want to copy the files saved by using sqlmap but can't find it.
Help me out

**Comment by xeffyr** [comment]
Sqlmap has no any relation with official Termux packages.
About copying files - is it a problem to use commands "termux-setup-storage", then "cp" to copy them to /sdcard ? I think not.
