### ISSUE TITLE
Can't run applications from fresh reinstall: CANNOT LINK EXECUTABLE: cannot locate symbol "nl_langinfo" referenced by ....

### ISSUE THREAD

**Issue by pricklygorse** [termux/termux-app#1001]
Hi, yesterday I installed termux and managed to follow these instructions with almost no issues to get R running with Termux https://www.reddit.com/r/rstats/comments/8rnxz2/instructions_for_r_onthego/ Lots of WARNING: linker errors but everything worked completely fine. unset LD_PRELOAD was required because of R segfaults.

Today, I uninstalled and reinstalled termux, to reset it and to try installing Termux debian. There is no Pandoc package for Termux, which I require for converting R documents to word, but it is available on debian (and it runs fine with R under UserLAnd debian, but Termux apparently runs applications faster than UserLAnd). 

I now cannot do anything with Termux, even after uninstall-reinstall, with a failsafe complete reset also. pkg update, and pkg install work fine, but I cant run almost anything because of a CANNOT LINK EXECUTABLE: cannot locate symbol "nl_langinfo" referenced by .... error. Trying the very first steps of the reddit tutorial above to add the pointless repository again fails from this fresh install because apt-key add fails with  CANNOT LINK EXECUTABLE: cannot locate symbol "nl_langinfo" referenced by "libreadline.so.7". pkg install nano works fine, but nano fails with "nl_langinfo" referenced by "nano", same for vim etc.

Here is the output of termux-info. Device is a kindle fire, which I know has a modified android, but yesterday Termux was running completely fine, and no issues with UserLAnd either. I've searched but I cant find an answer
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.19-g9c9ae7e286f #1 SMP PREEMPT Thu Jun 1 03:56:33 UTC 2017 armv8l Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
Amazon
Device model:
KFDOWI

**Comment by Grimler91** [comment]
Hi, thanks for reporting. This is unfortunately an issue after the latest libandroid-support update. We have some instructions in https://github.com/termux/termux-packages/issues/3283 with a temporarily fix from a fail-safe session

**Comment by DMSalesman** [comment]
@Grimler91

Good day. After following all the steps and downgrading `libandroid-support` to version 22-1, everything works properly.

After `apt update` and `upgrade`, though, `tree` still complains about missing the `nl_langinfo` symbol. `libandroid-support` is now at version 24.

Could you look into it, since it seems to be the same issue as the original poster?

**Comment by fornwall** [comment]
@DMSalesman Thanks for reporting, `tree` has now been updated!

**Comment by WeeBeasties** [comment]
I have this issue with R in termux on my chromebook. I have no problems with bash, nano, tree, python, etc... just R. I followed the directions from this website: https://conr.ca/post/installing-r-on-android-via-termux/
I had it all working, but after running an update in termux, R got nailed. Any suggestions and/or help would be greatly appreciated.

**Comment by alvfig** [comment]
`tmate` seems to need an related update, too.

```shell
$ tmate
CANNOT LINK EXECUTABLE: cannot locate symbol "nl_langinfo" referenced by "tmate"...
page record for 0xb6e8b02c was not found (block_size=16)
```

**Comment by AntoniusVip** [comment]
@DesKa->> php
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"...
page record for 0x7f86159010 was not found (block_size=16)
