### ISSUE TITLE
multiple instances support

### ISSUE THREAD

**Issue by Whishay** [termux/termux-app#1005]
**Feature description**
Describe the feature and why you want it.
I am turning my android phone to productivity device, one of the most popular cases
for me is that I need connect to remote hosts via openssh from within termux.

Unfortunately only one tab is available at current, any idea to support multiple tabs or instances?

It seems the latter is a bit easier and my idea of workaround is running multiple instances with different
process(app) names( 'termux1', 'termux2', etc), however, I failed to start it and I am not a veteran developer of android studio, any one can help me on this?

I am using android studio 3.3 but did not find any 'appName' related segments after an initial googling.

**Reference implementation**
Does another app/terminal emulator have this feature?
Provide links to more background information
Not yet.

**Comment by Grimler91** [comment]
You can already have different "tabs" by opening several sessions in the left drawer. You can then switch between them with [ctrl + alt + # if you have a hardware keyboard](https://wiki.termux.com/wiki/Hardware_Keyboard). It is also possible run several shells side-by-side with tmux. 

Is that sort of what you are after?

**Comment by Whishay** [comment]
Wow..., that is what exactly I wanted to have, then it is completely possible for me to finish 80+% work on my phone, thanks for that, cheers!.

**Comment by artisticfox8** [comment]
> You can already have different "tabs" by opening several sessions in the left drawer. You can then switch between them with [ctrl + alt + # if you have a hardware keyboard](https://wiki.termux.com/wiki/Hardware_Keyboard). It is also possible run several shells side-by-side with tmux.
> 
> Is that sort of what you are after?

Which left drawer?

**Comment by Grimler91** [comment]
> Which left drawer?

The one that opens from the left in for example this screen capture:
https://wiki.termux.com/images/1/1d/Start_failsafe_session.mp4

**Comment by artisticfox8** [comment]
> > Which left drawer?
> 
> The one that opens from the left in for example this screen capture:
> https://wiki.termux.com/images/1/1d/Start_failsafe_session.mp4

Thanks. Could you add a hamburger menu, so it's more obvious?
