### ISSUE TITLE
0.66 brokes non adaptive icons

### ISSUE THREAD

**Issue by 532910** [termux/termux-app#1006]
LineageOS 14.1-20190126
Android 7.1.2 (no adaptive icon support)

Termux 0.65 (fine, fullsize icon): 
![image](https://user-images.githubusercontent.com/14617699/52080139-23fc9500-25a8-11e9-9a3c-d77cb13debb9.png)

Termux 0.66 (ugly, small icon): 
![image](https://user-images.githubusercontent.com/14617699/52080146-2828b280-25a8-11e9-8a63-b283e072f9e9.png)

**Comment by xeffyr** [comment]
Fix for launchers not supporting adaptive icons: https://github.com/termux/termux-app/commit/7be1fe5555d0673a5b17ad6bb34bc18627de7684.

Icon by itself will continue to look similar to the adaptive:
* Normal: https://github.com/termux/termux-app/blob/7be1fe5555d0673a5b17ad6bb34bc18627de7684/art/ic_launcher2.png
* Round: https://github.com/termux/termux-app/blob/7be1fe5555d0673a5b17ad6bb34bc18627de7684/art/ic_launcher2_round.png
