### ISSUE TITLE
grep not working

### ISSUE THREAD

**Issue by chadpaine** [termux/termux-app#1007]

**Comment by xeffyr** [comment]
```
pkg install grep
hash -r
```

And grep works...
Default grep is from busybox, so if you use it immediately after installation, you need to refresh bash's search path via `hash -r`.

Though, in busybox's grep yes, this problem exists.

**Comment by chadpaine** [comment]
User error. I didn't realize grep wanted me to explicitly state in the comand line arguments 'grep "e" <file_or_dir>' as in search specifically this file or directory. That is, 'grep "e" imafile.txt"' and 'grep "e" -r .' work.
