### ISSUE TITLE
Add option to disable TermuxOpenReceiver or permission managment

### ISSUE THREAD

**Issue by bitboulder** [termux/termux-app#1010]
At first thank you very much for making this great app.

Though TermuxOpenReceiver the files in $HOME are available to other apps.
That is also true for sensible data like ssh-keys.
Therefore I want not to use TermuxOpenReceiver.

Could you add a config option to disable TermuxOpenReceiver?
Or more powerfull, could you only make files available which have the read permission for all other users (at least -rw-r--r-- for files and -rwxr-xr-x for directories)?
That would be a very good feature to protect sensible data.

**Comment by bitboulder** [comment]
> > Though TermuxOpenReceiver the files in $HOME are available to other apps.
> > That is also true for sensible data like ssh-keys.
> 
> O_o
> SSH keys are not password protected ?

They are password protected but still I don't want them to be readable
because if compromised the security more or less falls to the level
of simple password authentification.

> 
> > Could you add a config option to disable TermuxOpenReceiver?
> 
> It is hardcoded into AndroidManifest.xml.

I thought of an option which hides all files.

> 
> **But I still agree that we need proper file access management.** And not only because of privacy issues.
>

**Comment by twaik** [comment]
Done in 075a080f00e7ec637e69cc714c49239718bfda3d.
