### ISSUE TITLE
Termux ignores the last character in the pasted text

### ISSUE THREAD

**Issue by KaMyKaSii** [termux/termux-app#1011]
**Problem description**
Sometimes when you press Enter after pasting something, Termux simply ignores the last character in the pasted text. This problem happens very often with me, I can not say exactly why it starts but when it starts it continues during entire Termux session (so the temporary solution is to close Termux and open again). If after pasting, I type another character and then delete it, it continues with the same error. But if after paste I delete the last character and re-type it, it works. I made a video trying to show if my explanation was not very clear. And many thanks to all the contributors of this project, the Termux is incredible!

**Additional information**
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 4.4.78-perf+ #1 SMP PREEMPT Tue Dec 25 18:32:48 CST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
asus
Device model:
ASUS_Z01KD
https://drive.google.com/file/d/1w-sF1wW2NLbNDV-y-TwfrDkIbMx_ymvF/view?usp=drivesdk

**Comment by xeffyr** [comment]
Never experienced such issue.
I watched your [video](https://drive.google.com/file/d/1w-sF1wW2NLbNDV-y-TwfrDkIbMx_ymvF/view?usp=drivesdk) and it looks like it correctly pastes the text. Last character gets deleted when you press enter which points on keyboard issue.

Which keyboard do you use ?

**Comment by KaMyKaSii** [comment]
> Never experienced such issue.
> I watched your [video](https://drive.google.com/file/d/1w-sF1wW2NLbNDV-y-TwfrDkIbMx_ymvF/view?usp=drivesdk) and it looks like it correctly pastes the text. Last character gets deleted when you press enter which points on keyboard issue.
> 
> Which keyboard do you use ?

Yes, the last character is only deleted after I hit Enter. I use SwiftKey Beta. I will test with the standard keyboard of my Zenfone 4 (ZenUI Keyboard) and see if the problem continues

**Comment by Auxilus** [comment]
The problem only occurs with SwiftKey keyboard.

**Comment by KaMyKaSii** [comment]
Confirmed, really only happens with SwiftKey. I'm going to report to the developers, thank you
