### ISSUE TITLE
Odd Termux Beta Program Issue... 

### ISSUE THREAD

**Issue by ibuprophen1** [termux/termux-app#1017]
I wasn't sure if this is already known but, I'll try to explain it the best way I can. 

First, the following image, from the Google Play Store, reflects the Termux Beta Program Being full... 

[1-termux - play store](https://user-images.githubusercontent.com/18060271/52375797-8208fc80-2a2e-11e9-9441-f3280767871b.png)

Secondly, someone had provided me a link to the Termux Beta Program Sign up link via the Browser. So the following image reflects that I had Signed up for the Termux Beta Program... 

[2-termux - beta via browser](https://user-images.githubusercontent.com/18060271/52375829-92b97280-2a2e-11e9-9b93-b01fadf7e7a3.png)

Finally, the typical process for Beta Testers is to wait a bit, uninstall the Non Beta app and open the Play Store to install the Beta Apo but, the following image reflects what I see on the Google Play Store that shows that I'm a Beta Tester but, it doesn't provide me any way to install it. 

[3-termux - play store post beta enroll](https://user-images.githubusercontent.com/18060271/52375541-e2e40500-2a2d-11e9-85b6-7961b8c1ee39.png)

I ended up reinstalling the Non Beta Termux App... 

It's not a show stopper for me but, I wanted to bring this to your attention. 

Thank you very much for your time, support and understanding with this. :-) 

~Ibuprophen

**Comment by fornwall** [comment]
Hello and thanks for reporting!

The beta program is not used for the Termux app. Unfortunately it can not be disabled in Google Play, AFAIK. But as you notice, there is just no point in joining the beta program for this app currently.
