### ISSUE TITLE
Selected text difficult to distinguish in native text input bar

### ISSUE THREAD

**Issue by ticalc-travis** [termux/termux-app#1019]
When selecting text in the text input view (upon swiping the extra keys), highlighted text is not distinct from the rest, so it is impossible to easily see what is selected. Same problem when using the backspace-swipe feature in Gboard, which allows deleting the last few words: There is no background highlight that shows what is getting deleted.

To reproduce:
1. Open Termux and access the input line
2. Enter some text and then tap and hold to activate text selection mode

Actual behavior: There is no visual difference between selected and unselected text. Also, the text selection handles are virtually the same color as the background, sometimes making them invisible.

![image](https://user-images.githubusercontent.com/3048435/52452165-9b31ac00-2b07-11e9-985c-525c058c970f.png)

Expected behavior: The background of the selected text should be distinct from that of selected, and the selection handles' color should contrast sharply against the widget background.

termux-info:
Updatable packages: All packages up to date
System information: Linux localhost 3.18.14-14372886-QB20859662 #1 SMP PREEMPT Fri Nov 30 
16:00:00 KST 2018 armv8l Android
Termux-packages arch: arm
Android version: 8.1.0
Device manufacturer: samsung
Device model: SM-J727U

**Comment by xeffyr** [comment]
Confirming that problem exists:
![screenshot_20190208-024432_termux](https://user-images.githubusercontent.com/25881154/52452530-fdac9b80-2b4b-11e9-8586-fbcfcdf67fc4.jpg)
