### ISSUE TITLE
Zooming with Keyboard + Mouse

### ISSUE THREAD

**Issue by jazzpi** [termux/termux-app#102]
I have an ODROID XU 4, which has no touchscreen but is controlled via KBM. Is there any way to change the font size with this since AFAIK there is no way to replicate a pinch zoom with KBM?

**Comment by fornwall** [comment]
See https://termux.com/hardware-keyboard.html - you should be able to change font size by pressing Ctrl+Shift and + or -. Does that work?

**Comment by al-hub** [comment]
In my case (termux on Android 10), it worked by pressing Ctrl+Alt and + or -

**Comment by al-hub** [comment]
In my case (termux on Android 10), it worked by pressing Ctrl+Alt and + or -
