### ISSUE TITLE
Naive Text Input View sends a newline on completion

### ISSUE THREAD

**Issue by epitron** [termux/termux-app#1020]
When pressing the "send" button after entering text using the native input field (above the keyboard), it appends a newline character (\n), which many cli programs interpret as "enter".

However, real keyboard sends a carriage return (\r). Some programs expect this character, and either ignore the \n or interpret it as a soft enter.

Is there a reason \n was chosen over \r? It makes more sense to emulate pressing the enter key after the input.

**Comment by fornwall** [comment]
Thanks for reporting! This change will be part of the v0.67 update of the app which is to be released shortly.

**Comment by epitron** [comment]
Great! Thank you for being so quick!
