### ISSUE TITLE
`java.lang.RuntimeException: Unable to create directory: /data/data/com.termux/files/usr-staging/share` when installing the app on an adopted SD

### ISSUE THREAD

**Issue by PorygonZRocks** [termux/termux-app#1023]
Full logcat:

```
Bootstrap error
java.lang.RuntimeException: Unable to create directory: /data/data/com.termux/files/usr-staging/share
at com.termux.app.c.c(SourceFile:166)
at com.termux.app.c.b(SourceFile:50)
at com.termux.app.c$1.run(SourceFile:107)
```
My guess is that Termux is using the path `/data/data/com.termux/files/` rather than using `getFilesDir` or whatever it is.

**Comment by PorygonZRocks** [comment]
Looking at the code, [`TermuxService.FILES_PATH`](https://github.com/termux/termux-app/blob/330301899ad9ff76c2257e700a09964f512017de/app/src/main/java/com/termux/app/TermuxService.java#L49) is set to `"/data/data/com.termux/files"`. This is probably why, since if it's on the adopted SD I don't think this path would work.

**Comment by Grimler91** [comment]
Termux unfortunately won't work with another path without recompiling everything. 

The app uses `/data/data/com.termux/files`, as you pointed out, and all the packages are using `/data/data/com.termux/files/usr/[...]` as path to dependencies, conf files and others. 

If you want to use another PREFIX, then the apps and all packages need to be recompiled pointing to the new PREFIX unfortunately.

There was some experimenting done with a [dynamic PREFIX](https://github.com/termux/termux-packages/issues/2902) but patching all packages to use this is a lot of work and probably won't happen.
