### ISSUE TITLE
use VectorDrawable for text select icon

### ISSUE THREAD

**Issue by Lzhiyong** [termux/termux-app#1036]
The svg resources download https://github.com/Templarian/MaterialDesign/files/1950854/text-select-handle.zip

========================================================
text_select_handle_left_material.xml
<vector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt"
    android:viewportWidth="24"
    android:viewportHeight="24"
    android:width="24dp"
    android:height="24dp">
    <path
        android:pathData="M21 3v9a9 9 0 0 1 -9 9 9 9 0 0 1 -9 -9 9 9 0 0 1 9 -9z"
        android:fillColor="#2196F3" />
</vector>

========================================================
text_select_handle_right_material.xml
<vector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt"
    android:viewportWidth="24"
    android:viewportHeight="24"
    android:width="24dp"
    android:height="24dp">
    <path
        android:pathData="M3 3L3 12A9 9 0 0 0 12 21A9 9 0 0 0 21 12A9 9 0 0 0 12 3L3 3z"
        android:fillColor="#2196F3" />
</vector>

========================================================
VectorDrawable to BitmapDrawable

public BitmapDrawable getBitmapFromVectorDrawable(Context context, int drawableId) {
		Drawable drawable = ContextCompat.getDrawable(context, drawableId);
		if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
			drawable = (DrawableCompat.wrap(drawable)).mutate();
		}

		Bitmap bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(),
											drawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);
		Canvas canvas = new Canvas(bitmap);
		drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
		drawable.draw(canvas);

		return new BitmapDrawable(getResources(),bitmap);
	}

**Comment by xeffyr** [comment]
Closing as Termux uses selection handle drawable provided by Android:
```
R.drawable.text_select_handle_left_material
```
```
R.drawable.text_select_handle_right_material
```

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-app/commit/72981fb9816fa39462f88c8bfc382ed3761f4e31.
