### ISSUE TITLE
Curl: (3) URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by hollysheep** [termux/termux-app#1039]
Hi,

i tried to send a file from my smartphone (oneplus 3; lineage os 15.1) with curl to my raspberry pi with raspbian stretch. Here i have the following error after enter the password.

```
curl --upload-file /data/data/com.termux/files/home/test -u 'raspberrypi/pi' smb://192.168.10.23/usb
Enter host password for user 'raspberrypi/pi':
curl: (3) URL using bad/illegal format or missing URL
```

whats wrong with my command?

**Comment by xeffyr** [comment]
Change `smb://192.168.10.23/usb` to `smb://192.168.10.23/usb/`.

**Comment by Ajioz** [comment]
curl -F value=120 -H "X-AIO-Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \ https://io.adafruit.com/api/v2/Ajioz/feeds/servo-motor/data

Whats wrong with this code, I ran this on mac Computer its not working but worked on Windows OS

**Comment by xeffyr** [comment]
@Ajioz Remove backslash before URL.
```
curl -F value=120 -H "X-AIO-Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" https://io.adafruit.com/api/v2/Ajioz/feeds/servo-motor/data
```

**Comment by Ajioz** [comment]
@xeffyr Fantastic, fantastic.  You are awesome.
Many thanks

**Comment by sandhya019** [comment]
curl -u admin:Sujoydey@03 -X GET "http://localhost:8081/service/rest/v1/search/assets?group=$group_name&name=$name_oftheproj&version=$Release_Version&maven.extension=$extension" --output sujoy.jar

facing issue 
curl: (3) URL using bad/illegal format or missing URL
Build step 'Execute shell' marked build as failure

**Comment by Swetha554** [comment]
$ curl -d '{"QTEST_API_KEY": "[MASKED]", "QTEST_PATH": "https://qtest.t-mobile.com/", "QTEST_PROJECT_ID": 108, "QTEST_TEST_CASE_ID": [TS-677], "QTEST_RUN_CONTAINER_ID":[165759]}' -H "Content-Type: application/qtest" -X POST '/runTests/' -o Results.xml

Facing Below error for above curl statement . Can anyone help me out in resolving it
curl: (3) URL using bad/illegal format or missing URL
