### ISSUE TITLE
I can't find the APT manpage

### ISSUE THREAD

**Issue by JacobTDC** [termux/termux-app#1041]
I can't find the manpage for apt, I've even checked `$PREFIX/share/man`. Is there any way to install the APT manpages?

**Comment by JacobTDC** [comment]
I've done some research on the issue, but apparently it's not a common issue...

**Comment by xeffyr** [comment]
> Is there any way to install the APT manpages?

Currently no.
Problem is that APT manpages can't be built for some reason.

**Comment by JacobTDC** [comment]
Okay. Thanks.
