### ISSUE TITLE
Cant install mysqlclient using pkg install command ;  "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by baties** [termux/termux-app#1042]
**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by baties** [comment]
![screenshot_2019-02-23-08-22-07](https://user-images.githubusercontent.com/9303641/53281827-3fd8fe00-3744-11e9-9fcd-53c24c40a0d5.png)

**Comment by Grimler91** [comment]
```
$ mysql_config
The program 'mysql_config' is not installed. Install it by executing:
 pkg install mariadb
```

So install mariadb.

**Comment by baties** [comment]
Unfortunately it has error too :

Setting up pcre (8.42) ...
Setting up libedit (20181209-3.1-0) ...
Setting up mariadb (10.3.12-1) ...
Initializing mysql data directory...
/data/data/com.termux/files/usr/bin/my_print_defaults: Can't read dir of '/data/data/com.termux/files/usr/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted
Installing MariaDB/MySQL system tables in '/data/data/com.termux/files/usr/var/lib/mysql' ...
/data/data/com.termux/files/usr/bin/mysqld: Can't read dir of '/data/data/com.termux/files/usr/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted
cat: write error: Broken pipe

Installation of system tables failed!  Examine the logs in
/data/data/com.termux/files/usr/var/lib/mysql for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /data/data/com.termux/files/usr/bin/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /data/data/com.termux/files/usr/bin/mysqld --skip-grant-tables --general-log &

and use the command line tool /data/data/com.termux/files/usr/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> /data/data/com.termux/files/usr/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /data/data/com.termux/files/usr/var/lib/mysql that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
You can find the latest source at https://downloads.mariadb.org and
the maria-discuss email list at https://launchpad.net/~maria-discuss

Please check all of the above before submitting a bug report
at http://mariadb.org/jira

**Comment by Grimler91** [comment]
try `mkdir $PREFIX/etc/my.cnf.d` and then run
```
mysql_install_db --user=$(whoami) --datadir=$PREFIX/var/lib/mysql --basedir=$PREFIX
```
This seems to be a bug that should be fixed.

**Comment by baties** [comment]
Ok thanks . It was successful . But do I need to install mysqlclient now again or not ?
I want to connect my python restframework app to mysql .

**Comment by Grimler91** [comment]
? You haven't installed it AFAIK since it failed with an error so I suppose you want to install it

**Comment by baties** [comment]
I installed mariadb base on your help successfully . But then when I want to install mysqlclient again I have another error , look at this plz :
![screenshot_2019-02-23-12-23-27](https://user-images.githubusercontent.com/9303641/53284185-dd90f500-3765-11e9-9fcd-dc9af01bb42b.png)

**Comment by Grimler91** [comment]
Header files are found in the -dev packages so you want to install mariadb-dev

**Comment by baties** [comment]
After installing Termux I did as below :

pkg update
pkg install python
pkg install mariadb
mkdir $PREFIX/etc/my.cnf.d
mysql_install_db --user=$(whoami) --datadir=$PREFIX/var/lib/mysql --basedir=$PREFIX
apt install coreutils
apt install python-dev
pip install mysql-connector-python
 pkg install clang python-dev
 pip install mysqlclient

**Comment by baties** [comment]
> Header files are found in the -dev packages so you want to install mariadb-dev

Thank you very much , Grimler91 . Its OK now !!!
Many thanks to you .
