### ISSUE TITLE
Space bar swipe to move cursor

### ISSUE THREAD

**Issue by cyberb** [termux/termux-app#1043]
Google Keyboard supports swipe on space bar to move the cursor (left/right).

It helps in many apps (browser, mail ...), I would really love to use it in Termux app.

Terminal, vim ...

**Comment by ujeropoc** [comment]
Or add the Left/Right arrows to the special key bar.

Almost all CLI Programs support one way or another for working without arrow keys, most using readline which defaults to emacs mode. See https://superuser.com/a/90966

**Comment by cyberb** [comment]
Super cool!
Space bar swipe would still be useful though.

**Comment by cheetosysst** [comment]
exactly what i was so frustrated about the app when I first started using it

**Comment by Mhowser** [comment]
I need this feature! my fat fingers are always misspelling something with the touch keyboard! It starts wasting time when I have to backspace back to the spelling error and retype everything!

**Comment by paperbenni** [comment]
I neeeeeed this feature.

**Comment by trygveaa** [comment]
Is this even possible to implement? I'm not sure if we can react to swiping on the keyboard.

Are there any other terminals that supports this?

**Comment by xeffyr** [comment]
@trygveaa I guess problem is that such feature is just disabled when generic input type is used. Since Termux handles input by key codes, it is not possible to do something else currently.

**Comment by trygveaa** [comment]
@xeffyr: Yeah, that's what I thought.

**Comment by usernein** [comment]
any news on this? i miss it so much, since i'm using neovim on termux as my main code editor

**Comment by agnostic-apollo** [comment]
The gboard keyboard does not send move events with terminal input mode `TYPE_NULL` or even with `enforce-char-based-input=true` which uses a different mode. So termux can't do anything about this. Swipe left on extra keys and use text input mode for scroll bar support.

**Comment by Mhowser** [comment]
Is this generally the same for other keyboards? What about OpenBoard[OpenBoard](https://github.com/openboard-team/openboard)? 

Is it also theoretically possible to simulate rapid arrow keystrokes to move the cursor as of it was done by swiping the spacebar? Is this something Termux might be able to handle or is this solely up to the keyboard to handle it?

**Comment by agnostic-apollo** [comment]
> Is this generally the same for other keyboards? What about [OpenBoard](https://github.com/openboard-team/openboard)?

Yes, unlikely any keyboard does. TYPE_NULL means...

>Special content type for when no explicit type has been specified. This should be interpreted to mean that the target input connection is not rich, it can not process and show things like candidate text nor retrieve the current text, so the input method will need to run in a limited "generate key events" mode, if it supports it. Note that some input methods may not support it, for example a voice-based input method will likely not be able to generate key events even if this flag is set.

https://developer.android.com/reference/android/text/InputType#TYPE_NULL

Since terminal is not a text field containing words, its like a picture where each character is independent and like a pixel, that is why that mode is used and input won't work without it.

OpenBoard doesn't either.

> Is it also theoretically possible to simulate rapid arrow keystrokes to move the cursor as of it was done by swiping the spacebar?

The terminal default extra keys already provide 2 rows and all 4 arrow keys and long press works just fine, so don't think this is really an issue.

https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by Mhowser** [comment]
I am aware of the extra keys row, and thanks for the prior explanation too!

**Comment by usernein** [comment]
what if termux created a fake and hidden text field only to receive those events and control the cursor?
