### ISSUE TITLE
stuck on folder usr-staging 

### ISSUE THREAD

**Issue by vanshu** [termux/termux-app#1047]
**Problem description**
after install termux app ,open termux the progressbar shows it's still Installing... it's stuck for long time ,check the device folder in data/data/com.termux/files, the folders include home directory and usr-staging. seems it's stuck in here 

***Additional information**
termux version 0.6.5

**Comment by Grimler91** [comment]
What device is this? Which architecture? Why are you installing an older version of termux? 

Are you trying to install termux into the external sdcard? 
Do you have network problems? Can you access termux.net in your browser?

**Comment by xeffyr** [comment]
> Do you have network problems?

For unknown reason, IPv6 downloads are really slow on some devices and Termux may bootstrap 10 minutes or more. I had similar issue when IPv6 was enabled in my network, but issue affected only ARM device.

**Comment by vanshu** [comment]
1. my device nexus5x 32GB version 
2. arm64 architecture
3. the reason why I install 0.65 because I fork this project 
4. Nexus5x doesn't have external sdcard
5. I can access network, also http://termux.net, but when I changed URL into https://termux.net, the loading are extremely slow, it will cost a minute to open the website, sometimes it's connection timeout.
6. my network is China Telecom, didn't use a WIFI connection, just use sim card network to access the network

**Comment by vanshu** [comment]
the code stuck at TermuxInstall.java util connection timeout 
URL url=new URL("https://termux.net/bootstrap/bootstrap-" + archName + ".zip");
I can access this url by browser .

**Comment by xeffyr** [comment]
Closing because Termux no longer uses network-based installer.
