### ISSUE TITLE
New AddonApp: Termux:URI that sends commands to termux when a `termux:command` URI is opened

### ISSUE THREAD

**Issue by ujeropoc** [termux/termux-app#1048]
I propose another Addon-App (similar to termux:boot) that gets invoked by `termux:command` URIs.
Doing this in a seperate app would outsource all the security issues from the core app, be easy to replace and so on.

Control Flow:
1. User somehow opens a `termux:` URI
2. Termux:URI parses the URI into:
    * Command and args
    * Foreground/Background
    * possibly more (CWD, ENV, ...)
3. Termux:URI does a security check
4. Termux:URI sends the command to Termux

URI Encoding
-------
Possibilities of Encoding of command and arguments:

21. leave as is: `termux:command arg1 "arg 2"`  
      might not be supported by some apps
22. URL Encode `termux:command%20arg1%20%22arg2%22`  
      looks ugly
23. base64 Encode everything `termux:Y29tbWFuZCBhcmcxICJhcmcgMiI=`
      looks dangerous
24. let the user decide (see 35.)

Possibilities of Encoding of Foreground Background:

25. if the last char of the command is `&` its Background  
    feels very unix
26. different URI Scheme: `termuxbg` `background.termux.com` `background.v1.uri.termux.com`
27. URL Param `termux:command?background=1`  
    would work well with cwd, ...
28. Configurable outside of URI (see 35.)

Security
--------
My Ideas for security:

31. Ask the user: "Dou you want to execute `command arg1 "arg 2"`" [YES] [NO]
32. Configurable Whitelist, Add Button [YES and don't ask again]
33. Only commands in `.termux/uri/` can be executed.
34. A whitelist in textform in `.termux/uri/whitelist` with one line per allowed command
    * do full match ?
    * do prefix match? must clean chars like ` | ; &&` could be unsafe with some commands
35. call one single script, `.termux/uri-handler` with the complete uri, skipping Step 2 and 3 and let it decide what to do.

Additional features
----------
* Depending on how complicate Step 2 is, a wizard to generate the termux uri would be neat. either in the App, or in javascript, hosted on the termux website. (producing a qr code)

* Manage the whitelist

Benefit
--------
start commands in TERMUX from:
* all kinds of automation Apps
* QR Codes
* NFC Tags
* other shiny new things

If I'm not mistaken, this would (help to) fix these issues:
termux-tasker # 6
#547
#804 
#924 

And now?
-------
I have no clue about android programming, but I might enjoy playing around with it. I guess starting off of the termux:boot app to get something working, but I would need help making it into proper android app that follows some kind of coding standard etc.

**Comment by xeffyr** [comment]
Too much complicated.

Special characters such as space and '&' should be encoded and you will end with `2. URL Encode "termux:command%20arg1%20%22arg2%22"`. That's weird as most users won't be able to create/deal with such URLs.

## Security.

There too much problems

1. We can use either Android permission or show dialog each time command being executed. I guess you will agree that seeing dialog "Allow to execute command XXXXXXXX ?" each time will be annoying.

2. Another problem is that many users do not care about permissions. Therefore no matter, Android permission request or just a dialog, it won't help too much.

3. Final problem: what security checks should be done ??? It is not possible to know if command is secure without executing it. How application will distinguish if command if command listed in place "a" is acceptable and command listed in place "b" is forbidden ?

Such addon creates a good attack surface.

***

https://github.com/termux/termux-app/pull/1029 will allow to execute commands and it is ENOUGH.

**Comment by xeffyr** [comment]
We will not go further than allowing to execute commands with per-app permission.

**Comment by xeffyr** [comment]
#1029 is also solution for https://github.com/termux/termux-app/issues/804. Regarding https://github.com/termux/termux-app/issues/924, I'm very unsure that there will be solution unless it is possible to grant Android permission to ADB.

**Comment by ujeropoc** [comment]
how would you execute scripts after scanning qr codes or NFC Tags ?

**Comment by xeffyr** [comment]
NFC is a task for Termux:API.

https://github.com/termux/termux-app/pull/1029 reasonable bare minimum for developing third party plugins (including QR scanner).

We won't allow arbitrary third-party applications to interact with Termux unless they have permission to do so. All commands should be sent via intent so Android can verify caller applications. URLs will allow to bypass this procedure.

**Either forget about commands executable via URLs or make a fork!**

Regarding NFC and QR - they will not be available unless someone decide to submit a PR.
