### ISSUE TITLE
Graphical glitch with CTRL key on extra keys view

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-app#105]
This concerns the 0.35 Preview release. There is a small graphical glitch on very small phones. The CTRL key wraps around to two lines. This happens on my Xperia Z3 Compact, which has a resolution of 1280 x 720 Pixels. 
![screenshot_20160613-103121](https://cloud.githubusercontent.com/assets/7983745/16001544/df826b1c-3152-11e6-8406-7b87d85fd0ce.png)

**Comment by Quasic** [comment]
@Neo-Oli, is this still an issue after the recent extra keys update?

**Comment by xeffyr** [comment]
> 13 Jun 2016
> is this still an issue after the recent extra keys update?

Perhaps not...
