### ISSUE TITLE
BackKey as Escape not working

### ISSUE THREAD

**Issue by shahzadakram67** [termux/termux-app#1051]
I am unable to map BackKey as Escape, I tried this,

`back-key=escape`  in `~/.termux/termux.properties` but no success, Is it a bug or am I missing something?

**Comment by xeffyr** [comment]
Yes, add
```properties
back-key=escape
```
to `~/.termux/termux.properties`. Then execute `termux-reload-settings`. It works.

**Comment by shahzadakram67** [comment]
I have tried this but in vain. It just closes the keyboard and on next tap Termux it is closed as default behaviour..

**Comment by shahzadakram67** [comment]
I extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]

```
