### ISSUE TITLE
Add lolcat to package list?

### ISSUE THREAD

**Issue by jprfts** [termux/termux-app#1052]
**Feature description**
its lolcat. it rainbow pipes things
if im restricted to only a terminal, i might as well have some fancy things to do with it

**Reference implementation**
heres their repo: https://github.com/busyloop/lolcat

**Comment by xeffyr** [comment]
It is easily installable via `gem install lolcat` so why it should be packaged for APT repository ?

And our policy is to **not package** things perl/python/ruby/{other lang} packages. There few exceptions though, but only for important stuff.
