### ISSUE TITLE
Feature request: open with/share to Termux

### ISSUE THREAD

**Issue by Efreak** [termux/termux-app#1055]
Please implement a method to allow sharing files and urls to termux. This would make it easier to open a link from a browser to download an archive into termux (using aria2c, etc), as well as many other functions.

I think the best way would be to have a series of options available like there is with the widget; a confirmation file with titles (optional) and commands, with either an environment variable that gets replaced by the shared/opening path, or simply appending it to the command. Then, when something is shared to termux, provide options with either UI or a shell script. Perhaps allow defaults for URLs/protocols and file extensions.

Alternatively, when an item is shared to termux, just start a new session prompting for a command to be run on the input.

**Comment by DaBoss5** [comment]
Currently, you can share urls to termux (to have code run on it, you would need to have created ~/bin/termux-url-opener to run your code (you could make it interact with the user to do different things based on the situation).

For files, you should be able to create ~/bin/termux-file-editor, but I have been unable to get that to work.
