### ISSUE TITLE
pkg not updated

### ISSUE THREAD

**Issue by SergeyDjam** [termux/termux-app#1057]
```
$ pkg update
Ign:1 https://termux.net stable InRelease       
Err:2 https://termux.net stable Release
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to termux.net:443
Reading package lists... Done                   
E: The repository 'https://termux.net stable Release' does no longer have a Release file.       
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

ASUS Zenfone ZB602LK, termux (f-droid) - 0.66

**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by xeffyr** [comment]
Things to do:

* Check that your Internet connection is **stable**, i.e. there no high packet loss or ping. Provider's DPI system may cause this too.
* Try to run `pkg update` one more time (may help if your connection is unstable).
* Disable HTTPS: edit file `$PREFIX/etc/apt/sources.list` and change https to http.

**Comment by Fernal73** [comment]
I receive a similar error on running PKG up.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 https://its-pointless.github.io/files/24 termux InRelease
Ign:2 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:3 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:4 https://dl.bintray.com/grimler/termux-root-packages-24 root InRelease
Ign:5 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:6 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable InRelease
Ign:7 https://dl.bintray.com/xeffyr/x11-packages-24 x11 InRelease
Err:8 https://dl.bintray.com/termux/termux-packages-24 stable Release
  403  Forbidden
Get:9 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:9 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:11 https://dl.bintray.com/grimler/termux-root-packages-24 root Release [6185 B]
Hit:11 https://dl.bintray.com/grimler/termux-root-packages-24 root Release
Get:13 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:13 https://dl.bintray.com/grimler/science-packages-24 science Release
Get:15 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release [6065 B]
Hit:15 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release
Get:17 https://dl.bintray.com/xeffyr/x11-packages-24 x11 Release [6055 B]
Hit:17 https://dl.bintray.com/xeffyr/x11-packages-24 x11 Release
Reading package lists...
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does no longer have a Release file.

**Comment by xeffyr** [comment]
`403 Forbidden` ==> https://github.com/termux/termux-packages/issues/4358

**Comment by Fernal73** [comment]
Thanks. This happens intermittently.
Is there anything wrong with the .gpg file?

**Comment by Fernal73** [comment]
How long do you think we have to wait? This seems pretty permanent to me.

**Comment by JoseppeFalcone** [comment]
Yeah, the same thing is happening with me is it something i did or what?
