### ISSUE TITLE
prompt and cursor dislocation after command

### ISSUE THREAD

**Issue by Justsoos** [termux/termux-app#1058]
the record GIF
![Gif_20190311035643](https://user-images.githubusercontent.com/3480043/54090796-1a3e2c80-43b3-11e9-8ae7-4caff9211d0b.gif)

and termux info
[info_termux.txt](https://github.com/termux/termux-app/files/2949978/info_termux.txt)
ver 0.66

**Comment by xeffyr** [comment]
Absolutely okay. Caused by missing newline at the end of stream.
On PC it happens of course too:
```
> 
< HTTP/1.1 400 Bad Request
< Content-Type: text/html
< Content-Length: 69
< Date: Sun, 10 Mar 2019 20:13:17 GMT
< Connection: keep-alive
< 
* Connection #0 to host tlstest.paypal.com left intact
ERROR! Connection is not HTTPS. Please use https://tlstest.paypal.com[xeffyr]:~:$ 
```

**Comment by xeffyr** [comment]
This is not a bug.
