### ISSUE TITLE
Does not work when replacing applicationId

### ISSUE THREAD

**Issue by sonlv-enguys** [termux/termux-app#1059]
I tried to change applicationId from "com.termux" to "com.termux.support". But it doesn't seem to work. The error code is "/data/data/com.termux.support/files/usr/bin/longin no such file or derectory". So how can I do this? Thank you!

**Comment by Grimler91** [comment]
You need to recompile some packages and change [`$TERMUX_PREFIX`](https://github.com/termux/termux-packages/blob/25aaa34b1afdc6c17e51a5c6dc692a59c216b8b7/scripts/build/termux_step_setup_variables.sh#L7) (and perhaps `$TERMUX_ANDROID_HOME`) to match your new path. The packages [marked as essential](https://github.com/termux/termux-packages/blob/ba95fbd385c2d36e0ace7ab7dcac0db45846c055/packages/bash/build.sh#L11) would be a good start. 

Once you have those packages you need to create a bootstrap.zip similar to [the official ones](http://termux.net/bootstrap/) and upload it somewhere, and then change the bootstrap url found in [termux-app](https://github.com/termux/termux-app/blob/063ef02f2b5b95efc5961d4fbe90e8196f1bbc5e/app/src/main/java/com/termux/app/TermuxInstaller.java#L173) to download it from there.

**Comment by sonlv-enguys** [comment]
So when I finish using the script, use which command to recompile. Help me!

**Comment by sonlv-enguys** [comment]
After editing, how to build bootstrap.zip?

**Comment by xeffyr** [comment]
## Compiling packages

1. Make sure you have access to PC or at least VPS with docker installed.
2. Setup docker container as described in https://github.com/termux/termux-packages/blob/master/docs/DOCKER.md.
3. Enter docker container.
4. Override variables for prefix and home.
    ```
    export TERMUX_PREFIX=/data/data/com.termux.support/files/usr
    export TERMUX_ANDROID_HOME=/data/data/com.termux.support/files/home
    ```
    Alternatively, you can edit script https://github.com/termux/termux-packages/blob/25aaa34b1afdc6c17e51a5c6dc692a59c216b8b7/scripts/build/termux_step_setup_variables.sh.
5. Decide which packages you want to have in YOUR OWN REPOSITORY. Must have ones are: apt, dpkg, bash, dash, gnupg, busybox, termux-tools and all dependencies for these packages.

6. Build packages with `./build-package.sh {package name}`. By default, build is done for AArch64, but if you need, for example, ARM - execute script in the following way: `./build-package.sh -a arm {package name}`.

7. Built deb files located in directory `./debs`.

## Getting bootstraps
1. Setup APT repository.
2. Upload it to hosting.
3. Clone `https://github.com/termux/termux-packaging`
4. Correct urls in `termux-packaging/src/apt_repo.rs`
5. Build `termux-packaging` with `cargo build` - Rust installation required.
6. After you obtain termux-packaging binary, execute it in way like `./termux-packaging bootstraps ./`

***

If you can't use PC or VPS for some reason, you won't be able to build packages. If you can't setup package hosting, you will not be able to create bootstraps with official way. Application with modified prefix will be useless too.

I provided enough instructions for creating own Termux APT repository and bootstraps with modified prefix. **Everything else should be done by you, no matter how** (you really need Termux app with custom prefix, right ?).

**Comment by sonlv-enguys** [comment]
Step1: Run **./scripts/run-docker.sh ./build-package.sh -i -a x86_64 libandroid-support**
build success: 
deb/libandroid-support_24_arm.deb
deb/libandroid-support_24_i686.deb
deb/libandroid-support_24_x86_64.deb
deb/libandroid-support_24_aarch64.deb

Step2: Getting bootstraps

Did I do that right?

**Comment by sonlv-enguys** [comment]
I have build success and file .deb. So how do I create .zip files?

**Comment by xeffyr** [comment]
> ./scripts/run-docker.sh ./build-package.sh -i -a x86_64 libandroid-support

So... you need only libandroid-support ? How you will use it standalone ?
If you in doubt which packages you need to run custom Termux, build all of them.

> I have build success and file .deb. So how do I create .zip files?

Dude, read instructions carefully, from the first step to the last. Also know, that Termux is not offline-only thing. It is relying on package repository as well as utility for creating bootstraps.

***

Did you built ALL REQUIRED PACKAGES ? Answer: no.
Did you setup package hosting ? Answer: no.
Why no ? Because my instructions cover all these topics but you even didn't do the first one properly...

Should we do this for you ? Obviously, no !
