### ISSUE TITLE
How to switch between sessions via keyboard shortcut?

### ISSUE THREAD

**Issue by clouds56** [termux/termux-app#106]
Is it possible to switch to next and previous session/tab via ctrl+tab and ctrl+shift+tab respectively?
Or is there already some shortcut to do with this?

**Comment by fornwall** [comment]
See https://termux.com/hardware-keyboard.html:

1. `Ctrl+Shift+N` for next session.
2. `Ctrl+Shift+P` for previous session.

Does these work for you?

**Comment by ztq56** [comment]
That's great!
Though I prefer Ctrl+Tab. I'm very happy to see that I could customize these shortcut in the future!

**Comment by the-zucc** [comment]
I have had success with `Ctrl+alt+n` and `Ctrl+alt+p`

**Comment by porpa11** [comment]
How to create new session via keyboard.

**Comment by xeffyr** [comment]
@porpa11 https://wiki.termux.com/wiki/Hardware_Keyboard, `ctrl+alt+c` on **hardware** keyboard. Shortcuts for on-screen keyboard are not available.
