### ISSUE TITLE
ANNOT LINK EXECUTABLE "nano": library "libandroid-support.so" not found Aborted

### ISSUE THREAD

**Issue by dextercva** [termux/termux-app#1061]
**Problem description**
![Android7termux](https://user-images.githubusercontent.com/43370509/54216523-d14fba80-450f-11e9-9572-45085bebd0e1.png)

I don't know why this is happening i don't find any solution for it.

**Some are**
Even I can't open nano editor says `CANNOT LINK EXECUTABLE "nano": library "libandroid-support.so" not found
Aborted`

**Additional information**
I'm using android v7.1.2 naught

**Comment by DaBoss5** [comment]
Could you show the output of ```echo $LD_LIBRARY_PATH```

**Comment by dextercva** [comment]
Yes! Please have a look at image below.

![com termux](https://user-images.githubusercontent.com/43370509/54356709-44793e00-4682-11e9-849b-b90478189202.png)

**Comment by DaBoss5** [comment]
Ah, I believe that may be what's causing the issue. Try doing ```echo "export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib" >> ~/.bashrc```
After that open a new session, and see if that works

**Comment by xeffyr** [comment]
Never mess with environment variables. Especially with `LD_LIBRARY_PATH`, `LD_PRELOAD` and `PATH`.

**Comment by dextercva** [comment]
Thank you very much guys for your interest. I'll be happy if you provide me a bit of information of what caused this issue or possible ways that may cause this issue.
Thank you 😃

**Comment by wendao90** [comment]
> Ah, I believe that may be what's causing the issue. Try doing `echo "export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib" >> ~/.bashrc`
> After that open a new session, and see if that works

You got the point!!!  Thank you SOOO much~

**Comment by 687766616e** [comment]
> Could you show the output of `echo $LD_LIBRARY_PATH`

$ echo $LD_LIBRARY_PATH
/data/data/com.termux/files/usr/lib

**Comment by 687766616e** [comment]
I'm using this: https://gitlab.com/st42/termux-sudo

**Comment by 687766616e** [comment]
> Ah, I believe that may be what's causing the issue. Try doing `echo "export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib" >> ~/.bashrc`
> After that open a new session, and see if that works

$ echo $LD_LIBRARY_PATH
/data/data/com.termux/files/usr/lib
$ echo "export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib" >> ~/.bashrc
$ echo $LD_LIBRARY_PATH                                                    /data/data/com.termux/files/usr/lib
$

**Comment by 687766616e** [comment]
$ sudo nmap www.test.com.us --spoof-mac dell --badsum --randomize-hosts --source-port 8088 -f
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "u_foldCase_60" referenced by "/system/lib64/libsqlite.so"...
Starting Nmap 7.80 ( https://nmap.org ) at 2019-09-22 23:35 CST
Spoofing MAC address 00:00:97:81:AC:0D (Dell EMC)

**Comment by xeffyr** [comment]
@687766616e https://gitlab.com/st42/termux-sudo is a **third-party** stuff.
