### ISSUE TITLE
How can i get Username and Password

### ISSUE THREAD

**Issue by MoaazMughal** [termux/termux-app#1065]
When i try install pkg they asking the username and password and i use github username but it will not working.
Please help.

**Comment by Grimler91** [comment]
I have no idea what you are doing, you need to provide more information if you want help. Sounds like you are trying to clone a none-existing repo or cloning over ssh even though you haven't put your pub key in your settings on github.

**Comment by MoaazMughal** [comment]
I enter the Username but show this.
"remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/shawarkhanethicalhacker/D-TECT/'"
I put the right username of github but it said invalid.
Please help

**Comment by xeffyr** [comment]
Why you have slash at the end of git repo url ?
