### ISSUE TITLE
Feature Request: open Termux in a certain directory.

### ISSUE THREAD

**Issue by evan0greenup** [termux/termux-app#1067]
**Feature description**
Open Termux in a certain working directory specified by other Apps (File Manager).

In other words, provide a interface to other Apps.

**Reference implementation**
I have only used Termux before.

**Comment by xeffyr** [comment]
Is there a file manager waiting for implementation of this feature ?

> Reference implementation
I have only used Termux before.

Perhaps no.

***

> In other words, provide a interface to other Apps.

Interface must be implemented on both sides otherwise it will be useless because applications cannot automatically see and use them.

**Comment by xeffyr** [comment]
Do you have any examples of file managers that can pass directory to another applications ?

**Comment by evan0greenup** [comment]
@xeffyr , according to "Interface must be implemented on both sides otherwise it will be useless because applications cannot automatically see and use them." of your sentence. It indicates that there would be a possibility if a certain file manager project is willing to implemented a interface.

Reference Implementation:
Here is the file manager project [android-file-manager](https://gitlab.com/axet/android-file-manager)

The author seems willing to implement the interface. Because he shows that if Termux can provide a viable way, he will make a try.

It will be awesome, if this feature can be implemented.

Two example you provided are proprietary software, so they are unchangeable. but the example I provide is an open source project under GPL. So everything is possible. 

Please consider to reopen the issue! Thanks.

**Comment by evan0greenup** [comment]
@xeffyr, I have already submitted a issue to that author. So just tell him you are from Termux. You can have some conversation and determine the possibility to implement this feature. Hope this feature can come out as soon as possible.

**Comment by linsui** [comment]
@xeffyr Could you please reopen this issue? Material File can't make `Open in terminal` work with Termux without this feature, see https://github.com/zhanghai/MaterialFiles/issues/183 . Thanks!

**Comment by xeffyr** [comment]
@linsui Reopened in https://github.com/termux/termux-app/issues/1070.
