### ISSUE TITLE
Arch binaries from Termux

### ISSUE THREAD

**Issue by tzuand** [termux/termux-app#1069]
Issue #77 discusses how to gain access to Termux binaries from an Android shell.  It is amazing to finally get access to Linux tools from an Android shell (such as `htop`, `ncdu`, etc.).  Thanks everyone for your efforts!

Know I would like to execute Termux+Arch binaries from both Termux and an Android shell.  I can't grasp the reason why, but calling Arch binaries from Termux fail:

```
# pwd
/data/data/com.termux/files/home/arch

# ls -l usr/bin/bash
-rwxr-xr-x 1 u0_a85 u0_a85 806924 Jan 13 08:21 usr/bin/bash

# usr/bin/bash
bash: usr/bin/bash: No such file or directory

# /data/data/com.termux/files/home/arch/usr/bin/bash
bash: usr/bin/bash: No such file or directory

# ls -l /data/data/com.termux/files/home/arch/usr/bin/xclock
-rwxr-xr-x 1 u0_a85 u0_a85 40088 Feb 21 13:48 /data/data/com.termux/files/home/arch/usr/bin/xclock

# /data/data/com.termux/files/home/arch/usr/bin/xclock
bash: /data/data/com.termux/files/home/arch/usr/bin/xclock: No such file or directory
```
Any ideas?

By the way, I already have set:

`export LD_LIBRARY_PATH=/data/data/com.termux/files/home/arch/usr/lib`

**Comment by xeffyr** [comment]
You cannot execute Arch binaries from Termux without proot.
Just linker and ABI incompatibility.
