### ISSUE TITLE
/data/data/com.termux/files directory is cleared on reboot

### ISSUE THREAD

**Issue by raimoh** [termux/termux-app#1074]
On my Oreo 8.1 build, the termux app data folder gets cleared on every reboot of Android and the bootstrap package has to be downloaded every time. Any ideas why? 
I am running termux as system app.

**Comment by xeffyr** [comment]
You either hard-messed with scripts in Termux or just something wrong with your ROM.

**Comment by raimoh** [comment]
@xeffyr thanks for the hint, it was somehow related to termux boot. Removing termux boot fixed the problem.
