### ISSUE TITLE
What's the best way to deploy customized termux application(DeepCamera) to Play Store

### ISSUE THREAD

**Issue by solderzzc** [termux/termux-app#1075]
We are developing [AI camera](
https://github.com/SharpAI/DeepCamera) on Android and planning to distribute through google play store. We modified Termux a little bit to easy the setup for end user [Launcher](
https://github.com/SharpAI/Launcher_Termux).
We ported most of deep learning thing (python/javascript with GPUs support) onto Android through Termux. The system on Termux is about 600MB.

Now we want to know what's the best way to distribute on play store.
Following is the option we are now considering about:
- since package name com.termux will not available on play store, we need rebuild all thing to have renamed package(a lot of work for us)
- ask end user to install termux, then install our root fs (might cost too much end user's effort)

**Comment by Grimler91** [comment]
Hi, 

Only other convenient option I can think of would be if you could put the termux modifications in a new addon app. That app could then be distributed and installed by anyone (if it is built and signed with same key as termux-app).

**Comment by solderzzc** [comment]
So, how to handle that?
Is that possible to share the sign-key to us?
Or we can provide(already in GitHub) the build procedure for you to build the add-on?

**Comment by xeffyr** [comment]
> Is that possible to share the sign-key to us?

No, keys are not shared.

> Or we can provide(already in GitHub) the build procedure for you to build the add-on?

Does it require some things from Android side so it should be packaged into APK ? If not, then it can be purely packaged into \*.deb file(s) and distributed via APT like other Termux packages.

**Comment by solderzzc** [comment]
We compiled some of deep learning framework:
MXNet / TVM / Sklearn and OpenCV, some python/javascript code and several services startup scripts.

The easiest way for them is tar  the installed/compiled `usr` folder into one tarball.

**Comment by its-pointless** [comment]
As an addon? That sounds promising.

**Comment by xeffyr** [comment]
> The easiest way for them is tar the installed/compiled usr folder into one tarball.

In this way it is better to package it for apt/dpkg. It is like tarball but with some metadata.
All build scripts for creating packages are here: https://github.com/termux/termux-packages

**Comment by solderzzc** [comment]
hmm, how to build the base package of termux, I might try the CI way for a new build to run on our own Android package name.

**Comment by solderzzc** [comment]
It seems this is good/simple enough to distribute new application with different package name:
https://github.com/termux/termux-packages/issues/1756#issuecomment-407696733

**Comment by xeffyr** [comment]
> with different package name

Absolutely not.
All packages have hardcoded paths so they can find their configuration files and other data.

For example, a bash package:
```
$ cd $PREFIX/bin
$ strings bash | grep /data
/data/data/com.termux/files/usr/etc/bash.bashrc
/data/data/com.termux/files/usr/etc/profile
/data/data/com.termux/files/usr/share/bashdb/bashdb-main.inc
/data/data/com.termux/files/usr/bin/login
/data/data/com.termux/files/usr/bin/bash
/data/data/com.termux/files/home
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:.
/data/data/com.termux/files/usr/etc/hosts
/data/data/com.termux/files/usr/tmp/
```

**Comment by xeffyr** [comment]
Deb archives of course have hardcoded paths too:
```
$ dpkg-deb -c readline_8.0_aarch64.deb 
drwxr-xr-x builder/builder   0 2019-02-28 01:49 ./
drwxr-xr-x builder/builder   0 2019-02-28 01:49 ./data/
drwxr-xr-x builder/builder   0 2019-02-28 01:49 ./data/data/
drwxr-xr-x builder/builder   0 2019-02-28 01:49 ./data/data/com.termux/
drwxr-xr-x builder/builder   0 2019-02-28 01:49 ./data/data/com.termux/files/
drwx------ builder/builder   0 2019-02-28 01:49 ./data/data/com.termux/files/usr/
drwx------ builder/builder   0 2019-02-28 01:49 ./data/data/com.termux/files/usr/lib/
-rwx------ builder/builder 354504 2019-02-28 01:49 ./data/data/com.termux/files/usr/lib/libreadline.so.8.0
lrwxrwxrwx builder/builder      0 2019-02-28 01:49 ./data/data/com.termux/files/usr/lib/libreadline.so.8 -> libreadline.so.8.0
-rwx------ builder/builder  67912 2019-02-28 01:49 ./data/data/com.termux/files/usr/lib/libhistory.so.8.0
lrwxrwxrwx builder/builder      0 2019-02-28 01:49 ./data/data/com.termux/files/usr/lib/libhistory.so -> libhistory.so.8
lrwxrwxrwx builder/builder      0 2019-02-28 01:49 ./data/data/com.termux/files/usr/lib/libreadline.so -> libreadline.so.8
lrwxrwxrwx builder/builder      0 2019-02-28 01:49 ./data/data/com.termux/files/usr/lib/libhistory.so.8 -> libhistory.so.8.0
drwx------ builder/builder      0 2019-02-28 01:49 ./data/data/com.termux/files/usr/etc/
-rw------- builder/builder    489 2019-02-28 01:49 ./data/data/com.termux/files/usr/etc/inputrc
```

**Comment by solderzzc** [comment]
Got it. 

Change package name is for better user experiment, also we need much more time to pack our deep learning frame work porting into scripts. Before that, I started to rebuild the bootstrap.zip from here gnu4droid:
https://github.com/solderzzc/gnu4droid.

Then need to rebuild packages with this one termux_step_setup_variables.sh#L7..

**Comment by xeffyr** [comment]
Seems resolved now.
