### ISSUE TITLE
Termux not supported on Samsung galaxy tab 3

### ISSUE THREAD

**Issue by ulist** [termux/termux-app#1077]
I wondering why the other emulator works fine

**Comment by xeffyr** [comment]
You are getting "signal 4", right ? If so, then it is CPU.

**Comment by ulist** [comment]
No I can't install it

**Comment by xeffyr** [comment]
Okay, can you post screenshot of the error ?

**Comment by ulist** [comment]
it's not compatible with my device like it says in Google play
also I don't have it right now

**Comment by xeffyr** [comment]
Why not to try F-Droid then ? https://f-droid.org/en/packages/com.termux/

**Comment by ulist** [comment]
Well
