### ISSUE TITLE
Support SSH Agent Forwarding

### ISSUE THREAD

**Issue by nathan-sain** [termux/termux-app#108]
I would like to ssh to my mobile devices and use git in Termux without installing my ssh keys on those mobile devices. I usually accomplish this with SSH's builtin support agent forwarding. I have my .ssh/config file setup to do agent forwarding but the environment variables are not created in the Termux shell. Is this a known issue or perhaps something I need to configure in the Termux environment?

**Comment by mklein994** [comment]
This sounds like it's related to termux/termux-packages#341 and termux/termux-packages#290.

**Comment by fornwall** [comment]
Thanks - this should now work in the latest `7.2p2-5` version of the openssh package. Update to it with `apt update && apt upgrade` and make sure to kill any old `sshd` server process with `killall -9 sshd` before starting `sshd` again after updating.

Let me know if there are any remaining problem!
