### ISSUE TITLE
/system/bin/linker returned Segmentation fault

### ISSUE THREAD

**Issue by ulist** [termux/termux-app#1080]
Im trying  to run script on termux it executed but when I switched to ubuntu under proot and execute it again it returned 'Segmentation fault'
I figured that the problem in linker file why that happen ?
```
On ubuntu:
---
root@localhost:~# file /system/bin/linker
/system/bin/linker: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/, BuildID[md5/uuid]=92282558b2a7a287e9e0238b68572ee0, not stripped
---
On termux :
--- 
/system/bin/linker: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[md5/uuid]=92282558b2a7a287e9e0238b68572ee0, not stripped
---
```

**Comment by Grimler91** [comment]
Ubuntu uses glibc while termux uses bionic. The two are in general not compatible so I guess that's what's going on here. 

Hard to know without knowing more about what you are doing

**Comment by ulist** [comment]
I'm 100% knowledge dude  😶

**Comment by xeffyr** [comment]
> /system/bin/linker returned Segmentation fault

Why we should care about things in /system ??? Thats Termux issue tracker and not Android's.
