### ISSUE TITLE
13: Permission Denied.

### ISSUE THREAD

**Issue by ancientzords** [termux/termux-app#1084]
I make a mistake when i accidently delete some text in Bash.bashrc, and this happen:

```
jeto@localhost:~#apt update
E: Opening /data/data/com.termux/files/usr/etc/apt/sources.list.d/x11.list - ifstream::ifstream (13: Permission denied)
E: The list of sources could not be read.
```

**Comment by Grimler91** [comment]
Run rm -rf $PREFIX and restart termux to remove all installed packages (but leave $HOME intact). That's the easiest fix.

**Comment by TheFatCow** [comment]
Not working it still says permission denied

**Comment by Shahmeer5890** [comment]
Unsubscribe
