### ISSUE TITLE
New "Extra Keys" bar does not display buttons

### ISSUE THREAD

**Issue by mozzwald** [termux/termux-app#109]
Enabling the extra keys bar in preview v0.35 shows a blank bar. Swiping the bar left/right switches between the text input bar (which works) and the blank button bar. Tapping the empty button bar does nothing (no button presses appear in terminal). I am testing this on a Motorola Photon Q running CM 12.1 and a measly screen resolution of 540x960. 

Screenshots:
![shot_2016-06-28_08-38-56](https://cloud.githubusercontent.com/assets/1191098/16421450/9082ccb8-3d1a-11e6-8449-02095041fab7.png)
![shot_2016-06-28_08-39-19](https://cloud.githubusercontent.com/assets/1191098/16421652/560862f4-3d1b-11e6-87cd-d8949e0ef82e.png)

**Comment by Neo-Oli** [comment]
I can reproduce this on my Xperia Z Tablet running the stock  firmware.

**Comment by memeplex** [comment]
I can reproduce it in my nexus 7.

**Comment by fornwall** [comment]
Is this fixed by the new v0.39 update of the app for you?

**Comment by mozzwald** [comment]
Works for me on v0.39, thanks, closing.

**Comment by memeplex** [comment]
Works like a charm. Thanks!
