### ISSUE TITLE
Can someone explain how to set a cronjob on Termux?

### ISSUE THREAD

**Issue by Areahints** [termux/termux-app#1091]
I have added the following command to `crontab -e`

0 14 * * * some command

How can I check if it's running, usually I would do this via `ps -a` on a Linux install.

thanks!

**Comment by xeffyr** [comment]
Create crontab and then manually launch `crond`. There no init system and everything should be started manually.

**Comment by Areahints** [comment]
thanks @xeffyr  one last question

in #14 there's this answer

```
So the following is all you really need within bashrc, or preferably bash_profile if bash_profile works on your termux install:

if ! pgrep -f "crond" >/dev/null; then
echo "[Starting crond...]" && crond && echo "[OK]"
else
echo "[crond is running]"
fi

The reason why bash_profile is preferred, bash_profile is called once during initial login, versus bashrc upon each shell opening. (Will save a few CPU cycles to use bash_profile.)

```
If i add this i wont need to manually start crond right?

**Comment by xeffyr** [comment]
Yes, this should work.

**Comment by dimaslanjaka** [comment]
https://www.youtube.com/watch?v=-ImhbXQEdPI

**Comment by karlicoss** [comment]
https://www.reddit.com/r/termux/comments/i27szk/how_do_i_crontab_on_termux/g02pghj/
This tip helped me:

> pkg install cronie termux-services
> # restart termux session
>  sv-enable crond 
> crontab -e

**Comment by dummifiedme** [comment]
I needed some help here.
I had a cron job which works fine when I set it up. But in case I accidently kill termux, the services also stops forever for me.
 I tried enabling-disabling again, doesn't work. I even tried clearing cache and all, doesn't work. Ha to reinstall and set everything up again :(
 
 Is there a way to fix it?

Note: I am trying to auto sync a git repo.
