### ISSUE TITLE
[Samsung OneUI] Can't exit Termux properly

### ISSUE THREAD

**Issue by cawilliamson** [termux/termux-app#1094]
Hi folks!

I'm not sure if this has been raised already but ever since Samsung's Android Pie "OneUI" was released I cannot exit Termux without a force close.

Exiting works as normal but then you see it in the notification drawer as normal. Tapping Exit from there results in nothing happening.

Has anyone else experienced this and if so - how can I fix / workaround the issue?

**Comment by cawilliamson** [comment]
Is nobody else experiencing this at all? I've had this since I upgraded to the Samsung "OneUI" (aka Android Pie on Samsung) - never been able to use the exit button from the notification panel properly meaning I have to force close from settings whenever I want to leave Termux.

**Comment by cawilliamson** [comment]
I figured this one out finally! If Termux is marked as a "Sleeping app" in the Samsung battery manager it isn't allowed to the foreground to exit properly.

Remove it from battery manager and it exits cleanly as intended.

**Comment by Grimler91** [comment]
@cawilliamson Great that you figured it out! I'll close this then.
