### ISSUE TITLE
Question: Terminal - Option to disable line break?

### ISSUE THREAD

**Issue by GitToTheHub** [termux/termux-app#1095]
I'm using Termux with a Smartphone and don't want the output to be breaked in new lines, instead i want to scroll to left & right. It's very confusing, when it breaks on such a small screen on multiple lines. For example, when you print the help of a command it's very hard to read in portrait.
Is there an option to enable this?

**Comment by xeffyr** [comment]
No option to disable line break. Terminal cannot be automatically resized as it should have fixed size, otherwise many programs (especially ncurses-based) will be broken.

**Comment by GitToTheHub** [comment]
Thanks, is there an option to set the terminal width in generell?

**Comment by xeffyr** [comment]
Pinch zooming. Just like in web browser.

**Comment by GitToTheHub** [comment]
Thanks, i didn't knew about this feature yet. But the font size becomes really small, when you want for example read the git help. So i guess the terminal size, without losing the font size, cannot be changed :)

**Comment by artus** [comment]
What if it would be possible to pinch zoom to a size that makes the terminal very wife, and then enable keyhole view that does not change the width of the terminal but does change the width of the viewport?

**Comment by xeffyr** [comment]
> That viewport could then be used to scroll left and right etc?

Scrolling won't be implemented as gestures already reserved for mouse actions.

**Comment by onceagainifindmyselfhere** [comment]
Gestures and mouse actions can easily be toggled between each other

**Comment by ChiefMikeK** [comment]
You could also try to [tee(1)](https://linux.die.net/man/1/tee) your output and read it in another app
