### ISSUE TITLE
Keyboard is shown when open Termux from the background but keyboard was hidden before

### ISSUE THREAD

**Issue by GitToTheHub** [termux/termux-app#1097]
**Problem description**
When i hide the keyboard for a session (because it's a server session without needed input) and send Termux to the background and switch again back to Termux, then the keyboard is shown again.

It's very annoying, each time when i switch to my server session, that i must hide the keyboard again.

**Expected behavior**
When i hide (or show) the keyboard for a session, then termux should remind this setting and restore it, when i reopen it from the background.

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by xeffyr** [comment]
This is indended behaviour.

**Comment by GitToTheHub** [comment]
Why? Why i must always hide the keyboard again for my server session. What's the intention here?

**Comment by xeffyr** [comment]
Because many (if not most) users want their keyboard automatically shown.
