### ISSUE TITLE
Auto exit on success

### ISSUE THREAD

**Issue by scompo** [termux/termux-app#1099]
Hello, i liked how termux asked to press a key to exit, especially in conjunction with termux-widget, so I could look at the output before closing the window.
As I could understand from the issues on the project is not the default behaviour anymore.
I'm currently exiting with exit status <> 0 on my script right now, but I don't like this option much, there are no errors from what I'm doing.
Is there a correct way to enable the old behaviour without exiting with an error? Maybe an environment variable to postpone to my command invocation?

**Comment by xeffyr** [comment]
In bash, you can add something like `read -p "[Press enter]"` so it is not a problem to add some user interaction before closing session.

**Comment by scompo** [comment]
Thank you, I used

    read -p "press a key to exit" something

Just for reference there's no way from termux to re enable the old behaviour?

**Comment by xeffyr** [comment]
No way.
This is part of solution for https://github.com/termux/termux-app/issues/988.

**Comment by scompo** [comment]
Ok, thanks
