### ISSUE TITLE
Please dont kill me for reporting this but.... 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-app#1100]
"pkg list-asshole" command lists all the available package.

**Comment by sm4rk0** [comment]
Nice find, but it should be reported to [termux/termux-packages](https://github.com/termux/termux-packages), as [pkg command](https://github.com/termux/termux-packages/blob/fb72854f530ff0f1ad78f434f096b1ead540cd3d/packages/termux-tools/pkg#L37) is part of it.
