### ISSUE TITLE
How to disable Control keys above keyboard?

### ISSUE THREAD

**Issue by Merith-TK** [termux/termux-app#1103]
I use `Hackers Keyboard` which has all of the function keys added in the more recent updates, how do I disable this bar? it takes up a chunk of space on my phone that I kinda need to see what I'm coding.

**Comment by Grimler91** [comment]
Press volume up + q, or long press "keyboard" in the left-drawer. See also https://wiki.termux.com/wiki/Touch_Keyboard

**Comment by Merith-TK** [comment]
Thanks! This is useful!
