### ISSUE TITLE
Can you please add a "Donate to Project Development" MenuItem, in the "More..." Context Menu?

### ISSUE THREAD

**Issue by spaceman5** [termux/termux-app#1105]
Hi

Imagine the scenario inwhich someone bought all Termux Add-ons,
and he wants to support the project a bit more.
Or someone bought all the add-ons that he needs,
and doesn't want to buy and install the rest of the add-ons (that he doesn't need), yet he wants to support the project.

For this,
If you can add a MenuItem to the "More..." Context Menu, that will be called "Contribute to Project"
(financially I mean)

This will open a small InputBox, the user enters a number (in USD), and then confirms.

That way people who wish to, can contribute without installing any more add-ons,
and without being limited by the number of add-ons that exist.

Thank you

**Comment by xeffyr** [comment]
See https://termux.com/donate for donating options.

**Comment by spaceman5** [comment]
Terrific.

Allow me to raise 2 suggestions:
1) Please include in that webpage a remark regarding which of the 3 services takes less fee from the donation someone gives..
So for example, If a person donates 10$, and one service takes 2$, another takes 0.5$, it would definitely help people choose one :)

2) I highly recommend creating the mentioned MenuItem, that will simply open the browser (in Android, outside of Termux of course) with the above URL.
Because other people might not know about it, just like I didn't, and may not give this issue a lot of time to investigate. You want to help people do it, not make it harder...

Thank you for everything
