### ISSUE TITLE
Application name changed on F-Droid

### ISSUE THREAD

**Issue by gappleto97** [termux/termux-app#1107]
To be clear, as I was misunderstood on another issue, the name in the application listing on F-Droid has changed. I am not talking about the new icon. See:

Termux (failsafe) (Terminal emulator with packages) - https://f-droid.org/app/com.termux

![Screenshot](https://i.imgur.com/OAd8hrQ.png)

**Comment by Grimler91** [comment]
Thanks for reporting! This is a bit weird, the metadata that is supposed to hold this type of information [does not mention "(failsafe)"](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.termux.txt)

**Comment by fornwall** [comment]
Created an issue on F-Droid for it: https://gitlab.com/fdroid/fdroiddata/issues/1608

**Comment by Symbian9** [comment]
After upgrading to now I has two shortcuts:

- Termux
- Termux (failsafe)

If launch `Termux` output look like

```
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ 
```

If launch `Termux (failsafe)` output look like

```
u0_a130@ido:/data/data/com.termux/files/home $ 
```

Also there NO any apps available in `Termux (failsafe)`, for example:

```
u0_a130@ido:/data/data/com.termux/files/home $ bash
sh: bash: not found
127|u0_a130@ido:/data/data/com.termux/files/home $

**Comment by xeffyr** [comment]
@Symbian9 You have everything as should be. Second icon is intentional (provides access to /system/bin/sh). Read changelog.

**Comment by t-m-w** [comment]
When searching F-Droid for Termux, an application called AnLinux comes up as well. Due to the "(failsafe)" in the name of the current Termux entry, some users may be misled into believing that AnLinux is "the new Termux." Hopefully this name issue can be resolved soon to avoid further confusion.

**Comment by Grimler91** [comment]
This has been fixed.

**Comment by silversoul42** [comment]
Duplicate of #
