### ISSUE TITLE
Lost home directory

### ISSUE THREAD

**Issue by dwrz** [termux/termux-app#1108]
**Problem description**
I appear to have lost my home directory on reboot. There is nothing in the home directory and my packages are gone. It appears that Termux has been installed from scratch.

I updated Termux sometime in the last week, which added the failsafe icon. Earlier this week or last week, I had an Android system update. My device is a non-rooted Pixel 2.

The user has changed, it looks like it's gone from ua032 to ua132.

Is there any way for me to recover the home directory?

**Steps to reproduce**
Unfortunately, I'm not sure. I had a `mosh` session actively running in Termux before the reboot. After rebooting, all my files were gone.

**Expected behavior**
I expected my home directory to be left untouched by either an app update or a system update or a reboot of the device.

**Additional information**
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.155-g9db9532ae32d #1 SMP PREEMPT Fri Feb 8 01:28:38 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Google
Device model:
Pixel 2

**Comment by xeffyr** [comment]
> My device is a non-rooted Pixel 2.
> The user has changed, it looks like it's gone from ua032 to ua132.

User id chaning means that application was *reinstalled*, no matter by user or somehow by OS.

**Data is definetly lost.** Otherwise it had been present - Termux stores it's data in fixed location which is **same** on all devices regardless of Android version.

**Comment by dwrz** [comment]
Thank you -- appreciate a definitive answer. I'll pull out the backup, then.
