### ISSUE TITLE
Using the Termux shortcuts widget, how can I automatically close the session after the script has completed?

### ISSUE THREAD

**Issue by bitcoinmeetups** [termux/termux-app#1109]
Using the Termux shortcuts widget, how can I automatically close the session after the script has completed?

Hi, 

I am using the Termux shortcuts widget to launch scripts from the home screen (Android 8).

After the script has completed it prints "Process completed, press Enter".

I want to close the session automatically when the script has finished if possible.

Is there a way to do this?

BM

**Comment by xeffyr** [comment]
> Is there a way to do this?

Way is quite simple: update Termux application to **v0.67**.
Note that it will close session automatically only if exit code is "0" or "130".

**Comment by chew-z** [comment]
I had a couple of scripts for checking IP address, weather forecast etc. Since the update they close before I can see the results, so I had to add some sleep time. 

That change was unexpected. Makes writing some script more complex.

**Comment by Grimler91** [comment]
@chew-z You can exit with an error code to get the old behaviour (see xeffyrs comment above), so:
```bash
check-weather.sh
whats-my-ip.sh
exit 1
```

Will give you the "Press enter" as before.

**Comment by xeffyr** [comment]
Or just add `read -p "Press enter"` at the script end.

**Comment by chew-z** [comment]
Cool, thank you. ;-) 

I am not complaining, just have noticed that today and have been surprised. Still enjoying Termux
