### ISSUE TITLE
Auto-Close feautre, Howto

### ISSUE THREAD

**Issue by UmutAlihan** [termux/termux-app#1110]
Hi,

I have read in one of pull request discussion, that auto-close feature is implemented (which provides closing of termux without any user interactions such as "press Enter")

So how should we use this? Could you please provide more info on that?

**Comment by xeffyr** [comment]
It just permanent feature that automatically closes session when shell exits.

Shell can be exited with **ctrl+d** key combination or command "exit". Auto-closing works only in case if exit code was **0** or **130** - to make sure that user is able to read message if something errored.
