### ISSUE TITLE
Ngrok not connecting

### ISSUE THREAD

**Issue by Urfander** [termux/termux-app#1111]
I install ngrok in my termux and i connect to my account with authtoken but when i start in session status a appear "reconnecting (dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:376" and not connect.Someone can tell me what i have to do for ngrok work?Thanks

**Comment by xeffyr** [comment]
**Termux has nothing to do with Ngrok services !!!**

**Comment by xeffyr** [comment]
fishers...
