### ISSUE TITLE
Long Press Copy/Paste pop-up doesn't appear when connected with DeX

### ISSUE THREAD

**Issue by jbEEzerm** [termux/termux-app#1115]
**Problem description**
When using termux on galaxy s9 and connected to external monitor/keyboard via DeX, long pressing to use android clipboard does not work. The pull tabs for selecting/highlighting text appear but the pop-up to choose a particular action, Copy, Paste, etc. does not appear on screen. 
This works as expected when not connected to external peripherals using DeX.

**Steps to reproduce**
1) Connect DeX compatible USB dock
2) connect HDMI monitor and usb keyboard 
3) Launch termux
4) Long press on the window by pressing and holding left mouse button
5) Selector tabs appear but no function selector popup

**Expected behavior**
I would expect the android clipboard pop-up "copy/paste" menu would appear and be selectable.

**Additional information**
If I grab the termux window with the left mouse button and drag it to the left side of my monitor the "copy/paste/more" pop-up will appear. If I drag to the right side it will disappear again. It seems to only appear within a small area on the left side of my monitor. Perhaps this is a clue.

Other apps appear to support the use of the right mouse button to expose the clipboard copy/paste functions when using DeX. Using the right mouse button in termux  does expose a pop-up menu but clipboard copy/paste do not seem to be included on the options of this menu. Perhaps adding these functions to that menu is a better solution for DeX users.

$ termux-info
Updatable packages:
bash/stable 5.0.7 aarch64 [upgradable from: 5.0.3]
libnghttp2/stable 1.38.0 aarch64 [upgradable from: 1.37.0]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.112-15611914 #2 SMP PREEMPT Tue Mar 26 18:55:17 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-G960U

**Comment by mparson** [comment]
Same phone, same behavior.

However, it *does* work on my Galaxy Tab S5e.

**Comment by luben93** [comment]
I have the same problem on my galaxy S8

**Comment by luben93** [comment]
after some more duckducking i found that CTRL+ALT+V works for me

**Comment by iict-malyshkin** [comment]
Same problem on Galaxy Tab S4 after update from android 8 to android 9.
It worked fine on android 8.
On a9 copy/paste menu shows only if one of the text selection border has xpos < 600px and one (same or second one) has ypos <800px.
Also I have some troubles selecting text with stylus - it selects text ~50px above the cursor. Selecting with touch works without any problem.

**Comment by buttaface** [comment]
Works for me on Android 11, please reopen if still a problem.
