### ISSUE TITLE
Problem with Metasploit

### ISSUE THREAD

**Issue by Tema134** [termux/termux-app#1116]
Metasploit doesn't work and I get this error

metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
And this way can't help me
wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt

bash fix-ruby-bigdecimal.sh.txt

**Comment by xeffyr** [comment]
The only way to get a working metasploit is:
```
pkg install unstable-repo
pkg install metasploit
```
