### ISSUE TITLE
Why does the keyboard become a less functional style since version 66?

### ISSUE THREAD

**Issue by cok3307788** [termux/termux-app#1118]
**Feature description**
Why does the keyboard become a less functional style?
I noticed that since the 66 version, the keyboard has become less functional.
For example,it less the up and down arrow keys and page up/down keys, these functions are very useful for me, I hope to keep them.

**Reference implementation**
I hope I can keep the keyboard style at version 65.
How can I do?

**Comment by trygveaa** [comment]
It is configurable. Look at https://wiki.termux.com/wiki/Touch_Keyboard under "Extra Keys Row".
