### ISSUE TITLE
CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found

### ISSUE THREAD

**Issue by gerroon** [termux/termux-app#112]
Hi

THat is the message I get wehen I ssh to my tablet and run "mc". Naturally mc is installed on the tablet in Termux.

I am using CM 13 Marshmallow

thanks

**Comment by gerroon** [comment]
Hmmm

I was running as "su" when I tried to do that.

**Comment by fornwall** [comment]
When running `su`, the `LD_LIBRARY_PATH` environment variable needed by Termux packages to find shared libraries get lost.

For a utility script working around that see https://github.com/cswl/tsu, which you can install with `apt update && apt install tsu`.

**Comment by gerroon** [comment]
@fornwall 
thanks


cheers

**Comment by sinyopompos** [comment]
its worked, but everytime i going back to terminal again its says CANNOT LINK EXECUTABLE: library "libandroid-support.so" again, so i must type it manually for every start termux

**Comment by PranshuTG** [comment]
Uhhm I can't run tsu
and I need to run it because I read in another issue that java won't work on armv7 devices properly
CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
This is what it says when running it 
My phone is Samsung galaxy grand quattro
