### ISSUE TITLE
Question - How to tell Shell is Invoked as Login Shell

### ISSUE THREAD

**Issue by mitnk** [termux/termux-app#1120]
On Mac or Ubuntu hosts, login shell would prefixed with a `-`. If you run `ps ax`, you would see `-bash` as the command name. [Some other source here](https://superuser.com/questions/278859/dash-in-front-of-bash).

In Termux, this is not the case, `-` is not got prefixed. Then how, as shell itself, to tell if it's invoked as a login shell?

**Comment by xeffyr** [comment]
The symbol `-` before command is passed as *zero's command line argument* to execve() system call. Do not try to use this character for shell scripting, you will not be able to use it.

Read the man page of shell (e.g. [bash](https://linux.die.net/man/1/bash)) to learn how to launch login shell:
>-l
Make bash act as if it had been invoked as a login shell (see INVOCATION below). 

So in case of bash, just execute it as `bash -l`.

**Comment by mitnk** [comment]
Oh, thanks! I only noticed `--login` :)

**Comment by mitnk** [comment]
PS. I'm not asking how, I, to run shell as a login shell. I was asking how a shell (bash, fish, etc) is invoked **by Termux** when as a login shell :)

**Comment by xeffyr** [comment]
@mitnk In the same way as I wrote above. See https://github.com/termux/termux-packages/blob/master/packages/termux-tools/login
