### ISSUE TITLE
[Feature Request]  In-Memory FileSystem Hook instead $PREFIX/tmp

### ISSUE THREAD

**Issue by uzilla** [termux/termux-app#1121]
**Feature description**

Use In-Memory FileSystem Hook(may require a daemon for share) implement the tmpfs and bind it on $PREFIX/tmp or fake it as /tmp.

**Reference implementation**

None

**Comment by xeffyr** [comment]
Why not to implement user-space Linux kernel then ???

**Comment by xeffyr** [comment]
Definetly wontfix !
