### ISSUE TITLE
How to Embed Terminal Emulator in App

### ISSUE THREAD

**Issue by TheBrokenRail** [termux/termux-app#1124]
**Feature description**
There is no easy way to embed Termux's terminal into an android app. You would preferably not have to launch a program to use it.

**Comment by Grimler91** [comment]
There is at least one duplicate question/issue about this, but I can't locate it now.

You would need to recompile all termux packages you want to have access to as TERMUX_PREFIX would differ for the other app

**Comment by xeffyr** [comment]
> There is no easy way to embed Termux's terminal into an android app.

No and never be.
Packages are compiled against /data/data/com.termux/files/usr sysroot.

**Comment by xeffyr** [comment]
If you need only TerminalView without any packages, then it shouldn't be hard.

**Comment by TheBrokenRail** [comment]
No, I mean the actual VT-100 Terminal Emulator, not any of the packages, just a View, you can hook up to a stdout, receive stdin. This stdout could be from any source, and the stdin could go to any source, not necessarily executable's.

**Comment by xeffyr** [comment]
Than what problem with reusing https://github.com/termux/termux-app/tree/master/terminal-emulator and https://github.com/termux/termux-app/tree/master/terminal-view ?

**Comment by TheBrokenRail** [comment]
Their aren't really any documentation on how to use TerminalView.
