### ISSUE TITLE
copy and paste no longer works with gboard

### ISSUE THREAD

**Issue by Austcool-Walker** [termux/termux-app#1126]
GBoard restricts the paste function in the app I can copy but will not let me paste does termux support pasting commands or text anymore it used to work fine?

**Comment by Austcool-Walker** [comment]
![Screenshot_20190505-153845_Termux](https://user-images.githubusercontent.com/29024076/57199353-faa72880-6f4b-11e9-9e1a-76ab1a23c07c.jpg)

**Comment by xeffyr** [comment]
> does termux support pasting commands

Of course. But Termux:API is needed.

**Comment by Austcool-Walker** [comment]
The device seems to act as if the termux app is a secure windows for passwords or something this is not supposed to happen.

**Comment by Austcool-Walker** [comment]
Ok thanks

**Comment by xeffyr** [comment]
I just installed Gboard and copy/paste working fine. So there issue with something else.
