### ISSUE TITLE
我可以启动iOS文件吗？

### ISSUE THREAD

**Issue by zccusergit** [termux/termux-app#1127]
How termux boots IOS files

**Comment by xeffyr** [comment]
From Termux description:
```
Termux is an Android terminal emulator and Linux environment app
```

Is somewhere mentioned that Termux is IOS environment ? No. It even exclusively Android-only application.

**Comment by xeffyr** [comment]
By the way, executing IOS is definetly impossible here:
* All (or most) IOS system files are proprietary.
* IOS/darwin kernel interfaces are incompatible with Linux ones.
