### ISSUE TITLE
Trying to get and set system vars.

### ISSUE THREAD

**Issue by praveenscience** [termux/termux-app#1130]
Hi Guys... Quick help. I just installed Termux on my OnePlus mobile just now. Is it possible to run commands like `adb shell settings put global` on it? If so, how should I type them in the termux terminal?

I saw somewhere to use `su -c`, but I get an error saying: `No su program found` (similar to https://github.com/termux/termux-app/issues/430).

BTW, I am able to do it without rooting from `adb shell` from a PC / Mac.

I haven't rooted my phone and would like to **not** root the phone. BTW, the command I would like to run is:

```shell
adb shell settings get global op_voice_recording_supported_by_mcc
adb shell settings put global op_voice_recording_supported_by_mcc 1
```

I get this error if I try in termux, removing `adb shell`: `Failure calling service settings: Failed transaction`. How should I proceed? Am I making any mistake?

Please help. 😇

**Comment by xeffyr** [comment]
> Is it possible to run commands like adb shell settings put global on it?

Since there no package "adb", you can't execute commands like
```
adb shell settings put global op_voice_recording_supported_by_mcc 1
```
on device.

**Comment by praveenscience** [comment]
@xeffyr Agreed. But this is the main reason I tried installing this app. What about the error with settings?

**Comment by xeffyr** [comment]
You cannot write these settings without having system privileges (like adb) or root.

**Comment by praveenscience** [comment]
@xeffyr So is it true that without root permissions, I'll be able to do it on a MacOS using adb?

**Comment by xeffyr** [comment]
By using ADB, you can do some more stuff than regular application because of higher privileges.

**Comment by praveenscience** [comment]
Final question. Will I be able to do the above commands using Termux? Based on your comments, can I take it as "no"? Thanks again for your patience. 😇

**Comment by xeffyr** [comment]
You can't. Termux is not adb and doesn't have adb utility.

**Comment by praveenscience** [comment]
Thank you so much... 😇
