### ISSUE TITLE
Please remove "fail safe" icon.

### ISSUE THREAD

**Issue by neo-expert** [termux/termux-app#1131]
When I search for Termux APP, I always accidentally open the failsafe mode icon. What is it for? It is just annoying.
![Screenshot_20190514-172911_Google](https://user-images.githubusercontent.com/43422542/57711363-dabfe500-766e-11e9-934e-3d3b9ece86fc.jpg)

**Comment by xeffyr** [comment]
> Please remove "fail safe" icon.

`pm disable com.termux/com.termux.app.TermuxFailsafeActivity`

> What is it for?

From changelog:
*A failsafe session, to be used if normal sessions no longer start, is now accessible via separate launcher icon. With this change we now close sessions that exits cleanly directly.*

Required by https://github.com/termux/termux-app/issues/988.
