### ISSUE TITLE
Termux renamed the path of my internal storage when I am uploading to Google Drive

### ISSUE THREAD

**Issue by Edwin-Pratt** [termux/termux-app#1132]
**Problem description**
I have just noticed a bug. It seems to be caused by Termux. If I am uploading a file to Google Drive, and I want to go to the internal storage, I have to tap on an option called "Termux". Once there, I am placed in my Termux home folder.

![Screenshot_20190514-180016](https://user-images.githubusercontent.com/34472632/57714567-16f64400-7675-11e9-8a46-6669e9f3e541.png)
![Screenshot_20190514-180021](https://user-images.githubusercontent.com/34472632/57714729-6b99bf00-7675-11e9-9087-959bfff23e9a.png)

**Steps to reproduce**

1. Go to Google Drive.

2. Swipe left to right to open the menu.

3. Tap on "Termux" to go to the home directory of Termux.

**Expected behavior**

Before I installed Termux, I never had this issue. I always would see "Internal Storage".

**Additional information**
Post output of command `termux-info`.

```text
Updatable packages:
ncurses/stable 6.1.20181117-4 arm [upgradable from: 6.1.20181117-3]
ncurses-ui-libs/stable 6.1.20181117-4 arm [upgradable from: 6.1.20181117-3]
readline/stable 8.0-1 arm [upgradable from: 8.0]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.83+ #1 SMP PREEMPT Fri Mar 22 10:16:08 CST 2019 armv7l Android
Termux-packages arch:
arm
Android version:
8.1.0
Device manufacturer:
Mobicel
Device model:
TRENDY_LITE
```

**Comment by tomty89** [comment]
![_20190515_005343](https://user-images.githubusercontent.com/8604057/57716654-0f05c680-76ac-11e9-800c-499c2b6e9f43.JPG)
![_20190515_005237](https://user-images.githubusercontent.com/8604057/57716673-16c56b00-76ac-11e9-8067-de1ac1e1e6a7.JPG)
![_20190515_005252](https://user-images.githubusercontent.com/8604057/57716682-1af18880-76ac-11e9-94ef-7ec1535c6ec1.JPG)
![_20190515_005405](https://user-images.githubusercontent.com/8604057/57716696-2349c380-76ac-11e9-943d-7e405e154dff.JPG)
