### ISSUE TITLE
Zap2XML.pl Run Not able to Log in with Email

### ISSUE THREAD

**Issue by MCTyler** [termux/termux-app#1134]
**Feature description**
Trying to Download EPG with zap2xml.pl, installed all the libraries I can think of for Perl/cpan but launching App gets stuck at Email login. Any Ideas how to fix?

**Reference implementation**
     
     LWP will support https URLs if the LWP::Protocol::https module
     is installed.

     Failed to download within 3 retries.
     Server out of data? Temporary server error? Normal exit anyway.

**Comment by Grimler91** [comment]
What is zap2xml.pl? What is EPG? 

This doesn't seem to be a termux issue as we don't have a package/program called zap2xml. You also haven't given steps needed for reproducing the issue so this feels off topic for this repo. 

The [community channels](https://wiki.termux.com/wiki/Community) like [reddit](https://www.reddit.com/r/termux/) would probably be more appropriate for a question like this

**Comment by MCTyler** [comment]
Sorry, Zap2XML is a Perl Binary Script used to Download EPG (Electronic Program Guide) (TV Guide).
Steps to reproduce this issue is to Download zap2xml script, then run the script from the command line.

http://zap2xml.awardspace.info/

This script will run fine in any other Linux Platform but it qill not run in Termux. Maybe it never will...I don't really know.
