### ISSUE TITLE
Termux launcher icon gone

### ISSUE THREAD

**Issue by pollen5** [termux/termux-app#1139]
I just updated termux to latest today which included in changelog about removing the failsafe activity and suddenly the app icon is gone in my launcher, I'm using a Huawei Y5 2019 (Android 9 Pie)

**Comment by cyh-ustc** [comment]
I can't find the app icon too. 
I have to start the program in Google play store. 
I'm using a Huawei p20(Android pie).

**Comment by pollen5** [comment]
it just appeared back for me, what i recently did was a software update but i believe just a reboot was what it needed.
