### ISSUE TITLE
add to wiki "install to /system/bin/sh"

### ISSUE THREAD

**Issue by Mannshoch** [termux/termux-app#1142]
Please add this Question to Wiki: 
1.) "Could I add Terumx to /system/bin/sh?"
2.) "Could I Install apps with termux to /system/bin/sh?"

Answer may come from #128

**Comment by xeffyr** [comment]
No, we cannot add this information for multiple reasons:
* It is not possible: all our packages are compiled with prefix `/data/data/com.termux/files/usr` and therefore cannot be used outside of Termux app.

* You are requesting something wrong: `/system/bin/sh` is a file. It is not a directory and packages cannot be installed here.

* Overwriting `/system/bin/sh` as well as other system files is **very bad idea**.

**Comment by xeffyr** [comment]
Closing as offtopic since request goes above purpose of Termux project.
