### ISSUE TITLE
Can't use the app

### ISSUE THREAD

**Issue by PyHker** [termux/termux-app#1143]
I launched my app this morning and this error showed up

NOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "cat"...
page record for 0xb6e5100c was not found (block_size=64)
CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "realpath"...
page record for 0xb6e4d00c was not found (block_size=64)
/data/data/com.termux/files/usr/bin/login: 24: exec: : Permission denied

[Process completed (code 126) - press Enter]

**Comment by xeffyr** [comment]
Fixed.
But you may need to reinstall the app.
