### ISSUE TITLE
Termux suddenly Chinese anomaly display

### ISSUE THREAD

**Issue by 9tail123** [termux/termux-app#1144]
I didn't do any exception modification, but when I use the ls command to view the file after starting the termux, all the files containing Chinese characters are displayed abnormally. For example, "异常恢复.py" becomes "'$$\345 \274\202''常恢 '$'\345\244\215''.py'", but the "ls|grep 异常" command can display the file name normally, /data/data/com.termux/files/ There is no problem with the file name in the home directory. And I will not have problems creating a new file with a Chinese name in termux.what could be the problem?
I am using Google Translate, the language may have some problems, please forgive me.

**Comment by xeffyr** [comment]
Chinese characters in file name are displayed correctly:
![Screenshot_20190524-185056_Termux](https://user-images.githubusercontent.com/25881154/58340593-e40e3600-7e54-11e9-822f-1fefcfb1d17f.jpg)

**Comment by xeffyr** [comment]
You probably messed with encoding in file name. Or just something with OS.

**Comment by 9tail123** [comment]
是的，我之前也是正常的，但termux某次启动后ls命令似乎就出现了奇怪的问题，截图在这里http://www.bbvdd.com/d/201905242348397if.jpeg （上传图片时提示没有可用的应用，我临时寻找了一个在线图片分享网站）我不太确定这个问题究竟是怎么回事，这是仅属于ls的错误还是termux的问题，我应该怎么做？
Shì de, wǒ zhīqián yěshì zhèngcháng de, dàn termux mǒu cì qǐdòng hòu ls mìnglìng sìhū jiù chūxiànle qíguài de wèntí, jiétú zài zhèlǐ http://Www.Bbvdd.Com/d/201905242348397if.Jpeg (shàngchuán túpiàn shí tíshì méiyǒu kěyòng de yìngyòng, wǒ línshí xúnzhǎole yīgè zàixiàn túpiàn fēnxiǎng wǎngzhàn) wǒ bù tài quèdìng zhège wèntí jiùjìng shì zěnme huí shì, zhè shì jǐn shǔyú ls de cuòwù háishì termux de wèntí, wǒ yīnggāi zěnme zuò?
展开
Yes, I was normal before, but the ls command seems to have a strange problem after the termux is started. The screenshot is here http://www.bbvdd.com/d/201905242348397if.jpeg (The prompt is not available when uploading the image. The application, I temporarily looked for an online photo sharing site) I am not sure what the problem is, is this a problem that only belongs to ls or termux, what should I do?

**Comment by 9tail123** [comment]
Ok, thank you, my file doesn't know why, it seems to have become the ascii encoding format. It may be for this reason. I will continue to study it, bother, good night.
