### ISSUE TITLE
Termux Reboot API

### ISSUE THREAD

**Issue by Benozo** [termux/termux-app#1146]
Im not able to find any information or documentation if there is any reboot API.

If anyone can direct me to the docs would be much appreciated .

**Comment by Grimler91** [comment]
It's not possible to reboot an android device through the android api, at least not without root https://stackoverflow.com/questions/32984849/restart-android-device-programmatically

**Comment by Benozo** [comment]
Found another way, searching through the Termux file system i found "/system/bin/reboot"..this worked for my use case.
