### ISSUE TITLE
SSHD keeps timing out my SSH sessions. Where and how can I edit sshd_config or equivalent to keep sessions alive?

### ISSUE THREAD

**Issue by bitcoinmeetups** [termux/termux-app#1149]
SSHD keeps timing out my SSH sessions. Where and how can I edit sshd_config or equivalent to keep sessions alive?

**Comment by xeffyr** [comment]
https://stackoverflow.com/questions/25084288/keep-ssh-session-alive

And:
`man ssh_config`: https://linux.die.net/man/5/ssh_config
`man sshd_config`: https://linux.die.net/man/5/sshd_config
