### ISSUE TITLE
termux-* hangs

### ISSUE THREAD

**Issue by KrullBorg** [termux/termux-app#1151]
i have android 5.0 and when i run most of termux-* commands i don't get any output; the command hangs until ctrl-c

termux-info works

thanks in advance

Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.54 #1 SMP PREEMPT Wed Nov 4 09:12:54 CET 2015 armv7l Android
Termux-packages arch:
arm
Android version:
5.0
Device manufacturer:
bq
Device model:
Aquaris E5 HD

**Comment by Grimler91** [comment]
Have you installed the `termux-api` **app**?

**Comment by KrullBorg** [comment]
> Have you installed the `termux-api` **app**?

yes. maybe i need some other packages? or i need to set some permission?

running "termux-* -h" works

**Comment by Grimler91** [comment]
Make sure your packages are up to date. If the problem still occurs then we probably need to see the logcat output (if any). 

Similar previous issues: https://github.com/termux/termux-packages/issues/3809, https://github.com/termux/termux-packages/issues/2388

**Comment by KrullBorg** [comment]
i installed also Termux:API app and now commands work
