### ISSUE TITLE
No way to turn on extended keos

### ISSUE THREAD

**Issue by dov** [termux/termux-app#1152]
**Problem description**
On my new e-ink tablet there are no volume keys. There is therefore no way (at least that I know of) of turning on the extended keyboard.  A possible (and easily discoverable) interface for this would be in the "long press" settings menu.

**Systen info**
Updatable packages:
apt/stable 1.4.9-4 arm [upgradable from: 1.4.9-3]
command-not-found/stable 1.37 arm [upgradable from: 1.36]
dpkg/stable 1.19.6 arm [upgradable from: 1.19.4-3]
gnutls/stable 3.6.8 arm [upgradable from: 3.6.7.1]
libandroid-support/stable 24-3 arm [upgradable from: 24-2]
libbz2/stable 1.0.6-3 arm [upgradable from: 1.0.6-2]
libcurl/stable 7.65.0 arm [upgradable from: 7.64.1-1]
libevent/stable 2.1.10 arm [upgradable from: 2.1.8-1]
libgmp/stable 6.1.2-2 arm [upgradable from: 6.1.2-1]
libgnutls/stable 3.6.8 arm [upgradable from: 3.6.7.1]
libiconv/stable 1.16-2 arm [upgradable from: 1.16-1]
libidn2/stable 2.2.0 arm [upgradable from: 2.1.1a]
libxml2/stable 2.9.9-3 arm [upgradable from: 2.9.9-2]
ncurses/stable 6.1.20190511-1 arm [upgradable from: 6.1.20190511]
openssl/stable 1.1.1c arm [upgradable from: 1.1.1b-3]
readline/stable 8.0-1 arm [upgradable from: 8.0]
termux-tools/stable 0.66 all [upgradable from: 0.65]
Subscribed repositories:
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.0 #7 SMP PREEMPT Thu Apr 11 07:42:33 CST 2019 armv7l Android
Termux-packages arch:
arm
Android version:
6.0.1
Device manufacturer:
Onyx
Device model:

**Comment by xeffyr** [comment]
If no volume keys, then only through drawer: swipe right = > long press on button "keyboard". Hope swipe gestures working...

And what is your Termux application version ? Extended keys are enabled by default on fresh installation.

**Comment by dov** [comment]
Oh. Now I understand. The extended keys do appear. But I had chosen to increase the contrast on the E-ink screen which caused both text and background to be white. Once I turned that off they appeared. Getting "normal" application working on e-ink isn't easy...
