### ISSUE TITLE
tintin++ use termux,but extra keyboard can be better

### ISSUE THREAD

**Issue by zixijian** [termux/termux-app#1153]
**Feature description**
tintin++ is a Mud client,sometimes it need more key like e;w;up;down,now i can add it，but it only input the word,if wanna be better,should make more rules,like 'e:ENTER','do:{#alias pku xxx}'&only show E key.
thanks a lot。

**Comment by zixijian** [comment]
oh，hold key looks good，press key hold something，release key return back。
like turn on turn off.

**Comment by xeffyr** [comment]
> should make more rules,like 'e:ENTER','do:{#alias pku xxx}'&only show E key.
like'do:{i=1;i++}:{if i odd{xx}else{xxx}}'

While key mapping can be implemened, the rules you specified will not. Especially if they involve lang syntax elements like you specified (variables, conditionals, etc...).
