### ISSUE TITLE
Termux isn't working anymore on Android 8.1.0

### ISSUE THREAD

**Issue by draxaris1010** [termux/termux-app#1155]
I was trying to open termux and termux threw some errors
```
CANNOT LINK EXECUTABLE "cat": cannot locate symbol "iconv_open" referenced by "/data/data/com.termux/files/usr/bin/coreutils"...
Aborted
CANNOT LINK EXECUTABLE "realpath": cannot locate symbol "iconv_open" referenced by "/data/data/com.termux/files/usr/bin/coreutils"...

[Process completed (code 126) - press Enter]
```
When I press enter termux closed like you would type in `exit`

**Comment by draxaris1010** [comment]
When in failsafe I was dropped into the standard Android shell that looks like this
```
cedric:/data/data/com.termux/files/home $
```

**Comment by xeffyr** [comment]
Seems like you did partial upgrade, e.g. installing `coreutils` without doing `pkg upgrade` before.

Try to do `pkg upgrade` now. If fails, easiest fix will be to erase prefix:
```
rm -rf $PREFIX
```
then close/open Termux again and re-install needed packages.

**Comment by draxaris1010** [comment]
I tried but pkg depends on apt which isn't working
```
127|cedric:/data/data/com.termux/files/home$ cd ../usr/bin/
./pkg upgrade
./pkg: 43: ./pkg: apt: not found
127|cedric:/data/data/com.termux/files/usr/bin $
```

**Comment by draxaris1010** [comment]
Running `rm -rf $PREFIX` didn't worked either
```
127|cedric:/data/data/com.termux/files/usr/bin $
rm -rf $PREFIX
sh: rm -rf /data/data/com.termux/files/usr: not found
127|cedric:/data/data/com.termux/files/usr/bin $
```

**Comment by xeffyr** [comment]
I wrote above:

1. `rm -rf $PREFIX`

2. **Close Termux !!!** - means completely, all sessions.

3. Open it again.

**Comment by draxaris1010** [comment]
It still doesn't work 😕

**Comment by xeffyr** [comment]
If `rm` doesn't work, then from failsafe shell:
```
rm -rf /data/data/com.termux/files/usr
```

**Comment by draxaris1010** [comment]
I can only use the failsafe shell and I tried your command and here's the output
```
127|cedric:/data/data/com.termux/files/home $ rm -rf /data/data/com.termux/files/usr
sh: rm -rf /data/data/com.termux/files/usr: not found
127|cedric:/data/data/com.termux/files/home $
```
It says that the folder `/data/data/com.termux/files/usr` doesn't exist

**Comment by draxaris1010** [comment]
That is all on my non rooted `Lenovo Motorola Moto G5` running Android 8.1.0 installed from an update from Motorola

**Comment by xeffyr** [comment]
> It says that the folder /data/data/com.termux/files/usr doesn't exist

Okay, now exit, from all sessions or via force-close. And open Termux again, there should appear dialog like on first installation.
