### ISSUE TITLE
TMPDIR gets deleted while background processes may still be running

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-app#1159]
Right now TMPDIR gets deleted in `onDestroy()`. This will cause TMPDIR to get deleted when the last session exits. 
https://github.com/termux/termux-app/blob/e502b9169fdec30200a631cd42dfd3a092e0948e/app/src/main/java/com/termux/app/TermuxService.java#L245

At this point however backgrounded processes or services may still be running, which are suddenly missing their temp files. If you exit the last session you may be unable to access the still running tmux session (when you start a session again or via ssh) as an example.

**Comment by Grimler91** [comment]
Current workaround is to use $PREFIX/var/run instead of $TMPDIR for tmux and other programs

**Comment by sudomain** [comment]
I had tmux sockets get eaten in $TMPDIR as well today, thus I'd like to request for this to be open. People that customize tmux.conf (for example setting the server option `exit-empty` to off) might think there's a problem with tmux when it's really Termux obliterating their sockets in $TMPDIR.
