### ISSUE TITLE
jni won't compile 

### ISSUE THREAD

**Issue by spaesani** [termux/termux-app#116]
I cloned the master branch and cleaned up the try/catch but when building in Aide I don't see the jni termux lib anywhere.
On run the app crashes when trying to load the library.
Am I supposed to see the library or is it packed up somewhere on build?

**Comment by fornwall** [comment]
The JNI code is built by gradle (see `app/build.gradle`) - you may perhaps compile the single C file manually?

**Comment by spaesani** [comment]
Full build. 
I had thought that maybe the build packed up the lib 'on build' as opposed to storing it in the lib folder and then packing  or perhaps the build cleans it out after packing the apk.
I'm not that familiar with gradle and,so can't make out what's intended by looking at the gradle.build.
All I know is there is no trace of the lib after the apk installs and the apk is failing, in my guess,  trying to load it (assuming the rest of the code is clean).
