### ISSUE TITLE
Not installed in first run

### ISSUE THREAD

**Issue by alcott1331** [termux/termux-app#1165]
This problem is observed in Iran for several months
To install on the first run, you have to try different vpn so that after the endeavor, you will finally complete the installation.

Please solve the problem. We face many restrictions in Iran
![Screenshot_20190622-173936](https://user-images.githubusercontent.com/26351293/59964417-8cc3ba00-9515-11e9-910d-691ea4fbe733.png)

**Comment by xeffyr** [comment]
Hosting setup won't be changed.
