### ISSUE TITLE
Operation not permitted even though operation has been done

### ISSUE THREAD

**Issue by sdushantha** [termux/termux-app#1167]
**Problem description**
When you move a file from `~` to `~/storage/shared/` 3 errors are given saying that the `Operation not permitted`, even though the file was actually moved to `~/storage/shared/`

**Steps to reproduce**
```bash
$ cd ~
$ touch file.txt
$ mv file.txt storage/shared/
mv: can't preserve times of 'storage/shared/file.txt': Operation not permitted
mv: can't preserve ownership of 'storage/shared/file.txt': Operation not permitted
mv: can't preserve permissions of 'storage/shared/file.txt': Operation not permitted
```
Now, using your file browser, navigate to your local storage. You will see the `file.txt` there. But according to the errors show by Termux, the file shown have not been moved.

**Expected behavior**
Either the errors should be shown and the file shown not be moved, or the errors are not shown and the file is moved.

**Additional information**
```
Updatable packages:
openssl/stable 1.1.1c-1 arm [upgradable from: 1.1.1c]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.10.61-12236002 #1 SMP PREEMPT Thu Mar 28 14:53:18 KST 2019 armv8l Android
Termux-packages arch:
arm
Android version:
7.0
Device manufacturer:
samsung
Device model:
SM-A510F
```

**Comment by xeffyr** [comment]
> But according to the errors show by Termux, the file shown have not been moved.

No, it will be moved. Errors just tell you that program can't set times, ownership and permissions on files located on sdcard or shared storage.

**Comment by xeffyr** [comment]
Also, I'm suggest to always read complete error message, not only last part because it doesn't explains what exactly happens.

**Comment by sdushantha** [comment]
I'm really sorry about that.
