### ISSUE TITLE
Send text from text input view without newline

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-app#117]
I think there should be an additional way to send the text from the text input view of the v0,35 Preview release to the terminal without sending a newline. This would be very useful inserting into existing continuous text in a text editor or writing a string into a command without executing it yet. 

Maybe an additional button on the right of the text input view.

**Comment by fornwall** [comment]
This has been solved in version 0.47 of the app (see https://github.com/termux/termux-app/issues/261 for details).
