### ISSUE TITLE
Can't install packages. (+ Cava problems)

### ISSUE THREAD

**Issue by GuzioMG** [termux/termux-app#1171]
I recently came back to Termux and decided configure it to fit my preferences. So I first typed Java. And get "Did you mean cava? ". I thought, it's simply a OpenJDK release for Termux, so I downloaded it, without even checking. After getting
` 
Unable to access config '/data/data/com.termux/files/home/.config/cava/config', exiting...
` error, I decided to finally use Google. I noticed, it's just audio visualizer, so ignored that package. But why am I talking about it then? Well:
- It was the first and last package that worked
- Command `pkg install` stopped working after it
- The error says something about accessing to file, so maybe there is problem with permissions (I gave storage permissions to Termux)?

Anyway, I ignored Java and moved to installing Python. And.... Bang! Weird error appeared during installation. I decided to not care about it and begun Node.JS installation. But nope. Same error. I found C# package called Mono, but it requires PC to build and I don't have access to it by the end of the next week, so came back to installing Java. Aaaand I found it. But it needs wget package. And installing wget returned same error. So I can't do anything with my Termux. I hope you can help me.

And finally... Stack trace:
`
Do you want to continue? [Y/n] y
CANNOT LINK EXECUTABLE "dpkg-deb": library "liblzma.so.5" not found
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/ncurses_6.1.20190511-2_aarch64.deb (--unpack):
 dpkg-deb --control subprocess was killed by signal (Aborted)
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
`

Additional info from termux-info:
`
Updatable packages:
apt/stable 1.4.9-10 aarch64 [upgradable from: 1.4.9-4]
bash/stable 5.0.7-2 aarch64 [upgradable from: 5.0.3]
busybox/stable 1.30.1-2 aarch64 [upgradable from: 1.30.1-1]
ca-certificates/stable 20190515 all [upgradable from: 20190124]
command-not-found/stable 1.38 aarch64 [upgradable from: 1.37]
gpgv/stable 2.2.16 aarch64 [upgradable from: 2.2.15-1]
libandroid-support/stable 25 aarch64 [upgradable from: 24]
libbz2/stable 1.0.6-4 aarch64 [upgradable from: 1.0.6-2]
libc++/stable 20 aarch64 [upgradable from: 19b]
libcurl/stable 7.65.1 aarch64 [upgradable from: 7.64.1-1]
liblzma/stable 5.2.4-2 aarch64 [upgradable from: 5.2.4]
libnghttp2/stable 1.39.1 aarch64 [upgradable from: 1.37.0]
ncurses/stable 6.1.20190511-2 aarch64 [upgradable from: 6.1.20181117-1]
openssl/stable 1.1.1c-1 aarch64 [upgradable from: 1.1.1b-2]
readline/stable 8.0-2 aarch64 [upgradable from: 8.0]
termux-tools/stable 0.68 all [upgradable from: 0.65]
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.31-perf-gf2fd6b0 #1 SMP PREEMPT Thu Jan 10 13:30:16 WIB 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.1.2
Device manufacturer:
Xiaomi
Device model:
Redmi 4A
`

**Comment by xeffyr** [comment]
If you didn't used Termux for long time, the first thing you should do is `pkg upgrade`. Now, you just broke the whole installation.

Do `rm -rf $PREFIX` (backup $PREFIX data before, if needed), then **exit** and re-open Termux again.
