### ISSUE TITLE
Something wrong with my basic linux command. CANNOT LINK EXECUTABLE "cat": cannot locate symbol "iconv_open" referenced by "/data/data/com.termux/files/usr/bin/coreutils"...

### ISSUE THREAD

**Issue by JackLee1071426378** [termux/termux-app#1173]
CANNOT LINK EXECUTABLE "cat": cannot locate symbol "iconv_open" referenced by "/data/data/com.termux/files/usr/bin/coreutils"... All busybox command were died.

**Comment by Grimler91** [comment]
If `pkg upgrade` doesn't work then the easiest fix is to run `rm -rf $PREFIX` and then restart termux to download a fresh installation. 
Busybox works fine, it isn't linked against libiconv, it is some of the binaries from coreutils that doesn't work.

See also https://github.com/termux/termux-app/issues/1155

**Comment by JackLee1071426378** [comment]
I can run pkg command, and apt was alive. But it will stuck with calling `rm` command, so it failed... I tried `busybox ls` instead of `ls`, it can work. It was strange. It all happened after I install the mariadb, and run the `mysql_install_db`.

**Comment by Grimler91** [comment]
@JackLee1071426378 try `busybox rm -rf $PREFIX`.

Make sure to run `pkg upgrade` (or `apt update && apt upgrade`) if you haven't used termux in a while, before installing new packages, to decrease the risk of getting into problems due to a partial upgrade.

**Comment by JackLee1071426378** [comment]
It works, the usr directory was removed, and I have to reinstall all the software. But commands are revived.

**Comment by JackLee1071426378** [comment]
@Grimler91 Thanks!!!
