### ISSUE TITLE
الرجاء كل الرجاء المساعدة فالتطبيق لا يحمل الملفات الاساسية مع اني متصل بالإنترنت فالرجاء حل هذه المشكلة وشككرا

### ISSUE THREAD

**Issue by Jackhake** [termux/termux-app#1175]
الرجاء كل الرحاء حل هذه المشكلة فالتطبيق لا يحمل الملفات الاساسية مع اني متصل بالإنترنت فالرجاء حل هذه المشكلة وشكرا

**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by DaBoss5** [comment]
You may want to actually edit the template, and provide the information it requests (and preferably do it in English)

**Comment by xeffyr** [comment]
???

**Comment by xeffyr** [comment]
**No problem description - No solution !**
