### ISSUE TITLE
Reduce Size of Extra Keys

### ISSUE THREAD

**Issue by arndtc** [termux/termux-app#1178]
**Feature description**
Reduce Size of Extra Keys

**Reference implementation**
I was looking for a way to reduce the size of the Extra Keys Row.  I only wanted 1 row, but it appears to be about the same size as when there is 2 rows.  It might be marginally smaller, but the terminal gives me much more space when I just turn off the extra keys completely.

**Comment by xeffyr** [comment]
Actually this is a bug and described in https://github.com/termux/termux-app/issues/1003.
