### ISSUE TITLE
Not sure

### ISSUE THREAD

**Issue by bbalenciaga369** [termux/termux-app#1182]
**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.
I have installing termux and uninstalling it alot of times but its not workinb not matter what pkg i install. Keep setting up storage but still no directory. Its seem others are running on termux.net but mine is running on bintray. Can you please help out?
**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by xeffyr** [comment]
> Its seem others are running on termux.net but mine is running on bintray. Can you please help out?

**Comment by xeffyr** [comment]
> I have installing termux and uninstalling it alot of times but its not workinb not matter what pkg i install. 

That doesn't say anything about problem's origin.
Either post commands with their output or screenshot.

> Keep setting up storage but still no directory.

Are you sure you are doing this correctly ?

> Its seem others are running on termux.net but mine is running on bintray. Can you please help out?

Android 7+ devices use Bintray repository. This is intended behaviour.
