### ISSUE TITLE
Scrolling Behavior

### ISSUE THREAD

**Issue by neo-expert** [termux/termux-app#1184]
**Problem description**
Termux changes it's scrolling behavior for programms like vim and mosh. When you do scroll gestures there, Termux simulates Arrow-Butons, you would normally use to scroll in vim.
 For vim this is useful. But not for mosh. Mosh is like ssh, but uses similar functionally like vim, so Termux simulates Arrow-Butons there too. So when you scroll in mosh, Termux sends arrow-up and arrow-down commands to it.
Can we disable this?

**Steps to reproduce**
pkg install mosh &&
mosh user@server
#do some scroll gestures

**Expected behavior**
It should scroll normally

**Comment by xeffyr** [comment]
mosh doesn't support scrolling.
'https://github.com/mobile-shell/mosh/issues/122

***

Regarding VIM and other programs changing terminal mode, there no other way to scroll but only via mouse events. It isn't Termux changes scrolling behaviour but programs.
