### ISSUE TITLE
external is empty

### ISSUE THREAD

**Issue by daufinsyd** [termux/termux-app#1185]
Hello :)
**Problem description**

storage/external-1/ is empty although I executed the "termux-setup-storage" command.
(The first time I didn't had an sdcard, hence I deleted the folder (~/storage/external-1/) and executed the command once again but there is still no links).

**Steps to reproduce**
- install termux (LineageOS 16 - Android 9)
- grant storage perms (without sdcard)
- add sdcard
- ~/storage/external-1 is empty

**Expected behavior**
I van write to the sdcard using the Termux ~/storage/external-1 symlink.

**Additional information**
`Updatable packages:
ncurses/stable 6.1.20190511-5 aarch64 [upgradable from: 6.1.20190511-4]
Subscribed repositories:
System information:
Linux localhost 4.9.185-perf-g301928a #1 SMP PREEMPT Fri Jul 19 06:38:38 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
POCO F1`

**Comment by xeffyr** [comment]
Yeah, it is empty.
But that's not a bug. Symlink `external-1` points to a **private Termux directory** on external sdcard, i.e. `/storage/XXXX-XXXX/Android/data/com.termux/files`.
