### ISSUE TITLE
Not installing packages for metasploit

### ISSUE THREAD

**Issue by H4ck3r404** [termux/termux-app#1188]
I see this every time i'm trying to install metasploit. Pls help.

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 metasploit : Depends: libffi-dev but it is not installable
              Depends: libgmp-dev but it is not installable
              Depends: libiconv-dev but it is not installable
              Depends: libpcap-dev but it is not installable
              Depends: libsqlite-dev but it is not installable
              Depends: libxml2-dev but it is not installable
              Depends: libxslt-dev but it is not installable
              Depends: ncurses-dev but it is not installable
              Depends: openssl-dev but it is not installable
              Depends: postgresql-dev but it is not installable
              Depends: readline-dev but it is not installable
              Depends: ruby-dev but it is not installable
              Depends: zlib-dev but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by xeffyr** [comment]
`*-dev` packages will no longer be available for installation.
Wait for metasploit package upgrade.
