### ISSUE TITLE
Option to disable Volume Up and Down capturing

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-app#119]
With the next version supporting the extra keys view I think it's no longer necessary to use Volume Up and Down shortcuts. I propose a setting in `termux.properties` to disable this feature to get the standard Android volume control back.

**Comment by fornwall** [comment]
Will think about it - note that you can use `Volume Up+V` to bring up the standard volume control already.

**Comment by tukusejssirs** [comment]
Why there is no settings menu? Why one cannot use the volume buttons as they want? I don’t think that the implementation is too hard to make it happen.

For me, VolUp+V is not acceptable. I use Hacker’s Keyboard (see the screenshot below) and *all* keyboard shortcut work as expected in Termux.
![Screenshot_Termux_20190319-193249](https://user-images.githubusercontent.com/5111894/54632202-75d47e00-4a75-11e9-91fe-9f4029aa0365.png)
