### ISSUE TITLE
Change Default Path

### ISSUE THREAD

**Issue by ugurozturk** [termux/termux-app#1190]
Hi,
As suggested https://github.com/termux/termux-app/issues/836 here. It is not implemented so reopening it.

I want to change it as '/storage/emulated/0'

Thanks,

**Comment by xeffyr** [comment]
> It is not implemented

Because it won't be implemented.
Each package is compiled against prefix `/data/data/com.termux/files/usr`.

>I want to change it as '/storage/emulated/0'

That's not supported at all. Filesystem here doesn't support required features: executable bit, symlinks, sockets, etc...
