### ISSUE TITLE
Multiple windows in DeX

### ISSUE THREAD

**Issue by kudlicka** [termux/termux-app#1191]
**Feature description**
When using the DeX (desktop experience) mode on Samsung devices, Termux uses a single window. It would be great if it was possible to create sessions in new windows as well (and still allowing multiple sessions in each window). Even in the mobile UI, such a feature could be quite useful.

**Reference implementation**
Most of the terminals in Linux and MacOS have a similar feature, e.g. iTerm2 (for Mac) has _New window_ and _New tab_ to open a new session in either new window or a new tab in the existing window.

**Comment by PHPoenX** [comment]
@kudlicka you can use tmux

**Comment by xeffyr** [comment]
> you can use tmux

`tmux` scope is terminal only. It doesn't allow to create multiple **android application windows**.

**Comment by twaik** [comment]
I think you can make script which starts com.termux using am with --activity-multiple-task flag.

**Comment by xeffyr** [comment]
Covered by issue https://github.com/termux/termux-app/issues/1259.
