### ISSUE TITLE
Change default startup path

### ISSUE THREAD

**Issue by ugurozturk** [termux/termux-app#1192]
@xeffyr just give some face, dont lock and limit conversation to collaborators within minutes. There could be somebody, can see that you couldn't see yet. And ideas might be make the repo better than ever. 
https://github.com/termux/termux-app/issues/1190

it can also be compiled in /data/data/com.termux/files/usr here. Yet the startup path can be changed, when the program starts. it just gonna do something like 'cd /storage/emulated/0'

**Comment by xeffyr** [comment]
> it just gonna do something like 'cd /storage/emulated/0'

Well, then do
```
termux-setup-storage
cd /storage/emulated/0
```

Your issue isn't actually https://github.com/termux/termux-app/issues/836.

**Comment by ugurozturk** [comment]
@xeffyr thank you, just created a file named .bashrc and inserted a line "cd /storage/emulated/0" 
Exited the program and reopened, all worked as I wanted amazing

**Comment by xeffyr** [comment]
In v0.107 this will be implemented as `~/.termux/termux.properties` option `default-working-directory`.
