### ISSUE TITLE
Ping Failure 

### ISSUE THREAD

**Issue by hamkido** [termux/termux-app#1194]

**Comment by hamkido** [comment]
system:lineagos16.0
problem:Ping Failure
detail:ping github.com
PING github.com (140.82.114.4) 56(84) bytes of data.
^C
--- github.com ping statistics ---
16 packets transmitted, 0 received, 100% packet loss, time 15062ms

I try to fix it:
I have read the similar issue. ‘https://github.com/termux/termux-app/issues/862’
I follow the 'https://github.com/termux/termux-app/issues/862#issuecomment-427670239'
install the apk, but the apk worked.So I do not know why.

**Comment by hamkido** [comment]
I try to input termux-info  then input ping github.com
detail:
termux-info
ping github.com
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.153-perf-gd3f265d #1 SMP PREEMPT Thu Jan 24 00:58:13 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
MI 8 Lite
%                                                     ~  ping github.com
PING github.com (192.30.253.113) 56(84) bytes of data.
^C
--- github.com ping statistics ---
37 packets transmitted, 0 received, 100% packet loss, time 36099ms

**Comment by xeffyr** [comment]
`ping` is a system utility. Termux provides only wrapper.
All "ping issues" came either from your ROM (OS) or your network setup.
