### ISSUE TITLE
"CANNOT LINK EXECUTABLE" Error in Termux after updating Imagemagick to v 7.0.8.56

### ISSUE THREAD

**Issue by Tawanda-MT** [termux/termux-app#1197]
The following error is since upgrading imagemagick to v 7.0.8.56.

convert u.png test.png
CANNOT LINK EXECUTABLE: cannot locate symbol "jpeg_default_qtables" referenced by "/data/data/com.termux/files/usr/lib/libMagickCore-7.Q16HDRI.so"...
page record for 0xb6f4b02c was not found (block_size=16)

**Comment by fornwall** [comment]
Hello and thanks for reporting!

This should be fixed by upgrading all packages by running: `pkg up`.

If the problem remains even after running that, open a new issue at https://github.com/termux/termux-packages/issues/new?template=bug_report.md.
