### ISSUE TITLE
android.intent.action.view not working

### ISSUE THREAD

**Issue by X1nto** [termux/termux-app#1198]
Hello, i found an issue related to android.intent.action.view string when some repositories want to open downloaded files via gallery or other app

I.e: i was testing meterpreter for this error to appear, and when i do webcam_snap, the downloaded file does not open via gallery, it does not even prompt me to, and i get this error message

Starting: Intent { act=android.intent.action.VIEW dat=/data/data/com.termux/files/home/OZHXPeSz.jpeg }                                                        Error: Activity not started, unknown error code -1

So instead of app opening a gallery, i have to move downloaded file from termux's home direcrory (/data/data/com.termux/files/home) to for example /sdcard, which takes really long time to write the command, can anyone help?
Thanks.

Device: Amazon fire HD 8 2018
Os: Android 7.1.2
Termux version: 0.72

**Comment by xeffyr** [comment]
Applications can't view files located in Termux private directories directly. Use command `termux-open` which calls `com.termux/com.termux.app.TermuxOpenReceiver` with `android.intent.action.VIEW`.

**Comment by v217** [comment]
In the `fish` shell,
I set

    set -Ux BROWSER termux-open-url

and did get this error message:

    Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW 
    dat=file:///data/data/com.termux/files/usr/share/doc/fish/index.html flg=0x10000000 }
    u0_a151@localhost

**Comment by alexandre-mbm** [comment]
@xeffyr, in my case the `termux-open` command opens the file's content in the **QuickEdit+** at _content://com.termux.files..._ — that is not editable.

Is there how to open it for editing?

**Comment by xeffyr** [comment]
> Is there how to open it for editing?

Use SAF in QuickEdit to open file in R/W mode in $HOME directory.

`termux-open` is for viewing files only, not editing. It can't give R/W access.

**Comment by alexandre-mbm** [comment]
SAF? What is it?

**Comment by xeffyr** [comment]
> SAF? What is it?

Thing that allows you to select storage as document provider. If you are QuickEdit user, then you should know about it.

![20200620_092124](https://user-images.githubusercontent.com/25881154/85195014-c15c8400-b2d7-11ea-87df-befba7a94d45.jpg)

![20200620_092251](https://user-images.githubusercontent.com/25881154/85195021-c7eafb80-b2d7-11ea-9b8b-1361df7c527c.jpg)

**Comment by alexandre-mbm** [comment]
**Thank you very much!**

But...
> If you are QuickEdit user, then you should know about it.

Is it true?! https://github.com/termux/termux-app/issues/1198#issuecomment-517995984

**Comment by xeffyr** [comment]
Yeah, https://github.com/termux/termux-app/issues/1198#issuecomment-517995984 is true. You can't have **direct** (!) access to files.

But only with SAF because Termux implements document provider for it.
