### ISSUE TITLE
ESC button no response with an OTG keyboard

### ISSUE THREAD

**Issue by fornwall** [termux/termux-app#120]
_From @t123yh on July 26, 2016 0:28_

I'm using vim with a physical keyboard. However, the ESC button is not responding. Is that implemented? How can I debug or help to debug?

_Copied from original issue: termux/termux-packages#368_

**Comment by fornwall** [comment]
Could you use the app https://play.google.com/store/apps/details?id=com.sonelli.keywatcher and press Escape and attach the output?

**Comment by t123yh** [comment]
Date: Wed Jul 27 08:55:20 GMT+08:00 2016
Device Manufacturer: motorola
Device Model: XT1095
Device Board: MSM8974
Device Bootloader: 0x6016
Android Version: REL 6.0.1 (sdk:23)

*** Key Event Detected ***
Key Code: 111
Action: 0
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 7

*** Key Event Detected ***
Key Code: 111
Action: 1
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 7

**Comment by fornwall** [comment]
@t123yh Thanks for the information! Could you try creating the file `$HOME/.termux/termux.properties` and add the line

    back-key=escape

there, run `termux-reload-settings` and see if that makes a difference?

Otherwise,

- Key Code: 111 is `KeyEvent.KEYCODE_ESCAPE`.
- Action: 0 is `KeyEvent.ACTION_DOWN` followed by Action: 1 - `KeyEvent.ACTION_UP`.

Looks ok, so I wonder what the problem is.

**Comment by fornwall** [comment]
@t123yh Does the `v0.38` update make a difference?

If not, could you try the `back-key=escape` configuration shown above?

**Comment by t123yh** [comment]
Solved in 0.38, thanks.

**Comment by fornwall** [comment]
@t123yh Great, thanks! Did that require the `back-key=escape` configuration or did it work without having to do that?

**Comment by t123yh** [comment]
No, I haven't changed anything.
