### ISSUE TITLE
No shell on start

### ISSUE THREAD

**Issue by victor-yarema** [termux/termux-app#1201]
Sometimes (10% of cases) when I just start Termux it creates a new initial session tab/window and then it doesn't show anything related to new instance of interactive login shell. I guess that the shell is not being started at all in those cases. Here's the screenshot
![Screenshot_20190805-093929](https://user-images.githubusercontent.com/4112846/62461689-c24efa80-b785-11e9-81c1-f5bef845010a.png)

Interesting fact: it does echo what I type. Hotkeys like Ctrl+D and Ctrl+C are being just echoed back.

Steps to reproduce.
- Make sure Termux is not running.
- Start Termux.

Actual behavior.
- Sometimes (I'd say 10% of cases) I can't see login interactive shell in new session right after start.

Expected behavior.
- Termux start a new session with login interactive shell.

u0_a19 @ localhost 0 ~ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.131-ga2426c4f8f23 #1 SMP PREEMPT Fri May 10 20:32:26 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Google
Device model:
Pixel XL
u0_a19 @ localhost 0 ~

**Comment by xeffyr** [comment]
> Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main

> Android version:
9

Have you tried to erase application data or reinstall app ? You are using repositories for android 5.

**Comment by victor-yarema** [comment]
@xeffyr , no I didn't try to clean things up. I will try it later. I need some time to backup few things (or at least check if I need those) here and there.
Thanks for advice.
