### ISSUE TITLE
Broken pipe with ssh

### ISSUE THREAD

**Issue by meaz** [termux/termux-app#1204]
I have a small problem with termux. When I'm connected to my server with ssh, if I switch to another app, even for a couple of seconds, then I loose the connection and I have a message saying "broken pipe".

How can I fix that?

**Comment by xeffyr** [comment]
Seems your OS has "aggressive powersaving".

Try to enable wakelock (via button in Termux notification) and exclude Termux from battery optimizations via Android settings (if you have such).

**Comment by hangya** [comment]
For me setting `IPQoS throughput` in my .ssh/config helped.

**Comment by meaz** [comment]
@hangya thanks a lot, but it doesn't work for me.

**Comment by gprakosa** [comment]
Hi @meaz ,

In Android 10, I manage it by swipe down Notification Center and click "ACQUIRE WAKELOCK".

![IMG_20200320_055950](https://user-images.githubusercontent.com/6815935/77118820-0e7a5100-6a70-11ea-985c-8e68c5ded15f.jpg)

Then you may click "RELEASE WAKELOCK" when finish.
