### ISSUE TITLE
Apt update doesn't resolve properly when using Orbot's transproxy

### ISSUE THREAD

**Issue by SergeantBiggs** [termux/termux-app#121]
Apt update doesn't work when you proxy it through tor (using orbot's transparent proxy). This is the error message you get:
apt update
Ign:1 http://termux.net stable InRelease
Err:2 http://termux.net stable Release
  403  Forbidden
Reading package lists... Done
E: The repository 'http://termux.net stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
After disabling tor, everything works perfectly.

**Comment by fornwall** [comment]
Do you get a `403 Forbidden` if you access http://termux.net/dists/stable/Release with this proxy? Any idea why?

**Comment by SergeantBiggs** [comment]
I just acessed it with my normal browser, again using tor. I didn't get any error and I could download the file without any problems. I have no idea why this is.

**Comment by fornwall** [comment]
This should be fixed now - it was a problem on the server end causing captchas to be showed for Tor connections.

**Comment by dsvenky** [comment]
How to solve this trouble
