### ISSUE TITLE
supervisor

### ISSUE THREAD

**Issue by shenhai1120** [termux/termux-app#1211]
![image](https://user-images.githubusercontent.com/16817929/62908991-43714780-bdad-11e9-8cbb-1ebc91d4ff5d.png)

How to solve it？
i use termuxapp73 in Samsung note9

**Comment by Grimler91** [comment]
You need to patch it to use symlink instead, as done for example here: https://github.com/termux/termux-packages/blob/68892549829968117716e907f3c21183fa0c6f48/packages/ranger/ranger-core-actions.py.patch
