### ISSUE TITLE
Termux in the Kali NetHunter App Store

### ISSUE THREAD

**Issue by Re4son** [termux/termux-app#1213]
I am a big fan of Termux and would love to add it to our NetHunter App Store.
The App Store is based on F-Droid and dedicated to apps that are used in the security field:

[https://www.kali.org/news/kali-nethunter-app-store/](https://www.kali.org/news/kali-nethunter-app-store/)

Would you mind if we added Termux to the store?

It won't cause you any additional work, we'll monitor your repo and rebuild whenever new versions are ready for release.

We also offer a staging environment where you could share new versions with beta testers before rolling it out.

Would love to hear back from you.

Thanks heaps,
Re4son on behalf of the NetHunter team

**Comment by xeffyr** [comment]
I'm okay with adding Termux to NetHunter App Store. Waiting feedback from @fornwall and @Grimler91, though I guess they won't mind too.

**Comment by Grimler91** [comment]
The more spread the better, so sounds great :+1:

**Comment by Re4son** [comment]
Awesome, thanks heaps.
It's in staging now:
https://staging.nethunter.com/en/packages/com.termux/

About to be pushed to https://store.nethunter.com/

**Comment by xeffyr** [comment]
@Re4son Would it be possible to include Termux add-ons too ?

* https://github.com/termux/termux-api
* https://github.com/termux/termux-boot
* https://github.com/termux/termux-styling
* https://github.com/termux/termux-widget
* https://github.com/termux/termux-float
* https://github.com/termux/termux-tasker

Termux add-ons expect that are signed with same signature (use shared user id). If people are installing Termux app from Nethunter Store, they won't be able to install add-ons from different source.

**Comment by Re4son** [comment]
Will do it right now. Thanks for letting me know.
