### ISSUE TITLE
compile swoole

### ISSUE THREAD

**Issue by shenhai1120** [termux/termux-app#1214]
installed gcc-8
i want to compile swoole then i do this:

1. ln -s ../bin/gcc-8 ../bin/cc
2. ln -s ../bin/gcc-8 ../bin/gcc
3. ./configure

result
![image](https://user-images.githubusercontent.com/16817929/63020021-86c3d700-becf-11e9-88ca-22c1f794770f.png)

How to solve it?

**Comment by xeffyr** [comment]
1. GCC isn't officially supported.

2. Check the `config.log` file generated by `./configure`. It long, but contains answer to what caused your problem.

**Comment by xeffyr** [comment]
Seems like you just incorrectly created gcc symlinks.

**Comment by shenhai1120** [comment]
termux-gcc，redhat-gcc , linux-gcc
I don't know the difference between them.
i stop trying
