### ISSUE TITLE
Error after updating to 0.73 via official f-droid app

### ISSUE THREAD

**Issue by smith901** [termux/termux-app#1215]
I get this error message when launching Termux after upgrading from 0.72 to 0.73. Cannot downgrade within f-droid or manually installing:
`CANNOT LINK EXECUTABLE "cat": library "/data/data/com.termux/files/usr/lib/libiconv.so" not found
Aborted
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": cannot locate symbol "nl_langinfo" referenced by "/data/data/com.termux/files/usr/lib/libreadline.so.7.0"...`

`[Process completed (signal 6) - press Enter]`

Manually installing 0.72 gives app is corrupt even when downloaded directly: [https://f-droid.org/repo/com.termux_72.apk](url).

Have not tried the Play store version as installing thru f-droid is how I first came across app & I forgot how I setup Termux initially. I only remember it was a pain & I failed to put the commands in a script.

App will launch in failsafe mode but errors on simple commands that always worked before:
`BLU_Vivo_XL2:/data/data/com.temux/files/home $ pkg
sh: pkg: not found
127|BLU_Vivo_XL2:/data/data/com.termux/files/home $ apt-get
sh: apt-get: not found
127|BLU_Vivo_XL2:/data/data/com.termux/files/home $`

### Hardware
- model.: BLU Vivo XL2
- abi : arm64-v8a
- processor : AArch64 Processor rev 3 (aarch64)
- version : 7.0
- build number : NDR90M
- sdk : 24
- vm : ART
- kernel : 3.18.35

**Comment by Grimler91** [comment]
Easiest fix would be to run `rm -rf $PREFIX` from a failsafe session and then restart termux. This will remove all installed packages and re-download the essential packages, so you will need to re-install all installed packages unfortunately. Your files in $HOME will be left intact though

**Comment by smith901** [comment]
@Grimler91 Thanks, glad I don't sleep much. 
Didn't want to reinstall/setup everything but was intrigued that `rm -rf` would solve the problem so I did. Back up and running, found a script I started when setting up Termux.
