### ISSUE TITLE
Can't update or upgrade termux

### ISSUE THREAD

**Issue by MrNobodyTharusha** [termux/termux-app#1223]
When I type pkg update , pkg upgrade or pkg install <pakage> it shows,

$ pkg update
Hit:1 https://termux.net stable InRelease
Ign:2 https://hax4us.github.io/termux-tools termux InRelease
Ign:3 https://hax4us.github.io/termux-tools termux Release
Ign:4 https://hax4us.github.io/termux-tools termux/extras aarch64 Packages
Ign:5 https://hax4us.github.io/termux-tools termux/extras all Packages
Ign:4 https://hax4us.github.io/termux-tools termux/extras aarch64 Packages
Ign:5 https://hax4us.github.io/termux-tools termux/extras all Packages
Ign:4 https://hax4us.github.io/termux-tools termux/extras aarch64 Packages
Ign:5 https://hax4us.github.io/termux-tools termux/extras all Packages
Ign:4 https://hax4us.github.io/termux-tools termux/extras aarch64 Packages
Ign:5 https://hax4us.github.io/termux-tools termux/extras all Packages
Err:4 https://hax4us.github.io/termux-tools termux/extras aarch64 Packages
  404
Ign:5 https://hax4us.github.io/termux-tools termux/extras all Packages
Ign:6 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:7 https://dl.bintray.com/grimler/termux-root-packages-21 root InRelease
Ign:8 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Ign:9 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable InRelease
Ign:10 https://dl.bintray.com/xeffyr/x11-packages-21 x11 InRelease
Get:11 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:11 https://dl.bintray.com/grimler/game-packages-21 games Release
Get:13 https://dl.bintray.com/grimler/termux-root-packages-21 root Release [6185 B]
Hit:13 https://dl.bintray.com/grimler/termux-root-packages-21 root Release
Get:15 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:15 https://dl.bintray.com/grimler/science-packages-21 science Release
Get:17 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release [6065 B]
Hit:17 https://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release
Get:19 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release [6055 B]
Hit:19 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release
Err:21 https://termux.xeffyr.ml extra InRelease
  Connection timed out after 120000 milliseconds
Reading package lists... Done
W: Failed to fetch https://termux.xeffyr.ml/dists/extra/InRelease  Connection timed out after 120000 milliseconds
E: Failed to fetch https://hax4us.github.io/termux-tools/dists/termux/extras/binary-aarch64/Packages  404
W: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (main/binary-aarch64/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:2 and /data/data/com.termux/files/usr/etc/apt/sources.list.d/xeffyr.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:2 and /data/data/com.termux/files/usr/etc/apt/sources.list.d/xeffyr.list:1
W: Target Packages (x11/binary-aarch64/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:2 and /data/data/com.termux/files/usr/etc/apt/sources.list.d/xeffyr.list:1
W: Target Packages (x11/binary-all/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:2 and /data/data/com.termux/files/usr/etc/apt/sources.list.d/xeffyr.list:1
$

**Comment by MrNobodyTharusha** [comment]
Help me please....

**Comment by xeffyr** [comment]
Fix your sources.list files by removing repositories that doesn't work. Specifically remove https://hax4us.github.io/termux-tools/ and https://termux.xeffyr.ml/.

https://termux.xeffyr.ml/ IS NOT SAFE FOR USE AT ALL !!! **It is no longer controlled by me** (unlike its name)  and can contain whatever possible. For now it redirects to http://tpbay.ga, but one day it can be used for serving malware.
