### ISSUE TITLE
Termux error code 11

### ISSUE THREAD

**Issue by uknow89** [termux/termux-app#1229]
I've been trying to get termux up and going in a virtual app called vmos on a verizon note 9 but as soon as I open termux I get 

[Process completed (signal 11)  - press enter]

But if I press enter it just forecloses the app any help will be great PS I'm a noon when it come to code

**Comment by xeffyr** [comment]
This is VMOS bug and not Termux's one.

**Comment by xeffyr** [comment]
While VMOS offers "virtualised android", it's "virtualisation" isn't perfect.
