### ISSUE TITLE
termux-setup-storage isn't recognizing external SD Card

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-app#123]
Hi, I just got a new phone (Sony Xperia X) and`termux-setup-storage` doesn't create the `~/storage/external` symlink for my external sd card. The sd card is mounted as  `/storage/3331-3532`. Otherwise everything with the sd card seems to work. I even have write permissions to `/storage/3331-3532/Android/data/com.termux/files`

**Comment by fornwall** [comment]
Does it work if you `rm -Rf ~/.storage` and run `andtermux-setup-storage` again, with an `external-1` or `external-2` folder being setup pointing to the external sd card?
