### ISSUE TITLE
termux rw to root lmao

### ISSUE THREAD

**Issue by thomasths27** [termux/termux-app#1230]
Hi i don't thinks this is necessarily a problem with termux but more like a "funny" bug that let my heart skip two beats.

I am running a unrooted custom rom (that also has se-linux disabled).
I installed termux.
Did " ls / "
Got the contents of my system root.
hmm ok tried "rm -rf / " hmm "file system read only"
ran "pkg install openssh"

**ssh installed it self to my read only system partiton**

I took a look at via twrp and adb and jes /etc/sshd/ssh... stuff exists and is persistent.
This is probably some fuck up on my end but still very funny.

**how** 

**Steps to reproduce**

- Get a s7

- install lineage os unoffical by ivan meier (btw i reported this to him already and this github issue is just for shits and giggles) 

- install termux

- profit

**Expected behavior**
well 

**Additional information**
i am running a s7 adoptable storage, work profile, encryption.

**Comment by Grimler91** [comment]
> ssh installed it self to my read only system partiton

And how did you verify this?

/etc/sshd/sshd_config wasn't created by `pkg install openssh`, your ROM probably has a system-installed openssh.

**Comment by thomasths27** [comment]
> > ssh installed it self to my read only system partiton
> 
> And how did you verify this?
> 
> /etc/sshd/sshd_config wasn't created by `pkg install openssh`, your ROM probably has a system-installed openssh.

simple. i wiped system flashed the rom took a look with adb 
no ssh no nano 
installed termux pkg install nano sshd
and another look with adb

**Comment by Grimler91** [comment]
Well sure, post the logs and screenshots. `pkg`/`apt` doesn't work like this anyways, it doesn't install software to the wrong, read-only folder so the nano and ssh that you find in adb must come from somewhere else, or not reside in the system folder

**Comment by thomasths27** [comment]
[2019-08-28_16.33 (2).zip](https://github.com/termux/termux-app/files/3556655/2019-08-28_16.33.2.zip)
![photo_2019-08-29_19-08-24](https://user-images.githubusercontent.com/12694195/63961285-bad2f680-ca90-11e9-9d92-4c72fc6a80a4.jpg)
![photo_2019-08-29_19-08-29](https://user-images.githubusercontent.com/12694195/63961286-bad2f680-ca90-11e9-92c8-5baeb20dc327.jpg)
![photo_2019-08-29_19-08-33](https://user-images.githubusercontent.com/12694195/63961287-bb6b8d00-ca90-11e9-8c31-8b0e4ecbd35d.jpg)

**Comment by thomasths27** [comment]
> Well sure, post the logs and screenshots. `pkg`/`apt` doesn't work like this anyways, it doesn't install software to the wrong, read-only folder so the nano and ssh that you find in adb must come from somewhere else, or not reside in the system folder

if there is any thing special i can provide or should look for please ask

**Comment by thomasths27** [comment]
btw i found this issue when i actually tied editing the sshd config and got permission denied read only file system

**Comment by Grimler91** [comment]
Your `pkg install openssh` screenshot looks normal (files are put in /data/data/com.termux/files/usr/etc/), so I still believe the /bin/ssh* files are from your ROM. 

I can't see anything weird here. If you really want to verify it you could always reinstall the ROM, not install termux and check the content of /bin again.

**Comment by thomasths27** [comment]
> Your `pkg install openssh` screenshot looks normal (files are put in /data/data/com.termux/files/usr/etc/), so I still believe the /bin/ssh* files are from your ROM.
> 
> I can't see anything weird here. If you really want to verify it you could always reinstall the ROM, not install termux and check the content of /bin again.

i did like i wrote in my initial comment. But i will try a second time just to be save. Did you spot something unusual in the logs ?
https://github.com/termux/termux-app/files/3556655/2019-08-28_16.33.2.zip

**Comment by thomasths27** [comment]
ok the issue is on my end sorry.
the bin folder is not there right after rom install but after the first boot everything including nano and ssh is there.

i think this cleared things up for me
thanks
