### ISSUE TITLE
Problem about the bootstraps-xxx.zip

### ISSUE THREAD

**Issue by ljd1996** [termux/termux-app#1231]
What is the difference between bootstraps in phones larger than Android7 and smaller than Android7? I need to recompile the corresponding bootstrap for different package names such as ”com.test“. Now the compiled bootstrap can be used in mobile phones larger than Android 7. How can I compile the bootstrap below Android 7? Please help me! Thanks.

**Comment by Grimler91** [comment]
The packages in the android-5 bootstraps are built from the android-5 branch in termux-packages while the android-7 bootstraps are built from the master branch.

**Comment by ljd1996** [comment]
> The packages in the android-5 bootstraps are built from the android-5 branch in termux-packages while the android-7 bootstraps are built from the master branch.

Thank you!
