### ISSUE TITLE
Is it possible to launch Bluetooth through terminal?

### ISSUE THREAD

**Issue by seisdr** [termux/termux-app#1232]

**Comment by Grimler91** [comment]
Not sure what `launch bluetooth` means, but we don't have a bluetooth API so no.

See the feature requests: https://github.com/termux/termux-api/search?q=bluetooth&type=Issues

**Comment by seisdr** [comment]
Activate Bluetooth

**Comment by seisdr** [comment]
am start Manifest.permission.BLUETOOTH
This way?

**Comment by Grimler91** [comment]
This stackexchange answer might help you: https://stackoverflow.com/a/55064471
