### ISSUE TITLE
Problem with binary files

### ISSUE THREAD

**Issue by Awakened-Redstone** [termux/termux-app#1239]
**Problem description**
When I try to run some binary files I get ˋNo such file or directoryˋ

**Steps to reproduce**
1. Open Termux
2. Run ˋ/bin/restoreconˋ
  :x: It returns ˋbash: /bin/restoreconˋ

**Expected behavior**
It should run ˋrestoreconˋ command

**Additional information**

**Comment by xeffyr** [comment]
> /bin/restorecon

Use `/system/bin/restorecon` instead.

1. There no directory `/bin`.
2. Termux doesn't provide restorecon binary on its own.

**Comment by Awakened-Redstone** [comment]
![Screenshot_20190906-204309_Termux](https://user-images.githubusercontent.com/40528665/64466216-0d429180-d0e7-11e9-88b6-3f764da55dd1.jpg)

**Comment by Awakened-Redstone** [comment]
I took a while to upload the image.
It was supposed to run the bash that is at ubuntu-fs

**Comment by xeffyr** [comment]
You didn't mentioned that you are trying to run command under proot. However, `/bin/restorecon` isn't available here anyway.

Regarding screenshot, try to remove `-b ubuntu-fs/bin`.

**Comment by Awakened-Redstone** [comment]
Yeah. The original one is without it.
I don't understand why...
It was a script, but than I ran it on a command style

**Comment by Awakened-Redstone** [comment]
I'm trying to run ubuntu to use IntelliJ IDE on my phone
