### ISSUE TITLE
Press Enter To Close no longer works

### ISSUE THREAD

**Issue by metatribal** [termux/termux-app#124]
In the most recent update, 'quit' displays the 'press enter to close' statement, buy pressing enter again doesn't terminate the session.

**Comment by metatribal** [comment]
Termux v0.35 (2016-08-01)

**Comment by metatribal** [comment]
Update:. The enter key in hackers keyboard works fine, but the enter key on the stock Google keyboard does not.

**Comment by metatribal** [comment]
Update:  Hacker's Keyboard every only works when the new extra key row is NOT being displayed.

Sorry about all the comments, my client doesn't allow editing connects

**Comment by fornwall** [comment]
Thanks - this was indeed a regression with some keyboards, and should be fixed by the `v0.37` update which has been released and should be available as an update in Google Play and F-Droid shortly!

**Comment by metatribal** [comment]
This fixed the case where the extra key row is NOT displayed, but still
does not work when using the stock Google keyboard and the key row IS
displayed.

As an aside, it would be great to be able to customize the extra key row.

**Comment by metatribal** [comment]
Actually, when it doesn't work is when the prediction typing row is open.

It works as expected when the ESC/CTRL/ALT row is displayed.

The behavior I'd expect is when the 'press enter to close' msg is
displayed, pressing enter with an empty line in the prediction row would
terminate the session.

Thanks.

**Comment by fornwall** [comment]
> Actually, when it doesn't work is when the prediction typing row is open.

Aha - thanks, I'll fix that shortly as well!

**Comment by fornwall** [comment]
> Actually, when it doesn't work is when the prediction typing row is open.

Please try out the updated version `0.38` which should fix this issue!

It should be available as an update on F-Droid and Google Play shortly.
