### ISSUE TITLE
Input text issues with Samsung Android Keyboard (input text changes after pressing Enter)

### ISSUE THREAD

**Issue by arigit** [termux/termux-app#1241]
I'm opening this issue for people searching for solutions to a weird issue with termux that has bugged me for several months.

This is with a Samsung S10 device (Android 9) with stock firmware (kept up to date), that was using the Samsung Keyboard (configured with multiple input keyboards)

It may help others landing here.

Issue description: in termux, login to some server, and type in some command partially and then press "TAB" to get it to auto-complete, and you get the command you want to issue, such as:

```
cd .homeassistant
```
Then press enter. Even if you know that the command is OK and should succeed, you get a weird error as if you had made a typo:

```
~bash: cd: .homeassithom: No such file or directory
```

So you press the up arrow, which strangely shows that there was a typo (from bash's point of view), you correct it, and press enter, and again the same issue, perhaps with some different typo. You keep retrying and the command eventually succeeds.
The issue started out of the blue a few months ago. 

I tried many things, as I thought the problem could be with bash 'autocomplete' (but log in to the same server from other computers did not show this issue), then I wiped termux and all its config and re-installed it, and over time tried many other changes - to no avail.

At one point I suspected of the Samsung Keyboard auto-complete and "predictive input" features and disabled all of them. The frequency of the issue decreased a bit in the beginning (placebo?) but eventually it made no difference.

Google searches and github searches here did not show anything useful.

Eventually, I found this:  https://github.com/termux/termux-packages/issues/992
However, the 'workaround' described there did not help or apply to my use case as I was already using the English layout.

Solution: install another keyboard such as the popular Gboard (google's keyboard) which I incidentally found much better than Samsung's. Even with predictive suggestions and corrections turned on, Termux issues are all gone.

**Comment by arigit** [comment]
Closing the issue - per the initial comment this is NOT a Termux problem but a Samsung Keyboard issue.

**Comment by russglen78** [comment]
> Closing the issue - per the initial comment this is NOT a Termux problem but a Samsung Keyboard issue.

**Granted**, the only time this "Typo error" occurs in Termux is when using the "Samsung" Keyboard.
**This IS NOT a _Samsung Keyboard issue_.**
》This problem does not occur any other time using the Samsung Keyboard. 
》The only time this issue occurs is in Termux.



I know when one is granted with the Authority to Close Issues in github one becomes quick to close issues.
HOWEVER, you are mistaken when you stated this is not a termux issue, rather a Samsung keyboard issue

**Comment by kcubeterm** [comment]
@russglen78 if you have issues. here's a workaround 
https://wiki.termux.com/wiki/Terminal_Settings

**Comment by xeffyr** [comment]
@russglen78 This is bug of Samsung keyboard - it doesn't handle properly generic input.
