### ISSUE TITLE
App not updated on F-Droid

### ISSUE THREAD

**Issue by ameer1234567890** [termux/termux-app#1244]
Termux app, as well as termux-api app are not updated on F-Droid. Termux remains a version behind and termux-api several veraions behind at F-Droid

**Comment by xeffyr** [comment]
According to https://f-droid.org/wiki/page/com.termux/lastbuild, Termux app was built on F-Droid. Just it is not published immediately (may take 1-3 days unless F-Droid has issues).

**Comment by xeffyr** [comment]
Regarding Termux:API (https://f-droid.org/wiki/page/com.termux.api/lastbuild), there seems bad things happened. F-Droid failed to checkout it from Github.
