### ISSUE TITLE
No keep  current screen 

### ISSUE THREAD

**Issue by cDQK** [termux/termux-app#1245]
Like ffmpeg running output, sliding the screen and always beating to the latest output, I hope it shows the old output display

**Comment by RlZkhere** [comment]
If you dont' have set DISPLAY:=* option , it's normale that you find this errore , set DISPLAY and relaunch

**Comment by RlZkhere** [comment]
If you dont' have set DISPLAY:=* option , it's normale that you find this errore , set DISPLAY and relaunch

**Comment by fornwall** [comment]
Closing as duplicate of #1242.
