### ISSUE TITLE
How do I know what version of termux I'm running on my ChromeBook?

### ISSUE THREAD

**Issue by petjal** [termux/termux-app#1246]
Thanks for a great product!  I just got keybase installed in termux on my chromebook and it works great!

**Feature description**
Describe the feature and why you want it.

On a chromebook.  How do I get the termux version number?  Either a right-click on the icon, or from the termux command-line with something like:
termux --version
termux --help

**Reference implementation**
Does another app/terminal emulator have this feature?
Provide links to more background information

I can get it from Google Play Store (0.75, Sep 8, 2019).

I did a quick search of this github repo for a command-line option, but couldn't find anything, but I didn't really look that hard. 

find TermuxArch/ -type f | xargs grep "v0\.7" | cat -A | less
gives me a lot of 0.7s, but not 0.75.

**Comment by Harshiv-Patel** [comment]
Since app versions are declared in AndroidManifest.xml file,
Take a backup of Termux apk from `/data/app/com.termux` or it's equivalent directory and read it's AndroidManifest.xml with an app or program that can convert binary data of compiled xml to human readable format.

**Comment by petjal** [comment]
Thanks for the reply.  Here's what I got (no apparent 0.7x):
```
  129  find /data/data/com.termux/ -iname "*.apk"
  131  pkg install zip
  134  pkg install binutils
  135  unzip -p /data/data/com.termux/files/usr/libexec/termux-am/am.apk AndroidManifest.xml | strings -n 1 | head
  136  unzip -p /data/data/com.termux/files/usr/libexec/termux-am/am.apk META-INF/MANIFEST.MF | strings -n 1 | head
  139  pkg install file
  140  unzip -p /data/data/com.termux/files/usr/libexec/termux-am/am.apk META-INF/MANIFEST.MF | file -
  143  pkg install aapt
$ aapt l -a /data/data/com.termux/files/usr/libexec/termux-am/am.apk
AndroidManifest.xml
META-INF/MANIFEST.MF
classes.dex
resources.arsc

Android manifest:
N: android=http://schemas.android.com/apk/res/android
  E: manifest (line=2)
    A: android:versionCode(0x0101021b)=(type 0x10)0x1
    A: android:versionName(0x0101021c)="0.1" (Raw: "0.1")
    A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
    A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
    A: package="com.example.termuxam" (Raw: "com.example.termuxam")
    A: platformBuildVersionCode=(type 0x10)0x1c
    A: platformBuildVersionName=(type 0x10)0x9
    E: uses-sdk (line=7)
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0x15
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1b
    E: application (line=11)
      A: android:label(0x01010001)="TermuxAm" (Raw: "TermuxAm")
      A: android:supportsRtl(0x010103af)=(type 0x12)0xffffffff
```

**Comment by Harshiv-Patel** [comment]
What you have discovered with this `grep`ping is information about a sup package of Termux called `Termux-AM`.
In your question, you have asked the version of Termux (the app you installed from play store/app store).

You can try and run `termux-info` which would get you some information about installed packages and device information.

Please confirm and the Termux-App version is what you seek first.

**Comment by petjal** [comment]
Thanks again.   Thought so, but that was the only apk I could "find". 
I just upgraded to 0.84 (as shown in Play Store).
Still no indication of version from within termux, as far as I can tell. 
```
$ find /data/data/com.termux -iname "*apk*"
/data/data/com.termux/files/usr/libexec/termux-am/am.apk
$ termux-info
Packages CPU architecture:
i686
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.0-19748-gc785fae00b84 #1 SMP PREEMPT Thu Nov 14 23:15:39 PST 2019 i686 Android
Device manufacturer:
Google
Device model:
Acer Chromebook 14 for Work (CP5-471)

$ termux-info --help
usage: termux-info
Provides information about Termux, and the current system. Helpful for debugging.
```

**Comment by Harshiv-Patel** [comment]
Perhaps it's better to ask devs to include a build number and version info within the `termux-info` wrapper, than to manually parsing AndroidManifest.

**Comment by buttaface** [comment]
Finally fixed in termux-info, though it will only work for Termux 0.107 or later, termux/termux-packages#6547.
