### ISSUE TITLE
Building Flutter crashes Termux

### ISSUE THREAD

**Issue by NatoBoram** [termux/termux-app#1247]
**Problem description**

Termux crashes when trying to build `flutter`.

**Steps to reproduce**

```sh
# Dependencies
pkg install git dart-sdk

# Flutter
mkdir ~/Applications
cd ~/Applications
git clone git@github.com:flutter/flutter.git
```

Add the following to `~/.profile`

```sh
# Flutter
export "$HOME/Applications/flutter/bin:$PATH"
```

Restart Termux via `exit`.

```sh
flutter
cp -fr ~/../usr/lib/dart-sdk ~/Applications/flutter/bin/cache/
flutter
```

**Expected behavior**

Something wrong *probably* happens. However, I don't think Termux should be crashing.

**Additional information**

Related to https://github.com/flutter/flutter/issues/35933

```
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/unstable-packages-24 unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.165-gfff483291c07-ab5725533 #0 SMP PREEMPT Fri Jul 12 22:55:38 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
10
Device manufacturer:
Google
Device model:
Pixel 3
```

**Comment by Grimler91** [comment]
Have you forgotten to paste the crash? Or what do you mean with that it crashes?

**Comment by xeffyr** [comment]
> cp -fr ~/../usr/lib/dart-sdk ~/Applications/flutter/bin/cache/

I'm unsure if dart-sdk can be copied in such way.

**Comment by xeffyr** [comment]
Probably these errors ?
```
$ flutter doctor
Building flutter tool...
Failed to precompile build_runner:graph_inspector:

Failed to precompile build_runner:build_runner:
```
I also noticed that my device running out of memory when running `flutter doctor`.

***

Applied this patch to disable downloading of dart sdk:
```
diff --git a/bin/flutter b/bin/flutter
index 6579b643e..c42bada20 100755
--- a/bin/flutter
+++ b/bin/flutter
@@ -111,7 +111,6 @@ function upgrade_flutter () {
   if [[ ! -f "$SNAPSHOT_PATH" || ! -s "$STAMP_PATH" || "$(cat "$STAMP_PATH")" != "$revision" || "$FLUTTER_TOOLS_DIR/pubspec.yaml" -nt "$FLUTTER_TOOLS_DIR/pubspec.lock" ]]; then
     rm -f "$FLUTTER_ROOT/version"
     touch "$FLUTTER_ROOT/bin/cache/.dartignore"
-    "$FLUTTER_ROOT/bin/internal/update_dart_sdk.sh"
     VERBOSITY="--verbosity=error"
 
     echo Building flutter tool...
```

**Comment by NatoBoram** [comment]
Oh, thanks for looking into it!

Looks like I'll need to build it on an emulator or something to continue my stupid experiment, lmao.

**Comment by mukhtharcm** [comment]
Did you git it working? @NatoBoram

**Comment by NatoBoram** [comment]
Latest command to copy `dart-sdk` :

```bash
cp /data/data/com.termux/files/usr/lib/dart-sdk ~/Applications/flutter/bin/cache/ -r
```

Unfortunately, this time I get : 

```log
Building flutter tool...
The current Dart SDK version is 2.7.2.

Because flutter_tools depends on test
  >=1.16.0-nullsafety which requires SDK version
  >=2.10.0-0 <2.10.0, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

It looks like the package `dart` is outdated. I tried to build it, but it is ridiculously difficult to build for no good reason. Google *really* fucked up while building Dart, honestly.

**Comment by mukhtharcm** [comment]
@NatoBoram is this PR https://github.com/flutter/buildroot/pull/390 is to your same goal?

**Comment by NatoBoram** [comment]
It seems like that one is about "cross-building for ARM64" while I'm looking for "building *on* ARM64*

**Comment by Grimler91** [comment]
> It looks like the package dart is outdated. I tried to build it, but it is ridiculously difficult to build for no good reason. Google really fucked up while building Dart, honestly.

We have not been able to re-build dart since we changed the docker image to ubuntu version to 20.04 (or maybe the problem was the ndk r21 update? can't remember), the problem was mostly that darts sdk build system requires python2 in many places, and the newer ubuntu version defaults to python3

**Comment by mukhtharcm** [comment]
@NatoBoram  it's about building the engine for arm64. So if we get the engine builded can't we use flutter in termux?

**Comment by mukhtharcm** [comment]
@NatoBoram they said here https://github.com/flutter/flutter/issues/62672#issuecomment-667234996 that flutter uses a specialised dart SDK. And not the regular one.  
This may be because if that.

**Comment by NatoBoram** [comment]
@Grimler91 One issue I've had is with this piece of gore : 

> IMPORTANT: You must follow instructions for Getting the source before attempting to build. Just cloning a GitHub repo or downloading and unpacking a ZIP of the SDK repository would not work.

The thing is `fetch dart` hangs forever then crashes, so I can't even run `python2 ./tools/build.py`. I'm sure there's many problems down the road I've yet to face, as with any programs using outdated dependencies and trying to bypass proper Git usage with their own smartass in-house legacy build tools.

I'm so disappointed that they've decided that making it impossible to build was the logical solution. It's such a radical change from the very simple build process of Go.

**Comment by iCodeShit** [comment]
If you need more ram and hardisk for building use arm64 virtualization in google freeshell with docker qemu / qemu, google colab and qemu, github actions with qemu/docker. I'm looking into using flutter from termux too. Colab vm offer 75 gb hdd, 15gb ram. Github and Google free shell allow using docker too.

**Comment by lycstar** [comment]
![Screenshot_2021-02-05-23-26-35-301_com termux](https://user-images.githubusercontent.com/37872392/107053631-fd623c00-6809-11eb-8a39-d6fedb2ad0ac.jpg)
I want to try to compile android app with flutter in termux. First, need to compile the dart SDK for Android, and then need to modify the flutter tools to support Android host. But to complete this,  most important of all is need to modify the build script and the flutter engine tools, gradle tools, and Android build tools which can run under termux.

**Comment by sinojelly** [comment]
@lycstar How you modified flutter to support android host? Could you fork a flutter project, so we can refer and contribute to it.
I have installed dart & flutter on VHEditor ( Termux based VSCode), now I can edit dart files on android pad, but also can not compile it. There is a dart package in termux package, so we can install dart by using pkg install dart.

**Comment by CrazyMan-IK** [comment]
@lycstar Could you please leave a link to the modified version?

**Comment by sinojelly** [comment]
@CrazyMan-IK I have modified a version to run on android host, only comment out the unwanted code on android host.
https://gitee.com/sinojelly/Flutter/tree/stable/

**Comment by CrazyMan-IK** [comment]
@sinojelly I get the same error as with the official flutter "Error: Unable to 'pub upgrade' flutter tool", I know that this is due to the incompatibility of the x86_64 file and aarch64. Apparently you will have to manually compile dart_sdk

**Comment by lycstar** [comment]
There are many problems for dart sdk in android. for ex, pub download package will show untar failure. And there is a problem need to repair in dart sdk source, you can refer to my git action here[https://github.com/lycstar/build_dart_android_arm64_sdk/blob/c0807612b16d9f8f7334699e5e6a655a4a42b0b3/.github/workflows/main.yml#L28]()
