### ISSUE TITLE
Termux shortcut to launch 2 apps in split screen 

### ISSUE THREAD

**Issue by deftdawg** [termux/termux-app#1252]
**Feature description**
Be able to open 1 app using Termux-open, and then split screen and load a second app.

**Reference implementation**
I was just playing with Termux-open today and I can launch a stream which opens in VLC from one of my home security cameras.   I've now mapped that to a shortcut:

```bash
#!/data/data/com.termux/files/usr/bin/env bash

CAMERA=Camera1
TIMEOUT=300ms
(ncat -w ${TIMEOUT} -zv ${CAMERA} 554 2>/dev/null && termux-open rtsp://${CAMERA}:554/unicast) || echo "Camera not found at rtsp://${CAMERA}:554/unicast"
```

Was thinking it would be nice, if I could pull up a second app to control a door lock or house lights in split screen mode.   Right now I'm doing it manually when I want that.

This maybe beyond the scope of Termux, but figured I should ask. 😃

**Comment by OffifialMITX** [comment]
In case you have root access, you should be able to do this using Android's internal API. Maybe even just adb with some luck. As far as I am aware, apps are restricted from manipulating split-screen mode, similar to how they can't launch freeform without special permissions on Android 8+

**Comment by RlZkhere** [comment]
To do this you need to have root permission on your device , because you dont' have permission to run this Android internal API

**Comment by agnostic-apollo** [comment]
You could try [Taskbar](https://play.google.com/store/apps/details?id=com.farmerbb.taskbar), possibly with [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm). It doesn't require root. Closing since not a Termux issue.
