### ISSUE TITLE
If i build this app in android -studio and running as user apps got the following error 

### ISSUE THREAD

**Issue by sravanthi-s** [termux/termux-app#1253]
**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by sravanthi-s** [comment]
If i build this app in android -studio and running as user apps got the following error 
[log23.txt](https://github.com/termux/termux-app/files/3631473/log23.txt)
Can you please provide this app Android.mk to run this has platform app

**Comment by xeffyr** [comment]
> Can you please provide this app Android.mk to run this has platform app

All sources on git (and even under continuous integration & testing).
Also, I don't see any Termux-related error in your log.
