### ISSUE TITLE
Unable to write keyboard commands on Facemoji Keyboard for Xiaomi

### ISSUE THREAD

**Issue by Yanchik0402** [termux/termux-app#1257]
**Problem description**
It is not possible to write commands using the standard Xiaomi keyboard.
For example, when I write "pkg", there is nothing on the screen, after when I put a space or other punctuation marks, then "pkg" appears on the screen.

**Steps to reproduce**
1) Set in input settings "Facemoji Keyboard for Xiaomi"
2) Try to input any command in termux

**Expected behavior**
Normal command input

**Additional information**
$ termux-info
Updatable packages:
bash/stable 5.0.9 aarch64 [upgradable from: 5.0.7-5]
dash/stable 0.5.10.2-2 aarch64 [upgradable from: 0.5.10.2-1]
gawk/stable 5.0.1-4 aarch64 [upgradable from: 5.0.1-3]
libnghttp2/stable 1.39.2 aarch64 [upgradable from: 1.39.1-1]
readline/stable 8.0.1 aarch64 [upgradable from: 8.0-3]
unzip/stable 6.0-5 aarch64 [upgradable from: 6.0-4]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.153-perf-g1bb9020 termux/termux-packages#1 SMP PREEMPT Tue Jul 16 21:49:23 WIB 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
MI 8 Lite

**Comment by x2k13** [comment]
#686
