### ISSUE TITLE
[Feature request] Samsung DeX support.

### ISSUE THREAD

**Issue by DarthZedd** [termux/termux-app#1259]
Hi. I am an active user of Termux on Samsung DeX. The issue is that when the DeX is enabled/disabled the Termux session gets dropped.

Could Termux be updated for DeX usage please? Here is the official source from Samsung on how to adapt the app:

https://developer.samsung.com/samsung-dex/modify-optimizing

Thank you in advance.

**Comment by laem** [comment]
This is the main problem I've found too when trying to use a Galaxy phone as a development machine.

When you're working on it in Dex mode, get a phone call or have a tea, unplug your phone from the monitor, you have to launch termux again to get back to work.

**Comment by nathaneltitane** [comment]
Let's push the envelope even further: can Termux get an integrated VNC Client to run atop what seems to be another great use for this beautiful little application: chroot/proot?

This would surely make Termux the ultimate item in the portable development arsenal :)

**Comment by DarthZedd** [comment]
Using Andronix with Termux opened new opportunities under DeX. Though it still closes session when you detach the phone from DeX compatible hub so all work is lost if you need to make a phone call all of a sudden.

**Comment by DarthZedd** [comment]
For the users of Andronix (or alternatives) + Termux i have found a workaround of sorts.  DeX allows to continue using phone as usual while using dex on the connected monitor. So:

1) Connect your device to monitor to activate DeX 
2) Launch Termux on the PHONE
3) Launch Linux distro in Termux on the PHONE, start VNC server. Minimize Termux.
4) Launch VNC viewer in DEX

This way when you detach the device from DeX Termux session remains intact. When after connecting to DeX again you can re-launch your VNC viewer and you will have your Linux distro in the same spot you left it. 

Though still i beg Termux developers to adapt the app for DeX =)

**Comment by laem** [comment]
Thanks @DarthZedd that's a smart tip !

**Comment by fornwall** [comment]
Fixed by version 0.90 of the app, which has been released and should be available as an update shortly, by @jeansch in #1446.

**Comment by robsmith11** [comment]
Does anyone happen to know if a similar fix is possible for the Huawei Desktop mode (currently using it with a my Mate 20 X on Android 10).  When I disconnect the USB-C monitor, Termux and any running tmux sessions are killed.

**Comment by insign** [comment]
To avoid open a new issue I think the right click should act like a desktop right click. The same for selecting text, middle click. Something like Samsung Browser does.

Same to sessions which should become tabs like Chrome mobile do.

Thank you.

**Comment by nathaneltitane** [comment]
@xeffyr has this ever been fixed?
If it has been (which i think it was, in previous versions) it is now broken again under version 0.117 F-Droid
