### ISSUE TITLE
samsung keyboard no echo

### ISSUE THREAD

**Issue by resfilter** [termux/termux-app#126]
the latest version is broken with the Samsung keyboard if "predictive text" is enabled

if it is, chars are buffered (or in other words not echoed) at the keyboard and are not displayed in the terminal until the word is complete

for example typing "ls" does not display anything until you press space afterwards, at which point "ls " is displayed...

**Comment by Mutantoe** [comment]
This is also an issue on Samsung A3, using default OS.

**Comment by beholders-eye** [comment]
I'm having this same problem with the Samsung Galaxy J2

**Comment by ogerasymenko** [comment]
Meizu M2 Note with TouchPal same issue.

**Comment by fornwall** [comment]
Thanks for reporting - will do the final testing during the next couple of hours, then release an update fixing this issue!

**Comment by fornwall** [comment]
Please try out the updated version `0.38` which should fix this issue!

It should be available as an update on F-Droid and Google Play shortly.

**Comment by resfilter** [comment]
looks good!  thanks so much.  love your app.

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Fredrik Fornwall <notifications@github.com> Date: 2016-08-04  3:00 PM  (GMT-08:00) To: termux/termux-app <termux-app@noreply.github.com> Cc: Steve Haslin <resfilter@resfilter.net>, Author <author@noreply.github.com> Subject: Re: [termux/termux-app] samsung keyboard no echo (#126) 
Please try out the updated version 0.38 which should fix this issue!

It should be available as an update on F-Droid and Google Play shortly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/termux/termux-app","title":"termux/termux-app","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/termux/termux-app"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fornwall in #126: Please try out the updated version `0.38` which should fix this issue!\r\n\r\nIt should be available as an update on F-Droid and Google Play shortly."}],"action":{"name":"View Issue","url":"https://github.com/termux/termux-app/issues/126#issuecomment-237696797"}}}

**Comment by beholders-eye** [comment]
fornwall, this update (0.38) didn't fix the typing issue on my Samsung Galaxy J2. As a workaround I'm disabling, when using tmux, the word prediction feature of Samsung virtual keyboard. Isn't there anything else that should be tested for it to work?

**Comment by NitroNils** [comment]
Issue here as well, never seen before. No change of settings.

_Huawei ALE21_
_Android 6.0_
_Termux 0.65_

PS: I made a .gif to illustrate.

**Comment by bchristie** [comment]
Sorry for bringing back an old post, but appears Note 10+ has this issue as well.

Initial start of the app doesn't show keyboard (only helpers above). Upon restart, it comes back but 'buffers' words until complete (e.g. press space or select completed word from suggestions).

https://imgur.com/a/a3eMrIH

First image shows keyboard absent, second shows my attempt to type `pkg` but until I select from autocomplete it won't display in terminal.

**Comment by Gujs** [comment]
Same issue with Samsung Galaxy Tab S6.

**Comment by zuiko21** [comment]
Same here with Samsung SM-T510 (Galaxy Tab A) after last update.

**Comment by kvacha13** [comment]
Same on galaxy s10+. any fix or upcoming update?

**Comment by miguelPerezOntiveros** [comment]
I switched predictive text off and got the same results. I'm using a Note 10+

**Comment by sebelk** [comment]
Same problem, termux 0.96 on Samsung Galaxy A10s, I wonder why was this issue closed...

**Comment by xeffyr** [comment]
> I wonder why was this issue closed...

\-\-\> https://github.com/termux/termux-app/issues/686, PINNED btw.
