### ISSUE TITLE
How can i add termux to my app

### ISSUE THREAD

**Issue by sohutek** [termux/termux-app#1261]
**Feature description**
I'm really in love with termux. I wonder could i add termux to my app?

**Comment by Grimler91** [comment]
This has pretty much been asked before in https://github.com/termux/termux-app/issues/1124 and https://github.com/termux/termux-app/issues/1059

**Comment by xeffyr** [comment]
2 notes about *embedding Termux*:

1. Termux isn't cloneable. Why, answer in https://github.com/termux/termux-app/issues/1124#issuecomment-487406690.

2. Usage of our APT repository by **third-party** services is highly discouraged as will have noticeable impact on our hosting's bandwidth quota.
