### ISSUE TITLE
In vim in tmux, touching a split window will scroll another window

### ISSUE THREAD

**Issue by agguser** [termux/termux-app#1262]
```
% tmux -f /dev/null
% vim -u NONE +'set mouse=a' -o <(seq 1 499) <(seq 500 999)
```
then touch bottom window, then top window, do this a few times, notice that the content in top window scroll when touching bottom window! This problem does not occur in vim running outside tmux, or in vim in tmux through ssh from a computer using mouse click instead of touching.

**Comment by fornwall** [comment]
@agguser Thanks for your detailed description! It might be related to an issue in tmux, could you try updating to version `2.9a-5` of the tmux package by running `pkg up` and see if it works better?

**Comment by agguser** [comment]
After `pkg up`, the problem has gone! Thanks.
