### ISSUE TITLE
Termux dead | Termux failsafe only working

### ISSUE THREAD

**Issue by b3nsh4** [termux/termux-app#1266]
I was installing `termux-services`
After downloading, while installing, few warnings popped up; tar not found.
 I've logs uploaded. Failsafe is running.
![1](https://i.imgur.com/4J667yD.jpg)
Log..
![2](https://i.imgur.com/pGn3MfI.jpg)

**Comment by xeffyr** [comment]
Now you need to wipe or move somewhere your `$PREFIX` and restart application.

**Comment by b3nsh4** [comment]
@xeffyr If I remove $PREFIX, I'll lose everything. Making backup and restoring again causes same issue? What is the reason for this?

**Comment by xeffyr** [comment]
> What is the reason for this?

Missing binaries, environment broken, package manager unusable...
If you can somehow to create missing binaries and ensure that environment is sane, do it. We can't do that for you.
