### ISSUE TITLE
How to Auto-Run command ?

### ISSUE THREAD

**Issue by CMingTseng** [termux/termux-app#1267]
**Feature description**
Want disable or INVISIBLE Terminal GUI but can get Command (from Broadcast or  TerminalSession.write()) and then  auto run the command

When i first install termux-app 

install the base file  --from  bootstrap-arm-v15.zip

as TermuxActivity the app will run addNewSession 

i want run "apt update " & "apt install golang"

now i can  use  TerminalSession.write("apt update") send command text (only show GUI)

the command can not auto-run

anyone know how to do ?

THX

**Comment by xeffyr** [comment]
Use special intent - https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/TermuxService.java#L145.
