### ISSUE TITLE
cai i use link2sd app to send termux to sdcard 2nd partition?

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-app#1268]
can this affect termux functionality in some way?
What I want is to make some space to install a game, without uninstalling termux, link to the sdcard, and then "unlink" termux...

**Comment by xeffyr** [comment]
If second partition is ext4, then you should be able to do it.
But moving application data somewhere is *unsupported*, do not post any errors which you may face after moving data.

**Comment by kurokirasama** [comment]
sorry to bother you, but can i move to extSD and them mv back to intSD without opening termux along the way?
