### ISSUE TITLE
Unable to access Storage on Android 10

### ISSUE THREAD

**Issue by amanrao1997** [termux/termux-app#1269]
![Screenshot_20190929-030147](https://user-images.githubusercontent.com/5086622/65822656-87d57b80-e265-11e9-941e-82dbbeded1e9.png)
![Screenshot_20190929-025910](https://user-images.githubusercontent.com/5086622/65822657-87d57b80-e265-11e9-94e7-ef080f422fa3.png)
Issue
Tried termux-setup-storage but home folder doesn't have any storage mounted.
Unable to access /storage/emulated/0/ without root.
App settings don't have option to enable Storage Permission.

~ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/termux-root-packages-24 root/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.194-Illusion-v5.8-PixelExp+ #1 SMP PREEMPT Thu Sep 26 13:03:48 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
10
Device manufacturer:
Xiaomi
Device model:
Redmi Note 5 Pro

**Comment by xeffyr** [comment]
Termux doesn't have proper Android 10 support currently.

**Comment by adyady22222** [comment]
And is there any news about it???? something that will eventually fix this problem ??detailsss??

**Comment by DarthZedd** [comment]
> Termux doesn't have proper Android 10 support currently.

Are there any plans regarding this? My device should get upgrade to A10 this month and i strongly doubt if i will do this if Termux will not work properly.

**Comment by xeffyr** [comment]
> Are there any plans regarding this?

Termux is going to be completely re-worked in order to support Android 10. There a lot more issues than this one.

Currently it is partially saved by targeting API 28 instead of 29.

**Comment by xeffyr** [comment]
Android 10 uses a *scoped storage* (which means no free access to /sdcard for command line programs), but only for applications targeting for API 29: https://developer.android.com/training/data-storage/files/external-scoped.

Termux shouldn't have such issue, but it seems on some devices scoped storage enabled for everything. Is anyone who have this issue using Xiaomi device like OP ?

**Comment by amanrao1997** [comment]
> Android 10 uses a _scoped storage_ (which means no free access to /sdcard for command line programs), but only for applications targeting for API 29: https://developer.android.com/training/data-storage/files/external-scoped.
> 
> Termux shouldn't have such issue, but it seems on some devices scoped storage enabled for everything. Is anyone who have this issue using Xiaomi device like OP ?

I am using a AOSP custom rom on my device which is stock android.

**Comment by xeffyr** [comment]
I can't reproduce issue on the latest Android 10 image from Google.

Also, behaviour of your OS is different from one described on the official Android SDK documentation, so I'm in doubt that your AOSP is "stock android". For now considered as device-specific issue.

![Screenshot_1570191660](https://user-images.githubusercontent.com/25881154/66207134-a353e280-e6ba-11e9-98f7-a49b9d067118.png)

**Comment by xeffyr** [comment]
![Screenshot_1570191944](https://user-images.githubusercontent.com/25881154/66207392-515f8c80-e6bb-11e9-9355-2c7ea2cec990.png)

**Comment by xeffyr** [comment]
Android 10 issues are not going to be fixed shortly. And if even so, you won't have full access to `/sdcard` because of scoped storage. File access via SAF can't be passed to command line programs.

**Comment by amanrao1997** [comment]
> I can't reproduce issue on the latest Android 10 image from Google.
> 
> Also, behaviour of your OS is different from one described on the official Android SDK documentation, so I'm in doubt that your AOSP is "stock android". For now considered as device-specific issue.
> 
> ![Screenshot_1570191660](https://user-images.githubusercontent.com/25881154/66207134-a353e280-e6ba-11e9-98f7-a49b9d067118.png)

Weird, Did uninstall & reinstall and now I can see the storage permission.
¯\_(ツ)_/¯

Sorry for wasting time!

**Comment by cauerego** [comment]
just wanted to point this issue seem to be very relevant and it keeps coming and going. right now, there's an easy solution: 

open termux info, revoke permissions, run `termux-setup-storage`.

from:
https://github.com/termux/termux-app/issues/1617#issuecomment-723504941
