### ISSUE TITLE
Extra keys feature just shows a black, empty, bar

### ISSUE THREAD

**Issue by memeplex** [termux/termux-app#127]
On my nexus 7 all I'm able to see in the new extra keys bar is dismaying blackness. Swiping to the left for getting suggestions works fine, though, but no ctrl, alt or esc here :(

**Comment by Neo-Oli** [comment]
Hi, it appears to be an issue for some device. We're already tracking this issue at #109, therefore I am closing this. You can subscribe to #109 to get notified of changes.
