### ISSUE TITLE
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

### ISSUE THREAD

**Issue by adilakavov1204** [termux/termux-app#1272]
Hi guys. I faced with: `ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.`
 Maybe i should post this bug report in termux-packages  section but i decide to post it here and i will explain why futher. For some reasons i needed to use celery (task queue) with django on my Android phone. After installation of celery  i tried to test my celery installation which led me to mentioning above error. I found simple way to reproduce this error and for ease explanation i will omit describing of the way i detected it and will choose more simple way to reproduce this error. I do following run python i use python 3.7.3 than i am  trying to import synchronize from multiprocessing module
`from multiprocessing import synchronize ` 
After calling it termux give me an error i publish full traceback for more informativeness
`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/home/storage/predictions/env/lib/python3.7/lib-dynload/_multiprocessing.cpython-37m.so)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/synchronize.py", line 32, in <module>
    " synchronization primitives needed will not" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.` I read disscussion of 3770 issue https://bugs.python.org/issue3770 and like i understand this problem is depend on platform in attached link problem was occured on freebsd with python 2. Because of it i decide to publish bug report in termux-app section indeed termux-packages section. Is it problem with termux or i am doing anything wrong?  Here is output of my termux-info command 
System information:
Linux localhost 4.4.78-perf+ #1 SMP PREEMPT Tue Nov 6 10:12:39 CST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.1.0
Device manufacturer:
asus
Device model:
ZB602KL

**Comment by Grimler91** [comment]
Hi, see https://github.com/termux/termux-packages/issues/570, not much we can do about this as long as android doesn't support multiprocessing

**Comment by xeffyr** [comment]
> android doesn't support multiprocessing

Android supports multiprocessing, but not semaphores.

**Comment by RSwarnkar** [comment]
I want to run couple of Machine learning libraries that on import cause this error. Any luck :(

**Comment by BryleHelll** [comment]
> Hi, see [termux/termux-packages#570](https://github.com/termux/termux-packages/issues/570), not much we can do about this as long as android doesn't support multiprocessing

This issue need fix, coz i want use graal or maxine on termux which both uses mx (executing mx doesn't work becoz of this issue)

**Comment by BryleHelll** [comment]
;(
