### ISSUE TITLE
An old bug is back. 

### ISSUE THREAD

**Issue by johndoehack** [termux/termux-app#1273]
I get a bug that i thought it was fixed.
After running apt update i get the following lines:

Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/termux/termux-packages-24 stable Release
  403  Forbidden
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:6 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:6 https://dl.bintray.com/grimler/science-packages-24 science Release
Reading package lists... Done
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details

Please fix that or help me fix it.

I been using this tool for years with nethunter on it.

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/4358
