### ISSUE TITLE
Unable To Install Packages Or Do apt update On New Installation

### ISSUE THREAD

**Issue by azwalzaman** [termux/termux-app#1279]
**Problem description**
The apt update command is not working after I uninstalled and reinstalled Termux. The apt upgrade and apt install commands are also not working.

When I run apt update the output is:

`$ apt update`

`Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease`

`Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease`

`Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease`

`Err:4 https://dl.bintray.com/termux/termux-packages-24 stable Release`
  `403  Forbidden`

`Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]`

`Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release`

`Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]`

`Hit:7 https://dl.bintray.com/grimler/science-packages-24 science Release`
`Reading package lists... Done`

`E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.`

`N: Updating from such a repository can't be done securely, and is therefore disabled by default.`

`N: See apt-secure(8) manpage for repository creation and user configuration details. `

**Steps to reproduce**

1. Uninstall Termux.
2. Reinstall from Google Playstore
3. Run apt update(or any apt upgrade or apt install)

**Expected behavior**
I expected it to work as my previous installation did.

**Additional Information**
1. Phone: Redmi Y2
2. Android Version: 9

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/4358
