### ISSUE TITLE
Install packages to /system [feature request]

### ISSUE THREAD

**Issue by DRSDavidSoft** [termux/termux-app#128]
This may be a simple question, but since the installer is within the app, I figured I should ask it here. Termux is a wonderful app, and I use it almost on a daily basis. However, so often times I prefer to use the packages it provide from adb to manage my phone, and debug my own scripts and apps. I also prefer to use some other Terminal Emulator apps with Termux packages, rather than its own emulator. This is due to many reasons, such as being used to them, having more ready plugins, supporting tabs and easy style configuring.

I always use the solution provided [here](https://github.com/termux/termux-app/issues/77) to do so, however I think this process could be more easy, and robust if other people use Termux with their own Terminal emulators.

My purpose is that Termux Installer should provide a way to install its binaries to the /system/bin or /system/xbin, if the device is rooted. Also, it needs to either install the libraries in the proper /system directory, and/or add the binary and library directories to the PATH so that using termux outside its emulator could be as easy typing `tmux` in the console.

Of course, installing to the /system should _not_ be enabled by default, and it should be done so only if the device has root access, and the user chooses to do so.

Please consider adding this, I think install the bin files to the /system/bin directory will be both useful, and make more sense to Linux devs. :)

**Comment by iammeat** [comment]
I think this is a fantastic idea.  I also use rooted devices extensively and build my own firmware for many devices, so having this application and all the capabilities natively built in to my firmware files would be excellent.  

I would suggest though that the files are added in their own subdirectory of /system/bin, such as /system/bin/termux, with the path added to the root environment.  This would aid in easy removal in the future if required and avoid any conflict with files that already exist in Android.

**Comment by gene-pavlovsky** [comment]
+1

**Comment by alxpettit** [comment]
Yes please do the thing! :grinning:

**Comment by xeffyr** [comment]
Installing packages to /system will require compiling them against different prefix and having separate repository for them.

**Comment by alxpettit** [comment]
@xeffyr  How difficult would it be to patch them so that they use the PREFIX environment variable instead of a hardcoded path? You would need to adapt each script to use a little more active code, but it seems doable.

**Comment by alxpettit** [comment]
Alternative solution: automated script for creating symlinks for integrating Termux utilities to be more easily usable outside of the Termux environment, without actually changing the installation path. This seems like it would be very easy to do!
