### ISSUE TITLE
New installed app creates error

### ISSUE THREAD

**Issue by MbrooGit** [termux/termux-app#1280]
Just installed app from f-droid. The only command I used is "pkg update" but output is

> $pkg update
> Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
> Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
> Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
> Err:4 https://dl.bintray.com/termux/termux-packages-24 stable Release
>   403  Forbidden
> Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
> Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
> Get:6 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
> Hit:6 https://dl.bintray.com/grimler/science-packages-24 science Release
> Reading package lists... Done
> E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> $

Also `pkg list-all` show [installed, local] on every instaled app

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/4358
