### ISSUE TITLE
Update error 

### ISSUE THREAD

**Issue by dsvenky** [termux/termux-app#1281]
**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by dsvenky** [comment]
I'm getting 403 forbidden error I was tried few methods in Google and github but cant solved it

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/4358
