### ISSUE TITLE
403 forbidden while update or pkg Install

### ISSUE THREAD

**Issue by th3unkn0n** [termux/termux-app#1283]
Issue : when ever I try to update / upgrade , Install a package I get 403 forbidden error & lot of other my friends have same issue.
![Screenshot_20191001-232818_Termux](https://user-images.githubusercontent.com/40244622/65995100-687f5e00-e4b2-11e9-879c-8298ba0f81ca.jpg)
![IMG-20191001-WA0026](https://user-images.githubusercontent.com/40244622/65995126-77661080-e4b2-11e9-9fc7-80770d73ce7c.jpg)

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/4358

**Comment by Showen-X-Hacker** [comment]
Most of the time the problem comes from "/data/data/com.termux/files/usr/etc/apt/sources.list.d" (FYI I might typo the full path) directory.

Where you will find two files "game.list" and "science.list".You have to edit both files with nano,vim etc.Upon opening the file(s), you want to comment out the lines or url(s) in those files with "#".

For example: "#deb http://dl.bintray....

Note: You might wanna see which repository causes the 403 error during your "apt update"
 command.And then comment out that respository URL in the source lists.

**Comment by AnonymousxHacker** [comment]
The "sources.list.d" directory at /data/data/com.termux/files/usr/etc/apt/sources.list.d/" 
contains 2 repository files "game.list" and "science.list".

Using nano,vim or another text editor,  comment out the repository url(s) in these file with "#".
For example: "#deb https://ld.bintray...."

Note: In the 403 error message, note the repository url causing the error during your "apt update" command.After finding the repository url causing the 403 error, try to do the same by commenting out that specific repository url in the source.list file and/or directory to make it inactive or to un-use that specific repository url.

**Comment by oxi3280hack** [comment]
Hello mi french speak french pls

**Comment by AnonymousxHacker** [comment]
Translated the post in french.
Hopes this helps.

AnonymousxHacker a commenté il y a 6 jours
Le répertoire "sources.list.d" à /data/data/com.termux/files/usr/etc/apt/sources.list.d/ "
contient 2 fichiers de dépôt "game.list" et "science.list".

En utilisant nano, vim ou un autre éditeur de texte, commentez les URL du référentiel dans ces fichiers avec "#".
Par exemple: "#deb https: //ld.bintray ...."

Remarque: dans le message d'erreur 403, notez l'URL du référentiel à l'origine de l'erreur lors de votre commande "apt update". Après avoir trouvé l'URL du référentiel à l'origine de l'erreur 403, essayez de faire de même en commentant cette URL de référentiel spécifique dans le fichier source.list fichier et / ou répertoire pour le rendre inactif ou pour désutiliser cette URL de référentiel spécifique.

**Comment by trusktr** [comment]
I'm having this issue right now. Does it mean the server is overloaded again?

**Comment by trusktr** [comment]
> Using nano,vim or another text editor, comment out the repository url(s) in these file with "#".
For example: "#deb https://ld.bintray...."

Which editor comes pre-installed? I can't edit those files because there is no `nano` or `vim` installed.

**Comment by AkechiShiro** [comment]
I encountered this issue again today, I would like to know why this issue happens, I do not have two lines in my source.list just one line and this issue still happens, `nano` was pre-installed for me however vim was not.

**Comment by Grimler91** [comment]
@AkechiShiro see https://github.com/termux/termux-packages/issues/6726

**Comment by echoPATH** [comment]
chmod +rwrx game.list science list and root.list

**Comment by DARK-EAGLE-WARRIOR** [comment]
> Issue : when ever I try to update / upgrade , Install a package I get 403 forbidden error & lot of other my friends have same issue.
> ![Screenshot_20191001-232818_Termux](https://user-images.githubusercontent.com/40244622/65995100-687f5e00-e4b2-11e9-879c-8298ba0f81ca.jpg)
> ![IMG-20191001-WA0026](https://user-images.githubusercontent.com/40244622/65995126-77661080-e4b2-11e9-9fc7-80770d73ce7c.jpg)


I suggest u to use tool Termux-fix

$git clone https://github.com/DARK-EAGLE-WARRIOR/Termux-fix.git 

I used this tool when i have same error
And this tools work well to me 
Soory for my poor english 😌

**Comment by WMCB-Tech** [comment]
The problem here is that it uses `termux.net` domain which it is being used in Legacy environments, which in Newer Termux versions won't work

***

use this solution as suggested
https://github.com/termux/termux-packages/issues/6726

P.S. replace `termux.net` with `grimler.se` with your script

**Comment by DARK-EAGLE-WARRIOR** [comment]
> If someone facing the issue when you run
> `pkg install ....` or `pkg update`
> and get error 403 forbidden -
> The simple fix for that:
> run
> `apt upgrade`
> After that everything will work just fine.

This is only for  new termux version user
For legancy

> If someone facing the issue when you run
> `pkg install ....` or `pkg update`
> and get error 403 forbidden -
> The simple fix for that:
> run
> `apt upgrade`
> After that everything will work just fine.

This above is only for new termux version
Legacy environments user can use Termux-fix tool
$git clone https://github.com/DARK-EAGLE-WARRIOR/Termux-fix.git
This tools install on our bin so 
It can be use when any error came

**Comment by AnonymousxHacker** [comment]
> I'm having this issue right now. Does it mean the server is overloaded again?

Not sure what the problem is.
But reading error messages helps.

**Comment by AnonymousxHacker** [comment]
> > Using nano,vim or another text editor, comment out the repository url(s) in these file with "#".
> > For example: "#deb https://ld.bintray...."
> 
> Which editor comes pre-installed? I can't edit those files because there is no `nano` or `vim` installed.
> 
> EDIT: Well, after `cat`ting those files, I see they only have one URL each (the URL with the issue), so it would be pointless to have zero URLs right?
> 
> EDIT: In lieu of not having a text editor available by default, I used commands like `sed -i 's/deb /#dbe /g'` game.list` to comment out the lines in each files.
> 
> That worked!

Glad I could help.

**Comment by clementherve** [comment]
So, I came across this issue, too.
I eventually changed the package repo URL (/data/data/com.termux/files/usr/etc/apt/sources.list) to "deb https://packages.termux.org/apt/termux-main/ stable main" (see https://packages.termux.org/).
I am leaving this here if it can be useful to anyone!

**Comment by xeffyr** [comment]
Btw there is a pinned issue about repository change and 403/404 on old: https://github.com/termux/termux-packages/issues/6726

**Comment by richardeson** [comment]
> If someone facing the issue when you run 
> `pkg install ....` or `pkg update` 
> and get error 403 forbidden -
> The simple fix for that:
> run
> `apt upgrade`
> After that everything will work just fine.

It's work like a charm. 

Thank very much!
