### ISSUE TITLE
How to detect task finish and result ?

### ISSUE THREAD

**Issue by CMingTseng** [termux/termux-app#1284]
**Feature description**
When i input some task  like :  " pkg install -y golang "

i know TerminalSession mMainThreadHandler will get Message MSG_NEW_INPUT

if the screen close or the view invisible

when  the golang  install finish ( include  depend library .... )

how  to know the work finish & result ?

Ref : https://github.com/piotrmurach/tty-command

f the command succeeds, a `TTY::Command::Result` is returned that records stdout and stderr:

```ruby
out, err = cmd.run('date')
puts "The date is #{out}"
# => "The date is Tue 10 May 2016 22:30:15 BST\n"
```

You can also pass a block that gets invoked anytime stdout and/or stderr receive output:

```ruby
cmd.run('long running script') do |out, err|
  output << out if out
  errors << err if err
end
```

If the command fails (with a non-zero exit code), a `TTY::Command::ExitError` is raised. The `ExitError` message will include:

  * the name of command executed
  * the exit status
  * stdout bytes
  * stderr bytes

If the error output is very long, the stderr may contain only a prefix, number of omitted bytes and suffix.

**Comment by agnostic-apollo** [comment]
You are using a ruby library to run commands, so should ask help there on how to wait for commands, although `run` will already [wait](https://github.com/piotrmurach/tty-command#21-run). This is not a termux issue.
