### ISSUE TITLE
Showing ls in command line permanently

### ISSUE THREAD

**Issue by ParaDoxX08** [termux/termux-app#1285]
why its showing ls in command line of termux its permanent and i am not able to remove it
![Screenshot_20191002-095949](https://user-images.githubusercontent.com/54233405/66018264-fc294c80-e4fb-11e9-8f83-789cb77da14a.jpg)

**Comment by Grimler91** [comment]
Does it disappear if you open a new terminal?

**Comment by ParaDoxX08** [comment]
Yup every single time

**Comment by Grimler91** [comment]
So what is your PS1 set to? (run `echo $PS1`)

**Comment by ParaDoxX08** [comment]
![Screenshot_20191002-134522](https://user-images.githubusercontent.com/54233405/66028598-145c9400-e51b-11e9-842e-db4dfc23b81a.jpg)
Here it is $/ ls

**Comment by ParaDoxX08** [comment]
Sry /$ ls

**Comment by Grimler91** [comment]
That explains it. I guess you are exporting it in your ~/.bashrc or something. Change your PS1 to not have `ls` in it if you don't want it to show in every terminal
