### ISSUE TITLE
LD_LIBRARY_PATH is being set if a non-default repository is used

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-app#1286]
**Problem description**
`shouldAddLdLibraryPath()` checks for `https://dl.bintray.com/termux/termux-packages-24` at https://github.com/termux/termux-app/blob/92980824b19e233b6bda27419f29387cc3720306/app/src/main/java/com/termux/app/BackgroundJob.java#L142
If a different repository is set ,`LD_LIBRARY_PATH` will be set. In the recent repository outage various mirrors were suggested in https://github.com/termux/termux-packages/issues/4358 and recently I started experimenting with setting up my own mirror using  `aptly`. But setting a custom main repository will cause LD_LIBRARY_PATH being set and this will cause a lot of issues with packages (for example `mpd`, `mpv` and `pulseaudio`)

**Steps to reproduce**
Delete or comment out the `https://dl.bintray.com/termux/termux-packages-24` repository and restart Termux.

**Expected behavior**

`LD_LIBRARY_PATH` being only set if the legacy repository is used.

**Comment by Neo-Oli** [comment]
### Workaround
If you comment the line out and add a preceding space `line.startsWith("#")` will think the line isn't commented out and it will not apply `LD_LIBRARY_PATH`.
```
# The main termux repository:
 #deb https://dl.bintray.com/termux/termux-packages-24 stable main
# custom aptly repository
deb http://localhost:8111/ termux main
```

**Comment by xeffyr** [comment]
We may create file `$PREFIX/etc/termux-api24` or `$PREFIX/etc/.api24` in bootstraps used for API-24+ devices and then check its existence in application. Bintray repo checking may still be present for compatibility.

Another variant will be exporting `LD_LIBRARY_PATH` by default (if no Bintray repo used) and adding following lines to the `$PREFIX/bin/login`:
```
if LD_LIBRARY_PATH= bash -c true > /dev/null 2>&1; then
	unset LD_LIBRARY_PATH
fi
```

**Comment by xeffyr** [comment]
Should be fixed with https://github.com/termux/termux-app/commit/c0a0822843969affedbf9760d44234caf46c8cd5.
