### ISSUE TITLE
How to open the browser automatically?

### ISSUE THREAD

**Issue by d1y** [termux/termux-app#1287]
I wrote a nodejs script.

```js
const $Platform = `win`
const url = 'http://xx'
swtich ($Platform) {
  case 'win':
    // start url
    break;
  case 'osx':
    // open url
    break;   
  case 'andriod':
    // I assume that the andriod environment encountered is termux
    // How to open default browser?
    break;
}

```

Thank you

**Comment by d1y** [comment]
Termux should have an API that calls the default browser. This requires the termux container to interact with the host. I don't understand very well.

**Comment by AbdullahM0hamed** [comment]
Termux does have something for it:

termux-open http://xx 



So I guess you'd have to do something like this (which I tested in the node console): 

```url = "http://xx" 
exec = require("child_process").exec 

exec(`termux-open ${url}`)

**Comment by xeffyr** [comment]
**termux-open-url**

**Comment by d1y** [comment]
> **termux-open-url**

> Termux does have something for it:
> 
> termux-open http://xx
> 
> So I guess you'd have to do something like this (which I tested in the node console):
> 
> ```
> url = "http://xx" 
> exec = require("child_process").exec 
> 
> exec(`termux-open ${url}`) 
> ```

Yes, the api is awesome. Thank you
