### ISSUE TITLE
2-row button doesn't work in Android 5.1

### ISSUE THREAD

**Issue by LeapofAzzam** [termux/termux-app#1291]
**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.
* 2-row button doesn't work in Android 5.1

![Screenshot_2019-10-06-10-15-22](https://user-images.githubusercontent.com/48548847/66263754-6145b080-e822-11e9-9f0d-81caf7be6aba.png)
![Screenshot_2019-10-06-10-13-55](https://user-images.githubusercontent.com/48548847/66263755-61de4700-e822-11e9-9fea-dac3d253b0fb.png)
![Screenshot_2019-10-06-10-12-55](https://user-images.githubusercontent.com/48548847/66263756-630f7400-e822-11e9-9d9a-ccad6eabf911.png)

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by xeffyr** [comment]
Please, re-read the instruction about extra keys usage: https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row(s).

**Comment by xeffyr** [comment]
You have to restart Termux.
`termux-reload-settings` will not work if you did a syntax error before but then corrected.

**Comment by LeapofAzzam** [comment]
> `termux-reload-settings` will not work if you did a syntax error before but then corrected.

Hey! It worked!
![Screenshot_20191116_122536](https://user-images.githubusercontent.com/48548847/68988588-5bed7400-086c-11ea-83b5-0f44cc573f6b.jpg)
