### ISSUE TITLE
How to relocation dpkg   relation files/folder  

### ISSUE THREAD

**Issue by CMingTseng** [termux/termux-app#1298]
**Feature description**
I know FILES_PATH  (/data/data/com.termux/files) is bootstrap unzip path

for some reason  i must change the FILES_PATH (lie : /data/data/packageA/user/0/com.termux/files)

now i get the shell --- fixed setupProcessArgs --add interpreter( /bin/sh )

but when i use  dpkg install local *.deb !!!

i get  the . error

{ dpkg :error : unable to access the dpkg database directory /data/data/com.termux/files/var/lib}

Yes . ithe dpkg use old path !!??

not use    /data/data/packageA/user/0/com.termux/files/var/lib

How to fixed this ?

THX

**Comment by xeffyr** [comment]
>for some reason i must change the FILES_PATH (lie : /data/data/packageA/user/0/com.termux/files)

You can't use such path.
All executables must be placed directly on EXT4 file system (no sdcardfs-emulated) where Android allows to use unix permissions, symlinks, sockets, etc...

> How to fixed this ?

Create own repository with custom installation path, etc...

NOTE: **usage of our services (termux.net, dl.bintray.com/termux/*) by third-party projects is not allowed.**
