### ISSUE TITLE
Suggestion: Arrow keys

### ISSUE THREAD

**Issue by CyberLinx** [termux/termux-app#1299]
**Feature description**
Termux app is great, but i have noiced it doesn't have left and right arrow keys, it's a pain for me when i use nano to edit something, can you add it? Thanks

**Reference implementation**
I use JuiceSSH fot SSH connection and it have this feature, so why Termux not?

**Comment by Grimler91** [comment]
See https://wiki.termux.com/wiki/Touch_Keyboard on how to show the extra-keys row

**Comment by CyberLinx** [comment]
How to change the font size of the extra-keys

**Comment by AbdullahM0hamed** [comment]
There is no real way to do that as far as I can tell, but you can:

a) Have less keys per row to increase the size of the keys, 


b) have more keys per row to decrease the size (if you don't want to add more keys, you can add empty keys by using quoting empty strings)

**Comment by CyberLinx** [comment]
Ok, thanks, Termux is awesowe, the best app on android i've ever seen

**Comment by khansaad1275** [comment]
On this website, you can find one command method to enable keys in termux [[Enable Keys in termux](https://www.termux.ga/2020/01/how-to-enable-extra-keys-in-termux.html)]
