### ISSUE TITLE
emacs and file segfault

### ISSUE THREAD

**Issue by nico202** [termux/termux-app#13]
I just installed emac, it crash at boot with Error 11: Segmentation faultSegmantation fault
Also, using file on a file gives:
"file: filetype
Segmetation fault"

both have been installed from the repo.
Thanks, Nicolò

**Comment by fornwall** [comment]
Hi, sorry for not responding sooner here!

Emacs is a bit broken at the moment regretfully - you can subscribe to https://github.com/termux/termux-packages/issues/11 to see more information and get notifications about progress!
