### ISSUE TITLE
Use default android dns server

### ISSUE THREAD

**Issue by rugk** [termux/termux-app#130]
Currently termux always uses the servers listed in `/usr/etc/resolv.conf`.
However I'd like it to use the default android dns server. At least when there is no entry in the resolv file it should be used.
Otherwise a special entry such as `nameserver default` would be useful to indicate that the default android name server should be used.

I mean in a mobile network it might of course be the same as configured in the file (google name server), but when connected to a wi-fi network this is different.

**Comment by fornwall** [comment]
Hm, I thought most apps use the android system dns server - only `nmap` and `dnsutils` uses `$PREFIX/etc/resolv.conf`. Does that seem to be correct?

**Comment by rugk** [comment]
`nslookup` does also use the custom resolv.conf. (I only tested it with this utility)

However when some tools do it differently this is much more confusing. There should be a consistent behaviour, otherwise this complicates debugging and such things.
So either should all Termux programs honour the users resolv.conf or they should not.

My initial request is still valid through: Apps honouring the custom resolv.conf should be able to use the built-in Android dns server. AT least thee should be a consistent behaviour.

**Comment by fornwall** [comment]
Normally the libc implementation of the resolver uses `/etc/resolv.conf`, but that is not the case for the libc on Android. So having most program using `resolv.conf` is not possible without overriding the libc resolver, which is outside the scope here.

As for `nmap` and `dnsutils` (the latter which contains `nslookup`), perhaps they can be patched to use the system one either by default or as an option?

I guess the system name server can be obtained with `getprop net.dns1` (and `getprop net.dns2`), could you try to temporarily write that to `resolv.conf` and see if it works as expected for you?

**Comment by rugk** [comment]
> As for nmap and dnsutils (the latter which contains nslookup), perhaps they can be patched to use the system one either by default or as an option?

Yeah, I am :+1: of "as an option". :smiley: 

> I guess the system name server can be obtained with getprop net.dns1 (and getprop net.dns2), could you try to temporarily write that to resolv.conf and see if it works as expected for you?

Nice, did not knew about "getprop". Is this Android-specific or is this something Termux adds as a console command?

So I can use "getprop net.dns1" to get the dns server and write it into the resolv.conf file. And of course this works. I mean I also do know the dns server Android currently uses so I can "hardcode" it into the resolv.conf file, but this is only a workaround and no generic solution for this issue.
Unfortunately something like setting the nameserver to "nameserver net.dns1" or similar does not work...

**Comment by glitchphan** [comment]
What about
nameserver `getprop net.dns1`
?

**Comment by rugk** [comment]
No, this does not work either. In this case it shows a parsing error.

**Comment by jsainzvela** [comment]
Just found out about Termux and I think it is awesome already! :)

I have the same problem as depicted in this topic, has anybody found a solution to overwrite the resolv.conf file with the `getprop net.dns1` output?

Thanks!

Jorge

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#1174
