### ISSUE TITLE
Termux discord server

### ISSUE THREAD

**Issue by CyberLinx** [termux/termux-app#1303]
**Feature description**
Can you create a discord server for Termux? Some people doesn't have Gitter and/or IRC

**Comment by MegaArthur** [comment]
I'd opt for creating a Matrix community, then it can be bridged with both Discord and IRC

**Comment by PHPoenX** [comment]
> Some people doesn't have Gitter and/or IRC

you can use IRC without installing client

Also, some people don`t have discord

**Comment by fornwall** [comment]
Anyone is welcome to host a Discord server for discussing Termux, we can even link to it from the wiki if appropriate.

Just reach out to us (on Gitter or IRC, that is) if you're interested.

**Comment by pollen5** [comment]
I created one at https://discord.gg/HXpF69X if anyone is interested.

**Comment by sayantan300** [comment]
https://discord.gg/kVRHE6T one more server 😎

**Comment by kcubeterm** [comment]
https://discord.gg/JF66mEj one more

**Comment by xeffyr** [comment]
Issue is locked as we have now https://discord.gg/HXpF69X which is listed at https://discord.gg/HXpF69X.

For the official communities there one rule: one service - one channel. There no point to create more as they will only split community more. If you want any suggestions, contact the channel/service operator.
