### ISSUE TITLE
ssh logins don't need user name

### ISSUE THREAD

**Issue by GogoAkira** [termux/termux-app#1305]
I log in to Termux via ssh without entering user name, or by entering random made up username and it still logs in to existing u0_ user.
ssh ip_addr -p 8022, logs in to the u0_ user.
ssh randombla@ip_addr logs in to u0_ user.
ssh u0_@ip_addr logs in to u0_ user.

It's not a server I know :), well it is, it has nginx on it :), but still it's my Nexus 6P :)

**Comment by Grimler91** [comment]
Openssh has been patched to not compare the username since we can't control the username or have multiple users. See https://github.com/termux/termux-packages/blob/master/packages/openssh/auth.c.patch
