### ISSUE TITLE
Please help me!!!

### ISSUE THREAD

**Issue by dickyharper** [termux/termux-app#1307]
**Problem description**
'/data/data/com.termux/files/usr/bin/login: 4: /data/data/com.termux/files/usr/bin/login: cat: not found'

**Steps to reproduce**
apt-get update 
apt-get upgrade 
and some options are given, all are given the answer "y".

**Expected behavior**
What do I have wrong?

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by Grimler91** [comment]
Looks like you have somehow removed cureutils. Easiest fix would be to run `rm -rf $PREFIX` from a [failsafe session](https://wiki.termux.com/wiki/Recover_a_broken_environment) and then restart the app. This will keep all your files in $HOME but remove all installed packages and give you a fresh installation.

**Comment by dickyharper** [comment]
@grimler91
My problem is solved.  Thank you.  I am having this problem after every apt-get upgrade command.  Why exactly? 😕
