### ISSUE TITLE
hope a flag add into 'uname -r'

### ISSUE THREAD

**Issue by dawendiguo** [termux/termux-app#1309]
**Feature description**
I hope a termux can have a diffrent with linux system info. so that 'cmake' can compile file with diffrent library。
**Reference implementation**
when i use cmake compile my code, cmake can't differentiate which is linux  and  which is termux . the two system have diffrent library use. some example: when i compile in linux,  i don't need '-llog', but if it is termux in android '-llog' is must use. 
so i hope add a flag in " uname -r" . cmake's ${CMAKE_SYSTEM} can use to pick out which is termux, and which is linux.

**Comment by xeffyr** [comment]
We will not modify `uname -r` behaviour. Faking kernel release is quite weird way to distinguish OS or environment. Use `uname -o` instead. In Termux it outputs operating system as Android - that change is Termux-specific.

There also Termux-specific defines in C/C++ headers - https://github.com/termux/termux-packages/commit/b9d83f9fb83e42b3fbd2d515412d44111846ef96. You can use them too.
