### ISSUE TITLE
Android x86_64 6.0.1, why aarch64 binary ? Can't get x86_64 binary?

### ISSUE THREAD

**Issue by youling257** [termux/termux-app#131]
# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=MOB30R
ro.build.display.id=android_x86_64-eng 6.0.1 MOB30R eng.ubuntu.20160805.080110 test-keys
ro.build.version.incremental=eng.ubuntu.20160805.080110
ro.build.version.sdk=23
ro.build.version.preview_sdk=0
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=6.0.1
ro.build.version.security_patch=2016-07-05
ro.build.version.base_os=
ro.build.date=Fri Aug  5 08:22:39 CEST 2016
ro.build.date.utc=1470378159
ro.build.type=eng
ro.build.user=ubuntu
ro.build.host=android-nightly
ro.build.tags=test-keys
ro.build.flavor=android_x86_64-eng
ro.product.model=Generic Android-x86_64
ro.product.brand=Android-x86
ro.product.name=android_x86_64
ro.product.device=x86_64
ro.product.board=
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=x86_64
ro.product.cpu.abilist=x86_64,x86,arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
ro.product.cpu.abilist64=x86_64,arm64-v8a
ro.product.manufacturer=unknown
ro.product.locale=en-US
ro.wifi.channels=
ro.board.platform=android-x86
# ro.build.product is obsolete; use ro.product.device
ro.build.product=x86_64
# Do not try to parse description, fingerprint, or thumbprint
ro.build.description=android_x86_64-eng 6.0.1 MOB30R eng.ubuntu.20160805.080110 test-keys
ro.build.fingerprint=Android-x86/android_x86_64/x86_64:6.0.1/MOB30R/ubuntu08050804:eng/test-keys
ro.build.characteristics=tablet
# end build properties

#
# ADDITIONAL_BUILD_PROPERTIES
#
ro.com.android.dateformat=MM-dd-yyyy
ro.ril.hsxpa=1
ro.ril.gprsclass=10
keyguard.no_require_sim=true
ro.com.android.dataroaming=true
ro.opengles.version=196608
dalvik.vm.heapstartsize=16m
dalvik.vm.heapgrowthlimit=192m
dalvik.vm.heapsize=512m
dalvik.vm.heaptargetutilization=0.75
dalvik.vm.heapminfree=512k
dalvik.vm.heapmaxfree=8m
ro.dalvik.vm.isa.arm=x86
ro.enable.native.bridge.exec=1
ro.dalvik.vm.isa.arm64=x86_64
ro.enable.native.bridge.exec64=1
ro.carrier=unknown
ro.config.notification_sound=OnTheHunt.ogg
ro.config.alarm_alert=Alarm_Classic.ogg
persist.sys.dalvik.vm.lib.2=libart
dalvik.vm.isa.x86_64.variant=x86_64
dalvik.vm.isa.x86_64.features=default
dalvik.vm.isa.x86.variant=dalvik.vm.isa.x86.features=default
ro.kernel.android.checkjni=1
dalvik.vm.lockprof.threshold=500
dalvik.vm.image-dex2oat-filter=verify-at-runtime
dalvik.vm.dex2oat-filter=verify-at-runtime
dalvik.vm.usejit=true
net.bt.name=Android
dalvik.vm.stack-trace-file=/data/anr/traces.txt
ro.sf.lcd_density=240
hal.sensors.iio.accel.matrix=0,1,0,1,0,0,0,0,-1

**Comment by youling257** [comment]
if i disable android x86_64 nativebridge , it will
 : not foundcom.termux/files/usr/bin/bash[1]: ELF��@�
/data/data/com.termux/files/usr/bin/bash[2]: @@@@@�888�: not found
/data/data/com.termux/files/usr/bin/bash[3]: �: not found
/data/data/com.termux/files/usr/bin/bash[4]: �Y��X�: not found
/data/data/com.termux/files/usr/bin/bash[5]: X�: not found
/data/data/com.termux/files/usr/bin/bash[6]: @��: not found
/data/data/com.termux/files/usr/bin/bash[7]: syntax error: ')' unexpected

[Process completed with code 1 - press Enter to close]

if i enable nativebridge, it will get aarch64 binary .

**Comment by fornwall** [comment]
You have a `x86_64` Android system, which can run `aarch64` via emulation, and you get the `aarch64` install even tough `x86_64` would  be better? Is that correct?

**Comment by youling257** [comment]
yes, x86_64 would be better

**Comment by fornwall** [comment]
Thanks - this should be resolved in the `v0.39` update of the Termux app!

The problem was that the ordering of [Build.SUPPORTED_ABIS](https://developer.android.com/reference/android/os/Build.html#SUPPORTED_ABIS)/`ro.product.cpu.abilist` was not considered, so a suboptimal arch was used.

**Comment by youling257** [comment]
@fornwall 
apt update
Get:1 http://termux.net stable InRelease [1683 B]
Get:2 http://termux.net stable/main all Packages [2952 B]
Get:3 http://termux.net stable/main x86_64 Packages [41.0 kB]
Err:3 http://termux.net stable/main x86_64 Packages
  Hash Sum mismatch
Fetched 45.4 kB in 2s (20.7 kB/s)
Reading package lists... Done
E: Failed to fetch http://termux.net/dists/stable/main/binary-x86_64/Packages.xz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
$

**Comment by fornwall** [comment]
@youling257 I had misconfigured cache settings for the new `x86_64` repository - this have now been fixed, so should work after an `apt update`.

Thanks!

**Comment by 5chdn** [comment]
Hi, just having the same hashsum mismatch error on a nexus 5 (arm) with termux 0.39... should I open another ticket?

![screenshot_20160821-183756](https://cloud.githubusercontent.com/assets/15729797/17838468/9872d240-67ce-11e6-801a-7d259e040cc0.png)

**Comment by fornwall** [comment]
@5chdn It works for me when I test on an arm device - could you try again and see if it works better? It can have been a temporary cache somewhere along the line.

**Comment by 5chdn** [comment]
Yeah, all right, was just temporary.
