### ISSUE TITLE
CANNOT LINK EXECUTABLE "cat": library "libandroid-support.so" not found 

### ISSUE THREAD

**Issue by youling257** [termux/termux-app#1312]
**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by youling257** [comment]
termux 0.76

NNOT LINK EXECUTABLE "cat": library "libandroid-support.so" not found
libc: CANNOT LINK EXECUTABLE "cat": library "libandroid-support.so" not found
libc: Fatal signal 6 (SIGABRT), code -6 in tid 13845 (cat)
Aborted
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": library "libandroid-support.so" not found
libc: CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": library "libandroid-support.so" not found
libc: Fatal signal 6 (SIGABRT), code -6 in tid 13841 (bash)

[Process completed (signal 6) - press Enter]

**Comment by xeffyr** [comment]
Check the https://github.com/termux/termux-app/issues/1307 - it has solution.

**Comment by youling257** [comment]
I update termux 0.76 from google play store.
it's impossible to clear termux data! I would never do that.

**Comment by xeffyr** [comment]
> I would never do that.

And you never fix that.
Just remember that we will not (and can't) connect to your device and repair the environment for you.
