### ISSUE TITLE
Unable to compile Simh under android 8.0.0

### ISSUE THREAD

**Issue by g1gop** [termux/termux-app#1313]
Hi Not sure what to post here so copying email about problem which hopefully will give enough info.Please let me know if any other info is needed.
Alan

Hi, I uninstalled all and re installed. Same error.

Will send this email to support.

Alan
On 21/10/2019 21:44, Mark Pizzolato wrote:
>
> Hmm.  I done this with several Android versions which were all on Google devices.
>
>  
>
> I’ve currently got a Pixel 3 with Android 10, but I know it worked on my older Nexus 5X with Android 8.  I’ve got an old Google Nexus 7 tablet running Android 6.0.1 which also works fine.
>
>  
>
> Pixel 3:
>
>  
>
> $ pwd
>
> /data/data/com.termux/files/home
>
> $ cd simh
>
> $ rm BIN/pdp8
>
> $ make pdp8
>
> lib paths are: /usr/lib /system/lib
>
> include paths are:  /data/data/com.termux/files/usr/include/aarch64-linux-android /data/da
>
> ta/com.termux/files/usr/lib/clang/8.0.1/include /data/data/com.termux/files/usr/include
>
> using libm: /system/lib/libm.so
>
> using semaphore: /data/data/com.termux/files/usr/include/semaphore.h
>
> using libdl: /system/lib/libdl.so /data/data/com.termux/files/usr/include/dlfcn.h
>
> ***
>
> *** pdp8 Simulator being built with:
>
> *** - compiler optimizations and no debugging support. clang version 8.0.1.
>
> *** - Per simulator tests will be run.
>
> ***
>
> *** git commit id is 0de9b62850c03fc435cecfcc928f4dad65933ebe.
>
> *** git commit time is 2019-10-18T23:18:39-0700.
>
> ***
>
> gcc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow -finline-functions -DSIM_GIT_COMM
>
> IT_ID=0de9b62850c03fc435cecfcc928f4dad65933ebe -DSIM_GIT_COMMIT_TIME=2019-10-18T23:18:39-0
>
> 700  -DSIM_COMPILER="clang version 8.0.1" -I . -D_GNU_SOURCE -D__ANDROID_API__=29 -DSIM_BU
>
> ILD_OS=" On Android Version 10" -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAV
>
> E_DLOPEN=so -DHAVE_UTIME -DHAVE_GLOB  PDP8/pdp8_cpu.c PDP8/pdp8_clk.c PDP8/pdp8_df.c PDP8/
>
> pdp8_dt.c PDP8/pdp8_lp.c PDP8/pdp8_mt.c PDP8/pdp8_pt.c PDP8/pdp8_rf.c PDP8/pdp8_rk.c PDP8/
>
> pdp8_rx.c PDP8/pdp8_sys.c PDP8/pdp8_tt.c PDP8/pdp8_ttx.c PDP8/pdp8_rl.c PDP8/pdp8_tsc.c PD
>
> P8/pdp8_td.c PDP8/pdp8_ct.c PDP8/pdp8_fpp.c scp.c sim_console.c sim_fio.c sim_timer.c sim_
>
> sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim
>
> _card.c -I PDP8 -o BIN/pdp8 -lm -ldl
>
> $ uname -a
>
> Linux localhost 4.9.165-g3206e079fc69-ab5845057 #0 SMP PREEMPT Sat Aug 31 00:42:08 UTC 201
>
> 9 aarch64 Android
>
> $
>
>  
>
>  
>
> Nexus 7:
>
> $ cd simh
>
> $ uname -a
>
> Linux localhost 3.4.0-gad29d11 #1 SMP PREEMPT Sat Jul 2 00:00:53 UTC 2016 armv7l And
>
> roid
>
> $ git pull
>
> remote: Enumerating objects: 1735, done.
>
> remote: Counting objects: 100% (1735/1735), done.
>
> remote: Compressing objects: 100% (48/48), done.
>
> remote: Total 3195 (delta 1695), reused 1724 (delta 1687), pack-reused 1460
>
> Receiving objects: 100% (3195/3195), 9.01 MiB | 3.47 MiB/s, done.
>
> Resolving deltas: 100% (2457/2457), completed with 421 local objects.
>
> From https://github.com/simh/simh
>
>    8c0439fe..0de9b628  master         -> origin/master
>
>    e5b8139f..cf9ead8d  Supnik-Current -> origin/Supnik-Current
>
>  * [new tag]           v3.10          -> v3.10
>
> Updating 8c0439fe..0de9b628
>
> Checking out files: 100% (567/567), done.
>
> Fast-forward
>
> [..]
>
>  566 files changed, 363880 insertions(+), 19148 deletions(-)
>
> […]
>
> $ make pdp8
>
> lib paths are: /usr/lib /system/lib /data/data/com.termux/files/usr/lib
>
> include paths are:  /data/data/com.termux/files/usr/lib/clang/6.0.0/include /data/da
>
> ta/com.termux/files/usr/include
>
> using libm: /system/lib/libm.so
>
> using librt: /data/data/com.termux/files/usr/lib/librt.so
>
> using libpthread: /data/data/com.termux/files/usr/lib/libpthread.so /data/data/com.t
>
> ermux/files/usr/include/pthread.h
>
> using regex: /data/data/com.termux/files/usr/include/regex.h
>
> using semaphore: /data/data/com.termux/files/usr/include/semaphore.h
>
> using libdl: /system/lib/libdl.so /data/data/com.termux/files/usr/include/dlfcn.h
>
> ***
>
> *** pdp8 Simulator being built with:
>
> *** - compiler optimizations and no debugging support. clang version 6.0.0.
>
> *** - Per simulator tests will be run.
>
> ***
>
> *** git commit id is 0de9b62850c03fc435cecfcc928f4dad65933ebe.
>
> *** git commit time is 2019-10-18T23:18:39-0700.
>
> ***
>
> gcc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow -finline-functions -DSIM_GI
>
> T_COMMIT_ID=0de9b62850c03fc435cecfcc928f4dad65933ebe -DSIM_GIT_COMMIT_TIME=2019-10-1
>
> 8T23:18:39-0700  -DSIM_COMPILER="clang version 6.0.0" -I . -D_GNU_SOURCE -D__ANDROID
>
> _API__=23 -DSIM_BUILD_OS=" On Android Version 6.0.1" -DUSE_READER_THREAD -DSIM_ASYNC
>
> H_IO  -DHAVE_REGEX_H -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLO
>
> PEN=so -DHAVE_UTIME -DHAVE_FNMATCH      PDP8/pdp8_cpu.c PDP8/pdp8_clk.c PDP8/pdp8_df
>
> .c PDP8/pdp8_dt.c PDP8/pdp8_lp.c PDP8/pdp8_mt.c PDP8/pdp8_pt.c PDP8/pdp8_rf.c PDP8/p
>
> dp8_rk.c PDP8/pdp8_rx.c PDP8/pdp8_sys.c PDP8/pdp8_tt.c PDP8/pdp8_ttx.c PDP8/pdp8_rl.
>
> c PDP8/pdp8_tsc.c PDP8/pdp8_td.c PDP8/pdp8_ct.c PDP8/pdp8_fpp.c scp.c sim_console.c 
>
> sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_se
>
> rial.c sim_video.c sim_imd.c sim_card.c -I PDP8 -o BIN/pdp8 -lm -lrt -lpthread -ldl 
>
>  
>
> $
>
>  
>
> The above was with older termux packages.  I’ll update the packages…   Hmmm.  That didn’t work due to some entangled dependency and the old termux version. 
>
>  
>
> The next step would be to uninstall termux completely and start from a clean install.  I did the uninstall, but Android version 6 is no longer supported with the current termux, so I had to dig up an earlier version that would work.  Once I did that, I installed it and the used “pkg install” to install the specific required packages: git clang make, cloned the repo and and it also built cleanly.
>
>  
>
> Looking at the output produced by my make activities vs your make activities leads me to suspect that you might have possibly installed some other packages.
>
>  
>
> I say this since my compile line on Android 6 has –DHAVE_FNMATCH and yours does not, but it does have –DHAVE_GLOB.  The makefile prefers using glob over readdir() and fnmatch(), but somehow your environment has glob() but is missing globfree() which should appear together.  I suggest that you uninstall termux and start over and install the specific packages (git, clang and make) and confirm that it actually works for you.  Looking closer on Android 10 I see that my compile line has –DHAVE_GLOB instead of the Android 6 –DHAVE_FNMATCH, so maybe termux has different package repositories based on the Android version and maybe the Android 8 version of the glob library is missing globfree().  If you still observe this problem after a minimal install, I suggest that you point out this problem as feedback to the termux package and they should be able to get on it quickly.
>
>  
>
> -          Mark
>
>  
>
> From: Alan Abbott [mailto:g1gop@yahoo.co.uk]
> Sent: Monday, October 21, 2019 12:00 AM
> To: Mark Pizzolato <Mark@infocomm.com>
> Subject: Re: [Simh] Simh on Android
>
>  
>
> 1) 8.0.0 (Samsung A5(2017))
>
> 2)?? $ uname -a Linux localhost 3.18.14-13712092-QB25741392 #1 SMP PREEMPT Fri Aug 30 19:46:22 KST 2019 aarch64 Android $
>
> 3) just installed all packages.
>
>  
>
> This is the output from make pdp8:
>
> make pdp8 libpaths are: /usr/lib /system/lib
> include paths are: /data/data/com.termux/files/usr/include/aarch64-linux-android /data/data/com.termux/files/usr/lib/clang/8.0.1/include /data/data/com.termux/files/usr/include using libm: /system/lib/libm.so using semaphore: /data/data/com.termux/files/usr/include/semaphore.h using libdl: /system/lib/libdl.so /data/data/com.termux/files/usr/include/dlfcn.h * * pdp8 Simulator being built with: * - compiler optimizations and no debugging support. clang version 8.0.1.
> * - Per simulator tests will be run. * * git commit id is 0de9b62850c03fc435cecfcc928f4dad65933ebe.
> * git commit time is 2019-10-18T23:18:39-0700.
> * gcc -std=c99 -U__STRICT_ANSI__ -O2 -fno-strict-overflow -finline-functions -DSIM_GIT_COMMIT_ID=0de9b62850c03fc435cecfcc928f4dad65933ebe -DSIM_GIT_COMMIT_TIME=2019-10-18T23:18:39-0700 -DSIM_COMPILER="clang version 8.0.1" -I . -D_GNU_SOURCE -D__ANDROID_API__=26 -DSIM_BUILD_OS=" On Android Version 8.0.0" -DHAVE_SEMAPHORE -DHAVE_SYS_IOCTL -DHAVE_LINUX_CDROM -DHAVE_DLOPEN=so -DHAVE_UTIME -DHAVE_GLOB PDP8/pdp8_cpu.c PDP8/pdp8_clk.c PDP8/pdp8_df.c PDP8/pdp8_dt.c PDP8/pdp8_lp.c PDP8/pdp8_mt.c PDP8/pdp8_pt.c PDP8/pdp8_rf.c PDP8/pdp8_rk.c PDP8/pdp8_rx.c PDP8/pdp8_sys.c PDP8/pdp8_tt.c PDP8/pdp8_ttx.c PDP8/pdp8_rl.c PDP8/pdp8_tsc.c PDP8/pdp8_td.c PDP8/pdp8_ct.c PDP8/pdp8_fpp.c scp.c sim_console.c sim_fio.c sim_timer.c sim_sock.c sim_tmxr.c sim_ether.c sim_tape.c sim_disk.c sim_serial.c sim_video.c sim_imd.c sim_card.c -I PDP8 -o BIN/pdp8 -lm -ldl
> /data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/tmp/sim_fio-d00378.o: in function `sim_dir_scan':
> sim_fio.c:(.text+0xf0c): undefined reference to `glob'
> /data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: sim_fio.c:(.text+0xfe4): undefined reference to `globfree'
> clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
> make: * [makefile:2161: BIN/pdp8] Error 1
> $
>
>  
>
>  
>
> On 20/10/2019 23:15, Mark Pizzolato wrote:
>
>     Hi Alan,
>
>      
>
>     On Sunday, October 20, 2019 at 2:06 PM, Alan Abbott wrote:
>
>         This is the error I get when running make:
>
>          
>
>          
>
>         sim_fio.c:(.text+0xf0c): undefined reference to `glob'
>
>         /data/data/com.termux/files/usr/bin/aarch64-linux-android-ld:
>
>         sim_fio.c:(.text+0xfe4): undefined reference to `globfree'
>
>         clang-8: error: linker command failed with exit code 1 (use -v to see
>
>         invocation)
>
>         make: *** [makefile:2134: BIN/pdp1] Error 1
>
>      
>
>     Several questions:
>
>      
>
>     1) What Android version are you working with?
>
>     2) What is the output of "uname -a"?
>
>     3) Did you just install termux (and the required packages) or had you installed any of these earlier?
>
>      
>
>     - Mark

**Comment by xeffyr** [comment]
>  sim_fio.c:(.text+0xf0c): undefined reference to `glob'

Patch makefiles to link with libandroid-glob.
