### ISSUE TITLE
Integrated/add-on/plugin VNC Client - Samsung DeX support.

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#1315]
**Feature description**
Termux would greatly benefit the addition of a built-in/add-on VNC client into it's tool set.
Termux's ability to run proot/chroot and the latest blow to the Dex community withthe loss of Linux on Dex development is a great opportunity to get this project started.

This would make Termux a one-stop shop for all that is needed to run a graphical environment, either within termux, or as a chroot/proot using only the app to do so.

No other VNC clients availaible seem to replicate the Linux on Dex experience and taking cues from what has already been done can surely benefit this usage scenario.

The only good VNC client I would currently use would Be the RealVNC one, but it does not support the Dex environment as it is touch only and it will surely not come to pass anytime soon even though the request for the resizable modification has been upvoted several times.

---

**Reference implementation**
Does another app/terminal emulator have this feature? No
Provide links to more background information: See anything that is Linux on Dex related for interface/GUI experience

**Comment by xeffyr** [comment]
The closest thing you are looking for is https://github.com/termux/termux-x11. It is not VNC though.

**Comment by nathaneltitane** [comment]
> The closest thing you are looking for is https://github.com/termux/termux-x11. It is not VNC though.

I've set up the termux x11-repo and got it to load and function adequately using a third-party VNC client - the idea would be to use a termux embedded vnc viewer to launch any kind of instance, be it termux environment or chroot.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-x11 - is Xwayland frontend and its purpose to make VNC no longer needed.

**Comment by nathaneltitane** [comment]
> https://github.com/termux/termux-x11 - is Xwayland frontend and its purpose to make VNC no longer needed.

Genius! So how would I go about in testing this?

**Comment by laem** [comment]
Meanwhile UserLand, once installed, lets you launch e.g. Firefox with one click (through bVnc for example).
It's far from perfect though, you'll have to manually replace tighvnc with tigervnc, and e.g. I can't get code-oss to launch. And the french keyboard doesn't work, you won't be able to use the Alt-Gr keys, essential for devs.

**Comment by MetalGearSolidNerd** [comment]
I am able to get code-oss to launch though not using UserLand.

Setup - TermuxArch in proot
Code-OSS
- Aarch64 build from headmelted (extracted the .deb file and used the binaries in standalone mode, proper way would be to create a PKGBUILD)
- Need to run as non-fakeroot user or pass --no-sandbox and --user-data-directory startup flag
- tightvnc was used as the X11 server

**Comment by lypanov** [comment]
I have great experiences using bVNC Pro on my Samsung S6 Tab.

**Comment by nathaneltitane** [comment]
you can achieve that with 'am start -a android.intent.action.VIEW -d vnc://localhost:{PORT}' in a scripted manner or other... no diss but projects like userland and anlinux are bloated and not entirely transparent as to the mechanics of their setup.... they require termux and a vnc viewer regardless, so might as well keep it open like [dextop](https://github.com/nathaneltitane/dextop)

**Comment by twaik** [comment]
I think this issue may be closed.

**Comment by agnostic-apollo** [comment]
termux-x11 developer saying we should not have termux-vnc :p

But yeah, out of scope unless someone writes an app.

**Comment by twaik** [comment]
> termux-x11 developer saying we should not have termux-vnc :p

I am only saying that one applicaion does not need to implement other application of completely other type as builtin. That should be implemented in different product.

**Comment by agnostic-apollo** [comment]
Yeah, termux org cannot provide everything, especially with 2-3 app devs.
