### ISSUE TITLE
proot permission denied

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#1316]
**Problem description**
when trying to chroot/proot in a directory other than the Termux environment (ex.: internal memory directory or external sdcard) proot operation fails witha  permission denied on --link2symlink.

**Steps to reproduce**
termux-setup-storage
cd storage/shared
wget https://raw.githubusercontent.com/Neo-Oli/termux-ubuntu/master/ubuntu.sh
bash ubuntu.sh

**Expected behavior**
completion of script without errors or failure as expected under termux home env.

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by xeffyr** [comment]
Shared storage (sdcard) doesn't support symlinks or executable permission.

**Comment by xeffyr** [comment]
There some work done for sdcard noexec workaround, but not released. Related issue - https://github.com/termux/proot/issues/50.
