### ISSUE TITLE
Termux api level

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#1317]
**Problem description**
Termux is not readily available to download for devices using Android 5 and above (API  21 +) for stock or non rooted devices that can still support development on Android or that meet performance requirements to run gui systems.

Some projects (i.e.: Anlinux) now require the use of termux to function but cannot do so when running prior versions of Android to the one currently supported.

**Steps to reproduce**
Use stock Nexus device running Android 5 or 6 and try to install termux. From playstore.

**Expected behavior**
Have app available, downloaded and fuully functional

**Additional information**
Post output of command `termux-info`. N/A too old to install

If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

![Screenshot_20191022-225036](https://user-images.githubusercontent.com/5674757/67352593-6a22cb80-f51e-11e9-839e-4ebdd58093bf.png)

**Comment by xeffyr** [comment]
We are moving towards dropping legacy Android support -- https://github.com/termux/termux-packages/issues/2874.

**Comment by xeffyr** [comment]
Seems app will receive updates for Android 5, we have branch https://github.com/termux/termux-app/tree/android-5 but v0.76 is not created for it.

***

Regarding repositories:

* https://github.com/termux/termux-packages  - currently has full legacy support.

* https://github.com/termux/unstable-packages - full legacy support which is going to be disabled in next several months.

* https://github.com/termux/x11-packages - limited legacy support which going to be disabled in next several months.

* https://github.com/termux/termux-root-packages - full legacy support.

* https://github.com/termux/science-packages - full legacy support.

* https://github.com/termux/game-packages - full legacy support.
