### ISSUE TITLE
dotnet core error

### ISSUE THREAD

**Issue by KoleckOLP** [termux/termux-app#1319]
After installing dotnet core with the "dotnet-install.sh -c Current" (or running a bindary file which includes all dependencies), you just get bash: "./dotnet : No such file or directory"

Even thoe the file is there.

shouldn't this work? Is there something I can do to get dotnet core linux-arm apps running on my phone (Armv7l it's arm32 which is suported by dotnet core)

Oh my phones architecture is "arm" not "armhf" nor "armel"

Please help me anyone

**Comment by xeffyr** [comment]
This just ABI incompatibility.
Program must be compiled for Android with NDK in order to be executed in Termux.
