### ISSUE TITLE
include .hushlogin in termux environment as default

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#1321]
**Feature description**
add .hushlogin to termux env to come into a clean prompt. errors could be relocated
addresses chroot grouid errors and others

**Reference implementation**
Does another app/terminal emulator have this feature?
Provide links to more background information

**Comment by xeffyr** [comment]
Hushlogin has special meaning for termux: https://github.com/termux/termux-packages/blob/master/packages/termux-tools/login#L3.

Since we don't want to disable motd by default - wontfix.
