### ISSUE TITLE
Crashed after an update.

### ISSUE THREAD

**Issue by DebianLynx** [termux/termux-app#1327]
**Problem description**
It couldn't enter the command line after an update by Google play.

**Steps to reproduce**
Update termux from 0.75 to 0.76.

**Expected behavior**
Act normally as it should be.

**Additional information**

CANNOT LINK EXECUTABLE "cat": library "libandroid-support.so" not found
Aborted
CANNOT LINK EXECUTABLE "realpath": library "libandroid-support.so" not found
Aborted
/data/data/com.termux/files/usr/bin/login: 27: exec: : Permission denied

[Process completed (code 126) - press Enter]

**Comment by xeffyr** [comment]
Add via failsafe shell
```
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
```
to `~/.bashrc`.

That's not a bug. Just incompatibility with legacy environment, i.e. packages installed from `termux.net` or `https://mirrors.tuna.tsinghua.edu.cn/termux/`.

**Comment by gemini4545** [comment]
> Add via failsafe shell
> 
> ```
> export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
> ```
> 
> to `~/.bashrc`.
> 
> That's not a bug. Just incompatibility with legacy environment, i.e. packages installed from `termux.net` or `https://mirrors.tuna.tsinghua.edu.cn

> Add via failsafe shell
> 
> ```
> export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
> ```
> 
> to `~/.bashrc`.
> 
> That's not a bug. Just incompatibility with legacy environment, i.e. packages installed from `termux.net` or `https://mirrors.tuna.tsinghua.edu.cn/termux/`.

what's the failsafe shell and where/how to find it? thanks.

**Comment by gemini4545** [comment]
> Add via failsafe shell
> 
> ```
> export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
> ```
> 
> to `~/.bashrc`.
> 
> That's not a bug. Just incompatibility with legacy environment, i.e. packages installed from `termux.net` or `https://mirrors.tuna.tsinghua.edu.cn/termux/`.

what's the failsafe shell and where/how to find it? thanks.

**Comment by xeffyr** [comment]
1. Via application shortcut.

2. Via drawer -> hold new session button -> failsafe

**Comment by gemini4545** [comment]
>     2. Via drawer -> hold new session button -> failsafe

I opened the failsafe shell, but I can't add the code to ~/.bashrc becuase there is no vi or vim command in this mode. I used  '>>' to add but I'm not sure whether it's successful cause there is no cat or more etc. as well. 
After restart the termux, still the same error.

**Comment by gemini4545** [comment]
>     1. Via application shortcut.
> 
>     2. Via drawer -> hold new session button -> failsafe

I've add it to ~/.bashrc successfully, but the termux still has the same error. how to deal with this? 
Thank you

**Comment by langrenfengzi** [comment]
I have the same issue after upgrade to v0.82.   I forgot from which version.
"**LD_LIBRARY_PATH**" fix doesn't work for me. 

[**rm -rf $PREFIX** ](https://github.com/termux/termux-app/issues/1307) worked.
But I have to reinstall all the commands, I can't remember them, and the poor download speed. :(
