### ISSUE TITLE
File format not recognized   ?

### ISSUE THREAD

**Issue by CMingTseng** [termux/termux-app#1329]
Dear Sir

i use  termux-termux-packages && termux/termux-packaging

i get 540 deb files

when packaging 

i get 

[*] Extracting 'libandroid-support'...
ar: package.deb: File format not recognized

THX

**Comment by xeffyr** [comment]
> termux-termux-packages && termux/termux-packaging

I didn't know what you tried to do but instructions from https://github.com/termux/termux-packages/wiki/For-maintainers#generating-bootstrap-archives works fine as soon as your host is Linux-based (e.g. Ubuntu or ArchLinux).

**Comment by xeffyr** [comment]
[![asciicast](https://asciinema.org/a/kZ0yNyYoX41wQQHwZ4CBya2xX.svg)](https://asciinema.org/a/kZ0yNyYoX41wQQHwZ4CBya2xX)

Everything works. Just make sure:

* You have properly configured APT repository and it has `*.deb` (deb 2.0 binary Debian archive) packages. You have no other choice there as only proper APT repository provides enough metadata for tracking dependencies.
* You are running bootstrap script on Linux-based host.

Bootstrap script shouldn't be modified. There just no point of making this as its behaviour can be changed with options:
```
 -a, --add PKG_LIST          Specify one or more additional packages
                             to include into bootstrap archive.
                             Multiple packages should be passed as
                             comma-separated list.

 --architectures ARCH_LIST   Override default list of architectures
                             for which bootstrap archives will be
                             created.
                             Multiple architectures should be passed
                             as comma-separated list.

 -p, --prefix PATH           Specify rootfs prefix absolute path.
                             Should be exactly same as in packages
                             in the remote repository.

 -r, --repository URL        Specify URL for APT repository from
                             which packages will be downloaded.
```
Though, prefix option is not freely configurable as should match prefix used in packages.

**Comment by CMingTseng** [comment]
> [![asciicast](https://camo.githubusercontent.com/c7519af8b2faf66c76edb1a0300435d11e8e12e0/68747470733a2f2f61736369696e656d612e6f72672f612f6b5a30794e79596f58343177515148775a34434279613278582e737667)](https://asciinema.org/a/kZ0yNyYoX41wQQHwZ4CBya2xX)
> 
> Everything works. Just make sure:
> 
> * You have properly configured APT repository and it has `*.deb` (deb 2.0 binary Debian archive) packages. You have no other choice there as only proper APT repository provides enough metadata for tracking dependencies.
> * You are running bootstrap script on Linux-based host.
> 
> Bootstrap script shouldn't be modified. There just no point of making this as its behaviour can be changed with options:
> 
> ```
>  -a, --add PKG_LIST          Specify one or more additional packages
>                              to include into bootstrap archive.
>                              Multiple packages should be passed as
>                              comma-separated list.
> 
>  --architectures ARCH_LIST   Override default list of architectures
>                              for which bootstrap archives will be
>                              created.
>                              Multiple architectures should be passed
>                              as comma-separated list.
> 
>  -p, --prefix PATH           Specify rootfs prefix absolute path.
>                              Should be exactly same as in packages
>                              in the remote repository.
> 
>  -r, --repository URL        Specify URL for APT repository from
>                              which packages will be downloaded.
> ```
> 
> Though, prefix option is not freely configurable as should match prefix used in packages.
@xeffyr 
Dear Sir 

Very thx

This is my step 

1. i clone termux/termux-packages

2. install docker and run  ./scripts/run-docker.sh

3. interactive @ Docker   ---   use  ./build-all.sh . get 540 deb files !! <-- but packages folder has 650 package folder !!   i lost ?

4. after  get 540 deb files i run i modify generate-bootstraps.sh (modify prefix & repository )

5.  i get error   --- package.deb: File format not recognized 

but i can not find package.deb

[https://i.imgur.com/RyuDm6V.png](url)

THX

root@5377a29617ff:/ubuntutmp# ./generate-bootstraps.sh
[*] Downloading package list for architecture 'all'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  133k  100  133k    0     0   238k      0 --:--:-- --:--:-- --:--:--  238k
[*] Reading package list for 'all'...
[*] Downloading package list for architecture 'aarch64'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  133k  100  133k    0     0   384k      0 --:--:-- --:--:-- --:--:--  383k
[*] Reading package list for 'aarch64'...
[*] Downloading 'libandroid-support'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   166    0   166    0     0    230      0 --:--:-- --:--:-- --:--:--   230
100 63365    0 63365    0     0  40854      0 --:--:--  0:00:01 --:--:--  150k
[*] Extracting 'libandroid-support'...
ar: package.deb: File format not recognized

**Comment by xeffyr** [comment]
> but i can not find package.deb

Files are stored in folder `/tmp/bootstrap-tmp.{many random characters}`.

**Comment by xeffyr** [comment]
I see steps about building deps & generating bootstraps... In which you creating APT repository ?
