### ISSUE TITLE
Option to run as overlay

### ISSUE THREAD

**Issue by ghost** [termux/termux-app#133]
sometimes it would be pretty cool to have the terminal emulator in an overlay like for example
   https://github.com/jgilfelt/GhostLog

**Comment by Neo-Oli** [comment]
[Termux:Float](https://play.google.com/store/apps/details?id=com.termux.window) does this. Does this fit your need?

**Comment by rgh36167** [comment]
seems slightly different, alpha blended full screen overlay to keep an eye watch whether something interesting is happening in the background. Especially useful over the lockscreen.
