### ISSUE TITLE
svn checkout isn't working on internal storage

### ISSUE THREAD

**Issue by WanderingRonin** [termux/termux-app#1335]
$svn checkout https://github.com/hrydgard/ppsspp/trunk/assets
svn: E000001: Unable to create pristine install stream
svn: E000001: Can't set permissions on '/storage/emulated/0/download/assets/.svn/tmp/svn-xuFmvo'
svn: E000001: Can't set permissions on '/storage/emulated/0/download/assets/.svn/tmp/svn-xuFmvo': Operation not permitted

This is what I get each time I run this command, after I did the standadd termux-storage-setup, can anyone help me?

**Comment by Grimler91** [comment]
It isn't possible to have executable files in the shared storage. Nothing we can do about this.
