### ISSUE TITLE
mtr: Failed to resolve host: rw: Name or service not known

### ISSUE THREAD

**Issue by butterl** [termux/termux-app#1336]
**Problem description**
the mtr running in termux returns mtr: Failed to resolve host: rw: Name or service not known both on ip and web urls

**Steps to reproduce**
1. install mtr after install root repository
2. mtr show  ip_address

**Expected behavior**
mtr could show trace information on termux

**Additional information**
mtr: Failed to resolve host: rw: Name or service not known

**Comment by xeffyr** [comment]
Are you running it under root ?

**Comment by xeffyr** [comment]
> mtr: Failed to resolve host: rw: Name or service not known

Just host `rw` does not exist, so it cannot be resolved.
Not a bug.

**Comment by butterl** [comment]
It returns same kind of error puting [option] as rw, show , and report.  
The mtr command works well while using same phone to sharing network with a ubuntu 18.04 machine， and only the mtr running in termux seems return the error "Failed to resolve host: XXX : No address associated with hostname"  

looks like mtr treating ip to url and need a dns resolve？
