### ISSUE TITLE
Left/right cursor keys to move the cursor in the shell

### ISSUE THREAD

**Issue by terr72** [termux/termux-app#1345]
**Feature description**
Everybody knows this situation: you type in a very long command and suddenly you realise you made a typo or you want to change a command from the bash history.
In a regular environment, you go back/forward with the left/right cursor keys on your keyboard.
It would be nice to have left/right cursors keys as well and/or a possibility to move the cursor by tapping on a certain position.

**Comment by xeffyr** [comment]
> It would be nice to have left/right cursors keys

Covered by https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row(s).

> possibility to move the cursor by tapping on a certain position.

Some text editors support this behaviour when mouse support is turned on in their configuration.

Or you need that feature added to whole terminal ? That will have *bad effects*...

**Comment by terr72** [comment]
Oops, thank your for that link. I was under the impression the extra key rows are hardcoded.

Regarding the tapping issue: which editors support this? I've tried vi, nano and the internal editor of MC with no avail.

**Comment by xeffyr** [comment]
`vi` - is from busybox. Never supported mouse.
`vim` - supports mouse, but I'm unsure about taps.
`nano` - supports mouse and taps. Launch: `nano -m`.
`micro` - supports mouse and taps.

Not sure about others.

**Comment by snogglethorpe** [comment]
FWIW, Emacs supports the mouse fully (tapping, dragging, etc) if "xterm-mouse-mode" is enabled.

This suggests that termux uses the xterm mouse protocol, so I'd guess anything which works on a normal xterm should work on termux....
