### ISSUE TITLE
can develop a termux app store and create python ,c,java,vim ,jupyter icons on andriod screen and click the icons to start python, vim linux apps?

### ISSUE THREAD

**Issue by ZihaoXingstudy** [termux/termux-app#1348]
can develop a termux app store and create python ,c,java,vim ,jupyter icons on andriod screen and click the icons to start python, vim linux apps?
Termux should  build a termux software store, users can install c, c++, java, python, vim, jupyter notebook, php, R and other software from the termux software store, and generate icons for these software on Android phones and Android tablet desktops. Users can directly click on these linux software icons such as python, vim, java, etc. to start the installation of linux software. The system that integrates Android app store and linux app store will become the best operating system, which can surpass windows, macos, ios and other systems.

**Comment by xeffyr** [comment]
Termux is and remains be **linux terminal emulator**.
