### ISSUE TITLE
Move ctrl key to the left or to the right in extra keys row

### ISSUE THREAD

**Issue by memeplex** [termux/termux-app#135]
Ctrl seems to be strategically located so that my finger will hide the command line when doing ctrl-p/ctrl-n to navigate history. Am I the only one experiencing this? Is my finger too fat?

**Comment by Quasic** [comment]
I think this was addressed by the recent update to the Extra Keys Row...

**Comment by xeffyr** [comment]
Since extra keys are configurable (details on https://wiki.termux.com/wiki/Touch_Keyboard), it should be quite easy to move ctrl key to place where needed.
