### ISSUE TITLE
dark theme support

### ISSUE THREAD

**Issue by 532910** [termux/termux-app#1351]
Please add support for dark theme:
![image](https://user-images.githubusercontent.com/14617699/69095651-d502ec00-0a63-11ea-9fed-98f9c921b325.png)
![image](https://user-images.githubusercontent.com/14617699/69095916-5e1a2300-0a64-11ea-9a5a-26d08388a121.png)
![image](https://user-images.githubusercontent.com/14617699/69096015-99b4ed00-0a64-11ea-8566-becd6fb0a126.png)

**Comment by xeffyr** [comment]
Already added in https://github.com/termux/termux-app/pull/1293.

**Comment by xeffyr** [comment]
Put `use-black-ui = true` to `$HOME/.termux/termux.properties`.

**Comment by 532910** [comment]
It works, but
1. not not fine:
![image](https://user-images.githubusercontent.com/14617699/69099297-76417080-0a6b-11ea-9794-157fb73bd144.png)
2. it should get default value from the system settings.
3. it should be configured via menu

**Comment by xeffyr** [comment]
> it should be configured via menu

In Termux all settings configured via `termux.properties`.

**Comment by 532910** [comment]
>    Not all OS versions have dark theme in systemn settings.
    Sometimes dark theme in app is not desirable even if system theme is dark.

Nothing wrong here. It's just a default setting that can be overwritten via `termux.properties`.

**Comment by 532910** [comment]
What about [1], should this issue be reopened?
