### ISSUE TITLE
[Question] How to install wordpress?

### ISSUE THREAD

**Issue by MS-Jahan** [termux/termux-app#1352]
I was wondering if I could install Wordpress in Termux. I've tried Wordpress on Ubuntu before, but Termux is different. I couldn't find any article or video showing installation process for Wordpress in Termux. So, how to achieve that?

Sorry for bad English. Any help will be greatly appreciated.

**Comment by xeffyr** [comment]
See https://wiki.archlinux.org/index.php/Wordpress.
The only difference will be used paths as Termux uses `/data/data/com.termux/files/usr` as rootfs.
