### ISSUE TITLE
App install location

### ISSUE THREAD

**Issue by VitaliyKulikov** [termux/termux-app#1360]
**Feature description**

I need to install application on external storage. I am limited with internal on Android TV.

**Reference implementation**

To allow the system to install your application on the external storage, modify your manifest file to include the **android:installLocation** attribute in the **<manifest>** element, with a value of either "_preferExternal_" or "_auto_". For example:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    android:installLocation="preferExternal"
    ... >
```

[App install location](https://developer.android.com/guide/topics/data/install-location)

**Comment by xeffyr** [comment]
External install location is unsupported by design.
