### ISSUE TITLE
Infinite times "y" spam

### ISSUE THREAD

**Issue by av1choudhary** [termux/termux-app#1367]
**Problem description**
Open termux, enter "yes"(y not Y) and press enter.
y will start flooding the screen.

**Expected behavior**
"yes" is not recognised as an internal or external command.

**Comment by AbdullahM0hamed** [comment]
This isn't really an issue. "Yes" is a command, and the infinite spam of y is the default output.

Also, why would you run it, expecting it to do nothing?


An accident makes sense, simply Ctrl + C, and don't use it again, unless you need it.

**Comment by av1choudhary** [comment]
I accidentally pressed yes after a failed command. But expected output should be something else. That's what i am saying. Anyways this doesn't disturbs the functionality of termux. Just to inform. 🙂

**Comment by av1choudhary** [comment]
@

**Comment by trygveaa** [comment]
> But expected output should be something else.

@av1choudhary: No, the output shouldn't be something else, this is the expected output. See http://man7.org/linux/man-pages/man1/yes.1.html
