### ISSUE TITLE
Th3inspector permision denided

### ISSUE THREAD

**Issue by RamadhanP** [termux/termux-app#1368]
Can't locate HTTP/Request.pm in @INC (you may need to install the HTTP::Request module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.0 /data/data/com.termux/files/usr/lib/perl5/5.30.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.30.0 .) at Th3inspector.pl line 5.
BEGIN failed--compilation aborted at Th3inspector.pl lin

**Comment by Grimler91** [comment]
you need to install the http::request module through cpan or cpanm.
