### ISSUE TITLE
bash  bad interpreter :No such file or directory

### ISSUE THREAD

**Issue by CMingTseng** [termux/termux-app#1369]
Dear Sir

1. i change the applicationId : not  com.termux

2. so  i builded & use our prefix  bootstrap 

3. i finish install . basic system  get the env

But ...

i want  run some shell script 

like :  install_golang.sh / install_python.sh/.....

i  use this command .  under . $

like this :

S ./install_golang.sh

i get error message . :  

bash ./install_golang.sh : /bin/bash: bad interpreter : No such file or directory

when change to 

S  ../usr/bin/bash  ./install_golang.sh

then shell script can run !!!

_____ . the same shell script i use oem version termux___

i can direct run . ./install_golang.sh

THX

**Comment by xeffyr** [comment]
Either use proper shebangs or patch the https://github.com/termux/termux-exec/blob/master/termux-exec.c#L1.
