### ISSUE TITLE
Unstable and x11 repo not working

### ISSUE THREAD

**Issue by oscarpoudel** [termux/termux-app#1370]
![Screenshot_2019-12-10-00-59-09-504_com termux](https://user-images.githubusercontent.com/56015125/70641542-e788d380-1c65-11ea-98bb-beca79c7c9b8.png)

**Steps to reproduce**
I just installed termux ...installed root repo ...but unstable repo not working

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/4467#issuecomment-546736733

**Comment by Mhowser** [comment]
@xeffyr how can I remove the unstable repo? I can't update.
![Screenshot_20200322-040819](https://user-images.githubusercontent.com/24195572/77247936-fda61880-6bf2-11ea-9eca-c602a4895858.png)
