### ISSUE TITLE
Should ask for permission to access storage

### ISSUE THREAD

**Issue by alleluia20** [termux/termux-app#1371]
**Problem description**
After installing Termux, I could not see any files ("ls -l" returned "access denied"). I thought it was a grave bug of Termux but, after googling, I discovered that I had to manually grant permission to access storage (Settings -> Apps -> Termux -> Permissions). Virtually all Android apps ask for the permission (using a pop up) when that permission is needed.

**Steps to reproduce**
Cd to any directory that you can see in Android (for example, Downloads). Run "ls -l" and you get "access denied" (unless you have manually granted Termux the permission to access the storage).

**Expected behavior**
Should display a pop up asking for the permission, as virtually all Android apps do. Alternatively, this could be done the old way (asking for the permission at the moment of installing Termux), but this would be old-fashioned.

If no request for the permission is displayed, many (probably most) users will not realise that they have to grant the permission manually, so they will not be able to use Termux.

**Comment by xeffyr** [comment]
This is done via `termux-setup-storage` which already described on wiki at relevant page.
