### ISSUE TITLE
Cannot run in Samsung secure folder

### ISSUE THREAD

**Issue by Yajo** [termux/termux-app#1373]
**Problem description**
I own a samsung tablet and I would find it very useful to run Termux inside its secure folder, where apps are only unlocked after a fingerprint. For example I can leave my ssh key unencrypted as long as the whole termux app is protected, saving me many password typing.

However, a dialog says: **Unable to install. Termux can only be installed on the primary user account.**

**Steps to reproduce**
1. Buy a Samsung tablet.
1. Enter secure folder.
1. Install Termux there.
1. Open it there.

**Expected behavior**
Be able to run it in secure folder.

**Additional information**
This is run outside of secure folder:

```
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.112-16982790 #2 SMP PREEMPT Thu Oct 17 19:12:11 KST 2019 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T720
```

**Comment by xeffyr** [comment]
Yes, Termux can be installed as only primary user, which excludes sandboxes and work profiles.

Application expects that installation path is predefined (/data/data/com.termux/files/usr, otherwise package environment will be broken) and device user is `owner` (otherwise java-based utilities like termux-api will not work).

**Comment by Yajo** [comment]
Hmm ok, do we have any solution for the password typing? Mostly for SSH keys. Protecting those with fingerprint would be very helpful.
