### ISSUE TITLE
python command history not working

### ISSUE THREAD

**Issue by v-python** [termux/termux-app#1375]
Installed Termux. Installed Python (3). Gave Termux storage permission.

Run an interactive Python script. it works! Yay!

But the nice up-arrow above the keyboard causes the python program to get fed an escape sequence rather than selecting the previous command for re-execution or editing (re-execution works in the Termux shell, I haven't figured out editing)

Is this an Android limitation? A porting issue? A need to download a package? A bug? I Googled quite a bit without finding useful results.

An attempt to pip install readline failed to find /bin/hash

If my newbie status is the cause of this confusion, please point me to an appropriate forum.

**Comment by xeffyr** [comment]
Command line editing works perfectly for both python 3 command line and `input()` function.

**Comment by v-python** [comment]
I'm glad to hear  command line editing works.

That doesn't help with why it doesn't work for me, and it gives me no pointers to either documentation for configuring the feature, or a help forum, neither of which I could find by googling.

It doesn't work for me, on Android 10, Pixel 3A, with either the Gboard or Hacker's keyboard. Where do I look next?

**Comment by xeffyr** [comment]
> Where do I look next?

1. You did't filled bug report template properly.

2. You did't provide any snippets of code where "command line editing" does not working.

No one knows what is happening by your *abstract* description of the issue.

**Comment by v-python** [comment]
It's a simple command line program that calls input to get each line. Very basic. And at the prompt produced by input, first I enter some input, and get the expected output, and another prompt. I tap the up-arrow above the keyboard (which does work at the shell prompt) and I get a character sequence display after my program's prompt that looks like   ^[[A  (which I would interpret as a terminal escape sequence).

**Comment by v-python** [comment]
![Screenshot_20191213-155908](https://user-images.githubusercontent.com/3078240/70839529-ec629a00-1dc1-11ea-90e1-9c370278cf65.png)

**Comment by xeffyr** [comment]
>It's a simple command line program that calls input to get each line. Very basic. And at the prompt produced by input, first I enter some input, and get the expected output, and another prompt.

I have asked for **code snippet**.
By that description, there a lot variants how your program can be written.

**Comment by v-python** [comment]
It's a very basic program regarding I/O, but is 7MB of data and logic embedded. I'll work on a snippet.

**Comment by xeffyr** [comment]
You can't post part where input is read ?

**Comment by v-python** [comment]
![Screenshot_20191213-161321](https://user-images.githubusercontent.com/3078240/70839830-8e36b680-1dc3-11ea-8909-3d500f0e2bf3.png)


Here's snippet.py to go with the screen shot.  This is VERY basic.
while True:
    line = input('foo> ').split()
    print( f'{line=}' )
    if line[ 0 ] == 'exit':
        exit()

**Comment by v-python** [comment]
> while True:
    line = input('foo> ').split()
    print( f'{line=}' )
    if line[ 0 ] == 'exit':
        exit()

**Comment by v-python** [comment]
Well, I don't know how to convince github to preserve the indentation.

**Comment by v-python** [comment]
`while True:
    line = input('foo> ').split()
    print( f'{line=}' )
    if line[ 0 ] == 'exit':
        exit()
`

There, insert code did it.
The top of the screenshot above, was when I first extracted a while loop out of the code and left it indented one level. I unindented it, and produced the above, and the bottom part of the screen shot shows the result.

While the up arrow and down arrow above the keyboard are pretty obvious and work to scroll the command history, even in the shell I have no idea how to edit the command, other that backspace and type. Is there a way to move the cursor and edit in the middle of the command line? Tapping in the command line doesn't move the block cursor. There's a double-headed left-right arrow, but no clue what it is supposed to do, on my system, it seems to list all the files in the current directory, like ls

**Comment by v-python** [comment]
Well, github doesn't show you how what you do is going to look after you click Comment. Insert code didn't preserve it either.

**Comment by v-python** [comment]
And I can't paste in a .py file either.

**Comment by xeffyr** [comment]
Line editing is enabled only in interactive mode. In script it should be enabled manually by just importing `readline`:
``` .py
import readline

while True:
    line = input("foo> ")
    print( f'{line=}' )
    if line[ 0 ] == 'exit':
        exit()
```

**Comment by v-python** [comment]
I'm happy to do that, but I never had to do it on Windows. I'll give it a try.

**Comment by xeffyr** [comment]
That's specific to *nix systems.

**Comment by v-python** [comment]
back when I worked on *nix, I was still using Perl for scripting, I acquired a python taste after moving to Windows, and although I have a bunch of Python code running on my web server, it isn't interactive via an input() loop!

Documented where? Python docs? Or termux? I'd love to find more documentation for termux.

And the line editing? Is it only via backspace and retype? No corrections in the middle of the line?

import readline  cured the command history scrolling... and breaks on Windows, so I'll have to make it conditional.

**Comment by xeffyr** [comment]
>Documented where?

On https://docs.python.org/3.8/library/functions.html#input:
```
If the readline module was loaded, then input() will use it to provide elaborate line editing and history features.
```

> I'd love to find more documentation for termux.

Python already provides reasonable amount of documentation. For input() it can be accessed with:
```
python
help(input)
```

Also, we don't want to duplicate already existing and correct documentation. Termux-specific docs are located on https://wiki.termux.com/wiki/Main_Page but package-specific information should be obtained either from manpages or the official web pages.

> And the line editing? Is it only via backspace and retype? No corrections in the middle of the line?

Read the docs for readline module.

**Comment by xeffyr** [comment]
And for readline, https://docs.python.org/3.8/library/readline.html#module-readline.
