### ISSUE TITLE
Ability to access OTG USB Storage

### ISSUE THREAD

**Issue by rgazapo** [termux/termux-app#1376]
**Feature description**
Since Termux have the ability to access local storage via 'termux-setup-storage', I want to request extend this, to create shorcut to access OTG USB storage, normally created on /mnt/media_rw/[device_id]

This would be very usseful, in my case to make rsync from local storage to external USB drive like a backup

**Reference implementation**
Does another app/terminal emulator have this feature?
I don't think so

Provide links to more background information
https://wiki.termux.com/wiki/Termux-setup-storage
https://github.com/termux/termux-app/issues/157

**Comment by xeffyr** [comment]
Termux cannot pass SAF-based storage access to command line programs.
Closing.

**Comment by xeffyr** [comment]
It is possible to access only Termux private dir, e.g `/storage/xxxx-xxxx/Android/data/com.termux` for external sdcard & usb sticks or hdd.

**Comment by rgazapo** [comment]
To me it's working like your wiki page state:

$ cd ~
$ pwd
/data/data/com.termux/files/home
$ ls
storage
$ cd storage/
$ ls
dcim  downloads  movies  music	pictures  shared
$ ls -l
total 0
lrwxrwxrwx 1 u0_a193 u0_a193 24 Dec 13 09:04 dcim -> /storage/emulated/0/DCIM
lrwxrwxrwx 1 u0_a193 u0_a193 28 Dec 13 09:04 downloads -> /storage/emulated/0/Download
lrwxrwxrwx 1 u0_a193 u0_a193 26 Dec 13 09:04 movies -> /storage/emulated/0/Movies
lrwxrwxrwx 1 u0_a193 u0_a193 25 Dec 13 09:04 music -> /storage/emulated/0/Music
lrwxrwxrwx 1 u0_a193 u0_a193 28 Dec 13 09:04 pictures -> /storage/emulated/0/Pictures
lrwxrwxrwx 1 u0_a193 u0_a193 19 Dec 13 09:04 shared -> /storage/emulated/0

If you can create a reference to "/storage/emulated/0" on shared 

Why can not be created a link to "/mnt/media_rw/[DEVICE-ID]" ?

Other apps with just storage request get access to that location

**Comment by xeffyr** [comment]
>Why can not be created a link to "/mnt/media_rw/[DEVICE-ID]" ?

I have answered why - `It is possible to access only Termux private dir, e.g /storage/xxxx-xxxx/Android/data/com.termux`.

**Comment by xeffyr** [comment]
Try rm `~/storage`, plug in the USB stick and execute `termux-setup-storage` again. It should create link like `~/storage/external-1` which will point to Termux dir on external storage.

**Comment by jayaramvgc** [comment]
> Try rm `~/storage`, plug in the USB stick and execute `termux-setup-storage` again. It should create link like `~/storage/external-1` which will point to Termux dir on external storage.

tried.. no external-1 appeared. Instead, the existing one before executing 'termux-setup-storage' is gone

**Comment by jayaramvgc** [comment]
otg usb drive access from commandline will be very useful pl suggest alternative solution
