### ISSUE TITLE
...cann't locate symbol "__aeabi_memcpy"...

### ISSUE THREAD

**Issue by King-1025** [termux/termux-app#1380]
My Phone is XIAO MI NOTE. 
When I used APT command to update and upgrade packages, the process was shutted down by  "...cann't locate symbol __aeabi_memcpy..." of error message. 
A shared library named "libiconv.so" seems like LINK FAILED! Would U like to help ME? My brother, Thanks!🌹

`$ termux-info` 
```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
Updatable packages:
All packages up to date
Android version:
6.0.1
Kernel build information:
Linux localhost 3.4.0-gf4b741d-00690-gc8911e2 #1 SMP PREEMPT Thu Dec 28 23:45:24 CST 2017 armv7l Android
Device manufacturer:
Xiaomi
Device model:
MI NOTE LTE
```

**Comment by xeffyr** [comment]
1. Try to reinstall Termux.
2. Post output of `termux-info` here.

**Comment by King-1025** [comment]
Because of GFW's restriction, the network is always so terrible. I have modified official software source, instead of software source of Tsinghua.
Here is it: `https://mirrors.tuna.tsinghua.edu.cn/termux/`
I'm not sure that there is a problem in the software source.

**Comment by xeffyr** [comment]
@King-1025 This mirror mixes package versions and some of them are too outdated. It is not safe to upgrade with that mirror, especially due to changes we did recently.

I have attached list with all version mismatches detected for that mirror: 
[version-mismatch.txt](https://github.com/termux/termux-app/files/3965325/version-mismatch.txt)

**Comment by xeffyr** [comment]
It also very interesting why it mixes packages from both https://termux.net and http://dl.bintray.com/termux/termux-packages-24/.

**Comment by xeffyr** [comment]
Repository `https://mirrors.tuna.tsinghua.edu.cn/termux/` is incompatible with your device.

**Comment by King-1025** [comment]
I got it, thank u!

**Comment by King-1025** [comment]
I am going to report these problems to maintainers of the mirror repository.


Thank you for your help.


---Original---

**Comment by King-1025** [comment]
As a Chinese, I think it's Chinese laziness.




---Original---

**Comment by King-1025** [comment]
As a Chinese, I think it's Chinese laziness.


---Original---

**Comment by King-1025** [comment]
I am going to report these problems to maintainers of the mirror repository.



Thank you for your help.



---Original---
