### ISSUE TITLE
Variables problem

### ISSUE THREAD

**Issue by gitsrk** [termux/termux-app#1381]
when i use \W veriable on ps1 prompt there is problem  after i write long command thet repeat on same line
**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by gitsrk** [comment]
my issue is when i use ps1 prompt to custmization i add \W veriable and then i open new seassion then i write any long command  exp: 123456 when it come to 7 word thet comand start on thet same  line like 723456

**Comment by Grimler91** [comment]
Which PS1 are you using?

**Comment by xeffyr** [comment]
Make sure you are enclosed non-printable characters between `\[` and `\]` correctly.

https://unix.stackexchange.com/questions/105958/terminal-prompt-not-wrapping-correctly

**Comment by gitsrk** [comment]
> Which PS1 are you using?

PS1='\033[1;91m nitro@termux[\033[1;93m\W\033[1;91m]:# \033[1;92m'

**Comment by xeffyr** [comment]
Should be:
```
PS1='\[\033[1;91m\] nitro@termux[\[\033[1;93m\]\W\[\033[1;91m\]]:# \[\033[1;92m\]'
```

Bash calculates prompt length by characters in PS1. It knows nothing about `\033[1;91m` and treats it as word. As result, your prompt will be wrapped before cursor will reach its real end.

Enclose escape sequences between `\[` and `\]`.

From [bash reference](http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Controlling-the-Prompt):
* `\[`
   Begin a sequence of non-printing characters. This could be used to embed a terminal control sequence into the prompt. 

* `\]`
   End a sequence of non-printing characters.

**Comment by gitsrk** [comment]
Thnkx for information my problem is solved👍👍
