### ISSUE TITLE
emacs tramp mode gives error about /bin/sh

### ISSUE THREAD

**Issue by shivsoji** [termux/termux-app#139]
error:

emacs: /bin/sh: No such file or directory

tried this but not working:

(setq shell-file-name "/data/data/com.termux/files/usr/bin/bash")

**Comment by fornwall** [comment]
Hi! As I'm not an emacs user myself, could you give exact steps how to reproduce?

**Comment by shivsoji** [comment]
in emacs,  dired mode with this command
C-x d 
And some remote host
/user@host:/dir

Gives above error

**Comment by fornwall** [comment]
@shivsoji Thanks a lot for the descriptive problem report!

This has been fixed in version `25.0.95-2` of the emacs package, to which you can update with

    apt update && apt upgrade

**Comment by shivsoji** [comment]
Thanks
