### ISSUE TITLE
pip3 update question

### ISSUE THREAD

**Issue by beskhu3epnm** [termux/termux-app#1391]
Hi. Sorry if this is a stupid question. I installed `pip3 install totalsize` a few weeks ago, but running the same line again does not update the script. `pkg list-all totalsize` doesn't show the script. I'm not sure how to go about updating it, or removing it to install it fresh. Can you help?

**Comment by xeffyr** [comment]
Pip packages should be upgraded with
```
pip3 install --upgrade <package name>
```

> pkg list-all totalsize

pkg will not show any python modules installed with `pip`.

**Comment by beskhu3epnm** [comment]
Much appreciated.
