### ISSUE TITLE
What is Legacy env?

### ISSUE THREAD

**Issue by llllllllqq** [termux/termux-app#1393]
My motd says:
You are using legacy Termux environment.
Packages are unmaintained and will not
receive any updates.

What can I do?

Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-21 root stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages-21 x11 main
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages-21 unstable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Wed Oct 23 21:35:26 CST 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 5

**Comment by xeffyr** [comment]
All Termux installations using
```
deb https://termux.net stable main
```
as package repository are considered as **legacy environment**.

I see that your Android OS version is 9 so you may update to a normal one with `termux-upgrade-repo`.

Support for legacy environment is dropped in ~1.5 weeks.

**Comment by xeffyr** [comment]
See https://github.com/termux/termux-packages/issues/4467.

**Comment by sidahmed44478** [comment]
hi xeffyr
 i did with `termux-upgrade-repo` and it runs without any error . but even i restart termux after that i stil cant install metasploit with `apt insall unstable-repo && apt install metasploit`
i have samsung galaxy m30s android 9 
any ideas ?

**Comment by Mhowser** [comment]
You have a typo in your install command. that must be why.

**Comment by xeffyr** [comment]
@Mhowser Not a typo. Unstable repo compatible with Android 5 is no longer available.

**Comment by zai1213** [comment]
You are using legacy termux environment .package are unmaintained and will not receive any update.  What we can do?

**Comment by kcubeterm** [comment]
> What we can do?

The things you can do is either update package your own or just update your android version.

**Comment by xeffyr** [comment]
> What we can do?

Only 2 variants, if still using Android versions in range 5.x - 6.x:
1. Nothing. Just ignore this notice.
2. Get a new device with Android 7.0 at least.

If you have "legacy environment" on Android 7+, then do:
```
pkg upgrade
termux-upgrade-repo
```
Also people using legacy environment on Android 7+ should read https://github.com/termux/termux-app/issues/1703 - if updated application to v0.99 or newer and got "CANNOT LINK EXECUTABLE" on startup.
