### ISSUE TITLE
ssh is not working

### ISSUE THREAD

**Issue by Lemon-Hacking** [termux/termux-app#1395]
The command "ssh localhost" returns with "**ssh: connect to host localhost port 22: Connection refused**" and creating a PHP development server :-

**PHP 7.3.12 Development Server started at Thu Dec 26 14:08:54 2019
Listening on http://localhost:2931
Document root is /data/data/com.termux/files/home
Press Ctrl-C**

Then trying to forward connections :-  "**ssh -R 80:localhost:2931**" returns with 

**ssh: connect to host serveo.net port 22: Connection timed out**

after a long pause.

**Comment by fbartels** [comment]
the ssh server on termux is not listening on port 22, but port 8022.

**Comment by xeffyr** [comment]
@Lemon-Hacking Serveo.net is down and you can't use it anymore.

**Comment by Lemon-Hacking** [comment]
Using port 8022 worked and I was able to connect to localhost (192.x). Yes, I just noticed that Serveo is down :- 
Serveo is temporarily disabled due to phishing.
Serveo will return in a few days with a few new restrictions to help dissuade abuse. Thanks for your patience!
