### ISSUE TITLE
stdOut breaks and stdIn is hidden until reset

### ISSUE THREAD

**Issue by buffermet** [termux/termux-app#1396]
**Problem description**
When I enter `su -c "echo" &>/dev/null`, my stdIn and stdOut breaks, stdIn becomes invisible and all output is dumped on one line. It's as if all newlines are replaced with spaces when they aren't supposed to: 
![Screenshot_20191227-011539_Trebuchet](https://user-images.githubusercontent.com/29265684/71481028-f7004300-2847-11ea-89ae-8efe8747c06a.png)

**Steps to reproduce**
Rumning Termux with SU permission on Android 9 (LineageOS 16.0), enter `su -c "echo" &>/dev/null` and observe the session has become near impossible to use. Session requires `reset` command or should be destroyed.

**Expected behavior**
No output, stdIn should move to the next line.

**Additional information**
Post output of command `termux-info`.
```
$ termux-info
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
Updatable packages:
clang/stable 9.0.1 arm [upgradable from: 9.0.0-2]
command-not-found/stable 1.44 arm [upgradable from: 1.42]
dnsutils/stable 9.14.9 arm [upgradable from: 9.14.8]
ecj/stable 4.14 all [upgradable from: 4.12-2]
fribidi/stable 1.0.8 arm [upgradable from: 1.0.7]
glib/stable 2.62.4 arm [upgradable from: 2.62.3-1]
libllvm/stable 9.0.1 arm [upgradable from: 9.0.0-2]
libvpx/stable 1.8.2 arm [upgradable from: 1.8.1-1]
python/stable 3.8.1 arm [upgradable from: 3.8.0-3]
Android version:
9
Kernel build information:
Linux localhost 3.4.113-lineageos-g2df84e6 #1 SMP PREEMPT Sun Dec 8 18:51:36 UTC 2019 armv7l Android
Device manufacturer:
samsung
Device model:
klte
```

**Comment by AbdullahM0hamed** [comment]
I also used to get this error (but with tsu and not su). `reset 2> /dev/null` should sort it out temporarily. If that works, you could probably add it to the su script.

**Comment by buffermet** [comment]
I can reset the session but I shouldn't have to do that each time. This is a bug that should be fixed imo.

**Comment by xeffyr** [comment]
This is bug of `su` binary. Not Termux.
Known to happen on Lineage OS.

**Comment by buffermet** [comment]
> This is bug of `su` binary. Not Termux.
> Known to happen on Lineage OS.

Ok, thanks for clarifying.
