### ISSUE TITLE
Can't install termux from playstore or Fdroid

### ISSUE THREAD

**Issue by abinashdash17** [termux/termux-app#1398]
I can no longer install Termux in my device. I removed it yesterday for a clean install from playstore. But after removing it i can't install it from playstore or fdroid version. As far as i remember, the termux i was using, was from fdroid and i've not updated it from last 2 3 months.What to do?

**Comment by xeffyr** [comment]
What Android version ?

**Comment by SDRausty** [comment]
https://wiki.termux.com/wiki/Installation

**Comment by abinashdash17** [comment]
android 5. I read the news just now that android 5 support will be dropped. Anyway somehow it got fixed. Here's what i did:
1.Installed Fdroid. enabled fdroid archive
2. installed termux and termux api
3. used link2sd to move it to sdcard and then moved it back to phone memory(as i had a doubt the this linking might have caused issue.)
4.uninstalled termux and termux-api
5. now i can install the version which is showing up in Playstore.
PS: In the playstore version, i read the news about dropping support for android 5.

**Comment by SDRausty** [comment]
> android 5

@abinashdash17 what is the best way to make ready for this change?

Reference:  https://www.reddit.com/r/termux/comments/dnzdbs/end_of_android56_support_on_20200101/

**Comment by prashant930** [comment]
> android 5. I read the news just now that android 5 support will be dropped. Anyway somehow it got fixed. Here's what i did:
> 1.Installed Fdroid. enabled fdroid archive
> 2. installed termux and termux api
> 3. used link2sd to move it to sdcard and then moved it back to phone memory(as i had a doubt the this linking might have caused issue.)
> 4.uninstalled termux and termux-api
> 5. now i can install the version which is showing up in Playstore.
> PS: In the playstore version, i read the news about dropping support for android 5.

How to enable archive

**Comment by xeffyr** [comment]
> How to enable archive

Through F-Droid settings.

**Comment by prashant930** [comment]
> > How to enable archive
> 
> Through F-Droid settings.

Thank you but i have installed

**Comment by max601** [comment]
Ey man

If you're still trying to install termux I might have found a way to do that so basically I went to playstore and tried installing termux after a few failed attempts I saw that a termux app from playstore called termux:API was already installed I Uninstalled it and tried installing termux again but only this time it succeeded so if you try that maybe it will work?

**Comment by Jharaghav23228** [comment]
Termux showing incompatible on f droid

**Comment by agnostic-apollo** [comment]
> Termux showing incompatible on f droid.
> What to do?
> My android version is 6.0.1

Install old version for android 6.

https://github.com/termux/termux-app#installation

**Comment by blazingcody** [comment]
Mine is android 11 and it won't install either

**Comment by Yonle** [comment]
> Mine is android 11 and it won't install either

Uninstall all Termux app including it's plugin like Termux:API, Termux:Boot and etc that installed from play store.

**Comment by IchabaGodwin** [comment]
I tried downloading with playstore and f droid, it still won't download.... Android 10 please help

**Comment by RalfWerner** [comment]
Checks in the Android Setting->Apps, whether Termux/Plugins are installed. Then uninstall these and try Fdroid Termux Install again.
