### ISSUE TITLE
How can I launch an Android widget from within Termux?

### ISSUE THREAD

**Issue by bitcoinmeetups** [termux/termux-app#1399]
How can I launch an Android widget from within Termux?

Let's say another Android app has a widget (e. g. Automate). How can I write a Termux script which launches that widget?

**Comment by AbdullahM0hamed** [comment]
Find out the activity that gets launched, and then use `am start -n <package>/<activity>`

**Comment by SDRausty** [comment]
```
$ am start -n /system/app/talkback/talkback.apk start
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] pkg=start cmp=/system/app/talkback/talkback.apk }
Error: Activity not started, unknown error code -101
$ am start -n /system/app/talkback/talkback.apk
Starting: Intent { cmp=/system/app/talkback/talkback.apk }
Error: Activity not started, unknown error code -101
```

A working example is requested.  I searched; `"am start" site:wiki.termux.com` and did not find the information regarding a working example:
> How can I launch an Android shortcut from within Termux?

**Comment by AbdullahM0hamed** [comment]
@SDRausty Not sure if the example you provided was a counter to what I said, so I'm just going to clarify that I meant something along the lines of

`
am start -n com.termux/com.termux.app.TermuxActivity`

![Screenshot_20191227-234932_Termux](https://user-images.githubusercontent.com/25087116/71536087-92a2b980-2903-11ea-9d4f-79b3a07d0bc7.jpg)

**Comment by SDRausty** [comment]
@AbdullahM0hamed thank you for the clarification.  

> just going to clarify that I meant something along the lines of
` am start -n com.termux/com.termux.app.TermuxActivity`

However:
```
$ am start -n com.termux/com.termux.app.TermuxActivity
Starting: Intent { cmp=com.termux/.app.TermuxActivity }
Warning: Activity not started, intent has been delivered to currently running top-most instance.
```

**Comment by AbdullahM0hamed** [comment]
I suspect that it calls the existing instance if it's already open, and a new instance if it isn't.

Below is a screenshot of me opening chrome (the first time chrome was already open, and the second time it was closed):

![Screenshot_20191228-001015_Termux](https://user-images.githubusercontent.com/25087116/71536401-b0bde900-2906-11ea-9428-1d33daf6a03d.jpg)

**Comment by bitcoinmeetups** [comment]
Hi. I think with Android "apps with shortcuts" does not mean what it would normally mean. Most apps have icons that you click on the homescreen to start them. But that's not what I'm looking for. Actually I should have said widgets. I got confused because the widgets are also sometimes referred to as shortcuts.

Anyway, I'm looking specifically for a way to launch a widget from Termux. I was not able to launch apps with the instructions above either. But anyway it's the launching of wiidgets that I'm after.

**Comment by SDRausty** [comment]
> How can I launch an Android widget from within Termux?

> confused because the widgets are also sometimes referred to as shortcuts.

new vocabulary ~= confusion

With search string: `linux learning curve site:.org` this is a never ending story...

Based on the new issue title, is this what you are seeking @bitcoinmeetups?
```
$ ~/buildAPKs/build.widgets.bash
.
.
.
Results for ~/buildAPKs/sources/widgets/:                                                                                                                     
10 possible                                                                   
10 built
```
From https://buildapks.github.io/buildAPKs/

The command `tree ~/buildAPKs/sources/widgets/` will show the source tree.  You can find and add widgets with `~/buildAPKs/build.github.bash/` which builds Github accounts.

**Comment by SDRausty** [comment]
Hello,

> How can I launch an Android widget from within Termux?

> confused because the widgets are also sometimes referred to as shortcuts.

new vocabulary ~= confusion

With search string: `linux learning curve site:.org` this is a never ending story...

> How can I launch an Android widget from within Termux?

Based on the new issue title, is this what you are seeking @bitcoinmeetups?
```
$ ~/buildAPKs/build.widgets.bash
.
.
.
The APK org.omnirom.android.monthcalendarwidget.apk file can be installed from Download/builtAPKs/widgets.20191228/org.omnirom.android.monthcalendarwidget.1577539047.apk
.
.
.
Results for ~/buildAPKs/sources/widgets/:                                                                                                                     
10 possible                                                                   
10 built
```

[![Screenshot_20191228-084420_Termux.jpg](https://raw.githubusercontent.com/BuildAPKs/docsBuildAPKs/master/bitpics/screenshots/Screenshot_20191228-084420_Termux.jpg)](https://buildapks.github.io/docsBuildAPKs/setup)

The command `tree ~/buildAPKs/sources/widgets/` will show the source tree.  You can find and add widgets with the command [`~/buildAPKs/build.github.bash`](https://github.com/BuildAPKs/buildAPKs.github/blob/master/build.github.bash) which builds Github accounts on smartphone in Termux.

**Comment by xeffyr** [comment]
@bitcoinmeetups What you are looking for is the calling specific intents with specified arguments. You can't call widget directly but only what is behind it.

Example for launching Termux activity:
```
am start -n com.termux/.app.TermuxActivity
```
\- note that Termux cannot have more than one activity launched at the time, existing one will be brought to the front due to configuration in [AndroidManifest.xml](https://github.com/termux/termux-app/blob/master/app/src/main/AndroidManifest.xml#L36) (single task mode).

Widgets are not exception and their action can be called through argument too. But this is more complicated and there no universal way how to do that. Example for calling scripts through Termux:Widget:

1. Obtain the token from shared preferences. Should be possible from Termux but since I use debug versions of applications I used ADB:
```
herolte:/ $ run-as com.termux.widget                                                                                                                                                                              
herolte:/data/data/com.termux.widget $ cat shared_prefs/token.xml                                                                                                                                                 
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="token">c27d1264-b1d6-48d7-980f-58cbc3e964fe</string>
</map>
```

2. Get the necessary arguments for intent. In my case:
* Activity name: `com.termux.widget/.TermuxLaunchShortcutActivity`
* Script name: `/data/data/com.termux/files/usr/bin/login` (yes, you can execute programs outside of shortcuts with Termux:Widget).
* Token string name: `com.termux.shortcut.token`
* Token string value: `c27d1264-b1d6-48d7-980f-58cbc3e964fe`

3. Execute intent with activity manager:
```
am start -n com.termux.widget/.TermuxLaunchShortcutActivity -d file://com.termux.widget/data/data/com.termux/files/usr/bin/login --es com.termux.shortcut.token c27d1264-b1d6-48d7-980f-58cbc3e964fe
```
\- launches a new login shell session due to called script `login`, but you can put anything other here.

**Comment by SDRausty** [comment]
> note that Termux cannot have more than one activity launched at the time,

@xeffyr does this mean Termux app should be rebuild?  If so, which lauchMode(s) resolve this issue?

```
$ am start -n com.termux/.app.TermuxActivity
Starting: Intent { cmp=com.termux/.app.TermuxActivity }
Warning: Activity not started, intent has been delivered to currently running top-most instance.
```

> note that Termux cannot have more than one activity 
>>android:launchMode="singleTask

Reference: https://developer.android.com/guide/topics/manifest/activity-element.html

**Comment by SDRausty** [comment]
> which lauchMode(s) resolve this issue?

From the documention reviewed, given time, the answer to the question is variable (depreciation, etc...).

**Comment by xeffyr** [comment]
> does this imply Termux app should be rebuild?

No, single task mode is intentional.

There no reason for having multiple activities. You also won't be able to start activity anyway if it is already running at the front.

Instead of
```
Warning: Activity not started, intent has been delivered to currently running top-most instance.
```
you will just get
```
Warning: Activity not started, its current task has been brought to the front
```

**Comment by SDRausty** [comment]
@xeffyr thank you for your time and answer.

> No, single task mode is intentional.
> There no reason for having multiple activities

**Comment by SDRausty** [comment]
> How can I launch an Android widget from within Termux?

` ~/buildAPKs/build.widgets.bash ` 

Another way to accomplish this task of "launch an Android widget from within Termux" is:
`~/buildAPKs/scripts/bash/github/build.github.topics.bash widgets`

Note: [widget|widgets] running ` ~/buildAPKs/scripts/bash/github/build.github.topics.bash ` without arguments has more information.

Installing the Android widget APKs built in Termux is required to activate them.

**Comment by SDRausty** [comment]
> How can I launch an Android widget from within Termux?

` ~/buildAPKs/build.widgets.bash ` 

Another way to accomplish this task of "launch an Android widget from within Termux" is:
`~/buildAPKs/scripts/bash/github/build.github.topics.bash widget`

Note: [widget|widgets] running ` ~/buildAPKs/scripts/bash/github/build.github.topics.bash ` without arguments has more information.

```
$ ~/buildAPKs/scripts/bash/github/build.github.topics.bash
GitHub topic name must be provided;  See ~/buildAPKs/opt/db/TNAMES for topic names that build APKs on device with BuildAPKs!  To build all the topic names contained in this file run for NAME in $(cat ~/buildAPKs/opt/db/TNAMES) ; do ~/buildAPKs/scripts/bash/github/build.github.topics.bash $NAME ; done.  File ~/buildAPKs/.conf/GAUTH has information should you choose to run this for loop command regarding bandwidth supplied by GitHub.
```

Installing the Android widgets [buildAPKs](https://buildapks.github.io/buildAPKs/) built in Termux is required to activate them in Android.
