### ISSUE TITLE
(IDEA) Access Termux from ADB

### ISSUE THREAD

**Issue by Merith-TK** [termux/termux-app#1400]
**Feature description**
Basically add a binary you can use to access termux from `adb shell` 
hell it may even be an sh script

**Reference implementation**
not that im aware of, but maybe you could store the binary in `/sdcard/Android/data/com.termux/`?

**Comment by xeffyr** [comment]
> Basically add a binary you can use to access termux from adb shell

```
adb root
adb shell
export PREFIX=/data/data/com.termux/files/usr
export HOME=/data/data/com.termux/files/home
export PATH=$PREFIX/bin:$PREFIX/bin/applets
unset LD_LIBRARY_PATH
exec $PREFIX/bin/login
```

> maybe you could store the binary in /sdcard/Android/data/com.termux/?

Many times was answered - that's not possible. Why ? - Limits of file system:

* No symlinks.
* No sockets.
* No unix permissions.
* Mounted with `noexec`.
* Privacy issues.

Noexec can be bypassed with special proot version, but others not.
