### ISSUE TITLE
can't use proot

### ISSUE THREAD

**Issue by liuerhang** [termux/termux-app#1402]
I download the termux from googleplay.

Then,I finish the install of teemux.

use termux-chroot after install the proot.

```
$ termux-chroot
proot error: execve("/usr/bin/bash"): No such file or directory
proot info: It seems that termux-exec is active and is prepending /data/data/com.termux/... to executable paths
If this is path is not available inside proot, please "unset LD_PRELOAD"
fatal error: see `proot --help`.
proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp', please report this error.
proot error: can't chmod '/data/data/com.termux/files/usr/tmp/proot-13923-HVYA4H': No such file or directory
```

device information:
device: Galaxy S10 5G(SM-G977N)
root:no
android_version:10.0

**Comment by SDRausty** [comment]
> use proot 
> use termux-chroot 

https://github.com/termux/proot/issues?q=is%3Aissue+chroot+proot+nesting

> In general, nesting proot doesn't work well, 

Reference https://github.com/termux/proot/issues/82

**Comment by fornwall** [comment]
Hi! I'm closing this as it's not related to the Termux app directly - reopen an issue at https://github.com/termux/proot if desired!
