### ISSUE TITLE
No commands are working after editing th bash.bashrc file by mistake

### ISSUE THREAD

**Issue by Shubhendra-kushwaha** [termux/termux-app#1403]
By mistake I have edited badly my bash.bashrc file located in /data/data/com.termux/files/use/etc/.
I made a repository on https://github.com/Shubhendra-kushwaha/YourName.git which edit that file but by mistake I leaved blanked the first and last name .
After this when I open termux nothing displays and whatever I type Figlet converts it into ASCII text
![Screenshot_20191229_210347](https://user-images.githubusercontent.com/37535104/71559124-8e4fdb00-2a80-11ea-97ea-d16c67913776.jpg)
Please help me 😞😞😟😟to restore that file and make termux working

**Comment by SDRausty** [comment]
> Launching a Failsafe Session
> 1. Close all sessions of Termux application.
> 2. Either long-press the termux launcher icon and then press "failsafe" (only works on recent android versions) or long-press the "new session" button in the left drawer inside the termux app.

Reference https://wiki.termux.com/wiki/Recover_a_broken_environment

> How do I fix a broken environment?

Reference https://wiki.termux.com/wiki/FAQ

**Comment by SDRausty** [comment]
> edited badly my bash.bashrc file 
> restore that file 

https://github.com/search?q=.bashrc

**Comment by SDRausty** [comment]
> edited badly my bash.bashrc file 
> restore that file 

1. https://github.com/search?q=.bashrc

2. `grep -r .bashrc termux-packages/` after cloning https://github.com/termux/termux-packages might resolve your request better than the first answer.  

Did you forget to backup your work @Shubhendra-kushwaha before editing?
