### ISSUE TITLE
Additional Packages - libpcre3,  libpcre3-dev, libssl-dev 

### ISSUE THREAD

**Issue by ysliew** [termux/termux-app#1404]
**Feature description**
Describe the feature and why you want it.

**The above packages  (libpcre3,  libpcre3-dev & libssl-dev) will enable customization and compilation of NGINX and additional modules to be done on Termux.** Will be very handy.

**Reference implementation**
Does another app/terminal emulator have this feature?
Provide links to more background information

Not to my knowledge, great to have others inputs on the same =)

**Comment by xeffyr** [comment]
>libpcre3, libpcre3-dev, libssl-dev

All of these are available:
* pcre
* openssl

We do not follow Debian packaging scheme and headers are not split into dev packages. Also packages may have different names (see above).
