### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by systemsgo** [termux/termux-app#1406]
When entering text using the samsung keyboard the text is not displayed until I hit enter or other characters such as slash.  If turn off predictive text it works normally but I have to kill and restart the Termux process first.

I'm using a Galaxy S10.  This was working fine prior to the December update.

**Comment by SDRausty** [comment]
> samsung keyboard the text is not displayed

Is the result the same with `/buildAPKs/build.developers.tools.bash` keyboard?

**Comment by SDRausty** [comment]
> samsung keyboard the text is not displayed

Is the result the same with `~/buildAPKs/build.developers.tools.bash` keyboard?

**Comment by SDRausty** [comment]
> turn off predictive

ditto

**Comment by systemsgo** [comment]
Yes, this works with non predictive keyboards.  I seem to remember this was broken a year or so ago, then was fixed.  It seems to have broken again with Samsung's December update.

**Comment by SDRausty** [comment]
> this works with non predictive keyboards

Predictive keyboards seem to do more. I encountered a gibberish cleverly entered with this alogram.

**Comment by SDRausty** [comment]
> this works with non predictive keyboards

Predictive keyboards seem to do more. I have encountered a gibberish cleverly entered with this alogram.

Side note:  ` $ wae A\ Line\ In\ The\ Sand\ -\ Linkin\ Park\ \(The\ Hunting\ Party\)-FkDrVL8Tsuw.mp4 `

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-app/issues/1235 and linked issue

**Comment by systemsgo** [comment]
This doesn't seem directly caused by predictive text.  When using most apps with predictive text, character input still appears one character at a time.  The predictive aspect only allows for autocompletion or correction.  Termux also works this way with predictive in some cases,  it only stopped working recently.  Switching keyboards doesn't do anything to address the underlying issue.

**Comment by rayabee** [comment]
Same problem here. Also Samsung s10. Any updates or fixes available yet?

**Comment by MoonbeamMoony** [comment]
How can I fix this? 
![Screenshot_20200626-104051_Termux](https://user-images.githubusercontent.com/67381949/85815252-886e5480-b79a-11ea-8653-8de0d2018948.jpg)

**Comment by MoonbeamMoony** [comment]
> How can I fix this?
> ![Screenshot_20200626-104051_Termux](https://user-images.githubusercontent.com/67381949/85815252-886e5480-b79a-11ea-8653-8de0d2018948.jpg)

I cannot switch keyboard. If I press "1/2", it'll press "backspace"
