### ISSUE TITLE
Make Termux Android 6.x compatible again

### ISSUE THREAD

**Issue by x2k13** [termux/termux-app#1407]
**Problem description**
Termux used to be compatible with Android 6.x - now it isn't anymore.

**Steps to reproduce**
Try to install (update to the) the latest Termux version on an Android 6.x device.

**Expected behavior**
App is installed (updated) and works.

**Comment by xeffyr** [comment]
Support for Android 5.x.x - 6.x.x is dropped forever. Time to upgrade your devices or learn how to backport git changes.

https://github.com/termux/termux-packages/issues/4467
