### ISSUE TITLE
File permission error despite granting file access

### ISSUE THREAD

**Issue by J-Cake** [termux/termux-app#1408]
**Problem description**
I can't tell if I'm just being ignorant or if it's a genuine issue. I've got node.js and typescript installed but I can't compile the files because of permission errors. Mind you, I've granted filesystem access to termux.

**Steps to reproduce**
1) I've got a typescript program on a USB device that I need to compile.

2) install node.js 
```
$ pkg install nodejs
```

3) install typescript
```
$ npm install typescript
```

4) compile typescript
```
$ tsc
```
**Note the `EACCESS` error reported by node**
This also occurs when doing NPM installs inside the project directory.

**Expected behaviour**
Compile typescript files without permission errors

**Additional information**
```
Updatable packages:
apt/stable 1.4.9-24 aarch64 [upgradable from: 1.4.9-16]
busybox/stable 1.31.1-2 aarch64 [upgradable from: 1.30.1-9]
ca-certificates/stable 20191129 all [upgradable from: 20190828]
command-not-found/stable 1.44 aarch64 [upgradable from: 1.39]
curl/stable 7.67.0 aarch64 [upgradable from: 7.66.0]
dos2unix/stable 7.4.1 aarch64 [upgradable from: 7.4.0-1]
gpgv/stable 2.2.19 aarch64 [upgradable from: 2.2.17]
inetutils/stable 1.9.4-8 aarch64 [upgradable from: 1.9.4-7]
libcurl/stable 7.67.0 aarch64 [upgradable from: 7.66.0]
libgcrypt/stable 1.8.5-1 aarch64 [upgradable from: 1.8.5]
libnghttp2/stable 1.40.0 aarch64 [upgradable from: 1.39.2]
net-tools/stable 1.60.2017.02.21-3 aarch64 [upgradable from: 1.60.2017.02.21-2]
openssl/stable 1.1.1d-1 aarch64 [upgradable from: 1.1.1d]                     procps/stable 3.3.16 aarch64 [upgradable from: 3.3.15-6]
psmisc/stable 23.3 aarch64 [upgradable from: 23.2-1]
tar/stable 1.32-5 aarch64 [upgradable from: 1.32-4]
termux-tools/stable 0.74 all [upgradable from: 0.71]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.111-16290088 #1 SMP PREEMPT Tue Nov 12 19:19:26 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9                                                                             Device manufacturer:
samsung
Device model:
SM-G950F
```

**Comment by xeffyr** [comment]
1. Post **full** error log.

2. Make sure that everything is done in Termux home directory (no sdcards and usb sticks, their file system has limits).

**Comment by J-Cake** [comment]
It works on the internal storage but not on external devices. Why is that?

**Comment by xeffyr** [comment]
> Why is that?

External devices do not support unix file permissions and special files like symlinks. Btw, that's why Termux keeps its stuff under `/data/data/*`.

**Comment by J-Cake** [comment]
If the device is formatted with the *exact* same filesystem as the internal one, would that be a different matter?

**Comment by xeffyr** [comment]
> would that be a different matter?

Not unless it will be mounted manually with command `mount` (root needed). Android applies file system overlay (called `sdcardfs`) which turns any file system into FAT32 or exFAT.

**Comment by J-Cake** [comment]
Okay, the *root needed* did it for me. So I'm restricted to using the internal storage. That's not a problem, just another step in between. Thanks again.
