### ISSUE TITLE
Termux arrow keys appearing wrong

### ISSUE THREAD

**Issue by indiancybertroops** [termux/termux-app#1410]
sir i don't know why my termux's arrow keys appearing like (IJ ij ' ) could you please provide solution 
![Screenshot_20200103-211411](https://user-images.githubusercontent.com/17755328/71732809-2f1e0c00-2e6e-11ea-95c0-fca7da97136e.png) 

image attached with it could you please provide solution immediately

**Comment by xeffyr** [comment]
What is your `termux-info` ?

**Comment by himeshvyas26** [comment]
> What is your `termux-info` ?

![Screenshot_20200103-212057](https://user-images.githubusercontent.com/17755328/71733199-021e2900-2e6f-11ea-8518-5a2a648a0fa2.png)



check this

**Comment by robertvandeneynde** [comment]
This is clearly some encoding issue, it's really weird that your TAB key is still rendered using the Unicode symbol.

**Comment by agnostic-apollo** [comment]
Likely fixed by 0af8236. Can be opened again if not fixed.
