### ISSUE TITLE
termux on Galaxy A10 64bit runs only on 32 bit      

### ISSUE THREAD

**Issue by ronnac** [termux/termux-app#1412]
**Problem description**
I installed termux on a Samsung Galaxy A10 which has an armhf 64bit architecture (Exynos 7884).
However the command  
"getconf LONG_BIT" yields 32, meaning termux uses 32bit.
**Steps to reproduce**
N/a

**Expected behavior**
64bit termux

**Comment by xeffyr** [comment]
> 64bit architecture (Exynos 7884).

CPU does not matter. It's important whether Android provides 64bit core libraries and linker. Some devices do not have them even CPU and kernel are 64bit.

Nothing can be done with that as Termux will just not work here.
