### ISSUE TITLE
Is it possible to know the brightness of the screen? 

### ISSUE THREAD

**Issue by Sh1Yo** [termux/termux-app#1414]
I want to run some scripts when the brightness of the is less than some value

**Comment by AbdullahM0hamed** [comment]
Termux-brightness only seems to set the brightness, so there doesn't seem to be a way to do this as of right now.

However, you can do `su -c settings get system screen_brightness` to get the brightness.

**Comment by Sh1Yo** [comment]
Thanks, but it requires root (. I believe that this feature will be implemented in the API

**Comment by Sh1Yo** [comment]
I think it is better to reopen the issue in the termux-api
