### ISSUE TITLE
Horizontal scrolling in termux app

### ISSUE THREAD

**Issue by kcubeterm** [termux/termux-app#1417]
**Feature description**
Termux should have horizontal scrolling , similar to vertical scroll,

**Comment by Abdella555** [comment]
Lack of file tool I don't this

**Comment by Neo-Oli** [comment]
That's really not how terminals work. Output is always wrapped at width of terminal. In order for horizontal scrolling termux would have to report it's width to be greater than it actually is and this would cause a lot of ncurses and similar programs to be sized to whatever that size is and look really messy. 

One other possibility would be to  simply translate horizontal scrolling to arrow keys, but that would only work in very few programs (like running `less --chop-long-lines --shift 1`)

**Comment by kcubeterm** [comment]
Thanks
