### ISSUE TITLE
I want to a option to hide the bottom bar including `ESC, .. , CTRL, ALT, - , ..` buttons

### ISSUE THREAD

**Issue by ChoiChoongHo94** [termux/termux-app#1419]
**Feature description**
I want to a option to hide the bottom bar including `ESC, .. , CTRL, ALT, - , ..` buttons.

**Comment by Grimler91** [comment]
Long press "keyboard" in the left drawer or press vol up + K. See https://wiki.termux.com/wiki/Touch_Keyboard.
