### ISSUE TITLE
Unhiding extra keys while input view was shown causes incorrect keyboard handling

### ISSUE THREAD

**Issue by ticalc-travis** [termux/termux-app#1420]
**Problem description**

If the extra keys bar was last showing the input view when it is shown with Volume Up + k/q, Termux can enter a state where all keyboard input is stuck responding as if Volume Up is being continually held down.

I updated to the 2020-01-04 release on Play Store and can still reproduce the problem.

**Steps to reproduce**

1. Start a new Termux session
2. Show extra keys and swipe to the input view
3. Tap back on the terminal area to remove focus from the input view and verify that characters tapped on the keyboard are going into the terminal session as expected
4. Press VolUp + q or VolUp + k to hide extra keys, then again to re-show it
5. Swipe away the input view or tap again in the terminal region and attempt to type again

Instead of text, the keys still behave as if VolUp is stuck down, even in other sessions and after switching between Termux and other apps.

**Expected behavior**

Normal keyboard operation, as VolUp is not in fact pressed anymore.

**Workaround**

Tap the terminal area (or otherwise remove focus from the native input field) and press VolUp + q/k one more time to undo the glitched state and allow normal input again.

**Additional information**

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
apt/stable 1.4.9-24 arm [upgradable from: 1.4.9-22]
autossh/stable 1.4g-2 arm [upgradable from: 1.4g-1]
busybox/stable 1.31.1-4 arm [upgradable from: 1.31.1-2]
ca-certificates/stable 20191129 all [upgradable from: 20191016]
command-not-found/stable 1.45 arm [upgradable from: 1.42]
curl/stable 7.68.0 arm [upgradable from: 7.67.0]
gpgv/stable 2.2.19 arm [upgradable from: 2.2.17-1]
grep/stable 3.4 arm [upgradable from: 3.3-2]
inetutils/stable 1.9.4-8 arm [upgradable from: 1.9.4-7]
krb5/stable 1.17.1-1 arm [upgradable from: 1.17-1]
libcurl/stable 7.68.0 arm [upgradable from: 7.67.0]
libedit/stable 20191211-3.1-0 arm [upgradable from: 20191025-3.1-0]
libgcrypt/stable 1.8.5-1 arm [upgradable from: 1.8.5]
libnghttp2/stable 1.40.0 arm [upgradable from: 1.39.2]
net-tools/stable 1.60.2017.02.21-3 arm [upgradable from: 1.60.2017.02.21-2]
openssh/stable 8.1p1-4 arm [upgradable from: 8.1p1-1]
procps/stable 3.3.16 arm [upgradable from: 3.3.15-6]
psmisc/stable 23.3 arm [upgradable from: 23.2-1]
rsync/stable 3.1.3-6 arm [upgradable from: 3.1.3-5]
tar/stable 1.32-5 arm [upgradable from: 1.32-4]
termux-auth/stable 1.3 arm [upgradable from: 1.1-1]
vim/stable 8.2.0100 arm [upgradable from: 8.1.2200]
vim-runtime/stable 8.2.0100 all [upgradable from: 8.1.2200]
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.14-14372886-QB27449830 termux/termux-packages#1 SMP PREEMPT Fri Nov 22 17:07:32 KST 2019 armv8l Android
Device manufacturer:
samsung
Device model:
SM-J727U
```

**Comment by agnostic-apollo** [comment]
Fixed by 395759c
