### ISSUE TITLE
Opening a port for public IP?

### ISSUE THREAD

**Issue by RajaMBZ** [termux/termux-app#1421]
I want to open a specific port (3000) for my public IP, such that canyouseeme.org tells me that I've got the port opened and nc command shows it. I see there's no ufw in termux, so is there any alternate for this?

**Comment by xeffyr** [comment]
> I see there's no ufw in termux, so is there any alternate for this?

Termux will never have a firewall because it is useless and will not work. Termux is not a system, it's an Android app and nothing more.
