### ISSUE TITLE
Permission denied when executing program

### ISSUE THREAD

**Issue by joshop** [termux/termux-app#1428]
**Problem description**
My Android 7 phone is not rooted but has Team Win Recovery Project which I can boot into and get a root shell. I downloaded an adb binary for my phone and used that to copy it to my Termux home. I `chmod`ded it so that I could access it and `chown`ed it so that my user was the owner. Despite this, I'm still unable to run the binary from Termux. I have run `ls -l` and confirmed that I own it and have permissions, but still get Permission denied when I try to execute.

**Steps to reproduce**
Unfortunately, I don't know what I did to trigger this.

**Expected behavior**
Due to the fact that I own the file and have execute permissions, I should be able to execute it.

**Additional information**
Here's `termux-info`:
```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g4d4c2fc-00014-g2658ba1 #1 SMP PREEMPT Fri Aug 10 15:39:51 KST 2018 armv7l Android
Device manufacturer:
LGE
Device model:
LG-TP260
```

**Comment by xeffyr** [comment]
> I chmodded it so that I could access it and chowned it so that my user was the owner.

You need to `/system/bin/restorecon` it. Android applies SELinux policy as well for permission management.

**Comment by ManuLinares** [comment]
> > I chmodded it so that I could access it and chowned it so that my user was the owner.
> 
> You need to `/system/bin/restorecon` it. Android applies SELinux policy as well for permission management (SELinux takes priority over ownership & file access attributes).

This should be added to the wiki, permissions, restorecon
