### ISSUE TITLE
No such file or directory when executing

### ISSUE THREAD

**Issue by joshop** [termux/termux-app#1429]
**Problem description**
My Android 7 phone is not rooted but has Team Win Recovery Project which I can boot into and get a root shell. I downloaded an adb binary for my phone and used that to copy it to my Termux home. I previously posted an issue about permissions but realized I had to run `restorecon` on the file. After doing that, however, I attempt to execute it in Termux and I get a `No such file or directory`.

**Steps to reproduce**
The file is an ARM ADB binary that I own and have write, read and execute permissions for. After being unable to execute it, I ran `restorecon`. I'm unsure of any other steps.

**Expected behavior**
The binary should execute. If it's invalid or for the wrong architecture, the file should at the very least be found and then fail to properly execute.

**Additional information**
Here's `termux-info`:
```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g4d4c2fc-00014-g2658ba1 #1 SMP PREEMPT Fri Aug 10 15:39:51 KST 2018 armv7l Android
Device manufacturer:
LGE
Device model:
LG-TP260
```

**Comment by xeffyr** [comment]
> I attempt to execute it in Termux and I get a No such file or directory.

Make sure your binary is either **statically linked** or compiled with Android NDK.

https://wiki.termux.com/wiki/FAQ#Why_does_an_executable_throw_the_.27No_such_file_or_directory.27_error_even_though_the_file_exists_.3F

> If it's invalid or for the wrong architecture, the file should at the very least be found and then fail to properly execute.

You are missing one important thing - the libc ABI.

**Comment by trusktr** [comment]
Ah, so using tools like `n` or `nvm` to download latest `node`.js won't work? How do you recommend to get latest Node in Termux v0.101? Do we have to compile from source?
