### ISSUE TITLE
Content changes in Termux storage aren't reflected in DocumentsProvider

### ISSUE THREAD

**Issue by stevogotchi** [termux/termux-app#143]
TermuxDocumentProvider isn't notifying of content change.
Can do so using ContentProvider notification system. See docs starting at "To support change notifications..."

https://developer.android.com/reference/android/provider/DocumentsProvider.html#queryChildDocuments(java.lang.String, java.lang.String[], java.lang.String)

How to repro:

In Android Nougat DocumentsProviders are visible in Downloads sidebar.
Open Downloads.
Open Sidebar.
Select "Termux" entry in draw > see Termux content loaded in main window.

Switch to Termux app.
cd to same directory visible in Downloads app.
touch newfile

Switch to Downloads app.

Expected:
See "newfile" listed.

Actual: 
No "newfile" seen.

Note: Clicking away from directory and back shows "newfile".

 Cheers! Termux is really fun!

**Comment by stevogotchi** [comment]
Note, github doesn't handle the documentation URL correctly. Try copy/paste "https://developer.android.com/reference/android/provider/DocumentsProvider.html#queryChildDocuments(java.lang.String, java.lang.String[], java.lang.String)"

**Comment by Neo-Oli** [comment]
[The link](https://developer.android.com/reference/android/provider/DocumentsProvider.html#queryChildDocuments(java.lang.String, java.lang.String[], java.lang.String))

**Comment by fornwall** [comment]
I think this is something we will have to live with - as the Termux app itself does not modify the file system, but underlying processes do, it would be difficult/expensive to monitor all file system changes.

The workaround with clicking away from the directory and back will have to do!

**Comment by stevogotchi** [comment]
FileObserver lets you monitor changes to the file system regardless of which process makes them.

https://developer.android.com/reference/android/os/FileObserver.html

You can see an example of usage in ExternalStrorageProvider.

https://android.googlesource.com/platform/frameworks/base/+/cefba58/packages/ExternalStorageProvider/src/com/android/externalstorage/ExternalStorageProvider.java#474
