### ISSUE TITLE
symbolic link broken after reboot, caused `login` not work

### ISSUE THREAD

**Issue by CHN-beta** [termux/termux-app#1430]
**Problem description**

After installing termux from play store and open it the first time, everything works well. But just reboot the phone, all symbolic link under /data/data/com.termux/files/usr/bin was broken, and termux said:

```
exec("/data/data/com.termux/files/usr/bin/login"): No such file or directory

[Process completed (code 1) - press Enter]
```

I have Redmi k20 pro (or named MI 9T pro). Months ago, I use MIUI (the official ROM), termux runs well. About a month ago, I flashed [EvolutionX](https://forum.xda-developers.com/k20-pro/development/rom-evolution-x-3-3-t4002669) and the issue above happened every time I reboot the phone. I reported it to the developer, but get no reply. So I turn to [pixel experience](https://forum.xda-developers.com/k20-pro/development/rom-pixel-experience-t4014141), termux works again. Yesterday I updated the version to 15/01/20, and the issue happened again.

**Steps to reproduce**

1. Install termux from play store or anywhere else, open it. Tap:

```
ls -l /data/data/com.termux/files/usr/bin
```

![TIM图片20200117104603](https://user-images.githubusercontent.com/35858462/72580315-a21b8e00-3916-11ea-96e5-99ad4ad07b00.png)

We could see the symbolic link is OK.

2. Simply reboot the phone. Open termux. It will tell you:

```
exec("/data/data/com.termux/files/usr/bin/login"): No such file or directory

[Process completed (code 1) - press Enter]
```

![Screenshot_20200117-104354](https://user-images.githubusercontent.com/35858462/72580346-c11a2000-3916-11ea-801c-cbd46dc0818f.png)

in adb shell:

```
su
ls -l /data/data/com.termux/files/usr/bin
```

![深度截图_20200117104502](https://user-images.githubusercontent.com/35858462/72581039-e871ec80-3918-11ea-8042-c000df6fe6eb.png)

We could see the symbolic link is broken.

3. Clean user data of termux in settings, open termux again, everything works again (of course, all data about termux lost).

**Additional information**

`termux-info` after reboot and clean data:

```
$ termux-info
Updatable packages:
apt/stable 1.4.9-25 aarch64 [upgradable from: 1.4.9-19]
busybox/stable 1.31.1-4 aarch64 [upgradable from: 1.30.1-9]
ca-certificates/stable 20200101 all [upgradable from: 20190828]
command-not-found/stable 1.46 aarch64 [upgradable from: 1.42]
curl/stable 7.68.0 aarch64 [upgradable from: 7.66.0-1]
gpgv/stable 2.2.19 aarch64 [upgradable from: 2.2.17]
grep/stable 3.4 aarch64 [upgradable from: 3.3-2]
inetutils/stable 1.9.4-8 aarch64 [upgradable from: 1.9.4-7]
libcurl/stable 7.68.0 aarch64 [upgradable from: 7.66.0-1]
libgcrypt/stable 1.8.5-1 aarch64 [upgradable from: 1.8.5]
libnghttp2/stable 1.40.0 aarch64 [upgradable from: 1.39.2]
net-tools/stable 1.60.2017.02.21-3 aarch64 [upgradable from: 1.60.2017.02.21-2]
procps/stable 3.3.16 aarch64 [upgradable from: 3.3.15-6]
psmisc/stable 23.3-2 aarch64 [upgradable from: 23.2-1]
tar/stable 1.32-5 aarch64 [upgradable from: 1.32-4]
termux-tools/stable 0.74 all [upgradable from: 0.72]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://termux.org/packages stable/main
System information:
Linux localhost 4.14.164-iMMENSITY #1 SMP PREEMPT Wed Jan 15 14:42:05 UTC 2020 aarch64 Android
Termux-packages arch:
aarch64
Android version:
10
Device manufacturer:
Xiaomi
Device model:
Redmi K20 Pro
```

And `logcat -d "*:W"` from adb (with root):

[logcat.txt.gz](https://github.com/termux/termux-app/files/4074859/logcat.txt.gz)

**Comment by xeffyr** [comment]
This is not Termux issue. (and unreproducible)

The problem you described here is more like symptom of a file system corruption or even memory chip failure. You also mentioned that on MIUI Termux ran well, so why no to flash it back ?

All OS issues are out of scope for fixing, especially if issue comes from such low level as kernel or hardware.
