### ISSUE TITLE
[Quick question] Apk calls Termux-app

### ISSUE THREAD

**Issue by klango** [termux/termux-app#1434]
Hi Community I have a quick question, 
could I write an ordinary apk that calls one of the termux app with a specific parameter? Lets say I have a native Apk in java, I open it and once I click a button it calls an termux app as string for instance ls -la.
Can it be done with termux-api? Or rather not, (just Termux-api calling Android OS) since command line binaries are standalone and executed outside of Android runtime context. 

**Reference implementation**
Does another app/terminal emulator have this feature?

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-app/pull/1029.
No, it is currently not possible.
