### ISSUE TITLE
cant install any package

### ISSUE THREAD

**Issue by AmidBidee** [termux/termux-app#1437]
pkg upgrade
Ign:1 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:2 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:3 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Hit:3 https://dl.bintray.com/grimler/game-packages-21 games Release
Err:5 https://dl.bintray.com/grimler/game-packages-21 games Release.gpg
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
Hit:6 https://termux.net stable InRelease
Get:7 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Hit:7 https://dl.bintray.com/grimler/science-packages-21 science Release
Err:6 https://termux.net stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6700B77E6D8D0AE7
Err:8 https://dl.bintray.com/grimler/science-packages-21 science Release.gpg
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
Err:4 https://bintray.com/xeffyr/unstable-packages unstable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Fetched 18.9 kB in 21s (861 B/s)
Reading package lists... Done

**Comment by AmidBidee** [comment]
Please I need help.

**Comment by xeffyr** [comment]
One question, how `https://bintray.com/xeffyr/unstable-packages` appeared in your list if your current main repo is `https://termux.net` ?

X11 & Unstable repositories are **incompatible** with API 21.

***

Your solution will be: `rm -rf $PREFIX` and restart Termux application.
