### ISSUE TITLE
Hello World while trying to install geckodriver for phoneinfoga to be linked to google via firefox i got this reply (~  sudo sh -c 'tar -x geckodriver -zf geckodriver-*.tar.gz -O > /usr/bin/geckodriver' No command sudo found, did you mean:  Command tsudo in package tsu) note firefox was not installed yet.

### ISSUE THREAD

**Issue by claythe3ed** [termux/termux-app#1438]
**Problem description**
A clear and concise description of what the problem with the termux app is. You may post screenshots in addition to description.

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by xeffyr** [comment]
Firefox is not available in Termux, `geckodriver` will be probably useless.
