### ISSUE TITLE
Version and other debug information as a command

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-app#144]
Could we maybe have a command like `termux-info` which would give helpful information about the state of termux. Something like:
1. Version
2. Google Play or F-Droid
3. Which, if any, packages are not the latest version
4. `uname -a`

This would be very helpful for support going forward. 
I tried writing a bash script that could do it but I can't figure out how to do 1 and 2. Is it even currently possible?

**Comment by fornwall** [comment]
A good idea!

From the adb shell you can use `dumpsys package com.termux | grep versionName` to get the version, but the permission to use `dumpsys` is not granted to non-system apps.

A solution could be to expose an API method just like Termux:API does, which can be used to show the version. I'm planning to move some API methods (at least termux-share and termux-notification) into the main app anyway.

About who installed the app: I think you can detect google play (`com.android.vending`, test with `pm list packages -i | grep com.termux` and look at the installer field) - anything else such as f-droid and manual installation has installer=null.

**Comment by Neo-Oli** [comment]
Does it even need an API method? Couldn't the install process of Termux simply put the version number into a plain text file somewhere in /data/data/com.termux where the bash script could read it?

**Comment by Neo-Oli** [comment]
I created a shell script at [termux-info](https://github.com/Neo-Oli/termux-info/blob/master/termux-info) that would provide the information. `pm list packages -i | grep com.termux` is perfect, as it also provides the information about installed Add-Ons.

Everything except version number should work. The version number function assumes a plaintext file at `$PREFIX/version`, but it can easily be replaced with an API command, if you should choose to go that route instead.

This bash script could be provided via the apt repository via the termux-tools package
Because any version number function would not work below version 0.40 it will just show `<0.40` (assuming it's in the next version).

Here's a sample output:
```
$ termux-info
Termux version:
<0.40
Installed Termux apps:
package:com.termux.api  installer=com.android.vending
package:com.termux.styling  installer=com.android.vending
package:com.termux.widget  installer=com.android.vending
package:com.termux.window  installer=com.android.vending
package:com.termux  installer=com.android.vending
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.84-perf-gfc8e9bb #1 SMP PREEMPT Thu May 5 20:48:38 2016 aarch64 Android
```

**Comment by cpbl** [comment]
termux-info does not report Termux version (as of v.75, v.77)

**Comment by xeffyr** [comment]
@cpbl It no longer prints version - https://github.com/termux/termux-packages/issues/1426.
