### ISSUE TITLE
listing theOCINT pkg for Termux pls

### ISSUE THREAD

**Issue by claythe3ed** [termux/termux-app#1440]
**Feature description**
Describe the feature and why you want it.

**Reference implementation**
Does another app/terminal emulator have this feature?
Provide links to more background information

**Comment by Grimler91** [comment]
Ocint doesn't seem to be a package.

**Comment by claythe3ed** [comment]
OSINT stand for Open Source Intelligence it got so many pkgs for information gathering and social engineering.

**Comment by xeffyr** [comment]
If you are about https://github.com/i3visio/osrframework, then it will not be added.

We do not add python packages using external dependency modules ([requirements.txt](https://github.com/i3visio/osrframework/blob/master/requirements.txt)). Install it with `pip` instead.
