### ISSUE TITLE
termux packages not working under su (not working under root)

### ISSUE THREAD

**Issue by xiaxhck** [termux/termux-app#1441]
When i try the bash commands or other termux packages commands under su (root) it's not working. 
Script like: command not found or permission denied 
But i gave the permission on supersu
I tried everything but it's not working under su 
Please help!!

**Comment by xiaxhck** [comment]
Okay i find the way. We have to use "sudo" command before any needed root tools commands. Got it.

**Comment by gMan1990** [comment]
@cxtiebuxny where is the `sudo` command?
