### ISSUE TITLE
Cannot compile paho-mqtt c library

### ISSUE THREAD

**Issue by Nic2012** [termux/termux-app#1442]
There is another great library supporting mqtt: https://github.com/eclipse/paho.mqtt.c
I tried in termux
```
git clone https://github.com/eclipse/paho.mqtt.c.git
cd paho.mqtt.c
make
...
cc -DNOSTACKTRACE -DNOLOG_MESSAGES src/Thread.c -g -o build/output/test/test1 src/../test/test1.c -lpaho-mqtt3c  -I src -lpthread -L build/output
src/../test/test1.c:148:10: fatal error: 'sys/timeb.h' file not found
#include <sys/timeb.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:218: build/output/test/test1] Error 1
...
```
Seems that ftime isnt supporting in posix anymore, I am not an c expert, how could it be fixed?
Regrads,
Nic

**Comment by xeffyr** [comment]
`sys/timeb.h` is not available for Android.

Add this to appropriate locations in source code:
``` .c
struct timeb {
	time_t time;
	unsigned short int millitm;
	short int timezone;
	short int dstflag;
};
```

`ftime()` is not implemented in Bionic libc as well:
```
int ftime(struct timeb *tb)
{
	struct timeval  tv;
	struct timezone tz;

	if (gettimeofday (&tv, &tz) < 0)
		return -1;

	tb->time    = tv.tv_sec;
	tb->millitm = (tv.tv_usec + 500) / 1000;

	if (tb->millitm == 1000) {
		++tb->time;
		tb->millitm = 0;
	}
	tb->timezone = tz.tz_minuteswest;
	tb->dstflag  = tz.tz_dsttime;

	return 0;
}
```

However, in case https://github.com/eclipse/paho.mqtt.c, you should be able just to avoid compiling tests. See its Android.mk - https://github.com/eclipse/paho.mqtt.c/blob/master/android/Android.mk.

**Comment by Nic2012** [comment]
Thank y for y help.
I was successful in compiling after copied timeb.h from https://android.googlesource.com/platform/development/+/73a5a3b/ndk/platforms/android-20/include/sys/timeb.h eg to folders $PREFIX/include/, ..include/sys and ...include/linux.
