### ISSUE TITLE
Extra-keys and disable termux shortcuts...

### ISSUE THREAD

**Issue by tevig** [termux/termux-app#1443]
**Feature description**
The ability to add holding CTRL on the extra-keys (example 'CTRLh') and disable the built-in termux shortcuts.

**Comment by Grimler91** [comment]
What do you mean by shortcuts?

**Comment by tevig** [comment]
I mean this:
Wiki.termux.com/wiki/Touch_Keyboard

**Comment by tevig** [comment]
CTRL + A
CTRL + C
...
CTRL + Z
these associations can be disabled?

**Comment by Grimler91** [comment]
No, it is not possible. And the problem is that your keyboard sends the wrong keycodes, not that termux messes it up. Test with another keyboard to confirm

**Comment by tevig** [comment]
I apologize, but I did not mean that the problem is in termux. I was just looking for a solution (sorry my bad English)

It is very strange that some of the commands work correctly, and some are mistaken.

**Is it possible to emulate a clamped\hold CTRL in termux (extra-key)?**
That is, CTRL is always pressed. To disable it, you need to click on it again
