### ISSUE TITLE
Upgrade Termux on Android 10.x

### ISSUE THREAD

**Issue by benlavender** [termux/termux-app#1452]
Hi, what’s the easiest method for upgrading Termux on my 10.x device? I notice the app is outputting “You are using legacy termux environment. packages are unmaintained and will not receive any updates” but I don’t see any upgrade path nor available play store updates?

Thanks 

Packages CPU architecture:
aarch64
Subscribed repositories:
sources.list
deb https://termux.net stable main
game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.177-ge3f0ab3137ca #1 SMP PREEMPT Sat Nov 23 02:52:46 UTC 2019 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 2

**Comment by Grimler91** [comment]
Hi, run the script `termux-upgrade-repo`. It should be installed already as part of the package `termux-tools`. 

This will generate a script for reinstalling all packages from the newer repos and then remove $PREFIX to give you a fresh installation. 

All files in $HOME are left alone. After restarting the app you can run `./termux-reinstall.sh` to install everything again.

**Comment by benlavender** [comment]
Thanks that worked
