### ISSUE TITLE
Help me i have a problem

### ISSUE THREAD

**Issue by Hachimiz** [termux/termux-app#1453]
> dpkg: warning: symbolic link '/data/data/com.termux/files/usr/var/service/ftpd/log/run' size has changed from 66 to 62

> `dpkg:` `warning:` `symbolic` `link` '/data/data/com.termux/files/usr/var/service/telnetd/log/run' size has `changed` `from` `66` `to` `62`
Preparing to unpack .../command-not-found_1.46_aarch64.deb...
Unpacking command-not-found (1.46) over (1.42) ...
Preparing to unpack .../inetutils_1.9.4-8_aarch64.deb ...
Unpacking inetutils (1.9.4-8) over (1.9.4-7) ...
Preparing to unpack .../net-tools_1.60.2017.02.21-3_aarch64.deb ...
Unpacking net-tools (1.60.2017.02.21-3) over (1.60.2017.02.21-2) ...
Preparing to unpack .../util-linux_2.35.1_aarch64.deb ...
Unpacking util-linux (2.35.1) over (2.34-2) ...
Setting up net-tools (1.60.2017.02.21-3) ...
Setting up inetutils (1.9.4-8) ...
Setting up busybox (1.31.1-6) ...
dpkg: warning: symbolic link '/data/data/com.termux/files/usr/var/service/telnetd/log/run' size has changed from 66 to 62

Configuration file '/data/data/com.termux/files/usr/var/service/ftpd/run'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** run (Y/I/N/O/D/Z) [default=N] ? Y
Y
Installing new version of config file /data/data/com.termux/files/usr/var/service/ftpd/run ...
dpkg: warning: symbolic link '/data/data/com.termux/files/usr/var/service/ftpd/log/run' size has changed from 66 to 62
Setting up command-not-found (1.46) ...
Setting up util-linux (2.35.1) ...

Why dpkg eror??? 
Cant u help me ????

**Comment by talentlessguy** [comment]
Please edit your comment with proper formatting

use ``` for code, like
```
code
```

**Comment by Hachimiz** [comment]
> Harap edit komentar Anda dengan pemformatan yang tepat
> 
> gunakan `` `untuk kode, seperti
> 
> ```
> code
> ```

Oke

**Comment by xeffyr** [comment]
Closing as `warning` is not `error`. Prompts & notices from your [post](https://github.com/termux/termux-app/issues/1453#issue-558763201) are completely normal and expected during package upgrade.
