### ISSUE TITLE
I have problem in termux installed Virtual anlinux Os Debian

### ISSUE THREAD

**Issue by IndonesiaTermuxCrew** [termux/termux-app#1456]
> root@localhost:~# apt install git
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  git-man less liberror-perl patch
Suggested packages:
  gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs
  git-mediawiki git-svn ed diffutils-doc
The following NEW packages will be installed:
  git git-man less liberror-perl patch
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
Need to get 7356 kB of archives.
After this operation, 38.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian buster/main arm64 less arm64 487-0.1+b1 [117 kB]
Get:2 http://deb.debian.org/debian buster/main arm64 liberror-perl all 0.17027-2 [30.9 kB]
Get:3 http://deb.debian.org/debian buster/main arm64 git-man all 1:2.20.1-2 [1619 kB]
Get:4 http://deb.debian.org/debian buster/main arm64 git arm64 1:2.20.1-2 [5467 kB]
Get:5 http://deb.debian.org/debian buster/main arm64 patch arm64 2.7.6-3+deb10u1 [122 kB]
Fetched 7356 kB in 4s (1832 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package less.
(Reading database ... 45958 files and directories currently installed.)
Preparing to unpack .../less_487-0.1+b1_arm64.deb ...
Unpacking less (487-0.1+b1) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../liberror-perl_0.17027-2_all.deb ...
Unpacking liberror-perl (0.17027-2) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a2.20.1-2_all.deb ...
Unpacking git-man (1:2.20.1-2) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a2.20.1-2_arm64.deb ...
Unpacking git (1:2.20.1-2) ...
Selecting previously unselected package patch.
Preparing to unpack .../patch_2.7.6-3+deb10u1_arm64.deb ...
Unpacking patch (2.7.6-3+deb10u1) ...
Setting up udisks2 (2.8.1-4) ...
Failed to scan devices: No such file or directory
dpkg: error processing package udisks2 (--configure):
 installed udisks2 package post-installation script subprocess returned error exit status 1
Setting up less (487-0.1+b1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
dpkg: dependency problems prevent configuration of gvfs-daemons:
 gvfs-daemons depends on udisks2; however:
  Package udisks2 is not configured yet.

> dpkg: error processing package gvfs-daemons (--configure):

> dependency problems - leaving unconfigured

> Setting up liberror-perl (0.17027-2) ...

> Setting up patch (2.7.6-3+deb10u1) ...

> Setting up git-man (1:2.20.1-2) ...

> dpkg: dependency problems prevent configuration of gvfs:arm64:

 

> gvfs:arm64 depends on gvfs-daemons (<< 1.38.1-5.1~); however:

 

>  Package gvfs-daemons is not configured yet.

 

> gvfs:arm64 depends on gvfs-daemons (>= 1.38.1-5); however:

> Package gvfs-daemons is not configured yet.

> dpkg: error processing package gvfs:arm64 (--configure):

> dependency problems - leaving unconfigured

> Setting up git (1:2.20.1-2) ...

> Processing triggers for man-db (2.8.5-2) ...

> Errors were encountered while processing:

> udisks2

 

> gvfs-daemons

 

> gvfs:arm64

> E: Sub-process /usr/bin/dpkg returned an error 

> code (1)

` can you help me with this problem ???? `

**Comment by imprakharshukla** [comment]
Do this for udisks2
```
sudo apt install udisks2 -y
echo "" > /var/lib/dpkg/info/udisks2.postinst
sudo dpkg --configure -a
sudo apt-mark hold udisks2
```
