### ISSUE TITLE
Numpad key '0' react as '1'

### ISSUE THREAD

**Issue by t123yh** [termux/termux-app#146]
![screenshot_20160825-145252](https://cloud.githubusercontent.com/assets/8972552/17959601/f4c535c0-6a66-11e6-9991-4e9b5182dc0b.png)

The 144 is when I press '0', and 145 is when I press '1'.

**Comment by t123yh** [comment]
![screenshot_20160825-145714](https://cloud.githubusercontent.com/assets/8972552/17959638/44f15f2e-6a67-11e6-8732-f7557d1b48b9.png)
And numpad '.'(Dot) doesn't work, either.

**Comment by fornwall** [comment]
Is this with a USB OTG keyboard?

**Comment by t123yh** [comment]
@fornwall Yes.

**Comment by fornwall** [comment]
@t123yh Thanks for the great bug report! This has been fixed in the newly released `0.41` version which should be available as an update shortly.
