### ISSUE TITLE
Bug in pop-up

### ISSUE THREAD

**Issue by Morpheus2077** [termux/termux-app#1462]
![Screenshot_20200215-130647~2](https://user-images.githubusercontent.com/57775700/74591796-aca27380-4ff9-11ea-9e44-f957bc2fcd73.png)

my copy text box is over diplay text

Device: Mi A2 running Android 10
Termux: 0.92

**Comment by xeffyr** [comment]
This is not a bug. You can move this box to any place you want, but default is exactly above text selection.

**Comment by Morpheus2077** [comment]
ah yes, sorry did not know, how i change

**Comment by Morpheus2077** [comment]
ah yes, sorry did not know, how i change
