### ISSUE TITLE
How to make a terminal of your own with a graphical interface and how to get all the tools

### ISSUE THREAD

**Issue by kalicsv** [termux/termux-app#1464]
<！-nIMPORTANT：nN1。对Android5.x-6.x的支持已经完成。N2。在注释后填写模板。n->n**问题描述**n<！-问题是什么？除了描述之外，你还可以发布截图。n->n n**步骤复制**n<！-n步来再现行为。请张贴所有必要的n命令，需要复制问题。n->n*预期的行为**n<！-对你期望发生的事情有一个清晰而简明的描述。n->n**附加信息**n*Termux应用程序版本：n*Android操作系统版本：n*设备模型：

**Comment by Grimler91** [comment]
Android 5 and 6 are no longer supported.
