### ISSUE TITLE
nmap

### ISSUE THREAD

**Issue by kalicsv** [termux/termux-app#1465]
<！-nIMPORTANT：nN1。对Android5.x-6.x的支持已经完成。N2。在注释后填写模板。n->n**特征描述**n<！-描述该特性以及需要它的原因。n->n**引用实现**n n另一个应用程序/终端仿真器有此特性吗？提供指向更多背景信息的链接。

**Comment by Grimler91** [comment]
Android 5 and 6 are no longer supported.
