### ISSUE TITLE
netstat does not work correctly

### ISSUE THREAD

**Issue by Zibri** [termux/termux-app#1466]
Why does "netstat for android" app work and the netstat command in termux does not?
netstat for android chan show all apps listening ports while netstat complains for access problems.

**Comment by xeffyr** [comment]
> Why does "netstat for android" app work

Because it retrieves data through Android API and not the /proc/net interface.

**Comment by Anonymous2716** [comment]
Solution?!!

**Comment by xeffyr** [comment]
> Solution?!!

Rooted device. There no other solutions for Android SELinux hardening.
