### ISSUE TITLE
all possible permissions

### ISSUE THREAD

**Issue by Zibri** [termux/termux-app#1467]
instead of rooting, wouldn't be better to have termux ask for ALL android permission and then use a lesf signed certificate to rebuild the apk and install it??

**Comment by xeffyr** [comment]
> instead of rooting, wouldn't be better to have termux ask for ALL android permission

root is not achievable by asking all Android permissions. Especially when some of them possible only for system applications.

**Comment by Zibri** [comment]
I know that. I was suggesting a parallel release, an apk which asks all permissions. (then pm grant can do the rest).
