### ISSUE TITLE
Adding a login and a lock feature to termux

### ISSUE THREAD

**Issue by samiuljoy** [termux/termux-app#1470]
Thank you for taking your time to create such an amazing app c:
I'd like to make a little suggestion, perhaps a new addtion to termux app!
Introduction  of a Lock Feature!
I wrote a script (https://github.com/samiuljoy/useradd-and-login-script) the othet day(it still needs some modifications) to add user and whenever a person presses lock, the terminal gets locked, and after pressing the correct username and password, the user may login. For example: a person has to go somewhere but leaves the phone someplace, if it isn't locked, someone with proper linux skill can access all the data in termux home, so I think adding a lock feature can be helpful. 
![Screenshot_2020-02-22-03-15-28](https://user-images.githubusercontent.com/51329626/75072440-b4927400-5521-11ea-9273-01f62a94650a.png)
It still has some bugs and needs some more features like logging and such,  however I think it might be helpful c: I hope that this feature can be added c:
N.B: If you happen to like my theme >> https://github.com/samiuljoy/custom_bash_for_termux/blob/master/10.png

**Comment by xeffyr** [comment]
Can be easily bypassed with "failsafe shell" feature. Termux is not going to be designed for local password login.

**Comment by samiuljoy** [comment]
I feel so embarrased right now knowing that, can you delete this issue please...apparently I dont have an option to delete
