### ISSUE TITLE
App crashes after Vim command

### ISSUE THREAD

**Issue by MichaelC2-718** [termux/termux-app#1471]
**Problem description**

I was editing a 200+ MB text file in vim. I attempted to run a substitution command, but the app crashed after my keyboard hid of its own accord. I am using [Gboard](https://www.google.com/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dcom.google.android.inputmethod.latin%26hl%3Den_US%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Dgboard%26pcampaignid%3DAPPU_1_KxVTXuLVMcGX-gSM7L_QAQ&ved=2ahUKEwiil6_u8-jnAhXBi54KHQz2DxoQ5YQBMAB6BAgREAI&usg=AOvVaw1fjk9CEEWAqII0RPpehHrM). Both apps are up to date as of 2/23/2020.

**Steps to reproduce**

```
$vim primes.txt
:%s/\n/ /g
```
I also tried it without the trailing g. Both times the command began successfully, but then my keyboard hid and one of the following occurred:
- The app closed unexpectedly
- Vim exited, I saw `Killed`, and the bash prompt appeared without clearing the vim text—see image

![Screenshot_20200223-172502](https://user-images.githubusercontent.com/59812288/75123081-7dc37780-5661-11ea-95a4-fbebfc3e86f0.png)

**Expected behavior**

I expected vim to complete the command without crashing.

**Additional information**

* Termux application version: 0.92
* Gboard application version: 9.0.10.293664837-release-arm64-v8a
* Android OS version: 7.0
* Device model: SAMSUNG-SM-G
920A
* Kernel version: 3.10.61-12991177

**Comment by xeffyr** [comment]
That's out-of-memory condition, i.e. Android kills process using a lot of RAM. This cannot be fixed on Termux side.
