### ISSUE TITLE
continually repeated symbol "~" when the app is launched

### ISSUE THREAD

**Issue by EzePerez** [termux/termux-app#1472]
Hi, i have a simple but really big problem. When i launch termux app, it starts to write the symbol "~" continuosly and constantly in the prompt. it doesn't stop at all. 
I've been using the app for a couple of weeks for practicing python and connecting through ssh and it worked normally. I reinstalled the app but it didn't solve the problem, even when i open a failsafe session the problem is still there. I don't have any idea what is going on. Thanks for the help.

![termux bug 2](https://user-images.githubusercontent.com/53160017/75285093-ba73a800-57f4-11ea-87d8-14b49fb84a5f.jpeg)
![termux bug](https://user-images.githubusercontent.com/53160017/75285099-bba4d500-57f4-11ea-8ac2-f825644a3dd3.jpeg)

* Termux application version: 0.92
* Android OS version: 7.0
* Device model: Philips S329

**Comment by imprakharshukla** [comment]
Can you try switching your keyboard, maybe that solves the issue for you.

**Comment by Grimler91** [comment]
Does this happen also if you ssh into termux? Are you using the standard android keyboard? Are you using the standard shell (bash)?

**Comment by EzePerez** [comment]
Hi! one week ago i changed the default language and theme of the keyboard and the problem seems to be fixed. I've been using it this week for testing if the problem comes back and worked well until now. Thanks for your replies.

**Comment by Daiman1993** [comment]
oke
