### ISSUE TITLE
please show Me require ignore battery optimisation code

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-app#1474]
Dear specialists,
I do not see at all and I love. programming. Because I can not see so perfect code like Termux is using to recall simple ignore battery optimisation dialog. Which Termux recall, when user press acquire wakelock in The notification area.
Would somebody of you be so kind and would somebody of you copy The code from Termux srouce, which is capable to recall ignore battery optimisation dialog?
I can not find The code somewhere else on The Internet.
Thank you very very much for yours time.
I do not know, which file contain The code. If C part of Termux or Java.

**Comment by xeffyr** [comment]
> Would somebody of you be so kind and would somebody of you copy The code from Termux srouce, which is capable to recall ignore battery optimisation dialog?

https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/TermuxService.java#L118
