### ISSUE TITLE
Home key on a bluetooth keyboard does not work

### ISSUE THREAD

**Issue by Mihara** [termux/termux-app#148]
Thanks for making proper Linux on Android practical! Now it's just a matter of getting it all to work smoothly.

It took me a while to figure out why the escape key on my bluetooth keyboard isn't working, but once I found out that it's sending KeyCode 4, which is KEYCODE_BACK, I've been able to fix this through `termux.properties`.

But now I have another problem - the key for Home cursor move (Fn+Left) is not getting registered at all, (tested with `vtshowkeys`) even though it's sending keycode 122, which *should* be MOVE_HOME. It is otherwise identical to the Left key *(same Meta State, same source, same keyboard type, the only thing different is the key code)* so it should, in theory, work, but doesn't.

As a side note, External Keyboard Helper *(which I can't use to remap keys, since it completely borks Alt keys in Termux. I haven't been able to figure out why.)* has one right idea: It is supposed to be capable of only reinterpreting keys if they come from an input device with an ID that is higher than a certain threshold. Hardware keys on the device itself typically come first, so you can have the back key on the device and the escape key on the keyboard at the same time. Could this possibly be implemented for the 'escape' setting in `termux.properties`?

**Comment by fornwall** [comment]
Thanks - the Home key should now work as of the newly released version `0.40` update, which should be available as an update for everyone shortly!

Let me know if it doesn't work after updating to version `0.40`!

**Comment by Mihara** [comment]
It works, no further keyboard issues to report. 👍 

Please consider if it is possible to tell devices apart buy their evdev ID number though, that would make working with an external keyboard considerably easier.
