### ISSUE TITLE
Floating buttons

### ISSUE THREAD

**Issue by jimmy0699** [termux/termux-app#1482]
Ability do add / configure floating buttons that sends text to termux. This gives much more flexibility and speed up work and make it more easy. Also gives field for future development, ie: user may configure set of buttons and switch them using buttons itself or define different action if button is hold or swiped etc..., user builds his own kind of keyboard dedicated to his work. May works as 3rd party termux package. Similar to those from blowtorch app

![screen-0](https://user-images.githubusercontent.com/3270903/76218431-8a74cd80-6214-11ea-8038-2d2614b35f25.jpg)

**Comment by mwalimu-prog** [comment]
Looks awesome.

**Comment by twaik** [comment]
We already have ExtraKeys bar for people who needs additional keys and popup feature for people who needs more keys than ExtraKeys can contain normally.

**Comment by twaik** [comment]
Duplicate of #342
