### ISSUE TITLE
Can't run c++ codes

### ISSUE THREAD

**Issue by BruceMoustache** [termux/termux-app#1486]
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
$ g++ hello.cpp
hello.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
$

**Comment by xeffyr** [comment]
Make sure your include line is exactly `#include <iostream>`.
