### ISSUE TITLE
Seems to switch to root, but still does not have permissions. Can you help me. I use magisk. And termux and packages are up to date

### ISSUE THREAD

**Issue by yyy33** [termux/termux-app#1487]
$ tsu
# whoami
root
$ tsu
# cd /system
# touch aa
touch: cannot touch 'aa': Read-only file system
# ls -ld .                                      drwxr-xr-x 22 root root 4096 Feb 27 14:36 .     #1482

**Comment by xeffyr** [comment]
That's expected. You need to remount /system in RW-mode manually.

**Comment by yyy33** [comment]
> That's expected. You need to remount /system in RW-mode manually.

Thanks
