### ISSUE TITLE
Compatibility with replicant OS

### ISSUE THREAD

**Issue by millerebonds** [termux/termux-app#1488]
Hello, 
I have replicant 6 on a samsung S3 i9300, and termux was compatible.
Now with the new versions, it's incompatible. I use f-droid.

Termux is very useful for me, to use w3m and search some little informations on internet without comsuming too much data.

**Feature description**

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by Grimler91** [comment]
I guess you are on android 5 or 6? We dropped support for android 5 and 6 in the beginning of this year so the only way you can get the app is to compile it yourself (or download an older version)

**Comment by millerebonds** [comment]
replicant 6 is based on android 6.0.1

I don't know how to compile it myself. I made very little compilation on the computer, using make and not understanding a lot.

Maybe a fork for replicant would be a solution?

**Comment by xeffyr** [comment]
Last stuff available for Android 5.x-6.x available here - https://archive.org/download/termux-repositories-legacy.
