### ISSUE TITLE
service_wake_lock can only work on power supply and WiFi, not on jupyter

### ISSUE THREAD

**Issue by jiangsy163** [termux/termux-app#1489]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: 
* Android OS version: 
* Device model: Huawei P30 Pro

**Comment by jiangsy163** [comment]
Android 10 , sets the power consumption management to manual, the jupyter can run in the background

**Comment by Grimler91** [comment]
Not sure what you are saying here.
Jupyter freezes even though you have a wake lock but if you changed a power management setting it works?

**Comment by xeffyr** [comment]
Wake lock affects only condition whether will device's CPU go to sleep mode or not. It does not affect advanced power management such as process freezing used on Huawei devices.

As I know, there no way to whitelist Termux from freeze cgroup without root or changing the ROM.
