### ISSUE TITLE
Turn off extra Keys

### ISSUE THREAD

**Issue by PandaSITT** [termux/termux-app#1491]
**Feature description**

**Reference implementation**

I've installed Termux on my Chromebook.
Since a Chromebook has an almost complete keyboard the extra keys are useless.
Can you guys add a feature to turn off the extra keys?
Btw I love the app

**Comment by xeffyr** [comment]
Open drawer (swipe right or ctrl+alt+right arrow on physical keyboard), then long click on "keyboard" button.
