### ISSUE TITLE
Repeating characters on Samsung keyboard

### ISSUE THREAD

**Issue by danieliasantos** [termux/termux-app#1492]
**Problem description**
Repeating characters when using the standard keyboard of the Samsung Galaxy Note 9 with Android 10, as if with high repetition sensitivity. Makes it impossible to enter passwords.

**Steps to reproduce**
Just use the Samsung Keyboard on Termux command line.

**Expected behavior**
Do not repeat characters.

**Comment by xeffyr** [comment]
Shoudl be fixable by https://wiki.termux.com/wiki/Terminal_Settings#Workaround_for_some_keyboards_issues.
