### ISSUE TITLE
Что делать, если вылазит данная ошибка в Termux 

### ISSUE THREAD

**Issue by DamFx** [termux/termux-app#1495]
Подскажите, что делать при этой ошибке:
CANNOT LINK EXECUTABLE "/system/bin/sh": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
И как её исправить?

**Comment by xeffyr** [comment]
`unset LD_PRELOAD`.

На некоторых устройствах бинарники в /system/bin 32-битные несмотря на то, что сборка Android 64-бит.
