### ISSUE TITLE
  Tsu failed to promote permission。android7.1.2 CPU mtk6795

### ISSUE THREAD

**Issue by mashen11** [termux/termux-app#1496]
**Additional information**

* Termux application version:0.9.2
* Android OS version:7.1.2
* Device model:leTv x500

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/zsh": cannot locate symbol "ucnv_open_56" referenced by "/system/lib64/libmtk_symbols.so"...
Aborted

**Comment by xeffyr** [comment]
Report this to https://github.com/cswl/tsu.
