### ISSUE TITLE
Option to quit app

### ISSUE THREAD

**Issue by razzintown** [termux/termux-app#15]
There is no clear way to quit the app, even after selecting Hangup.

**Comment by fornwall** [comment]
You can close the session by pressing return when the `Process completed` message is shown - if this was the last active session, the app will quit. It's also possible to quit by pinch-expanding the Termux notification which shows an "EXIT" action on it.

I agree that it's not clear enough how to exit. Perhaps appending `- press Enter to quit` to the `Process completed message` could be a solution?

**Comment by jarrettgilliam** [comment]
What about just closing that session and sending the `Process completed` message as a toast notification?

**Comment by fornwall** [comment]
@jarrettgilliam The drawback with automatically closing the session is that the terminal can sometimes contain information that you do not want to miss, if you accidentally closed the session or something crashed.

I'm leaning on trying out `- press Enter to close` in the next update and see how it's received!

**Comment by jarrettgilliam** [comment]
@fornwall Ah, that makes sense. Good call.

**Comment by fornwall** [comment]
The `- press Enter to close` message will be in the next release (version 0.20) - thanks for the feedback!

**Comment by trusktr** [comment]
This still isn't convenient.

1. There's no notification that I can pinch-zoom to open to press exit.
2. If I have 10 sessions open, I have to go exit out of each manually. It's even more tedious if I have more sessions open.
3. Furthermore it is difficult to quit some sessions manually as they involve multiple steps. For.e. to quit a session with vim we have to type commands to exit vim first, then we can press Ctrl+d,enter. It's too much.

Ideal:

1. There should just be an option in the menu to quit Termux (all sessions).
2. It would also be simple if it just quit when we swiped the app away from the Android app switcher view.

**Comment by xeffyr** [comment]
> How do you exit in Vim?

ESC + "`:x`" (or "`:q`").

> Even using the emulator doesn't seem to work.

You can't pass ESC to the emulator, use Extra Key Row (https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row) in Termux instead.

**Comment by Tracyorama** [comment]
I just close the app and start a new session, then I pkg remove app responsible and the following video shows how to kill sessions: https://youtu.be/K2qMhpfAfXU

**Comment by WAC11** [comment]
this video is great. i installed termux in my mob but was figuring how to kill session or go back to cursor as it was stuck

**Comment by reydloto** [comment]
How quit toilet tool?
