### ISSUE TITLE
Termux su bad system call

### ISSUE THREAD

**Issue by ysuf0** [termux/termux-app#1500]
İ am use custom rom (dotOS). i made try root with twrp super su zip file. Another app say "no root" but termux say `Bad system call`. How can i fix it 
![Screenshot_20200329-124415_Termux](https://user-images.githubusercontent.com/37940536/77845913-0f6f5900-71bb-11ea-909d-3223a2181ca0.png)

**Comment by xeffyr** [comment]
Check out on https://forum.xda-developers.com/ how to properly root your device. It seems you are using wrong/outdated supersu file incompatible with your OS.

There is nothing to do with Termux itself.

**Comment by xeffyr** [comment]
Locking as offtopic.
