### ISSUE TITLE
ERROR: ld.so: object '/lib/aarch64-linux-gnu/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored

### ISSUE THREAD

**Issue by saihum** [termux/termux-app#1505]
Sorry,a total noob herezipper_mouth_face I was trying to install ubuntu19 through termux.but Whenever I started vncserver.. I see this error..can anyone tell me what am I missing here? The error follows:
ERROR: ld.so: object '/lib/aarch64-linux-gnu/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by xeffyr** [comment]
Check if libgcc is installed.
