### ISSUE TITLE
Crashes when doing complex and memory consuming commands tasks.

### ISSUE THREAD

**Issue by warriorstar123** [termux/termux-app#1509]
Recently termux app has got unstable and keeps crashing when complex tasks such as video conversion with ffmpeg or processing big files or handling big chunks of data are being done. It cannot handle high memory consumption, the phone initially hangs and termux got crashed and exited.

**Comment by xeffyr** [comment]
Packages are not related to application stability.

What you are observing is an out-of-memory condition. We can't do anything with that. Android devices aren't PC's and are not designed for operations requiring lots of resources
```
processing big files or handling big chunks of data
```
Android OS will automatically kill resource-intensitive tasks to prevent lock down of whole device.
