### ISSUE TITLE
Sqlite3 not install

### ISSUE THREAD

**Issue by rajagupt01** [termux/termux-app#1511]
npm install sqlite3
nFailed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/data/data/com.termux/files/home/RajaIsLive/node_modules/sqlite3/lib/binding/node-v79-android-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/data/data/com.termux/files/home/RajaIsLive/node_modules/sqlite3/lib/binding/node-v79-android-arm64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)

**Comment by xeffyr** [comment]
`pkg install clang libsqlite pkg-config` before doing `npm install`.

**Comment by mixnenu** [comment]
thanks

**Comment by rajagupt01** [comment]
Again same problem were detected


npm install
Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/data/data/com.termux/files/home/RajaIsLive/node_modules/sqlite3/lib/binding/node-v79-android-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/data/data/com.termux/files/home/RajaIsLive/node_modules/sqlite3/lib/binding/node-v79-android-arm64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)

**Comment by rajagupt01** [comment]
$ pkg-config
The program pkg-config is not installed. Install it by executing:
 pkg install pkg-config
$
$ pkg-config
The program pkg-config is not installed. Install it by executing:
 pkg install pkg-config
$ pkg install clang libsqlite pkg-config
Reading package lists... Done
Building dependency tree
Reading state information... Done
clang is already the newest version (9.0.1-5).
libsqlite is already the newest version (3.31.1).
The following additional packages will be installed:
  glib
The following NEW packages will be installed:
  glib pkg-config
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 1058 kB of archives.
After this operation, 5747 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 glib aarch64 2.64.2 [1032 kB]
Get:2 https://dl.bintray.com/termux/termux-packages-24 stable/main aarch64 pkg-config aarch64 0.29.2 [25.9 kB]
Fetched 1058 kB in 19s (55.4 kB/s)
Selecting previously unselected package glib.
(Reading database ... 17082 files and directories currently installed.)
Preparing to unpack .../glib_2.64.2_aarch64.deb ...
Unpacking glib (2.64.2) ...
Selecting previously unselected package pkg-config.
Preparing to unpack .../pkg-config_0.29.2_aarch64.deb ...
Unpacking pkg-config (0.29.2) ...
Setting up glib (2.64.2) ...
Setting up pkg-config (0.29.2) ...
Processing triggers for man (1.14.5-1) ...
$ npm start
Please run "npm install" again! Package "sqlite3" is missing.
$ npm install
Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/data/data/com.termux/files/home/RajaIsLive/node_modules/sqlite3/lib/binding/node-v79-android-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/data/data/com.termux/files/home/RajaIsLive/node_modules/sqlite3/lib/binding/node-v79-android-arm64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
$

**Comment by xeffyr** [comment]
You have problem somewhere else then.
sqlite installation works.

![Screenshot_20200414-134137_Termux](https://user-images.githubusercontent.com/25881154/79216582-17cfc100-7e56-11ea-93c0-c5942b340eda.jpg)

**Comment by rajagupt01** [comment]
![Screenshot_20200414-185245_Termux](https://user-images.githubusercontent.com/63354685/79229757-2bdce800-7e81-11ea-999e-175a90aafe2c.jpg)
Problem is that the Android -arm64 not founded

**Comment by rajagupt01** [comment]
![Screenshot_20200414-185759_Termux](https://user-images.githubusercontent.com/63354685/79230226-e2d96380-7e81-11ea-9e96-1c80a968ad8a.jpg)

**Comment by xeffyr** [comment]
> Problem is that the Android -arm64 not founded

Those do not exist. You need to compile it from source.

If gyp is used, you need more packages:
```
pkg install clang libsqlite pkg-config python make
```

**Comment by rajagupt01** [comment]
Not worked sir again and again what can i do

**Comment by rajagupt01** [comment]
![Screenshot_20200414-200529_Termux](https://user-images.githubusercontent.com/63354685/79237032-52a01c00-7e8b-11ea-87ac-dcaa4623bd33.jpg)

**Comment by xeffyr** [comment]
> Not worked sir again

I have no idea why you see my commands truncated...

Posting again (one line, begins with `pkg` and ends with `make`):
```
pkg install clang libsqlite pkg-config python make
```

**Comment by rajagupt01** [comment]
Sir please you can compiled in your side and then me to full process

**Comment by rajagupt01** [comment]
Sqlite3 already installed they don't find android arm-64 please you can compile your send send me to android-64 node file please.
