### ISSUE TITLE
[Feature request] add setting option to set `home` dir under `/storage/xxx/`

### ISSUE THREAD

**Issue by stevenleeS0ht** [termux/termux-app#1512]
**Feature description**
add option to set `home` directory to `/storage/xxx` or other file-manager accessible locatoin.

It can bring much more convenient for  user.

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by Grimler91** [comment]
Just add `cd /storage/xxx` to your ~/.bashrc and you will be there per default. Note that you can't have executable files in the shared storage so trying to use it like homedir will have drawbacks
