### ISSUE TITLE
Can't take full screen screenshot due to soft keyboard

### ISSUE THREAD

**Issue by bengalih** [termux/termux-app#1520]
**Problem description**
Can't take full screen screenshot because soft keyboard continually pops up when Termux gets focus.

**Steps to reproduce**
Minimize soft-keyboard so Termux is full screen.
Press power button to take screen shot (Pixel 3 Android 10)

**Expected behavior**
Screen shot will take screen exactly as it looks when power button was pressed.
Instead, when system passes control back to Termux it pops back open the soft keyboard.

This effecitvely prevents getting a screen shot of more than about 60-70% of terminal window.

**Additional information**

* Termux application version: 0.94
* Android OS version: 10
* Device model: Pixel 3XL

**Comment by Grimler91** [comment]
I am not familiar with the pixel, but quite a lot of devices also take screenshots when you hold volume down + power button. If I do that I can take screenshots without the keyboard. Does that work for you?

**Comment by bengalih** [comment]
@Grimler91 Yes.  Thanks that works for now.  I've always had issues with that shortcut on many devices, and stopped trying to use it once Pixel introduced the ability to take it through the power menu after holding just the power button.  For now this is a good workaround, but I'm not sure what the need to bring the soft keyboard back into focus automatically when switching back to the app.  One would think that if a user minimized the keyboard that they would want to keep it minimized until tapping into the terminal window to bring it back into focus.
Hopefully this can be included as default behavior or an option on a future release.

**Comment by agnostic-apollo** [comment]
Install [v0.113](https://github.com/termux/termux-app/releases/tag/v0.113) when its released on F-Droid and add the line `soft-keyboard-toggle-behaviour=enable/disable` in `~/termux.properties` file to change default behaviour of keyboard toggle buttons to `enable/disable`. In this mode, tapping a keyboard toggle button will disable (and hide) the keyboard and tapping on the terminal view will not open the keybaord automatically, until a keyboard toggle button is pressed again manually. The extra keys and left drawer `KEYBOARD` toggle button and `ctrl+alt+k` hardware keyboard shortcut is whats referred as keyboard toggle buttons.
