### ISSUE TITLE
Help me plz ... What can I do to avoid this error?

### ISSUE THREAD

**Issue by meybod** [termux/termux-app#1521]
![Screenshot_20200420-091208](https://user-images.githubusercontent.com/63988303/79715291-9b6f2f00-82e8-11ea-927c-0da834f41e6b.png)
I want update this...
404 not found error
what can I do?!

**Comment by xeffyr** [comment]
Switching to next Ubuntu version is everything that you can do.

Ubuntu Disco v19.04 is short-living release which is supported only 9 months. Support ended in January 2020 and it seems to be completely purged from servers recently.
