### ISSUE TITLE
Visiting an HTML file in Termux HOME

### ISSUE THREAD

**Issue by angelog0** [termux/termux-app#1522]
Maybe this is not an issue.

In my home I have this HTML file

```
$ ls $PWD/foo.html
/data/data/com.termux/files/home/foo.html
```

but when I copy/paste it in Chromium address bar and try to visit it (in Emacs jargon), the browser says "file not found", even if it hast the right URL

`file:///data/data/com.termux/files/home/foo.html`

Notice that often I do the same on Windows, GNU/Linux or macOS...

**Comment by xeffyr** [comment]
`file:///data/data/com.termux/files/home/foo.html` isn't correct way for accessing files under $HOME. Third-party apps which do not have same uid and SELinux label can't access these files directly.

Use `termux-open` instead.

**Comment by angelog0** [comment]
...but when I use `termux-open` the browser ask for downloading `foo.htm` into its `Download` folder (under `/sdcard/`). It is the same as if in Termux

`$ cp foo.html /sdcard/Download/`

and copy/paste `/sdcard/Download/foo.html` in the browser

**Comment by Grimler91** [comment]
> ...but when I use termux-open the browser ask for downloading foo.html into its Download folder (under /sdcard/)

Maybe try another browser, when I tried it just now it works fine, with firefox

**Comment by xeffyr** [comment]
Most ROMs have built-in HTML viewer which is able to handle intents sent by `termux-open`.

**Comment by angelog0** [comment]
> Maybe try another browser, when I tried it just now it works fine, with firefox

sure it has been copied in firefox download folder?

**Comment by angelog0** [comment]
just out of curiosity.. Why does Termux uses `/data/data/com.termux/files/home` as HOME directory and does not create something like `../home/owner`?  ..and why `ls -l` display `u0_a95` as user and group? if the user is `u0_a95` i would expect to find `.../home/u0_a95` folder...

I'm sorry to take advantage of your patience...

**Comment by xeffyr** [comment]
Because each Android application is a sandbox with own user id and groups. Application, same as Linux user, can have only one user id.

**Comment by Grimler91** [comment]
Termux is just a terminal emulator, and android is not a GNU/Linux OS. Some of the differences between termux and a "normal" GNU/Linux OS is described in the wiki:
https://wiki.termux.com/wiki/Differences_from_Linux

Some [apps need to to know HOME during compilation](https://github.com/termux/termux-packages/blob/f679a18402681a15c60f8f9b8b9c82843a041917/scripts/build/termux_step_setup_variables.sh#L25)

I guess we can close this issue

**Comment by RalfWerner** [comment]
## 6 shots on the subject and Android 11:
In **shot1** is _this issue_ opened with `termux-open` (_chrome_ with Android 9 device). In **shot2** (R11) _this **failed**_ because `am` just does not work in R11 and `t.html` was generated. In **shot4** I selected _it_ with the _file app_ select _Chrome_ in **shot5** and  displayed it - **shot6**.
![grafik](https://user-images.githubusercontent.com/45426380/79773465-c9c52c80-8331-11ea-9983-3955fa6b8d61.png)
