### ISSUE TITLE
Failed to compile native code with NDK

### ISSUE THREAD

**Issue by tomchrisdperez** [termux/termux-app#1524]
**Problem description**
On windows platform, when starting build it said "crtbegin_so.o" does not exist.
Error while executing process E:\androidsdk\nsdk\ndk\21.0.6113669\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\androidsdk\termux-app-master\terminal-emulator\src\main\jni\Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=E:/androidsdk/termux-app-master/terminal-emulator/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\androidsdk\termux-app-master\terminal-emulator\build\intermediates\ndkBuild\debug\lib APP_CFLAGS+=-std=c11 APP_CFLAGS+=-Wall APP_CFLAGS+=-Wextra APP_CFLAGS+=-Werror APP_CFLAGS+=-Os APP_CFLAGS+=-fno-stack-protector APP_CFLAGS+=-Wl,--gc-sections termux}
  [armeabi-v7a] Compile thumb  : termux <= termux.c
  [armeabi-v7a] SharedLibrary  : libtermux.so
  
  E:/androidsdk/nsdk/ndk/21.0.6113669/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot open crtbegin_so.o: No such file or directory
  E:/androidsdk/nsdk/ndk/21.0.6113669/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot open crtend_so.o: No such file or directory
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  make: *** [E:/androidsdk/nsdk/ndk/21.0.6113669/build//../build/core/build-binary.mk:725: E:/androidsdk/termux-app-master/terminal-emulator/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libtermux.so] Error 1

**Comment by xeffyr** [comment]
Have you tried to build it with Android Studio, i.e. without manual ndk-build call ?

**Comment by tomchrisdperez** [comment]
I'm already using android studio to build it. NDK is the latest version.

**Comment by xeffyr** [comment]
I can't reproduce the issue on my Windows 10 machine.

No NDK issues during build time:
![win10-1 screenshot](https://user-images.githubusercontent.com/25881154/79874171-b2994400-83f0-11ea-9f61-1d74406047d3.png)

APK built successfully:
![win10-2](https://user-images.githubusercontent.com/25881154/79874420-060b9200-83f1-11ea-89f5-06e04666a921.png)

**Comment by xeffyr** [comment]
`crtbegin_so.o" does not exist` clearly shows that issue is with your NDK installation and not with Termux app sources.
