### ISSUE TITLE
access getfattr from adb shell (root)

### ISSUE THREAD

**Issue by dkwo** [termux/termux-app#1526]
I'm sure this is not a bug, just me being dumb.

I installed termux from playstore, and from termux pkg install attr.
I reboot intro twrp recovery, decrypt my partition, and adb shell.
Now I have a root shell, and would like to use the getfattr command from termux on some file.
I understand from #77 I should export PATH and LD_LIBRARY_PATH, but I keep getting error 'No such file or directory'.

What is the correct way of doing this?

**Comment by Grimler91** [comment]
So you are in a recovery shell, is `/data` mounted? Does `ls /data/data/com.termux/files/` show you termux's folders?

**Comment by xeffyr** [comment]
`/system` should be mounted as it provides dynamic linker (`/system/bin/linker` or `/system/bin/linker64`) and `libc`.

**Comment by dkwo** [comment]
@Grimler91 `/data/data` is mounted, as I can `ls` stuff there.
@xeffyr Could you remind me where to mount it? after that, should I still export `PATH` etc as in the other thread?
Thanks.

**Comment by xeffyr** [comment]
If you are launching Termux from **recovery** (CWM or TWRP) shell:
```
adb shell
mount /data
mount /system
export PREFIX=/data/data/com.termux/files/usr
export PATH=$PREFIX/bin:$PATH
export TMPDIR=/tmp
```
Variable `LD_LIBRARY_PATH` is not needed if you have Android 7 and higher.
`HOME` can be set to `/`.

**Comment by dkwo** [comment]
I'm launching indeed from TWRP recovery, but this is what I get:

$ adb shell
willow:/ # mount /data
mount: '/dev/block/mmcblk0p87'->'/data': Device or resource busy
1|willow:/ # mount /system
mount: '/system' not in fstab

**Comment by xeffyr** [comment]
> 1|willow:/ # mount /system
mount: '/system' not in fstab

I'm wondering how recovery determines the block device for `/system` partition if `/etc/recovery.fstab` doesn't have it specified.

Unfortunately I can't tell you different command for mounting `/system`. Block device name is unique per each device model. Determine it yourself by rebooting into Android and checking output of command `mount`, then in recovery do something like
```
mount BLOCK_DEVICE_PATH /system
```
If this will not work, the only thing you can try is
```
mkdir -p /system/bin
ln -s /sbin/linker /system/bin/linker
```
If your device is 64bit, additionally do
```
ln -s /sbin/linker64 /system/bin/linker64
```

**Comment by xeffyr** [comment]
You may have a ramdisk-less Android setup - in this case `/system` is a part of rootfs. Mounting of "system" partition will be complex in this case:
```
mkdir -p /tmp/rootfs
mount BLOCK_DEVICE_PATH /tmp/rootfs
mkdir -p /system
mount --bind /tmp/rootfs/system /system
```
`BLOCK_DEVICE_PATH` should be determined from output of `mount` or `cat /proc/mounts`.

**Comment by dkwo** [comment]
Thanks anyway, I realised I can just enable root for adb shell from inside lineageos, and then `adb root` can use `getfattr`. Dumb me ;)
