### ISSUE TITLE
Can't put selection start point between 5th and 9th column

### ISSUE THREAD

**Issue by bpsib** [termux/termux-app#1527]
**Problem description**
I can't put the text selection start point anywhere between column 4 and 9. It just jumps when trying to do it. Same goes for the end point between 7th and 3rd last column.
Video: [20200426_222937.gif](https://user-images.githubusercontent.com/5899155/80321364-7280f980-8814-11ea-8427-17b572894423.gif)

**Expected behavior**
Selection point shouldn't jump when trying to precisely place it.

**Additional information**

* Termux application version: 0.94
* Android OS version: 9
* Device model: Huawei P20 Pro

**Comment by trygveaa** [comment]
This is fixed in PR #1477.

Well, it still jumps, because it has to in order to change the direction of the handles, but it jumps in different positions when dragging from left to right vs right to left, so that makes it possible to select all positions.
