### ISSUE TITLE
First character of string in Text Input View can only be ASCII

### ISSUE THREAD

**Issue by Mamporrero** [termux/termux-app#1528]
**Problem description**

If the first character input into Text Input View is an accented letter or other non-ASCII character, it is not transferred to Termux correctly

**Steps to reproduce**

Type a Linux command, for instance echo (followed by a space). Swipe left on the extra keys bar to reveal the text input view bar. Using a multilingual keyboard (I use Gboard), input an  accented character, followed by any other characters. Press Return to pass the string to Termux. The first character will not be transferred. In the case of at least one non-ASCII character, the Spanish inverted exclamation mark, something further happens: the input string is placed at the beginning of the Linux command instead of the end -- so an attempt to say "echo ¡Hola!" ends up as "Hola!echo ".

**Expected behavior**

I would expect the first input character to be passed normally to Termux.

**Additional information**

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.14-15260192 termux/termux-packages#1 SMP PREEMPT Thu Jan 24 11:55:50 KST 2019 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T580
```

**Comment by xeffyr** [comment]
> something further happens: the input string is placed at the beginning of the Linux command instead of the end -- so an attempt to say "echo ¡Hola!" ends up as "Hola!echo ".

Can't reproduce the issue (Samsung Galaxy S7, Android 8.0):
![Screenshot_20200427-230533_Termux](https://user-images.githubusercontent.com/25881154/80415823-c1459680-88db-11ea-92d6-1117487178f7.jpg)

**Comment by Mamporrero** [comment]
Ah. I wonder if it has something to do with Android version? I can reproduce it on my Galaxy M30s phone running android 9 (I reported it from a tablet running 8.1).

**Comment by Mamporrero** [comment]
OK, things are a little clearer. The behaviour described occurs when the shell in use is bash, whereas with sh (= dash) one sees the expected behaviour. I assume that xeffyr is using  sh -- hence the plain "$" prompt. Here's a screenshot.
![Screenshot_20200428-223744_Termux](https://user-images.githubusercontent.com/33513872/80535569-5068b200-89a1-11ea-9a89-568011a1ccba.jpg)

**Comment by xeffyr** [comment]
> I assume that xeffyr is using sh -- hence the plain "$" prompt.

1. I use `bash`. Only.
2. My Termux installation is sane, unlike yours.

Here is why Bash has `$` prompt in Termux: https://github.com/termux/termux-packages/blob/master/packages/bash/etc-bash.bashrc#L7

**Comment by xeffyr** [comment]
![Screenshot_20200429-001527_Termux](https://user-images.githubusercontent.com/25881154/80538544-9a0bc980-89ae-11ea-8a28-af4365e2b3d9.jpg)

**Comment by Mamporrero** [comment]
Right. Problem located and eliminated. Thanks.
