### ISSUE TITLE
have supervisor on termux

### ISSUE THREAD

**Issue by Cristy86** [termux/termux-app#1529]
**Feature description**

I am using Termux to host a discord bot and I really want to have a process manager like supervisor. But the thing is that supervisor won't work because of this error:
``module os has no attribute link`` (here's a [screenshot](https://i.imgur.com/zh7Q3Nj.png))
I would really appreciate any advice!

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by Grimler91** [comment]
Have a look at termux-services: https://wiki.termux.com/wiki/Termux-services

You can probably patch the python code to use symlink instead of hardlinks as well

**Comment by Cristy86** [comment]
I will take a look. Thanks!
