### ISSUE TITLE
Terminal emulation: blinking cursor?

### ISSUE THREAD

**Issue by Mihara** [termux/termux-app#153]
I'm not sure it's a bug, because the last time I dug into the intricacies of Unix terminal definitions was really long ago, and I ran away screaming. But it kind of presents a practical problem:

The cursor does not natively blink, and Emacs can't _make_ it blink.

Also, the result of running `tput cnorm` and `tput cvvis` commands is identical, a rectangle cursor, when the first one is supposed to produce an underscore cursor, so something is very probably wrong.

This is kind of a problem in Emacs, because when background is used for highlighting _(i.e. on TODO items in org-mode)_ the block cursor can become completely invisible while over the highlighted text, and blinking cursor becomes a necessity.

**Comment by Quasic** [comment]
I don't think the cursor ANSI escape sequences for blinking are supported, either, but block, | and _ are:
printf '\e[2 q'
printf '\e[4 q'
printf '\e[6 q'

**Comment by rendiix** [comment]
Any progress for this issue?

**Comment by dediiskandar** [comment]
ada yang tahu cara membiat cursor berkedip di termux ?

**Comment by dediiskandar** [comment]
ada yang tahu cara membuat cursor berkedip di termux

**Comment by Freed-Wu** [comment]
So far, blink style is not supported by termux.
```shell
pip install rich
python -m rich|grep blink
```
the word blink will be still not blinking.

**Comment by trygveaa** [comment]
@Freed-Wu: This issue is about having a blinking cursor. That is not the same thing as blinking text.

**Comment by Freed-Wu** [comment]
sorry for my error :(
I'll open a new issue to ask whether it can support blinking text.

**Comment by fanlei** [comment]
Hope the terminal emulation can support the blinking cursor. Without it, there are two practical problems I met when using termux:
1. When switching between two windows using a keyboard shortcut like Alt + Tab, the blinking cursor can indicate which window is active immediately. Without it, I many times have to type something to make sure I am on the correct window. Annoying.
2. Block shape cursor in Vim makes the text under the cursor invisible. Just like @Mihara  mentioned in Emacs.

**Comment by Splendid-star** [comment]
It shows this but it doesn't show the password stuff

**Comment by agnostic-apollo** [comment]
>It shows this but it doesn't show the password stuff

It doesn't should what password "stuff"?
