### ISSUE TITLE
exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

### ISSUE THREAD

**Issue by yihanwu1024** [termux/termux-app#1533]
**Problem description**

If a reboot force stopped Termux (not by other methods), the next time Termux starts with this message in the terminal:
```
exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]
```
And this can only be fixed by uninstalling and reinstalling the app. Clearing the app data does NOT help.

**Steps to reproduce**

1. Launch Termux. Let the "Installing" finish.
2. Reboot the phone.

**Expected behavior**

Termux loads normally after the reboot, and previous work is not saved.

**Additional information**

* Termux application version: 0.94
* Android OS version: 10, 11 Developer Preview 3
* Device model: Google Pixel 2 XL (taimen)

**Comment by Grimler91** [comment]
So this happened in a fresh installation of termux? 
You mentioned "installing", you mean the installation of the bootstrap packages? Are you sure that installation finished before the reboot?

**Comment by xeffyr** [comment]
Seems like your ROM removes the executable bits on app data files... Can you try to open failsafe shell and do
```
ls -l /data/data/com.termux/files/usr/bin/login
```

If executable bits are really being removed, then issue can be solved by https://github.com/termux/termux-app/pull/1427.

**Comment by yihanwu1024** [comment]
> So this happened in a fresh installation of termux? 
> You mentioned "installing", you mean the installation of the bootstrap packages? Are you sure that installation finished before the reboot? 

Yes, fresh install, first launch, and then the "Installing" dialog. Not even a package installed.

**Comment by yihanwu1024** [comment]
> Seems like your ROM removes the executable bits on app data files... Can you try to open failsafe shell and do
> ```
> ls -l /data/data/com.termux/files/usr/bin/login
> ```
> 
> If executable bits are really being removed, then issue can be solved by https://github.com/termux/termux-app/pull/1427.

It is there, with the right permissions.
```
:/data/data/com.termux/files/usr/bin $ ls -l | grep login
-rwx------ 1 u0_a52 u0_a52     834 2020-04-05 09:23 login
```
So I guess this issue is not a duplicate?

**Comment by aan230999** [comment]
Nice

**Comment by Grimler91** [comment]
@yihanwu1024 Could you capture a logcat with adb when you try opening termux?

**Comment by xeffyr** [comment]
> It is there, with the right permissions.

Last remaining thing - SELinux. Full output of `adb logcat` should tell what is happening, hope avc denials logging is not disabled on your ROM.

**Comment by xeffyr** [comment]
Closing as related to https://github.com/termux/termux-app/issues/1072.
