### ISSUE TITLE
Can't install termux on nox emulator 6.6.0.5 android 7

### ISSUE THREAD

**Issue by kotenok2000** [termux/termux-app#1534]
**Problem description**

Can't install termux on nox emulator 6.6.0.5 android 7
**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by xeffyr** [comment]
Fails at bootstrapping stage ?

**Comment by kotenok2000** [comment]
Yes.It tells me to check network and try again. I can open termux.net/bootstrap ,
![Снимок экрана (39)](https://user-images.githubusercontent.com/8822292/80805185-0b6e9680-8bc0-11ea-871e-31751917cd72.png)

**Comment by xeffyr** [comment]
If emulator doesn't wrap the files into EXT4 file system image, then unfortunately nothing can be done here. Use a different emulator.
