### ISSUE TITLE
unused DT entry: type 0x1d arg 0xf8

### ISSUE THREAD

**Issue by leejie123** [termux/termux-app#1537]
![Screenshot_2020-05-03-22-53-17-776_com termux](https://user-images.githubusercontent.com/15863698/80917627-f564ff80-8d92-11ea-9c43-ed9a5c04b695.jpg)

Hello, i meet this  problem when i execute  ```termux-usb -l ```. needing  help..

I have tried solutions  in  other  issues but does  not work

**Comment by Grimler91** [comment]
Which solutions have you tried? 
What's your output of `termux-info`?

**Comment by leejie123** [comment]
> Which solutions have you tried?
> What's your output of `termux-info`?

**Comment by Grimler91** [comment]
You can't use the tsinghua repository on android 6. The packages in that repo are compiled for android 7 and newer, and that gives this type of warning and other problems. You need to remove $PREFIX, restart the app and reinstall your packages from the termux.net repository instead

**Comment by bhagwandassony1** [comment]
![Screenshot_20200804-213345](https://user-images.githubusercontent.com/69147279/89319285-6dcbad00-d66f-11ea-934a-3fafe4e98405.png)

**Comment by bhagwandassony1** [comment]
![Screenshot_20200804-215851](https://user-images.githubusercontent.com/69147279/89319428-9c498800-d66f-11ea-849f-817a9c7941a9.png)
