### ISSUE TITLE
User Android System open directory dialog to choose current working directory

### ISSUE THREAD

**Issue by stevenleeS0ht** [termux/termux-app#1538]
**Feature description**
`cd xxx` is not so convenient for user to choose current working directoy, call the open directory dialog in Android system would be a good idea.

Add a button on the side bar or above the keyboard would be a ideal strategy.

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by xeffyr** [comment]
> cd xxx is not so convenient

Why shell is still convenient in 2020 ?

**Comment by xeffyr** [comment]
Your request for replacing `cd` command is definitely wontfix as it just can't be implemented. Termux shell is free from Android framework/api and therefore certain its parts just cannot be replaced by graphical interface. And even if possible, that is not going to happen as introduces non-standard behaviour to command line tool.
