### ISSUE TITLE
Modifier Keys and SwiftKey arrow keys. 

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-app#154]
With the [Swiftkey](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey&hl=de) keyboard it is possible to enable an extra row with arrow keys. 

![capture](https://cloud.githubusercontent.com/assets/7983745/18311496/f2fbba90-7504-11e6-9551-14ffa78cf9ae.PNG)

Right now pressing Volume Down or enabling the modifier keys (CTRL, ALT) from the extra keys view does not trigger the corresponding Alt + Up, Ctrl + Right etc. Even pressing the keyboards own shift key doesn't produce a Shift + Up. 

Can this even be fixed by Termux or is the problem with Swiftkey?

**Comment by ilmaisin** [comment]
Can reproduce with MessagEase Keyboard.

With MessageEase, one can operate the arrow keys via swiping left and right on space bar and up and down on `i` and `s` respectively.

With the similar extra keyboard of JuiceSSH this works fine.

**Comment by Neo-Oli** [comment]
I think this issue can safely be closed. The extra keys row of the Termux app neatly sidestepped this issue years ago.
