### ISSUE TITLE
Run Deno in termux

### ISSUE THREAD

**Issue by JosiasAurel** [termux/termux-app#1541]
**Feature description**

Ability to run programs like deno

I know y'all do a good job with this wonderful app I use everyday but I just have a request. Is it possible to give ability to run Deno (NodeJS successor ) inside termux?. If no, what about if I install a Linux distro (say Ubuntu) and try installing Deno, will it work ?

Best regards 🤸

**Comment by xeffyr** [comment]
> If no, what about if I install a Linux distro (say Ubuntu) and try installing Deno, will it work ?

Should work as soon as it is compatible with distro and your CPU arch.

**Comment by vkuehn** [comment]
NodeJs works for me
