### ISSUE TITLE
Writing to sdcard

### ISSUE THREAD

**Issue by KoleckOLP** [termux/termux-app#1543]
**Feature description**
I wish to be able to write to my sdcard.

I had this issue on Andorid 9 and I also have it on Android 10
Xiaomi Mi A3, the SDcard is mounted as portable media. 

My sdcad is mounted at /storage/3665-13FE/ by default
and when I try to write to it I get 
![image](https://user-images.githubusercontent.com/22729896/81213755-26357680-8fd7-11ea-85d0-8e395f992d5a.png)

I with to access more than a empty folder on the SD card
![image](https://user-images.githubusercontent.com/22729896/81213911-63016d80-8fd7-11ea-8f0c-e45c043104fc.png)

**Reference implementation**
Other apps have this select root of the sdcard before you can use it and than they can read and write to it somewhat fine, I don't know why are there somany issues with sdcards

**Does another app/terminal emulator have this feature?
Provide links to more background information.**
Apps like ES File Explorer can acess read ani write to it, Camera and many more apps. Why can't termux?

**Comment by trygveaa** [comment]
You need to run `termux-setup-storage`. See https://wiki.termux.com/wiki/Termux-setup-storage

**Comment by xeffyr** [comment]
> I with to access more than a empty folder on the SD card

This is private directory, i.e.
```
/storage/3665-13FE/Android/data/com.termux/files
```
and it does not contain files by default.

If you need to move file on external storage, put file here and then move to appropriate place with a normal file manager.

More info about how Termux handles storage you can get at https://wiki.termux.com/wiki/Internal_and_external_storage.
