### ISSUE TITLE
tsu package not getting installed...

### ISSUE THREAD

**Issue by starry69** [termux/termux-app#1546]
**Problem description**

![Screenshot_20200508-113045](https://user-images.githubusercontent.com/58552395/81375579-73246480-911f-11ea-879c-8fbb64cb17fc.jpg)

Tsudo package not getting installed properly as this screenshot tells itself.
**Steps to reproduce**

run these commands:
```pkg install tsudo```
And then 
```tsudo```
It'll say tsu package not installed even if you've install it many times
**Expected behavior**

it shouldn't have happened as tsu is installed already
**Additional information**
* Termux application version: Version 0.94
* Android OS version: android 10
* Device Asus zenfone max pro m1

**Comment by Grimler91** [comment]
tsudo has been renamed to sudo (and command-not-found has not been updated)

**Comment by starry69** [comment]
Thank you.

**Comment by Grimler91** [comment]
Thanks for reporting, I'll update command-not-found

**Comment by starry69** [comment]
Sure 👍

**Comment by klash098** [comment]
чё делать если sudo тоже не работает?
