### ISSUE TITLE
Option to increase the font size of Terminal on Samsung Dex

### ISSUE THREAD

**Issue by VenkyDevHub** [termux/termux-app#1547]
Hi Termux,

First of all, thanks a lot for creating such as wonderful app. I'm using my Samsung Galaxy S10e phone to connect to laptop to run Samsung Dex where I wanna run, use and develop my projects using Termux. But, there is one small limitation which has been bothering me is that I'm unable to increase the font size of the terminal as seen in the attached screenshot.
Is it possible already to increase the font size somehow on Samsung Dex? On Phone, I know that we can pinch to zoom in and out, but would you please add such feature for Samsung Dex and similar platforms where this app can be used at its fullest.
![image](https://user-images.githubusercontent.com/26375947/81405836-0636bc00-916b-11ea-8bf2-e81a2bc0bdd7.png)

Thanks and Regards,
Venky.

**Comment by trygveaa** [comment]
I assume you have a hardware keyboard when using Samsung Dex? If so, you can use `ctrl`+`alt`+`+`/`-`. See https://wiki.termux.com/wiki/Hardware_Keyboard

**Comment by VenkyDevHub** [comment]
Hey @trygveaa,

That's great!! It works. Sorry for bothering with a new issue. Thanks very much for the quick support!
