### ISSUE TITLE
please enable WIFIlock feature and permission to allow Internet radio players for Linux to recieve WIFI signal with 1 or 2 Bars strenghtDear specialists,

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-app#1548]

**Comment by JanuszChmiel** [comment]
This Android permission allow users to have his screen turned off but WIFI chip is styll working with high performance. This permission is very important if user play live streams and WIFI signal strenght is 1 2 bars. And if The phone screen have been turned off. Termux support Ignorebatteryoptimisations permission Unfortunately, simply adding wifilock permission to androidmanifest.xml is not enough. Somebody familiar with Java language would had to add The right code to The right place.
I believe, that you will allov ArchLinux users and not only them to listen live streams on their balcones, where WIFI signal strenght can balance between 1 or 2 bars.

**Comment by xeffyr** [comment]
Turning on wakelock enables wifi lock too. However that do not affect wifi powersaving at hardware level, it just not possible to do that (only through recompiling kernel).

https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/TermuxService.java#L114-L115

Workaround variants:
* Keep screen on.
* Continuously send packets to some host. I use `ping -i 0.3 -s 16 192.168.1.1` to keep wifi at best performance when screen if off.

**Comment by JanuszChmiel** [comment]
Oh, thank you very much for yours useful tip. Yes, if screen is turned on,
really, live stream do not stop to play. But when I turn The screen of when
WIFI signal strenght balances around 1 or 2 bars, it automatically stop to
play. If WIFI bars is more than 2, even when WIFI chip performance is
automatically degradated when The phone is turned off live stream play. So
by other words, Android build in Wifilock is toy for children who believe,
that miracles happens. But no.
Yes. I have The same experience when I have used PPCJVM and I have made
simple radio player for Android. Even when I have acquired Wifilock and
Wafelock Wifi chip performance really degradates when phone screen is turned
off.
The only question is, if ISP server administrator will not unconnect Me from
The Internet when I will use The command
ping -i 0.3 -s 16 192.168.1.1 
If The server admin will not think, that I want to hack some network. Is
this IP address secure?
I Am using modern WIFI router from O2 company. But I do not want to make
Server Admins from O2 engry on Me, that I Am playing with The network.

**Comment by xeffyr** [comment]
> If The server admin will not think, that I want to hack some network. Is
this IP address secure?

No matter whether IP is secure or not. The idea is just to send packets so wifi module will not go into idle state with low performance. You can use any valid IP.
