### ISSUE TITLE
App problem

### ISSUE THREAD

**Issue by BruhNoway** [termux/termux-app#1549]
**Problem description**
![Screenshot_20200508_231253](https://user-images.githubusercontent.com/65033281/81425382-b1eb0680-9181-11ea-98c4-0451cc6a4698.png)

**Expected behavior**
My Termux for some reason legacy? can someone tell me what must to do?

**Additional information**

* Termux application version: 0.83
* Android OS version: 2.1
* Device model: vivo y35

**Comment by BruhNoway** [comment]
pls someone help me what must i do

**Comment by xeffyr** [comment]
We do not support Android OS versions lower than 7.0.
