### ISSUE TITLE
Problem with 'su' from termux-tools

### ISSUE THREAD

**Issue by voidzero** [termux/termux-app#155]
The following output comes up when I run su:

<pre>@localhost ~ % su
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
page record for 0x7f972b0090 was not found (block_size=64)
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
page record for 0x7fa15e8090 was not found (block_size=64)
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
page record for 0x7fb3c38090 was not found (block_size=64)
Failed to setup keys using zkbd.
zsh compinit: insecure directories and files, run compaudit for list.
Ignore insecure directories and files and continue [y] or abort compinit [n]? ycompinit:446: scalar parameter REPLY created globally in function compinit
#
@localhost / #</pre>

I'm using zsh as my shell. 'warncreateglobal' is enabled by default, so that warning about REPLY comes from there and is not a termux bug, but the libs stuff probably is.

**Comment by fornwall** [comment]
Could you paste the output of running `sh -x su`?

**Comment by voidzero** [comment]
<pre>@localhost ~ % which su
su: aliased to nocorrect su
@localhost ~ % unalias su
@localhost ~ % which su
/data/data/com.termux/files/usr/bin/su
@localhost ~ % sh -x su
sh: 0: Can't open su
@localhost ~ % sh -x $(which su)
+ ROOT_SHELL=/data/data/com.termux/files/usr/bin/bash
+ test -x /data/data/com.termux/files/home/.termux/shell
+ readlink -f /data/data/com.termux/files/home/.termux/shell
+ ROOT_SHELL=/data/data/com.termux/files/usr/bin/zsh
+ [ -x /system/xbin/su ]
+ PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/su/bin:/su/xbin:/system/bin:/system/xbin exec /system/xbin/su --preserve-environment -c LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib /data/data/com.termux/files/usr/bin/zsh
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
page record for 0x7fb6988090 was not found (block_size=64)
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
page record for 0x7f95b18090 was not found (block_size=64)
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
page record for 0x7f94276090 was not found (block_size=64)
Failed to setup keys using zkbd.
zsh compinit: insecure directories and files, run compaudit for list.
Ignore insecure directories and files and continue [y] or abort compinit [n]? ^C#                                             localhost#</pre>

**Comment by voidzero** [comment]
Okay, this bug didn't get attention and for a while I was able to run su without problems.
however, as of recently, it fails again and there is no way at all for me to get a root shell.. so please help.

```
u0_a159@localhost ~ % which su
/data/data/com.termux/files/usr/bin/su
u0_a159@localhost ~ % su
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit
page record for 0x7f943c6010 was not found (block_size=64)
u0_a159@localhost ~ % sh -x $(which su)
+ unset LD_LIBRARY_PATH
+ [ -x /system/xbin/su ]
+ PATH=/sbin/su:/su/bin:/su/xbin:/system/bin:/system/xbin exec /system/xbin/su
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit
page record for 0x7f81e16010 was not found (block_size=64)
u0_a159@localhost ~ %  
```

**Comment by Grimler91** [comment]
There's been some similar issues in past. unset LD_PRELOAD before running su and the particular error regarding libtermux-exec should go away.

**Comment by kgaughan** [comment]
Just got this same error regarding libtermux-exec.so when upgrading Python 3. Unsetting LD_PRELOAD did the trick, but why would a 32-bit SO be present in the first place?

**Comment by Grimler91** [comment]
@kgaughan some devices, for example (some?) chromebooks, are 64 bit but install 32 bit android apps. pip and other package managers look at the architecture and see 64 bit though and uses that arch.

See for example https://github.com/termux/termux-packages/issues/2281 and https://github.com/termux/termux-app/issues/644.

Might be the same in your case.

**Comment by luismene** [comment]
> <pre>@localhost ~ % which su
> su: aliased to nocorrect su
> @localhost ~ % unalias su
> @localhost ~ % which su
> /data/data/com.termux/files/usr/bin/su
> @localhost ~ % sh -x su
> sh: 0: Can't open su
> @localhost ~ % sh -x $(which su)
> + ROOT_SHELL=/data/data/com.termux/files/usr/bin/bash
> + test -x /data/data/com.termux/files/home/.termux/shell
> + readlink -f /data/data/com.termux/files/home/.termux/shell
> + ROOT_SHELL=/data/data/com.termux/files/usr/bin/zsh
> + [ -x /system/xbin/su ]
> + PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/su/bin:/su/xbin:/system/bin:/system/xbin exec /system/xbin/su --preserve-environment -c LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib /data/data/com.termux/files/usr/bin/zsh
> CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
> page record for 0x7fb6988090 was not found (block_size=64)
> CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
> page record for 0x7f95b18090 was not found (block_size=64)
> CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
> page record for 0x7f94276090 was not found (block_size=64)
> Failed to setup keys using zkbd.
> zsh compinit: insecure directories and files, run compaudit for list.
> Ignore insecure directories and files and continue [y] or abort compinit [n]? ^C#                                             localhost#</pre>
>

**Comment by luismene** [comment]
> > <pre>@localhost ~ % which su
> > su: aliased to nocorrect su
> > @localhost ~ % unalias su
> > @localhost ~ % which su
> > /data/data/com.termux/files/usr/bin/su
> > @localhost ~ % sh -x su
> > sh: 0: Can't open su
> > @localhost ~ % sh -x $(which su)
> > + ROOT_SHELL=/data/data/com.termux/files/usr/bin/bash
> > + test -x /data/data/com.termux/files/home/.termux/shell
> > + readlink -f /data/data/com.termux/files/home/.termux/shell
> > + ROOT_SHELL=/data/data/com.termux/files/usr/bin/zsh
> > + [ -x /system/xbin/su ]
> > + PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/su/bin:/su/xbin:/system/bin:/system/xbin exec /system/xbin/su --preserve-environment -c LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib /data/data/com.termux/files/usr/bin/zsh
> > CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
> > page record for 0x7fb6988090 was not found (block_size=64)
> > CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
> > page record for 0x7f95b18090 was not found (block_size=64)
> > CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libpcre.so" is 32-bit instead of 64-bit
> > page record for 0x7f94276090 was not found (block_size=64)
> > Failed to setup keys using zkbd.
> > zsh compinit: insecure directories and files, run compaudit for list.
> > Ignore insecure directories and files and continue [y] or abort compinit [n]? ^C#                                             localhost#</pre>
> > 
> 
>
