### ISSUE TITLE
Clang unable to make temporary file error

### ISSUE THREAD

**Issue by nihinivi** [termux/termux-app#1550]
So i have updated my termux recently before it was working perfectly but after update when i try to compile a file i get this error
`clang-9: error: unable to make temporary file: No such file or directory`
command used
`g++ filename.cpp`
Also used this command in tsu mode

**Comment by Grimler91** [comment]
You should not use this command in tsu mode, there is no reason for it. 

Could be that you have messed up the directory permissions due to running it as root. What does `ls -l $PREFIX/..` show?

**Comment by nihinivi** [comment]
@Grimler91 Thanks for looking into the problem
$ ls -l $PREFIX/ ..
..:
total 8
drwx------  2 u0_a76 u0_a76 4096 May  9 15:24 home
drwx------ 10 u0_a76 u0_a76 4096 May  9 15:24 usr

/data/data/com.termux/files/usr/:
total 36
drwx------  3 u0_a76 u0_a76 8192 May  9 15:26 bin
drwx------  6 u0_a76 u0_a76 4096 May  9 15:23 etc
drwx------ 52 u0_a76 u0_a76 4096 May  9 15:26 include
drwx------  9 u0_a76 u0_a76 4096 May  9 15:26 lib
drwx------  5 u0_a76 u0_a76 4096 May  9 15:26 libexec
drwx------ 16 u0_a76 u0_a76 4096 May  9 15:26 share
drwx------  2 u0_a76 u0_a76 4096 May  9 15:26 tmp
drwx------  7 u0_a76 u0_a76 4096 May  9 15:24 var

this is the output

**Comment by Grimler91** [comment]
So the problem is not with the folder permissions. 

What program are you compiling? 
What are you running to compiling it?

**Comment by nihinivi** [comment]
@Grimler91 A simple hello world program below
`#include <iostream>

int main(){
    std::cout << "Hello World" << endl;
    return 0;`
and im running 
`g++ name.cpp -o hello-world`

**Comment by xeffyr** [comment]
> So the problem is not with the folder permissions.

SELinux maybe. Try to remove & create tmpdir (as **non-root**):
```
rm -rf $PREFIX/tmp
mkdir $PREFIX/tmp
```

Also check if variable `TMPDIR` points to right place, it should be:
```
/data/data/com.termux/files/usr/tmp
```

**Comment by nihinivi** [comment]
@Grimler91 Thanks the $TMPDIR was at $HOME/.suroot/tmp now i changed it to $PREFIX/tmp by `set TMPDIR=$PREFIX/tmp`
and its working fine now
