### ISSUE TITLE
Ngrok  permission denied problem

### ISSUE THREAD

**Issue by gurusanthi** [termux/termux-app#1551]
$ chmod +x termux-ngrok.sh
$ ./termux-ngrok.sh
bash: ./termux-ngrok.sh: Permission denied

**Comment by kcubeterm** [comment]
Try changing after changing the name
```
mv termux-ngrok.sh ngrok
```

./ngrok

**Comment by xeffyr** [comment]
Just don't exec it on sdcard.

**Comment by Egolka** [comment]
./ngrok authtoken (my token)
bash: ./ngrok: Permission denied
I don't know what to do.

**Comment by kcubeterm** [comment]
First of all make sure ngrok executable is not in internel storage or external storage,

Keep it in home directory ,and then execute it, if still get same.
Give permission to it.

```
chmod +x ngrok
./ngrok 

```

If still get same error, install ngrok again by following command

```
pip install pyngrok
```
Now just run your ngrok

```
ngrok authtoken kdkdvzkdnxkdmxlsncismxkd

```

**Comment by Egolka** [comment]
Now bash writes: ./ngrok: text file busy

**Comment by Egolka** [comment]
I now wrote ls there it is shown in green ngrok. Does that mean it works?

**Comment by Egolka** [comment]
and also such a problem if I write ./ngrok http 4040 then the following error pops up bash: ./ngrok: There is no such file or directory

**Comment by kcubeterm** [comment]
Lol, look like I have to teach you,

execute following command in your terminal

```
pkg install openssh
ssh lucky/git@nyc1.tmate.io
```

after join, just write something,

**Comment by Egolka** [comment]
what to teach?

**Comment by Egolka** [comment]
what to teach?

**Comment by Egolka** [comment]
so how do I solve the problem bash: ./ngrok: There is no such file or directory

**Comment by Grimler91** [comment]
@Egolka That error means that the executable is compiled against another libc than android's. You cannot fix it (except if you recompile the program against android's libc, but that will be hard since ngrok isn't open-source).

**Comment by kcubeterm** [comment]
ngrok compiled binaries works in termux, ,

**Comment by Egolka** [comment]
so i can't send my phishing site to anyone
