### ISSUE TITLE
Termux Launcher Pro

### ISSUE THREAD

**Issue by x2k13** [termux/termux-app#1552]
Looks like someone is making use of Termux' name on a completely unrelated, ad-loaden and useless launcher app, which also isn't free. 

[Termux Launcher Pro, Play Store](https://play.google.com/store/apps/details?id=com.ss.a2is.termux.pro) 

Just wanted to let you know, sorry when I posted it here, but I had no idea where else I could get your attention as fast as here. 😉

**Comment by xeffyr** [comment]
Usage of `Termux` name in third-party projects does not violate anything. Termux is not a trademark, so Google won't bother to remove apps using that word as part of name of another application.
