### ISSUE TITLE
SSH into my Termux through Hotspot without Internet

### ISSUE THREAD

**Issue by marhf** [termux/termux-app#1553]
Hey,

I am trying to figure out a way to SSH into my Termux with my phone's Hotspot without Internet Connection onto a **Secure Shell App, V 0.31** (_Chrome Browser Extension acts as a SSH Client_)

So can I do that with my SSH Client connected to my Hotspot..?

And also can I SSH into a client machine running Linux itself without Internet Connection...?

BTW Huge Respects for developing such a great app...!!!

**Comment by disklosr** [comment]
Hello,

Of course it's possible :) Did you take a look at [this](https://wiki.termux.com/wiki/Remote_Access) ?

Here's a short version:

1. Install openssh using `pkg install openssh`
2. Set a new password for your user (use `whoami` command to get current user name)
3. Start ssh server in termux using `sshd` command. The server listens to port 8022
3. Use an ssh client connected to the same home network as your phone to connect: `ssh -p 8022 my_user@ip_address_of_your_phone`, it will then prompt you to log in via the password you just set.
