### ISSUE TITLE
Termux doesn't respect "mobile data only app" policy

### ISSUE THREAD

**Issue by disklosr** [termux/termux-app#1556]
**Problem description**
At least in recent Samsung devices, there's this option where you can restrict an app to only use internet from mobile data even if wifi is connected. Termux doesn't respect this choice and always prefers wifi over mobile data when available, regardless of the "data only app" policy. I tried with Firefox and it does respect it. [Here's a video](https://www.youtube.com/watch?v=PSEAHISLPxU) of how the policy can be set.

**Steps to reproduce**
1. Add termux to "data only apps" list via mobile data settings menu (see previous video for how to do this)
2. Make sure phone is connected to both wifi and mobile data
3. Open a new termux session and check what network is it connected to (by getting your public address for instance)
4. Termux is connected through wifi even if policy was set to mobile data only

**Expected behavior**
Termux should be connected to internet through mobile data

**Additional information**
Restarting the phone doesn't fix the issue

* Termux application version: latest version in Play store as of now (termux-info doesn't print version)
* Android OS version: 10
* Device model: Samsung A40 (SM-A405FN)

**Comment by xeffyr** [comment]
Traffic from command line utilities will always go through "default" connection. They are not running in Android framework (API) and cannot be controlled from this side (only by explicit firewalling applied by OS).
