### ISSUE TITLE
exec("/data/data/com.termux/files/usr/bin/login"): Permission denied  [Process completed (code 1) - press Enter]

### ISSUE THREAD

**Issue by chekamarue** [termux/termux-app#1557]
**Problem description**

I keep getting this error each Time I open termux

exec("/data/data/com.termux/files/usr/bin/bash"): Permission denied

[Process completed (code 1) - press Enter]

**Steps to reproduce**

installing termux as a system app! 
**note**
 uninstall termux and installing it as user app didn't help 
installed from play store or fdroid didn't help 
setting permission 777 to login file didn't help 

**Expected behavior**

receiving the bellow error every time I launch termux 

exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

**Additional information**

* Termux application version: latest 
* Android OS version: 10
* Device model: sumsung A50

**Comment by Grimler91** [comment]
Probably same issue as https://github.com/termux/termux-app/issues/1557. A logcat would be useful so that we can understand the issue better

**Comment by chekamarue** [comment]
> Probably same issue as #1557. A logcat would be useful so that we can understand the issue better

sorry I don't have access to a pc for the time being :(

is there anything else I can provide to fix the issue?

**Comment by Grimler91** [comment]
Sorry, pasted the wrong link, I meant this issue: https://github.com/termux/termux-app/issues/1533
