### ISSUE TITLE
will there ever be a windows version of termux?

### ISSUE THREAD

**Issue by Ahmed-Mokhles** [termux/termux-app#1558]
hello
im not sure if this has been asked (or answered) before, so i thought i'd post a new issue.

there seems to be absolutely no clue of a windows version of termux, and any google searches only bring up articles on using bluestacks (or some other android emulator).

but emulators use up a lot of resources, and i was thinking that with the availability of a physical keyboard and a decent screen, there should be no reason not to have termux for windows (or pc in general - linux, mac, etc.)

are the devs considering providing a pc version of termux? or is that not going to happen?

thanks in advance.

**Comment by xeffyr** [comment]
No, we will never work on Windows version. We do not have any people who will work on it and porting utilities to Windows is useless anyway. For Windows you have some choices which would be definitely better than Termux in any way:

* Cygwin (https://www.cygwin.com/)

  Cygwin is a distribution of popular GNU and other Open Source tools running on Microsoft Windows.

* Windows Subsystem for Linux (only for Windows 10)

  Native compatibility layer for running Linux executables on Windows.

* VirtualBox (https://www.virtualbox.org/)

  Setup a virtual machine and install the Linux distribution you want.

On Linux, there is no valid reason to have Termux. If you really need it on Linux, install Anbox and in  it Termux.

I hope you understand that main purpose of Termux is to bring utilities from GNU/Linux to Android OS and therefore it is ultimately tuned only for such variant of the OS.

**Comment by RalfWerner** [comment]
Addition: my favorite is https://mobaxterm.mobatek.net/ (also contains WSL and nedit ...)
