### ISSUE TITLE
The Wiki front page should link to settings

### ISSUE THREAD

**Issue by trygveaa** [termux/termux-app#1560]
Currently, no pages in the wiki link to the [settings page](https://wiki.termux.com/wiki/Terminal_Settings), so you have to search for it to find it.

I think it should be linked to from the front page, in the introduction section together with "User Interface", "Software" and "Hardware".

I'm opening an issue here because the front page is protected, so I can't edit it.

**Comment by xeffyr** [comment]
Done.
