### ISSUE TITLE
Command Line

### ISSUE THREAD

**Issue by caltrop-3** [termux/termux-app#1567]
**Problem description**
bash history gets messed up & command line wraps to same line

**Steps to reproduce**
make a multi-line $PS1

**Expected behavior**
wrap to next line & ungarbled bash history

**Additional information**

* Termux application version: 0.94
* Android OS version: 9
* Device model: Moto G7

**Comment by xeffyr** [comment]
> command line wraps to same line

Expected behaviour if you didn't wrapped colors between brackets: `\[` and `\]`. Otherwise it will treat colors as characters and won't be able to calculate prompt width properly.

https://stackoverflow.com/questions/342093/ps1-line-wrapping-with-colours-problem and also in bash manpage.

**Comment by caltrop-3** [comment]
$ ls $FILES/usr/include *curs*.h

lists entire directory not wildcard specification

part of the command line / $PS1 issue

**Comment by caltrop-3** [comment]
command line still getting messed up

**Comment by xeffyr** [comment]
> $ ls $FILES/usr/include curs.h
lists entire directory not wildcard specification

I don't see any wildcard here. Your command will list directory `$FILES/usr/include` and `curs.h` in PWD in case if it exists.

Only you here have "messed up" command line.
