### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by caltrop-3** [termux/termux-app#1568]
**Feature description**
I want to be able to do simple 2D graphics from Termux, but 3D would be nicer.

like old DOS TurboC graphics.h

I have seen people talk about graphics.h, OpenGL, X11, & other stuff.

I'm totally baffled...

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Graphical_Environment

**Comment by xeffyr** [comment]
> like old DOS TurboC graphics.h

1. Termux is not DOS. It is Android OS (Linux).
2. Termux does not have native graphics. You'll need an X server or VNC.
