### ISSUE TITLE
colors.properties documentation

### ISSUE THREAD

**Issue by caltrop-3** [termux/termux-app#1569]
**Feature description**
what color number does what

color0=micro's backround
color??=whatever

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by caltrop-3** [comment]
~/.termux/colors.properties changes the escape sequence colors like those used in $PS1 & the 'echo' command

**Comment by xeffyr** [comment]
They are standard xterm color palette. Nothing Termux-specific and documentation for xterm can be found on the internet.
https://github.com/termux/termux-app/blob/master/terminal-emulator/src/main/java/com/termux/terminal/TerminalColorScheme.java#L14
