### ISSUE TITLE
ls issue

### ISSUE THREAD

**Issue by caltrop-3** [termux/termux-app#1570]
**Problem description**
echo $FILES
/data/data/com.termux/files

$ ls $FILES/usr/include *curs*.h

lists entire directory not wildcard specification

cd to the directory and wildcards work as expected

**Steps to reproduce**
always occurs

**Expected behavior**
wildcard that works

**Additional information**

* Termux application version: latest
* Android OS version: 9
* Device model: Moto G7

**Comment by Grimler91** [comment]
You haven't code-formatted your example. What did you mean to write? `ls $FILES/usr/include *curs*.h`? 

That will show you all files in `$FILES/usr/include` and files matching `*curs*.h`. Maybe you meant `ls $FILES/usr/include/*curs*.h`.

Closing since I can't see a termux issue here.
