### ISSUE TITLE
Android Movement Keys NOP

### ISSUE THREAD

**Issue by caltrop-3** [termux/termux-app#1571]
**Problem description**
Android movement keys noon operational

**Steps to reproduce**
always

**Expected behavior**
operational movement keys

**Additional information**
![Screenshot_20200518-190732](https://user-images.githubusercontent.com/31071746/82267783-56680800-993b-11ea-91fb-8350b52580bc.png)

* Termux application version: lastest
* Android OS version: 9
* Device model: Moto G7

**Comment by xeffyr** [comment]
Yes, they are NOP when text input view is active.
