### ISSUE TITLE
Missing 'man' Pages

### ISSUE THREAD

**Issue by caltrop-3** [termux/termux-app#1572]
**Problem description**
after installing 'man'  I find some commands like 'df' are missing

the number of missing 'man' pages is unknown

**Steps to reproduce**
always

**Expected behavior**
basic 'man' pages being available

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by xeffyr** [comment]
> I find some commands like 'df' are missing

In Termux, `df` is a wrapper around `/system/bin/df`. We do not provide manpages for system binaries for 2 reasons:
* System programs are ROM-specific.
* Android OS simply does not have manpages for them and we can't pick ones from the original as it may not be valid for binary in /system/bin.

**Comment by xeffyr** [comment]
@caltrop-3 Before submitting a bug report, please try to understand whether this is a real issue and not the *intended behaviour*.
