### ISSUE TITLE
ERROR: ld.so: object '/lib/aarch64-linux-gnu/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored

### ISSUE THREAD

**Issue by jakubix30** [termux/termux-app#1576]
I have problem with "ERROR: ld.so: object '/lib/aarch64-linux-gnu/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored" I tried install ligbcc but when i install i have "E : Unable to Locate Package" and i can't install ligbcc i don't now what i can do

**Comment by xeffyr** [comment]
Any reason to have that library in preload ?

**Comment by dhineshromeo** [comment]
I also had this error

**Comment by BotGamer2813** [comment]
Alguna ayuda para solucionar esto muchas gracias.
ERROR: 1ld.so: object '/usr/lib/aarch64-linux-gnu/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/aarch64-linux-gnu/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
??????(kali??localhost)-[~]
????$

**Comment by xeffyr** [comment]
@BotGamer2813 Just edit your proot (Kali?) startup script and remove `LD_PRELOAD` assignment.

It seems that someone found `LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgcc_s.so.1` without understanding the context and add it in his scripts. `LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgcc_s.so.1` will work only in AArch64 (arm64) distributions. In any other you get an error: `LD_PRELOAD cannot be preloaded`.

*Read the scripts you are getting from the Internet, as sometimes they are doing literally weird stuff.*
