### ISSUE TITLE
Fatal Error : UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ashishkumawat** [termux/termux-app#1578]
I am getting this error I try run app on my device Mi A2

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.termux-ZZO7KTCo1qu9TXJipBH3pg==/base.apk", zip file "/data/app/com.termux-ZZO7KTCo1qu9TXJipBH3pg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.termux-ZZO7KTCo1qu9TXJipBH3pg==/lib/arm64, /system/lib64]]] couldn't find "libtermux-bootstrap.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.termux.app.TermuxInstaller.loadZipBytes(TermuxInstaller.java:169)
        at com.termux.app.TermuxInstaller$1.run(TermuxInstaller.java:82)`

**Comment by Grimler91** [comment]
From where did you get the app?

**Comment by ashishkumawat** [comment]
I cloned whole project from github on my machine and tried to run.

**Comment by Grimler91** [comment]
> I cloned whole project from github on my machine and tried to run.

Maybe I am out-of-the-loop, but how can you "run" an android app on a computer ("machine")?

**Comment by xeffyr** [comment]
> "/data/app/com.termux-ZZO7KTCo1qu9TXJipBH3pg==/base.apk", zip file "/data/app/com.termux-ZZO7KTCo1qu9TXJipBH3pg==/split_config.xxhdpi.apk"]

I'm in doubt that apk is from source. Splitapk configuration is produced by Google Play only.

Suck APKs **cannot be backed-up** as they lose bootstraps and other architecture-dependent things.

**Comment by xeffyr** [comment]
If apk is built from source, make sure you have used these command for compilation:
```
./gradlew assembleDebug
```
SDK and NDK must be up-to-date.
