### ISSUE TITLE
Ability To Run Multiple Commands Inside Linux Environment

### ISSUE THREAD

**Issue by BeingDatta** [termux/termux-app#1579]
Hi there,

I want to achieve something like this ...... 
Firstly I want to install linux inside termux. 
Secondly I want to make custom commands widgets to run inside that linux environment. For eg .......

Say I can now run nethunter by passing **"su -c bootkali_bash"** but I also want to run **"apt update && apt upgrade"** along with the first command inside nethunter environment.

Is it possible in any way like proot or chroot method or anything else ?

Regards.

**Comment by Grimler91** [comment]
Just add the commands to your bootkali_bash script, execute commands instead of opening a bash shell

**Comment by BeingDatta** [comment]
can you be specific  how to add the commands to bootkali_bash script?

**Comment by BeingDatta** [comment]
@Grimler91 can you tell me how to add the commands in bootkali_bash script?

**Comment by xeffyr** [comment]
@BeingDatta You can add commands by editing script file with text editor, e.g. vim or nano.

**Comment by BeingDatta** [comment]
@xeffyr first learn my problem then answer i know how to write script the problem is i want to run multiple commands from android environment to nethunter environment. the first script is running but the second should run inside nethunter that is what not happening.

say su -c bootkali is running
but wifite -i wlan0 is not running

did you get that now ???

**Comment by xeffyr** [comment]
> i want to run multiple commands from android environment

Pass `"command1 && command2 && command3"` as argument to shell interpreter.

I don't know the content of `bootkali_bash` but if you are using chroot, modifying its call to for example this:
```
chroot /path/to/rootfs sh -c "apt update && apt upgrade -yq && wifite -i wlan0"
```

> but wifite -i wlan0 is not running

Ensure that **wifite** can work on your device. That program does not work under proot. It requires a rooted device and Monitor Mode support in your chipset.

> did you get that now ???

I understand what you are trying accomplish. The question is only about your shell scripting knowledge. I see you are trying to use Kali and Nethunter software, so you should be ok with scripting. Posts however do not show that...

And you should understand that **we will not write any scripts for you**. That's Termux bug tracker and not something like https://stackoverflow.com/.
