### ISSUE TITLE
using htop 

### ISSUE THREAD

**Issue by aliza-ada** [termux/termux-app#1580]
![Screenshot_20200529-113703_Termux](https://user-images.githubusercontent.com/29276037/83231475-c9297c80-a1a0-11ea-84ec-3e55072472e3.jpg)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: 0.94
* Android OS version: 10 / Q stock
* Device model: Galaxy J6

$ htop
CANNOT LINK EXECUTABLE "htop": cannot locate symbol "__aeabi_ldiv0" referenced by "/data/data/com.termux/files/usr/bin/htop"...
$

**Comment by Grimler91** [comment]
Similar issue as https://github.com/termux/termux-app/issues/1580. You can probably use the workaround described in https://github.com/termux/termux-packages/issues/4615#issuecomment-586636010

**Comment by aliza-ada** [comment]
i used 
`LD_PRELOAD=/system/apex/com.android.media.swcodec/lib/libclang_rt.ubsan_standalone-arm-android.so htop`
it works but how fix this problem for ever? need add to profile?

**Comment by Grimler91** [comment]
You can create an alias: `alias htop="LD_PRELOAD=/system/apex/com.android.media.swcodec/lib/libclang_rt.ubsan_standalone-arm-android.so htop"`, put that in your .bashrc

**Comment by xeffyr** [comment]
Perhaps everything for Android 10 should be built with undefined behaviour sanitizer to prevent this kind of errors ?

**Comment by aliza-ada** [comment]
thanks for help im w8 for new update to fix this problem and using alias for this
btw i have this problem in wget and i fixed by this way https://github.com/termux/termux-app/issues/1580#issuecomment-635902755 .

**Comment by bayuah** [comment]
So, I tried https://github.com/termux/termux-app/issues/1580#issuecomment-635902755, but this error appears instead:

```
$ LD_PRELOAD=/system/apex/com.android.media.swcodec/lib/libclang_rt.ubsan_standalone-arm-android.so htop
CANNOT LINK EXECUTABLE "htop": library "/system/apex/com.android.media.swcodec/lib/libclang_rt.ubsan_standalone-arm-android.so" needed or dlopened by "/data/data/com.termux/files/usr/bin/htop" is not accessible for the namespace "(default)"
```

Is there any alternative?
