### ISSUE TITLE
CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found  TSU

### ISSUE THREAD

**Issue by PranshuTG** [termux/termux-app#1581]
hi so my problem is that I can't run tsu command and it says CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found 

to reproduce this I installed tsu and typed in tsu and bamm
CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found 

I'm using samsung galaxy grand quattro

Lineage os 
Android 6

**Comment by xeffyr** [comment]
Try
```
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib`
```
***
_Android 5.x - 6.x is not supported and bugs are not going to be fixed for them._
