### ISSUE TITLE
How to Exit the "word typing" phrase?

### ISSUE THREAD

**Issue by BlueWhaleYT** [termux/termux-app#1582]
Hey there. I am a newbie of Termux. I wanna host the python discord bot with Termux. After I typed
`$ python Bot.py`

then it starts to enter a word typing phrase(not allowed to type commands)

So. How I exit it? or if there are users had been posted similar to this issue. Please for the link.
thanks guys.
![20200531_115310](https://user-images.githubusercontent.com/52563316/83344136-7a611b80-a335-11ea-9fa2-70f090da5514.png)

**Comment by Grimler91** [comment]
Ctrl + c or ctrl + d can generally be used to stop and exit processes
