### ISSUE TITLE
Hola prácticamente estoy empezando en esto ya tenía termux ypor error lo borre completamente, lo volví a instalar ya había dado permiso de almacenamiento en Termux (no cuento con SD ya q4es bastante la memoria interna 90gb) por alguna razón volví a ejecutar termux - setup - storage y me apareció esto Directory '~/storage' is going to be wiped. No storage contents will be touched.  Do you want to continue ? (y/n)porque es 

### ISSUE THREAD

**Issue by Geminis983** [termux/termux-app#1585]
Ojalá puedan orientarme por favor

**Comment by xeffyr** [comment]
1. Use **English** to write issues. Google Translate is not a perfect tool to correct decipher what you wrote here.
2. Yes, if directory `~/storage` is present, `termux-setup-storage` will prompt you about deleting it. In previous versions that directory was wiped without user prompt.
