### ISSUE TITLE
termux-chroot crash the app

### ISSUE THREAD

**Issue by west-shell** [termux/termux-app#1592]
I want to enter termux-chroot once opened termux.
so I add exec termux-chroot to .zshrc .
But now I cant enter termux
it shows
[Process completed (signal 35) - press Enter]
what could i do if not reset

**Comment by xeffyr** [comment]
Open failsafe shell and remove or rename your .zshrc.

Adding termux-chroot into shell startup file is bad idea. It will recursively loop until out-of-memory condition will happen.

**Comment by west-shell** [comment]
what is failsafe shell 
how can i get in it

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Recovering_a_broken_environment

**Comment by west-shell** [comment]
Thank you very much
