### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by SA651** [termux/termux-app#1593]
How to move or copy files like photos,media from termux home directory to phone storage

**Comment by xeffyr** [comment]
Use command `mv`.
```
termux-setup-storage
mv ./file_or_dir_1 ./file_or_dir_2 ./file_or_dir_3 /sdcard/
```

Alternate way is to use file manager like https://play.google.com/store/apps/details?id=nextapp.fx, connect to Termux storage and move files to your phone storage.
