### ISSUE TITLE
Coping in Dex mode form Andronix to Termux doesn't work while using bluetooth keyboard

### ISSUE THREAD

**Issue by Dirik94** [termux/termux-app#1594]
**Problem description**
<img width="1026" alt="Screenshot 2020-06-10 at 10 56 12" src="https://user-images.githubusercontent.com/51020279/84358509-8798c880-abc7-11ea-8958-dfdaa0dfeace.png">
<img width="1021" alt="Screenshot 2020-06-10 at 10 56 25" src="https://user-images.githubusercontent.com/51020279/84358520-8cf61300-abc7-11ea-8174-395295fab849.png">

Coping in Samsung Dex mode form Andronix to Termux doesn't work while using Bluetooth keyboard. Crlt+v or command+v does nothing in Dex mode. The issue persists in Dex mode in Mac OS while using the built-in keyboard as well.
Copying and pasting by phone touch controls works fine.
I have risen this issue with andronix team but they responded it is Termux issue.
https://github.com/AndronixApp/AndronixOrigin/issues/37#issue-636147607

**Steps to reproduce**
- Installing andorinix and Termux apps
- Opening Samusng Dex on Mac OS or normal Dex mode
- Choosing to install paid Ubuntu version in Androinix
- clicking button to copy linux command line
- trying to paste by command+V or crtl+v doesn't work

**Expected behavior**
Using keyboard shortcut Command+V or Crlt+V should paste form andoinix to Termux.

**Additional information**

* Termux application version: 0.94
* Android OS version: 10 One UI ver: 2.1
* Device model: Samsung s10e
* OS: Macbook pro 13 retina Mac OS 10.15.5, a1502

**Comment by xeffyr** [comment]
ctrl-v is not correct shortcut for pasting in Termux and generally any terminal.

Use ctrl-alt-v as documented at https://wiki.termux.com/wiki/Hardware_Keyboard.

**Comment by Dirik94** [comment]
Thank you for reply! I works with crlt+alt+v.
