### ISSUE TITLE
Package request:Pyinstaller

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-app#1595]
Currently pyinstaller gets install on termux without error. But while running it requires python environment to be compiled and installed manually with --enable-shared option. However compiling python on termux is creating a lots of errors. Termux not having proper packages and configurations to allow compiling python from source.
Pyinstaller is great tool from python side and it allows building standalone executables from python script. 
Please someone provide solution if possible.

**Comment by Grimler91** [comment]
Python, and most of our packages, have already been compiled with `--enable-shared`. 

Please share code for reproducing the error you get with pyinstaller, and share the full log output.

**Comment by tathastu871** [comment]
https://paste.ubuntu.com/p/Jcq5kQHnTT/
Above link has full error log

**Comment by Grimler91** [comment]
@tathastu871 can you give the commands to reproduce that output?

**Comment by tathastu871** [comment]
> @tathastu871 can you give the commands to reproduce that output?

pyinstaller ./HTML_TABLE_TO_CSV.py and 
pyinstaller --onefile /.HTML_TABLE_TO_CSV.py
Both above comand gave this error.(The python file has pa das as dependency

**Comment by tathastu871** [comment]
Have tried installing ubuntu on termux and then compiling pyinstaller and bootlaoder from source for termux based ubuntu and it worked.

**Comment by xeffyr** [comment]
> But not work on termux itself

Because Termux is not FHS-compliant.

**Comment by Grimler91** [comment]
Fairly easy patch:

```diff
diff -u -r /data/data/com.termux/files/usr/lib/python3.8/site-packages/PyInstaller.orig/depend/bindepend.py /data/data/com.termux/files/usr/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py
--- /data/data/com.termux/files/usr/lib/python3.8/site-packages/PyInstaller.orig/depend/bindepend.py	2020-07-03 12:40:51.609419646 +0200
+++ /data/data/com.termux/files/usr/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py	2020-07-03 12:42:50.369419561 +0200
@@ -780,7 +780,7 @@
     # Look in the known safe paths.
     if lib is None:
         # Architecture independent locations.
-        paths = ['/lib', '/usr/lib']
+        paths = ['/data/data/com.termux/files/usr/lib', '/lib', '/usr/lib']
         # Architecture dependent locations.
         if compat.architecture == '32bit':
             paths.extend(['/lib32', '/usr/lib32', '/usr/lib/i386-linux-gnu'])
```

I can open an issue upstream later.

**Comment by msn-05** [comment]
> Fairly easy patch:
> 
> ```diff
> diff -u -r /data/data/com.termux/files/usr/lib/python3.8/site-packages/PyInstaller.orig/depend/bindepend.py /data/data/com.termux/files/usr/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py
> --- /data/data/com.termux/files/usr/lib/python3.8/site-packages/PyInstaller.orig/depend/bindepend.py	2020-07-03 12:40:51.609419646 +0200
> +++ /data/data/com.termux/files/usr/lib/python3.8/site-packages/PyInstaller/depend/bindepend.py	2020-07-03 12:42:50.369419561 +0200
> @@ -780,7 +780,7 @@
>      # Look in the known safe paths.
>      if lib is None:
>          # Architecture independent locations.
> -        paths = ['/lib', '/usr/lib']
> +        paths = ['/data/data/com.termux/files/usr/lib', '/lib', '/usr/lib']
>          # Architecture dependent locations.
>          if compat.architecture == '32bit':
>              paths.extend(['/lib32', '/usr/lib32', '/usr/lib/i386-linux-gnu'])
> ```
> 
> I can open an issue upstream later.

thanks bro this worked!
