### ISSUE TITLE
Extras Keys

### ISSUE THREAD

**Issue by Morpheus2077** [termux/termux-app#1596]
How do i recover this function, it only works without extra keys.
![Screenshot_20200612-150527~2](https://user-images.githubusercontent.com/57775700/84547050-12b5b380-acd9-11ea-9da7-afc00fa27c34.png)

**Comment by xeffyr** [comment]
What do you mean ? Extra keys work for me...

**Comment by xeffyr** [comment]
If you are on v0.95, check https://github.com/termux/termux-app/pull/1479 about new configuration.

**Comment by Morpheus2077** [comment]
solved thanks
