### ISSUE TITLE
`which` not found

### ISSUE THREAD

**Issue by ElvenSpellmaker** [termux/termux-app#1597]
**Problem description**
After upgrading termux it seems to no longer have `which` which broke my rvm install.
I had to install the `debianutils` package to get rvm working again.

**Steps to reproduce**
Upgrade Termux and try to use anything with `which`.

**Expected behavior**
Commands shouldn't disappear between versions without clear warning.

**Additional information**

* Termux application version: latest 
* Android OS version: 10
* Device model: OnePlus 6

**Comment by xeffyr** [comment]
> After upgrading termux it seems to no longer have which which broke my rvm install.

Correct. We are deprecating busybox and its applets are removed.

> I had to install the debianutils package to get rvm working again.

Yes, you need to use a "complete" packages like this one instead. Also `debianutils` is now part of default Termux installation if using app v0.95+.

**Comment by ElvenSpellmaker** [comment]
Interesting how I didn't have the app installed, I'm on the latest version 0.95 according to the Play store

**Comment by xeffyr** [comment]
@ElvenSpellmaker Default installation means "clean state" (e.g. after `rm -rf $PREFIX` and restart). If you just updated app, that won't change anything in $PREFIX.
