### ISSUE TITLE
New termux notification icon too thin.

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#1600]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: latest
* Android OS version: 10
* Device model: galaxy note 10+

![Screenshot_20200614-134050_Termux](https://user-images.githubusercontent.com/5674757/84600111-267e2880-ae45-11ea-9778-1811fe3faa86.jpg)

**Comment by sfzhi** [comment]
May I suggest to remove the surrounding circle, make the `>_` larger and draw it with thicker lines? I think that would make a decent icon - simple and recognizable.

**Comment by ezhd** [comment]
Just like it used to be. 
It was god damn ideal! Followed Android design guidelines perfectly. It was one of the reasons I loved the app in the first place. 
Please bring the old icon back 🙏

**Comment by xeffyr** [comment]
Continued in \-\-\> https://github.com/termux/termux-app/issues/1619
