### ISSUE TITLE
Using Kotlin Script

### ISSUE THREAD

**Issue by bartekpacia** [termux/termux-app#1602]
Currently, the Gradle build files are written in Groovy.
It can be also done using the new [Gradle Kotlin DSL](https://docs.gradle.org/current/userguide/kotlin_dsl.html) and take advantage of the following features:
- the same language everywhere (assuming that the project will be rewritten to Kotlin)
- better support from the Android Studio when editing the build files

More info: https://proandroiddev.com/converting-your-android-gradle-scripts-to-kotlin-1172f1069880

**Reference implementation**
-

**Comment by twaik** [comment]
I do not think we should rewrite significant part of a project to fit modern technologies.
