### ISSUE TITLE
[BUG] clear Command isn't working well

### ISSUE THREAD

**Issue by Gauravjani207** [termux/termux-app#1604]
What happens: when I have lots of text on termux screen I press _ctrl+l_  or simply type clear commnd to clear screen. It clear temporarily, but when minimize app and resume it again, whole history of text is on screen.

Thank You

**Comment by xeffyr** [comment]
> It clear temporarily, but when minimize app and resume it again, whole history of text is on screen.

Works according to terminal specification. I.e. clears "current page".
Want to clear scrollback ? Use `reset` instead.
