### ISSUE TITLE
Bypass battery optimisations with Wallpaper

### ISSUE THREAD

**Issue by Kaank2006** [termux/termux-app#1605]
**Wallpaper to bypass battery restrictions**

As you know, wake lock does not entirely bypass phone battery saving optimisations for some devices. This feature would be able to set your wallpaper via the termux app, so the device does not kill Termux to prioritise other apps. To not force one single wallpaper, a user would be able to upload his own wallpaper and use termux to set it. This would help people who are using Linux distrobutions in termux, because vnc viewers are usually heavy on memory, which results in termux being killed. 

**I have seen this implemented in the app "Power Shade".** 

Provide links to more background information.
Unfortunately, I have found no website about this.

**Comment by xeffyr** [comment]
> Bypass battery optimisations with Wallpaper

Could you elaborate more on that ? How wallpaper is related to battery optimizations ?

Do you have any link to Android SDK documentation which describes well relationship between wallpaper and battery optimization or Doze mode ?

> To not force one single wallpaper, a user would be able to upload his own wallpaper and use termux to set it.

That functionality is already implemented through Termux API.
Check https://wiki.termux.com/wiki/Termux-wallpaper and https://wiki.termux.com/wiki/Termux:API.

> This would help people who are using Linux distrobutions in termux, because vnc viewers are usually heavy on memory, which results in termux being killed.

Again, please elaborate. What does it have to do with VNC viewers ?

**Comment by Kaank2006** [comment]
> > Bypass battery optimisations with Wallpaper
> 
> Could you elaborate more on that ? How wallpaper is related to battery optimizations ?



> Do you have any link to Android SDK documentation which describes well relationship between wallpaper and battery optimization or Doze mode ?

Sorry, like I said, this is all hearsay, I may ask the "powersshade" developers about where they found it. 

But I think the concept is that if an application sets your wallpaper, android let's it stay on the background and keep running to not freeze live wallpaper services. 

First of all, sorry for sending a kind of enhancement that is hearsay. 

> > To not force one single wallpaper, a user would be able to upload his own wallpaper and use termux to set it.
> 
> That functionality is already implemented through Termux API.
> Check https://wiki.termux.com/wiki/Termux-wallpaper and https://wiki.termux.com/wiki/Termux:API.

I did not know that, thanks for pointing it out. 

> > This would help people who are using Linux distrobutions in termux, because vnc viewers are usually heavy on memory, which results in termux being killed.
> 
> Again, please elaborate. What does it have to do with VNC viewers ?

Android kills apps that take too much memory that aren't on the foreground. While using a vnc viewer and termux at the same time (which it to connect to your distro which you are running via proot), you have to switch between them occasionally, to make android not freeze termux. 

But again, since you gave me a solution to setting the wallpaper via termux, the feature I suggested is unnecessary.

**Comment by xeffyr** [comment]
> But I think the concept is that if an application sets your wallpaper, android let's it stay on the background and keep running to not freeze live wallpaper services.

Wallpapers actually set by Android. Application just requests to use a specific file as wallpaper.

Live wallpapers are running only when device screen is on, so has nothing to do with battery optimization.

>While using a vnc viewer and termux at the same time (which it to connect to your distro which you are running via proot), you have to switch between them occasionally, to make android not freeze termux.

Thanks for clarifying, but I'm maintainer of `tigervnc` package and variety of other packages for Termux. I didn't observed any Termux freezes. This also goes against app lifecycle defined by SDK. If you experiencing such behaviour, then your OS is not standard (device manufacturer is Huawei?) and we can't do anything with that.
