### ISSUE TITLE
Python cgi script not executing when using http.server

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-app#1606]
**Problem description**

Script content:
#!/data/data/com.termux/files/usr/bin/python3
import cgi
import cgitb; cgitb.enable()  # for troubleshooting
print ("Content-type: text/html\n")
print('<html>')
print(' <head>')
print(' <title>test</title>')
print(' </head>')
print(' <body>')
print(' <h2>teeeeeeeeeest</h2>')
print(' </body>')
print(' </html>')
**Steps to reproduce**

chmod +x test.py
python3 -m http.server --cgi 8000
Above command when executed from outside cgi-bin directory shows blank page

Above command when executed from cgi-bin directory shows the filen content and not executing the script.
![Screenshot_20200616-215304_Termux](https://user-images.githubusercontent.com/65007212/84801260-92ff5000-b01c-11ea-81a9-4f64204220c6.jpg)
![Screenshot_20200616-215257_Termux](https://user-images.githubusercontent.com/65007212/84801266-94c91380-b01c-11ea-8a33-f2df1d475ab8.jpg)
![Screenshot_20200616-215314_Chrome Dev](https://user-images.githubusercontent.com/65007212/84801270-95fa4080-b01c-11ea-8f43-94c14956ac79.jpg)

**Expected behavior**

![Screenshot_20200616-220114_Chrome Dev](https://user-images.githubusercontent.com/65007212/84801550-f25d6000-b01c-11ea-9c07-8dd2b00259b8.jpg)

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
See xeffyrs comments in https://github.com/termux/termux-app/issues/1601 i.e. fix script path

**Comment by xeffyr** [comment]
@tathastu871 Check what you are typing in shell before submitting bug report !

URL should be http://localhost:8000/cgi-bin/test.py.

You have omitted the `cgi-bin` between `http://localhost:8000/` and `/test.py`.

**Comment by tathastu871** [comment]
> @tathastu871 Check what you are typing in shell before submitting bug report !
> 
> URL should be http://localhost:8000/cgi-bin/test.py.
> 
> You have omitted the `cgi-bin` between `http://localhost:8000/` and `/test.py`.

You first read what issue i have created.
I have clearly mentioned in issue that when script is opened from cgi-bin folder it shows a blank page and when opened from any other folder it shows content rather than executing

**Comment by Grimler91** [comment]
@tathastu871 the blank page issue was fixed with the extra newline after `Content-type: text/html`.

**Comment by tathastu871** [comment]
> @tathastu871 the blank page issue was fixed with the extra newline after `Content-type: text/html`.

already added \n to content line still blank page

**Comment by tathastu871** [comment]
Its not a typo mistake please read issue carefully
You first read what issue i have created.I have clearly mentioned in issue that when script is opened from cgi-bin folder it shows a blank page and when opened from any other folder it shows content rather than executing.
Xefffyr You first understand that in python the directory from which python -m http.server --cgi 8000 is executed , that directory becomes the home page for localhost url in browser.Means if i have started server from cgi-bin folder than in url cgi-bin is not required and if we write cgi-bin that it will show path not exist. So url will be localhost:8000/test.py because localhost itself is cgi-bin folder in this scenario
However if have my  cgi-bin folder in home directory and i started server from home folder than home folder becomes localhost and so while accessing script i have to write localhost:8000/cgi-bin/test.py because on this scenario localhost is home folder so it will open localhost that is home folder and then go to cgi-bin folder and then script.
i have tried both above ways1) Firstly i created cgi-bin folder and placed script in it then i ran server from home directory and visited localhost:8000/cgi-bin/test.py. It showed blank page.








2) i ran server directly from cgi-bin directory  itself and in browser i entered localhost:8000/test.py. This time it showed me the content of script rather than executing.







Please read issue conpletely before closing or arriving at any conclusion. We are having problem thats why we have created issue. Why are you closing issue before we read your comment and reply
Sent from Yahoo Mail on Android 
 
  On Wed, 17 Jun 2020 at 9:47, Henrik Grimler<notifications@github.com> wrote:   


@tathastu871 the blank page issue was fixed with the extra newline after Content-type: text/html.

**Comment by Grimler91** [comment]
> Firstly i created cgi-bin folder and placed script in it then i ran server from home directory and visited localhost:8000/cgi-bin/test.py. It showed blank page.

Which browsers have you tried with? Maybe the one you are trying requires \r\n instead of \n.

> i ran server directly from cgi-bin directory  itself and in browser i entered localhost:8000/test.py. This time it showed me the content of script rather than executing.

Script needs to be in a cgi-bin subdirectory, otherwise the http module does not know that it should be evaluated and not just served.

> Please read issue conpletely before closing or arriving at any conclusion

We have read the issue and have not been able to reproduce your problem. Since it works for us there does not seem to be an issue with termux for us to act on, we use github as a bug tracker and not as a general help forum. It is possible to continue commenting on issues after they have been closed.

**Comment by tathastu871** [comment]
Ok trying other solutions. Anyway Thanks. 
Already tried \n \n\n \r\n and all such combinations. Tried using browsers like chrome uc brave opera.
Also configured apache server and added handler for cgi py and pl scripts but in apache server also either there occurs blank page or script showing contents
