### ISSUE TITLE
Extra Keys Height Stays at 1 Row

### ISSUE THREAD

**Issue by SkittishSloth** [termux/termux-app#1607]
**Problem description**

I'd had Termux installed for a while, had to uninstall it about a while ago, and just reinstalled it earlier this week; not sure what updates I might've missed, so I can't pinpoint when this happened, but I do see quite a bit of work regarding Extra Keys recently. I don't think those changes have propagated to F-Droid yet, so maybe this is resolved - or maybe I have something else going on?

When I configure extra keys for two rows and reload (via termux-reload-settings), it adds the keys perfectly fine, but they're smaller - the grid they're displayed in stays the same size even though it has two rows instead of one. My thumbs are way too fat for these and I can't really use it any more.

**Steps to reproduce**

Just adding the two-row configuration from the wiki will reproduce it. Changing the style seems to affect the width of the keys, but not the height. 

**Expected behavior**

The buttons should be the same size - or at least close to the same size - regardless of the number of rows displayed, with the grid growing to accommodate.

**Additional information**

* Termux application version: 0.94 (from F-Droid)
* Android OS version: 7.0
* Device model: SM-G928T

I'd greatly appreciate any help - I absolutely love Termux, but I can't really get anything done like it it now. Please let me know if you need any further information from me.

**Comment by xeffyr** [comment]
> it adds the keys perfectly fine, but they're smaller - the grid they're displayed in stays the same size even though it has two rows instead of one

Known bug and there is already submitted issue for that.

Just restart application and it will appear as normal 2-row.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app/issues/1003

**Comment by SkittishSloth** [comment]
Thanks for the reply! I didn't catch that it was a known bug, but I did come back to say that a restart fixed it so I'm happy again. Thank you!
