### ISSUE TITLE
external css linked with html not working with apache server 

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-app#1608]
**Problem description**

External css not applyint styles to html on apache localhost
**Steps to reproduce**

both html and css are in same folder(/data/data/com.termux/files/usr/share/apache2/default-site/htdocs)
apachectl start
Html file
```
<html>                                       
 <head>                                              
 <link rel="stylesheet" type="text/css"  href="http://localhost:8080/main.css" />
</head>
<body>
<h1> Chapter 1.</h1>                          
<h1>Chapter 1.</h1>                         
 </body>                                        
 </html>
```

main.css
```
<style>
h1 {
    color: red;
}
</style>
```

**Expected behavior**

Expected behaviour is all h1 headings in browser to be in red colour

**Additional information**

Tried solutions:
-------------------------
```<link rel="stylesheet" type="text/css"  href="http://localhost:8080/main.css" />```

```<link rel="stylesheet" type="text/css"  href="./main.css" />```

```<link rel="stylesheet" type="text/css"  href="main.css" />```

Also tried adding css mime type and enabling conf in httpd.conf and .htacces. Used Addtype to add css and js

Also enabled mod_mime module

Also added Content-type: text/javascript or Content-type: text/css to html file 

But nothing worked

* Termux application version:0.95
* Android OS version:10
* Device model:SM A750F

**Comment by xeffyr** [comment]
Can you check server logs ? Is your main.css accessed at all ? Have you tried to clear browser cache ?

**Comment by tathastu871** [comment]
> Can you check server logs, is your main.css accessed at all ? Have you tried to clear browser cache ?

Already tried clearing browser as apache carries out caching of pages and so cache is cleared but still no benefit

**Comment by xeffyr** [comment]
Ok, but what about logs ? Is there any line showing that main.css was accessed ?

**Comment by tathastu871** [comment]
> Ok, but what about logs ? Is there any line showing that main.css was accessed ?

I have deleted access log file and restarted apache and then just opened html file in browser and then checked access log it had two entry one for html and other for css

It means that when html is accessed the linked css is also accessed so problem might be different.

![Screenshot_20200618-205821_Termux](https://user-images.githubusercontent.com/65007212/85040943-f61cee00-b1a6-11ea-8811-1abcb76ae700.jpg)

**Comment by xeffyr** [comment]
Logs are ok, now the problem I can think about is CSS file. What it's exact content ?

Is it look like in your post (had to edit it to enable code formatting):
```
<style>
h1 {
    color: red;
}
</style>
```

Or this ?
```
h1 {
    color: red;
}
```

***

If you use CSS in separate file, you SHOULD NOT use `<style>` tag and code must look like
```
h1 {
    color: red;
}
```

**Comment by xeffyr** [comment]
https://www.w3schools.com/css/css_howto.asp
