### ISSUE TITLE
[INFO] F-Droid release for v0.95 is not available

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-app#1609]
Latest Termux version for F-Droid is **v0.94** currently.

F-Droid has issues with building the latest version. Its build log at https://f-droid.org/wiki/page/com.termux/lastbuild_95 shows (as of 2020-06-21 07:50:09Z):
```
"could not bring up vm 'builder_default'"
```

We can't do anything with that failure as F-Droid manages builds on its own and it's unclear what caused the issue.

**Comment by xeffyr** [comment]
During the time when F-Droid was unable to "bring up vm builder_default", Google released a new NDK version. App build configuration was updated only in https://github.com/termux/termux-app/commit/2224d917a331b2e77dd299b9d02c87d8f4ab7610 which goes after v0.95.

I will update tag to that commit, there no changes except updated NDK but F-Droid should be able to build application successfully.

**Comment by termux4me** [comment]
> During the time when F-Droid was unable to "bring up vm builder_default", Google released a new NDK version. App build configuration was updated only in [2224d91](https://github.com/termux/termux-app/commit/2224d917a331b2e77dd299b9d02c87d8f4ab7610) which goes after v0.95.
> 
> ```
> A problem occurred configuring project ':app'.
> > Requested NDK version 21.2.6472646 did not match the version 21.3.6528147 requested by ndk.dir at /home/vagrant/android-ndk/r21d
> ```
> 
> I will update tag to that commit, there no changes except updated NDK but F-Droid should be able to build application successfully.

i cant install Termux 0.95 from Google play store and i tried several times to install it
getting error when it hits 100% 
note i did try to download it with system android 8.1
and 10

**Comment by xeffyr** [comment]
> i cant install Termux 0.95 from Google play store and i tried several times to install it

Then don't mix installations from different sources. Google Play and F-Droid builds have different signatures which must match between all add-ons and Termux app.

If you want to install Termux from Google Play, then uninstall Termux app and all add-ons before attempting to reinstall. You just have no other choice. Same signature is requirement of Termux add-on design.

**Comment by xeffyr** [comment]
Version 0.95 is now on F-Droid.
