### ISSUE TITLE
incorrect line wrapping if PS1 contains ANSI escape sequenses in the last line

### ISSUE THREAD

**Issue by vladko312** [termux/termux-app#1611]
**Problem description
If `PS1` contains escape sequences (for example `\e[91m`), problems appear while writing long commands.
The first line ends before the end of the screen.
The second line overwrites the first.
Selecting long commands from history (by arrows) leads to strange output.

**Steps to reproduce**
`nano ~/../usr/etc/bash.bashrc`
Add `PS1` variable like `\n\e[92m\u@\h\e[0m:\e[94m\W\e[0m\$ `
Save file
Restart app
Start using it with long commands

**Expected behavior**
Colors are not affecting line wrapping
Behavior similar to `PS1` set to `\n\u@\h:\W\$ `, but with colorful `user@host:dir$ ` string

**Additional information**

* Termux application version:
0.95
* Android OS version:
8.1.0 (MIUI global 9.5.13.0)
* Device model:
Xiaomi Redmi Note 5

**Comment by trygveaa** [comment]
This is nothing specific to Termux. When you use colors in PS1 you have to surround them with `\[` and `\]`. See https://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html

> As mentioned before, non-printing escape sequences have to be enclosed in `\[\033[` and `\]`.

**Comment by vladko312** [comment]
Thank you for your response. 
Sorry, I am a bit new to terminals (previously worked with them as with abstract input/output)

**Comment by vladko312** [comment]
Found another issue with colors in `PS1`:
My `PS1` is now set to `\[\e[91m\]\n\u@\h\[\e[0m\]:\[\e[94m\]\W\[\e[0m\]\$ ` and it works fine while using the app. 
However, if I switch to another app and back, beginning of the last line becomes white (while directory is still blue and other lines are correct)
Is it related to `\n` after color (and intended) or is it a bug?

**Comment by vladko312** [comment]
**Before switching apps**
![IMG_20200623_123646](https://user-images.githubusercontent.com/37411315/85388205-7e581600-b54e-11ea-9601-5f57587cdffe.jpg)
**After switching apps**
![IMG_20200623_123745](https://user-images.githubusercontent.com/37411315/85388240-89ab4180-b54e-11ea-8522-a014edad560d.jpg)
**After input**
![IMG_20200623_123707](https://user-images.githubusercontent.com/37411315/85388287-9465d680-b54e-11ea-96b5-686aee192c07.jpg)

**Comment by vladko312** [comment]
Moving `\n` to the beginning of `PS1` solves the problem, but is it a correct behaviour?

**Comment by trygveaa** [comment]
Sounds like a bug, I don't think it should behave differently before and after you switch out and in of the app.

**Comment by vladko312** [comment]
It seemed strange to me, as this affected previosly printed text

**Comment by xeffyr** [comment]
@vladko312 Move newline to beginning and problem will gone. Do not add `\n` inside colored sequence.

```
\n\[\e[91m\]\u@\h\[\e[0m\]:\[\e[94m\]\W\[\e[0m\]$
```
