### ISSUE TITLE
Termux-setup-storage

### ISSUE THREAD

**Issue by sowntharso** [termux/termux-app#1612]
termux app any error create

**Problem description**
Directory '~/storage' is going to be wiped. No sto

**Steps to reproduce**

**Expected behavior**
<!--
 #1383 

**Additional information**

* Termux application version:0.95
* Android OS version:9PKQ1 .190319 .001
* Device model:Redmi 8

**Comment by sowntharso** [comment]
Termux-setup-storage next step Directory '~/storage' is going to be wiped. No sto this error

**Comment by xeffyr** [comment]
If you read carefully, you will figure out that this is not error.
If `termux-setup-storage` really deletes directory `~/storage` and makes it again, so nothing wrong here. Just a prompt whether to continue or not.

**Comment by sowntharso** [comment]
All setps for correct following but this is erro coming update your app any
error create your app unusfull app ok

**Comment by xeffyr** [comment]
> All setps for correct following but this is erro coming update your app

If you can read, you will understand that this is not error.

> any error create your app unusfull app ok

Well, then uninstall application immediately.
