### ISSUE TITLE
could not install Termux from play store for samsong A50

### ISSUE THREAD

**Issue by termux4me** [termux/termux-app#1615]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by ChiefMikeK** [comment]
## Please submit the requisite information! :neckbeard: 
![zero](https://user-images.githubusercontent.com/20070053/86231152-abe33600-bbc4-11ea-92c8-b1fccef933d5.png)
