### ISSUE TITLE
CLI App Manager

### ISSUE THREAD

**Issue by joshcangit** [termux/termux-app#1616]
**Feature description**

Termux can already analyze apk files. However, would there be a way to manage installed apps?

I simply want a way to access the `versionName` or `versionCode` from the **AndroidManifest.xml**.

**How I did it initially**
I found the base apk, a.k.a _Source Directory_, using [apps_Packages Info](https://f-droid.org/en/packages/com.oF2pks.applicationsinfo/) or [App Manager](https://apt.izzysoft.de/fdroid/index/apk/io.github.muntashirakon.AppManager).
Then, I executed the command from [here](https://stackoverflow.com/a/4697460)  using `aapt`.

```
apk="/data/app/eu.faircode.email-<base64 string>/base.apk"
aapt dump badging $apk | sed -n "s/.*versionName='\([^']*\).*/\1/p"
```

**Problem**
The `<base64 string>` kept changing after each time the installed app is updated so I can't use the above commands programmitically.

Does another app/terminal emulator have this feature?
> So far, I haven't heard of any other terminal emulators with this feature.

**Comment by xeffyr** [comment]
> kept changing after each time the installed app is updated so I can't use the above commands programmitically

Use utility `pm`. For example, `pm path com.android.chrome` or `pm path com.termux`.

**Comment by joshcangit** [comment]
Still not working.

```
cmd: Failure calling service package: Failed transaction (2147483646)
```

**Comment by xeffyr** [comment]
> Did not work.

Which Android version ?

**Comment by joshcangit** [comment]
> Which Android version ?

Android 10

**Comment by xeffyr** [comment]
Ok, then 'pm' is broken as of Android 10.

You can submit a request to https://github.com/termux/termux-api as just terminal app can't solve that problem.  Describe which features you need, for example:
* show versions of installed apks.
* show package names of installed apks.

**Comment by joshcangit** [comment]
> Ok, then 'pm' is broken as of Android 10.
> 
> You can submit a request to https://github.com/termux/termux-api as just terminal app can't solve that problem. Describe which features you need, for example:
> 
> * show versions of installed apks.
> * show package names of installed apks.

I've submitted an issue to that repository. Someone there said `pm` will soon be replaced with `cmd`. Even so, the error still persists.

**Comment by xeffyr** [comment]
As I wrote, you should create a *request for similar functionality* not filing a bug report for /system/bin/pm or /system/bin/cmd. 

These utilities are not managed by Termux, instead they are part of Android OS and we simply can't fix them. These utilities are intended to be used only with ADB for debugging purposes and their usage may get disabled for non-privileged shells.

What we can do is only to create an API for getting info about installed applications, nothing more.

**Comment by joshcangit** [comment]
https://github.com/termux/termux-api/issues/354#issuecomment-652387465
