### ISSUE TITLE
new icon size and border

### ISSUE THREAD

**Issue by 532910** [termux/termux-app#1619]
1. The new icon's border is extremely thin, so it's flickers on my screen.
2. New icon is very small (compared to other icons)

![image](https://user-images.githubusercontent.com/14617699/86023183-026d3a80-ba34-11ea-8d40-3f6022a0fff2.png)
![image](https://user-images.githubusercontent.com/14617699/86023190-04cf9480-ba34-11ea-9664-522e16231b08.png)

* Termux application version: 0.95

**Comment by ezhd** [comment]
Android development guidelines have exact specs for notification icons. I would suggest following them. 
Also I can volunteer to create some mock-ups

**Comment by ezhd** [comment]
Here are some wireframe mockups I made just now.

![01](https://user-images.githubusercontent.com/19352190/87285169-68bc8780-c521-11ea-8e6a-4f60115c64c5.png)
![02](https://user-images.githubusercontent.com/19352190/87285175-69551e00-c521-11ea-85e9-7cc425edf9ea.png)
![03](https://user-images.githubusercontent.com/19352190/87285177-69edb480-c521-11ea-8db1-39c74a4e0045.png)
![04](https://user-images.githubusercontent.com/19352190/87285178-6a864b00-c521-11ea-9248-b56170208064.png)
![og](https://user-images.githubusercontent.com/19352190/87285181-6a864b00-c521-11ea-8300-efbe48d1ea98.png)

And this is real life screenshot comparison on Pixel 2XL device. (Compiled preview apk with svg vector assets)
if anyone interested, I can share svgs ready for production :)

![Frame 7](https://user-images.githubusercontent.com/19352190/87286038-82120380-c522-11ea-8e4e-d8bd1fa4e145.png)

Personal favorite is the last # 04

**Comment by xeffyr** [comment]
> Personal favorite is the last # 04

Agree, the last one seems best. Could you submit a PR with updated icon?

**Comment by trygveaa** [comment]
While I agree that the new one is too thin, isn't it best if it keeps the same placements and proportions as the launcher icon? The last one of your mockups does not. As you can see in the original notification icon (which is identical to the launcher icon apart from the circle), the bottom of the > and _ should align.

**Comment by ezhd** [comment]
I agree that # 03 follow launcher icon the most. In fact it is exact copy. The # 04 was inspired by real life terminal underscore caret, which is usually falls under the line. 
As an afterthought I guess we should stick to the original launcher icon aka # 03

(This is why we have several version presented)

**Comment by xeffyr** [comment]
Part of v0.96 release.
