### ISSUE TITLE
how to install JDK and JRE  in  termux? not ecj

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-app#1622]
Who knows how to install JDK and JRE in termux ? not ecj.   Thanks.

**Comment by xeffyr** [comment]
Termux does not support JDK natively. You need to setup a proot'ed Linux distribution (Arch/Debian/Ubuntu) and install JDK here.

https://wiki.termux.com/wiki/PRoot

Would not suggest any "Termux java installers" available on Github - all of them either use binary-patched JDK from Debian or stolen one from Jvdroid app. None of them working 100% properly.
