### ISSUE TITLE
Multi-Arch support 

### ISSUE THREAD

**Issue by SamarJi** [termux/termux-app#1623]
# 32bit (armhf) on 64bit(arm64)
Hey, can the termux team add multi arch support to termux. I am using aarch64 (all upcoming devices will have this arm arch), I wanted to run armhf debian rootfs, but it giving error , can you add multi arch support.

**Comment by SamarJi** [comment]
Even armhf arch is important to run other softwares

**Comment by xeffyr** [comment]
> can the termux team add multi arch support to termux.

Not for these reasons:
1. Double size of package repositories.
2. Termux-exec LD_PRELOAD'ed library can be only either 32-bit or 64-bit.
3. You can setup it *manually*.

Even if someone will add it to termux-packages, I will refuse to setup/maintain it for my Unstable & X11 repositories.

> I wanted to run armhf debian rootf

Debian has nothing to do with Termux & its multiarch support. Proot already supports 32-bit environment on AArch64, so there shouldn't be any problem with multiarch. Everything you need is to create a 32bit Debian installation or consult Debian documentation to whether it is possible to install armhf over arm64.

**Comment by SamarJi** [comment]
Always thanks to termux developer an termux team to provide quick solution, still I have the problem.

**Comment by SamarJi** [comment]
Finally I got it what I needed
