### ISSUE TITLE
I need a Permission

### ISSUE THREAD

**Issue by SamarJi** [termux/termux-app#1624]
Before saying this, I am aware of the following things:-
(1) If I do it , it can also break some important packages like tigervnc.
(2) Termux packages didn't hardwere acceleration.

I am working debian 20.04 port, which's main feature would hardware acceleration to play games on it, it will on work until I have all the required packages in termux for hardware acceleration. Inbuilt package mesa/x11 doesn't have full access, I want to create a custom build for it, but I needed permission. I will be responsible if anything breaks or crashes on termux in my phone.

Please give me this permission, I wanted to do some experimental things with it to know something more about it.

**Comment by SamarJi** [comment]
This would help me to know will debian proot have hardware acceleration in future, it's something like my search.

**Comment by xeffyr** [comment]
> I am working debian 20.04 port

? Never heard about Debian 20.04... Latest stable is 10.

> I want to create a custom build for it, but I needed permission

Everyone here already has permission to create a custom package builds. Termux is open source.

Clone the repo and follow instructions from https://github.com/termux/termux-packages/wiki.

**Comment by SamarJi** [comment]
Thanks for it, I will give you report (where I can give) my aim is gaming on termux without breaking packages
