### ISSUE TITLE
Replace the `dash` key into a `return` key

### ISSUE THREAD

**Issue by Yuriusu** [termux/termux-app#1626]
Just a tiny bit feature request :laughing: I think the <kbd>dash</kbd> key is unnecessary, I never really use it. Instead, turn it into a <kbd>return</kbd> (i.e, <kbd>enter</kbd>) key.

![Screenshot_20200703-230042_Termux](https://user-images.githubusercontent.com/66087162/86481364-71bf9300-bd82-11ea-8099-be22c79a349e.png)

**Comment by Grimler91** [comment]
It is possible to customize the buttons there, see https://wiki.termux.com/wiki/Touch_Keyboard, so you can edit `~/.termux/termux.properties` and define `extra-keys` to get whichever keys you want
