### ISSUE TITLE
Unable to start the APP

### ISSUE THREAD

**Issue by phone-burner** [termux/termux-app#1629]
**Problem description**

Unable to start the application .
I tried to remove the application and install it from Google Play , and it was still unable to start .
![Screenshot_2020-07-04-20-52-33-820_com miui bugreport](https://user-images.githubusercontent.com/51866924/86523278-93ad3880-be9c-11ea-94bd-16d0066bfc51.jpg)

**Steps to reproduce**

Unknown
**Expected behavior**

Just to start the APP .
**Additional information**

* Termux application version:0.95
* Android OS version:9
* Device model:MI 6X (wayne)

**Comment by xeffyr** [comment]
Required permission is already added: https://github.com/termux/termux-app/blob/master/app/src/main/AndroidManifest.xml#L22.

I'm closing this as OS bug, your ROM doesn't see permission declaration for some reason or has "special" settings for foreground services.
