### ISSUE TITLE
When long tapping a word selection appears on the line above

### ISSUE THREAD

**Issue by memeplex** [termux/termux-app#163]

**Comment by memeplex** [comment]
Could you reproduce this one? Do you need some more input? Maybe I could take a look at the code if you hint me where to start. I'm still experiencing the problem.

**Comment by Auxilus** [comment]
Yes I've encountered this too...
If you zoom in much it will be on same line but otherwise it goes one line above..

**Comment by Quasic** [comment]
I also experience this.

Probably a separate issue, but it's also hard to select text on the first few lines, depending on the zoom, because the selection bar gets in the way. I can't tell what is selected or change that until I copy.

**Comment by Luflosi** [comment]
I'm having the same issue. Has there been any progress on this issue in the past two years?

**Comment by xeffyr** [comment]
Closing as no longer reproducible. Maybe due to recent changes for text selection improvements.
