### ISSUE TITLE
Unable to resolve termux.org

### ISSUE THREAD

**Issue by damionx7** [termux/termux-app#1631]
**Problem description**

Hey there, I have been having a strange problem. I can't update packages after ssh. It works fine when i update from mobile.
I have attached the screenshot for the issue. 

<img width="400" alt="git" src="https://user-images.githubusercontent.com/6530843/86559292-1e4c7100-bf4b-11ea-8016-19f5e47edbf4.png">

**Steps to reproduce**

1. SSH to termux from mac
2. Try to update termux with `pkg update` - get could not resolve termux.org
3. Try to curl `google.com` - get unknown host google.com
5. Try `dig google.com` - works

**Expected behavior**

**Additional information**

* Termux application version: 0.95
* Android OS version:  10
* Device model: OnePlus 7 Pro

**Comment by xeffyr** [comment]
Fix **your network** !

The reason why `dig` woks is that it uses custom DNS servers completely unrelated to those used by your device.

**Comment by damionx7** [comment]
as i said, i can access the network from my phone fine. Its only when i access through ssh, i am not able to connect.

**Comment by xeffyr** [comment]
Hm, only thing that I can think about is difference between environment variables. Android 10 introduces some which allow libc to properly access certain OS components.

Please run comman `env` in Termux without SSH and compare with output of this command under SSH. Post here variables which are missing, they most likely starting with prefix `ANDROID_`.

**Comment by damionx7** [comment]
so, here are the two logs. 
[ssh.log](https://github.com/termux/termux-app/files/4877938/ssh.log)
[mobile.log](https://github.com/termux/termux-app/files/4877939/mobile.log)

**Comment by xeffyr** [comment]
You are completely missing all `ANDROID_` variables in SSH.

1. Are you have configured "any environment cleanup" in .bashrc or somewhere else?
2. What is your OpenSSH version? Are all packages up-to-date?

Diff:
```
~/Загрузки $ diff -uN <(sort mobile.log) <(sort ssh.log)
--- /dev/fd/63	2020-07-06 12:34:26.903489835 +0300
+++ /dev/fd/62	2020-07-06 12:34:26.903489835 +0300
@@ -1,26 +1,29 @@
-ANDROID_DATA=/data
-ANDROID_ROOT=/system
-ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
-ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
-BOOTCLASSPATH=/apex/com.android.runtime/javalib/core-oj.jar:/apex/com.android.runtime/javalib/core-libart.jar:/apex/com.android.runtime/javalib/okhttp.jar:/apex/com.android.runtime/javalib/bouncycastle.jar:/apex/com.android.runtime/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/android.test.base.jar:/system/framework/tcmiface.jar:/system/framework/telephony-ext.jar:/system/framework/qcnvitems.jar:/system/framework/oneplus_sdk_utils.jar:/system/framework/oneplus_sdk_wrapper.jar:/system/framework/oneplus-framework.jar:/system/framework/QPerformance.jar:/system/framework/UxPerformance.jar:/system/framework/WfdCommon.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar
 _=/data/data/com.termux/files/usr/bin/env
-EXTERNAL_STORAGE=/sdcard
 HOME=/data/data/com.termux/files/home
 LANG=en_US.UTF-8
+LC_ALL=en_US.UTF-8
+LC_CTYPE=UTF-8
+LC_TERMINAL=iTerm2
+LC_TERMINAL_VERSION=3.3.12
+LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
 LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
 LESS=-R
 LOGNAME=u0_a202
 LSCOLORS=Gxfxcxdxbxegedabagacad
 LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
+MAIL=/var/mail/root
 OLDPWD=/data/data/com.termux/files/home
 PAGER=less
-PATH=/data/data/com.termux/files/home/.pyenv/plugins/pyenv-virtualenv/shims:/data/data/com.termux/files/home/.pyenv/shims:/data/data/com.termux/files/home/.pyenv/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+PATH=/data/data/com.termux/files/home/.pyenv/plugins/pyenv-virtualenv/shims:/data/data/com.termux/files/home/.pyenv/shims:/data/data/com.termux/files/home/.pyenv/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/sbin:/sbin/su:/su/bin:/su/xbin:/system/bin:/system/xbin
 PREFIX=/data/data/com.termux/files/usr
 PWD=/data/data/com.termux/files/home
 PYENV_SHELL=zsh
 PYENV_VIRTUALENV_INIT=1
 SHELL=/data/data/com.termux/files/usr/bin/zsh
 SHLVL=1
+SSH_CLIENT=192.168.43.65 54411 22
+SSH_CONNECTION=192.168.43.65 54411 192.168.43.80 22
+SSH_TTY=/dev/pts/0
 TERM=xterm-256color
-TMPDIR=/data/data/com.termux/files/usr/tmp
+USER=u0_a202
 ZSH=/data/data/com.termux/files/home/.oh-my-zsh
```

Missing:
```
ANDROID_RUNTIME_ROOT=/apex/com.android.runtime
ANDROID_DATA=/data
ANDROID_ROOT=/system
ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
```

**Comment by xeffyr** [comment]
Also:
* What is your SSH configuration?
* Why you have LD_LIBRARY_PATH set?

**Comment by xeffyr** [comment]
I'm closing as issue is in your setup:
1. You have missing lots of variables.
2. Connection info shows that SSH is running on port 22 when the Termux standard is 8022.
3. In PATH I see appended `sbin:/sbin/su:/su/bin:/su/xbin:/system/bin:/system/xbin` which are never configured by our OpenSSH build.

You most likely using some custom SSH server, probably supplied with your ROM or rooting tool (Magisk?). Utilities provided by third-parties are outside of Termux support and are not guaranteed to work correctly. In fact, they often missing important patches and generally out-of-sync with the recent Android OS versions.

**Comment by damionx7** [comment]
i was using magisk ssh module for this.  i found the issue https://github.com/termux/termux-app/issues/77#issuecomment-340069834

**Comment by xeffyr** [comment]
As I wrote, third party tools are not guaranteed to work.

Use Termux `openssh` package instead.
