### ISSUE TITLE
apt update command error

### ISSUE THREAD

**Issue by Adrien999** [termux/termux-app#1632]
The repository 'https://termux.org/packages stable Release' does no longer have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?)

Help.

**Comment by xeffyr** [comment]
This really was not an issue... You had just wait 5-20 minutes once you encountered it.

**Comment by xeffyr** [comment]
Btw, ensure that URL has slash at the end.
```
deb https://termux.org/packages/ stable main
```
I.e. `packages/` but not `packages`.

Do not edit sources.list files unless you don't know what its content mean.
