### ISSUE TITLE
Termux doesn't respect "show virtual keyboard" setting

### ISSUE THREAD

**Issue by jaykru** [termux/termux-app#1634]
**Problem description**
Termux doesn't respect the "Show virtual keyboard: Keep it on screen while physical keyboard is active" system setting. On my device, modifier keys are controlled by the soft keyboard meaning that many special characters are unavailable rending Termux nearly useless. 

**Additional information**
* Termux application version: 
* Android OS version: 10
* Device model: Unihertz Titan

**Comment by xeffyr** [comment]
> Termux doesn't respect the "Show virtual keyboard: Keep it on screen while physical keyboard is active"

What means "doesn't respect" ?
* Is it not being shown at all?
* Or just it can be hidden by pressing button "back" or other keyboard toggles? (that's expected behaviour btw, not Termux but Android)

**Comment by jaykru** [comment]
The virtual keyboard is not shown at all. On my device this breaks functionality totally because the special keys are accessed via a virtual keyboard overlay.

**Comment by xeffyr** [comment]
Have you tried to press "keyboard" button on the drawer?

**Comment by brianclemens** [comment]
I also have this issue (same phone). The software keyboard part of the Titan is "Kika Keyboard", which shows symbols or special keys and whatnot depending on the context. The overlay flashes on the screen for a fraction of a second and then disappears. If I press the "keyboard" button in the drawer a few times I can get the overlay to flash on the screen for a moment again, but that's it.

**Comment by agnostic-apollo** [comment]
Can you guys check if 4d1851e6 solves the issue. The debug build apk is available [here](https://github.com/termux/termux-app/actions/runs/821865196). Note that you won't be able to install the apk if you are using F-Droid or Play Store builds. Check https://github.com/termux/termux-app#installation. If you can't reinstall, then wait for new update to be pushed to F-Droid. Thanks.

**Comment by twaik** [comment]
Is this still relevant?
