### ISSUE TITLE
'DRAWER' extra key not working

### ISSUE THREAD

**Issue by scrouthtv** [termux/termux-app#1635]
**Problem description**
I tried adding an extra key to open the drawer according to https://wiki.termux.com/wiki/Touch_Keyboard#Supported_keys.
Now my termux.properties looks as follows:
```
shortcut.create-session = ctrl + t
shortcut.next-session = ctrl + m
shortcut.previous-session = ctrl + n

back-key = escape

extra-keys = [ ['ESC', 'DRAWER', 'CTRL', 'ALT', 'FN', 'LEFT', 'DOWN', 'UP', 'RIGHT'] ]
```
After `termux-reload-settings`, the extra row looks as follows: 
![image](https://user-images.githubusercontent.com/23227405/86895776-441d7580-c105-11ea-9978-631dcc0f1593.png)

And if I press the button it simply inserts the text DRAWER into the command line:
![image](https://user-images.githubusercontent.com/23227405/86895904-729b5080-c105-11ea-85aa-33f9a60b91ba.png)

**Steps to reproduce**
Add an `DRAWER` extra key to your extra key row and `termux-reload-settings`. Try pressing the `DRAWER` key.

**Expected behavior**
The app drawer opens.

**Additional information**

* Termux application version: FDroid Version 0.94
* Android OS version: Android 10 aarch64
* Device model: OnePlus 5T A5010 (Qualcomm MSM8988)

**Comment by Grimler91** [comment]
The DRAWER functionality was added in [v0.95](https://github.com/termux/termux-app/releases/tag/v0.95), upgrade your termux app and it should work

**Comment by scrouthtv** [comment]
Why don't I get this update on FDroid?

**Comment by scrouthtv** [comment]
Yeah forgot to refresh...

**Comment by SDRausty** [comment]
Thank you for adding the DRAWER option;   This is a real convenience on beveled smartscreens 🎵 🎶
