### ISSUE TITLE
Could not resolve host: termux.org

### ISSUE THREAD

**Issue by abhishekchauhan-dev** [termux/termux-app#1637]
![IMG_20200710_120217](https://user-images.githubusercontent.com/66209860/87124935-4586a380-c2a7-11ea-8ba2-7cfccd353a98.jpg)
![IMG_20200710_120217](https://user-images.githubusercontent.com/66209860/87124956-4f100b80-c2a7-11ea-8ba7-4ea816b01b27.jpg)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by xeffyr** [comment]
Problem is on your side.

**Comment by Grimler91** [comment]
You can try switching the main repository to another mirror by running `termux-change-repo`.

**Comment by abhishekchauhan-dev** [comment]
I will try

**Comment by abhishekchauhan-dev** [comment]
Thanks buddy
