### ISSUE TITLE
Issue #61 [Solved] Add better support for root

### ISSUE THREAD

**Issue by st42** [termux/termux-app#164]
I started using Termux a couple weeks ago that I downloaded from F-Droid. I have been using it ever since. I noticed that root use was a problem so I searched online and came across #61  and decided to solve the problem.

I add a comment to the original issue but as old as it was I didn't know if it would get noticed.

My solution to this issue is at my github https://github.com/st42/termux-sudo.git

Here is the README.md
# termux-sudo

A bash script that provides sudo for Termux  
Termux is a terminal emulator and Linux environment for Android

**Requirements**

Rooted phone with su binary  
SUDO WILL NOT WORK WITHOUT SU

**Installing sudo**
1. Download sudo to phone and extract
2. Open Termux and change to extraction directory
3. Execute the following commands to place sudo into the correct directory with the proper permissions and ownership

```
cat sudo > /data/data/com.termux/files/usr/bin/sudo
chmod 700 /data/data/com.termux/files/usr/bin/sudo
```

**Features**
- Sets up its environment automatically on first run, no need to do anything but use it
- Creates a root folder `.suroot` in the Termux home folder with proper root permissions and ownership
- Creates `.bashrc` file in root folder with proper PATH and LD_LIBRARY_PATH variables set so all binaries function correctly
- Bash prompt PS1 variable is also set so you don't have `bash-4.4#` as prompt just `#`
- Automatically creates `.bash_history` in root folder when you drop to a root shell so root shell history is preserved
- Can be used like ordinary sudo (but only as root, no other user)
- Can drop to root shell `sudo su [-]`
- Runs built in Termux binaries and exteral binaries with optional arguments as root in current directory
- Generates output in shell currently using
- Can be used in other bash scripts
- [option] Can turn off colored error messages be editing the variable `colored` at the beginning of sudo file

```
Usage:

sudo su [-]  
  Drop to root shell

sudo <command> [<args>]  
  Run command as root with optional arguments
```

**This was inspired by the following:**

https://github.com/cswl/tsu  
https://gist.github.com/cswl/cd13971e644dc5ced7b2

**Comment by machchhindra** [comment]
It's working only rooted mobile...

I wanna this trick non rooded mobile...plz give me help

**Comment by igormorgado** [comment]
@machchhindra how can you be a unix user and not read this:

Rooted phone with su binary
SUDO WILL NOT WORK WITHOUT SU

All CAPS belong to us.

**Comment by Seliniux777** [comment]
`su executable not found`
`sudo requires su`
help me

**Comment by st42** [comment]
@Seliniux777 
As stated in the requirements your phone must be rooted for termux-sudo to work. If it is rooted, your su binary is in a non-standard location. Locate the su binary and I can help you.

**Comment by Shreyansh-Nayak** [comment]
I  have a problem , when I run the command "cat sudo > /data/data/com.termux/files/usr/bin/sudo" it says no such file or directory but when I checked the file exists and has correct permissions.

**Comment by st42** [comment]
@Shreyansh-Nayak 

I have moved termux-sudo to gitlab.

https://gitlab.com/st42/termux-sudo

Please address all future questions there

**Comment by ZAFFER-MEHDI** [comment]
# su executable not found
sudo requires su

**Comment by Amuthasurabi95** [comment]
Am getting this error-> su executable not found
sudo requires su 
And I tried this-> pkg install su and I'm getting this error-> E: Unable to locate package su
Kindly help me

**Comment by rafikp** [comment]
su (short for substitute or switch user) command allows you to run commands
with another user's privileges, by default the root user.

**Comment by xeffyr** [comment]
@Amuthasurabi95 `sudo` requires device to be rooted.
