### ISSUE TITLE
how to install python-dev in termux

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-app#1640]
i remember long time ago, it could install python-dev in termux. odd thing.

$ pkg install python-dev
Hit:1 https://its-pointless.github.io/files/24 termux InRelease
Ign:3 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:4 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:2 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Hit:8 https://dl.bintray.com/grimler/science-packages-24 science Release
Get:5 https://dl.bintray.com/termux/termux-packages-24 stable Release [8255 B]
Hit:5 https://dl.bintray.com/termux/termux-packages-24 stable Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
91 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python

E: Package 'python-dev' has no installation candidate

**Comment by Grimler91** [comment]
`python-dev` is now part of python, we stopped splitting packages into -dev packages half a year (or one year?) ago. So, installing the main package also gives you the -dev files
