### ISSUE TITLE
Entered word repeats if space or any special key is pressed.(Samsung Galaxy j2(pro).

### ISSUE THREAD

**Issue by Rashik4567** [termux/termux-app#1642]
**Problem description**
 If a word enters like (PKG) then any special key is pressed like (space) it prints (PKGPKG). But if you cut the last PKG then again press Space it won't repeat.

**Steps to reproduce**

**Expected behavior**
It will only print that I have entered.

**Additional information**

* Termux application version:0.83
* Android OS version:6.0.1
* Device model:sm-j210f

**Comment by xeffyr** [comment]
Related to https://github.com/termux/termux-app/issues/686. Though this issue is different, its origin is same.

> Android OS version:6.0.1

Termux on Android 6 is not eligible for receiving updates. We have dropped support for old Android versions (5.x - 6.x) 01.01.2020.
