### ISSUE TITLE
crond service  could not start

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-app#1645]
i run pkg update and pkg upgrade today, bad things come out, could not run crond, i could run  crond start  before update and upgrade.
What's wrong? Could you help to fix it ? Thanks.

$ crond start
The program crond is not installed. Install it by executing:
 pkg install cronie
$ pkg install cronie
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  cronie
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/48.3 kB of archives.
After this operation, 258 kB of additional disk space will be used.
(Reading database ... 48747 files and directories currently installed.)
Preparing to unpack .../cronie_1.5.5-5_aarch64.deb ...
Unpacking cronie (1.5.5-5) ...
dpkg: warning: symbolic link '/data/data/com.termux/files/usr/var/service/crond/log/run' size has changed from 66 to 62
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/cronie_1.5.5-5_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/var/service/crond/log/run', which is also in package busybox 1.31.1-11
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/cronie_1.5.5-5_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
$

**Comment by xeffyr** [comment]
```
pkg upgrade
pkg install cronie
```

Partial updates are not supported by Termux. Proper package installation without `pkg upgrade` using before is not guaranteed to.
