### ISSUE TITLE
Unable to install on armhf android 9

### ISSUE THREAD

**Issue by Merith-TK** [termux/termux-app#1647]
**Problem description**
When i try and isntall via Playstore or Fdroid, or even building from source, i am unable to install. android studio states this when i build and "run"
```
07/13 11:20:15: Launching 'app-app' on samsung SM-J337R4.
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_SHARED_USER_INCOMPATIBLE

List of apks:
[0] 'D:\_Workspace\Termux\app\app\build\outputs\apk\debug\app-debug.apk'
Installation failed due to: 'null'
```

PlayStore and FDroid tell me an "unknown error has occured"

**Steps to reproduce**
Just try and install on an android 9 device that does not have an armv8/arm64 cpu
**Expected behavior**
the ability to install the app
**Additional information**

* Termux application version: [Master](https://github.com/termux/termux-app/commit/0910844896475418dc28ebfd2d3bae43528d5b26)
* Android OS version: 9
* Device model: j337r4

**Comment by xeffyr** [comment]
> INSTALL_FAILED_SHARED_USER_INCOMPATIBLE

Error points on already installed add-on or application installed with a different signature.

All applications, whenever that is Termux app, add-on, their updates as well as previous version, **all must be signed with same key**.

**Comment by Merith-TK** [comment]
ah, had an custom build of the api installed, thanks for pointing that out
—Merith
