### ISSUE TITLE
CANNOT LINK EXECUTABLE  for R after install gcc-9

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-app#1648]
after install libgomp-9 gcc-9  could not run R.  Where is wrong? when  uninstall   libgomp-9 gcc-9  could run R.

$ R
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/R/bin/exec/R": invalid ELF file "/data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/9.3.0/libm.so" load segment[4]: p_offset (0x5000) + p_filesz (0x0) ( = 0x5000) past end of file (0x4540)

$ R

R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: aarch64-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

**Comment by its-pointless** [comment]
odd how it does that. 
mv /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/9.3.0/libm.so /data/data/com.termux/files/usr/lib/gcc/aarch64-linux-android/9.3.0/libm.so.ndk 
should fix

**Comment by its-pointless** [comment]
okay the issue is in /data/data/com.termux/files/usr/lib/R/etc/ldpaths 
fixed and uploaded
