### ISSUE TITLE
App Request {DISCORD}

### ISSUE THREAD

**Issue by SamarJi** [termux/termux-app#1650]
Official site :- https://discord.com

Link to .deb :- https://discordapp.com/api/download%3Fplatform%3Dlinux%26format%3Ddeb&ved=2ahUKEwiHsI6jpszqAhUBXSsKHd0bBpwQFjAKegQIBhAB&usg=AOvVaw0V_Sx6dLeNYyjzEc66xKJY&cshid=1594714574135

-----------------------------------------------------------------

Hi termux team , can you add discord im termux, already discord app is available
for android, but it doesn't give many required features. If it is possible to add discord for termux, try.

Your sincerely user,
Samar

**Comment by xeffyr** [comment]
We do not package nodejs stuff requiring lots of modules.

> Link to .deb :-

Link to pre-compiled deb is useless:
* We do not accept pre-compiled binaries.
* Binaries compiled for the GNU/Linux systems are not working in Termux properly or do not work at all.
