### ISSUE TITLE
please add hot key to create new Termux session

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-app#1651]
Dear specialists,
Because I do not see at all, I can not access create new Termux session by using Explore by touch Android feature. How complex would be to extend yours code, so new Termux session could be started after pressing CTRL+SHIFT+n keys? Or it is too comple xto monitor hot keys when Termux window is active?

If I have understood Termux well, it is possible to run Multiple sessions at The same time. And user can for example run one console app in one session and other Termuc compatible app in second session. I Am even dreaming about running several Linux distros at The same time when using Proot app. Sure I know, that I must have The common sense and that I can not too many various Linux distros at The same time. But two with only console based apps not X11 could be OK.

Thank you very much for yours time and for yours understanding my plea.
With The warmest regards and with The deepest appreciation.
Janusz Chmiel

**Comment by hazho** [comment]
yes, this is very important

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Hardware_Keyboard (CTRL + ALT + C).

**Comment by JanuszChmiel** [comment]
Thank you very much for yours answer and for yours advice.
