### ISSUE TITLE
JDK

### ISSUE THREAD

**Issue by guozhenduo** [termux/termux-app#1652]
Termux app(v0.95)how to install JDK?Or how to install openjdk9? 
ecj and dx are very complicated to compile.

**Comment by xeffyr** [comment]
OpenJDK is not supported officially.

**Comment by guozhenduo** [comment]
I know.

**Comment by SDRausty** [comment]
@guozhenduo `ecj` and `dx` can easily be installed and employed with [buildAPKs](https://buildapks.github.io/buildAPKs/) which builds unlimited apps in native Termux, including native APKs built on device and for the device's architecture it is built in.

> ecj and dx are very complicated to compile.

No they are not.  Not anymore at least, building packages is completely automated in Arch Linux in Termux PRoot as of this month:
```
[user11:24~]$ yay dx
174 aur/android-sdk-build-tools-18.1.1 r18.1.1-2 (+0 0.00)
Build-Tools for Google Android SDK (aapt, aidl, dexdump, dx, llvm-rs-cc)...             
```                                                                                     
```
[user11:30~]$ yay ecj
6 aur/gcc6-gcj-ecj 4.9-1 (+1 0.00)
A fork of the Eclipse Java bytecode compiler for GCJ...                                 
```                                                                                     
```                                                                                     
[user11:41~]$ yay openjdk                                                               
94 aur/zulu-10-bin 10.0.2-2 (+0 0.00) (Orphaned)                                        
Zulu is a certified build of OpenJDK that is fully compliant with the Java SE standard...
```
I am not sure if these are the results you are looking for for a couple of reasons.  Please let me know if they are.                                                              The good news is that many of the aur packages do compile on device easily as far as I can tell.        

What used to be a long series of commands to attempt to build a package has as of this month become
 a one tap affair with [Arch Linux in Termux PRoot](https://termuxarch.github.io/TermuxArch/).  Enjoy!

**Comment by guozhenduo** [comment]
I 'm install Ubuntu in termux,and I try install openjdk,as a result, openjdk was too big:528MB......

**Comment by guozhenduo** [comment]
And then I wrote a Makefile, like this:
Hello.dex: Hello.class
	dx --dex --output=Hello.dex Hello.class
Hello.class: Hello.java 
	ecj Hello.java
