### ISSUE TITLE
crond start   fail

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-app#1653]
i reinstall termux again to fix crond. the version is 0.95.  crond still could not use.

$ crond start
crond: can't lock /data/data/com.termux/files/usr/var/run/crond.pid, otherpid may be 26285: Try again
$

**Comment by xeffyr** [comment]
You have crond already running. If not, rm the file /data/data/com.termux/files/usr/var/run/crond.pid.

Consider to use `termux-services` for daemon management. https://wiki.termux.com/wiki/Termux-services
