### ISSUE TITLE
Extra-keys are not being added

### ISSUE THREAD

**Issue by saihum** [termux/termux-app#1654]
![IMG_20200716_105102](https://user-images.githubusercontent.com/54665629/87630110-2f209200-c756-11ea-835f-5c54cddb8cb7.jpg)
I tried to add extra keys by this method in wikitermux
![IMG_20200716_112251](https://user-images.githubusercontent.com/54665629/87630344-ba9a2300-c756-11ea-830e-b6e08a6a6e3f.jpg)
As I've installed metasploit I don't really wanna clear all the data.. Is there any other way?

**Comment by Grimler91** [comment]
What have you put in ~/.termux/termux.properties?

**Comment by saihum** [comment]
> What have you put in ~/.termux/termux.properties?

Exactly this
extra-keys = [['ESC','HOME','-','END','/','UP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT']]

**Comment by Grimler91** [comment]
The error indicates that you have an extra comma after 'UP' or 'RIGHT', but what you pasted now works. Are you sure that you have exactly that in ~/.termux/termux.properties?

**Comment by saihum** [comment]
> The error indicates that you have an extra comma after 'UP' or 'RIGHT', but what you pasted now works. Are you sure that you have exactly that in ~/.termux/termux.properties?

Sorry my bad.. It worked... Thank you
