### ISSUE TITLE
CURL error

### ISSUE THREAD

**Issue by sandhya019** [termux/termux-app#1655]
hi 
i am facing issue with curl command

curl -u admin:Sujoydey@03 -X GET "http://localhost:8081/service/rest/v1/search/assets?group=$group_name&name=$name_oftheproj&version=$Release_Version&maven.extension=$extension" --output sujoy.jar

curl: (3) URL using bad/illegal format or missing URL
Build step 'Execute shell' marked build as failure

**Comment by Grimler91** [comment]
Clearly you have done some mistake when building the URL, hard to tell what when you only show part of whatever script you are using.

I can't see that there is any problem with curl so closing this. Read the [curl docs](https://curl.haxx.se/docs/httpscripting.html).
