### ISSUE TITLE
TCP Port Not Forwarding

### ISSUE THREAD

**Issue by Pdune** [termux/termux-app#1657]
![Screenshot_20200717-100655.png](https://user-images.githubusercontent.com/68368008/87770365-3eb7dd80-c81f-11ea-9467-2398eecf6d42.png)
I've tried many Port numbers i don't know what to do now😔

**Comment by Grimler91** [comment]
Serveo has been offline for like a year due to phishing, will probably never work again

**Comment by Grimler91** [comment]
See https://wiki.termux.com/wiki/Bypassing_NAT for other ways to access termux

**Comment by Pdune** [comment]
> Serveo has been offline for like a year due to phishing, will probably never work again

Wow really😐!?

**Comment by Pdune** [comment]
> See https://wiki.termux.com/wiki/Bypassing_NAT for other ways to access termux

Thank you very much🙏

**Comment by xeffyr** [comment]
> Serveo has been offline for like a year due to phishing, will probably never work again

It was back recently, yet still unstable.

![Снимок экрана от 2020-07-17 12-59-30](https://user-images.githubusercontent.com/25881154/87774623-74fc5980-c82d-11ea-878b-7b4d8a67b0dd.png)

***

Error in https://github.com/termux/termux-app/issues/1657#issue-659060447 shows that server is not running on localhost. Standalone port forwarding is useless, local server is needed.
