### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by saihum** [termux/termux-app#1658]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:latest
* Android OS version: 9.. MIUI 11
* Device model:REDMI 6A
I tried to install two programs ..those are tool-x and Ip-trace by Rajkumar dusad.. programs are successfully installed but when I try to use those tools.. I come across this error

@localhost ~> trace -m
Failed to execute process '/data/data/com.termux/files/usr/bin/trace'. Reason:
exec: Exec format error
The file '/data/data/com.termux/files/usr/bin/trace' is marked as an executable but could not be run by the operating system.
Screenshot
![IMG_20200718_144024](https://user-images.githubusercontent.com/54665629/87848724-ab58d800-c904-11ea-8851-d5ee1f4a11e7.jpg)
I think that it's termux's error

**Comment by xeffyr** [comment]
You can't exec binaries if its architecture does not match one of your CPU.
