### ISSUE TITLE
No command tcpsvd found

### ISSUE THREAD

**Issue by egeres** [termux/termux-app#1659]
**Problem description**

I'm trying to upload files to termux by creating a FTP server. I'm launching this server with :

```
tcpsvd -vE 0.0.0.0 1024 ftpd -w ~
```
But it displays the message:

```
No command tcpsvd found, did you mean:
  Command cupsd in package cups
  Command pcscd in package pcscd
  Command tclsh in package tcl
  Command tcsh in package tcsh
```

Following [this](https://wiki.termux.com/wiki/Remote_Access) guide hasn't helped so far.

**Steps to reproduce**

Execute that command.

**Expected behavior**

The ftp server should be launched and be accessible.

**Additional information**

* Termux application version: 0.95
* Android OS version: 8.1.0
* Device model: MI PAD 4 PLUS

**Comment by xeffyr** [comment]
> Following this guide hasn't helped so far.

This guide is subject for change. When you have read it last time? It was rewritten and no longer uses any "tcpsvd"

Use `termux-services` as shown in guide, otherwise use:
```
pkg install busybox
busybox tcpsvd ...
```

Busybox applets are deprecated and removed from Termux installation. This is not a bug.

**Comment by egeres** [comment]
Oh, my bad, thank you !!
