### ISSUE TITLE
How to repair/uninstall/delete  Brainf#ck-psiphon pro go on Termux

### ISSUE THREAD

**Issue by Pdune** [termux/termux-app#1660]
Problem description
<!--
I was installing Brainf#ck-psi-phon-pro-go which i successfully did and i ran it. ![Screenshot_20200718-145239.png](https://user-images.githubusercontent.com/68368008/87854683-d4349980-c913-11ea-84e5-24670955f6e1.png) 
Now I'm trying to run it again, it gives me this-![IMG-20200718-WA0173.jpg](https://user-images.githubusercontent.com/68368008/87854451-6cca1a00-c912-11ea-907b-b2de0a374eef.jpg)

**Steps to reproduce**
<!--
$ cd ~/go/src/github.com/aztecrabbit/  brainfuck-psiphon-pro-go

$ ./brainfuck-psiphon-pro-go

**Additional information**

* Termux application version:0.95
* Android OS version:8.10
* Device model:Tecno CF7
How can I repair this problem?
Do I have to uninstall and install brainf#ck again? If so, who do I uninstall it?

**Comment by xeffyr** [comment]
Third-party software is not under official Termux support. Report issues to the original author of "Brainf#ck-psiphon pro go".
