### ISSUE TITLE
Please help on repairing Brainf#ck-psiphon-pro-go

### ISSUE THREAD

**Issue by Pdune** [termux/termux-app#1661]
I installed Brainf#ck and ran it and it had no problems-![IMG-20200718-WA0118.jpg](https://user-images.githubusercontent.com/68368008/87855002-d7308980-c915-11ea-8f8a-cfbeb43f3546.jpg)

Then i closed it..im not sure if i closed it properly then i reopend it again then this showed-![IMG-20200718-WA0173.jpg](https://user-images.githubusercontent.com/68368008/87854888-34780b00-c915-11ea-9c3e-8b22be176673.jpg)
Even when i exit Termux and  open ot again and when i try to run Brainf#ck it does not run like the first time...
I need help repairing Brainf#ck or uninstalling so that i can install it again properly...😔🙏

**Comment by Grimler91** [comment]
Looks like a python program so I guess you installed it through pip. It is not a termux program so it has nothing to do with us and we don't know how to "repair" it. Open an issue in the Brainfuck Psiphon Pro Go repo https://github.com/aztecrabbit/brainfuck-psiphon-pro-go
