### ISSUE TITLE
Clang Static Compilation And armv7 compiler

### ISSUE THREAD

**Issue by shemanshu1511** [termux/termux-app#1662]
I wanna compile Static executable with -static flag
But getting this error from clang-9 today i  updated to 10.0
and It's still not fixed

Errors :-

$ clang++ hello.cpp -static
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: cannot find -lc++_shared
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: cannot find -lm
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: cannot find -lc
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)

it says it cannot find libc++_shared.so and some other libs but when i checked the $PREFIX/libs it was there could someone please help me on this
and i couldnt find the libc.so in the lib directory

And Request :-
Add -m32 -m64 like multilibs

Thanks in advance :)

**Comment by xeffyr** [comment]
Static compilation is not supported as we use libs from /system/lib(64). It is not recommended anyway as libc.a is API level specific and is not portable.

> Add -m32 -m64 like multilibs

`pkg install ndk-multilib`
