### ISSUE TITLE
Curl duplicate progress data (metr and bar) in loop

### ISSUE THREAD

**Issue by Yusifx1** [termux/termux-app#1665]
**Problem description**
When writing any Curl command like this `curl -# -A "some_user_agent" url >>name` in loop it will dupe in vertical phone mode. Pictures: with [progress-bar](https://i.stack.imgur.com/hIQbu.jpg) and [standard](https://i.stack.imgur.com/ZmmkG.jpg). 
In hotizontal mode it work as expected. [Horizontal mode after vertical mode](https://user-images.githubusercontent.com/63213937/88056882-51f5e080-cb72-11ea-8caf-0179cd1afd0b.jpg)

**Steps to reproduce**
Just download or get file with curl in vertical mode with `while read url`. Example:
```
count=1
 while read url
do 
e=$(if [[ $url =~ ^.*[.](gif|jpg|png|webm) ]] ;then echo "${url##*.}"; fi)
curl -# --create-dirs -o "$name/${count}.$e" -C - $url
count=$((count+1))
done <url.pictures.txt
```

**Expected behavior**
It should be normal like in horizontal mode

**Additional information**

* Termux application version: 0.90-0.95 from play market
* Android OS version: 10,9 and 7
* Device model:honor 10 lite with android 10 and 9, samsung j5 with custom android 7 and more

**Comment by Grimler91** [comment]
Hi, thanks for the report. This type of issue happens for curl (and other programs) when the terminal width is smaller than some value, it is not termux specific. 

I think patching curl to handle small screens better is out of our scope, I would suggest opening an issue in the [curl repo](https://github.com/curl/curl) and request better support for small terminals.

**Comment by xeffyr** [comment]
This affects all utilities displaying progress bar or other interactive elements, e.g. `pip`. These utilities expect that terminal width is 80 columns as minimum which is reasonable for standard system configurations.
