### ISSUE TITLE
Permission request [CAMERA]

### ISSUE THREAD

**Issue by SamarJi** [termux/termux-app#1666]
Hi, i am using windows 10 in qemu inside termux, i wanna add face lock in it. I am using ubuntu 20 proot and installed a webcam and a camera application, but they both won't worked because there is no camera permission permission for termux expect storage.

**Comment by xeffyr** [comment]
> i am using windows 10 in qemu inside termux, i wanna add face lock in it.

No, you won't be able to use camera in qemu. Even if Termux will have necessary permission, it won't work. QEMU needs a direct access to hardware in this case, however there are few issues:
* No virtualization. KVM is not supported and I even won't bother to enable it -in modern devices hypervisor is locked by ARM TrustZone.
* Its unlikely that Windows and other OS has a proprietary driver for camera used on mobile device. Even if such exists and compatible with your device, it's very unlikely that it freely downloadable from the Internet.

Note that Termux:API has camera permission. If it is enabled, then Termux app will have that permission too.

**Comment by SamarJi** [comment]
Thanks for help, i think with termux api, i can run webcam on proot
