### ISSUE TITLE
Postgresql package gives an error in initdb command 

### ISSUE THREAD

**Issue by IgnisDa** [termux/termux-app#1668]
**Problem description**
The postgresql package does not work

**Steps to reproduce**
```
pkg install postgresql
mkdir -p $PREFIX/var/lib/postgresql
initdb $PREFIX/var/lib/postgresql
```

**Expected behavior**
The database is should have been created but instead gives this error

```
CANNOT LINK EXECUTABLE DEPENDENCIES: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit
no data was returned by command ""/data/data/com.termux/files/usr/bin/postgres" -V"
The program "postgres" is needed by initdb but was not found in the
same directory as "/data/data/com.termux/files/usr/bin/initdb".
Check your installation.
```

**Additional information**

* Termux application version: Latest
* Android OS version:
* Device model: Fire HD 8 (Generation 6)

**Comment by Grimler91** [comment]
What is your output of `termux-info`?

`unset LD_PRELOAD` will prevent loading libtermux-exec, but this should not be necesssry

**Comment by IgnisDa** [comment]
`set -u LD_PRELOAD` did work for me, thank you so much! Do you still need the output from `termux-info`?

**Comment by Grimler91** [comment]
Yes please, since this doesn't solve the problem, only work around it. 

Note that without libtermux-exec preloaded you cannot run scripts with shebangs like `#!/usr/bin/bash`, they have to point to our prefix `#!/data/data/com.termux/files/usr/bin/bash`.

**Comment by IgnisDa** [comment]
`Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-21 root stable
Updatable packages:
All packages up to date
Android version:
5.1.1
Kernel build information:
Linux localhost 3.18.19-g4f38db79049 #1 SMP PREEMPT Thu Dec 12 05:39:15 UTC 2019 armv8l Android
Device manufacturer:
Amazon
Device model:
KFGIWI`

I don't use scripts in termux, so that won't be an issue.

**Comment by Grimler91** [comment]
Thanks! I see that you are on android 5, and those packages are not updated anymore so we will not fix this. The issue only probably happens for this particular tablet, good that the workaround works for you!
