### ISSUE TITLE
support

### ISSUE THREAD

**Issue by guozhenduo** [termux/termux-app#1669]
What language does termux support? Also, when can the version of Python downloaded by termux be 3.9.x?

**Comment by Grimler91** [comment]
> What language does termux support

Programming languages? We support all languages [we have packages for](https://github.com/termux/termux-packages/tree/master/packages). This includes: c, c++, python, golang, rust, lua, perl and many others.

> Also, when can the version of Python downloaded by termux be 3.9.x?

Python 3.9 is scheduled to be released in October. Once it has been released some volunteer also needs to update patches and spend some time getting it working, so, termux will get python 3.9 in October or later.
