### ISSUE TITLE
Need help with using 'settings' command

### ISSUE THREAD

**Issue by tinboyko** [termux/termux-app#1671]
Hi, I want to build web interface for mobile for my personal use as router. For this purpose I using web servers on termux. So I need read and write sytem settings. e,g ```settings get global airplane_mode_radios```. Main goal that Node could exec this command. I can get results by using ```su -c "...."``` in termux terminal. But I getting error when I trying to exec it via node. Then when I using directly command ```settings get``` I getting error about missing permission ```android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY```. I'm newbie in android dev and I wonder how I could add this permissions in custom build? I tried with ```<uses-permission android:name="android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY" />``` but when I granting this permission via ```pm grant``` getting error ``` is not a changeable permission type```

any help would be appreciated, thanks

**Comment by twaik** [comment]
`android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY` is a system permission. It can not be granted to regular apps. So you can use `settings` command only with `su`/`tsu`/`sudo`.
