### ISSUE TITLE
[Bug] Termux renders some fonts above normal height

### ISSUE THREAD

**Issue by Morpheus2077** [termux/termux-app#1674]
![Screenshot_20200727-062755~2](https://user-images.githubusercontent.com/57775700/88526742-b251ab80-cfd2-11ea-8a25-3c549082c558.png)

Termux did not correct the height of the fonts, and is it possible to implement a correction?

Font used: Code New Roman

**Comment by agnostic-apollo** [comment]
[Pinch and zoom](https://upload.wikimedia.org/wikipedia/commons/c/cc/Pinch_zoom.png) can be used to change font size.

**Comment by Morpheus2077** [comment]
> [Pinch and zoom](https://upload.wikimedia.org/wikipedia/commons/c/cc/Pinch_zoom.png) can be used to change font size.

I tried to do that before

**Comment by Morpheus2077** [comment]
I did a small example with a random app

![termux_font_rendering](https://user-images.githubusercontent.com/57775700/117589897-eb42b300-b102-11eb-96b3-68aabb1ae8c7.png)

**Comment by Morpheus2077** [comment]
So same it happens to Letter Gothic, Code New Roman, Andale Mono, etc
