### ISSUE TITLE
how can i install a 32bit version termux into a 64bit android system?

### ISSUE THREAD

**Issue by mathpopo** [termux/termux-app#1675]
**Feature description**

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by xeffyr** [comment]
By manual bootstrap package unpacking.

**Comment by mathpopo** [comment]
@xeffyr   could you give me learning web?

**Comment by xeffyr** [comment]
1. Download bootstrap archive.
2. Extract it.
3. Create symlinks.
4. Switch to system environment.
5. Replace the $PREFIX.
```
cd $HOME/../
curl -LO http://dl.bintray.com/termux/bootstrap/bootstrap-arm-v25.zip

unzip -d usr32 bootstrap-arm-v25.zip

cd usr32
while read -r line; do src=$(echo "$line" | awk -F'←' '{ print $1 }'); target=$(echo "$line" | awk -F'←' '{ print $2 }'); ln -s "$src" "$target"; done < <(cat SYMLINKS.txt)
cd ..

unset LD_PRELOAD
/system/bin/sh
export PATH=/system/bin

mv usr usr64
mv usr32 usr
```
then restart Termux.

**Comment by mathpopo** [comment]
@xeffyr  below operations afrer termux.apk installed  and  run in terminal ?

**Comment by Tech-abm** [comment]
How to decompile cython so file using 32bit and 64bit on termux
