### ISSUE TITLE
64-bit instead of 32-bit

### ISSUE THREAD

**Issue by mathpopo** [termux/termux-app#1678]
https://github.com/termux/termux-app/issues/567

but :
$ ls
CMakeCache.txt	CMakeFiles  Makefile  cmake_install.cmake  face_attr
$ file ./face_attr 
./face_attr: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=d2909b25aa04ef4b4132e85571b38c088beb00b4, with debug_info, not stripped
$ ./face_attr 
CANNOT LINK EXECUTABLE "./face_attr": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
Aborted
$ unset LD_PRELOAD
$ ./face_attr 
CANNOT LINK EXECUTABLE "./face_attr": "/data/data/com.termux/files/usr/lib/libz.so.1.2.11" is 64-bit instead of 32-bit
Aborted

**Comment by xeffyr** [comment]
Why not to compile it 64bit? Termux does not support multilib environment.
