### ISSUE TITLE
Termux could not find su

### ISSUE THREAD

**Issue by Mannshoch** [termux/termux-app#168]
All other apps have no problem with su. but termux seems not be able to find su.

**Comment by fornwall** [comment]
@Mannshoch In another terminal app (where su is working), what is the output of `which su`?

**Comment by Mannshoch** [comment]
Was possible to geht su back. Had to remove all data in the APP settings (260MB). Im wondering how it grows that mich.

**Comment by tgc12** [comment]
I have the same problem. It has begun with phh's systemless superuser v259 and magisk 7.
The path for the su binary (which su) it's "/magisk/.core/bin/su", the only app that has problems with su it's Termux.

**Comment by alien2003** [comment]
The same problem with the latest Magisk and systemless phh Superuser

**Comment by tgc12** [comment]
I have found a temporal solution.
You need to edit the su script under /data/data/com.termux/files/usr/bin/su
And replace or add the path to your su binary inside the script.
It works flawlessly until the su package gets an update, you can still edit it again.

**Comment by fornwall** [comment]
@tgc12 Thanks, `/magisk/.core/bin/su` should now work with `su` after updating installed packages with

    apt update && apt upgrade
