### ISSUE TITLE
Documentation: SSH password login and rsync is possible !

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#1680]
This is not a bug at all, but the description says that the SSH daemon (when installed with apt install openssh) can accept passwords and can even easily rsync between two devices, no matter what, as long they have ssh installed.
I found this documentation:
https://glow.li/posts/run-an-ssh-server-on-your-android-with-termux/

For a new phone it is rather clunky to enter text on that tiny screen as I had. But I used the trick which I also use on datacenter servers.
Within Termux, on the tiny screen I typed 'passwd' and filled in a new password twice and started the SSH daemon (sshd).
Then on the computer in a macOS terminal (Linux terminal or Windows Powershell or Putty terminal also works) I did 
ssh-copy-id -p 8022 [wifi ip-address of cellphone]
said 'yes' to fingerprint and entered the password.
Then I did 
ssh-p 8022 [wifi ip-address of cellphone]
and was 'in'.

And using rsync (apt install rsync) between two phones, both have Termux installed) also works. A very easy way to copy videos, photos, etc. from one to another device.
Pull request from old device :
rsync --rsh='ssh -p 8022' -a -r -u -v -c -0 -n user:/storage/emulated/0/Videos/* /storage/emulated/0/Videos 
copies all videos.

* Termux application version:  Latest by July 2020
* Android OS version: 10.x
* Device model: 1+ 6

**Comment by xeffyr** [comment]
> I found this documentation:
https://glow.li/posts/run-an-ssh-server-on-your-android-with-termux/

From what time blogs became Termux documentation?
Official docs are https://wiki.termux.com/wiki/Main_Page only.

> Within Termux, on the tiny screen I typed 'passwd' and filled in a new password twice and started the SSH daemon

https://wiki.termux.com/wiki/Remote_Access#Setting_up_password_authentication

**Comment by xeffyr** [comment]
There no any reason to post "documentation" to Termux bug tracker, especially if you have not checked the official Termux informational resources.
