### ISSUE TITLE
[REQUEST] Please make side bar Dark too

### ISSUE THREAD

**Issue by RealGJ** [termux/termux-app#1681]
Termux app is dark as it should be, but side bar isn't. Please make that dark too

Screenshot:
https://photos.app.goo.gl/2A4BRu1bWjUxxdHY7

**Comment by xeffyr** [comment]
Termux uses light UI theme by default, that's why side bar is white.

Put `use-black-ui = true` to ~/.termux/termux.properties and restart application to have it black.

**Comment by trygveaa** [comment]
Or upgrade to v0.95 or newer. That uses dark UI automatically if it's enabled system wide.

**Comment by RealGJ** [comment]
@xeffyr thank you. It worked!!
