### ISSUE TITLE
Can't access external storage

### ISSUE THREAD

**Issue by superbonaci** [termux/termux-app#1683]
I run `termux-setup-storage` and waits a couple of seconds and nothing happens. I want to gain access to external microsd which I replaced yesterday. Storage permission is allowed.

* Termux application version: latest from play store
* Android OS version: 10
* Device model: Samsung Galaxy S10

**Comment by xeffyr** [comment]
> I want to gain access to external microsd which I replaced yesterday. 

Write access isn't possible.

**Comment by superbonaci** [comment]
I don't understand why other apps can gain access to external sdcard and Termux can't. Technically is possible, why not implement it?

**Comment by xeffyr** [comment]
Because Termux environment technically is not other apps. Yes, terminal emulator is Android app but command line utilities are Linux apps. CLI do not have access to Android API, they are executed directly by kernel bypassing the Android framework.

**Comment by xeffyr** [comment]
> Technically is possible, why not implement it?

Possible, bot wontfix. Why?
* Each package has to be patched: we will need to rework the I/O completely in order to redirect it through JNI to the Android API methods.
* This will require lots of work. I personally do not want to make all packages use the JNI and will not bother to maintain that.
* There will be issues and performance loss.

**Comment by superbonaci** [comment]
Ok I understand.

**Comment by superbonaci** [comment]
Ok I understand. I was trying to run some Go programs on external sd, but I see will not be possible in the near future.

**Comment by xeffyr** [comment]
Even if external sd would be writable, you won't be able to execute any programs (except scripts) from it anyway. All kinds of storage (except /system and /data) are mounted with noexec, effectively disabling program execution on them.

**Comment by superbonaci** [comment]
Ok I understand. What happens if I have LineageOS rooted with Magisk? Could I use Termux more broadly?

**Comment by xeffyr** [comment]
With root you will have at least read-write access on external sdcard. You can try to remount it with "exec" option to enable execution, not sure whether sdcardfs daemon will handle it properly.
