### ISSUE TITLE
termux-open-url issue

### ISSUE THREAD

**Issue by tihstae** [termux/termux-app#1684]
Whenever I try to use termux-open-url, I get the following error message:
                            Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=www.google.com flg=0x10000000 }

Is there a configuration file that I need to edit or something to make this work or what?  Preferably, I'd like to have Firefox open the url if at all possible.  Thanks for any help that anyone has to give to me for this issue.  😀

**Comment by xeffyr** [comment]
Use proper format of urls.
```
https://www.google.com
```
but NOT this:
```
www.google.com
```

**Comment by tihstae** [comment]
Thank you for your help.
