### ISSUE TITLE
ps start date is incorrect

### ISSUE THREAD

**Issue by 8HoLoN** [termux/termux-app#1690]
**Problem description**
The `ps` command output bad start date and hour (only the minutes, seconds seems right).

**Steps to reproduce**
type `date` : the datetime is correct
type `ps -eo lstart,cmd` : the datetime is incorrect (Thu Jan 1 02:33:34 1970) for all process

**Expected behavior**
The lstart datetime of the process (`ps command`) should output with the correct datetime and not `1970`

**Additional information**

* Termux application version: v0.95 (latest)
* Android OS version: 10
* Device model: Aquaris X2 Pro

**Comment by xeffyr** [comment]
That's due to /proc/ access restriction on the modern Android OS versions. You need to either run `ps` as root or have SELinux in permissive mode (again, root is needed).

Nothing can be done on Termux side.

**Comment by 8HoLoN** [comment]
Thank you for your explanation, I finally managed to polyfill this without being root.
