### ISSUE TITLE
Feature request: Swipe horizontally to move cursor

### ISSUE THREAD

**Issue by mobd** [termux/termux-app#1692]
**Feature description**

At the moment it's not possible to move the cursor horizontally, which means if you want to change a command at the beginning you have to delete and retype it all. I think adding a swipe gesture to move the cursor would be really useful.

**Reference implementation**
Right now scrolling in vim already moves the cursor up and down, I don't know if this would be similar codewise but having the same thing horizontally would be great.

**Comment by nikey02** [comment]
You can use arrow keys to move cursor by 
[Extra keys](https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row.28s.29) 

Or try
[flesky keyboard](https://play.google.com/store/apps/details?id=com.syntellia.fleksy.keyboard)

To move cursor slide over spacebar
But in flesky keyboard has issue sometimes backspace not works

**Comment by mobd** [comment]
Ah I guess that works. Thanks for the tip!
