### ISSUE TITLE
Does not start on Mi Mix 2s

### ISSUE THREAD

**Issue by sailerinteractive** [termux/termux-app#1698]
Since the latest update of Termux today, Termux no longer starts on my Xiaomi Mix Mix 2s running MIUI 11.0.5.0 

![IMG_20200809_172106](https://user-images.githubusercontent.com/725890/89735904-fa0e1380-da65-11ea-83ff-50e50fdcedad.jpg)

When hitting Enter the app closes.

**Comment by xeffyr** [comment]
See my answer in https://github.com/termux/termux-app/issues/1697#issuecomment-671041996.

That's a wontfix. Legacy environment (i.e. packages installed from `termux.net` or their backups) is no longer supported.
