### ISSUE TITLE
Cannot install or update packages in VMOS(com.vmos.pro) virtual machine

### ISSUE THREAD

**Issue by nukemiko** [termux/termux-app#1699]
![Screenshot_20200810_161453_com vmos pro](https://user-images.githubusercontent.com/53572814/89763541-52581a80-db25-11ea-8e12-f673db35df4b.jpg)
While I run command "pkg update", it always report error, such as:
`W: GPG error: https://dl.bintray.com/termux/termux-packages-24 stable Release: Unknown error executing apt-key`
This error only occur in the VMOS virtual machine.

**Comment by Grimler91** [comment]
This is a bug or just missing feature in the VMOS. Not really anything we can do about it.

**Comment by Ivonov1** [comment]
This version works its from apkpure you can explore more version on this website here is the link https://m.apkpure.com/termux/com.termux/download/73-APK?from=versions%2Fversion it has features missing

**Comment by xeffyr** [comment]
> it has features missing features from future version

Could you give an example of what is "missing" from the newer Termux versions?
