### ISSUE TITLE
bug: Home/End key does not move cursor in termux

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-app#170]
Android 5.0
The bash is in vi insert mode, and Home/End key does not move cursor.
Arrow keys work perfectly, and the soft keyboard (I am using com.xinshuru.inputmethod) Home/End works in other applications.

**Comment by fornwall** [comment]
@torappinfo Could you use the app https://play.google.com/store/apps/details?id=com.sonelli.keywatcher and press the Home and End keys, and paste the output here to see which key codes are sent?

Also, do you know how I myself could install the com.xinshuru.inputmethod soft keyboard?

**Comment by torappinfo** [comment]
This url should work:
https://play.google.com/store/apps/details?id=com.xinshuru.inputmethod

**Comment by torappinfo** [comment]
com.sonelli.keywatcher is for hardware keyboard only, there is nowhere to invoke soft keyboard.

**Comment by fornwall** [comment]
After testing the input method there is unfortunately currently not anything Termux can do about it - it has to be fixed on the side of the input method. Try reporting it there, with a description like

> The keyboard needs to send key events for Home and End keys (at least if the current input type is [InputType.TYPE_NULL](https://developer.android.com/reference/android/text/InputType.html#TYPE_NULL).

The reason that it works in other apps is that they use normal text views handled by the system - but a terminal is not a normal textview, and needs raw key events to function.
