### ISSUE TITLE
how to build GCC in termux ?

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-app#1700]
i had tried to build GCC 7.5.0 in termux  many times, but failed. any suggestion?

**Comment by Grimler91** [comment]
You can install it from [its-pointless repository](https://github.com/its-pointless/its-pointless.github.io) rather than building it yourself

**Comment by SDRausty** [comment]
@leechaowen gcc can be built in Arch Linux Termux PRoot by using `yay`:
```
$ yay gcc
217 aur/sh4eb-nofpu-elf-gcc 8.2.1+20181127-1 (+0 0.00) (Orphaned) (Out-of-date: 2019-06-10)
    The GNU Compiler Collection for the sh4eb-nofpu-elf target.
216 aur/mipsel-linux-gcc3 3.3.4-1 (+0 0.00) (Out-of-date: 2019-06-08)
    mipsel-linux GNU (cross) Compiler Collection
.
.
.
3 core/gcc-fortran 9.3.0-1 (6.4 MiB 20.5 MiB)
    Fortran front-end for GCC
2 core/gcc-d 9.3.0-1 (10.6 MiB 64.4 MiB)
    D frontend for GCC
1 core/gcc 9.3.0-1 (24.6 MiB 102.2 MiB) [base-devel] (Installed)
    The GNU Compiler Collection - C and C++ frontends
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
```
There are 217 gcc builds to choose from.  206 of them want to be **built on device**.

**Comment by leechaowen** [comment]
> You can install it from [its-pointless repository](https://github.com/its-pointless/its-pointless.github.io) rather than building it yourself

Thanks your support. but the  its-pointless.github.io connection refused, the service is not stable.
$ pkg update
Err:1 https://its-pointless.github.io/files/24 termux InRelease
  Failed to connect to its-pointless.github.io port 443: Connection refused

**Comment by xeffyr** [comment]
> but the its-pointless.github.io connection refused, the service is not stable.

Interesting, it is hosted on Github and it seems Github is not blocked for you, if you can write messages here.

You can try to download files manually, by browsing https://github.com/its-pointless/its-pointless.github.io/tree/master/files/24/dists/termux.
