### ISSUE TITLE
Can't start termux shell after app update

### ISSUE THREAD

**Issue by target111** [termux/termux-app#1701]
**Problem description**
I just updated the termux app and noticed that I can't open a shell. Each time it gives back those errors:
```
CANNOT LINK EXECUTABLE "cat": library "libandroid-support.so" not found
CANNOT LINK EXECUTABLE "realpath": library "libandroid-support.so" not found
/data/data/com.termux/files/usr/bin/login: 27: exec: : Permission denied

[Process completed (code 126) - press Enter]
```

**Steps to reproduce**
Update to latest version and open app

**Expected behavior**
Get a shell prompt without any errors

**Additional information**

* Termux application version: 0.98
* Android OS version: 10
* Device model: OnePlus 6

**Comment by xeffyr** [comment]
See my answer at https://github.com/termux/termux-app/issues/1697#issuecomment-671039503 and https://github.com/termux/termux-app/issues/1697#issuecomment-671041996.

You need to clear app data.
