### ISSUE TITLE
After update to 0.96 shell does not start, CANNOT LINK EXECUTABLE "libandroid-support.so" not found

### ISSUE THREAD

**Issue by galets** [termux/termux-app#1702]
Termux has been auto-updated by google play, and now it will not start:

![screenshot-termux](https://user-images.githubusercontent.com/2415755/89799889-e654c280-dae2-11ea-858f-24c85b281640.png)

Device info:
![device-info](https://user-images.githubusercontent.com/2415755/89800007-0be1cc00-dae3-11ea-8beb-81210c5142dd.png)

I am aware of solution #1307 where it is suggested to blow the `$PREFIX` directory, but there has to be a better way. Upgrades often happen unattended and there's typically an expectation that one should not completely break the environment

**Comment by xeffyr** [comment]
>  but there has to be a better way

`termux-upgrade-repo`, if you haven't mixed Android 5 and Android 7+ packages - in this case only `rm -rf` will be a solution.

**Comment by xeffyr** [comment]
> Upgrades often happen unattended and there's typically an expectation that one should not completely break the environment

When support for certain things is dropped completely, expect breakage at some point. 01.01.2020 we stopped support for Android 5.x and 6.x and there was a 6 months delay before v0.96 has removed support for legacy environment entirely.

**Comment by galets** [comment]
Leonid: how am I supposed to run `termux-upgrade-repo` when bash will not start?

**Comment by xeffyr** [comment]
Termux has failsafe shell which works with broken environment. Open it, and
```
export PREFIX=/data/data/com.termux/files/usr/bin
export LD_LIBRARY_PATH=$PREFIX/lib
export PATH=$PREFIX/bin
termux-upgrade-repo
```

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Recover_a_broken_environment#Launching_a_Failsafe_Session

**Comment by espes** [comment]
I appreciate that there's not much energy for backwards compatibility, but even including instructions for migrating old environments would have saved me quite some strife tonight ^^;

I had an environment old enough that it didn't include the termux-upgrade-repo scipt. For others googling why their termux suddenly stopped working, what worked for me was:
- Opening a failsafe shell by opening the drawer with CTRL-ALT-→, pressing "New Session", then "Failsafe"
- Then running:
```export PREFIX=/data/data/com.termux/files/usr
export LD_LIBRARY_PATH=$PREFIX/lib
export PATH=$PREFIX/bin:/bin
wget https://raw.githubusercontent.com/termux/termux-packages/android-5/packages/termux-tools/termux-upgrade-repo
sed -i '/TERMUX_PREFIX/d' termux-upgrade-repo
sh termux-upgrade-repo```

**Comment by nathanielatom** [comment]
Thank you! This upgrade script is much better than simply wiping all the data under $PREFIX (which took some work to install and configure the correct packages for compiling python libraries).

I tried editing https://wiki.termux.com/wiki/Recover_a_broken_environment with the above solution (and error message/cause), but I do not have permission.

**Comment by xeffyr** [comment]
> I tried editing https://wiki.termux.com/wiki/Recover_a_broken_environment with the above solution

`termux-upgrade-repo` has nothing to do with _Recovering a broken environment_. Its only purpose to assist transition from legacy termux.net repo to a new one.

Here is everything that `termux-upgrade-repo` does:
* Generates a script that keeps configuration of known repositories, e.g. official and by its-pointless, and creates a list of packages for reinstallation.
* Wipes $PREFIX.
So all package-specific configuration, databases, other files stored in $PREFIX will gone.

**Comment by nathanielatom** [comment]
Sorry, I guess I considered the phrase "broken environment" to mean the more general sense, such as termux shell being unable to start after an automatic app update. But I see now it must mean specifically the broken .dotfiles kind of environment. 

Thanks for detailing what it does. I also ran

```
du -sh $PREFIX
mkdir ~/prefix_bak
cp -r $PREFIX ~/prefix_bak/
```

beforehand, just to hold on to that package-specific stuff (like which python libraries were installed, etc).

I think the `termux-upgrade-repo` command could potentially benefit from this (as an optional step, after listing the size). I could create a PR at some point with this change and some more docs, if there's interest.

Thanks again!
