### ISSUE TITLE
Could consider the native termux  had beened installed GCC and gfortran in the next version?

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-app#1704]
it's hard for me to install GCC  and other packsges from   https://github.com/its-pointless/its-pointless.github.io.
Connection refused for a long time long time . i had tried to build gcc in termux but fail.
$ pkg update
Err:1 https://its-pointless.github.io/files/24 termux InRelease
  Failed to connect to its-pointless.github.io port 443: Connection refused

**Comment by Grimler91** [comment]
GCC cannot (at least not easily) be cross-compiled after the android-ndk dropped GCC for clang. There are many many many old closed issues about this that you can find by searching the issues for GCC.

As for the connection refused, see @xeffyr's response in https://github.com/termux/termux-app/issues/1700#issuecomment-671683011
