### ISSUE TITLE
Source list is down or wrong!

### ISSUE THREAD

**Issue by hamody114** [termux/termux-app#1707]
I downloaded the app fresh and never touch it and it tells me that...
`pkg update
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://dl.bintray.com/termux/termux-packages-24
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [8255 B]
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:6 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Ign:7 https://dl.bintray.com/termux/termux-packages-24 stable Release.gpg
Get:8 https://dl.bintray.com/grimler/game-packages-24 games Release.gpg [475 B]
Get:9 https://dl.bintray.com/grimler/science-packages-24 science Release.gpg [475 B]
Get:10 https://dl.bintray.com/grimler/game-packages-24 games/stable aarch64 Packages [3983 B]
Get:11 https://dl.bintray.com/grimler/science-packages-24 science/stable aarch64 Packages [8722 B]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).`

any suggestions?

**Comment by Grimler91** [comment]
Looks like the metadata generation on bintray got stuck somehow. I've issued a manual re-generation so hopefully this is fixed within a few minutes.

**Comment by Grimler91** [comment]
Fixed now, thanks for reporting

**Comment by Qixpy** [comment]
Hey tere, how can i fix it. I have same problem. Pls help me.

**Comment by agnostic-apollo** [comment]
@Qixpy Check termux/termux-packages#6593
