### ISSUE TITLE
Python Pandas

### ISSUE THREAD

**Issue by Vishwajeetbamane** [termux/termux-app#1709]
I am unable to install pandas on latest Python version.
I first installed Python by executing following command :-
`pkg install python`
It automatically installed Python's latest version 3.8.1
After installing Python , I tried to install pandas by...
`pip install pandas`
But it failed

I even tried updating all packages and tried everything but nothing happened.

**Comment by Grimler91** [comment]
You haven't shared any information whatsoever about the error so we can only guess what is going on.

Please read the [previous 18 questions about pandas](https://github.com/search?q=org%3Atermux+pandas&type=Issues), they probably contain your particular error.
