### ISSUE TITLE
Unable to install python's specific version

### ISSUE THREAD

**Issue by Vishwajeetbamane** [termux/termux-app#1710]
I am unable to install Python's specific version.
I executed `pkg  install python=3.8.1` but it is showing error.
![Screenshot_2020-08-13-21-43-53-02_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/56468218/90159557-331fee00-ddae-11ea-8623-704a90b02879.jpg)

**Comment by xeffyr** [comment]
As Termux follows rolling-release update style (aka Arch Linux, Alpine edge or Debian Sid), older versions are not available for installation.
