### ISSUE TITLE
Custom Startup Commands

### ISSUE THREAD

**Issue by BeingDatta** [termux/termux-app#1711]
is it possible to use custom commands at startup say (/sbin/su -c "/system/bin/sh -") so that termux start in root shell like other terminal emulators have ?

Basically what i want is to run termux like any other terminal at / directory not in (/data/data/com.termux/files/home) and that too at the very begining.

Regards

**Comment by xeffyr** [comment]
Create file `~/.termux/shell` with this content:
```
#!/system/bin/sh
exec /sbin/su -c "/system/bin/sh -"
```
Then `chmod 755 ~/.termux/shell` and you should be ok...

**Comment by BeingDatta** [comment]
> Create file `~/.termux/shell` with this content:
> ```
> #!/system/bin/sh
> exec /sbin/su -c "/system/bin/sh -"
> ```
> Then `chmod 755 ~/.termux/shell` and you should be ok...

i did this as per u stated but to my surprise its stuck at blackscreen unless and untill i m doing "ctrl+d" its not entering the shell. after that its entering root shell in root directory as u have mentioned. would you be able to solve this issue.

**Comment by BeingDatta** [comment]
Anyway solved it by passing

/sbin/su /system/bin/sh -c "commands"

Regards.
