### ISSUE TITLE
Termux cant open files

### ISSUE THREAD

**Issue by omegalul666** [termux/termux-app#1712]
Termux version: 0.98
Mobile: Huawei Nova 5t (android)
Issue: The app cant open files its open only itself...

**Comment by Grimler91** [comment]
Please be more specific and follow the bug report template: https://github.com/termux/termux-app/issues/new?template=bug_report.md

 Open files in what way? Open files where?

**Comment by omegalul666** [comment]
When i want open file via Termux, Termux opens like when im opening only Termux.

**Comment by omegalul666** [comment]
I think Termux dont open in storage emulated but its only my idea so...

**Comment by alephalpha0** [comment]
@omegalul666 are you passing a file to termux via Android's share menu? Eg, sharing a file from a file manager to termux? If so, you need to follow the instructions given by termux and create a `termux-url-opener` script to be `chmod a+x` and placed in $HOME/bin. At least that seems to be what your issue description states you're doing.. 🤷🏼‍♂️

**Comment by omegalul666** [comment]
@alephalpha0 ok thanks! ill try

**Comment by omegalul666** [comment]
And ill write if its work or not
