### ISSUE TITLE
RUN_COMMAND Permission Message in the Permission Controller

### ISSUE THREAD

**Issue by MuntashirAkon** [termux/termux-app#1713]
**Problem description**

This is not exactly a friendly message when asking for permission through permission controller.

![Screenshot_Permission_controller](https://user-images.githubusercontent.com/8176128/90232745-f3551700-de3e-11ea-84ef-1e2b47db3c36.png)

**Steps to reproduce**

Add the following code in the main activity of any sample code:
```java
        if (ContextCompat.checkSelfPermission(this, "com.termux.permission.RUN_COMMAND") != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this, new String[]{"com.termux.permission.RUN_COMMAND"}, requestCode);
        }
```

**Expected behavior**

The message should be more concise and clear without any full stop. For example, “execute arbitrary commands within Termux environment” so that the whole message should be read as “Allow **App Manager** to execute arbitrary commands within Termux environment?”.

**Additional information**

* Termux application version: 0.95

I can make a PR if you're interested.

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/termux-app/commit/b486d29d2342583dbaad42787ae47cd7a8d499b4.
