### ISSUE TITLE
Obtain geolocation within Termux

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#1714]
I use Andronix, an extension of Termux allowing running Linux GUI under Termux, accessible via VNC.
That works very good, but I am unable to obtain geolocation within it.
Termux lacks a geolocation permission, so subsystems of it cannot access the device builtin GPS.
The function termux-location is part of the Termux API (which does have location access) and is not used by Andronix which uses 'plain' Termux.

**Steps to reproduce**
Use any location aware app (e.g. Firefox browser within Linux XFCE, *not* in Android) and open an online map (e.g. wego.here.com) and enable access to location from that site in Firefox settings.

**Expected behavior**
Location should be shown.

* Termux application version: 0.95
* Android OS version: 10 (Oneplus Oxygen OS 10.3.5)
* Device model: Oneplus 6

**Comment by xeffyr** [comment]
> The function termux-location is part of the Termux API (which does have location access) and is not used by Andronix which uses 'plain' Termux.

Proot can use Termux utilities including termux-location, follow https://github.com/termux/proot/issues/23#issuecomment-615965709.

> Use any location aware app (e.g. Firefox browser within Linux XFCE, not in Android) and open an online map (e.g. wego.here.com) and enable access to location from that site in Firefox settings.

This is not possible. Location can be obtained only from Android API.

**Comment by xeffyr** [comment]
> Termux lacks a geolocation permission, so subsystems of it cannot access the device builtin GPS.

This is not the case. Permission is propagated by Termux:API if granted though Android settings.

The reason why it can be used by utilities is because it can be accessed only through API.

**Comment by freebrowser1** [comment]
Network location indeed does work inside Firefox, but not the GPS.

**Comment by xeffyr** [comment]
As I wrote, GPS will not work without Termux:API. Use `termux-location` for getting GPS data and only if satellite signal is good. It unlikely will work in-room.
