### ISSUE TITLE
What is the max version of termux which will run on android 4.0.4?

### ISSUE THREAD

**Issue by hamzazia1** [termux/termux-app#172]
Hi,

I have samsung 10.1 gt-p7510 running android 4.0.4 and your latest version from google play store is incompatible.

Which version should I use? Can you please give me the apk for that version?

Sincerely,
Hamza

**Comment by fornwall** [comment]
I'm sorry, but there is no version compatible with Android 4 - Termux required Android 5 from the start.

**Comment by hamzazia1** [comment]
@fornwall No issues. I'll try something else.
