### ISSUE TITLE
Termux is not connecting to repos.

### ISSUE THREAD

**Issue by CybernetiX-S3C** [termux/termux-app#1723]
Termux failed to connect to repos during update and upgrade.

$ apt update
0% [Working]^C
$ pkg upgrade
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: bad
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: bad
Using fallback mirror: https://termux.org/packages
Err:1 https://termux.org/packages stable InRelease
  Failed to connect to termux.org port 443: Connection timed out
Err:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
  Failed to connect to dl.bintray.com port 443: Connection timed out
0% [Working]^C
$ uname -a
Linux localhost 3.18.71-14274519 #1 SMP PREEMPT Tue Mar 17 15:57:04 KST 2020 aarch64 Android
-->

*Android 8.0
*Samsung Galaxy S7 SM-G930V

![Screenshot_20200822-160436_Termux](https://user-images.githubusercontent.com/39076455/90964985-37c16200-e492-11ea-8f1a-e5d95bf91880.jpg)

**Comment by CybernetiX-S3C** [comment]
Same problem persists. I have rebooted the phone. I have exited the app. My internet is fine. The app is a problem.

**Comment by CybernetiX-S3C** [comment]
I have never disabled wifi within the app itself.

[https://cybernetix-s3c.net/main](https://cybernetix-s3c.net/main) 

This is not the first time I have used Linux based commands.

**Comment by CybernetiX-S3C** [comment]
It's also happening on my LG Q7+.

Reinstalled the app. Works fine when initial updating. Exit, reboot, reopen, and the problem appears.

**Comment by xeffyr** [comment]
> Also, why would you close an issue that is still open as an issue?

Because all mirrors are operating fine. And since they are placed in different locations with different ISPs, it is very unlikely if all of them will stop work at once.

Only you had submitted this issue.

> I reinstalled the app 3 times. It will work again, once reinstalled. I will get it upgraded to the last point. Exit, reboot, reopen, and the same problem appears.

Problem is either with your Wi-Fi router, ISP or device.

**Comment by xeffyr** [comment]
Issue is locked now.
