### ISSUE TITLE
proot and proot-distro problems on android 9

### ISSUE THREAD

**Issue by fu7eL5sa** [termux/termux-app#1725]
**Problem description**

A lot of packages (see on screenshot below) fail to process and no web browser works on debian (using the proot and the script from https://wiki.termux.com/wiki/Debian) and ubuntu with proot-distro.
**Steps to reproduce**

`pkg update -y && pkg install proot-distro -y`
`proot-distro install ubuntu`
`proot-distro login ubuntu`
`apt-get update && apt-get upgrade -y`
`apt-get install -y sudo xfce4 tightvncserver`
**Expected behavior**

No errors on post processing packages, web browser, would open (tested with Chromium and Firefox-esr. Midori opens but doesn't load any webpage).
**Additional information**

* Termux application version: 0.96
* Android OS version: Android Pie, api 28
* Device model: LG K40s

![termuxbug](https://user-images.githubusercontent.com/70115767/90993711-50ae3e00-e58c-11ea-90ae-5fec62554b46.png)

**Comment by xeffyr** [comment]
Not a proot/proot-disto issue.

There is a problem with installing/upgrading such packages as `udisks2` but that can't be solved. They require a real root access to work or maybe at least SELinux in permissive mode.

**Comment by fu7eL5sa** [comment]
thank you a lot for your reply.
I've done the same thing on a android 7 device (LG K10 Power, without root access) and everything worked fine. why doesn't it work on android 9? is it something to do with SELinux?

**Comment by xeffyr** [comment]
On higher Android versions SELinux is more restrictive.

**Comment by fu7eL5sa** [comment]
oh, ok. thank you very much for making this clearer to me. and thank you for the hard work with termux, it's an awesome app!
