### ISSUE TITLE
Help is unclear for builtin HW keyboards.

### ISSUE THREAD

**Issue by v6ak** [termux/termux-app#173]
The help for keyboard is divided to physical keyboards and touch keyboards. However, the help for touch keyboards rather a help for reduced keyboards. On one hand, keyboards of devices like BB PRIV or Xperia Mini Pro miss some important keys and the help for “touch keyboards” can be also helpful there. On the other hand, full software keyboards (e.g., Hacker's Keyboard) on tablets don't need this.

Maybe the section Touch keyboards should be renamed to Reduced keyboards.

**Comment by xeffyr** [comment]
Closing as that really isn't issue. We split docs for software (touch) & hardware keyboards intentionally as Termux handles them differently.

Renaming section to a "reduced keyboards" will make docs really unclear.
