### ISSUE TITLE
Commands as app shortcut?

### ISSUE THREAD

**Issue by victorbnl** [termux/termux-app#1730]
**Feature description**
I'd like to have commands when I long press icons on launcher that supports it
[An example of app shortcuts](https://i.imgur.com/OHkJN6i.jpg)
I see at this place there are already the two buttons, "Failsafe" and "New session" but it would be great to have custom commands
I imagine this as a folder like ~/.shortcuts and every script here is as a shortcut, exactly like the widget

**Reference implementation**
I don't know whether other terminal apps have this feature, but it shouldn't be very difficult to implement as there are already the two buttons here, meaning the developers who made this already know how it works. I'd like to make a pull request but I'm poor at Android development and it seems complicated

**Comment by xeffyr** [comment]
Application shortcuts are defined through immutable resource. What you are requesting is not possible as far I know.

They are defined here: https://github.com/termux/termux-app/blob/master/app/src/main/res/xml/shortcuts.xml
and referenced from https://github.com/termux/termux-app/blob/master/app/src/main/AndroidManifest.xml#L53. Both of these files can't be changed at runtime since they are part of APK file.

**Comment by xeffyr** [comment]
update: Android has https://developer.android.com/reference/android/content/pm/ShortcutManager, so implementation should be easy.

**Comment by Victor-Bo** [comment]
Yep, I found some documentation, dynamic shortcuts, see here: 
https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts#dynamic

**Comment by hltdev8642** [comment]
I didn't verify this, but I imagine this would be relatively easy using nova launcher (+ sesame shortcuts) and intents

**Comment by Victor-Bo** [comment]
No I meant on the app side and something that works with all the launcher, with the link I sent above

**Comment by hltdev8642** [comment]
I think in sesame you can create new custom shortcuts for any app, but i gotcha!

**Comment by Victor-Bo** [comment]
I don't even think it would be possible because you're saying sesame allows us to create intents, and there's not one intent per command. But anyway I don't use it and don't want to use it, I use Niagara launcher and I think this kind of functionality could be useful for many people

**Comment by WMCB-Tech** [comment]
Actually, it would be kinda nice to add it,

Termux as app shortcuts is like (.desktop) files in linux so you can execute it on your home screen

And i use Termux:widget plugin although they are listed but i use it to launch scripts

**Comment by Victor-Bo** [comment]
Yeah I know the widget app but app shortcuts are way cleaner, more beautiful etc

**Comment by hltdev8642** [comment]
> I don't even think it would be possible because you're saying sesame allows us to create intents, and there's not one intent per command. But anyway I don't use it and don't want to use it, I use Niagara launcher and I think this kind of functionality could be useful for many people

agreed, was just brainstorming really :-]

**Comment by Victor-Bo** [comment]
Aaaah ok ok no problema x). Anyway I think I'll try to make a pull request but I struggle understanding how Termux works xD

**Comment by hltdev8642** [comment]
> Aaaah ok ok no problema x). Anyway I think I'll try to make a pull request but I struggle understanding how Termux works xD

I guess what I was trying to say, is that sesame shortcuts allows you to make custom shortcuts for any app on your device, and figured maybe you could look at what intents they used to figure out how it would be accessed/implemented

**Comment by Victor-Bo** [comment]
Aaaah ok, I didn't know Sesame was open source
