### ISSUE TITLE
F-Droid has problems with publishing v0.99 update

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-app#1736]
In https://f-droid.org/wiki/page/com.termux/lastbuild_99:

```
== Installed Android Tools ==

INFO: Creating log directory
INFO: Creating temporary directory
INFO: Creating output directory
INFO: Using git version 2.11.0
INFO: Building version 0.99 (99) of com.termux
INFO: Getting source for revision v0.99
INFO: Creating local.properties file at build/com.termux/local.properties
INFO: Creating local.properties file at build/com.termux/app/local.properties
INFO: Cleaned build.gradle of keysigning configs at build/com.termux/app/build.gradle
INFO: Running 'prebuild' commands in build/com.termux/app
INFO: Cleaning Gradle project...
ERROR: Could not build app com.termux: Error cleaning com.termux:0.99
==== detail begin ====
Found 6.6.1 via distributionUrl
No hash for gradle version 6.6.1! Exiting...
==== detail end ====
```

Latest version on F-Droid is v0.96. It looks like F-Droid is unprepared for newer Gradle versions.

Problem is *unreproducible* with local and GithubActions builds.

**Comment by Grimler91** [comment]
Looks like the missing hash was added a week ago: https://gitlab.com/fdroid/fdroidserver/-/commit/394ad8f8630b9db1eec74f0410679c9d49c70926, so now the build should succeed as soon as fdroid's buildserver is updated, which does not seem to happen automatically: https://gitlab.com/fdroid/admin/-/issues/128

**Comment by xeffyr** [comment]
v0.99 build succeeded according to https://f-droid.org/wiki/page/com.termux/lastbuild_99 and should be available soon. I'm closing this.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app/commit/cba80b6c0b29525536b52bdddd02845833d6cf15 seems to be not need, I'll revert it.
