### ISSUE TITLE
All Termux commands should be able to run from a third party app or a shell script like tmux, hping3, etc.

### ISSUE THREAD

**Issue by Dhruvkanani** [termux/termux-app#1737]
**Feature description**

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by xeffyr** [comment]
> All Termux commands should be able to run from a third party app or a shell script like tmux, hping3, etc.

Question or statement?

If the first - see https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/RunCommandService.java#L17-L44 for instructions.

If the latter - wontfix. Termux will never provide a permissionless silent default way for execution of arbitrary commands by third-parties.
