### ISSUE TITLE
apt update - not working 

### ISSUE THREAD

**Issue by GabrielGab** [termux/termux-app#174]
Hi , I am getting this issue from yesterday -10/7 , first install on my "Moto X play" Android 6.0.1 from Cyanogenmod.
Get 1 : ok 
Get 2: Hash Sum mismatch

Then , I tried to "apt install vim",  same on Nodejs Packages and the answer is :
E: Unable to locate package nodejs.
 
Reinstalling, rebooting , nothing change .
I have read very good comments from this tool , that match my needs.
Thanks.

**Comment by fornwall** [comment]
Could you try running `apt clean` and `apt update` before trying to install vim again?

**Comment by GabrielGab** [comment]
Thanks fornwall . I tried , but still same problem . As an additional info , I have installed "GNURoot Debian" and everything is working fine  - update , vim , nano , nodejs , npm , etc . At least , the specific customer request is done , but I really would like to give Termux a try..
I also clear the app data , and install older version from F-droid  , and installed it in some other Samsung phone , then same results ,
May be something is missing **in  /stable/main/binary-all/Packages.xz** ?!

**Comment by tinydynamite00** [comment]
@GabrielGab JIC you're still having problems: each installation of Termux and any of its add-ons must be from the same source, i.e. install from F-Droid **or** Play Store. The apps cannot be mixed as they are signed with different keys. 
> Presently running Termux + Termux:API (both via Play Store), fresh install of Android 7.0 + 6.0.1
> on N6 and G2, respectively. `apt update` working w/o issue

**Comment by GabrielGab** [comment]
May somebody make a fresh installation of termux  ?, if it was preinstalled before , please , "clear data" from - Settings - Apps - Storage  of Android options ,

I have no doubts that previously installed termux are doing fine, but I guess that something is not working for new installations . I have done this test from several devices (mine and some friends ) , for Android 6./5 , custom and official ROMs.

**Getting error is : "Hash Sum mismatch" in Get 2** , when I try a "apt update" command.

Thanks !!

**Comment by fornwall** [comment]
@GabrielGab I tested on a clean install and it works for me.

Could it be a problem with the [http://termux.net/dists/stable/main/binary-all/Packages.xz](http://termux.net/dists/stable/main/binary-all/Packages.xz) file being cached somewhere for you? Can you run

    wget http://termux.net/dists/stable/main/binary-all/Packages.xz
    sha256sum Packages.xz

? It should output `3fac9416d038553984c269a817681cbf2081212bbecd070c2a78859e1bc213ff`.

Also, could you give the complete error message from running `apt update`?

**Comment by GabrielGab** [comment]
Hi . received your mail , just try again "apt update" on an open session of
termux and everything is working fine !
Thanks .Something cached somewhere ...

**Comment by fornwall** [comment]
@GabrielGab Ok, great! I'm closing this issue, let me know if you encounter any problem again!

**Comment by Emmanuelaji** [comment]
Err:4 https://xeffyr.github.io/termux-x-repository termux Release
  404


Please can someone help me solve this error code?

**Comment by xeffyr** [comment]
Remove `https://xeffyr.github.io/termux-x-repository` from your `$PREFIX/etc/apt/sources.list`.

**Comment by Emmanuelaji** [comment]
Thanks alot
