### ISSUE TITLE
An issue with the APKsigner, signing doesn't happen

### ISSUE THREAD

**Issue by darshytheplayer** [termux/termux-app#1741]
When trying to sign the apk, I get this: Exception in thread "main" java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;                                                                                                         at com.android.apksig.internal.apk.v1.V1SchemeSigner.generateManifestFile(V1SchemeSigner.java:378)                                                                                                  at com.android.apksig.internal.apk.v1.V1SchemeSigner.sign(V1SchemeSigner.java:253)                at com.android.apksig.DefaultApkSignerEngine.outputJarEntries(DefaultApkSignerEngine.java:657)                                                                                                      at com.android.apksig.ApkSigner.sign(ApkSigner.java:436)                                          at com.android.apksig.ApkSigner.sign(ApkSigner.java:193)                                          at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:340)                               at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)                        Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[zip file "/data/data/com.termux/files/usr/share/dex/apksigner.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)                         at java.lang.ClassLoader.loadClass(ClassLoader.java:380)                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)                                          ... 7 more                                                                                make: *** [Makefile:887: build/us_pc/sm64.us.f3dex2e.apk] Error 1                                 ~                                                                                                 $
It was meant to sign the apk and make the app installable, it's reproduceable by pasting in a command (which is altered by choice, though it does not affect installation) to starting part 2 of the apk building.

**Additional information**

* Termux application version: 0.98
* Android OS version: 7.0 Nougat
* Device model: LGMS210, LG Aristo

**Comment by xeffyr** [comment]
**Please fill the template properly!** Your post doesn't provide any information about the problem.

**Comment by xeffyr** [comment]
Fixed in latest build of `apksigner`.
