### ISSUE TITLE
Can I Compile QEMU from source?

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/termux-app#1742]
Hey. I am using QEMU in Termux for a while. but I want to test new features in QEMU by compiling Qemu from git

But the issue is the dependencies which it compiled with Android NDK

So is it OK to compile QEMU from git directly from Termux without any PRoot/Chroot setup

**Comment by xeffyr** [comment]
> So is it OK to compile QEMU

That's completely untested. Also be sure that QEMU is quite brittle thing, it can fail easily in non-standard environments like Termux. It is being updated ONLY if new version build is confirmed to work properly on each of ARM, AArch64, i686 and x86_64 architectures.

If want to build on device, you'll need to apply patches from https://github.com/termux/termux-packages/tree/master/packages/qemu-system-x86_64-headless - v5.x will probably require some adaptation. And don't forget to check the package config options at https://github.com/termux/termux-packages/blob/master/packages/qemu-system-x86_64-headless/build.sh#L13.
