### ISSUE TITLE
Android 11: Fdsan errors

### ISSUE THREAD

**Issue by BongoEADGC6** [termux/termux-app#1748]
**Problem description**
mosh worked fine on Android 10, but no longer works.
Error message:
fdsan: attempted to close file descriptor 11, expected to be unowned, actually owned by FILE* 0x7d642414b8
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).

Likely related to: https://developer.android.com/about/versions/11/behavior-changes-all

**Steps to reproduce**
pkg install mosh
mosh user@hostname

**Expected behavior**
Run without issue

**Additional information**
Multiple packages seen to have the same issue 
https://github.com/termux/science-packages/issues/50

* Termux application version: 0.98
* Android OS version: 11
* Device model: Pixel 3 

Migrated from: https://github.com/termux/termux-packages/issues/5790

**Comment by BongoEADGC6** [comment]
https://github.com/flutter/flutter/issues/43844
Similar issue here

**Comment by Grimler91** [comment]
Closing in favour of https://github.com/termux/termux-packages/issues/5790 so that we are tracking the issue in one place only
