### ISSUE TITLE
Chrome OS crashes when disconnecting external monitor

### ISSUE THREAD

**Issue by kanreki** [termux/termux-app#1749]
**Problem description**

Chrome OS crashes when disconnecting external monitor if a Termux window was present on the external monitor.

I use Termux on a Chromebook with Android app support. I sometimes connect an external monitor via a docking station (hardware details below). On my old monitor it was working fine. But I recently got a new monitor, and I've started to see these crashes. (The old monitor was a rather old, pre-4K 24" HP monitor. The new one is as described below.)

If there is a Termux window appearing on the external monitor at the time I disconnect the docking station, then Chrome OS crashes, and I see a single Chrome browser window (on the laptop screen of course) with the message "Chrome didn't shut down correctly." If I click the "Restore" button, the browser windows that had been active are restarted; but of course not any of the Termux windows.

If instead I move the Termux window to the laptop's internal screen before disconnecting, then it works OK.

**Steps to reproduce**

1. connect laptop to external monitor
2. launch Termux; move the Termux window to the external monitor
3. disconnect the external monitor

**Expected behavior**

All windows that had been on the external monitor automatically move to the laptop's internal screen; none of them disappear entirely. This is what used to happen when I had the old monitor.

**Additional information**

* docking station: [moshi Symbus](https://www.moshi.com/en/product/symbus-compact-usb-c-dock/us-version)
* monitor: [LG 27UL500 27" 4K](https://www.lg.com/us/monitors/lg-27UL500-W-4k-uhd-led-monitor)

***Output of termux-info***

```
Packages CPU architecture:
i686
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.0-20557-ge6ecf4a9a948 #1 SMP PREEMPT Mon Sep 7 01:32:04 PDT 2020 i686 Android
Device manufacturer:
Google
Device model:
HP Chromebook 13 G1
```

(BTW, how can I find the Termux application version? See #1246)

**Comment by xeffyr** [comment]
> Chrome OS crashes

> But I recently got a new monitor, and I've started to see these crashes.

> then Chrome OS crashes, and I see a single Chrome browser window (on the laptop screen of course) with the message "Chrome didn't shut down correctly." 

Report this to Google. Termux doesn't manage the hardware and operating system state and issue you are describing is **an operating system bug**. Application should never be able to crash OS in any way.

**Comment by xeffyr** [comment]
> how can I find the Termux application version?

In application info.

**Comment by YoungElPaso** [comment]
@kanreki I also experienced this, did you ever file this issue anywhere else?

**Comment by kanreki** [comment]
> @kanreki I also experienced this, did you ever file this issue anywhere else?

https://bugs.chromium.org/p/chromium/issues/detail?id=1127431
