### ISSUE TITLE
Just a clue - not an issue 

### ISSUE THREAD

**Issue by GabrielGab** [termux/termux-app#175]
Someone knows a way to make a tunnel connection in Termux ?. With WiFi connection I can access nodejs/express server, but with Data connection - no way -  some firewall is between .
So I need some tunneling service for access nodejs server from an external url .
Normally for this situation I use Ngrok :    **https://ngrok.com/download**
Thanks  in advance.

**Comment by fornwall** [comment]
Perhaps [localtunnel](https://github.com/localtunnel/localtunnel)? I haven't used that myself though.

You're welcome to ask this (and other questions) at https://termux.com/community!

**Comment by pyhedgehog** [comment]
@GabrielGab, You can use tor ([orbot](https://play.google.com/store/apps/details?id=org.torproject.android) in case of android) for this. Note that orbot creates another HiddenService for every port.

**Comment by fornwall** [comment]
@pyhedgehog @GabrielGab Note that a tor package is now available in Termux and can be installed with `apt install tor`.

**Comment by pyhedgehog** [comment]
What for?! Orbot at least has auto-start.

**Comment by arunr2580** [comment]
How to install ngrok in termux plz helpme 9562424931 wtsapp pllzzz

**Comment by sdrausty** [comment]
@arunr2580 This thread is regarding Termux App.  You probably want to ask your question at https://github.com/termux/termux-packages/issues

**Comment by sdrausty** [comment]
@pyhedgehog 
> at least has auto-start.

Termux has auto start.  See https://github.com/termux/termux-boot

**Comment by oneo766** [comment]
Ngrok isn't working in termux...please help me...
