### ISSUE TITLE
Support for HarmonyOS 2.0

### ISSUE THREAD

**Issue by WakemanCK** [termux/termux-app#1750]
** Feature description **

Huawei lauched its HarmonyOS 2.0 on 10 Sep. Please add support for it. Thanks!

(Previously, someone used termux to check HarmonyOS 1.0 and it reported the OS was Android 9. The screenshot became famous in China and was used by Huawei haters as an "evidence" that HarmonyOS is fake. I highly doubt HarmonyOS is fake. However, I guess it did retain some Android modules in 1.0, so termux still thought it was Android.

With the lauch of HarmonyOS 2.0, I hope someone can look into it to make termux able to distinguish HarmonyOS from Android. Thanks a lot!)

**Comment by WakemanCK** [comment]
Nevermind. Actually it is probably too early to ask for this.

Right now, Android apps cannot be run on HarmonyOS 2.0. Huawei says that they will release a tool that helps developers to convert Android apps to HarmonyOS apps. Maybe I shall come back when they release this tool.

**Comment by xeffyr** [comment]
@WakemanCK Please note that if HarmonyOS doesn't use compatible ABIs for native interface, we will not support this OS. As far I know, it uses a "microkernel" which definitely is not Linux. Probably few programs using a pure C and cross-platform support in mind will work, but others will not.

The tool you are talking about very unlikely will be able to rewrite ELF (executable and linkable format) binaries in way supported by Harmony OS.

We have no possibility of supporting operating systems different from Android. Please note that Termux is a terminal emulator and *Linux environment* app for Android OS and heavily utilizes the fact that Android is built on top of Linux kernel.

**Comment by handicraftsman** [comment]
@xeffyr it is probably time to reopen this issue, as it is clear now that HarmonyOS uses Linux + AOSP (+ many custom APIs) under the hood on phones and tablets.

**Comment by xeffyr** [comment]
@handicraftsman What is required to support HarmonyOS? If it uses "Linux + AOSP", then I see no problem with downloading APK from F-Droid and installing it.

**Comment by ChiefMikeK** [comment]
FYI
-  Huawei  has 2 versions of harmony under development one of which is an inhouse microkernel for iot devices and another one based on AOSP 10.
-  `uname -a` will continue to report Android until compiled/fixed by **Huawei  devs**.
-  It's beyond termux to fake the output of uname !

**Comment by xeffyr** [comment]
> uname -a will continue to report Android until compiled/fixed by Huawei devs.

Coreutils has operating system explicitly set as "Android": https://github.com/termux/termux-packages/blob/master/packages/coreutils/build.sh#L20

**Comment by agnostic-apollo** [comment]
Related info

https://twitter.com/AdamConwayIE/status/1400806402621333504?s=19

**Comment by handicraftsman** [comment]
>     * Huawei  has 2 versions of harmony under development one of which is an inhouse microkernel for iot devices and another one based on AOSP 10.
>     * Neither of which have released source(s) yet.

These exact statements are faked by ArsTechnica, you can find code for both versions at https://gitee.com/openharmony/ . That is not exactly what runs at Huawei phones, but is it's base system. 
Both of these buildtypes actually share same API in ohos java package.
There are actually 2 microkernels for IoT, LiteOS A and LiteOS M. Both of these (and Linux too) have bindings for their inhouse abstraction layer which is present on all 3 buildtypes.
 
>     * `uname -a` will continue to report Android until compiled/fixed by **Huawei  devs**.
>     * It's beyond termux to fake the output of uname !
And well, that's true.
