### ISSUE TITLE
DECRQM returns crap

### ISSUE THREAD

**Issue by pjanx** [termux/termux-app#1752]
**Problem description**

DECRQM is implemented wrong. It reports "set" when the feature is unknown, and reports "unknown" when a feature is known.

```
                                int internalBit = mapDecSetBitToInternalBit(mode);
                                if (internalBit == -1) {
                                    value = isDecsetInternalBitSet(internalBit) ? 1 : 2; // 1=set, 2=reset.
```

The fix appears to be trivial: change `==` to `!=`.

**Additional information**

* Termux application version: master
* Android OS version: —
* Device model: —

**Comment by Grimler91** [comment]
Thanks for noticing, this bug has apparently been there since the first commit: https://github.com/termux/termux-app/blob/a18ee58f7a4f56cab6ba4a8cacaa70c4c76379b3/app/src/main/java/com/termux/terminal/TerminalEmulator.java#L729

**Comment by xeffyr** [comment]
Part of [v0.100](https://github.com/termux/termux-app/releases/tag/v0.100) release.
