### ISSUE TITLE
How to make a similar app using flutter?

### ISSUE THREAD

**Issue by gauravmehta13** [termux/termux-app#1753]
i want to make similar app using flutter , is there any way to do that?

**Comment by Grimler91** [comment]
Well sure, read the flutter docs and start coding:
https://flutter.dev/docs/get-started/flutter-for/android-devs

**Comment by xeffyr** [comment]
Yes, you probably will just need to rewrite it completely in Dart, not sure whether Flutter allows mixing of Java, Kotlin and Dart parts. How to do that is offtopic there, as we do not work with Flutter/Dart.

You'll also need to create own APT repository with packages recompiled with your new application package name to avoid hardcoded path issues. For distribution, you definitely will want change the `com.termux` to something own.
