### ISSUE TITLE
read: Illegal option -N

### ISSUE THREAD

**Issue by domker** [termux/termux-app#1759]
**Problem description**

Termux don't pass option e. g. "-N 1" of "read" command when used in a bash script.
If you type "read -N 1" directly into Termux, it works fine.

**Steps to reproduce**

1. Make simple bash script:
```bash
#!/bin/bash
read -N 1 -p "Type one char: "
```
2. Run script:
sh myscript.sh
3. Now You see: 
`read: Illegal option -N`

**Expected behavior**

Successful execution of the read command with option (e. g.) "-N 1", as in the case of a direct shell call.

**Additional information**

* Termux application version: 0.99
* Android OS version: 8.0.0
* Device model: Xiaomi Mi5 Pro

**Comment by Grimler91** [comment]
You are probably using the system shell. 
`/bin/bash` does not exist, so `#!/bin/bash` is not a valid shebang.

Try changing to `#!/data/data/com.termux/files/usr/bin/bash`

**Comment by xeffyr** [comment]
> sh myscript.sh

Just don't run Bash script withj Dash (sh).

* `./myscript.sh`
* Or `bash myscript.sh`
