### ISSUE TITLE
Apktool does not allow me to view the content of the apk files in Termux

### ISSUE THREAD

**Issue by AdrMXR** [termux/termux-app#1760]
When I unzip the apk apparently everything is done correctly, but when trying to see for example the `AndroidManifest.xml` file it appears like this.

```
$ apktool d prueba.apk
 I: Using Apktool 2.3.4 on prueba.apk
 I: Copying raw resources...
 I: Baksmaling classes.dex...
 I: Copying assets and libs... 
 I: Copying unknown files... 
 I: Copying original files...
$ cd prueba 
$ cat AndroidManifest.xml 
^K^@^@4^K^@^@b^K^@^@�^K^@^@�^K^@^@�^K^@^@^K^@v^@e^@r^@s^@i^@o^@n^@C^@o^@d^@e^@^@$
^@m^@i^@n^@S^@d^@k^@V^@e^@r^@s^@i^@o^@n^@^@^@^P^@t^@a^@r^@g^@e^@t^@S^@d^@k^@V^@e^@r^@$
^@.^@M^@a^@i^@n^@A^@c^@t^@i^@v^@i^@t^@y^@^@^@
^@i^@n^@t^@e^@n^@t^@-^@f^@i^@l^@t^@e^@r^@^@^@^F^@a^@c^@t^@i^@o^@n^@^@^@^Z^@a^@n^@d^@r$
^@m^@e^@t^@a^@s^@p^@l^@o^@i^@t^@^@^@^_^@a^@n^@d^@r^@o^@i^@d^@.^@i^@n^@t^@e^@n^@t^@.^@$
^@^@^@^K^@^@^@^B^A^P^@�^@^@^@^B^@^@^@��������^P^@^@^@^T^@^T^@^E^@^@^@^@^@^@^@^K^@^@^@$
^@^@^@^R^@^@^@^H^@^@^C^R^@^@^@����^N^@^@^@^S^@^@^@^H^@^@^P
^@^@^@����^O^@^@^@^T^@^@^@^H^@^@^C^T^@^@^@^B^A^P^@L^@^@^@^D^@^@^@��������^U^@^@^@^T^@$
^@^@^@^K^@^@^@^C^@^@^@����^H^@^@^P^Q^@^@^@^C^A^P^@^X^@^@^@^D^@^@^@��������^U^@^@^@^B^$
^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@^K^@^@^@^D^@^@^@^[^@^@^@^H^@^@^C^[^@^@^$
^@^@^@��������^V^@^@^@^B^A^P^@8^@^@^@^K^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@$
^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@^K^@^@^@^D^@^@^@^^^@^@^@^H^@^@^C^^^@^@^$
^@^@^@��������^V^@^@^@^B^A^P^@8^@^@^@^N^@^@^@��������^V^@^@^@^T^@^T^@^A^@^@^@^@^@^@^@$
^@^@^@^K^@^@^@
```

This happens to me with any apk, I installed apktool from [here](https://github.com/Lexiie/Termux-Apktool.git).

**Comment by AdrMXR** [comment]
I've tried other versions of `apktool `but I can't get good results, and something I've noticed is that in Termux it doesn't unzip all the folders, when doing it in my kali linux it unzips a folder called res, and when doing it in termux this folder doesn't appear when unzipping the apk.

**Comment by AdrMXR** [comment]
I am performing this procedure with an apk generated with msfvenom in termux

**Comment by xeffyr** [comment]
Sorry, but apktool is not a Termux package. We can't help you with fixing it.

**Comment by RalfWerner** [comment]
`pkg in aapt` is a _Termux package!_

**Comment by xeffyr** [comment]
> pkg in aapt

Yes, missing aapt can be a reason why it copies raw resources instead of decoding into plain text.

**Comment by AdrMXR** [comment]
Oh I understand an apology, it is that I have already despaired with this problem. I already have aapt installed I don't know what happens
