### ISSUE TITLE
library "libicuuc.so.66" not found

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-app#1765]
i had been installed R-base in termux ,everything is ok. but after  i run pkg update today,  it seems damaged the R-base or termux system.  it comes out error  library "libicuuc.so.66" not found . Could some one help me fix the issue ? or has some measures to avoid such proplem , **.so could not found. Thanks.

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/bit/libs/bit.so':
  dlopen failed: library "libicuuc.so.66" not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘RSQLite’
* removing ‘/data/data/com.termux/files/usr/lib/R/library/RSQLite’
* restoring previous ‘/data/data/com.termux/files/usr/lib/R/library/RSQLite’

```

**Comment by xeffyr** [comment]
Closing as issue with **third-party** package.
