### ISSUE TITLE
Missing echo of alphabetic keyboard strokes. 

### ISSUE THREAD

**Issue by bruncsak** [termux/termux-app#1766]
**Problem description**

I am using virtual keyboard. At the shell prompt, alphabetic characters are not echoed until I hit space, numeric or punctuation character.

**Steps to reproduce**

Always like that no special configuration needed.

**Expected behavior**

Each alphabetic character should be echoed immediately. 

**Additional information**

* Termux application version: 0.99
* Android OS version: 9
* Device model: SM-G955F

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/issues/5830#issuecomment-695369758

**Comment by bruncsak** [comment]
Thanks, working great now. Do the Android 9 maintainers know about this?

**Comment by Grimler91** [comment]
@bruncsak it's an issue with samsung devices, and not only on android 9. It was supposedly reported to samsung according to https://github.com/termux/termux-app/issues/686#issuecomment-648135346
