### ISSUE TITLE
CRITICAL: cannot export env variables through script:bash

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#1767]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: latest
* Android OS version: 10
* Device model: Samsung Galaxy Note 10+ - latest updates and patches installed

**Comment by xeffyr** [comment]
> cannot export env variables through script

What does that mean?

Are you trying to export variables in current shell by executing script? - That won't work because impossible by Linux processes design and security reasons.

In order to export variables, you need to source it. Example: `source script.sh`.

**Comment by nathaneltitane** [comment]
@xeffyr - exactly my point: even doing 'source script.sh' through another script results in the export not working - also: the export used to work just fine a few versions ago using my linux-dextop setup script.

**Comment by xeffyr** [comment]
Post the example of code which does not work and steps how to reproduce the issue.

**Comment by nathaneltitane** [comment]
@xeffyr  - from my repo: github.com/nathaneltitane/linux-dextop

ˋˋˋ
#!/bin/bash

# Author: Nathanel Titane - nathanel.titane@gmail.com

# linux-dextop # Linux on Android # Termux Dextop // Ubuntu Dextop #

# script #

script=$(basename -- "${BASH_SOURCE[0]}")

# version #

version="09-20-2020"

# variables #

option=$1
output=$2

# set defaults

if [ -z $option ]
then
	option="full"
fi

if [ -z $output ]
then
	output="vnc"
fi

# usage #

while (($#))
do
	case "$1" in
		-b|--base)
			option="base"
			;;
		-f|--full)
			option="full"
			;;
		-m|--minimal)
			option="minimal"
			;;
		-v|--vnc)
			output="vnc"
			;;
		-x|--xorg)
			output="xorg"
			;;
		-h|--help)
			echo -e ""
			echo -e "USAGE:"
			echo -e ""
			echo -e "-b, --base \t Base setup: download and unpack root filesystem and utilities."
			echo -e "-f, --full \t Full setup: download and install full desktop environment and utilities."
			echo -e "-m, --minimal \t Minimal setup: download and install minimal set of utilities:."
			echo -e " \t\t Note:"
			echo -e " \t\t this option is ideal for running specific applications and their dependencies only."
			echo -e ""
			echo -e "-h, --help \t Show help and usage."
			echo -e "-v, --version \t Show ${script} version."
			echo -e ""
			exit
			;;
		-v|--version)
			echo -e ""
			echo -e "$script $version"
			echo -e ""
			exit
			;;
		*)
			echo -e ""
			echo -e "$script: Unknown option $1"
			echo -e "Type './$script --help' for help and usage information."
			echo -e ""
			exit
			;;
		esac
	shift
done

# write globals

cat << 'FILE' > /data/data/com.termux/files/usr/bin/globals
export SETUP_OPTION="${option}"
export SETUP_OUTPUT="${output}"
export SETUP_DIRECTORY="${PREFIX%/*}"
export BINARIES_DIRECTORY="${PREFIX}"/bin
export LIBRARIES_DIRECTORY="${PREFIX}"/lib
export PROOT_DIRECTORY="${SETUP_DIRECTORY}"/img
export BIND_DIRECTORY="${SETUP_DIRECTORY}"/mnt
export INITIAL_DIRECTORY="${PWD}"
FILE

source /data/data/com.termux/files/usr/bin/globals

# set work directory

cd "${SETUP_DIRECTORY}" || exit 1

# dependencies #

# emulate console.fwd until dependencies are loaded

echo "[ > ] Copying necessary binary files."
echo

# binaries #

binaries_list=(
	console
	check-architecture
	create-user
	proot-environment
	proot-image
	proot-launch
	proot-packages
	proot-setup
	remove-files
	termux-environment
	termux-groups
	termux-packages
	termux-storage
	user-information
	vnc-pass
	vnc-start
	vnc-stop
	xfconf-read
	xfconf-write
)

for binary in ${binaries_list[@]}
do
	binary_url=bin-dex.ntttn.me/"$binary"

	# get binaries from repository

	curl -sL ${binary_url} > "$BINARIES_DIRECTORY/$binary" &

	echo  " [ > ] Downloading binary [ $binary ]."
	echo

	# set execution mode for binary

	chmod +x "$BINARIES_DIRECTORY/$binary"
done

source /data/data/com.termux/files/usr/bin/console

# proceed with setup

console.fwd "Preparing environment..."
echo

# setup #

# get user information

"$BINARIES_DIRECTORY"/user-information

# setup transient storage - termux <<< device >>> proot

"$BINARIES_DIRECTORY"/termux-storage

# setup termux package requirements

"$BINARIES_DIRECTORY"/termux-packages

# verify architecture match

"$BINARIES_DIRECTORY"/check-architecture

# download and setup image

"$BINARIES_DIRECTORY"/proot-image

# download and setup configurations into proot directories

configurations_list=(
	i3-settings
	xfce4-settings
)

for configuration in ${configurations_list[@]}
do
	configuration_url=cfg-dex.ntttn.me/"$configuration"

	# get configurations from repository

	curl -sL ${configuration_url} > "$PROOT_DIRECTORY"/tmp/"$configuration" &

	console.spinner "Downloading configuration [ $configuration ]."
	echo

done

console.info "Copied necessary configuration files."
echo

# download and setup images into proot directories

images_list=(
	bird.png
	bird.svg
)

for image in ${images_list[@]}
do
	image_url=img-dex.ntttn.me/"$image"

	# get imageses from repository

	curl -sL ${image_url} > "$PROOT_DIRECTORY"/usr/share/backgrounds/"$image" &

	console.spinner "Downloading image [ $image ]."
	echo

done

console.info "Copied necessary image files."
echo

# download and setup libraries into proot directories

libraries_list=(
	libandroid-shmem-aarch64.so
)

for library in ${libraries_list[@]}
do
	library_url=lib-dex.ntttn.me/"$library"

	# get libraries from repository

	curl -sL ${library_url} > "$PROOT_DIRECTORY"/lib/"$library" &

	console.spinner "Downloading library [ $library ]."
	echo

done

console.info "Copied necessary library files."
echo

# transfer termux unregitered group IDs into proot

termux-groups

# setup termux environment requirements

termux-environment

# setup proot environment requirements

proot-environment

# setup proot system requirements

proot-setup

# cleanup #

# purge all setup traces:
# use BASH_SROUCE for all bash-specific invocations to the script path:
# $0 is POSIX compliant and may not always return the correct value.

# rm $INITIAL_DIRECTORY/${BASH_SOURCE[0]}

# automatic proot setup transition:
# run 'proot-launch' as 'root' through shell and continue setup in that environment

$BINARIES_DIRECTORY/bash -c 'proot-launch'
ˋˋˋ

**Comment by xeffyr** [comment]
export is working, see screenshot:
![Screenshot_20200922-034320_Termux](https://user-images.githubusercontent.com/25881154/93834937-4021de00-fc86-11ea-87c0-d2933da0260f.png)

***

I'll assume you have issue in https://github.com/nathaneltitane/linux-dextop/blob/master/setup#L86: you are expecting that variables will be replaced, right? In your code, they won't, as `cat << 'FILE'` should be `cat << FILE`.

**Comment by xeffyr** [comment]
If issue is not with
```
export SETUP_OPTION="${option}"
export SETUP_OUTPUT="${output}"
```
being empty, then show relevant place.

**Comment by nathaneltitane** [comment]
@xeffyr 

what happens when you run source vars.sh from another bash script?

**Comment by xeffyr** [comment]
Variable is being exported as it should:
![Screenshot_20200922-035241_Termux](https://user-images.githubusercontent.com/25881154/93835189-2339da80-fc87-11ea-8982-1f5c6ad1d423.png)

**Comment by nathaneltitane** [comment]
> export is working, see screenshot:
> ![Screenshot_20200922-034320_Termux](https://user-images.githubusercontent.com/25881154/93834937-4021de00-fc86-11ea-87c0-d2933da0260f.png)
> 
> I'll assume you have issue in https://github.com/nathaneltitane/linux-dextop/blob/master/setup#L86: you are expecting that variables will be replaced, right? In your code, they won't, as `cat << 'FILE'` should be `cat << FILE`.

actually not, I rely on your $PREFIX env preset - option and output are defaulted if empty at the top of the setup

**Comment by xeffyr** [comment]
Anyway, you have issues with heredoc.

![Screenshot_20200922-035644_Termux](https://user-images.githubusercontent.com/25881154/93835381-ae1ad500-fc87-11ea-99cc-f64da7b162b2.png)

**Comment by xeffyr** [comment]
In `setup` you should have
```
export PROOT_DIRECTORY="\${SETUP_DIRECTORY}"/img
export BIND_DIRECTORY="\${SETUP_DIRECTORY}"/mnt
```
Then globals will be generated properly.

**Comment by nathaneltitane** [comment]
> In `setup` you should have
> 
> ```
> export PROOT_DIRECTORY="\${SETUP_DIRECTORY}"/img
> export BIND_DIRECTORY="\${SETUP_DIRECTORY}"/mnt
> ```
> 
> Then globals will be generated properly.

will review my code. sorry for the trouble

**Comment by nathaneltitane** [comment]
@xeffyr 

no dice - variables are properly set in the script, bash -x returns that the values are exported but they do not show up in env...

**Comment by nathaneltitane** [comment]
@xeffyr 

run this and tell me if export still actually works...

`#!/bin/bash

cat << 'FILE' > poop-out
export FOOOO=BAAAAR
FILE

source poop-out`

**Comment by xeffyr** [comment]
> By Linux processes design and security reasons, process cannot modify environment variables of parent.

**Comment by nathaneltitane** [comment]
> > By Linux processes design and security reasons, process cannot modify environment variables of parent.

well Ican assure you it did a few versions ago....

**Comment by xeffyr** [comment]
That never worked on any Bash versions because that's not possible. Violates process memory separation.

**Comment by xeffyr** [comment]
You need to source into **current** shell.

**Comment by xeffyr** [comment]
This will not work:
```
bash script_with_source.sh
echo $FOO
```

But this will:
```
source script_with_source.sh
echo $FOO
```

**Comment by ZalgoNoise** [comment]
That is expected when you launch a shell session that sources your variables and immediately to exits.

So your second example works because the active shell session is loaded with the variables from the script.

**Comment by nathaneltitane** [comment]
> That is expected as you launch a shell session that sources your variables but immediately exits.
> 
> So your second example works because the active shell session is loaded with the variables from the script.
> 
> (for context)

took @xeffyr 's recommmendations and got everything working. got it after reading up on kernel security and shell exec
