### ISSUE TITLE
The View Network Connection function is no good for specific Proxy or VPN connection

### ISSUE THREAD

**Issue by stevenx2010** [termux/termux-app#1768]
**Problem description**
The ability to View Network Connection in new version of Termux is good. But in my use case, it won't work! 

My use case is:
Hiding ports of proxy software such as shadowsocks, etc. through SSH channel with port forwarding.

1st step: use Termux to set up a SSH channel with port forwarding;
2nd step: use proxy software such as shadowsocks to set up VPN connection by use of the above SSH channel;

Once the proxy (VPN) connection has been built, the Termux changes to use the proxy (VPN) connection automatically, then it creates a connection cycle! No more internet connections. 

However, the old versions without View Network Connection have no such problem.

The correct connection flow should be: Browser --> VPN connection through SSH channel  --> SSH channel by Termux --> Remote Server --> Internet accessing

However with the View Network Connection of Termux, the flow becomes:

Browser --> VPN connection through SSH channel --> SSH channel by Termux (changed to VPN automatically because of View Network Connection) --> VPN connection through SSH channel (Connection Cycle!)

Suggestion: add an option in Setting of Termux to switch on/off the View Network Connection function.

**Steps to reproduce**
As above
 
**Expected behavior**
The proxy softwares can use the SSH channel set up by Termux, other than Termux use the VPN connection created by proxy software

**Additional information**

* Termux application version: 0.99
* Android OS version: 10
* Device model: Huawei P40

**Comment by xeffyr** [comment]
Please note that Termux is a regular application. It doesn't manage networking on its own. Thus, to break the loop you will need to add Termux application to VPN exceptions in your proxy software if possible.

**Comment by stevenx2010** [comment]
Sorry, the functional description of Termux in F-Droid misled me. Finally, I found it's the problem of old version of shadowsocks in latest Android. Updating shadowsocks to latest version solved the problem. thanks!
