### ISSUE TITLE
feature request: 

### ISSUE THREAD

**Issue by ljca** [termux/termux-app#1769]
**Feature description**
Can I support Chinese input after connecting the physical keyboard?

**Reference implementation**

**Comment by xeffyr** [comment]
This is **question** or **feature request**? Also provide more information.

Do you have problems with writing in Chinese when using physical keyboard?

**Comment by ljca** [comment]
Well, this is should be a bug.
When I use termux, I hope I can input Chinese even when connected to a physical keyboard, but unfortunately I can’t input Chinese even when I switch the input method. Please forgive my poor English explanation, I used a translation

**Comment by xeffyr** [comment]
> I can’t input Chinese even when I switch the input method.

Ok, you have a variation of https://github.com/termux/termux-app/issues/250 and https://github.com/termux/termux-app/issues/705.

Closing as issue is with general handling of hardware keyboard and not with specific input method/language.
