### ISSUE TITLE
undefined reference to `_mcount'

### ISSUE THREAD

**Issue by guozhenduo** [termux/termux-app#1771]
I'm run a commoand in zsh:
```
clang -pg No01.c 
```

Then print the following error:
```
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/tmp/No01-3b5a7a.o: in function `main':
No01.c:(.text+0x20): undefined reference to `_mcount'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

Does termux's clang compiler not support the pg option?

**Comment by xeffyr** [comment]
You need package uftrace in order to use that feature. It has libmcount.so which adds missing symbol.

**Comment by guozhenduo** [comment]
Thank you, @xeffyr .

**Comment by guozhenduo** [comment]
I ran a.out, but I printed the error below:
mcount: /home/builder/.termux-build/uftrace/src/libmcount/record.c:1150:record_proc_maps     ERROR: cannot open for writing maps file: No such file or directory

**Comment by guozhenduo** [comment]
What will I do.

**Comment by xeffyr** [comment]
@guozhenduo Trying to open /proc/PID/maps for writing? That's not possible as file is RO...

**Comment by xeffyr** [comment]
> I ran a.out

`clang -pg` isn't standalone and can't be used like with GCC. You need external utility for profiling and that's why I suggested uftrace.

See usage below:
![Screenshot_20200929-122023_Termux](https://user-images.githubusercontent.com/25881154/94539662-35e77d00-024e-11eb-9ae1-3152e0a1cfe3.png)

**Comment by guozhenduo** [comment]
Okay.
