### ISSUE TITLE
Termux能够增加汉化吗？

### ISSUE THREAD

**Issue by Zacharia2** [termux/termux-app#1772]

**Comment by Zacharia2** [comment]
Can we increase the Sinicization?

termux是一个比较好的APP，希望能有给它做个汉化。

**Comment by Zacharia2** [comment]
Termux is a good app. I hope it can be translated into Chinese.

**Comment by Grimler91** [comment]
There are a few closed PRs for adding a simplified Chinese translation (and for various other languages). However, even if we translate the app all the programs would still be in English only, so we are so far not considering adding more languages to the app.
