### ISSUE TITLE
Unable to run command a second session created

### ISSUE THREAD

**Issue by metadata007** [termux/termux-app#1777]
**Problem description**

I was unable to run package installation command on one session while another session is running package installation command

**Steps to reproduce**

**Expected behavior**

Able to run several package installation command on different session simultaneously

**Additional information**

* Termux application version: 0.101
* Android OS version: 10
* Device model: Tecno mobile l

I was unable to run package installation commands on second session I created, package installation command on the second section was Unable to run, the package installation command on second session can run only if the package installation command on First session completed.

Which means I can't run package installation command on different session at the same time, I'm reporting this because the old version was not like this, all of this started after I updated it to new version

This is the error I got:
E: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock - open (11: Try again)
E: Unable to lock the administration directory (/data/data/com.termux/files/usr/var/lib/dpkg/), is another process using it?

Can you kindly fix this and update to new version or is there a command I can run to fix this

**Comment by kcubeterm** [comment]
dpkg locks itself so that two process don't update content simultaneously. It prevents you from breakage and dependancy error.

 It's not an error. Let first session finish his job and then install another.

BTW, you can install multiple package with comma separated list e.g

```
pkg install python, rust, apache2 
```
