### ISSUE TITLE
Q: How to delete residual files from Termux

### ISSUE THREAD

**Issue by sobaee** [termux/termux-app#1778]
Hi developer
 I used Pyglossary for conversion process of glossaries, but after completing or if any issue happen woth conversion, the residual files remains in Termux data, so its data increasing to be very large.

I don't know how to remove this data without affecting the basic data of Termux

**Comment by xeffyr** [comment]
Check files in your `$HOME`, remove ones which you don't need.

Also look into directory `$PREFIX/tmp` and remove files from there. Do not touch everything else.

**Comment by sobaee** [comment]
They found at $PREFIX/tmp
I successfully removed them.
Thanks a lot 🙏
