### ISSUE TITLE
Occasionally pip stops working

### ISSUE THREAD

**Issue by ShyPixie** [termux/termux-app#178]
Occasionally the pip stops working, and I have to close the terminal and open it again to return to normal.

The command ends with this error:

File "/data/data/com.termux/files/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/usr'

This was expected?

**Comment by fornwall** [comment]
Could you post the complete error message/stack trace?
