### ISSUE TITLE
Termux:Boot - trojan detected by Malwarebytes on Android

### ISSUE THREAD

**Issue by PeterTGarner** [termux/termux-app#1784]
Android/Trojan.Boogr.gsh

/data/app/com.termux.boot/N3iRmCwlX86Ax1CpN4DlyQ==/base.apk

Termux:Boot

Deleted

Installed some time ago from Google Play Store. Phone is power cycled every night.

**Comment by xeffyr** [comment]
False positive & known issue which will not be solved.

I won't be surprised if `Android/Trojan.Boogr.gsh` borrowed some Termux:Boot code related to on-boot jobs.

**Comment by trygveaa** [comment]
Report it to Malwarebytes?

**Comment by PeterTGarner** [comment]
Thanks! I'll be reporting it.

**Comment by xeffyr** [comment]
FYI, VirusTotal scan of Termux:Boot from F-Droid: https://www.virustotal.com/gui/file/35cae49192d073151e3177956ea4f1d6309c2330fed42ec046cbb44cee072a32/detection

8 from 64. engines detect it as "virus". Interesting that *Malwarebytes* here does not recognize as infected.
