### ISSUE TITLE
Not a real bug, but which version is correct ?

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#1786]
I have version 0.99, and now I see the newest version is 0.101, which appears much older (or a different branch) ?
I'd expect version 0.99 would be followed by 1.00, 1.01, etc.
Is 1.01 of the same branch as 0.99 ?

**Comment by trygveaa** [comment]
0.101 is the most recent. 101 is bigger than 99, the number of digits doesn't matter, each part separated by `.` is separate. You can also see at https://github.com/termux/termux-app/releases that 0.101 was released 10 days ago from master.

**Comment by xeffyr** [comment]
> I'd expect version 0.99 would be followed by 1.00, 1.01, etc.

Versioning has format of X.Y, where:
* X is a major number meaning **drastic, incompatible changes** with further serious impact on user experience. Solving https://github.com/termux/termux-packages/wiki/Termux-and-Android-10 will involve releasing of Termux 1.0.
* Y is a patch level. Bugfixes & new features.

Assume that 0.101 is just a 101th release of Termux.
