### ISSUE TITLE
Command control buggy for bash shell

### ISSUE THREAD

**Issue by isodecryptor** [termux/termux-app#1788]
**Problem description**

My shell scripts are not finishing command 1 before executing command 2. Causing unpredictable execution of commands. One example would be a file being not found in the first execution of the bash shell script. Executing it a second time leads to the conclusion the file does exist. This leads to the conclusion that the command control flow in bash is buggy and not completing command1 before executing command2. 
**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:. .101
* Android OS version: android 9 
* Device model: samsung j737t

**Comment by Grimler91** [comment]
Could you share the scripts? 

Which shell are you using?

How are you running them (from the command line, from termux-boot, from termux-widget)?

**Comment by isodecryptor** [comment]
Yes, so i noticed if i copy and past multiple commands such as

pkg update
pkg upgrade
pkg install git
git clone..
Bash shell. I caught the shells command flow being illogical. It appears
that some commands do not wait for the exit code of the previous command.

An example would be
#!/bin/bash
pkg install proot-distro
proot-distro install ubuntu
proot-distro login ubuntu

mv directory/file directory/file

The shell throws the "abort "when copying and pasting multiple commands
when asking for user input such as yes.

My shell script in the example above would run all the way through proot
installation but then say that the file to move does not exist. A second
execution of the script and the file is where to be expected. I switched to
dash and there is command flow issues similar to the above. This was only
noticeable since today. Something has changed. Rolled back to older version
and still noticed. Even did a phone wipe to the beggining. Sudden change in
command control flow. Still persist in factory reset. No clue how but the
commands are not waiting for the other command to complete. Or pasting
multiple commands leads to abort after user input. This seems to be a
severe issue with logic flow of any shell and has stopped progress for rtmp
server development, which i had, fully, functional just yester with nginx.
Impressive software. But this sudden change in command flow from the shell
is not predictable or bash compliant.

**Comment by Grimler91** [comment]
> It appears that some commands do not wait for the exit code of the previous command

I have not noticed such a problem in my everyday usage of termux

> The shell throws the "abort "when copying and pasting multiple commands
when asking for user input such as yes.

If you copy paste multiple commands but some of the commands expect input then your commands will not work as expected, that's how bash works and not a termux issue, maybe this is what happens with your script as well.

**Comment by xeffyr** [comment]
> Yes, so i noticed if i copy and past multiple commands such as

>pkg update
pkg upgrade
pkg install git
git clone..
Bash shell. I caught the shells command flow being illogical. It appears
that some commands do not wait for the exit code of the previous command.

>An example would be
#!/bin/bash
pkg install proot-distro
proot-distro install ubuntu
proot-distro login ubuntu

>mv directory/file directory/file

**Please provide EXACT steps to reproduce.** Full commands with all arguments and file paths. Also you need to provide:
* Screenshot
* `strace -o log.txt -fv -s 2000 bash ./yourscript.sh` - will be long, so upload `log.txt` to pastebin service.
* Scripts causing issue for you.

I never got any issues with Bash and I guess you are first who got "illogical shell control flow". We need a proof of existence of that issue, to exclude so-called "user error" and shell scripting misunderstanding.

> My shell script in the example above would run all the way through proot installation but then say that the file to move does not exist.

It will not run all the way through proot installation... To run commands in your proot installation, you need to log into proot'ed environment and run script from there.

> This was only noticeable since today. Something has changed. Rolled back to older version
and still noticed. Even did a phone wipe to the beggining. Sudden change in
command control flow. Still persist in factory reset.

We have not released any shell updates.

***

I'm closing this for now.

**Comment by isodecryptor** [comment]
Would you consider adding alpine 3.12 as an option in proot-distro. Every
since the alpine upgrade, git commands do not seem to work as expected. It
appears to be an issue with ca-certificates.
