### ISSUE TITLE
Termux suddenly closed when more cpu or memory used

### ISSUE THREAD

**Issue by sobaee** [termux/termux-app#1789]
Hello dear developers

I use Termux for glossary converting tool "pyglossary", when I try to convert a big glossary Termux closed suddenly when the process reach to 99.9%,
N.B: I did everything to prevent closing (kept termux notification and locked it in recent apps, added exeption for Termux in battery and memory optimization, closed every app other than Termux, run it infront of other apps with light on and I kept cooling my phone with fun.

N.B: converting smaller glossaries of the same type done smoothly "so, it is not pyglossary issue"
N.B: During the process, cpu usage reach to 100% many times and sometimes android tells me that python use more cpu and I close this message. But no memory or storage space problems.

I hope you suggest or make any solution.
Thanks a lot 🙏

**Comment by xeffyr** [comment]
Nothing can prevent Termux from being closed once certain memory usage threshold is reached. Safe memory usage by any application on Android is no more than 50%. Beyond that, probabilities of triggering OOM killer drastically increase.

Android devices are focusing on system stability and multitasking, they are not designed for processing large amounts of data.

>  added exeption for Termux in battery and memory optimization

Android does not have such thing as "exceptions for memory optimization".

> But no memory or storage space problems.

Really? Then how Termux reached out-of-memory condition (crash)?

**Comment by sobaee** [comment]
Sorry, my mistake 
I edited the comment to be slightly perfect as you may like to see.

About apps that aren't checked by Device care, this picture may help to show what I main:
![Screenshot_20201010212256](https://user-images.githubusercontent.com/65910585/95662333-dbe49280-0b3e-11eb-9e99-5f9439eda3df.jpg)

Thanks for your quick response, and understanding.

One more thing,
 Cpu has no thing to do with this crash?

**Comment by xeffyr** [comment]
> About apps that aren't checked by Device care, this picture may help to show what I main:

Device Care has nothing to do with lowmemorykiller (kernel driver) or lmkd (userspace) and can't configure them.

> Cpu overusing has no thing to do with this crash?

CPU overusing causes device heating and quickly drains battery charge, nothing more.

***

Suggesting to try
```
ulimit -m $((256 * 1024))
ulimit -v $((256 * 1024))
```
to limit memory allocations to 256MiB max. You may change "256" to some other value, e.g. 512.

**Comment by sobaee** [comment]
Many thanks
I appreciate that 🙏
