### ISSUE TITLE
Could GUI apps run from Termux be run in a "kiosk" mode?

### ISSUE THREAD

**Issue by dumblob** [termux/termux-app#1794]
**Feature description**

I'd imagine any application supporing fullscreen could be turned to kiosk mode (i.e. swallow all input - be it from the user or system).

**Reference implementation**

Does another app/terminal emulator have this feature?

I don't know any (I've googled it and there are only commercial apps on Google Play, but nothing which would allow running arbitrary GUI fullscreen termux app as kiosk).

**Comment by xeffyr** [comment]
If you mean "GUI" as "X11 application", then it can't.
