### ISSUE TITLE
ERROR {   err: [Error: EACCES: permission denied, open '/data/data/com.termux/files/home/xxxxx

### ISSUE THREAD

**Issue by forliuyifei** [termux/termux-app#1799]
**Problem description**

I'm a hexo blogger, building hexo on my PC & Android phone.
Everything is OK on the Git Bash, when I use termux, run `hexo clean && hexo g && hexo s`, it still seems fine ( `Hexo is running at http://localhost:4000` ).
But if I change any files in the hexo blog folder, it display an error **permission denied**.

**Steps to reproduce**

Here comes the error codes:
```
ERROR {
  err: [Error: EACCES: permission denied, open '/data/data/com.termux/files/home/loafing.cn/source/_posts/adb-notes.md'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/data/data/com.termux/files/home/loafing.cn/source/_posts/adb-notes.md'
  }
} Process failed: %s _posts/adb-notes.md
```

**Expected behavior**

**Additional information**

* Termux application version: 0.101
* Android OS version: Android 10（QQ3A.200805.001
PixelExperience_Plus_lavender-10.0-20201014-2254-OFFICIAL）
* Device model: Redmi Note 7（lavender）
* Magisk 20.4，manager 8.02 (307）

**Comment by forliuyifei** [comment]
![Screenshot_20201023-125422592](https://cdn.jsdelivr.net/gh/forliuyifei/img@mater/img/2020/10/1603430791772.webp)

**Comment by xeffyr** [comment]
Seems like permission or SELinux problem. Have you ever used root for accessing Termux home directory?

Editing files as root in Termux is a typical case of such problem, especially when SELinux is `enforcing`. If you don't use/have root permissions, then ensure that files have at least `600` (rw-------) access mode.

**Comment by forliuyifei** [comment]
> Seems like permission or SELinux problem. Have you ever used root for accessing Termux home directory?
> 
> Editing files as root in Termux is a typical case of such problem, especially when SELinux is `enforcing`. If you don't use root permissions, then ensure that files have at least `600` (rw-------) access mode.

Yes, I have used root for accessing Termux home directory, but it still "permission denied" when files changed.

Let me try shared directory tomorrow 🤧

**Comment by forliuyifei** [comment]
Unfortunately, using the shared directory is not helpful either 😭
When I run 
`cd ~/storage/shared/blog/test`
`npm install`
```
npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../atob/bin/atob.js
npm ERR! dest /storage/emulated/0/blog/test/node_modules/.bin/atob
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../atob/bin/atob.js' -> '/storage/emulated/0/blog/test/node_modules/.bin/atob'
npm ERR!  [OperationalError: EPERM: operation not permitted, symlink '../atob/bin/atob.js' -> '/storage/emulated/0/blog/test/node_modules/.bin/atob'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, symlink '../atob/bin/atob.js' -> '/storage/emulated/0/blog/test/node_modules/.bin/atob'] {
npm ERR!     errno: -1,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'symlink',
npm ERR!     path: '../atob/bin/atob.js',
npm ERR!     dest: '/storage/emulated/0/blog/test/node_modules/.bin/atob'
npm ERR!   },
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../atob/bin/atob.js',
npm ERR!   dest: '/storage/emulated/0/blog/test/node_modules/.bin/atob',
npm ERR!   parent: 'test'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2020-10-23T17_24_52_014Z-debug.log
```

**Comment by xeffyr** [comment]
> I have used root for accessing Termux home directory

That's an answer why you have permission denial. *Really I can't expect something else here... Common issue.*

You just have messed up SELinux labels on files. Ensure that everything has proper ownership (Termux uid) and do as root
```
restorecon -Rv /data/data/com.termux/files
```
and NEVER edit files in Termux home as root anymore, at least if you are not aware of how file permissions work on Android.

Termux provides possibilities of rootless access to home directory. https://wiki.termux.com/wiki/Internal_and_external_storage#Access_Termux_from_file_manager

> Unfortunately, using the shared directory is not helpful either

Shared storage, as well as any vFAT (FAT32) or exFAT file systems, does not support file permissions, execution and symlinks.

All work should be done in Termux home directory.

***

Closing as *expected behavior*.
