### ISSUE TITLE
repository is disabled now.

### ISSUE THREAD

**Issue by HafizZiq** [termux/termux-app#1802]
another one
![Screenshot_20201027-065257186](https://user-images.githubusercontent.com/46204743/97237190-a8ce1e80-1821-11eb-814e-ca3bf9da853f.jpg)

**Comment by xeffyr** [comment]
`termux-mirror.ml` is under maintenance and is **disabled**.

Don't use `apt` or `apt-get`, but use `pkg` instead - it will select working mirror automatically. Otherwise use `termux-change-repo`.
