### ISSUE TITLE
Execution failed for task ':app:setupBootstraps' in branch 'android-10'

### ISSUE THREAD

**Issue by nokotan** [termux/termux-app#1806]
#### Problem description

Building termux from source fails with error **Execution failed for task ':app:setupBootstraps'.**
Seems that `java.io.FileInputStream.transferTo()` is introduced in Java 9, not usuable in Java 8.

```sh
Execution failed for task ':app:setupBootstraps'.
> No signature of method: java.io.FileInputStream.transferTo() is applicable for argument types: (FileOutputStream) values: [java.io.FileOutputStream@9822dc2]
```

####  Steps to reproduce

- Clone termux repository
- Check out android-10 branch
- Launch android studio and open the directory that contains termux project files
- Start build

####  Expected behavior

Successful build

####  Additional information

* Host machine: Android Studio 4.1 on Windows 10
* Android gradle plugin version: 4.0.1
* Gradle version: 6.5.1
* Gradle JDK version: 1.8
* Android target SDK: 29.5

**Comment by xeffyr** [comment]
> Seems that java.io.FileInputStream.transferTo() is introduced in Java 9, not usuable in Java 8.

We use Java 11.

https://github.com/termux/termux-app/blob/android-10/.github/workflows/debug_build.yml#L22

> Host machine: Android Studio 4.1 on Windows 10

Windows hosts are not supported currently as whole Termux development is done on Linux-based OS.

**Comment by nokotan** [comment]
Specifing JDK location in `File > Project Structure > SDK Location` to my JDK 11 installation gives me successful build.
Thank you for your advise and Happy coding :)

**Comment by Argo18** [comment]
Is therw a new command on termux
