### ISSUE TITLE
Can't run `su` on a rooted device

### ISSUE THREAD

**Issue by DaKnig** [termux/termux-app#1807]
**Problem description**

Previously I could run `su` and `sudo su` but now I can't. when I run `su` it just says "permission denied" without popping up the Magisk dialog. Magisk doesnt even have Termux in the list as neither allowed nor forbidden entry. I can use the Android Terminal Emulator app just fine with su. maybe some new Termux update broke it.

**Steps to reproduce**

1. open termux
2. run `su` or `sudo (something)`
3. permission denied. no poppup asking me about root permissions.

**Expected behavior**

a poppup appears asking for root permissions.

**Additional information**

* Termux application version: 0.102
* Android OS version: 8.0.0
* Device model: Samsung Galaxy S8

**Comment by ZalgoNoise** [comment]
Install the `tsu` package with `pkg in tsu`, then use it to launch a root wrapper for termux.

**Comment by DaKnig** [comment]
I already had tsu installed; tried many things, reinstalling the app worked for me (but for some reason deleting the app data did not). works now.
