### ISSUE TITLE
How to get mosquitto.conf file ?

### ISSUE THREAD

**Issue by AnkurJagani** [termux/termux-app#1809]
Hi there,

How to check `mosquitto.conf` file for changing some configurations? I failed to find the file while I was looking at `/etc` directory inside my non-rooted android device. Not to mention, I have successfully installed the mosquitto package with the help of `pkg install mosquitto`. 

Thanks,
Ankur J.

**Comment by xeffyr** [comment]
>  failed to find the file while I was looking at /etc directory inside my non-rooted android device.

File is at
```
/data/data/com.termux/files/usr/etc/mosquitto/mosquitto.conf
```
as Termux does not comply with File System Hierarchy standard.

**Comment by AnkurJagani** [comment]
as I have clearly mentioned that I am on non-rotted android device. navigating to the `/data/data/com.termux/files/usr/etc/mosquitto/mosquitto.conf` is unsuccessful. can you help to fire the command to see how can we open the `mosquitto.conf` file inside termux?

**Comment by xeffyr** [comment]
> as I have clearly mentioned that I am on non-rotted android device. 

... Did you know that Termux already stores its env in `/data/data/com.termux/files/usr` and can access this path without root? Did you know that Termux has text editors like `vim`, `nano` ?

Running a simple command like `pwd` in Termux environment or reading Termux Wiki will allow to figure out how to do lots of things. https://wiki.termux.com/wiki/Differences_from_Linux

If you don't want to use command line text editors, then unfortunately we can't help you.

> navigating to the /data/data/com.termux/files/usr/etc/mosquitto/mosquitto.conf is unsuccessful.

```
nano /data/data/com.termux/files/usr/etc/mosquitto/mosquitto.conf
```
was always successfull.
