### ISSUE TITLE
Selected red text is invisible w/ default color scheme

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-app#181]
With current default color scheme, When the red text is selected, it is almost invisible.

The escape code for red text is "^[[31m^[[1m".

**Comment by xeffyr** [comment]
Closing as this should be already fixed. Termux now uses reverse colors for selection.
![Screenshot_20210203-191916](https://user-images.githubusercontent.com/25881154/106784745-59d02a80-6655-11eb-82f0-a288e19e21de.png)
