### ISSUE TITLE
Mouse dragging to select text in Termux

### ISSUE THREAD

**Issue by PePoDev** [termux/termux-app#1810]
Can I use Mouse dragging to select text in Termux ?

### Informations
OS: Android 10
Device: Samsung Note 20 Ultra (Exynos 990)
Dex Mode: enabled

**Comment by hltdev8642** [comment]
if you mean using the native Android copy/paste, then yes just long press until copy comes up...however I have a feeling you have something else in mind 🤔

**Comment by PePoDev** [comment]
@hltdev8642 Thanks for answering me.

I use Termux on Samsung Dex Mode and I need to use mouse draging to select string like a PC.

**Comment by hltdev8642** [comment]
A little more context on what you are looking to do specifically (or if it's just general usage).

if it's just global/general usage then I dont have a great answer off the top of my head (probably something that termux devs would be able to answer).

if however your looking just to edit code/text files then id highly recommend the text editor [micro](https://micro-editor.github.io). it will probably work for dragging like that right out of the box, but you can also debug input events in the program using a debug feature built in (you could maybe at least figure out the touch event representations).

good luck :]
