### ISSUE TITLE
Root problem

### ISSUE THREAD

**Issue by chawla-sunny** [termux/termux-app#1816]
I have problem the time I root my termux I root my mobile after root termux with kali, ubuntu, sudo root termux without root my mobile I try all but what is the main problem when I root termux  after is install Tool-X its show your offline please help 

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:9
* Device model: xiaomi note 5 pro

**Comment by xeffyr** [comment]
Sorry but this is not a place for reporting Tool-X problems.

**Comment by chawla-sunny** [comment]
This is not a problem of Tool-X because when is download Tool-X with or without root my termux I am able to download in both but when I try to to download any another tool from Tool-X when termux is in root Tool-X not open  and said your offline but when download without root my termux able to download but not working because ask for root

**Comment by xeffyr** [comment]
> This is not a problem of Tool-X

This doesn't matter now. Your issue is not related to Termux application or its packages.
