### ISSUE TITLE
How to solve this problem Plz helps

### ISSUE THREAD

**Issue by SONU980** [termux/termux-app#1817]
![Screenshot_2020-11-01-11-07-45-14](https://user-images.githubusercontent.com/64944488/98880842-abca3f80-24ae-11eb-8c75-2fb4f5db4cbc.jpg)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
You do not seem to have a web server running in termux (read the error message)
