### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by MasteSosa** [termux/termux-app#1818]
**Feature description**

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by MasteSosa** [comment]
I need help using termux i been using termux for months and still its not doing what i needed done please help i havent hack nothing

**Comment by kcubeterm** [comment]
You need to learn basic of linux terminal. Let's start from here https://wiki.termux.com/wiki/Getting_started
