### ISSUE TITLE
Apt-get upgrade and certain module installs break termux

### ISSUE THREAD

**Issue by OlyAndy** [termux/termux-app#182]
E. g. For android support library :

CANNOT LINK EXECUTABLE: library "libandroid-support.so" not found
page record for 0xb6ea100c was not found (block_size=64)

[Process completed with code 1 - press Enter to close]

Similar error messages after APT upgrade

**Comment by OlyAndy** [comment]
Issue is that files in /data/data/com.termux/files/usr/libexec need global read permissions

**Comment by OlyAndy** [comment]
Similarly,  files in /data/data/com.termux/files/usr/bin such as su and dash need global rx permissions to allow su to work

**Comment by fornwall** [comment]
Currently it's best not to run `apt` as root (there is no advantage in doing so, and causes issues such as this at the moment).
