### ISSUE TITLE
Segmentation fault in termux

### ISSUE THREAD

**Issue by jayashridangat** [termux/termux-app#1826]
Hello sir
I am using termux for c++ compiling
But i've been having issues with some codings
For some codes it shows segmentation fault
![Screenshot_20201119_203347](https://user-images.githubusercontent.com/74724243/99683647-93f24d00-2aa6-11eb-982b-8d286f9a4968.jpg)
I tried to fix it but cant
Plz help

**Comment by xeffyr** [comment]
This is not a place where you can ask for help with debugging your code.

**Comment by siddhatehuti** [comment]
🤣🤣🤣😬 he wants us to solve his jigsaw puzzle for him
