### ISSUE TITLE
termux man page has a typo

### ISSUE THREAD

**Issue by thinker-amir** [termux/termux-app#1829]
**Problem description**
I found a typo on termux man page, it's written `sinle-user` instead of `single-user`

**Steps to reproduce**
You can find this typo on the `man termux` page
 See *Only one user* Section.

**Additional information**

* Termux application version: 0.101
* Android OS version: 10
* Device model: Xiaomi mi9t

**Comment by xeffyr** [comment]
Thanks, that has been fixed in the latest version of package `termux-tools` which provides that manpage: https://github.com/termux/termux-packages/commit/21aab222d691a84c42b2b824a442b30bdf7c28c8

**Comment by xeffyr** [comment]
Just noticed about another typo in same section, lol.
