### ISSUE TITLE
CANNOT LINK EXECUTABLE "apt"

### ISSUE THREAD

**Issue by whqatever** [termux/termux-app#1830]
**Problem description**

I cannot update and this is the result of 'pkg update'

`$ pkg update
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
CANNOT LINK EXECUTABLE "apt": cannot locate symbol "glob" referenced by "/data/data/com.termux/files/usr/lib/libapt-pkg.so"...
/data/data/com.termux/files/usr/bin/pkg: line 127: 28736 Aborted                 apt update`

**Comment by xeffyr** [comment]
Workaround is here: https://github.com/termux/termux-packages/issues/5994#issuecomment-723142275
