### ISSUE TITLE
Real Termux widget

### ISSUE THREAD

**Issue by bitcoinmeetups** [termux/termux-app#1833]
Hi,

It's me, Mr. Nice. 

Feature request for Termux.

The Termux:widget app just displays shortcuts.

The Termux:float app is always floating.

How about a real widget app so we can have a real Terminal on the Android home screen which displays all sorts of useful information and accepts input too?

This would be very useful.

BM

**Comment by xeffyr** [comment]
> which displays all sorts of useful information and accepts input too?

Never seen widgets which allow keyboard input.

**Comment by xeffyr** [comment]
Besides keyboard input, everything else already requested in https://github.com/termux/termux-widget/issues/29.
