### ISSUE TITLE
Clang/LLVM linker error 

### ISSUE THREAD

**Issue by IsmailAyvaz** [termux/termux-app#1840]
**Problem description**

  i am getting __atomic_fetch_add_4 error when i try to build c++ projects i think especially atomic library included ones.

**Steps to reproduce**

*   I cloned a repository via git
*   then i ran Cmake succesfully 
 **output of cmake** : -- The CXX compiler identification is Clang 10.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: (build directory)
*  i typed make and **output** :
 [  1%] Building CXX object src/test/json/CMakeFiles/tao-json-test-with_arguments.dir/with_arguments.cpp.o
[  2%] Linking CXX executable tao-json-test-with_arguments
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset 68
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset 6c4
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset 721
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset 7bf
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset 81c
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset 879
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset 8d6
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset 9b8
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset a48
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset ad8
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset b7d
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset c86
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset d8f
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset e1f
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: DWARF error: could not find variable specification at offset e7c
CMakeFiles/tao-json-test-with_arguments.dir/with_arguments.cpp.o: in function `long std::__ndk1::__libcpp_atomic_refcount_decrement<long>(long&)':
/data/data/com.termux/files/usr/include/c++/v1/memory:3361: undefined reference to `__atomic_fetch_add_4'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/test/json/CMakeFiles/tao-json-test-with_arguments.dir/build.make:103: src/test/json/tao-json-test-with_arguments] Error 1
make[1]: *** [CMakeFiles/Makefile2:316: src/test/json/CMakeFiles/tao-json-test-with_arguments.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

* i tried passing -latomic to linker but didnt work

**Expected behavior**
    I expected to build test executables .

**Additional information**

* Termux application version: 0.101
* Android OS version: Android 10
* Device model: Samsung Galaxy A105G
* Architecture: 32 bit armv8l

**Comment by xeffyr** [comment]
Need linking with libatomic. Add `-latomic` to LDFLAGS.

**Comment by IsmailAyvaz** [comment]
No adding -latomic dont solve the problem as i mentioned in question.
Only adding both -latomic and -u atomic_fetch_add_4 solved the problem but then new error occured about atomic library and i have stopped trying it .

**Comment by xeffyr** [comment]
> No adding -latomic dont solve the problem as i mentioned in question.

Then it was added in a wrong place. The order of static libraries matters.

Using `-latomic` always solved packaging problems like yours.
