### ISSUE TITLE
Cannot delete golang packages...

### ISSUE THREAD

**Issue by MrAdityaAlok** [termux/termux-app#1841]
**Problem description**

![Screenshot_2020-12-05-18-46-12-394](https://user-images.githubusercontent.com/73517616/101244056-2db62d00-372a-11eb-9ff7-48e8856f0491.jpeg)

When I tried to delete(by  **rm -rf**  command) golang package files installed by **go get** command(in $HOME/go/pkg/) , it shows permission denied error. 
And of course my  device is not rooted.

**Steps to reproduce**

- Install golang pkg 
- Install any golang library by **go get** command
- try to remove files in $HOME/go/pkg

**Expected behavior**

Should remove these files without permission denied error.

**Additional information**
I even tried to give it read-write permission by **chmod** but nothing happened.

* Termux application version: 0.101
* Android OS version: Android 9
* Device model:  Lenovo TB-X605LC

**Comment by xeffyr** [comment]
This is *expected behavior* of Golang. Modules are made read-only when downloaded. To delete them, do:
```
chmod 700 -R ./go
rm -rf ./go
```

**Comment by xeffyr** [comment]
https://github.com/golang/go/issues/28902#issuecomment-440519471

**Comment by MrAdityaAlok** [comment]
Thank you
And **SORRY 🥺**
