### ISSUE TITLE
cloned termux-app permissions patch

### ISSUE THREAD

**Issue by RadicalEd360** [termux/termux-app#1844]
**Feature description**

the appcloner app allows an app to be cloned and work in two spaces. Allowing to press the square key twice to switch to another terminal via native app switching, as i would to switch to chrome.

After attempting to clone, everything goes fine, except new clone termux is in /data/data/com.termuy ,     even this isnt an issue as the app is correctly recognizing its new path. However its unable to bind a login shell with this msg:

exec("/data/data/com.termuy/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

It looks as tho a new user is in charge of the new path or something along that line. I am unable to test this theory furthur as i do not have root permission to be able to examine the new root at com.termuy, the original termux user doesnt have perms to read the new location, and termux apps do not have a tty fallback shell like linux does when the x display goes haywire.

Would be a big improvement in workflow to be able to just switch terminals with the app switcher as i use it all the time working with vim and testing on the browser. Would be nice to have two vims in app switcher.

Thank You for your wonderful work!

* Update *
found failsafe mode in new cloned app, starts a shell and gives me access to a new user named u0_a171, which is different than the original user, however i am met with issues, possibly related to being in failsafe?

$ bash

sh: bash: inaccessible or not found

$ /data/data/com.termuy/files/usr/bin/bash
           
CANNOT LINK EXECUTABLE "/data/data/com.termuy/files/usr/bin/bash": library "libandroid-support.so" not found

the clones /bin/pkg is also owned by the original user and not the new clone user.

**Comment by AbdullahM0hamed** [comment]
Cloning the app isn't possible as per https://github.com/termux/termux-app/issues/1761#issuecomment-693607829

**Comment by RadicalEd360** [comment]
> Cloning the app isn't possible as per [#1761 (comment)](https://github.com/termux/termux-app/issues/1761#issuecomment-693607829)

Thank You
