### ISSUE TITLE
libstdc++ support

### ISSUE THREAD

**Issue by Dammibruh** [termux/termux-app#1846]
hey, I was trying to make a C++ program that uses filesystem header , but the problem is libstdc++fs is not found I tried to search for a previous issues found this [one](https://github.com/termux/termux-app/issues/968) from 2018 does termux or google ndk supports libstdc++fs yet or no ?

**Comment by Grimler91** [comment]
[It is planned for r22](https://github.com/android/ndk/issues/609#issuecomment-620858677), current version is r21.
