### ISSUE TITLE
ls -l /data/data/com.termux/files/usr/bin/login

### ISSUE THREAD

**Issue by ajanik3040** [termux/termux-app#1847]
![Screenshot_2020-12-08-19-31-00](https://user-images.githubusercontent.com/75679092/101490153-29894a00-398c-11eb-9731-7cdc23bf12b3.png)

How to fix this issue ?

**Comment by xeffyr** [comment]
Use `tsu` to get a root shell.

`sudo su` is abuse of both `su` and `sudo` at the same time and may have unpredictable results.

**Comment by Abzobio** [comment]
Issue inbox
