### ISSUE TITLE
Cant SSH on mobile data

### ISSUE THREAD

**Issue by FoxxyPlayys01** [termux/termux-app#1849]
when im on wifi i can ssh to my server with no problem but when im on mobile data i cant ssh at all it says host unreachable.
my data is working fine with normal.stuff. howefer ping doesnt work with any ip or domain so idk whats going on there

**Comment by xeffyr** [comment]
> howefer ping doesnt work with any ip or domain so idk whats going on there

Definitely not a Termux problem. Please note that application doesn't manage network of your device. Check your device settings, maybe there some traffic optimization for mobile data.

Also be sure that some mobile carriers restricts target ports to which you can connect or even protocols.

***

`ssh` works fine for me on both mobile and wifi network.
