### ISSUE TITLE
self directory.

### ISSUE THREAD

**Issue by zachsfallen** [termux/termux-app#1851]
hi zach allen. 

im trying access the self directory with out rooting my device. what programs do i use too access those directorys? commands would be awesome.

Does another app/terminal emulator have this feature?.

**Comment by xeffyr** [comment]
Without root, you can access only `/storage/emulated/0` if Termux has been granted the storage access permission.

Directory below, i.e. `/storage/emulated`, is restricted for privacy reasons - on devices with multiple user accounts that's important.
