### ISSUE TITLE
npm install error on Android 11

### ISSUE THREAD

**Issue by forliuyifei** [termux/termux-app#1852]
**Problem description**

![Screenshot_20201214-102150~01-01](https://i.loli.net/2020/12/14/uE12fj9iCZQRl4V.jpg)

**Steps to reproduce**

When I run `npm i`

**Expected behavior**

Please help me to fix it.

**Additional information**

* Termux application version: 0.101
* Android OS version: 11
* Device model: lavender（redmi note 7）pixel experience

**Comment by Grimler91** [comment]
Your screenshot shows only warnings, no errors
