### ISSUE TITLE
Permanent $PATH Environment Variable Change Not Working

### ISSUE THREAD

**Issue by Procambarus-gracilis** [termux/termux-app#1853]
I have a shell script I want to run from anywhere in Termux and although I've changed my $PATH variable (I created a file called .bashrc in $HOME), when I try to run this script by typing "sh my_script," it doesn't launch and I get an error saying the file can't be opened.  If I instead type "sh path/to/my/script/my_script" it works but to my understanding, the whole point of changing the $PATH variable is to avoid doing this in the dirst place.  Also, I included the Termux-specific shebang "#!/data/data/com.termux/files/usr/bin/bash" at the very first line at the start of my script.

What am I missing here?  Does Termux handle this differently than standard Linux?  Is what I am trying to do here impossible in Termux?  Is there an alternative way to do this in Termux so that I can run my script anywhere in Termux without typing the whole path to my script's location?

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by xeffyr** [comment]
`sh file.sh` executes file `file.sh` in **current** directory.

`sh /path/to/file.sh` executes `file.sh` at path `/path/to/file`. Path can be absolute (starts from `/`, root) or relative to current directory. **It has nothing to do with PATH variable!**

Shebang specifies the script interpreter and is needed only if file is *executable* and its directory is listed in `PATH` variable. PATH variable is not permanent and should be configured through `~/.bashrc` or equivalent. Executables can be placed only in internal storage, i.e. Termux home directory ($HOME) or prefix ($PREFIX).

Just copy your script to `$PREFIX/bin`, `chmod +x` it and then it should work by just typing its name in shell.

***

*Learn basics of shell scripting and command line.*

Closing as I do not see any problem from Termux side.

**Comment by Procambarus-gracilis** [comment]
Ok.  Thanks.

**Comment by Procambarus-gracilis** [comment]
Hi Leonid,

One quick question, would you please tell me why I am unable to run C programs on Termux despite having the "clang" compiler installed?  I am able to type "gcc" to compile (executing "gcc -v" returns that the compiler is actually clang) but when I type ./myprog or ./myprog.out in order to run them, I get a bash error saying that my permission was denied.  Doing this exact procedure on a cluster (Linux) causes the program to run nicely, although my cluster uses gcc which never returns messages saying it's actually clang.  Thanks.
________________________________

**Comment by Grimler91** [comment]
Where does `myprog` come from, or how did you compile it? You can only run programs which are compiled against your CPU architecture and that are compiled against androids libc

**Comment by xeffyr** [comment]
@Procambarus-gracilis Because you should not execute programs from shared storage. You seems have not read https://github.com/termux/termux-app/issues/1853#issuecomment-746944626 carefully.

**Comment by Procambarus-gracilis** [comment]
I got it working.  I put it in the appropriate place for executables.  Thanks.

ESent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by Procambarus-gracilis** [comment]
I got it.  Thanks.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
