### ISSUE TITLE
Permission denied when trying to write or create file on USB Drive

### ISSUE THREAD

**Issue by stevenleeS0ht** [termux/termux-app#1855]
**Problem description**

All of the shell command or executable file in Termux are not able to write data or create file at place on USB flash drive, through I have permitted Termux to access data at storage.

**Steps to reproduce**

My USB drive have file system exFAT, it can be discovered and read/writed by File Manager.

**Expected behavior**

It should be able to write or create file on any User accessible directory and filesystem.

**Additional information**

* Termux application version: 0.103
* Android OS version: 10

**Comment by stevenleeS0ht** [comment]
One possibly reason might because is exFAT filesystem doesn't support file owner and permission, Termux just regard files permission as root.

However, in desktop linux, the situation is a little bit different, if the filesystem doesn't support permission, it will be open to everyone.

**Comment by stevenleeS0ht** [comment]
@fornwall and @xeffyr please have a look.

**Comment by Grimler91** [comment]
It is not possible without root currently, see duplicate issue https://github.com/termux/termux-app/issues/71. 

Termux is only allowed to write to /sdcard and the folder Android/data/com.termux/files on the external sdcard, other places, including usb devices, are not possible to write to without root

**Comment by Argo18** [comment]
Even the shellphish no file found linux choice not found what happen

**Comment by kcubeterm** [comment]
@Argo18 That's not our issue, please search on google to alternative. Linux choice either have deleted that repo or privatised.
