### ISSUE TITLE
Feature request: adjust height of extra commands 

### ISSUE THREAD

**Issue by fieldlab** [termux/termux-app#1857]
**Problem description**

This is only a feature request. The "extra commands" lines above the keyboard are tall- there is significant empty height above the characters. This effects the vertical spacing between the "extra commands" lines, and the vertical spacing to the terminal text. Together this represents significant screen area which could instead be used for more terminal text area.

**Steps to reproduce**

Just add one or two lines of "extra commands" on Android (phone, portrait mode), using a command such as:

`echo` "extra-keys = [['~','/','','UP','HOME','END','CTRL'],['BACKSLASH','=','LEFT','DOWN','RIGHT','TAB','DEL']]" > /data/data/com.termux/files/home/.termux/termux.properties`

**Expected behavior**

Currently works as expected without problems. This is only a feature request. I would suggest the "extra commands" line height offer adjustability, perhaps using a parameter in the termux.properties file. Perhaps a "line-height" parameter, and "alignment" parameter (top, center, bottom).

Keep up the great work!

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
netcat/stable 7.91 aarch64 [upgradable from: 7.80]
nmap/stable 7.91 aarch64 [upgradable from: 7.80]
Android version:
10
Kernel build information:
Linux localhost 4.9.210-gdee0d123b122-ab6570413 #0 SMP PREEMPT Tue Jun 9 02:07:02 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 3a
```

**Comment by dontknow3d** [comment]
I would also want this feature, because to me the 2 line extra keys layout is too crammed in vertical space, id like it to be bigger. But i have also seen other people say they want it smaller, so an "extra-keys-height" property would be very useful.
