### ISSUE TITLE
Error when run 'pkg update'

### ISSUE THREAD

**Issue by sandyukts** [termux/termux-app#1859]
$ pkg update
Checking availability of current mirror: ok
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [8255 B]
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Fetched 19.8 kB in 7s (2771 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  xxhash
The following packages will be upgraded:
  apt bash ca-certificates clang coreutils dash dpkg harfbuzz
  libllvm php termux-am termux-tools
12 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 7172 kB/48.7 MB of archives.
After this operation, 1585 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 https://dl.bintray.com/termux/termux-packages-24 stable/main arm php arm 8.0.0-1 [7172 kB]
Err:1 https://dl.bintray.com/termux/termux-packages-24 stable/main arm php arm 8.0.0-1
  Error reading from server - read (5: I/O error) [IP: 35.161.162.245 443]
E: Failed to fetch https://dl.bintray.com/termux/termux-packages-24/arm/php_8.0.0-1_arm.deb  Error reading from server - read (5: I/O error) [IP: 35.161.162.245 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

-help
![Uploading Screenshot_20201226-224340_Termux.jpg…]()

**Comment by xeffyr** [comment]
See my answer in https://github.com/termux/termux-packages/issues/6181#issuecomment-751368279.
