### ISSUE TITLE
How to compile vim in termux?

### ISSUE THREAD

**Issue by zetaw** [termux/termux-app#186]
I clone the code of vim, and Makefile,but it doesn't work. This may be because of the "configure".The "configure" is a shell script,and it begins with:
#! /bin/sh
However, in my cell phone, it's actually /data/data/com.termux/file/usr/bin/sh.
So, How can I get the configure right, and compile vim successfully?
I want to cmpile vim to add support for python and lua.

**Comment by Neo-Oli** [comment]
You need to run `termux-fix-shebang configure` to fix the shebang. 
Sidenote. `vim-python` is available as a package you can install with `apt install vim-python`

**Comment by zetaw** [comment]
However, if you run apt install vim-python, you can only add support for python3, but not pyhton2.
Thank you all the way.

**Comment by zetaw** [comment]
I try the advice, but when I make, the gcc report that there is an error with 'bzero' and 'strings.h'. So how can I fix it?

**Comment by Neo-Oli** [comment]
Vim requires a few patches to run on Termux. It's probably not that easy to compile it on Termux. It might be easier to cross-compile using the existing package sources here: https://github.com/termux/termux-packages/tree/master/packages/vim and add support for Lua and Python2 there.

**Comment by zetaw** [comment]
How to use the packages? I cloned it, but have no ideas to use it. Perhaps I should edit the "build.sh"? How to patch the patches.
Thank you very much. I think you

**Comment by zetaw** [comment]
have almost solved  my problem.

**Comment by fornwall** [comment]
For these types of question I thinks it's better to use our chat channel at https://gitter.im/termux/termux or #termux on freenode.

**Comment by albertogalan** [comment]
thanks. Very usefull
