### ISSUE TITLE
who can help me?

### ISSUE THREAD

**Issue by mathpopo** [termux/termux-app#1863]
![329908773](https://user-images.githubusercontent.com/21274466/103255631-fbb08780-49c4-11eb-8bcb-e848575d1f86.jpg)

**Comment by WMCB-Tech** [comment]
Try `pkg update` again

If not, try `termux-change-repo`

**Comment by mathpopo** [comment]
![329908773](https://user-images.githubusercontent.com/21274466/103256266-8db98f80-49c7-11eb-9cd2-d293dfb4ae1a.jpg)

**Comment by mathpopo** [comment]
![Uploading 687769884.jpg…]()

**Comment by mathpopo** [comment]
![687769884](https://user-images.githubusercontent.com/21274466/103256607-d291f600-49c8-11eb-992f-f79afe9159f3.jpg)
