### ISSUE TITLE
Not all extra keys repeat

### ISSUE THREAD

**Issue by greysdawn** [termux/termux-app#1864]
**Problem description**

Only certain keys seem to repeat when added to the extra keys row. More specifically, only the arrow keys seem to, and other keys/macros don't automatically send repeated keypresses.

**Steps to reproduce**

1. Add an extra key through `termux.properties`, eg. by adding `{key: '/'}` to an advanced setup
2. Attempt to hold down the key
3. See that it doesn't repeat, but rather only registers after releasing the key
4. Add an arrow key in, eg: `{key: 'UP', display: '⬆️'}`
5. Hold down this key (preferably after building a command history or somewhere you can move the text cursor upwards)
6. Observe that it repeats automatically 

**Expected behavior**

The `/` key should repeat the same way the arrow key does

**Additional information**

* Termux application version: 0.101 (from system app settings)
* Android OS version: 9
* Device model: Samsung Galaxy Note 8

**Comment by xeffyr** [comment]
Intended behavior. Only `"UP", "DOWN", "LEFT", "RIGHT", "BKSP", "DEL"` are made repeatable.
