### ISSUE TITLE
Do I have to reinstall Termux if I move to F-Droid

### ISSUE THREAD

**Issue by dipayand** [termux/termux-app#1866]
Termux Wiki States:

"Since November 2, 2020 we no longer able to publish updates of Termux application and add-ons because we are not ready for changes upcoming with SDK level 29 (Android 10).

Everyone should move to F-Droid version, if possible." 

SO IF I HAVE TO MOVE TO F-DRIOID VERSION THEN DO I LOOSE ALL DATA. I MEAN DO I NEED TO UNINSTALL AND THEN REINSTALL FROM F-DROID

**Comment by xeffyr** [comment]
You need to uninstall a Play Store version first because APKs on F-Droid use a different signature.

**Comment by shankar12789** [comment]
https://wiki.termux.com/wiki/Backing_up_Termux

Follow the above steps before uninstalling the Play Store version

**Comment by xeffyr** [comment]
> https://wiki.termux.com/wiki/Backing_up_Termux

Just have updated these instructions. Restoring from tar should be much easier now.
