### ISSUE TITLE
Error while updating unstable repo

### ISSUE THREAD

**Issue by shankar12789** [termux/termux-app#1867]
**Problem description**
Trying to update unstable repo causes repository not signed error

**Error message**
E: The repository 'https://dl.bintray.com/xeffyr/unstable-packages unstable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Steps to reproduce**
pkg install unstable-repo && pkg update

**Expected behavior**
Updation of unstable repository successfully

**Additional information**

* Termux application version: 0.103
* Android OS version: 10
* Device model: Redmi Note 7 pro
* sources.list:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main

**Comment by xeffyr** [comment]
I'm aware of that issue and will be resolved shortly.
