### ISSUE TITLE
How to install and run Bitcoin pkg on a microSD

### ISSUE THREAD

**Issue by theDavidCoen** [termux/termux-app#1868]
I'm trying to set up a Bitcoin Node, using Termux, on a Xiaomi Note 9 Pro.
I have a 512 GB microSD for the full blockchain, but if I install Bitcoin with `pkg install bitcoin` and run bitcoind, Termux installs it on its folder and downloads the blockchain there.

How can I move bitcoind to the external microSD and download the full blockchain there?

I also run `termux-setup-storage` and tried to install Bitcoin Core with wget. I have all the folder in storage/external-1, but if I go to bin and run `bitcoind` I get `bash: /data/data/com.termux/files/usr/bin/bitcoind: No such file or directory`

Can anybody help me?

**Comment by xeffyr** [comment]
Use option `-datadir` of utility `bitcoind`. Suggesting to check the all options supported by Bitcoin daemon: `bitcoind -?`.

> tried to install Bitcoin Core with wget

Saving data to `$HOME/.bitcoin` is default official behavior of both Bitcoin Core. With version obtained with `wget` you do not get anything different. However you will not be able to run it at all, Termux is not a Linux distribution - https://wiki.termux.com/wiki/Differences_from_Linux.
