### ISSUE TITLE
There is no metasploit for unstable source!

### ISSUE THREAD

**Issue by whitedays2007** [termux/termux-app#1870]
#### Why doesn't termux have metasploit, there is before.

Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
unstable-repo is already the newest version (4.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package metasploit

**Comment by kcubeterm** [comment]
https://github.com/termux/termux-packages/issues/6206
