### ISSUE TITLE
Colors problems

### ISSUE THREAD

**Issue by destime224** [termux/termux-app#1871]
All colors except background-colors aren't working and just showed only with neon.
It looks as black-white as Windows terminal.
Leagoo M8, Android 6.0

**Comment by Grimler91** [comment]
Hi, please provide a screenshot to show the problem. 
Are you talking about backgrounds set with termux-styling?

In any case, android 5 and 6 are not supported any more by us so there will not be any app updates related to this.

**Comment by destime224** [comment]
I have not Termux:Styling and make background colors with special texts (for example "\\e[1m").
But even commands like "ls" that have a auto colors for files, directories and all aren't working and showed with neon.

![OneShot_20210104_141346](https://user-images.githubusercontent.com/38858785/103530032-ce1d7f80-4e97-11eb-8f8e-53bf413e73f9.png)

**Comment by xeffyr** [comment]
@destime224 Issue is with your device (operating system). This case is not a subject for fixing on Termux side and as already stated by @Grimler91 *Android 6.x is not supported by Termux*, so it won't get any updates.

However I can suggest to
1. Try to reset or reinstall Termux.
2. Ensure that your OS doesn't apply various font "enhancements" like high-contrast, custom colors or something else.

**Comment by destime224** [comment]
@xeffyr I fix it. A smartphone transferred from my father and high contrast was switched on. It was problem with colors. I have to redo my bash-scripts that use inconvenient background colors but thanks

**Comment by suraj208** [comment]
![Screenshot_20210710-014758](https://user-images.githubusercontent.com/84099838/125148758-04c4a300-e124-11eb-8edd-e60a768842d5.png)
My termux has loss it ability to show color
