### ISSUE TITLE
Allow view pdf file in termux

### ISSUE THREAD

**Issue by Frischid** [termux/termux-app#1872]
**Feature description**

First of all: Thank you for this nice, helpful app!

I use termux to convert pdf files to svg to view and edit them with another app. It all works quiet well except that I needed to change the manifest to be able to "view" the files directly and convert them with termux.

For my personal use case it would be great being able to "view" pdf files with termux.

**Reference implementation**
Would be quiet simple to implement, we need to add this line to AndroidManifest.xml:
`<data android:mimeType="application/*" />` or better: `<data android:mimeType="application/pdf" />`

```
.
.
.
<intent-filter tools:ignore="AppLinkUrlError">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="text/*" />
                <data android:mimeType="application/pdf" />
                <data android:mimeType="application/*log*" />
                <data android:mimeType="application/json" />
                <data android:mimeType="application/*xml*" />
                <data android:mimeType="application/*latex*" />
                <data android:mimeType="application/javascript" />
            </intent-filter>
.
.
.
```

**Comment by xeffyr** [comment]
I guess it would be better to use `<data android:mimeType="application/*" />` rather than adding individual file types.

**Comment by Frischid** [comment]
Very fast! Thank you!

**Comment by bassmadrigal** [comment]
Any chance this can be optional? I'm not terribly familiar with Android development, but I'm thinking it's only changeable at your level and not something you can make optional within the app.

I open PDFs a lot and I'm not presented an option to make a certain app default with PDFs, so I am presented the selector every time I try to open one, which can be a little frustrating (first world problems, I know).
