### ISSUE TITLE
Restoring Termux data after migrating to f-droid build breaks executables

### ISSUE THREAD

**Issue by KaMyKaSii** [termux/termux-app#1873]
**Problem description**

Self-explanatory title. After restoring the data from the backup file, I can only run the binaries already installed during the same session (before pressing exit). In a new session, I can no longer run the executables that are installed, despite seeing them in their respective folders with a root file manager

**Steps to reproduce**

1. Backup:
```
cd /data/data/com.termux/files
tar -cvf /sdcard/termux-backup.tar home usr
```
2. Uninstall Termux from PlayStore and install it from f-droid
3. Restore:
```
cd /data/data/com.termux/files
tar -xf /sdcard/termux-backup.tar --recursive-unlink --preserve-permissions
```
I also tried to restore only the "home" but got the same result
```
tar -xf /sdcard/termux-backup.tar home --recursive-unlink --preserve-permissions
```

**Expected behavior**

That the binary execution continues to work normally

**Additional information**

* Termux application version: 0.104
* Android OS version: 9
* Device model: Zenfone 4 2017 (ZE554KL)

**Comment by xeffyr** [comment]
I can't reproduce the issue. Everything is running correctly. Ensure that `tar -xf` is not running as root.

And I should note that `--recursive-unlink` wipes everything in $PREFIX before restoring from backup, including the dependencies of binaries installed before doing `tar -xf`. *That's intended behavior of commands provided on Wiki.*

**Comment by Grimler91** [comment]
What does 

> I can no longer run the executables that are installed

mean? Trying to run them gives you some error? (Which error?)

Also ensure that you are using termux's `tar` and not `/system/bin/tar` (check with `which tar`), but I don't see how you could end up using the latter unless you are running as root or something as xeffyr said

**Comment by xeffyr** [comment]
> Also ensure that you are using termux's tar and not /system/bin/tar

Should be exactly `$PREFIX/bin/tar` as only it is working as needed. Commands are from https://wiki.termux.com/wiki/Backing_up_Termux (yet without gzip compression).

**Comment by KaMyKaSii** [comment]
> What does
> 
> > I can no longer run the executables that are installed
> 
> mean? Trying to run them gives you some error? (Which error?)
> 
> Also ensure that you are using termux's `tar` and not `/system/bin/tar` (check with `which tar`), but I don't see how you could end up using the latter unless you are running as root or something as xeffyr said

Okay, I found out that programs still run normally with the full path, I think they were just removed from the path or something
```
~ $ echo $PATH
”/data/data/com.termux/files/home:/data/data/com.termux/files/usr/bin”
```
![Screenshot_20210104-205703681](https://user-images.githubusercontent.com/17092335/103592682-705a5900-4ed2-11eb-9125-d936ec7c848c.jpg)

**Comment by xeffyr** [comment]
> ~ $ echo $PATH
”/data/data/com.termux/files/home:/data/data/com.termux/files/usr/bin”

Check your .bashrc because your PATH variable contains something very wrong. `echo $PATH` should print content without symbol `"`.

**Comment by KaMyKaSii** [comment]
> > ~ $ echo $PATH
> > ”/data/data/com.termux/files/home:/data/data/com.termux/files/usr/bin”
> 
> Check your .bashrc because your PATH variable contains something very wrong. `echo $PATH` should print content without symbol `"`.
> 
> Issue is neither with Termux nor with `tar` command.

You're right, I deleted the .bashrc file through the root file manager and Termux is back to normal. What I don't understand is why it be the problem if I only had a few aliases and functions in it and there was no problem when I was using Termux from playstore
```
alias zz="${HOME}/zstd-1.4.5_api29_static"
alias ff="proot ${HOME}/1ffmpeg"
alias fp="proot ${HOME}/ffprobe"
export PATH=”${HOME}:$PATH”
alias sshh="ssh root@192.168.31.1"
alias otimizarapps="su -c cmd package bg-dexopt-job"
function twitch720() { am start -a "android.intent.action.VIEW" -p "com.mxtech.videoplayer.ad" -d "$(youtube-dl -f 720p60 -g https://twitch.tv/"$1")"; }
function twitch1080() { am start -a "android.intent.action.VIEW" -p "com.mxtech.videoplayer.ad" -d "$(youtube-dl -f 1080p60__source_ -g https://twitch.tv/"$1")"; }
function twitchaudio() { am start -a "android.intent.action.VIEW" -p "com.mxtech.videoplayer.ad" -d "$(youtube-dl -f audio_only -g https://twitch.tv/"$1")"; }
function liveyoutube() { am start -a "android.intent.action.VIEW" -p "com.mxtech.videoplayer.ad" -d "$(youtube-dl -f 96 -g "$1")"; }

#org.videolan.vlc
#com.mxtech.videoplayer.ad

```

**Comment by xeffyr** [comment]
Because you have invalid character in line with PATH export. There is a difference between yours (not correct)
```
export PATH=”${HOME}:$PATH”
```

and this (correct)
```
export PATH="${HOME}:$PATH"
```

`” (hex code: 0x201d)` != `" (hex code: 0x22)`

Check what you are typing. If symbols look same, that doesn't mean that shell will treat them as equal.

**Comment by xeffyr** [comment]
Because you have invalid character in line with PATH export. There is a difference between yours (not correct)
```
export PATH=”${HOME}:$PATH”
```

and this (correct)
```
export PATH="${HOME}:$PATH"
```

`” (hex code: 0x201d)` != `" (hex code: 0x22)`

Check what you are typing. If symbols look same, that doesn't mean that shell will treat them as equal.
