### ISSUE TITLE
Why not move everything to `sdcard/Android/data/com.termux`

### ISSUE THREAD

**Issue by Malaska678** [termux/termux-app#1875]
=]  this only a question

**Comment by Malaska678** [comment]
The good thing with this is everything can be modified by the user

**Comment by xeffyr** [comment]
> Why not move everything to `sdcard/Android/data/com.termux`

Because of `noexec` and lack of symlink & other special files support.

**Comment by Malaska678** [comment]
> > Why not move everything to `sdcard/Android/data/com.termux`
> 
> Because of `noexec` and lack of symlink & other special files support.

I see that why i close it
