### ISSUE TITLE
[Feature Request] Ability to use Images as Terminal Background

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/termux-app#1878]
**Feature description**
it would be cool if Termux can use pictures as background and the terminal will look aesthetic like anime background in your Terminal or matrix image background

**Reference implementation**

Does another app/terminal emulator have this feature?

Afaik, XFCE Terminal can set pictures as Terminal Background, so yeah it would be cool if termux does that the same

**Comment by GxmerSam** [comment]
I agree too, maybe can be added with termux styling

**Comment by xeffyr** [comment]
Duplicate of https://github.com/termux/termux-app/issues/365.
