### ISSUE TITLE
Status do termux

### ISSUE THREAD

**Issue by ghostkiller-gif** [termux/termux-app#1882]
W: GPG error: https://grimler.se/termux-packages-24 stable Release: The following signatures were invalid: BADSIG 5A897D96E57CF20C Termux Releases (Termux automatic builds) <contact@termux.com>
E: The repository 'https://grimler.se/termux-packages-24 stable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
~ $ pkg install metasploit
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package metasploit
~ $  apt-get update && apt-get -V upgrade
Ign:1 https://grimler.se/termux-packages-24 stable InRelease
Get:2 https://grimler.se/termux-packages-24 stable Release [8255 B]
Get:3 https://grimler.se/termux-packages-24 stable Release.gpg [821 B]
Ign:3 https://grimler.se/termux-packages-24 stable Release.gpg
Ign:4 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:5 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:6 https://dl.bintray.com/xeffyr/unstable-packages unstable InRelease
Get:7 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Get:9 https://dl.bintray.com/xeffyr/unstable-packages unstable Release [6065 B]
Reading package lists... Done
W: GPG error: https://grimler.se/termux-packages-24 stable Release: The following signatures were invalid: BADSIG 5A897D96E57CF20C Termux Releases (Termux automatic builds) <contact@termux.com>
E: The repository 'https://grimler.se/termux-packages-24 stable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

Fica dando esse erro quando eu dou pkg install metasploit ou qualquer outro tipo de package

A mesca coisa com o apt update 

apt update
Ign:1 https://grimler.se/termux-packages-24 stable InRelease
Get:2 https://grimler.se/termux-packages-24 stable Release [8255 B]
Get:3 https://grimler.se/termux-packages-24 stable Release.gpg [821 B]
Ign:3 https://grimler.se/termux-packages-24 stable Release.gpg
Ign:4 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:5 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:6 https://dl.bintray.com/xeffyr/unstable-packages unstable InRelease
Get:7 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Get:9 https://dl.bintray.com/xeffyr/unstable-packages unstable Release [6065 B]
Reading package lists... Done
W: GPG error: https://grimler.se/termux-packages-24 stable Release: The following signatures were invalid: BADSIG 5A897D96E57CF20C Termux Releases (Termux automatic builds) <contact@termux.com>
E: The repository 'https://grimler.se/termux-packages-24 stable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

E no apt upgrade aparece outro tipo de erro 

apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
E: Could not get lock /data/data/com.termux/cache/apt/archives/lock. It is held by process 32542 (apt)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to lock directory /data/data/com.termux/cache/apt/archives/

**Comment by WMCB-Tech** [comment]
> ~ $ pkg install metasploit
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package metasploit

Metasploit Is Removed from Termux (package policy has changed)

---
> ~ $ apt-get update && apt-get -V upgrade
Ign:1 https://grimler.se/termux-packages-24 stable InRelease
Get:2 https://grimler.se/termux-packages-24 stable Release [8255 B]
Get:3 https://grimler.se/termux-packages-24 stable Release.gpg [821 B]
Ign:3 https://grimler.se/termux-packages-24 stable Release.gpg
Ign:4 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:5 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:6 https://dl.bintray.com/xeffyr/unstable-packages unstable InRelease
Get:7 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Get:9 https://dl.bintray.com/xeffyr/unstable-packages unstable Release [6065 B]
Reading package lists... Done
W: GPG error: https://grimler.se/termux-packages-24 stable Release: The following signatures were invalid: BADSIG 5A897D96E57CF20C Termux Releases (Termux automatic builds) contact@termux.com
E: The repository 'https://grimler.se/termux-packages-24 stable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

Try `pkg update` again or `termux-change-repo`

---
> apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
E: Could not get lock /data/data/com.termux/cache/apt/archives/lock. It is held by process 32542 (apt)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to lock directory /data/data/com.termux/cache/apt/archives/

Wait if there's another `apt` process is doing some install or update operations

**Comment by ghostkiller-gif** [comment]
> > ~ $ pkg install metasploit 
> > Verificando a disponibilidade do espelho atual: ok 
> > Lendo listas de pacotes ... Concluído 
> > Construindo árvore de dependências 
> > Lendo informações de estado ... Concluído 
> > E: Não foi possível localizar o metasploit do pacote
> 
> Metasploit foi removido do Termux (a política do pacote foi alterada)
> 
> > ~ $ apt-get update && apt-get -V upgrade 
> > Lendo listas de pacotes ... Feito 
> > W: Erro GPG: https://grimler.se/termux-packages-24 Versão estável: As seguintes assinaturas eram inválidas: BADSIG 5A897D96E57CF20C Termux Versões (compilações automáticas Termux) [contact@termux.com](mailto:contact@termux.com) 
> > E: O repositório ' https://grimler.se/termux-packages-24 versão estável' não está assinado. 
> > N: A integridade dos metadados não pode ser verificada, o repositório está desativado agora. 
> > N: Possível causa: o repositório está em manutenção ou fora do ar (URL sources.list incorreto?).
> 
> Tente `pkg update`novamente ou`termux-change-repo`
> 
> > apt upgrade 
> > E: Não foi possível obter lock /data/data/com.termux/cache/apt/archives/lock. É realizado pelo processo 32542 (apt) 
> > N: Esteja ciente de que remover o arquivo de bloqueio não é uma solução e pode quebrar seu sistema. 
> > E: Não é possível bloquear o diretório /data/data/com.termux/cache/apt/archives/
> 
> Espere se houver outro `apt`processo executando alguma operação de instalação ou atualização (você pode ver se `apt`está sendo executado com `ps`ou `htop`)

Ok vo verificar termux change repo

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-03-10-36](https://user-images.githubusercontent.com/77376582/104413361-f9196a80-554c-11eb-9bd1-8dd8415ed930.png)

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-03-12-43](https://user-images.githubusercontent.com/77376582/104413549-4695d780-554d-11eb-942f-401d08344d49.png)

**Comment by ghostkiller-gif** [comment]
Eu estava botando o comando termux-change-repo ele volta ao erro da mesma forma

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-03-15-36](https://user-images.githubusercontent.com/77376582/104413741-a42a2400-554d-11eb-9226-167857c5f586.png)

**Comment by ghostkiller-gif** [comment]
Apareceu isso oque eu faço

**Comment by WMCB-Tech** [comment]
I think this has something to do with the repositories, could you output `termux-info`?

**Comment by ghostkiller-gif** [comment]
> I think this has something to do with the repositories, could you output `termux-info



> Acho que isso tem a ver com os repositórios, você poderia enviar `termux-info`?

Ok

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-03-19-27](https://user-images.githubusercontent.com/77376582/104413983-2fa3b500-554e-11eb-8a64-c1b0d42d5b3e.png)

**Comment by WMCB-Tech** [comment]
Ok, i changed the repo to grimler.se and this happens:

![Screenshot_2021-01-13-14-20-32-51.jpg](https://user-images.githubusercontent.com/65075766/104414072-8e971780-55aa-11eb-9450-527e9b0cffa6.jpg)

Try changing the repo, (main repository)

**Comment by ghostkiller-gif** [comment]
> Ok, mudei o repo para grimler.se e isso acontece:
> 
> ![Screenshot_2021-01-13-14-20-32-51.jpg](https://user-images.githubusercontent.com/65075766/104414072-8e971780-55aa-11eb-9450-527e9b0cffa6.jpg)
> 
> Tente alterar o repo, (repositório principal)

Ok vou dar termux change repo e alterar o maintenance

**Comment by WMCB-Tech** [comment]
Yes, changing it may help

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-03-26-21](https://user-images.githubusercontent.com/77376582/104414499-26671800-554f-11eb-93df-28d0e1473d00.png)

**Comment by ghostkiller-gif** [comment]
Tenho que botar o grimle?

**Comment by WMCB-Tech** [comment]
Maybe the official repository, (It works fine to me)

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-03-26-21](https://user-images.githubusercontent.com/77376582/104414754-86f65500-554f-11eb-83f0-a07fd69b5299.png)

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-03-32-28](https://user-images.githubusercontent.com/77376582/104415052-097f1480-5550-11eb-91ea-4405b3ed4f65.png)

**Comment by ghostkiller-gif** [comment]
Isso aqui que dizer que deu certo ou ainda e o erro

**Comment by WMCB-Tech** [comment]
Ok, you still choosed `grimler.se` repository

Try choosing bintray repository instead

**Comment by ghostkiller-gif** [comment]
> Ok, você ainda escolheu o `grimler.se`repositório
> 
> Tente escolher o repositório bintray
> e espere até que seja consertado

Ok vo fazer denovo no termux-change-repo

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-03-39-02](https://user-images.githubusercontent.com/77376582/104415538-f15bc500-5550-11eb-8967-94a5322b9bd8.png)

**Comment by ghostkiller-gif** [comment]
E agora deu certo?

**Comment by WMCB-Tech** [comment]
Yep, it should be fixed by now until the grimler.se repo is fixed

**Comment by ghostkiller-gif** [comment]
> Sim, ele deve estar consertado agora até que o repo grimler.se seja consertado

Ok vo esperar consertarem

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-04-09-50](https://user-images.githubusercontent.com/77376582/104418181-47326c00-5555-11eb-8ff0-8a46e2ed78cb.png)

**Comment by ghostkiller-gif** [comment]
Estava verificando o ps deu isso e o htop nao tenho instalado

**Comment by ghostkiller-gif** [comment]
~ $ pkg install metasploit
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package metasploit

Esse erro nao sai nem dos outros package que eu uso ja tentei apt update ele da o erro aquilo e o apt upgrade tambem e pkg update e o pkg upgrade

**Comment by ghostkiller-gif** [comment]
apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
E: Could not get lock /data/data/com.termux/cache/apt/archives/lock. It is held by process 32542 (apt)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to lock directory /data/data/com.termux/cache/apt/archives/

Eu preciso remover essa pasta com rm /data/data/com.termux/cache/apt/archives/

**Comment by ghostkiller-gif** [comment]
Talvez issi quebre o sistema

**Comment by kcubeterm** [comment]
Solution has already mentioned above and please use english.
