### ISSUE TITLE
Termux com erro repositorio

### ISSUE THREAD

**Issue by ghostkiller-gif** [termux/termux-app#1883]
apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
E: Could not get lock /data/data/com.termux/cache/apt/archives/lock. It is held by process 32542 (apt)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to lock directory /data/data/com.termux/cache/apt/archives/

Esse erro estou achando que devo remover esse repositorio ou talvez reinstale o termux

ps
  PID TTY          TIME CMD
  618 pts/20   00:00:00 ps
25492 pts/20   00:00:00 bash
~ $ htop
The program htop is not installed. Install it by executing:
 pkg install htop

W: GPG error: https://grimler.se/termux-packages-24 stable Release: The following signatures were invalid: BADSIG 5A897D96E57CF20C Termux Releases (Termux automatic builds) <contact@termux.com>
E: The repository 'https://grimler.se/termux-packages-24 stable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

Tambem aconteceu quando apareceu um waiting lock for cache dpkg no repositorio mesmo eu reconfigurando o termux-change-repo vem a acontecer isso

Waiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by process 32542 (apt)
Waiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontenWaiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by process 32542 (apt)
Reading package lists... 0%

**Comment by WMCB-Tech** [comment]
Same issue in #1882 

> Waiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by process 32542 (apt)
Waiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontenWaiting for cache lock: Could not get lock /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. It is held by process 32542 (apt)

This problem occurs when another `apt` process is running

**Comment by ghostkiller-gif** [comment]
> Mesmo problema em [# 1882](https://github.com/termux/termux-app/issues/1882)
> 
> > Esperando pelo bloqueio do cache: Não foi possível obter o bloqueio /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontend. Ele é mantido pelo processo 32542 (apt) 
> > Aguardando bloqueio de cache: Não foi possível obter bloqueio /data/data/com.termux/files/usr/var/lib/dpkg/lock-frontenAguardando bloqueio de cache: Não foi possível obter bloqueio / dados /data/com.termux/files/usr/var/lib/dpkg/lock-frontend. É realizado pelo processo 32542 (apt)
> 
> Este problema ocorre quando outro `apt`processo está sendo executado

Como faço pra resolver isso

**Comment by WMCB-Tech** [comment]
> This problem occurs when another `apt` process is running
Maybe there's another `apt` process is running, 

Try executing:
`ps a | grep apt`

If there's an `apt` process, then you have to terminate it or wait

---

Btw, please speak in english

**Comment by ghostkiller-gif** [comment]
> > Este problema ocorre quando outro `apt`processo está em execução. 
> > Talvez haja outro `apt`processo em execução,
> 
> Tente executar:
> `ps a | grep apt`
> 
> Se houver um `apt`processo, você deve encerrá-lo ou esperar
> 
> Btw, por favor fale em ingles

Ok

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-04-52-48](https://user-images.githubusercontent.com/77376582/104422253-443a7a00-555b-11eb-822b-a56cbcfc5869.png)

**Comment by ghostkiller-gif** [comment]
ok I did this process and now

> > > Este problema ocorre quando outro `apt`processo está em execução. 
> > > Talvez haja outro `apt`processo em execução,
> > 
> > 
> > Tente executar:
> > `ps a | grep apt`
> > Se houver um `apt`processo, você deve encerrá-lo ou esperar
> > Btw, por favor fale em ingles
> 
> Está bem

ok I did this process and now

**Comment by ghostkiller-gif** [comment]
![Screenshot_2021-01-13-05-04-21](https://user-images.githubusercontent.com/77376582/104423500-f0309500-555c-11eb-9c04-14b2054275b8.png)

**Comment by Grimler91** [comment]
Repo is fixed now, so `pkg upgrade` should work with the grimler.se mirror as well. Thanks for reporting!
