### ISSUE TITLE
F-Droid Termux on android 11

### ISSUE THREAD

**Issue by cadanganrendy** [termux/termux-app#1895]
I'm using mi 9 with revengeos android 11, i'm trying to install termux 103, 104, and 105 from f-droid... and can't get installed because the installer say "unknown error"
i'm trying installing from f-droid app and download direct from f-droid site... both not working...

**Comment by Grimler91** [comment]
Do you have any termux apps (termux-app, termux-api, termux-boot, ..) installed from any other source (like google play)? All apps need to be installed from the same source as they are signed with different keys on google play and fdroid.

A logcat would show a more detailed error message if you do not believe the installation source to be the problem.

**Comment by cadanganrendy** [comment]
im forgot to uninstall termux-api installed from google play... thnks..
