### ISSUE TITLE
Is it possible to create an APK with pre-installed scripts and packages? 

### ISSUE THREAD

**Issue by ethixkr** [termux/termux-app#1898]
**Dumb-Proofing**

**Ability to "pre-package" scripts and packages for my clients to run on their device without having to go through the "terminal experience" which can be intimidating for those unfamiliar with Linux.**

Would this be possible?

**Comment by WMCB-Tech** [comment]
Yes, it's possible by changing the bootstrap sources by yourself, but I don't think this will be implemented without recompiling the app with changed bootstrap

Alternate way is backup and restore

**Comment by ethixkr** [comment]
I see... even if it's just running a few lines of code to properly set up FRP-client and an SSH? I set up a reverse proxy for a client and it's apparently so useful that he wants to scale it up to all his employees. That'd be a nightmare for me...

**Comment by xeffyr** [comment]
Either repack & re-compile existing bootstrap archives or implement a custom installer for your scripts. No way - you have to re-compile the application.
