### ISSUE TITLE
Add LXDE to termux

### ISSUE THREAD

**Issue by The-C-programmer** [termux/termux-app#1900]
add LXDE to termux.
-->

**Feature description**

**Reference implementation**

UserLAnd has LXDE on it.
https://wiki.termux.com/wiki/Graphical_Environment

**Comment by Yisus7u7** [comment]
![Screenshot_20210123-125553](https://user-images.githubusercontent.com/64093255/105611888-29031200-5d86-11eb-8f3b-a1669173f5fc.png)
No me parece buena idea amigo, termux ya tiene xfce4 y ellos aparte dijieron que no iban a migrar más escritorios, aparte xfce 4 es altamente personalizable :

**Comment by The-C-programmer** [comment]
> ![Screenshot_20210123-125553](https://user-images.githubusercontent.com/64093255/105611888-29031200-5d86-11eb-8f3b-a1669173f5fc.png)
> No me parece buena idea amigo, termux ya tiene xfce4 y ellos aparte dijieron que no iban a migrar más escritorios, aparte xfce 4 es altamente personalizable :

Yo leí que los desarrolladores de Termux dijeron en la wiki que no iban a migrar más escritorios; "Es posible configurar un entorno de escritorio completo en Termux. Solo se admite XFCE, no se está planificando la migración de otros entornos." Eso fue lo que dijeron, pero no me acuerdo en qué fecha lo publicaron.

**Comment by The-C-programmer** [comment]
I am Uruguayan and I speak Spanish, I don't know if you speak Spanish.

**Comment by The-C-programmer** [comment]
> ![Screenshot_20210123-125553](https://user-images.githubusercontent.com/64093255/105611888-29031200-5d86-11eb-8f3b-a1669173f5fc.png)
> No me parece buena idea amigo, termux ya tiene xfce4 y ellos aparte dijieron que no iban a migrar más escritorios, aparte xfce 4 es altamente personalizable :

En Termux, ya hay un repositorio llamado X11-packages, ahí están las fuentes para paquetes inestables de Termux, capaz que ahí puede estar LXDE.

**Comment by Yisus7u7** [comment]
Uno solo puede instalar xfce4, no LXDE, con el x11-repo, esta solicitud de paquete deber ser cerrada

**Comment by The-C-programmer** [comment]
> Uno solo puede instalar xfce4, no LXDE, con el x11-repo, esta solicitud de paquete deber ser cerrada 

Vale

**Comment by The-C-programmer** [comment]
> Uno solo puede instalar xfce4, no LXDE, con el x11-repo, esta solicitud de paquete deber ser cerrada 

La puedo cerrar yo?

**Comment by DarthZedd** [comment]
Why not just use Andronix?

**Comment by WMCB-Tech** [comment]
Yeah, you can run LXDE and ssh your termux into it

**Comment by Yisus7u7** [comment]
Pero ya Andronix no tiene nada que ver con termux, eso es un projecto aparte

**Comment by WMCB-Tech** [comment]
In my opinion with LXDE, LXDE is not being used by many people (as it's not that visually friendly) and most phones can run XFCE very well as it's the lightweight alternative to LXDE yet visually appealing

---

I think it can be added to termux by looking at these dependencies 
https://wiki.lxde.org/en/Main_Page

In my case in Debian, installing skeleton lxde `apt install lxde-core --no-install-recommends --no-install-suggests` can install with minimal dependencies as possible

I think this should be transferred to x11 packages repo although some people does not like `lxde`

**Comment by Yisus7u7** [comment]
The developers of termux said that they will not migrate other desktops, apart you are right, xfce4 is better than lxde

**Comment by WMCB-Tech** [comment]
Yeah, adding such packages may not have some effort in the terms of usability and lxde is currently replaced by lxqt, and still uses GTK2 (Arch Linux provides GTK3 Variant of LXDE)
