### ISSUE TITLE
termux api hangs on android 11 / oneplus 7

### ISSUE THREAD

**Issue by mitnk** [termux/termux-app#1902]
Programs like `termux-notification -c text` hangs forever, after upgrading my OS version today. Does not work after a uninstall and re-install from F-Droid.

How could I dig more info what I'm missing? I've gave every possible permission related to the two apps. Thanks.

* Termux application version: latest from F-Droid
* Termux API version: latest from F-Droid
* Android OS version: 11 (security update 2020-12-01 kernel 4.14.190-perf+)
* Device model: OnePlus 7 (GM1900_15_210110)

**Comment by mitnk** [comment]
Nice that it works after I uninstall them all and re-installed them from Google Play. Versions on F-Droid seems outdated.

**Comment by xeffyr** [comment]
> Versions on F-Droid seems outdated.

Google Play builds are end-of-life and NOT recommended for use. That's F-Droid is up-to-date. https://github.com/termux/termux-app/releases

**Comment by mitnk** [comment]
@xeffyr do I used a fake F-Droid app ... I checked it F app itself, it says it up to date. And check termux app on the platform, it says termux was last updated months ago. screenshot below:

![image](https://user-images.githubusercontent.com/177049/105576565-96c33400-5dae-11eb-8e92-20b6f00d93fd.png)

Should I only use F-Droid website?

**Comment by xeffyr** [comment]
Maybe you are using some unofficial F-Droid... Ensure this is not a Kali Nethunter Store as it provides outdated versions.

Use v0.104 (as v0.105 broken) from F-Droid website.
![Снимок экрана от 2021-01-23 13-21-17](https://user-images.githubusercontent.com/25881154/105576850-52b83b00-5d7e-11eb-8994-4ff42d3955c3.png)

**Comment by mitnk** [comment]
@xeffyr Thanks a lot!
