### ISSUE TITLE
Cannot play any audio files using the built-in AOSP media player after updating to v0.105

### ISSUE THREAD

**Issue by TheMCNerd2017** [termux/termux-app#1905]
**Problem description**

Upon updating to the latest version of Termux that was offered on F-Droid (v0.105 which I didn't know was broken until now) I can no longer open/listen to any audio files of any kind. I am not offered the option to use the built-in AOSP media player, only the option to open the file with Termux.

**Steps to reproduce**

1. Install the 0.105 or later version of Termux on a device running GrapheneOS or any other Android OS that only contains the default AOSP media player.
2. Attempt to open any audio file. The file will open with Termux and attempting to choose what program to open the audio file with will only show Termux as a valid option.

**Expected behavior**

Audio files (wav, mp3, opus, etc) should open with the built-in AOSP media player and not be restricted to opening only in Termux.

**Additional information**

* Termux application version: v0.105
* Android OS version: GrapheneOS 11 (2021.01.05.03)
* Device model: Pixel 4 XL

**Comment by alou-S** [comment]
Try going to Android Settings > Apps 

Select any Termux related apps (Termux, Termux:API etc)
Select Set as default
Hit Clear Defaults

This should work

**Comment by TheMCNerd2017** [comment]
> Try going to Android Settings > Apps
> 
> Select any Termux related apps (Termux, Termux:API etc)
> Select Set as default
> Hit Clear Defaults
> 
> This should work
> 
> If it doesn't then its either on the media 0layer or Android's end since it doesn't properly associate media files with the AOSP player

Sorry for the very late response (I don't check my email very often), but everything on the "Open by default" menu for Termux is grayed out. I can't set defaults or reset them. I'm guessing it's either an issue with the AOSP media player itself or Android. I've since installed another media player (Vanilla Music) which gives me almost all of the functionality that the stock AOSP media player provided when it was usable.

**Comment by agnostic-apollo** [comment]
Termux has no control over what your default app is set for specific file types. If I set Termux as default for mp3 files on my Android 7 device and Android 11 avd, it does say in Termux App Info "Some defaults set" and I can clear them. If its not showing in your phone, then its your phones issue, not Termux. You can try using in `Android Settings` > `Apps` -> `Options` (3 dots on top right) -> `Reset app preferences`, or` Android Settings` -> `System` > `Advanced` > `Reset app preferences`
