### ISSUE TITLE
Last update (v. 0.105) doesn't work on Samsung S8+ SM-G955F

### ISSUE THREAD

**Issue by PolGZ** [termux/termux-app#1907]
Hi, today I tried to open termux and it didn't launch. I tried erasing cache, erasing full data + uninstall-install, but it didn't open.

Got the 0.104 version (everything through F-Droid) and it starts and run perfectly again.

Samsung Galaxy S8+ SM-G955F Android 9 (last OTA version available) kernel 4.4.111-18920278

**Comment by lolorc** [comment]
Same here with los 17.1 on s9+

**Comment by PolGZ** [comment]
Thats right! sorry! I skipped it since it said "Android 10 EMUI 10.1.0 (witch does not support Google play services)" and that is far from my case. I didn't read the coments about 0.106. Hope it comes soon to F-Droid!
