### ISSUE TITLE
Why can't I use tsu？

### ISSUE THREAD

**Issue by q821863269** [termux/termux-app#1909]
pkg i -y tsu
After installing tsu

$tsu
enter main
/system/xbin/su: invalid option -- -

Why can't I use tsu？
Hope to get an answer

Just ask,Can you install OpenVPN on termux?

* Termux application version: 0.73
* Android OS version: Android5.1
* Device model: MEIZU MX5

**Comment by xeffyr** [comment]
What issue I see only here is that you seems using official `su` provided by Meizu and it is not supported by `tsu` wrapper. Recommended rooting methods are Magisk and SuperSU only.

As Termux or Android 5 no longer receives official support, this issue is not going to be fixed.
