### ISSUE TITLE
am start fails unless termux is in foreground

### ISSUE THREAD

**Issue by tunerooster** [termux/termux-app#1912]
I am running vanilla Android 10 on a Teclast M40 tablet with termux and openssh installed.

I am trying to run this command (over ssh):
```
 am start io.homeassistant.companion.android/.launch.LaunchActivity
```
I can ssh into termux with no problem.  However, when I run the above command via ssh, it does nothing.
**__But__**:
If I run termux **__on the tablet__** so termux is running in the foreground, before running the command over ssh, *then* run the same command, **__it works__** just fine.

I need to be able to start/restart (-S option) the app when termux is not running (but when sshd is running).  Is there any way to do this?

Please and thank you for any advice!

**Comment by xeffyr** [comment]
That's all about Android 10 restrictions about background activities: https://developer.android.com/guide/components/activities/background-starts.

**Comment by tunerooster** [comment]
I see.  I also noticed this...  Is it relevant (i.e., could termux be modified to call "the startForegroundService() method instead of startService()"?

From: https://developer.android.com/about/versions/oreo/background
-----------------------------------------------------------

By default, these changes only affect apps that target Android 8.0 (API level 26) or higher. However, users can enable these restrictions for any app from the Settings screen, even if the app targets an API level lower than 26. You may need to update your app to comply with the new limitations.

Check to see how your app uses services. If your app relies on services that run in the background while your app is idle, you will need to replace them. Possible solutions include:

If your app needs to create a foreground service while the app is in the background, use the startForegroundService() method instead of startService().
If the service is noticeable by the user, make it a foreground service. For example, a service that plays audio should always be a foreground service. Create the service using the startForegroundService() method instead of startService().
