### ISSUE TITLE
termux-storage-get hangs on Pixel 3 running Android 11

### ISSUE THREAD

**Issue by John-L** [termux/termux-app#1916]
Termux v0.101 command termux-storage-get hangs on Pixel 3 with Android 11 and latest version from Google Play.

Cntl-C required to cancel program.

**Steps to reproduce**

> termux-storage-get a.txt
**Expected behavior**

Expect default file chooser app to open.
**Additional information**

When is the v1.0 release targeted for Google Play?

* Termux application version: v0.101
* Android OS version: 11 (latest)
* Device model: Pixel 3

**Comment by xeffyr** [comment]
Doesn't hang on Pixel 5.

**Comment by John-L** [comment]
I get the same results before, and after, running the termux-setup-storage command, that prompts me to allow access to the file system. The documentation seems to suggest this isn't necessary, regardless, it doesn't affect the failure.

How do I install the Termux:API application? I have previously installed the termux-api package.

**Comment by xeffyr** [comment]
@John-L You can install Termux:API from same source where you got the app. 

Google Play: https://play.google.com/store/apps/details?id=com.termux.api
F-Droid: https://f-droid.org/en/packages/com.termux.api/

Package doesn't work without application.

**Comment by John-L** [comment]
Thanks. All set.
