### ISSUE TITLE
How to make ps command working under Termux/Ubuntu?

### ISSUE THREAD

**Issue by kotoOo** [termux/termux-app#1917]
> You need to bind mount fake proc `uptime` `stat` if using `ps` command
> `proot-distro` already handles this one including [Andronix](https://github.com/AndronixApp/AndronixOrigin/commit/390288d66e3f4c746e3575aa321d0998b5c31599) as well but missing both `loadavg` and `uptime` for other process viewing utilities
> It seems this will be used as default bind mounts on `proot` helpers out there
> _Originally posted by @WMCB-Tech in https://github.com/termux/termux-app/issues/299#issuecomment-770606076_

@WMCB-Tech Thanks a lot for the useful answer! 
@xeffyr What's the point of not only arguing for no-feature, but also locking that thread and therefore not letting people discuss a possible solution?

Of course we cannot overcome host OS restrictions, however nobody is asking for that, I'm looking for only how to get an emulated system working properly. I do not expect to get a full list of my Android processes there, but I do expect the command working and giving me processes that were started within this emulated Ubuntu environment. Once Linux on Dex stopped developing, Termux is probably the best way nowadays to set up a web developer's workspace on Android. But some important parts are missing. So let's get clear about perspectives at least.

**Comment by xeffyr** [comment]
@kotoOo Have you what was suggested by @WMCB-Tech? Or at least to look at https://wiki.termux.com/wiki/PRoot (read whole page, btw)? It has a solution, briefly:
```
pkg install proot-distro
proot-distro install ubuntu-20.04
proot-distro login ubuntu-20.04
# Continue in Ubuntu environment from there
```

> I'm looking for only how to get an emulated system working properly

Given solutions is not enough? Ok explaining:

To get working `ps` and other utilities, you need some files in `/proc` (loadavg, stat, vmstat, version, uptime) be at least readable. As you can't make them readable without root, then inside `proot` you need provide fake files with such name but appropriate data. See how `proot-distro` does it:
* Filling data: https://github.com/termux/proot-distro/blob/master/proot-distro.sh#L533
* Bind: https://github.com/termux/proot-distro/blob/master/proot-distro.sh#L1136-L1159

> So let's get clear about perspectives at least.

There not so much to discuss on this issue. You are limited to these variants:
1. Use a patched `procps` and other proc packages like Termux does.
2. Setup a custom `/proc` inside `proot`, like `proot-distro` utility does.
3. Use QEMU in system mode to run a custom OS without restrictions.
4. Use rooted shell.
5. Use custom ROM with SELinux in permissive mode or modified sepolicy (like Lineage OS ROMs).
