### ISSUE TITLE
Question: Change fonts to disable use of emoji related characters?

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#1919]
running certain commands that use certain special character tend to have a non homogenous output for said characters and symbols and end up showing 'emoji' like character output.

can the font(s) be changed to disable that and have a lightly more purist character set?

**Comment by xeffyr** [comment]
You may try to search such fonts, download a TTF file and place it to `~/.termux/font.ttf` and restart application.

However I'm not sure that this will work. Everything is rendered by Android OS, including fonts. If this is a reason of emojis being shown, then Termux will have to implement own renderer which unlikely to happen (considering that key parts are actually a copy from https://github.com/jackpal/Android-Terminal-Emulator).
