### ISSUE TITLE
"libandroid_runtime.so" is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by mtsdesign** [termux/termux-app#192]
Hi there,
Have an isue when running the terminux-setup-storage command. The command gives an error CANNOT LINK EXECUTABLE DEPENDENCIES: "libandroid_runtime.so" is 64-bit instead of 32-bit.
I am on an unrooted kindle fire 6th gen (which is 64bit)

Many thanks for the great product.
MTS

**Comment by Neo-Oli** [comment]
What is the output of `dpkg --print-architecture`?

**Comment by renebruns** [comment]
Chiming in here as I have the same issue on my Kindle Fire HD 8 (2016):

Created some debugging output:
```
$ termux-setup-storage
CANNOT LINK EXECUTABLE DEPENDENCIES: "libandroid_runtime.so" is 64-bit instead of 32-bit

$ uname -a
Linux localhost 3.18.19-g1f9a828 #1 SMP PREEMPT Thu Dec 1 11:53:01 UTC 2016 armv8l Android

$ dpkg --print-architecture
arm

$ file /system/lib/libandroid.so
/system/lib/libandroid.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped

$ file /system/lib64/libandroid.so
/system/lib64/libandroid.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped

$ getprop | grep cpu
[ro.boot.secure_cpu]: [1]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
```

Hope that helps. Let me know if you need anything more.

**Comment by mtsdesign** [comment]
Hello, sorry for slow reply. I have been moving house.

output for last version and recently updated version is the same:

$ termux-setup-storage
CANNOT LINK EXECUTABLE DEPENDENCIES: "libandroid_runtime.so" is 64-bit instead of 32-bit

$ uname -a
Linux localhost 3.18.19-g1f9a828 #1 SMP PREEMPT Thu Dec 1 11:53:01 UTC 2016 armv8l Android

$ dpkg --print-architecture
arm


$ getprop | grep cpu
[ro.boot.secure_cpu]: [1]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]


Many thanks
M

On 3 January 2017, at 09:07, Oliver Schmidhauser <notifications@github.com> wrote:

What is the output of dpkg --print-architecture?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/termux/termux-app","title":"termux/termux-app","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/termux/termux-app">https://github.com/termux/termux-app</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Neo-Oli in #192: What is the output of `dpkg --print-architecture`?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/termux/termux-app/issues/192#issuecomment-270073040">https://github.com/termux/termux-app/issues/192#issuecomment-270073040</a>"}}}

**Comment by fornwall** [comment]
Could you affected print the output of running:

    ls -lha /system/bin/linker /system/bin/app_process

**Comment by renebruns** [comment]
Exactly the same here

**Comment by fornwall** [comment]
@renebruns @mtsdesign Thanks for the information!

Could you run `apt update && apt upgrade` to update to version `0.34` of the `termux-tools` package and check if that resolves this issue?

**Comment by mtsdesign** [comment]
Yes, that's working for me.

Thanks so much - it's made using termux much easier.
Now just to find a way to root this damn tablet.

Many thanks again.
Mike
