### ISSUE TITLE
curl: (3) URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by zerodekk** [termux/termux-app#1920]
curl -L " https://git.io/tmpsms "  > tmpsms && chmod + x tmpsms

Its showng 
curl: (3) URL using bad/illegal format or missing URL
What the problem?

**Comment by xeffyr** [comment]
Double-check what you are typing... Either remove quotes or remove spaces before and after URL.
```
curl -L https://git.io/tmpsms > tmpsms && chmod + x tmpsms
```
