### ISSUE TITLE
VNC lost connection about per 20 seconds

### ISSUE THREAD

**Issue by zeerd** [termux/termux-app#1924]
**Problem description**

I am using Termux + Andronix + PCMode on an OnePlus8T.

The Andronix could install an Ubuntu Desktop with VNC Server running on Termux. So I could run a VNC Client to connect the server and use the desktop.

It works fine, when I run the VNC Client from a PC via network.
But when I run a VNC Client from the PC-Mode of the phone-itself, the VNC connection will lost about each 15~20 seconds.

At this moment, If I touch the termux application on the screen of the phone, the connection might come back to work for a next 15~20 seconds, and then, lost again.

I am not sure of that it's an issue of Termux or Andronix or the Android-OS itself.
Just looking for some suggest.

**Steps to reproduce**
1. Install an Ubuntu 20.04 with FXCE following the wizard of Andronix.
2. run ./start-ubuntu.sh to start the ubuntu desktop from Termux commandline.
3. run vncserver-stop to stop the default vnc(sometimes, it's broken), and run vncserver-start to restart it again.
4. Use any VNC Client to connect it from the PC Mode(the port of VNC Server is 5901).
5. The VNC Client could work, and then, the connection of VNC will lost after about 15~20 seconds.
6. Touch the termux application on the screen of phone might make the connection back. Looks like the Termux lost the activation and got it back again.

**Expected behavior**

Hope the VNC could work well both from a remote PC and from the PC Mode of the phone itself.

**Additional information**

* Termux application version: 0.106 from F-Droid
* Android OS version: Hydrogen OS 11.0.6.8.KB05/Android 11 with  Security update of Nov,1,2020 and Google Play System Update of Oct,1,2020.
* Device model: OnePlus8T

**Comment by WMCB-Tech** [comment]
Maybe the Battery Optimization Killed your VNC Session, you need to toggle wakelock and whitelist Termux

**Comment by zeerd** [comment]
I closed all the settings I could found.

According this url: https://dontkillmyapp.com/oneplus

I disabled both the Deep optimization and the Sleep standby optimization .
And, Turn off System settings > Battery > Battery optimization, switch to ‘All apps’ in top right menu > Termux > Don’t optimize
And, locked the Termux in recent app.

**Comment by xeffyr** [comment]
Look the VNC server log first. Maybe it just crashes.
