### ISSUE TITLE
termux-notification does not work in background scripts (i.e., those in $HOME/.shortcuts/tasks)

### ISSUE THREAD

**Issue by bdantas** [termux/termux-app#1925]
_termux-notification_ works if script is in /data/data/com.termux/files/home/.shortcuts/ but does **not** work if script is in /data/data/com.termux/files/home/.shortcuts/tasks/

**Steps to reproduce**
1. Create this script as /data/data/com.termux/files/home/.shortcuts/tester:
```
#!/bin/sh
termux-notification
```
2. Create a Termux shortcut widget for _tester_ on phone's home screen. Launching the widget produces a notification.
3. Move the script to /data/data/com.termux/files/home/.shortcuts/tasks/tester
4. Delete the Termux shortcut widget for _tester_ and re-create it using the new path. Launching the widget does not produce a notification.

**Expected behavior**
A shell script should be able to create a notification using _termux-notification_ regardless of whether the script is running in a terminal or running in the background.

**Additional information**
* Termux application version: 0.104
* Termux API version: 0.47
* Android OS version: LineageOS 16
* Device model: OnePlus 5

I already tried comparing the environment of terminal vs. background (by redirecting output of _env_ to a log file) and did not find an obvious culprit.

**Comment by agnostic-apollo** [comment]
Likely termux has not been granted [Draw Over Apps](https://github.com/termux/termux-tasker#draw-over-apps-permission-optional) permission.

**Comment by bdantas** [comment]
Thank you, agnostic-apollo. "Display over other apps" (as it seems to be called on LOS16) is now allowed for Termux. The problem persists, unfortunately.

**Comment by agnostic-apollo** [comment]
You need to allow it.

**Comment by bdantas** [comment]
Some more information: 
My trivial _tester_ script (see above) seems to hang when it is run in the background, because it shows up in the output of _pgrep -fa tester_ for about a minute. During that minute, other scripts that call _termux-notification_ also hang, even if they are launched in foreground/terminal.

**Comment by agnostic-apollo** [comment]
So there is an `ANR` being thrown for the `termux-api` `NotificationAPI` if it is started from background.

```
BroadcastQueue: Receiver during timeout of BroadcastRecord{6e40f6b u0 null} : ResolveInfo{db56d04 com.termux.api/.TermuxApiReceiver m=0x0}
com.termux.api I/com.termux.api: Thread[7,tid=8330,WaitingInMainSignalCatcherLoop,Thread*=0xe9693400,peer=0x12c40298,"Signal Catcher"]: reacting to signal 3
com.termux.api I/com.termux.api: Wrote stack traces to tombstoned
/ActivityManager: ANR in com.termux.api
    PID: 7620
    Reason: Broadcast of Intent { flg=0x10 cmp=com.termux.api/.TermuxApiReceiver (has extras) }
``` 

When [ ResultReturner.returnData()](https://github.com/termux/termux-api/blob/v0.47/app/src/main/java/com/termux/api/util/ResultReturner.java#L109) is called by the [NotificationAPI](https://github.com/termux/termux-api/blob/v0.47/app/src/main/java/com/termux/api/NotificationAPI.java#L50), that's where the problem occurs. The background task can also be seen in Termux notification task count. The solution would likely be to move the `NotificationAPI` to an `IntentService` as well like some of other APIs, as recommended by the [ANR](https://developer.android.com/topic/performance/vitals/anr#slow_broadcast_receivers) docs. The [goAsync()](https://developer.android.com/reference/android/content/BroadcastReceiver#goAsync()) wouldn't prevent the `ANR` either. Although, broadcast receivers should be allowed to run for a few seconds, but its still throwing an `ANR`. Confirmed on android 10 avd.

**Comment by bdantas** [comment]
> Thanks for the report.
Sure thing. Thank you very much for taking the time to reproduce the problem and figuring out the underlying issue. Android is not my forte and it would have taken me years (if ever) to come up with a correct and specific diagnosis in this case. 

While there's no fix for this, my workaround will be to run my script via a widget pointing to /data/data/com.termux/files/home/.shortcuts/myscript (i.e., the script will run in foreground terminal, not in the background). A terminal will flash on the screen when I launch the script, but I'll live.

Happy hacking!

**Comment by agnostic-apollo** [comment]
Start by checking android `logcat` when getting into such problems. If you have tasker, then you can use the [Grab Timed And Filtered Logcat](https://github.com/agnostic-apollo/Tasker-Random-Stuff/tree/master/grab_timed_and_filtered_logcat) task to quickly grab logcat entries for the next few seconds, to make searching easier or use [Save logcat, dmesg and last_kmesg](https://github.com/agnostic-apollo/Tasker-Random-Stuff/tree/master/save_logcat_dmesg_last_kmesg) task to dump the entire current `logcat` buffer. Otherwise, use adb from a PC.

There is a fix available, someone just needs to implement it.

And welcome.

**Comment by krystean** [comment]
I'm currently working on a personal project involving Termux:API. What I have learned by digging through the sources is that the `termux-notification` content (option `-c` or `--content`) is not passed as an argument when  the API is called through the client binary in `$PREFIX/libexec/termux-api`. Rather, it is either piped through if content option is set (an input) or waits for stdin instead. The latter is what's causing it to hang -- it's waiting for input. If you're using it in scripts, you need to set the content option or use `echo your_content | termux-notification`. Setting an empty string with `-c` or `--content` will also hang.
  
`termux-toast` is the same case.

**Comment by agnostic-apollo** [comment]
Should be fixed when `termux-api` is updated to `v0.55` as per termux/termux-packages@3255528f

**Comment by agnostic-apollo** [comment]
@krystean Thanks for investigating and finding the real cause. :) Mine was just a side affect.

**Comment by krystean** [comment]
@agnostic-apollo Thank you for fixing it :)

**Comment by agnostic-apollo** [comment]
You are welcome :)
