### ISSUE TITLE
Syscalls implementation

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-app#1927]
I'm curious at how you handle syscalls in termux, not proot. I'm wondering if you guys implement linux-syscall-support.h from chromium/aosp I do find it useful if it can work as a syscall helper. It mirrors libc and allows direct calls. 

Source code

https://chromium.googlesource.com/linux-syscall-support/

**Comment by xeffyr** [comment]
We do not implement them on our own. Termux project is just port of common utilities to Android. There nothing more than few patches and cross-compilation with Android NDK LLVM toolchain.
