### ISSUE TITLE
Cryptic addresses during the update

### ISSUE THREAD

**Issue by LinuxOpa** [termux/termux-app#1929]
**Problem description**

Cryptic addresses during the update

**Steps to reproduce**
apt update / upgrade

**Expected behavior**

**Additional information**

* Termux application version: 
Latest
* Android OS version:
8.0
* Device model:
Cubot X18Plus

are these cryptic addresses ok?

Get:2 **https://ipfs.io/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4** x11 InRelease [14.0 kB]
Ign:3 https://grimler.se/game-packages-24 games InRelease
Ign:4 https://grimler.se/termux-root-packages-24 root InRelease
Ign:5 https://grimler.se/science-packages-24 science InRelease
Get:1 **https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx** stable InRelease [14.0 kB]
Hit:6 https://grimler.se/game-packages-24 games Release
Hit:7 https://grimler.se/termux-root-packages-24 root Release
Hit:8 https://grimler.se/science-packages-24 science Release
**E: Repository 'https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease' **changed its 'Origin' value from 'Bintray' to 'termux-main stable'
**E: Repository 'https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease' **changed its 'Label' value from 'Bintray' to 'termux-main stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N]

**Comment by xeffyr** [comment]
Expected behavior.

https://github.com/termux/termux-packages/issues/6348

**Comment by LinuxOpa** [comment]
ok, thank you.
