### ISSUE TITLE
Enable character based input by default

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#1930]
**Feature description**

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by xeffyr** [comment]
Problem is that
```
InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS
```
is not correct input type. It is used to workaround certain keyboards like a stock one by Samsung but breaks other keyboards which respect `TYPE_NULL`.

Already has been discussed with @fornwall and `TYPE_NULL` remains to be default.
