### ISSUE TITLE
Unable to start service Intent for RUN_COMMAND

### ISSUE THREAD

**Issue by wvthoog** [termux/termux-app#1932]
So I've made a simple Android Kotlin application to start up Bettercap from an external app. Been at this for a couple of days now and it keep complaining about: 

```
2021-02-12 15:13:13.002 1589-2623/? I/AppsFilter: interaction: PackageSetting{6fc3a2 nl.wvthoog.bettercap/10332} -> PackageSetting{d9a2791 com.termux/10207} BLOCKED
2021-02-12 15:13:13.002 1589-2623/? W/ActivityManager: Unable to start service Intent { act=com.termux.RUN_COMMAND cmp=com.termux/.app.RunCommandService (has extras) } U=0: not found
```

This is my AndroidManifest.xml

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="nl.wvthoog.bettercap">

    <uses-permission android:name="com.termux.permission.RUN_COMMAND" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.Bettercap">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

and this is my MainActivity.kt

```kotlin
package nl.wvthoog.bettercap

import android.content.Intent
import android.os.Bundle
import android.widget.Button
import androidx.appcompat.app.AppCompatActivity


class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val btn_click_me = findViewById(R.id.button) as Button
        btn_click_me.setOnClickListener {
            val intent = Intent()
            intent.setClassName("com.termux", "com.termux.app.RunCommandService")
            intent.setAction("com.termux.RUN_COMMAND")
            //intent.action = "com.termux.RUN_COMMAND"
            intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/usr/bin/top")
            //intent.putExtra("com.termux.RUN_COMMAND_WORKDIR", "/data/data/com.termux/files/home");
            //intent.putExtra("com.termux.RUN_COMMAND_BACKGROUND", false);
            startService(intent)

        }
    }
}
```

Have set "allow-external-apps = true"  in ~/.termux/termux.properties

My phone is running Termux 0.101 on Android 11 (Pixel Experience - Magisk rooted) and followed the instructions mentioned in termux/termux-packages#804

Not sure what's wrong here. Can anyone point me in the right direction. Thanks so much.

**Comment by agnostic-apollo** [comment]
This seems to be expected behaviour when targeting sdk 30 (android 11). You need to add `com.termux` package to the [`queries`](https://developer.android.com/training/basics/intents/package-visibility#package-name) element of your `AndroidManifest.xml`.

@xeffyr Maybe add this to the `RunCommandService` file docs.

**Comment by wvthoog** [comment]
Yes, that was it. Now it works correctly. 

Thank you

**Comment by agnostic-apollo** [comment]
Welcome.

**Comment by QiubyZ** [comment]
> Yes, that was it. Now it works correctly.
> 
> Thank you

how to solved ?
please tellme

**Comment by agnostic-apollo** [comment]
> how to solved ?

https://github.com/termux/termux-app/wiki/Termux-Libraries#target-sdk-30-package-visibility

https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent

**Comment by QiubyZ** [comment]
> > how to solved ?
> 
> https://github.com/termux/termux-app/wiki/Termux-Libraries#target-sdk-30-package-visibility
> 
> https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent

can you give me example?

<?xml version='1.0' encoding='utf-8'?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="shortcut.termux">
    <uses-permission android:name="com.termux.permission.RUN_COMMAND"/>
    
    <uses-sdk
        android:minSdkVersion="8"
        android:targetSdkVersion="30" />
    
    <queries>
        <package android:name="com.termux" />
    </queries>
    
    <application
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        android:resizeableActivity="true">

        <activity
            android:name=".MainActivity"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
