### ISSUE TITLE
How to set user name on termux

### ISSUE THREAD

**Issue by wangmings** [termux/termux-app#1933]
How do I set the username on Termux
system: Android 10
For example, change the default username: u0_a484

**Comment by agnostic-apollo** [comment]
Termux is a single user environment and users are assigned by android to each app. You cannot change it. Check [here](https://wiki.termux.com/wiki/Differences_from_Linux) and [here](https://www.reddit.com/r/termux/comments/j87mjn/what_is_the_difference_between_the_u0_xxx_account/?utm_medium=android_app&utm_source=share).
