### ISSUE TITLE
Buildng-cross compiler based on gcc for non android platforms

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-app#1935]
I don't know if this is an app issue or a packages issue. I'm trying to build a cross-toolchain for n64, ps1, msdos, mingw and I always get a libcpp issue. I'm wondering if it is because of the ndk parts or something else.

**Comment by Grimler91** [comment]
You need to be way more specific than that. 

What toolchain, gcc? 
What do you mean with console? 
What do you mean with "libcpp issue", what error do you get?

Most likely the issue is one of the usual android quirks

**Comment by strikersix23** [comment]
psx, n64, anything targeting mips. I'm trying to replicate what happened

**Comment by strikersix23** [comment]
I'm using this repo to build djgpp 
If you want to also replicate this while im trying 
https://github.com/andrewwutw/build-djgpp

**Comment by strikersix23** [comment]
Its an fputc error

![Capture+_2021-02-14-12-28-24](https://user-images.githubusercontent.com/17087430/107885489-41b3a300-6ec0-11eb-8550-72557b648f6f.png)

**Comment by strikersix23** [comment]
> You need to be way more specific than that.
> 
> What toolchain, gcc?
> What do you mean with console?
> What do you mean with "libcpp issue", what error do you get?
> 
> Most likely the issue is one of the usual android quirks

I replicated it the libcpp errors are fputc in lex.c 

![Capture+_2021-02-14-12-28-24](https://user-images.githubusercontent.com/17087430/107885707-7d9b3800-6ec1-11eb-9c42-ff17a37371c2.png)
I deleted my previous comments decide to give a full explanation. everytime I compile gcc 9.2.0 or newer I get an undefined reference to fputc_unlocked and related classes. I did try to patch lex.c using its-pointless repos gcc patches but it continued and still failed. I would like to know if there is a way to fix this

**Comment by xeffyr** [comment]
That's all due to Bionic libc. It just don't have such function. You will need to implement it yourself or use acceptable equivalent like this one:
```
static inline int fputc_unlocked(int c, FILE *stream)
{
        return fputc(c, stream);
}
```

**Comment by strikersix23** [comment]
@xeffyr how do implement it in a header?
