### ISSUE TITLE
Proot is useless 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-app#1936]
Proot de termux, no longer serves or is defective, when I install a distribution using proot-distro, and it starts to decompress resources, many messages come out saying operation not allowed, the same if I use third-party scripts (Andronix app), which happens with proot?, apart from update termux to the latest version of F-droid store, also the version of play store happens to it, which is happening , please help 

**Additional information**

~ $ termux-info
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.71-perf-gb847930 #1 SMP PREEMPT Fri Sep 27 14:15:01 CDT 2019 armv7l Android
Device manufacturer:
motorola
Device model:
moto e5 cruise

**Comment by xeffyr** [comment]
In case of proot-distro, just do `proot-distro remove <distribution>`. Similar in case of Andronix - just `rm -rf` the rootfs, then re-install.

Perhaps you just interrupted rootfs extracting operation at some point and then trying to perform installation over partially extracted.

**Comment by Yisus7u7** [comment]
You didn't tell me, never canceled the process, I erased termux and reinstalled it, and I still did, it fails, always, with anything that fences to install, when I use proot-distro or proot to install a chroot distro, at the time of installation I get messages saying operation not supported, and it is defective

**Comment by Yisus7u7** [comment]
![Uploading Screenshot_20210214-170318.png…]()

**Comment by xeffyr** [comment]
Trying to install on sdcard?

**Comment by Yisus7u7** [comment]
No, I understand that in the sdcard you can not, I am installing it where always, in $HOME of termux

**Comment by xeffyr** [comment]
Ok, then report to https://github.com/termux/proot/issues. More like a device-specific issue.

**Comment by Yisus7u7** [comment]
Ok

**Comment by WMCB-Tech** [comment]
I also have the same problem extracting the rootfs although it works fine afterwards, but I'm not sure how affects the usage of distros
