### ISSUE TITLE
Sustainable mirrors

### ISSUE THREAD

**Issue by Haiz14** [termux/termux-app#1937]
Feature Name: If bandwith (the amount of packages downloaded) exceeds 1GB /day you can pay for more bandwith/day or download more next day.

Now server can be sustainable.

If I missed any detail you can ask
I just had this idea while exercising and I noth familiar with many terms so sorry for using wrong words 'bandwith'.

Thks for reading

**Comment by Haiz14** [comment]
Can do /month or something like that you guys ge the general idea.

**Comment by xeffyr** [comment]
> exceeds 1GB /day you can pay

Our traffic exceeds **terabytes** per day. Paying thousands and even hundreds of USDs is not an option.
