### ISSUE TITLE
Question - Can i Install lightweight linux distributions

### ISSUE THREAD

**Issue by FardeenCodes** [termux/termux-app#1938]
I saw Proot  on your wiki i saw that i can install Arch Linux , Ubuntu , Debian . but can i install distros like 
Puppy Linux , Bodhi Linux .
I want to install them because they are lightweight.

**Comment by WMCB-Tech** [comment]
Bodhi, Puppy is not such and isn't used for chroots,

You may try alpine as a lightweight alternative
