### ISSUE TITLE
Hi can you help me please

### ISSUE THREAD

**Issue by inhdyaii** [termux/termux-app#1939]
why I can't install metasploit
$ pkg install metasploit
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package metasploit

**Comment by FloatKey** [comment]
Simply because any version of metasploit or stored in termux repositories. In addition, many of metasploit functions will be non-functional or root-required.

If you can't understand that, just forgot this kind of tools, termux is not made for this usage.
