### ISSUE TITLE
How can install metasploit

### ISSUE THREAD

**Issue by inhdyaii** [termux/termux-app#1940]
$ pkg install metasploit
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package metasploit

**Comment by Grimler91** [comment]
We do not have it in our repos, it was removed since it is a hacking tool. You will have to compile it yourself from source or find some other place where the package is provided. 

Closing as off-topic.

**Comment by layaachmad** [comment]
_**We do not that discuss about that hacking topics**_

**Comment by xeffyr** [comment]
@layaachmad This issue has been created *before* hacking topic was banned and is closed anyway.
