### ISSUE TITLE
This definetly the worst thing that may happen.

### ISSUE THREAD

**Issue by ako123456** [termux/termux-app#1945]
This definetly the worst thing that may happen.
Though, in AVD with Android Q Preview Termux still works:

![Screenshot_1552922384](https://user-images.githubusercontent.com/25881154/54541377-7d772280-49a2-11e9-9627-7531e47ee074.png)

![Screenshot_1552922415](https://user-images.githubusercontent.com/25881154/54541446-9da6e180-49a2-11e9-9184-19be22758411.png)

_Originally posted by @xeffyr in https://github.com/termux/termux-app/issues/1072#issuecomment-473957917_

**Comment by xeffyr** [comment]
Reposting my comments?
