### ISSUE TITLE
Add an -a option to busybox fstrim

### ISSUE THREAD

**Issue by bugf1xer89** [termux/termux-app#1947]
**Feature description**
The -a option would allow to trim everything in one command

**Reference implementation**
Many Linux distros already have that feature

**Comment by xeffyr** [comment]
Wontfix for that reason as we do not implement custom functionality in provided utilities.

Busybox provides a limited variant of `fstrim` and thus doesn't necessarily should match `fstrim` utility from Linux distributions.
