### ISSUE TITLE
Add .local/bin to path ...

### ISSUE THREAD

**Issue by italomaia** [termux/termux-app#195]
Hello. I just tried to add .local/bin to my $PATH by writing a .bashrc file does ... nothing. Is there a better/advised approach?

**Comment by fornwall** [comment]
The file .profile is better for this - just put your PATH manipulation there.

**Comment by mcurotto** [comment]
@fornwall changing path in ~/.profile or ~/.bashrc does not work when executing scripts through shortcuts or tasker. Is it some issue or am I missing something?
Thanks
