### ISSUE TITLE
Can't find and open my.cnf mariadb in termux

### ISSUE THREAD

**Issue by minhdanhsc** [termux/termux-app#1951]
I installed mariadb from termux. However I need to customize the my.cnf configuration file.
The problem is I can't open the file with nano or vim. as the command: nano /etc/my.cnf.
Can everyone open the my.cnf file. Help me.

**Comment by xeffyr** [comment]
```
nano $PREFIX/etc/my.cnf
```
or
```
nano /data/data/com.termux/files/usr/etc/my.cnf
```

https://wiki.termux.com/wiki/Differences_from_Linux#Termux_is_not_FHS_compliant

**Comment by minhdanhsc** [comment]
sorry but after i run the command:  `nano /data/data/com.termux/files/usr/etc/my.cnf`

I opened the file but there were only a few lines like this. What do I have to do next to reach the true mariadb my.cnf.

 
```
#This group is read both by the client and the server
#use it for options that affect everything

[client-server]

#include *.cnf from the config directory
 
!includedir /data/data/com.termux/files/usr/etc/my.cnf.d
```

**Comment by xeffyr** [comment]
Actually that's a true `my.cnf` provided by mariadb package. Add your configuration in it.

**Comment by minhdanhsc** [comment]
I have to add an example innodb_log_file_size to the file:
```
This group is read both by the client and the server
use it for options that affect everything

[client-server]

#include *.cnf from the config directory
!includedir /data/data/com.termux/files/usr/etc/my.cnf.d
#add here
innodb_log_file_size=128M
```
However, when running `mysql` it gives an error : `mysql : unknown variable 'innodb_log_file_size=128M'`

**Comment by minhdanhsc** [comment]
Thank you for everything. For those who come later. It is true that this file is my.cnf. And I just started adding [mysqld] for it to work.
```
This group is read both by the client and the server
use it for options that affect everything

[client-server]

#include *.cnf from the config directory
!includedir /data/data/com.termux/files/usr/etc/my.cnf.d
#add here note 
[mysqld]
innodb_log_file_size=128M
```
