### ISSUE TITLE
What is this url that apt is using?

### ISSUE THREAD

**Issue by s0uls0ci3ty** [termux/termux-app#1956]
https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx:

**Comment by agnostic-apollo** [comment]
It's a new repository mirror due to bintray shutdown. Check [here](https://www.reddit.com/r/termux/comments/lpugwd/repository_10via0com_changed_its_label_value_from/god62vw?utm_source=share&utm_medium=web2x&context=3) and issue #6348

>Grimler91:
>It is a consequence of us moving away from bintray (as mentioned already). Before, bintray created the metadata, and set that tag to bintray. Now that we are building and signing ourselves there is no reason for keeping "bintray" in that tag. Apt warns you since this metadata changed even though the url is the same. You have to accept it once, and then it is remembered for the future
