### ISSUE TITLE
Dark/Light theme request 

### ISSUE THREAD

**Issue by Morpheus2077** [termux/termux-app#1957]
Add fully dark/light theme into status bar, extra keys background and maybe for pop-up menu, not only to side menu

**Comment by WMCB-Tech** [comment]
Already Implemented,

Just add this into your termux.properties file

```
use-black-ui = true
```

or turn on dark theme on your device's settings

**Comment by Morpheus2077** [comment]
> Already Implemented,
> 
> Just add this into your termux.properties file
> 
> ```
> use-black-ui = true
> ```
> 
> or turn on dark theme on your device's settings
