### ISSUE TITLE
[BUG]: Something wicked happened resolving 'main.termux-mirror.ml:https'

### ISSUE THREAD

**Issue by PinkDev1** [termux/termux-app#1958]
**Problem description**

After running `apt update` it seems it can't connect to `main.termux-mirror.ml`:
```bash
~ $ apt update
Err:1 https://main.termux-mirror.ml stable InRelease
  Something wicked happened resolving 'main.termux-mirror.ml:https' (7 - No address associated with hostname)
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:5 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Fetched 11.5 kB in 6s (1889 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
39 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Failed to fetch https://main.termux-mirror.ml/dists/stable/InRelease  Something wicked happened resolving 'main.termux-mirror.ml:https' (7 - No address associated with hostname)
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

I know this is not a connection error on my end, because I can browse online, `curl example.com`, etc. I also know it's not my end that's failing, because it seems other sites can't reach `main.termux-mirror.ml` either:[[1]](https://www.isitdownrightnow.com/main.termux-mirror.ml.html)[[2]](https://downforeveryoneorjustme.com/main.termux-mirror.ml)

![IsItDown_Results](https://i.imgur.com/tam1DFA.png)
![Down_for_Everyone_or_Just_Me_Results](https://i.imgur.com/W43Ug9X.png)

The contents of my `sources.list`:
```bash
deb https://main.termux-mirror.ml/ stable main
```

I know this is not simply a classic "server is down", bc I've tried to update weeks before, but I got the same error back then.
Did I miss anything? Was I supossed to change my sources.list? 

**Additional information**

* Termux application version: 0.108 (F-Droid Release)
* Android OS version: 9
* Device model: Moto e(6) plus

**Comment by WMCB-Tech** [comment]
do `pkg update` again, it seems you still have bintray repos which your repository index is outdated

**Comment by xeffyr** [comment]
Use `pkg update`, it will check the mirror before use. And please update your Termux app (v0.108 at least) as only it includes up-to-date mirror lists.

termux-mirror.ml has been shutdown permanently as part of switching to IPFS as per https://github.com/termux/termux-packages/issues/6348#issuecomment-776169136.
