### ISSUE TITLE
High battery drainage with background Termux (even with just bash)

### ISSUE THREAD

**Issue by tmp6154** [termux/termux-app#1959]
**Problem description**

Running Termux in background (even without any activity - just a single session with bash prompt is enough, no CPU or network intensive tasks) drains quite a lot of power. Amongst all battery consumers, Termux alone draws a whopping 80%. Need to note that this is **without** a wakelock. This makes phone to burn more than twice the power that normally is used during idling, so naturally - the only workaround I have to use now is to kill the Termux forcibly via settings when not used (plain exit doesn't work - if session is closed by typing "exit" in bash prompt - Termux still runs and still consumes the same).

![IMG_20210307_114722](https://user-images.githubusercontent.com/5955408/110234378-35f55280-7f3b-11eb-8cb5-0c970a05a28c.jpg)

**Steps to reproduce**

Just run termux and leave session in background (switch to other app or launcher).

**Expected behavior**

Modest battery consumption during idling.

**Additional information**

* Termux application version: 0.101
* Android OS version: MIUI Global 12.0.2 (Android 10)
* Device model: Xiaomi Mi 9T Pro

**Comment by agnostic-apollo** [comment]
Maybe you are running some processes in rc files or something. Run `ps -aux` or `top` to find running processes. Run with `su` if you have granted termux root. I often have termux running the whole day without any battery drained notified by android battery management or BetterBatteryStats. This could be a device specific issue too, so also run `logcat` and see if it is throwing something.

**Comment by tmp6154** [comment]
No, there's nothing besides bash and ps. My device is not rooted, so there's no root processes.

`$ ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
u0_a171  11541  0.0  0.0  29620  4508 pts/0    S<s   1970   0:00 /data/data/com.t
u0_a171  11779  1.0  0.0  27748  3136 pts/0    R<+   1970   0:00 ps -aux`

But it's good to know that it's not normal. I already thought so, but was unable to Google anything about Termux's battery use to confirm it.

You may be right that this is device specific problem, because in Android battery management it looks rather peculiar. I mean, despite it adds up to 80% of all battery consumption, reported CPU time for Termux is just 2 seconds, which indicates that process is (mostly) idling.

Since the screen is off during that time, the only reason I can think of for battery drainage is that OS keeps a CPU wakelock for Termux for some reason and accounts all battery use to that. Even though in notifications, Termux reports that wakelock is not acquired and there's "acquire" button. That would also explain, why battery is still drained, when session is closed via exiting bash.

**Comment by agnostic-apollo** [comment]
Yeah, that little CPU time shouldn't drain battery. Run `adb shell dumpsys power` and check under the `Wake Locks` section to see active wakelocks. There are battery monitoring apps as well, but you can check out google's own [battery-historian](https://github.com/google/battery-historian) to see what's going on. Also check `logcat`, it will likely throw something to indicate the issue.

**Comment by tmp6154** [comment]
![image](https://user-images.githubusercontent.com/5955408/110255576-85706880-7fa5-11eb-8444-90b9172a1a6c.png)

Looks like there were some full wakelocks, but if their full time is really accurate, they were too short to cause battery drain.

**Comment by agnostic-apollo** [comment]
How did you take these readings? Did you let phone run for a while after boot or after enabling [`full-wake-history`](https://github.com/google/battery-historian#wakelock-analysis). Termux by default doesn't acquire wakelocks automatically as far as I know, so they shouldn't even be on the list, unless something is acquiring them. You need to check your termux app data or plugins to see possible acquirers. Maybe [backup termux](https://wiki.termux.com/wiki/Backing_up_Termux) and then clear data/reinstall if you can't find the issue and see if battery drain still exists. Did `logcat` not show anything relavent?

**Comment by tmp6154** [comment]
Looks like on my phone, disabling the notifications in the application's settings stops the battery drainage for some reason. Yes, so it appears that this was caused by OS build on my phone not liking the Termux's notification (one with session count and "acquire wakelock" button). After disabling notifications, battery usage goes back to normal.

![image](https://user-images.githubusercontent.com/5955408/110857124-849f4580-82c9-11eb-879f-d80e325dc9c9.png)

**Comment by agnostic-apollo** [comment]
Unless you can provide more specific info of why that is happening, we can't fix it, if it's even possible considering this is likely a device specific issue. Logs would help, which you still haven't responded about. MIUI seems to have weird issues with notifications like termux/termux-tasker#38, so you may want to wait for an update and see if that fixes it.

**Comment by tmp6154** [comment]
Regarding the logs - there seems to be several termux-related warnings, but I'm not sure if there's anything useful.

> callback=android.app.ITransientNotification$Stub$Proxy@1fe1d36
> 03-12 10:19:28.324  1614  4185 W ActivityTaskManager: Duplicate finish request for ActivityRecord{4ad8d53 u0 com.termux/.app.TermuxActivity t17054 f}
> 03-12 10:21:02.564  1614  2459 W NotificationService: Toast already killed. pkg=com.termux callback=android.app.ITransientNotification$Stub$Proxy@3c9d847
> 03-12 10:21:08.514  1614  4157 W ActivityTaskManager: Force removing ActivityRecord{c576cc0 u0 com.termux/.app.TermuxActivity t17054 f}: app died, no saved state
> 03-12 16:00:23.158 12331 12331 W bash    : type=1400 audit(0.0:31043): avc: granted { execute_no_trans } for path="/data/data/com.termux/files/usr/bin/rsync" dev="sda31" ino=2758792 scontext=u:r:untrusted_app_27:s0:c171,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c171,c256,c512,c768 tclass=file
> 03-12 16:00:23.158 12331 12331 W rsync   : type=1400 audit(0.0:31044): avc: granted { execute } for path="/data/data/com.termux/files/usr/bin/rsync" dev="sda31" ino=2758792 scontext=u:r:untrusted_app_27:s0:c171,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c171,c256,c512,c768 tclass=file
> 03-12 16:00:23.208 12331 12331 W rsync   : type=1400 audit(0.0:31045): avc: granted { execute } for path="/data/data/com.termux/files/usr/lib/libcrypto.so.1.1" dev="sda31" ino=2755269 scontext=u:r:untrusted_app_27:s0:c171,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c171,c256,c512,c768 tclass=file
> 03-12 16:02:00.271 28287 28299 W com.termux: Reducing the number of considered missed Gc histogram windows from 1341 to 100
> 03-12 16:10:29.832 13402 13402 W Finsky  : [2] ggc.p(4): No everExternallyHosted provided for com.termux
> 03-12 16:10:32.607 13402 13402 W Finsky  : [2] ggc.p(4): No everExternallyHosted provided for com.termux

**Comment by agnostic-apollo** [comment]
> `ActivityTaskManager: Duplicate finish request for ActivityRecord`

That will be fixed by #1953

> `ActivityTaskManager: Force removing ActivityRecord`

That's probably normal, when android OOM kills an app.

>  `avc: granted`

Those are `auditallow` rules for selinux, normal too.

Nothing related to notification battery drain issues itself, might not even be logged if its a bug in the OS. You can report it to xiaomi, there is an MI community, maybe they can help. Basically doesn't seem to be a termux issue itself, so closing for now. Can be opened again if more info is found on if termux can fix this.
