### ISSUE TITLE
Issue updating

### ISSUE THREAD

**Issue by Post-Man91** [termux/termux-app#1961]
**Problem description**

I recieve this error when running apt update 
Err:5 https://main.termux-mirror.ml stable Release
  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. 

**Steps to reproduce**
 Update from fdroid then Apt update 

**Expected behavior**
expect everything to update as usual

**Additional information**

* Termux application version:version 0.108
* Android OS version:8.1
* Device model:QS5509A

**Comment by WMCB-Tech** [comment]
Seems https://main.termux-mirror.ml/ is down, change it with `termux-change-repo`

**Comment by Post-Man91** [comment]
Where exactly is the list of repos that are up or do u know of one?

**Comment by Post-Man91** [comment]
It updated fine when i used pkg instead of apt which is the real reawon i posted this im wonderimg if theres an issue with apt on termux? Or do they pull from different sources?

**Comment by WMCB-Tech** [comment]
Termux recently switched to ipfs and some repos have been changed sources, see https://github.com/termux/termux-packages/issues/6348 for more information

**Comment by Post-Man91** [comment]
Gotya thanks man

**Comment by Post-Man91** [comment]
Actually im still a bit confused do you mean that apt pulls from ipfs and pkg doesnt
When i run apt update i get the error but pkg update gives no error and works as expected so is that do to each using something different to pull from repos?

**Comment by Grimler91** [comment]
`pkg` is a wrapper around `apt`. `pkg` checks so current mirror works before trying to update. the termux-mirror.ml mirror was dropped [a month ago](https://github.com/termux/termux-packages/commit/b373b3dfff980d5103f8b5122c0b81b0d9faae20#diff-926df3194e5f727be3fefbac2278032a4b2331fa147ddb70c3898602a23765a4), so other mirrors need to be used.
