### ISSUE TITLE
Ruby gems not getting installed 

### ISSUE THREAD

**Issue by surya-bug** [termux/termux-app#1962]
**Problem description**

When I try to install a ruby gem with gem install <gem name> , the prompt hangs for 5-10 mins then I get an error stating **  Setting up tsu (8.5.1-3) ...
$ tsu
# gem install pry packet-fu **

I'm attaching the screenshot 

![Screenshot_20210311-232024.png](https://user-images.githubusercontent.com/77871514/110831570-608b3680-82c0-11eb-8b9d-8dc9a494e75a.png)

**Steps to reproduce**

gem install gem-name

**Expected behavior**

Successfully installed gem-name

**Additional information**

* Termux application version: 0.101
* Android OS version: 10
* Device model: Redmi note 5 pro(Whyred)

**Comment by Grimler91** [comment]
Why are you installing as root? There is no need for it and trying to do so messes up file and folder permissions in $PREFIX. 

Do not use (t)su for anything unless you are sure you need it. You might need to reinstall termux now (or `chown` and `restorecon` files back to the correct user).

**Comment by Grimler91** [comment]
Other guess is that you have some network issues (based on the `Unable to download data https://rubygems.org/` message). Can you access that url in a browser?

**Comment by surya-bug** [comment]
As suggested , I did a re install .. then too the same problem persists..the net connection is working fine

Attaching a screenshot for your reference.

![Screenshot_20210312-075344.png](https://user-images.githubusercontent.com/77871514/110882599-3c534800-8308-11eb-97cf-8190bb5704bd.png)

**Comment by agnostic-apollo** [comment]
You were still using `tsu` after [reinstall](https://matrix.to/#/!ttKPgmaucSQTHmGurC:gitter.im/$cvbGPMw_RnkH6N78yiDcghsNNPraKf0kgkOTAlA7anc?via=matrix.org&via=gitter.im&via=privacytools.io)

```
` Setting up tsu (8.5.1-3) ...
$ tsu
# gem install pry packet-fu `
```

Uninstall termux, **DO NOT** run `tsu`, and only install the gems. Never install gems with a root shell unless you have a specific use case.

And as for timeout, visit rubygems.org/specs.4.8.gz and see if you can download the file.

Otherwise, post a log of `gem install --debug sinatra`. I'm pretty sure you are messing something on your end, since gem installed on my device.

**Comment by surya-bug** [comment]
@agnostic-apollo I'm not using tsu in my previous screenshot ... 

![Screenshot_20210312-075344.png](https://user-images.githubusercontent.com/77871514/110884786-a7524e00-830b-11eb-9943-f2ff9c58a120.png)

**Comment by surya-bug** [comment]
gem install sinatra --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `Net::OpenTimeout' at /data/data/com.termux/files/usr/lib/ruby/3.0.0/net/http.rb:987 - execution expired
Exception `Net::OpenTimeout' at /data/data/com.termux/files/usr/lib/ruby/3.0.0/net/http.rb:989 - execution expired
Exception `Net::OpenTimeout' at /data/data/com.termux/files/usr/lib/ruby/3.0.0/timeout.rb:118 - execution expired
Exception `Net::OpenTimeout' at /data/data/com.termux/files/usr/lib/ruby/3.0.0/net/http.rb:1054 - execution expired
Exception `Gem::RemoteFetcher::UnknownHostError' at /data/data/com.termux/files/usr/lib/ruby/3.0.0/rubygems/remote_fetcher.rb:263 - timed out (https://index.rubygems.org/)

**Comment by agnostic-apollo** [comment]
Even if you had run `gem install` once with a root shell, you would have messed up the file ownership. Running it again like in your last screenshot wouldn't ignore previous damage. Either reinstall termux or fix ownership manually.

And like I said, check the url. Or try with a VPN.

**Comment by agnostic-apollo** [comment]
That seems to be a connectivity issue. Others have reported issues too like [here](https://stackoverflow.com/questions/49800432/gem-cannot-access-rubygems-org). It could also be a [IPv6 issue](https://help.rubygems.org/discussions/problems/37907-unable-to-download-data-from-httpsrubygemsorg-timed-out#comment_48254922), try changing your internet connection, disabling IPv6, DNS in WiFi settings, or use a VPN. Basically not a termux issue.

**Comment by surya-bug** [comment]
It's working when connecting to WiFi but not on my mobile network. Not a termux issue .
