### ISSUE TITLE
Can't install Termux 0.108 on Android 10

### ISSUE THREAD

**Issue by tfkhdyt** [termux/termux-app#1963]
**Problem description**
I wanted to move from the play store version to the f-droid version, but it turned out that it got an error when I was going to install the application. I've already uninstalled the play store version

**Steps to reproduce**
1. Download from f-droid
2. Install
3. Installation failed

**Expected behavior**
The application should be installed like normal

**Additional information**

* Termux application version: 0.108
* Android OS version: 10
* Device model: realme 3 Pro

![Screenshot_2021-03-12-04-47-24-66_66a3b1c2c181ff92b8bf945e748b6fb7](https://user-images.githubusercontent.com/47195537/110860102-42b7d480-82b4-11eb-9e7f-146a712900d0.jpg)

**Comment by agnostic-apollo** [comment]
>failed to install due to an unknown error

Uninstall ALL termux plugins that you installed from Playstore as well before installing F-Droid builds.

**Comment by tfkhdyt** [comment]
Damn you're right, I haven't uninstalled termux:API yet 😅
I thought it doesn't matter if i haven't uninstalled any plugin
Thank you so much

**Comment by agnostic-apollo** [comment]
Welcome
