### ISSUE TITLE
Unsuccessful replacement of termux system with ArchLinux system.

### ISSUE THREAD

**Issue by Maxython** [termux/termux-app#1966]
### Hi everyone. 
I decided to change the termux system to the arch linux system.  But when I did everything, an error pops up:
```
exec("/data/data/com.termux/files/usr/bin/login"): No such file or directory

[Process completed (code 1) - press Enter]
```
But the file does exist.
![Screenshot_20210316-003105_Files](https://user-images.githubusercontent.com/60917834/111223999-effd5600-85ee-11eb-9bcd-b164cecba250.jpg)

## The theory of how to change the system.
There is only one system folder in termux and that is **usr**.  According to theory, if change this folder (such a but on the basis of another system), then can probably change the system. Based on the new system, I took Arch Linux ([TermuxArch](https://github.com/SDRausty/TermuxArch) ). And after changing **usr** and adding other system folders from arch, termux doesn't work for me.  
  
### After that, I had questions:
1. Is it possible to change the termux system and if so how?
2. What is the problem with this error and how can I fix it?

**Comment by xeffyr** [comment]
The only thing you are missing is that `proot` is still required. You can't just replace the `usr` directory. Termux **is different** from Linux distributions: https://wiki.termux.com/wiki/Differences_from_Linux.

You will have better luck with writing a custom login script and replacing one in `$PREFIX/bin`, so it will start a proot'ed Arch Linux session automatically. But don't touch anything else if you are not able to figure out dependency chain.

**Comment by Maxython** [comment]
What do you mean by writing a custom login script?  It's just that there is little information on the Internet about it.

**Comment by xeffyr** [comment]
`$PREFIX/bin/login`

Please note that I won't write it for you. Learn Bash scripting and do it on your own.

**Comment by Maxython** [comment]
After some experimentation, I got a similar error, but because of **lib**.
```
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/sh": "/data/data/com.termux/files/usr/lib/libc.so" has bad ELF magic: 2f2a2047

[Process completed (code 1) - press Enter]
```
From this we can conclude that it is better not to change folders, but to add content from the folder.

**Comment by ravener** [comment]
That sounds like a really bad and risky idea you are doing. Why don't you just stick to normal proot. Have some startup script to automatically log you in when you open termux or something

**Comment by xeffyr** [comment]
@Maxython Again, read the https://wiki.termux.com/wiki/Differences_from_Linux. And https://wiki.termux.com/wiki/Getting_started - especially section "How does it work".

Termux is not a Linux distribution and is not a chroot environment. Just putting Arch Linux files into /usr will not work. You need to use proot just like TermuxArch scripts do.

All Termux packages are patched and built with specific configuration, that's why them work. As Arch Linux packages are neither patched for Termux nor have appropriate build-time configuration such as prefix path, they will not work.

**Comment by Maxython** [comment]
Ok, I got it.

**Comment by Maxython** [comment]
In short, I made arch linux auto-start.  Who wants to do the same, here are all the commands.  
## Mandatory commands and actions.
- `pkg update -y`
- `apt-get install git wget proot`
- Add the storage directory to **arch** using the `termux-setup-storage` command.
## Access to com.termux (optional).
The **arch** folder should be located at `/data/data/com.termux`.
```bash
mv arch /data/data/com.termux #Folder transfer
rm -fr home #Removing home directory
ln -s /data/data/com.termux home #Create a home directory that points to /data/data/com.termux
```
## Adding Arch Linux autorun.
To get Arch Linux to start automatically, need to add a startup command in file `/usr/etc/bash.bashrc`.
**Command to add:**
```bash
echo 'startarch' >> /data/data/com.termux/files/usr/etc/bash.bashrc
```
## Blocking the exit command on Arch Linux (optional).
In the `arch/etc/bash.bashrc` file need to add command.
**Commands:**
```bash
enable -n exit #Blocking the exit command
enable -n enable #Blocking the enable command so as not to unblock exit
```
or
```bash
alias exit='text ._.'
```
___
After these steps, restart Termux and Arch Linux will boot up immediately)

**Comment by WMCB-Tech** [comment]
@Maxython why not `exec` it in `.bashrc` or `.profile` instead as a safest alternative

**Comment by Maxython** [comment]
@WMCB-Tech can you write where else commands are executed when Arch starts? I just try to start Arch with a specific user, and he endlessly asks for a password (if the password fails, the cycle ends). As far as I understand, some commands are executed on root, and because of the user change, the system asks for a password.

**Comment by WMCB-Tech** [comment]
If it asks you endlessly for password, ensure you have password set for your desired user account with `passwd` command

**Comment by Maxython** [comment]
> Although i never get into this scenario bf, usually when logging in `startarch u user`, it shouldn't ask you for a password

My user changed in bashrc, because of this he asked for a password.  And thanks for solving the problems)
