### ISSUE TITLE
populate TZ environment variable for all sessions from system's timezone

### ISSUE THREAD

**Issue by ilyapashuk** [termux/termux-app#1968]
please perform on session startup some analog of this:
export TZ="$(getprop persist.sys.timezone)

with this it will be much more simple to many apps to detect system timezone

**Comment by alou-S** [comment]
This is not really required since most apps get the timezone from time date daemon when the TZ environment variable not

Most Linux OS'es don't even set this variable in the environment by default.
If needed you could simply initialize it ever shell session by adding it to the .rc file.

**Comment by xeffyr** [comment]
TZ environment has been already discussed here (or possibly in termux-packages).

It is required by very few packages only (emacs and maybe something else). For the rest it just overrides current Android time zone.
