### ISSUE TITLE
cd: Permission denied: Can't read the Internal storage

### ISSUE THREAD

**Issue by forliuyifei** [termux/termux-app#1971]
![Screenshot_20210319-073528_Termux](https://user-images.githubusercontent.com/53306807/111710966-babe6580-8885-11eb-8ba2-f75302238ba6.png)

**Comment by forliuyifei** [comment]
I have given all the permissions required by termux

**Comment by agnostic-apollo** [comment]
Disable permission and re-grant it.

**Comment by forliuyifei** [comment]
> Disable storage permission and re-grant it.

Great, it works now.
