### ISSUE TITLE
TERMUX_VERSION is not in env

### ISSUE THREAD

**Issue by mitnk** [termux/termux-app#1972]
In release note of 107, there is

> Export current application version as environment variable TERMUX_VERSION.

How this env loaded? I upgraded to 108, but does not have this env:
```
$ env | grep -i TERM
SHELL=/data/data/com.termux/files/usr/bin/bash
PREFIX=/data/data/com.termux/files/usr
PWD=/data/data/com.termux/files/home
LOGDIR=/data/data/com.termux/files/usr/var/log
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
HOME=/data/data/com.termux/files/home
SVDIR=/data/data/com.termux/files/usr/var/service
TMPDIR=/data/data/com.termux/files/usr/tmp
TERM=xterm-256color
GOPATH=/data/data/com.termux/files/home/go
_=/data/data/com.termux/files/usr/bin/env

```

**Comment by mitnk** [comment]
How could I check its current version? `termux-info` do not report its version. It says the version of this app is 0.108 in app's info page of the OS.

**Comment by agnostic-apollo** [comment]
>It shows "0.108" in app's info-page from the OS.

This is what I meant. Are you using F-Droid builds?

There might be a possibility that [BuildConfig.VERSION_NAME](https://github.com/termux/termux-app/commit/e03858f0659c108f12d44b5c162586a66d351765) is returning `null`. Shouldn't happen though, correct version is showing on debug builds and as reported by [others](https://www.reddit.com/r/termux/comments/m39w5v/termuxinfo_not_showing_termux_version/). Using `PackageManager` might be better to get version.

However, your environment seems to be modified than the default. Don't even see `PATH`. That is likely the reason.

**Comment by mitnk** [comment]
> Are you using F-Droid builds?

This IS the issue: I downloaded latest F-Droid app from f-droid.org, and then using F-Droid app to updated termux to latest version. It did show the 0.108 version as I mentioned above.

I just downloaded the `com.termux_108.apk` from f-droid.org website, and installed it. Then the `TERMUX_VERSION` shows up. So I guess there must be issues in the F-Droid.app. (This is the second time bit by this app :(, will never try it again)

> Don't even see PATH

I deleted the PATH, it's very long in my case, and not related.

----

However, there is another issue: the `TERMUX_VERSION` does not show up in the env list when ssh to termux (with sshd running).

**Comment by agnostic-apollo** [comment]
F-Droid APKs provided via site and app should be the same, specially considering app one showed correct version. I checked with installing Termux from F-Droid app and it showed `TERMUX_VERSION`.


>However, there is another issue: the TERMUX_VERSION does not show up in the env list when ssh to termux (with sshd running).

The variable is exported while launching a terminal session through the app as linked above. It's not exported by any of the shell profile/rc files, so it wouldn't be available with `sshd`. Maybe an `env` variables file can be saved by Termux app in `$PREFIX/etc/` that can be sourced by profile/rc files. Check termux/termux-packages#1644

The important variables will likely even need an exception for ssh as per [this](https://github.com/termux/termux-packages/pull/2345/commits/13900eb9b652df40bc984e96a10eed9a5608f848). Not sure what the ideal solution is here, other maintainers can give better recommendations.

**Comment by mitnk** [comment]
> F-Droid APKs provided via site and app should be the same

Ah, maybe I was checking with ssh only, not pretty sure about that now..

Thanks for your explanation.

**Comment by RalfWerner** [comment]
@mitnk Alternatively, the _Termux version_ can also be _determines_ with`aapt d badging $a|head -n 4`
which also usable with _older_`*.apk`. To do this, you need the package/var:`pkg in aapt;  l=../../lib` or
`t=com.termux;  l=/data/data/$t/lib` and `a=$l/../../base.apk`. For _very old_ versions, possibly
`a=$(pm path $t|grep base|cut -d: -f2)`. Advantage: You also get the other build information from Termux.

**Comment by agnostic-apollo** [comment]
> > F-Droid APKs provided via site and app should be the same
> 
> Ah, maybe I was checking with ssh only, not pretty sure about that now..
> 
> Thanks for your explanation.

Yeah, that might be it. You are welcome.

**Comment by xeffyr** [comment]
Package `openssh` is going to be fixed, i.e. not remove `TERMUX_VERSION` during login anymore. Additionally `termux-info` script will be updated to show app version (for obvious reasons minumum is v0.107 app to have it shown).
