### ISSUE TITLE
wtf happened?

### ISSUE THREAD

**Issue by annihat** [termux/termux-app#1973]
**Problem description**

I upgraded my phone from an Android **5** model & Termux got **three hundred times larger** in one step!?!
The current version is **over four hundred times larger!?!**

**Steps to reproduce**

'upgrade' from v0.75 to v0.76 or higher 

**Expected behavior**

Termux to remain as a couple of hundred Kilobytes (& trending slightly smaller as had been happening for the previous few years). 

An explanation & apology in F-Droid's listing, the Readme & the Changelog appears to me as imperative. 

**Additional information**
https://github.com/termux/termux-app/compare/v0.75...v0.76 

* Termux application version: v0.76 or higher 
* Android OS version: over 5 
* Device model: any

**Comment by agnostic-apollo** [comment]
We are currently on Termux version `0.108`. And android version < 7 is not supported anymore.

**Comment by annihat** [comment]
> We are currently on Termux version `0.108`. And android version < 7 is not supported anymore.

what, exactly, is that meant to mean? It doesn't even approach the question raised

**Comment by agnostic-apollo** [comment]
Termux APKs come with [bootstrap zips](https://github.com/termux/termux-packages/releases) containing binaries of all architectures that provide a minimal shell environment to the user. So current APK size is ~80MB. Termux App source code itself is pretty small.

Check termux/termux-app#1301 which was added for the [`0.76` release](https://github.com/termux/termux-app/releases/tag/v0.76).

**Comment by annihat** [comment]
I'm confused now but the gist I'm getting is that Termux was always >20 MB & the .apk in the appstore was just a downloader? The majority of the app was downloaded whenever the app was run? installed? upgraded? but now it's included in the .apk along with redundant versions? 

I would still very much like to see this clarified in the Readme & Changelog

**Comment by WMCB-Tech** [comment]
Google Play Builds split apks per Architecture which builds in play store is over ~20mb, which it only includes one bootstrap archive inside the apk, 

Whilst the F-Droid builds includes all architecture-bootstrap archives inside the apk which is over ~80mb,

**Comment by annihat** [comment]
> Google Play Builds split apks per Architecture which builds in play store is over ~20mb, which it only includes one bootstrap archive inside the apk,
> 
> Whilst the F-Droid builds includes all architecture-bootstrap archives inside the apk which is over ~80mb,
> 
> of course, F-Droid doesn't support split-apks yet afaik so it's bloated

F-Droid does seem to support multiple builds on the same version number, each with a different architecture - a different solution to the same problem.

**Comment by agnostic-apollo** [comment]
The app store version previously was not just a downloader. It was the android app itself, majorly the terminal view. But underneath, the terminal needs to run commands, whose binaries are stored in `$PREFIX/bin`, like the `bash` shell and some others, etc. Those were previously downloaded after APK installation, now they come with the APK. The `bash` is the default Termux shell and hence part of bootstrap. All other binaries/packages provided by Termux that are not part of bootstrap can optionally be installed by users manually with `apt` and `pkg` if they want. The bootstrap basically contains the important command binaries including `bash`, needed to run a basic shell environment. Download the bootstrap zip release and see what's inside.

**Comment by annihat** [comment]
Thank you, that does clarify what's going on & the links you provided earlier state the reason behind it. 

Much appreciated, thank you. 

I hope you see why I was alarmed though? An app that I wanted to come back to suddenly being 400 times larger without any apparent explanation. It's also 200 times larger than the well-known _jackpal_ terminal & the package management system + basic utilities are the only obvious difference which, without research, doesn't  seem to add up to 80MB.

**Comment by agnostic-apollo** [comment]
You are welcome.
