### ISSUE TITLE
Use Termux with ADB permissions/Use Termux tools inside ADB

### ISSUE THREAD

**Issue by ustcpetergu** [termux/termux-app#1974]
Termux is a wonderful tool, but by default its permission is a normal app's permission if without root. 

ADB uses the default crappy Android shell, but it has slightly higher permission -- making it a must in some scenarios, for example, starting Shizuku(iirc), and `getevent`. 

My question would be, whether could I use Termux tools with ADB's permission? For example, I want to use `stdbuf -o0` from `coreutils` on the output of `getevent` to avoid buffering. 

I know I could install ADB executables for ARM, run them in Termux, and "debug the phone itself" via ADB over network, but inside that ADB, when permission is slightly higher, I loss access to Termux tools again. 

I also imagined copying Termux to somewhere ADB can access and allow executables(so certainly not SD card) then use them in ADB, but limited by my knowledge I couldn't do that. 

Any help is appreciated.

**Comment by xeffyr** [comment]
There are 2 variants to do so:
1. Get a development (debug) build of Termux from either Github Actions artifacts or compile it manually. After installation run with ADB `run-as com.termux` to get into Termux application environment. But this will drop privileges from `shell` user to Termux app.
2. Run a root shell if your ROM allows that.
   ```
   adb root
   adb shell
   ```
No other variants possible.

**Comment by ustcpetergu** [comment]
Thanks for your reply. I got it.
