### ISSUE TITLE
[Solved]Can't install in Android 10

### ISSUE THREAD

**Issue by NeilTohno** [termux/termux-app#1976]
**Problem description**
Hi, I can't termux install in Android 10, I found this problem in January,.

**Additional information**

* Termux application version: v0.108
* Android OS version: Android 10
* Device model: xiaomi MI8

**Turn on Developer Options, and turn off MIUI optimization.**

**Comment by agnostic-apollo** [comment]
No info on any error you get...

Uninstall ALL termux and its plugin apps installed from playstore before installing termux from F-Droid. You can't mix them because of different APK signatures.

**Comment by NeilTohno** [comment]
> No info on any error you get...
There was a problem parsing the package APK.

> Uninstall ALL termux and its plugin apps installed from playstore before installing termux from F-Droid. You can't mix them because of different APK signatures.
 I know it.

**Comment by agnostic-apollo** [comment]
Redownload the APK from F-Droid and also search "termux" in your apps list in Android Settings.

**Comment by SDRausty** [comment]
> Can't install in Android 10

Termux works like a charm on mine.

Termux fonctionne comme un charme sur le mien.

**Comment by NeilTohno** [comment]
> Redownload the APK from F-Droid and also search "termux" in your apps list in Android Settings.

I have tried three times, but failed, the v 0.101 work perfct.
I also can't install  F-Droid APP.

**Comment by agnostic-apollo** [comment]
It's likely missing permissions, check update to my previous comment. And I'm assuming you are uninstalling said perfect v0.101 before installing new APK.

**Comment by xeffyr** [comment]
@NeilTohno Before installing v0.108, **uninstall** (yes, open Android settings --> applications and uninstall):
* Termux
* Termux:API
* Termux:Boot
* Termux:Widget
* Termux:Float
* Termux:Styling
* Termux:Tasker

**Comment by SDRausty** [comment]
Thank you for confirmation @NeilTohno
