### ISSUE TITLE
Close virtual keyboard by terminal-setting

### ISSUE THREAD

**Issue by heeplr** [termux/termux-app#1978]
**Feature description**

When opening a termux session, the virtual keyboard is shown by default. That's counterproductive when using TUI applications (i.e. mouse emulation) and shortcuts, since the keyboard uses a lot of screen estate/the keyboard has to be closed manually everytime.

It would be nice, if there'd be a way to optionally keep the keyboard closed by default.

**Comment by agnostic-apollo** [comment]
Seems reasonable, will add.

**Comment by freebrowser1** [comment]
I agree, would be very useful.
