### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by inderjeet68g** [termux/termux-app#1979]
This app is not installing in mi mi note 8 pro![Screenshot_2021-03-25-21-27-19-093_com.google.android.packageinstaller.jpg](https://user-images.githubusercontent.com/76393788/112503678-24240400-8db1-11eb-88ee-5be4287de431.jpg)

**Comment by xeffyr** [comment]
Before installing Termux from F-Droid, or if you don't know the source from where apk was downloaded, first **uninstall** (yes, open Android settings --> applications and uninstall) the application and plugins:
* Termux
* Termux:API
* Termux:Boot
* Termux:Widget
* Termux:Float
* Termux:Styling
* Termux:Tasker

If you think you have not plugins installed, strongly suggesting to go through application list in Android settings and double check.
