### ISSUE TITLE
The started server continues to work after the session is closed

### ISSUE THREAD

**Issue by brookite** [termux/termux-app#1988]
In this case, the problem does not appear if the server is closed during a session. It will appear if you abruptly close the session without stopping the process with the server

I am running HTTP server on Python. Forgetting to shut down the server in a normal way, I habitually close the session
After a while, I notice that the battery charge decreases faster. The battery consumption statistics show that Termux is draining the Android device's battery. To solve this problem, Termux needs to be forcedly closed in the system settings, then this helps

Is it possible to fix this?

Device: Redmi Note 7
OS: MIUI 12 (Android 10) aarch64
Kernel version: 4.4.192
Termux version: 0.108

**Comment by Grimler91** [comment]
What does "abruptly close the session" mean? 

So your issue is that the server is running in the background? To stop it you can kill it with `kill` or `pkill`. `pstree -p` will show you running processes, and their PIDs, and you can then do `kill $PID`, or if you know the name of the process (for example `python`) you can do `pkill python`. 

This is intended behavior, so not something that will be changed.

**Comment by Grimler91** [comment]
If you want to be sure it does not run in the background then consider running it in the foreground

**Comment by agnostic-apollo** [comment]
When the Termux sessions are closed, like from the `Exit` button in Termux notification, the [TermuxService](https://github.com/termux/termux-app/blob/v0.108/app/src/main/java/com/termux/app/TermuxService.java#L274) sends a [SIGKILL](https://github.com/termux/termux-app/blob/v0.108/terminal-emulator/src/main/java/com/termux/terminal/TerminalSession.java#L286) to all the running sessions. However, if your server process was run in the background like with `command &`, then it will not receive the signal and will continue running, until at least android OOM decides to kill the Termux app process to free memory. Basically, do what Grimler says, run it in foreground in a separate session.

You can check if the server is still running after restarting termux by running `ps -ef` (not `ps` alone) or `pgrep -fa python`.

**Comment by agnostic-apollo** [comment]
This behaviour is different from linux distros where `SIGHUP` is sent when a session exits, and processes started with only `&` will be killed, unless `nohup` is used.

In case of termux, [`android.system.Os kill()`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:libcore/luni/src/main/java/android/system/Os.java;l=332) is called to send `SIGKILL` only to the shell process via [`kill`](https://man7.org/linux/man-pages/man2/kill.2.html) system call, which wouldn't kill the children. If children had to be killed, then something like the following would have to be implemented, there may be a java way...

```
killtree() {
    local signal="$1"; local pid="$2"; local cpid
    for cpid in $(pgrep -P "$pid"); do killtree "$signal" "$cpid"; done
    [[ "$pid" != "$$" ]] && signal="${signal:=15}"; kill "-$signal" "$pid" 2>/dev/null
}
```

**Comment by brookite** [comment]
Roughly understood your comments on my problem.  But it is not entirely clear what "in the foreground" means.
 I will briefly describe my problem again.  I created a Python http server and created a bash script to run it.  Every time I start the server with the "bash server.sh" command.  Then, when I need to close the server and Termux, I, out of habit, click the Close button in Android notifications, and do not end the process with the server.
 And after that, the server continues to work and consume the device's battery.

**Comment by agnostic-apollo** [comment]
> But it is not entirely clear what "in the foreground" means.

"Basically", it means when you run the `bash server.sh` command, the command doesn't immediately exit and keeps on running and likely shows the output of the server logs until you press Ctrl+C or something. Background/daemon mode would mean the command exits immediately and allows you to run more commands in the same session, but the server stays running in the background.

https://www.digitalocean.com/community/tutorials/how-to-use-bash-s-job-control-to-manage-foreground-and-background-processes

> I created a Python http server and created a bash script to run it.

Without knowing what your python code is to create a HTTP server or what commands you are running in the `bash` script, it would probably be hard to give the right advice. But whatever framework/library you are using would probably have some daemon mode option, you need to **disable** that.

>click the Close button in Android notifications

You mean `Exit` button, right?

**Comment by brookite** [comment]
Yes, Exit button, sorry.  Here is a fragment of my Python code.  My server starts on an additional thread.  I think thread.setDaemon (True) is related to this problem.

```
def server():

global httpd

socketserver.TCPServer.allow_reuse_address = True

httpd = socketserver.TCPServer(("", PORT), MyHttpRequestHandler)

print("Http Server Serving at port", PORT)

httpd.serve_forever()

thread = Thread(target=server)

thread.setDaemon(True)

thread.start()

```

**Comment by agnostic-apollo** [comment]
Yeah, that's probably it according to python docs

https://docs.python.org/3/library/threading.html#threading.Thread.daemon

>The entire Python program exits when no alive non-daemon threads are left.

Setting it to `true` will make the python program exit without waiting for the daemon thread to complete. So remove that line, and test with `ps -ef` after reopening termux after `Exit`.

**Comment by brookite** [comment]
Thanks for the advice.  I will definitely try to do it

**Comment by agnostic-apollo** [comment]
welcome.

**Comment by brookite** [comment]
I tried removing the 'thread.setDaemon (True)' line, but that didn't change the situation. The thing is, my server runs on a additional (not main) thread. My guess is that when Exit is pressed while my Python script is running, the main thread ends, but somehow this additional thread continues to work with the server. Is this possible? I apologize for the possibly incorrect question, but, unfortunately, I do not have a lot of knowledge in Unix architecture.

**Comment by brookite** [comment]
![IMG_20210403_221939.jpg](https://user-images.githubusercontent.com/57016414/113487723-b8d1e480-94ca-11eb-87f8-79cc103abafa.jpg)
Processes with PIDs 6261 and 6298 are associated with my script
These commands are called after closing Termux with the server running (Exit button)
