### ISSUE TITLE
metasploit-framework

### ISSUE THREAD

**Issue by Ammu09A** [termux/termux-app#1989]
#1940 #1435 #1188 #1870 
![Screenshot_2021-04-03-00-56-34-02_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/81829153/113448664-e3179980-9419-11eb-8cad-ff08bc68139c.jpg)

**Comment by Ammu09A** [comment]
If anyone know the solution.
and also a good knowledge of cyber security.
Please contact me at: aman9760528609@gmail.com

**Comment by agnostic-apollo** [comment]
Metasploit has been removed from termux repos.

https://github.com/termux/unstable-packages/commit/a0bbde10d152190783c07e1719a4bc6a5ebf2109
