### ISSUE TITLE
Login to use Termux (optional) 

### ISSUE THREAD

**Issue by mlanner** [termux/termux-app#199]
I would like to have some secondary login/auth, other than unlocking my device, to open and access Termux. For example, to launch and get into Termux, require a PIN code, password, or if the device has a fingerprint reader, unlock Termux that way. It would be a great feature. This functionality could be optional and configurable, as I realize some users may not want it.

**Comment by tinydynamite00** [comment]
+1 I'd like to see a "lockdown" option implemented as well. Outside of either a <code>proot</code> or systemless root scenario the integration (or a variation) of <code>passwd</code> together with its PAM-modules might be seen as merely symbolic. On the other hand, Termux provides nearly limitless capabilities; an excellent learning environment for nascent and seasoned users of the CLI. It stands to reason that one of the most fundamental parts of a Linux, e.g. its security suite (optional) would be included.

**Comment by qntmpkts** [comment]
This is a feature that should be handled via a supported package such as [vlock](https://packages.debian.org/wheezy/utils/vlock).

**Comment by martmists** [comment]
I would like to also see an option to use fingerprint, if available.

**Comment by TheDiamondYT1** [comment]
@martmists Although i dont own an Android with a fingerprint scanner (iPhone 6s // Galaxy S4 mini) i still agree that this would be a nice feature.

**Comment by xeffyr** [comment]
I have wrote basic 'passwd' and 'login' commands for Termux. Sources [here](https://github.com/xeffyr/termux-rootfs/tree/master/pkg-sources/login_passwd).

**Comment by s33wagz** [comment]
what's going on with this?

**Comment by xeffyr** [comment]
Closing as will seriously interfere with failsafe shell functionality which require free access to environment bypassing all scripts/configs/etc...
