### ISSUE TITLE
Enter does not work with input method KDE Connect

### ISSUE THREAD

**Issue by pacazo** [termux/termux-app#1998]
LG Velvet L-52A 5G, Android 10.
OpenSuse GNU/Linux 15.2 with KDE desktop

**Problem description**

When using the "KDE Connect remote control input", the key `<Enter>` does not work on termux. It does work on other apps (For example, I can type text on text apps and pressing `<Enter>` for new line does start a new line)

**Steps to reproduce**

Install termux and KDE connect. Link the phone with the computer. Enable KDE connect input method on the phone. Type normally on the computer keyboard. The commands appear as typed on the phone, but `<ENTER>` does not work.

**Expected behavior**

Pressing `ls<Enter>` on the computer should list the files, but nothing happens after typing `ls`.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://main.termux-mirror.ml/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.19.81-perf termux/termux-packages#1 SMP PREEMPT Fri Mar 12 19:01:15 KST 2021 aarch64 Android
Device manufacturer:
LGE
Device model:
L-52A
```

**Comment by agnostic-apollo** [comment]
Use [Ctrl+j](https://www.reddit.com/r/kde/comments/ha4h2d/kde_connect_remote_keyboard_enter_key/?utm_medium=android_app&utm_source=share). Also check [this](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/892#issuecomment-656979729). This isn't directly a Termux issue.
