### ISSUE TITLE
Cannot write to external SD card

### ISSUE THREAD

**Issue by Yajo** [termux/termux-app#20]
```
$ touch /storage/extSdCard/test
touch: /storage/extSdCard/test: Permission denied
```

I guess this comes from Android 5's new permissions for SD cards. Any way to fix it?

**Comment by fornwall** [comment]
Unless you have root you can't write to all locations on external SD cards. You should however be able to write to the folder Android/data/com.termux/ on it (which is the Android 5 permission model as you say)!

**Comment by Yajo** [comment]
but then how do file managers write there?

**Comment by cswl** [comment]
File managers hack on the Storage Access Framework.  Thats why they ask you first to choose the root folder of your external sdcard.

**Comment by Yajo** [comment]
I found that [one of the Android developer spoke about the possibility for apps to write to SD card folders](https://groups.google.com/forum/#!topic/android-platform/14VUiIgwUjY[201-225]). It's a feature introduced in Android 5 after the issues about that raised from the community. I use OfficeSuite, which uses this method, and after selecting the folder for the first time you get full write access.

IMHO this is a very important feature for Termux because having a powerful terminal is only half-powerful unless you have a good editor for it, and any other app will have the same problem, but I'm opening an issue in TurboEditor too.

Could you please reopen this?

**Comment by Craeckie** [comment]
+1 feature would be very useful!

**Comment by fornwall** [comment]
See [Internal and external storage](https://termux.com/storage.html) - it's possible to at least create a folder on the external SD card now (`$HOME/storage/external`) where Termux can write.

**Comment by Yajo** [comment]
I have no Android 6 so I cannot try, but is it possible to share that folder with another apps, like a text editor?

**Comment by terba** [comment]
Currently I'm moving my music collection using termux's sshd to the internal storage and then I'm moving that to the external SD card with Amaze file manager on the decice. I have to do that in 5 parts on my super shiny new Android phone. And I even can not use rsync to update the collection later. And no mass storage mode on this fantastic phone. MTP simply can not handle that amount of data. And we are in 2016.

It's a shame that I was not able to repair my last Nokia N900... By the way thanks for Termux, without it I would only have landline phone in the future.

**Comment by Neo-Oli** [comment]
@terba all my Music lives in ~/storage/external/ (`termux-setup-storage`) which is a directory on the sdcard in /storage/[sdcard_name]/Android/data/com.termux/files. Music managers do have access to this directory, so I just use it like that. But if you want you can move it with Amaze to the external sd-card root. This way you can do it in one part, because it writes directly to the sd.

**Comment by terba** [comment]
I had this idea also, to use termux's external folder for music library, and even tried it, but Vanilla Music was not able to see the files. Maybe I missed something? I try it again. Thanks!

**Comment by Neo-Oli** [comment]
I am using Poweramp, which seems to work. But I have seen other apps completely ignore the Android folder, even if explicitly set. I still haven't found a Gallery app that let's me choose the termux folder.

**Comment by terba** [comment]
Media library scanning doesn't recognizes termux's external folder, but a simple folder based player works. Thanks!

**Comment by willsALMANJ** [comment]
@terba I had the same problem with the default Android music player not showing files that I had transferred to the SD card with rsync. I found that using another app to force rescan the SD card allowed the music files to show up in the music player.

**Comment by terba** [comment]
@Neo-Oli and @willsALMANJ: On my device a .nomedia file gets created at boot time in the external SD cards "Android" folder. That is what prevents media indexing my ...com.termux/files/home/storage/external folder. If I remove that .nomedia file with a file manager and trigger a reindex after each boot, my files show up until the next reboot. But it is useless for me anyway, because Android media indexer can not deal with UTF8 in tags... And this OS is used by the whole world... The solution is to forget the Android's built-in media library, and use a music player with it's own media library as Neo-Oli suggested above.

**Comment by CaptainPackers** [comment]
On my Asus ZenPad 10.1 (P023) running Android 5.0.2, I do not see a com.termux folder at /storage/MicroSD/Android/data, so I don't even have the option of writing there. Anyone have any experience with this. I would like to use termux to write to my sd card.
Thanks

**Comment by Cypher1** [comment]
Can this be reopened. I would like to be able to use my terminal to edit and run files that I already have, I guess I could move everything into termux's data folder but that seems messy and unnecessary.

**Comment by geek1011** [comment]
Finally figured it out for rooted devices running marshmallow or greater!

````
su
pm grant com.termux android.permission.READ_EXTERNAL_STORAGE
pm grant com.termux android.permission.WRITE_EXTERNAL_STORAGE
````

**Comment by HJarausch** [comment]
For me, it doesn't work after I leave root with 'exit'.

**Comment by insign** [comment]
@geek1011 worked like a charm!

**Comment by geek1011** [comment]
And without root, you can just run that in adb shell without the su command.

**Comment by rogerxxxx** [comment]
I tried the prior mentioned "pm" read/write permission within an adb shell, and I still do not have write access on the external storage device.  I do not have a rooted device, but  geek1011 stated should work.  However, most other adb functions work.

I have a Samsung Galaxy S3 Tab.  Maybe the adb shell is limited to certain Android versions or devices?  Most adb functions do appear to work, but this Samsung device's adb functions seems to have restricted push/pull operations.

**Comment by Quasic** [comment]
I wish the SD card supported symlinks, too, or that Android wasn't blocking access to all but that one deep folder, but so far, I haven't seen a better solution. I have seen some problems solved that I thought were harder, though...

**Comment by geek1011** [comment]
@Quasic I'm not sure if this will work, but have you tried making a disk image file on the SD card, and loop mounting it?

**Comment by Quasic** [comment]
@geek1011, I have not, but others have (@sdrausty is one, I think.) As I understand it, it is near impossible without root.

**Comment by komi015** [comment]
For this problème u Can use this comand:
termux-setup-storage ,it fond and u agree the the following android dialogue to allow sdcard permissions.
Thank

**Comment by giggls** [comment]
> For me, it doesn't work after I leave root with 'exit'.

Same here (Android 8.1 /LineageOS 15.1).

**Comment by Chubukov-Aleksey** [comment]
I found that AnExplorer can request permission to write on sdcard without need to select sdcard's root folder.

**Comment by QJKX** [comment]
> Finally figured it out for rooted devices running marshmallow or greater!
> 
> ```
> su
> pm grant com.termux android.permission.READ_EXTERNAL_STORAGE
> pm grant com.termux android.permission.WRITE_EXTERNAL_STORAGE
> ```
> 
> Edit: This only seems to work temporarily.

This doesn't seem to work (anymore?) on 8.1.
The commands work without an error, but I can't actually write to the external SD card.

WRITE_MEDIA_STORAGE looks like the correct permission (but putting that in the command doesn't work because it's not in the com.termux manifest.) I expect the permission to be restricted to system apps anyway, but that might be a better option for rooted users than running as root?

**Comment by bhagwandassony1** [comment]
![Screenshot_20200804-142357](https://user-images.githubusercontent.com/69147279/89274187-18bc7680-d630-11ea-82df-0ebc2e845d45.png)
