### ISSUE TITLE
Run command causing "Error: Not found; no service started." on version v0.83  on android 6

### ISSUE THREAD

**Issue by brunoais** [termux/termux-app#2000]
This is v0.83 on android 6

This is the command:
```am startservice --user 0 -n com.termux/com.termux.app.RunCommandService -a com.termux.RUN_COMMAND --es com.termux.RUN_COMMAND_PATH '/data/data/com.termux/files/usr/bin/top' --esa com.termux.RUN_COMMAND_ARGUMENTS '-n,5' --es com.termux.RUN_COMMAND_WORKDIR '/data/data/com.termux/files/home' --ez com.termux.RUN_COMMAND_BACKGROUND 'false'```
adb answers with:
`Error: Not found; no service started.`
logcat shows:
```
.113 20157 20157 D AndroidRuntime: Calling main entry com.android.commands.am.Am
.118  1665  3016 W ActivityManager: Unable to start service Intent { act=com.termux.RUN_COMMAND cmp=com.termux/.app.RunCommandService (has extras) } U=0: not found
```
Did I miss something related to my version? It appears like the version I have is the latest one that works on my phone. I only want some help and I don't expect fixes in case it is a bug that existed in this version.

If it's something that didn't exist by then, is there an alternative to run a small script to start the ssh server? I'm using termux ssh server because I want PPKey access instead of password

**Comment by agnostic-apollo** [comment]
Which version are you on?

**Comment by brunoais** [comment]
It's in the title :).
Termux 0.83 on Android 6

**Comment by agnostic-apollo** [comment]
Not possible to use `RUN_COMMAND Intent` on that version. It was added in [0.95](https://github.com/termux/termux-app/releases/tag/v0.95). Try [Termux:Tasker](https://github.com/termux/termux-tasker) or [Termux:Widget](https://github.com/termux/termux-widget). Not sure if it will surely work since your version is too old.

**Comment by brunoais** [comment]
@agnostic-apollo Does 0.95 work on android 6? If so, where can I find the apk? F-droid only stores only far back to 0.106

**Comment by xeffyr** [comment]
@brunoais No, v0.95 doesn't support Android 6 and won't be backported. We have already dropped this Android version from support.

**Comment by brunoais** [comment]
OK. I wish that information was included in the wiki where it explains about min version. I'll add that.

**Comment by xeffyr** [comment]
It is already under "system requirements" on main page (https://wiki.termux.com/wiki/Main_Page).

**Comment by brunoais** [comment]
That is for the latest version. Not for when the feature became available.
Unfortunately, changing to a different phone is very much not viable to me. Where I live they are super price hiped.

**Comment by agnostic-apollo** [comment]
0.83 was the last version for android 6 support.

You can get the APKs for termux-app and plugins from here. Will require uninstallation of termux-app and any plugins you have installed in your device if you installed them from playstore before, otherwise installation will fail for below APKs.

https://archive.org/details/termux-repositories-legacy

**Comment by brunoais** [comment]
@agnostic-apollo Oh! Nice!
However, I can't find 0.83 in there. The latest there seems to be `0.79`. Is that the one?

**Comment by agnostic-apollo** [comment]
It is 0.83 for termux-app. Click on `ANDROID PACKAGE ARCHIVE` to view the 8 files.

**Comment by brunoais** [comment]
OK. I got it now. I need:
`termux-v0.79-offline-bootstraps.apk`: Termux itself
`termux-task-git-debug.apk`: Termux addon for tasker.
It's working now.
Thank you for the help. This is exactly what I needed.

**Comment by agnostic-apollo** [comment]
welcome
