### ISSUE TITLE
`\b\n` does not work together 

### ISSUE THREAD

**Issue by MrAdityaAlok** [termux/termux-app#2001]
**Problem description**

Bakspace escape sequence does not work when printed in combination with new line character

Example:
- Python
```
Python 3.9.4 (default, Apr  8 2021, 23:14:57)
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print("gh\b")
gh
>>> print("gh\b",end="") #works now
g>>>
```
- Go
```
package main
import "fmt"

func main(){
  fmt.Print("kj\b")
}

Output:
k
```
But when
```
package main
import "fmt"

func main(){
  fmt.Println("kj\b")
}

Output:
kj
```
**Expected behavior**

should output as when without `\n`
**Additional information**

* Termux application version: 0.108
* Android OS version: 9

**Comment by Grimler91** [comment]
The same behaviour can be seen on archlinux so this is not a termux issue

**Comment by MrAdityaAlok** [comment]
@Grimler is there any workaround for this

**Comment by Grimler91** [comment]
Probably, I don't really know what you are actually trying to do though. Here's a stack exchange question asking basically the same as you asked here: https://stackoverflow.com/questions/9667462/backspace-behavior-in-python-statement-what-is-correct-behavior-of-printing-a#9667680

**Comment by MrAdityaAlok** [comment]
@Grimler thank you, I was having a big misconception 😄
