### ISSUE TITLE
Issue with apt and/or dpkg

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-app#2003]
Android 10
Device Manufacturer:LG
Also tested on samsung j7 crown running android 9
Same issue

Pkg installing via pkg is not work ipfs is giving error
"Failed to fetch https://ipfs.io/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4/pool/main/s/sdl2-ttf-static/sdl2-ttf-static_2.0.15-21_arm.deb  500  Internal Server Error [IP: 209.94.90.1 443]"

Expected install to work
Ipfs url may be down or issues with dpkg

Screenshot

Error:
![Screenshot_20210413-232413](https://user-images.githubusercontent.com/17087430/114654361-9f415180-9caf-11eb-9d05-b09f2a54471c.png)

Device info:

![Screenshot_20210413-232552](https://user-images.githubusercontent.com/17087430/114654388-b3854e80-9caf-11eb-87c3-f49bc94e55ab.png)

**Comment by WMCB-Tech** [comment]
Try changing working mirrors with `termux-change-repo` and try again

**Comment by strikersix23** [comment]
Did that its same error

**Comment by strikersix23** [comment]
In fact I did everything recommended

**Comment by WMCB-Tech** [comment]
i guess you may try:

```
apt clean && apt autoclean

termux-change-repo # pick working miror

[...]

pkg install <your-package>
```
