### ISSUE TITLE
Release version of SettingsActivity does not work

### ISSUE THREAD

**Issue by hrap1919** [termux/termux-app#2005]
**Problem description**

The release build (0.109) crashes after choosing any item in settings menu (Debugging and Terminal I/O).

**Steps to reproduce**

Build the release apk in Android Studio, run it, go to Settings/Debugging or Terminal I/O. The debug build works fine.

**Expected behavior**

The behavior similar to debug build.

**Additional information**

* Termux application version: 0.109
* Android OS version: 9.0
* Device model: Motorola g7 Power

**Comment by hrap1919** [comment]
The release build becomes fine after removing
```
minifyEnabled true
shrinkResources true
```
from the apps gradle script

**Comment by agnostic-apollo** [comment]
Did you not get a crash report notification when opening termux again or a stacktrace in logcat?

**Comment by hrap1919** [comment]
[crashreport.txt](https://github.com/termux/termux-app/files/6313376/crashreport.txt)

**Comment by agnostic-apollo** [comment]
Interesting, thanks. I'll look into it.

**Comment by agnostic-apollo** [comment]
The Tasker [latest beta](https://www.reddit.com/r/tasker/comments/mq4hwc/dev_tasker_51210beta_fixing_access_to_external/?utm_medium=android_app&utm_source=share) was also having problems due to proguard not working properly causing random issues, wonder if this is related. Those 2 options are like default for release APKs, I additionally disabled obfuscation in this release, which again shouldn't haven't thrown a `ClassNotFound` exception.

**Comment by hrap1919** [comment]
I am not sure that this is related to proguard. I have a broken debug apk if
```
debug {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.debug
        }
``` 
And I have a correctly workin release apk if
```
release {
            //minifyEnabled true
            //shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
```

**Comment by agnostic-apollo** [comment]
Proguard/R8 handles those as well.

https://developer.android.com/studio/build/shrink-code

**Comment by hrap1919** [comment]
Ok, thanks for the info. BTW the issue is minifyEnabled. I tried to to remove only one line shrinkResources, with the same crash

**Comment by agnostic-apollo** [comment]
The `shrinkResources` only takes effect if `minifyEnabled` is `true`.

**Comment by hrap1919** [comment]
Yes, but I tried 
```
release {
            minifyEnabled true
            //shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
```
The problem still exists.

 BTW I have installed the apk on Android 7 (armv7) with the same issue.

**Comment by agnostic-apollo** [comment]
It would, cause `minifyEnabled` does the code shrinking and obfuscation, removing `shrinkResources` wouldn't change anything.

The `TerminalIOPreferencesFragment` and `DebuggingPreferencesFragment` classes are not being used inside java code and are getting removed, they don't exist inside the apk.

I can reproduce the issue though. proguard rules need to be added. Looking into it.

**Comment by agnostic-apollo** [comment]
You can pull the latest changes from `master` branch and test it out for release builds. Thanks again.

**Comment by hrap1919** [comment]
Thanks, it works.

**Comment by agnostic-apollo** [comment]
Great, welcome.
