### ISSUE TITLE
Termux 0.110 missing in f_droid

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#2007]
The release notes https://github.com/termux/termux-app/releases
mention that 0.110 is available on f_droid, but it is not.

Forgot to publish it to f-droid ?

**Comment by agnostic-apollo** [comment]
It usually takes F-Droid a few days (often a week) after we release on github for them to build the new release and publish it. We don't build and publish it ourselves. Basically, wait a bit.
