### ISSUE TITLE
F-Droid back more than two versions

### ISSUE THREAD

**Issue by vkuehn** [termux/termux-app#2012]
**Problem description**
new versions are only on f-droid but that is still on an 0.108

**Steps to reproduce**
look at F-Doird market

**Additional information**
still it would be nice to get latest version also in Playstore. It's sad that F-Droid lags updates

**Comment by trygveaa** [comment]
It's an issue at F-Droids side:
https://github.com/termux/termux-app/issues/2011#issuecomment-823945801
https://github.com/termux/termux-app/issues/2011#issuecomment-824516106

**Comment by WMCB-Tech** [comment]
You can still get latest apks in github actions page and get apk artifakts though you need to do full uninstall and reinstall

**Comment by vkuehn** [comment]
@trygveaa thanks for the Link
@WMCB-Tech sure but really reduces the number of people who can use Termux thought. And for F-Droid it's a shame
