### ISSUE TITLE
The problem is that if I upgraded and updated Kali Linux why? It was running from the beginning and after I upgraded and updated.  I want to log in to Termux and start it, but it does not work. I want a possible solution?

### ISSUE THREAD

**Issue by Mustafa911-WEB** [termux/termux-app#2013]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:
![Screenshot_2021-04-23-08-23-36-710_com termux](https://user-images.githubusercontent.com/78945128/115829009-18ab1380-a417-11eb-8ba2-fcbe1983596e.jpg)

**Comment by xeffyr** [comment]
Issue is not related to Termux.
