### ISSUE TITLE
Termux use termux-chroot command problem

### ISSUE THREAD

**Issue by wangmings** [termux/termux-app#2016]
Android version: 10
Termux version: 0.108

Question:
Start the termux-chroot command! Cause some commands to freeze! Long execution time!

Problem demonstration:

1、Open Termux
2、Enter the termux-chroot command
3、Enter pip list

The above demonstrates more than just this command problem!  This problem also occurs with other commands under the termux-chroot command!  Of course do not start the termux-chroot command!  The execution of other commands does not have the problems mentioned above at all!  Currently looking for a solution!

You can see it from the above demo!
It takes longer to start the termux-chroot command and execute the pip list command!

**Comment by WMCB-Tech** [comment]
>It takes longer to start the termux-chroot command

Probably the reason why is that shells like zsh/fish with plugins might be slow in proot, do you have custom shells set?

**Comment by wangmings** [comment]
I did not install plugins such as zsh or fish!  There is no setting for the shell!  Basically keep the default state!  I also tried the ideas you provided!  Enter termux-chroot bash on the command line and enter pip list for detection!  But it didn't work!  It still takes more than ten seconds to output!

**Comment by wangmings** [comment]
I asked others that it was: Running a command in proot may take longer than in a normal shell, because proot adds an extra layer to intercept system calls!  The specific layer to be added for interception is not explained!  Is it possible to modify the interception by other methods!  Has reached the effect of executing other commands without stalling!  See if everyone has a good idea to solve this problem!

**Comment by WMCB-Tech** [comment]
> But it didn't work! It still takes more than ten seconds to output!

Because `termux-chroot` relies on `proot` performance loss is acceptable as it intercepts system calls

*Execution time in `pip list` without the use of `termux-chroot*
```
real    0m1.245s
user    0m0.965s
sys     0m0.246s
```

*Execution time in `pip list` with `termux-chroot`*
```
real    0m8.707s
user    0m4.195s
sys     0m1.338s
```

---

So basically, i have the same symptoms as yours (pip list takes 10s to launch)

But that's the way on how proot works, however this might be fixed but may be out-of-scope for increasing performance of proot

**Comment by wangmings** [comment]
Say something like this!  There is basically no solution to this problem!

**Comment by wangmings** [comment]
It seems that it is basically impossible to solve this problem!

**Comment by WMCB-Tech** [comment]
proot also depends on your device speed as well, but since this is the way
on how proot handle things, there's no easy fix, unless a new solution arise
