### ISSUE TITLE
Com Port Access Denied while Uploading Python sketch to the Node mcu in Pycharm

### ISSUE THREAD

**Issue by kiranshetty07** [termux/termux-app#2017]
I am running simple sketch in pycharm . But While uploading Its showing like this

raise PyboardError('failed to access ' + device)
ampy.pyboard.PyboardError: failed to access COM4 
Connecting to COM4
Uploading files: 0% (0/1)
If  i upload sketch through arduino ide then sketch upload succesfully done. If  I am uploading using   pycharm in Windows , i am not able to give com port access

please help me out

Thank you

**Comment by Grimler91** [comment]
Windows? What does this have to do with termux?
