### ISSUE TITLE
Package 'php' has no installation candidate how to fix this

### ISSUE THREAD

**Issue by Abhay575** [termux/termux-app#2018]

**Comment by xeffyr** [comment]
`apt update`, then `pkg install php`.

**Comment by Ken741** [comment]
![image](https://user-images.githubusercontent.com/90460593/132861166-b635c766-4cfc-45b5-a1a2-4c9eb02e7ba4.png)

Anyone knows how to fix this error???

**Comment by xeffyr** [comment]
@Ken741 Ensure that your device arch is not `x86_64` - on it php is disabled.

**Comment by Ken741** [comment]
@xeffyr  So I have to enalbe php on x64_86 arch??

**Comment by Ken741** [comment]
@xeffyr  I'm confsued ;-; I'm kind of new to termux

**Comment by Ken741** [comment]
@xeffyr  I am download "bash TermuxArch/setupTermuxArch.sh" This is what's happening right now 
![image](https://user-images.githubusercontent.com/90460593/132909671-1ca0d616-b6a1-4220-9502-8cb7861c8222.png)
what will happeny by this??

**Comment by Ken741** [comment]
@xeffyr  I'm new to termux I don't know what to do I'm confused
