### ISSUE TITLE
Where can I download v0.112 ?

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#2019]
This Github site points to the latest version of 0.112, but there is no download link and it says 'f-droid only', but on f-droid, the latest version is 0.108.
So why is version 0.112 not downloadable ?

**Comment by Grimler91** [comment]
The fdroid entry [has been updated](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.termux.yml#L690) and the [build succeeded](https://monitor.f-droid.org/builds/log/com.termux/112), so will hopefully be published on f-droid soon.

I also note that this is the third time you ask this question in the last two weeks. Asking multiple times will not make it appear faster on fdroid unfortunately. If you are very curious then I would suggest opening an issue in the fdroid repo and ask about it.

See also discussion in https://github.com/termux/termux-app/issues/2011

**Comment by WMCB-Tech** [comment]
lmao, people is really excited with the new Termux Release due to several new features
