### ISSUE TITLE
Termux uses hardcoded Google resolvers

### ISSUE THREAD

**Issue by yitzhaq** [termux/termux-app#2020]
**Problem description**

Termux appears to be hardcoded to using Google's resolvers (8.8.8.8 and 8.8.4.4) by default. If these happen to be blocked on your network, DNS doesn't work in Termux at all.

**Steps to reproduce**

`dig github.com | grep SERVER`

You should see your reply coming from system resolvers. Instead you see Google's resolvers (assuming you can reach them).

The problem has also been witnessed with other commands (like a simple `host`), so it appears to be Termux-wide, and not limited to `dig`.

**Expected behavior**

Termux should use the system's resolvers, like any other app. It should not be hardcoded to explicitly use any particular resolver(s). And if it absolutely has to use hardcoded resolvers - though I fail to see any reason why that should be the case - it should not use Google, but instead something with a rather more sensible privacy policy, like Cloudflare's 1.1.1.1/1.0.0.1.

**Additional information**

* Termux application version: 0.112 (from F-Droid)
* Android OS version: 9
* Device model: Samsung Galaxy S9

**Comment by xeffyr** [comment]
It doesn't hardcode anything on its own but rather uses what has been hardcoded in Android OS. It is not possible change this, as we will not re-implement the DNS functionality provided by the libc.

Some packages do hostname resolution on its own and use name servers provided in `$PREFIX/etc/resolv.conf`. You can edit this file and provide custom servers.

**Comment by ChiefMikeK** [comment]
after fresh install of dnsutils defualt =  
``` 
﹩cat $PREFIX/etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
```
And it's not what my system wifi setting is! recommend check your conf  
 :neckbeard:
