### ISSUE TITLE
Cannot update to newest version of Termux

### ISSUE THREAD

**Issue by asxlvm** [termux/termux-app#2025]
**Problem description**

So, my current Termux version is the newest one from Google Play (0.101), I tried updating to the one from F-Droid but I keep getting "App not installed"

**Steps to reproduce**
 
Install newest GP version of Termux (0.101) and try updating to the one from F-Droid

**Expected behavior**

It should update without any issues

**Additional information**

* Termux application version: 0.101
* Android OS version: 10
* Device model: Poco F1
* Available storage: 5GB

**Comment by WMCB-Tech** [comment]
Uninstall Termux app and it's Add-ons from Google play first then install Termux app from F-droid

See https://github.com/termux/termux-app#installation
