### ISSUE TITLE
NullPointerException on com.termux.app.TermuxService.wantsToStop()

### ISSUE THREAD

**Issue by MatthewScholefield** [termux/termux-app#2026]
When I opened the Termux app after it was cleared from my recent apps, it immediately notified me of this crash. I have attached the report below. I cannot consistently reproduce but it has happened about two times before, only within the last few weeks. A possibly relevant detail is that I frequently use Termux:Widget to launch scripts (but this error was from just launching regular Termux).

## Report Info

**User Action**: `CRASH_REPORT`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2021-05-02 18:49:30 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2021-05-02 14:09:19 UTC`  

### Stacktrace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.termux.app.TermuxService.wantsToStop()' on a null object reference
	at com.termux.app.terminal.TermuxTerminalSessionClient.onSessionFinished(TermuxTerminalSessionClient.java:77)
	at com.termux.terminal.TerminalSession$MainThreadHandler.handleMessage(TerminalSession.java:358)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.112`  
**VERSION_CODE**: `112`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
##

### Software

**OS_VERSION**: `4.19.110-perf+`  
**SDK_INT**: `30`  
**RELEASE**: `11`  
**INCREMENTAL**: `2104120358`  
**SECURITY_PATCH**: `2021-04-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `OnePlus`  
**BRAND**: `OnePlus`  
**MODEL**: `KB2007`  
**PRODUCT**: `OnePlus8TTMO`  
**DISPLAY**: `KB2007_15_210412`  
**ID**: `RP1A.201005.001`  
**BOARD**: `kona`  
**HARDWARE**: `qcom`  
**DEVICE**: `OnePlus8TTMO`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by agnostic-apollo** [comment]
Thanks a lot for the report. Should be fixed in next release.
