### ISSUE TITLE
licenses

### ISSUE THREAD

**Issue by PRACH4** [termux/termux-app#2028]
`<program> Copyright (C) <year> <name of author>`

This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'. This is free software, and you are welcome to redistribute it under certain conditions; type `show c' for details.

**Comment by agnostic-apollo** [comment]
The name of author isn't required for GPLv3 licence. I assume that's what you mean.

Year and author's name not included in Linux license itself.

https://github.com/torvalds/linux/blob/master/COPYING

https://github.com/torvalds/linux/blob/master/LICENSES/preferred/GPL-2.0

**Comment by agnostic-apollo** [comment]
I have still added the repository name to the license in 3e7b360.

**Comment by agnostic-apollo** [comment]
Don't open multiple issues for the same thing.
