### ISSUE TITLE
pip install lxml error:

### ISSUE THREAD

**Issue by kmahyyg** [termux/termux-app#203]
gcc compile libxml2 error
not found /usr/includes/libxml2/libxml/xpath.h

i guess it's because your apk didn't soft-link this path .
please fix.
screenshot can be seen here:

![scrrenshoy] (https://ooo.0o0.ooo/2016/11/27/583af6587f37a.png)

**Comment by fornwall** [comment]
Install the required package for building lxml:

    apt install libxslt-dev

Does it work now?

**Comment by kmahyyg** [comment]
thanks.it works.

2016年11月28日 01:43，"Fredrik Fornwall" <notifications@github.com>写道：
