### ISSUE TITLE
Why packages are not going to be update...

### ISSUE THREAD

**Issue by evildevill** [termux/termux-app#2030]
<!-
![Screenshot_20210504_051053](https://user-images.githubusercontent.com/66058079/116951363-0f386b80-aca1-11eb-8afa-764b65411d54.jpg)

**Additional information**

* Termux application version: latest
* Android OS version: 10
* Device model: vivo V30

**Comment by WMCB-Tech** [comment]
See https://github.com/termux/termux-packages/issues/6726
