### ISSUE TITLE
fzf key-bindings not working on Termux

### ISSUE THREAD

**Issue by pvonmoradi** [termux/termux-app#2031]
**Problem description**
I've installed `fzf` in Termux. Problem is, none of the keybindings (Ctrl+t, Alt+c, Ctrl+r) work but fzf itself works:  
`history | fzf` ->️✅
`Ctrl+r` -> ❌

**Steps to reproduce**
`pkg install fzf fd`
`cat ~/.bashrc`
```bash
# Using fd instead of find for fzf
# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fd --type f'
# To apply the command to CTRL-T and ALT-C as well
export FZF_ALT_C_COMMAND="fd --type d"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```
**Expected behavior**
fzf key bindings should work similar to desktop Linux

**Additional information**
Also does not work on a ssh session from desktop linux.

* Termux application version:`0.101`
* Android OS version: `10`
* Device model:`Galaxy M20`

**Comment by pvonmoradi** [comment]
The problem was that key-binding definitions were not actually sourced in my `.bashrc`. 
Solved with this:  
```bash
# FZF configs in TERMUX
# Auto-completion
[[ $- == *i* ]] && source "$PREFIX/share/fzf/completion.bash" 2> /dev/null
# Key bindings
source "$PREFIX/share/fzf/key-bindings.bash"

# Using fd instead of find for fzf
# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fd --type f'
# To apply the command to CTRL-T and ALT-C as well
export FZF_ALT_C_COMMAND="fd --type d"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```
Note that the `completion.bash` are for invoking fzf automatically on calling tab on commands like `kill -9 <TAB>`

**Comment by agnostic-apollo** [comment]
Glad to hear you got it solved. Closing.
