### ISSUE TITLE
I am using this app from 1 year it's very very good app , I almost write my every code in it (programming) ,but there are some issues,Please add pygame and java direct compiler like in c/c++ (gcc/g++)

### ISSUE THREAD

**Issue by SD-RX** [termux/termux-app#2032]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: 112
* Android OS version: 7.1.2
* Device model: miui

**Comment by xeffyr** [comment]
`pygame` is a python package installable through pip. Packaging policy: https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests

JDK is already requested.
