### ISSUE TITLE
Turmex 0.112 apk not installed on f droid

### ISSUE THREAD

**Issue by MohdAltaf01** [termux/termux-app#2034]
Please help fast this version is not installing

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app#installation

Uninstall Termux app and add-ons like Termux:API, Termux:Boot, Termux:Widget and others before installing app from F-Droid.

**Comment by MohdAltaf01** [comment]
> https://github.com/termux/termux-app#installation
> 
> Uninstall Termux app and add-ons like Termux:API, Termux:Boot, Termux:Widget and others before installing app from F-Droid.

Thanks
