### ISSUE TITLE
Can I start the APP on my phone with a command on termux

### ISSUE THREAD

**Issue by wangmings** [termux/termux-app#2036]
Can I start the APP on my phone with a command on termux

**Comment by agnostic-apollo** [comment]
Check [here](https://www.reddit.com/r/termux/comments/62zi71/can_i_start_an_app_from_termuxs_command_line_how/dfqqs0k?utm_source=share&utm_medium=web2x&context=3)

**Comment by wangmings** [comment]
thank you very much!  But the second part com.package.name.ActivityName is the activity class: is there any good way to view this activity class of App?

**Comment by agnostic-apollo** [comment]
Use {App Manager](https://github.com/MuntashirAkon/AppManager), then check `Main Activity` at the bottom under `APP INFO` tab.

**Comment by wangmings** [comment]
Is there a command line to view the method of this App activity class

**Comment by agnostic-apollo** [comment]
Over adb or with root. You can grant termux `android.permission.DUMP` permission once over `adb` with ` adb shell pm grant com.termux android.permission.DUMP` so that you can use `dumsys` commands without root. Requires Termux version `>= 0.109`

https://stackoverflow.com/questions/12698814/get-launchable-activity-name-of-package-from-adb/28738721

**Comment by wangmings** [comment]
In the case of obtaining root, it seems that there is no adb command on termux!  Only execute: pm grant com.termux android.permission.DUMP will prompt an error: cmd: Failure calling service package: Failed transaction (2147483646)

**Comment by agnostic-apollo** [comment]
`adb != root`. Adb commands run as the `shell` user. Root commands runs with `root` user and have higher privilege.

You need to run `pm` command prefixed with adb if you haven't rooted your device. Run it from a computer after connecting phone with usb or after installing `adb` with [`android-tools`](https://www.reddit.com/r/termux/comments/mmu2iu/announce_adb_is_now_packaged_for_termux/) and using wireless mode toggle in developer options on android 11+.

https://developer.android.com/studio/command-line/adb

**Comment by wangmings** [comment]
thank you for your reply!  That is to say, this adb command can only be performed through the PC! In termux, only this command can be used to obtain the App activity class: aapt dump badging base.apk
