### ISSUE TITLE
repository not available

### ISSUE THREAD

**Issue by salimicali** [termux/termux-app#2037]
target os: android 7
termux version: 0.101

This problem occurs when  directly connection or VPN connection

$ apt update                               
  Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease                                                 Ign:2 https://main.termux-mirror.ml stable InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease                                            Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden                                           Err:6 https://main.termux-mirror.ml stable Release
  Redirection from https to 'http://ww38.main.termux-mirror.ml/dists/stable/Release' is forbidden
Reading package lists... Done                              E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.       N: Metadata integrity can't be verified, repository is disabled now.                                                  N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).                                 E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.  N: Metadata integrity can't be verified, repository is disabled now.                                                  N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://main.termux-mirror.ml stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-app#google-playstore-deprecated and https://github.com/termux/termux-packages/issues/6726
