### ISSUE TITLE
[Question] Can this app run on Android 4 without termux packages?

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/termux-app#2040]
Hi, i know this app can't be installed on Android 4 due to various reasons like porting packages for Android 4

But does the core Termux app itself run on Android 4 (jellybean/kitkat) as well just to run barebones Android's shell in Termux UI (just for fun i guess)?

If so, should i recompile Termux app by setting the minimum api level for compatibility with Android 4 and possibly removing all Bootstrap Related stuff that could execute Termux binaries?

That's all i can think of, any answer is appreciated, thanks!

**Comment by xeffyr** [comment]
Nope, due to used APIs which not present in old Android versions.

While the app can be ported, that's unlikely to be done officially.

**Comment by agnostic-apollo** [comment]
Yeah, as xeffyr mentioned, a lot of Android/Java APIs currently being used are not compatible with android 4. Even supporting android 7 for file APIs was troublesome in `0.109`. For Android `4`, it would probably be easier to backport [`0.75`](https://github.com/termux/termux-app/compare/v0.75...v0.76) before `minSdkVersion` was bumped from [`21` to `24`](https://github.com/termux/termux-app/commit/c76cec186af4df7b1020cd1471ea50dfcb25afba#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9), if its even possible without crippling something important.
