### ISSUE TITLE
curl: (3) URL using bad/illegal format or missing URL Error

### ISSUE THREAD

**Issue by Swetha554** [termux/termux-app#2041]
$ curl -d '{"QTEST_API_KEY": "[MASKED]", "QTEST_PATH": "https://qtest.t-mobile.com/", "QTEST_PROJECT_ID": 108, "QTEST_TEST_CASE_ID": [TS-677], "QTEST_RUN_CONTAINER_ID":[165759]}' -H "Content-Type: application/qtest" -X POST '/runTests/' -o Results.xml

Facing Below error for above curl statement . Can anyone help me out in resolving it
curl: (3) URL using bad/illegal format or missing URL

**Comment by xeffyr** [comment]
This is Termux application bug tracker. We would not look into issues with third-party software or issues caused by your misunderstanding of command (`curl`) usage.

`man curl` to see the command line format.
