### ISSUE TITLE
Can ONLY install from Play Store

### ISSUE THREAD

**Issue by soulife83** [termux/termux-app#2042]
I can install other apps from F-Droid. I can install other APK files I've downloaded. I turned off Google's app protection. I even tried the download from the website. Installs "fail for unknown reason". But will install fine or Google Play.

Download is confirmed not corrupted.

Stock OEM Galaxy S10+
USA, Unlocked, No Root, never carrier flashed device.
Fully up to date Android 11 w\ May 1st security patch.

I just want my repos to update 😔

**Comment by xeffyr** [comment]
Before installing Termux from F-Droid, **uninstall** the Termux application and all add-ons like Termux:API, Termux:Widget, Termux:Styling, etc.

https://github.com/termux/termux-app#installation

**Comment by soulife83** [comment]
None of them are installed. I wouldn't comment first and then try
everything I could think of last of course.
I freshly installed Termux on a new phone. It wouldn't update the repos.
Google searches implied Play store obsolescence, so I uninstalled and tried
F-Droid.
F-Droid installs all fail due to "an unknown error"
The APK from the website fails to install (and yes, unknown sources are
permitted).

I've put extensive effort into getting this to work. I didn't want to fill
the post with "yes, I applied common sense" content. Should I post logs?
Something is not right...

**Comment by Grimler91** [comment]
> Should I post logs?

Yes, post a logcat and we can see what the issue is

**Comment by WMCB-Tech** [comment]
@soulife83 

> F-Droid installs all fail due to "an unknown error"

That happens to me whenever i install stuff in F-droid, (not App not installed error)

You could download Termux here directly from the F-Droid site
https://f-droid.org/en/packages/com.termux/

**Comment by soulife83** [comment]
I did download directly from the site. It still failed. I will get logs
tomorrow.
