### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ismael9090** [termux/termux-app#2043]
Hi every body  i faced a problem after install metaspliot as shown below  any idaea ?
msfconsle

/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/static.rb:111:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:37:in `new'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:37:in `build'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:101:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:101:in `inject'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:101:in `build'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/engine.rb:510:in `block in app'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/engine.rb:506:in `synchronize'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/engine.rb:506:in `app'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /data/data/com.termux/files/usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /data/data/com.termux/files/usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /data/data/com.termux/files/usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /data/data/com.termux/files/usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /data/data/com.termux/files/usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /data/data/com.termux/files/usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /data/data/com.termux/files/usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `public_send'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `method_missing'
        from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:4:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/msfconsole:18:in `require'
        from /data/data/com.termux/files/usr/bin/msfconsole:18:in `<main>'
~ $

**Comment by xeffyr** [comment]
Sorry, but we're not providing help with Metasploit installation. If you have installed it with a some script from the Internet, try to reach its author for troubleshooting.
