### ISSUE TITLE
Access to /storage/emulated/0/Android/data/

### ISSUE THREAD

**Issue by udiNur** [termux/termux-app#2044]
**Feature description**
Enable accessing to `/storage/emulated/0/Android/data/` with termux-storage-setup
**Reference implementation**
Is passable in other file explorer apps like "Total Commander" after you enabled  it
![1](https://user-images.githubusercontent.com/13526747/117436646-e1208900-af37-11eb-8294-48c63cf36c0d.jpeg)
![2](https://user-images.githubusercontent.com/13526747/117436788-0d3c0a00-af38-11eb-83d6-6fb0eed76c46.jpeg)

I think that it becomes a lot more useful after OnePlus has moved the phone recordings from the general storage into `/Android/data/com.oneplus.communication.data/` on one of the last updates

**Other Links:**

1. https://www.reddit.com/r/oneplus/comments/mxkyfe/android_11_oneplus_7t_call_recording_file_location/gx2kh13/
2. https://android.stackexchange.com/questions/231466/can-i-mount-data-data-app-name-on-external-sd-card

**Comment by xeffyr** [comment]
Enabling access to `/sdcard/Android` is not possible because that's Android restriction. Nothing can be done by Termux app with that.
