### ISSUE TITLE
ghc-pkg cannot link libncursesw.so.6

### ISSUE THREAD

**Issue by dammi-i** [termux/termux-app#2045]
hello I'm getting this error whenver I try to run ghc-pkg:
`CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/ghc-8.10.1/bin/ghc-pkg": library "libncursesw.so.6" not found`
even that I have libncursesw.so.6 in usr/lib path.

**Comment by xeffyr** [comment]
Known issue, also note that package is located at https://github.com/termux/unstable-packages/tree/master/disabled-packages/ghc. Package cannot be fixed currently since our clang version is too high for `ghc`.
