### ISSUE TITLE
pkg update && pkg upgrade error

### ISSUE THREAD

**Issue by reedniv** [termux/termux-app#2046]
I have issue about update & upgrade pkg on response Forbidden like this :

`Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease      Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release          403  Forbidden
Get:1 https://k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx.ipns.dweb.link stable InRelease [14.0 kB]
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release     403  Forbidden
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

What the problem and what i can to do

**Comment by agnostic-apollo** [comment]
Check termux/termux-packages#6726
