### ISSUE TITLE
Cannot install wget

### ISSUE THREAD

**Issue by PQCraft** [termux/termux-app#2047]
**Problem description**

`pkg install wget` says `Cannot locate package: wget` or something to that effect. <p>
**Steps to reproduce**

[install termux]
```
pkg upgrade
pkg install wget
```
[use wget] <p>
**Expected behavior**

pkg installs wget and doesnt return an error <p>
**Additional information**
The repos seem out of date and when its updating them I end up seeing a lot of '403 Forbidden' errors.
* Termux application version: 0.101
* Android OS version: 9
* Device model: Samsung Galaxy J7 Star

**Comment by agnostic-apollo** [comment]
Check termux/termux-packages#6726

After changing repositories, `pkg install wget` should work. And move to F-Droid builds.

**Comment by PQCraft** [comment]
@agnostic-apollo Thank you for responding quickly and it worked btw :)
