### ISSUE TITLE
I can't install packages

### ISSUE THREAD

**Issue by Maria2020-svg** [termux/termux-app#2052]
![Screenshot_20210511-001617](https://user-images.githubusercontent.com/62624271/117726004-98dec080-b1ee-11eb-8f3f-608e211f7009.png)

**Problem description**

I cannot install any package
**Steps to reproduce**

**Expected behavior**

To install packages.
**Additional information**

* Termux application version: 0.112
* Android OS version: 9
* Device model: Cubot Note 7

**Comment by xeffyr** [comment]
`pkg update`
