### ISSUE TITLE
Will termux support kivy or be able embeded in kivy in near future?

### ISSUE THREAD

**Issue by Karobben** [termux/termux-app#2053]
I always want to write a cross-platform app but I only know bash and python. As a result, kivy is the best choice for me.
I previously wrote a few R and python scripts on termux, it works fine but hard to be executed on the phone with the virtue keyboard. Tui app is acceptable but the GUI app is much cooler than it. 

But kivy only ran in the python environment which has limited possibilities compared with termux.
It must have tons of fun if Kivy could be executed on termux or embedded in a kivy app. 

So, if it is possible, I'd like to write an app like Aid Learning [aidlearning/AidLearning-FrameWork](https://github.com/aidlearning/AidLearning-FrameWork/blob/master/README-cn.md)

**Comment by xeffyr** [comment]
There no plans with Kivy integration.
