### ISSUE TITLE
getting this error while updating package using apt update .....

### ISSUE THREAD

**Issue by its-shubham2323** [termux/termux-app#2054]
**Problem description**

**Steps to reproduce**

**Additional information**

* Termux application version: 0.101
* Android OS version: 10 
* Device model: Redmi 7 ![IMG_20210512_122500.jpg](https://user-images.githubusercontent.com/65482186/117931752-333d2200-b31d-11eb-977e-abd84d15d613.jpg)

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/6726
