### ISSUE TITLE
Ability to access termux $PREFIX using documents API

### ISSUE THREAD

**Issue by suhan-paradkar** [termux/termux-app#2055]
**Feature description**

Its really comfortable to manage files with external file manager.. but currently only $HOME directory is accessible... Can $PREFIX be made accessible the very same way?

**Reference implementation**

Does another app/terminal emulator have this feature?
No
Provide links to more background information.

**Comment by WMCB-Tech** [comment]
You can symlink `$PREFIX` on your home directory as a workaround

**Comment by suhan-paradkar** [comment]
> You can symlink `$PREFIX` on your home directory as a workaround

Oh yeah.. I tried it.. It works..
