### ISSUE TITLE
A Question from Kali NetHunter

### ISSUE THREAD

**Issue by kimocoder** [termux/termux-app#2060]
Good day!

This is a inquiry, asking for permission to fork and use Termux as our preferred terminal instead of our current running.

Termux is a better option for us basicly.

Gimme a hint if it's okey that we fork and NetHunterize it 👍 

christian@aircrack-ng.org

**Comment by Grimler91** [comment]
Hi, yeah that is totally fine, this is an open-source project after all. It would not be the first fork either.

You will need to update all occurrences of TERMUX_PREFIX, and re-compile packages and bootstraps against the other prefix, but you probably know that already 👍 
See https://github.com/termux/termux-app/issues/1983 for a recent issue with some problems and solutions when forking.

**Comment by kimocoder** [comment]
Perfect, has to ask anyway 🥇 

Thanks for the information!

**Comment by suhan-paradkar** [comment]
@t184256 's [nix-on-droid](https://github.com/t184256/nix-on-droid-app) can be a good example here...
