### ISSUE TITLE
Pkg does not work.  Forbidden 403

### ISSUE THREAD

**Issue by Maxython** [termux/termux-app#2061]
### Hello everyone.
For some reason pkg does not work, because of this I cannot update the system. 
#### Here is the error screen:
![Screenshot_20210514-171334_Termux](https://user-images.githubusercontent.com/60917834/118313041-ec0c8800-b4fa-11eb-9c46-a5c6b3eb8bda.jpg)
I've already tried reinstalling termux - no result.  

----
Is it some kind of service bug or is it a service setting?

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-packages/issues/6726 and also install from F-Droid instead.
