### ISSUE TITLE
Idea: Back to Google Play (How can WebAssembly make termux better)

### ISSUE THREAD

**Issue by RazyRabbit** [termux/termux-app#2062]
# Back to Google Play (How can WASM make termux better)

## What is WebAssembly (WASM)?
WASM is a binary instruction format and a stack-based virtual machine.

## How can it contribute to Termux?
* **Easy** (development/migration will be easy for the Termux Team)
* **Fast** (the speed will continue near native)
* **Platform Independent** (ends with the need to have versions of the packages for ARMv7, ARMv8, x86 in the repositories)
* **Sandboxed** (adds a security layer and better permission control between the executable and the environment)

## Google Play
Since WASM is virtual machine, we do not need to worry about problems with syscalls restrictions annymore, and everything should work without many modifications.

https://webassembly.org/

**Comment by agnostic-apollo** [comment]
WASM has already been discussed. You are welcome to send a pull request for a working implementation.

https://github.com/termux/termux-app/issues/1072#issuecomment-633665141
