### ISSUE TITLE
I can't install new updates.

### ISSUE THREAD

**Issue by Enemyforever** [termux/termux-app#2064]
-----

**Problem description**
 I can't install new versions of termux app from 0.108 version, onwards.

**Steps to reproduce**
 ----

**Expected behavior**
 ----

**Additional information**

* Termux application version: 0.108 - 0.111 - 0.112
* Android OS version: 9
* Device model: Huawei Y6 2019

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-app#installation

**Comment by Enemyforever** [comment]
If you think I didn't uninstall the android version I have to say I did and nop.

**Comment by xeffyr** [comment]
@Enemyforever You need to uninstall
* The Termux application. (perhaps you did only this step)
* All add-ons: Termux:API. Termux:Boot, Termux:Widget, Termux:Styling and so on.

**Comment by Enemyforever** [comment]
Thanks. I didn't uninstall termux widget.

Now I have the new version installed.
