### ISSUE TITLE
Can't even pkg update after installing

### ISSUE THREAD

**Issue by Dargkkast** [termux/termux-app#2065]
**Problem description**

I wanted to clean up my termux. Because I thought uninstalling stuff was such a chore, I just went and uninstalled and installed once again. But now I can't even "apt update"/"pkg update"...

![Screenshot_2021-05-16-15-26-34-912_com termux](https://user-images.githubusercontent.com/78185094/118398959-1d9c6500-b65b-11eb-87d9-1dcdb216899b.jpg)

I uninstalled and reinstalled again, but to no avail. I can use nano, mkdir, ls, pwd, df,... so the commands do work. I can also ping Google, so Termux can connect to internet.

**Steps to reproduce**

Introducing the command just after installing Termux...
☉ ‿ ⚆

**Additional information**

* Termux application version: 0.101
* Android OS version: 10
* Device model: Redmi Note 8T

**Comment by agnostic-apollo** [comment]
Install from F-Droid https://github.com/termux/termux-app#Installation and/or check https://github.com/termux/termux-packages/issues/6726
