### ISSUE TITLE
Repositories are all down

### ISSUE THREAD

**Issue by talesam** [termux/termux-app#2066]
I am using the playstore termux in the stable version. The repositories are all down, I tested them all and they are not working. Could you check that ?!

See the image below when I send the repository update.

![photo_2021-05-16_13-25-06](https://user-images.githubusercontent.com/981368/118404656-30f30480-b64a-11eb-8827-824ddd69cde5.jpg)

**Comment by xeffyr** [comment]
Don't use Termux from Play Store. It is deprecated and has outdated repository links.

See https://github.com/termux/termux-packages/issues/6726.
