### ISSUE TITLE
curl not working

### ISSUE THREAD

**Issue by Taushifk** [termux/termux-app#2069]
**Problem description**

I am trying to install laravel but show error

![Screenshot_20210517-191939](https://user-images.githubusercontent.com/53345813/118509516-b90e0280-b74d-11eb-8ccb-da7591b2661c.jpg)

also try pip install but return error

![Screenshot_20210517-191659__01](https://user-images.githubusercontent.com/53345813/118509641-d80c9480-b74d-11eb-922f-ecf2de947196.jpg)

I think is curl error but npm install is working.

**Steps to reproduce**

composer create-project --prefer-dist laravel/laravel:^7.0 blog
pip install pillow

**Expected behavior**

Install packege

**Additional information**

* Termux application version:  0.112
* Android OS version: 11
* Device model: OnePlus nord

**Comment by xeffyr** [comment]
Check your network connection. Also check whether your packages are up-to-date.
