### ISSUE TITLE
C file does not compile (error glob).

### ISSUE THREAD

**Issue by Maxython** [termux/termux-app#2070]
### Hello everyone.
Trying to compile the C file but getting an error.
```
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/main-d1040d.o: in function `main':
main.c:(.text+0x10): undefined reference to `globfree'
```
This is strange because all important packages (including glob) are installed.  Even stranger is the fact that the file is easily compiled on another device.  

I guess this is due to the different device architectures.  On the device that compiles with an error, the arm7l architecture (32bit).  And on the other, which compiles without errors, the aarch64 architecture.

**Comment by xeffyr** [comment]
`pkg install libandroid-glob` - if not installed.

Then link your program with this library:
```
clang main.c -o main -landroid-glob
```

> Even stranger is the fact that the file is easily compiled on another device.

That depends on Android version. The lower Android version, the less functions are implemented in system C library. You need to link with libandroid-glob.

**Comment by Yisus7u7** [comment]
I'm the one with the 32-bit cell phone, The tWhen compiling that error is thrown, and if I have libandroid-glob installed, my cell phone is Android 8

**Comment by xeffyr** [comment]
> and if I have libandroid-glob installed

Just having it installed is not enough. You should link with it manually since this is not a standard C library. How to do it shown in this comment: https://github.com/termux/termux-app/issues/2070#issuecomment-843598728

glob function is natively available on Android 9 and higher. On everything older you have to link with android-glob library.

**Comment by Yisus7u7** [comment]
Oh ok, @Maxython
