### ISSUE TITLE
Cursor styles

### ISSUE THREAD

**Issue by suhan-paradkar** [termux/termux-app#2075]
**Feature description**

Well, the recent v0.113 did implement 'blinking cursor' ,well this is a request to add additional cursor options, like backslash cursor or underscore as a cursor.
I would like to contribute for this feature....

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by agnostic-apollo** [comment]
I thought about adding that, but it could already be done with `.bashrc`. Check [TerminalTest](https://github.com/termux/termux-app/blob/v0.113/terminal-emulator/src/test/java/com/termux/terminal/TerminalTest.java#L103).

- block: `echo -e "\033[2 q"`
- underline: `echo -e "\033[4 q"`
- bar: ` echo -e "\033[6 q"`

If we had to add that in termux app itself, then it would require

- Defining a key and internal values, map, default value `TerminalEmulator.DEFAULT_CURSOR_STYLE`  in [TermuxPropertyConstants](https://github.com/termux/termux-app/blob/master/termux-shared/src/main/java/com/termux/shared/settings/properties/TermuxPropertyConstants.java).
- Add `Integer getTerminalCursorStyleInternalPropertyValueFromValue(String value)` and `Integer getTerminalCursorStyle()` methods in [TermuxSharedProperties](https://github.com/termux/termux-app/blob/master/termux-shared/src/main/java/com/termux/shared/settings/properties/TermuxSharedProperties.java) to get the value.
- Add `DEFAULT_CURSOR_STYLE =  CURSOR_STYLE_BLOCK` to `TerminalEmulator`.
- Get that properties value in [TerminalEmulator.reset()](https://github.com/termux/termux-app/blob/master/terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java#L2331) with the [`TerminalSessionClient mClient`](https://github.com/termux/termux-app/blob/master/terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java#L155) if `mClient` is not `null`. Ideally add `TerminalEmulator.setCursorStyle()` method and call it in `reset()`.
- Which would require adding the interface method `Integer getTerminalCursorStyle()` to [`TerminalSessionClient`](https://github.com/termux/termux-app/blob/master/terminal-emulator/src/main/java/com/termux/terminal/TerminalSessionClient.java) which returns an `Integer`, not an **int**.
- Add default implementation to [`TermuxTerminalSessionClientBase`](https://github.com/termux/termux-app/blob/master/termux-shared/src/main/java/com/termux/shared/terminal/TermuxTerminalSessionClientBase.java) which returns `null` (which `TerminalEmulator` should check to default to `DEFAULT_CURSOR_STYLE`).
- Add termux actual implementation in [TermuxTerminalSessionClient](https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/terminal/TermuxTerminalSessionClient.java) which returns `mActivity.getProperties().getTerminalCursorStyle()`.

Hope that's clear enough. Check the previous commits to the files to see how it should be done, like 31298b88 or e4e638bd. Make sure to add javadocs and also comments where appropriate.

**Comment by suhan-paradkar** [comment]
@agnostic-apollo yeah I saw a few lines of code which idicated that it was a WIP..
