### ISSUE TITLE
Native text input box hides the keyboard

### ISSUE THREAD

**Issue by Archenoth** [termux/termux-app#2077]
**Problem description**

When you swipe the extra keys row to get to the native input text box for typing, the soft keyboard hides itself.

In addition, when you tap the terminal, if you tap the text input box again, the keyboard hides and returns really quickly, resizing the terminal twice in the process. (Which can be really noticeable in ncurses programs)

**Steps to reproduce**

1) Open a new Termux window with an extra keys row while using a soft keyboard
2) Swipe the extra keys row to get access to the native input box

And for bonus points, after the above:
1) Tap the terminal window
2) Tap the native input box as if you were going to type

![GIF showing both issues, first showing a termux window with a keyboard, and watching it disappear both when swiping the extra keys row, and also when tapping the terminal and then the native input box](https://user-images.githubusercontent.com/1385527/119180492-99b4f500-ba2d-11eb-8277-bc21977ee28e.gif "Keyboard disappearing in the two ways described above, oh nose!")

**Expected behavior**

Neither situation should hide the keyboard and cause terminal resizes.

**Additional information**

* Termux application version: Version 0.113
* Android OS version: 11
* Device model: Pixel 5

**Comment by xeffyr** [comment]
Confirming issue on the latest version (v0.113). Doesn't happen on 0.112.

**Comment by agnostic-apollo** [comment]
Thanks for the report. Should be fixed in the next release.

**Comment by Archenoth** [comment]
Nice! Thank youuu~

**Comment by agnostic-apollo** [comment]
welcome :)
