### ISSUE TITLE
Execution of pasted commands

### ISSUE THREAD

**Issue by w-canvas** [termux/termux-app#2078]
**Feature description**

Since updating to 0.113 termux doesn't recognize the last "RETURN" (end line) character as execution request when a command is pasted from the clipboard.

The shell, now,  just adds a line and waits for user input instead of running the command.

Automatic execution made certain tasks easier for me.

Is there a way to turn this feature back on?

**Reference implementation**

Gnome terminal executes pasted commands by default.

**Comment by xeffyr** [comment]
This is not Termux issue, neither shell bug or disabled "feature". Expected behaviour of Bash 5.1 regarding data pasted from clipboard.

You don't see this issue in your Gnome Terminal due to either different Bash version or different shell.

**Comment by xeffyr** [comment]
You can try to edit `$HOME/.inputrc` by adding this line
```
bind 'set enable-bracketed-paste off'
```

**Comment by agnostic-apollo** [comment]
You can check the current value with `bind -v | grep paste`

**Comment by w-canvas** [comment]
> You can try to edit `$HOME/.inputrc` by adding this line
> 
> ```
> bind 'set enable-bracketed-paste off'
> ```

Thank you. I added the line and now I'm back to full efficiency.
