### ISSUE TITLE
How to write on sd card 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-app#2082]
@xeffyr @WMCB-Tech

Hello, and accessed my sd card from termux (no root), the sd card supports executables and this would be of great help to me, but termux can not write files on it, gives you permission denied, can I fix it?

![Screenshot_20210523-201358](https://user-images.githubusercontent.com/64093255/119284274-ec94d500-bc04-11eb-85dc-1df7131d409f.png)

![Screenshot_20210523-201717](https://user-images.githubusercontent.com/64093255/119284356-26fe7200-bc05-11eb-9a3a-4dafbcf10c20.png)

**Comment by agnostic-apollo** [comment]
Writing to external removable sd card and USBs is not officially supported by Android with shell commands and is only supported with SAF. It may work on some devices, but not all. You can't do anything to change that without root.

**Comment by WMCB-Tech** [comment]
probably it is restricted in read only but with access to it's app directory 
`/storage/1234-5678/Android/data`

Normal command line applications won't be able to write in external storage completely but Android apps can have full access into it

You can see more at
https://wiki.termux.com/wiki/Internal_and_external_storage

**Comment by Yisus7u7** [comment]
Ok, thank you very much, the sd card if you allow executables, the rare thing is that the application folder (com.termux) does not allow them

**Comment by RalfWerner** [comment]
> but termux can not write files on it, gives you permission denied, can I fix it?

@Yisus7u7 Access to your external data should be possible by Steps: _Deny_ and _Allow_ in the  Android Storage Setup for the Termux app. This is actually made by `termux-setup-storage` (you've already done), but _sometimes_ does not work, especially with Android 11 devices. Sometimes a reboot also helps to get access to `df|grep storage|cut -d% -f2`.
Scripts can also be saved on `sdcard` and run there e.g. with: `ln -s /storage/44C4-1B1A/bstart .bashrc` or 'bash .bashrc`
