### ISSUE TITLE
Need answers

### ISSUE THREAD

**Issue by BrandonHall6518** [termux/termux-app#209]
Okay so I was messing around seeing what I could do and I so happened to stumble apon this weird command. Basically I put into termux was "reset termux" I got back "reset: unknown terminal type termux" then on a new line it prompted me with "Terminal type?" Now when I put something in it says "reset: unknown terminal type (what ever I put in)" now I was curious if this was a bug or there like actual terminal types.

**Comment by Quasic** [comment]
"reset" is the command to basically clear the screen. I'm not familiar with a parameter, and mine doesn't support one. Perhaps you've changed $TERM?
http://techtitbits.com/2010/10/resolving-unknown-unknown-terminal-type-error/
My $TERM is set to "xterm-256color" in case that helps.

When I get stuck, rebooting the phone has always gotten me out, but you can accidentally mess up files in storage and you can mess up things enough that you need to reinstall the app.

**Comment by BrandonHall6518** [comment]
Not quite and I do know what reset does but what I was trying to figure out was what terminal types are but thanks anyway :)

**Comment by fornwall** [comment]
The reset command takes an optinal argument the terminal type. There is no terminal type named "termux", which is why the error happens when running `reset termux`. Just running `reset`  without arguments will work.
