### ISSUE TITLE
Can't cd to /sdcard 

### ISSUE THREAD

**Issue by pr13260** [termux/termux-app#2090]
**Problem description**
When I tried to cd to /sdcard it said permission denied I have already did termux-setup-storage and also gave permission manually 

**Expected behavior**
2 days ago it was working fine today I upgraded to latest version by fdroid 

**Additional information**

* Termux application version:lastest by fdroid 
* Android OS version:11
* Device model: Samsung galaxy A21S

**Comment by Grimler91** [comment]
Try revoking and then re-enabling the storage permission in the app settings

**Comment by pr13260** [comment]
Thanks solver after a force stop ☺️☺️
