### ISSUE TITLE
Set 'paste as plain text' as default in termux

### ISSUE THREAD

**Issue by suhan-paradkar** [termux/termux-app#2091]
**Problem description**

Since paste as plain text is not implemented.. I face the following problems while using GitHub android app to copy a chunk of code and then execute it in termux

![Screenshot_2021-05-30-17-02-24-75.jpg](https://user-images.githubusercontent.com/76830230/120102473-d8068e80-c168-11eb-8d06-72e79fc25e7f.jpg)

This is due to the terminal taking the entire code chunk as a single command, neglecting the spaces.This happens in all shells... Not only in fish

![Screenshot_2021-05-30-17-10-33-36.jpg](https://user-images.githubusercontent.com/76830230/120102708-f751eb80-c169-11eb-8cb7-c90e9b0f5ceb.jpg)

**Steps to reproduce**

Open the github mobile app copy a chunk of code, paste it...and hit enter

**Expected behavior**

The terminal must take not it as a single command.

**Additional information**

* Termux application version:0.113
* Android OS version:9
* Device model:Oppo A12

**Comment by RalfWerner** [comment]
Your `curl` does not seem to work (should end with prompt).
I tested on two devices (Andriod 9/11 - each with `pkg up` before) and get:
```
[~/TMP]$ pkg show curl
Package: curl
Version: 7.77.0-2
Essential: yes
Maintainer: @termux
Installed-Size: 324 kB
Depends: libcurl (= 7.77.0-2)
Homepage: https://curl.se/
Download-Size: 157 kB
APT-Manual-Installed: yes
APT-Sources: https://termux.org/packages stable/main aarch64 Packages
Description: Command line tool for transferring data with URL syntax

[~/TMP]$ curl --location https://git.io/Jt68D>debian
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 16898  100 16898    0     0  12699      0  0:00:01  0:00:01 --:--:-- 12699
[~/TMP]$ ll debian
-rw------- 1 u0_a259 u0_a259 16898 May 30 14:31 debian
```

**Comment by agnostic-apollo** [comment]
Set `enable-bracketed-paste` to `off`. Check [here](https://github.com/termux/termux-app/issues/2078#issuecomment-846378918).

**Comment by agnostic-apollo** [comment]
It's likely not related to bracketed paste mode and that command won't affect `fish` shell. It might be due to github app not properly adding newlines. Check in text editor.

The below commands are working fine for github site for both `bash` with and without `enable-bracketed-paste` and `fish`. The difference with it `off` is that commands will run one after another and will have `PS1` before each.

```
curl --location git.io/Jt68d > debdroid
mv debdroid $PREFIX/bin/
rm $PREFIX/bin/debdroid
echo here
```

**Comment by suhan-paradkar** [comment]
Copying from Github website works fine.. but gives the error when github app is used

**Comment by agnostic-apollo** [comment]
Then not a termux-app issue. Report to github-app. You could also pipe the copied string to `xxd` 
or `cat -A` too see what's between the lines.
