### ISSUE TITLE
Software Directional Keys

### ISSUE THREAD

**Issue by HiDe-Techno-Tips** [termux/termux-app#2093]
**Feature description**

## Enable Gboard directional keys

The Software Directional Keys in [Gboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin) is disabled in Termux for some reason.

<img src="https://user-images.githubusercontent.com/61367380/120108281-1b212b80-c182-11eb-890c-0e43704cc43c.png" height=620px>

## Or Add Software Directional Keys above Android keyboard (Will be more convenient)
Examples from SSH Terminal of [Admin Hands](https://play.google.com/store/apps/details?id=com.arpaplus.adminhands):

<img src="https://user-images.githubusercontent.com/61367380/120107910-7520f180-c180-11eb-963b-09e963c06463.png" height=620px>

[Video preview](https://user-images.githubusercontent.com/61367380/120108006-e5c80e00-c180-11eb-8cd5-798395079e14.mp4) 

# Why its important
* Everyone using Termux will benefit from this feature as it enables users to access their command history easily. It is possible with hardware keyboard but, as said earlier the built in Software Directional Keys in [Gboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin) is disabled in Termux for some reason. 
* Also, there was no way to correct one single wrong character in a long command as the cursor position in Termux cannot be set without Directional Keys . This feature will solve this problem.
* Without this feature, nano text editor is useless in Termux untill you have a hardware keyboard because of the same reason as stated above.

**Reference implementation**
Does another app/terminal emulator have this feature?
Provide links to more background information.

Feature present in SSH Terminal of [Admin Hands](https://play.google.com/store/apps/details?id=com.arpaplus.adminhands) with the default keyboard.

**Comment by Indranil012** [comment]
https://wiki.termux.com/wiki/Touch_Keyboard

**Comment by agnostic-apollo** [comment]
The gboard directional keys will only work for `Text Input View`, not for terminal. For terminal, just add required arrow keys to extra keys. Check link above.

**Comment by HiDe-Techno-Tips** [comment]
Thanks for the reply. I successfully configued extra keys but look at the extra keys in this screenshot:
The `ij` you see is UP key, the `'` below it is DOWN, `IJ` is LEFT and `'n` is RIGHT. Why is this happening? How do I make them look like Directional Keys?

![Screenshot_20210531-074947](https://user-images.githubusercontent.com/61367380/120130894-dc708d00-c1e4-11eb-80ef-02b7089ff3cd.png)
