### ISSUE TITLE
volume-keys=volume not working

### ISSUE THREAD

**Issue by Indranil012** [termux/termux-app#2094]
**Problem description**

I added "volume-keys=volume" in termux.properties but the volume key is only working if i press volume_up + v

**Steps to reproduce**

Add This line to ~/.termux/termux.properties
volume-keys=volume

**Expected behavior**

To controll media volume in termux app

**Additional information**

* Termux application version: 0.113
* Android OS version: 10
* Device model: Poco m2 reloaded (shiva)

If you need log please inform me. Thanks

**Comment by Indranil012** [comment]
It's fixed don't know why it wasn't working

**Comment by agnostic-apollo** [comment]
You need to run `termux-reload-settings` after changing settings. Some settings require termux app restart.

https://wiki.termux.com/wiki/Terminal_Settings
