### ISSUE TITLE
Termux PREFIX collides with Node/nvm PREFIX

### ISSUE THREAD

**Issue by GameKyuubi** [termux/termux-app#2096]
**Problem description**

[Using `nvm` to change node versions is impossible because nvm requires PREFIX all to itself but so does Termux.](https://github.com/nvm-sh/nvm/issues/1645)  Unsetting PREFIX breaks Termux, but leaving PREFIX set breaks nvm, which means the only node version you can use is from apt/pkg which is not sufficient.  Nvm is pretty unanimously what you want to use to switch Node versions so it's a bit of a problem.

**Steps to reproduce**

```
$ touch .bashrc
$ curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
$ export NVM_DIR="$HOME/.nvm"
$ [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
$ [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
$ nvm install 10  # install node v10
```
gives
```
bash: /data/data/com.termux/files/home/.nvm/versions/node/v10.24.1/bin/node: No such file or directory
version is required
nvm is not compatible with the "PREFIX" environment variable: currently set to "/data/data/com.termux/files/usr"
Run `unset PREFIX` to unset it.
```
of course, it's actually right there
```
$ ls -la .nvm/versions/node/v10.24.1/bin/node
-rwx------ 1 u0_a240 u0_a240 37453792 Apr  6 06:35 .nvm/versions/node/v10.24.1/bin/node
```
But it can't be run, even if you follow nvm's instructions to unset PREFIX.

**Expected behavior**

to be able to use nvm to change between functioning versions of node.

**Additional information**

* Termux application version: 0.101
* Android OS version: 9
* Device model: MotoG6

**Comment by Yonle** [comment]
Well, I confirm you can only able to run any node bins from nvm on proot. Also it's symlink issue (Or idk yet). You can also run it by using qemu-user-aarch64 (I didn't test it yet) but i didn't sure it'll works.

**Comment by agnostic-apollo** [comment]
Yeah, proot was what I was about to suggest. I don't use it myself, but that should solve the issue. `PREFIX` can't be renamed in termux at this point. Termux packages including `termux-tools` and scripts of termux users rely on it. Changing it would break a lot, so it's not possible.

`grep -RI '$PREFIX' "$PREFIX"`
