### ISSUE TITLE
Can't install from F-Droid

### ISSUE THREAD

**Issue by GameKyuubi** [termux/termux-app#2097]
**Problem description**

Installing 0.113, 0.112, or 0.111 from F-Droid gives a `Failed to install due to an unknown error` message and does not install.

**Steps to reproduce**

uninstall google play store version, wiping ALL data.  go to F-Droid, download/install 0.111, 0.112, or 0.113.

**Expected behavior**

no error, seamless install like play store version

**Additional information**

* Termux application version: --
* Android OS version: 9
* Device model:  MotoG6

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-app#installation

**Comment by GameKyuubi** [comment]
@agnostic-apollo Is there anything else to be done other than uninstall the play store version?  I don't see anything else.

**Comment by GameKyuubi** [comment]
Aha, found the issue in the `uninstall` section.  Thanks!
