### ISSUE TITLE
SSH doesn't work on 64-bit Android

### ISSUE THREAD

**Issue by Nebucatnetzer** [termux/termux-app#21]
I'm trying to generate ssh keys but I'm getting this error. 

CANNOT LINK EXECUTABLE DEPENDENCIES: "libcrypto.so" is 32-bit instead of 64-bit

**Comment by fornwall** [comment]
Hi, see [CANNOT LINK EXECUTABLE under common problems](https://github.com/termux/termux-packages/wiki/Common-problems#cannot-link-executable-cannot-locate-symbol--referenced-by-) and re-open this issue if the problem still remains (or you think the linked information can be made clearer)!

**Comment by Nebucatnetzer** [comment]
Great thank you haven't seen that yet works like a charm now :)
May I suggest that you add a link to the help section on the website?
I thought it might be a common problem but I couldn't see  a FAQ section or something similar.

**Comment by fornwall** [comment]
Great that it works for you now!

I'm experimenting with a wiki/help page system now, will link to it soon to make it discoverable!
