### ISSUE TITLE
dns seems forbidden

### ISSUE THREAD

**Issue by xoba** [termux/termux-app#210]
seems like i have same issue as #141, and here's a simple program that reproduces it:

```go
package main

import (
	"io"
	"log"
	"net/http"
	"os"
)

func main() {
	resp, err := http.Get("https://google.com")
	if err != nil {
		log.Printf("oops: %v", err)
		return
	}
	defer resp.Body.Close()
	io.Copy(os.Stdout, resp.Body)
}
```

the error states that udp connection on port 53 was refused.

**Comment by fornwall** [comment]
@xoba Thanks for the test case!

It works for me when testing on a Nexus 6p running Android 7.1. Which device and Android version do you run on?

Anyone else here who can test the above program?

**Comment by fornwall** [comment]
@xoba To be sure, run `apt update && apt upgrade` to ensure that you are running latest package versions before trying to compile again.

If the problem remains, what does `dpkg --print-architecture` output?

**Comment by xoba** [comment]
`dpkg --print-architecture` outputs "aarch64".

ran the update and upgrade, seems i was already up-to-date

**Comment by Neo-Oli** [comment]
I tested it on my Xperia X (Android 6.0.1, aarch64) and it seems to work as well.

**Comment by xoba** [comment]
i am running huawei nexus 6p running android 7.0, seems 7.1.1 is available, will update now.

btw, i compiled this on ubuntu amd64 as follows:

```
GOARCH=arm64 go build test.go
```

then from termux i scp'd `test` binary over and ran as `./test`

**Comment by xoba** [comment]
are there any special permissions required for dns port 53 access on android? since other network stuff seems to work. i'm wondering if go language is making direct port 53 network calls (udp), whereas other apps might proxy through the android o/s? might make a difference permission-wise? thanks!

**Comment by Neo-Oli** [comment]
Can confirm, compiling on Ubuntu and running on Termux produces this error. 
`2016/12/08 12:37:22 oops: Get https://google.com: dial tcp: lookup google.com on [::1]:53: read udp [::1]:58085->[::1]:53: read: connection refused`

**Comment by xoba** [comment]
i tried compiling on termux (instead of ubuntu amd64) with go1.7.4.linux-armv6l.tar.gz (from https://golang.org/dl/), but running go/bin/go said "file doesn't exist", whereas it clearly did exist; weird. could it be that armv6l isn't the right one for huawei 6p?

**Comment by Neo-Oli** [comment]
Is there a reason you don't install golang from the repository?
`apt install golang`

**Comment by xoba** [comment]
i tried that, got an error during `apt` process, some http request failed. i will try again

**Comment by xoba** [comment]
ran `apt install golang` successfully this time, then `go run test.go` and `go build test.go` worked like a charm! no more dns/port-53 error. any idea why it works now? maybe something to do with cgo on android arm vs ubuntu-compiled is pure go? maybe now go on android is using android o/s as dns proxy? just wondering. thanks!

**Comment by fornwall** [comment]
@xoba Sorry for the late reply, but indeed I think the issue is that on Android you need to link to the libc resolver for it to work, which statically compared binaries from ubuntu does not.
