### ISSUE TITLE
PACKAGES ARE NOT CHANGED

### ISSUE THREAD

**Issue by pr13260** [termux/termux-app#2100]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:0.113
* Android OS version:11
* Device model: Samsung galaxy A21S

**Comment by pr13260** [comment]
[*] Default repositories selected
    Changing main repository                               [*] Running apt update
Hit:2 https://grimler.se/game-packages-24 games InRelease  Hit:3 https://grimler.se/science-packages-24 science InRelease                                                        Ign:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease        Ign:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease        Ign:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease
Err:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease
  Connection failed [IP: 172.67.212.200 443]
Reading package lists... Done                              Building dependency tree... Done
All packages are up to date.                               W: Failed to fetch https://termux.org/packages/dists/stable/InRelease  Connection failed [IP: 172.67.212.200 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Grimler91** [comment]
Seems like the ipfs mirror is down right now, so try another mirror

**Comment by pr13260** [comment]
> Seems like the ipfs mirror is down right now, so try another mirror

Booh seems like almost all are down first bintray then ipfs 

Btw thanks I would try out
For now I am closing this issue 😊😊
