### ISSUE TITLE
SEEMS GRIMLER MIRROR ALSO DOWN

### ISSUE THREAD

**Issue by pr13260** [termux/termux-app#2102]
**Problem description**
apt update if giving error

**Steps to reproduce**
3 mirror are down 

**Additional information**

* Termux application version:0.113
* Android OS version:11
* Device model: Samsung galaxy A21S

**ERROR LOG**
~ $ apt update
Hit:2 https://grimler.se/game-packages-24 games InRelease
Hit:3 https://grimler.se/science-packages-24 science InRelease
Ign:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease
Ign:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease
Ign:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease
Ign:1 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease
Ign:4 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable Release
Ign:4 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable Release
Ign:4 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable Release
Err:4 https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable Release
  Connection failed [IP: 172.67.212.200 443]
Reading package lists... Done
E: The repository 'https://termux.org/packages stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
~ $

**Comment by Grimler91** [comment]
Does not seem like you have changed anything compared to be previous output you posted? 

In any case, termux.org/packages now point to another mirror so it should work, please try again

**Comment by Yonle** [comment]
Well. It's recommended to install with `pkg` in this cases right now. 

Do `pkg install <package>` for installing package.
