### ISSUE TITLE
Android 6.0 Can Be Compatible Again?

### ISSUE THREAD

**Issue by Skyler-X670** [termux/termux-app#2103]
can the latest version of Termux be compatible with the **Android 6.0** version?

**Comment by WMCB-Tech** [comment]
No and it will never be, see https://github.com/termux/termux-packages/issues/4467

***

Maintaining older Android versions would require more people to maintain it, you could for the Termux Repository and build packages that would support these Android versions

**Comment by xeffyr** [comment]
We no longer work on Android 5.0 and 6.0 and there is a reason behind:
* It is not possible to maintain package repositories for both Android 5.0 and 6.0 at same time.
* Devs do not have devices with such old Android version. Maybe someone from https://github.com/orgs/termux/people still have such device, but these people do not work on Termux app development.
