### ISSUE TITLE
[Bug] Termux packages not working under SU

### ISSUE THREAD

**Issue by ghost** [termux/termux-app#211]
When I am using root with the su command, it seems that none of the add-on packages installed by apt-get are found.  For example:

su
root@android:/ # openssl
sh: openssl: not found
127|root@android:/ #

------

When I do this NOT as root (standard user) it works:

openssl
OpenSSL>

**Comment by Nedgeva** [comment]
Same here.

**Comment by hackel** [comment]
Why would you expect them to work?  First, su launches the /system/bin/sh shell automatically.  Second, you need to update your PATH to point to the binaries.  Third, you need to export the shared library path.  I created the following script in `/su/bin/bash`:
```bash
#!/system/bin/sh

export HOME=/su/root
export PATH=$PATH:/data/data/com.termux/files/usr/bin
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib exec /data/data/com.termux/files/usr/bin/bash --init-file /su/root/.bashrc
```
Now I just have to remember to run "su -c bash" instead of just "su".  Certainly not ideal, but it gets the job done.  You can add it as an alias in your (Termux user) .bashrc: `alias su='su -c bash'`.

**Comment by gerroon** [comment]
@hackel 

I do not understand your script. Do you mind expanbding on it a bit?


How come you are able to create a folder like "/su/root" on the system? Is this an absolute path in termux or in the nadroid system?

**Comment by hackel** [comment]
@gerroon This is created by SuperSU.  I believe it's bind-mounted, and actually exists on the data partition.  It may not exist for other superuser variants.

**Comment by sm4rk0** [comment]
Duplicate of #61 ?

**Comment by pill11** [comment]
/su/root does not exist on my phone.

**Comment by pill11** [comment]
@hackel i getting this error

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": library "libandroid-support.so" not found
Aborted
/su/bin/bash[7]: --init-file: not found

**Comment by parashghosh** [comment]
Any video tutorial on how to solve this?

**Comment by cad1994** [comment]
Same problem, i feel very limited by this problem, i tried to send the commands to any folder about bin/su created in my phone, the command is only found in one but when i run the command i have this error "libandroid-ncurtils.so needed", please to the developer help in this

**Comment by eternalodball** [comment]
https://github.com/cswl/tsu 
Git clone this and type 
cd tsu
python3 extract_usage.py
It should fix it mine worked🙃

**Comment by intika** [comment]
copy the following to `/system/xbin/tsu` then run `chmod 755 /system/xbin/tsu` 

to use it, on the terminal after "su" run "tsu"

```
#!/system/bin/sh

export PATH=$PATH:/data/data/com.termux/files/usr/bin
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib 
export HOME=/data/data/com.termux/files/home 

exec sh
```
