### ISSUE TITLE
Can't update packages

### ISSUE THREAD

**Issue by priyankavarun** [termux/termux-app#2115]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:0.73
* Android OS version:6.0.1
* Device model:vivo1603
![Screenshot_20210606_174027](https://user-images.githubusercontent.com/85468481/120952560-f2dc9280-c768-11eb-8fb6-e387654b219d.png)
![Screenshot_20210606_173744](https://user-images.githubusercontent.com/85468481/120952573-fa03a080-c768-11eb-86ad-f9e2c2785223.png)

**Comment by agnostic-apollo** [comment]
You need to use the following mirrors for science, game and root repos for android-5/6.

https://github.com/termux/science-packages-21-bin
https://github.com/termux/game-packages-21-bin
https://github.com/termux/termux-root-packages-21-bin

You can manually edit the files under `$PREFIX/etc/apt/sources.list.d` with `nano` command to update the urls. Then run `apt update`.
