### ISSUE TITLE
Weird question when pkg upgrade

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#2116]
**Problem description**
First: Recently I changes the repo due to the required change of the new repo server.
Now I did `apt update` and then `apt upgrade`.
Then this question appeared:

````*] Default repositories selected
    Changing main repository
[*] Running apt update
Hit:1 https://grimler.se/game-packages-24 games InRelease
Hit:3 https://grimler.se/termux-root-packages-24 root InRelease
Get:4 https://grimler.se/science-packages-24 science InRelease [13.3 kB]
Get:2 https://packages.termux.org/apt/termux-main stable InRelease [14.0 kB]
E: Repository 'https://grimler.se/science-packages-24 science InRelease' changed its 'Origin' value from 'science-packages-24 science' to 'termux-science science'
E: Repository 'https://grimler.se/science-packages-24 science InRelease' changed its 'Label' value from 'science-packages-24 science' to 'science-packages science'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N] 
````
I answered 'y' but the question re-appeared and again.
So then I aborted with Ctrl+C and changed repository again by `termux-change-repo ` and set it to Main => Hosted to grimler.se.
Then it worked, but I had to reinstall an update (nmap) manually by `apt install nmap` and then `apt update` reported that all was up to date.

But another thing is missing: Apache 2.4.48. Not very important, but other platforms (homebrew on macOS or apt on 'real' desktop Linux) install this version. Normally Termux is rather early with new versions (e.g. PHP 8.0.6, like the Homebrew version in macOS) but Termux sticks to 2.4.46.
Am I doing wrong and missing other (more important) updates ?

**Additional information**

* Termux application version: 0.113
* Android OS version: Oxygen OS 10.3.11 stock ROM
* Device model: Oneplus 6

**Comment by xeffyr** [comment]
Type "y" and continue.

https://github.com/termux/termux-packages/issues/6726 \-\-\> `If you get E: Repository .. changed its .. value from .. to ..`:
> Package manager can show you a notification with prompt which look like this one:
 E: Repository 'https://grimler.se/termux-root-packages-24 root InRelease' changed its 'Origin' value from 'Bintray' to 'termux-root-packages-24 root'
 E: Repository 'https://grimler.se/termux-root-packages-24 root InRelease' changed its 'Label' value from 'Bintray' to 'termux-root-packages-24 root'
 N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
 Do you want to accept these changes and continue updating from this repository? [y/N] 
It is completely normal. Answer "yes" to this prompt. It will be shown only once per repository, so package manager will ask you to confirm for game-repo, science-repo, etc separately but you will need to confirm them only one time.

**Comment by Grimler91** [comment]
> But another thing is missing: Apache 2.4.48

It was released only a week ago. No one has spent time on updating packages since then, and no one has opened a PR to update the package
