### ISSUE TITLE
system structure

### ISSUE THREAD

**Issue by PickaxeHit** [termux/termux-app#2117]
**Problem description**

My device is aarch64 supported. But in Termux it shows"armv8l", 
`~ $ uname -m`
`armv8l`
And when I tried to use "proot-distro"to login ubuntu, it shows my device is armhf when I use apt source to install packages.

**Additional information**

* Termux application version:0.113
* Android OS version: Android 11
* Device model:Redmi note 7 pro(aarch64)

**Comment by agnostic-apollo** [comment]
Use `dpkg --print-architecture`
