### ISSUE TITLE
No updates anymore after pkg update

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#2120]
An example:
Apache 2.4.48 is now released and PHP 8.0.7 as well, but pkg update does not mention them.
Not that those (minor) updates are that important for me, but it appears that the update mechanism is not working anymore.
I changed repository after I should because of bintray was down. I did that with `termux-change-repo` and after that I called `apt upgrade` and then a few new packages installed. 
But now no new packages installed. I use the 'default repository' of the 'main repositories'.
 
Should I use another repo ?

**Additional information**

* Termux application version: 0.113
* Android OS version: 10.5.11
* Device model: Oneplus 6

**Comment by suhan-paradkar** [comment]
> An example:
> Apache 2.4.48 is now released and PHP 8.0.7 as well, but pkg update does not mention them.
> Not that those (minor) updates are that important for me, but it appears that the update mechanism is not working anymore.
> I changed repository after I should do that with termux-change-repo and after that I called apt upgrade and then a few new packages installed.
> But now no new packages installed. I use the 'default repository' of the 'main repositories'.
> 
> Should I use another repo ?
> 
> **Additional information**
> 
> * Termux application version: 0.113
> * Android OS version: 10.5.11
> * Device model: Oneplus 6

That is because those aren't updated in termux-packages repository....

**Comment by freebrowser1** [comment]
> That is because those aren't updated in termux-packages repository....

What should I do then ?

I followed these instructions : https://github.com/termux/termux-app/issues/2067  selected all as instructed.

and got this 

````[*] Grimler's mirrors selected
    Changing main repository
    Changing game repository
    Changing root repository
    Changing science repository
[*] Running apt update
Hit:1 https://grimler.se/termux-packages-24 stable InRelease
Get:2 https://grimler.se/game-packages-24 games InRelease [15.5 kB]
Get:3 https://grimler.se/termux-root-packages-24 root InRelease [17.0 kB]
Hit:4 https://grimler.se/science-packages-24 science InRelease
Get:5 https://grimler.se/game-packages-24 games/stable aarch64 Packages [7662 B]
Get:6 https://grimler.se/termux-root-packages-24 root/stable aarch64 Packages [13.6 kB]
Get:7 https://grimler.se/termux-root-packages-24 root/stable all Packages [463 B]
Fetched 54.3 kB in 4s (13.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.````

**Comment by suhan-paradkar** [comment]
> What should I do then ?
You can either wait until someone pulls a PR to bump version or pull a PR yourself

**Comment by xeffyr** [comment]
@freebrowser1 New upstream versions aren't available immediately but instead only if Termux package maintainers have bumped the version/patches for this package. Reminding that Termux isn't Debian or something like and no one there works on package updates 24x7.

If you are curious what has been updated recently, see https://github.com/termux/termux-packages/commits/master.
