### ISSUE TITLE
hello please help me can't run ubuntu on termux

### ISSUE THREAD

**Issue by projectku970** [termux/termux-app#2123]
can't run ubuntu on termux

https://imgur.com/gallery/q39zDUJ

**Comment by WMCB-Tech** [comment]
Use Android Emulators with full linux features, such Android emulators are unsupported than AVD or Android x86 in Virtualbox

***

BTW, you might wanna use Windows Subsystem for Linux instead

**Comment by projectku970** [comment]
so what should i do i want to run this like on an android phone using my laptop using the msi app player or also called bluestacks, and actually i don't have an android phone and i want to use this bluestack to be similar to an android phone to give an example to subscribers I'm on youtube so I can run termux on bluestacks what's the solution please help me thank you

**Comment by WMCB-Tech** [comment]
The example is installing Android Virtual Device by Android Studio, Genymotion, or Android x86 in virtualbox
