### ISSUE TITLE
Termux v0.101 `terminal-transcript-rows=x" none

### ISSUE THREAD

**Issue by xb3b6** [termux/termux-app#2126]
I saw an update https://github.com/termux/termux-app/commit/0b4bbaf23d349e65b2f2c69b53c0a579cac92ddc
I updated Termux from f-droid to v0.101, applied the settings for the file "nano .termux/termux.properties>` terminal-transcript-rows = 10000` ", restarted Termux.  But nothing happened.  I checked '`for i in {1..2001};  do echo $ i;  done` 'and I get display of scroll lines from 3-2001

**Comment by agnostic-apollo** [comment]
Update to [`v0.114`](https://www.reddit.com/r/termux/comments/o09m66/dev_termux_v0114_release/).

**Comment by agnostic-apollo** [comment]
Moreover, with `terminal-transcript-rows = 10000`, running `for i in {1..2001}; do echo $ i; done` will obviously get you `1` to `~2000` lines. Do a for loop of `>10000` lines to see that limit is not the default `2000` anymore.

**Comment by xb3b6** [comment]
Sorry. 
 Everything is working. 
 There was a conflict of versions of Termux GP vs F-droid

**Comment by agnostic-apollo** [comment]
Cool.
