### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by AAMSK** [termux/termux-app#2128]
Err:4 https://dl.bintray.com/grimler/game-packages-21 games Release
  403  Forbidden

Err:5 https://dl.bintray.com/grimler/termux-root-packages-21 root Release
  403  Forbidden

Err:6 https://dl.bintray.com/grimler/science-packages-21 science Release
  403  Forbidden

E: The repository 'https://dl.bintray.com/grimler/game-packages-21 games Release' does not have a Release file.

N: Updating from such a repository can't be done securely, and is therefore disabled by default.

N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by agnostic-apollo** [comment]
Check [here](https://github.com/termux/termux-app/issues/2115#issuecomment-855544280).
