### ISSUE TITLE
Copy paste using keyboard

### ISSUE THREAD

**Issue by azclub-ltd** [termux/termux-app#2129]
We can just copy and paste something by long tap on termux ui. But to copy paste using hardware keyboard there definitely needs a feature.  It is necessary  for them who connect Hardware keyboard through OTG. In kali Linux we can copy and paste using Ctrl+shift+c and Ctrl+shift+v. And also(after update) when I try to select a line, it select the upper line of that line.. Hope that Dev will think about it.

**Comment by agnostic-apollo** [comment]
Duplicate of #1891.

>And also(after update) when I try to select a line, it select the upper line of that line.

Select how? Open another issue with a video showing the bug.
