### ISSUE TITLE
Termux cannot install in my Android 10 device I've downloaded it a couple of times from F-droid but it's not downloading only the Termux 101version works😔😔 

### ISSUE THREAD

**Issue by Mayor294** [termux/termux-app#2131]
Android 10

**Problem description**

@
**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application  #version:114
* Android OS version:10
* Device model:Tecno ld7

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-app#installation

**Comment by Aridlvory** [comment]
I had the same problem it has been resolved

- does your mobile satisfies all the condition? 

- First check if u have installed any of the plugins from playstore if so delete them

- delete the termux u had (backup it)

-  reinstall latest

**Comment by Mayor294** [comment]
It finally worked thanks alot ☺️☺️☺️...
I was using 101version of Termux maybe that's why my Metasploit wasn't working......

Pls does anyone know any package you can use to trace your phone using it's IMEI pls..my elder sisters phone got stolen so I decided to go back to old life in Termux
