### ISSUE TITLE
VNC Viewer

### ISSUE THREAD

**Issue by observerunion** [termux/termux-app#2132]
**Problem description**
--> So I Want to Clone Termux-Desktop on Termux When I Do It Asks Me For A VNCViewer On There So When I Install The VNC Viewer And Type In vncviewer My System Starts To Become Weird Then Corrupts Completely

**Steps to reproduce**
vncviewer

**Expected behavior**
 To Work Normally?

**Additional information**

* Termux application version: 0.113
* Android OS version:7.1.2
* Device model:j320fn

**Comment by xeffyr** [comment]
We don't have any "Termux-Desktop" repo under our organisation. Report issue to the correct repository as we're not fixing third-party projects.
