### ISSUE TITLE
MiXplorer - Open in terminal

### ISSUE THREAD

**Issue by xmha97** [termux/termux-app#2135]
Hi, I using Termux v0.114 on Android 7.1.1
The "Open in terminal" button on MiXplorer not working.
![Animation](https://user-images.githubusercontent.com/23485114/122626475-0e785f00-d0c0-11eb-8391-a88c027f1732.gif)

**Comment by agnostic-apollo** [comment]
It's as the error says, `executable` was [not passed](https://github.com/termux/termux-app/blob/v0.114/app/src/main/java/com/termux/app/RunCommandService.java#L101). Report to MiXplorer dev. It was working on older versions of Mixplorer, he must have broken something. It's not even working on termux `v0.113` and no changes have been made in `RunCommandService` related to this for many versions. And [`am` command](https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#top-command-with-am-startservice-command) works, so not a termux issue.
