### ISSUE TITLE
ls: cannot open directory '.': Permission denied

### ISSUE THREAD

**Issue by IWareQ** [termux/termux-app#2136]
**Problem description**
ls: cannot open directory '.': Permission denied

**Steps to reproduce**
cd /storage/emulated/0/Download/testPath 
see error

**Expected behavior**

**Additional information**
Before that, I had version 0.101, because I didn't know that google play doesn't update anymore, I updated to the latest version, and ls stopped working
* Termux application version: 0.114
* Android OS version: 10
* Device model: Redmi Note 8

**Comment by xeffyr** [comment]
Run `termux-setup-storage` or in any other way grant the storage access permission to Termux application.
