### ISSUE TITLE
extra-keys-style=none do not remove extra keys bar

### ISSUE THREAD

**Issue by vldmrrr** [termux/termux-app#2139]
**Problem description**

Added the following line to ~/.termux/termux.properties:
```extra-keys-style=none```
Issued comand termux-reload-settings, closed and reopened termux.
Expected extra keys bar to be hidden, but it was sill shown.

```
$ termux-info
Application version:
0.114
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.146 termux/termux-packages#2 SMP PREEMPT Thu Feb 4 17:08:34 CST 2021 aarch64 Android
Device manufacturer:
Planet
Device model:
Cosmo_Communicator
```

**Comment by dolunay1982** [comment]
termux-info Application version: 0.114 Packages CPU architecture: aarch64 Subscribed repositories: # sources.list deb https://packages.termux.org/apt/termux-main/ stable main # game-repo (sources.list.d/game.list) deb https://packages.termux.org/apt/termux-games games stable # science-repo (sources.list.d/science.list) deb https://packages.termux.org/apt/termux-science science stable Updatable packages: All packages up to date Android version: 9 Kernel build information: Linux localhost 4.4.146 termux/termux-packages#2 SMP PREEMPT Thu Feb 4 17:08:34 CST 2021 aarch64 Android Device manufacturer: Planet Device model: Cosmo_Communicator
