### ISSUE TITLE
Private Storage is only option to run Node.js

### ISSUE THREAD

**Issue by koopuluri** [termux/termux-app#214]
I've tried to do some node.js development and attempted to use termux to run the commands. Everything works fine when using Termux's private storage, but when I copied over all of my files to the Shared Internal Storage, I ran into the error: "maximum call stack size exceeded", and it failed to compile. 

I followed this blogpost: https://medium.freecodecamp.com/building-a-node-js-application-on-android-part-1-termux-vim-and-node-js-dfa90c28958f#.7h71s73jd, which ran into the same issue. 

What are the differences in functionality b/w the Shared Internal Storage vs. the Private Storage? 

Getting this to work in shared storage would be valuable because then I could edit the files through another app, and run them through Termux. Would love to help out, just don't know where to start. Any pointers would be appreciated.

**Comment by dontsave** [comment]
I've run into this issue also, and I'd love to know if there was a solution. npm install fails on shared storage, restricting node development to private storage. This forecloses the possibility of using an external application to make edits. Although I did notice that Termux implements the Storage Access Framework, there aren't any good editor apps that implement this feature. My device is rooted, and there are some editors that allow root mode, however this still causes problems as saving files in root mode changes ownership to root, causing permissions issues when executing node as the Termux user. The Termux Sudo solution posted in another thread also fails for commands like sudo npm start and sudo supervisor app.js.

Would love to hear if anyone has a good node workflow on Android that doesn't involve using a nix editor like vim or emacs.

**Comment by fornwall** [comment]
> Although I did notice that Termux implements the Storage Access Framework, there aren't any good editor apps that implement this feature.

With [Turbo Editor](https://play.google.com/store/apps/details?id=com.maskyn.fileeditor&hl=en) you can enable "Use the Storage Access Framework" from the right hand drawer!

**Comment by fornwall** [comment]
About differences between external storage and internal: external storage does not allow chmod to modify file attributes (to e.g. set executable permission or limit access from other users), perhaps that is why it doesn't work?

I'm closing this issue as it probably requires some larger work in the nodejs project itself (so an issue would need to be report against nodejs and worked on there).
