### ISSUE TITLE
[BUG] Termux  getting many errors in apt update/upgrade

### ISSUE THREAD

**Issue by skhrlx** [termux/termux-app#2143]
**Termux  getting many errors in pkg update/upgrade**

When I type "pkg update" or "pkg update" I am getting  a lot of errors, i dont make any change on the app, just downloaded from google play, >>>ONLY THIS<<<

![Screenshot_20210621-191534_Termux](https://user-images.githubusercontent.com/85849948/122837806-1f48f080-d2cb-11eb-89b5-0e2090255c1b.jpg)

**Additional information**

* Termux application version: 0.101 (I tried old versions too, and I'm getting the same errors)
* Android OS version: 9.0
* Device model: SM-G611MT

**Comment by agnostic-apollo** [comment]
Uninstall and download from F-Droid. Playstore is not supported currently.

https://github.com/termux/termux-app#Installation
