### ISSUE TITLE
Google Play's Termux app does *not* say "This app is deprecated!"

### ISSUE THREAD

**Issue by jaimet** [termux/termux-app#2144]
**Problem description**

According to https://github.com/termux/termux-packages/issues/6726:
"Do not use Termux app from Google Play. It is deprecated.

But there is nothing on the "main" app "page" to show or indicate that the Termux app on the Play Store is deprecated. (Please see screenshot) Yes, I realise that it is mentioned in the "About this app" page, but I think it would be a good idea to make this information more promiment.

**Steps to reproduce**

Search for the Termux app on the Google Play Store.

**Expected behavior**

When I search for Termux on the Play Store, I would like some indication that the Termux app on the Play Store is deprecated. NB: I do NOT suggest removing the app from the Play Store (because I have seen "Play Store Squatting" occur when other open source apps have done this - see https://play.google.com/store/apps/details?id=com.drunkdeveloper.location.sensor.radio.network.wifi.status for an example)

Perhaps it would be possible to rename the app from "Termux" to "Termux - now deprecated!" ?

**Additional information**

Hey, I've just realised: if you make it clearer that the app is deprecated, you might even cut down on the following "issue noise":

https://github.com/termux/termux-packages/issues/7025
https://github.com/termux/termux-packages/issues/7024
https://github.com/termux/termux-packages/issues/7023
https://github.com/termux/termux-packages/issues/7004
https://github.com/termux/termux-packages/issues/6997
etc
etc
etc

* Termux application version:
* Android OS version:
* Device model:

![Screenshot_20210622-091803](https://user-images.githubusercontent.com/8218065/122894026-c1ee8700-d33e-11eb-99a7-3f9c16b3163c.jpg)

**Comment by agnostic-apollo** [comment]
Look again thoroughly!

**Comment by xeffyr** [comment]
Already mentioned in app description.

![Screenshot_20210622-130951](https://user-images.githubusercontent.com/25881154/122906903-4e0ea780-d35b-11eb-90a1-2e603d3783c1.png)

Renaming the application, especially like "Termux - Now deprecated" may lead to deletion from Play Store by Google staff.
