### ISSUE TITLE
Where is Termux Settings?

### ISSUE THREAD

**Issue by angelog0** [termux/termux-app#2147]
In a changelog [here](https://github.com/termux/termux-app/releases/tag/v0.113), you wrote:

> [...] can also be enabled from `Termux Settings` -> `Termux` -> `Terminal I/O` -> `Soft Keyboard Enabled` toggle.

Where can one find `Termux Settings` and friends? I tried in device `Settings` -> `Apps` -> `Termux` but didn't find anything.

**Comment by agnostic-apollo** [comment]
`Long pressing terminal view` -> `More` -> `Settings` (like you do for copying text)

**Comment by angelog0** [comment]
Thanks!
