### ISSUE TITLE
CANNOT LINK EXECUTABLE "cmake":

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-app#2148]
Android 11
Termux -V 0.114
Every time I am getting error like this...
When I export LD LIBRARY PATH/system/vendor/lib64/".  Getting error like

CANNOT LINK EXECUTABLE "cmake": cannot locate symbol "_ZN4Json19StreamWriterBuilderC1Ev" referenced by "/data/data/com.termux/files/usr/bin/cmake"...

apt update && apt upgrade -y. (done)
After that same issues happen
without export LD LIBRARY PATH system vendor lib64
Not happen issue
But with LD LIBRARY PATH cmake error again..

Please give me solution...
![Screenshot_2021-06-24-09-44-16-070_com termux](https://user-images.githubusercontent.com/72664192/123202167-b7182b80-d4d1-11eb-851d-b85e8d7e07ab.jpg)

![Screenshot_2021-06-24-09-52-45-048_com termux](https://user-images.githubusercontent.com/72664192/123202292-f6df1300-d4d1-11eb-846d-7d3ac3535e80.jpg)

**Comment by agnostic-apollo** [comment]
`cmake` provided by termux is meant to be linked with termux libraries under `$PREFIX/lib` and not with android libraries under `/system`. Termux does not even use `LD_LIBRARY_PATH` anymore and it should normally be unset, since `DT_RUNPATH` is used instead. Do not set `LD_LIBRARY_PATH` to android libraries only and attempt to run termux binaries, they will fail. If you must set it for some reason, use `LD_LIBRARY_PATH="$PREFIX/lib:/system/lib64:/system/lib"`. When running android binaries under `/system`, you may have to remove the termux lib path.

https://wiki.termux.com/wiki/Differences_from_Linux

**Comment by Saikatsaha1996** [comment]
compatibility with Android OS and to remove the need to maintain custom toolchains we compile all our packages with the Android NDK. The resulting binaries are linked against the Bionic libc (files libc.so, libm.so, libdl.so from /system/lib or /system/lib64).

Use of the libc provided by Android and FHS incompatibility make it impossible to execute native packages copied from Linux distributions:

Dynamically linked programs will not run because the linker is expected in a nonexistent location (/lib) and libc ABI does not match


I understand it...

But I need more help...
When I input export LD_LIBRARY_PATH="$PREFIX/lib:/system/lib64:/system/lib"

Than I am trying to cmake ..

Showing OpenCL library not found...
![Screenshot_2021-06-24-12-41-49-164_com termux](https://user-images.githubusercontent.com/72664192/123219316-63660c00-d4ea-11eb-9fc5-c3f20a321481.jpg)

**Comment by Grimler91** [comment]
@Saikatsaha1996 this is not a termux issue, issues when trying to use system libraries is out of scope here. 

You probably want to investigate what the cmake module actually checks for, to see why it fails, and then check various other resources online for how to properly use opencl on android.

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 this is not a termux issue, issues when trying to use system libraries is out of scope here.
> 
> You probably want to investigate what the cmake module actually checks for, to see why it fails, and then check various other resources online for how to properly use opencl on android.

Actually my libOenCL.so available in system/vendor/lib64

**Comment by xeffyr** [comment]
@Saikatsaha1996 You need headers as well, not just library (.so) file.

**Comment by Saikatsaha1996** [comment]
export LD_LIBRARY_PATH="$PREFIX/lib:/system/lib64:/system/lib"
export CFLAGS="-I$HOME/OpenCL-Headers"
export LDFLAGS="-L/system/vendor/lib64"

After that same problem could not find OpenCL library
![Screenshot_2021-06-24-15-16-11-397_com termux](https://user-images.githubusercontent.com/72664192/123242115-56074c80-d4ff-11eb-834e-ac650080926b.jpg)
