### ISSUE TITLE
Termux loading .profile on failsafe

### ISSUE THREAD

**Issue by h0m3** [termux/termux-app#2150]
**Problem description**

Termux app is running ~/.profile even on failsafe mode making the environment unrecoverable.

![Screenshot_20210629-070519_Termux](https://user-images.githubusercontent.com/3425853/123779368-79881980-d8a8-11eb-9f17-a02ab2814088.jpg)

**Steps to reproduce**

Create a broken ~/.profile like adding exit and try to run Failsafe mode.

**Expected behavior**

Beign dumped into a failsafe shell to recover the environment

**Additional information**

* Termux application version: 0.101
* Android OS version: Android 11
* Device model: Samsung Galaxy Tab S7

**Comment by xeffyr** [comment]
That's actually issue of `/system/bin/sh` which is being used as "failsafe" shell.

Best thing we can do here is either not set `HOME` variable for failsafe shell or set it to some system directory like `/` or `/data`.

**Comment by agnostic-apollo** [comment]
So i removed prefixing `-` for arg1 for failsafe session so that it's not considered a login shell as per [this](https://unix.stackexchange.com/a/228940). That's working for android 7 and 11 (maybe it was avd 10), both use `toybox`. Should work for others too hopefully.

**Comment by xeffyr** [comment]
@agnostic-apollo Won't it try to load ~/.mkshrc then?

**Comment by agnostic-apollo** [comment]
@xeffyr That should not be an issue normally. `mksh` [does load `.mkshrc`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:external/mksh/src/main.c;l=663) but for android its set to [`/system/etc/mkshrc`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:external/mksh/Android.bp;l=114) even though its default is [`~/.mkshrc`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:external/mksh/src/main.c;l=41).

I tried with an invalid `/system/etc/mkshrc` and it failed the failsafe on my rooted android 7, but an invalid `~/.mkshrc` didn't cause failure. So as long as users are not modifying the former, it should not be an issue. You can confirm this with:

```
cat /system/bin/sh | strings | grep -i mkshrc
${ENV:-/system/etc/mkshrc}
```
