### ISSUE TITLE
Automatically executing shell scripts in the downloads directory (public directories) using Termux>=0.109 from an android app

### ISSUE THREAD

**Issue by AnnieJohnson25** [termux/termux-app#2151]
Hi @xeffyr ,

@sorna-meena and I are developing an app, that automatically executes a shell script in Termux when the user clicks a button. So, this external app (our app) places the script in the downloads folder (as our app can access only public directories) and we use the following code to run the shell script.

```
Intent intent = new Intent();
intent.setClassName("com.termux", "com.termux.app.RunCommandService");
intent.setAction("com.termux.RUN_COMMAND");
intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/home/storage/downloads/Folder/ShellScript.sh");
```

The ShellScript.sh file only has read write permissions and no execute permissions in the downloads directory. 

Trials:

1) Version: Termux 0.101 (Downloaded from Google Play)
    Android 11, API 30

The above code (external app) perfectly runs the shell script in a new Termux session although this file has no execute permissions.

2) Version: Termux 0.114 (Downloaded from F-droid)
    Android 11, API 30

However, we needed to make use of RUN_COMMAND_SERVICE.EXTRA_PENDING_INTENT in our app as we are implementing an IntentService to wait for an intent to complete after which we start a PendingIntent. This required us to move to Termux having a version>=0.109 that we downloaded from F-droid. We observed that the ShellScript.sh file did not have execute permissions and the above code did not run the shell script. Instead, we got permission denied. We got the following error:

## Report Info

**User Action**: `PLUGIN_EXECUTION_COMMAND`
**Sender**: `RunCommandService`
**Report Timestamp**: `2021-06-29 11:44:25 UTC`
##

## RUN_COMMAND Execution Intent Command

**Previous State**: `Pre-Execution`
**Current State**: `Failed`
**Executable**: `/storage/emulated/0/Download/Folder/ShellScript.sh`
**Arguments:** -
**Working Directory**: -
**inBackground**: `false`
**isFailsafe**: `false`
**Session Action**: -
**isPluginExecutionCommand**: `true`
**Pending Intent Creator:** - 

**Stdout**: -

**Stderr**: -

**Exit Code**: - 

**Err Code**: `2`
**Errmsg:**
The executable regular file at path is not executable. Permission Denied.
Executable Absolute Path: "/storage/emulated/0/Download/Folder/ShellScript.sh"

### StackTraces

`-`
##

### Plugin API Help

Visit https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent for more info on RUN_COMMAND Intent usage.
##

## Termux App Info

**APP_NAME**: `Termux`
**PACKAGE_NAME**: `com.termux`
**VERSION_NAME**: `0.114`
**VERSION_CODE**: `114`
**TARGET_SDK**: `28`
**IS_DEBUG_BUILD**: `false`
**APK_RELEASE**: `F-Droid`
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`
##

### Software

**OS_VERSION**: `5.4.61-android11-0-00791-gbad091cc4bf3-ab6833933`
**SDK_INT**: `30`
**RELEASE**: `11`
**ID**: `RSR1.201013.001`
**DISPLAY**: `RSR1.201013.001`
**INCREMENTAL**: `6903271`
**SECURITY_PATCH**: `2020-09-05`
**IS_DEBUGGABLE**: `0`
**IS_TREBLE_ENABLED**: `true`
**TYPE**: `user`
**TAGS**: `release-keys` 

### Hardware

**MANUFACTURER**: `Google`
**BRAND**: `google`
**MODEL**: `sdk_gphone_x86`
**PRODUCT**: `sdk_gphone_x86`
**BOARD**: `goldfish_x86`
**HARDWARE**: `ranchu`
**DEVICE**: `generic_x86_arm`
**SUPPORTED_ABIS**: `x86, armeabi-v7a, armeabi`
##

Alternate solutions we tried:

1) We could not give execute permissions to any files in the downloads directory. 

2) We could not use a mv, cp or chmod command in the external app we are making so that we can automatically first move the shell script to another directory (home), then give execute permissions and then run the script on Termux.

**We were wondering if there is a flag that we can set in order to automatically execute shell scripts in the downloads directory like how it was possible in the Termux 0.101 version? Any advice/ suggestions are appreciated.**

Thanks in advance!

**Comment by xeffyr** [comment]
How to run shell script in directory with noexec:
```
bash /storage/emulated/0/Downloads/yourscript.sh
```

\- hopefully this example will give you an idea how you can adjust your code to be able run scripts located in shared storage.

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#RUN_COMMAND-Intent-Command-Extras

**Comment by AnnieJohnson25** [comment]
Thank you for your quick response!

We tried using the bash command in our app in the following ways:

1)

`Intent intent = new Intent();
intent.setClassName("com.termux", "com.termux.app.RunCommandService");
intent.setAction("com.termux.RUN_COMMAND");
intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/home/storage/downloads/Folder/ShellScript.sh");
intent.putExtra("com.termux.RUN_COMMAND_ARGUMENTS", new String[]{"bash"});`

2)

`Intent intent = new Intent();
intent.setClassName("com.termux", "com.termux.app.RunCommandService");
intent.setAction("com.termux.RUN_COMMAND");
intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/home/storage/downloads/Folder/ShellScript.sh");
intent.putExtra("com.termux.RUN_COMMAND_ARGUMENTS", new String[]{"/data/data/com.termux/files/usr/bin/bash"});`

3)

`Intent intent = new Intent();
intent.setClassName("com.termux", "com.termux.app.RunCommandService");
intent.setAction("com.termux.RUN_COMMAND");
intent.putExtra("com.termux.RUN_COMMAND_PATH", "bash /data/data/com.termux/files/home/storage/downloads/Folder/ShellScript.sh");`

I think the first 2 approaches are still executing ./ShellScript.sh instead of bash ShellScript.sh so we still get Permission denied.

The 3rd approach gives no path such file or directory "bash /data/data/com.termux/files/home/storage/downloads/Folder/ShellScript.sh"

How should we be executing a bash command with com.termux.RUN_COMMAND?

**Comment by xeffyr** [comment]
All your 3 variants are wrong.

Executable must be `bash` and argument is your script.

```
intent.setClassName("com.termux", "com.termux.app.RunCommandService");
intent.setAction("com.termux.RUN_COMMAND");
intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/usr/bin/bash");
intent.putExtra("com.termux.RUN_COMMAND_ARGUMENTS", new String[]{"/storage/emulated/0/Downloads/Folder/ShellScript.sh"});
intent.putExtra("com.termux.RUN_COMMAND_WORKDIR", "/data/data/com.termux/files/home");
intent.putExtra("com.termux.RUN_COMMAND_BACKGROUND", false);
intent.putExtra("com.termux.RUN_COMMAND_SESSION_ACTION", "0");
startService(intent);
```

**Comment by AnnieJohnson25** [comment]
Thanks you so much! This works perfectly!

**Comment by tathastu871** [comment]
> All your 3 variants are wrong.
> 
> Executable must be `bash` and argument is your script.
> 
> ```
> intent.setClassName("com.termux", "com.termux.app.RunCommandService");
> intent.setAction("com.termux.RUN_COMMAND");
> intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/usr/bin/bash");
> intent.putExtra("com.termux.RUN_COMMAND_ARGUMENTS", new String[]{"/storage/emulated/0/Downloads/Folder/ShellScript.sh"});
> intent.putExtra("com.termux.RUN_COMMAND_WORKDIR", "/data/data/com.termux/files/home");
> intent.putExtra("com.termux.RUN_COMMAND_BACKGROUND", false);
> intent.putExtra("com.termux.RUN_COMMAND_SESSION_ACTION", "0");
> startService(intent);
> ```

can someone provide adb am star intent command for this.
after installint fresh termux i want to execute certain command in termux without opening termux directly from adb pc
