### ISSUE TITLE
Can't install any packages

### ISSUE THREAD

**Issue by amiria703** [termux/termux-app#2152]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: Latest
* Android OS version: 11 LineageOS 18.1
* Device model: Sony Xperia Z1

`$ pkg update
The program pkg is not installed. Install it by executing:
 pkg install termux-tools
$ pkg install termux-tools
The program pkg is not installed. Install it by executing:
 pkg install termux-tools`

The termux got broken don't know what causes the issue

**Comment by agnostic-apollo** [comment]
For `pkg`, you can run

```
apt update
apt install termux-tools
```

but if you have broken other stuff, then run `termux-reset` or start a fail safe session and run `rm -rf /data/data/com.termux/files/usr` and restart termux. Or just reinstall termux.

https://wiki.termux.com/wiki/Recover_a_broken_environment

And latest version is not a version. Is it the one for play store or F-Droid? Install from F-Droid.

https://github.com/termux/termux-app#installation
