### ISSUE TITLE
Termux on Android 12 randomly stops all processes in background

### ISSUE THREAD

**Issue by KSPAtlas** [termux/termux-app#2157]
**Problem description**

When on Android 12, Termux closes while running in the background. It doesn't crash, it gives you a "process completed" message.
**Steps to reproduce**

1. Install the Android 12 beta 2.1
2. Run a program (for example a Proot) that involves running in the background
**Expected behavior**

It would continue to run.
**Additional information**
This doesn't happen instantly, it takes about a minute to happen.
* Termux application version: 0.114
* Android OS version: Android 12 beta 2.1
* Device model: Google Pixel 3 "Blueline"

**Comment by Kaank2006** [comment]
I'd advise you to refer to dontkillmyapp.com
Even if wakelock is acquired some vendors just have some extra "battery optimisations"

**Comment by KSPAtlas** [comment]
This is on an AOSP (cause pixel) and I've disabled battery optimization. As I said, it says "Process completed" instead of crashing

**Comment by KSPAtlas** [comment]
I've renamed the issue to make it better reflect the issue

**Comment by agnostic-apollo** [comment]
Related #2015

Processes and apps don't crash, they are killed by android.

**Comment by KSPAtlas** [comment]
Doesn't Termux run in a sandbox?

**Comment by agnostic-apollo** [comment]
Termux app process does and so does (bash) shell and its child processes including background processes, but not demonized processes. Check [here](https://github.com/termux/termux-app/issues/2015#issuecomment-860492160).
