### ISSUE TITLE
How to change package name without error?

### ISSUE THREAD

**Issue by leo9595** [termux/termux-app#2160]
Hi, I'm new to android development and I'm editing the termux script for a study. However, when I change the package name "com.termux" to anything else, it doesn't work.

Can anyone tell me what's stopping me? When compiling I don't have any error, the error I get is when I open the app on android, I get the following error: "failed to get context from package "com.termux". This can be because the app package is not installed app or has a different APK signature. Check the installation instructions at: https://github.com/termux/termux-app for more details."

I've done everything in my power, can you give me an idea how to solve it?

**Comment by xeffyr** [comment]
Application package name is not easily changeable. Every .deb file installable inside Termux is bound to application package name, so path
```
/data/data/com.termux/files/usr
```
will exist. For same reason Termux doesn't support installations for secondary device accounts.

Also before installing the modified APK you need to completely uninstall the original Termux application and add-ons Termux:API, Termux:Styling, Termux:Boot and others.

**Comment by agnostic-apollo** [comment]
That error would have been thrown when [this](https://github.com/termux/termux-app/blob/v0.116/app/src/main/java/com/termux/app/TermuxActivity.java#L194) is called and actually thrown via [`PackageUtils`](https://github.com/termux/termux-app/blob/v0.116/termux-shared/src/main/java/com/termux/shared/packages/PackageUtils.java#L41).

- Check [TermuxConstants](https://github.com/termux/termux-app/blob/v0.116/termux-shared/src/main/java/com/termux/shared/termux/TermuxConstants.java#L177) javadocs for instructions on what changes to make in the app to change package name.
- You also need to recompile bootstrap zip for the new package name. Check [here](https://github.com/termux/termux-app/issues/1983) and [here](https://github.com/termux/termux-app/issues/2081#issuecomment-865280111).

**Comment by leo9595** [comment]
> > Failed to get package context for the "com.termux" package. This may be because the app package is not installed or it has different APK signature from the current app. Check install instruction at https://github.com/termux/termux-app for more details.
> 
> That error would have been thrown when [this](https://github.com/termux/termux-app/blob/v0.116/app/src/main/java/com/termux/app/TermuxActivity.java#L194) is called and actually thrown via [`PackageUtils`](https://github.com/termux/termux-app/blob/v0.116/termux-shared/src/main/java/com/termux/shared/packages/PackageUtils.java#L41).
> 
> * Check [TermuxConstants](https://github.com/termux/termux-app/blob/v0.116/termux-shared/src/main/java/com/termux/shared/termux/TermuxConstants.java#L177) javadocs for instructions on what changes to make in the app to change package name.
> * You also need to recompile bootstrap zip for the new package name. Check [here](https://github.com/termux/termux-app/issues/1983) and [here](https://github.com/termux/termux-app/issues/2081#issuecomment-865280111).

thank you so much! I will try, thank you.

**Comment by agnostic-apollo** [comment]
You are welcome.
