### ISSUE TITLE
chdir("/data/data/com.termux/files/home"): Permission denied :/ $

### ISSUE THREAD

**Issue by developeranaz** [termux/termux-app#2161]
**Problem description**
Showing this error at startup
`chdir("/data/data/com.termux/files/home"): Permission denied`
`:/ $`

Hi I use termux a lot and I had a lot of data in its home folder but now I can't access anything.
I accidentally removed his permission for `"/data/data/com.termux/files/"`
Directory Now I can't access any directory.
Tried force stopping on app info and restarting the phone.

Displays this message when termux starts 
"chdir ("/data/data/com.termux/files/home"): Permission denied
: / $ "

Now I can't get any permission to do anything also now I need to copy some important files in termux home directory to my '`/storage/emulated/0/`'.
I also tried `chmod + x * ` but termux doesn't have permission to access its `/data/data/com.termux/files/usr/bin/` directory, so I couldn't use the `cp` command to copy

**Screenshots**

![Screenshot_20210705_200128_com termux](https://user-images.githubusercontent.com/71500526/124487202-0b71b400-ddcc-11eb-9bb5-c672fefc38c1.jpg)

![Screenshot_20210705_200244_com termux](https://user-images.githubusercontent.com/71500526/124487338-34924480-ddcc-11eb-915a-44218309be0a.jpg)

**Steps to reproduce**
`cd /data/data/com.termux/files`
`chmod -x *`

**Expected behavior**

**Additional information**

* Termux application version: 0.114
* Android OS version: 9
* Device model: Huwaei Honor 7x BND-AL 10

**Comment by Grimler91** [comment]
Have you tried to re-add the `x` permission? `chmod +x /data/data/com.termux/*`

If that does not work for some reason then try from a [failsafe session](https://wiki.termux.com/wiki/Recover_a_broken_environment)

**Comment by developeranaz** [comment]
> Have you tried to re-add the `x` permission? `chmod +x /data/data/com.termux/*`
> 
> If that does not work for some reason then try from a [failsafe session](https://wiki.termux.com/wiki/Recover_a_broken_environment)

It worked
Thanks for such a quick response.
Using  failsafe mode and grant permission from `/data/data/com.termux/files/`
Using `chmod +x *` Fixed for me
