### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Neutronblazer** [termux/termux-app#2162]
**Problem description**
My phone cant install the app.

**Steps to reproduce**

**Expected behavior**
 The app installed on my phone

**Additional information**

* Termux application version:0.114
* Android OS version:8.1
* Device model:SM-G610F

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app#installation

Ensure you didn't installed from Google Play (or other non-Fdroid sources) before: Termux app, Termux:API, Termux:Styling, Termux:Widget, Termux:Boot and other add-ons. If found such in your system application list, uninstall them.

**Comment by Neutronblazer** [comment]
Thanks so much it installed now
