### ISSUE TITLE
Need help with fakeroot issue for makepkg.

### ISSUE THREAD

**Issue by Maxython** [termux/termux-app#2164]
### Hello everyone.

In the near future I am going to compile a few configured arch packages so that can run arch commands on termux. It was also the perfect opportunity to test makepkg for this.  Bottom line: there is a problem with `fakeroot`.  When compilation comes to running fakeroot, the following error occurs.
```
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```
If just disable `fakeroot`, then the compilation is successful but without the package itself.

The very reason for the error is understandable, but I don't know what to do in this case...

----
#### PS:
I must say right away that there is a way out of this situation (you will need to use TermuxArch), but this problem still needs to be solved in the near future.

**Comment by Maxython** [comment]
@Yisus7u7

**Comment by Yisus7u7** [comment]
Did you compile it with termux or using the gcc of arch?

**Comment by Maxython** [comment]
Makepkg is bash script.

**Comment by Yisus7u7** [comment]
Oh :(, as I once said, I still don't know about makepkg, I recently learned comp work .deb, once I throw a read to how to make a makepkg and it seems somewhat complicated

**Comment by Yisus7u7** [comment]
If I'm not wrong the makepkg follows the script orders, compiles something and creates the package not?

**Comment by Maxython** [comment]
If you have scripts (for example C/C++), then in the PKGBUILD file you must add the compilation of these scripts (it is better to do this with make). But if you already have the sources (like mine), then you just need to re-place them in `$pkgdir`.

**Comment by Maxython** [comment]
Here is an example PKGBUILD files that compile a package from source.
https://github.com/Maxython/arch-packages-for-termux/blob/main/profile/PKGBUILD
https://github.com/Maxython/arch-packages-for-termux/blob/main/termux-commands/PKGBUILD

**Comment by xeffyr** [comment]
Launch proot with `--sysvipc` option to have Sys V IPC. Otherwise get yourself a root+custom kernel with Sys V IPC enabled or use `fakeroot` with TCP-based IPC.

**Comment by Maxython** [comment]
Thank)

**Comment by Maxython** [comment]
Good news: makepkg runs on termux.
