### ISSUE TITLE
Implement an '/etc/os-release'?

### ISSUE THREAD

**Issue by WheezyE** [termux/termux-app#2165]
**Feature description**

I think it would be very helpful (and kind of cute) if Termux had an `/etc/os-release` file of its own since Termux runs bash scripts.

I am currently trying to create a multi-platform install script for Winlink, which I'm calling "[Winelink](https://github.com/WheezyE/Winelink)."  I would like to be able to run different installations depending on which OS/arch the script detects.  Android (Termux) is one of my target OS's via [AnBox86](https://github.com/lowspecman420/AnBox86) (arm-Termux + [box86](https://github.com/ptitSeb/box86/) + i386-[wine](https://www.winehq.org/)).

`uname -o` ("Android") works for my purposes at the moment, but I think having an `/etc/os-release` file could help keep users from accidentally running my Winelink script on a chroot instead of Termux.

**Reference implementation**

Does another app/terminal emulator have this feature?

 - No other Android apps to my knowledge.

Provide links to more background information

 - Most major Linux releases after 2012 implement an [os-release](http://0pointer.de/blog/projects/os-release.html) file to help users and scripts quickly differentiate which Linux OS they are running on.  A collection of example os-release files can be found [here](https://github.com/chef/os_release).  The os-release man page is [here](https://www.freedesktop.org/software/systemd/man/os-release.html).

**Comment by agnostic-apollo** [comment]
Have you tried using  `$TERMUX_VERSION` or checking if `$PREFIX` is set to `/data/data/com.termux/files/usr`?

Termux packages are updated independently of the termux app itself.

**Comment by WheezyE** [comment]
Thank you for the ideas.  `$TERMUX_VERSION` returns blank info for me, but using `$PREFIX` would be more specific to Termux than `uname -o` and does include Termux's name in it, so this would be a good option for what I'm trying to do.

I suppose it's more of a technicality than anything, but thought it would be nice/fun to have an os-release file for the Termux app itself, since packages are then installed via command line inside of the app.

**Comment by agnostic-apollo** [comment]
> Thank you for the ideas. `$TERMUX_VERSION` returns blank info for me

You are welcome. You need to have [`>= v0.107`](https://github.com/termux/termux-app/releases/tag/v0.107) for it to be set and so its only available on F-Droid releases since playstore releases were deprecated at `v0.101`.

https://github.com/termux/termux-app#installation

>but using $PREFIX would be more specific to Termux than uname -o and does include Termux's name in it, so this would be a good option for what I'm trying to do.

That should work, as long as you are not attempting to add support for termux forks, otherwise a regex comparison like `[[ $PREFIX =~ /data/data/[^/]+/files/usr ]] && echo IN_TERMUX` should work better, where `[^/]+` means one or more characters that are not a forward slash `/`.

> I suppose it's more of a technicality than anything, but thought it would be nice/fun to have an os-release file for the Termux app itself, since packages seem to be then installed via command line inside of the app.

It's not a bad idea per se, will consider adding this in future.

**Comment by WheezyE** [comment]
Ah yes, you're right I'm using the Google Play Store version at the moment.  I've been meaning to upgrade.
Thank you so much for the help and the regex command (that saves me some trouble).  I appreciate it!

**Comment by agnostic-apollo** [comment]
Goodluck. You are very welcome :)
