### ISSUE TITLE
Impossible to open APK file on some ROMs with Termux installed

### ISSUE THREAD

**Issue by CrystalCommunication** [termux/termux-app#2166]
**Problem description**

On some custom ROMs, such as dotOS, it becomes impossible to install .apk files if there is more than one application registered to open .apk files. I believe this happens because the default app chooser is crashing on purpose, so you cannot select the Android package installer. Termux registers itself as an application that can open .apk files, meaning that you cannot install downloaded .apk files if you have Termux installed. Other apps that have this behaviour, such as Split APK Installer, provide an option to disable it so you can install .apk files normally.

**Steps to reproduce**

1. Use a ROM that does not allow opening .apk files if a third-party application is registered for .apk files.
2. Install Termux
3. Download and attempt to open a .apk file
4. Nothing happens (or you are returned to home screen)

**Expected behavior**

.apk file opens with the Android package installer, giving prompts to complete installation of the app

**Additional information**

* Termux application version: 0.116
* Android OS version: 11
* Device model: Xiaomi Redmi Note 4 (Snapdragon)

**Comment by agnostic-apollo** [comment]
That shouldn't happen normally. Why do you expect an app to fix a custom ROM bug? Will require every app that opens APKs to have this option since someone may use it. Anyways, what's the error or exception thrown when you try to install an APK with termux installed, assuming chooser is actually crashing? Have you checked `logcat`?

https://developer.android.com/studio/command-line/logcat

**Comment by CrystalCommunication** [comment]
I do not believe it is actually a bug. I think the ROM is doing that on purpose, possibly for security purposes (i.e. to prevent an installed app from hijacking and infecting an apk before you install it). I found a workaround using a rooted adb shell and it was a huge pain in the ass so I'm not going to undo it just to get a logcat. I suppose I will investigate the root cause of this later, but I can't think of a situation where I'd want to open an apk file with Termux. I can transfer any apk files I need over to Termux's home directory easily enough using the Documents UI or by giving Termux permission to access external storage. I guess I'll close this since there's clearly no intention to fix it.

**Comment by CrystalCommunication** [comment]
I found a way to get a logcat without undoing my workaround. Here's the stack trace.

```
07-08 11:28:09.760 18045 18045 E system:ui: Not starting debugger since process cannot load the jdwp agent.
07-08 11:28:10.008 18045 21060 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
07-08 11:28:10.008 18045 21060 E AndroidRuntime: Process: system:ui, PID: 18045
07-08 11:28:10.008 18045 21060 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.android.packageinstaller:drawable/ic_app_icon with resource ID #0x7f070060
07-08 11:28:10.008 18045 21060 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_app_icon.xml from drawable resource ID #0x7f070060
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:910)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:692)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:993)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:983)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:957)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at com.android.internal.app.ResolverListAdapter$TargetPresentationGetter.loadIconFromResource(ResolverListAdapter.java:964)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at com.android.internal.app.ResolverListAdapter$TargetPresentationGetter.getIconBitmap(ResolverListAdapter.java:920)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at com.android.internal.app.ResolverListAdapter$ActivityInfoPresentationGetter.getIconBitmap(ResolverListAdapter.java:843)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at com.android.internal.app.ResolverListAdapter$TargetPresentationGetter.getIcon(ResolverListAdapter.java:908)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at com.android.internal.app.ResolverListAdapter$ActivityInfoPresentationGetter.getIcon(ResolverListAdapter.java:843)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at com.android.internal.app.ResolverListAdapter.loadIconForResolveInfo(ResolverListAdapter.java:599)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at com.android.internal.app.ResolverListAdapter$LoadIconTask.doInBackground(ResolverListAdapter.java:782)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at com.android.internal.app.ResolverListAdapter$LoadIconTask.doInBackground(ResolverListAdapter.java:769)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x106002f
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.Resources.getValueForDensity(Resources.java:1465)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1033)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.graphics.drawable.AdaptiveIconDrawable.updateLayerFromTypedArray(AdaptiveIconDrawable.java:530)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.graphics.drawable.AdaptiveIconDrawable.inflateLayers(AdaptiveIconDrawable.java:494)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.graphics.drawable.AdaptiveIconDrawable.inflate(AdaptiveIconDrawable.java:235)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:144)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1361)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:973)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:896)
07-08 11:28:10.008 18045 21060 E AndroidRuntime: 	... 18 more
```

Is it crashing because it can't draw the icon for the package installer app? Isn't there supposed to be a placeholder icon? Whatever the case it seems this is not actually intentional, my bad for assuming that. I'll go bark up the ROM developers' tree.

**Comment by xeffyr** [comment]
> 07-08 11:28:10.008 18045 21060 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.android.packageinstaller:drawable/ic_app_icon with resource ID #0x7f070060
07-08 11:28:10.008 18045 21060 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_app_icon.xml from drawable resource ID #0x7f070060

These 2 lines point that your ROM has serious issue with internal component `com.android.packageinstaller`, which is APK installation program. Looks like someone messed up resource IDs with apktool, that's a common issue...

**Comment by CrystalCommunication** [comment]
I see, maybe I will install a different ROM then. That's really annoying. Alternatively I suppose I could just rip the package installer apk out of a LineageOS build and try putting it into this ROM. I'm sorry for wasting your time because of my sloppy ROM.

**Comment by agnostic-apollo** [comment]
> possibly for security purposes (i.e. to prevent an installed app from hijacking and infecting an apk before you install it).

Any app that has storage permission can infect an APK at any time. Overlays usually are the issue.

Newer android versions require an app to be granted special permission to open and install an apk.



> I guess I'll close this since there's clearly no intention to fix it.

I didn't say no. It can be added in future but would be low priority.

> Here's the stack trace.

That's better. That's how you debug problems. Thanks

>Caused by: android.content.res.Resources$NotFoundException: Drawable com.android.packageinstaller:drawable/ic_app_icon with resource ID #0x7f070060

That's a definite issue with `packageinstaller`. With the share/chooser menu, it requires an app to have an icon, so when only 1 app, then it isn't shown so no crash.

The icon should exist normally as per [this](https://cs.android.com/android/_/android/platform/frameworks/base/+/f4bb58411b8dae02b7f9c416d3f36a1a8d0ef9b5) commit in AOSP. The issue is the resources id, I agree with xeffyr, that likely would have happened with messing around with the APK. It's also reported for another custom rom [here](https://forum.xda-developers.com/t/rom-official-mido-coltos-v6-4-10-0-16-sep-2020.4048681/post-83534061). And as per commit, it would happen even if user has installed a common app as GDrive which usually comes preinstalled. So yeah, report to ROM authors.

**Comment by CrystalCommunication** [comment]
> Any app that has storage permission can infect an APK at any time. Overlays usually are the issue.

Good point, I guess I didn't really think this through. I started jumping to conclusions when I saw the commit to disable the feature in SAI's GitHub. Sorry I didn't do my due diligence before opening and issue. It's been ages since I messed with Android this heavily so getting a logcat didn't even occur to me.

> I didn't say no. It can be added in future but would be low priority.

While it would be convenient to have a workaround in Termux, I think ROM developers should really stop fiddling with the package installer apk altogether. For reference, [here is the commit that added the feature for SAI](https://github.com/Aefyr/SAI/commit/8ce33e060c8a92726b9562f7ae1e9c5b4c711e19).

The workaround I mentioned was basically to manually set the package installer as the default application by copying some lines from package-restrictions.xml on a device running LineageOS, thus skipping the file chooser dialog and bypassing this issue. Again, I was overthinking things and overlooked the obvious cause of the problem.

I will be a little surprised if the ROM authors don't already know about this. It seems like it should've come up, seeing how I would assume there would be a decent amount of overlap between users running custom ROMs and having more than one app installed to handle apk files. Either way it really kinda sours my opinion of the ROM as a whole.

**Comment by agnostic-apollo** [comment]
>  I saw the commit to disable the feature in SAI's GitHub. 
> While it would be convenient to have a workaround in Termux

Neither commit nor release notes mention why it was added as a feature. I'll try look into adding it in termux as well, there are issues with other mime types as well so need to think on the design, time consuming stuff.

> Again, I was overthinking things and overlooked the obvious cause of the problem.

Well, now you know where to look when problems occur in future.

>I will be a little surprised if the ROM authors don't already know about this

Might be possible they already know and haven't updated. But if they only have a single test device for the ROM and issue is not occurring on it due to no additional apps or they never tried to install APKs manually, then it would take a user to report the issue for them to know.
