### ISSUE TITLE
Keyboard bug

### ISSUE THREAD

**Issue by camelCase-dumb** [termux/termux-app#2172]
I can't find the best words to describe it so I just recorded it instead.

https://user-images.githubusercontent.com/56781329/125730007-f4f040cb-f588-4ad7-baf3-edddfe21b7c9.mp4

**Comment by harieamjari** [comment]
I can't view the footage. I've spent time transcoding it with ffmpeg but the result is still "Unsupported video codec".

Could you write your problem in words?

**Comment by Grimler91** [comment]
Looks like https://github.com/termux/termux-app/issues/686, you can workaround it by setting `enforce-char-based-input=true` in ~/.termux/termux.properties (see https://github.com/termux/termux-app/issues/686#issuecomment-681026810)

**Comment by camelCase-dumb** [comment]
Oh that fixed it closing it now.
