### ISSUE TITLE
All repositories are down

### ISSUE THREAD

**Issue by nemecekjh** [termux/termux-app#2173]
**Problem description**
All repositories have been down since Wednesday, July 14th 2021.
#2067 did not help.

**Steps to reproduce**
```
apt update
apt install [package]
```

**Expected behavior**
the package list should update and [package] should install.

**Additional information**
Same error occurred on two different devices and Android versions.

device 1:
* Termux application version: 0.101
* Android OS version: 11 (LineageOS 18.1, not rooted)
* Device model: Samsung Galaxy Note 4 (SM-910F)

device 2:
* Termux application version: 0.101
* Android OS version: 9 (stock Samsung ROM, not rooted)
* Device model: Samsung Galaxy S8 (SM-G950F)

**Comment by xeffyr** [comment]
Open https://github.com/termux/termux-packages/issues/6726 and follow the instructions. Otherwise, use Termux application from F-Droid, uninstalling before app and all add-ons from Play Store. Termux on Play Store no longer receives updates.

**Comment by xeffyr** [comment]
If you still have issues, then you really didn't followed instructions exactly or missed step. - You have to change all repositories, not the first one only, and use Grimler's mirror.

Termux repositories are up.

**Comment by nemecekjh** [comment]
> Otherwise, use Termux application from F-Droid

Yes, sorry, I didn't notice that the Google Play version was deprecated 🙃 

It still won't update though 😞 
I am absolutely positive I did everything in [here](https://github.com/termux/termux-packages/issues/6726).
What's going on?

Here's a screenshot if needed:
![obrázek_2021-07-16_204517](https://user-images.githubusercontent.com/79845941/125994630-fc14a55c-b2fc-495e-a10c-d86ed1eb8c65.png)

**Comment by xeffyr** [comment]
Manually edit `$PREFIX/etc/sources.list` and files in `$PREFIX/etc/sources.list.d`. Pick URLs from https://github.com/termux/termux-packages/wiki/Mirrors

**Comment by nemecekjh** [comment]
Yeah, when I curl the file I can clearly see the signature at the end, yet when I try to `apt update`, it's not signed. What's going on? Is it an APT issue?

**Comment by xeffyr** [comment]
Uninstall Termux and all add-ons (like Termux:API, Termux:Styling, etc) and then install Termux from F-Droid.

https://github.com/termux/termux-app#f-droid

**Comment by nemecekjh** [comment]
I don't have any addons on the Note 4, and I installed it from F-Droid this time.

**Comment by xeffyr** [comment]
And it shows exactly same error as you have posted previously?

I can't reproduce it. Try VPN, to exclude cases where your connection is tampered outside.

If that is a bug in `apt`, it would be reproducible by everyone. Otherwise this is either device-specific or networking (ISP) issue.

![apt](https://user-images.githubusercontent.com/25881154/126001578-7048f918-0ade-4e4a-8362-8a9fa5742f3c.jpg)

> https://github.com/termux/termux-packages/wiki/Mirrors#repositories-and-mirrors
Service availability may vary depending on your device, Internet connection quality, and censorship events in your country. If we detect serious issue on our side, we will post announce on GitHub and our community pages. Other issues, like introduced on client side or somewhere between endpoints, would be ignored.

**Comment by nemecekjh** [comment]
I doubt it has anything to do with censorship or internet connection quality, the InRelease file downloaded without problem, plus I had the same problem in 2 different cities, with two different ISPs.
Nevertheless, I got a VPN to the US and got the exact same error.

**Comment by xeffyr** [comment]
Then device-specific or ROM-specific issue (`getline` has nothing to do with network, it is used to read local files). And as I wrote, bugs in package should be reproducible by everyone. So far only you reporting this.

Try `rm -rf $PREFIX` and restart app, other device...

And if you really on F-Droid Termux variant, post screenshot with `apt update`.

**Comment by nemecekjh** [comment]
yes, it works on the S8 now. It's a bummer that it doesn't work on the Note 4 though. Here's the screenshot, just in case something can be done about it.
![image](https://user-images.githubusercontent.com/79845941/126031736-1aadec2f-51bc-47a0-95aa-a9549e492a1b.png)
