### ISSUE TITLE
App not installing on MIUI12

### ISSUE THREAD

**Issue by sid-am-ahd935** [termux/termux-app#2179]
Tried every mirror and version above 113, it does not install on my MIUI12. Only the Termux app in the playstore is getting installed, but that does not  suffice the task ongoing.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation

**Comment by sid-am-ahd935** [comment]
I have found out the cause, there was an already installed termux:API of the older version of termux which was preventing the installing of the newer one.
