### ISSUE TITLE
The full screen does not allow the termux to understand where the top of the keyboard is

### ISSUE THREAD

**Issue by Dolfost** [termux/termux-app#2180]
**Problem description**

Im enabled a full screen in termux.properties and this happen: Vim line is hidden behind the keyboard, the screen is not promoted itself to the point where the keyboard would be under the text in the terminal.
(I do not need a drain state when using the terminal)

![Screenshot_20210720-125439_Termux](https://user-images.githubusercontent.com/59747489/126306940-9a240791-2762-4c3f-bf6e-caed1e0020ac.png)
![Screenshot_20210720-125452_Termux](https://user-images.githubusercontent.com/59747489/126306945-75bf669b-7cba-4681-963a-8558669dcd33.png)
![Screenshot_20210720-130216_Termux](https://user-images.githubusercontent.com/59747489/126306946-c9db2dcb-c748-49c9-b3e5-d1f8fd710af6.png)
![Screenshot_20210720-130221_Termux](https://user-images.githubusercontent.com/59747489/126306948-a76ac904-c0b0-4864-a3c6-616c6ed3cd96.png)

**Steps to reproduce**

Create file: $HOME/.termux/termux.properties
Add to this file a string: fullscreen = true
Restart Termux.
Then any commands in terminal. Or open the vim.

**Expected behavior**

It should work as usual, commands should not climb under the keyboardwhen full screen in termux.priperties is true.

**Additional information**

* Termux application version: 0.117
* Android OS version: Lineage OS 17.1
* Device model: Xiaomi Mi A1 (tissout)

**Comment by agnostic-apollo** [comment]
Have you tried setting `use-fullscreen-workaround = true` and then restarting termux?

**Comment by Dolfost** [comment]
> Have you tried setting `use-fullscreen-workaround = true` and then restarting termux?

 Yes of course. Also I tried all possible combinations of values (4) for: 
`fullscreen` and `use-fullscreen-workaround`

**Comment by Dolfost** [comment]
I did it! All you had to do was turn on the _Terminal Margin Ajustment_ in the Termux settings! By the way in my case the value of `use-fullscreen-workaround` does not affect this.
Thanks!

![Screenshot_20210720-155826_Termux](https://user-images.githubusercontent.com/59747489/126328824-a0254887-10f2-4d3b-8a84-9e587471ac6a.png)
![Screenshot_20210720-155855_Termux](https://user-images.githubusercontent.com/59747489/126328834-ce16c81a-bc6b-4377-b9c5-ea9be0aff62d.png)

**Comment by agnostic-apollo** [comment]
`Terminal Margin Ajustment` should be enabled by default, did you disable it yourself?

On my LG G5 7.0, margin adjustment does work to fix fullscreen issue but when switching to text input view, the terminal disappears, have to press back button to close keyboard to make it appear and then keyboard has to reopened. That may be fixable.

https://wiki.termux.com/wiki/Touch_Keyboard

If `use-fullscreen-workaround` is enabled, then fullscreen issue is fixed too and doesn't have the text input view issue or gboard clipboard bar covering extra keys issue (for which margin adjustment was created).

Those 2 are competing things, kinda doing similar thing and probably shouldn't be used together. But if it works for you to fix fullscreen issue, then great.

**Comment by Dolfost** [comment]
> `Terminal Margin Ajustment` should be enabled by default, did you disable it yourself?

Yes, I turned it off.

> Those 2 are competing things, kinda doing similar thing and probably shouldn't be used together if causing issues. But if it works for you to fix fullscreen issue, then great.

Quite an interesting thing, probably depends on the OS.

**Comment by agnostic-apollo** [comment]
Yeah, lot of fragmentation and bugs.
