### ISSUE TITLE
Install octicons weathericons in termux

### ISSUE THREAD

**Issue by sudipta-nandan** [termux/termux-app#2183]
I have been using Emacs for quite a few time. While customizing it I came into account that there is a pack name all-the-icons.el which enables a lots of icons to be used in emacs. The pack creates a lots of ttf files of the icons under .local/share/fonts. But I cant install these icons ttf file in termux. Actually I dont know how to incorporate these ttf files of icons in termux so that the icons are porperly rendered.

**Comment by xeffyr** [comment]
Termux can load only **one** ttf file and only that is located under `~/.termux/font.ttf`.
