### ISSUE TITLE
The termux app throwing errors while apt update && upgrade

### ISSUE THREAD

**Issue by Allan-sketch** [termux/termux-app#2185]
````
WARNING: linker: libandroid-support.so: unused DT entry: type 0x6fffffff arg 0x1
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "__register_atfork" referenced by "libandroid-support.so"...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/libgmp_6.2.1_arm.deb (--unpack):
 rm command for cleanup subprocess returned error exit status 1
````
What can I do in this can someone explain me anything??

From @Allan-sketch

**Comment by xeffyr** [comment]
What is your Android OS version?

**Comment by Allan-sketch** [comment]
5.1.1

**Comment by Allan-sketch** [comment]
Lollipop

**Comment by xeffyr** [comment]
We have dropped support of this Android version 1.5 years ago.

If you attempt to replace repositories with ones from https://github.com/termux/termux-packages/wiki/Mirrors, you will break the environment. Our packages are compatible only with Android 7.0 and higher.

**Comment by Allan-sketch** [comment]
What x an I do now

**Comment by xeffyr** [comment]
What you can do:
* Reset Termux installation through clearing application data and beginning from scratch without messing up with repositories.
* Get a new device or update the current one to *at least* Android 7.0 and use the latest Termux app v0.117+.
