### ISSUE TITLE
Custom home path?

### ISSUE THREAD

**Issue by NTT1906** [termux/termux-app#2186]
**Feature description**

Can termux support custom home path since termux has no explorer, which jas made the file more difficult to edit ~~

**Comment by xeffyr** [comment]
No, it doesn't support custom home path. Stuff like Termux properties is hardcoded to be inside home directory:
```
/data/data/com.termux/files/home
```

You can override the HOME variable by doing `export HOME=/your/path/here` in ~/.bashrc, but entirely on your own.

If you need just different startup directory, then put `cd /your/path/here` instead to ~/.bashrc.

**Comment by agnostic-apollo** [comment]
You can also add something like `default-working-directory=/sdcard` to `~/.termux/termux.properties` instead of `cd`.

And you can open termux home in your file explorer app if it supports SAF. Check https://github.com/termux/termux-tasker#creating-and-modifying-scripts
