### ISSUE TITLE
Hooks don't work with file explorer apps.

### ISSUE THREAD

**Issue by YellowOnion** [termux/termux-app#2187]
**Problem description**
Termux attempts to "download" files shared from Google Pixel "files" app, and Solid Explorer.

**Steps to reproduce**

Share or open a file from a explorer app like Solid Explorer.

**Expected behavior**
`~/bin/termux-file-editor` or `~/bin/termux-url-opener` is run.

**Additional information**

* Termux application version: 0.117 
* Android OS version: 11
* Device model: Pixel 4a

**Comment by agnostic-apollo** [comment]
Press `Edit` button in termux  popup after sharing file.
