### ISSUE TITLE
Soft keyboard is opened when Termux is put to foreground, even if keyboard was manually closed

### ISSUE THREAD

**Issue by Susko3** [termux/termux-app#2188]
**Problem description**

The soft keyboard will open every time Termux is put to foreground. This shouldn't happen if the keyboard was manually closed (eg. by tapping on keyboard button in the drawer or by pressing back to close the keyboard).

**Steps to reproduce**

1. Open Termux
2. Close the soft keyboard by pressing the `keyboard` button in the left drawer, or by pressing the back button
3. Put Termux to background (by pressing the home or recents button)
4. Open Termux again
5. Notice that the keyboard is open, even though it was manually closed

**Expected behavior**

The keyboard shouldn't open if it was manually closed. If I had wanted the keyboard to open, I'd have tapped on the screen. 

**Additional information**

* Termux application version: 0.114
* Android OS version: 10
* Device model: Realme 6

**Comment by agnostic-apollo** [comment]
Check [this](https://github.com/termux/termux-app/pull/2114#issuecomment-855389029) for why that can't be done reliably. Use `soft-keyboard-toggle-behaviour=enable/disable` added in [`v0.113`](https://github.com/termux/termux-app/releases/tag/v0.113) with the `KEYBOARD` extra key or left drawer button if you don't want keyboard to show automatically.

**Comment by Susko3** [comment]
Would it be possible to make the `termux.properties` `back-key` have an option to toggle the keyboard the same way `KEYBOARD` extra key does?

Something like setting `back-key=keyboard`

**Comment by agnostic-apollo** [comment]
But then you won't be able to exit termux with back key. It should likely technically be possible though.

Moreover, note that `back-key=escape` already exists https://wiki.termux.com/wiki/Terminal_Settings
