### ISSUE TITLE
When termux uses the system signature, an error is reported when the command is executed

### ISSUE THREAD

**Issue by tangzeyu7** [termux/termux-app#2189]
# can't execute: Permission denied

## Configuration

* Termux uses the system signature in the platform source code
    ![platform签名](https://cdn.jsdelivr.net/gh/tangzeyu7/-imgur@master/1627283761765-platform.png)

* Configure sharedUserId="android.uid.system" in AndroidManifest 
    ![sharedUserId](https://cdn.jsdelivr.net/gh/tangzeyu7/-imgur@master/1627284009951-shareduserid.png)

### Session mode

* Start interface

    ![](https://cdn.jsdelivr.net/gh/tangzeyu7/-imgur@master/1627284257036-termux_session_terminal.png)

* Execute Command

    ![](https://cdn.jsdelivr.net/gh/tangzeyu7/-imgur@master/1627284509129-termux_session_permission_denied.png)

### Failsafe mode

 * The start interface is consistent with the Session
 * Execute Command

    ![](https://cdn.jsdelivr.net/gh/tangzeyu7/-imgur@master/1627284767569-termux_failsafe_script.png)

* ls -l

    ![](https://cdn.jsdelivr.net/gh/tangzeyu7/-imgur@master/1627284813234-termux_failsafe_ls.png)
    ![](https://cdn.jsdelivr.net/gh/tangzeyu7/-imgur@master/1627284886742-termux_failsafe_ls_ls.png)
    ![](https://cdn.jsdelivr.net/gh/tangzeyu7/-imgur@master/1627284899144-termux_failsafe_ls_whoami.png)

* Execute Command: ./

    ![](https://cdn.jsdelivr.net/gh/tangzeyu7/-imgur@master/1627284947139-termux_failsafe_ls_permission_denied.png)

What causes this problem? How to solve it?

**Comment by agnostic-apollo** [comment]
Are you on android 10+? If yes, then likely issue considering that now termux will be running as the user of the `system` package, its `targetSdkVersion` restrictions would apply and not termux's own. That's why `/system/bin`  binaries work fine but not the ones in termux's own priv app data dir under `$PREFIX`. Check https://github.com/termux/termux-packages/wiki/Termux-and-Android-10

Check `logcat` for confirmation, likely selinux `avc` denial entries.

I wonder why `sh` session started in normal session instead of `bash` (failing), maybe [`canExecute()`](https://github.com/termux/termux-app/blob/v0.117/termux-shared/src/main/java/com/termux/shared/shell/TermuxSession.java#L85)  failed (unless OP changed default). 🤔

**Comment by tangzeyu7** [comment]
You're right, it does run on Android 10.
Error log:
```
2021-07-27 09:44:47.910 18506-18506/com.termux W/com.termux: type=1400 audit(0.0:1245): avc: denied { execute } for name="login" dev="dm-8" ino=644006 scontext=u:r:system_app:s0 tcontext=u:object_r:system_app_data_file:s0 tclass=file permissive=0
2021-07-27 09:45:00.002 18594-18594/? W/sh: type=1400 audit(0.0:1277): avc: denied { execute } for name="coreutils" dev="dm-8" ino=646644 scontext=u:r:system_app:s0 tcontext=u:object_r:system_app_data_file:s0 tclass=file permissive=0
```
This problem has been bothering me for 2 days, thank you for your help!

**Comment by tangzeyu7** [comment]
> Are you on android 10+? If yes, then likely issue considering that now termux will be running as the user of the `system` package, its `targetSdkVersion` restrictions would apply and not termux's own. That's why `/system/bin` binaries work fine but not the ones in termux's own priv app data dir under `$PREFIX`. Check https://github.com/termux/termux-packages/wiki/Termux-and-Android-10
> 
> Check `logcat` for confirmation, likely selinux `avc` denial entries.
> 
> I wonder why `sh` session started in normal session instead of `bash` (failing), maybe [`canExecute()`](https://github.com/termux/termux-app/blob/v0.117/termux-shared/src/main/java/com/termux/shared/shell/TermuxSession.java#L85) failed (unless OP changed default). 🤔

You're right, it does run on Android 10.
Error log:
```
2021-07-27 09:44:47.910 18506-18506/com.termux W/com.termux: type=1400 audit(0.0:1245): avc: denied { execute } for name="login" dev="dm-8" ino=644006 scontext=u:r:system_app:s0 tcontext=u:object_r:system_app_data_file:s0 tclass=file permissive=0
2021-07-27 09:45:00.002 18594-18594/? W/sh: type=1400 audit(0.0:1277): avc: denied { execute } for name="coreutils" dev="dm-8" ino=646644 scontext=u:r:system_app:s0 tcontext=u:object_r:system_app_data_file:s0 tclass=file permissive=0
```
This problem has been bothering me for 2 days, thank you for your help!

**Comment by agnostic-apollo** [comment]
You are welcome.

**Comment by TREYWANGCQU** [comment]
Thanks

**Comment by agnostic-apollo** [comment]
@tangzeyu7 You may wanna check out https://github.com/termux/termux-app/issues/2445#issuecomment-985484952.

**Comment by tangzeyu7** [comment]
> @tangzeyu7 You may wanna check out [#2445 (comment)](https://github.com/termux/termux-app/issues/2445#issuecomment-985484952).

OK, thank you for reminding me.

**Comment by agnostic-apollo** [comment]
Welcome.
