### ISSUE TITLE
cannot open URLs from XFCE in VNC

### ISSUE THREAD

**Issue by rkitover** [termux/termux-app#2191]
**Problem description**
I set up XFCE as described here:

https://wiki.termux.com/wiki/Graphical_Environment

using TruVNC as the VNC viewer, switched to immersive mode with SystemUI Tuner.

When I open a URL in the normal termux terminal, using the following command, it works fine:

am start --user 0 -a android.intent.action.VIEW -d https://www.google.com

However, when I run this command in xfce4-terminal it says "Starting intent" but nothing happens, and firefox does not do anything.

**Steps to reproduce**
Run command to open intent with a URL in a VNC session, e.g. with `termux-open-url`.

**Expected behavior**
I expect android to switch to firefox and open the requested URL in a tab, this is what happens in the normal termux terminal.

**Additional information**

* Termux application version: 0.101
* Android OS version: 11
* Device model: Samsung s7+ tablet, not rooted

**Comment by xeffyr** [comment]
On Android 11 you can't start activities when Termux is in background.

**Comment by agnostic-apollo** [comment]
> you can't start activities when Termux is in background

If that's the reason, then granting termux `Draw Over Other Apps` should work.

**Comment by rkitover** [comment]
@agnostic-apollo Thank you, that fixed it for me.

I went to `Settings -> Applications` then I pressed the three dots at the top and went to `Special Permissions` then I went to `Always on Top` and selected Termux. That's the russian translation, it may be `Draw Over Other Apps` in the English locale.

Now I can open URLs in XFCE in VNC.

I will update the wiki.

**Comment by agnostic-apollo** [comment]
You are welcome. Yeah, that should be it. The name changes on different android versions/manufactures/locales. Permission should also be accessible directly from Termux App Info under `Advanced`, like from `Android Settings` -> `Apps`.
