### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by InternetOwnBoy** [termux/termux-app#2194]
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.34.0/i686-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.34.0 /data/data/com.termux/files/usr/lib/perl5/5.34.0/i686-android /data/data/com.termux/files/usr/lib/perl5/5.34.0) at Th3inspector.pl line 6.
BEGIN failed--compilation aborted at Th3inspector.pl line 6.

**Comment by agnostic-apollo** [comment]
termux/termux-packages#2378
