### ISSUE TITLE
Unable to access data and obb folder

### ISSUE THREAD

**Issue by holiq** [termux/termux-app#2196]
**Problem description**
I can't access data folder and different obb in android folder with response `Permission denied`

**Additional information**

* Termux application version: 0.117
* Android OS version: 11
* Device model: Samsung A20S

![Screenshot_20210731-165740_Termux](https://user-images.githubusercontent.com/30729921/127736402-205e3f56-d8c8-4033-b63b-54990d162f8d.png)

**Comment by agnostic-apollo** [comment]
Duplicate #1952

You probably should be able to access `Android/obb` directory after granting termux install apps permission. Access to `Android/data` is gone on Android 11, at least for Termux, other apps may use `SAF` hack, but I have been notified that that doesn't work on Android 12.

**Comment by agnostic-apollo** [comment]
Duplicate of #1952.

**Comment by Ismailhossen1** [comment]
please  make termux  capable   for  accessing  data and obb folder....is this feature   will  get in future ???

**Comment by agnostic-apollo** [comment]
Termux can't bypass android restrictions. Use root or possibly adb for `Android/data` if supported.

**Comment by donmor** [comment]
Using android 12, I can access Android/data using zarchiver by granting access manually. This hack may works with termux. Anyone reopen this issue?

**Comment by WilsonBradley** [comment]
Can you repost here?

**Comment by Drjacky** [comment]
> Duplicate of #1952
> 
> You probably should be able to access `Android/obb` directory after granting termux install apps permission. Access to `Android/data` is gone on Android 11, at least for Termux, other apps may use `SAF` hack, but I have been notified that that doesn't work on Android 12.

But still, it doesn't list the system apps' packages
