### ISSUE TITLE
termux suddenly stopped

### ISSUE THREAD

**Issue by holiq** [termux/termux-app#2197]
**Problem description**
When I was developing laravel after 5 minutes passed suddenly the localhost connection was lost and when I checked it turned out that termux had stopped, so I had to restart the server 

**Additional information**

* Termux application version: 0.117
* Android OS version: 11
* Device model: Samsung A20S

**Comment by Grimler91** [comment]
Most likely killed by android for out-of-memory reasons, but without a logcat we can only guess. Closing since there is nothing to be done without more information

**Comment by agnostic-apollo** [comment]
Samsung may be killing even foreground services. Check `logcat`.

urbandroid-team/dont-kill-my-app#307

https://dontkillmyapp.com/samsung

**Comment by rajrish5541f** [comment]
I got the same problem while using Ubuntu in my android through termux and vnc server. It worked only for 5 to 10 mins.
![SmartSelect_20220904-092551_Termux.jpg](https://user-images.githubusercontent.com/107606176/188296606-dc80caa1-8143-4f4c-b7b7-4294a3254c65.jpg)

**Comment by 2096779623** [comment]
> I am using android 12 12 GB ram

https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8#disable-phantom-process-killing
