### ISSUE TITLE
CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double"

### ISSUE THREAD

**Issue by vikitajudin** [termux/termux-app#2200]
Anyone can help me with this problem? if i run php script is always show like this :

Welcome to Termux!

Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

The Google Play version of the Termux app no longer
receives updates. For more information, visit:
https://wiki.termux.com/wiki/Termux_Google_Play

~ $ termux-setup-storage
~ $ cd /sdcard/termux/fx/express/hogcoin
.../express/hogcoin $ ls
bot.php  config.php  cookie.txt
.../express/hogcoin $ php bot.php
CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double" referenced by "/data/data/com.termux/files/usr/bin/php"...
.../express/hogcoin $

**Comment by Grimler91** [comment]
php works fine for me. Make sure your packages are up to date.

If the problem persists after updating packages are up to date then please fill in the [bug report template](https://github.com/termux/termux-app/issues/new?assignees=&labels=&template=bug_report.md)

**Comment by thunder-coding** [comment]
Oops, that's me who recently bumped libffi, `php` needs to be rebuilt. `TERMUX_PKG_REVISION` needs to be bumped

**Comment by Grimler91** [comment]
Seemed to not be necessary to bump on aarch64, but maybe other arches have problems
