### ISSUE TITLE
Termux can’t exec daemon serve including termux-services

### ISSUE THREAD

**Issue by TREYWANGCQU** [termux/termux-app#2202]
**Termux condition**

* Termux application version: ```0.117```
* Android OS version: Android ```11(3-1, 2021)```
* Device model: MEIZU 17

**Problem description**

Termux can’t exec daemon serve including [termux-services](https://github.com/termux/termux-services). And I found it like,
``` shell
sshd
#nothing happen
nmap localhost
#you won't find 8022 port
ps -A
# you won't find pid of sshd
adb devices
#daemon not running and starting again and again
service-daemon start
#Starting daemon... it seems good but...
service-daemon stop
#No such process...
```

**One possible solution**
I have to open sessions for each services like,
```shell
sshd -D -e
adb nodaemon server
#....
```

**Comment by agnostic-apollo** [comment]
Likely related to #2015. Also check https://dontkillmyapp.com/meizu

**Comment by TREYWANGCQU** [comment]
> Likely related to #2015. Also check https://dontkillmyapp.com/meizu

I'm quiet sure that the key point in my issue is not  about ```battery manager```.

I have already set a ```performance mode```.  As termux is battery-locked and  won't be killed by Meizu, I could connect the phone via ``` sshd  -D -e``` for a long time.

But the ``` problem```  is still there. I couldn't start services in one single session.

**Comment by agnostic-apollo** [comment]
Check `logcat` over `adb`, maybe it indicates the killing. Considering no daemon is running and `sshd -D` is working, this is most likely your device issue and not broken termux packages.

**Comment by exsystem** [comment]
Same problem also for MEIZU 18SPro.
