### ISSUE TITLE
Add "copy all text" or "save all text to file" action

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-app#2204]
**Feature description**

Sometimes I just want to copy all text from terminal screen to file. I still don't know how to do that except manually selecting + scrolling all the way up. Ctrl-A also doesn't work.
**Reference implementation**

Does another app/terminal emulator have this feature?

It is easy to that on PC.

**Comment by Aridlvory** [comment]
Its simple
**Copy everything in the terminal**

Long press on the screen 

U will see a popup saying

Copy,more

There go tap the more button and then u will see this

![Screenshot_20210805-123914_Termux.jpg](https://user-images.githubusercontent.com/78092537/128307456-30297312-d642-42f7-a769-9ce6dd85de4a.jpg)

Tap the share transcript button

Your device's "share to whom" screen appears

Tap copy

Last step : paste it wherever u want 😀

**Comment by Mark-Joy** [comment]
oh my my, how foolish of me!! Thank you! 😂
