### ISSUE TITLE
How can I install an APK from the Termux command line?

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-app#2205]
**Feature description**

How can I install an APK from the Termux command line?

**Reference implementation**

This command `am start --user 0 -n com.android.chrome/com.google.android.apps.chrome.Main` launches Chrome Browser from Termux in Android.  I have noticed the install newly implemented unknown apps setting in Termux;  What is the command to install an APK from the Termux command line?

**Comment by agnostic-apollo** [comment]
Check [here](https://www.reddit.com/r/termux/comments/mzjeci/termux_v0112_release/gw22z4x?utm_source=share&utm_medium=web2x&context=3) if you want to use intents and show install screen after granting termux install permission as mentioned in 93a5bf8d. For background installation, you can either use use `pm install` command with `root`, or `adb install` if you have setup `adb` with [`android-tools`](https://www.reddit.com/r/termux/comments/mmu2iu/announce_adb_is_now_packaged_for_termux/). Check `pm --help` or `adb --help` for more info or search on internet.

**Comment by xeffyr** [comment]
`termux-open /storage/emulated/0/application.apk`

**Comment by SDRausty** [comment]
Thank you for your quick replies; This feature is great!
