### ISSUE TITLE
Problems of PKG and apt

### ISSUE THREAD

**Issue by txmu** [termux/termux-app#2206]
When I open the software and try to run PKG update, the following output (termux change repo executed) get: 1 https://mirrors.bfsu.edu.cn/termux/termux-packages-24  stable InRelease [14.0 kB]Err:1  https://mirrors.bfsu.edu.cn/termux/termux-packages-24  stable InReleaseAt least one invalid signature was encountered.Reading package lists... DoneW: GPG error:  https://mirrors.bfsu.edu.cn/termux/termux-packages-24  stable InRelease: At least one invalid signature was encountered.E: The repository ' https://mirrors.bfsu.edu.cn/termux/termux-packages-24  stable InRelease' is not signed.N: Metadata integrity can't be verified, repository is disabled now.N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by agnostic-apollo** [comment]
Change mirror to another Chinese mirror. Check https://github.com/termux/termux-packages/issues/6726

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-packages/wiki/Mirrors/_compare/08af56a8310031165b74424aa93f68f8aa347b9f...6f01d20223b476ae0b4d194d86216bcdc0fb4186
