### ISSUE TITLE
Termux cannot run on Android 11 at all

### ISSUE THREAD

**Issue by txmu** [termux/termux-app#2207]
The system version is Android 11 and cannot obtain root permission. After the first installation, the following output appears
![Screenshot_2021-08-05-16-51-55-271_com termux](https://user-images.githubusercontent.com/71213934/128376057-02a557e7-7cf8-4e06-a5a1-a0ff3805bef8.jpg)

**Comment by agnostic-apollo** [comment]
>cannot obtain root permission

What do you mean by that. How are you trying to do that?

Where did you install the APK from? Long click on the terminal like you would for copying text -> More -> Report Issue. Then copy the text with the Copy option in menu (3 dots top right). Paste that here.

**Comment by Yoyo509905905509** [comment]
I am having that problem too

**Comment by etmatrix** [comment]
I'm running 0.117 on LOS 18.1 Android 11 and I have no this issue. So it's too generic can't run on android 11.

**Comment by agnostic-apollo** [comment]
Until users who post reports and others commenting don't follow the instructions written now and others that may come and post the results, there will be no help and issue will likely be closed after some days. "Me too" does not help anyone without the data asked for.

In addition to above, also need output for `adb shell logcat -d` command for selinux issues (`avc` entries). And did existing users receive an android update after which this error came, maybe AOSP made changes.

**Comment by xeffyr** [comment]
> maybe AOSP made changes

If that has been introduced in AOSP, then this should be a mass problem.

On my Pixel 5 with latest updates Termux works fine.

***

*When reporting issue, include your device model or at least brand (not forgetting about logs). Android is fragmented and same application can behave differently on different devices having same Android version. Including device model in report will help to collect stats about problematic devices.*

**Comment by agnostic-apollo** [comment]
Yeah, I agree, AOSP changes are unlikely, at least this late in an android version, but individual vendors may have done so in their update. 2 of the 3 above have/mention `root`, so that's likely the issue.

**Comment by aarohikashab92** [comment]
xmlstarlet/stable 1.6.1-4 aarch64

**Comment by ShivamJoker** [comment]
I can't even install the app on my google pixel from fdroid

**Comment by agnostic-apollo** [comment]
> I can't even install the app on my google pixel from fdroid

Check https://github.com/termux/termux-app#installation

**Comment by TREYWANGCQU** [comment]
find ```su``` file in /system/bin or /system/xbin

Then making a [soft link](https://blog.reaticle.com/2020/08/10/build-termux.html) to termux directory /com.termux/files/usr/bin

**Comment by artisticfox8** [comment]
The app works all right on Samsung

**Comment by simbelmine** [comment]
Our Android app was using "ip neigh" and it was working fine on Android 11 phones (targetSDKVersion 29).
Google Play Store forced us to start targeting 30 instead. And now it doesn't work. 

It's not much, but maybe that's why some folks are experiencing issues with Termux (if they forked it and changed the target version). 
My Termux app (from Play Store) is working fine on Android 11, but it's targeting 28. So it's expected to work.

If someone comes up with something more, please share!
