### ISSUE TITLE
Termux Not Installing

### ISSUE THREAD

**Issue by praveenkumar222** [termux/termux-app#2208]
![Screenshot_20210806-110347](https://user-images.githubusercontent.com/77523501/128461489-cbb06377-1fda-4bf2-9364-5d821c12b24f.jpg)

I can't install termux .It Shows error while installing"The Package Conflicts with an existing  package by the same name.

Termux application version: Version 0.117 (117) 
Android OS version:7.1
Device model:SM-J250F

**Comment by Grimler91** [comment]
Probably because you have some addon apps from google play installed. Uninstall all termux apps from google play before you install termux, see https://github.com/termux/termux-app#Installation
