### ISSUE TITLE
Can't hit enter on Android TV

### ISSUE THREAD

**Issue by tylerswagar** [termux/termux-app#221]
I don't know how official the Android TV support is, but it's apparently supported enough for Termux to show up in the Play Store, so I figure this report is worth a shot.

For a couple updates now, I believe 0.44 onward, I can't enter commands on my Nexus Player.  I can punch them in, but the "done" button on the on-screen keyboard does nothing.  This only happened after the Termux update, as I haven't updated the Player itself since the jump to Android 7.1.1 back on December 5th, and this doesn't occur in other apps.  This is not an issue on my phone.

Again, I don't know whether this device is a priority, but I hope I can get Termux working on it again, as the SSH daemon is my main method of transferring files on and off this thing.

Thank you.

**Comment by fornwall** [comment]
Thanks for reporting it! Before the 0.44 update, was it the "done" button that behaved as enter, or was it another enter key visible?

**Comment by tylerswagar** [comment]
I couldn't remember, so I used F-Droid as an easy way to get 0.42 and yeah, it was "done".

**Comment by fornwall** [comment]
@tylerswagar Thanks a lot for reporting and helping! This will be fixed in a minor v0.46 update which should be available as an update in a couple of hours.

**Comment by fornwall** [comment]
Note: On F-Droid the delay for the update will be a bit longer as they do a nightly build, but it should be available within a day.
