### ISSUE TITLE
Running termux even if there is an error with login.

### ISSUE THREAD

**Issue by Maxython** [termux/termux-app#2212]
## Hi all.
By the name, you already understand what I mean)  
Is this implementation possible?  If not, can you make a file to control the startup login?

**Comment by agnostic-apollo** [comment]
Use failsafe session, either from desktop shortcut or from left drawer in termux by long pressing `NEW SESSION` button.

https://wiki.termux.com/wiki/Recover_a_broken_environment

**Comment by Maxython** [comment]
Yes, I know about this method, but it is rather inconvenient to enable this session to delete `login`.  I would re-implement deleting `login` in `profile`, but running `login` is higher.

**Comment by agnostic-apollo** [comment]
How many times are times are you messing up the `login` file that it is becoming inconvenient to open a failsafe session?

You aren't supposed to modify a core script, neither in termux nor in linux distros. If you are playing around with it, make `login` a wrapper script that calls your other modified version and if it fails, then continue running the termux default one.

**Comment by Maxython** [comment]
The problem is that the `login` from the arch of the `util-linux` package and in order for it to work, you need to run it with the `asl` command, and the `util-linux` package is also updated.  But it doesn't matter because I solved this problem.
