### ISSUE TITLE
[question] build bash from source

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-app#2213]
Hello,
If I want to build `bash` from source, what are the steps/configs to make sure it works with termux environment the same as the default termux's bash?

Thank you.

**Comment by Grimler91** [comment]
Have a look at the wiki pages about the [build environment](https://github.com/termux/termux-packages/wiki/Build-environment), how to [build a package](https://github.com/termux/termux-packages/wiki/Building-packages), and all the [builds scripts](https://github.com/termux/termux-packages/tree/master/scripts/build) (for details)
