### ISSUE TITLE
An editor on play store that violates GPL License

### ISSUE THREAD

**Issue by Yonle** [termux/termux-app#2216]
So a month ago, i found an editor called **Astro** at play store that used to edit & ran Javascript code with **NodeJS**.

Basically, the app has a terminal based of Termux. The app itself closed source. I found some of termux component related on this app as well. So i can say this app with the developer **Violates GPL License.**

Link to app: https://play.google.com/store/apps/details?id=com.astrosohu
![Screenshot_2021_0811_121325.png](https://user-images.githubusercontent.com/63401712/128975044-4dd17c34-030f-484e-a045-5c8a225e889f.png)

**Comment by Grimler91** [comment]
Ping @sohutek

**Comment by xeffyr** [comment]
Terminal emulator library is licensed under Apache 2.0 license which allows including the licensed component into closed source application without revealing all source code. Do not assume that GPLv3 == Apache 2.0 or any other open source license. They are different. See https://github.com/termux/termux-app/blob/master/LICENSE.md and https://github.com/termux/termux-app/blob/master/termux-shared/LICENSE.md.

As soon as "Astro" editor doesn't incorporate things licensed under GNU GPL (v2, v3), it should not reveal its sources but has to include the copyright notices about used components. Packages are another question however. At least this app doesn't use our repositories to deliver software to its users.

**Comment by xeffyr** [comment]
Apparently GPL violation still takes place. That's more like a drop-in copy of Termux components, without without license and even source code content.

Included GPLv3-only components:
```
./com/astrosohu/app/ExtraKeysView$a.smali
./com/astrosohu/app/ExtraKeysView$b.smali
./com/astrosohu/app/ExtraKeysView$c.smali
./com/astrosohu/app/ExtraKeysView$d.smali
./com/astrosohu/app/ExtraKeysView$e.smali
./com/astrosohu/app/ExtraKeysView$f.smali
./com/astrosohu/app/ExtraKeysView$g.smali
./com/astrosohu/app/ExtraKeysView$h.smali
./com/astrosohu/app/ExtraKeysView$i.smali
./com/astrosohu/app/ExtraKeysView$j.smali
./com/astrosohu/app/ExtraKeysView$k.smali
./com/astrosohu/app/ExtraKeysView$l.smali
./com/astrosohu/app/ExtraKeysView$m.smali
./com/astrosohu/app/ExtraKeysView$n.smali
./com/astrosohu/app/ExtraKeysView$o.smali
./com/astrosohu/app/ExtraKeysView$p.smali
./com/astrosohu/app/ExtraKeysView$q.smali
./com/astrosohu/app/ExtraKeysView.smali
./com/astrosohu/app/TermuxActivity$a.smali
./com/astrosohu/app/TermuxActivity$b.smali
./com/astrosohu/app/TermuxActivity$c.smali
./com/astrosohu/app/TermuxActivity$d.smali
./com/astrosohu/app/TermuxActivity$e.smali
./com/astrosohu/app/TermuxActivity$f.smali
./com/astrosohu/app/TermuxActivity$g.smali
./com/astrosohu/app/TermuxActivity$h.smali
./com/astrosohu/app/TermuxActivity$i.smali
./com/astrosohu/app/TermuxActivity$j.smali
./com/astrosohu/app/TermuxActivity$k.smali
./com/astrosohu/app/TermuxActivity$l.smali
./com/astrosohu/app/TermuxActivity$m.smali
./com/astrosohu/app/TermuxActivity$n.smali
./com/astrosohu/app/TermuxActivity$o.smali
./com/astrosohu/app/TermuxActivity$p$a.smali
./com/astrosohu/app/TermuxActivity$p$b.smali
./com/astrosohu/app/TermuxActivity$p.smali
./com/astrosohu/app/TermuxActivity.smali
./com/astrosohu/app/TermuxHelpActivity$a.smali
./com/astrosohu/app/TermuxHelpActivity.smali
./com/astrosohu/app/TermuxOpenReceiver$ContentProvider.smali
./com/astrosohu/app/TermuxOpenReceiver.smali
./com/astrosohu/app/TermuxService$a.smali
./com/astrosohu/app/TermuxService.smali
./com/astrosohu/filepicker/TermuxDocumentsProvider.smali
./com/astrosohu/filepicker/TermuxFileReceiverActivity.smali
```

I have also noticed references to our resources, which normally should never happen in forks:
```
com/astrosohu/app/TermuxHelpActivity$a.smali
55:    const-string p1, "https://wiki.termux.com"

com/astrosohu/app/v.smali
246:    const-string v2, "https://dl.bintray.com/termux/termux-packages-24"

com/astrosohu/app/TermuxHelpActivity.smali
132:    const-string v0, "https://wiki.termux.com/wiki/Main_Page"
```

**Comment by Yonle** [comment]
Well, Any update regarding this?

**Comment by agnostic-apollo** [comment]
Report the app on playstore for violating license/copy cat. That's the only thing reasonably doable. Unless someone wants to take the case to court depending on licensing laws of host country.

**Comment by Yonle** [comment]
Yeah. It's already a month and there's no update about it. Alright let's do it then

**Comment by Yonle** [comment]
Seems like it's still there, though i already report it, too.

**Comment by Yonle** [comment]
By the way maybe send DMCA would solve this issue quickly, or 🤷

**Comment by xeffyr** [comment]
@Yonle I've already sent report about this app and once more a bit later. Zero actions from Play Store staff side. I've also posted an application review with notification that it violates license and got shadow ban.

**Comment by Yonle** [comment]
By the way they have Discord community. Guess?

> What I really don't understand with this... crap (i.e. Google Play Store) is that their staff allows breaking guidelines in certain unknown cases 

You see that most apps in play store is mostly an adware or something like a rip off from Open source software. I really curious what Google staff does since this app violate the GPL License for a year right now. 

> btw, that's the reason why it still has malware published.

I agree with you. Some paid app can sometime a scam or something that contain malware. However, Like i said before, Most of their app contains adware that i can't count how many adware apps that they have.

**Comment by Yonle** [comment]
Three months without response from Google Play Store. Crap. Anyways bumping this issue back.

**Comment by sanikava** [comment]
This app is just editor and it only edits like nano or you can also use other editors 😅 but it's connected to do that and i don't think it copys any of termux components it just opening and running in separate termux

**Comment by agnostic-apollo** [comment]
>Three months without response from Google Play Store and the app still there. Crap.

Yeah, I don't expect any response from them. Social media/news shaming could be done, not sure what affect it will have. App isn't too popular either.

> i don't think it copys any of termux components it just opening and running in separate termux

https://github.com/termux/termux-app/issues/2216#issuecomment-898373316

You should read on how GPLv3 license works.

**Comment by sanikava** [comment]
> 

Ok it's just violating GPL but still play store have so many employees and they are still slow because of heavy traffic there are millions of apps there tho 🤔

**Comment by laughingwater** [comment]
Bruh they also copied ACode's UI too LMAO

**Comment by Damaj301damaj-lol** [comment]
![Screenshot_20220811-121303_ASTRO.png](https://user-images.githubusercontent.com/90093996/184101583-725062c5-9f8c-4e71-8edb-181d206847d3.png) the app requires termux to be installed :p

**Comment by Yonle** [comment]
This issue is now solved. Closing.
