### ISSUE TITLE
Issues with Python on Termux

### ISSUE THREAD

**Issue by StarshineLight** [termux/termux-app#2219]
**Problem description**

[The Torch (pyTorch) aarch64 (arm64) implementation](https://github.com/KumaTea/pytorch-aarch64)  **is not** working using the default Python library `pkg install python` on Termux (Python version 3.9.6). When importing the module, you get this issue: `OSError: dlopen failed: library "libgomp.so.1" not found`. [I reported the issue to the developer & maintainer of the pytorch aarch64 module](https://github.com/KumaTea/pytorch-aarch64/issues/10)  and their answer was as follows: "This situation could be expected, because Termux uses a customized minimal (i.e. incomplete) Linux environment, which means some components are missing. It could be solved (and I personally recommend) by using some App, like Andronix and AnLinux, to create a chroot environment, and provide a full Linux env.". **The issue is not found on linux container apps on android.** 
![129401306-8915db3c-2f08-4ddc-9c5f-3bf28bf8c2aa](https://user-images.githubusercontent.com/88848983/129403147-aa456398-8cd0-4ea1-b058-e24cc613e35c.jpg)
![129401317-d4963eac-679c-4c37-9d9a-7a4ab183f0d2](https://user-images.githubusercontent.com/88848983/129403153-8077f517-2c6a-4b43-b67d-6334a1100454.jpg)

**Steps to reproduce**

1. Install Termux
2. Execute `pkg install python`
3. Execute `pip install torch -f https://torch.kmtea.eu/whl/stable.html`
4. Execute `python`
5. Execute `import torch`

**Expected behavior**

Torch imports successfully.
![129401317-d4963eac-679c-4c37-9d9a-7a4ab183f0d2](https://user-images.githubusercontent.com/88848983/129403371-b446e6c4-20cd-4239-8ce5-7ac8ada75df0.jpg)

**Additional information**

* Termux application version: 0.101
* Android OS version: 9
* Device model: dream2lte (Samsung Galaxy S8+)

Credits to KumaTea for the screenshots and the help provided into troubleshooting this issue.

**Comment by xeffyr** [comment]
Expected behavior: https://wiki.termux.com/wiki/Differences_from_Linux. Native extensions should be built for Android OS, not for Linux distribution.

**Comment by StarshineLight** [comment]
Uhmm.. Could you clarify a little tiny more on how to solve this issue

**Comment by xeffyr** [comment]
You have only 2 ways to solve it:
* Build PyTorch specially for Termux, like any of our packages.
* Setup a chroot inside Termux, e.g. via `proot-distro`:
   ```
   pkg install proot-distro
   proot-distro install ubuntu-20.04
   proot-distro login ubuntu-20.04
   ```
   and only then install PyTorch inside chroot.
