### ISSUE TITLE
screen vibration cannot be disabled

### ISSUE THREAD

**Issue by immae** [termux/termux-app#222]
I tried to put "bell-character=ignore" in the termux proprerties, but the *screen* keeps shaking each time a bell character is given. This happens since version 0.44 or 0.45, and really makes the app unusable when there are a lot of events (for instance, when the bell is done at each irc message received...)

**Comment by fornwall** [comment]
Thanks for the feedback! I'll remove the experimental shaking-on-bell behaviour in minor v0.46 update which will be available as an update in a couple of hours (or within a day on F-Droid).

**Comment by immae** [comment]
Thanks!
