### ISSUE TITLE
Pip spam

### ISSUE THREAD

**Issue by StarshineLight** [termux/termux-app#2220]
**Problem description**

Pip spams the terminal when installing modules
![Screenshot_20210813-224817_Termux](https://user-images.githubusercontent.com/88848983/129411364-c5d69364-b0c3-422c-8cea-70667f4b0db4.jpg)

**Steps to reproduce**

Just install something using pip

**Expected behavior**

No spam

**Additional information**
My theory to why this happens is that Termux ignores some rewrite policies like (\r) on python.

* Termux application version: 0.117
* Android OS version: 9
* Device model: dream2lte

**Comment by agnostic-apollo** [comment]
Use quiet mode like with `--quiet`. This is not a termux issue. Look into `pip` docs  or help.

**Comment by xeffyr** [comment]
That's expected. Resize terminal to at least 80 columns so progress bar can fit into the screen width.
