### ISSUE TITLE
Bootstrap Error

### ISSUE THREAD

**Issue by XDSwang** [termux/termux-app#2221]
![VATE9}AZ4XD@4}_DM3402DP](https://user-images.githubusercontent.com/39626582/129432760-91a4dd44-6cfa-4136-a4c4-65e2dcb1dd13.png)

**Comment by agnostic-apollo** [comment]
Have you have rooted your device? Where is the other app and device info that appeared in the report? Copy it with 3 dot menu on top right and post it here.

Considering `include` directory wouldn't exist on fresh install (but may after "try again"), you are likely messing around with `root`. Either completely uninstall termux and reinstall it and start fresh or remove `usr-staging` directory from [failsafe session](https://wiki.termux.com/wiki/Recover_a_broken_environment) with `su -c 'rm -rf /data/data/com.termux/files/usr-staging'`. You may also want to delete `usr` directory with `su -c 'rm -rf /data/data/com.termux/files/usr'` or restore ownership with something like [this](https://github.com/termux/termux-app/issues/2080#issuecomment-846575028).

**Comment by xeffyr** [comment]
Could be related: https://www.reddit.com/r/termux/comments/bwmvz6/install_on_sd/, as well as https://github.com/termux/termux-app/issues/2238.

**Comment by arbaleast** [comment]
> Have you have rooted your device? Where is the other app and device info that appeared in the report? Copy it with 3 dot menu on top right and post it here.
> 
> Considering `include` directory wouldn't exist on fresh install (but may after "try again"), you are likely messing around with `root`. Either completely uninstall termux and reinstall it and start fresh or remove `usr-staging` directory from [failsafe session](https://wiki.termux.com/wiki/Recover_a_broken_environment) with `su -c 'rm -rf /data/data/com.termux/files/usr-staging'`. You may also want to delete `usr` directory with `su -c 'rm -rf /data/data/com.termux/files/usr'` or restore ownership with something like [this](https://github.com/termux/termux-app/issues/2080#issuecomment-846575028).

thanks a lot

**Comment by arbaleast** [comment]
https://unix.stackexchange.com/questions/206594/why-cant-i-delete-this-file-as-root

**Comment by agnostic-apollo** [comment]
Welcome. Did you manage to fix the issue?

**Comment by agnostic-apollo** [comment]
Install `v0.118.0+` and post errors if any.
