### ISSUE TITLE
cmd/go: go get

### ISSUE THREAD

**Issue by schwrzstrbn** [termux/termux-app#2223]
Updating golang's installation to a latest version via:

$ go get golang.org/dl/go1.17rc2
$ go1.17rc download

The last command returns "command not found".

Is there any solution to this? Am I missing something?

Termux v0.117

**Comment by agnostic-apollo** [comment]
Those downloads are for linux distributions and not for termux on android. Termux provides its own packages which you install via `apt`/`pkg`. Current version is `1.16.6`. You will have to wait for it to be updated or can request for an update at https://github.com/termux/termux-packages/issues

https://github.com/termux/termux-packages/commits/master/packages/golang
