### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gideonoffre** [termux/termux-app#2226]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android 
![Screenshot_20210815-162235](https://user-images.githubusercontent.com/88966989/129483746-6e348fd8-2ef5-48ee-af31-46c7a4b8a03c.png)
This keep I can't run apt update && apt upgrade

**Comment by agnostic-apollo** [comment]
termux/termux-packages#6726
