### ISSUE TITLE
termux is a shell for a android rom or linux kernel ?

### ISSUE THREAD

**Issue by jhonattanvargas** [termux/termux-app#223]
Hi, i have this question and i dont know what is the better place to ask it, i hope someone can help me :)

**Comment by fornwall** [comment]
Termux is both a terminal emulator (like xterm) and a collection of packages for Android (somewhat like a Linux distribution like Ubuntu or Fedora).

See e.g. http://linuxcommand.org/lc3_lts0010.php for more information.
