### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by thecowmilk** [termux/termux-app#2230]
### Problem description

Termux app in my android phone is very frustrating. I can't write to it at all! When I write words don't appear simultaneously as I type them and i can only see what I have wrote only after i press space or any other special character.

When I press dot for example "text.txt" it will duplicate word "text" and add it like this "text.text.txt". Its pretty frustrating and not user friendly. I want to use this app but this is making deleting it.

### Steps to reproduce the behavior.

Commands are:
"touch test.txt" (then press space)
You just have to write into terminal to see what I'm talking about.

### What is the expected behavior?

Normal writing, user friendly interface.

### System information

* Termux application version: 0.101
* Android OS version: 9
* Device model: Samsung Galaxy S8

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app/issues/686#issuecomment-681026810
