### ISSUE TITLE
[Bug]: Unable to copy the text in the bottom column

### ISSUE THREAD

**Issue by GitHubNeko** [termux/termux-app#2233]
### Problem description

Termux cannot copy any text in the bottom column

![Screenshot_20210822_232015_com termux](https://user-images.githubusercontent.com/83487691/130360741-3acad912-6644-4dde-a0ff-21340b8adaa0.jpg)

### Steps to reproduce the behavior.

Any command, but you must enter the command in the bottom column

### What is the expected behavior?

Hope to fix

### System information

* Termux application version: 0.117
* Android OS version: 9
* Device model: HUAWEI P10

**Comment by xeffyr** [comment]
Yes, I can confirm that for some reason menu box isn't shown when selecting the last line above keyboard or extra keys (if enabled).

**Comment by agnostic-apollo** [comment]
Yeah, that's a known issue. Will look into it.
