### ISSUE TITLE
[Bug]: Sliding my spacebar does not move the app cursor (it does in all other apps) on Samsung Galaxy A52

### ISSUE THREAD

**Issue by artisticfox8** [termux/termux-app#2234]
### Problem description

When I hold and slide my finger on the space bar on the Samsung keyboard, I can move the cursor left or right in all apps, except Termux.

### Steps to reproduce the behavior.

Open Termux on an Android 11 Samsung device, such as Samsung Galaxy A52.
write any text
hold the space bar, until the "cursor control" text appears.
move your finger left or right

### What is the expected behavior?

The cursor moves accordingly

### System information

* Termux application version: 0.101
* Android OS version: 11
* Device model: Samsung Galaxy A52

**Comment by xeffyr** [comment]
This is not a bug and also has been reported previously.

Rich features of keyboards are disabled when working in Termux, however you can try alternate input type field as workaround: https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View

**Comment by artisticfox8** [comment]
> This is not a bug and also has been reported previously.
> 
> Rich features of keyboards are disabled when working in Termux (console isn't text field and accepts raw key codes only), however you can try alternate input type field as workaround: https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View
Thanks, this looks fine. However, I still believe that every terminal should have an easy way to move the cursor. So, my other idea is adding left and right arrow buttons to the toolbar

**Comment by trygveaa** [comment]
> Thanks, this looks fine. However, I still believe that every terminal should have an easy way to move the cursor. So, my other idea is adding left and right arrow buttons to the toolbar

See https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row
