### ISSUE TITLE
[Bug]: when press enter, termux change the command line

### ISSUE THREAD

**Issue by LeCanardNoir** [termux/termux-app#2239]
### Problem description

![Screenshot_20210823-071038_Termux](https://user-images.githubusercontent.com/801372/130438332-edc05d73-c1a4-4608-ac37-363d486388c3.jpg)

### Steps to reproduce the behavior.

Just typing a command and press enter.
The line change by itself. 

### System information

* Termux application version: last
* Android OS version: 10
* Device model: samsung A70

Termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
apt/stable 2.3.8 aarch64 [upgradable from: 2.3.6]
command-not-found/stable 1.63 aarch64 [upgradable from: 1.62]
coreutils/stable 8.32-8 aarch64 [upgradable from: 8.32-7]
curl/stable 7.78.0 aarch64 [upgradable from: 7.77.0-3]
dash/stable 0.5.11.4 aarch64 [upgradable from: 0.5.11.3]
dialog/stable 1.3-20210621-0 aarch64 [upgradable from: 1.3-20210530-0]
diffutils/stable 3.8 aarch64 [upgradable from: 3.7-3]
libandroid-support/stable 28-1 aarch64 [upgradable from: 28]
libcurl/stable 7.78.0 aarch64 [upgradable from: 7.77.0-3]
libgnutls/stable 3.6.16 aarch64 [upgradable from: 3.6.15-3]
libidn2/stable 2.3.2 aarch64 [upgradable from: 2.3.0-2]
libnettle/stable 3.7.3 aarch64 [upgradable from: 3.7.2]
libnghttp2/stable 1.44.0 aarch64 [upgradable from: 1.43.0]
nano/stable 5.8 aarch64 [upgradable from: 5.7]
pcre/stable 8.45 aarch64 [upgradable from: 8.44-1]
termux-tools/stable 0.134 all [upgradable from: 0.130]
unrar/stable 6.0.7 aarch64 [upgradable from: 6.0.5]
Android version:
11
Kernel build information:
Linux localhost 4.14.190-21840848-abA715WVLU3CUF1 #1 SMP PREEMPT Wed Jun 9 21:57:46 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A715W

**Comment by xeffyr** [comment]
Related to keyboard autocorrection/autosuggestions.

**Comment by twaik** [comment]
Closing this due to the lack of activity. Seems like it was fixed but user did not post confirmation.

**Comment by salvalie** [comment]
This bug is still present in latest release even with that workaround applied

**Comment by robertkirkman** [comment]
> This bug is still present in latest release even with that workaround applied

If this is happening to you, could you try using this keyboard and let me know if it's still happening after you switch?

https://f-droid.org/en/packages/org.pocketworkstation.pckeyboard/

**Comment by salvalie** [comment]
It didn't happen with your keyboard but it does happen with Samsung one and also in foss simple keyboard
