### ISSUE TITLE
[Bug]: cant update debian the normal way, perl libcrypt.so.1 not there

### ISSUE THREAD

**Issue by fxmbsw7** [termux/termux-app#2241]
### Problem description

i tried ( as since ever ) update fresh deb, to more than stable sources ( as for me usual )
on the libc package ( see pic ) then it says on attempting to open perl for whatever, libcrypt.so not found
.. i tried dist-upgrade -t unstable, with stable, testing, unstable, and experimental sources on
.. this could be either a debian bug i dunno, i was disappointed to see err while it worked for forever
this is on a new install on new phone
plz help, need to free time code..
![Screenshot_2021-08-24-23-11-34-92](https://user-images.githubusercontent.com/39368685/130692386-2e83af7d-733c-4213-bb3c-3dc2497d291c.jpg)

### Steps to reproduce the behavior.

realme gt 5g, termux, debian install, ./start-deb

in /etc/apt/sources.list
i removed the -src line
and replaced the bullseye to four entries
the mentioned stable, testing, unstable, experimental
( i run such setup since 2002 )

then did apt-get update
and apt-get dist-upgrade -t unstable

then soon after downloading the err appears
im too depressed to investigate the issue
plz help

### What is the expected behavior?

the expected was an np upgrade to newer sw versions

### System information

* Termux application version: 0.117
* Android OS version: 11
* Device model: realme rmx2202 ( gt 5g )

**Comment by fxmbsw7** [comment]
i made it, by first dist-upgrade -t stable, then -t unstable

**Comment by twaik** [comment]
1. It is a repo of terminal emulatornot of anything related to program it executes.
2. We do not know what is `start-deb` script and what does it do.
3. We do not know how exactly you installed debian. The only supported way to install distributions is `proot-distro`. In the case if you have problems with proot-distro you should create issue in appropriate repo.
