### ISSUE TITLE
[Bug]: termux-file-editor now empty

### ISSUE THREAD

**Issue by Eli-the-Bearded** [termux/termux-app#2247]
### Problem description

Android 11, `$TERMUX_VERSION` shows 0.117.

Until recently I could `<` share photos from [F-Stop Gallery](https://play.google.com/store/apps/details?id=com.fstop.photo) with Termux and run my ~/bin/termux-file-editor to process the images. Something has changed, and I'm not sure if it is F-Stop doing things wrong, or Termux not handling F-Stop's new way of doing things.

According to the (shown in-app and impossible to link to) changelog for F-Stop 5.3.27:

   * When sharing file, F-Stop will also send Title. Useful for sharing to Whatsapp, for example

I see no other sharing changes in any 5.x version.

What happens now with Termux is the save file toast no longer shows a default filename and if I provide one manually, I get a zero length file. I have verified with another program that the old behavior, get a default filename and get a file saved in $HOME/downloads still works, so it is not 100% broken.

I've contacted F-Stop support, too, but I have not heard a response from them.

### Steps to reproduce the behavior.

Use F-Stop 5.3.27 (or probably newer) to share a file with Termux.

The changelog explicitly says 5.3.27 introduced new changes to F-Stop sharing.

### What is the expected behavior?

Shared files are received in Termux.

### System information

* Termux application version: 0.117 installed from F-Droid
* Android OS version: 11 (2021-08-01 security update)
* Device model: oneplusn10

**Comment by Eli-the-Bearded** [comment]
For the record, seeing this fixed in the F-droid version as of this week.

**Comment by agnostic-apollo** [comment]
Great! Thanks for reporting and feedback.
