### ISSUE TITLE
apk?

### ISSUE THREAD

**Issue by ghost** [termux/termux-app#2266]
### Problem description

where to find the apk file link?, after reading your whole essay im just frustrated provide me the apk file link in the first line of readme i guess, or provide me apk file link by quote reply here!!

### System information

* Termux application version: play store version
* Android OS version: android 10
* Device model: redmiY3

**Comment by xeffyr** [comment]
https://f-droid.org/repo/com.termux_117.apk ...

**Comment by SDRausty** [comment]
>either unpublished or replaced with stub

Stub is best, "Where'd it go?  Gone?!  404!  That's all we know," will not be an issue.

**Comment by nitin-ojha1** [comment]
> Download apk of Termux and not F-Droid itself.

to download something from f-droid we first need to dowload f-droid itself

amd ny f-droid crashed during the installation of termux, but no problem now, its fixed and i downloaded the termux apk succesfully

**Comment by SDRausty** [comment]
>to download something from f-droid we first need to dowload f-droid itself

No, this is not true.  Individual Termux-app APKs can be downloaded by just tapping the links on this page: 
https://f-droid.org/packages/com.termux/

**Comment by xeffyr** [comment]
> to download something from f-droid we first need to dowload f-droid itself

If devs didn't tell that you should install F-Droid first, then this is not necessary. You don't need F-Droid to download APK files. Visiting web site is enough.

https://user-images.githubusercontent.com/25881154/132946711-634c2604-d4d0-46d0-8607-7b93d8dc0e69.mp4
