### ISSUE TITLE
[Bug]: Missing android.permission.PACKAGE_USAGE_STATS permission

### ISSUE THREAD

**Issue by UnknownErrror** [termux/termux-app#2269]
### Problem description

When I tried to run ```/system/bin/dumpsys batterystats``` on my device, I got this:

```Permission Denial: can't dump OppoBatteryStatsService from from pid=5147, uid=10349 due to missing android.permission.PACKAGE_USAGE_STATS permission```

Termux app does not request ```android.permission.PACKAGE_USAGE_STATS``` permission, so this command fails

### Steps to reproduce the behavior.

Run ```/system/bin/dumpsys batterystats```

### What is the expected behavior?

Command works properly

### System information

* Termux application version: 0.117
* Android OS version: 11
* Device model: Realme 7

**Comment by agnostic-apollo** [comment]
Have you granted Termux  `android.permission.DUMP` with `adb shell pm grant com.termux android.permission.DUMP`?

**Comment by UnknownErrror** [comment]
Yes

**Comment by Sonyversion8** [comment]
> Yes

≥

**Comment by Sonyversion8** [comment]
≥
