### ISSUE TITLE
FR: Pause/Resume process

### ISSUE THREAD

**Issue by gerroon** [termux/termux-app#227]
Hi

I am not sure if this is possible but it would be nice to have a way to pause and resume processes running inside termux. We could have a button in the tray area where we have exit and wakelock buttons.

thanks

**Comment by BitNetwork** [comment]
Normally this can be achieved by `^Z` (Ctrl + Z) and `fg` to resume.

**Comment by vishalbiswas** [comment]
There is a `termux-wakelock` in termux-api now, which puts up a notification with Release and Exit as buttons.

**Comment by xeffyr** [comment]
> it would be nice to have a way to pause and resume processes

This can be achieved with signals:

* `kill -STOP {pid}` - Stop process with specified *pid* number.
* `kill -CONT {pid}` - Continue process with specified *pid* number.

**Comment by pros-per** [comment]
i made a mistake, must i start from scratch?
