### ISSUE TITLE
[Bug]: Fail to install on Android 8.1

### ISSUE THREAD

**Issue by fhoshino** [termux/termux-app#2270]
### Problem description

Failed to install, unknown error

![Screenshot_20210912-153121](https://user-images.githubusercontent.com/771955/132977979-48e14009-e8ec-4b45-b012-fcc9ab585c22.jpg)

### Steps to reproduce the behavior.

Try to install and failed

### System information

* Termux application version: 0.117
* Android OS version: 8.1
* Device model: Oneplus 5

**Comment by xeffyr** [comment]
Open Android Settings --> Applications, and delete every app named Termux, Termux:API, Termux:Boot, Termux:Float, Termux:Styling, Termux:Task, Termux:Widget. You need to delete all add-ons including old Termux app when changing installation source.

Only then try installing application from F-Droid.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation
