### ISSUE TITLE
[Bug]: termux-reload-settings not refreshing Termux app on properties change

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#2277]
### Problem description

customizing the termux properties file under $HOME and using termux-reload-settings no longer refreses the bottom helper bar. Termux must be closed (exit/logout) and relaunched for changes to take effect.

### Steps to reproduce the behavior.

edit $HOME/.termux/termux.properties
type termux-reload-settings

*nothing happens*

### What is the expected behavior?

bar at bottom (if helper keys change) should reconfigure and refresh to new termux-properties setup

### System information

* Termux application version: 0.117 F-Droid
* Android OS version: 11 (latest patches) - Samsung official
* Device model: Samsung Galaxy Note 20 U 5G

**Comment by agnostic-apollo** [comment]
Can't reproduce this on latest debug build. And the file is `termux.properties`, no dash `-`.

**Comment by nathaneltitane** [comment]
> Can't reproduce this on latest debug build. And the file is `termux.properties`, no dash `-`.

quick typing - sorry
Weird...
