### ISSUE TITLE
Issues with python module-scripts

### ISSUE THREAD

**Issue by martmists** [termux/termux-app#228]
Recently I found out that when module installed with python's `pip` can occasionally add command-line tools. 
However, due to termux files being located in `/data/data/com.termux/files`, the line `#!/usr/bin/env python3.5` does not work. 
This is also because in termux, python3.5 is just called `python`. Is there a way to get this fixed in any way?

**Comment by its-pointless** [comment]
termux-fix-shebang is a script that will fix the shebang...

**Comment by xeffyr** [comment]
Closing since `termux-exec` already adds support for standard shebangs.
