### ISSUE TITLE
[Bug]: Termux always crash

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/termux-app#2281]
### Problem description

It start recently. When I start termux for a time it will crashed. 

Note: I disable the auto kill and enable the waakelock , but still don't work

### Steps to reproduce the behavior.

Every time I start Termux

### System information

* Termux application version: 0.117
* Android OS version:10
* Device model: Vivo V2027(Y20)

**Comment by NoNameMan1231** [comment]
It happened for 2 times . At last time I restart my phone and got into bootloop. I worry it would happened again

**Comment by agnostic-apollo** [comment]
You haven't posted any error.

**Comment by NoNameMan1231** [comment]
But I can't remove the label!

**Comment by agnostic-apollo** [comment]
What label are you talking about? The red `bug report` label?

Post the error for which you created this issue, otherwise issue will be closed.

**Comment by NoNameMan1231** [comment]
Ya

**Comment by Grimler91** [comment]
If "crash" is the red text shown for outdated termux versions then there is no issue here. Read the text and follow the instructions.

**Comment by agnostic-apollo** [comment]
He wrote `0.117` as termux version so I assumed the banner was not the issue.

**Comment by Grimler91** [comment]
We need more info I guess (termux-info output, logcat output, screenshots (if applicable))
