### ISSUE TITLE
[Bug]: System crash when changing storage location.

### ISSUE THREAD

**Issue by CastorDYvaine** [termux/termux-app#2290]
### Problem description

I have a new Motorola moto e7 onto which i installed termux.
I now have got 8GB worth of executables in termux.
I was attempting to change storage location to the sdcard (Speed 4, formatted as internal storage extension), at about 20% through moving my system automatically restarted into a bootloop.
I have been able to repeat this a couple times.
Im running Android 10 with termux 0.101.

### Steps to reproduce the behavior.

Change termux storage location to sdcard (You need it formatted as an extension of the internal storage) in system settings > wait until it reaches approx 20%.

### What is the expected behavior?

Android System crash > bootloop.

### System information

* Termux application version: 0.101
* Android OS version: 10
* Device model: motorola moto e7

**Comment by xeffyr** [comment]
External storage is unsupported: https://github.com/termux/termux-app/blob/4f66786b987d1846d42cb1dba542bbfe821b4a37/app/src/main/AndroidManifest.xml#L5. Android system crash points on ROM bug, fixing which is beyond the scope of Termux development. I even wonder why Android allowed you to move the application.

Any manipulations with your Android OS, storage and things unsupported by Termux should be done on your own risk.

**Comment by CastorDYvaine** [comment]
It seems i had enabled  "force allow apps to external" in android debugging settings.
Thanks.
