### ISSUE TITLE
[Bug]: unable to uninstall packages and show them on new version

### ISSUE THREAD

**Issue by Catawbas** [termux/termux-app#2294]
### Problem description

so I tried to install node.js by doing pkg install nodejs
I wanted to install herokucli on termux I have done this before with older versions so many times but now after trying npm install -g heroku it showing its problem with npm and now I can't even switch to older versions since older version(playstore) not receiving updates 

### Steps to reproduce the behavior.

install any package 
after that try doing pkg show package name 
you will see errors 
if you try to uninstall it you will see same error 

### What is the expected behavior?

pkg show git 
should show pkg info not error

### System information

* Termux application version:0.117
* Android OS version:11
* Device model:Samsung a21s

**Comment by agnostic-apollo** [comment]
>Issues without proper description will be closed without solution.

No error info provided.
