### ISSUE TITLE
[Bug]: can't install on android 9

### ISSUE THREAD

**Issue by Tritoapriansyah** [termux/termux-app#2298]
### Problem description

![Screenshot_2021-09-26-06-59-29-89_a812e245fcf1a37fd6842cccf825bab5](https://user-images.githubusercontent.com/48681738/134788915-3a14ae2f-ec2a-4abc-840e-1a455b631719.jpg)

### Steps to reproduce the behavior.

.

### System information

* Termux application version:117
* Android OS version:9
* Device model:CPH1923

**Comment by Tritoapriansyah** [comment]
![Screenshot_2021-09-26-07-17-56-56](https://user-images.githubusercontent.com/48681738/134789004-f9bc0c9e-c764-435a-b8ec-cb326c7b361c.jpg)

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation
