### ISSUE TITLE
ranger doesn't launch

### ISSUE THREAD

**Issue by sekret1** [termux/termux-app#23]
I installed several packages, all of them work fine except ranger crashes with the following message:

**Comment by sekret1** [comment]
anger
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ranger", line 38, in <module>
    import ranger
ImportError: No module named 'ranger'

**Comment by sekret1** [comment]
OK, it's horrible to do this by phone! ;-) Here's the complete output

$ ranger
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ranger", line 38, in <module>
    import ranger
ImportError: No module named 'ranger'

**Comment by fornwall** [comment]
Hi, I just made a fix for the ranger package, could you update to the latest version (execute `apt update && apt upgrade`) and see if the problem remains?

If the problem remains, could you write the output of running `uname -a` and `find $PREFIX -name ranger` here, as well as write which Android version and device you are running on?

**Comment by sekret1** [comment]
Hi there, now it runs fine! :-) Thanks!

And yes, I should have provided that info ... It's stock CyanogenMod 12.1-20151117 (current snapshot) on my serranoltexx (Samsung Galaxy S4 Mini)

**Comment by Fmert24** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ranger", line 36, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ModuleNotFoundError: No module named 'ranger'
