### ISSUE TITLE
Add ability to open more than one terminal

### ISSUE THREAD

**Issue by trufae** [termux/termux-app#231]
Having app-level splits (not requiring tmux) or at least being able to have more than one shell (like Material Terminal, or other android terminals do) out there will be very handy because switching between panes will be more natural and native. I can rebuild the app with a different pkgname to load the app twice and use the multi-window system feature (on android7 or remixOS) to have more than one termux terminal opened.. but i would prefer not to do hacks to get more than one terminal opened. (specially on remixOS)

**Comment by Neo-Oli** [comment]
You can already open more than one terminal by opening the navigation drawer (swiping from the left) and tap on "NEW SESSION". Does that work for you?

**Comment by trufae** [comment]
Oh wow! Didnt knew this hidden magic. Also found that control+alt+num are the keys to switch betweent them. Nice!

The longpress in keyboard button to toggle the extra keys is not something that i expected either but its nice.

Maybe this should be more visible. Like showing an option in the More menu of the longpress event.

I also find it hard to change the font size without a touchscreen that supports pinch. 

Anyway thanks for this great app and ecosystem :) it really makes android useful for me

**Comment by trygveaa** [comment]
> I also find it hard to change the font size without a touchscreen that supports pinch.

If you have a hardware keyboard (which it seems like you do, since you mention ctrl+alt), you can use ctrl+alt++ and ctrl+alt+- to change the font size. See more shortcuts here: https://termux.com/hardware-keyboard.html

**Comment by PwnicornDev** [comment]
I think it would be good to show the drawer on the first run, like other apps do.

**Comment by trufae** [comment]
also, using horizontal swipe (or swipe from the right corner) to go to the next or previous terminal would be nice. maybe we can also enable this behaviour for the left corner if the swipe starts at the top or botom part of the screen.. or maybe just consider the horizontal swipe on the top of the screen as a gesture to go to the next or previous terminal.

**Comment by grepper** [comment]
I think a horizontal swipe is a great idea, and it would be similar to what is implemented on 'Android Terminal Emulator' and similar apps other apps based on it. Granted you could not do a swipe from left as that brings up the navigation drawer currently, but a wrap around right swipe would be okay.
I find I can not find a keybinding to switch terminals using a 'soft' keyboard - ctrl+alt+NUM does not work, at least using 'hackers keyboard' app.

p.s.
thanks for an amazing app!

**Comment by Neo-Oli** [comment]
Closing this, because the original issue is resolved
@trufae @grepper You can subscribe to the issue about switching terminals by swiping here: https://github.com/termux/termux-app/issues/48

**Comment by giabao87** [comment]
how to open more than 8 of numbers in termux. Can open 10 or 15 windows. who can help me with that?

**Comment by giabao87** [comment]
So the termux application can only open 8 windows. Can not open more than
is not you

Vào 1:29 Th 4, 12 thg 12 2018 Leonid Plyushch <notifications@github.com đã
viết:

**Comment by DaBoss5** [comment]
You can take advantage of termux's ability to pick up intents and pass it on to termux-url-opener (this script will run in its own terminal window, even if you have 8 windows open), and do this:

Modify your termux-url-opener (in ~/bin):
From your code to:
  if [ "$@" == "TabLimitIncrease.xyz" ]
  then
      bash #or whatever shell you use
   else
       #rest of your code or leave blank
   fi

Then create a $PREFIX/bin/tab, and add this code to it:
#!/data/data/com.termux/files/usr/bin/bash

am start -a android.intent.action.SEND --es android.intent.extra.TEXT TabLimitIncrease.xyz -t text/plain com.termux &> /dev/null

Then set it to executable using chmod +x $PREFIX/bin/tab


After that you can just type tab and press enter to open new tabs beyond the limit

**Comment by Kilo-411** [comment]
That was i big help.. I found this discussion very helpful. I was just glancing through .. Im gonna do some more reading on topics i aint read.

**Comment by rajesh6432** [comment]
i'am getting this error
can you help me
/data/data/com.termux/files/home/bin/termux-url-opener: 7: /data/data/com.termux/files/home/bin/termux-url-opener: Syntax error: "fi" unexpected

**Comment by PRINCE-MRJ** [comment]
> You can take advantage of termux's ability to pick up intents and pass it on to termux-url-opener (this script will run in its own terminal window, even if you have 8 windows open), and do this:
> 
> Modify your termux-url-opener (in ~/bin):
> From your code to:
> if [ "$@" == "TabLimitIncrease.xyz" ]
> then
> bash #or whatever shell you use
> else
> #rest of your code or leave blank
> fi
> 
> Then create a $PREFIX/bin/tab, and add this code to it:
> #!/data/data/com.termux/files/usr/bin/bash
> 
> am start -a android.intent.action.SEND --es android.intent.extra.TEXT TabLimitIncrease.xyz -t text/plain com.termux &> /dev/null
> 
> Then set it to executable using chmod +x $PREFIX/bin/tab
> 
> After that you can just type tab and press enter to open new tabs beyond the limit
> ![Screenshot_20190310-225307](https://user-images.githubusercontent.com/25087116/54092732-7ee39200-4387-11e9-9a10-e00f2ef0fdd7.png)

Hey bro do u have a YouTube channel or any where I can find a video for that coz have failed to get it in writing

**Comment by Quasic** [comment]
> i'am getting this error
> can you help me
> /data/data/com.termux/files/home/bin/termux-url-opener: 7: /data/data/com.termux/files/home/bin/termux-url-opener: Syntax error: "fi" unexpected

Try removing else

**Comment by codecreate-dev** [comment]
I didn't know about the swipe left either. I just googled on the off chance someone managed to maybe get a second session open.

Damn, why isn't this flagged as a major feature???

This solves the major issue when coding, having to close each file to edit a different one. I can't believe this has been a feature sitting here all this time lol.

Termux with Neovim is now a decent mobile IDE for web dev.

**Comment by trygveaa** [comment]
> This solves the major issue when coding, having to close each file to edit a different one. I can't believe this has been a feature sitting here all this time lol.
> 
> Termux with Neovim is now a decent mobile IDE for web dev.

Why would you use multiple terminal windows to edit multiple files in neovim? You can open as many files as you want at the same time in neovim, which is much more practical.

**Comment by codecreate-dev** [comment]
Can you? As is evident, I am very new to Termux and nvim ... previously was a Geany user then Visual Studio.

I used to use nano but recently moved to vim/nvim. Something tells me I am in need of nvim RTFM time !
