### ISSUE TITLE
[Feature]: Close keyboard when clicking in the background

### ISSUE THREAD

**Issue by cdhiraj40** [termux/termux-app#2314]
### Feature description

Activities do not support closing the keyboard when clicking in the background, having this feature will def make a better user experience

### Additional information

https://github.com/cdhiraj40/enviroCar-app
and just got approval to add this in https://github.com/cdhiraj40/AntennaPod

**Comment by agnostic-apollo** [comment]
What "background" are you referring to?

Tapping the terminal text area [opens the keyboard if it's closed](https://github.com/termux/termux-app/blob/dcedf394343f97284359f33a52e264089a335751/app/src/main/java/com/termux/app/terminal/TermuxTerminalViewClient.java#L174), just like normal edit text fields in android. No reason to close it for that when tapping and termux app doesn't even know if keyboard is open anyways. You can use `KEYBOARD` extra key to toggle the keyboard.

**Comment by cdhiraj40** [comment]
> What "background" are you referring to?
> 
> Tapping the terminal text area [opens the keyboard if it's closed](https://github.com/termux/termux-app/blob/dcedf394343f97284359f33a52e264089a335751/app/src/main/java/com/termux/app/terminal/TermuxTerminalViewClient.java#L174), just like normal edit text fields in android. No reason to close it for that when tapping and the termux app doesn't even know if the keyboard is open or closed anyways (unless disabled). You can use the `KEYBOARD` extra key to toggle the keyboard.
> 
> https://wiki.termux.com/wiki/Touch_Keyboard

I was referring to the terminal text area only 
I just thought it would be good the way it opens the keyboard when clicked in the terminal it closes too. If you approve then only I work. thanks :)

**Comment by agnostic-apollo** [comment]
The terminal text area is an edit text field itself, it is not the background. When you type in a edit text field, like url in a browser or in chats, tapping it again doesn't close keyboard, it stays open. That's the current termux behaviour and must not be changed by default. Even if more users request toggling, a `termux.properties` property would need to be added for it and then changes tested rigourously since keyboard logic is quite complex in termux, read the keyboard logic in the file linked above, it's near the bottom. Also check https://github.com/termux/termux-app/pull/2114#issuecomment-855389029.

**Comment by cdhiraj40** [comment]
> The terminal text area is an edit text field itself, it is not the background. When you type in a edit text field, like url in a browser or in chats, tapping it again doesn't close keyboard, it stays open. That's the current termux behaviour and must not be changed by default. Even if more users request toggling, a `termux.properties` property would need to be added for it and then changes tested rigourously since keyboard logic is quite complex in termux, read the keyboard logic in the file linked above, it's near the bottom. Also check [#2114 (comment)](https://github.com/termux/termux-app/pull/2114#issuecomment-855389029).

okay, I read it and understood the behavior. thanks for the help. according to you are there any issues where I can work on it? would love to contribute :)

**Comment by SDRausty** [comment]
>tapping it again doesn't close keyboard, it stays open. That's the current termux behaviour and must not be changed by default. Even if more users request toggling,

+1 for current termux behaviour

**Comment by agnostic-apollo** [comment]
>are there any issues where I can work on it?

There are a lot of issues open for `termux-app` and the other termux plugin apps, you can look into those and see what you can actually implement.
