### ISSUE TITLE
[Feature]:

### ISSUE THREAD

**Issue by johsacher** [termux/termux-app#2315]
### Feature description

How can I configure touch events as mouse events? Being able to move cursor by tapping. This was enabled by default in playstore version.

### Additional information

people asked about it in posts, but now answer how to switch behavior to "touch emulates mouse":
*** https://www.reddit.com/r/termux/comments/pi2igz/some_tap_in_the_terminal_features_work_others_dont/

**Comment by xeffyr** [comment]
For now touch events are only handled as mouse clicks or wheel, both variants work only in alt buffer applications like wheel. So tapping shouldn't be an issue. It works in `vim` and `nvim`. Bash doesn't support cursor movement by mouse clicks.

Full mouse support like dragging is available only with hardware mouse (tested with `tmux` + mouse connected via USB-OTG).

**Comment by xeffyr** [comment]
Here is how mouse click work:

https://user-images.githubusercontent.com/25881154/135839889-4c8cbd22-7cf2-4221-aab9-fb420ee9a078.mp4

**Comment by johsacher** [comment]
thank you for quick reply!
it works in vim indeed.
i m heavy emacs user, in emacs it does not work by default. so i guess it s emacs' responsibility to make that work. i ll try to figure it out via emacs configuration.

**Comment by Grimler91** [comment]
We set some (mouse-)scroll related settings in [site-init.el](https://github.com/termux/termux-packages/blob/master/packages/emacs/site-init.el), maybe there are other options that should be set there

**Comment by RalfWerner** [comment]
> it works in vim indeed.

@johsacher `mc` (**m**idnight **c**ommander: **m**ost **c**omfortable **m**ouse/finger **c**ontrol) also supports cursor position by finger tap

**Comment by xeffyr** [comment]
This still appears to be an issue. Termux packages the `site-init.el` into `emacs` package and places it at
```
$PREFIX/share/emacs/27.2/lisp/emacs-lisp/site-init.el
```

Content:
```
; Enable terminal mouse events:
(xterm-mouse-mode 1)
(global-set-key [mouse-4] 'scroll-down-line)
(global-set-key [mouse-5] 'scroll-up-line)
```

So it seems to be not picked if mouse doesn't work without manual config.
