### ISSUE TITLE
coreutils: tail not behaving properly with -c and no file argument

### ISSUE THREAD

**Issue by st42** [termux/termux-app#232]
The following command doesn't work properly
`echo -n 123456 | tail -c 3`
This should output `456`
Instead its trying to open a file named 3
It give the following error
`tail: cannot open '3' for reading: No such file or director`

**Comment by fornwall** [comment]
Hm, interesting. This is tails from coreutils.

1. The `-c` parameter does work when no FILE parameter is specified, but `echo -n 123456 | tail -c 3 -` workd.

2. Using the longer parameter `--bytes` work in `echo -n 123456 | tail --bytes 3`.

**Comment by fornwall** [comment]
Thanks a lot for reporting the issue! This has now been fixed in version `8.26-1` of the coreutils package, to which you can update with:

    apt update && apt upgrade
