### ISSUE TITLE
[Bug]: [Resolved] Install Failed on MIUI 12.5 base on Android 11

### ISSUE THREAD

**Issue by aojie654** [termux/termux-app#2329]
### Problem description

Could not install Termux 0.117 on MIUI 12.5 based Android 11 (which should be supported)

### Steps to reproduce the behavior.

1. Install directly via the APK file downloaded from F-Droid, failed
2. Install via F-Droid, failed
3. Install via SPI (which could tell me the fail reason), failed with reason: INSTALL_FAILED_SHARED_USER_INCOMPATIBLE
4. Based on the findings from [XDA: install failed shared user incompatible](https://forum.xda-developers.com/t/solved-install-failed-shared-user-incompatible.1219029/) I think may be I should try to uninstall something with ADB
5. Connect my phone to computer, run the command:
``` zsh
adb shell pm list packages -f | grep termux
```
I found there are some thing like:
``` zsh
package:/data/app/....../base.apk=com.termux.styling
```
I think maybe the problem is here.
6. Try to uninstall with adb:
``` zsh
adb uninstall com.termux.styling
```
Tips me sucess:
``` zsh
Success
```
7. Reinstall Termux on phone (for install via ADB will be blocked by MIUI), success.

### System information

* Termux application version: 0.117
* Android OS version: MIUI 12.5 based on Android 11
* Device model: Xiaomi Mi10 (umi)

**Comment by xeffyr** [comment]
@aojie654 What the point of claiming something when you even didn't read it? https://github.com/termux/termux-app#installation

**Comment by agnostic-apollo** [comment]
It takes great skill to go to `termux-app` `README` and squint your eyes just enough to see only the `Issues` link and not the `Installation` link in `Contents` at the top. And then open a long issue, often with a rant and often without even seeing pinned issues or searching existing ones.

**Comment by mashirozx** [comment]
Same issue, and thanks for your suggestions, they just work. I used to install Termux from Google Play and also installed few plugins (style and API), after remove them I am able to install the latest Termux with ADB.
