### ISSUE TITLE
coreutils: tail still not behaving properly with -c and no file argument

### ISSUE THREAD

**Issue by st42** [termux/termux-app#233]
I upgraded to version `8.26-1` of coreutils
`echo -n 123456 | tail -c 3`
Now gives the following error
`tail: 'standard input': cannot seek to relative offset 0: Illegal seek`

`echo -n 123456 | tail -c 3 -`
`echo -n 123456 | tail --bytes 3`
Also give the same error

I tried the following with included busybox and get the appropriate output
`echo -n 123456 | busybox tail -c 3`
`echo -n 123456 | busybox tail -c 3 -`
`--bytes` option with busybox isn't available

**Comment by fornwall** [comment]
Interesting - it seems to work on aarch64, but not on 32-bit arm.

**Comment by fornwall** [comment]
This issue seems to result from `src/tail.c` in coreutils, in the `tail_bytes` function:

```C
      off_t end_pos = ((! presume_input_pipe && usable_st_size (&stats)
                        && n_bytes <= OFF_T_MAX)
                       ? stats.st_size : -1);
      if (end_pos <= ST_BLKSIZE (stats))
        return pipe_bytes (pretty_filename, fd, n_bytes, read_pos);
```

Here end_pos is -1, but the `ST_BLKSIZE` macro defined in `lib/stat-size.h`:

```C
# define ST_BLKSIZE(statbuf) ((0 < (statbuf).st_blksize \
                               && (statbuf).st_blksize <= ((size_t)-1) / 8 + 1) \
                              ? (statbuf).st_blksize : DEV_BSIZE)
```

 resolves into an unsigned long on 32-bit android (due to how the `st_blksize` field is defined there), so we have a -1 to unsigned comparison.

**Comment by fornwall** [comment]
@st42 Thanks for the informative report! The coreutils package has been updated to version `8.26-2` which should fix this issue, update to it with:

    apt update && apt upgrade
