### ISSUE TITLE
[Bug]: Download failed!

### ISSUE THREAD

**Issue by HeavymetalHorseman** [termux/termux-app#2330]
### Problem description

I had Termux from the Play Store installed and fully updated. Then I got a message from Termux saying that it's going to be discontinued in the Play Store, that I must follow the Wiki, and reinstall Termux from F-Droid. I followed the Wiki, but errors showed up in my Termux (telling me that it was corrupted), so I uninstalled it instead. Then I went to F-Droid to install the most current version of Termux. It wouldn't let me, it just said 'Download failed!' I want to fix this issue, but don't know what to do. Can I get some help please? 

### Steps to reproduce the behavior.

Download Termux from F-Droid.

### What is the expected behavior?

Download failed!

### System information

* Termux application version: Forgot to write it down before uninstalling it, sorry.
* Android OS version: Android 10
* Device model: Moto G7

**Comment by agnostic-apollo** [comment]
You must uninstall termux and all the plugins before installing. If F-Droid app itself is causing trouble and not installing termux, then download APK directly from site https://f-droid.org/en/packages/com.termux/

https://github.com/termux/termux-app#installation
