### ISSUE TITLE
[Bug]: pkg list adds line

### ISSUE THREAD

**Issue by factorial52** [termux/termux-app#2334]
### Problem description

pkg list adds a line at the start of the output which reads "Listing... Done" This throws off scripts, wc, etc.

As stated in the GNU coreutils documentation "Programs should never print extraneous header or trailer data, since these could get sent on down a pipeline."

It appears that apt list does the same thing, so I suspect this is an upstream issue. If those devs are sticky about it, maybe it could be patched out for the pkg command.

### Steps to reproduce the behavior.

pkg list-installed, pkg list-all

### System information

* Termux application version:0.117
* Android OS version:RQ3A.211001.001
* Device model:

**Comment by agnostic-apollo** [comment]
The `pkg` command in termux is just a wrapper script for `apt`.

https://github.com/termux/termux-packages/blob/master/packages/termux-tools/pkg#L195

However, `apt` output is not meant to be parsed by scripts like it can be for `apt-get` or `dpkg` commands. Use `dpkg` to list packages.

https://unix.stackexchange.com/questions/590699/should-i-use-apt-or-apt-get-in-shell-scripting

https://askubuntu.com/questions/1179938/what-is-the-script-able-equivalent-to-the-user-command-apt-list-installed
