### ISSUE TITLE
Termux doesn't work on android 7.1 or later

### ISSUE THREAD

**Issue by hungryseashell** [termux/termux-app#234]
After upgrading my phone to android 7.1 or 7.1.1 this error msg greets me and I cannot use termux at all:

```
CANNOT LINK EXECUTABLE "-bash": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...

[Process completed (signal 6) - press Enter] 
```

As I said in 7.0 it worked.
The soc on the phone is a 64bit mediatek one.

**Comment by fornwall** [comment]
Which device is this? Are you running a custom ROM or stock?

**Comment by hungryseashell** [comment]
It is the Jiayu S3 with mediatek MT6752 SOC.
The ROM is a custom AOSP one.

Can you or anyone confirm if termux works on other android 7.1 phones/ROMs?

**Comment by fornwall** [comment]
I can confirm that Android 7.1 works on Nexus and Pixel devices.

Do you have more information about the custom ROM (link to thread or sources)?

**Comment by hungryseashell** [comment]
I think the ROM sources are here: https://github.com/MediatekAndroidDevelopers/

The thread is here: https://forum.xda-developers.com/jiayu-s3/development/rom-unofficial-aosp-n-jiayu-s3-t3451923


Also I found confirmation that termux doesn't work on an other phone's ROM from the same developement team. [here](https://forum.xda-developers.com/showpost.php?p=70249278&postcount=75)

**Comment by yenon** [comment]
I had a similar issue, although it appeared after restoring the app with oandbackup. It seems like oandbackup (and probably other backup softwares) doesn't like symlinks. Try backing up the app and see if it works after wiping the app data.

**Comment by fornwall** [comment]
@yenon Interesting, thanks for the information about backup software and symlinks.

@hungryseashell: Could this be relevant here, have you used any backup software that could affect Termux?

**Comment by hungryseashell** [comment]
Ok, it seems like a ROM issue for me. I tried an other 7.1 ROM, restored termux from backup and it worked without any issue.
