### ISSUE TITLE
[Bug]: npm ERR! code EACCES when doing "npm i"

### ISSUE THREAD

**Issue by 1rens1** [termux/termux-app#2363]
### Problem description

Hi, I was just cloning my node project to my phone so it can run 24/7.
But when I do `npm i`, npm gives a `code EACCES`.
I have googled and searched [termux issues](https://github.com/termux/termux-packages/issues) but non of them solved my problem...

```
~/.../Directory $ npm i
npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path ../detect-libc/bin/detect-libc.js
npm ERR! dest /storage/emulated/0/Directory/node_modules/.bin/detect-libc
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '../detect-libc/bin/detect-libc.js' -> '/storage/emulated/0/Directory/node_modules/.bin/detect-libc'
npm ERR!  [Error: EACCES: permission denied, symlink '../detect-libc/bin/detect-libc.js' -> '/storage/emulated/0/Directory/node_modules/.bin/detect-libc'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../detect-libc/bin/detect-libc.js',
npm ERR!   dest: '/storage/emulated/0/Directory/node_modules/.bin/detect-libc'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-10-27T23_53_27_850Z-debug.log
```

### What steps will reproduce the bug?

`npm i` (on a nodejs project)

### What is the expected behavior?

npm will download the necessary packages and will not receive `code EACCES`

```
~/.../Directory $ npm i

added 136 packages, and audited 137 packages in 3m

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

### System information

* Termux application version: v0.117 from [F-Droid](https://f-droid.org/en/packages/com.termux/)
* Android OS version: 11
* Device model: SM-A107F

```
~ $ termux-info
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.127-21859993 #1 SMP PREEMPT Tue Jul 20 09:06:23 +07 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-A107F
```

**Comment by nikeedev** [comment]
I get different error. And i do have the project in home(`~`) directory, but still says that the cache folder lies in a root-owned folder. That folder (`.npm`), lies in the same home directory.

**Comment by nikeedev** [comment]
Here is the error i get:

```
npm ERR! code EACCES
npm ERR! syscall link
npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/5cfde819
npm ERR! dest /data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/32/bd/197224773201aee7f472a236d2e44c2f28bdb84170fd5c8f0be2ce678f500a8511598f236f407ecad74ca3046deb00b674e0fde69043b05cb9a5c0c9ca69
npm ERR! errno EACCES
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 10400:10400 "/data/data/com.termux/files/home/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-07-05T19_56_17_495Z-debug-0.log```

**Comment by james122207** [comment]
you guys solved it?please let me know how did you solve it, thanks!

**Comment by nikeedev** [comment]
> you guys solved it?please let me know how did you solve it, thanks!

I believe this should help: https://github.com/termux/termux-app/issues/2363#issuecomment-953494320

It didn’t for me, so that’s why I keep waiting for an answer.

**Comment by james122207** [comment]
> > you guys solved it?please let me know how did you solve it, thanks!
> 
> I believe this should help: [#2363 (comment)](https://github.com/termux/termux-app/issues/2363#issuecomment-953494320)
> 
> It didn’t work for me, so that’s why I keep waiting for an answer.

didn't work for me too..

**Comment by DorukAysor** [comment]
> Here is the error i get:
> 
> ```
> npm ERR! code EACCES
> npm ERR! syscall link
> npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/5cfde819
> npm ERR! dest /data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/32/bd/197224773201aee7f472a236d2e44c2f28bdb84170fd5c8f0be2ce678f500a8511598f236f407ecad74ca3046deb00b674e0fde69043b05cb9a5c0c9ca69
> npm ERR! errno EACCES
> npm ERR!
> npm ERR! Your cache folder contains root-owned files, due to a bug in
> npm ERR! previous versions of npm which has since been addressed.
> npm ERR!
> npm ERR! To permanently fix this problem, please run:
> npm ERR!   sudo chown -R 10400:10400 "/data/data/com.termux/files/home/.npm"
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-07-05T19_56_17_495Z-debug-0.log```
> ```

Some latest solutions up there?...

**Comment by khaledafnouch** [comment]
use yarn insteed without ''i''
you only type '' yarn ''

**Comment by nasyx-rakeeb** [comment]
Its easy to solve, all you need to do is do `npm i` in your termux home directory, you can go to termux home directory with this command: `cd $HOME` then simply clone or create a nodejs project there and install the packages, then you will need acode code editor to edit the code files

**Comment by lanss-id** [comment]
@nasyx-rakeeb thanks a lot bro, im get all fixed for long time bug like this. 
If im not see your comments, i'll have error forever

**Comment by Simx303** [comment]
> As of v7.13, you can set node-linker=hoisted in a .npmrc in the root of your project. pnpm will create a flat node_modules like the one created by npm or Yarn, without using symlinks at all.[SO]( https://stackoverflow.com/a/65638449)

so then you can juat use pnpm without symlinks
