### ISSUE TITLE
[Feature]: Add ability to set `$TERM` through `termux.properties`

### ISSUE THREAD

**Issue by gustav-b** [termux/termux-app#2367]
### Feature description

I would like to be able to set the `TERM` environment variable to another value than the default `xterm-256color`, e.g. to `xterm`. If I understand [the code](https://github.com/termux/termux-app/blob/94e01d68d6c915740f6d2a1f7ea1bcdb6bf1f0d5/termux-shared/src/main/java/com/termux/shared/shell/TermuxShellUtils.java#L60) correctly, the value is currently hard coded. It would be nice if this could be overridden through a `termux.properties` setting.

### Additional information

Some other terminal emulators like iTerm2 and Alacritty have this setting.

**Comment by xeffyr** [comment]
Is it not possible to set this value through ~/.bashrc or other shell-apecific configuration file? This value is only environment variable.

Just to note that Termux does not support emulating different terminal types and xterm-256color is sufficient.

**Comment by gustav-b** [comment]
Thanks for your reply and thanks for Termux,

> Is it not possible to set this value through ~/.bashrc or other shell-apecific configuration file? This value is only environment variable.

Yea, it's possible as it's just an environment variable. I would however argue that it's not a shell-specific variable but a terminal-specific one. My bash configuration file is executed by Bash run under multiple terminal emulators: iTerm2, rxvt, Termux, etc. I could set `$TERM` conditionally in `~/.bashrc` by guessing the terminal being used, but that feels a bit backwards.

> Just to note that Termux does not support emulating different terminal types and xterm-256color is sufficient.

Got it. But I guess it supports xterm with just 16 colors too?
