### ISSUE TITLE
[Bug]: side stripes in landscape mode using MatePad 11 on HarmonyOS 2.0

### ISSUE THREAD

**Issue by gkorzhuk** [termux/termux-app#2368]
### Problem description

Hello! I'm trying to use my new MatePad 11 as road warrior terminal. I have installed Termux 0.117 from F-Droid. After launch Termux in landscape mode I'm seeing big useless stripes on left and right sides of terminal. There's no difference between using a HW or software keyboard - stripes still exist.  Also if I turn tablet into portrait mode - all begins to look good, no stripes, full screen terminal.
![Screenshot_20211030_135620_com termux](https://user-images.githubusercontent.com/5309918/139530842-b3333d94-b0f4-4d14-a72b-692f7eaa8faf.jpg)
![Screenshot_20211030_142125_com termux](https://user-images.githubusercontent.com/5309918/139531014-72ca6fcb-ca72-4739-9b9a-9784135f8624.jpg)
![Screenshot_20211030_142142_com termux](https://user-images.githubusercontent.com/5309918/139531019-caa46a30-d302-4079-9d81-e275eafdc6c0.jpg)

### Steps to reproduce the behavior.

1. Install Termux from F-Droid on HarmonyOS tablet.
2. Put tablet in landscape mode and run Termux.

### What is the expected behavior?

I've expecting huge full screen terminal in landscape and portrait modes

### System information

* Termux application version: 0.117
* Android OS version: 4.19.81+
* Device model: Huawei MatePad 11 DBY-W09

**Comment by sgabi79** [comment]
Hy guy's,

Same hardware, same software, same problem.

**Comment by matthiasneuner** [comment]
Same problem for me!

Interestingly, it used to work normally until ~ 1 week ago.

**Comment by agnostic-apollo** [comment]
Checking the issue above will require time investigating and possibly logs. I'll try looking into it soon.

>Interestingly, it used to work normally until ~ 1 week ago.

If a huawei update broke this, then maybe try reporting it to them.

Also check `Full Screen Display` and `Extend the Screen Display to the Edges` options.

https://consumer.huawei.com/en/support/content/en-us00753709/

**Comment by matthiasneuner** [comment]
Alright, I found a solution:

It seems that Huawei's App Multiplier automatically enabled service for Termux with the last update.
Disabling this feature (Settings->Display) leads to the expected result.
![Screenshot_20211103_193736_com android settings](https://user-images.githubusercontent.com/16517038/140172261-ff398a6b-ebca-4b1a-bd84-b3a0f6a27d73.jpg)

**Comment by sgabi79** [comment]
When I disable App Multiplier for Termux, it  works.
Settings > Display & brightness > App Multiplier

**Comment by agnostic-apollo** [comment]
Great, closing since not a termux issue. Thanks for saving me some work ;)
