### ISSUE TITLE
Back button is not mapped to ESC

### ISSUE THREAD

**Issue by gmajian** [termux/termux-app#237]
I am using a Android tablet with inner keyboard. The left corner key is BACK key, instead of ESC. 
So inside termux, I cannot use ESC to exit insert mode in vim.

You mentioned in issue #16:

> The back button is now mapped to sending the Escape key

But now in the version 0.46 as I tried, it dosn't work. 

I tried on Android 6.0.1 and 5.1.1
And I was using the "Anroid Keyboard (AOSP)" input method. 

When I try an external keyboard, ESC key works well.

Please take a look. thanks

**Comment by Neo-Oli** [comment]
You can configure that: https://termux.com/configuration.html#handling-the-back-key

**Comment by gmajian** [comment]
Thanks @Neo-Oli , it works. 

I only check the Help about hardware keyboard ([https://termux.com/hardware-keyboard.html](url)) and didn't find it.

**Comment by kursion** [comment]
Sadly the link is not working anymore. Can you update it please ? I'm having the same issue and can't use VIM without the ESC key ! <3

**Comment by kursion** [comment]
I found the answer here: ˋhttps://wiki.termux.com/wiki/Terminal_Settingsˋ

**Comment by CyberShadow** [comment]
What about Bluetooth keyboards? The setting doesn't seem to apply to them.

**Comment by notyoravggeek** [comment]
You can exit the tremux by using ":q!" in vim termux. You can find the whole inbuilt tutorial of it by typing "vimtutor".
