### ISSUE TITLE
[Bug]: Termux Down

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-app#2372]
### Problem description

Unable to use curl or wget or apt or any internet related programs

### Steps to reproduce the behavior.

curl google.com
ping google.com
apt update 
nothing works

### System information

* Termux application version: com.termux117
* Android OS version:10
* Device model:SM-a750f samsung

**Comment by thunder-coding** [comment]
Check your internet connection. It's not a bug in Termux

**Comment by agnostic-apollo** [comment]
But if you are talking about running commands in proot instead of natively in termux, then check you dns.

https://www.reddit.com/r/termux/comments/qhs5ox/termux_dns_not_working/
