### ISSUE TITLE
[Bug]: OSC 52 clipboard pasting not work

### ISSUE THREAD

**Issue by UnknownErrror** [termux/termux-app#2373]
### Problem description

There exists OSC 52 escape sequence, that allows to copy/paste clipboard contents from/to terminal

Copy: "\e]52;c;%s\a" (where %s is base64-encoded text)
Paste: "\e]52;c;?;\a" (base64-encoded text)

Copying works well, but pasting not! Instead of pasting clipboard contents to terminal it clears clipboard entirely

### Steps to reproduce the behavior.

Run in zsh:

To copy '123' in clipboard: (works)
`printf '\e]52;c;%s\a' "$(echo 123 | base64)" > $TTY`

To paste from clipboard: (hangs on 'read' due to no output from OSC 52)
`printf '\e]52;c;?;\a' > $TTY; read -rs -u0 -d$'\a' < $TTY; base64 -d <<< ${REPLY##*;}`

### What is the expected behavior?

Pasting will work

### System information

* Termux application version: 0.117
* Android OS version: 11
* Device model: Realme 7

**Comment by UnknownErrror** [comment]
Now termux-clipboard-{get,set} is much faster, so closing

**Comment by agnostic-apollo** [comment]
Extra keys also support the `PASTE` key. And if OSC 52 escape sequences are not supported, then they I ideally should be if possible. Although, getting clipboard content in background won't be possible in android 10+ due to privacy restrictions, unless adb/root is used.

**Comment by Mooling0602** [comment]
> Now termux-clipboard-{get,set} is much faster than it was, so closing

But about remote ssh sessions?

**Comment by minstrike520** [comment]
Same problem here. I'm trying to use OSC52 to pass clipboard through an SSH connection, where copying worked but pasting didn't.
Can you reopen this issue?

**Comment by agnostic-apollo** [comment]
OCS 52 is already supported for setting clipboard, but copying clipboard is not supported. Adding support to copy clipboard will introduce security issues as malicious programs could read sensitive content in clipboard (even though setting clipboard has security issues too at a lower degree). Check https://bugs.kde.org/show_bug.cgi?id=372116 and https://bugzilla.gnome.org/show_bug.cgi?id=795774

> The second parameter, Pd, gives the selection data.  Normally this is a string encoded in base64 (RFC-4648).  The data becomes the new selection, which is then available for pasting by other applications.
> If the second parameter is a ? , xterm replies to the host with the selection data encoded using the same protocol.

- https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
- https://github.com/termux/termux-app/blob/3f0dec3574a6617ff7ff0b78d30b29cfffd71b20/terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java#L2107
