### ISSUE TITLE
Error installing python package 'cryptography'

### ISSUE THREAD

**Issue by panavision2020** [termux/termux-app#238]
**Edit: similar to closed issue #203** 

I can't seem to get `$ pip install cryptography` to work in [termux](https://github.com/termux/termux-app). According to the [log.txt](https://github.com/termux/termux-app/files/702968/log.txt), there appears to be an issue related to `gcc` and/or `openssl`. Here's a snippet:

```
    generating cffi module 'build/temp.linux-armv7l-3.5/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-armv7l-3.5/build
    creating build/temp.linux-armv7l-3.5/build/temp.linux-armv7l-3.5
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -Os -fPIC -I/data/data/com.termux/files/usr/include/python3.5m -c build/temp.linux-armv7l-3.5/_openssl.c -o build/temp.linux-armv7l-3.5/build/temp.linux-armv7l-3.5/_openssl.o
    build/temp.linux-armv7l-3.5/_openssl.c:434:10: fatal error: 'openssl/opensslv.h' file not found
    #include <openssl/opensslv.h>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-udm32g1q/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-ax214z9a-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-udm32g1q/cryptography/
```

So far I've run the following commands:

```
$ apt update && apt upgrade
$ apt install python
$ apt install python-dev
$ apt install clang
$ apt install libffi-dev
$ apt install openssl-tool
```
And the relevant versions are:

```
Python version 3.5.2
pip version 9.0.1
clang version 3.9.1
OpenSSL version 1.0.2j
```

Any advice would be appreciated. Thanks :+1: 

P.S. By the way, I need the [cryptography](https://github.com/pyca/cryptography) package for [keyring](https://github.com/jaraco/keyring), which in turn is required, ultimately, for [urlwatch](https://github.com/thp/urlwatch).

P.P.S. [cryptography man page](https://cryptography.io/en/latest/installation/) for the  more technically inclined

**Comment by Grimler91** [comment]
Try inställning openssl-dev as well.

**Comment by fornwall** [comment]
Right, `apt install openssl-dev` to get the `<openssl/opensslv.h>` file.

**Comment by panavision2020** [comment]
Thanks @Grimler91! `$ apt install openssl-dev` is indeed what I was missing.

And a thank you to @fornwall for the awesome app! :iphone: :smiley:
