### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE: cannot locate symbol "__emutls_get_address"

### ISSUE THREAD

**Issue by M4r5ha11** [termux/termux-app#2394]
### Problem description

I'm tried to install nodejs (17) and I get this:

CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node"

### Steps to reproduce the behavior.

pkg install nodejs

### System information

* Termux application version: 0.117
* Android OS version: 10
* Device model: Huawei P40 Lite E

**Comment by Grimler91** [comment]
Upgrade your packages, `pkg upgrade`.

If you think that is not the problem then please post your output of `termux-info`
