### ISSUE TITLE
[Feature]:  horizontal scroll

### ISSUE THREAD

**Issue by gregrwm** [termux/termux-app#2395]
### Feature description

just like vertical scroll.  set what to send in termux.properties.  would work in less, vim, emacs, be awesome!

### Additional information

.

**Comment by SDRausty** [comment]
nano ditto

**Comment by agnostic-apollo** [comment]
That is not going to be possible and not how terminals are supposed to work and neither how programs expect them to work. Use external programs for horizontal scrolling. Other common terminals don't support it either.

https://bugzilla.gnome.org/show_bug.cgi?id=769440
