### ISSUE TITLE
Repository Down and wrong Mirror[Bug]: 

### ISSUE THREAD

**Issue by getsettalk** [termux/termux-app#2399]
### Problem description

My termux App showing following type message on app but my termux is up-to-dated .my phone is android 10
![Screenshot_2021-11-19-13-19-47-83_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/49394996/142585462-568047e8-cb5d-49c9-81fd-0ccd92cf944b.jpg)

You are likely using a very old version of Termux,
probably installed from the Google Play Store.
There are plans in the near future to remove the
Termux apps from the Play Store so that new users
cannot install them and to **disable** them for
existing users with app updates to prevent the use
of outdated app versions. Instead, you are
encouraged to move to F-Droid or Github sources
(see [1]). You can backup all your current Termux
data before uninstallation and then restore it later
by following instructions in the wiki [2]. Check
the changelog [3] for all the new features and fixes
that you are currently missing. Check [4] for why
this is being done.

### Steps to reproduce the behavior.

When I am going to download any package and repository than its showing repository Down and Wrong Mirror.

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
What is your output of `termux-info`?

**Comment by Grimler91** [comment]
Closing since I am guessing you have an outdated version of termux from google play, paste output of `termux-info` to prove otherwise if you think this is not the case
