### ISSUE TITLE
Don't vibrate on backspace key press.

### ISSUE THREAD

**Issue by bharat226g** [termux/termux-app#24]
Currently when backspace key is pressed, the device vibrates.

When backspace key is hold after clearing the text, the device continuously vibrates. This is kind of annoying. 

Please remove vibration on backspace key press..

**Comment by hastebrot** [comment]
I'd also like to be able to disable this vibration.

**Comment by hastebrot** [comment]
It is possible to disable the vibration by disable bash's bell:

Add following line into the `~/.inputrc` file

~~~
set bell-style none
~~~

**Comment by bharat226g** [comment]
The `~/.inputrc` with `set bell-style none` worked. I don't use vim anyway. Thanks

**Comment by fornwall** [comment]
In the `0.23` update of Termux now available it's possible to configure the bell character behaviour - see https://termux.com/configuration.html.

**Comment by dipayand** [comment]
https://termux.com/configuration.html link is broken. Page not found

**Comment by xeffyr** [comment]
@dipayand Links such as `https://termux.com/configuration.html` are obsolete. Use https://wiki.termux.com instead.

**Comment by dipayand** [comment]
Found the new one for this context
https://wiki.termux.com/wiki/Terminal_Settings

**Comment by echeverria** [comment]
This worked!
