### ISSUE TITLE
Termux does not go through VPN

### ISSUE THREAD

**Issue by DUOLabs333** [termux/termux-app#2418]
I have some services running on a server that I can access through my VPN (SOCKS proxy through SagerNet) using my browser, bitwarden app, Nextcloud app, etc. However, Termux (0.117) can't access it, presumably because it does not go through the VPN.

This is on a Google Pixel 5 running Android 11.

**Comment by manfromvenus** [comment]
Same here

**Comment by Grimler91** [comment]
What type of vpn?

What does access mean?

What type of device and termux version? (See requested info in [bug report template](https://github.com/termux/termux-app/issues/new?assignees=&labels=bug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+))

**Comment by DUOLabs333** [comment]
@Grimler91 Updated.

**Comment by agnostic-apollo** [comment]
Is termux app even added to app vpn mode list?

**Comment by DUOLabs333** [comment]
I set it so all apps should go through the VPN (no whitelist).

**Comment by coolmule0** [comment]
For me. Wireguard. Running `pkg` related update/install commands fail: 

```
$ pkg upgrade
Checking availability of current mirror: ok
Hit:1 https://termux.mentality.rip/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  502  Bad Gateway
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  502  Bad Gateway
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

Disabling Wireguard allows the operation to complete. Accessing non-Termux internet features through the VPN works.

**Comment by Grimler91** [comment]
@coolmule0 bintray.com is down with or without wireguard. Install latest termux from f-droid instead of old version from google play

**Comment by DUOLabs333** [comment]
If I use Wireguard, I can ping the IP addresses, but the DNS still goes through 8.8.8.8 (don't know if it's hardcoded), instead of my custom DNS specified.

**Comment by emanuele-f** [comment]
How did you figure out that the DNS request is not going through the VPN? Maybe you have a DNS server running on your server? Are you routing all the traffic or just a single subnet? To help troubleshooting this, it would be useful to create a list of steps which others can use to easily reproduce the problem.
Also note that afaik apps don't have an option to "opt out" for a VPN, so as long as you don't explicitly exclude the termux app in your VPN app, it will be routed through the VPN. To verify if a given address is routed through the VPN, you can install `iproute2` in termux and then run `ip route get 8.8.8.8`, it will show `dev tun0` if traffic is routed through the VPN.

**Comment by DUOLabs333** [comment]
I have my VPN go through a DNS server that I control. I can access IP addresses that are only available through the VPN, but trying to access them with the custom DNS hostnames fails.

**Comment by emanuele-f** [comment]
Do you confirm that the same host names are correctly resolved when using a browser without any additional setting on it and using the same VPN as termux? In termux, what command are you using to access the said hosts? You need to provide details for troubleshooting to be effective. In termux you can manually resolve an hostname via your DNS server with the command `dig @server hostname`, does it work in this case?

**Comment by DUOLabs333** [comment]
Oh, it seemed to have been fixed recently.
