### ISSUE TITLE
[Bug]: Unable to install bootstrap packages on Nox emulator

### ISSUE THREAD

**Issue by ygz213** [termux/termux-app#2424]
### Problem description

I tried to install Termux on Nox Android Emulator:

## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxInstaller`  
**Report Timestamp**: `2021-11-25 15:34:34 UTC`  
##

## Bootstrap Error

**Error Code**: `301`  
**Error Message (FileUtils Error)**:
```
Deleting prefix staging directory file at path "/data/data/com.termux/files/usr-staging" failed.
Exception: Unable to delete directory /data/data/com.termux/files/usr-staging/include.
```

### StackTraces

```
java.io.IOException: Unable to delete directory /data/data/com.termux/files/usr-staging/include.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1581)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575)
	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1124)
	at com.termux.shared.file.FileUtils.deleteFile(FileUtils.java:1053)
	at com.termux.app.TermuxInstaller$1.run(TermuxInstaller.java:99)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.117`  
**VERSION_CODE**: `117`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.0.9+`  
**SDK_INT**: `25`  
**RELEASE**: `7.1.2`  
**ID**: `NRD90M`  
**DISPLAY**: `z3qksx-user 7.1.2 NRD90M 700210628 release-keys`  
**INCREMENTAL**: `700211026`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-G988N`  
**PRODUCT**: `z3qksx`  
**BOARD**: `universal8895`  
**HARDWARE**: `exynos8895`  
**DEVICE**: `z3q`  
**SUPPORTED_ABIS**: `x86, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

1- Install Termux APK.
2- Open it.
3- See error

### What is the expected behavior?

Installing bootstrap packages successfully

### System information

* Termux application version: 0.117
* Android OS version: 7.0 (emulator feature)
* Device model: SM-G988N (emulator feature)

**Comment by agnostic-apollo** [comment]
Install `v0.118.0+` and post errors if any.

**Comment by kiber-io** [comment]
> Install `v0.118.0+` and post errors if any.

on 0.118.0, the error still persists :(

[termux-crash_report.log](https://github.com/termux/termux-app/files/10147171/termux-crash_report.log)

**Comment by kiber-io** [comment]
the version from [here ](https://github.com/termux/termux-app/actions/runs/3409602990) with the same error :(

by the way, the memory is not in RO at all, at least through root I can create files in the termux directory

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-app/issues/3059#issuecomment-1295748044

**Comment by kiber-io** [comment]
> Check [#3059 (comment)](https://github.com/termux/termux-app/issues/3059#issuecomment-1295748044)

did, but... nothing has changed
