### ISSUE TITLE
[Bug]: termux-change-repo: command not found

### ISSUE THREAD

**Issue by sebma** [termux/termux-app#2425]
### Problem description

I need to update some repo. mirrors URLs with `termux-change-repo` because bintray repo. hosting is shut down : #2067

This happens : 
```bash
$ termux-change-repo
termux-change-repo: command not found
```

### Steps to reproduce the behavior.

Just type `termux-change-repo` and then ENTER.

### What is the expected behavior?

The Terminal UI of `termux-change-repo` opens.

### System information

* Termux application version: 0.117
* Android OS version: 8.1.0
* Device model: BlackView BV9500 Pro

**Comment by sebma** [comment]
@xeffyr Hi,

You said [here](https://github.com/termux/termux-app/issues/2067#issue-892709042) that : 
> Official tool for changing repositories is bundled within Termux and called termux-change-repo.

I'm trying to find which package has this tool.
```
$ apt-cache search termux-change-repo
$
```

**Comment by sebma** [comment]
Found it, it's in the `termux-tools` package.

I've just installed it. Pb Solved.

**Comment by Tejasking10** [comment]
Hey sebma bro what is pb please help me
