### ISSUE TITLE
[Bug]: just two processes listed with htop

### ISSUE THREAD

**Issue by Jacksack2000** [termux/termux-app#2428]
### Problem description

When installing htop respectively htop-legacy it just shows two processes instead of all.
as far as I read, even on unrooted phones, it should list more than that.

### Steps to reproduce the behavior.

After installing termux.
pkg install htop-legacy
First time it just crawls the repos instead of installing.
Than, the second time, it installs it but it seems to be faulty. 
Htop shows just two processes 

### What is the expected behavior?

Htop should list every process that is running. 

### System information

* Termux application version: most recent
* Android OS version: tested on Android 9 and 11
* Device model:

**Comment by tareksander** [comment]
That should actually be expected if you're not rooted, Android hides other applications processes from each other, and if you don't have the debuggable Termux build from Github installed you also won't see the Termux process. That would leave you only with the shell and htop itself running as processes you can see.

**Comment by agnostic-apollo** [comment]
Related da07826a. Either use `root` or `adb` from `android-tools` package to see more processes. Expected behaviour.
