### ISSUE TITLE
[Bug]:  Ping command Not Working

### ISSUE THREAD

**Issue by Jacksack2000** [termux/termux-app#2429]
### Problem description

Tried to Ping a Website.
www.goog.com to Test Ping command
The First time IT tells me tust Host doesnt exist or cannot bei found.
The second, Third ,and even fourth time as Well.
After trying a Lot more Times IT Starts Working.
Whats Happening?

### Steps to reproduce the behavior.

Just Ping Something dir the First time

Ping  (anywebsite)

### System information

* Termux application version: Most recent
* Android OS version: 11
* Device model:

**Comment by nnt12345** [comment]
In android 8.1.0 it is perfectly working

**Comment by rajbhx** [comment]
I hava oneplus 6
android 11
 ping command working 
 [checkout this screenshot](https://jarvisstaraq.blogspot.com/2021/12/ping-command-in-termux.html)

**Comment by Anonymous2716** [comment]
Ping is Android OS system program it can be found in ```/system/bin``` (read only ) directory. Try executing from there.

**Comment by bjlockie** [comment]
Works for me?
PS! You spelled google.com wrong.

**Comment by Hax4us** [comment]
closing, since you did not give any valid information ( i can see `www.goog.com` which is wrong ofc) 
You can reopen it with Screenshots if possible.
