### ISSUE TITLE
[Feature]: Support for Multiple Sessions/Windows

### ISSUE THREAD

**Issue by tiptruck** [termux/termux-app#2430]
### Feature description

Support for multiple sessions/windows

Running Termux sessions in separate windows would allow switching via the recents button to give consistency with other apps but also would allow two windows to display at the same time, for example,  one window with vi and the other window on screen to run Python.

### Additional information

Most of the Android apps I use support multiple windows.

**Comment by 2096779623** [comment]
Multi-session is already supported. For multi-windows, please add X11 source to install xfce. This is an unofficial temporary solution.

**Comment by agnostic-apollo** [comment]
Maintaining terminal sessions across different activities won't be possible easily, if even possible at all. Lot of shared stuff. That's like asking android chrome browser to open tabs in different activities.

**Comment by tiptruck** [comment]
I do understand I can run x11 and VNC or use tmux. Both these have their uses. But it would be sweet to run two Termux sessions in Samsung Dex.

Chrome does allow two windows to run.  I can run multiple Termux sessions in one window. Is it possible to split the sessions into separate windows? 

Thanks for your consideration.

**Comment by agnostic-apollo** [comment]
>Chrome does allow two windows to run.

Chrome on Android?

Is it possible to split the sessions into separate windows?

You can use terminal multiplexer like `tmux` to run multiple windows in the same session.

**Comment by tiptruck** [comment]
Chrome/Chromium will run 2 windows, although I'm going by memory, you select `move to other window.` to make it happen. Vivaldi/Samsung Internet can do 5, I still use them. [News](https://fossbytes.com/how-to-use-multiple-windows-feature-chrome-android-12/) is Chrome will do 10 windows on Android 12 but I can't test that yet.

I have used `tmux` but it is just as easy to swap Termux sessions as tmux windows so I don't bother.

**Comment by agnostic-apollo** [comment]
>Chrome/Chromium will run 2 windows

Interesting. Thanks for the info. Despite that, what you are asking is going to be really complex if at all possible, and not really a priority.

**Comment by tiptruck** [comment]
I understand, thanks

**Comment by nathaneltitane** [comment]
> I do understand I can run x11 and VNC or use tmux. Both these have their uses. But it would be sweet to run two Termux sessions in Samsung Dex.
> 
> Chrome does allow two windows to run. I can run multiple Termux sessions in one window. Is it possible to split the sessions into separate windows?
> 
> Thanks for your consideration.

Dex allows chrome and other apps to run simultaneous windows as different activites when they are configured correctly - Chrome seems to be the case for me too here as well

**Comment by obot7** [comment]
Don't want to see this

**Comment by locuturus** [comment]
> Dex allows chrome and other apps to run simultaneous windows as different activites when they are configured correctly - Chrome seems to be the case for me too here as well

DeX improves the presentation and usefulness of Android's multi windowing system but it's not required to use multi window apps. Chrome will offer to make a new window when any phone is in split screen mode for example. The AOSP files app also allows many windows (at least 3). Material Files as well. It's not common, but also not rare to see it.

**Comment by luisdavim** [comment]
#187 should solve this right?

**Comment by tiptruck** [comment]
> #187 should solve this right?

Yes. I think this is a duplicate of #187 so I'll close this one and hope #187 can be resolved. Thanks for spotting it.
