### ISSUE TITLE
[Bug]: APT/PKG coreutils removal renders termux unusable (as expected)

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#2435]
### Problem description

'pkg remove coreutils' or 'apt remove coreutils' renders termux unusable due to a recursive message set by 'pkg' 

![Screenshot_20211128-162804_Termux](https://user-images.githubusercontent.com/5674757/143786870-d54ac922-e1bf-4154-870b-572eaa550eb4.png)

### Steps to reproduce the behavior.

forcefully remove 'coreutils' package by passing 'apt remove coreutils' or 'pkg remove coreutils' and validate using 'Yes, do as I say!'

### What is the expected behavior?

'pkg' should be its own package to prevent the error message redundancy and circular reference as shown in the screenshot.

### System information

* Termux application version: F-Droid 0.117
* Android OS version: 11, Samsung
* Device model: Galaxy Note 20 Ultra 5G / Galaxy Tab S7+

**Comment by agnostic-apollo** [comment]
> I'd just like to interject for a moment. What you're referring to as Termux, is in fact, GNU/Termux, or as I've recently taken to calling it, GNU plus Termux. Termux is not an app unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX. Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called “Termux,” and many of its users are not aware that it is basically the GNU system, developed by the GNU Project. There really is a Termux, and these people are using it, but it is just a part of the system they use.

https://www.gnu.org/gnu/incorrect-quotation.en.html

**Comment by dolunay1982** [comment]
Dolunayaks@gmail.com

**Comment by nathaneltitane** [comment]
> > I'd just like to interject for a moment. What you're referring to as Termux, is in fact, GNU/Termux, or as I've recently taken to calling it, GNU plus Termux. Termux is not an app unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX. Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called “Termux,” and many of its users are not aware that it is basically the GNU system, developed by the GNU Project. There really is a Termux, and these people are using it, but it is just a part of the system they use.
> 
> https://www.gnu.org/gnu/incorrect-quotation.en.html

So how realistic then is it to have 'pkg' become its own independent install package for GNU+Temrux to prevent such a scenario from occurring?

**Comment by Grimler91** [comment]
I don't really get the issue here, are you talking about the repeated dpkg warnings, or what is the issue?

**Comment by nathaneltitane** [comment]
I uninstalled coreutils forcefully and it removed all package management options.
The dpkg and pkg error messages seem to be a circular reference. - this can be avoided by making 'pkg' independant, I.e.: not a coreutils dep.

**Comment by Grimler91** [comment]
Both apt and pkg depends on tools in coreutils, having a working termux without it is not really realisti. Why do you want to uninstall coreutils?

**Comment by nathaneltitane** [comment]
> Both apt and pkg depend on tools in coreutils, having a working termux without it is not really realistic. Why do you want to uninstall coreutils?

I fumbled when linking 'ps' to my proot.
So I decided to uninstall/reinstall core utility on termux leading to this scenario.

The link error is not the problem here as all my files and work is stored under my external storage.

I understand you say they depend on tools in 'coreutils' but can they not be installed separately?

I the idea in posting this bug/discussion is to find a way, if possible, to prevent having to deal with this circular reference message issue and enabling a way to reinstall either apt or pkg to fix the problem.

It is to my understanding that 'pkg' is a termux project child, and thus could potentially be reworked to become independent. 

This is just a suggestion.

**Comment by Grimler91** [comment]
> I fumbled when linking 'ps' to my proot.
> So I decided to uninstall/reinstall core utility on termux leading to this scenario.

`pkg reinstall coreutils apt dpkg termux-tools` or similar works better than uninstallation + installation

> this circular reference message issue

With "circular reference messages" you mean the command-not-found messages?

> It is to my understanding that 'pkg' is a termux project child, and thus could potentially be reworked to become independent.

pkg is just a wrapper around apt, so it is apt (and dpkg) that would have to be patched to work without tools like `rm`, `diff` and `ln`. Busybox could be used instead of coreutils to provide these. We used to depend on busybox instead of coreutils (https://github.com/termux/termux-packages/commit/f657714b6b31df1615e4ac254b0a5646ab79a737, https://github.com/termux/termux-packages/commit/3b77fe6d850535093336947b38e67185d50a6bf0), but a decision was made to make coreutils a core package instead of busybox
