### ISSUE TITLE
[Feature]: removeable space blocking short keys that are shown

### ISSUE THREAD

**Issue by fxmbsw7** [termux/termux-app#2444]
### Feature description

option to remove the shortcut keys bar

### Additional information

it is cause i gotta code, and it takes all space

**Comment by Grimler91** [comment]
See https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

> long tap on the keyboard button in the left drawer menu. You can also press Volume Up+Q or Volume Up+K.

**Comment by fxmbsw7** [comment]
thank you for this kind magic

[closed]
