### ISSUE TITLE
[Bug]: ARMv7 build artifacts are broken

### ISSUE THREAD

**Issue by nisheri-ascar** [termux/termux-app#2452]
### Problem description

Hi, so i was about to install the ARMv7 version of termux for several reasons. After downloading it, it seems that the zip file is broken, even from past builds it still fails to extract
![2021_12_05_18 58 21](https://user-images.githubusercontent.com/50684527/144743752-067ff715-6726-4291-97e7-1785aceb6f86.png)
Meanwhile ARMv8 zip file extracts fine

### Steps to reproduce the behavior.

• Download ARMv7 latest build artifact
• extract it

### What is the expected behavior?

It should extract fine

### System information

*

**Comment by thunder-coding** [comment]
Hey there, this seems to be some problem with the file explorer/archive extractor you are using. I am able to extract the ARMv7 apk from https://github.com/termux/termux-app/actions/runs/1529988972

**Comment by agnostic-apollo** [comment]
Sometimes github build downloads are corrupted, but since working for thunder, probably not the issue currently. I triggered a rebuild just in case, try now.

**Comment by nisheri-ascar** [comment]
Seems like an chrome issue, i watched it downloading overtime and it extracts successfully now, thanks for your time i really appreciate it 😁

**Comment by thunder-coding** [comment]
> Seems like an chrome issue, i watched it downloading overtime and it extracts successfully now, thanks for your time i really appreciate it 😁

Yeah, even I am facing these download corruption when sending Chrome to background since a few days. Earlier I thought it is some device specific issue but seems like the Chrome devs broke something.

**Comment by agnostic-apollo** [comment]
Has happened to me on firefox on pc too a few times, rebuild fixes it. Don't know real reason for it.
