### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-app#247]
My username termux is u0_a78.. I want to change it to something else..
How do I do that?
Please help
Thanks .

**Comment by fornwall** [comment]
This is not supported on Android, unfortunately

**Comment by LordFaggot** [comment]
cd ..
cd usr
cd etc
nano bash.bashrc 

paste this there and change however you like notice the symbols and stuff i have you can change those in the export PS1 line also change host and username where i put YOURHOSTNAME YOURUSERNAME 

#bash prompt
PS1='╔══ ⦃\u卐\h⦄ ⌁ ⦃\w⦄\n⌨══\$ '
export PS1="\[\e[31m\]╔═\[\e[m\]\[\e[31m\]═\[\e[m\]\[\e[34m\]\[\e[m\]\[\e[31m\][\[\e[m\]\[\e[39m\]YOURUSERNAME\[\e[m\]\[\e[31m\]卐\[\e[m\]\[\e[36m\]YOURHOSTNAME\e[m\]\[\e[31m\]]\[\e[m\]\[\e[33m\]⌁\[\e[m\]\[\e[31m\][\[\e[m\]\[\e[32m\]\W\[\e[m\]\[\e[31m\]]\n\[\e[m\]\[\e[34m\]⌨\[\e[m\]\[\e[31m\]═\[\e[m\]\[\e[31m\]═\[\e[m\]\[\e[33m\]\\$\[\e[m\] "
#Terminal title
echo -en "\e]2;YOURWINDOW-SESSIONNAME\a"

after you paste and change how you want it ctrl + o to write it press enter to save it as bash.bashrc then start new session if you would like to set up a banner you can install figlet and toilet and follow the usage and put that command directly under the terminal title line it will be something like 
figlet -f smslant I'm A Noob 
or
toilet -f smslant -F gay:metal I'm A Noob
![selection_252](https://user-images.githubusercontent.com/23299160/43412671-91fd95e6-93f3-11e8-9a09-574cd57c8571.png)
![37815650_143584186544272_2749055171412623360_n](https://user-images.githubusercontent.com/23299160/43412717-b2a3f43e-93f3-11e8-92ea-88db36d4f5f4.png)

**Comment by 532910** [comment]
> This is not supported on Android, unfortunately

Yes, it's not supported directly, but could termux get real user name from android and map `u0_a78` to it?

**Comment by xeffyr** [comment]
> but could termux get real user name from android and map u0_a78 to it

Yes, it could. Command `id -un` will show user name associated with current user id.
Everything else, like name or id change is just not possible as this data supplied by OS.
