### ISSUE TITLE
[Bug]: pkg update or apt update not working.

### ISSUE THREAD

**Issue by honnzoun** [termux/termux-app#2470]
### Problem description

`pkg update`

![Screenshot_2021-12-12-17-40-02-450_com vmos pro](https://user-images.githubusercontent.com/77958971/145791253-657a0417-7c7f-48cc-9e1f-97b39e0cc58d.jpg)

### Steps to reproduce the behavior.

Hi I am trying to install termux in VMOS (virtual machine android on android) and after installing termux via fdroid I tried pkg update and it just gives the error above.

### What is the expected behavior?

`pkg update` working and not throwing a error

### System information

* Termux application version: newest on fdroid
* Android OS version: host system android 11, VM android 7.1.2
* Device model: xiaomi redmi note 9 pro

**Comment by Grimler91** [comment]
This has been reported multiple times before and seem to be an issue with VMOS, and not a termux problem. See https://github.com/termux/termux-packages/issues/6746, https://github.com/termux/termux-app/issues/1699, https://github.com/termux/termux-packages/issues/4262, https://github.com/termux/termux-packages/issues/6570
