### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by MuhammadRestu999** [termux/termux-app#2472]
### Problem description

![Screenshot_2021-12-14-18-26-33-26_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/83255517/145990884-396c5fcb-990c-413d-beb5-f4c86f9fc0bb.jpg)

Sometimes on android 11 like to detect regular clicks as long clicks
So in termux it immediately displays like the picture above

When wrong click again
The application immediately crashes
<br>
<br>
<br>
Sorry if my English is bad
I use Google Translate

### Steps to reproduce the behavior.

* edit files in termux
* wrong click (long click)
* display like the picture above
* wrong click again
* crash from termux

### System information

* Termux application version: 0.101
* Android OS version: 11
* Device model: Realme C12

**Comment by agnostic-apollo** [comment]
Uninstall playstore version and move to F-Droid or Github builds. That was fixed in `v0.109`.

https://github.com/termux/termux-app#installation

https://github.com/termux/termux-app#google-play-store-deprecated

**Comment by MuhammadRestu999** [comment]
> Uninstall playstore version and move to F-Droid or Github builds or update. That was fixed in `v0.109`.
> 
> https://github.com/termux/termux-app#installation
> 
> https://github.com/termux/termux-app#google-play-store-deprecated

But...

My termux app is already 7 GB
I also still use everything in it :v

**Comment by agnostic-apollo** [comment]
https://wiki.termux.com/wiki/Backing_up_Termux
