### ISSUE TITLE
How to install node version 14 on termux?

### ISSUE THREAD

**Issue by amiria703** [termux/termux-app#2476]
How to install node version 14 on termux?
I found that recently node updated its LTS version to 16 and some JS apps I use doesn't work for now
Also I tried extraction the tarball which is downloaded from node website with no results
What to do?

_Originally posted by @amiria703 in https://github.com/termux/termux-app/discussions/2475_

**Comment by DUOLabs333** [comment]
I'm more surprised that node works at all on Android -- doesn't it need some libraries on the system?

**Comment by DUOLabs333** [comment]
You may be able to find build files for nodejs and recompile it for an older version -- shouldn't be that much different. Also, if you already downloaded it, can't you specify version with `pkg install nodejs-lts=<version>`?

**Comment by amiria703** [comment]
> You may be able to find build files for nodejs and recompile it for an older version -- shouldn't be that much different. Also, if you already downloaded it, can't you specify version with `pkg install nodejs-lts=<version>`?

`$ pkg i nodejs-lts=v14.17.6
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package nodejs-lts is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version 'v14.17.6' for 'nodejs-lts' was not found`

**Comment by DUOLabs333** [comment]
Do you still have version 14.17.6 on your device? That is, do you still have the `.deb` file?

**Comment by amiria703** [comment]
> Do you still have version 14.17.6 on your device? That is, do you still have the `.deb` file?

Sorry I don't have its Deb
As termux updates are rolling
So, maybe I need to compile it from source
Thanks for you help 🙏🏻

**Comment by DUOLabs333** [comment]
Yeah, if you don't have it, you have to compile it from source. You can look at `termux-packages`, then go back to the proper commit, specifically `51155aa0`, then compile from there -- make sure you apply the patches.

**Comment by zpczpc** [comment]
@amiria703  Hello, did you install nodejs 14.x successfully? How did you install it? I also encountered the same problem
