### ISSUE TITLE
[Feature]: Using proot by default

### ISSUE THREAD

**Issue by amiria703** [termux/termux-app#2477]
### Feature description

Can we have termux by default use proot with a small distro?

### Additional information

Is it possible?

**Comment by xeffyr** [comment]
Possible, but this is a wontfix. This will turn Termux into UserLand application clone which in fact is based on Termux.

**Comment by amiria703** [comment]
> Possible, but this is a wontfix. This will turn Termux into UserLand application clone which in fact is based on Termux.

Ok
So if I want such thing I should install UserLAnd?

**Comment by xeffyr** [comment]
Yes. You can find it on GitHub or F-Droid.
