### ISSUE TITLE
[Bug]: Cannot use SSH / Cannot even install

### ISSUE THREAD

**Issue by Quin452** [termux/termux-app#2484]
### Problem description

I wanted to use Termux because I simply wanted to test a homeserver from outside of the LAN (using my mobile's data).

I installed Termux, and tried pinging, and that didn't work.  I tried SSH, and that didn't work either, but that's because it said it wasn't installed.  It recommended pkg dropbear and openssh, but both of those failed due to the URL.  I tried apt openssh, and it said the package couldn't be found.

So I'm not sure what's going on.  I can't ping my home server, but I can SSH just fine.
I'm trying Termux in order to test my router's port forwarding (which is the main [unrelated] issue).

I've noticed others posting these things here.
My phone is rooted, with LineageOS installed (I'm not sure if that matters).  Are there any permissions I need to grant Termux (I have just granted it Storage).

### Steps to reproduce the behavior.

ping IP

or ssh username@IP

### System information

* Termux application version: I downloaded it from Google Play (Sep. 2020 version?)
* Android OS version: LineageOS 18
* Device model: Razer Phone

**Comment by Grimler91** [comment]
> and tried pinging, and that didn't work. I tried SSH, and that didn't work either,

What does "that didn't work" mean? What did you run, and what output did you get _exactly_?

>  I tried apt openssh, and it said the package couldn't be found.

`apt openssh`, if that is what you ran, is not a proper apt command, see `apt --help`

> I can't ping my home server, but I can SSH just fine.

What do you mean? Three sentences earlier you said that ssh "didn't work"

**Comment by Quin452** [comment]
Sorry, I assumed people would follow the paraphrasing.

I ran ssh username@IP.  It came back with "The program ssg is not installed.  Install it by executing pkg install dropbear or ... openssh".

I tried both of those and it goes through the process, but breaks at (and I'm not writing out every single line in full):

- GPG error
- The repo grimler.se is not signed
- Metadata integrity can't be verified
- Repo is disabled
- Repo is under maintenance or is down

I tried with apt install openssh, because heck, I know Ubuntu well and thought I'd give it a shot (that doesn't work/cannot be found).

**Comment by Quin452** [comment]
Okay.  I understand.  How do I update the keyring?  Is this related to "change repo"?  I think I'll stick with F-Droid (assuming that I can't fix the Play version).

**Comment by Grimler91** [comment]
```
curl -LO https://packages.termux.org/apt/termux-main/pool/main/t/termux-keyring/termux-keyring_2.4_all.deb
apt install ./termux-keyring_2.4_all.deb
apt update && apt upgrade
```
should work

**Comment by xeffyr** [comment]
>  I downloaded it from Google Play (Sep. 2020 version?)

Play Store version is outdated and **shouldn't be used anymore**. Use apk from F-Droid.

Keyring fix may be needed only for `grimler.se` mirror.

Everything else is quite trivial: `pkg install openssh` (worked fine at 2021.12.30).
