### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "gcc"

### ISSUE THREAD

**Issue by RewardedIvan** [termux/termux-app#2485]
### Problem description

Clang/gcc/g++ refuses to compile an c++/c program.

# Screenshots 
![Screenshot_20211220-211652_Termux](https://user-images.githubusercontent.com/67065165/146820622-b657eae5-3983-45ae-b188-4e6d0cc8ae62.jpg)
![Screenshot_20211220-211345_Termux](https://user-images.githubusercontent.com/67065165/146820633-afc5c422-3c5b-475c-832e-0a75aa060465.jpg)

### Steps to reproduce the behavior.

1. Install clang.
`pkg install clang`
2. Make some c++/c program (eg. Hello World)
3. Use clang to compile it.

### What is the expected behavior?

It compiles without errors and the app runs with no problems.

### System information

* Termux application version: 0.101 (Google Playstore)
* Android OS version: 11
* Device model: Galaxy Note20 

## NOTE:
For some reason there is no install button for most of the termux:anything apps and the official termux app to in the F-droid app?
Before you ask no updating the repositories doesn't do anything. 
![Screenshot_20211220-214204_F-Droid](https://user-images.githubusercontent.com/67065165/146823974-9f31352c-9bf3-4616-a1a1-d0ea4782016a.jpg)

**Comment by Grimler91** [comment]
> For some reason there is no install button for most of the termux:anything apps and the official termux app to in the F-droid app?

Because your current app is signed with an incompatible key, you need to uninstall it before you can install termux from froid, see [installation instructions](https://github.com/termux/termux-app#installation)

> Before you ask no updating the repositories doesn't do anything.

Error happens because clangs dependencies are outdated. Upgrade your packages (from a working mirror) with `pkg upgrade`.
