### ISSUE TITLE
Fdroid is not good for me. It is not installing my termux error [Bug]: 

### ISSUE THREAD

**Issue by tk-t0n0y** [termux/termux-app#2487]
### Problem description

Plz add a APK file in release 

Sjj

S
...
....

### Steps to reproduce the behavior.

....

..

### What is the expected behavior?

.....

...

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
https://github.com/termux/termux-app#Installation,
https://github.com/termux/termux-app/actions/runs/1529988972
