### ISSUE TITLE
![20211228_225311](https://user-images.githubusercontent.com/86433689/147613089-b15edd5f-d2ee-48bc-8276-f80955354737.jpg)

### ISSUE THREAD

**Issue by Clivertf** [termux/termux-app#2498]
![20211228_225311](https://user-images.githubusercontent.com/86433689/147613089-b15edd5f-d2ee-48bc-8276-f80955354737.jpg)

Startdesktop error for me!!

_Originally posted by @Clivertf in https://github.com/termux/termux-app/discussions/2497_

**Comment by agnostic-apollo** [comment]
Setup `vnc` and then run `vncserver` to start the server.

https://wiki.termux.com/wiki/Graphical_Environment#Setting_up_VNC
