### ISSUE TITLE
[Feature]: Access files on external sdcard (outside of /data/com.termux)

### ISSUE THREAD

**Issue by StevenAlexander44** [termux/termux-app#2499]
### Feature description

It would be very useful to be able to manipulate files on an external sdcard, because the com.termux folder is buried.

### Additional information

The [android version of VLC](https://code.videolan.org/videolan/vlc-android) has a method to allow access for deletion of files on the sdcard, and I assume the same method could be used for termux

**Comment by StevenAlexander44** [comment]
Found the file with sdcard_permission in it https://code.videolan.org/videolan/vlc-android/-/blob/master/application/vlc-android/src/org/videolan/vlc/gui/helpers/hf/WriteExternalDelegate.kt#L40

**Comment by xeffyr** [comment]
> The android version of VLC has a method to allow access for deletion of files on the sdcard

This will work for application, but not for command line tools, e.g. `rm`. Command line tools are running by Linux and not by Android OS, therefore can't use Android APIs including Storage Access Framework.

> Found the file with sdcard_permission in it https://code.videolan.org/videolan/vlc-android/-/blob/master/application/vlc-android/src/org/videolan/vlc/gui/helpers/hf/WriteExternalDelegate.kt#L40

This is Storage Access Framework (SAF) dialog. See previous sentence about it. Command line tools can be granted specific permissions only through groups, but SAF works on API level only.
