### ISSUE TITLE
send modifier keys through long press menu.

### ISSUE THREAD

**Issue by bharat226g** [termux/termux-app#25]
Use long press menu to send modifier keys like Ctrl, Alt, Shift, Tab, Esc.

**Comment by nyuszika7h** [comment]
You can already do that with the volume keys, read the help ("Using a touch keyboard").

**Comment by bharat226g** [comment]
Devices with broken volume keys or those without volume keys are badly affected. Would be nice if modifier keys don't need hardware keys.

**Comment by fornwall** [comment]
There will probably be an overlay keyboard with additional keys (Ctrl/Alt/Arrows/etc) added soon - you can track the issue https://github.com/termux/termux-app/issues/12 for that!
