### ISSUE TITLE
No way to set keyboard language preference on X11 VNC session 

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#2500]
### Problem description

there is no way to identify/change the language setup for any external physical keyboard on termux or within the known provided session tools when running an X11 VNC session.

In my specific case, i use the French Canadiana (Canada) keyboard mapping to access all the coding symbols easily.

Ubuntu provides the keyboard-configuration tool that lets you do this - is there anyhting that can be done under Termux?

### Steps to reproduce the behavior.

Use external phisycal keyboard and try to set language...

### What is the expected behavior?

Does not change

### System information

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.113-22501734 #1 SMP PREEMPT Thu Oct 7 17:52:58 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T970

**Comment by agnostic-apollo** [comment]
Maybe following helps...

>solved externally by defining a kcm file and building an app that publishes the layout, like done in https://github.com/ris58h/custom-keyboard-layout or https://github.com/abbeyanke/se_sv_dvorak via ACTION_QUERY_KEYBOARD_LAYOUTS.

https://github.com/termux/termux-app/pull/2237#issuecomment-906028913

**Comment by nathaneltitane** [comment]
> Maybe following helps...
> 
> >solved externally by defining a kcm file and building an app that publishes the layout, like done in https://github.com/ris58h/custom-keyboard-layout or https://github.com/abbeyanke/se_sv_dvorak via ACTION_QUERY_KEYBOARD_LAYOUTS.
> 
> https://github.com/termux/termux-app/pull/2237#issuecomment-906028913

could 'am' handle this through a call?
