### ISSUE TITLE
[Bug]: Termux:Float shows "very old version" warning after update

### ISSUE THREAD

**Issue by J-Reis** [termux/termux-app#2501]
### Problem description

When competely uninstalled, then reinstalled from F-Droid, Termux & Termux:Float work as expected. However, after running `pkg update` Termux:Float always shows "You are likely using a very old version of Termux" warning.

<details>
<summary>Screenshot:</summary>

- ![Screenshot_20211231-090706_Brave](https://user-images.githubusercontent.com/23666144/147829971-7da2624d-8eb1-49d6-ba7a-3ebc67f777db.png)

</details>

[TermuxFloat_termux-info_fresh.log](https://github.com/termux/termux-app/files/7796594/TermuxFloat_termux-info_fresh.log)
[TermuxFloat_termux-info_post-update.log](https://github.com/termux/termux-app/files/7796595/TermuxFloat_termux-info_post-update.log)

### Steps to reproduce the behavior.

1. Uninstall all Termux apps via Setting > Apps menu: in my case Termux:Float, Termux:Styling, Termux:API & Termux.
2. Install Termux & Termux:Float via F-Droid
3. open/run Termux & update packages with `pkg update`
4. open Termux:Float

### What is the expected behavior?

normal function w/out version warning

### System information
```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.186-21635681 #1 SMP PREEMPT Wed Jul 28 15:37:01 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G960U
```

**Comment by agnostic-apollo** [comment]
This should automatically be fixed with  `termux-float` [v0.15.0](https://github.com/termux/termux-float/releases/tag/v0.15.0) release. Related issue termux/termux-float#39.
