### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-app#2506]
### Problem description

/main aarch64 Packages [332 kB]
Ign:4 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages
Get:5 https://packages.termux.org/apt/termux-science science/stable aarch64 Packages [18.9 kB]
Err:5 https://packages.termux.org/apt/termux-science science/stable aarch64 Packages
  File has unexpected size (14 != 18874). Mirror sync in progress? [IP: 139.178.84.50 443]
  Hashes of expected file:
   - Filesize:18874 [weak]
   - SHA512:35a8a21caaafd91d0e8ca008368d7e1826e6797f3158cbc891b2ff89ab39b1992ba322e59c8f5838b03f13222b408658807c361375dbca9d339d669bc0369981
   - SHA256:119f0bb6ed4e49798049dfe18639789a6994819c11ea1200639cabeb7558fc4e
   - SHA1:c99e2d1ac431f93f93d19714f9e6970431ccf47f [weak]
   - MD5Sum:5fc1c1669281eaa5763c4976a2de4bab [weak]
  Release file created at: Thu, 02 Dec 2021 08:36:02 +0000
Get:4 https://packages.termux.org/apt/termux-main stable/main aarch64 Packages [332 kB]
Reading package lists... Done
W: GPG error: https://packages.termux.org/apt/termux-games games InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
E: The repository 'https://packages.termux.org/apt/termux-games games InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
~ $

### Steps to reproduce the behavior.

Apt update error
PKG install update error

### System information

* Termux application version: 0.117
* Android OS version: 11
* Device model: MI 10T

**Comment by Grimler91** [comment]
Try again, should work now

**Comment by Saikatsaha1996** [comment]
> Try again, should work now. (Sidenote: game-repo and science-repo can be uninstalled, the repositories do not contain any packages anymore)

Ok thank you

**Comment by Saikatsaha1996** [comment]
> Try again, should work now. (Sidenote: game-repo and science-repo can be uninstalled, the repositories do not contain any packages anymore)

I should change repo? Or just try with PKG update?

**Comment by Saikatsaha1996** [comment]
> Try again, should work now. (Sidenote: game-repo and science-repo can be uninstalled, the repositories do not contain any packages anymore)

Not working
PKG update not working
Termux-change-repo after PKG update not working

**Comment by Grimler91** [comment]
@Saikatsaha1996 well what error do you get? Works fine for me with or without the empty repos:
```
~ $ apt update
Hit:1 https://its-pointless.github.io/files/24 termux InRelease
Hit:2 https://packages.termux.org/apt/termux-main stable InRelease
Get:3 https://packages.termux.org/apt/termux-games games InRelease [7654 B]
Hit:4 https://packages.termux.org/apt/termux-root root InRelease
Get:5 https://packages.termux.org/apt/termux-science science InRelease [7666 B]
Hit:6 https://packages.termux.org/apt/termux-x11 x11 InRelease
Fetched 15.3 kB in 5s (2804 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
9 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 well what error do you get? Works fine for me with or without the empty repos:
> 
> ```
> ~ $ apt update
> Hit:1 https://its-pointless.github.io/files/24 termux InRelease
> Hit:2 https://packages.termux.org/apt/termux-main stable InRelease
> Get:3 https://packages.termux.org/apt/termux-games games InRelease [7654 B]
> Hit:4 https://packages.termux.org/apt/termux-root root InRelease
> Get:5 https://packages.termux.org/apt/termux-science science InRelease [7666 B]
> Hit:6 https://packages.termux.org/apt/termux-x11 x11 InRelease
> Fetched 15.3 kB in 5s (2804 B/s)
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> 9 packages can be upgraded. Run 'apt list --upgradable' to see them.
> ```

![Screenshot_2022-01-05-03-30-09-334_com termux](https://user-images.githubusercontent.com/72664192/148129544-975e3f18-79c3-4433-af49-5687a2b64ca8.jpg)

**Comment by Grimler91** [comment]
Just remove those empty repos with `apt remove game-repo && apt remove science-repo`, and then upgrade all packages with `apt update && apt upgrade`. Error happens because the `termux-keyring` package is too old

**Comment by Saikatsaha1996** [comment]
> 

Thank you Done 🤗
One more thing thank you for clvk PKG
