### ISSUE TITLE
'termux-reload-settings' no longer refreshes bottom bar

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#2507]
### Problem description

typing or programatically calling 'termux-reload-settings' no longer has any effect on bottom bar settings and visual properties

### Steps to reproduce the behavior.

create or edit file termux.properties
keep session open
call 'termux-reload-settings'

### What is the expected behavior?

bottom bar, when changed (buttons or layout) should refresh instantly after comand is passed

### System information

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
libgnutls/stable 3.6.16-1 aarch64 [upgradable from: 3.6.15-3]
termux-tools/stable 0.155 all [upgradable from: 0.130]
util-linux/stable 2.37.2-1 aarch64 [upgradable from: 2.37]
Android version:
11
Kernel build information:
Linux localhost 4.19.113-22501734 #1 SMP PREEMPT Thu Oct 7 17:52:58 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T970

**Comment by xeffyr** [comment]
Check whether you have errors in extra keys row configuration. `termux-reload-settings` worked within version 0.117, not sure about latest git.

**Comment by nathaneltitane** [comment]
@xeffyr, the weird part is that the file changes are loaded when termux is completeley stopped and and a new session is opened but not when the command is called while termux is running...

My termux.properties file is as follows (hosted [here] and was sampled from the one in your wiki pages(https://raw.githubusercontent.com/nathaneltitane/terminal/master/termux/termux.properties)):

`
# use black for drawer and dialogs - Android 9.0+ default

use-black-ui=true

# enforce character based input - workaround for word-based input keyboards

enforce-char-based-input=true

# handle the bell character - vibrate | beep | ignore

bell-character=beep

# handle the escape key - escape | back

back-key=back

# rename current terminal session

shortcut.rename-session=ctrl+n

# open a new terminal with ctrl+t (volume down+t)

shortcut.create-session=ctrl+t

# move to previous terminal session

shortcut.previous-session=ctrl+1

# move to next terminal session

shortcut.next-session=ctrl+2

# configure keyboard shortcut keys

extra-keys=[														\
	['ESC', '|',    '/',   'HOME', 'UP',   'END',   'PGUP', '_', 'BKSP'			],	\
	['TAB', 'CTRL', 'ALT', 'LEFT', 'DOWN', 'RIGHT', 'PGDN', '-', 'RETURN'	]	\
]
`

**Comment by agnostic-apollo** [comment]
Set log level to `Debug` and see if `logcat -d` shows the `Received intent to reload styling` entry after running command or if some error is thrown.

https://github.com/termux/termux-app/blob/v0.117/app/src/main/java/com/termux/app/TermuxActivity.java#L839

**Comment by nathaneltitane** [comment]
> Set log level to `Debug` and see if `logcat -d` shows the `Received intent to reload styling` entry after running command or if some error is thrown.
> 
> https://github.com/termux/termux-app/blob/v0.117/app/src/main/java/com/termux/app/TermuxActivity.java#L839

logcat does not show any error - I really don'T know what happened but it seems to be functioning now - I did update to API 51 not too long ago, don'T know if this has anything to do with it.

Closing for now.

Thank you

**Comment by agnostic-apollo** [comment]
This seems to be some Samsung android 11 issue, where `BroadcastReceiver` does not work sometimes, closing #2277 as well.  Make sure to disable battery optimizations and grant `Draw Over Apps`, maybe that helps. Without more info we can't do anything.

https://dontkillmyapp.com/samsung

**Comment by WMCB-Tech** [comment]
I'm a non-samsung user here and does happen the same. although i'll try your suggestion to grant `Draw Over apps` suggestion see if it does refresh configurations immediately

**Comment by agnostic-apollo** [comment]
Great. Thanks!
