### ISSUE TITLE
[Bug]: nodejs fails under termux

### ISSUE THREAD

**Issue by DoveBoy** [termux/termux-app#2513]
### Problem description

nodejs fails under termux v0.118.0 - 2022-01-07 20.59. Running any version of nodejs inside termux is not responsive. v0.117 is normal

### Steps to reproduce the behavior.

pkg install nodejs
node xxx.js

### System information

* Termux application version:v0.118.0 - 2022-01-07 20.59
* Android OS version:12
* Device model:OPPO Find X3 Pro

**Comment by agnostic-apollo** [comment]
Working fine on Android 12 avd. You may wanna look into #2366.


## Transcript

````
Welcome to Termux!

Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

~ $ curl -L 'https://github.com/agnostic-apollo/tudo/releases/latest/download/tudo' -o "/data/data/com.termux/files/usr/bin/tudo"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- -  0     0    0     0    0     0      0      0 --:--:-- -100   135  100   135    0     0    136      0 --:--:-- --:--:-- --:--:--   136
100   643  100   643    0     0    454      0  0:00:01  0:00:01 --:--:--   454
  0     0    0     0    0     0      0      0 --:--:--   20  195k   20 40828    0     0  13047      0  0:00:15   49  195k   49 98507    0     0  27192      0  0:00:07  100  195k  100  195k    0     0  54830      0  0:00:03  0:00:03 --:--:-- 96026
~ $
~ $ export termux_bin_path="/data/data/com.termux/files/usr/bin"; export owner="$(stat -c "%u" "$termux_bin_path")"; chown "$owner:$owner" "$termux_bin_path/tudo" && chmod 700 "$termux_bin_path/tudo";
~ $ tudo -s --shell=node <(cat <<'TUDO_EOF'
console.log(`Hi, ${process.argv[2]} ${process.argv[3]}.`)
TUDO_EOF
) "node" "shell"
The "TUDO_SHELL" file at path "/data/data/com.termux/files/usr/bin/node" failed one or more of the following test types: [regular file], [readable], [executable]
Failed to validate "TUDO_SHELL"
~ $ apt install nodejs
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  c-ares libicu
Suggested packages:
  clang make pkg-config python
The following NEW packages will be installed:
  c-ares libicu nodejs
0 upgraded, 3 newly installed, 0 to remove and 1 not upgraded.
Need to get 17.6 MB of archives.
After this operation, 87.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.termux.org/apt/termux-main stable/main x86_64 c-ares x86_64 1.18.1 [124 kB]
Get:2 https://packages.termux.org/apt/termux-main stable/main x86_64 libicu x86_64 70.1 [9396 kB]
Get:3 https://packages.termux.org/apt/termux-main stable/main x86_64 nodejs x86_64 17.3.0-1 [8052 kB]
Fetched 17.6 MB in 15s (1184 kB/s)
Selecting previously unselected package c-ares.
(Reading database ... 4115 files and directories currently installed.)
Preparing to unpack .../c-ares_1.18.1_x86%5f64.deb ...
Unpacking c-ares (1.18.1) ...
Selecting previously unselected package libicu.
Preparing to unpack .../libicu_70.1_x86%5f64.deb ...
Unpacking libicu (70.1) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_17.3.0-1_x86%5f64.deb ...
Unpacking nodejs (17.3.0-1) ...
Setting up libicu (70.1) ...
Setting up c-ares (1.18.1) ...
Setting up nodejs (17.3.0-1) ...
~ $ tudo -s --shell=node <(cat <<'TUDO_EOF'
console.log(`Hi, ${process.argv[2]} ${process.argv[3]}.`)
TUDO_EOF
) "node" "shell"
Hi, node shell.
~ $ tudo -s --shell=node <(cat <<'TUDO_EOF'
const readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
})

readline.question(`What is your name?\n`, (name) => {
    console.log(`Hi, ${name}.`)
    readline.close()
})
TUDO_EOF
)
What is your name?
apollo
Hi, apollo.
~ $
````
##


## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##


## Device Info

### Software

**OS_VERSION**: `5.10.43-android12-9-00031-g02d62d5cece1-ab7792588`  
**SDK_INT**: `31`  
**RELEASE**: `12`  
**ID**: `SE1A.211012.001`  
**DISPLAY**: `sdk_gphone64_x86_64-userdebug 12 SE1A.211012.001 7818354 dev-keys`  
**INCREMENTAL**: `7818354`  
**SECURITY_PATCH**: `2021-11-05`  
**IS_DEBUGGABLE**: `1`  
**IS_EMULATOR**: `1`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `userdebug`  
**TAGS**: `dev-keys`  

### Hardware

**MANUFACTURER**: `Google`  
**BRAND**: `google`  
**MODEL**: `sdk_gphone64_x86_64`  
**PRODUCT**: `sdk_gphone64_x86_64`  
**BOARD**: `goldfish_x86_64`  
**HARDWARE**: `ranchu`  
**DEVICE**: `emulator64_x86_64_arm64`  
**SUPPORTED_ABIS**: `x86_64, arm64-v8a`  
##


## Termux APT Info


### Subscribed Repositories

#### sources.list
`deb https://packages.termux.org/apt/termux-main/ stable main`
##


### Updatable Packages

```
apt/stable 2.3.13-4 x86_64 [upgradable from: 2.3.13-3]
```
##



##

**Comment by DoveBoy** [comment]
@agnostic-apollo The nodejs installation is working, and the node commands are recognized as normal, but I can't run the program with node xxx.js
![Screenshot_2022-01-11-14-08-04-16_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/19201447/148890560-6e577af7-a34d-4f44-8d1e-e805e51a75fc.jpg)

**Comment by agnostic-apollo** [comment]
As already shown above, simple nodejs commands are working. You can create a file yourself with the commands and test. As for whether `jd_sign.js` does or doesn't work, open an issue in the respective repository where you downloaded the script. We don't provide support for 3rd party tools. If issue is in fact being caused by termux, provide simple sample scripts and proof.

**Comment by DoveBoy** [comment]
@agnostic-apollo The same script, 0.117 runs fine, 0.118 runs without any response.
[jd_bean_sign.js](https://gist.github.com/DoveBoy/5eb133a8b5d6da7128a030b80a93e00b)

**Comment by xeffyr** [comment]
@DoveBoy Application and packages are independent. Application is just display, nothing more.

**Comment by DoveBoy** [comment]
@xeffyr The same nodejs version is not as compatible on 0.118 as on 0.117, and many of the same scripts do not work on 0.118

**Comment by agnostic-apollo** [comment]
Provide video/transcript of **fresh install** of `0.117` and `0.118.0` showing the same script doesn't work. You may be missing a config file that's causing a problem. I will also not run random scripts on my devices, which is also downloading other scripts from the internet. Narrow down the issue and provide a smaller script with it only.

The only reason for differences in behaviour between versions could be changes to terminal view or emulator, but don't think any were made in this release that would cause "no response". And changes have been available on github for many months and nobody has reported an issue, so it's more likely you are doing something wrong.

**Comment by DoveBoy** [comment]
@agnostic-apollo
![Screenshot_2022-01-11-20-18-10-08_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/19201447/148943175-a00a8830-6ed6-44d6-8139-3604d396c460.jpg)
![Screenshot_2022-01-11-20-18-16-04_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/19201447/148943188-49db7dc1-bfcd-4a58-a38a-4ca053b92280.jpg)
![Screenshot_2022-01-11-20-31-56-81_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/19201447/148943203-7718f6b2-6bf3-4c6c-ae04-46f236d56f30.jpg)
![Screenshot_2022-01-11-20-32-03-86_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/19201447/148943211-ed507a97-2579-468f-bbd9-06f9074234d6.jpg)
 
The same nodejs version and script. `0.118` not work. `0.117` work fine.

**Comment by Grimler91** [comment]
@DoveBoy give output of `termux-info` in both versions. 
Most likely nodejs and/or it's dependencies are old in your 0.117 installation.

**Comment by DoveBoy** [comment]
Repeatedly switch between the two versions to test, each time needing to uninstall and reinstall. Can I test with a virtual machine since it already affects normal use?

**Comment by agnostic-apollo** [comment]
Yes, but test with only official android studio virtual devices, not any third party ones.

https://developer.android.com/studio/run/managing-avds
