### ISSUE TITLE
[Feature]: Dynamic dark/light theme switch based on current OS dark/light mode

### ISSUE THREAD

**Issue by humky** [termux/termux-app#2516]
### Feature description

Currently the termux interface color is set to black or white based on Android OS dark/light mode at a time of termux launch, the interface colors doesn't update mid session when Android dark/light mode is changing.
Proposal: Change termux interface color based on current OS light/dark mode dynamically.

Currently there are no ways of setting dark/light termux themes for dynamic switch along with the OS dark/light mode.
Proposal: Something like
`dark-theme = base16-one-dark`
`light-theme = base16-one-light`
Switch between them based on current OS dark/light mode dynamically.

### Additional information

I'm not familiar with other implementations.

**Comment by agnostic-apollo** [comment]
Already implemented locally, will be available in next/future versions.

**Comment by Vixeliz** [comment]
Not to be that person who ask just to ask but im genuinely curious since it's been a decent amount of time if this is available and im missing it or if it's still not implemented? If it isn't implemented is it still planned or would you be looking for a pr from someone else?

**Comment by agnostic-apollo** [comment]
Closed in 6631599f and d96883c and available in github action builds. Will be available in next release.

**Comment by lakshyarao22** [comment]
Not available till date.
