### ISSUE TITLE
I can't execute sudo apt update while i have root.

### ISSUE THREAD

**Issue by kakahost** [termux/termux-app#2517]
### Problem description

It says "You should not use command 'apt' as root. This is dangerous as may damage your Termux installation and data."

### Steps to reproduce the behavior.

It says "You should not use command 'apt' as root. This is dangerous as may damage your Termux installation and data."

### System information

* Termux application version: playmarket
* Android OS version: 10
* Device model: Mi A2 Lite

**Comment by Grimler91** [comment]
Intended behaviour. Why do you want to run apt as root?
