### ISSUE TITLE
Use the external storage if avaliable

### ISSUE THREAD

**Issue by GreenJoey** [termux/termux-app#252]
Termux currently uses its private data directory in /data/data to store all the store. But this becomes a little pain when the packages installed and the files in the Termux /home grows. Like for example I have Python, c-lang, ruby, rails and django installed and my termux data size has grown over 50MB. As the internal storage is also used by the OS to install apps and is the default storage for all apps, Termux becomes a problem. So why not use the devices' external storage for Termux files. Not will Termux get more space but will also keep the device's internal storage free.

**Comment by natebass** [comment]
I don't think Termux can get permission to execute files from the sdcard. For example:

```shell
/data/data/com.termux/files/home
⟩ cd /sdcard/Download/

/sdcard/Download
⟩ touch foo.txt

/sdcard/Download
⟩ ls -l
total 0
-rw-rw---- 1 root everybody 0 Feb  5 06:11 foo.txt

/sdcard/Download
⟩ chmod +x foo.txt 
chmod: changing permissions of 'foo.txt': Operation not permitted
```

**Comment by fornwall** [comment]
Right, the external storage on Android does not permit executable files.

Other parts (non-executable files) could be stored there, but I don't now if there is any easy robust way to do that in a general way from Termux side, so that should perhaps be left up to users to do case by case.

**Comment by GreenJoey** [comment]
But you use sdcard for /home??

**Comment by GreenJoey** [comment]
Also I am sure you can do. Before setting down with Termux, I used to use Linux Deploy. I installed Ubuntu, Arch and Kali, all on directory install. All worked fine. I guess vfat supports permissions and Linux can handle permissions on fat partitions

**Comment by natebass** [comment]
I see [LinuxDeploy](https://play.google.com/store/apps/details?id=ru.meefik.linuxdeploy&hl=en) requires root. @GreenJoey Could you install it on the sdcard?

**Comment by Grimler91** [comment]
@GreenJoey, I'm wondering the same as @natebass, doesn't LinuxDeploy require root and an extra partition on the external sdcard?

**Comment by GreenJoey** [comment]
@natebass  Yup. I always used to use Linux Deploy images on sdcard

**Comment by GreenJoey** [comment]
@natebass @Grimler91 Linux Deploy requires root for chrooting into the deployed Linux partition, not for installing Linux in sdcard

**Comment by GreenJoey** [comment]
I worked around it by using virtualenv and Termux's external storage
