### ISSUE TITLE
Is there any way to attach java process directly to EmulatorView ?

### ISSUE THREAD

**Issue by eakteam** [termux/termux-app#2520]
### Feature description

I wonder if there is any easy way to only import `terminal-emulator` and `terminal-view` (Termux Core) and use them to read directly from Java process ex. `System.getEnvironment().exec()` ?

### Additional information

This would be great for custom builds

**Comment by eakteam** [comment]
Thank you !

**Comment by agnostic-apollo** [comment]
Welcome. Btw you can just import the `termux-shared` library in your own apps. Check https://github.com/termux/termux-app/wiki/Termux-Libraries.
