### ISSUE TITLE
[Feature]: Highlighting links in the terminal (underlining)

### ISSUE THREAD

**Issue by snooppr** [termux/termux-app#2525]
### Feature description

Highlighting links in the terminal (underlining).

When the user has set the config 
`terminal-onclick-url-open=true`
 found links in the terminal should be underlined and show the user that it is a link and not a string.  An example, when the output in the CLI is large, you need to look at what is a link and what is a string (underlining, highlighting links in the CLI is a classic).

Example v.0.118.0
🌎  Spotify_community: https://community.spotify.c
om/t5/forums/searchpage/tab/user?q=admin
🇷🇺  Sprashivai: http://sprashivai.ru/admin?sl
🌎  Stackoverflow:
https://stackoverflow.com/users/?search=admin
🌎  Steamcommunity:
https://steamcommunity.com/id/admin
🌎  SteamGroup:
https://steamcommunity.com/groups/admin
🌎  Steamid: https://steamid.uk/profile/admin
🌎  Strava: https://www.strava.com/athletes/admin

Example v.0.119.0
🌎  Spotify_community: h̲t̲t̲p̲s̲:̲/̲/̲c̲o̲m̲m̲u̲n̲i̲t̲y̲.̲s̲p̲o̲t̲i̲f̲y̲.̲c̲
̲o̲m̲/̲t̲5̲/̲f̲o̲r̲u̲m̲s̲/̲s̲e̲a̲r̲c̲h̲p̲a̲g̲e̲/̲t̲a̲b̲/̲u̲s̲e̲r̲?̲q̲=̲a̲d̲m̲i̲n̲
🇷🇺  Sprashivai: h̲t̲t̲p̲:̲/̲/̲s̲p̲r̲a̲s̲h̲i̲v̲a̲i̲.̲r̲u̲/̲a̲d̲m̲i̲n̲?̲s̲l̲
🌎  Stackoverflow:
h̲t̲t̲p̲s̲:̲/̲/̲s̲t̲a̲c̲k̲o̲v̲e̲r̲f̲l̲o̲w̲.̲c̲o̲m̲/̲u̲s̲e̲r̲s̲/̲?̲s̲e̲a̲r̲c̲h̲=̲a̲d̲m̲i̲n̲
🌎  Steamcommunity:
h̲t̲t̲p̲s̲:̲/̲/̲s̲t̲e̲a̲m̲c̲o̲m̲m̲u̲n̲i̲t̲y̲.̲c̲o̲m̲/̲i̲d̲/̲a̲d̲m̲i̲n̲
🌎  SteamGroup:
h̲t̲t̲p̲s̲:̲/̲/̲s̲t̲e̲a̲m̲c̲o̲m̲m̲u̲n̲i̲t̲y̲.̲c̲o̲m̲/̲g̲r̲o̲u̲p̲s̲/̲a̲d̲m̲i̲n̲
🌎  Steamid: h̲t̲t̲p̲s̲:̲/̲/̲s̲t̲e̲a̲m̲i̲d̲.̲u̲k̲/̲p̲r̲o̲f̲i̲l̲e̲/̲a̲d̲m̲i̲n̲
🌎  Strava: h̲t̲t̲p̲s̲:̲/̲/̲w̲w̲w̲.̲s̲t̲r̲a̲v̲a̲.̲c̲o̲m̲/̲a̲t̲h̲l̲e̲t̲e̲s̲/̲a̲d̲m̲i̲n̲

Please correct if possible.

### Additional information

...

**Comment by agnostic-apollo** [comment]
That can't be added. Terminals have specific specs which must be followed for displaying data and it can't be modified for links since there may be conflicts. Use escape sequences to highlight them yourself in your source data if you want.
