### ISSUE TITLE
[Bug]: pkg upgrade fails due to DNS problems, probably regression

### ISSUE THREAD

**Issue by xandro0777** [termux/termux-app#2529]
### Problem description

"pkg upgrade" cant resolve any mirror and says "Something wicked happened resolving 'packages.termux.org:https'. "

The mirrors are accessible if I access them with Fennec browser.

I have installed this instance of termux about a week ago and downloaded some packages without problems even a few days ago but doesn't work since at least 2 days.

Probably related to recent update of Termux that was 4 days ago on F-droid.

In strace I see the following:
```
14632 connect(3, {sa_family=AF_UNIX, sun_path="/dev/socket/dnsproxyd"}, 110) = 0
14629 rt_sigprocmask(SIG_BLOCK, [WINCH RTMIN],  <unfinished ...>
14632 fcntl(3, F_GETFL)                 = 0x2 (flags O_RDWR)
14629 <... rt_sigprocmask resumed>[RTMIN], 8) = 0
14632 fstat(3,  <unfinished ...>
14629 rt_sigprocmask(SIG_SETMASK, [RTMIN],  <unfinished ...>
14632 <... fstat resumed>{st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
14629 <... rt_sigprocmask resumed>[WINCH RTMIN], 8) = 0
14632 write(3, "getaddrinfo packages.termux.org "..., 51) = 51
14629 write(1, "\33[33m\r0% [Working]", 18 <unfinished ...>
14632 read(3,  <unfinished ...>
14629 <... write resumed>)              = 18
14629 write(1, "\33[0m", 4)             = 4
14629 pselect6(9, [5], [8], NULL, {tv_sec=0, tv_nsec=500000000}, NULL) = 2 (in [5], out [8], left {tv_sec=0, tv_nsec=499990077})
14629 read(5, "102 Status\nMessage: Connecting t"..., 64000) = 127
14629 write(8, "600 URI Acquire\nURI: https://pac"..., 574) = 574
14629 pselect6(6, [5], [], NULL, {tv_sec=0, tv_nsec=499990000}, NULL <unfinished ...>
14632 <... read resumed>"401\0\0\0\0\4\2\0\0\0", 4096) = 12
```
Any idea?

### Steps to reproduce the behavior.

pkg upgrade

### What is the expected behavior?

find a mirror and download packages

### System information

* Termux application version: 0.118.0 F-droid
* Android OS version: 11
* Device model: Realme

**Comment by Grimler91** [comment]
Have you tried another mirror?

**Comment by xandro0777** [comment]
@Grimler91:  None works.

**Comment by xandro0777** [comment]
Started working again without any change on my phone or network. 

I would leave it open for a few more days - if others should encounter the same problem the strace in the bug description might be helpful to debug it.

**Comment by xandro0777** [comment]
still works and nobody else complained, closing it.
