### ISSUE TITLE
Extra key on overly

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-app#253]
I'd be nice if you add shift key on overly along with cntrl and alt keys...

**Comment by rsdoiel** [comment]
it would be nice to have a ribbon similar to SSH Juices ribbon that has home, array, page up/down, Ctrl, ATL, etc.

**Comment by luisdavim** [comment]
Yes, something like juicy ssh's overlay would be awesome.

**Comment by xeffyr** [comment]
@Auxilus Shouldn't be this closed ?

**Comment by Auxilus** [comment]
@xeffyr yup.. thanks for the ping
