### ISSUE TITLE
[Feature]: Don't auto open keyboard when switching from other apps

### ISSUE THREAD

**Issue by Mark-Joy** [termux/termux-app#2532]
### Feature description

1. When switching from other apps, soft-keyboard is automatically open. It's a bit annoying when you just want to see the log on the terminal screen. Please make this action configurable.

### Additional information

2. Far better if we can configure open soft-keyboard on double-click or long press on terminal screen.

Thank you.

**Comment by Grimler91** [comment]
It's a good suggesrion. `soft-keyboard-toggle-behaviour = enable/disable` in .termux/termux.properties makes it to "disable" the keyboard until the `KEYBOARD` is pressed again, bit doesn't sound like that is quite what you are after

**Comment by agnostic-apollo** [comment]
`hide-soft-keyboard-on-startup=true` 1ef8eb92
