### ISSUE TITLE
[Feature]: Add button to open side menu in menu opened by menu key

### ISSUE THREAD

**Issue by Soundtoxin** [termux/termux-app#2537]
### Feature description

Recently I am having lots of trouble swiping in from the left to slide out the sessions list. May or may not be related to TUI apps with mouse support being open. I wish pressing menu for the popup also had a way for me to get to those options so I could still switch between my sessions easily when the gesture isn't working.

### Additional information

I don't know why this second box is necessary.

**Comment by agnostic-apollo** [comment]
There is an issue with `v0.118.0` on some devices where drawer is harder to open now, needs to be investigated. Set like `terminal-margin-horizontal=3` in `termux.properties` and see if that helps? Change value as needed.

https://github.com/termux/termux-app/releases/tag/v0.118.0

https://github.com/termux/termux-app/commit/63504f0a

There is already a `DRAWER` extra key.

https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by Soundtoxin** [comment]
Thank you very much! I didn't know about that configuration file or the stuff you could change at all! Very cool.

The margin thing helps but is not perfect. I have it on 6 now, and I can get it to work at least 1/3 attempts now, works best if I go slow. I bound the drawer key as well, so I shouldn't get stuck like before.

**Comment by agnostic-apollo** [comment]
You are welcome. You may want to try first tapping the (top) edge for peeking and then swiping.
