### ISSUE TITLE
[Bug]: Font errors

### ISSUE THREAD

**Issue by Player1041** [termux/termux-app#2539]
### Problem description

I'm using Android 12 and One UI 4 on a Samsung Galaxy S10 and some letters show as stretched and broken.
![image](https://user-images.githubusercontent.com/95597200/150599071-6873aeb1-ed9b-495f-bfef-19feca1c6344.png)
It worked fine on Android 11 but I don't know why 12 broke it.
I downloaded it through F-Droid on an unrooted device.
Latest version.

Any help would be good.

### Steps to reproduce the behavior.

Android 12 on One UI 4, open the app. That's it.

### What is the expected behavior?

Normal text.

### System information

* Termux application version: 0.117 ?
* Android OS version: 12
* Device model: Samsung Galaxy S10

**Comment by agnostic-apollo** [comment]
Upload a higher resolution photo, doesn't seem broken. Also confirm termux version.

**Comment by Player1041** [comment]
> Upload a higher resolution photo, doesn't seem broken. Also confirm termux version.
> 
> 

Ok.
![SmartSelect_20220121-205320_Termux.jpg](https://user-images.githubusercontent.com/95597200/150611812-e8c8239d-a519-433a-823d-fc2791846440.jpg)
Is that better?
Also the version according to F-Droid is 0.117

**Comment by agnostic-apollo** [comment]
Latest on F-Droid is `v0.118.0`.

Install Termux:Styling, then long hold on terminal -> More -> Style -> Change Font. Then try switching to a different font and also back to default. Exit termux after font change or run `termux-reload-settings`.

If samsung messed up the default monospace font, complain to them.

**Comment by Player1041** [comment]
> Latest on F-Droid is `v0.118.0`.
> 
> Install Termux:Styling, then long hold on terminal -> More -> Style -> Change Font. Then try switching to a different font and also back to default. Exit termux after font change or run `termux-reload-settings`.
> 
> If samsung messed up the default monospace font, complain to them.

Ok, yeah that's Samsung fucking up. 
Is there a way to download fonts for Termux?

**Comment by agnostic-apollo** [comment]
ttf files are available online for many different fonts. You can try roboto and noto fonts which are used by android by default. Maybe there an option to change fonts in samsung android settings.

https://fonts.google.com/noto/specimen/Noto%20Sans%20Mono

u/RatchetGuy also reported a font issue on r/tasker for Android 12 OneUI 4.0.

https://www.reddit.com/r/tasker/comments/s9chzy/tasker_widget_text_not_fully_visible_on_android/
