### ISSUE TITLE
[Bug]: vnc process terminated when switching to different app

### ISSUE THREAD

**Issue by magbulogtong81** [termux/termux-app#2540]
### Problem description

I have this weird bug on android 11 where the vncserver is killed whenever i switch to vnc viewer. i checked pstree to verify that the process for vncserver is running.
it is on ubuntu proot-distro and i used tightvncserver for vnc and xfce4 for desktop environment.

its weird because i know this works on android 9 and below. ( i can't remember if this works on this phone with android 10)

here's what happend shown on video below

https://user-images.githubusercontent.com/46246619/150596194-42981a22-b554-4070-9605-d940d7d0d441.mp4

(here's a [google drive link](https://drive.google.com/file/d/158ZfR-l2_kiZQYP3FAoOqhSsNg32YMp0/view?usp=drivesdk) incase the video doesn't work here)

### Steps to reproduce the behavior.

`cat proot-ubuntu-login.sh` shows my script that runs:
`proot-distro login ubuntu --user lil` where "lil" is the user
`./proot-ubuntu-login.sh` (login with ubuntu)
`vncserver :1` (runs vnc on port 5901)
`pstree` (shows process tree)
then when I open it with vnc viewer(`localhost:5901` or `127.0.0.1:5901`), it says that the it can't connect to the server
when i switch back to termux, i ran `pstree`, but the vnc process is not there anymore

### What is the expected behavior?

the vncserver process is terminated when you switch to other apps. (vnc viewer app in this case)

### System information

* Termux application version: 0.117
* Android OS version: android 11
* Device model: oppo A53 (cph2127)

**Comment by agnostic-apollo** [comment]
Try running the server in foreground with `vncserver -fg :1` since daemon may be getting killed by android.

 https://manpages.debian.org/unstable/tigervnc-standalone-server/tigervncserver.1.en.html

**Comment by WilsonBradley** [comment]
Having same problem when running server
nethunter kex 
Process dies within a 1-2 minutes
What to use in command line to run in foreground?

Tanx

**Comment by agnostic-apollo** [comment]
https://wiki.termux.com/wiki/Hacking

**Comment by magbulogtong81** [comment]
for those who might encounter this issue, try this:
download tini from [here](https://github.com/krallin/tini/releases) 

it might get downloaded with filename like ``tini-arm64``. if it does, just rename it to ``tini``

put it in your $PATH

add a .profile entry with nano or vim

paste this:
``if [ -z "$TINI_SESSION" ]``
``then``
        ``export TINI_SESSION="1"``
        ``exec tini -s bash``
``fi``

close termux and open it again

type ``ps``

if it shows like this:
``PID TTY          TIME CMD``
``22845 pts/0    00:00:00 tini``
``22960 pts/0    00:00:00 bash``
``32212 pts/0    00:00:00 ps``

then it's working. if it's showing a different one, you did it wrong.

**Comment by WilsonBradley** [comment]
> for those who might encounter this issue, try this: download tini from [here](https://github.com/krallin/tini/releases)
> 
> it might get downloaded with filename like `tini-arm64`. if it does, just rename it to `tini`
> 
> put it in your $PATH
> 
> add a .profile entry with nano or vim
> 
> paste this: `if [ -z "$TINI_SESSION" ]` `then` `export TINI_SESSION="1"` `exec tini -s bash` `fi`
> 
> close termux and open it again
> 
> type `ps`
> 
> if it shows like this: `PID TTY TIME CMD` `22845 pts/0 00:00:00 tini` `22960 pts/0 00:00:00 bash` `32212 pts/0 00:00:00 ps`
> 
> then it's working. if it's showing a different one, you did it wrong.

Thank you so much... Will give this a try to see if the process stays (will report back).. Appreciate it.!!

**Comment by WilsonBradley** [comment]
> for those who might encounter this issue, try this: download tini from [here](https://github.com/krallin/tini/releases)
> 
> it might get downloaded with filename like `tini-arm64`. if it does, just rename it to `tini`
> 
> put it in your $PATH
> 
> add a .profile entry with nano or vim
> 
> paste this: `if [ -z "$TINI_SESSION" ]` `then` `export TINI_SESSION="1"` `exec tini -s bash` `fi`
> 
> close termux and open it again
> 
> type `ps`
> 
> if it shows like this: `PID TTY TIME CMD` `22845 pts/0 00:00:00 tini` `22960 pts/0 00:00:00 bash` `32212 pts/0 00:00:00 ps`
> 
> then it's working. if it's showing a different one, you did it wrong.

Sorry, noob here.. When you say put in your $PATH, you mean copy  tini & .profile to here for example; 
/data/data/com.termux/files/home
? Im doing this on a phone so, copy/paste doesnt even seem to carry over from browser to termux. Termux doesnt seem to have edit functions..

**Comment by magbulogtong81** [comment]
> Sorry, noob here.. When you say put in your $PATH, you mean copy tini & .profile to here for example; /data/data/com.termux/files/home ? Im doing this on a phone so, copy/paste doesnt even seem to carry over from browser to termux. Termux doesnt seem to have edit functions..

you could download tini with wget
(example: wget https://github.com/krallin/tini/releases/download/v0.19.0/tini-arm64)

what i mean about the $PATH is you should put the tini to a directory where you could execute it system wide
(on linux, $PATH contains multiple directories)
/data/data/com.termux/files/usr/bin should be your default $PATH

what i mean about the .profile entry is that you should create the ``.profile`` as a text file using nano or vim(or any text editor) on your home directory then paste the script mentioned above

**Comment by magbulogtong81** [comment]
I forgot to mention, you should select the static build to make it work
![Screenshot_2022-11-22-06-46-35-21_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/46246619/203174077-5c32293a-90dd-46cb-8dbf-622a838a4d5e.jpg)

also, you should select the correct version for your device architecture.
(you could check it by executing:
``dpkg --print-architecture`` on termux)
if it shows arm/armhf, then select armhf
if it shows arm64/aarch64, then select arm64
if it shows i386, then select i386
if it shows amd64, then select amd64

**Comment by WilsonBradley** [comment]
Thank you so much for your time/help
I went ahead and installed openssh and was able to ssh from desktop (so cut / paste works ;-) )
It's arm64
I followed your instructions and tini is not running yet.. :-(
~ $ ps
  PID TTY          TIME CMD
24692 pts/1    00:00:00 bash
24744 pts/1    00:00:00 ps
-------------------------------------------------
I wget tini into here and the .profile into here;

/data/data/com.termux/files/usr/bin

**Comment by magbulogtong81** [comment]
> I wget tini into here and the .profile into here;
> 
> /data/data/com.termux/files/usr/bin

no, that's wrong. ``.profile`` must be on home directory, so that termux will automatically execute the script, and tini must be on $PREFIX/bin; check the images below
![IMG_20221123_222952](https://user-images.githubusercontent.com/46246619/203573264-4270a691-00f0-475a-b492-935dd2fc6328.jpg)
![IMG_20221123_223215](https://user-images.githubusercontent.com/46246619/203573280-c139ddc6-0ab2-4c63-b5a2-f1bf00f5d131.jpg)

**Comment by WilsonBradley** [comment]
Thank you so much.. 
Sorry this is so problematic... 
This reminds me of "one step forward, two steps back"

I got the .profile script to run at start. However, It seems I did not have the tini extracted in correct place/or script can't find it now. Once I start termux-app now, it runs script but kills session once it can't find it. 
Is there a way to access the files in the Termux "container" ? I need to either place tini in correct location or disable start script now. 

......  .     .  .
 - X11:     pkg install x11-repo

For fixing any repository issues,
try 'termux-change-repo' command.

Report issues at https://termux.dev/issues
**bash: exec: tini: not found**

**[Process completed (code 127) - press Enter]**

**Comment by WilsonBradley** [comment]
@sylirre @magbulogtong81 
YAY!!!! Got tini working.
~ $ ps
  PID TTY          TIME CMD
 3338 pts/1    00:00:00 tini
 3371 pts/1    00:00:00 bash
 3443 pts/1    00:00:00 ps

Thank you so much!!!
Hoping this will help keep kex running on Android without it killing it within 1-3 min.. 
However, I did learn a lot. Appreciate all your help..

**Comment by WilsonBradley** [comment]
For all Android users above Version 8>  Hope this helps you guys..
There is a adb workaround and can validate it works, (until reboot)
adb into connected phone and paste below;
 adb shell "/system/bin/device_config put activity_manager max_phantom_processes 2147483647"
More info here;
https://youtu.be/jSHpmvfNUUA
https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#device_config-command

**Comment by agnostic-apollo** [comment]
>For all Android users above Version 8> Hope this helps you guys..

Phantom process killer was added in Android 12.

**Comment by magbulogtong81** [comment]
> @sylirre @magbulogtong81 YAY!!!! Got tini working. ~ $ ps PID TTY TIME CMD 3338 pts/1 00:00:00 tini 3371 pts/1 00:00:00 bash 3443 pts/1 00:00:00 ps
> 
> Thank you so much!!! WAS, hoping this would have helped keep kex (Xtigervnc) running on Android without it killing it within 1-2 min.. But still no.. 

huh. have you tried running a different server? like ssh or httpd? just to see if those also get killed.
