### ISSUE TITLE
[Feature]: link to "Backup" on "Getting started"

### ISSUE THREAD

**Issue by beroal** [termux/termux-app#2541]
### Feature description

Backups are encouraged on the "Getting started" page in the Wiki, but it isn't mentioned that backups should be done in a special way (the "Backing up Termux" page).

I would edit it myself, but I'm not sure whether I'll be able to edit it if I register an account in the Wiki.

### Additional information

Not applicable

**Comment by agnostic-apollo** [comment]
Link to https://wiki.termux.com/wiki/Backing_up_Termux has been added in https://wiki.termux.com/wiki/Getting_started.

>I'm not sure whether I'll be able to edit it if I register an account in the Wiki.

It is no longer allowed for random users to edit wiki, even with an account.
