### ISSUE TITLE
[Bug]: where is termux-notifcation , api package is installed

### ISSUE THREAD

**Issue by fxmbsw7** [termux/termux-app#2547]
### Problem description

i cant find the notif part of termux api ( and prolly every other api program too )
the packages were via f droid installed

termux-tabtab shows
termux-am               termux-info             termux-restore
termux-backup           termux-open             termux-setup-storage
termux-change-repo      termux-open-url         termux-wake-lock
termux-chroot           termux-reload-settings  termux-wake-unlock
termux-fix-shebang      termux-reset

### Steps to reproduce the behavior.

its not in $PATH

### What is the expected behavior?

not miss the bin

### System information

* Termux application version: 0.118
* Android OS version: 12
* Device model: realme gt rmx2202

**Comment by Grimler91** [comment]
Sounds like you haven't installed the `termux-api` package, `pkg in termux-api`
