### ISSUE TITLE
[Feature]: Disable "Open with Termux"

### ISSUE THREAD

**Issue by Worldwidebrine** [termux/termux-app#2549]
### Feature description

It's really annoying to see Termux in "Open with" when I click any of my files. Even apk.
To import files into Termux, I can just click "Share" though.

I should be able to disable it.

### Additional information

Other terminal apps? They don't even show up in "Open with" so they don't need.

**Comment by PacMicro** [comment]
> ### 功能描述
> 当我单击任何文件时，在“打开方式”中看到 Termux 真的很烦人。甚至是.apk。 要将文件导入 Termux，我只需单击“共享”即可。
> 
> 我应该可以禁用它。
> 
> ### 附加信息
> 他们甚至没有出现在“打开方式”中，所以他们不需要。

This is useless function, you can just ignore it

> ### Feature description
> It's really annoying to see Termux in "Open with" when I click any of my files. Even apk. To import files into Termux, I can just click "Share" though.
> 
> I should be able to disable it.
> 
> ### Additional information
> They don't even show up in "Open with" so they don't need.



> ### 功能描述
> 当我单击任何文件时，在“打开方式”中看到 Termux 真的很烦人。甚至是.apk。 要将文件导入 Termux，我只需单击“共享”即可。
> 
> 我应该可以禁用它。
> 
> ### 附加信息
> 他们甚至没有出现在“打开方式”中，所以他们不需要。

This is a pointless feature, you don't want to see Termux in the list you can uninstall it 😄

**Comment by PacMicro** [comment]
> ### 功能描述
> 当我单击任何文件时，在“打开方式”中看到 Termux 真的很烦人。甚至是.apk。 要将文件导入 Termux，我只需单击“共享”即可。
> 
> 我应该可以禁用它。
> 
> ### 附加信息
> 他们甚至没有出现在“打开方式”中，所以他们不需要。

This is a pointless feature, you don't want to see Termux in the list you can uninstall it 😄

**Comment by Grimler91** [comment]
It's a pretty useful feature. Maybe you want to download and automatically decompile an apk with apktool, or download a pdf and automatically import it into a zotero or papis bibliography.

The termux-file-edit script can do different actions depending on file type, so for example:

```
$ cat ~/bin/termux-file-editor
#!/data/data/com.termux/files/usr/bin/sh

if [ "${1##*.}" = "apk" ]; then
    cd ~/apks
    apktool decode "$1"
elif [ "${1##*.}" = "pdf" ]; then
    papis add "$1"
fi
```

**Comment by Grimler91** [comment]
(I don't think it is possible to add a disable option for this, since it needs to modify the AndroidManifest, but keeping open to let someone more knowledgeable answer that)

**Comment by agnostic-apollo** [comment]
It's possible dynamically by disabling the `Activity` component. Already added helper utils for it, need to add toggle in termux settings. 075a080f

**Comment by UnknownErrror** [comment]
Probably `.filepicker.TermuxFileReceiverActivity` activity can be split into 2 different activities:

First with `android.intent.action.SEND` support
Second with `android.intent.action.VIEW` support

And add activity disabling options into settings

So users can disable intents they don't want to use ("Open with" is too annoying, if I want open file in Termux I will "Share" it)

**Comment by agnostic-apollo** [comment]
Yeah, splitting of `VIEW` and `SEND` will need to be done.

Unfortunately, you can't update manifest `intent-filter`s dynamically. However, the `View` `mimeTypes` can be split into separate `intent-filter`s so that support can be added to disable individual `mimeTypes` with `activity-alias`, but then multiple entries will show in share menu and likely every user would not want that. It would increase choosing time too for a user so that the right file is sent through right receiver. One can handle `mimeTypes` in the script itself anyways. Users who have problems with termux automatically opening without android showing any chooser will just have to use the toggle to completely disable every `mimeType` or allow all.

https://github.com/termux/termux-app/blob/2a1c5a70da4739cf8284f4df7be720f24cafba8c/app/src/main/AndroidManifest.xml#L131

https://stackoverflow.com/a/10403074

**Comment by agnostic-apollo** [comment]
Btw, you can run `pm disable com.termux/.filepicker.TermuxFileReceiverActivity` from adb or root shell to disable the component. It will of course disable both `VIEW` and `SEND`. Can enable it again with `pm enable`.

**Comment by Tachi107** [comment]
> you can run `pm disable com.termux/.filepicker.TermuxFileReceiverActivity` from adb or root shell to disable the component

Do you need root access from adb to be able to run this command? While running it with `adb shell`, it throws a `SecurityException`

**Comment by twaik** [comment]
farmerbb's Taskbar can disable it's Launcher component on demand. [The code](https://github.com/farmerbb/Taskbar/blob/db983e405f8d77ab39d91c6d8c3ff1b6fdbc374f/app/src/main/java/com/farmerbb/taskbar/util/U.java#L1956):
```
    public static void setComponentEnabled(Context context, Class<?> clazz, boolean enabled) {
        ComponentName component = new ComponentName(context, clazz);
        context.getPackageManager().setComponentEnabledSetting(component,
                enabled ? PackageManager.COMPONENT_ENABLED_STATE_ENABLED
                        : PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                PackageManager.DONT_KILL_APP);
    }
```

**Comment by agnostic-apollo** [comment]
> farmerbb's Taskbar can disable it's Launcher component on demand.

Termux [uses it too](https://github.com/termux/termux-app/issues/2549#issuecomment-1024897794). Will probably add a `termux.properties` prop for it instead.

**Comment by twaik** [comment]
Wow. Did not know. Thanks.

**Comment by agnostic-apollo** [comment]
>it throws a SecurityException

App may need to be debuggable.

>Wow. I did not know. Thanks.

You are welcome.

**Comment by Tachi107** [comment]
Thanks!

**Comment by agnostic-apollo** [comment]
Welcome.

**Comment by vonguyenkhang** [comment]
I have both `disable-file-view-receiver=true` and `disable-file-share-receiver=true` in termux.properties file, but both file share and file view are still not disabled after termux-reload-settings and reboot.
My phone is Xiaomi Redmi Note 9 Pro Global (joyeuse), MIUI 14.0.3, Android 12.

**Comment by agnostic-apollo** [comment]
Install [v0.119.0-beta.1](https://github.com/termux/termux-app/releases/tag/v0.119.0-beta.1), it won't be backported.

**Comment by RpxdYTX** [comment]
I'm on v0.119.0-beta.3 and the options don't work, beta.1 crashes on boot
