### ISSUE TITLE
Cannot Upgrade command-not-found

### ISSUE THREAD

**Issue by lynnellemmanuel** [termux/termux-app#255]
It's my first time to use this so I did `apt update` then do `apt install` to each packages list. However, when it comes to command-not-found, an error occurred:

Err:1 http://termux.net stable/main i686 command-not-found i686 1.17
  404  Not Found [IP: 104.18.36.234 80]
E: Failed to fetch http://termux.net/dists/stable/main/binary-i686/command-not-found_1.17_i686.deb  404  Not Found [IP: 104.18.36.234 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by fornwall** [comment]
Run `apt update && apt upgrade` to install the latest version of all installed packages!

**Comment by lynnellemmanuel** [comment]
I just did and still points that there is one package in the list.

LYNNELL EMMANUEL NERI
Back-End Web Developer
lynnellemmanuel@gmail.com

**Comment by lynnellemmanuel** [comment]
Err:1 http://termux.net stable/main i686 command-not-found i686 1.17
  404  Not Found [IP: 104.18.37.234 80]
E: Failed to fetch http://termux.net/dists/stable/main/binary-i686/command-not-found_1.17_i686.deb  404  Not Found [IP: 104.18.37.234 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by fornwall** [comment]
Hm, it shouldn't try to fetch version 1.17 of command-not-found, the current version it 1.19.

But it seems that `apt update` hits a cached version. Could you try an:

    apt update && apt upgrade

again, possibly on another network (perhaps switching from wifi to cellular or vice versa)? If that does not fix it, does

    apt update --fix-missing  && apt upgrade --fix-missing

work?

**Comment by lynnellemmanuel** [comment]
Just tried but still an error.

apt update --fix-missing  && apt upgrade --fix-missing
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  command-not-found
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 12.2 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://termux.net stable/main i686 command-not-found i686 1.17
  404  Not Found [IP: 104.18.36.234 80]
E: Failed to fetch
http://termux.net/dists/stable/main/binary-i686/command-not-found_1.17_i686.deb
 404  Not Found [IP: 104.18.36.234 80]

**Comment by fornwall** [comment]
@lynnellemmanuel Are you still having this (or similar problems), or did it start to work?

If the problem persists, it seems to be due to you not receiving an updated Package list. Could you run `wget http://termux.net/dists/stable/main/binary-i686/Packages && grep command-not-found_ Packages` and paste the output?

**Comment by lynnellemmanuel** [comment]
Hello. I tried to run the command above and it says that Packages file
already exists. So, I ran apt update && apt upgrade and it now starting to
install everything, yahoo! Thank you.

**Comment by fornwall** [comment]
@lynnellemmanuel Great, thanks!

**Comment by lynnellemmanuel** [comment]
You're very much welcome!
