### ISSUE TITLE
[Feature]: Execute script in QR code link

### ISSUE THREAD

**Issue by loynoir** [termux/termux-app#2553]
### Feature description

Give a QR code with url `X`

Button `Execute script in QR code link`

Similar to

```sh
bash -c "$(curl $X)"
```

### Additional information

Or, is it possible to access termux from adb?

**Comment by akw326** [comment]
Y are u asking ?

**Comment by loynoir** [comment]
@akw326 
It's feature request on `Execute script in QR code link` :)
Would be great, if also can be access from adb.

**Comment by akw326** [comment]
I don't know how to send

**Comment by agnostic-apollo** [comment]
Share the url with termux and handle it in `~/bin/termux-url-opener`

https://wiki.termux.com/wiki/Intents_and_Hooks

You can use `run-as` command over adb for github debug builds only, not F-Droid. Search related issues. Or `ssh` over wifi.
