### ISSUE TITLE
[Bug]: no audio

### ISSUE THREAD

**Issue by dontknowhy** [termux/termux-app#2554]
### Problem description

Termux using termux:api to play some media files.
But it can't play audio from pulseaudio:(
Not long after I started PulseAudio, PluseAudio and its sub-processes would be killed for no apparent reason. 
After PulseAudio was killed, I could not transfer the sound of the Linux system inside the root container through PluseAudio. 
I tried simple protocol player but it did not work. Although it will indicate that audio is playing, I can't hear any audio 

### Steps to reproduce the behavior.

pulseaudio --start
./start-debian.sh #from AnLinux
export PULSE_SERVER=127.0.0.1
pulseaudio --start 
vncserver-start #from AnLinux, just about vncserver
cd /sdcard/download
*start to play rickroll*

### What is the expected behavior?

Never gonna…

### System information

* Termux application version:
latest
* Android OS version:
11
* Device model:
BRT-W09

**Comment by dontknowhy** [comment]
这个issue是由中文翻译而来，可能不准

**Comment by dontknowhy** [comment]
Good  news:
I fix it with :pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 #runing in termux
export PULSE_SERVER=127.0.0.1

**Comment by darnrain** [comment]
This is my fix for pulseaudio in Termux. Put this line in your ~/.bashrc The "p" is what you type in the command prompt to execute this line of code and "pianobar' is the program that you want to run. Just change those two things, then type ". .bashrc" that's it. Enjoy audio in Termux.

alias p='if pgrep pulseaudio; then pkill -9 pulseaudio && pulseaudio -D --disallow-exit --exit-idle-time=-1; else pulseaudio -D --disallow-exit --exit-idle-time=-1; fi; pianobar $1'

**Comment by Houin2** [comment]
Same problem and tried many ways and the sound does not work run mobox darkos Even in the same termux it doesn't give audio at all 
My device is matepad 11 ram 6 sd 865 I tried termux on another phone and if the audio works I don't understand why it doesn't on my tablet

**Comment by psychk09** [comment]
Ahhhh
