### ISSUE TITLE
[Bug]: AM not functioning under proot - android 12

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#2559]
### Problem description

invoking 'am' ends up in error:

/data/data/com.termux/files/usr/bin/am: line 3: /system/bin/app_process: No such file or directory

proot startup command is functional and is as follows:

ˋˋˋ
unset LD_PRELOAD

    # setup 'proot' command arguments

    unset session_command

    session_command+="proot"
    session_command+=" --kill-on-exit"
    session_command+=" --link2symlink"
    session_command+=" --rootfs=${ROOT}"
    session_command+=" --change-id=${USER_ID}:${GROUP_ID}"
    session_command+=" --pwd=${HOME}"
    [ -d "/apex" ]                                && session_command+=" --bind=/apex:/apex"
    [ -d "/data" ]                                && session_command+=" --bind=/data:/data"
    [ -d "/dev" ]                                 && session_command+=" --bind=/dev:/dev"
    [ -e "/dev/urandom" ]                         && session_command+=" --bind=/dev/urandom:/dev/random"
    [ -e "/linkerconfig/ld.config.txt" ]          && session_command+=" --bind=/linkerconfig/ld.config.txt:/linkerconfig/ld.config.txt"
    [ -f "/plat_property_contexts" ]              && session_command+=" --bind=/plat_property_contexts:/plat_property_contexts"
    [ -f "/property_contexts" ]                   && session_command+=" --bind=/property_contexts:/property_contexts"
    [ -d "/proc" ]                                && session_command+=" --bind=/proc:/proc"
    [ -d "/proc/self/fd" ]                        && session_command+=" --bind=/proc/self/fd:/dev/fd"
    [ -e "/proc/self/fd/0" ]                      && session_command+=" --bind=/proc/self/fd/0:/dev/stdin"
    [ -e "/proc/self/fd/1" ]                      && session_command+=" --bind=/proc/self/fd/1:/dev/stdout"
    [ -e "/proc/self/fd/2" ]                      && session_command+=" --bind=/proc/self/fd/2:/dev/stderr"
    [ -d "/storage" ]                             && session_command+=" --bind=/storage:/storage"
    [ -d "/sys" ]                                 && session_command+=" --bind=/sys:/sys"
    [ -d "/system" ]                              && session_command+=" --bind=/system:/system"
    [ -d "/vendor" ]                              && session_command+=" --bind=/vendor:/vendor"
    [ -d "${PREFIX%/*}"/home ]                    && session_command+=" --bind=${PREFIX%/*}/home:/home/${USER}"
    [ -d "${PREFIX}"/storage/external ]           && session_command+=" --bind=${PREFIX}/storage/external:/media/external"
    [ -d "${PREFIX}"/storage/internal ]           && session_command+=" --bind=${PREFIX}/storage/internal:/media/internal"
    [ -d "${PREFIX}"/storage/internal/Documents ] && session_command+=" --bind=${PREFIX}/storage/internal/Documents:/home/${USER}/Documents"
    [ -d "${PREFIX}"/storage/internal/Downloads ] && session_command+=" --bind=${PREFIX}/storage/internal/Downloads:/home/${USER}/Documents"
    [ -d "${PREFIX}"/storage/internal/Music ]     && session_command+=" --bind=${PREFIX}/storage/internal/Music:/home/${USER}/Music"
    [ -d "${PREFIX}"/storage/internal/Pictures ]  && session_command+=" --bind=${PREFIX}/storage/internal/Pictures:/home/${USER}/Pictures"
    [ -d "${PREFIX}"/storage/internal/Public ]    && session_command+=" --bind=${PREFIX}/storage/internal/Public:/home/${USER}/Public"
    [ -d "${PREFIX}"/storage/internal/Templates ] && session_command+=" --bind=${PREFIX}/storage/internal/Templates:/home/${USER}/Templates"
    [ -d "${PREFIX}"/storage/internal/Videos ]    && session_command+=" --bind=${PREFIX}/storage/internal/Videos:/home/${USER}/Videos"
    [ -d "${PREFIX}"/tmp ]                        && session_command+=" --bind=${PREFIX}/tmp:/tmp"
    session_command+=" env -i"
    session_command+=" ANDROID_ART_ROOT=${ANDROID_ART_ROOT}"
    session_command+=" ANDROID_DATA=${ANDROID_DATA}"
    session_command+=" ANDROID_I18N_ROOT=${ANDROID_I18N_ROOT}"
    session_command+=" ANDROID_ROOT=${ANDROID_ROOT}"
    session_command+=" ANDROID_RUNTIME_ROOT=${ANDROID_RUNTIME_ROOT}"
    session_command+=" ANDROID_TZDATA_ROOT=${ANDROID_TZDATA_ROOT}"
    session_command+=" BOOTCLASSPATH=${BOOTCLASSPATH}"
    session_command+=" DEX2OATBOOTCLASSPATH=${DEX2OATBOOTCLASSPATH}"
    session_command+=" PREFIX=${PREFIX}"
    session_command+=" COLORTERM=${COLORTERM}"
    session_command+=" DISPLAY=${DISPLAY}"
    session_command+=" HOME=${HOME}"
    session_command+=" LANG=${LANG}"
    session_command+=" LOCALHOST=${LOCALHOST}"
    session_command+=" PATH=${PATH}"
    session_command+=" SHELL=${SHELL}"
    session_command+=" TERM=${TERM}"
    session_command+=" TMPDIR=${TMPDIR}"
    session_command+=" USER=${USER}"
    session_command+=" XDG_RUNTIME_DIR=/run/user/${USER_ID}"
    session_command+=" XDG_CONFIG_DIRS=/etc/xdg"
    session_command+=" XDG_CACHE_HOME=${HOME}/.cache"
    session_command+=" XDG_CONFIG_HOME=${HOME}/.config"
    session_command+=" XDG_DATA_HOME=${HOME}/.local/share"
    session_command+=" XDG_STATE_HOME=${HOME}/.local/state"
    session_command+=" XDG_DATA_DIRS=/usr/local/share:/usr/share"
    session_command+=" XAUTHORITY=${XDG_RUNTIME_DIR}/Xauthority"
    session_command+=" ${SHELL} --login"

    # execute 'proot'

    ${session_command}ˋ
ˋˋˋ

N.B.: issue would not happen under Android 11 and intents were handled appropriately

### Steps to reproduce the behavior.

example:

am start -d vnc://

### What is the expected behavior?

should open vnc handler capable applciation installed on system

ends up erroring out and no action is taken

### System information

Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# sources.list.d/science.list
deb https://grimler.se/science-packages-24 science stable
# sources.list.d/unstable.list
deb https://grimler.se/unstable-packages unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
Updatable packages:
bash/stable 5.1.16 aarch64 [upgradable from: 5.1.12-2]
harfbuzz/stable 3.3.1 aarch64 [upgradable from: 3.2.0]
libgnutls/stable 3.6.16-2 aarch64 [upgradable from: 3.6.16-1]
termux-tools/stable,stable 0.161 all [upgradable from: 0.160]
Android version:
12
Kernel build information:
Linux localhost 4.19.113-23197409 #1 SMP PREEMPT Tue Dec 21 19:32:04 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N986W

**Comment by Grimler91** [comment]
Is /system binded correctly? 

/system/bin/app_process is probably a symlink, is the folder with the destination binded?

**Comment by nathaneltitane** [comment]
> Is /system binded correctly? 
> 
> /system/bin/app_process is probably a symlink, is the folder with the destination binded?

fixed.

**Comment by Grimler91** [comment]
@nathaneltitane please share the solution so that other people running into the same issue can benefit from this public bug tracker

**Comment by nathaneltitane** [comment]
> @nathaneltitane please share the solution so that other people running into the same issue can benefit from this public bug tracker

was my mistake, was running an experimental logic argument in my script that did not make /system bind as it should have
