### ISSUE TITLE
[Bug]: E: Unable to locate package npm

### ISSUE THREAD

**Issue by shanduy** [termux/termux-app#2560]
### Problem description

Hello termux team.
I got an error installing pkg install npm
And I get this error that is in the capture

![WhatsApp Image 2022-02-02 at 21 07 11](https://user-images.githubusercontent.com/79606488/152269860-84c7563b-595c-4ecb-98c1-2dcc115cc66f.jpeg)

Previously this package if they installed me correctly

If someone could help me I would be grateful

The version of is 0.118

### Steps to reproduce the behavior.

pkg install npm

### What is the expected behavior?

The error that I get is
Unable to locate package npm

### System information

* Termux application version: 0.118 F-Droid
* Android OS version: 10
* Device model: Redmi Note 8

**Comment by agnostic-apollo** [comment]
There is no package `npm` in termux. Install `nodejs` pacakge for `npm`.

**Comment by shanduy** [comment]
then the package
pkg install npm
does not exist??

Why several bots for whatsapp that are installed use the pkg install npm

**Comment by agnostic-apollo** [comment]
`npm` is a binary provided by `nodejs` in both termux and linux distro. Don't know what these bots are doing.

```
$ dpkg -S $PREFIX/bin/npm
nodejs: /data/data/com.termux/files/usr/bin/npm
```
