### ISSUE TITLE
[Bug]: new session opens to many windows

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-app#2566]
### Problem description

When I go to open a new sesion from my launcher it opens the maximum amount with no way to exit other than quitting the app 
I have tried multiple launchers thinking it might be a launcher issue first, it still caused it.
It has been this way since around the end of January,
I'm using github nightly

### Steps to reproduce the behavior.

hold termux in launcher
tap new session

### What is the expected behavior?

opens a new singular session

### System information

* Termux application version:
* Android OS version: 12 , ONE UI 4
* Device model: SM-A426U

**Comment by agnostic-apollo** [comment]
Thanks for the report. Fixed with a56ed57. Can you test the apk from https://github.com/termux/termux-app/actions/runs/1798139516?

**Comment by strikersix23** [comment]
Thank

**Comment by agnostic-apollo** [comment]
Wel
