### ISSUE TITLE
[Feature]: renaming files in the document provider

### ISSUE THREAD

**Issue by beroal** [termux/termux-app#2568]
### Feature description

When I work with the Termux document provider (I'm not sure the name is correct) in the Files application and select a file in it, I don't see the Rename command. Is this a limitation of Termux or Android? It would be nice to have this command.

### Additional information

I see this command when working with the external memory in the Files application.

**Comment by thunder-coding** [comment]
There's already #1944 which seems to fix this. (If I'm not wrong). 

Note: I'm not an Android dev

**Comment by agnostic-apollo** [comment]
> Note: I'm not an Android dev

Requesting my review... who says I am?

**Comment by thunder-coding** [comment]
I'm closing this as a duplicate of #2415
