### ISSUE TITLE
Preserve filename when using termux-storage-getfile

### ISSUE THREAD

**Issue by omilu** [termux/termux-app#257]
The `termux-storage-getfile` mechanism gives no way to preserve the original filename.

Is it possible to implement something to preserve the filename?? 

For example, calling `termux-storage-getfile` without a destination filename, causes the script to create a file with the same name of the file that is selected in the popup and copies into it.

Even better if `termux-storage-getfile` is enhanced so it can select multiple files at once, instead of one at a time.

**Comment by fornwall** [comment]
This issue was moved to termux/termux-api#69
