### ISSUE TITLE
[Feature]: Multiple fonts support

### ISSUE THREAD

**Issue by Iamafnan** [termux/termux-app#2575]
### Feature description

Hey can you add support to load more then one font in termux

### Additional information

Idk what to write here

**Comment by beelzebielsk** [comment]
Hi, can this be reopened? Or can we get an explanation as to why it was closed? Multiple fonts is a useful feature for things like proper italics. Many fonts separate their bold and italic styles into a totally separate font. Kitty is an example of a terminal emulator that supports more than one font at a time.

**Comment by agnostic-apollo** [comment]
The description of this issue wasn't clear about usage. For italic fonts support, there is a pull request open that has not been merged yet. #2829
