### ISSUE TITLE
[Bug]: Sympathetic scrolling in adjacent tmux panes

### ISSUE THREAD

**Issue by ax0** [termux/termux-app#2576]
### Problem description

Scrolling up through a program such as man in tmux leads to sympathetic scrolling in horizontally neighbouring panes. I cannot reproduce the issue over SSH or in terminal emulators running on Xvnc, so I assume the issue lies in Termux's terminal emulator.

### Steps to reproduce the behavior.

Assuming `tmux` and `man` are installed and tmux has its default key bindings:
1. Start `tmux`.
2. Populate the pane with text, e.g. `ls $PREFIX/bin`.
3. Split the screen horizontally, i.e. `CTRL-b %`.
4. Run `man tmux`.
5. Scroll down by pressing `DOWN` a few times.
6. Scroll up by pressing `UP` a few times and observe that both panes scroll up simultaneously.

### What is the expected behavior?

There should be no sympathetic scrolling.

### System information

* Termux application version: 0.118.0
* Android OS version: 10, 11
* Device model: Huawei MatePad 11, Samsung Galaxy Note 3

**Comment by pierreyves-lebrun** [comment]
Was able to replicate this issue on MacOS 12.2

**Comment by MrAdityaAlok** [comment]
According to @pierreyves-lebrun comment, it seems to be an upstream problem. Hence, closing.

**Comment by evg-zhabotinsky** [comment]
The above PR definitely fixes the problem for me, and this is how de-facto standard xterm behaves. (And apparently how VT510 behaved too.)
So, if Mac terminal really doesn't handle it this way, IMO it is broken.
