### ISSUE TITLE
[Feature]: Double-tap open drawer button to switch between two most recent sessions

### ISSUE THREAD

**Issue by Soundtoxin** [termux/termux-app#2583]
### Feature description

I want to be able to tap the button twice quickly to change between the two most recent sessions, like an alt-tab. Something like this currently exists with the app switcher button in Android for switching back and forth between two apps quickly. I think it would be nicer than having to move my finger over to the side to select the session. Especially when I'm usually just using two sessions at a time.

### Additional information

Native Android's app switcher has a similar idea.

**Comment by Soundtoxin** [comment]
> Session shortcuts should suffice for that.
> 
> https://wiki.termux.com/wiki/Terminal_Settings#Handling_terminal_sessions

I didn't know about that, however the examples at least don't do this. I basically want prev/next in one button. Just a quick swap back and forth. At least I assume it's previous in absolute terms (up and down in the list) and not previously used / next used (next used wouldn't make much sense)

**Comment by agnostic-apollo** [comment]
Add both to `termux.properties`. The `next-session` must match the `macro`. Next will just cycle/loop through sessions list indexes (not last used), so will act as swap for 2 sessions. You can also add `previous-session` as `popup`.

https://wiki.termux.com/wiki/Touch_Keyboard#Advanced_extra_keys_configuration

```
# Go one session down with (for example) ctrl + 2
shortcut.next-session = ctrl + 2

extra-keys = [[ {macro: 'CTRL 2', display: 'SWAP'}, ... ]]
```

**Comment by Soundtoxin** [comment]
Is there a way to tie the next session function to a double tap or maybe long press of that drawer button? I really don't like the sound of ctrl-2.

**Comment by agnostic-apollo** [comment]
You can use some other key combos. Add `macro` to `popup` of `DRAWER` key and swipe up on the key if you want one key only. And double tap can't work on extra keys, it will just run the key twice, and long press is reserved for special keys like `CTRL`, etc.

**Comment by Soundtoxin** [comment]
Double tapping the `DRAWER` key like I double tap my app switcher button sounds like it would actually be easier than moving my finger over to the drawer once it slides out. Having to do a key combo sounds slow/tedious enough that it's not really better. I haven't experimented yet because I just don't like what I'm imagining after what you're telling me. I don't want to be a nuisance, so I probably won't reopen the issue, but it definitely doesn't *feel* solved/not-an-issue to me.
It does sound like it would require a lot of work to implement if current key behavior doesn't allow this, but in that case I'd be fine if this stayed open a while with intent to get to it eventually. It bums me out to think that this may never ever be implemented.

**Comment by agnostic-apollo** [comment]
> Double tapping the `DRAWER` key like I double tap my app switcher button sounds like it would actually be easier than moving my finger over to the drawer once it slides out.

Are you saying that swiping up on the `DRAWER` extra key with the finger would be much harder than double tapping on it? The later would require you to put your finger down again for the second tap and will obv be slower. I would advise you to read the docs and actually experiment before complaining slowness/tediousness. And key combos/shortcuts are core part of softwares including terminals, they are supposed to be used.

https://askubuntu.com/a/423532

Support for double tap is not really planned considering that popup/swipe-up already exists for the same thing and works fine. Keyboards keys don't really have double tap support normally anyways and usually long hold/swipe up.

**Comment by Soundtoxin** [comment]
>And key combos/shortcuts are core part of softwares including terminals, they are supposed to be used.

Yes... I fully agree.

I'm not against keyboard combos/shortcuts in general. 99% of my termux usage involves attaching to a remote tmux session, hitting ctrl-b all the time. It's just that in this situation it would feel slow with a software keyboard. It would probably be fine with a hardware keyboard.

>Are you saying that swiping up on the DRAWER extra key with the finger would be much harder than double tapping on it? 

Well, swiping sounds like a potentially unreliable and unnatural gesture I'd have to make, and the whole reason I even have a `DRAWER` button is because the sliding out of the drawer became pretty unreliable itself. In OpenLauncher I can get to my app drawer with a swipe up or a double tap on some empty space and I find myself using the double tap more because it's faster and more reliable than the swipe which often seems to not activate. Gestures seem cool sometimes but they just let me down a lot.

>Keyboards keys don't really have double tap support normally anyways and usually long hold/swipe up.

If you mean software keyboard, I've seen it used on shift to activate caps lock at the least. On hardware keyboards, it's certainly more niche, but it's something that QMK allows. I think it's called "tap dance".

>https://askubuntu.com/a/423532

I'm 100% happy with how tmux handles multiple shells and I hate having tabs in terminal emulators. My use-case here is specifically that I'm ssh'd into two *different* machines, often each with their own tmux session. e.g. my remote server with irc, torrent client, etc. personal machine with my music player, rss feed... Plus if I launch a script from the widget, I always get sent back to my second termux session instead of the one I was last using, which is annoying because I'm often doing some clipboard manipulation with plans to paste into that session I was in ASAP and then I'm thrown into the wrong one.

If I just wanted more shells on the same machine, local or not, I'd use tmux for this.

>I would advise you to read the docs and actually experiment before complaining slowness/tediousness.

Yeah, maybe. I'll do some reading and testing when I have time, but at this point you've kinda convinced me my ideal solution isn't an option, so that's definitely demotivating.

Thank you for your time.
