### ISSUE TITLE
[Feature]: Consider adding symlink to Termux R/W path of internal storage in $HOME/storage

### ISSUE THREAD

**Issue by truboxl** [termux/termux-app#2584]
### Feature description

https://github.com/termux/termux-packages/issues/5486#issuecomment-654895162

I was about to rant why https://github.com/termux/termux-app/pull/753 (android.permission.WRITE_MEDIA_STORAGE) not being added since it is needed allow processes to be inside group `sdcard_rw` for older Android versions, particularly Android 7.

To my surprise, without starting to root, even if the bottom dont work due to their canonical group permission under `sdcard_rw` and not `everybody`:
```
/sdcard
$HOME/storage/*
/storage/emulated/0
```
A direct path to `/storage/emulated/0/Android/data/com.termux` works

It feels like `/storage/emulated/0/Android/data/com.termux` is long, forgetful and heavily underappreciated in a non-root environment. Not many will even think about using that for anything. But it should be shown available or at least mentioned. Otherwise what's the use of granting Storage permission in older Android versions?

Unfortunately I have no idea what's best to call the symlink as.

### Additional information

1. Imagine (or try) using Android 7 device today and don't even think about using root
2. Run `termux-setup-storage`
3. Grant Storage permission
4. Run `ls -l storage/*/` to find all Permission denied
5. Start flooding Github Issues
6. ???
7. You won't even start thinking about the existence of `/storage/emulated/0/Android/data/com.termux`

**Comment by truboxl** [comment]
Ah... This probably will be a duplicate of #2481.
But from my POV is what's the use of Storage permission in Android 7?
While their POV is the confusing naming schemes of symlinks...

**Comment by truboxl** [comment]
Never mind. Closing this issue as this is a duplicate of #2481 and also because the `Storage` permission is working as advertised.

For whatever reason, after running `termux-setup-storage` and granting the `Storage` permission,
it still shows `Permission denied` for `ls storage/*`.
I have to go `Force stop` Termux app, then `ls storage/*` shows all the files.
A simple `exit` command or `EXIT` from notification is not enough. Sometimes rebooting the device may not even fix it.

**Comment by mitnk** [comment]
As wiki page [Termux-setup-storage](https://wiki.termux.com/wiki/Termux-setup-storage) say, you may need to **revoke and grant** "storage permission" to Termux app again in system settings.
