### ISSUE TITLE
[Bug]: ssh-agent stops working when termux is sent to the background

### ISSUE THREAD

**Issue by returntrip** [termux/termux-app#2586]
### Problem description

This was working on Android 11 and I have this issue since I received Android 12 on my Oneplus 9.

When using `ssha` or `source-ssh-agent`, while `termux` is in the foreground, I am able to connect to my `ssh` sessions without being prompted for my passphrases each time I initiate the connection (beside for the first connection).

The moment I send `termux` to the background (i.e.: to launch an ssh session from the widget), the agent stops working and all keys are forgotten.  When I `ssh-add -L`, the following error is shown `Error connecting to agent: Connection refused`

### Steps to reproduce the behavior.

1. Start `termux`
2. Launch an `ssha` session via widget script
3. Pasphrase is asked for each single subsequent session 

### What is the expected behavior?

Passphrases is asked only once

### System information

* Termux application version:  0.118.0                   
* Android OS version: 12
* Device model: Oneplus 9

```
~ $ termux-info                                                   Application version:                                              0.118.0                                                           Packages CPU architecture:                                        aarch64                                                           Subscribed repositories:                                          # sources.list                                                    deb https://packages.termux.org/apt/termux-main/ stable main      Updatable packages:
apt/stable 2.3.15 aarch64 [upgradable from: 2.3.13-3]
bash/stable 5.1.16 aarch64 [upgradable from: 5.1.12-2]
command-not-found/stable 1.73 aarch64 [upgradable from: 1.71]
libexpat/stable 2.4.4 aarch64 [upgradable from: 2.4.2]
libgnutls/stable 3.6.16-2 aarch64 [upgradable from: 3.6.16-1]
libtirpc/stable 1.3.2-1 aarch64 [upgradable from: 1.3.2]
ncurses/stable 6.3 aarch64 [upgradable from: 6.2.20200725-6]
openssl/stable 1.1.1m-1 aarch64 [upgradable from: 1.1.1l]
termux-keyring/stable 3.0 all [upgradable from: 2.4]
termux-tools/stable 0.161 all [upgradable from: 0.155]
Android version:
12
Kernel build information:
Linux localhost 5.4.86-qgki-04206-g55ac8cdda695 #1 SMP PREEMPT Tue Jan 18 20:33:24 CST 2022 aarch64 Android
Device manufacturer:
OnePlus
Device model:
LE2113
```

**Comment by agnostic-apollo** [comment]
You should check android `logcat` or post it to find why it was killed. Also check if its related to #2366, does `bash` shell also exit sometimes?

Long hold terminal -> More -> Report Issue -> Yes to include debug info. It should add recent `logcat` output. If that doesn't show anything, then would require running `adb logcat -d > logcat.txt` to include system logcat output instead of just termux.

**Comment by returntrip** [comment]
Thansk for your reply!

`bash` does not exit unexpectedly in my case.

I am attaching the log cat here 
[termux-report_issue_from_transcript.log](https://github.com/termux/termux-app/files/8083394/termux-report_issue_from_transcript.log)

**Comment by agnostic-apollo** [comment]
Welcome. Nothing there, run it over `adb`.

**Comment by returntrip** [comment]
Apologies for the long delay. Attached is the logcat file. Thanks again for your help!

[logcat.txt](https://github.com/termux/termux-app/files/8147100/logcat.txt)

**Comment by agnostic-apollo** [comment]
```
I Athena  : MemoryGuardAction: check & kill orphan process...
I Athena  : MemoryGuardAction: found orphan process [1][13685][10374]ssh-agent
I Athena  : MemoryGuardAction: kill orphan process [1][13685][10374]ssh-agent(ssh-agent)(50)
I Athena  : OplusClearSystemService : K [13685]ssh-agent/50, reason: 71
W AthenaKillerManagerService: Killing 13685 ssh-agent(0), o-kill(71)
I Process : Sending signal. PID: 13685 SIG: 9
```

You should run `ssh-agent -D` so that agent runs in foreground or disable Athena. Check #2015.

https://manpages.debian.org/unstable/openssh-client/ssh-agent.1.en.html

Or possibly use `tini`.

https://wmcbtech30.vercel.app/posts/android-daemonized-process

Closing since not a termux issue.
