### ISSUE TITLE
Problem with Termux's terminal interface

### ISSUE THREAD

**Issue by GreenJoey** [termux/termux-app#259]
I always get this problem with Termux when I type in long lines in the shell, especially if the device is in landscape mode. I will upload a screenshot

**Comment by GreenJoey** [comment]
![Here is the screenshot](https://cloud.githubusercontent.com/assets/19374280/23178370/289e89d4-f890-11e6-8fc9-f09f06dd16da.png)

**Comment by fornwall** [comment]
Hi! Can you check which shell you are running by running `ps $$`?

Could you specify steps how to reproduce the problem!

**Comment by GreenJoey** [comment]
Shell is bash. You reproduce it putting your device in landscape and plug in a keyboard via USB and something very long like a `git commit -m` message

**Comment by fbartels** [comment]
I see that you have customized your ps1, are you sure that this isn't the source of the broken line breaks?

http://askubuntu.com/questions/251154/long-lines-overlap-in-bash-ps1-customized-prompt

**Comment by fornwall** [comment]
@fbartels Good point!

@GreenJoey Can you check if your problem is fixed if you try a simple prompt, like `export PS1='$ '`?

**Comment by GreenJoey** [comment]
I am closing this Issue as I am using ZSH with Oh-My-Zsh. I don't have any problems now.
