### ISSUE TITLE
Incompability with MI PAD

### ISSUE THREAD

**Issue by stieizc** [termux/termux-app#26]
When I tried to install termux on MI PAD, but sadly Google Play tells me that
```
This item is not compatible with your device
```
As far as I know, MI PAD doesn't have a GPS module, but I don't think that is the cause. How can I look into this issue?

**Comment by fornwall** [comment]
Termux requires Android 5.0 or later versions, and and arm or intel cpu. Does this explain why it's not available (is the device running an earlier Android version)?

**Comment by stieizc** [comment]
MI PAD runs Android 4.4 which I think is the cause. Thank you! I will close this issue.
