### ISSUE TITLE
export libpython2.7.so.1.0 not found!

### ISSUE THREAD

**Issue by termux-linux-0x0** [termux/termux-app#2601]
### Problem description

I have android **termux**. How to export ```libpython2.7.so.1.0``` in **termux**.
Error occurs when I encrypt python2 from ```pyinstaller```. Mean libpython not found.
My main question is that how I can export libpython2.7.so.1.0 in ```termux```.

### Steps to reproduce the behavior.

I have android **termux**. How to export ```libpython2.7.so.1.0``` in **termux**.
Error occurs when I encrypt python2 from ```pyinstaller```. Mean libpython not found.
My main question is that how I can export libpython2.7.so.1.0 in ```termux```.

### System information

* Termux application version: 0.117
* Android OS version: 10
* Device model: techno

**Comment by Grimler91** [comment]
You haven't filled in the bug report template, so I have no idea what you are doing (what does "encrypt python2 from `pyinstaller`" mean?). There's no steps to reproduce, or even a full error message, so closing this
