### ISSUE TITLE
[Bug]: Volume keys don't act as shortcuts

### ISSUE THREAD

**Issue by vlig** [termux/termux-app#2607]
### Problem description

Volume keys control volume, I don't know how to make it act as shortcuts. I have read the wiki, but haven't found way to fix such behaviour.
Accessibility features on my phone are disabled AFAIK (I've just never needed it).

### Steps to reproduce the behavior.

Just try some of the shortcuts with volume keys - it adjusts volume and prints pressed symbol.

### What is the expected behavior?

It's expected that volume keys act like shortcuts instead of volume setting.

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: Xiaomi Redmi Note 9 Pro (MIUI Global 12.5.2)

**Comment by agnostic-apollo** [comment]
You may have defined `volume-keys=volume` in `~/.termux/termux.properties`, although its not enabled by default.

Or #1721 could be an issue, but you say you haven't enabled any services...

**Comment by vlig** [comment]
> You may have defined `volume-keys=volume` in `~/.termux/termux.properties`

No, I haven't. Moreover, I've tried to define `volume-keys=virtual` with no expected result.

> you say you haven't enabled any services

It's true. But there's maybe some tricky option on my phone which isn't visible on the first sight... I guess I should try another device some of these days (I haven't extra device).

**Comment by Victor9578** [comment]
i also have same solution,
Do you solve it?

**Comment by vlig** [comment]
> i also have same solution, Do you solve it?

I haven't used it for a couple of months, but just tried and it works... so, I'm going to close the issue in a while if it keeps all right. Try to upgrade all apps on your phone and do pkg upgrade of course.
