### ISSUE TITLE
Extended keyboard: allow inline input (don't force newline)

### ISSUE THREAD

**Issue by memeplex** [termux/termux-app#261]
Currently the extended keyboard is handy for entering natural language fragments for which suggestions are very helpful. But you're forced to do it line-oriented, why? There are many occasions when one just want to insert some text into an already written line.

**Comment by memeplex** [comment]
What do you think of this solution, which I find both simple and general: if the buffer is empty, send a newline, otherwise send the content of the buffer with the newline stripped. This way <Enter><Enter> means "insert the buffer content and send a newline" (which is the current, forced, behavior), while a single <Enter> means just "insert the buffer content".

I would like to motivate this request with a common use-case: I wrote some text in vim, say a note, and now I would like to replace some words in the middle of that text; since it's natural language the keyboard suggestions would be really useful in order to enter the replacement text.

**Comment by fornwall** [comment]
Interesting idea! Any opinions? @Neo-Oli?

**Comment by Neo-Oli** [comment]
@fornwall I think this is a really good idea and would solve this (and #117) nicely.

**Comment by fornwall** [comment]
This is now available in version 0.47 of the Termux app, which should be available as an update shortly! Thanks @memeplex for the suggestion!

**Comment by memeplex** [comment]
Great, thanks! :)

Just one thing: I notice the auto-capitalization after a period is not activated, it's that on purpose? I don't know a lot about the edition modes android supports but I can say it's not a matter of how my keyboard is configured.

**Comment by memeplex** [comment]
Great, thanks! :)

Just one thing: I notice the auto-capitalization after a period is not
activated, it's that on purpose? I don't know a lot about the edition modes
android support but I can say it's not a matter of how my keyboard is
configured.
