### ISSUE TITLE
[Bug]: I can't install a single package

### ISSUE THREAD

**Issue by Aridlvory** [termux/termux-app#2613]
### Problem description

When I install any packages it dosent download it
I tried installing termux-api and it says
`termux-api has no installation candidate`
Even apt update is not working
I tried uninstalling termux but same problem appears again
Please help me
![Screenshot_20220224-195608_Termux](https://user-images.githubusercontent.com/78092537/155543150-34da5714-6b14-4342-a7ad-76766f5d9634.jpg)

### Steps to reproduce the behavior.

pkg update
Pkg install termux-api
pkg install python3

### What is the expected behavior?

Installs the packages

### System information

Application version: 0.118.0
Packages CPU architecture: aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.127-23190912 #1 SMP PREEMPT Thu Dec 9 08:51:06 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T220

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/9133

**Comment by Aridlvory** [comment]
I tried changing all repository but the result is same

**Comment by Grimler91** [comment]
Screenshot clearly shows that you are subscribed to packages.termux.org, not grimler.se
