### ISSUE TITLE
[Bug]: Keyboard & terminal border not drawn correctly on fullscreen

### ISSUE THREAD

**Issue by shadmansaleh** [termux/termux-app#2614]
### Problem description

When `fullscreen` option is enabled last few rows of termux gets hidden behind keyboard . If extra-rows/termux tool bar is enabled it gets hidden behind keyboard along with small parts pf terminal window . If termux tool bar is disabled several line of terminal window gets hidden behind keyboard . This is problemetic for example when editing with vim/neovim cmddline / message line gets hidden behind keybord making them almost unusable :/

It's easy to show then explain . See the recording

https://user-images.githubusercontent.com/13149513/155547448-b219b3ed-e1dc-4147-974d-24afee4ffa17.mp4

Any idea why this might be happening ?

### Steps to reproduce the behavior.

- have `fullscreen = true` in your ~/.termux/termux.properties
- open termux with soft keybord enabled :D

### What is the expected behavior?

Keyboard shouldn't hide portion of terminal

### System information

* Termux application version: 0.118.0
* Android OS version: 10
* Device model: SM-M205F

**Comment by agnostic-apollo** [comment]
https://wiki.termux.com/wiki/Terminal_Settings#FullScreen_Mode

**Comment by shadmansaleh** [comment]
Thanks . Sorry I missed that.
