### ISSUE TITLE
[Feature]: include meta data about termux in release file

### ISSUE THREAD

**Issue by renhiyama** [termux/termux-app#2620]
### Feature description

It seems that there's no file named `/etc/os-release` in termux.
All of the linux distros have one with them, so having one for termux is no great deal, and it's one step forward for termux to become a better linux emulator. You know, some guys might depend on release file to learn what distro is being currently use, and those alternatives which check which package manager is present, may give a false alert that ubuntu/debian is being used and not termux, since apt-get is found on termux too.

### Additional information

https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by renhiyama** [comment]
This can help termux related packages to even learn what termux version is being currently used, and find easily whether the version is old or not, etc.

**Comment by renhiyama** [comment]
It would be better to have `lsb_release` command for termux too, as that's also used to find out the current "distro" information

**Comment by Grimler91** [comment]
This is a good idea, but I suppose all scripts/programs that parse os-release or lsb-release are hardcoded to look for /etc/{os,lsb}-release, so they won't find termux's file anyways

**Comment by renhiyama** [comment]
That's why I asked to add this feature? Because some scripts just depend on this one thing only most of the times... And if this is added, devs can easily ship codes specially for termux ;)

**Comment by renhiyama** [comment]
Now thinking more about it, yea it doesn't make any sense.

**Comment by jvschiavo** [comment]
> Now thinking more about it, yea it doesn't make any sense.

Why not? Couldn't we at least have a `lsb-release`/`lsb_release` package/command that outputs similar results from other distros?

**Comment by zhangjing-GitHub-Code** [comment]
> > Now thinking more about it, yea it doesn't make any sense.
> 
> Why not? Couldn't we at least have a `lsb-release`/`lsb_release` package/command that outputs similar results from other distros?

Yeah, I think that's good.
SO WHY NOT??
@termux
@renhiyama 
@Grimler91
