### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "ssh": library "libcrypto.so.1.1" not found: needed by main executable

### ISSUE THREAD

**Issue by LinuxOpa** [termux/termux-app#2621]
### Problem description

after today's update: 
execute ssh:
CANNOT LINK EXECUTABLE "ssh": library "libcrypto.so.1.1" not found: needed by main executable

### Steps to reproduce the behavior.

execute ssh

### What is the expected behavior?

ssh

### System information

* Termux application version: 0.118.0 from F-Droid
* Android OS version: 11
* Device model: Realme 6

**Comment by wmcbtech30** [comment]
Might be related to #9050 maybe it's best to wait all packages to be fixed and run `pkg update` periodically

**Comment by thunder-coding** [comment]
Yeah it's due to #9050, openssh 8.8p1-2 should work, `pkg update` to update to newer version

**Comment by stl3** [comment]
PS - if you don't see any updates yet, change repo's and check using `termux-change-repo`

**Comment by LinuxOpa** [comment]
bug fixed, switched between repo 1,3,2, in each repo
 apt update
 apt full-upgrade
 apt autoremove
 apt autoclean
in repo 2
![2](https://user-images.githubusercontent.com/41851582/155840038-bdee433c-0f68-4542-a7b0-a37906472b33.jpg)
 the repair was done
case can be closed
THANK YOU!

**Comment by thunder-coding** [comment]
> bug fixed, switched between repo 1,3,2, in each repo

That's because OpenSSL 3 rebuilds are almost done. Or else you would have to follow #9050 (recovering from broken environment)

**Comment by LinuxOpa** [comment]
all fine now
THANK YOU!

**Comment by LandisTwo** [comment]
same issue 2022-10-31
pkg update fixed all package issues.
Thanks.
