### ISSUE TITLE
[Feature]: Add the android.permission.MANAGE_EXTERNAL_STORAGE permission to enable termux to access the Android/data directory

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-app#2622]
### Feature description

Add the android.permission.MANAGE_EXTERNAL_STORAGE permission to enable termux to access the Android/data directory.

### Additional information

https://developer.android.com/training/data-storage/manage-all-files

**Comment by agnostic-apollo** [comment]
Termux is currently running in legacy storage mode and `MANAGE_EXTERNAL_STORAGE` is to be used when `targetSdkVersion` is `30+`, current is `28`.

However, support was already added in 9eeb2bab.
