### ISSUE TITLE
(Bug):I think is android version 12 caused the problem,i met a problem:(process completed signal 9 press enter)when i was running my kali nethunter on termux.

### ISSUE THREAD

**Issue by Kekw02** [termux/termux-app#2625]
### Problem description

When running kali nethunter for almost 5mins,my kex will showing connection failed,connection reset.When i go back to termux app,it shows( process completed signal 9 press enter),so how to do with it?

### Steps to reproduce the behavior.

![Uploading Screenshot_20220227-222614_Termux.jpg…]()

### System information

* Termux application version: 0.118.0
* Android OS version:12
* Device model:Samsung a52

**Comment by agnostic-apollo** [comment]
Could have checked pinned issue #2366

**Comment by Arcsincode** [comment]
it is all about Android 12

**Comment by 2096779623** [comment]
> it is all about Android 12

May be battery optimization.

**Comment by Jaldn** [comment]
...may take the risk that I believe wrongly or rightly, of first uninstalling apps, trying the lightest version of termux & Linux (lighter packages)...if it doesn't go well...what to do...please advise.  Should I try looking into virtual machines?
