### ISSUE TITLE
Files copied or written from Termux under /storage/shared/ cannot be found from the Android File app. [Bug]: 

### ISSUE THREAD

**Issue by GachiLogTokyo** [termux/termux-app#2630]
### Problem description

Copy from Termux or
Written files are no longer visible from the Android side.
It seems that previously written files are not the problem, only newly copied files.

### Steps to reproduce the behavior.

touch /storage/shared/asdf.txt
Open shared folder with File App.

### System information

* Termux application version: 0.118.0
* Android OS version: 11(2022.01.22) / FireOS 7.3.2.2 
* Device model: Oppo A73 / FireHD 10(2019)

**Comment by agnostic-apollo** [comment]
> touch /storage/shared/asdf.txt

Correct path is `~/storage/shared`. The `~/` expands to `/data/data/com.termux/files/home`.

Assuming you ran `termux-setup-storage`.

https://wiki.termux.com/wiki/Termux-setup-storage
