### ISSUE TITLE
[Bug]: Download failed I can't download files

### ISSUE THREAD

**Issue by woshigenm** [termux/termux-app#2631]
### Problem description

![Screenshot_20220304_011956](https://user-images.githubusercontent.com/99122353/156617584-7b8a96ce-b475-44e0-8e84-13a1818eaeab.jpg)
![Uploading Screenshot_20220304_012248.jpg…]()

### Steps to reproduce the behavior.

pkg install git

### What is the expected behavior?

failed

### System information

* Termux application version:
* Android OS version:
* Device model:
termux 0.118.0
Android os 11
mobile phone

**Comment by agnostic-apollo** [comment]
Mirror should have been syncing packages with main termux repo. Wait a while and running again should fix the issue or use `termux-change-repo` to switch to a different mirror.

**Comment by tarek-jm** [comment]
![Image](https://github.com/user-attachments/assets/14114256-643a-4249-9af9-5591343a612d)
