### ISSUE TITLE
[Bug]: Cannot be installed

### ISSUE THREAD

**Issue by PatrickStart7** [termux/termux-app#2633]
### Problem description

I can't install termux app from F-Droid

![Screenshot_2022-03-04-21-35-03-12](https://user-images.githubusercontent.com/100847464/156783493-fb2e5327-344d-4f92-8052-f580db8d98af.jpg)
Translation : Error installing termux, Failed to install due to unknown error
Available storage : 4 GB+

### Steps to reproduce the behavior.

1. Download termux from fdroid
2. Install termux
3. Fail

### What is the expected behavior?

1. Download termux from fdroid
2. Install termux
3. Success

### System information

* Termux application version: 0.118.0 (Latest)
* Android OS version: 11
* Device model: Realme C12

**Comment by PatrickStart7** [comment]
uh I reported on the wrong account :v

**Comment by MuhammadRestu999** [comment]
answer [here](https://github.com/termux/termux-app/issues/2634)
