### ISSUE TITLE
[Bug]: Can't install x11-repo's packages

### ISSUE THREAD

**Issue by Gorkido** [termux/termux-app#2636]
### Problem description

Can't install x11-repo packages.

Error's Screen Shot:
![image](https://user-images.githubusercontent.com/81165187/156831619-6391f3b6-48c3-4f8f-b025-882dd83f0260.png)

Also when installing (any)package(s):
![image](https://user-images.githubusercontent.com/81165187/156831891-1e0f8771-f16b-403b-a032-448615667342.png)

### Steps to reproduce the behavior.

- Install Termux-App from Fdroid
- Start the app
- Install x11-repo package
- Try installing x11-repo packages
- Output: Unable to locate package "package"

### What is the expected behavior?

The package must be installed.

### System information

* Termux application version: 0.118.0
* Android OS version: 10
* Device model: Huawei Mate 10 Pro
* Kernel Architecture: aarch64

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-packages/issues/9286
