### ISSUE TITLE
[Feature]: Test mirrors Speed

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-app#2637]
Added.
[9889](https://github.com/termux/termux-packages/pull/9889)

**Comment by Grimler91** [comment]
Using some sort of proper way to determine the closest mirror would be a good improvement. 

One such software is [mirrorbits](https://github.com/etix/mirrorbits), but it needs rsync or ftp access to determine if mirror is up-to-date, and it seems that only a few of the existing mirrors support this. 

Basically, it needs a [file list through rsync](https://github.com/etix/mirrorbits/blob/eeea0e026d0ca99c7009a91a54369f7c29e87049/scan/rsync.go#L61) (or ftp). It seems only the grimler.se mirror and plug-mirror.rcac.purdue.edu mirror support this. 

Some of the mirrors in China do have rsync, but it doesn't seem to be possible to get a file list. Compare the output of

```
# This works and can be used by mirrorbits:
RSYNC_PASSWORD=termuxmirror rsync -r --no-motd rsync://rsync@grimler.se/termux/
```
and
```
# This just returns the main folder content
rsync -r --no-motd rsync://mirrors.tuna.tsinghua.edu.cn/termux/apt/
```

for example.

There are probably other software/ways to implement this type of geo-based mirror selection. 
Fosshost has some sort of [cdn/mirror service](https://fosshost.org/news/fosshost-mirror-service-changes/), maybe that could help us
