### ISSUE TITLE
can't start rails server

### ISSUE THREAD

**Issue by hnmn** [termux/termux-app#264]
When type a 'rails server' it start and show big command list i have install gem  v -2.6.10 and rails v -5.0.2 ,ruby v -2.4.0 also i tried for rails v -5.0.1 and latest v -5.1.0.beta1 but doesn't work here is error:
Welcome to Termux!

Online help:     https://termux.com/help
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   packages search <query>
Install a package: packages install <package>
Upgrade packages:  packages upgrade
Learn more:        packages help
$ cd demo
$ bundle install
Using rake 12.0.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.1
Using minitest 5.10.1
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 2.0.0
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Using byebug 9.0.6
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using method_source 0.8.2
Using thor 0.19.4
Using debug_inspector 0.0.2
Using ffi 1.9.17
Using multi_json 1.12.1
Using rb-fsevent 0.9.8
Using puma 3.7.1
Using bundler 1.14.5
Using sass 3.4.23
Using tilt 2.0.6
Using sqlite3 1.3.13
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using nokogiri 1.7.0.1
Using rack-test 0.6.3
Using sprockets 3.7.1
Using websocket-driver 0.6.5
Using mime-types 3.1
Using coffee-script 2.4.1
Using uglifier 3.1.2
Using rb-inotify 0.9.8
Using turbolinks 5.0.1
Using activesupport 5.0.2
Using loofah 2.0.3
Using mail 2.6.4
Using listen 3.0.8
Using rails-dom-testing 2.0.2
Using globalid 0.3.7
Using activemodel 5.0.2
Using jbuilder 2.6.3
Using spring 2.0.1
Using rails-html-sanitizer 1.0.3
Using activejob 5.0.2
Using activerecord 5.0.2
Using spring-watcher-listen 2.0.1
Using actionview 5.0.2
Using actionpack 5.0.2
Using actioncable 5.0.2
Using actionmailer 5.0.2
Using railties 5.0.2
Using sprockets-rails 3.2.0
Using coffee-rails 4.2.1
Using jquery-rails 4.2.2
Using web-console 3.4.0
Using rails 5.0.2
Using sass-rails 5.0.6
Bundle complete! 15 Gemfile dependencies, 62 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ ruby bin/rails server
=> Booting Puma
=> Rails 5.0.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:22:in `rescue in block in <class:Railtie>': tzinfo-data is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install (TZInfo::DataSourceNotFound)
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/activesupport-5.0.2/lib/active_support/railtie.rb:19:in `block in <class:Railtie>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
        from /data/data/com.termux/files/home/demo/config/environment.rb:5:in `<top (required)>'
        from /data/data/com.termux/files/home/demo/config.ru:3:in `require_relative'
        from /data/data/com.termux/files/home/demo/config.ru:3:in `block in <main>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
        from /data/data/com.termux/files/home/demo/config.ru:in `new'
        from /data/data/com.termux/files/home/demo/config.ru:in `<main>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/server.rb:59:in `app'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/server.rb:124:in `log_to_stdout'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/server.rb:77:in `start'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:90:in `block in server'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `server'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
$

**Comment by zlfera** [comment]
add tzinfo-data gem

**Comment by fornwall** [comment]
@hnmn Does the above suggestion by @zlfera to add the tzinfo-data gem work?

**Comment by hnmn** [comment]
Finaly it works thanks @zlfera and @fornwall 
First time i add tzinfo-data gem to local gem doesn't work then i add to my gemfile and it work

**Comment by hnmn** [comment]
Sorry for reopen issue .i reopen issue bcoz i can't fount any correct solution that work for me.
Now i can start rails server but i faced new problem . when i run  'rails generate' or 'rails console' just rails commands it shows (errno: ENOENT) message . 
 
Here is error like previous​ one :
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/run.rb:76:in `spawn': No such file or directory - /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/bin/spring (Errno::ENOENT)
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/run.rb:76:in `boot_server'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/run.rb:56:in `cold_run'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/run.rb:33:in `rescue in call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/run.rb:30:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:24:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /data/data/com.termux/files/home/myapp1/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

**Comment by onlurking** [comment]
@hnmn, i've managed to fix this problem running termux-fix-shebang on spring gem
```bash
termux-fix-shebang /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring
```
