### ISSUE TITLE
[Bug]:  Termux public key connection

### ISSUE THREAD

**Issue by ainz29** [termux/termux-app#2641]
### Problem description

I am trying to make a client-server connection, using termux(server) and my pc(host). I initially thought that this error was related to, [(https://github.com/termux/termux-app/issues/775) ]check my permissions and everything is correct.
I handle many ssh keys and to have a control I put a personalized name for example serverhost serverhost.pub by default ssh-keygen generates the path /home/user/.ssh/id_ed25519(or id_rsa) depending on the case.

It happens that termux does not recognize those custom names and does not allow me to connect through a public key.
yes or yes I have to place id_25519.pub (and private too) and after doing that it allows me to connect.

### Steps to reproduce the behavior.

When I have id_25519.pub
03-06 21:12:39.813 18369 18369 I sshd    : Accepted publickey for u0_a2** from 79.142.69.*** port 45844 ssh2: ED25519 SHA256:xwG3G4BmxXaQ+uyfYIYAH0Rp+/0HDsQ***

when I have serverhost.pub

03-06 21:12:23.161 18367 18367 I sshd    : Connection closed by authenticating user u0_a2** 79.142.69.*** port 45842

termux
openssh
sshd
publickey

I'm not an expert and I don't know how to send those detailed logs. I hope these steps can be reproduced

### System information

* Termux application version: fdroid 0.118.0
* Android OS version: 11
* Device model: xiaomi

**Comment by MrAdityaAlok** [comment]
@ainz29  By default, ssh searches for id_dsa and id_rsa files.  For custom name or location of key you need to explicitly reference the key in the ssh command like so:
```
ssh user@server -i /path/to/mykey
```

**Comment by Naim75o** [comment]
🤣
