### ISSUE TITLE
[Bug]: error when run apt update

### ISSUE THREAD

**Issue by ItzMepHazn0010** [termux/termux-app#2642]
### Problem description
when i run update 
an error like this appears
Ign:1 https://packages.termux.org/apt/termux-main stable InRelease
Ign:1 https://packages.termux.org/apt/termux-main stable InRelease
Ign:1 https://packages.termux.org/apt/termux-main stable InRelease
Err:1 https://packages.termux.org/apt/termux-main stable InRelease
  Could not connect to packages.termux.org:443 (216.18.208.174). - connect (111: Connection refused) Could not connect to packages.termux.org:443 (216.18.208.171). - connect (111: Connection refused) Could not connect to packages.termux.org:443 (216.18.208.172). - connect (111: Connection refused) Could not connect to packages.termux.org:443 (216.18.208.173). - connect (111: Connection refused) Could not connect to packages.termux.org:443 (216.18.208.170). - connect (111: Connection refused)
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
W: Failed to fetch https://packages.termux.org/apt/termux-main/dists/stable/InRelease  Could not connect to packages.termux.org:443 (216.18.208.174). - connect (111: Connection refused) Could not connect to packages.termux.org:443 (216.18.208.171). - connect (111: Connection refused) Could not connect to packages.termux.org:443 (216.18.208.172). - connect (111: Connection refused) Could not connect to packages.termux.org:443 (216.18.208.173). - connect (111: Connection refused) Could not connect to packages.termux.org:443 (216.18.208.170). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.

### Steps to reproduce the behavior.

apt update

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: vivo 2007

**Comment by sk0kanik** [comment]
termux/termux-packages#9286

**Comment by ItzMepHazn0010** [comment]
@sk0kanik still bro.

**Comment by Grimler91** [comment]
S
