### ISSUE TITLE
Can't install app. Tried the .118 and .117 version , version from playstore , apk from fdeoid website, app from fdeoid app. Always says unknown error occurred. Help!![Bug]: 

### ISSUE THREAD

**Issue by User5768** [termux/termux-app#2643]
### Problem description

Can't install app. Tried the .118 and .117 version , version from playstore , apk from fdeoid website, app from fdeoid app. Always says unknown error occurred. Help!![Bug]: 

### Steps to reproduce the behavior.

Just try to install the app. Will download but not install!

### What is the expected behavior?

Can't install

### System information

* Termux application version:0.117 and 0.118
* Android OS version: Android 11
* Device model:Lenovo K10 tab

**Comment by User5768** [comment]
New to GitHub so cope with the Syntex errors and writing entire essue in title

**Comment by ChiefMikeK** [comment]
Try
- https://github.com/termux/termux-app/releases
- make sure that no other termux-apps, api widgets  ect.  are installed
