### ISSUE TITLE
[Bug]: https://termux.net/bootstrap connection timed out.

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-app#2644]
### Problem description

![image](https://user-images.githubusercontent.com/57583560/157165616-333b3b26-31a7-4f21-8ab3-016d0641992c.png)

### Steps to reproduce the behavior.

https://termux.net/bootstrap

### System information

* Windows Version:10 2004 Pro
* Chrome Version:80.0.3987.163

**Comment by wmcbtech30** [comment]
@fornwall is currently maintaining the legacy Termux repository which we don't have control over it. but for people who is still reliant older Android 5/6 devices and don't have plans willing to upgrade their OS or their device, they may not install new packages or reinstall Termux installation in the future
***
There will be more issues for people using outdated software such as security issues and app compatibility.

**Comment by agnostic-apollo** [comment]
https://archive.org/details/termux-repositories-legacy

https://github.com/termux/termux-app#installation
