### ISSUE TITLE
[Bug]: keyboard input error

### ISSUE THREAD

**Issue by Ai686Leo** [termux/termux-app#2645]
### Problem description

https://user-images.githubusercontent.com/77483101/157256563-939db59a-cb46-4f04-ae1c-65c421793232.mp4

### Steps to reproduce the behavior.

updated to the latest version

### System information

* Termux application version:0.118.0
* Android OS version:EMUI 10,Android 10
* Device model:Huawei mate 10 pro

**Comment by agnostic-apollo** [comment]
Add `enforce-char-based-input=true` to `~/.termux/termux.properties` and restart termux and check.

https://wiki.termux.com/wiki/Terminal_Settings#Workaround_for_some_keyboards_issues

**Comment by Ai686Leo** [comment]
> Add `enforce-char-based-input=true` to `~/.termux/termux.properties` and restart termux and check.
> 
> https://wiki.termux.com/wiki/Terminal_Settings#Workaround_for_some_keyboards_issues

it's already there![正在上传 t2{beafb39} (612c4467-3741-44e6-a926-3ccfbddb911e id=0x7f0a03ac)…]()

**Comment by agnostic-apollo** [comment]
Then try setting it to `false`. Whatever keyboard you are using is giving you word completion suggestions which is not what any keyboard is supposed to do with the two modes (`InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS` and `InputType.TYPE_NULL`) termux uses based on prop value. If both values don't work, then use different keyboard or file a report to keyboard dev to fix the issue.

https://github.com/termux/termux-app/blob/v0.118.0/terminal-view/src/main/java/com/termux/view/TerminalView.java#L265

**Comment by Ai686Leo** [comment]
> Then try setting it to `false`. Whatever keyboard you are using is giving you word completion suggestions which is not what any keyboard is supposed to do with the two modes (`InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS` and `InputType.TYPE_NULL`) termux uses based on prop value. If both values don't work, then use different keyboard or file a report to keyboard dev to fix the issue.
> 
> https://github.com/termux/termux-app/blob/v0.118.0/terminal-view/src/main/java/com/termux/view/TerminalView.java#L265
Thank you
