### ISSUE TITLE
[Feature]: Add Documents to termux- setup-storage

### ISSUE THREAD

**Issue by ParetoOptimalDev** [termux/termux-app#2648]
### Feature description

[Here](https://github.com/termux/termux-app/blob/85376e2796c7d85a5866914f6b9e19120dfdbd8f/app/src/main/java/com/termux/app/TermuxInstaller.java#L287)  I'd like Documents to be added so I can access my Obsidian notes from termux.

### Additional information

No

**Comment by Dalmater** [comment]
You could try to link it yourself. On Android it's like this `ln -s /storage/emulated/0/Documents/ documents`.
You can see the real path with `ls -lH` in the storage folder/directory.
