### ISSUE TITLE
Option to restore sessions from widget

### ISSUE THREAD

**Issue by kokoko3k** [termux/termux-app#265]
Would it be possible, or maybe it already is, to restore opened sessions when tapping an entry on the widget, instead of launching a new one?

To be clear,
-make an ssh shortcut to a remote server
-start it
-do not close/disconnect from it
-start it again

You ends having 2 connections to the same server, i would like to have a way to choose the running one.

**Comment by fornwall** [comment]
A good idea. I wonder if this could be done always (for every shortcut launch), or if it needs opt in/out to allow multiple sessions for one shortcut? Opinions?

**Comment by fornwall** [comment]
This issue was moved to termux/termux-widget#12
