### ISSUE TITLE
[Bug]: Some IP at packages.termux.org are not working

### ISSUE THREAD

**Issue by Hill-98** [termux/termux-app#2650]
### Problem description

Recently Termux has been failing to connect to packages.termux.org when updating packages, and after some testing I found that some of the IP addresses returned by DNS for packages.termux.org were not working.

I get DNS results, but only `216.18.208.171` works.
```
; <<>> DiG 9.18.0 <<>> packages.termux.org @1.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15682
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;packages.termux.org.           IN      A

;; ANSWER SECTION:
packages.termux.org.    300     IN      CNAME   ogd.proxy.infra.aarch64.com.
ogd.proxy.infra.aarch64.com. 86400 IN   A       216.18.208.171
ogd.proxy.infra.aarch64.com. 86400 IN   A       216.18.208.170
ogd.proxy.infra.aarch64.com. 86400 IN   A       216.18.208.174
ogd.proxy.infra.aarch64.com. 86400 IN   A       216.18.208.173
ogd.proxy.infra.aarch64.com. 86400 IN   A       216.18.208.172

;; Query time: 450 msec
;; SERVER: 1.0.0.1#53(1.0.0.1) (UDP)
;; WHEN: Fri Mar 11 02:04:35 CST 2022
;; MSG SIZE  rcvd: 169
```

```
* Added packages.termux.org:80:216.18.208.174 to DNS cache
* Hostname packages.termux.org was found in DNS cache
*   Trying 216.18.208.174:80...
* Connected to packages.termux.org (216.18.208.174) port 80 (#0)
> GET / HTTP/1.1
> Host: packages.termux.org
> User-Agent: curl/7.82.0
> Accept: */*
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

While ideally the client would try all IP addresses in turn, my private DNS server will only return 1 from it, so there is no extra available for the client.

### Steps to reproduce the behavior.

` curl -v --resolve "packages.termux.org:80:216.18.208.174" http://packages.termux.org/`

### System information

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: OPPO

**Comment by agnostic-apollo** [comment]
Recently, we moved fosshost server to different location. Check https://github.com/termux/termux-packages/issues/9286

I can confirm that only `*.171` ip is working and all others are not. CC @Grimler91

**Comment by Grimler91** [comment]
Can confirm as well. @Hill-98 thanks for debugging this and providing steps to verify the issue!

I have filed an issue at https://support.fossho.st.

**Comment by Hill-98** [comment]
I've changed the mirror using `termux-change-repo` and uninstalled `game-repo science-repo`, thanks for your replies.

**Comment by Grimler91** [comment]
fosshost has fixed the issue, a service for reverse proxying was not start automatically, causing this issue for several servers. 
So, thanks for reporting!
