### ISSUE TITLE
[Bug]: https://termux.net redirects to https://ipinfo.io/census

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-app#2651]
### Problem description

My android 5 (termux.net) redirects to ipinfo.io/census. Can you please change android5 repo

### Steps to reproduce the behavior.

1. Go to termux.net

### System information

* Chrome version: 98.0.4758.101
* Operating system: Android

**Comment by agnostic-apollo** [comment]
Confirmed that http://termux.net/dists/stable/Release is redirecting to https://ipinfo.io/census

Unfortunately, non of the active termux maintainers have access to termux.net to fix/look into the issue. Only @fornwall has access, who is non-responsive.

**Comment by Grimler91** [comment]
Support for android 5 & 6 have been dropped for more than 2 years now in any case

**Comment by Grimler91** [comment]
Repo from archive at https://archive.org/details/termux-repositories-legacy has been uploaded to packages.termux.org, to subscribe to the repo put 

```
deb https://packages.termux.org/termux-main-21 stable main
```

in `$PREFIX/etc/apt/sources.list`.

**Comment by agnostic-apollo** [comment]
Great. But wouldn't the repo be signed with your new key?

Will look into pushing update for old apps.

**Comment by Grimler91** [comment]
Yes, I could update repo urls in apt and *-repo and re-sign the repo with my old, deprecated, key that is [already part of termux-keyring](https://github.com/termux/termux-packages/blob/android-5/packages/termux-keyring/grimler.gpg) on the android-5 branch, but users anyways need to first manually change the repo url to get that update so doesn't really simplify anything for now

**Comment by agnostic-apollo** [comment]
I think best use your new key for repo signing. If app releases are going to be on github, then F-Droid users would still have to reinstall app, which can have new key in bootstrap, basically `master` branch `termux-keyring`. If we are going to put an effort to support legacy, then users should at least put effort to switch source. Asking everyone to change url would be a nightmare too for us like bintray.

**Comment by Grimler91** [comment]
If we create new bootstraps and make a new release of the android-5 app, then sure, switching to new key sounds good, but re-signing the repo now will just create one extra hurdle for users: instead of just changing the repo URL they also have to manually install new termux-keyring package
