### ISSUE TITLE
[Bug]: Termux breaks onscreen buttons when it is root.

### ISSUE THREAD

**Issue by kotenok2000** [termux/termux-app#2657]
### Problem description

Up is replaced with ^[[A
down is replaced with ^[[B
right is replaced with ^[[C
left is replaced with ^[[D
Home is replaced with ^[[H
end is replaced with ^[[F
pageup is replaced with ^[[5~
pagedown is replaced with ^[[6~
esc is replaced with ^[

### Steps to reproduce the behavior.

1. Install memu emulator https://www.memuplay.com/
2. Enable root in settings.
3. Restart emulator
4. install termux from fdroid
5. Check that screen buttons work as intended.
6. Run su command

Buttons now work as stated in problem description

### What is the expected behavior?

buttons work as intended.

### System information

* Termux application version:0.118.0
* Android OS version:7.1 memu 32
* Device model:

**Comment by agnostic-apollo** [comment]
`mksh` shell (`/system/bin/sh`) likely started by `su` is a very limited shell and not featured like `bash` shell used by termux by default. This is not a termux issue.

I suggest you use [`sudo su`](https://github.com/agnostic-apollo/sudo) or optionally `tsu` for running root shells.

**Comment by agnostic-apollo** [comment]
You should only install one of them. Reinstall my `sudo` and post transcript with full output in a markdown code block for `sudo -vv su`

**Comment by kotenok2000** [comment]
I have installed your sudo 
It says

Running sudo

Running sudo_set_su_variables
A su binary found at "/system/xbin/su"
The su binary found does not support '--mount-master' option, continuing search
A su binary found at "/system/bin/su"
The su binary found does not support '--mount-master' option, continuing search
