### ISSUE TITLE
[Bug]: freed address still readable

### ISSUE THREAD

**Issue by oddwatcher** [termux/termux-app#2663]
### Problem description

When i was trying to write a program of quicksort , i wrote a bug which a pointer pointed to an address which is freed but the program went on, it can still read the data in that address with out throw out a segmentation error . At first i missed this problem out but when i tried to compile it on windows using same clang compiler the bug revealed it self. The code is in my repo sort 1.c is the bug but still working one 2.c is fixed one.https://github.com/oddwatcher/sort

delete(r);
L->data = (L->r)->data;
delete(L->r);
output(L);
in 1.c this ,However the piller can be the same with L->r when nothing is added to its left ,so after deleting L the piller is pointing to a freed address, this still working in termux but not any elsewere

### Steps to reproduce the behavior.

create a .c file then type 
#include<stdio.h>
#include<stdlib.h>
typedef struct node
{
    int data;
    struct node *l;
    struct node *r;
} node;
node *newnode(int data, node *l, node *r)
{
    node *new = (node *)malloc(sizeof(node));
    new->data = data;
    new->l = l;
    new->r = r;
    return new;
}
void delete (node *p)
{
    if (p->l != NULL)
    {
        (p->l)->r = p->r;
    }
    if (p->r != NULL)
    {
        (p->r)->l = p->l;
    }
    printf("Deleting:%p:%d\n", p, p->data);
    free(p);
}
int main(){
node *a = newnode(0,NULL,NULL);
a->r = newnode(-1,a,NULL);
a->l = newnode(1,NULL,a);
delete(a);
printf("%d",(a->l)->data);
}

![Screenshot_2022-03-16-14-14-30-950_com termux](https://user-images.githubusercontent.com/55705026/158527979-8466b96d-9abd-4bc9-a329-b4b976d0a35b.jpg)

### What is the expected behavior?

it should throw out segmentation error; but nothing happend

### System information

* Termux application version:0.118.0
* Android OS version:11
* Device model:xiaomi pad pro 5 - snapdragon 870
* Clang vision :clang version 13.0.1
Target: aarch64-unknown-linux-android24

**Comment by agnostic-apollo** [comment]
Accessing freed memory is undefined behaviour and will not necessarily throw a segmentation fault.

https://stackoverflow.com/questions/29999818/accessing-a-freed-pointer-shouldnt-output-be-a-segmentation-fault

**Comment by oddwatcher** [comment]
Thanks
