### ISSUE TITLE
[Bug]: termux older version on GitHub show no apks

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-app#2664]
### Problem description

OLD Termux versions will show no apks.
Please fix it
Only (source zip and tar.gz which contains no apks)

### Steps to reproduce the behavior.

Go to Termux/termux-app
Click on releases

### What is the expected behavior?

Older version show apks

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by agnostic-apollo** [comment]
Automatic APK attachment to github releases with [github workflow](https://github.com/termux/termux-app/blob/master/.github/workflows/attach_debug_apks_to_release.yml) was added in `v0.118.0` and wasn't available before.

Build old releases from source if you want them.
