### ISSUE TITLE
Lint error on build

### ISSUE THREAD

**Issue by lynfield** [termux/termux-app#2669]
### Problem description

Getting lint errors while using gradlew build with tree android 5

### Steps to reproduce the behavior.

 Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

  Errors found:

  C:\Users\Administrator\Desktop\termux-app-android-5\app\src\main\java\com\termux\app\TermuxService.java:109: Error: Tag name should use a unique prefix followed by a colon (found termux). For instance myapp:mywakelocktag. This will help with debugging [InvalidWakeLockTag]
                  mWakeLock = pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, EmulatorDebug.LOG_TAG);
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### What is the expected behavior?

_No response_

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
Android 5 is no longer supported since 2020-01-01. [Skip the lint step](https://stackoverflow.com/questions/21143556/avoid-lint-when-gradle-execute-check) or fix/workaround the issue following the suggestions in the message to build the app for android-5
