### ISSUE TITLE
Fails to start in Android 7.1.1

### ISSUE THREAD

**Issue by toloveru** [termux/termux-app#267]
On Android 7.1.1 (64-bit) I've encountered the following error after attempting to install Termux.
The storage permission has been granted to the app.
On Google I was unable to find any further information about it.

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/sh": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...

[Process completed (signal 6) - press Enter]

**Comment by toloveru** [comment]
Solved by switching to a different ROM.

**Comment by fornwall** [comment]
@toloveru Thanks for the update! Which ROM was it you had problems with?

**Comment by toloveru** [comment]
It was a custom ROM with a lot of other bugs in it which may not necessarily be related to Android 7.1 itself. You can find it [here](http://www.mediafire.com/file/2tc6ss3duibafrw/Nougat_7_for_Doogee_T6_Pro.zip).

**Comment by agiz** [comment]
I have the same problem with MadOS 7.1.1 for vernee apollo lite. Is this termux issue or rom vendor issue?

**Comment by toloveru** [comment]
I found that it happens with all 7.x ROMs for my device, and in both Termux as well as ROM Toolbox Pro's terminal. The terminal from Jack Palevich doesn't have the issue in 7.x though, and all of the aforementioned terminals open correctly in the 6.x releases of Android.
Maybe the sources of Jack's terminal could guide us towards a solution?
https://github.com/jackpal/Android-Terminal-Emulator

**Comment by thurask** [comment]
I can say Termux works on 7.0/Galaxy S8+ (Snapdragon). Maybe it's just Mediatek devices?

**Comment by roccomuso** [comment]
I'm having the same issue on a huawei tablet (`armv71`).
It used to work, but now I'm having this error message:

`[Process completed (signal 11) - press Enter]`

**Comment by Neo-Oli** [comment]
@roccomuso That sounds like a different problem. You probably have an error in your `~/.bash_login` file (or another startup file that you may have tinkered with). Try starting a failsafe session by long pressing the "New Session" Button from the left drawer. From this session you have basic access to termux. Try to identify the problem with your startup. Maybe try deleting your `~/.bash_login` (or other startup files).

**Comment by roccomuso** [comment]
Hm I've not tinkered with startup files at all. I don't even have a `.bash_login` file in my root dir.

**Comment by fornwall** [comment]
@roccomuso If you are sure that you have no custom init files (like `~/.profile` or similar) I think the best thing is to get a clean install - run

    rm -Rf $PREFIX

in a failsafe session (se @Neo-Oli:s reply above), exit all sessions and restart Termux. This causes a clean Termux install while keeping your home folder.

**Comment by roccomuso** [comment]
@fornwall With a clean Termux install using that command it worked again.
