### ISSUE TITLE
[Feature]: pkg autoremove

### ISSUE THREAD

**Issue by mooreye** [termux/termux-app#2670]
### Feature description

**What:** `pkg autoremove` reports unknown command. `apt autoremove` works though. It would be nice if there was an equivalent subcommand for `pkg` to autoremove packages. Also, it would be even better if there was a combined `pkg` command that would be equivalent to `pkg upgrade && apt autoremove` just like `pkg upgrade` already seems to combine `apt update && apt upgrade`.

**Why:** To be able to use only `pkg` command for managing installed packages instead of also `apt`.

### Additional information

Standard `apt` has this.

**Comment by sk0kanik** [comment]
``pkg remove --autoremove`` works btw

**Comment by zairullahdev** [comment]
use apt if your a Linux average

**Comment by mooreye** [comment]
> `pkg remove --autoremove` works btw

Didn't know that, it's good enough for me so closing.
