### ISSUE TITLE
[Bug]: In termux-wiki, tmate get no address 

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-app#2671]
### Problem description

The resolve ssh Bff5fhJquRpO105c3OL62Icfp@fk2.tmate.io have no address associated with hostname

### Steps to reproduce the behavior.

1. Go to Termux-wiki/tmate

### What is the expected behavior?

The fk2.tmate.io contiues

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
That is just an example address, you will need to generate your own token for it to work
