### ISSUE TITLE
[Bug]: In termux-wiki/openfoam, page 404 not found

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-app#2672]
### Problem description

The website https://grimler.se/testing/OpenFOAM is 404 not found, means the web server is down.

### Steps to reproduce the behavior.

Go to Termux-wiki then OpenFOAM

### What is the expected behavior?

No Response

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
Thanks, updated
