### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "php": library "libssl.so.3" not found

### ISSUE THREAD

**Issue by Miraniya** [termux/termux-app#2674]
### Problem description

CANNOT LINK EXECUTABLE "php": library "libssl.so.3" not found

### Steps to reproduce the behavior.

Solve

### What is the expected behavior?

Fix the library "libssl.so.3

### System information

* Termux application version: 
* Android OS version: 
* Device model:

**Comment by DethByte64** [comment]
pkg install openssl

And if that doesn't work,

    export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib/

**Comment by Grimler91** [comment]
Upgrade your packages

**Comment by Miraniya** [comment]
> ### Problem description
> CANNOT LINK EXECUTABLE "php": library "libssl.so.3" not found
> 
> ### Steps to reproduce the behavior.
> Solve
> 
> ### What is the expected behavior?
> Fix the library "libssl.so.3
> 
> ### System information
> * Termux application version:
> * Android OS version:
> * Device model:

**Comment by Miraniya** [comment]
> Upgrade your packages

Always Upgraded

**Comment by Grimler91** [comment]
> > Upgrade your packages
> 
> Always Upgraded

Seems unlikely. Share your output of `termux-info`.

**Comment by Miraniya** [comment]
> > > Upgrade your packages
> > 
> > 
> > Always Upgraded
> 
> Seems unlikely. Share your output of `termux-info`.

![IMG_20220325_094532](https://user-images.githubusercontent.com/94036580/160053176-8e6f12f3-fd9e-4ea9-8f71-1b184ddcbbf0.jpg)

Android OS version: 10
Device model: Redmi 9
-------------------------------------------------------------
My Steps
------------------
Installed Termux
1) termux-change-repo ( Selected  ) 
2) Science repository  science-packages
3) Mirrors by BFSU  Hosted on mirrors.bfs
' then run '
Error  : """
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.                                       N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?)."""
4) pkg install php   
upgraded php
Then
php -S 127.0.0.1:8080 
But 
CANNOT LINK EXECUTABLE "php": library "libssl.so.3" not found 
Problem founded

**Comment by Miraniya** [comment]
> > > Upgrade your packages
> > 
> > 
> > Always Upgraded
> 
> Seems unlikely. Share your output of `termux-info`.

How To Run This PHP
Please tell me steps

**Comment by Miraniya** [comment]
> ```
> pkg install openssl
> ```
> 
> And if that doesn't work,
> 
> ```
> export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib/
> ```

Not working

**Comment by thunder-coding** [comment]
Update your packages using `pkg up`. And if it doesn't help. See termux/termux-packages#9050.

**Comment by charlis** [comment]
I was facing a similar issue while trying to use `pkg up`.

In my case, the executable was expecting to find the library inside 

`/data/data/com.termux/files/usr/lib/`

. but it was installed inside

`/data/data/com.termux/files/usr/lib/openssl-1.1/libssl.so.1.1`

so I created a link for the required libraries (`libssl.so` and `libcrypto.so`) inside the expected directory:

`$ ln -s -T /data/data/com.termux/files/usr/lib/openssl-1.1/libssl.so.1.1 /data/data/com.termux/files/usr/lib/libssl.so.1.1`
`$ ln -s -T /data/data/com.termux/files/usr/lib/openssl-1.1/libcrypto.so.1.1 /data/data/com.termux/files/usr/lib/libcrypto.so.1.1`

and the problem was gone.

**Comment by Appleeyes** [comment]
I'm facing the same issue and tried all options but still not working

**Comment by 2096779623** [comment]
> I'm facing the same issue and tried all options but still not working

`termux-info` plz.

**Comment by Presh-Codes** [comment]
> Upgrade your packages

How

**Comment by MuluhGodson** [comment]
> > Upgrade your packages
> 
> How

`pkg up`

**Comment by dten** [comment]
> > I'm facing the same issue and tried all options but still not working
> 
> `termux-info` plz.

I'm struggling with this also.

Everyone says update but update a doesn't work because. SSL is broken.

`termux-info` just hangs

**Comment by Grimler91** [comment]
> I'm struggling with this also.
> 
> Everyone says update but update a doesn't work because. SSL is broken.

If upgrade doesn't work either then download apt and/or openssl debs "manually" through curl or browser from https://packages.termux.dev/apt/termux-main/pool/main/a/apt/ and https://packages.termux.dev/apt/termux-main/pool/main/o/openssl/, and then install with `dpkg -i /path/to/downloaded/debs`, and then try `pkg upgrade` again

**Comment by dten** [comment]
Thanks that does get it working. I downloaded with browser and accessed them from storage after `termux-setup-storage`

I suspect I could have just done curl and libcurl, but I ended up doing those and apt and it's dependencies which then resulted in an error accessing a function which updating libc++ fixed.
After that apt reported the public key was missing and switching repositories with `termux-change-repo` allowe me to `pkg up` and now things work again thanks

**Comment by mrsauravsahu** [comment]
I was getting this error with any pkg command. I ended up cleaning up the termux environment (as I was just using Ubuntu on my Tab S4) - https://wiki.termux.com/wiki/Recover_a_broken_environment

Check out the last section in the troubleshooting guide - 
I nuked my termux install - `rm -rf /data/data/com.termux/files/usr`

**Comment by wildy283** [comment]
im solving the problem with install upgrade packages and setup termux storage

**Comment by masshuvo** [comment]
The problem solution: 
pkg upgrade -y

**Comment by alprofmahmoud** [comment]
![Screenshot_20230930_121249_Termux](https://github.com/termux/termux-app/assets/35482927/19fa9d5b-cb2d-46c9-9a86-5f757de1b365)
What is the solution to this error?

**Comment by twaik** [comment]
> What is the solution to this error?

`pkg upgrade -y`

**Comment by alprofmahmoud** [comment]
> > What is the solution to this error?
> 
> `pkg upgrade -y`
![Screenshot_20231001_003626_Termux](https://github.com/termux/termux-app/assets/35482927/eef3e03b-08b7-4a3b-b3d5-4c488967e244)

**Comment by TomJo2000** [comment]
If you are on the Playstore version of Termux please uninstall it and reinstall either from F-Droid or the GitHub repo's releases section.

The Playstore version of Termux is deprecated.
