### ISSUE TITLE
Bluetooth Connectivity

### ISSUE THREAD

**Issue by wayofthefuture** [termux/termux-app#268]
Is it possible to connect to a bluetooth device currently connected to the Android device via Termux? Thanks.

**Comment by wayofthefuture** [comment]
I am willing to fund development of this feature if anyone is interested.

**Comment by Grimler91** [comment]
@wayofthefuture Could you elaborate a bit? What would you like to do, connect to a bluetooth device and do serial communication?

**Comment by wayofthefuture** [comment]
Yes that is correct. Utf-8 / ASCII messages coming across the serial port as a stream of data. It would have to be able to enumerate available bluetooth devices paired with the tablet / phone, then connect to a specified device based on some kind of identifier or device name.

The enumeration library is already written, it's called node bluetooth-serial-port. All you would have to do is provide the bluetooth interface via rfcomm or libbluetoothdev, mimicking the standard bluetooth on linux, and it should work I would think. Thanks.

**Comment by Grimler91** [comment]
Closing this in favour of https://github.com/termux/termux-app/issues/235.
