### ISSUE TITLE
> > ```

### ISSUE THREAD

**Issue by Saeedalbaji** [termux/termux-app#2684]
> > ```
> > E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
> > ```
> 
> > N: Metadata integrity can't be verified, repository is disabled now.
> 
> > N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
> 
> Yes, I've checked that repository. It is missing a **Release** file but the **Release.gpg** file is still there.

I have reinstalled the Termux app but the logs are still there and I can't do the 'update and upgrade'.

_Originally posted by @potatonc in https://github.com/termux/termux-packages/issues/5653#issuecomment-669696833_

**Comment by Grimler91** [comment]
Install from fdroid instead of google play. See https://github.com/termux/termux-packages/issues/6726
