### ISSUE TITLE
[Feature]: publish Arch Specific APKs on F-Droid

### ISSUE THREAD

**Issue by AlbertEienstein** [termux/termux-app#2686]
### Feature description

Can you please Publish Termux's Arch-specific APKs on F-droid too?

### Additional information

In Fact, F-droid provides Option to deliver Arch-Specific APKs a Browser App called [Bromite](https://bromite.org) also does that.

**Comment by agnostic-apollo** [comment]
Not supported by F-Droid.

It requires separate version codes for each arch. Use github builds.

https://github.com/termux/termux-app/pull/1904

https://gitlab.com/indicproject/indic-keyboard/-/issues/123

https://forum.f-droid.org/t/does-f-droid-allow-building-architecture-specific-apks/16734/8

https://github.com/termux/termux-app#github
