### ISSUE TITLE
[Bug]: aarch64 sed aarch64 4.7-2

### ISSUE THREAD

**Issue by ajunkdha** [termux/termux-app#2687]
### Problem description

Really good all termux error

### Steps to reproduce the behavior.

Apr update and error' aarch64

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by thunder-coding** [comment]
Seems like you are using outdated mirrors.

`termux-change-repo` and select Cloudflare proxy. Then `pkg up`

**Comment by ajunkdha** [comment]
> Seems like you are using outdated mirrors.
> 
> `termux-change-repo` and select Cloudflare proxy. Then `pkg up`

yes but for android 5 and 6 how to use change repo??

**Comment by agnostic-apollo** [comment]
Duplicate of #2651

**Comment by ajunkdha** [comment]
Why you closed this issue.? Are you dev ??  risk program?
