### ISSUE TITLE
[Bug]: pkg does not work when logged in as root via ssh

### ISSUE THREAD

**Issue by GOD-pro** [termux/termux-app#2689]
### Problem description

```
~ # pkg clean
Ability to run this command as root has been disabled permanently for safety purposes.

~ # su u0_a123 -l -c /data/data/com.termux/files/usr/bin/pkg clean
/data/data/com.termux/files/usr/bin/pkg: line 201: apt: command not found
                  
~ # su u0_a123 -l -c /data/data/com.termux/files/usr/bin/pkg install root-repo
grep: grep: Unknown option 'P'Unknown option 'P' (see "grep --help") (see "grep --help")

~ # su u0_a123 -c "$PREFIX/bin/pkg upgrade"
grep: Unknown option 'P' (see "grep --help")
grep: Unknown option 'P' (see "grep --help"

```
can't install pkg packages without using the termux's terminal running in the phone .

### Steps to reproduce the behavior.

$ ssh device-ip
(I set the shh port to 22)
I could not login (wrong password) 
It worked after adding "PermitRootLogin True" to sshd_config
but it would not get it login as a normal user anymore 

### What is the expected behavior?

Same output when running as a non-root user.

### System information

* Termux application version: f-droid Version 0.118.0
* Android OS version: 12
* Device model:  xiaomi-mido

**Comment by Grimler91** [comment]
> ```
> ~ # su u0_a123 -l -c /data/data/com.termux/files/usr/bin/pkg clean
> /data/data/com.termux/files/usr/bin/pkg: line 201: apt: command not found
> ```

Clearly $PREFIX/bin isn't included in $PATH in your shell, set PATH and potentially some other environmental variables and it should work, though some su binaries/some root methods are known to be buggy.

Running sshd as root on port 22 and allowing root login is not really something we recommend, better stick to logging in as normal user and switching to root from the shell if required

**Comment by agnostic-apollo** [comment]
> Running sshd as root on port 22 and allowing root login is not really something we recommend, better stick to logging in as normal user and switching to root from the shell if required

For linux distros that would make sense but in android/termux there is no root user authentication even if you login as termux user if magisk/supersu has granted permission to termux app. What benefit do you see?

**Comment by Grimler91** [comment]
> What benefit do you see?

In this case it sounds like OP is using termux's sshd but as root and on port 22, and logging in as root clearly hasn't given a "termux shell" (or maybe OP uses some magisk module or similar).
Even if logging in as root works fine I'm also afraid of selinux context issues (at least with some su binaries), but maybe those concerns are unwarranted. 

Best way to get to a termux shell or run something as the termux user after logging in as root is probably your [tudo script](https://github.com/agnostic-apollo/tudo), should probably add it to the repo.. :)

**Comment by agnostic-apollo** [comment]
I was commenting on the "allowing root login" part itself. For OP's case, you are right, he definitely should not be login in as root since `apt` commands would not work and selinux content would be an issue too even if correctly sets up the environment. Easier to go to root context from termux context instead of the other way around.

> Best way to get to a termux shell or run something as the termux user after logging in as root is probably your [tudo script](https://github.com/agnostic-apollo/tudo), should probably add it to the repo.. :)

Yeah, that could be done. xeffyr also removed the req [for no single file scripts](https://github.com/termux/termux-packages/commit/1a6093548033b975e1dca49c0f234c1f30c4946c#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L55) from packaging policy. I will look into adding `tudo` and `sudo` after making some changes after the `am` stuff is handled, @tareksander would probably kill me if I start doing something else currently. ;)
