### ISSUE TITLE
Respect feedback behaviour on extra keys view

### ISSUE THREAD

**Issue by vaites** [termux/termux-app#269]
Extra keys view doesn't respect user defined feedback for keyboard, I mean, doesn't vibrate if is defined in preferences. I know there are many keyboards on the market but Android has a generic setting for this.

**Comment by fornwall** [comment]
Thanks! This will be enabled in the next update (v0.49) which will be pushed as an update shortly.

**Comment by vaites** [comment]
Thanks!
