### ISSUE TITLE
CANT INSTALL GCC COMPILE AND SETUP CLANG [Bug]: 

### ISSUE THREAD

**Issue by ajunkdha** [termux/termux-app#2692]
### Problem description

I don't understand, just this week my termux has a problem with the pack 

### Steps to reproduce the behavior.

Apt update && apt upgrade 

Apt install git 
Apt install gcc 

And troble

### What is the expected behavior?

Whats is this projeck close??

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by MrAdityaAlok** [comment]
@ajunkdha  We do not have gcc. We use clang. Install it using `pkg install clang`.

> Whats is this projeck close??

What do you mean by it?

**Comment by ajunkdha** [comment]
> @ajunkdha We do not have gcc. We use clang. Install it using `pkg install clang`.
> 
> > Whats is this projeck close??
> 
> What do you mean by it?

Ya pkg install gcc-10 android 10 ..not istall what do you mean?

**Comment by ajunkdha** [comment]
before i can use..is there any result in this project?

**Comment by ajunkdha** [comment]
Hahaha you dont have solution? What you mean im using ubuntu??? Yah this my solution .. and termux go on with risk ?? Im install ubuntu and every my risk on my termux hash clear.

**Comment by MrAdityaAlok** [comment]
First of all write in your native language and use Google translate on it, then paste that here. (It knowns better english than you)

> > @ajunkdha We do not have gcc. We use clang. Install it using `pkg install clang`.
> > > Whats is this projeck close??
> > 
> > 
> > What do you mean by it?
> 
> Ya pkg install gcc-10 android 10 ..not istall what do you mean?

We use clang as our c/c++ compiler which is also used by Google for Android. Why do you want gcc. What can it do that clang cannot.

**Comment by MrAdityaAlok** [comment]
> before i can use..is there any result in this project?

No meaning I can infer.
