### ISSUE TITLE
[Bug]: DU command as script - "inaccessible or not found" or "no closing quotes"

### ISSUE THREAD

**Issue by MisiekDP** [termux/termux-app#2697]
### Problem description

Hey,
I have some problems with sh scripts on Termux on Android.

My script code:
`#!/bin/bash

mainLocation="/data/media/0/!Temp/!Test"

echo "Rozmiary katalogow:"
du -hd 1 /data/media/0/!Temp/!Test`

And I get an errors: from executing in Termux:
`1|:/sdcard/!Temp # sh script2.sh
: inaccessible or not found
: inaccessible or not found
Rozmiary katalogow:
: No such file or directoryst
script2.sh[14]: no closing quote`

But when I execute only the command `du -hd 1 /data/media/0/!Temp/!Test` I get correct values:
`1|:/sdcard/!Temp #
u -hd 1 /data/media/0/!Temp/!Test             <
6.6M    /data/media/0/!Temp/!Test/Locus
1.9G    /data/media/0/!Temp/!Test/xd
1.9G    /data/media/0/!Temp/!Test/Telegram
85M     /data/media/0/!Temp/!Test/zedge
3.9G    /data/media/0/!Temp/!Test
:/sdcard/!Temp #`

### Steps to reproduce the behavior.

Do a sh script with content:

`#!/bin/bash

mainLocation="/data/media/0/!Temp/!Test"

echo "Rozmiary katalogow:"
du -hd 1 /data/media/0/!Temp/!Test`

### What is the expected behavior?

The correct values like:

`1|:/sdcard/!Temp #
u -hd 1 /data/media/0/!Temp/!Test             <
6.6M    /data/media/0/!Temp/!Test/Locus
1.9G    /data/media/0/!Temp/!Test/xd
1.9G    /data/media/0/!Temp/!Test/Telegram
85M     /data/media/0/!Temp/!Test/zedge
3.9G    /data/media/0/!Temp/!Test
:/sdcard/!Temp #`

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: OnePlus 7 Pro

**Comment by agnostic-apollo** [comment]
> script2.sh[14]: no closing quote

You have unmatched quoting issue in your script. And you haven't posted full script either, only `6` lines. And this isn't a termux issue.

**Comment by MisiekDP** [comment]
I have only these lines of code, no more. This is the reason that I write here.
And where issue could be? I have installed BusyBox 1.34.1 by osm0sis in Magisk, do you recommend better way to get linux commands?

![Screenshot_20220408-123358](https://user-images.githubusercontent.com/22171619/162419033-1c161579-3db9-48e1-ae94-b149ae31b8fb.jpg)

**Comment by agnostic-apollo** [comment]
Remove line `7`, don't know why it exists.

Command substitution should ideally have quotes around `$()` as well like: `roz="$(du -hs "/path")"`

Line `10` and `13` have double quotes escaping issues. Inside double quotes exists inside double quotes, they need to be escaped with backslash `\`, like `echo "something \"with quotes\" it it"`

I suggest you read on shell script quoting. Ask such questions is shell related forums, not termux repos.

https://www.gnu.org/software/bash/manual/html_node/Quoting.html

https://bash.cyberciti.biz/guide/Quoting

https://www.linuxjournal.com/content/bash-quoting

https://stackoverflow.com/questions/25941394/how-does-bash-deal-with-nested-quotes

**Comment by MisiekDP** [comment]
Yes, thank for the quotes, I will read it.

Now I cleaned some code and it looks like a problem with variable which contains a path. The static path in the du command is not a problem :/

**Comment by MisiekDP** [comment]
![Screenshot_20220408-131511~01](https://user-images.githubusercontent.com/22171619/162426021-fc6162b5-9c04-43a4-b76d-84df1634539e.jpg)
![Screenshot_20220408-131704~01](https://user-images.githubusercontent.com/22171619/162426033-c565f080-02f9-412c-92a2-83bd2e377b35.jpg)
