### ISSUE TITLE
Google Pixel C Keyboard Escape key handling

### ISSUE THREAD

**Issue by gscholt** [termux/termux-app#27]
Hi,

I have recently (naturally) aquired a Pixel C with the Pixel C Keyboard. Almost everything seems to be working, there is just an annoyance preventing me from using termux fully.
Since they Pixel C Keyboard is missing keys, there are build-in [hotkeys](https://support.google.com/pixel/answer/6326992?hl=en) for the missing ones. However:

If I press the ![...](https://lh3.googleusercontent.com/FS30qf3hlMsphqXMswSDwRgvOnHTBOG0Tnip2Gb5hnNOvW6VkKf8u6jL1zJBmMG8vvJi=w18-rwa)+1 key that maps to escape I *also* get the extended-keys soft-keyboard. It makes vi quite frustrating to use :)

I believe this is an issue with termux because:
- other programs I tried to not have this behaviour
- termux does not have this behavour with other keys like [ or ] that are also not present as physical keys.
- escape keys are funny with terminals :)

**Comment by fornwall** [comment]
Nice! Unfortunately the Pixel C is not available here (sweden) yet, so I haven't tried it out!

> If I press the ...+1 key that maps to escape I also get the extended-keys soft-keyboard

With '_get the extended-keys soft-keyboard_', do you mean that the soft keyboard pops up in addition to the escape key being sent?

**Comment by gscholt** [comment]
> With 'get the extended-keys soft-keyboard', do you mean that the soft keyboard pops up in addition to the escape key being sent?

Correct.

There is some coupling between the hardware and the software keyboard. The 'search', 'alt' and '...' key are all used as regular modifier keys, but they also have their own function if not used as a modifier. Similar to how windows treats the 'windows' (aka 'meta'?) key: win+key is an action, but just the win key also pops up the start menu. In the case of the Pixel C Keyboard the ... functions like AltGr does when you have a non-English keyboard layout selected, so perhaps it really just *is* that key (e.g.: if you select Us-International layout, the '...'+5 turns into a €). If you however just press that key, you get the soft-keyboard extended symbols tab. Just like if just press the 'alt' key, you get the soft-keyboard emoji tab.

The escape key seems to be treated differently than other keys in this manner. '...'+o and '...'+p just insert the correct [ and ] key. '...'+1 correctly functions like escape, but also still opens the soft-keyboard as if you did not press the 1 key before releasing the '...' key.

If I were to guess, perhaps only the '1' key is marked as consumed but the '...' modifier key is not? Perhaps the keyboard literally sends AltGr-down, Esc-down, Esc-up, AltGr-up, and termux doesn't eat the modifier key for escape like it does for other keys, so it arrives at the system which only sees the AltGr events and does the soft-keyboard stuff.

**Comment by gscholt** [comment]
Perhaps it has to do with ["replace" key event] support, apparently new in android, see:
https://android.googlesource.com/platform/frameworks/base/+/a43a96b%5E%21/#F0
where they added the mapping for the <AltR>+1 -> ESCAPE to the keyboard driver.

This is really a special beast it seems?

**Comment by fornwall** [comment]
@gscholt Could you use the app https://play.google.com/store/apps/details?id=com.sonelli.keywatcher and press ...+1 (which I understand should result in just the Escape key being executed by Termux, and nothing more, right?) and attach the output here (or mail it to me)?

**Comment by gscholt** [comment]
I did some playing around with the app.
My observations:
* flags, source, keyboard type and device id are constant
* the ...+1 -> esc mapping IS special
* the ...+2 0-> ` mapping is NOT special.
* the 1 key has keycode 8
* the 2 key has keycode 9
* the key with ...+1 has keycode 111 (this is esc?)
* the key with ...+2 still has keycode 9
Logging follows:

### Pressing '...'+'1':
Date: Wed Dec 23 19:21:37 GMT+01:00 2015
Device Manufacturer: google
Device Model: Pixel C
Device Board: dragon
Device Bootloader: Google_Smaug.7132.260.0
Android Version: REL 6.0.1 (sdk:23)

*** Key Event Detected ***
Key Code: 58
Action: 0
Meta State: 34
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

*** Key Event Detected ***
Key Code: 111
Action: 0
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

*** Key Event Detected ***
Key Code: 111
Action: 1
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

*** Key Event Detected ***
Key Code: 58
Action: 1
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

### Pressing just '1'
Date: Wed Dec 23 19:33:30 GMT+01:00 2015
Device Manufacturer: google
Device Model: Pixel C
Device Board: dragon
Device Bootloader: Google_Smaug.7132.260.0
Android Version: REL 6.0.1 (sdk:23)

*** Key Event Detected ***
Key Code: 8
Action: 0
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

*** Key Event Detected ***
Key Code: 8
Action: 1
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

### Pressing '...'+'2'  (resulting in `)
Date: Wed Dec 23 19:34:09 GMT+01:00 2015
Device Manufacturer: google
Device Model: Pixel C
Device Board: dragon
Device Bootloader: Google_Smaug.7132.260.0
Android Version: REL 6.0.1 (sdk:23)

*** Key Event Detected ***
Key Code: 58
Action: 0
Meta State: 34
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

*** Key Event Detected ***
Key Code: 9
Action: 0
Meta State: 34
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

*** Key Event Detected ***
Key Code: 9
Action: 1
Meta State: 34
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

*** Key Event Detected ***
Key Code: 58
Action: 1
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

### Pressing just '2'
Date: Wed Dec 23 19:34:24 GMT+01:00 2015
Device Manufacturer: google
Device Model: Pixel C
Device Board: dragon
Device Bootloader: Google_Smaug.7132.260.0
Android Version: REL 6.0.1 (sdk:23)

*** Key Event Detected ***
Key Code: 9
Action: 0
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

*** Key Event Detected ***
Key Code: 9
Action: 1
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 42

**Comment by fornwall** [comment]
From [KeyEvent.java](https://android.googlesource.com/platform/frameworks/base.git/+/master/core/java/android/view/KeyEvent.java):

    public static final int KEYCODE_ALT_RIGHT       = 58;
    public static final int KEYCODE_ESCAPE          = 111;

    public static final int ACTION_DOWN             = 0;
    public static final int ACTION_UP               = 1;

    public static final int META_ALT_ON = 0x02;
    public static final int META_ALT_RIGHT_ON = 0x20;

So the sequence for ...+1:

    (1) Key Code: 58, Action: 0, Meta State: 34
    (2) Key Code: 111, Action: 0, Meta State: 0
    (3) Key Code: 111, Action: 1, Meta State: 0
    (4) Key Code: 58, Action: 1, Meta State: 0

would mean (since 34=0x02 + 0x20):

    (1) AltRight down, meta=ALT_ON | ALT_RIGHT_ON
    (2) Escape down
    (3) Escape up
    (4) AltRight up

The special thing that Termux in TerminalView.java does is to catch the Escape key in `onKeyPreIme()`, in order to prevent the escape key being treated as back:

    @Override
    public boolean onKeyPreIme(int keyCode, KeyEvent event) {
        if (LOG_KEY_EVENTS) Log.i(EmulatorDebug.LOG_TAG, "onKeyPreIme(keyCode=" + keyCode + ", event=" + event + ")");
        if (keyCode == KeyEvent.KEYCODE_ESCAPE || (keyCode == KeyEvent.KEYCODE_BACK && mOnKeyListener.shouldBackButtonBeMappedToEscape())) {
            // Handle the escape key ourselves to avoid the system from treating it as back key
            // and e.g. close keyboard.
            switch (event.getAction()) {
            case KeyEvent.ACTION_DOWN:
                return onKeyDown(keyCode, event);
            case KeyEvent.ACTION_UP:
                return onKeyUp(keyCode, event);
            }
        }
        return super.onKeyPreIme(keyCode, event);
    }

This would return true since `onKeyDown()` and `onKeyUp()` returns true unless `event.isSystem()`, which is not the case here.

So if the above flow does not miss anything, it would mean that the problem is due to `onKeyPreIme()` returning `true` for the `Escape down/up` events.

**Comment by fornwall** [comment]
> So if the above flow does not miss anything, it would mean that the problem is due to onKeyPreIme() returning true for the Escape down/up events.

Which could perhaps make sense - by eating the key event before the IME sees it, the IME would be left with only seeing the two events:

    (1) AltRight down, meta=ALT_ON | ALT_RIGHT_ON
    (4) AltRight up

which would be the same as just pressing the `...` key. @gscholt: Could you test what pressing and releasing just the `...` key sends?

**Comment by fornwall** [comment]
Intercepting `keyCode == KeyEvent.KEYCODE_ESCAPE` in `onKeyPreIme()` may not be necessary, at least not longer.

It came from Android 4.4 or earlier, where if I recall correctly this was needed to prevent the system from handling Escape as the back key. This intercepting does not seem to be necessary anymore, since at least on Android 5.1 and 6.0 the Escape key is sent to `onKeyDown` as other keys and can be consumed there, without messing with the IME.

**Comment by gscholt** [comment]
As expected, just the ... key is just the AltR:

Date: Fri Dec 25 00:45:40 GMT+01:00 2015
Device Manufacturer: google
Device Model: Pixel C
Device Board: dragon
Device Bootloader: Google_Smaug.7132.260.0
Android Version: REL 6.0.1 (sdk:23)

*** Key Event Detected ***
Key Code: 58
Action: 0
Meta State: 34
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 44

*** Key Event Detected ***
Key Code: 58
Action: 1
Meta State: 0
Flags: 8
Source: 257
Keyboard Type: 2
Device ID: 44


(and after I press the button, the software keyboard pops up)

**Comment by fornwall** [comment]
@gscholt Thanks for all the help! Could you try out the newly released `0.23` version of Termux to see if it fixes the issue :pray: ?

**Comment by gscholt** [comment]
Problem solved.
Awesome, thanks.
