### ISSUE TITLE
Never request permission

### ISSUE THREAD

**Issue by AoEiuV020** [termux/termux-app#270]
I think you can call ensureStoragePermissionGranted() in main activity.onCreate()
sorry for my poor English,

**Comment by fornwall** [comment]
As there are several Termux users not using storage permissions, this is an opt-in through the `termux-setup-storage` command.

**Comment by gerroon** [comment]
termux-setup-storage does not work for me on Nougat, it does not do anything whatsoever when trying to write to external except getting "permission denied"

**Comment by AoEiuV020** [comment]
That's what I want to say.
you must goto
Setting ==> Apps ==> termux ==> permisstions
turn on the "Storage"
It's too much trouble.

**Comment by gerroon** [comment]
@AoEiuV020 

I already did that. External sd acess is read only.
