### ISSUE TITLE
[Bug]: exec("data/data/com.termux/files/usr/bin/login"): No such file or directory

### ISSUE THREAD

**Issue by Mrcubix** [termux/termux-app#2702]
### Problem description

Termux throw this error on start if the entire app (and data) is moved to the sdcard using an app like link2sd.

The path to termux after moving everything is `/data/sdcard2/data/com.termux`.

It seem that a path stored somewhere is hardcoded to `/data/data`.

Modifying the default working directory doesn't seem to affect the error in anyway at all.

If changing path in the packages is also required to fix this issue, then termux should probably make use of an environment variable instead.

Notes: 

- This is done on LineageOS 14.1
- Link2SD require an ext2 partition to move app data to the sdcard.
- Android does not allow me to move apps to the SD card without formatting it (even with the force allow option on).
- Even when done, it doesn't actually move the data to the sdcard, which is why i'm not using it.

### Steps to reproduce the behavior.

1. Move the app to the sdcard using Link2SD or any other app using a similar process.
2. Done.

### What is the expected behavior?

No errors should be thrown and termux should work as intended.

### System information

* Termux application version: 0.118.0
* Android OS version: 7.1.2
* Device model: SM-T560

**Comment by agnostic-apollo** [comment]
Termux uses the hard coded `$PREFIX` `/data/data/com.termux/files` for all its packages at compile time.

Check [here](https://github.com/termux/termux-app/issues/2291#issuecomment-925803066) for why your request for dynamic prefix won't be implemented.

Termux does not support installation on sd card officially. You will have to recompile ALL packages if you want to use `/data/sdcard2/data/com.termux`. For compiling just bootstrap, check https://github.com/termux/termux-packages/wiki/For-maintainers#build-bootstrap-archives, for other packages, check https://github.com/termux/termux-packages/wiki/Building-packages. You won't be able to run any packages installed from termux repos.

Another option that **may** work is to create `ext4` image in sd card and mount it at `/data/data/com.termux/files`. Expect speed degradation depending on sd card r/w speeds.

**Comment by Mrcubix** [comment]
I actually got it to work this time with the following steps:

Starting from an install from scratch :

- Install Termux API,
- Install Termux,
- Symlink /data/data/com.termux to /data/sdcard2/data/com.termux with method of choice (i used Link2SD)
- All packages will now install and work properly

Any packages installed before Symlinking won't work anymore after Symlinking

Should probably put that somewhere.
Thanks anyway.

**Comment by agnostic-apollo** [comment]
Ah, that could be done too. Although, still better to use `ext4` partition.

**Comment by agnostic-apollo** [comment]
Link2SD should have automatically created the symlink if you used `Link2SD` mode instead of native `app2sd`.

http://www.link2sd.info/faq
