### ISSUE TITLE
[Feature]: Verify offical site termux.com to brave browser rewards.

### ISSUE THREAD

**Issue by anshiq** [termux/termux-app#2705]
### Feature description

Hi, Termux maintaners my name is Anshik. I wanna donate some fund to termux. Please verify your official website to brave rewards. I have some BAT coins if I transact through Bitcoin the charges are very high. So please verfy your website so that user can send directly fund to your account thankyou. Loving and very thankful for your work what are you doing.

### Additional information

thanks,

**Comment by twaik** [comment]
https://termux.dev/en/donate.html
