### ISSUE TITLE
[Temporary Correction]: Temporary fix for Termux on Android 12, Works!

### ISSUE THREAD

**Issue by MatheusTGamerPro** [termux/termux-app#2708]
### Feature description

So, I was trying to use VScode by Ubuntu in Termux, however, as we already know Android 12 put a limit of processes to run on Android, better known as "Phantom Process", I've temporarily managed to find a way to fix it, and get you running VSCode and Ubuntu on your Android 12, I'll be putting together an install script to help everyone that contains this version of Android. Basically you will be able to execute several programming languages, being HTML, Python, Java, And several others.. I'll bring you more news soon. Thank you Termux developers for making this possible for us. Waiting for Android 13!

![Screenshot_2022-04-11-17-46-59-083_com realvnc viewer android](https://user-images.githubusercontent.com/89700288/162829284-b8a8e536-e5f0-46da-9d47-7b0e896cf30d.jpg)

**device used**:
    PocoX3Pro
    Architecture: 64-Bit (arm64)
    Android: 12
    Termux: v0.118

### Additional information

This is a temporary fix, until a new Android update.

**Comment by Grimler91** [comment]
Are the instructions on [how to disable the phantom process killing](https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8#how-to-disable-the-phantom-processes-killing) by @agnostic-apollo not working?

**Comment by MatheusTGamerPro** [comment]
> Are you even sure your problem is phantom processes, have you checked `logcat` to confirm, before and after updating `max_phantom_processes` value?
> 
> And on every boot way doesn't work on devices that have gms, you need to disable device config sync.

Yes, I already did the analysis on the problem, I was using the **top** command to view the total open processes, after I start Firefox + VSCode, they together already give more than 15 processes , I notice that it is already running with ~37 processes in total, it takes a few seconds and right after Termux it issues the error "signal 9",

**Comment by MatheusTGamerPro** [comment]
Sorry, I accidentally closed it.

**Comment by agnostic-apollo** [comment]
Confirm with https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8#how-to-detect-phantom-processes-that-were-killed and make sure you are following `Run commands once` section of https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8#disable-phantom-process-killing

**Comment by MatheusTGamerPro** [comment]
> Confirm with https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8#how-to-detect-phantom-processes-that-were-killed and make sure you are following `Run commands once` section of https://gist.github.com/agnostic-apollo/dc7e47991c512755ff26bd2d31e72ca8#disable-phantom-process-killing

Okay, I checked this further.

**Comment by xx1182** [comment]
What's the temporary fix? I also tried the ADB thing but it did not fix the problem. Regards.

**Comment by Nerd00F** [comment]
Did you run a full linux on android??

**Comment by Athayde3586** [comment]
It's asking too verify

**Comment by GameKyuubi** [comment]
I would like to point out that commit 963027690 on 20210814, b737fa84cfa2964811a639e02880c3a2bd69e77a works.  I had it un-updated on my phone and it still works after android 12 update.  New version gets killed.  This commit got removed but likely other commits around that time period will work.  I haven't tried yet tho.

**Comment by freebrowser1** [comment]
Maybe, for me indeed on an Android 12 emulator, but I have no real Android 12 device.

**Comment by nerd00f** [comment]
@agnostic-apollo i think you can close this issue

**Comment by nerd00f** [comment]
and maybe alter the "NOTICE: Termux is broken on Android 12. " on the readme, reffering this solution

**Comment by xx1182** [comment]
> and maybe alter the "NOTICE: Termux is broken on Android 12. " on the readme, reffering this solution

Uhm ! mines has a has and it works but compiler ...

*Do you hairy vag? Know?

**Comment by agnostic-apollo** [comment]
Firstly, OP still hasn't provided debug info for phantom processes showing that provided solution in my gist don't work on their device. Secondly, running code in VSCode is just an alternate way of running code, it won't affect phantom process killing in any way.

>No need for making persistent changes.

GMS updates can happen after hours or days after boot, so your processes will get killed even if you set value in startup scripts, etc if update happens after startup. Persistence mode is necessary on Android 12.
