### ISSUE TITLE
[Bug]: Unable to open left panel menu when using gesture navigation on Android

### ISSUE THREAD

**Issue by keven-mate** [termux/termux-app#2713]
### Problem description

When using Android gesture Navigation I'm unable to open the left panel menu, when I swipe left I Termux closes, this may not be related to termux itself but I think it would be nice if therr was another way to open the panel

### Steps to reproduce the behavior.

Activate Gesture Navigation on your android device

### What is the expected behavior?

When Swiping left I should have the left panel menu open

### System information

* Termux application version:
* 0.118.0

* Android OS version:
* Android 10

* Device model:
* Galaxy S9 (SM-960F)

**Comment by agnostic-apollo** [comment]
`DRAWER` extra key.

https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by leapofazzam123** [comment]
> `DRAWER` extra key.
> 
> https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

Still doesn't resolve the issue. I'm in the latest version and this bug also occurs to me

**Comment by leapofazzam123** [comment]
Can someone reopen this issue?

**Comment by Grimler91** [comment]
> Still doesn't resolve the issue

What do you mean? `DRAWER` extra key doesn't open the left drawer?

Original post sounds like an issue with gesture navigation, please provide a logcat if you think it is a termux issue

**Comment by keven-mate** [comment]
> Can someone reopen this issue?

Are you using gesture navigation?

If yes, you got two options, one is modifying the file at .termux/termux.properties and add the drawer to the extra keys line, or you can long press the left side of the termux screen for a couple of milliseconds and the drawer will open.

If you want to add the extra key, just follow this guide: https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by ChiefMikeK** [comment]
I had simular problem that was caused by the long press delay (Android system settings > Accesibility > `Touch & Hold`) 
- You can try cycling it thru it's long/normal/short time out.
- reboot should not usually be necessary 95% of the time... but?

**Comment by leapofazzam123** [comment]
> Are you using gesture navigation?

Yes, that how I would normally open drawers

**Comment by keven-mate** [comment]
Follow the guide I've posted on my previous comment, any doubt just ask
