### ISSUE TITLE
Text is cut from left side on Android TV

### ISSUE THREAD

**Issue by pranavg189** [termux/termux-app#272]
I installed the Termux app from the Google Play Store on the NVIDIA Shield Android TV running Android 7.0 at 4K 60Hz Resolution. But for some reason, the text on left side is cut a little bit. Though not much of a hindrance as Termux is still pretty usable. Sounds like a DPI problem. You can see the image below:

[https://ibb.co/kN13Jv](https://ibb.co/kN13Jv)

**Comment by fornwall** [comment]
Could you fix this issue by disabling overscan: https://www.howtogeek.com/252193/hdtv-overscan-what-it-is-and-why-you-should-probably-turn-it-off/

Termux currently doesn't use a margin to compensate for overscan, but it could be added.

**Comment by pranavg189** [comment]
@fornwall  yes, I was able to fix it by using the inbuilt overscan app in Shield Android TV.
