### ISSUE TITLE
pip install cmake not working [Bug]: 

### ISSUE THREAD

**Issue by Haiz14** [termux/termux-app#2722]
### Problem description

While doing *pip install cmake* some errors seem to crop up. 

important part of logs: https://pastebin.com/1wzHY5vT

full logs: https://pastebin.com/iWD4mxmm

Same issue: https://github.com/scikit-build/cmake-python-distributions/issues/223

It seemed to work fine BF4: https://www.reddit.com/r/termux/comments/omx8fq/cmake_on_termux/?

### Steps to reproduce the behavior.

#install dependencies
`pkg install ninja cmake`
`pip install ninja`

Finally

`pip install cmake`

### What is the expected behavior?

The pkg should have been installed 

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: RMX2151

**Comment by Grimler91** [comment]
Looks like you need to install a compiler, i.e. `pkg install clang`, or better yet: `pkg install build-essential`
