### ISSUE TITLE
[Bug]: Can't install packages

### ISSUE THREAD

**Issue by kwanele-Cyber** [termux/termux-app#2723]
### Problem description

I am unable to install packages in termux
When ever I try to install a new package in termux I get an error message
I've even tried updating the pkg & apt-get but I still get the same results

### Steps to reproduce the behavior.

pkg install <package>
      Or 
apt-get install <package>

### What is the expected behavior?

OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.bintray.com:443
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#google-play-store-deprecated

https://github.com/termux/termux-app#installation
