### ISSUE TITLE
[Bug]: Garbage File Inside App Data

### ISSUE THREAD

**Issue by giiutfff** [termux/termux-app#2724]
### Problem description

After install Termux, there is a file named `rList` under `/data/data/com.termux/files`.

### Steps to reproduce the behavior.

Install Termux.

### What is the expected behavior?

Only `home` and `usr` folders are under `/data/data/com.termux/files`.

### System information

* Termux application version: 0.118
* Android OS version: 12

**Comment by Grimler91** [comment]
What does the file contain? What is its datestamp/size (`ls -l $PREFIX/../`)? 

I have not seen it on any of the various device where I have termux installed.

**Comment by agnostic-apollo** [comment]
Termux apps do not itself create any such files and its probably a ROM bug or something.

https://forum.xda-developers.com/t/pls-help-rlist-com-files-in-data-data-what-is-this.2978784/

https://stackoverflow.com/questions/28907785/spurious-files-in-my-applications-data-directory

**Comment by giiutfff** [comment]
Yep, just found the same file under other apps too. Definitely it is some kind of OEM "optimisation". What a whole new level of BS, like Android not sucks enough.
