### ISSUE TITLE
[Bug]: Unable to run `/bin/bash` from termux-file-editor

### ISSUE THREAD

**Issue by Estecka** [termux/termux-app#2727]
### Problem description

When running a script through the termux-file-editor, commands such as `/bin/bash` or `/bin/sh` won't run properly. (`No such file or directory`)
Simply calling `bash` or `sh` without the /bin/ still works.

As a result, any shell script that starts with `#!/bin/bash` won't be able to run when executed directly, they can only be run with `bash script.sh`. If those scripts also call other script, the only way to make them run is to refactor them all into using this syntax.

### Steps to reproduce the behavior.

- Create `~/boop.sh` as such :
```shell
#!/bin/bash
echo boop
```
- Create `~/bin/termux-file-editor` as such :
```shell
#!/bin/bash

~/boop.sh             #error: /bin/bash: bad interpreter: No such file or directory
/bin/bash ~/boop.sh   #error: /bin/bash: No such file or directory
bash ~/boop.sh        #ok
```
- Share any file to the Termux app

### What is the expected behavior?

`~/boop.sh` should be executed thrice and run successfully everytime.

### System information

* Termux application version: 0.118.0
* Android OS version: 8.1.0
* Device model: Redmi Note 5

**Comment by Estecka** [comment]
But still, why is this issue specific to termux-file-editor ? I have no issue running `/bin/bash` from a regular terminal, should I not be able to do that ?

**Comment by agnostic-apollo** [comment]
Linux distros != Termux.

All termux binaries exist under `/data/data/com.termux/files/usr/bin` and not `/usr/bin` or `/bin`, those paths point to android os rootfs.

The termux-exec shebang fix for called scripts does not apply for `termux-file-editor`.

`bash` directly works since its under `$PATH`.


https://github.com/termux/termux-tasker#termux-environment

https://wiki.termux.com/wiki/Termux-exec

https://github.com/agnostic-apollo/tudo#path-and-ld_library_path-priorities

**Comment by Estecka** [comment]
Thanks for the doc. So far I got everything to work as expected by prefacing the script with this:
```shell
#!/bin/bash

if [ -z LD_PRELOAD ]
then \
    export LD_PRELOAD=$PREFIX/lib/libtermux-exec.so
    bash $0 $@
    exit
fi

~/boop.sh             #ok
/bin/bash ~/boop.sh   #ok

```
To me, having this kind of singular fix specifically in `termux-file-editor` is much more manageable than changing the shebang in every other scripts.

**Comment by agnostic-apollo** [comment]
`bash $0 $@` should be `bash "$0" "$@"` if it must.

If you run other script with `tudo <script_name>`, then it will work too.
