### ISSUE TITLE
[Bug]: Cant acess sdcard files

### ISSUE THREAD

**Issue by HeroRebor** [termux/termux-app#2728]
### Problem description

**Cant acces sd card files**

_So basically I have a project of github which I want to do in termux. So the file name is Multi-Variant . When I type on termux termux-setup-storage and then type cd /sdcard it open the sdcard then I type ls but it dont show the file which I want to access but same file if i move it to termux storage and then I type ls it show that file_

### Steps to reproduce the behavior.

These are the commands when I type
~ $ cd /sdcard
/sdcard $ ls
 Android
 ApnaNotificationImages
 ApnaTime
 AzRecorderFree
 Call
 DCIM
 DLMImageToPdf
'Document Scanner'
 Documents
 Download
 DroidFish
 Duo
 Fachat
 Fonts
 GROWTH_TEST
 ImageToPdf
 IntroMaker
 KineMaster
 LazyList
 LoanFrom
 MT2
'Magic Neon Art Editor'
 Mobizen
 Movies
 Music
'New F'
'New folder'
 Notifications
 OSSLog
'PDF Converter'
 PDFfiles
 PDFfilter
 PDFmaker
 Pictures
 Podcasts
 RecForge
 Receipts
 Ringtones
/sdcard $

But the same file if I want to acess with termux storage and type
~ $ ls
BotLi         Multi-Variant  iovr      storage
BotLi-Heroku  downloads      personal
~ $ cd Multi-Variant
~/Multi-Variant $

### What is the expected behavior?

I want that the file which I can acces with termux storage same file want to acces with sdcard 
My android have low storage so I cant put that big file in termux storage
Kindly fix it

> ### _**Thank you for reading!**_

### System information

* Termux application version:
* Android OS version:
* Device model: Samsung A10s

**Comment by Grimler91** [comment]
`/sdcard/` and `~/storage/shared` are in the internal storage. 

If you want to keep files on the external sdcard you can put them in `~/storage/external-*/`, which corresponds to the folder `Android/data/com.termux/files/` on the external sdcard (check absolute path with `realpath ~/storage/external-*`)

**Comment by HeroRebor** [comment]
I cant understand how to put files in sdcard?

**Comment by ChiefMikeK** [comment]
@HeroRebor in the future  
Please **search first then ask for help** on the reddit termux forum
- https://www.reddit.com/r/termux/  
- $ `cd ~/storage/external-1` 
- then copy or move your files to this directory
- I also suggest you make a symlink in your home directory
