### ISSUE TITLE
Home key doesn't work in Termux:Float but does in Termux (Hacker's Keyboard)

### ISSUE THREAD

**Issue by like2omg** [termux/termux-app#273]
I hope the title explained it enough...  
I am not using an external, nor physical, keyboard on this device, but I do have root and a few programs that have the potential to automate interaction (not used for those tasks yet, just a manually-made click-through overlay to show my battery status at each current time).

So far, that is the only key that I have tried and had any problems at all with.

The problem has caused some frustration on my end which is quite annoying:

* Going back to the start of a long line in the bash shell takes some time and I must start all over if I switch its command history with the nearby up or down keys.
* node interpreter (package nodejs) becomes a real annoyance because of the history does not save any changes like bash does... even temporairly. (I don't know if standard behavior.)

**Comment by fornwall** [comment]
The Home key in Termux:Float should be fixed by the just made version 0.8 update!

For future information: There is now a dedicated repo for Termux:Float at https://github.com/termux/termux-float!

> node interpreter (package nodejs) becomes a real annoyance because of the history does not save any changes like bash does... even temporairly. (I don't know if standard behavior.)

Hm, this should work? Can you ensure that you have the latest package versions by running `apt update && apt upgrade`?

**Comment by like2omg** [comment]
Okay, I did not recall saying the "Android home button" but I do mean "Home key on Hacker's Keyboard IME"... Also, it is fixed as I check right now. Thank you.
