### ISSUE TITLE
[Bug]: termux was unable to install bootstrap packages

### ISSUE THREAD

**Issue by tuppi-ovh** [termux/termux-app#2733]
### Problem description

I cannot access the shell on my tablet after a fresh install because of this error: 

![Screenshot_20220424-144516](https://user-images.githubusercontent.com/59368736/164977253-ef9c60c5-b541-4738-9820-879921c2f43f.png)

The internet is ok on the tablet. The app is installed on the main storage, not SD card. 

If I access the page http://termux.net/bootstrap from my browser, I get this:
  {"code":"PAGE_NOT_FOUND","message":"Page not found"}

### Steps to reproduce the behavior.

See in the description.

### System information

* Termux application version: 0.83
* Android OS version: 6.0.1
* Device model: Lenovo TB-8703X

**Comment by wmcbtech30** [comment]
#2659

**Comment by wmcbtech30** [comment]
https://github.com/termux/termux-app/issues/2651

**Comment by Grimler91** [comment]
termux-v0.79-offline-bootstraps.apk from https://archive.org/details/termux-repositories-legacy should work
