### ISSUE TITLE
[Bug]: 7z makes Termux crash

### ISSUE THREAD

**Issue by dontknowhy** [termux/termux-app#2745]
### Problem description

Bruh
i have a 11G big .vmdk file from 小白之家 in bilibili
so i had to compress it
but it seems like 7z is TOO FAST
when it comes around 5%
it crashed
i think it's Android's progress management problem

### Steps to reproduce the behavior.

Download a special .XBZJ file from https://fnca1-my.sharepoint.com/:f:/g/personal/kiju03_liuyumei8_com/EjwtJV8aZ3hPu7QOsVbloh4B0Es7kDAJ4aw_niPpE_YmdQ?e=HxcWCT
"not my one drive. Password is XBZJ. you only need to check the file size or compress it with the following instructions "

use nice -n 99 ionice -c 2 -n 7 7z a -mmt16 -mx9 win8102.7z  *filename you downloaded*

wait about 5 minutes 
Termux crash
Without any information

### What is the expected behavior?

compress file as we know

### System information

* Termux application version:
latest
* Android OS version:
Android 11
* Device model:
BRT-W09

**Comment by wmcbtech30** [comment]
What is your device's memory? maximum compression would cause IO/CPU usage to go high especially for big archives with highest compression algorithm

Also you could try adjusting nice values to see the difference

**Comment by dontknowhy** [comment]
> What is your device's memory? maximum compression would cause IO/CPU usage to go high especially for big archives with highest compression algorithm. triggering Android low memory killer
> 
> Also you could try adjusting nice values to see the difference 

8G
And i'm using -mmt8 to compress
it's working
and nice is only for better CPU performance.
you can try to start a program in a high nice level to have a better experience 
it can speed up the 7z

~~i think you can google BRT-W09 or google HONOR ViewPad 7 Pro~~
~~i'm china so you may search ViewPad 7 Pro~~

**Comment by MrAdityaAlok** [comment]
Closing. Doesn't seem to be a problem with Termux, most probably Android is killing process.
