### ISSUE TITLE
[Bug]: Nodejs

### ISSUE THREAD

**Issue by danicaStarR** [termux/termux-app#2746]
### Problem description

Can not install nodejs or nodejs-lts in apt.

### Steps to reproduce the behavior.

apt install nodejs 
node

### System information

* Termux application version: 0.97
* Android OS version: 6.0.1(Can use apt)
* Device model: vivo

**Comment by danicaStarR** [comment]
`$ node
WARNING: linker: node: unused DT entry: type 0x1d arg 0x5c650f
WARNING: linker: /data/data/com.termux/files/usr/lib/libcares.so: unused DT entry: type 0x1d arg 0xab1
CANNOT LINK EXECUTABLE: library "libcrypto.so.1.1" not found
page record for 0xb6f4a02c was not found (block_size=16)
`

**Comment by Grimler91** [comment]
I can't reproduce the issue with up-to-date android-5 packages. Make sure latest package versions are installed, `apt update && apt upgrade`

**Comment by danicaStarR** [comment]
@Grimler91 I was use `...termux.com/apt/termux-main`

**Comment by Grimler91** [comment]
You can't use repositories for android >= 7 on android 5 or 6

**Comment by danicaStarR** [comment]
@Grimler91 Why
![termux](https://user-images.githubusercontent.com/103302052/166234952-13b71d21-0a68-4f97-af47-abe0d0929bcb.png)

**Comment by Grimler91** [comment]
Looks like you haven't followed instructions [in wiki](https://github.com/termux/termux-app/wiki/Termux-on-android-5-or-6) (termux-keyring isn't updated). Maybe you also have a broken environment due to mixing android-5 and >= 7 packages. Hard to tell since you've just posted a screenshot without any information.

**Comment by danicaStarR** [comment]
@Grimler91 
First:
` shell
sed -i'' 's|deb https://termux.net stable main|deb https://packages.termux.org/termux-main-21 stable main|' "$PREFIX/etc/apt/sources.list"
sed -i'' 's|deb https://dl.bintray.com/grimler/game-packages-21 games stable|deb https://termux.org/game-packages-21-bin games stable|' "$PREFIX/etc/apt/sources.list.d/game.list"
sed -i'' 's|deb https://dl.bintray.com/grimler/science-packages-21 science stable|deb https://termux.org/science-packages-21-bin science stable|' "$PREFIX/etc/apt/sources.list.d/science.list"
sed -i'' 's|deb https://dl.bintray.com/grimler/termux-root-packages-21 root stable|deb https://termux.org/termux-root-packages-21-bin root stable|' "$PREFIX/etc/apt/sources.list.d/root.list"
`
then:
` shell
pkg update
`
