### ISSUE TITLE
[Bug]: gcc cctools problem

### ISSUE THREAD

**Issue by HeroRebor** [termux/termux-app#2747]
### Problem description

Hello so I want to compile 1 file with gcc cctools but whenever I type it show error 

### Steps to reproduce the behavior.

`~ $ apt install gcc-cctools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package gcc-cctools`

### What is the expected behavior?

Why this error showing and how to fix it?

### System information

* Termux application version:
* Android OS version:
* Device model: Samsung A10S

**Comment by wmcbtech30** [comment]
We don't have such package. though closet alternative to gcc is clang

You may also look at this but we don't have such support because this was compiled for `armel`? devices
https://github.com/mooring/cctools-gcc-for-terminal-IDE-on-Android

**Comment by RalfWerner** [comment]
Or look at https://github.com/its-pointless/gcc_termux (includes gfortran too)

**Comment by HeroRebor** [comment]
> We don't have such package. though closet alternative to gcc is clang
> 
> You may also look at this but we don't have such support for 3rd party and idk if this is what you wants https://github.com/mooring/cctools-gcc-for-terminal-IDE-on-Android

But I saw many people installing gcc by that command?

**Comment by RalfWerner** [comment]
> But I saw **many people** installing gcc by that command?

`gcc-cctools` is not a termux package! Ask **many people** what environment they use.
