### ISSUE TITLE
[Feature]: Msys2

### ISSUE THREAD

**Issue by HeroRebor** [termux/termux-app#2749]
### Feature description

Plz make msys2 in termux plz

### Additional information

If this already exists on termux then tell how to install in termux

**Comment by wmcbtech30** [comment]
Msys2 is made for Microsoft Windows. we already have existing tools available (maybe you're looking for `build-essential` to compile apps?). please elaborate your issue as we don't know what you're trying to achieve

**Comment by HeroRebor** [comment]
> Msys2 is made for Microsoft Windows. we already have existing several unix tools available. please elaborate your issue as we don't know what you're trying to achieve with it

I want to compile a thing using msys2 
And that can be done by msys2 and gcc  only
But nowadays gcc dont work so msys2 only work
I dont have pc
That's I need msys2 in android 
Plz help termux termux is good and help in many things but this pkg Is important 
Kindly do

**Comment by wmcbtech30** [comment]
We have `clang` and other development tools that you can build programs from source. but not in win32 format, closing since we don't use msys2 packages

**Comment by HeroRebor** [comment]
But in future cant it be done?
