### ISSUE TITLE
New Session in current dir

### ISSUE THREAD

**Issue by vishalbiswas** [termux/termux-app#275]
I would like a feature to toggle Opening new Termux sessions in the current dir of an onscreen session.
Also, an intent to start a shell in specific dir from other apps would be awesome. For example, a share intent from a file manager to start a session in current dir.

**Comment by dredmorbius** [comment]
Is a terminal multiplexer such as screen or tmux a suitable workaround?

**Comment by vishalbiswas** [comment]
my screen is already too small and I use soft keyboard, tmux cannot help there

**Comment by dredmorbius** [comment]
tmux of itself will start a new terminal session, without taking up any screen real estate.  Screen likewise.

Have you at least tried it?

I can see how invoking the command key sequences (C-b and C-a respectively) might not be ideal with a soft keyboard.  I use a Bluetooth keyboard myself, and strongly recommend it.

**Comment by vishalbiswas** [comment]
@dredmorbius learning tmux means learning another batch of shortcut keys ;)
I'll give it a try

**Comment by dredmorbius** [comment]
@vishalbiswas It's highly leveraged knowledge.  My problem is I know all the screen key sequences, which differ slightly from tmux.

Both are exceptionally useful tools though. Highly recommended to learn them.

**Comment by vishalbiswas** [comment]
**New Session** button now opens another shell in current working directory.
