### ISSUE TITLE
[Bug]: unable to find termux-packages in GitHub repo

### ISSUE THREAD

**Issue by coudx** [termux/termux-app#2751]
### Problem description

![Screenshot_2022-04-30-23-12-05-019_com termux](https://user-images.githubusercontent.com/43221225/166134594-16ea7071-1b78-4527-ab30-80c8fcb7062c.jpg)
![Screenshot_2022-04-30-23-15-36-672_com termux](https://user-images.githubusercontent.com/43221225/166134621-dc74c7e0-7461-4c75-8789-cb483e2138b3.jpg)

### Steps to reproduce the behavior.

As I expect GitHub repo for termux should contain above pkg that I'm trying to install

### System information

* Termux application version:0.118.0
* Android OS version:12
* Device model:M2101K9G

**Comment by Grimler91** [comment]
No idea why you expect there to be a package named "termux-packages"
