### ISSUE TITLE
[Bug]: When running "pkg list-all" command

### ISSUE THREAD

**Issue by AdrianM269** [termux/termux-app#2757]
### Problem description

When running the command, it doesn't let you see all the packages listed because you can't scroll up to the top of the list

### Steps to reproduce the behavior.

Run the " pkg list-all " command

### What is the expected behavior?

Can't scroll up to the beginning of the listed packages 

### System information

* Termux application version: 0.118.0 (F-droid)
* Android OS version: Android 12
* Device model: SM-A515F/DSN

**Comment by wmcbtech30** [comment]
try with `pkg list-all | less`

the terminal limits it's scrollback buffer to 2000. with `less` you should be able to scroll up beyond that limit
