### ISSUE TITLE
How can we join 2 binary file in termux

### ISSUE THREAD

**Issue by HeroRebor** [termux/termux-app#2758]
### Feature description

Actually I need compiled to binary file and now I need to join it
Is there any way to join them using termux

### Additional information

I tried to find it in google but didn't got answer 
Plz tell how to join 2binary file in termux
If there no such way can this feature will be bring in future?

**Comment by Grimler91** [comment]
`cat a b > c` will "join 2 binary files", but I don't think that's what you are really asking

**Comment by HeroRebor** [comment]
`~ $ cat a b > c
cat: a: No such file or directory
cat: b: No such file or directory
~ $`

**Comment by HeroRebor** [comment]
I was aking that only but your solution showing that error

**Comment by wmcbtech30** [comment]
You must provide actual split files instead of an example above. use `cat` on those split files and redirect them as shown above but not with the `a`, `b` examples

**Comment by HeroRebor** [comment]
A mean file no 1 and b means file no 2?
Suppose my file name are hero another is reborn
So cat hero reborn> c

**Comment by HeroRebor** [comment]
It worked
