### ISSUE TITLE
[error] No puedo instalar cryptography 

### ISSUE THREAD

**Issue by DrooxingJ** [termux/termux-app#2761]
### Problem description

pip install cryptography --no-binary cryptography                                           Collecting cryptography
  Using cached cryptography-37.0.2.tar.gz (585 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done    Preparing metadata (pyproject.toml) ... done
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp310-cp310-linux_aarch64.whl
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (pyproject.toml) ... error
  error: subprocess-exited-with-error
                                                  × Building wheel for cryptography (pyproject.toml) did not run successfully.                    │ exit code: 1
  ╰─> [232 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-310
      creating build/lib.linux-aarch64-cpython-310/cryptography
      copying src/cryptography/fernet.py -> build/lib.linux-aarch64-cpython-310/cryptography          copying src/cryptography/__about__.py -> build/lib.linux-aarch64-cpython-310/cryptography       copying src/cryptography/exceptions.py -> build/lib.linux-aarch64-cpython-310/cryptography
      copying src/cryptography/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography
      copying src/cryptography/utils.py -> build/lib.linux-aarch64-cpython-310/cryptography
      creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat
      copying src/cryptography/hazmat/_oid.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat                                              copying src/cryptography/hazmat/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat
      creating build/lib.linux-aarch64-cpython-310/cryptography/x509
      copying src/cryptography/x509/base.py -> build/lib.linux-aarch64-cpython-310/cryptography/x509
      copying src/cryptography/x509/oid.py -> build/lib.linux-aarch64-cpython-310/cryptography/x509
      copying src/cryptography/x509/name.py -> build/lib.linux-aarch64-cpython-310/cryptography/x509
      copying src/cryptography/x509/ocsp.py -> build/lib.linux-aarch64-cpython-310/cryptography/x509
      copying src/cryptography/x509/general_name.py -> build/lib.linux-aarch64-cpython-310/cryptography/x509
      copying src/cryptography/x509/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/x509
      copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-aarch64-cpython-310/cryptography/x509
      copying src/cryptography/x509/extensions.py -> build/lib.linux-aarch64-cpython-310/cryptography/x509
      creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives                        copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/_cipheralgorithm.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/_asymmetric.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/_serialization.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives
      creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends
      copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends
      creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings                       copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings                        creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/twofactor           copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/twofactor                                                    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/twofactor                                                copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/twofactor
      creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric                                                    copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric                                               copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric                                                   copying src/cryptography/hazmat/primitives/asymmetric/types.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric                                                 copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric                                                   copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric                                               copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric                                                    copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric                                                  copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/asymmetric                                              creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/serialization       copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/serialization                                            copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/serialization                                        copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/serialization                                             creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/ciphers             copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/ciphers        copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/ciphers       copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/ciphers                                                    copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/ciphers        copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/ciphers
      creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/kdf               copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/kdf                copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/kdf            copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/kdf              copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/primitives/kdf              creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl               copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl              copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl          copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl         copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl            copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl         copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl          copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl              copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl             copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl         copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl        copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl           copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl                                                     copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl            copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl            copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl                                                     copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl           copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl             copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl        copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/backends/openssl
      creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings/openssl               copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings/openssl        copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings/openssl                                                    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings/openssl
      running egg_info                                writing src/cryptography.egg-info/PKG-INFO      writing dependency_links to src/cryptography.egg-info/dependency_links.txt
      writing requirements to src/cryptography.egg-info/requires.txt                                  writing top-level names to src/cryptography.egg-info/top_level.txt
      reading manifest file 'src/cryptography.egg-info/SOURCES.txt'                                   reading manifest template 'MANIFEST.in'         no previously-included directories found matching 'docs/_build'                                 warning: no previously-included files found matching 'vectors'                                  warning: no previously-included files matching '*' found under directory 'vectors'              warning: no previously-included files matching '*' found under directory '.github'              warning: no previously-included files found matching 'release.py'                               warning: no previously-included files found matching '.coveragerc'                              warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files found matching '.readthedocs.yml'                         warning: no previously-included files found matching 'dev-requirements.txt'                     warning: no previously-included files found matching 'tox.ini'                                  warning: no previously-included files found matching 'mypy.ini'                                 warning: no previously-included files matching '*' found under directory '.circleci'
      adding license file 'LICENSE'                   adding license file 'LICENSE.APACHE'            adding license file 'LICENSE.BSD'               adding license file 'LICENSE.PSF'
      writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
      copying src/cryptography/py.typed -> build/lib.linux-aarch64-cpython-310/cryptography           creating build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings/_rust           copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings/_rust               copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings/_rust               copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-aarch64-cpython-310/cryptography/hazmat/bindings/_rust               running build_ext
      generating cffi module 'build/temp.linux-aarch64-cpython-310/_openssl.c'                        creating build/temp.linux-aarch64-cpython-310                                                   running build_rust                                  Updating crates.io index
      warning: spurious network error (2 tries remaining): SSL error: syscall failure: Software caused connection abort; class=Os (2)
      warning: spurious network error (1 tries remaining): failed to resolve address for github.com: No address associated with hostname; class=Net (12)                                              error: failed to get `asn1` as a dependency of package `cryptography-rust v0.1.0 (/data/data/com.termux/files/usr/tmp/pip-install-_7oan4ca/cryptography_c60ec21460e346a3b97433d38b10225f/src/rust)`
                                                      Caused by:
        failed to fetch `https://github.com/rust-lang/crates.io-index`                                                                                Caused by:
        network failure seems to have happened          if a proxy or similar is necessary `net.git-fetch-with-cli` may help here                       https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli                                                                   Caused by:                                        failed to resolve address for github.com: No address associated with hostname; class=Net (12)                                                                                                     =============================DEBUG ASSISTANCE=============================                      If you are seeing a compilation error please try the following steps to                         successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip                          2) Read https://cryptography.io/en/latest/installation/ for specific
             instructions for your platform.              3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq/                                                       4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation/#rust                               
          Python: 3.10.4                                  platform: Linux-4.14.186-aarch64-with-libc                                                      pip: n/a
          setuptools: 62.1.0                              setuptools_rust: 1.3.0
          =============================DEBUG ASSISTANCE=============================            
      Traceback (most recent call last):                File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()                                        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()                              File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup                                           exec(compile(code, __file__, 'exec'), locals())                                               File "setup.py", line 39, in <module>             setup(
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup                                                  return distutils.core.setup(**attrs)          File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands                                   self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command                                              super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command                                    cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')                     File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command                                     self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command                                              super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command                                    cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 136, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)                  File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 144, in run
          base_class.run(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools_rust/setuptools_ext.py", line 124, in run
          build_rust.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools_rust/command.py", line 101, in run
          self.run_for_extension(ext)                   File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools_rust/build.py", line 112, in run_for_extension
          dylib_paths = self.build_extension(ext, self.target)                                          File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools_rust/build.py", line 143, in build_extension
          target_dir = _base_cargo_target_dir(ext)                                                      File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools_rust/build.py", line 690, in _base_cargo_target_dir
          target_directory = ext._metadata()["target_directory"]                                        File "/data/data/com.termux/files/usr/tmp/pip-build-env-lbnrcpub/overlay/lib/python3.10/site-packages/setuptools_rust/extension.py", line 225, in _metadata
          self._cargo_metadata = json.loads(subprocess.check_output(metadata_command))                  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'src/rust/Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

### Steps to reproduce the behavior.

pip install cryptography --no-binary cryptography

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by sk0kanik** [comment]
>  running build_rust Updating crates.io index warning: spurious network error (2 tries remaining): SSL error: syscall failure: Software caused connection abort; class=Os (2) warning: spurious network error (1 tries remaining): failed to resolve address for github.com: No address associated with hostname; class=Net (12) error: failed to get `asn1` as a dependency of package `cryptography-rust v0.1.0 (/data/data/com.termux/files/usr/tmp/pip-install-_7oan4ca/cryptography_c60ec21460e346a3b97433d38b10225f/src/rust)` Caused by: failed to fetch `https://github.com/rust-lang/crates.io-index` Caused by: network failure seems to have happened if a proxy or similar is necessary `net.git-fetch-with-cli` may help here https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli Caused by: failed to resolve address for github.com: No address associated with hostname; class=Net (12) 

Internet Connection Problem?

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/issues/9982#issuecomment-1095549082

Before installing cryptography, please install `rust` first.

**Comment by MrAdityaAlok** [comment]
Doesn't seem to be a problem with Termux, closing now.
