### ISSUE TITLE
Unable to start activity...

### ISSUE THREAD

**Issue by GL513** [termux/termux-app#2763]
### Problem description

[termux-crash_report.log](https://github.com/termux/termux-app/files/8645178/termux-crash_report.log)

Random crash after closing the foreground service.

### Steps to reproduce the behavior.

N/A

### What is the expected behavior?

Application doesnt crash...

### System information

Check the crash report file

**Comment by agnostic-apollo** [comment]
Duplicate of https://github.com/termux/termux-app/issues/2552

Disable battery optimization for `termux-app`.
