### ISSUE TITLE
[Feature]: Android 11 Float Support without Termux:Float

### ISSUE THREAD

**Issue by zairullahdev** [termux/termux-app#2768]
### Feature description

It's for I'm gaming like Roblox, Minecraft, Or Something, I can run termux and use it like normal, Termux Float Is Too Old

### Additional information

No, Only Chat app like Whatsapp Have this feature

**Comment by zairullahdev** [comment]
![Screenshot_20220511_130333_080032403b0f3d7ce099ec68649d222a](https://user-images.githubusercontent.com/99532718/167779756-a8809de4-307d-4214-8fa2-feeaa6ffe58a.jpg)
Like this

**Comment by errr-maxx** [comment]
This is not a feature of Android 11... It's a feature of your phone.
For example: on Realme phones, this is supported for all apps.

**Comment by wmcbtech30** [comment]
Termux:Float is not old, It's an extension for Termux application for people who don't have such features. Termux also supports floating/resizable windows natively from your device (mine has floating window feature and termux works in it). closing

**Comment by zairullahdev** [comment]
There's no CTRL, ALT, etc on there
