### ISSUE TITLE
[Bug]: Error code: code 100

### ISSUE THREAD

**Issue by Anonymous1231-dev** [termux/termux-app#2769]
### Problem description

When I'm trying to wakelock Termux. It returned me code 100

![Screenshot_20220511_192221](https://user-images.githubusercontent.com/87801676/167838107-49a63a2b-3c0a-45f2-acf9-c7afc76b2c3f.jpg)

### Steps to reproduce the behavior.

Press "Acquire Wakelock"

### System information

* Termux application version: 0.118.0+4b3b1a5
* Android OS version: 12 
* Device model: V2027

**Comment by agnostic-apollo** [comment]
Thanks for the report. Will fix it.
