### ISSUE TITLE
[Feature]: Transfer from iSH

### ISSUE THREAD

**Issue by upintheairsheep** [termux/termux-app#2775]
### Feature description

Collab with the creator of iSH for this one. iSH is basically Termux for iOS (but it is way slower than termux). Please make an option to transfer from iSH to termux either by:
1. Importing .tar files from iSH
2. WiFi transfer via a package
3. Transfer via USB (collab with AOSP needed)

### Additional information

E

**Comment by DethByte64** [comment]
Why not use ssh? Openssh is available on both apps. It would be easier to scp your files back and forth, than for the hardworking termux devs to implement features and get a bigger headache than they already have with the Legacy android 5/6 and the Android W/X problems.

**Comment by wmcbtech30** [comment]
Closing since this is out of scope and can be done by user side.
