### ISSUE TITLE
[Bug]: Cannot compile cross compiler

### ISSUE THREAD

**Issue by zap8600** [termux/termux-app#2777]
### Problem description

I'm trying to build a cross-compiler on my phone so that I can take my work wherever. The target is i686-elf. When building gcc-12.1.0, I get an issue with libcpp that says `use of undeclared identifier 'fputc_unlocked'`. I've seen one issue that says that it can be implemented into the bionic library, but I don't know how to do this. Could someone help me?

### Steps to reproduce the behavior.

Compile gcc.

### What is the expected behavior?

Libcpp should build successfully. 

### System information

* Termux application version: v0.118.0
* Android OS version: 10
* Device model: SM-G965U

**Comment by Grimler91** [comment]
You can probably use fputc instead. That's what we [https://github.com/search?q=org%3Atermux+fputc_unlocked&type=code](do for libelf)
