### ISSUE TITLE
Cannot create /lib64

### ISSUE THREAD

**Issue by zap8600** [termux/termux-app#2779]
### Problem description

I would like to emulate the Minecraft Bedrock server on my phone. I can't create the /lib64 folder to copy the libraries to. 

### Steps to reproduce the behavior.

mkdir /lib64

### System information

* Termux application version: v0.118.0
* Android OS version: 10
* Device model: SM-G965U

**Comment by wmcbtech30** [comment]
The root directory is read only, if Minecraft bedrock server is closed source then you may use proot instead.

**Comment by zap8600** [comment]
I'm unsure how to use proot in my case.
