### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SplitSecComp** [termux/termux-app#2781]
### Problem description

Hi.
I am running Termux, Termux API and Termux boot on Android 10 and 11. Every thing works fine while Termux is open and running on the screen in the foreground. Termux-location, Termux-battery-status etc runs fine from Node-red while Termux is running in the foreground. As soon as i open Node-red dashboard or any other app that Termux move to the Background Termux- location etc stops to work. It gives me error: "SyntaxError: Unexpected end of JSON input"

Kindly assist.

Many thanks.

### Steps to reproduce the behavior.

Run the above mentioned apps on Android 11.

### System information

* Termux application version: Latest version
* Android OS version: Android 11
* Device model: Samsung A03 core

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-api/issues/514#issuecomment-1128727763

**Comment by SplitSecComp** [comment]
> ### Problem description
> Hi. I am running Termux, Termux API and Termux boot on Android 10 and 11. Every thing works fine while Termux is open and running on the screen in the foreground. Termux-location, Termux-battery-status etc runs fine from Node-red while Termux is running in the foreground. As soon as i open Node-red dashboard or any other app that Termux move to the Background Termux- location etc stops to work. It gives me error: "SyntaxError: Unexpected end of JSON input"
> 
> Kindly assist.
> 
> Many thanks.
> 
> ### Steps to reproduce the behavior.
> Run the above mentioned apps on Android 11.
> 
> ### What is the expected behavior?
> _No response_
> 
> ### System information
> * Termux application version: Latest version
> * Android OS version: Android 11
> * Device model: Samsung A03 core



> Check [termux/termux-api#514 (comment)](https://github.com/termux/termux-api/issues/514#issuecomment-1128727763)

Hi Agnostic.

I have looking at the other issue that you have referred me too. I did not see a solution is this something you are working on or how to i resolve this?

**Comment by agnostic-apollo** [comment]
Read my comment again, it is pretty clear. Currently, only solution is for termux to be in foreground when you run those commands.
