### ISSUE TITLE
Can not install Termux from non-playstore sources

### ISSUE THREAD

**Issue by Bluscream** [termux/termux-app#2782]
![Screenshot_2022-05-19-14-46-10-743.jpeg](https://user-images.githubusercontent.com/3318223/169297682-1232dc32-7947-4315-87f2-89be170a407c.jpeg)

![Screenshot_2022-05-19-14-49-38-356.jpeg](https://user-images.githubusercontent.com/3318223/169297701-0ae8f35b-08c9-446b-a706-e32d328019fd.jpeg)

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation
