### ISSUE TITLE
Install `v0.118.0+` and post errors if any.

### ISSUE THREAD

**Issue by joshuafvr** [termux/termux-app#2790]
Install `v0.118.0+` and post errors if any.

_Originally posted by @agnostic-apollo in https://github.com/termux/termux-app/issues/2168#issuecomment-1109101754_

**Comment by joshuafvr** [comment]
Still having same issue @agnostic-apollo

**Comment by joshuafvr** [comment]
![1653360508769](https://user-images.githubusercontent.com/74902842/169938826-ed08e9d3-690a-4dad-a7f4-3ef4746b7c8e.jpg)

**Comment by 2096779623** [comment]
https://github.com/termux/termux-app/issues/2168#issuecomment-876029352

> Copy the complete error from menu on top right (3 dots) and post that and not screenshots.

**Comment by Grimler91** [comment]
That screenshot seem to be from the old android-5 app and not from 0.118.0+. The error message is different in 0.118+:

https://github.com/termux/termux-app/blob/master/app/src/main/res/values/strings.xml#L31
https://github.com/termux/termux-app/blob/android-5/app/src/main/res/values/strings.xml#L16

**Comment by joshuafvr** [comment]
> That screenshot seem to be from the old android-5 app and not from 0.118.0+. The error message is different in 0.118+:
> 
> https://github.com/termux/termux-app/blob/master/app/src/main/res/values/strings.xml#L31 https://github.com/termux/termux-app/blob/android-5/app/src/main/res/values/strings.xml#L16

Well I downloaded it from play store just yesterday can you send the latest version pls

**Comment by joshuafvr** [comment]
Ok thanks bruv

**Comment by Grimler91** [comment]
If you are on android < 7 then you need to go for one of the android-5 apks from CI build: https://github.com/termux/termux-app/actions/runs/2373736679

**Comment by joshuafvr** [comment]
Thanks mate

**Comment by joshuafvr** [comment]
> If you are on android < 7 then you need to go for one of the android-5 apks from CI build: https://github.com/termux/termux-app/actions/runs/2373736679

![Screenshot_2022-05-28-01-56-00](https://user-images.githubusercontent.com/74902842/170803545-5667c200-c584-46bd-bf3b-e64bf890c092.png)
Thanks broo u really help me
