### ISSUE TITLE
[Bug]: https://deb.kcubeterm.me/termux-main/ failed to fetch

### ISSUE THREAD

**Issue by rubinchyk** [termux/termux-app#2791]
### Problem description

Can't install / upgrade any package. Have an exception:

Err:1 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.

### Steps to reproduce the behavior.

Install app to Android
pkg upgrade

### What is the expected behavior?

Upgrade all packages

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: Xiaomi Note 8 Pro

**Comment by Anonymous1231-dev** [comment]
Seems like in `termux-packages` and not here

**Comment by Grimler91** [comment]
Seems like your packages are outdated. Switch to a working mirror with `termux-change-repo` and then upgrade everything, `apt update && apt upgrade`
