### ISSUE TITLE
[Feature]: rename github actions names for artifacts

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-app#2793]
### Feature description

to be honest this isnt a big issue. 
The android 5, and android 7 apks are getting to long

As of currently why not make a change 
Android 5 = lagacy
Android 7 = main, current, "insert anything. Here"

### Additional information

This would make it easier to sort the artifacts, allowing for quicker reference and maintaining ease of use, just a suggestion not a really big issue

**Comment by agnostic-apollo** [comment]
> create a third alternative like `android-10`,

`tapm-android-7` actually since it would support android `7+`.

https://github.com/termux/termux-app/blob/b950efec27e71455c9e2c594c7ee45999927ed0b/termux-shared/src/main/java/com/termux/shared/termux/TermuxBootstrap.java#L141
