### ISSUE TITLE
[Bug]: Termux unable to handle pkg commands, neither apt

### ISSUE THREAD

**Issue by EDM115** [termux/termux-app#2794]
### Problem description

Everytime I'm using any `pkg` or `apt` command, I get the following error :  
```
~ $ pkg update
Testing the available mirrors:
[*] https://mirror.mwt.me/termux/main: ok
[*] https://termux.sahilister.in/apt/termux-main: ok
[*] https://plug-mirror.rcac.purdue.edu/termux/termux-main: ok
[*] https://termux.mentality.rip/termux-main: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://termux.librehat.com/apt/termux-main: ok
[*] https://termux.astra.in.ua/apt/termux-main: ok
[*] https://packages-cf.termux.org/apt/termux-main: ok
[*] https://dl.kcubeterm.com/termux-main: ok
/data/data/com.termux/files/usr/bin/pkg: line 142: 7
8
9
10
11
12
13
14
16: syntax error in expression (error token is "8
9
10
11
12
13
14
16")
```
*(example here with `pkg update`)*

### Steps to reproduce the behavior.

+ Open the app
+ Run any `pkg` or `apt` command

### What is the expected behavior?

I expect the commands to work. Btw, it appeared only since 2,5 days.

### System information

* Termux application version : `0.118.0` installed from GitHub releases
* Android OS version : `8.1.0`
* Device model : Wiko View Go - `armeabi-v7a`

**Comment by Grimler91** [comment]
Has been fixed in latest termux-tools, so `apt update && apt upgrade` should fix it
