### ISSUE TITLE
[Bug]: Termux replaces `˜` with `~`

### ISSUE THREAD

**Issue by suhr** [termux/termux-app#2799]
### Problem description

When you input `˜` with https://github.com/dzaima/hackerskeyboard, `~` is inserted instead.

### Steps to reproduce the behavior.

1. Open termux
2. Input `˜` using https://github.com/dzaima/hackerskeyboard

### What is the expected behavior?

It should not be replaced with `~`. `˜` is a [Self/Swap modifier](https://mlochbaum.github.io/BQN/doc/swap.html) in BQN programming language. Replacing it with `~` breaks code entered with arrays hacker's keyboard.

### System information

No need, this is the place of termux code which does the substitution: https://github.com/termux/termux-app/blob/master/terminal-view/src/main/java/com/termux/view/TerminalView.java#L821

**Comment by Grimler91** [comment]
Do you want to create a PR? 
As code comment says, the assumption was that `the desire to input the original characters should be low`, but if that is not true and you need it then we can just remove that case from the switch

**Comment by agnostic-apollo** [comment]
Check 231ecff, it should work. I have tested with extra keys and its not getting replaced anymore and hacker keyboard has event source `0`.
