### ISSUE TITLE
[coc.nvim] build/index.js not found, please install dependencies and compile coc.nvim by: yarn install[Bug]: 

### ISSUE THREAD

**Issue by Jenish154** [termux/termux-app#2802]
### Problem description

I tried to install the coc.nvim plugin for neovim it installs but i get this error when I open neovim

### Steps to reproduce the behavior.

Install the coc.nvim in your init.vim file and install it and restart neovim

### What is the expected behavior?

[coc.nvim] build/index.js not found, please install dependencies and compile coc.nvim by: yarn install

### System information

* Termux application version:Newest Version
* Android OS version:10
* Device model:Redmi 9a

**Comment by luisdavim** [comment]
I use coc.nvim on Termux with no problems. Are you sure you followed the correct installation process?

**Comment by Freed-Wu** [comment]
I can use coc.nvim in termux, although I use a release version not build it manually. Can you try <https://github.com/neoclide/coc.nvim/tree/release>?

**Comment by ciullaanthonyj** [comment]
> 

Worked for me!

**Comment by Freed-Wu** [comment]
> > 
> 
> Worked for me!

Glad to hear this good message.

Can this issue be closed?
