### ISSUE TITLE
Problem installing termux and plugins 

### ISSUE THREAD

**Issue by Aplha101** [termux/termux-app#2803]
### Problem description

I was having issues installing termux and other plugins when i saw the termux:API app already installed in uninstalled it and was successfully able to install termux styling and termux float but I'm still not able to install termux 

### Steps to reproduce the behavior.

Installalling termux apk from GitHub after uninstalling the termux api

### System information

* Termux application version: 0.118
* Android OS version: 8
* Device model:

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation
