### ISSUE TITLE
Cache downloaded deb files for sharing between devices.

### ISSUE THREAD

**Issue by bharat226g** [termux/termux-app#281]
The current termux app doesnt cache the downloaded deb files.

Would be nice to cache downloaded deb files, as an advanced configurable option, not enabled by default.

**Comment by fornwall** [comment]
If you install a package using `apt-get` instead of `apt` the downloaded deb files should be cached in `$PREFIX/var/cache/apt/archives`.

Try it out with (assuming that `yasm` is not already installed):

    apt-get install yasm
    ls $PREFIX/var/cache/apt/archives

**Comment by bharat226g** [comment]
yes, apt-get does cache packages. Thank you.
