### ISSUE TITLE
Can't get private /storage/external directory created because I am using adoptable storage on my SD card?

### ISSUE THREAD

**Issue by azinod** [termux/termux-app#282]
So I used the termux-setup-storage command to setup local storage, but the storage/external folder is not being created.

I suspect this happens because I am using my SD card as adoptable storage, and the /external folder is only created if I have a SD card but apparently has to be mounted as external storage and not internal/adoptable storage.

Is there a way around this?

**Comment by biojet1** [comment]
I think the path to termux is hard codedk, search "/data/data/com.termux/files/" in termux-app

**Comment by sdrausty** [comment]
A Feature Request: `mount loopback device`   https://github.com/termux/termux-app/issues/376 topic.  A few related https://github.com/termux/termux-app/issues/created_by/sdrausty issues.  Someday.  Maybe soon.

**Comment by xeffyr** [comment]
When external sdcard is formatted as adoptable storage, it will be mounted as shared (internal) storage (which is `/sdcard` or `/storage/emulated/0`).

So you need refer to `storage/shared` instead. Directory `storage/external` is used for external *removable* (non-adoptable) storage.
