### ISSUE TITLE
[Bug]: Trying to install from artifact https://github.com/termux/termux-app/actions/runs/2373736679 renders app not installed on android 6

### ISSUE THREAD

**Issue by bitcoinmeetups** [termux/termux-app#2823]
### Problem description

[Bug]: Trying to install from artifact https://github.com/termux/termux-app/actions/runs/2373736679 renders app not installed error on android 6

### Steps to reproduce the behavior.

If you have an old Android phone laying around, you can try to install the APK. I tried almost all versions including arme, universal, arm64 and all of them rendered app not installed error on Android 6.

### What is the expected behavior?

"App installed successfully"

### System information

* Termux application version:  https://github.com/termux/termux-app/actions/runs/2373736679 
* Android OS version: Android 6
* Device model:
Asus Zen

**Comment by agnostic-apollo** [comment]
Uninstall existing termux and any plugin apps from android settings app list.
