### ISSUE TITLE
[Bug]: Cannot update to v0.118

### ISSUE THREAD

**Issue by Melab** [termux/termux-app#2824]
### Problem description

I have Termux v0.101 currently installed. I downloaded v0.118 from F-Droid's website and attempting to install the package results in "App not installed". Why? How do I fix this?

### Steps to reproduce the behavior.

See above.

### System information

* Termux application version: 0.101
* Android OS version: 10
* Device model: Google Pixel

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation
