### ISSUE TITLE
[Feature]: access control on storage access framework clients of termux

### ISSUE THREAD

**Issue by aa755** [termux/termux-app#2825]
### Feature description

like most people, i have to run some untrusted closed source apps. I would like them to not have access to my termux directory. Actually, i want most apps to not have access to my termux directory. Is it possible to implement a whitelist?

### Additional information

None

**Comment by agnostic-apollo** [comment]
No other non-termux app has access to termux private files under `$HOME` or `$PREFIX`, unless you manually give access via SAF. Neither does termux have access to other app's private files, unless root has been granted.

https://wiki.termux.com/wiki/Internal_and_external_storage
