### ISSUE TITLE
[Bug]: Termux xdg-open can't use external aplications

### ISSUE THREAD

**Issue by Fmert24** [termux/termux-app#2828]
### Problem description

External aplications mpv vlc or samsung galery cannot used
termux 0.117 is capable starting external aplications but 0.118 is not capable

### Steps to reproduce the behavior.

cd ~/storage/DCIM/Screenshots/
xdg-open foo.jpg
galery aplication popup boble says acces denied

### What is the expected behavior?

Opens a image in phones galery aplication or starts a video

### System information

* Termux application version:0.118
* Android OS version:9
* Device model:SM-J701F

**Comment by agnostic-apollo** [comment]
Check release note.

https://www.reddit.com/r/termux/comments/s266li/dev_termux_v01180_release/

https://github.com/termux/termux-app/releases/tag/v0.118.0
