### ISSUE TITLE
[Bug]: kindle fire HD 7 (2019) fails to install 

### ISSUE THREAD

**Issue by lnee94** [termux/termux-app#2830]
### Problem description

When i do `adb install com.termux_118.apk `
I get 
```
Performing Streamed Install
adb: failed to install com.termux_118.apk: Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package couldn't be installed in /mnt/expand/3d65df1c-a4a5-4618-b749-37276c697b35/app/com.termux-UzGAbtSQlAAzSTlBeNtvHg==: Package com.termux has no signatures that match those in shared user com.termux; ignoring!]
```

### Steps to reproduce the behavior.

Have a kindle of the type `HD 7 (2019)` or others idk
Download the APK and run `adb install com.termux_118.apk `

### What is the expected behavior?

For termux to install

### System information

* Termux application version:118
* Android OS version:9
* Device model:Fire 7 (9th generation)

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation
