### ISSUE TITLE
[Bug]: can't upgrade installed packages

### ISSUE THREAD

**Issue by baitmooth** [termux/termux-app#2837]
### Problem description

When trying to upgrade the installed packages via 'pkg upgrade' the process fails with:
`Testing the available mirrors:
[*] https://mirror.mwt.me/termux/main: ok
[*] https://termux.sahilister.in/apt/termux-main: ok
[*] https://plug-mirror.rcac.purdue.edu/termux/termux-main: ok
[*] https://termux.mentality.rip/termux-main: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://termux.librehat.com/apt/termux-main: ok
[*] https://termux.astra.in.ua/apt/termux-main: ok
[*] https://packages-cf.termux.org/apt/termux-main: ok
[*] https://dl.kcubeterm.com/termux-main: ok
/data/data/com.termux/files/usr/bin/pkg: line 142: 7
8
9
10
11
12
13
14
16: syntax error in expression (error token is "8
9
10
11
12
13
14
16")`

### Steps to reproduce the behavior.

Run `pkg upgrade`

### What is the expected behavior?

Get updated packages 

### System information

* Termux application version: 0.118.0 via fdroid
* Android OS version: lineageos18.1
* Device model: SM-A520F

**Comment by Grimler91** [comment]
Do `apt update && apt upgrade` and pkg will work again

**Comment by baitmooth** [comment]
> Do `apt update && apt upgrade` and pkg will work again

Thanks. That worked.
