### ISSUE TITLE
[Feature]: Configure the buttons below terminal window

### ISSUE THREAD

**Issue by ZaxonXP** [termux/termux-app#2839]
### Feature description

Currently there are following buttons displayed and cannot be configured:
ESC  /    -   HOME  <up>   END   PGUP
TAB   CTRL    ALT   <left> <down>  <right>  PGDN

It would be nice to have a possibility to edit the content of this on-screen keypad.

### Additional information

n/a

**Comment by agnostic-apollo** [comment]
https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row
