### ISSUE TITLE
Termux doesn't start

### ISSUE THREAD

**Issue by GitKalle** [termux/termux-app#284]
If I try to start Termux it closed immediately.

Android-version: 5.1.1

Logcat:

V/WindowManager(  572): Adding window Window{35c26e57 u0 com.termux/com.termux.app.TermuxActivity} at 17 of 24 (before Window{24b3138b u0 Starting com.termux})
D/ZenLog  (  572): intercepted: 0|com.termux|1337|null|10169,none
V/NotificationService(  572): pkg=com.termux canInterrupt=false intercept=true
D/ListenerService( 1554): onNotificationPosted 001 : com.termux
E/StatusBar( 1327): couldn't inflate view for notification com.termux/0x539
W/StatusBar( 1327): removeNotification for unknown key: 0|com.termux|1337|null|10169
D/NotificationService(  572): onNotification error pkg=com.termux tag=null id=1337; will crashApplication(uid=10169, pid=27053)
D/ListenerService( 1554): onNotificationRemoved : com.termux
W/StatusBar( 1327): removeNotification for unknown key: 0|com.termux|1337|null|10169
V/WindowManager(  572): Adding window Window{1809ae2d u0 com.termux/com.termux.app.TermuxActivity} at 18 of 25 (before Window{24b3138b u0 Starting com.termux})
I/WindowManager(  572): Switching to real app window: Window{35c26e57 u0 com.termux/com.termux.app.TermuxActivity}
E/AndroidRuntime(27053): Process: com.termux, PID: 27053
E/AndroidRuntime(27053): android.app.RemoteServiceException: Bad notification posted from package com.termux: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.termux user=UserHandle{0} id=1337 tag=null score=-20 key=0|com.termux|1337|null|10169: Notification(pri=-2 contentView=com.termux/0x1090078 vibrate=null sound=null defaults=0x0 flags=0x62 color=0xff000000 actions=2 vis=PRIVATE))
W/ActivityManager(  572):   Force finishing activity 1 com.termux/.app.TermuxActivity
W/PackageManager( 1327): Failure retrieving resources for com.termux: Resource ID #0x0
W/ActivityManager(  572): Activity pause timeout for ActivityRecord{12a36802 u0 com.termux/.app.TermuxActivity t1014 f}
I/WindowState(  572): WIN DEATH: Window{35c26e57 u0 com.termux/com.termux.app.TermuxActivity}
W/InputDispatcher(  572): channel '1809ae2d com.termux/com.termux.app.TermuxActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  572): channel '1809ae2d com.termux/com.termux.app.TermuxActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/WindowState(  572): WIN DEATH: Window{1809ae2d u0 com.termux/com.termux.app.TermuxActivity}
W/InputDispatcher(  572): Attempted to unregister already unregistered input channel '1809ae2d com.termux/com.termux.app.TermuxActivity (server)'
I/ActivityManager(  572): Process com.termux (pid 27053) has died
W/ActivityManager(  572): Scheduling restart of crashed service com.termux/.app.TermuxService in 1000ms

**Comment by fornwall** [comment]
Which device? Custom rom or stock?

**Comment by GitKalle** [comment]
It's a Sony Xperia Z3 compact with custom Rom.

**Comment by GitKalle** [comment]
Plugin Termux:Float works without problems.

**Comment by MineFuehrer** [comment]
Could be related:

https://forum.odroid.com/viewtopic.php?f=113&t=26601

**Comment by GitKalle** [comment]
Up to version 0.51 I had the problem. 
Now I'm on Carbonrom (Android 7.1.2) and I don't have any problems.

_Sent from my Sony Xperia Z3C using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
