### ISSUE TITLE
[Bug]:UNABLE TO INSTALL BOOTSTRAP PACKAGES

### ISSUE THREAD

**Issue by SHAHZAIN-SDJ** [termux/termux-app#2846]
### Problem description

Unable

### Steps to reproduce the behavior.

Unable

### What is the expected behavior?

UNABLE 

### System information

* Termux application version:all
* Android OS version:6.1
* Device model:samsunggrandprimeplus

**Comment by Grimler91** [comment]
Maybe you are experiencing https://github.com/termux/termux-app/issues/2844, or maybe you are on android 5/6: https://github.com/termux/termux-app/wiki/Termux-on-android-5-or-6

**Comment by SHAHZAIN-SDJ** [comment]
SIR CHECK OUT THIS ISSUE AGAIN SOME DAYS EARLIER THIS VERISON OFF TERMUX
WORK PROPLY BUT IM UNINSTALL DUE TOO SOME THEN AGAIN INSTALL AND FACING
THIS PRONLM PLEASE FIX THIS...THIS ISSUE IS NOT FACE MEE SOME OTHERS USERS
ALSOO THIS PROBLEMS PLeASE SIR FIX THIS 😍🙄😷
