### ISSUE TITLE
[Bug]: Text cut off on italic

### ISSUE THREAD

**Issue by holiq** [termux/termux-app#2856]
### Problem description

I use powerlevel and font [Meslo Nerd Font patched for Powerlevel10k](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k) on my termux, but in my neovim, the italic text is cut off like in the screenshot below, if i use another font the italic text is not cut off but the icon at the prompt does not appear or error, so how to fix that?
![Screenshot_20220624-173212_Termux](https://user-images.githubusercontent.com/30729921/175522263-a9678bc8-471b-433d-9d5e-0f1d0bf94b14.png)

### Steps to reproduce the behavior.

```sh
vi test.ts
```
And type this
```ts
public 
function
status
// Comment
// M
```

### System information

* Termux application version: 0.0118.0+8746db0
* Android OS version: Android 11
* Device model: Samsung Galaxy A20s

**Comment by rendiix** [comment]
Use Termux apk from this pr https://github.com/termux/termux-app/pull/2829 Or wait until the projects are merged. It supports true italic font

![Screenshot_20220628-111110012 (1)](https://user-images.githubusercontent.com/16639978/176091248-87bf6496-2926-4397-873b-5352577aef38.jpg)

**Comment by holiq** [comment]
@rendiix I have tried as you said, but it still doesn't work, Maybe my phone is not suitable for this, after remembering it happened after I updated my phone software

**Comment by rendiix** [comment]
Have you added the true italic font to the .termux folder?
![Screenshot_20220629-064728462 (1)](https://user-images.githubusercontent.com/16639978/176322726-8f1702ce-b9fa-4d25-ada5-4dfa2c7da153.jpg)

Fonts are still truncated if you don't use italic fonts
![Screenshot_20220629-064107168 (1)](https://user-images.githubusercontent.com/16639978/176323000-7487024a-2ebb-4b11-a428-f7f646f84c3d.jpg)

**Comment by holiq** [comment]
@rendiix oh yeah that's work, i forgot to add font-italic, thanks mate 
![Screenshot_20220629-143522_Termux](https://user-images.githubusercontent.com/30729921/176379198-3cb9449a-a658-404a-8aa9-4b00826cb8e7.png)
