### ISSUE TITLE
[Bug]:  latest versions are not showing in f-droid Android 10.x

### ISSUE THREAD

**Issue by pro465** [termux/termux-app#2859]
### Problem description

im running termux 0.101 without being able to update it using f-droid

### Steps to reproduce the behavior.

- open f-droid in Android 10.x
- search for termux app

### What is the expected behavior?

latest version to show up, since im running a supported android version

### System information

* Termux application version: 0.101
* Android OS version: 10
* Device model: M2006C3LI

**Comment by Grimler91** [comment]
You need to uninstall the app first if it is installed from google play, they are signed with different keys and incompatible
