### ISSUE TITLE
Please do not symlink gcc to clang

### ISSUE THREAD

**Issue by pmatos** [termux/termux-app#286]
I noticed gcc is not supported and instead installs clang, that's fine except gcc is _not_ clang, so please do not make them the same. Symlinking gcc to clang is not a solution but something that needs fixing.

**Comment by fornwall** [comment]
I would like gcc to be supported and work well on Android - but unfortunately it doesn't. Upstream doesn't support Android and google has dropped support for gcc targeting Android.

Given that, `gcc` as a symlink to `clang` is probably the best solution (a lot better than not having gcc at all) for most users, as it doesn't break their workflow and makes installing things using tarballs/pip/gem/npm/etc mostly work. macOS also does it and it works for many users there as well.

So not an ideal, but hopefully a pragmatic setup.

**Comment by fornwall** [comment]
For those really requiring gcc in Termux, @its-pointless is hosting gcc in a third-party repository.
