### ISSUE TITLE
[Bug]: Can't Access some files in /sdcard using termux.

### ISSUE THREAD

**Issue by anshiq** [termux/termux-app#2860]
### Problem description

I was using termux to share data from /sdcard/android/obb to other phone using sshd and scp. But it was unable to access files of the obb folder. 

### Steps to reproduce the behavior.

Termux-setup-storage
Cd /sdcard/android/obb
scp file.txt scp://user@ip:8022//

### System information

* Termux application version:
* Android OS version:
* Device model:
Latest .118 i think
Android 11
Redmi note 8 pro

**Comment by 2096779623** [comment]
Don't you think, you need to provide the output of `termux-info` :) .

**Comment by wmcbtech30** [comment]
Android 11 introduced restrictions regarding with `Android/{data,obb}` access
https://developer.android.com/about/versions/11/privacy/storage#file-access

Closing since this cannot be fixed on termux-side, which this would have required extra privileges for programs to access those directories

**Comment by agnostic-apollo** [comment]
Grant `REQUEST_INSTALL_PERMISSION` for `Android/obb` access.

https://github.com/termux/termux-app/commit/93a5bf8d

**Comment by anshiq** [comment]
Is that included in latest version  of termux or not.

**Comment by agnostic-apollo** [comment]
`v0.109+`

**Comment by agnostic-apollo** [comment]
`v0.109+`

**Comment by anshiq** [comment]
so why i am not able to access files present in obb.

**Comment by anshiq** [comment]
@2096779623 @wmcbtech30 @agnostic-apollo @EdwardBetts  https://developer.android.com/training/data-storage/manage-all-files  can this help to access all files.

**Comment by agnostic-apollo** [comment]
1. Actual path is `/sdcard/Android/obb`, not `/sdcard/android/obb`
2. Actually grant  `REQUEST_INSTALL_PERMISSION` as linked commit says in my comment

**Comment by sylirre** [comment]
> https://developer.android.com/training/data-storage/manage-all-files can this help to access all files.

This is only to opt-out from scoped storage on Android 10+. With it application can read/write all kinds of files, not only media.

It doesn't give access to `obb` directory as stated in documentation.
>> Write access to all internal storage directories⁠, **except** for /Android/data/, /sdcard/Android, and most subdirectories of /sdcard/Android. This write access includes [direct file path](https://developer.android.com/training/data-storage/shared/media#direct-file-paths) access.
