### ISSUE TITLE
[Bug]:[Process completed (signal 11) - press Enter]

### ISSUE THREAD

**Issue by rbjnazz** [termux/termux-app#2863]
### I just messed up .zshrc

result:

![Screenshot_2022-07-04-16-33-49-22_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/85556041/177116480-f9ed56e6-f8e1-49ed-af6f-4ecf612d7434.jpg)

### Steps to reproduce the behavior.

I added this on my .zshrc 
```bash
export PATH="/data/data/com.termux/files/home/storage/some-folder"
```

### System information

* Termux application version: 0.118.0
* Android OS version: 10
* Device model: Realme 3 RMX1821

**Comment by sylirre** [comment]
> export PATH="/data/data/com.termux/files/home/storage/some-folder"

By doing that you are discarding old `PATH` and shell will not be able to find standard utilities.

Do this instead:
```
export PATH="${PATH}:${HOME}/storage/some-folder"
```
However adding directories from `~/storage` isn't a good idea - file system on shared (external) storage doesn't allow execution.
