### ISSUE TITLE
Allow hiding android vitural keys

### ISSUE THREAD

**Issue by xtyxtyx** [termux/termux-app#287]
When using termux with a keyboard, the virtual key at the bottom of the screen has no use and it takes extra space.

It would be fine if we can do this by typing a line such as `virtual-keys=false` into termux.properties file.

Thank you very much!

**Comment by Grimler91** [comment]
The soft keyboard disappears automatically for me (on my samsung s4 and tablet) when connecting a hardware keyboard. Does it disappear if you tap the keyboard button in the left menu? 

![screenshot](https://cloud.githubusercontent.com/assets/18900601/24404892/32e27362-13c3-11e7-90d6-65e4a48041cc.png)

**Comment by xtyxtyx** [comment]
Sorry, I mean this.
![_20170328_205021](https://cloud.githubusercontent.com/assets/15033141/24405702/70816120-138b-11e7-8547-ba491b392d67.JPG)

![screenshot_2017-03-28-19-07-53](https://cloud.githubusercontent.com/assets/15033141/24405507/bca0efea-138a-11e7-9f79-3be54e2af1e2.png)

**Comment by Grimler91** [comment]
Ah, sorry, I read your question too fast..

**Comment by twaik** [comment]
From https://wiki.termux.com/wiki/Terminal_Settings
Fullscreen mode

### Enable fullscreen mode with

```
fullscreen=true
```

It is likely that with fullscreen enabled, the Extra Keys view may no longer be visible. To fix, add
```
use-fullscreen-workaround=true
```
Note: Fullscreen may not work well for all devices so consider it unstable for now.
