### ISSUE TITLE
[Bug]: Unable to use the package manager "pkg install"

### ISSUE THREAD

**Issue by LobsterMan123** [termux/termux-app#2874]
### Problem description

I just installed Termux from F-droid as recommended since I had the older version but whenever I try to use the "pkg" package manager either to update packages or to try to get a package directly, I get the following error:

_Testing the available mirrors:
[*] https://packages-cf.termux.org/apt/termux-main: ok
[*] https://deb.kcubeterm.me/termux-main: ok
[*] https://termux.mentality.rip/termux-main: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://termux.librehat.com/apt/termux-main: ok
Picking mirror: https://deb.kcubeterm.me/termux-main
Get:1 https://deb.kcubeterm.me/termux-main stable InRelease [507 B]
Err:1 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror._

Here are my device specs upon running "termux-info":

_Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.14-14676478 #1 SMP PREEMPT Mon May 10 21:24:57 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T378V_

Why am I unable to use the package manager?  Thanks for any help anyone can provide.

LM

### Steps to reproduce the behavior.

Commands that trigger the error are: _pkg upgrade_ and _pkg install vim_

### System information

Application version:
0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
8.1.0
Kernel build information:
Linux localhost 3.18.14-14676478 #1 SMP PREEMPT Mon May 10 21:24:57 KST 2021 armv8l Android
Device manufacturer:
samsung
Device model:
SM-T378V

**Comment by agnostic-apollo** [comment]
Use `termux-change-repo` to change repo and run `apt update; apt install termux-tools`

**Comment by filip2cz** [comment]
> Use `termux-change-repo` to change repo and run `apt update; apt install termux-tools`

I need to install termux-tools firts, but i can't use package manager
