### ISSUE TITLE
sigtimedwait 

### ISSUE THREAD

**Issue by abijahm** [termux/termux-app#288]
am trying to compile nimlang on android i get an error

undefined reference to sigtimedwait

**Comment by MeinFuehrer** [comment]
Were you following these instructions?

http://stisa.space/articles/compile-nim-on-android/

**Comment by abijahm** [comment]
yah i followed the instruction they solve the issue with glob.h  it seems that the function sigtimedwait is not in the signal.h included in termux , could you have the solution to this

**Comment by MeinFuehrer** [comment]
Those instructions are out of sync in two respects, namely, `aarch64` is already a supported target and it's not reveant anyway as we're trying to compile for `armhf`.

Might be a good idea posting a build log in the Nim forum.

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#899
