### ISSUE TITLE
[Feature]: Possible to decrease the ram and rom usage of the termux

### ISSUE THREAD

**Issue by passerbyo** [termux/termux-app#2880]
### Feature description

Possible to decrease the ram and rom usage of the termux

### Additional information

Possible to decrease the ram and rom usage of the termux

**Comment by SunPodder** [comment]
Termux itself consumes a little amount of ram and the app size is about 100MB. The total app size depends on the packages and tools you installed from other sources. It is totally upto which packages you use and how much space they consume. The maintainer have nothing to do with it.
