### ISSUE TITLE
[Bug]: Virtual Keyboard issues with vim

### ISSUE THREAD

**Issue by ArtemisX64** [termux/termux-app#2884]
### Problem description

I am facing a weird issue with vim in Termux. When I press backbutton, the virtual keyboard hides and it pops up when I click anywhere else on termux except in case of vim where I have to either exit vim or go to recents to get virtual(soft) keyboard back.

### Steps to reproduce the behavior.

Open Vim, press back button to hide keyboard. Press Anywhere to bring the keyboard back.

### What is the expected behavior?

Soft keyboard shows up

### System information

* Termux application version: 0.118.0+605dd6c
* Android OS version: 12
* Device model: OnePlus CE2 Lite

**Comment by zairullahdev** [comment]
Literally just swipe the virtual toolbar to right and click there, then swipe the virtual toolbar again to left

**Comment by 2096779623** [comment]
I often encounter this when using vim.

**Comment by sweetkitty13** [comment]
> Literally just swipe the virtual toolbar to right and click there, then swipe the virtual toolbar again to left

I know a even better idea by swipping left(Opens a treeview with new session and Keyboard buttons) and clicking keyboard. But since outside of vim, it opens keyboard when I touch anywhere, shouldn't I expect the same inside vim too?

**Comment by SunPodder** [comment]
Not only vim but also nano. When you add `set mouse` in `.nanorc`. 
It happens because you are using your touch inputs as mouse movement not as mouse clicks and this is built-in in vim (nano needs to be configured). So I don't think it's a bug. 
The best workaround for this is to add `KEYBOARD` key in your termux extra keys. Use that key to open and close keyboard

**Comment by sweetkitty13** [comment]
> Not only vim but also nano. When you add `set mouse` in `.nanorc`. It happens because you are using your touch inputs as mouse movement not as mouse clicks and this is built-in in vim (nano needs to be configured). So I don't think it's a bug. The best workaround for this is to add `KEYBOARD` key in your termux extra keys. Use that key to open and close keyboard

Works like charm. I think I should leave this open so that others can see the workaround(when using vim)

**Comment by 2096779623** [comment]
@Neo-Oli Add it to Termux Wiki?

**Comment by sylirre** [comment]
That's expected behavior for all programs that use *alternate screen mode* (most Ncurses-based programs) and listen to mouse events. There are other differences besides this one, like up/down swipe is translated into mouse wheel events.
