### ISSUE TITLE
Use an external keyboard can't type in Chinese[Bug]: 

### ISSUE THREAD

**Issue by CYLlinmaian** [termux/termux-app#2888]
### Problem description

You cannot enter Chinese when using an external keyboard. You can use the virtual keyboard. I hope to repair it and adapt to the external keyboard

### Steps to reproduce the behavior.

Chinese input

### System information

* Termux application version:.118
* Android OS version:huawei matpad 10.8
* Device model:

**Comment by 2096779623** [comment]
大哥，用英语！

**Comment by Grimler91** [comment]
Is the layout of the keyboard set to Chinese? What happens when you try to write something?

I don't have a keyboard with Chinese layout, but switching from English to Swedish input works fine with the hardware keyboards I do have

**Comment by 2096779623** [comment]
It may be that Android does not support physical keyboard input Chinese by default. My Android version is 10, and it only shows these supported languages:

https://user-images.githubusercontent.com/57583560/179122502-c754d62b-bf9e-4043-a951-916d63a2e135.png

https://user-images.githubusercontent.com/57583560/179122527-aec0fbb4-cdf1-4b84-97d1-65750ab6e2a5.png

https://user-images.githubusercontent.com/57583560/179122537-d8b8035a-652a-4230-91a6-33b72138ae3d.png

https://user-images.githubusercontent.com/57583560/179122557-76d84f51-acdd-4339-89b1-caad78c5b11d.png

https://user-images.githubusercontent.com/57583560/179122571-7cb17910-ff5d-4b66-8a06-672a18476c51.png

**Comment by agnostic-apollo** [comment]
Android does not provide chinese keyboard layout files by default currently. Even gboard added support for chinese in only [2018](https://www.androidpolice.com/2018/03/06/google-announces-new-language-support-gboard-including-korean-chinese/).

https://cs.android.com/android/platform/superproject/+/android-12.0.0_r34:frameworks/base/packages/InputDevices/res/raw/

You could potentially create one yourself with https://github.com/ris58h/custom-keyboard-layout or https://github.com/abbeyanke/se_sv_dvorak

This is not really the job for Termux app, so closing.
