### ISSUE TITLE
[Feature]: Add ADB shell `PATH` to Termux `PATH`

### ISSUE THREAD

**Issue by Rudxain** [termux/termux-app#2890]
### Feature description

The default `PATH` in my device is: `/data/data/com.termux/files/usr/bin`, and I had to append `/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin` because Termux doesn't have `strings` cmd.

I'm not saying that `strings` should be preinstalled, I would rather uninstall `md5sum` from Termux just to use the one from `/system/bin`, and only install the Termux version if I want additional features.

What I mean is that Termux should use built-in system executables, and give users an opt-in to install "enhanced" versions if they want

### Additional information

Llamalab Automate also makes use of the default system `PATH`

**Comment by 2096779623** [comment]
Termux has adb, install it with this command, it will be in PATH: `pkg i android-tools`.

**Comment by Grimler91** [comment]
Just add `/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin` to PATH in your ~/.bashrc or similar. There's no guarantee those system tools work, or work the same on devices from different manufacjters, so adding them to PATH to default for all users would be a bad idea

**Comment by sylirre** [comment]
> What I mean is that Termux should use built-in system executables

It shouldn't and in fact that's the main difference of Termux from other terminal emulator apps. It provides a custom userland with full blown tools like Bash, Coreutils and a lot more. Not the limited Toybox-based set of utilities.

> give users an opt-in to install "enhanced" versions if they want

Users already can opt-in or opt-out of this. If you prefer system executables, consider editing the ~/.bashrc (already suggested).

**Comment by Rudxain** [comment]
@2096779623 why is ADB related to this? I don't understand. Please explain

**Comment by 2096779623** [comment]
> @2096779623 why is ADB related to this? I don't understand. Please explain

Not all Android comes with adb, if not, you need to install it manually.

Android platform tools contains adb.

**Comment by Rudxain** [comment]
> Just add `/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin` to PATH in your ~/.bashrc or similar

I already did that to my `.bash_profile`, thank you for the suggestion anyways.

> There's no guarantee those system tools work, or work the same on devices from different manufacters, so adding them to PATH per default for all users would be a bad idea

Good point, I didn't thought of that

**Comment by Rudxain** [comment]
> Not all Android comes with adb, if not, you need to install it manually

True, but doesn't that have compatibility problems on legacy devices? Or does it work on almost any Android version (5L and up)?

**Comment by 2096779623** [comment]
> True, but doesn't that have compatibility problems on legacy devices? Or does it work on almost any Android version (5L and up)?

This package is not available in Termux for Android 5.

**Comment by Rudxain** [comment]
> This package is not available in Termux for Android 5.

I just rembered that newer versions Termux are only compatible with A7, silly me. Sorry for asking a stupid question

**Comment by 2096779623** [comment]
> Edit: "Automate" has support for ADB via WiFi, but I didn't test it on my A8O device. Does ADB work via USB OTG?

https://github.com/termux/termux-packages/issues/1145

https://github.com/termux/termux-packages/issues/10634

You can have a try😁

**Comment by Rudxain** [comment]
I have an OTG cable now. I'll test ADB OTG, when I get some free time IRL.

BTW, I just noticed that this issue is a "spiritual duplicate" of #2201

**Comment by reeaosirjustsir** [comment]
Hello there! **Reeao here!**

I have my former issued problem you can **mistakenly** go.:
https://github.com/termux/termux-app/issues/4007
