### ISSUE TITLE
[Bug]: problems with Emoji Keyboard

### ISSUE THREAD

**Issue by AndreyKozhev** [termux/termux-app#2899]
### Problem description

When I use Emoji Keyboard, errors occur, as in the video below, when using any other keyboard, the text is entered normally.

https://user-images.githubusercontent.com/103951737/179760360-b3188d96-0b45-4310-af9f-1d900317ab6b.mp4

### Steps to reproduce the behavior.

Select Emoji Keyboard as the default keyboard, enter commands in Termux.

### What is the expected behavior?

Commands will be printed as when using any keyboard.

### System information

* Termux application version: 0.118.0+2113407 (118)
* Android OS version: 10
* Device model: M2006C3MNG (Redmi 9C)

**Comment by 2096779623** [comment]
This is "word mode", you need to click on the word to type.

**Comment by 2096779623** [comment]
https://user-images.githubusercontent.com/57583560/179764208-7b68892c-3ea5-4ee5-8295-58a86c46f1cb.mp4

**Comment by AndreyKozhev** [comment]
Understood, thanks.
