### ISSUE TITLE
Add support for Samsung's multi-window

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-app#29]
Would be nice to have a web page or video open next to my Termux shell in splitscreen, [docs available here](http://developer.samsung.com/resources/multiwindow).

**Comment by sarimak** [comment]
Extract from the docs is also available here: https://f-droid.org/forums/topic/request-add-support-for-samsung-multi-window/

**Comment by Holzhaus** [comment]
Bump, this would be absolutely awesome.

**Comment by makripodis** [comment]
That would be mandatory for me as well. I have the same need as joakim-noah, I am using an ssh client to my server to do this instead ov termux, so it would be realy great if you made the app split-view compatible!

**Comment by fornwall** [comment]
Thanks to @bumper314 this will be available in a v0.52 update available later today!

**Comment by joakim-noah** [comment]
Just downloaded the update and tried it out, works great!  Thanks, @bumper314.
