### ISSUE TITLE
Manually Entered Command Works; Script/Tasker Plugin: "Permission Denied"

### ISSUE THREAD

**Issue by anndrewww** [termux/termux-app#290]
The following functions perfectly when manually entered into a Termux session:

`rsync -avz -e ssh XX@XXX.XXX.XXX:/home/XXX/Pictures/Snapshots /data/data/com.termux/files/home/downloads/Snapshots`

The same command has been copied into an executable (chmod +x) script, but when I attempt to execute via the command line (./SyncSnapshots) or via the Tasker plugin, the following is returned:

via command line: `bash: ./SyncSnapshots: Permission Denied`

via Tasker plugin: `exec("data/data.com.termux/files/home/.termux/tasker/SyncSnapshots"): Permission Denied`

**Comment by YPetremann** [comment]
Maybe the fault is that your script is not executable, try chmod on it.

**Comment by anndrewww** [comment]
Nope, the script is executable.
