### ISSUE TITLE
[Feature]: In termux settings have a dark theme 

### ISSUE THREAD

**Issue by sebastianjnuwu** [termux/termux-app#2900]
### Feature description

 terminal in dark theme and go to settings and everything is white 

### Additional information

![Screenshot_20220719-181928](https://user-images.githubusercontent.com/101356556/179850524-3f46857c-ef74-45ab-8cfe-e15b46558fa1.jpg)

**Comment by agnostic-apollo** [comment]
Terminal theme != app theme.

App theme will be black if android goes into dark mode. To force dark mode, add `use-black-ui=true` to `~/.termux/termux.properties`.

https://wiki.termux.com/wiki/Terminal_Settings#Dark_theme
