### ISSUE TITLE
[Bug]: 0Ch (form feed) handling

### ISSUE THREAD

**Issue by alexm0n** [termux/termux-app#2901]
### Problem description

It would seem the handling of the 0Ch character (form feed) isn't working, or perhaps doesn't exist.

It should (appear to) clear the screen, though I think the actual behavior is to push everything on the screen to backscroll.

### Steps to reproduce the behavior.

echo -e "\x0c"

### System information

* Termux application version: 0.118.0
* Android OS version:
* Device model: TCL 10L

**Comment by alexm0n** [comment]
It would seem this behavior is inconsistent between the terminals I've tested.. Ideas?

**Comment by 2096779623** [comment]
![Screenshot_20220720-195909](https://user-images.githubusercontent.com/57583560/179976494-64e76d85-4dd8-4f80-aacf-2c902dd9ac8e.png)

`Bash` shell.

**Comment by agnostic-apollo** [comment]
Form feed clearing is not supported by all terminals and so is not portable. Use `clear` command or `printf '\033[2J'` or related control sequences.

https://stackoverflow.com/questions/37774983/clearing-the-screen-by-printing-a-character

https://unix.stackexchange.com/questions/591445/how-to-shift-previous-output-upwards-on-konsole

https://unix.stackexchange.com/questions/375743/why-clear-do-not-clear-whole-screen/375784#375784
