### ISSUE TITLE
[Bug]: exec("/data/data/com.termux/files/usr/bin/login"): Permission denied  [Process completed (code 1) - press Enter

### ISSUE THREAD

**Issue by Mrp1r4t3** [termux/termux-app#2915]
### Problem description

![Screenshot_20220802_205238](https://user-images.githubusercontent.com/57308381/182379280-bd4d2129-41ec-4df4-954c-046b15e34db5.jpg)

### Steps to reproduce the behavior.

Automatically kill the termux when executing command 'exec' in fail-safe session Ex.

:/data/data/com.termux/files/home $ exec blabla
sh: blabla: inaccessible or not found

[Process completed (code 127) - press Enter]

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

## Termux:API App Info

**APP_NAME**: `Termux:API`  
**PACKAGE_NAME**: `com.termux.api`  
**VERSION_NAME**: `0.50.1`  
**VERSION_CODE**: `51`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `4.9.227-perf+`  
**SDK_INT**: `30`  
**RELEASE**: `11`  
**ID**: `RP1A.200720.012`  
**DISPLAY**: `RP1A.200720.012 release-keys`  
**INCREMENTAL**: `eng.compil.20220427.170636`  
**SECURITY_PATCH**: `2022-05-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `vivo`  
**BRAND**: `vivo`  
**MODEL**: `V2102`  
**PRODUCT**: `2102`  
**BOARD**: `QC_Reference_Phone`  
**HARDWARE**: `qcom`  
**DEVICE**: `2034`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Github

[Termux](https://github.com/termux/termux-app)  
[Termux:API](https://github.com/termux/termux-api)  
[Termux:Boot](https://github.com/termux/termux-boot)  
[Termux:Float](https://github.com/termux/termux-float)  
[Termux:Styling](https://github.com/termux/termux-styling)  
[Termux:Tasker](https://github.com/termux/termux-tasker)  
[Termux:Widget](https://github.com/termux/termux-widget)  
[termux-packages](https://github.com/termux/termux-packages)  

### Email

[termuxreports@groups.io](mailto:termuxreports@groups.io)  

### Reddit

[r/termux](https://www.reddit.com/r/termux)  

### Wiki

[Termux Wiki](https://wiki.termux.com)  
[Termux](https://github.com/termux/termux-app/wiki)  
[termux-packages](https://github.com/termux/termux-packages/wiki)  
##

**Comment by Mrp1r4t3** [comment]
![Uploading Screenshot_20220802_205826.jpg…]()

**Comment by 2096779623** [comment]
Relevant issues: https://github.com/termux/termux-packages/issues/7369

# Methods without root
Enter failsafe first.
then:
```bash
cd /data/data/com.termux/files/usr/bin
stat login
```
If you see that it is not '0700/-rwx------' in the 'access' line, execute:
```bash
chmod 700 /data/data/com.termux/files/usr/bin/login
```
Then re-enter termux
# With root method
This method is applicable to 'Stats Login' when 'uid' is another user (not ` $user 'in termux).
~~If there is no root, it is recommended to use the first one~~
```bash
su -c 'chown $(whoami):$(whoami) /data/data/com.termux/files/usr/bin/login'
```
