### ISSUE TITLE
[Feature]: Use builtIN graphics API

### ISSUE THREAD

**Issue by xx1182** [termux/termux-app#2923]
### Feature description

Yeah, it is constructed in a way to "EMULATE" a terminal, what if it was constructed in a way to "MAKE" a terminal.

What if the whole view was constructed as as "low code" OpenGL https://www.khronos.org/opengl/wiki/Buffer_Object in native, and then... View ATERM rather than """not a terminal multiplayer""" 
https://developer.android.com/training/graphics/opengl/environment

**Rather than trying to directly access the GPU, just a file that file will be the swap since the CPU has to say to the GPU and then move the memory, and set it as device in your termux. /Dev/ttt **

The view should be something like this(know mostly PC, I'm making this up from knowing):
Nice = &*OpenGlContext(init)

fs.WriteFile("android/data/termux/Dev/TTT", Nice) //we write the location in memory of the openglcontext

Renderer{
swap = fs.readstream(/Dev/TTT)
Nice.BufferObjext = swap
} //just like videogames

/dev/TTT: //since termux is emulator the ram has to pass through it(GPU>TERMUX>GPU)

A fake device that just gets everything called by the Termux Implementation of OpenGL, so even graphics can be emulated natively.

Thanks. 

### Additional information

Let's goo

**Comment by xx1182** [comment]
It would be like if every program written in openGl should be recompiled to openGlContext = the adress in memory in which is /Dev/TTT {0x00aaa12}

**Comment by xx1182** [comment]
The way x11 does is by using drivers, that's it, wether it be trough a "user space implementation" like fbdev or DRM(direct kernel drivers), termux fakes the /Dev/.

To make x11 work, need also driver for one of the fake devices(That's how X does), /Dev/ttt, and to construct a fake device driver accordingly or trough the suggested implementation

**Comment by sylirre** [comment]
> Yeah, it is constructed in a way to "EMULATE" a terminal, what if it was constructed in a way to "MAKE" a terminal.

Good to read: https://en.wikipedia.org/wiki/Terminal_emulator. This article will help you to understand why Termux is a terminal emulator and what exactly it emulates. Has nothing to do with hardware emulation or virtual machines.

> just a file that file will be the swap since the CPU has to say to the GPU and then move the memory

🤯

***

First, Termux is indeed terminal emulator (subset of Xterm specification) but is not a hardware or system emulator. For second, it won't be possible to emulate a virtual GPU device using OpenGL APIs (more specifically - OpenGL ES, as only this one supported by Android).

It's unclear what you are suggesting us: virtual GPU, native graphical output to the terminal, support for OpenGL (not ES)... A frontend for graphical output is already in development: https://github.com/termux/termux-x11

Feature request doesn't seem to be correct as lacks of proper technical description and will be closed.

**Comment by xx1182** [comment]
Sorry I was suggesting to embeed "terminal drivers" trough proot, like a termux driver, so it could load devices correctly

**Comment by sylirre** [comment]
In this case should be achievable by https://github.com/termux/termux-x11. But as said, this add-on is still in development.
