### ISSUE TITLE
[Bug]: ipv6 not working in dual stack environment

### ISSUE THREAD

**Issue by jostreff** [termux/termux-app#2924]
### Problem description

I'm using termux on a test phone. I'm very surprised that ipv6 ping doesn't even work. Apparently dns resolving works though. At the same time, sites like ipv6-test.com or ipv6.google.com open wonderfully.
![Screenshot_2022-07-26-10-22-15-554_com termux](https://user-images.githubusercontent.com/14915659/183260197-520634a9-7498-47e3-b5d8-134df4e78153.jpg)
![Screenshot_2022-07-25-20-13-16-193_com termux](https://user-images.githubusercontent.com/14915659/183260201-e54022b0-0a9a-4e7b-888d-0a2c7d163463.jpg)

### Steps to reproduce the behavior.

nothing special - just try.

### What is the expected behavior?

icmpv6 to work

### System information

* Termux application version: latest public available
* Android OS version: 9 pie
* Device model: xiaomi note 5 pro

**Comment by sylirre** [comment]
`ping` and `ping6` are wrappers for Android OS utilities in /system/bin as only they have privilege capabilities set. Indeed, on some ROMs system utilities are faulty and nothing can be done with that. Though, `ping6` will probably start work in ADB or in root shell.

Works on Pixel 5, latest stock ROM:
![Screenshot_20220806-214141](https://user-images.githubusercontent.com/107305601/183262002-e489b0a3-0e5c-4cb6-9598-6b669a7f1a45.png)

***

Device-specific issue can't be fixed on Termux side and will be closed without solution.

**Comment by jostreff** [comment]
it's probably a defect of the rom that xiaomi made :(
