### ISSUE TITLE
[Bug]: PS1 Bug

### ISSUE THREAD

**Issue by crischutu07** [termux/termux-app#2928]
### Problem description

When you set PS1 for too long may it create the bug when you wrote the long code in terminal like this

https://user-images.githubusercontent.com/81855366/183295425-64d294cc-ce55-48ff-a44a-c45cc3a2d2a1.mp4

### Steps to reproduce the behavior.

1. Open Termux 0.118.0
2. Setting the bash.bashrc in /data/data/com.termux/files/usr/etc/bash.bashrc
3. Set the original PS1 into note and add long PS1 like example: `PS1="\033[0;33m\u\033[0;37m@\033[0;36m\h:\033[0;32m\w\033[0;37m` the code including color
4. Open new terminal
5. Wrote long code or spam, and may create the PS1 bug

### System information

* Termux application version: 0.118.0
* Android OS version: Android 12
* Device model: Oppo A53

**Comment by crischutu07** [comment]
Sorry for the motd.sh load too long

**Comment by sylirre** [comment]
This is a bug in your PS1. Termux, specifically the shell, behaves correctly.

You need to enclose escape sequences in `\[` and `\]`.
