### ISSUE TITLE
[Bug]: Mix Explorer Launches Bash Shell Should be Fish

### ISSUE THREAD

**Issue by remlap** [termux/termux-app#2929]
### Problem description

Termux is set to use Fish shell with chsh but when I invoke Termux from within Mix Explorer it uses Bash shell.

### Steps to reproduce the behavior.

Launch Mix Explorer with Fish set to default shell 

### What is the expected behavior?

Mix Explorer Launches Termux with Fish

### System information

* Termux application version: 118
* Android OS version: 12
* Device model: Pixel 6

**Comment by Grimler91** [comment]
What is "mix explorer"?

**Comment by remlap** [comment]
> What is "mix explorer"?

https://mixplorer.com/
https://play.google.com/store/apps/details?id=com.mixplorer.silver

Android File Manger

**Comment by agnostic-apollo** [comment]
That's because MiXplorer always sends a `RUN_COMMAND` intent for `$PREFIX/bin/bash` instead of `$PREFIX/bin/login`, and so not a termux issue, report it to its dev. Other issues have been reported for it too in the past (#2135 and termux/termux-packages#7537).
