### ISSUE TITLE
How to add custom repository?

### ISSUE THREAD

**Issue by KhanMaytok** [termux/termux-app#293]
Hello, I would like to add some packages, but I can't

I run in Termux:

    apt install python-dev libxml2-dev libxslt1-dev zlib1g-dev

But I get

    Unable to locate package libxslt1-dev
    Unable to locate package zlib1g-dev

¿How can I add custom sources-list to Termux?

**Comment by its-pointless** [comment]
Install libxslt-dev
 and zlib-dev is in ndk-sysroot package

**Comment by fornwall** [comment]
As @its-pointless says, in Termux the package is `libxslt-dev` (we generally avoid version numbers in package names).

Zlib is part of the Android platform, so you get that one for free and can compile against it as long as you have clang installed.

Third party repositories can be added by editing `$PREFIX/etc/apt/sources.list`, but note that you cannot use Debian repositories but must use repositories specific to Termux - there aren't that many around yet (but we should probably have a central place for listing them soon).

**Comment by KhanMaytok** [comment]
Many thanks for your responses! And many thanks for Termux too, it is awesome

**Comment by keeganjk** [comment]
@fornwall Yes, you should list them somewhere or add compatibility for Debian sources. That would be great.

**Comment by sdrausty** [comment]
https://wiki.termux.com/wiki/Package_Management#Community_Repositories

**Comment by Cvar1984** [comment]
Somebody can help me? my public key is missing, i can't update using original termux's repo

**Comment by Grimler91** [comment]
@Cvar1984 you can find the original trusted.gpg here: https://github.com/termux/termux-packages/blob/master/packages/apt/trusted.gpg?raw=true
