### ISSUE TITLE
[Bug]: error exec("/data/data/com.termux/files/usr/bin/login"): Permission denied  [Process completed (code 1) - press Enter]

### ISSUE THREAD

**Issue by Matheus-TestUser1** [termux/termux-app#2931]
### Problem description

exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

### Steps to reproduce the behavior.

how can i solve this is giving this error 
https://github.com/termux/termux-app/suites/7686140987/artifacts/320906962 

![Screenshot_20220809-115414_Termux](https://user-images.githubusercontent.com/99508668/183682978-1da8628e-6b6d-4278-bb0b-7e9c76cbb8e7.jpg)

### System information

* Termux application version: 0.118.0
* Android OS version:11
* Device model:Samsung A01

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/issues/7369
