### ISSUE TITLE
error: Android 5.0 and later only support position-independent executables (-fPIE).

### ISSUE THREAD

**Issue by zap8600** [termux/termux-app#2937]
### Problem description

Attempted to compile a GCC cross-compiler for i686-elf.
Finished with error.

### Steps to reproduce the behavior.

Build GCC with instructions from [here](https://wiki.osdev.org/GCC_Cross-Compiler#GCC).

### What is the expected behavior?

GCC should build.

### System information

Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=1429
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.27.0
Android version:
10
Kernel build information:
Linux localhost 4.9.186-22990479 #1 SMP PREEMPT Thu Feb 24 18:22:06 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G965U

**Comment by Grimler91** [comment]
Compile with `-fPIE` as the error says. See https://en.wikipedia.org/wiki/Position-independent_code
