### ISSUE TITLE
[Termux-github] detect as virus

### ISSUE THREAD

**Issue by kayyum-uddin** [termux/termux-app#2938]
### Problem description

Termux (any github release) detect as virus in android 12 by phone manager.
![IMG_20220817_101034](https://user-images.githubusercontent.com/94560388/185036592-5777fca3-4de9-41b6-958a-5e8b58116878.jpg)
![IMG_20220817_101018](https://user-images.githubusercontent.com/94560388/185036597-305ae0c3-b1b5-48f4-b621-816c840e323b.jpg)

### Steps to reproduce the behavior.

Install github release version, then run scan via phone manager (realme).

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by 2096779623** [comment]
![image](https://user-images.githubusercontent.com/57583560/185036955-91dd546e-5690-4a15-bfdc-253fe0a158d8.png)

Click this.

**Comment by kayyum-uddin** [comment]
APK:RepMalware [Trj] - wtf really?
![Screenshot_2022-08-17-09-57-49-93_035d55d4552197c94b0185899d8a326c~2](https://user-images.githubusercontent.com/94560388/185043076-a72d2ea0-dd69-44e8-b0da-b82759bd8fc0.jpg)

**Comment by Grimler91** [comment]
Seems like a false-positive, termux isn't a rootkit virus.

Maybe some actual rootkit virus has re-used code from termux, causing termux to be marked as a virus as well.

**Comment by agnostic-apollo** [comment]
AntiVirus apps often show false positives. The trojans in the screenshot were also detected in other apps as per search results. You can file a false positive at https://www.avast.com/false-positive-file-form.php

>Maybe some actual rootkit virus has re-used code from termux, causing termux to be marked as a virus as well.

Can you find and install this real rootkit virus on your daily device and see if its violating any of our GPL licensed code. Thanks!

**Comment by agnostic-apollo** [comment]
Both of the above trojan names are from avast.

https://forum.avast.com/index.php?topic=304817.0

https://forum.eset.com/topic/32957-eset-mobile-security-as-a-threat-on-huawei-optimizer-for-android/

**Comment by kayyum-uddin** [comment]
This issue doesn't exist in F-droid release, now currently using F-droid version so i don't care if real virus exist even or not in github release.

**Comment by Grimler91** [comment]
> Can you find and install this real rootkit virus on your daily device and see if its violating any of our GPL licensed code. Thanks!

Good plan, I'll get right to it ;)

**Comment by 2096779623** [comment]
![image](https://user-images.githubusercontent.com/57583560/197384620-f413c75c-593d-41cf-ba32-ea31489d2d5c.png)

Looks like the false positives are lifted.
