### ISSUE TITLE
not able to write to tmp folder on emacs starup (when lisp is loading org-mode)

### ISSUE THREAD

**Issue by eeenilsson** [termux/termux-app#294]
When running lisp on emacs startup (require 'org) caused the following error:

Debugger entered--Lisp error: (file-error "Creating directory" "No such file or directory" "/data/data/com.termux/files/home/tmp/babel-14591piN")
  make-directory-internal("/data/data/com.termux/files/home/tmp/babel-14591piN")
  make-directory("/data/data/com.termux/files/home/tmp/babel-14591piN")

Similar problem was fixed previously: http://endlessparentheses.com/running-emacs-on-android.html

I was able to solve this by using a wokraround based on the above, adding to the lisp file: (setq temporary-file-directory "/data/data/com.termux/files/usr/tmp/).

**Comment by fornwall** [comment]
Hm, I thought `temporary-file-directory` was already patched to be `$PREFIX/tmp` by default.

Some things to try out1

- Can you check the output of `apt-cache show emacs | grep Version` to verify that you are running the latest version `25.1-2`?

- How are you launching emacs? Directly or using emacsclient (or anything special)?

- Should creating `~/.emacs` with the content `(require 'org)` be enough to reproduce the issue, or do I need to do something more (warning: I'm not an emacs user normally)?
