### ISSUE TITLE
[Bug]: 连接蓝牙键盘无法输入中文/You can't input Chinese by connecting the Bluetooth keyboard.

### ISSUE THREAD

**Issue by liumingju** [termux/termux-app#2944]
### Problem description

When the Bluetooth keyboard is connected and used, Chinese characters can't be typed in termux anyway.

### What steps will reproduce the bug?

All

### System information

termux-info
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18720
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.26.0
Android version:
12
Kernel build information:
Linux localhost 5.10.66-android12-9-00001-gd262b276948e-ab8291727 termux/termux-packages#1 SMP PREEMPT Fri Mar 11 03:13:00 UTC 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
22041211AC

**Comment by buttaface** [comment]
Closing since no response after suggestions were made.
