### ISSUE TITLE
[Feature]: Other language support

### ISSUE THREAD

**Issue by petertill** [termux/termux-app#2949]
### Feature description

Currently, the app only speaks english. I think it would be very helpful to have support for other languages, so that it would be easier to understand how to use the application for the users.

### Additional information

It does not have this feature yet.

**Comment by 2096779623** [comment]
> Even if we translate the app all the programs would still be in English only, so we are so far not considering adding more languages to the app.

**Comment by petertill** [comment]
> > Even if we translate the app all the programs would still be in English only, so we are so far not considering adding more languages to the app.
> 
> Btw, you can try to translate https://termux.dev website.
> 
> https://github.com/termux/termux.github.io

Alright, I'll try to translate the website.
