### ISSUE TITLE
[Bug]: Build failed

### ISSUE THREAD

**Issue by morningos** [termux/termux-app#2951]
### Problem description

When I build project with `./gradlew build` , I got those error:
```
> Task :termux-shared:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':termux-shared:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:
  
  /root/workspace/android/termux-app/termux-shared/src/main/java/com/termux/shared/view/ViewUtils.java:84: Error: Call requires API level 24 (current min is 21): android.app.Activity#isInMultiWindowMode [NewApi]
              isInMultiWindowMode = (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) && ((AppCompatActivity) context).isInMultiWindowMode();
                                                                                                                      ~~~~~~~~~~~~~~~~~~~
  /root/workspace/android/termux-app/termux-shared/src/main/java/com/termux/shared/view/ViewUtils.java:88: Error: Call requires API level 24 (current min is 21): android.app.Activity#isInMultiWindowMode [NewApi]
              isInMultiWindowMode = (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) && ((Activity) context).isInMultiWindowMode();
```

### Steps to reproduce the behavior.

cd /path/to/project
./gradlew build

### What is the expected behavior?

build success

### System information

root@imorning
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.4.0-124-generic
Uptime: 7d 17h 23m
Packages: 1298
Shell: bash 5.0.17
Disk: 387G / 1.9T (22%)
CPU: Intel Core i3-2330M @ 4x 2.2GHz [45.0°C]
GPU: GeForce 610M
RAM: 3272MiB / 7797MiB
JDK: openjdk version "11.0.16" 2022-07-19

**Comment by agnostic-apollo** [comment]
What sources are you building? The `master` branch is building fine. Did you make any changes to gradle versions? There is obviously a check `Build.VERSION.SDK_INT >= Build.VERSION_CODES.N` before the call so it shouldn't throw an error and is likely a false positive by the linter due to inline check.

https://github.com/termux/termux-app/blob/211340781bcb0576ffe100fda2e0ed87d7333d53/termux-shared/src/main/java/com/termux/shared/view/ViewUtils.java#L84

You likely bumped gradle or plugin version.

https://issuetracker.google.com/issues/120255046

Maybe replace with `if` statement instead of `&&` or add `//noinspection NewApi` above line.

**Comment by morningos** [comment]
> 

![image](https://user-images.githubusercontent.com/44289789/185949597-63018fee-04bb-49a4-99c2-6fa49078f2d1.png)

**Comment by agnostic-apollo** [comment]
Send contents of `build.gradle` and `gradle/wrapper/gradle-wrapper.properties`.

**Comment by morningos** [comment]
build.gradle
```

buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.2.2"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

gradle/wrapper/gradle-wrapper.properties
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

```

And I solved with this:
![image](https://user-images.githubusercontent.com/44289789/185951193-57371e26-6a51-4104-b047-31426c46a50e.png)

**Comment by agnostic-apollo** [comment]
So I manually ran `gradlew lint` and it caused the same error, apparently normal builds are not triggering it. I have fixed it locally and changes will be pushed soon. Thanks for the report.
