### ISSUE TITLE
[Bug]: I cant use termux on my phone Oppo F1s

### ISSUE THREAD

**Issue by client-233444013** [termux/termux-app#2959]
### Problem description

After i downloaded termux 0.119.1 which is github version.. then i opened it..i got some error code tht i dont understand what it says

PLEASEE FIX THIS I NEED TO USE IT ON MY DEVICE

### Steps to reproduce the behavior.

All of it

### What is the expected behavior?

Error

### System information

* Termux application version: 0.119.1
* Android OS version: 5.1
* Device model: Oppo f1s
* Ram: 4 GB
* Kernal Arch: aarch64
* Kernel Version: 3.10.72+ (1482847378)
* Root Access: Yes
* 
![Screenshot_2022-08-24-10-47-49-10](https://user-images.githubusercontent.com/105601107/187120223-ad4c131a-1007-4cd6-b625-43a4236235fb.png)

**Comment by 2096779623** [comment]
There is a dedicated version for Android 5, download it here: https://github.com/termux/termux-app/actions/runs/2851414268

**Comment by client-233444013** [comment]
> 

Is tht work?

**Comment by client-233444013** [comment]
> There is a dedicated version for Android 5, download it here: https://github.com/termux/termux-app/actions/runs/2851414268

It works thank you so much
