### ISSUE TITLE
[Feature]: list Termux sessions

### ISSUE THREAD

**Issue by babaric-dev** [termux/termux-app#2960]
### Feature description

I want to do something on Termux start but only in the first session (i.e. clicking new session in the left menu returns false).

I am using bash, if it matters.

### Additional information

nil

**Comment by agnostic-apollo** [comment]
You can check if `$SHELL_CMD__TERMINAL_SESSION_NUMBER_SINCE_APP_START` is `1` in `~/.bashrc` if using github builds.

https://github.com/termux/termux-app/commit/150b1ff99c280dac09209b16c4149d3accf39591
