### ISSUE TITLE
[Feature]: a portable Termux without installing the termux app,  for example in /data/local/tmp/ directory

### ISSUE THREAD

**Issue by diyism** [termux/termux-app#2976]
### Feature description

I wish a portable Termux environment without installing the termux app,
for example I can use the termux environment in /data/local/tmp/ directory

I've tested this:
```
$ adb push ./my_portable_termux/com.termux/files/*    /data/local/tmp/
$ adb shell
$ cd  /data/local/tmp/
$ export SHELL="/data/local/tmp/termux/usr/bin/bash"
$ export PREFIX="/data/local/tmp/termux/usr"
$ export PWD="/data/local/tmp/termux/home"
$ export EXTERNAL_STORAGE="/sdcard"
$ export LD_PRELOAD="/data/local/tmp/termux/usr/lib/libtermux-exec.so"
$ export HOME="/data/local/tmp/termux/home"
$ export LANG="en_US.UTF-8"
$ export TMPDIR="/data/local/tmp/termux/usr/tmp"
$ export ANDROID_DATA="/data"
$ export TERM="xterm-256color"
$ export SHLVL="1"
$ export ANDROID_ROOT="/system"
$ export LD_LIBRARY_PATH="/data/local/tmp/termux/usr/lib"
$ export PATH="/data/local/tmp/termux/usr/bin:/data/local/tmp/termux/usr/bin/applets"
$ export _="/data/local/tmp/termux/usr/bin/env"
$ whoami
shell
$ type pkg
pkg is /data/local/tmp/termux/usr/bin/pkg
$ ls -al /data/local/tmp/termux/usr/bin/pkg
-rwxrwxrwx 1 root root 5908 Sep  6 16:20 /data/local/tmp/termux/usr/bin/pkg
$ pkg
/system/bin/sh: /data/local/tmp/termux/usr/bin/pkg: Permission denied
```
It seems broken,
Any possibility to realize such feature?

**Comment by Grimler91** [comment]
Most termux programs and libraries contain hardcoded /data/data/com.termux/files/usr paths in their RPATH, and shebangs, config paths etc. Changing to a dynamic PREFIX path is a lot of work and not something we want to work on, see https://github.com/termux/termux-packages/issues/2902. 

Due to this it is not possible to use termux from other paths. You can always compile static binaries of programs you need, and run those from anywhere

**Comment by diyism** [comment]
Thanks, 
I found this, I think I can modify it before build bootstrap zip: https://github.com/termux/termux-packages/blob/master/scripts/properties.sh#L28

**Comment by Grimler91** [comment]
Yes, exactly, if you are building your own packages you can use any path you want

**Comment by dmdhrumilmistry** [comment]
will this method work if I want to use my sdcard as termux base directory?

**Comment by agnostic-apollo** [comment]
Slight correction, if you enable adoptable storage for an external sd card, it is reformatted to ext4/f2fs and you can use hack mentioned in https://github.com/termux/termux-app/discussions/2437#discussioncomment-5623823 for storing termux app data in adoptable storage.
