### ISSUE TITLE
Unsure if this is an issue

### ISSUE THREAD

**Issue by Quasic** [termux/termux-app#298]
I expect my carrier messed this up, as dns was slow for other urls, as well. I'm wondering if it falls back to an invalid url or something. Sorry if this is in the wrong place.

$ apt update
Ign:1 http://termux.net stable InRelease
Get:2 http://termux.net stable Release [1162 B]
Err:3 http://termux.net stable Release.gpg
  404  Not Found [IP: 104.18.36.234 80]
Reading package lists... Done
E: The repository 'http://termux.net stable Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by fornwall** [comment]
It's probably due to caching at the cloudflare (which Termux uses as a CDN) - can you try again and see if running `apt update` works?

**Comment by Quasic** [comment]
Thanks, I think it worked, but I got a circular trigger error with man. I think I've had a man error once or twice before, without any real problems. I haven't found any yet, this time.
[apt error 0.txt](https://github.com/termux/termux-app/files/911745/apt.error.0.txt)

**Comment by vishalbiswas** [comment]
@Quasic `apt install -f`

**Comment by fornwall** [comment]
@Quasic Does it work now if you perform an `apt update && apt upgrade` again?

**Comment by Quasic** [comment]
Yes, it works. Thanks!

**Comment by emahuni** [comment]
for posterity's sake: @vishalbiswas: the -f switch makes it work. I was having a somewhat similar problem.
