### ISSUE TITLE
[Bug]: I can install Termux from Google Play Store, but not from F-droid

### ISSUE THREAD

**Issue by Ddystopia** [termux/termux-app#2985]
### Problem description

I can install Termux from Google Play Store, but not from F-droid.

My phone is OnePlus Nord 2, F-droid says to me "No version with compatible signature", but when it is downloaded from Google Play Store, it has buttons uninstall/open and version.

Now it says, that I need to install it F-droid, not from Google Play Store. But I can't.

### Steps to reproduce the behavior.

Take OnePlus Nord 2, install F-droid and try to install Termux.

### What is the expected behavior?

To Termux be installed from F-droid 

### System information

* Termux application version: 0.101
* Android OS version: 11
* Device model: OnePlus Nord 2

**Comment by Damaj301damaj-lol** [comment]
You should remove the play store version beforehand

**Comment by Bolgrin** [comment]
Having the same issue. Termux started acting weird on me.  Tried to uninstall and start fresh, termux is unavailable on f-droid and git hub. (Maybe termux it's self is down,idk). Looked through all my files with zarchiver, looked at all my apps.  Termux is gone completely. I'll try and email the termux team. 

But dont download the one from google play store.  It no longer works in regards to installing much needed packages.

**Comment by Bolgrin** [comment]
Ok.  I commented before that it wasnt working for me as well and the proposed solutions do not work.   Figured it out for me at least .  Goto the termux github profile and click on the link for download on fdroid.   For some reason it worked.  

Also, the google play version is defunked and none of the packages will work or update.

**Comment by agnostic-apollo** [comment]
All your queries are already detailed at https://github.com/termux/termux-app#Installation and https://github.com/termux/termux-app#google-play-store-deprecated
