### ISSUE TITLE
[Bug]: Bell/Vibrate no longer works, and blank toasts show when switching tabs.

### ISSUE THREAD

**Issue by Zorbatron** [termux/termux-app#2991]
### Problem description

Actions producing the bell character no longer cause my device to vibrate. And when opening the app or switching tabs, the toasts at the top of the screen pop up, but they are blank.

### Steps to reproduce the behavior.

`bell-character = vibrate` is uncommented and `bell-character = ignore` is commented out.

I am unsure how to reproduce this as I have re-installed Termux, which did not fix the issue. On my older phone, both the vibrate and toasts work so it may be a device-specific issue.

### What is the expected behavior?

When pressing backspace with nothing on the terminal, the device should vibrate. When pressing TAB and there are multiple auto-completions, it should vibrate. When switching tabs, there should be a toast message showing the name of the tab. When opening the app, there should be a toast with "[1]" indicating you're in the 1st tab.

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

## Termux:API App Info

**APP_NAME**: `Termux:API`  
**PACKAGE_NAME**: `com.termux.api`  
**VERSION_NAME**: `0.50.1`  
**VERSION_CODE**: `51`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.19.239-gf0caf26d8587-ab8714951`  
**SDK_INT**: `33`  
**RELEASE**: `13`  
**ID**: `TP1A.220624.014`  
**DISPLAY**: `TP1A.220624.014`  
**INCREMENTAL**: `8819323`  
**SECURITY_PATCH**: `2022-08-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `Google`  
**BRAND**: `google`  
**MODEL**: `Pixel 5a`  
**PRODUCT**: `barbet`  
**BOARD**: `barbet`  
**HARDWARE**: `barbet`  
**DEVICE**: `barbet`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by Zorbatron** [comment]
Thank you for mentioning #2942. 

My other issue with the vibration is not fixed by restarting the app, and switching the bell character to audio does nothing either.

**Comment by Zorbatron** [comment]
I've found the issue for the vibration: I had "touch feedback" turned to 0 in the Vibration and haptics settings.

**Comment by fuyasu** [comment]
![Screenshot_20220929-042340.png](https://user-images.githubusercontent.com/72053270/192941253-a159ff7c-8ef4-4071-87c3-8be02ed5c956.png)

**Comment by fuyasu** [comment]
Help

**Comment by 2096779623** [comment]
> Help

https://wiki.termux.com/wiki/hacking
