### ISSUE TITLE
[Bug]: Network utils don't work in Android 13

### ISSUE THREAD

**Issue by dainslef** [termux/termux-app#2993]
### Problem description

Linux network utils like `net-tools` and `iproute2` don't work (or work correctly) in Android 13.
It seems Android 13 limits the network devices' permission?

### Steps to reproduce the behavior.
`ip` tool from `iproute2`:

```
$ ip address 
Cannot bind netlink socket: Permission denied
```

`ifconfig` tool from `net-tools` seems work, but lose some info:

```
$ ifconfig
Warning: cannot open /proc/net/dev (Permission denied). Limited output.
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.89.64.189  netmask 255.255.255.0  broadcast 10.89.64.255
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 3000  (UNSPEC)
```

### What is the expected behavior?

`ip address` and `ifconfig` show full network devices and IP addresses info correctly.
(In Android 12, these tools can work correctly).

### System information

* Termux application version: 0.118
* Android OS version: Stock Android 13
* Device model: Pixel 4a 5g

**Comment by Grimler91** [comment]
We probably can't "fix" this, only way to get full access to /proc and /sys would be to be rooted.

Best we could do is to add a termux-api command that returns (some of) the information through the [android api](https://developer.android.com/reference/android/net/Network)

**Comment by agnostic-apollo** [comment]
This is not an android 13 issue and exists since like android 10. The `proc_net` and `proc_net_tcp_udp` files are not accessible to `untrusted_app` domain but are allowed for `shell` (`adb`).

https://cs.android.com/android/_/android/platform/system/sepolicy/+/7a4af30b385d0a2a6c6093a6814492c4c18603b3

https://cs.android.com/android/_/android/platform/system/sepolicy/+/424517721cb71bc842cc37d82e8b61a6a4a6e00a

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r3:system/sepolicy/private/app.te;l=1

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r3:system/sepolicy/public/app.te;l=222

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r3:system/sepolicy/public/shell.te;l=103

Running `ls /proc/net/dev` results in following `avc` denial entry in `logcat`.

```
W/ls: type=1400 audit(0.0:150): avc: denied { getattr } for path="/proc/5585/net/dev" dev="proc" ino=4026532016 scontext=u:r:untrusted_app_27:s0:c157,c256,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.termux
```

```
adb shell ls -Z /proc/net
u:object_r:proc_net:s0         anycast6
u:object_r:proc_net:s0         arp
u:object_r:proc_net:s0         arp_tables_matches
u:object_r:proc_net:s0         arp_tables_names
u:object_r:proc_net:s0         arp_tables_targets
u:object_r:proc_net:s0         can
u:object_r:proc_net:s0         can-bcm
u:object_r:proc_net:s0         dev
u:object_r:proc_net:s0         dev_mcast
u:object_r:proc_net:s0         dev_snmp6
u:object_r:proc_net:s0         fib_trie
u:object_r:proc_net:s0         fib_triestat
u:object_r:proc_net:s0         hci
u:object_r:proc_net:s0         hidp
u:object_r:proc_net:s0         icmp
u:object_r:proc_net:s0         icmp6
u:object_r:proc_net:s0         if_inet6
u:object_r:proc_net:s0         igmp
u:object_r:proc_net:s0         igmp6
u:object_r:proc_net:s0         ip6_flowlabel
u:object_r:proc_net:s0         ip6_tables_matches
u:object_r:proc_net:s0         ip6_tables_names
u:object_r:proc_net:s0         ip6_tables_targets
u:object_r:proc_net:s0         ip6t_hashlimit
u:object_r:proc_net:s0         ip_tables_matches
u:object_r:proc_net:s0         ip_tables_names
u:object_r:proc_net:s0         ip_tables_targets
u:object_r:proc_net:s0         ipt_hashlimit
u:object_r:proc_net:s0         ipv6_route
u:object_r:proc_net:s0         l2cap
u:object_r:proc_net:s0         mcfilter
u:object_r:proc_net:s0         mcfilter6
u:object_r:proc_net:s0         netfilter
u:object_r:proc_net:s0         netlink
u:object_r:proc_net:s0         netstat
u:object_r:proc_net:s0         nf_conntrack
u:object_r:proc_net:s0         nf_conntrack_expect
u:object_r:proc_net:s0         packet
u:object_r:proc_net:s0         pfkey
u:object_r:proc_net:s0         pppol2tp
u:object_r:proc_net:s0         protocols
u:object_r:proc_net:s0         psched
u:object_r:proc_net:s0         ptype
u:object_r:proc_net:s0         raw
u:object_r:proc_net:s0         raw6
u:object_r:proc_net:s0         rfcomm
u:object_r:proc_net:s0         route
u:object_r:proc_net:s0         rt6_stats
u:object_r:proc_net:s0         rt_cache
u:object_r:proc_net:s0         sco
u:object_r:proc_net:s0         snmp
u:object_r:proc_net:s0         snmp6
u:object_r:proc_net:s0         sockstat
u:object_r:proc_net:s0         sockstat6
u:object_r:proc_net:s0         softnet_stat
u:object_r:proc_net:s0         stat
u:object_r:proc_net_tcp_udp:s0 tcp
u:object_r:proc_net_tcp_udp:s0 tcp6
u:object_r:proc_net_tcp_udp:s0 udp
u:object_r:proc_net_tcp_udp:s0 udp6
u:object_r:proc_net_tcp_udp:s0 udplite
u:object_r:proc_net_tcp_udp:s0 udplite6
u:object_r:proc_net:s0         unix
u:object_r:proc_net:s0         vlan
u:object_r:proc_net:s0         wireless
u:object_r:proc_net:s0         xfrm_stat
u:object_r:proc_net:s0         xt_quota
```

**Comment by dainslef** [comment]
> This is not an android 13 issue and exists since like android 10. The `proc_net` and `proc_net_tcp_udp` files are not accessible to `untrusted_app` domain but are allowed for `shell` (`adb`).
> 
> https://cs.android.com/android/_/android/platform/system/sepolicy/+/7a4af30b385d0a2a6c6093a6814492c4c18603b3
> 
> https://cs.android.com/android/_/android/platform/system/sepolicy/+/424517721cb71bc842cc37d82e8b61a6a4a6e00a
> 
> https://cs.android.com/android/platform/superproject/+/android-13.0.0_r3:system/sepolicy/private/app.te;l=1
> 
> https://cs.android.com/android/platform/superproject/+/android-13.0.0_r3:system/sepolicy/public/app.te;l=222
> 
> https://cs.android.com/android/platform/superproject/+/android-13.0.0_r3:system/sepolicy/public/shell.te;l=103
> 
> Running `ls /proc/net/dev` results in following `avc` denial entry in `logcat`.
> 
> ```
> W/ls: type=1400 audit(0.0:150): avc: denied { getattr } for path="/proc/5585/net/dev" dev="proc" ino=4026532016 scontext=u:r:untrusted_app_27:s0:c157,c256,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.termux
> ```
> 
> ```
> adb shell ls -Z /proc/net
> u:object_r:proc_net:s0         anycast6
> u:object_r:proc_net:s0         arp
> u:object_r:proc_net:s0         arp_tables_matches
> u:object_r:proc_net:s0         arp_tables_names
> u:object_r:proc_net:s0         arp_tables_targets
> u:object_r:proc_net:s0         can
> u:object_r:proc_net:s0         can-bcm
> u:object_r:proc_net:s0         dev
> u:object_r:proc_net:s0         dev_mcast
> u:object_r:proc_net:s0         dev_snmp6
> u:object_r:proc_net:s0         fib_trie
> u:object_r:proc_net:s0         fib_triestat
> u:object_r:proc_net:s0         hci
> u:object_r:proc_net:s0         hidp
> u:object_r:proc_net:s0         icmp
> u:object_r:proc_net:s0         icmp6
> u:object_r:proc_net:s0         if_inet6
> u:object_r:proc_net:s0         igmp
> u:object_r:proc_net:s0         igmp6
> u:object_r:proc_net:s0         ip6_flowlabel
> u:object_r:proc_net:s0         ip6_tables_matches
> u:object_r:proc_net:s0         ip6_tables_names
> u:object_r:proc_net:s0         ip6_tables_targets
> u:object_r:proc_net:s0         ip6t_hashlimit
> u:object_r:proc_net:s0         ip_tables_matches
> u:object_r:proc_net:s0         ip_tables_names
> u:object_r:proc_net:s0         ip_tables_targets
> u:object_r:proc_net:s0         ipt_hashlimit
> u:object_r:proc_net:s0         ipv6_route
> u:object_r:proc_net:s0         l2cap
> u:object_r:proc_net:s0         mcfilter
> u:object_r:proc_net:s0         mcfilter6
> u:object_r:proc_net:s0         netfilter
> u:object_r:proc_net:s0         netlink
> u:object_r:proc_net:s0         netstat
> u:object_r:proc_net:s0         nf_conntrack
> u:object_r:proc_net:s0         nf_conntrack_expect
> u:object_r:proc_net:s0         packet
> u:object_r:proc_net:s0         pfkey
> u:object_r:proc_net:s0         pppol2tp
> u:object_r:proc_net:s0         protocols
> u:object_r:proc_net:s0         psched
> u:object_r:proc_net:s0         ptype
> u:object_r:proc_net:s0         raw
> u:object_r:proc_net:s0         raw6
> u:object_r:proc_net:s0         rfcomm
> u:object_r:proc_net:s0         route
> u:object_r:proc_net:s0         rt6_stats
> u:object_r:proc_net:s0         rt_cache
> u:object_r:proc_net:s0         sco
> u:object_r:proc_net:s0         snmp
> u:object_r:proc_net:s0         snmp6
> u:object_r:proc_net:s0         sockstat
> u:object_r:proc_net:s0         sockstat6
> u:object_r:proc_net:s0         softnet_stat
> u:object_r:proc_net:s0         stat
> u:object_r:proc_net_tcp_udp:s0 tcp
> u:object_r:proc_net_tcp_udp:s0 tcp6
> u:object_r:proc_net_tcp_udp:s0 udp
> u:object_r:proc_net_tcp_udp:s0 udp6
> u:object_r:proc_net_tcp_udp:s0 udplite
> u:object_r:proc_net_tcp_udp:s0 udplite6
> u:object_r:proc_net:s0         unix
> u:object_r:proc_net:s0         vlan
> u:object_r:proc_net:s0         wireless
> u:object_r:proc_net:s0         xfrm_stat
> u:object_r:proc_net:s0         xt_quota
> ```

It seems `ip` tool doesn't need to read `/proc/net/dev`,  
I test `ip address` in Android 12, it can work correctly, the `Cannot bind netlink socket: Permission denied` info is only shown in Android 13.

**Comment by Mrzaman7852** [comment]
I couldn't hack any Wi-fi router. Plz 🙏 help me

**Comment by chebro** [comment]
facing the same issue on my pixel 4a device running android 13, i could run the `ip` command just find on android 12. only started facing the issue after upgrading to 13.

**Comment by agnostic-apollo** [comment]
`ip address` triggers `W/ip: type=1400 audit(0.0:616): avc: denied { bind } for scontext=u:r:untrusted_app_27:s0:c157,c256,c512,c768 tcontext=u:r:untrusted_app_27:s0:c157,c256,c512,c768 tclass=netlink_route_socket permissive=0 app=com.termux`

Access revoked in android 13.

>Enforce RTM_GETLINK restrictions on all apps

>Extend existing restrictions targeting only apps with API level >= 30 to all apps.

https://cs.android.com/android/_/android/platform/system/sepolicy/+/a4433b4397b88fc9878506aa3ccfa8ada171345b

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r3:system/sepolicy/private/net.te;l=6

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r3:system/sepolicy/private/app_neverallows.te;l=128

**Comment by etckra** [comment]
Are there any plans to fix this because Nethunter ain't working properly and I really want it to.

**Comment by l29ah** [comment]
Disabling SELinux completely creates a security risk.

>  I tried on rooted Android 14 with the same restriction successfully.

Have you succeeded without disabling SELinux on 14?

**Comment by agnostic-apollo** [comment]
Running `su -c 'supolicy --live "allow untrusted_app_27 untrusted_app_27 netlink_route_socket bind"'` should work without having to completely disable selinux.

**Comment by freebrowser1** [comment]
> Running `su -c 'supolicy --live "allow untrusted_app_27 untrusted_app_27 netlink_route_socket bind"'` should work without having to completely disable selinux.

Is this number '27' in 'untrusted_app_27'  a hardcoded value or should it be the ID of the app u0_aXXX, (in this case for the Termux app) ?

**Comment by agnostic-apollo** [comment]
- https://github.com/agnostic-apollo/Android-Docs/blob/master/site/pages/en/projects/docs/os/selinux/context-types.md#untrusted_app_27
- https://github.com/termux/termux-app/blob/755b752a95a0d1c15662713b38a7476b746a1e95/gradle.properties#L19

**Comment by Albertocarrillo1** [comment]
nmap google.com  --unprivileged

**Comment by Mafggj** [comment]
> ### Problem description
> Linux network utils like `net-tools` and `iproute2` don't work (or work correctly) in Android 13. It seems Android 13 limits the network devices' permission?
> 
> ### Steps to reproduce the behavior.
> `ip` tool from `iproute2`:
> 
> ```
> $ ip address 
> Cannot bind netlink socket: Permission denied
> ```
> 
> `ifconfig` tool from `net-tools` seems work, but lose some info:
> 
> ```
> $ ifconfig
> Warning: cannot open /proc/net/dev (Permission denied). Limited output.
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
> 
> wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.89.64.189  netmask 255.255.255.0  broadcast 10.89.64.255
>         unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 3000  (UNSPEC)
> ```
> 
> ### What is the expected behavior?
> `ip address` and `ifconfig` show full network devices and IP addresses info correctly. (In Android 12, these tools can work correctly).
> 
> ### System information
> * Termux application version: 0.118
> * Android OS version: Stock Android 13
> * Device model: Pixel 4a 5g
