### ISSUE TITLE
[Bug]: vim as root fails

### ISSUE THREAD

**Issue by mrturcot** [termux/termux-app#2999]
### Problem description

Cannot launch vim as root. Vim is installed through magisk module https://github.com/mirsella/magisk-vim-ndk

I've tested in 3 different terminal emulators and running vim as "su" root works fine. 

Message after executing vim command is "illegal instruction"

### Steps to reproduce the behavior.

Open terminal
Type "su" to gain root privileges
Execute command "vim"

### What is the expected behavior?

vim should open 

### System information

* Termux application version: 0.118.0
* Android OS version: lineage 19.1 / Android 12.1
* Device model: Pixel 5

**Comment by agnostic-apollo** [comment]
We don't provide support for third party tools not provided by termux. Termux runs a specialized environment due to which you may be getting errors. Ask in their repo.

And you can use termux provided `vim` package by installing it with `pkg install vim`

**Comment by mrturcot** [comment]
Ok thanks, I have installed vim through the pkg manager but doesn't work as root? Am I missing something? Can I use termux vim as su?

**Comment by mrturcot** [comment]
> We don't provide support for third party tools not provided by termux. Termux runs a specialized environment due to which you may be getting errors. Ask in their repo.
> 
> And you can use termux provided `vim` package by installing it with `pkg install vim`

Ok thanks, I have installed vim through the pkg manager but doesn't work as root? Am I missing something? Can I use termux vim as su?

**Comment by agnostic-apollo** [comment]
Install `sudo` from https://github.com/agnostic-apollo/sudo and then run `sudo su` and then run `vim` and it should work. Note that if you mess up file permissions/ownership/selinux context of termux files while modifying them with root, you are responsible for fixing stuff yourself and we won't provide help for it other than providing link to https://github.com/termux/termux-app/issues/2080#issuecomment-846575028

There is also `tsu` package as alternate to my `sudo` script but it often has issues, use what you think is best.

**Comment by mrturcot** [comment]
You guys rock, thanks for the help and quick replies. Termux is an awesome project. Appreciate it!!

**Comment by agnostic-apollo** [comment]
You are welcome.
