### ISSUE TITLE
apt update invalid message error

### ISSUE THREAD

**Issue by jlefman** [termux/termux-app#30]
Hi. I am receiving this error below on apt update. dpkg works without problems.

```
$ apt update
0% [Working]res_send: select: Connection refused
Hit:1 http://apt.termux.com stable InRelease
Reading package lists... Done
E: Invalid message from method http: ;; new DG socket
102 Status
URI: http://apt.termux.com/dists/stable/InRelease
Message: Connecting to apt.termux.com
```

Not sure if this is a local configuration issue or something on the repo side.

**Comment by fornwall** [comment]
It works for me. Could you try accessing http://apt.termux.com/dists/stable/InRelease in the browser on the device, and try running

    wget http://apt.termux.com/dists/stable/InRelease

Could you also paste the output of `uname -a` and `apt --version`?

**Comment by fornwall** [comment]
Also, which Android device do you run? Which Android version? Running a custom ROM?

**Comment by fornwall** [comment]
I'm closing this issue in favour of https://github.com/termux/termux-packages/issues/99 which tracks the same issue! You're very welcome to enter the information about Android device, version and ROM there!

**Comment by jlefman** [comment]
Thanks. Will address there.
