### ISSUE TITLE
[Bug]: termux conflicts with application installer

### ISSUE THREAD

**Issue by minhdanlc124** [termux/termux-app#3001]
### Problem description

When I install apk file the app installer is conflicted with termux and doesn't show the app settings panel
i use gsi rom, the device is not root and i have tried android 10.11 both i have not tried higher android version

### Steps to reproduce the behavior.

.

### System information

* Termux application version: latest fdroid
* Android OS version: 10 and 11
* Device model: whyred

**Comment by agnostic-apollo** [comment]
>uninstall any and all existing Termux or its plugin app APKs

https://github.com/termux/termux-app#Installation
