### ISSUE TITLE
[Bug]: Backspace is deleting a lot of content instead of one character

### ISSUE THREAD

**Issue by bbronisz** [termux/termux-app#3007]
### Problem description

Sometimes, but lately more often, when I start the Termux and use backspace on the keyboard (I use SwiftKey) it is deleting a lot of characters. It doesn't look like it deletes until previous word or anything as using it with the same text will result in different number of characters deleted. If it is short input then everything is deleted. Additionally I've noticed that it constantly vibrates, as if I'm using it on empty input.
And then after some restarts, it fixes and stops behaving like this. But unfortunately I haven't found the steps necessary to make it fix itself.
Fortunately I've found a workaround of adding additional buttons to xtra-keys in configuration (BKSP and DEL) so now I'll be trying to avoid using the physical button. However it's a little hard as I use it everywhere else. And there is not "undo" to such action and often a lot of input is lost.

### Steps to reproduce the behavior.

Start Termux after some time since last using it (day or few, I don't have the exact Steps to reproduce).
Use the keyboard's backspace and notice that a lot of input is deleted and phone vibrates.

### What is the expected behavior?

Physical backspace on the keyboard should delete only one character at a time.

### System information

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: Samsung S21 SM-G991B

**Comment by agnostic-apollo** [comment]
If keyboard app is sending delete events, termux is going to process them and vibration will occur when nothing left to delete.

Swiftkey apparently deletes entire word on long press of delete button which is likely what's causing the issue. You should be able to disable it from keyboard app's gesture settings.

You can enable terminal view key logging and check `TerminalView` log enteries for delete events.

https://github.com/termux/termux-app#debugging

Closing since likely a keyboard issue but can be opened if given proof of termux issue.

**Comment by bbronisz** [comment]
Thanks for quick response.
I wouldn't report this if I would get similar behavior in other apps. But I'll try to gather more information.
Just a question about the debugging: it mentions there to set `LogLevel` to `Debug` in `Termux` app settings. I don't understand where exactly? I've found today that there is `termux.properties` file and it is a configuration but it doesn't mention logging or debug. Where/how should I get to those app settings?

**Comment by agnostic-apollo** [comment]
> I wouldn't report this if I would get similar behavior in other apps. But I'll try to gather more information.

You can try `enforce-char-based-input=true`

https://wiki.termux.com/wiki/Terminal_Settings#Workaround_issues_with_some_keyboards

> `LogLevel` to `Debug` in `Termux` app settings. I don't understand where exactly?

Left drawer by swiping towards right from left edge of terminal or long hold terminal. I will update the docs.

**Comment by joneldiablo** [comment]
Backspace delete all command instead delete one char!
