### ISSUE TITLE
[Feature]: how to user termux in samsung maximum power saving mode?

### ISSUE THREAD

**Issue by olav2021** [termux/termux-app#3008]
### Feature description

Samsung has a very energyeffective power saving mode, only that just a couple of apps are available on a nonrooted device.

It looks like rooted devices may convert apps into system apps and use these in power saving mode.

My samsung is not rooted because of knox.

Any suggestions here on how to make a system termux app?

### Additional information

samsung maximum power saver

**Comment by agnostic-apollo** [comment]
You can't convert apps to system apps without root, that would be a security risk and immediately fixed by google.

Samsung is the worst vendor for battery optimizations. You can find some info at https://dontkillmyapp.com

Closing since not a termux issue.
