### ISSUE TITLE
[Bug]: Failed to fetch { 

### ISSUE THREAD

**Issue by GH05T-HUNTER5** [termux/termux-app#3009]
### Problem description

Picking mirror: https://deb.kcubeterm.me/termux-main
Get:1 https://deb.kcubeterm.me/termux-main stable InRelease [507 B]
Err:1 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.

### Steps to reproduce the behavior.

Change Termux Version 

### What is the expected behavior?

Proper package installation

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
> N: Use termux-change-repo for switching to a mirror.

Change to another mirror and upgrade all packages with `pkg upgrade`.
