### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Collin1234564** [termux/termux-app#3014]
### Problem description

Connection failed.
![Capture](https://user-images.githubusercontent.com/114713002/193173597-abb79f58-d458-4405-9230-9122ca7b6c36.JPG)

### Steps to reproduce the behavior.

Help with last step

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by SunPodder** [comment]
Please provide enough details. We can't read your mind. What steps you are following? It's most likely you didn't start the vnc server. Start is with `vncserver`
