### ISSUE TITLE
[Feature]: Material You Dynamic Icon

### ISSUE THREAD

**Issue by ph00lt0** [termux/termux-app#3017]
### Feature description

Please add support for a Material You Dynamic Icon.

### Additional information

-

**Comment by Anonymous1231-dev** [comment]
i think you should ask the icon pack creator , not termux.

**Comment by Anonymous1231-dev** [comment]
@agnostic-apollo @Grimler91 what do you think ?

**Comment by agnostic-apollo** [comment]
Can be done in future, not a priority for me personally, lot of other things to do. A pull request can be sent.

**Comment by boehs** [comment]
#2994 i believe

**Comment by Haiz14** [comment]
The is solved since monochrome PR is merged. You should close the issue

**Comment by Haiz14** [comment]
Sorry

**Comment by Ale0098** [comment]
Martineza8779@gmail.com
