### ISSUE TITLE
Termux bug

### ISSUE THREAD

**Issue by Ducky-Hax** [termux/termux-app#3018]
### Problem description

The first time i used Termux it worked perfectly,the next time when i wrote "apt update" it wont work.

### Steps to reproduce the behavior.

Please fix it
apt update

### What is the expected behavior?

I dont know

### System information

* Termux application version: last one
* Android OS version: 10
* Device model: Xiaomi

**Comment by 2096779623** [comment]
Please provide detailed screenshots or logs and `termux-info` .

**Comment by Anonymous2716** [comment]
@Ducky-Hax I think for this kind of issue termux has a reddit community . https://reddit.com/r/termux .
