### ISSUE TITLE
Integrate Termux Core in another App?

### ISSUE THREAD

**Issue by RicardoFR** [termux/termux-app#302]
Hi, 

I'm thinking the posibility of integrate Termux "Core" in another Android App Open Source project to use his powerfull capabilities , its posible?

Thanks un advance !

**Comment by fornwall** [comment]
Hi! Do you mean the terminal emulation part or the packages?

**Comment by RicardoFR** [comment]
Hi!
Imagine an App where you can execute commands and install packages, but invoking commands internally, for example wget to create an app to download files (for example), or an app to extract info from htop to show notifications to the user.

Thanks again !

**Comment by vishalbiswas** [comment]
I think he means that he wants to be able to get a shell or execute commands from a separate Android app.

**Comment by RicardoFR** [comment]
The idea is use Termux Shell in any app (maybe like a library?) For example :

Termux.execute("packages install htop", callback);
and then
Termux.execute("htop", callback);

Where callback give the command execution result.

I hope to have explained clearly, thank you very much for the help!

**Comment by mrjainvimal** [comment]
Hey Guys,

Any Success?

**Comment by RicardoFR** [comment]
seems not :(

**Comment by v0idst4r** [comment]
Basically if you want to use termux commands in any other shell application, you'd have to change the permissions of everything in the /data/data/com.termux folder. That is, unless you have root.

**Comment by DEVoytas** [comment]
I think that to make it work, every app that wants to use "termux core" would need to have separate private termux environment, so it doesn't interfere with main termux instance or other apps that use it.

**Comment by v0idst4r** [comment]
What other apps will use it if other apps would need a separate environment?

**Comment by Alexander--** [comment]
This can be accomplished by using Android Binder IPC to interact between client app and Termux process. Basically, the client app would have to call into AIDL interface, provided by Termux, and Termux would perform actions (running commands etc.) on it's behalf. The client app would be able to receive InputStream/OutputStream of executed command (by passing file descriptors via Binder) and use Termux AIDL API to control the command (such as send signals to it).

@fornwall I can come up with PR if you are interested in implementing something like that.

**Comment by EdwardIrby** [comment]
That would be pretty useful if one could user it in conjunction with a port of vscode or Monaco editor on a Chromebook.

**Comment by sdrausty** [comment]
Have you heard of this https://github.com/sdrausty/buildAPKs https://sdrausty.github.io/buildAPKs/
It builds applications in Termux.  Is this what you are looking for?  Seeking?

**Comment by EdwardIrby** [comment]
No not what I was thinking. Though that would be useful as I've switched all my personal dev work to the new pixelbook. 

I actually like ChromeOS except for the lack of a modern dev editor like atom or vscdoe. I was considering trying to fork one of these to android. Chrome Apps seem to not be getting any more love so I figure I'd try and build vscode for the android platform, so it can be used on Chromebooks that now support Android apps. 

I was thinking about how vscode uses hterm for it's integrated terminal and it be really useful if I could build it on top of or wrap it around termux. This would  allowing me to use termux via the integrated terminal and be able to manipulate shared storage and have all the linux cli goodness I use when doing dev work. I could do all of this without having to put the pixelbook into dev mode or run crouton or chrombrew. 

I figure a app like this would be extremely useful not just to me but also to students who's only device might a school issued chromebook. VI, Nano, Micro and the rest are useful and I use them on the reg but I still think there's something about a nice GUI editor that just helps with a fast workflow. 

I'm open to working with anyone on this if there's interest.

**Comment by Alexander--** [comment]
@EdwardIrby in case you weren't aware, such library already exists (but for different terminal emulator): https://github.com/jackpal/Android-Terminal-Emulator/tree/master/emulatorview.

**Comment by linamgr** [comment]
@Alexander-- @fornwall  do you have some advances for this issue? I'm interested in execute python  commands in termux from an android app. How I could do that? thnks.

**Comment by Alexander--** [comment]
@linamgr you'd need to modify Termux app for that. Or better yet, forget about Termux and integrate a terminal emulator library in your app (such as ATE library I linked above).

**Comment by linamgr** [comment]
@Alexander-- it seems a good option. Do you know a reliable source where I can find more information about ATE executing python scripts? Thnks.

**Comment by Alexander--** [comment]
@linamgr sorry, I don't have any. You might have better luck asking for advice on thematic forums, instead of this issue.

**Comment by markosjal** [comment]
what i want to be able to do is have an android app execute
streamlink http://tvcatchup.com/watch/itv --stream-url --default-stream best

then the output would pipe to the android app for playback:
https://manifest.googlevideo.com/api/manifest/hls_playlist/id/Ga3maNZ0x0w.4/itag/301/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D299/hls_chunk_host/r3---sn-hxb5j5cax-cwme.googlevideo.com/gcr/mx/ei/LoiQW63nIomjwQGqk6zICQ/playlist_type/DVR/initcwndbps/5350/mm/32/mn/sn-hxb5j5cax-cwme/ms/lv/mv/m/pl/20/dover/11/keepalive/yes/mt/1536198562/ip/17.23.14.85/ipbits/0/expire/1536220302/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,gcr,ei,playlist_type,initcwndbps,mm,mn,ms,mv,pl/signature/45C3CB1F54D74AD63BA654BA2F8B980AAF945AFE.05E86A2C0049CB5A56D236C4CB51C5BBE84DB685/key/dg_yt0/playlist/index.m3u8

Maybe there is a different way to do this? The links are only good for a few minutes it seems. So the request needs to be made at the moment it is played back.

**Comment by xeffyr** [comment]
Seems related to https://github.com/termux/termux-app/issues/804, so closing to prevent duplicate (or similar) issues.
