### ISSUE TITLE
[Bug]: neofetch shows exception

### ISSUE THREAD

**Issue by Sycher** [termux/termux-app#3023]
### Problem description

As shown in the figure：
![Screenshot_20221003_115516_com termux_edit_129844387515603](https://user-images.githubusercontent.com/111743479/193498977-f096e2a0-6925-47a9-8687-a67e04008762.jpg)

### Steps to reproduce the behavior.

pkg install neofetch

neofetch

### What is the expected behavior?

None

### System information

Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=16049
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0                                                           Packages CPU architecture:
aarch64                                                                          Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.29.3
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Fri Mar 18 17:15:34 CST 2022 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
EML-AL00

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/issues/12212
