### ISSUE TITLE
[Bug]: Pasting not working Android 13

### ISSUE THREAD

**Issue by PartyWumpus** [termux/termux-app#3025]
### Problem description

(stock android 13)
both `alt` + `ctrl`+ `v` and the key 'PASTE' don't work (first one does nothing, second one just types the word 'PASTE')

looking through issue #1891 it looks like both of these should be working?

(I am aware you can just hold to select and then paste)

### Steps to reproduce the behavior.

simply press Ctrl, alt and V and watch it do nothing

edit .termux/termux.properties and add PASTE as a key, press it and it just types PASTE

### What is the expected behavior?

both of those should paste the clipboard 

### System information

* Termux application version: most recent from playstore (seems to be 0.101?)
* Android OS version: android 13
* Device model: pixel 6a

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#google-play-store-deprecated

https://github.com/termux/termux-app#installation

**Comment by PartyWumpus** [comment]
> I'll just roast them so bad that I get banned from Github or something... 

@cujoXavier I'm sorry for not noticing the *zero mention* of an outdated version anywhere on the play store. I should have noticed the github one to be fair, but come on dude, it's not the worst thing in the world. 

Of course I understand this is an small open source project being run by (unpaid, volunteer) hardworking devs. That's why I try to report bugs when I find them in OS projects, because I know the devs really care about what they make and want the bugs fixed. This time, sure, I messed up and missed the obvious warning, and it wasted precious moments of a contributor's time. But come on, mistakes happen to the best of us.

(really though, you don't have to be so rude/angry for a mistake as small as this one, save your energy)

**Comment by agnostic-apollo** [comment]
> _zero mention_ of an outdated version anywhere on the play store.

It's mentioned at the top in app description.

**Comment by PartyWumpus** [comment]
> It's mentioned at the top in app description.

Woops, I didn't even realize that description could be expanded. That was pretty stupid of me to miss *2* error warnings explaining exactly what was wrong...
Sorry. (also sorry for wasting your time again by sending another mostly pointless message)

**Comment by agnostic-apollo** [comment]
Apology accepted.
