### ISSUE TITLE
[Bug]: Forced extra keys vibration can't be disabled

### ISSUE THREAD

**Issue by MrCatEsq** [termux/termux-app#3029]
### Problem description

Every time I press an extra key (ctrl, tab, etc, including not only "special" keys but also "pure" symbols like "-" or "="; no matter it was default config for extra keys or not) in Termux my phone vibrates. Even if the phone in the silent mode or/and keyboard vibration (gboard) turned off. 

There is no vibration feedback if I long press a key (pressing key down and keeping in this state) but only when I press them in default way (fast press down and press up like when I write this report).

May be related to https://github.com/termux/termux-app/issues/1183 but in my case there is no haptic (tactile) feedback nor simple vibration enabled in keyboard or system settings.

May be answered earlier in https://www.reddit.com/r/termux/comments/bei0jw/how_can_i_disable_vibration_in_termux/
but in my version (0.118.0 from f-droid) ignoring bell symbols (`bell-character = ignore` in `~/.termux/termux.properies`) doesn't take an effect to keyboard vibration while bell vibrations disabled successfully (`echo -e '\a'` is silent after the setting changed). Besides, I think it will be a dirty way to disable keyboard vibration even if it will work.

Is it must to be possible to disable extra key vibrations now? If it is impossible and works as expected please convert this bug issue to feature request to add a way to disable extra key vibrations.

### Steps to reproduce the behavior.

Enable silent mode on your mobile phone.
Open Termux app.
Try to press any extra key or key combination when extra key used.

### What is the expected behavior?

Extra key doesn't play any beep or vibration especially in the phone silent mode.

### System information

* Termux application version: Termux 0.118.0, .apk from f-droid
* Android OS version: MIUI Global 12.0.4 stable (based on Android 10)
* Device model: Xiaomi Mi 9 Lite
* Screen keyboard: Gboard [11.9.06.452014594](tel:11906452014594)-release-arm64-v8a

**Comment by agnostic-apollo** [comment]
Extra keys do not themselves produce any sound or vibration. Likely need to disable `Android Settings` -> `Sound` -> `Advanced` -> `Touch vibration`

**Comment by trygveaa** [comment]
@agnostic-apollo: Hm? The extra keys do vibrate on click by default: https://github.com/termux/termux-app/blob/cff6cff609143d7441b42dad20c058ca26543247/termux-shared/src/main/java/com/termux/shared/termux/extrakeys/ExtraKeysView.java#L507

It should follow the system though. If I disable system haptics in the Android settings, they stop vibrating on my phone.

**Comment by agnostic-apollo** [comment]
Ah, right, sorry, it will vibrate if system haptic feedback is enabled, which is usually enabled by default. Maybe a property like `night-mode` can be added with the values `system`/`true`/`false`.

**Comment by amaramth** [comment]
Some system haptics is good, but my soft keyboard doesn't vibrate, just the back/home/apps keys that I can think of. It should be possible to have termux extra keys not vibrate while keeping the home key as is.
