### ISSUE TITLE
Write access to usb pen drive

### ISSUE THREAD

**Issue by alexandre1985** [termux/termux-app#303]
I have termux on my android tv box and I want to have write access to my plugged-in usb pen. I have tried running `termux-setup-storage` command and it created $HOME/storage but this directory doesn't have a path to my usb drive.  
My usb drive is on /storage/udisk0 and I don't have write access in this directory using Termux.
Not detecting /storage/udisk0/ is this a bug of `termux-setup-storage` or is there another way to have write access to /storage/udisk0/ ? 
Because on the termux help, regarding `termux-setup-storage`, it says that:

> The contents of the created $HOME/storage folder are symlinks to different storage folders:
(...)
~/storage/external
Symlink to a Termux-private folder on external storage (only if external storage is available).

but I have a usb plugged-in and when I run `termux-setup-storage` it doesn't create the ~/storage/external directory.
I would like to know how can I have write access to my USB pen as a normal user without being root.

**Comment by alexandre1985** [comment]
Here is the [solution](http://www.cnx-software.com/2012/08/26/how-to-allow-apps-to-write-files-to-usb-mass-storage-devices-in-android/)

**Comment by michael-ts** [comment]
> Here is the [solution](http://www.cnx-software.com/2012/08/26/how-to-allow-apps-to-write-files-to-usb-mass-storage-devices-in-android/)

Uh... that solution requires root, no?  And if one's phone is not rootable, what is the solution then?

**Comment by alexandre1985** [comment]
It probably did. I no longer have this box. It was 2017...

**Comment by pavaneesh143** [comment]
How to formate usb pendirve in termux
