### ISSUE TITLE
[Bug]: Extra arrow keys not working in Emacs

### ISSUE THREAD

**Issue by yusi1** [termux/termux-app#3030]
### Problem description

I have an issue with Termux's extra keyboard, where the arrow keys don't work in Emacs, but work in the console.

When pressing the arrow keys in Emacs, it doesn't move point anywhere, instead random letters are shown on the screen rather than the arrow keys acting like arrow keys.

It's very annoying behaviour and makes it very cumbersome to move the point in Emacs (having to constantly press `ctrl` + `n/p` is annoying if you want to quickly move the point).

### Steps to reproduce the behavior.

- Use extra keyboard in Termux with arrow keys.
- Open Emacs with `emacs` from Termux CLI.
- Arrow keys return letters instead  of actually acting like arrow keys.

https://user-images.githubusercontent.com/82241382/194542898-a4350e66-d64b-46a9-a37e-f2fdf884b2ae.mp4

### What is the expected behavior?

Arrow keys work like arrow keys inside Emacs.

### System information

* Termux application version: 0.118.0 (FDroid)
* Android OS version: 12
* Device model: Samsung Galaxy A52s 5G

**Comment by yusi1** [comment]
Found this guide which shows how to use arrow keys inside Emacs on Termux: https://defkey.com/termux-shortcuts

**Comment by yusi1** [comment]
> 

Guide didn't work, arrow keys still don't work inside Emacs with `Volume Up + W/A/S/D`.

**Comment by Grimler91** [comment]
I can't reproduce the issue. What do you have in your ~/.emacs? Does the behaviour change if you start emacs with `emacs --no-init-file`?

**Comment by yusi1** [comment]
> I can't reproduce the issue. What do you have in your ~/.emacs? Does the behaviour change if you start emacs with `emacs --no-init-file`?

Yeah without loading my config in the arrow keys work now.

It turns out this bit in my config was somehow interfering with Termux's arrow keys, I commented this bit out and arrow keys work with my config now:
```

;; ;; Quicker keybinds
;; (progn
;;   (gkey "M-)" 'delete-window)
;;   (gkey "M-!" 'delete-other-windows)
;;   (gkey "M-\"" 'split-window-below)
;;   (gkey "M-£" 'split-window-right)
;;   (gkey "M-O" 'other-window)
;;   (gkey "M-B" 'consult-buffer)
;;   (gkey "M-F" 'find-file)
;;   (gkey "M-K" 'kill-this-buffer)
;;   (gkey "M-S" 'save-buffer)
;;   (gkey "M-:" 'other-window-kill-buffer)
;;   (gkey "M-{" 'diff-hl-previous-hunk)
;;   (gkey "M-}" 'diff-hl-next-hunk))
```

Thanks for the help! @Grimler91
