### ISSUE TITLE
[Bug]: T9 keyboard input not working properly | CAT S22

### ISSUE THREAD

**Issue by jconnolly837** [termux/termux-app#3035]
### Problem description

Termux will only recognize numbers on a T9 keyboard. Normal T9 features like predictive typing, or even the ability to type letters at all, doesn't work. All other apps, such as Markor, input text properly as shown in the first half of the video. The keyboard icon in Android's top bar shows that this is recognized as a text input field. Pressing the # key normally lets me cycle through T9 and other keyboard modes. But in Termux, it literally just types #. 
[http://lloydlynx.ddns.net/T9KeyboardNotWorkingTermux.mp4](http://lloydlynx.ddns.net/T9KeyboardNotWorkingTermux.mp4)

### Steps to reproduce the behavior.

1. Use a Cat S22 with the T9 keyboard
2. Use Termux from F-Droid
3. Only be able to input numbers

### What is the expected behavior?

I should be able to input text like any other app. Letters, symbols, numbers, whole sentence backspace, everything that this keyboard offers I should be able to input. 

### System information

* Termux application version: 0.118.0
* Android OS version: 11 Go Edition
* Device model: CAT S22

**Comment by agnostic-apollo** [comment]
https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View

https://wiki.termux.com/wiki/Terminal_Settings#Workaround_issues_with_some_keyboards
