### ISSUE TITLE
[Bug]: Dark mode ruins colors

### ISSUE THREAD

**Issue by pseudoparenchymatous** [termux/termux-app#3036]
### Problem description

When I enable dark mode in my phone, the terminal colors change and it ruins my color scheme.

This is what it looks like without dark mode 😍
![IMG_20221010_215455](https://user-images.githubusercontent.com/105337186/194887969-968bf5fc-dd96-4cab-b317-61cea9254c2c.jpg)

Enabling dark mode results to this 🤮
![IMG_20221010_215404](https://user-images.githubusercontent.com/105337186/194888213-dd8ad84f-d0c7-4508-ae19-4591829c892f.jpg)

How to remain in dark mode whilst keeping my color scheme? Setting `use-black-ui=true` or `use-black-ui=false`  in `$HOME/.termux/termux-properties` makes no difference. 

### Steps to reproduce the behavior.

Enable dark mode. 

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: Redmi Note 8

**Comment by TomJo2000** [comment]
You should be able to turn off Dark Mode on a per App basis in the device settings.

For me it's under `Settings > Display > Color scheme > More Dark Mode options`.
There should be a setting to stop Android from automatically messing with colors, and if that's not enough you can toggle Dark Mode on a per App basis.
![IMG_20221010_164711.jpg](https://user-images.githubusercontent.com/43716232/194893414-ccd1a947-428e-4ff3-8371-a2cff6a62823.jpg)

**Comment by photographep951-jpg** [comment]
https://www.facebook.com/Ami.Sagor.Das
free fire pkg bk
