### ISSUE TITLE
[Bug]: Not working Kitty in Timg

### ISSUE THREAD

**Issue by bropines** [termux/termux-app#3049]
### Problem description

In a recent update, kitty support was added to actions. Initially everything worked, but then the console started to output this. In the timg topic, I was sent here. 
https://github.com/hzeller/timg/issues/91
![photo_2022-10-18_03-16-11](https://user-images.githubusercontent.com/57861007/196294050-e8b45480-82da-4bde-9961-b6c50c66e3b7.jpg)

### Steps to reproduce the behavior.

1. Open termux
2. Install timg
3. Run timg with the -pk parameter

### System information

* Termux application version: v. 0.118.0+20dee0e
* Android OS version: 11
* Device model: Redmi Note 8T

**Comment by rihaq** [comment]
Kitty not supported

**Comment by bropines** [comment]
Oh, sorry, iTerm2. The thing is that on the PC, the same program easily works with kitty and iTerm2. This just says a bunch of characters

**Comment by trygveaa** [comment]
> Run timg with the -pk parameter
> Oh, sorry, iTerm2. The thing is that on the PC, the same program easily works with kitty and iTerm2. This just says a bunch of characters. I think the iTerm2 protocol works differently in Termux than in Timg.

The `-pk` option is for the kitty protocol according to the readme. For iTerm2 protocol, you should use `-pi`.

**Comment by bropines** [comment]
> 

I figured it out and just double-checked it. The result is the same. It outputs a dumb, incoherent set of characters
