### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TukangM** [termux/termux-app#3059]
### Problem description

i want reinstall termux and here screenshot after delete all data's
after reinstall / remove all data termux not installing bootstraps
![image](https://user-images.githubusercontent.com/91467886/198032845-452d588e-a805-4ab6-863b-f9310f1a8e5c.png)

### Steps to reproduce the behavior.

-

### What is the expected behavior?

cannot start termux environment

### System information

* Termux application version: lastest
* Android OS version: 10 (Custom ROM Nusantara Project)
* Device model: Mi-4C (on screenshoot is faked device models from audio mod DTS from asus)
![image](https://user-images.githubusercontent.com/91467886/198033426-19d7a087-29a2-49a3-ac9c-a0af66cffccb.png)

**Comment by TukangM** [comment]
i have root access... maybe root helping?

**Comment by Grimler91** [comment]
Don't really understand what you are asking, maybe you need to update your PATH to include /data/data/com.termux/files/usr/bin/, or maybe that folder has already been deleted, and in that case you can use /system/bin/rm instead, at least as root.

**Comment by Grimler91** [comment]
If bootstraps aren't shared then please provide the error that occurs when bootstrap installation fails

**Comment by TukangM** [comment]
> If bootstraps aren't shared then please provide the error that occurs when bootstrap installation fails

no. the bootstrap after delete data or reinstalling. no loading "Installing Bootstap" and then termux will become like this 
![image](https://user-images.githubusercontent.com/91467886/198064876-72e32238-d783-4c98-a276-181df6926cae.png)

**Comment by TukangM** [comment]
closed - fixed by mod in discord :)

**Comment by TukangM** [comment]
update: still not fixed
trying restorecon /data/data/com.termux -R (as root) and get this result
![image](https://user-images.githubusercontent.com/91467886/198752250-0fd5abe5-4004-45c8-98af-52974203e77d.png)
symlink broken

**Comment by agnostic-apollo** [comment]
Run from failsafe session `path=/data/data/com.termux; su -c "rm-rf '$path' && mkdir -p '$path' && chown $(id -u):$(id -u) -R '$path' && chmod -R 0700 '$path' && restorecon -v '$path'"` and then force stop and restart termux.

https://github.com/termux/termux-app/issues/2080#issuecomment-846575028

**Comment by TukangM** [comment]
> Run from failsafe session `path=/data/data/com.termux; su -c "rm-rf '$path' && mkdir -p '$path' && chown $(id -u):$(id -u) -R '$path' && chmod -R 0700 '$path' && restorecon -v '$path'"` and then force stop and restart termux.
> 
> [#2080 (comment)](https://github.com/termux/termux-app/issues/2080#issuecomment-846575028)

not work even on failsafe session

![image](https://user-images.githubusercontent.com/91467886/198868225-4169495c-58d5-478b-a54d-22f919aa94fc.png)

**Comment by agnostic-apollo** [comment]
Are you even rooted and which superuser manager are you using? Use full path to `su` binary if its not found in `$PATH`.

**Comment by TukangM** [comment]
> Are you even rooted and which superuser manager are you using?

25:MAGISKSU

> Use full path to `su` binary if its not found in `$PATH`.

idk how

**Comment by agnostic-apollo** [comment]
`/system/bin/su -c ...` "should" work for magisk 25.

**Comment by TukangM** [comment]
> /system/bin/su -c ...

![image](https://user-images.githubusercontent.com/91467886/200095025-b08cc32d-90f0-466c-9aaa-4838935bd46c.png)

**Comment by agnostic-apollo** [comment]
Your `su` binary is at `/sbin/su`. The `...` was meant to be replaced with the commands in my earlier comment and `path` set before `su` command. (what is wrong with you...)

**Comment by TukangM** [comment]
> Your `su` binary is at `/sbin/su`. The `...` was meant to be replaced with the commands in my earlier comment and `path` set before `su` command. (what is wrong with you...)
(idk)

![image](https://user-images.githubusercontent.com/91467886/200295346-cf313757-91fe-4160-a335-6d46d369347c.png)
/sbin/su work
rm-rf  inaccessible (rm-rf   mkdir  chown  restorecon command may not found too)

**Comment by agnostic-apollo** [comment]
>`rm-rf`

There was supposed to be a space like `rm -rf`, my mistake. `PATH` should point to `/system/bin`, so those should accessible. I  have updated the comment above.

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/200325738-d3d4e1e4-c4b0-45b4-8ce9-c986fa3a77f9.png)
```path=/data/data/com.termux; /sbin/su -c "rm -rf '$path' && mkdir -p '$path' && chown $(id -u):$(id -u) -R '$path' && chmod -R 0700 '$path' && restorecon -v '$path'"```

**Comment by agnostic-apollo** [comment]
hmmm, try running command again. If same error, could be some file corruption preventing even android from removing it during uninstallation. Run `/system/bin/ls -lhdZ /data/data/com.termux`, `/system/bin/ls -lhdZ /path/to/Normalize` and `/system/bin/ls -lhZ /path/to/Normalize` after running `/sbin/su` command. And post text instead of screenshots.

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/200333772-a91d1e34-3378-4e5c-b237-651dc12599da.png)
/system/bin/ls -lhdZ /data/data/com.termux
![image](https://user-images.githubusercontent.com/91467886/200334464-7c55b6f1-ca3e-468b-bd7c-63823fbacf77.png)
/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/usr/lib/aarch64-linux-gnu/perl/5.34.0/auto/Unicode/Normalize
![image](https://user-images.githubusercontent.com/91467886/200335230-e6c3b990-42e1-4795-8eea-e67eeb801525.png)
/system/bin/ls -lhZ /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/usr/lib/aarch64-linux-gnu/perl/5.34.0/auto/Unicode/Normalize       (no such file or dir)

**Comment by agnostic-apollo** [comment]
Well, seems like a corruption, would probably need to do filesystem repair.

For now try running `mv /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/usr/lib/aarch64-linux-gnu/perl/5.34.0/auto/Unicode/Normalize /data/corrupted` with root shell and then run that full `rm` command from outside a root shell.

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/200552938-702737b3-cd53-49a9-8938-ab4992eb7927.png)

**Comment by agnostic-apollo** [comment]
Seems like first command with `su` succeeded. Trying full `rm` command again and see if it succeeds now. If it does, restart termux and see if bootstrap installs.

**Comment by TukangM** [comment]
> Seems like first command with `su` succeeded. Try running full `rm` command again and see if it succeeds now. If it does, restart termux and see if bootstrap installs.

ok

**Comment by TukangM** [comment]
yes it's worked :D
thanks

![image](https://user-images.githubusercontent.com/91467886/200805003-bd1f1699-0870-4659-b2e1-2e6dfad091cc.png)

**Comment by agnostic-apollo** [comment]
Congratz! Welcome.

**Comment by Benjamin-Loison** [comment]
What about setting a title to this issue to ease searching through issues (even closed ones)?
It may not be precise, but as a first iteration I propose:

> Bootstrap failing

**Comment by agnostic-apollo** [comment]
Done.
