### ISSUE TITLE
Consider exporting TMPDIR by default

### ISSUE THREAD

**Issue by bchallenor** [termux/termux-app#306]
Termux already exports `PREFIX`; could it export `TMPDIR` as well?

I'm looking at compiling a Go application that makes frequent use of `ioutil.TempFile`. I could patch all the usages, or I could patch the Go runtime itself, but as Go respects `TMPDIR`, defining it by default in Termux would be the easiest solution.

Note [TMPDIR](https://en.wikipedia.org/wiki/TMPDIR) is a Unix standard and many programs will respect it.

**Comment by fornwall** [comment]
Thanks - `TMPDIR` is exported starting with version 0.49 of Termux, which has just been released and should be available as an update shortly!

**Comment by malbarbo** [comment]
`TMPDIR` is set when a termux windows is opened in the phone, but it is not set when connecting to phone by ssh... @fornwall Is this expected?
