### ISSUE TITLE
[Feature]: Please Append pandas installer to pkg:)

### ISSUE THREAD

**Issue by go0ril** [termux/termux-app#3064]
### Feature description

I never can install this thing: pandas
'pip install pandas'
#Result

'''

            numpy/core/src/npymath/npy_math_complex.c.src:1767:17: note: include the header <complex.h> or explicitly provide a declaration for 'cacoshl'
            numpy/core/src/npymath/npy_math_complex.c.src:1767:17: warning: call to undeclared library function 'casinhl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                ret.c99_z = casinhl(z1.c99_z);
                            ^
            numpy/core/src/npymath/npy_math_complex.c.src:1767:17: note: include the header <complex.h> or explicitly provide a declaration for 'casinhl'
            numpy/core/src/npymath/npy_math_complex.c.src:1767:17: warning: call to undeclared library function 'catanhl' with type '_Complex long double (_Complex long double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                ret.c99_z = catanhl(z1.c99_z);
                            ^
            numpy/core/src/npymath/npy_math_complex.c.src:1767:17: note: include the header <complex.h> or explicitly provide a declaration for 'catanhl'
            19 warnings generated.
            llvm-ar: adding 4 object files to build/temp.linux-aarch64-3.10/libnpymath.a
            building 'npyrandom' library
            compiling C sources
            C compiler: aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating build/temp.linux-aarch64-3.10/numpy/random
            creating build/temp.linux-aarch64-3.10/numpy/random/src
            creating build/temp.linux-aarch64-3.10/numpy/random/src/distributions
            compile options: '-Inumpy/core/include -Ibuild/src.linux-aarch64-3.10/numpy/core/include/numpy -Ibuild/src.linux-aarch64-3.10/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.10 -Ibuild/src.linux-aarch64-3.10/numpy/core/src/common -Ibuild/src.linux-aarch64-3.10/numpy/core/src/npymath -c'
            aarch64-linux-android-clang: numpy/random/src/distributions/random_mvhg_marginals.c
            aarch64-linux-android-clang: numpy/random/src/distributions/distributions.c
            aarch64-linux-android-clang: numpy/random/src/distributions/logfactorial.c
            aarch64-linux-android-clang: numpy/random/src/distributions/random_mvhg_count.c
            aarch64-linux-android-clang: numpy/random/src/distributions/random_hypergeometric.c
            llvm-ar: adding 5 object files to build/temp.linux-aarch64-3.10/libnpyrandom.a
            running build_ext
            customize UnixCCompiler
            customize UnixCCompiler using new_build_ext
            CCompilerOpt.__init__[786] : hit the memory cache
            CCompilerOpt.generate_dispatch_header[2272] : generate CPU dispatch header: (build/src.linux-aarch64-3.10/numpy/distutils/include/npy_cpu_dispatch_config.h)
            building 'numpy.core._multiarray_tests' extension
            compiling C sources
            C compiler: aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating build/temp.linux-aarch64-3.10/build/src.linux-aarch64-3.10/numpy/core/src/multiarray
            creating build/temp.linux-aarch64-3.10/numpy/core/src/common
            compile options: '-DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-aarch64-3.10/numpy/core/include/numpy -Ibuild/src.linux-aarch64-3.10/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.10 -Ibuild/src.linux-aarch64-3.10/numpy/core/src/common -Ibuild/src.linux-aarch64-3.10/numpy/core/src/npymath -c'
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/multiarray/_multiarray_tests.c
            aarch64-linux-android-clang: numpy/core/src/common/npy_argparse.c
            aarch64-linux-android-clang: numpy/core/src/common/mem_overlap.c
            aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r25b-api-24-v0/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r25b-api-24-v0/sysroot/usr/lib build/temp.linux-aarch64-3.10/build/src.linux-aarch64-3.10/numpy/core/src/multiarray/_multiarray_tests.o build/temp.linux-aarch64-3.10/numpy/core/src/common/mem_overlap.o build/temp.linux-aarch64-3.10/numpy/core/src/common/npy_argparse.o -L/data/data/com.termux/files/usr/lib -Lbuild/temp.linux-aarch64-3.10 -lnpymath -lpython3.10 -o build/lib.linux-aarch64-3.10/numpy/core/_multiarray_tests.cpython-310.so
            building 'numpy.core._multiarray_umath' extension
            compiling C dispatch-able sources
            CCompilerOpt.parse_targets[1768] : looking for '@targets' inside ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_unary_fp.dispatch.c
            CCompilerOpt._parse_target_tokens[1939] : skip targets (VSX2 SSE2) not part of baseline or dispatch-able features
            CCompilerOpt._parse_policy_not_keepbase[2051] : skip baseline features (NEON)
            CCompilerOpt._parse_target_tokens[1963] : policy 'MAXOPT' is ON
            CCompilerOpt._parse_policy_maxopt[2072] : debug mode is detected, policy 'maxopt' is skipped.
            CCompilerOpt._generate_config[2506] : generate dispatched config ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_unary_fp.dispatch.h
            CCompilerOpt.parse_targets[1768] : looking for '@targets' inside ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_arithm_fp.dispatch.c
            CCompilerOpt._parse_target_tokens[1939] : skip targets (AVX512F SSE2 AVX2) not part of baseline or dispatch-able features
            CCompilerOpt._parse_target_tokens[1963] : policy 'MAXOPT' is ON
            CCompilerOpt._parse_policy_maxopt[2072] : debug mode is detected, policy 'maxopt' is skipped.
            CCompilerOpt._generate_config[2506] : generate dispatched config ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_arithm_fp.dispatch.h
            CCompilerOpt.parse_targets[1768] : looking for '@targets' inside ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_arithmetic.dispatch.c
            CCompilerOpt._parse_target_tokens[1939] : skip targets (AVX512_SKX AVX2 AVX512F SSE41 SSE2 VSX2) not part of baseline or dispatch-able features
            CCompilerOpt._parse_policy_not_keepbase[2051] : skip baseline features (NEON)
            CCompilerOpt._parse_target_tokens[1963] : policy 'MAXOPT' is ON
            CCompilerOpt._parse_policy_maxopt[2072] : debug mode is detected, policy 'maxopt' is skipped.
            CCompilerOpt._generate_config[2506] : generate dispatched config ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_arithmetic.dispatch.h
            CCompilerOpt.parse_targets[1768] : looking for '@targets' inside ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_trigonometric.dispatch.c
            CCompilerOpt._parse_target_tokens[1939] : skip targets (AVX512F VSX2 (FMA3 AVX2)) not part of baseline or dispatch-able features
            CCompilerOpt._parse_policy_not_keepbase[2051] : skip baseline features (NEON_VFPV4)
            CCompilerOpt._parse_target_tokens[1963] : policy 'MAXOPT' is ON
            CCompilerOpt._parse_policy_maxopt[2072] : debug mode is detected, policy 'maxopt' is skipped.
            CCompilerOpt._generate_config[2506] : generate dispatched config ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_trigonometric.dispatch.h
            CCompilerOpt.parse_targets[1768] : looking for '@targets' inside ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_exponent_log.dispatch.c
            CCompilerOpt._parse_target_tokens[1939] : skip targets (AVX512F (FMA3 AVX2) AVX512_SKX) not part of baseline or dispatch-able features
            CCompilerOpt._parse_target_tokens[1963] : policy 'MAXOPT' is ON
            CCompilerOpt._parse_policy_maxopt[2072] : debug mode is detected, policy 'maxopt' is skipped.
            CCompilerOpt._generate_config[2506] : generate dispatched config ->  build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_exponent_log.dispatch.h
            C compiler: aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating build/temp.linux-aarch64-3.10/build/src.linux-aarch64-3.10/numpy/core/src/umath
            compile options: '-DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -Ibuild/src.linux-aarch64-3.10/numpy/core/src/common -Ibuild/src.linux-aarch64-3.10/numpy/core/src/umath -Inumpy/core/include -Ibuild/src.linux-aarch64-3.10/numpy/core/include/numpy -Ibuild/src.linux-aarch64-3.10/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.10 -Ibuild/src.linux-aarch64-3.10/numpy/core/src/common -Ibuild/src.linux-aarch64-3.10/numpy/core/src/npymath -c'
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_unary_fp.dispatch.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_arithm_fp.dispatch.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_arithmetic.dispatch.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_exponent_log.dispatch.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/umath/loops_trigonometric.dispatch.c
            numpy/core/src/umath/loops_unary_fp.dispatch.c.src:220:32: warning: unused variable 'unused_but_workaround_bug' [-Wunused-variable]
                         volatile npyv_f32 unused_but_workaround_bug = v_src0;
                                           ^
            numpy/core/src/umath/loops_unary_fp.dispatch.c.src:220:32: warning: unused variable 'unused_but_workaround_bug' [-Wunused-variable]
                         volatile npyv_f32 unused_but_workaround_bug = v_src0;
                                           ^
            numpy/core/src/umath/loops_unary_fp.dispatch.c.src:220:32: warning: unused variable 'unused_but_workaround_bug' [-Wunused-variable]
                         volatile npyv_f32 unused_but_workaround_bug = v_src0;
                                           ^
            numpy/core/src/umath/loops_unary_fp.dispatch.c.src:220:32: warning: unused variable 'unused_but_workaround_bug' [-Wunused-variable]
                         volatile npyv_f32 unused_but_workaround_bug = v_src0;
                                           ^
            numpy/core/src/umath/loops_unary_fp.dispatch.c.src:220:32: warning: unused variable 'unused_but_workaround_bug' [-Wunused-variable]
                         volatile npyv_f64 unused_but_workaround_bug = v_src0;
                                           ^
            numpy/core/src/umath/loops_unary_fp.dispatch.c.src:220:32: warning: unused variable 'unused_but_workaround_bug' [-Wunused-variable]
                         volatile npyv_f64 unused_but_workaround_bug = v_src0;
                                           ^
            numpy/core/src/umath/loops_unary_fp.dispatch.c.src:220:32: warning: unused variable 'unused_but_workaround_bug' [-Wunused-variable]
                         volatile npyv_f64 unused_but_workaround_bug = v_src0;
                                           ^
            numpy/core/src/umath/loops_unary_fp.dispatch.c.src:220:32: warning: unused variable 'unused_but_workaround_bug' [-Wunused-variable]
                         volatile npyv_f64 unused_but_workaround_bug = v_src0;
                                           ^
            numpy/core/src/umath/loops_arithmetic.dispatch.c.src:45:1: warning: unused function 'simd_divide_by_scalar_contig_s64' [-Wunused-function]
            simd_divide_by_scalar_contig_s64(char **args, npy_intp len)
            ^
            numpy/core/src/umath/loops_arithmetic.dispatch.c.src:110:1: warning: unused function 'simd_divide_by_scalar_contig_u64' [-Wunused-function]
            simd_divide_by_scalar_contig_u64(char **args, npy_intp len)
            ^
            numpy/core/src/umath/loops_arithm_fp.dispatch.c.src:454:1: warning: unused function 'run_binary_simd_add_LONGDOUBLE' [-Wunused-function]
            run_binary_simd_add_LONGDOUBLE(char **args, npy_intp const *dimensions, npy_intp const *steps)
            ^
            numpy/core/src/umath/loops_arithm_fp.dispatch.c.src:454:1: warning: unused function 'run_binary_simd_subtract_LONGDOUBLE' [-Wunused-function]
            run_binary_simd_subtract_LONGDOUBLE(char **args, npy_intp const *dimensions, npy_intp const *steps)
            ^
            numpy/core/src/umath/loops_arithm_fp.dispatch.c.src:454:1: warning: unused function 'run_binary_simd_multiply_LONGDOUBLE' [-Wunused-function]
            run_binary_simd_multiply_LONGDOUBLE(char **args, npy_intp const *dimensions, npy_intp const *steps)
            ^
            numpy/core/src/umath/loops_arithm_fp.dispatch.c.src:454:1: warning: unused function 'run_binary_simd_divide_LONGDOUBLE' [-Wunused-function]
            run_binary_simd_divide_LONGDOUBLE(char **args, npy_intp const *dimensions, npy_intp const *steps)
            ^
            2 warnings generated.
            8 warnings generated.
            4 warnings generated.
            compiling C sources
            C compiler: aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating build/temp.linux-aarch64-3.10/numpy/core/src/multiarray
            creating build/temp.linux-aarch64-3.10/build/src.linux-aarch64-3.10/numpy/core/src/npysort
            creating build/temp.linux-aarch64-3.10/numpy/core/src/umath
            creating build/temp.linux-aarch64-3.10/build/src.linux-aarch64-3.10/numpy/core/src/common
            compile options: '-DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -Ibuild/src.linux-aarch64-3.10/numpy/core/src/common -Ibuild/src.linux-aarch64-3.10/numpy/core/src/umath -Inumpy/core/include -Ibuild/src.linux-aarch64-3.10/numpy/core/include/numpy -Ibuild/src.linux-aarch64-3.10/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.10 -Ibuild/src.linux-aarch64-3.10/numpy/core/src/common -Ibuild/src.linux-aarch64-3.10/numpy/core/src/npymath -c'
            aarch64-linux-android-clang: numpy/core/src/multiarray/abstractdtypes.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/multiarray/arraytypes.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/array_assign_scalar.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/buffer.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/datetime.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/datetime_busdaycal.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/common.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/convert_datatype.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/alloc.c
            numpy/core/src/multiarray/convert_datatype.c:249:9: warning: comparison of nonnull parameter 'dtype' equal to a null pointer is 'false' on first encounter [-Wtautological-pointer-compare]
                if (dtype == NULL) {
                    ^~~~~    ~~~~
            build/src.linux-aarch64-3.10/numpy/core/include/numpy/__multiarray_api.h:112:40: note: declared 'nonnull' here
            NPY_NO_EXPORT NPY_STEALS_REF_TO_ARG(2) NPY_GCC_NONNULL(2) PyObject * PyArray_CastToType \
                                                   ^
            numpy/core/include/numpy/npy_common.h:81:43: note: expanded from macro 'NPY_GCC_NONNULL'
            #define NPY_GCC_NONNULL(n) __attribute__((nonnull(n)))
                                                      ^
            aarch64-linux-android-clang: numpy/core/src/multiarray/array_assign_array.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/descriptor.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/calculation.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/common_dtype.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/arrayfunction_override.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/convert.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/arrayobject.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/datetime_strings.c
            1 warning generated.
            aarch64-linux-android-clang: numpy/core/src/multiarray/conversion_utils.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/compiled_base.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/dragon4.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/multiarray/einsum_sumprod.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/dtypemeta.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/ctors.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/datetime_busday.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/hashdescr.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/item_selection.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/legacy_dtype_implementation.c                                                                    aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/multiarray/lowlevel_strided_loops.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/methods.c
            numpy/core/src/multiarray/item_selection.c:2092:1: warning: unused function 'count_nonzero_bytes_384' [-Wunused-function]
            count_nonzero_bytes_384(const npy_uint64 * w)
            ^
            aarch64-linux-android-clang: numpy/core/src/multiarray/nditer_api.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/dtype_transfer.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/number.c
            1 warning generated.                                                        aarch64-linux-android-clang: numpy/core/src/multiarray/iterators.c                                                                                      aarch64-linux-android-clang: numpy/core/src/multiarray/nditer_constr.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/refcount.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/multiarraymodule.c                                                                               aarch64-linux-android-clang: numpy/core/src/multiarray/sequence.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/multiarray/einsum.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/shape.c
            numpy/core/src/multiarray/einsum.c.src:408:32: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-warning-option]               #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
                                           ^                                            aarch64-linux-android-clang: numpy/core/src/multiarray/strfuncs.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/nditer_pywrap.c
            1 warning generated.
            aarch64-linux-android-clang: numpy/core/src/multiarray/usertypes.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/scalarapi.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/temp_elide.c                                                                                     aarch64-linux-android-clang: numpy/core/src/multiarray/vdot.c
            numpy/core/src/multiarray/temp_elide.c:84:10: fatal error: 'execinfo.h' file not found
            #include <execinfo.h>                                                                ^~~~~~~~~~~~
            1 error generated.
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/npysort/mergesort.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/npysort/radixsort.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/multiarray/scalartypes.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/npysort/quicksort.c                                                            numpy/core/src/multiarray/scalartypes.c.src:1847:9: warning: variable 'i' set but not used [-Wunused-but-set-variable]
                int i;
                    ^
            numpy/core/src/multiarray/scalartypes.c.src:1847:9: warning: variable 'i' set but not used [-Wunused-but-set-variable]
                int i;
                    ^
            numpy/core/src/multiarray/scalartypes.c.src:1847:9: warning: variable 'i' set but not used [-Wunused-but-set-variable]
                int i;
                    ^
            numpy/core/src/multiarray/scalartypes.c.src:1847:9: warning: variable 'i' set but not used [-Wunused-but-set-variable]
                int i;
                    ^                                                                   aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/multiarray/nditer_templ.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/flagsobject.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/npysort/selection.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/getset.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/npysort/timsort.c
            aarch64-linux-android-clang: numpy/core/src/umath/umathmodule.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/umath/matmul.c
            4 warnings generated.                                                       aarch64-linux-android-clang: numpy/core/src/umath/extobj.c
            aarch64-linux-android-clang: numpy/core/src/umath/reduction.c
            aarch64-linux-android-clang: numpy/core/src/multiarray/array_coercion.c                                                                                 aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/umath/scalarmath.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/umath/loops.c                                                                  aarch64-linux-android-clang: numpy/core/src/multiarray/array_method.c
            aarch64-linux-android-clang: numpy/core/src/umath/override.c
            aarch64-linux-android-clang: numpy/core/src/common/npy_argparse.c
            aarch64-linux-android-clang: numpy/core/src/common/array_assign.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/umath/clip.c
            aarch64-linux-android-clang: numpy/core/src/common/npy_longdouble.c
            aarch64-linux-android-clang: numpy/core/src/common/mem_overlap.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/npysort/binsearch.c
            aarch64-linux-android-clang: numpy/core/src/umath/ufunc_object.c
            aarch64-linux-android-clang: numpy/core/src/common/ucsnarrow.c
            aarch64-linux-android-clang: numpy/core/src/common/ufunc_override.c                                                                                     aarch64-linux-android-clang: numpy/core/src/common/cblasfuncs.c
            aarch64-linux-android-clang: numpy/core/src/common/numpyos.c
            aarch64-linux-android-clang: numpy/core/src/common/python_xerbla.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/common/npy_cpu_features.c
            numpy/core/src/common/npy_cpu_features.c.src:618:54: warning: code will never be executed [-Wunreachable-code]
                    npy__cpu_have[NPY_CPU_FEATURE_NEON]       = (hwcap & NPY__HWCAP_NEON)   != 0;                                                                                                                        ^~~~~                  numpy/core/src/common/npy_cpu_features.c.src:604:9: note: silence by adding parentheses to mark code as explicitly dead
                if (1)
                    ^                                                                           /* DISABLES CODE */ ( )
            1 warning generated.                                                        aarch64-linux-android-clang: numpy/core/src/umath/ufunc_type_resolution.c                                                                               aarch64-linux-android-clang: numpy/core/src/multiarray/mapping.c
            aarch64-linux-android-clang: build/src.linux-aarch64-3.10/numpy/core/src/npysort/heapsort.c
            error: Command "aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -Ibuild/src.linux-aarch64-3.10/numpy/core/src/common -Ibuild/src.linux-aarch64-3.10/numpy/core/src/umath -Inumpy/core/include -Ibuild/src.linux-aarch64-3.10/numpy/core/include/numpy -Ibuild/src.linux-aarch64-3.10/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/data/data/com.termux/files/usr/include/python3.10 -Ibuild/src.linux-aarch64-3.10/numpy/core/src/common -Ibuild/src.linux-aarch64-3.10/numpy/core/src/npymath -c numpy/core/src/multiarray/temp_elide.c -o build/temp.linux-aarch64-3.10/numpy/core/src/multiarray/temp_elide.o -MMD -MF build/temp.linux-aarch64-3.10/numpy/core/src/multiarray/temp_elide.o.d" failed with exit status 1

            ########### EXT COMPILER OPTIMIZATION ###########
            Platform      :
              Architecture: aarch64
              Compiler    : clang

            CPU baseline  :
              Requested   : 'min'
              Enabled     : NEON NEON_FP16 NEON_VFPV4 ASIMD
              Flags       : none
              Extra checks: none
                                                                                        CPU dispatch  :
              Requested   : 'max -xop -fma4'
              Enabled     : ASIMDHP ASIMDDP
              Generated   : none
            CCompilerOpt.cache_flush[809] : write cache to path -> /data/data/com.termux/files/usr/tmp/pip-install-vo7h3atf/numpy_e1041610002a4cb394f556e035404bef/build/temp.linux-aarch64-3.10/ccompiler_opt_cache_ext.py

            ########### CLIB COMPILER OPTIMIZATION ###########
            Platform      :                                                               Architecture: aarch64
              Compiler    : clang                                           
            CPU baseline  :                                                               Requested   : 'min'
              Enabled     : NEON NEON_FP16 NEON_VFPV4 ASIMD                               Flags       : none
              Extra checks: none                                            
            CPU dispatch  :                                                               Requested   : 'max -xop -fma4'
              Enabled     : ASIMDHP ASIMDDP
              Generated   : none                                                        CCompilerOpt.cache_flush[809] : write cache to path -> /data/data/com.termux/files/usr/tmp/pip-install-vo7h3atf/numpy_e1041610002a4cb394f556e035404bef/build/temp.linux-aarch64-3.10/ccompiler_opt_cache_clib.py                    [end of output]                                                 
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1                                                              ╰─> See above for output.                                                   
note: This error originates from a subprocess, and is likely not a problem with pip.
'''

### Additional information

I installed bunch of things and scripts but everitime its not work i using py 3.10

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/issues/12412
