### ISSUE TITLE
[Bug]: Android.WIN32.Agent.eq (MaxSecure)

### ISSUE THREAD

**Issue by pucgenie** [termux/termux-app#3066]
### Problem description

The Android 7 arm64 v8a build from 2 days ago is flagged by this anti-virus (I personally never have heard before).
What can I do to prevent this from happening or how can we check if there really was malicious code added?
termux-app_v0.118.0+29cf982-apt-android-7-github-debug_arm64-v8a.zip

### Steps to reproduce the behavior.

https://www.virustotal.com/gui/file/9070f91ad3b22c6d1459dac77f23ed0edcb6383f1c359c1fea53ce91d709a44f

### What is the expected behavior?

No suspicious flags.

### System information

* Termux application version: v0.118.0+29cf982
* Android OS version: android-7-github-debug_arm64-v8a
* Device model: not relevant

**Comment by Grimler91** [comment]
Only "MaxSecure" out of the ~50 AV vendors in that list seem to think termux is malicious, so seems like a false positive. Have to ask them for info to know how they reached their result.

To ensure your termux-app is free from malware you can look through the code in [the repo](https://github.com/termux/termux-app), and build the app from source yourself, or try to verify that the published apk at github is actually built by github actions from the code belonging to the corresponding commit.

See also https://github.com/termux/termux-app/issues/1784, https://github.com/termux/termux-app/issues/2938, https://github.com/termux/termux-boot/issues/115
