### ISSUE TITLE
Is it possible to enable/disable USB tethering from Termux or Termux-API?

### ISSUE THREAD

**Issue by bitcoinmeetups** [termux/termux-app#307]
Is it possible to enable/disable USB tethering from Termux or Termux-API?

**Comment by v0idst4r** [comment]
No.

**Comment by v0idst4r** [comment]
You can close this issue now

**Comment by Quasic** [comment]
I use an app for this purpose, but I don't know how it works: https://play.google.com/store/apps/details?id=com.tomlocksapps.bluetoothtetheringmanager

I don't know if it is possible to somehow control it from termux...

**Comment by hyperpallium** [comment]
@Quasic It uses non-public APIs. From its play store page:

> My app uses internal API staff, so It might not work on your device, because your manufacturer might cut some funcionality. So if you encounter any problem please write email to me and describe your problem.

**Comment by YveOms** [comment]
Yes. It is possible.

Adapted from this link, [Stackoverflow](https://stackoverflow.com/a/24346101)

Check your android version.

4.4.4:  34
5.1.0:  30
6.0.1:  30
7.0.0:  33

Ensure you are rooted.
Fire up termux, and type su and grant superuser permissions
Type: `service call connectivity 33 i32 1`; 33 refer table above. In my case it was Android 7
The 1 at the end is used to turn on. Use 0 to turn it off
