### ISSUE TITLE
502 bad getaway error for each command in termux 

### ISSUE THREAD

**Issue by UBV76** [termux/termux-app#3078]
### Problem description

When I want to do anything in termux I get error 
`502 bad getaway `
For example:
`pkg update`
....
`  502  Bad Gateway
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?). `
What should I do?

### Steps to reproduce the behavior.

...

### What is the expected behavior?

Nothing special 

### System information

* Termux application version:0.118.0
* Android OS version:11
* Device model:SMA107F

**Comment by Grimler91** [comment]
If you truly have 0.118.0 from f-droid, and not the old, outdated version from google play, then `apt remove game-repo science-repo && pkg upgrade` should do it.

See [README](https://github.com/termux/termux-app#Installation) https://github.com/termux/termux-packages/issues/6726 for further info
