### ISSUE TITLE
[Bug]:  Connecting, establishing handshake... this message keeps on for ever

### ISSUE THREAD

**Issue by noo7001** [termux/termux-app#3082]
### Problem description

after installing and connecting Kali, a message

Connecting...
Establishing handshake.
Please wait...

is on the screen and i cant use my phone.. if i exit the process is terminated,, i did everything exactly at it is in the tutorial..

### Steps to reproduce the behavior.

Just walking through the tutorial shown on Youtube.. by David Bombal

### What is the expected behavior?

to coonect and start using Kali linux on my android phone

### System information

* Termux application version: 
* Android OS version: 11
* Device model: Hawaii Honor X7

**Comment by Grimler91** [comment]
We won't help with third party scripts or tutorials
