### ISSUE TITLE
[Feature]: Remove $OLDPWD since it now useless

### ISSUE THREAD

**Issue by crischutu07** [termux/termux-app#3085]
### Feature description

As the title said, `$OLDPWD` is useless and `$PWD` is exist and `$OLDPWD` have the same directory for `$PWD`

### Additional information

no

**Comment by Grimler91** [comment]
Seem to work as it should for me:

```
$ echo $OLDPWD $PWD
/data/data/com.termux/files/home
$ cd Documents/
$ echo $OLDPWD $PWD
/data/data/com.termux/files/home /data/data/com.termux/files/home/Documents
```

**Comment by crischutu07** [comment]
> Seem to work as it should for me:
> 
> ```
> $ cd
> $ echo $OLDPWD $PWD
> /data/data/com.termux/files/home /data/data/com.termux/files/home
> $ cd Documents/
> $ echo $OLDPWD $PWD
> /data/data/com.termux/files/home /data/data/com.termux/files/home/Documents
> ```

`$OLDPREFIX` = `$HOME` 😳
