### ISSUE TITLE
[Bug]: The postgresql package does not work

### ISSUE THREAD

**Issue by ASoldo** [termux/termux-app#3086]
### Problem description

pkg install postgresql
mkdir -p $PREFIX/var/lib/postgresql
initdb $PREFIX/var/lib/postgresql

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/postgres": library "libexecinfo.so" not found: needed by main executable
no data was returned by command ""/data/data/com.termux/files/usr/bin/postgres" -V"
initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/data/data/com.termux/files/usr/bin/initdb"

Here is my termux-info: 
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11750
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
ndk-sysroot/stable 25b-2 aarch64 [upgradable from: 25b-1]
termux-tools version:
1.31.0
Android version:
12
Kernel build information:
Linux localhost 4.19.87-24217537 #1 SMP PREEMPT Mon Sep 19 11:36:05 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-N986B

### Steps to reproduce the behavior.

run this commands:
pkg install postgresql
mkdir -p $PREFIX/var/lib/postgresql
initdb $PREFIX/var/lib/postgresql
error!

### What is the expected behavior?

The database is should have been created but instead gives this error

### System information

* Termux application version: Latest
* Android OS version: 12
* Device model:SM-N986B

**Comment by 2096779623** [comment]
`rm -rf $PREFIX/var/lib/postgresql/`
`initdb $PREFIX/var/lib/postgresql`

```bash
~ $ rm -rf $PREFIX/var/lib/postgresql/
~ $ pkg i libandroid-execinfo
Checking availability of current mirror:
[*] https://mirrors.ustc.edu.cn/termux/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  libandroid-execinfo
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.5 kB of archives.
After this operation, 90.1 kB of additional disk space will be used.
Get:1 https://mirrors.ustc.edu.cn/termux/apt/termux-main stable/main aarch64 libandroid-execinfo aarch64 0.1 [14.5 kB]
Fetched 14.5 kB in 0s (41.7 kB/s)
Selecting previously unselected package libandroid-execinfo.
(Reading database ... 31293 files and directories currently installed.)
Preparing to unpack .../libandroid-execinfo_0.1_aarch64.deb ...
Unpacking libandroid-execinfo (0.1) ...
Setting up libandroid-execinfo (0.1) ...
~ $ initdb $PREFIX/var/lib/postgresql
The files belonging to this database system will be owned by user "u0_a334".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /data/data/com.termux/files/usr/var/lib/postgresql ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... mmap
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... PRC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start
```
