### ISSUE TITLE
[Bug]: mashal python: pls help

### ISSUE THREAD

**Issue by mocmeo-ship-it** [termux/termux-app#3089]
### Problem description

^^
ValueError: bad marshal data (unknown type code)

### Steps to reproduce the behavior.

I running file py encoded by mashal

### System information

* Termux application version: 0.118.0
* Android OS version: android 10
* Device model:
Vsmart star, vos 2.5

**Comment by Grimler91** [comment]
Doesn't seem to be any termux issue here

**Comment by mocmeo-ship-it** [comment]
> Doesn't seem to be any termux issue here

Why?
