### ISSUE TITLE
Support for Samsung DeX (Desktop Experience)

### ISSUE THREAD

**Issue by hirschnase** [termux/termux-app#309]
As discussed in [this Google+ thread](https://plus.google.com/u/0/112187690141583660341/posts/B7Qsp15fVgY?cfem=1), I would like to ask if changes could be made to Termux in order to work w/ the new Samsung DeX docking station thingy. All Android Apps work w/ DeX out of the box, however, if re-sizing or fullscreen should be supported, some adjustments must be made to the app, according to Samsung's website:

[http://developer.samsung.com/samsung-dex/modify](http://developer.samsung.com/samsung-dex/modify)

In Google+ has been mentioned, that Termux should potentially be re-sizable right now. I've tested it with a DeX-Station and found out, that it does not work (see attached Screenshot).

## Improvements that could be made

- Add support for fullscreen
- Add support for re-sizing of the App

I am happy to help with this by testing the App! Just let me know :)

![screen shot 2017-05-04 at 06 26 08](https://cloud.githubusercontent.com/assets/163801/25690539/8e7b23cc-3092-11e7-9452-25e0a7147ed6.png)

**Comment by hirschnase** [comment]
One more thing. I think that has nothing to do with DeX but more when an external (bluetooth, usb) keyboard is being used: when I exit the shell (exit, ctrl-d), there is a message "process completed, press enter" and I am not able to exit the app by pressing enter (nothing happens when I press enter on the keyboard).

**Comment by alive4ever** [comment]
[Optimizing Apps for Chromebooks](https://developer.android.com/topic/arc/index.html) article can be used as reference for this.

**Comment by ShawnMilo** [comment]
Cool. I'm holding out some hope that this will solve #250 as well!

**Comment by twoboxen** [comment]
Pretty easy fix.  I submitted a PR.

https://github.com/termux/termux-app/pull/433

**Comment by vzaliva** [comment]
I am also very interested in this issue. tmux+DeX is very powerful combination.
I have DeX device and will be glad to test potential fixes.

**Comment by vzaliva** [comment]
The link to DeX app upgrade guidelines in the origianl PR is no longer working. Here is the current one: http://developer.samsung.com/samsung-dex/modify-optimizing

**Comment by fornwall** [comment]
The newly released v0.58 of the Termux app now supports resizable windows when in Dex mode! The update should be available as an update within an hour or so on Google Play and a day or so on F-Droid.

@twoboxen Sorry about #433 - you were right in that it was resizeableActivity="true" which was needed. I still don't understand why it is needed as it should be the default value when the target API is 24+ (could it be a Samsung bug perhaps), but anyway it works now.
