### ISSUE TITLE
[Feature]: termux-backup and restore store home directory also

### ISSUE THREAD

**Issue by gyurmogyuri** [termux/termux-app#3090]
### Feature description

If you use [https://wiki.termux.com/wiki/Backing_up_Termux](https://wiki.termux.com/wiki/Backing_up_Termux)
_termux-backup_ 
_termux-restore_ app.
Don't store home folder and files within for backup. 
Or please write, only store /data/data/com.termux/**files/usr** dont store /data/data/com.termux/**files/home** folder

### Additional information

_termux-backup_ 
_termux-restore_ app.from [https://wiki.termux.com/wiki/Backing_up_Termux](https://wiki.termux.com/wiki/Backing_up_Termux)

**Comment by agnostic-apollo** [comment]
>These scripts backup and restore scripts will not backup, restore or in any other way touch your home directory. Check out the [notice](https://github.com/termux/termux-packages/blob/06499edb90a16fa471cff739ffee634f42a73913/packages/termux-tools/termux-restore#L6-L34) if have questions why so.

https://wiki.termux.com/wiki/Backing_up_Termux
