### ISSUE TITLE
[Bug]: GPG error: https://grimler.se/termux-packages-24

### ISSUE THREAD

**Issue by dfoulkes** [termux/termux-app#3094]
### Problem description

pkg update
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: bad
Picking mirror: https://grimler.se/termux-packages-24
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Get:2 https://grimler.se/termux-packages-24 stable InRelease [16.8 kB]
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.bintray.com:443
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.bintray.com:443
Err:2 https://grimler.se/termux-packages-24 stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B

### Steps to reproduce the behavior.

Pkg update

### System information

* Termux application version: 0.1.0
* Android OS version: 
* Device model:

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

https://github.com/termux/termux-app#google-play-store-deprecated
