### ISSUE TITLE
[Feature]: allow downgrade  python

### ISSUE THREAD

**Issue by a-gamer** [termux/termux-app#3095]
### Feature description

after upgrade termux  python updated to 3.11
and not working fine with frida have many issue so kindly allow to downgrade to python3.10
or fix the issue 

### Additional information

after upgrade termux  python updated to 3.11
and not working fine with frida have many issue so kindly allow to downgrade to python3.10
or fix the issue

**Comment by 2096779623** [comment]
```bash
pkg i tur-repo -y
pkg i python3.10 -y
```
