### ISSUE TITLE
Can't select text on the left side of the terminal because of the drawer

### ISSUE THREAD

**Issue by epitron** [termux/termux-app#31]
Right now, I can't select text that starts at column 0 in the terminal because the drawer that slides out from the left takes precedence. That drawer should be disabled when selecting.

It would also be nice if there was some way of confirming/correcting the selection, since it's difficult to tell which tiny character my finger is about to touch.

The simplest hack would be a little pop-up that says "is this selection correct?", and if not, the user is put back into selection mode.

**Comment by epitron** [comment]
Here's an extra feature that would help a lot: a "Select entities" mode which, instead of selecting individual characters, selects whole words, or whole filenames, with a single touch, or multiple words/filenames with a drag.

**Comment by fornwall** [comment]
Yea, text selection is definitely an area for improvement!

**Comment by fornwall** [comment]
Text selection has been quite improved in v0.26 of the app - try it out and report if there is any problem!

**Comment by epitron** [comment]
Very nice! Thank you!

**Comment by epitron** [comment]
There still seem to be some selecting issues: users can't select all the way to the edge of the screen, and the pop up menu can overlap the selection handles. 

Examples: 
https://0x0.st/ZXg.png
https://0x0.st/ZXx.png

**Comment by fornwall** [comment]
@epitron I'll look at improving the details! Note that you do not need to hit the handles exactly with the finger, it's enough to be close - this can be use to select all the way to the edge in your first screenshot.

**Comment by epitron** [comment]
I'll try that...
