### ISSUE TITLE
how to get out of git in the terminal?

### ISSUE THREAD

**Issue by Alan-White** [termux/termux-app#310]
I am a beginner and was trying to learn git in the terminal.  What do I type to get the terminal back to normal?  Thanks in advance.
![screen shot 2017-05-05 at 15 40 16](https://cloud.githubusercontent.com/assets/24911549/25750293/2c033820-31a9-11e7-84d3-a7e5cd5b118a.png)

**Comment by fornwall** [comment]
It seems that you are using oh my zsh which adds fancy prompts such as these - try running e.g. `bash` if you want to have a shell with an ordinary prompt.

Note that this repo is for https://termux.com/, an Android app, and not really the right place for this issue.
