### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by Crossshield45** [termux/termux-app#3101]
I got the same prob now. It doesn't connect.
"None of the mirrors are accessible."
      
What is solution.

**Comment by Grimler91** [comment]
Sounds like your internet connection is bad, or that you have installed an old version of the app from for example google play where none of the mirrors work anymore. Make sure you install from fdroid or github, see https://github.com/termux/termux-app#Installation

**Comment by Toniki8585** [comment]
> I got the same prob now. It doesn't connect. "None of the mirrors are accessible."
> 
> What is solution.
