### ISSUE TITLE
Sync the Termux theme with Android theme

### ISSUE THREAD

**Issue by xmha97** [termux/termux-app#3108]
### Feature description

Please add feature below:
- Sync the Termux theme with Android theme

### Additional information

Light theme is better for day
Dark theme is better for night

**Comment by agnostic-apollo** [comment]
Closed by 6631599f, will be available in next version.

**Comment by Indranil012** [comment]
> Closed by [6631599](https://github.com/termux/termux-app/commit/6631599fb627a849e64e76693cb3b0eb775b1a87), will be available in next version.

Does it mean we can use two different colors.properties for light and dark mode?

**Comment by agnostic-apollo** [comment]
The commit is for app theme, not terminal theme, but that is planned for the future.

https://matrix.to/#/!rrHhKvLYtBVDOISphu:gitter.im/$Sajk1zFmp0aX6fLxf5xs5j7p5AG6iK3aHwlmpeKhUkA?via=matrix.org&via=gitter.im&via=aria-net.org
