### ISSUE TITLE
long output + font size change makes termux freeze -- true clean command?

### ISSUE THREAD

**Issue by conrad-heimbold** [termux/termux-app#311]
If I have a lot of output in my terminal (e.g. from ``su -c logcat , CTRL-C ``), termux always freezes (for some time) if I then e.g. try to make the font size smaller. `` clear`` does not help, because it only jumps forward for one page size (blank space in between), but leaves the history. Is there some possibility to control, how much history termux should save? It would also be cool to have a command to truly clean the history.

**Comment by twaik** [comment]
What about `reset` command? It should reset all current terminal properties (like `no-echo` mode, background and foreground colors, etc) to default. 
You may add space before command to make bash not save command to history: ` reset`.

> It would also be cool to have a command to truly clean the history.

To clear bash history, you can use the `history -c` command. This command will erase all the commands you've previously executed in your terminal.
