### ISSUE TITLE
[Bug]: random blank area at at top, bottom and right 

### ISSUE THREAD

**Issue by zorro** [termux/termux-app#3118]
### Problem description

There are empty area at top, bottom and right side of the terminal. It change randomly while font size changes. It's reducing available terminal area.

![Screenshot_20221125-153951](https://user-images.githubusercontent.com/57064186/203961937-0db80226-cdf1-4036-a291-cb538b4ac3d3.png)

### Steps to reproduce the behavior.

* Change termux colour scheme to a light one.
* Open `vim` and choose a dark colour scheme.
* Keep changing the font size and observe the edges.

Note that this is not a `vim` issue. Just used vim for demonstration purposes 

### System information

Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #2 SMP PREEMPT Mon Mar 29 14:08:31 CST 2021 aarch64 Android
Device manufacturer:
LGE
Device model:
LM-X440IM

**Comment by agnostic-apollo** [comment]
You can use `terminal-margin-horizontal` and `terminal-margin-vertical` but in your case, issue seems to be some `vim` config if terminal uses full width and height in normal mode.

https://github.com/termux/termux-app/releases/tag/v0.118.0

**Comment by zorro** [comment]
> You can use `terminal-margin-horizontal` and `terminal-margin-vertical` but in your case, issue seems to be some `vim` config if terminal uses full width and height in normal mode.
> 
> https://github.com/termux/termux-app/releases/tag/v0.118.0

It's happening outside vim too. 

![Screenshot_20221125-220805](https://user-images.githubusercontent.com/57064186/204027036-6952a737-501b-410d-b3ec-d0fd95facd73.png)

**Comment by agnostic-apollo** [comment]
Terminal sets width and height depending on font size and device screen size to fit max columns/rows, and there may be vertical or horizontal space left if not enough room to add another. Set ` terminal-margin-horizontal` and `terminal-margin-vertical` to `0` to prevent any normal borders. Also you may wanna use same background color for vim theme.
