### ISSUE TITLE
Can't escape spaces when using scp

### ISSUE THREAD

**Issue by monkeyfunky** [termux/termux-app#312]
I attempted to use scp to copy some files from my PC to my phone. Whether I escape spaces in the path with backslash (\) or quotes it doesn't recognize it.

Ex:
`scp -r user@server:/home/user/dir1/some\ other\ dir .`

I get the following errors:

scp: /home/user/dir1/some: No such file or directory
scp: other: No such file or directory
scp: dir: No such file or directory

**Comment by Grimler91** [comment]
@monkeyfunky see this (stackoverflow question)[http://stackoverflow.com/questions/19858176/how-to-escape-spaces-in-path-during-scp-copy-in-linux], `scp -r user@server:"/home/user/dir1/some\ other\ dir" .` or `scp -r user@server:/home/user/dir1/some\\\ other\\\ dir .` should work according to the top-voted answer.

**Comment by monkeyfunky** [comment]
Yes thanks, that's it. So not a termux issue at all.
