### ISSUE TITLE
[Bug]: termux-setup-storage doesn't create external-1 folder

### ISSUE THREAD

**Issue by smartm0use** [termux/termux-app#3120]
### Problem description

I have attached a pendrive to my phone using an OTG cable. I can see it on Android and I see the content using a file explorer.

But I can't see it on Termux.

After I launch `termux-setup-storage` there is no "external-1" folder as expected, folders such as "dcim", "music", "shared" and so on are created instead.

I have already tried to disable and enable again the storage permission, but nothing changed.

If I type `mount` the pendrive appears like this:

```
/dev/block/vold/public:8,1 /mnt/media_rw/<drive-label> vfat...
```

What can I try to do?

### Steps to reproduce the behavior.

Just launch `termux-setup-storage` command.

### What is the expected behavior?

"external-1" folder being created.

### System information

* Termux application version: 4.4
* Android OS version: 8.1 (LineageOS 17.1)
* Device model: Xiaomi Mi A1

**Comment by agnostic-apollo** [comment]
>Shared storage devices returned here are considered a stable part of the device, including physical media slots under a protective cover. The returned paths do not include transient devices, such as USB flash drives connected to handheld devices. 

https://developer.android.com/reference/android/content/Context#getExternalFilesDirs(java.lang.String)

You can try `termux-saf-*` commands from `termux-api` package/app if  using github builds since usb otg drives would require `SAF` to access them.

https://github.com/termux/termux-api/pull/476

**Comment by smartm0use** [comment]
> external-1 is not being created for removable devices.

The wiki seems to say the opposite: "_External storage: external SD cards or USB hard drives. Typically read-only, except the Termux private directory._" (https://wiki.termux.com/wiki/Internal_and_external_storage).

According to wiki "_After creating directory Android/data/com.termux, through file manager or by termux-setup-storage, you can access your external SD directly in this folder._" But there is no "external-1" folder being created by termux-setup-storage.

What am I missing?


> > Shared storage devices returned here are considered a stable part of the device, including physical media slots under a protective cover. The returned paths do not include transient devices, such as USB flash drives connected to handheld devices.
> 
> https://developer.android.com/reference/android/content/Context#getExternalFilesDirs(java.lang.String)
> 
> https://github.com/termux/termux-app/blob/cff6cff609143d7441b42dad20c058ca26543247/app/src/main/java/com/termux/app/TermuxInstaller.java#L331-L339
> 
> You can try `termux-saf-*` commands from `termux-api` package/app if using github builds since usb otg drives would require `SAF` to access them.
> 
> [termux/termux-api#476](https://github.com/termux/termux-api/pull/476)

I'm using Termux 4.4, downloaded from F-Droid.

**Comment by agnostic-apollo** [comment]
The `termux-setup-storage` would ideally never create otg usb drives symlink, because its not returned  by `getExternalFilesDirs()` since Android does not consider them stable, even on android 5. Only sd card slot one is returned. However, otg usb drives may be accessible on some (old) android versions depending on vendor config with `/storage` (not `~/storage`) or `/mnt` paths.

https://cs.android.com/android/platform/superproject/+/android-5.0.0_r1.0.1:frameworks/base/core/java/android/content/Context.java;l=767

There are lot of definitions of what "external" even is.

>I'm using Termux 4.4, downloaded from F-Droid.

That version was never released.

https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.termux.yml#L36

**Comment by smartm0use** [comment]
> The `termux-setup-storage` would ideally never create otg usb drives symlink, because its not returned by `getExternalFilesDirs()` since Android does not consider them stable, even on android 5. Only sd card slot one is returned. However, otg usb drives may be accessible on some (old) android versions depending on vendor config with `/storage` (not `~/storage`) or `/mnt` paths.

Yes, I can see it under `/mnt/media_rw/` path.


> Note that USB card reader is not "external SD card".

Ok, I see, sorry.

Yes, I was wrong about the version, I'm using **0.117**. I do not know where 4.4 came from!

**Comment by smartm0use** [comment]
Hello, sorry if I open this again. Can you tell me when and where Termux app create "com.termux" folder?
I'm trying to figure out how a guy found the path of his external hdd just searching for "com.termux" folder.

Thank you!

**Comment by agnostic-apollo** [comment]
No need to reopen since its not an issue to solve. The `*/Android/data/com.termux` paths on stable storages are created when `getExternalFilesDirs()`  is called. It won't be created for external hd like already mentioned. You can use `mount` command to search for mounted volumes. It should ideally be mounted under `/mnt/media_rw` as is and then that likely mounted with `sdcardfs` under `/storage` for apps to use with `SAF`.

No idea who this guy is and which device/android version he's using.

**Comment by smartm0use** [comment]
Ok, I see, thank you.

> You can try `termux-saf-*` commands from `termux-api` package/app if using github builds since usb otg drives would require `SAF` to access them.
> 
> [termux/termux-api#476](https://github.com/termux/termux-api/pull/476)

I have followed the link but I do not figure out how to use SAF commands. Can you show some examples?
What do you mean for GitHub builds? Have I to build Termux app using the source code of master branch?

**Comment by tareksander** [comment]
> Have I to build Termux app using the source code of master branch?

Here are the builds: https://github.com/termux/termux-app/actions/workflows/debug_build.yml?query=is%3Asuccess+branch%3Amaster  
  
Click on the latest build and download the universal apk for your Android version, or the specific one if you know your architecture.  
Same thing for Termux:API: https://github.com/termux/termux-api/actions?query=branch%3Amaster+is%3Asuccess  
Make sure to uninstall Termux and plugins from f-droid first and back up your data.  

You can use the `--help` option with the SAF commands to get help.  
The process is this:
- use `termux-saf-managedir` to give Termux access to a directory via SAF
- use `termux-saf-ls` to list files and subfolders
- use `termux-saf-write/read/rm/create` to modify files in folders
- use `termux-saf-mkdir/rmdir` to create/delete folders
- use `termux-saf-dirs` to list all top-level folders you gave Termux access to

The commands output JSON, you can pipe into `jq` to get a pretty print.
