### ISSUE TITLE
[Feature]: Hide Extra Keys Row when the hardware keyboard is connected.

### ISSUE THREAD

**Issue by ZaxonXP** [termux/termux-app#3121]
### Feature description

It would be nice to get extra screen space in case when the hardware keyboard is connected, by hiding Extra Keys Row.

### Additional information

I tried to set the `extra-keys-style = none` or `extra-keys-style = []` and also used `Ctrl+Alt+K`, but none of these hides the extra keys displayed on the screen.

The only option now is to use the below config to reduce a space to minimum:
```
extra-keys = [[ \
  {key: ESC, popup: {macro: "CTRL d", display: "tmux exit"}}, \
  {key: CTRL, popup: {macro: "CTRL f BKSP", display: "tmux ←"}}, \
  {key: ALT, popup: {macro: "CTRL f TAB", display: "tmux →"}}, \
  {key: TAB, popup: {macro: "ALT a", display: A-a}}, \
  {key: LEFT, popup: HOME}, \
  {key: DOWN, popup: PGDN}, \
  {key: UP, popup: PGUP}, \
  {key: RIGHT, popup: END}, \
  {macro: "ALT j", display: A-j, popup: {macro: "ALT g", display: A-g}}, \
  {key: KEYBOARD, popup: {macro: "CTRL d", display: exit}} \
]]
```

Using termux version 0.118.0

**Comment by Grimler91** [comment]
Having an option to automatically hide the keys would make sense. Before that is implemented you can manually hide the extra-keys by long-pressing the keyboard button or pressing vol up + k or vol up + q.

**Comment by ZaxonXP** [comment]
I am OK even with the manually hiding the extra key row, but it looks like it does not work. 

I used the `Ctrl+Alt+K` from the hardware keyboard when I already had the option set for auto hide the soft keyboard (Settings -> Termux -> Terminal I/O -> Soft Keyboard Only If No Hardware). With the full screen enable I see the one row of extra keys with some black empty space below (left screenshot). When I press `Ctrl+Alt+k` then the below empty bar is removed (right screenshot).

![extra_keys_row](https://user-images.githubusercontent.com/6058640/205025022-906d9dec-e41d-42d6-8bb7-4dcbc7f58943.png)
 
So it looks like there are 2 bugs in a current implementation about this topic:

1. Extra black space below defined extra row of keys
2. Option `extra-keys-style = none` does not hide extra keys row.

**Comment by agnostic-apollo** [comment]
>but it looks like it does not work.
>I used the Ctrl+Alt+K from the hardware keyboard

Hardware keyboard shortcuts != Touch keyboard/Volume Keys shortcuts. Ctrl+Alt+K from the hardware keyboard will toggle the soft keyboard, not the extra keys toolbar.

Read what grimler said above.

>ou can manually hide the extra-keys by long-pressing the keyboard button in the left drawer, or pressing vol up + k or vol up + q, 

Currently, no hardware keyboard shortcut to toggle extra keys. Long press the keyboard button in the side bar.

>Option extra-keys-style = none does not hide extra keys row.

That defines the style of the unicode characters used in the extra keys buttons, it won't disable the extra keys.

>Extra black space below defined extra row of keys

That may be related to using `use-fullscreen-around=true` property and `Terminal Margin Adjustment` setting together. Use either or what works. If issue still exists, then can be looked into.

**Comment by ZaxonXP** [comment]
@agnostic-apollo: OK. Pressing `VolumeUp+k` made the extra keys row disappear (also when long press the keyboard in the side bar). 

The only pity is that there is no hardware button to hide it nor the configuration settings to do this by default. Could you please add these features to some future release?

The black space below is gone when the extra key row disappear. So it could be related to the fact that this key row has smaller vertical size than original.

Thanks for helping.

**Comment by agnostic-apollo** [comment]
> Could you please add these features to some future release?

Okay.

Welcome.

**Comment by CarterSnich** [comment]
Is this already implemented?
