### ISSUE TITLE
[Feature]: How to hide/configure where the session indicator "cloud" should be displayed?

### ISSUE THREAD

**Issue by ZaxonXP** [termux/termux-app#3122]
### Feature description

When the session is created/switched it is indicated in a white cloud in the top of the termux screen. In it there is session number and the name (if it was renamed).

### Additional information

How can I hide these "clouds" or how to configure the placement (I would like to move it to bottom of the screen)?

**Comment by agnostic-apollo** [comment]
Add `disable-terminal-session-change-toast=true` to `~/.termux/termux.properties`.
