### ISSUE TITLE
[Feature]: Document non-obvious settings

### ISSUE THREAD

**Issue by snooppr** [termux/termux-app#3125]
### Feature description

Termux has a terminal setting: `.termux/termux.properties` With an application update, this file does not change for the user and contains incomplete data, for example, it does not contain keys such as "`default-working-directory`";  "`terminal-onclick-url-open`"... 
There is a link to the [wiki](https://wiki.termux.com/wiki/Terminal_Settings)  page in the config, but it is incomplete and does not describe all the possibilities of key. 
And the third option, which is not obvious, is to look into the [source](https://github.com/termux/termux-tools/blob/master/termux.properties)  code, but not all the settings are listed there either, in particular, the "`terminal-onclick-url-open`" key is missing. 
Thus, the user remains unaware of the full settings.  It is obvious that this issue needs to be resolved.

### Additional information

https://wiki.termux.com/wiki/Terminal_Settings -bad

https://github.com/termux/termux-tools/blob/master/termux.properties -bad

.termux/termux.properties -bad

**Comment by agnostic-apollo** [comment]
A docs page will be provided on our site in next version, already written locally but requires some updates.

https://termux.dev/en/docs/
