### ISSUE TITLE
wget doesn't support ssl?

### ISSUE THREAD

**Issue by v0idst4r** [termux/termux-app#314]
When trying to wget anything that uses https, it reports that it is not an http or ftp url.

Example: wget "https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/oh-my-zsh.sh"

http://imgur.com/a/lVUN3

**Comment by fornwall** [comment]
The `wget` program that is pre-installed with Termux is a lightweight version from [busybox](https://busybox.net/) - to install the fully featured GNU wget version supporting https and more options run:

    packages install wget

**Comment by v0idst4r** [comment]
I have installed it with packages but for some reason it still points to the BusyBox version

**Comment by fornwall** [comment]
@v0idst4r Try running `hash -r` before running `wget` again. This clears the bash path cache so that new executables are found.

**Comment by luntik2012** [comment]
what is "packages"?

**Comment by sdrausty** [comment]
@luntik2012 have read this https://wiki.termux.com/wiki/Software article?

**Comment by xeffyr** [comment]
@luntik2012 If you mean 'packages' mentioned in https://github.com/termux/termux-app/issues/314#issuecomment-300595687, then it is a wrapper for 'apt' package manager. It was renamed to 'pkg' in https://github.com/termux/termux-packages/commit/fc0718410cb9e63ddeba8de3fcd9e6531630c7fa.

**Comment by sdrausty** [comment]
@xeffyr > It was renamed to 'pkg' 

> echo 'Usage: packages command [arguments]'

Changed to:
> echo 'Usage: pkg command [arguments]'

Maybe this change should be added as a historical note at https://wiki.termux.com the wiki?

**Comment by sdrausty** [comment]
@luntik2012 you are welcome.
