### ISSUE TITLE
[Bug]: "No such file or directory" running local script as superuser

### ISSUE THREAD

**Issue by Gooberpatrol66** [termux/termux-app#3143]
### Problem description

Termux as superuser can't find executables in the current directory

### Steps to reproduce the behavior.
```
>su
>ls
test.sh
>cat test.sh
#!/bin/bash
echo "works"
>./test.sh
/system/bin/sh: ./test.sh: No such file or directory
```

### What is the expected behavior?

script executes

### System information

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: Oneplus Nord N200

**Comment by agnostic-apollo** [comment]
Need to give executable permission before executing it like that. `chmod +x test.sh`. And should use `sudo` or `tsu` for running commands with root so that environment is properly set.

https://github.com/agnostic-apollo/sudo
