### ISSUE TITLE
[Bug]: Pointer tag was truncated error

### ISSUE THREAD

**Issue by anzhi0708** [termux/termux-app#3146]
### Problem description

This could be an `openjdk-17` issue; I was using a Python NLP package (see https://github.com/konlpy/konlpy/issues/418) which depends on Java (wrapped with Py4j) and "`Pointer tag for 0x76ca5e1860 was truncated.`" was printed, and program was aborted.

### Steps to reproduce the behavior.

1. Install `openjdk-17`
2. Install the Python package `konlpy`
3. Try to create a `konlpy.tag.Kkma` instance with `kkma = Kkma()`
4. Aborted

### What is the expected behavior?

I expected the instance to be created.

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: OPPO Reno2 (PCKM00, ColorOS 11.1)

**Comment by Haiz14** [comment]
I am trying to replicate your issue, i did everything you did but i get this error `No JVM shared library file (libjvm.so) found. Try s
etting up the JAVA_HOME environment variable properly.`

I did set $JAVA_HOME but it doesn't solve the issue `echo $JAVA_HOME /data/data/com.termux/files/usr/bin/java`

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-packages/issues/7332

>I did set $JAVA_HOME but it doesn't solve the issue

`export JAVA_HOME="$PREFIX/opt/openjdk"`
