### ISSUE TITLE
[Bug]: Termux UI crazy shake on Small window mode.

### ISSUE THREAD

**Issue by zixijian** [termux/termux-app#3147]
### Problem description

On Redmi xaga(MIUI) & iqoo8(OriginOS),Termux UI crazy shake on there Small window mode .
I wonder if it has something to do with the screen ratio, these two phones are 20.5:9 & 19.8:9.
I consulted with other people, and a lot of people have this problem.

OriginOS
![IMG_20221217_133449](https://user-images.githubusercontent.com/4952406/208227484-1e24da0c-0e2a-429c-be06-e40e3961c467.jpg)

MIUI
https://user-images.githubusercontent.com/4952406/208227518-24042114-363c-4e27-907d-9b9cee41f4f8.mp4

### Steps to reproduce the behavior.

Open Small Window Mode for termux.

### What is the expected behavior?

You can't watch termux when you switch to other work, and the Small window Termux is shaking like crazy.

### System information

```
TERMUX_API_APP__VERSION_NAME=0.50.1+2c6674f
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~j95nOBhoxCZsl82qMK_9KQ==/com.termux-PQTyH9ZJjihlhV2nR5el4g==/base.apk
TERMUX_APP__APK_RELEASE=UNKNOWN
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-5
TERMUX_APP__PID=8112
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c244,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c244,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10244
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+be66cff
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+be66cff
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
Updatable packages:
libprotobuf/stable 2:3.21.12 aarch64 [upgradable from: 2:3.21.11]
termux-tools version:
1.34.1
Android version:
13
Kernel build information:
Linux 11tp 5.10.101-android12-9-00027-g1292f517889e-ab8602202 #1 SMP PREEMPT Mon May 16 11:18:04 UTC 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
22041216C
```

**Comment by agnostic-apollo** [comment]
Disable `Terminal Margin Adjustment` in termux app settings.

**Comment by zixijian** [comment]
> Disable `Terminal Margin Adjustment` in termux app settings.

It worked.
