### ISSUE TITLE
[Bug]: Cannot install termux

### ISSUE THREAD

**Issue by INeT-NiNjA** [termux/termux-app#3152]
### Problem description

Termux installation cannot be done as 
![Screenshot_2022-12-21-15-57-15-537_com termux](https://user-images.githubusercontent.com/88530392/208886779-30990987-1bea-4885-b797-456a523570d7.jpg)
it displays fileutils error and missing file path but the path exists when I check from my file manager.

### Steps to reproduce the behavior.

I am using redmi 6a Android 9.

### System information

* Termux application version: 0.118.0
* Android OS version: Android 9 
* Device model: Redmi 6a MIUI 11

**Comment by agnostic-apollo** [comment]
Post the notification text.

**Comment by freebrowser1** [comment]
Did you give file access to Termux ? Normally the newly installed app (Termux in your case) prompts for it. 
By default, a newly installed app does not have access to the file system.

**Comment by tareksander** [comment]
The path is for app internal files, which apps should always have access to.

**Comment by Haiz14** [comment]
@INeT-NiNjA plss **post the notification message**

**Comment by shubhamsharmaw** [comment]
Bootstrap error termux
