### ISSUE TITLE
[Bug]: The instalation goes over 100% then shows error

### ISSUE THREAD

**Issue by vladd1234** [termux/termux-app#3159]
### Problem description

I install termux, but instead of stoping at 100%, the app goes over  #100% then shows error ( installing on f-droid)
I have screenshots but i dont know how to put them here
### Steps to reproduce the behavior.

Open f-droid
Atempt to install termux

### What is the expected behavior?

Goes over 100% then appears an error

### System information

* Termux application version:
* Android OS version: android 11
* Device model: Yestel T5

**Comment by Grimler91** [comment]
Sounds more like a fdroid app issue. I have experienced something similar when trying to download and install an app on unstable internet connection

**Comment by agnostic-apollo** [comment]
> I have screenshots but i dont know how to put them here

Click the image icon in github comment field and attach a photo.

> Goes over 100% then appears an error

I agree with grimler, likely fdroid app issue, it often has various issues. You can download apk directly from the site f-droid.org/en/packages/com.termux or force stop fdroid app and try installing again.

Closing since doesn't appear to be a termux app issue itself.

**Comment by vladd1234** [comment]
![Screenshot_20221228-211911](https://user-images.githubusercontent.com/121577814/209972576-856ef2c8-8518-4807-b160-5935bee0475e.png)

**Comment by vladd1234** [comment]
![Screenshot_20221228-211855](https://user-images.githubusercontent.com/121577814/209972610-c5e398e5-455c-4f82-aed9-086aa21b2a02.png)

**Comment by vladd1234** [comment]
@agnostic-apollo here are the screenshots

**Comment by agnostic-apollo** [comment]
> 195% download percentage is a nonsense.

@sylirre You are just limited by your maths man! :p

@vladd1234 Report F-Droid app issues to https://gitlab.com/fdroid/fdroidclient

**Comment by vladd1234** [comment]
And its no other way to get termux or its the sylirres option valid? @agnostic-apollo

**Comment by 2096779623** [comment]
> And its no other way to get termux or its the sylirres option valid? @agnostic-apollo

Download form github.
https://github.com/termux/termux-app/releases/tag/v0.118.0

**Comment by agnostic-apollo** [comment]
You can read about all options at https://github.com/termux/termux-app#installation

Yes, you can trust @sylirre

**Comment by vladd1234** [comment]
Ok,and if i want to install it from @2096779623  s link, i have to download all that or just one link?

**Comment by agnostic-apollo** [comment]
Download `universal` variant if you don't know your phone's arch. Read the link I sent, it has all the details.
