### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by sradityaa** [termux/termux-app#3164]
### Problem description

checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-android
checking target system type... aarch64-unknown-linux-android
checking for a BSD-compatible install... /data/data/com.termux/files/usr/bin/install -c
checking whether build environment is sane... yes
checking for aarch64-linux-android-strip... no
checking for strip... no
checking for a race-free mkdir -p... /data/data/com.termux/files/usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '10528' is supported by ustar format... yes
checking whether GID '10528' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for aarch64-linux-android-gcc... aarch64-linux-android-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether aarch64-linux-android-gcc accepts -g... yes
checking for aarch64-linux-android-gcc option to enable C11 features... none needed
checking whether aarch64-linux-android-gcc understands -c and -o together... yes
checking dependency style of aarch64-linux-android-gcc... gcc3
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for aarch64-linux-android-ar... no
checking for aarch64-linux-android-lib... no
checking for aarch64-linux-android-link... no
checking for ar... no
checking for lib... no
checking for link... link -lib
checking the archiver (link -lib) interface... unknown
configure: error: could not determine link -lib interface

### Steps to reproduce the behavior.

Please help

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
You haven't filled in the template correctly, how can anyone reproduce the issue for example?

My guess would be that you are missing various build tools, try installing build-essential
