### ISSUE TITLE
Select URL doesn't recognise URLs pointing to localhost or localhost:port

### ISSUE THREAD

**Issue by mindbound** [termux/termux-app#317]
URLs of the form `http://localhost:port` are not listed in the Select URL submenu (see screenshot). Termux v0.49, Android Marshmallow 6.0.1, armv7 (Samsung Galaxy Tab A).

![tmp_11255-screenshot_20170517-084456250678449](https://cloud.githubusercontent.com/assets/1147991/26140146/bc96b5b4-3add-11e7-93c4-6d8b3a7cc7e6.png)

**Comment by Wetitpig** [comment]
It should be the problem of this pattern: `"(?:^|[\\W])((ht|f)tp(s?)://|www\\.)" + (([\\w\\-]+\\.)+?([\\w\\-.~]+/?)*" + "[\\p{Alnum}.,%_=?&#\\-+()\\[\\]\\*$~@!:/{};']*)"`
Which means that the characters `http / ftp` or `www.` must be present for URL to be identified.

Found here: ./app/src/main/java/com/termux/app/TermuxActivity.java:678

**Comment by Wetitpig** [comment]
This pattern should be better, supporting all http(s) / ftp / file protocol urls:
`"\\b((?:https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|])"`

Also from same source(http://stackoverflow.com/questions/5713558/detect-and-extract-url-from-a-string)

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app/pull/1237
