### ISSUE TITLE
[Bug]: Termux

### ISSUE THREAD

**Issue by ngewa** [termux/termux-app#3174]
### Problem description

I want the armv8l version of Termux

### Steps to reproduce the behavior.

I want the armv8l version of Termux

### What is the expected behavior?

I want the armv8l version of Termux

### System information

* Termux application version:
* Android OS version:8.1.0
* Device model:SM-G610F

**Comment by agnostic-apollo** [comment]
Use `arm` version from Github or universal from Github/F-Droid.

https://github.com/termux/termux-app#Installation

https://github.com/termux/proot-distro/issues/34

**Comment by agnostic-apollo** [comment]
>I have used this ( https://github.com/termux/termux-app/releases/download/v0.118.0/termux-app_v0.118.0+github-debug_universal.apk ) but the application is not installed

Please use english language only.

Without knowing what gave the error and what error you got, we can't help. You will need to uninstall termux and ALL existing termux plugins from Android Settings -> App first if you installed termux apps from playstore or F-Droid before.
