### ISSUE TITLE
Connection failed. NetHunter Kex login

### ISSUE THREAD

**Issue by balaji020** [termux/termux-app#3176]
### Problem description

![photo_2023-01-08_07-27-08](https://user-images.githubusercontent.com/96853392/211177282-e632f489-a2d0-4a3f-afbd-7af6c51522c7.jpg)
Connection not taking place. Authentication is getting revoked and unable to move forward.

### Steps to reproduce the behavior.

1] Open NetHunter KeX app
2] Enter the password and change the host

### System information

* Termux application version:  0.118.0
* Android OS version: 9PKQT.180917.001
* Device model:

**Comment by agnostic-apollo** [comment]
This repo is for termux app, not NetHunter.

And check https://wiki.termux.com/wiki/Hacking
