### ISSUE TITLE
[Bug]: Only installs Minimal or Nano and will not open in the vnc

### ISSUE THREAD

**Issue by CJMAGTechnology** [termux/termux-app#3179]
### Problem description

I can't get Kex to work on galaxy a13 5g. 
When I first install Kali with Termux I get 2 choices. One is for (minimal) and one is for (nano). I have to choose one to install. The commands I use are: 
kali@kali:~$ termux-setup-storage
kali@kali:~$ pkg install wget
kali@kali:~$ wget -O install-nethunter-termux https://offs.ec/2MceZWr
kali@kali:~$ chmod +x install-nethunter-termux
kali@kali:~$ ./install-nethunter-termux

Then, when I type nethunter kex passwd after the installation completes, I get the error /usr/bin/kex: line 25: vncpasswd: command not found. 
When I try nh kex I get the same error, command not found, for line 19 vncserver, 20 vncserver, 25 vncpasswd, and 30 vncserver.

I then tried to  upgrade using:
sudo apt update
sudo apt full-upgrade -y

This did not resolve the issue. It seems to make it worse because now I can't use any tools. 

termux-app_v0.118.0+github-debug_arm64-v8a.apk denotes it is not compatible with my phone. 

### Steps to reproduce the behavior.

I have uninstalled and installed again multiple times and get the same thing. I've also tried to upgrade and get the same issue. 

### What is the expected behavior?

That I can update the passwd and then open the vnc. 

### System information

* Termux application version: termux-app_v0.118.0+github-debug_universal.apk
* Android OS version: 12
* Device model: Samsung A13 5G

**Comment by Grimler91** [comment]
Indeed, not a termux issue

**Comment by FlowerOfMay** [comment]
Any news? I have the same problem on a Huawei Y5.

**Comment by carryoky** [comment]
What's the solution, I'm experiencing the same issue
