### ISSUE TITLE
Why max sessions

### ISSUE THREAD

**Issue by Wetitpig** [termux/termux-app#318]
Why do we need to set the max number of sessions at 8?

Found here: `./app/src/main/java/com/termux/app/TermuxActivity.java:101:    private static final int MAX_SESSIONS = 8;`

Thanks

**Comment by heyitswither** [comment]
I'm assuming they have put a limit in place to prevent a performance hit from running a bunch of sessions at once. Why would anyone need more than 8 sesssions anyway?

**Comment by v0idst4r** [comment]
`tmux` and `screen` are great packages

**Comment by v0idst4r** [comment]
Scratch screen, doesn't look like Termux has it :(

**Comment by Neo-Oli** [comment]
Try running `apt update`. Screen should be available since a few weeks ago.

**Comment by Wetitpig** [comment]
No, I mean, why should there be a limit? If the user wants to jam the machine, then they do not have this option.

**Comment by v0idst4r** [comment]
If you want to "jam the machine" use `:(){ :|: & };:`

**Comment by Wetitpig** [comment]
...

**Comment by v0idst4r** [comment]
Also if you want more sessions to keep a command running in the background you can add a "&" to the end and it'll run in the background. You can use killall to stop it.
