### ISSUE TITLE
[Feature]: allow using GitHub app to report bugs

### ISSUE THREAD

**Issue by jidanni** [termux/termux-app#3180]
### Feature description

In the GitHub app one is unable to report bugs without switching to a browser due to the templates here.

Therefore please test starting with the GitHub app trying to report a termux bug, without leaving the GitHub app.

### Additional information

All other repositories don't have this problem.

**Comment by agnostic-apollo** [comment]
What exactly is the issue you are facing when posting from the app?

**Comment by jidanni** [comment]
If I choose bug report, for example, here's what I see, in Samsung using Android 12:
![Screenshot_20230111-230053_Android System.jpg](https://user-images.githubusercontent.com/1230959/211840281-86934c13-0a00-43dd-84d9-e8c508a8d905.jpg)

**Comment by agnostic-apollo** [comment]
I suggest you ask github app devs about this, there may be an issue already open about this in their repos if you search. Templates won't be removed, they are part of official github features, not some hack and are needed for useful termux bug reports as @sylirre already mentioned. Support should be added in Github app itself, you can't just ask every repo on github to remove their templates.

**Comment by jidanni** [comment]
OK, filed https://github.com/orgs/community/discussions/44032 .

**Comment by jidanni** [comment]
Okay, they put it on the list of things to do. https://github.com/community/community/discussions/44032#discussioncomment-4675440

**Comment by agnostic-apollo** [comment]
Great!
