### ISSUE TITLE
[Bug]: When using ssh to log in, you can log in even if the user name is wrong.

### ISSUE THREAD

**Issue by SiriusXT** [termux/termux-app#3186]
### Problem description

 When using ssh to log in, you can log in even if the user name is wrong. Is this a bug and a security risk? 

### Steps to reproduce the behavior.

 When using ssh to log in, you can log in even if the user name is wrong. 

### System information

* Termux application version:0.118.0
* Android OS version: 12
* Device model:

**Comment by agnostic-apollo** [comment]
Termux has patched its `sshd` to allow any user. Android assigns the user to termux app and it cannot be changed by users to their choice and neither can it access data of other app users unless default security policies of android itself are disabled, like selinux and so is not a security risk.
