### ISSUE TITLE
[Bug]: Error when forcibly updating repository without confirming information

### ISSUE THREAD

**Issue by talesam** [termux/termux-app#3192]
### Problem description

I always used the following command in my scripts to update the repositories, but without having to confirm configuration files, using only the `-y` option, messages still appear asking what to do with configuration files and I want them not to appear, so I use:
```
pkg update -y -o Dpkg::Options::=--force-confold
```
But now it started giving error.

### Steps to reproduce the behavior.

```
pkg update -y -o Dpkg::Options::=--force-confold
```

### What is the expected behavior?

Update all repositories i.e. `pkg update` without interaction and error.

### System information

* Termux application version: 0.118.0
* Android OS version: 12.1
* Device model: Redmi Note 6 Pro, Custom ROM

**Comment by agnostic-apollo** [comment]
What error?

**Comment by agnostic-apollo** [comment]
Secondly, `pkg update` will update `apt` cache only for last few versions, so won't upgrades all packages which is apparently what you are trying to do instead of  "update all repositories" since you are passing `-y -o Dpkg::Options::=--force-confold` . Use `pkg upgrade` instead to upgrade packages.

https://github.com/termux/termux-tools/pull/17

**Comment by talesam** [comment]
```
~ $ pkg update -y -o Dpkg::Options::=--force-confold
Checking availability of current mirror: ok
Get:1 https://deb.kcubeterm.me/termux-main stable InRelease [512 B]
Err:1 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.
~ $
```

**Comment by talesam** [comment]
Is there any command to choose the best and fastest mirror and then update them?

**Comment by agnostic-apollo** [comment]
That mirror is down, use `termux-change-repo` to switch to default mirror, then run `apt update; apt install termux-tools`.

>Is there any command to choose the best and fastest mirror and then update them?

After updating, run `termux-change-repo` again and choose mirror group.

**Comment by talesam** [comment]
> termux-change-repo
It opens a window, I want something without interaction

**Comment by agnostic-apollo** [comment]
Read both the scripts and figure out how they change and use the mirrors. Modifying `$PREFIX/etc/apt/sources.list` should be enough if using only `apt` and not `pkg`.

**Comment by talesam** [comment]
> Read both the scripts and figure out how they change and use the mirrors. Modifying `$PREFIX/etc/apt/sources.list` should be enough if using only `apt` and not `pkg`.

What is the difference between using apt and pkg? not an alias?

**Comment by agnostic-apollo** [comment]
It's a wrapper for `apt` that cycles mirrors to balance bandwidths usage across them.

https://github.com/termux/termux-tools/tree/master/scripts

**Comment by talesam** [comment]
But I still don't understand the difference between using pkg and apt, what is the native termux?

**Comment by agnostic-apollo** [comment]
`apt` won't cycle mirrors. Search on internet what `apt`  is.

**Comment by talesam** [comment]
I know what apt is, I've been using Linus for over 25 years, I've used several distros, but I thought pkg was the official package manager for termux, that's why I asked, I never understood why it accepts both, so pkg doesn't is the official package manager of it?

**Comment by agnostic-apollo** [comment]
>It's a wrapper for apt

That should have made it clear. `apt` is the official package manager, but users often don't know how to use it properly, like running `apt update` before `apt install`, which `pkg` does automatically. The `pkg` is not a package manager, just a wrapper script for them. It also changes mirror if current is not available. It also supports `pacman` if user is using that instead of `apt`. You can read the script to see what it does, that's why I sent the link. You can use either depending on your reqs and preference.
