### ISSUE TITLE
Nmap Errors

### ISSUE THREAD

**Issue by AdityaElvandel** [termux/termux-app#3197]
### Problem description

Can Someone Help?
I'm Trying To Use Nmap (With Sudo)
But it dosent work
I'm Also Using Termux Nethunter If That Helps
The Error:
┌──(kali㉿localhost)-[~]
└─$ sudo nmap -O [INSERT IP]
Starting Nmap 7.93 ( https://nmap.org ) at 2023-01-19 05:59 UTC
nmap: netutil.cc:3197: int route_dst_netlink(const sockaddr_storage*, route_nfo*, const char*, const sockaddr_storage*): Assertion `p != NULL' failed.
Aborted

### Steps to reproduce the behavior.

Run nmap with sudo

### What is the expected behavior?

It Running OS Scanning And Stuff

### System information

* Termux application version: 0.118.0
* Android OS version: 9
* Device model: Realme 1

**Comment by 2096779623** [comment]
```
~ $ termux-chroot
~ $  nmap -O 127.0.0.1
TCP/IP fingerprinting (for OS scan) requires root privileges.
QUITTING!
~ $ exit
logout
~ $ sudo nmap -O 127.0.0.1
Starting Nmap 7.93 ( https://nmap.org ) at 2023-01-19 14:26 CST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00013s latency).
All 1000 scanned ports on localhost (127.0.0.1) are in ignored states.
Not shown: 1000 closed tcp ports (reset)
Too many fingerprints match this host to give specific OS details
Network Distance: 0 hops

OS detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 1.70 seconds
~ $
```

-O requires the real root authority of the mobile phone, and these nmap functions that require root cannot be used in the proot container.

**Comment by AdityaElvandel** [comment]
Thank You!
