### ISSUE TITLE
'cd /data/media/0' returns Permission denied

### ISSUE THREAD

**Issue by ThePreviousOne** [termux/termux-app#32]
this is the External storage path is it not?

**Comment by fornwall** [comment]
I think the external storage path can very between devices, on a Sony device here it is `/storage/sdcard1/`.

You can make Termux create a symlink to an app-private part of the external storage:

1. Make sure you have an up to date Termux app (version 0.23 or later) and updated packages (`apt update && apt upgrade`).

2. Execute `termux-setup-storage`.

3. If the app can find external storage, a symlink will be setup at `$HOME/storage/external` to a Termux-specific folder in it.

4. By executing `ls -l $HOME/storage/external` you can see the path to it.

**Comment by TheDiamondYT1** [comment]
You need root to view /data.

``su``

Now do it.

**Comment by ThePreviousOne** [comment]
@TheDiamondYT1 yes and by extention /data/data or /data/media but /data/media/0 is the sdcard
I know how permissions work

**Comment by czy1996** [comment]
When I use termux-setup-storage, it shows that 
Open: Permission denied
