### ISSUE TITLE
Software keyboard not appearing

### ISSUE THREAD

**Issue by heyitswither** [termux/termux-app#320]
On my SM-G920V (Verizon Samsung Galaxy S6) running Android 7.0.1 the Termux app does not show the software keyboard. It does work, however, with a hardware keyboard plugged in or using Bluetooth. I am also using GBoard for my keyboard if that makes any difference.

**Comment by Neo-Oli** [comment]
Have you tried opening the left drawer and tapping on "keyboard"?

**Comment by heyitswither** [comment]
@Neo-Oli yes, i have

**Comment by v0idst4r** [comment]
A video would be helpful

**Comment by heyitswither** [comment]
I restarted and it works fine now

**Comment by v0idst4r** [comment]
Gg

**Comment by Matvei27** [comment]
I have the same issue, but it isn't fixed by rebooting.
Device is SM-W2018. It has a hardware keypad, so termux thinks there's a keyboard connected and won't let me toggle the software keyboard.

**Comment by Neo-Oli** [comment]
@Matvei27 There's usually a setting for that in the keyboards settings.

**Comment by Matvei27** [comment]
My device is set to display a software keyboard. It does that just fine in every app except for Termux.

**Comment by stvhas** [comment]
My device; Samsung Tab S4, Android 10, Stock Factory, all updates installed. 
Issue; Soft keyboard will not pop-up when bluetooth keyboard is connected. 
Hackers Software Keyboard installed.
Android Settings option; to show on-screen keyboard when physical keyboard connect, is set  to on.
Soft keyboard, and physical keyboard both operate together ok in other apps, issue is exprienced in Termux only.
Tapping 'keyboad' option in Termux side menu has no effect.
Disconnecting bluetooth keyboard results in soft keyboard functioning as normal, re-connect physical keyboard, and softkeyboard fails to pop-up.

**Comment by ykhandler** [comment]
In samsung tab S7+ you can press the Fn+Lang when using original Keyboard cover. Too bad i cannot find alternatif key in other keyboard...

**Comment by exedore6** [comment]
I'm having a similar issue with my S20 - when a keyboard is connected, termux ignores the "Show on-screen keyboard" flag.

**Comment by shadowquark** [comment]
Same issue.

If I connect a physical keyboard, there always be no screen keyboard, no matter how I choose the settings.

**Comment by w-canvas** [comment]
Same issue.

Running on a note 20, termux ignores "show on screen keyboard" configuration when detecting mx anywhere 2s mouse (registered as a keyboard). Other applications work fine.

**Comment by agnostic-apollo** [comment]
@w-canvas Firstly, install [`v0.113`](https://www.reddit.com/r/termux/comments/ngtzsr/dev_termux_v0113_release/) and try the `KEYBOARD` toggle button in the left drawer.

And which keyboard are you using? Try gboard or [HackerKeyboard](https://github.com/klausw/hackerskeyboard) and **enable** `Show soft keyboard` (always) toggle in `HackerKeyboard` settings.

**Comment by stvhas** [comment]
Samsung Tab S4, Android v10, in my setup, I am using Hacker Keyboard, and
have "Show Soft Keyboard" enabled, and show soft keyboard when Physical
keyboard is connected, there are moments when soft keyboard will refuse to
display specially during external bluetooth keyboard is connected.

**Comment by w-canvas** [comment]
Thank you. Updating with fdroid fixed the issue.

**Comment by agnostic-apollo** [comment]
@w-canvas thanks for confirming, did it require pressing the `KEYBOARD` toggle or it automatically showed up on startup?

@stvhas What version are you on?

>show soft keyboard when Physical keyboard is connected

Where is this setting?

**Comment by w-canvas** [comment]
> @w-canvas thanks for confirming, did it require pressing the `KEYBOARD` toggle or it automatically showed up on startup?

Showed up on startup for both gboard and hacker's keyboard.

"Show soft keyboard" option was off for hacker's keyboard ("when no hardware keyboard is available") but the option was turned on (the default) on the phone's settings (settings -> general management -> physical keyboard -> on screen keyboard - show screen keyboard when physical keyboard is connected).

**Comment by agnostic-apollo** [comment]
Great, that means at least the issue is solved for you since that's the normal state of toggles.
