### ISSUE TITLE
[Feature]: Keyboard minimize and set font.

### ISSUE THREAD

**Issue by aszswaz** [termux/termux-app#3201]
### Feature description

The keyboard that comes with termux-app works great, but when I use [scrcpy](https://github.com/Genymobile/scrcpy) to map my phone's screen to my computer, it's useless and takes up space. scrcpy can use the keyboard of the computer as the keyboard of the mobile phone, so that I don't need to input commands through the virtual keyboard.

Not only scrcpy, but also external keyboard via OTG.

![termux01](https://user-images.githubusercontent.com/57160610/213844497-e36a0f72-c8e3-4957-9b81-50a7af93e7d4.png)

So, is it possible to make the virtual keyboard support hidden?

In addition, I also hope to add a function to set the font. As can be seen from the above picture, the font of termux-app does not support Unicode icons.

### Additional information

I haven't used other mobile terminal emulators, and I don't think I'll be interested in using them in the future, since I like termux-app a lot.

**Comment by agnostic-apollo** [comment]
For disabling extra keys, long hold on keyboard button in left drawer.

For fonts, either use Termux:Styling or manually replace font file and run `termux-reload-settings`.

https://wiki.termux.com/wiki/Termux:Styling
