### ISSUE TITLE
Nethunter Kex

### ISSUE THREAD

**Issue by AdityaElvandel** [termux/termux-app#3203]
### Problem description

Hello I'm Running Termux Nethunter
But I Get This Error
When Trying To Run GUI
/usr/bin/kex: line 25: vncpasswd: command not found
Nethunter CLI Runs Fine

### Steps to reproduce the behavior.

Type "Nethunter Kex passwd" 

### What is the expected behavior?

Password Input

### System information

* Termux application version: 0.118.0
* Android OS version: 9
* Device model: Realme 1

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
