### ISSUE TITLE
App is not installing 

### ISSUE THREAD

**Issue by ajit56** [termux/termux-app#3206]
### Problem description

I downloaded termux from f droid , termux.com but when I click on app to install it,it says "do you want to update the app". I haven't installed app and it's plugins 

### Steps to reproduce the behavior.

I don't know if this only happens with me 
1.downlod the app
2.click on app
3. it will say do you want to update app
4. click on update
5. It shows that "pakage appear to be invalid"

### What is the expected behavior?

It will say app not installed 

### System information

* Termux application version:0.118.0
* Android OS version:12
* Device model: samsung galaxy m31

**Comment by ajit56** [comment]
![Screenshot_20230123-062723_Package installer](https://user-images.githubusercontent.com/97656561/213950342-295aab0f-4a8d-470b-9ae7-8bbeb73565bf.jpg)

**Comment by ajit56** [comment]
![Screenshot_20230123-062832_Package installer](https://user-images.githubusercontent.com/97656561/213950361-4df8536f-c984-4e6d-90a1-f709e02f3f0d.jpg)

**Comment by ajit56** [comment]
![Screenshot_20230123-062850_Settings Suggestions](https://user-images.githubusercontent.com/97656561/213950376-12480fb6-3775-4974-8167-e0aae38bf0d7.jpg)

**Comment by ajit56** [comment]
Last screenshot is of settings app

**Comment by Grimler91** [comment]
Uninstall termux-app, and all addon apps, before installing from github. You can find it in settings->apps if it doesn't appear on home screen or similar

**Comment by ajit56** [comment]
https://user-images.githubusercontent.com/97656561/214043822-0287ad2f-cf92-4f48-816b-ac10f57da661.mp4

**Comment by ajit56** [comment]
There is no termux in my device

**Comment by ajit56** [comment]
> Make sure you are downloading and installing this apk file: https://github.com/termux/termux-app/releases/download/v0.118.0/termux-app_v0.118.0+github-debug_universal.apk
> 
> Don't install (upgrade) the apk file over existing F-Droid or Play Store installations. In this case you need to **uninstall first** the Termux app and all add-ons through Android system settings: Termux:API, Termux:Boot, Termux:Float, Termux:Styling, Termux:Task, Termux:Widget.

This doesn't work

**Comment by agnostic-apollo** [comment]
Check https://www.reddit.com/r/termux/comments/uonv9s/comment/i8fuofc/?context=999

**Comment by ajit56** [comment]
Is there any other method without any device ?

**Comment by agnostic-apollo** [comment]
There are other apps than termux that provide on-device adb wireless shell, like Tasker.

**Comment by Jsirya** [comment]
Hi , I some how got a situation like that , I installed the Adguard  ad blocking app and also scanned from the miui security app not sure if relevent could have been something else and  then just vanished ,  can't find it  in settings app list nor the search bars , and also can't install either , but I used to make some file in storage nd some dls they are still there , I tried opening as using termux but can't find it even there .

**Comment by agnostic-apollo** [comment]
As per the  link above, after trying to install termux, run `adb logcat -d > logcat.txt` from pc and check output for errors from package manager or post it here after removing any potential personal info or email me.

Or you may still have an app installed with `com.termux` `sharedUserId`.

You can check with something like `adb shell dumpsys package | grep -A5 -B5 -E "sharedUser.*com.termux"`

Without the logs, we can't guess what's wrong on your specific device.

Trying to install termux in secondary user/profile and uninstalling it from primary user only can cause problems too, although it still shows in apps list and can be installed from other users from the options button in termux app info page.

**Comment by ajit56** [comment]
Any other method to solve problem ?

**Comment by agnostic-apollo** [comment]
Thoughts and prayers...

Since unlikely logs will be provided, so closing...

**Comment by agnostic-apollo** [comment]
You can also try another apk installer app that shows android internal errors for installation failure. Like https://f-droid.org/en/packages/com.aefyr.sai.fdroid/

Use system file picker inside the app and select termux apk downloaded from F-Droid or GitHub.

You would need to grant it install apps permission too from app info.

**Comment by nexusprime-here** [comment]
the same problem here
