### ISSUE TITLE
[Bug]: chmod +x install - nethunter - termux - "results in 'chmod --help' for more information"

### ISSUE THREAD

**Issue by pakmansta** [termux/termux-app#3207]
### Problem description

new device, installed termux to test it's abilities, simply stops at step 4 or 5 in the setup of kali on a android.

### Steps to reproduce the behavior.

once you get to the part were you can change permissions it locks and doesn't proceed any where past that point!

Android Kali
NetHunter
Rootless Install
13.
Change the permissions so that you can execute the file:
chmod
+x install
-
nethunter
-
termux

### What is the expected behavior?

I should have the ability to install the software after i've adjusted permissions but at this point I can't.....

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
Ask whoever wrote whatever script you are running for help.
