### ISSUE TITLE
[Need Help] No such file or directory

### ISSUE THREAD

**Issue by SaintNoodles** [termux/termux-app#3216]
### Problem description

![IMG_20230127_174401](https://user-images.githubusercontent.com/108394306/215060071-2d4e6262-b06a-4675-b3bb-360d4a759bfe.jpg)

I'm having a problem after downloading nethunter

 [*] Configuring NetHunter for Termux ... ./install-nethunter-termux: line 363: kali-arm64/etc/sudoers.d/kali: No such file or directory

### Steps to reproduce the behavior.

It's not a bug.

### System information

* Termux application version: termux-app_v0.118.0+github-debug_arm64-v8a.apk
* Android OS version: 8
* Device model: Huawei nova 2i

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
