### ISSUE TITLE
[Bug]: How to fix this problem

### ISSUE THREAD

**Issue by hhm1** [termux/termux-app#3223]
### Problem description

When I installed termux on Android 10, I encountered a problem

```
W: GPG error: https://mirrors.ustc.edu.cn/termux/apt/termux-main stable InRelease: At least one invalid signature was encountered.
E: The repository 'https://mirrors.ustc.edu.cn/termux/apt/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.
```
When I try to replace another device, it's OK

### Steps to reproduce the behavior.

First install termux, and then use the apt update command

### What is the expected behavior?

Replace the mirror source

### System information

* Termux application version:0.118.0
* Android OS version:10
* Models that can be used normally:Samsung SM-G6100
*  Models that cannot be used normally:A virtual machine

**Comment by Grimler91** [comment]
So termux-change-repo does not help? In that case I guess you are using some virtual machine (which one?) that lacks necessary features

**Comment by hhm1** [comment]
It's from China，Chinese name:光速虚拟机

**Comment by 2096779623** [comment]
> These "virtual" environments are not supported by Termux. They have a number of issues including broken apt-key.

`光速虚拟机` is the Chinese version of vphonegaga.
