### ISSUE TITLE
[Bug]: pip install pandas compile error

### ISSUE THREAD

**Issue by mablue** [termux/termux-app#3225]
### Problem description

I got this error message when allways I want to install pandas:
https://pastebin.com/qWSjLQaf

### Steps to reproduce the behavior.

```
pip freeze > unins && pip uninstall -y -r unins && rm unins
pip cache dir
rm -rf /data/data/com.termux/files/home/.cache/pip
pip install pandas

```

### What is the expected behavior?

a simple installed pandas🥲🐼🐼
its very important package please append a major support pkg package to it.cuz it's an important pyton package and We nneed more support on it as python programmers. If somebody can make a pkg package like python-cryptography and etc to it we will be happy

### System information

* Termux application version: 118
* Android OS version: 13
* Device model: mi9t pro

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/issues/12412

**Comment by mablue** [comment]
You saved my life...Thanks 🙏
```
pip install --no-use-pep517 pandas
```
https://github.com/termux/termux-packages/issues/12412#issuecomment-1281125508

pleeeease append it to termux python wiki

**Comment by itsbiillgatesyall** [comment]
pkg i python-pandas
