### ISSUE TITLE
[Bug]: swipe not working on keyboard

### ISSUE THREAD

**Issue by rubo77** [termux/termux-app#3226]
### Problem description

I am used to type via the swipe method on my android.
In termux swipe is not working

### Steps to reproduce the behavior.

Swipe over the keyboard

### What is the expected behavior?

Only the last letter is typed

### System information

* Termux application version: 0.118
* Android OS version:12
* Device model:
Samsung S10 plus

**Comment by agnostic-apollo** [comment]
Use Text input view.

https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View

**Comment by rubo77** [comment]
great!

> To access the text input view you have to swipe the extra keys view to the left.
