### ISSUE TITLE
/system/bin/am: Permission denied

### ISSUE THREAD

**Issue by Filip-K** [termux/termux-app#323]
Hi! I just installed Termux on my Android 5.0.1 device, ran `apt update && apt upgrade`, then `termux-setup-storage` and got
```
/data/data/com.termux/files/usr/bin/am: 3: exec: /system/bin/am: Permission denied
```
Does it mean `termux-setup-storage` does not work on 5.0.1?

This is not a duplicate of termux/termux-api#26 as I can't even touch /system/bin/am with a `ls`.

**Comment by xeffyr** [comment]
`/data/data/com.termux/files/usr/bin/am` no longer use /system/bin/am so issue is outdated.
