### ISSUE TITLE
[Feature]: Documentation on how to roll my own termux APK with additional packages and scripts pre-installed in the bootstrap.zip

### ISSUE THREAD

**Issue by shaunmulligan** [termux/termux-app#3239]
### Feature description

I would like to include termux into an androidOS I am building but would like to include several packages and scripts by default to run on first launch of termux. From what I understand there is a group of packages/scripts added to bootstrap.zip and that is pulled into the APK at build time. 

It would be great if there was documentation on how to customize bootstrap.zip and then how to include it in the APK build.

### Additional information

not that I'm aware of.

**Comment by shaunmulligan** [comment]
perhaps it's enough to just change https://github.com/termux/termux-app/blob/master/app/build.gradle#L185 to point to a forked version of termux-packages releases and update the SHA256 for the checksum too? Does anyone know if that would work?

**Comment by shaunmulligan** [comment]
Just found this https://github.com/termux/termux-packages/wiki/For-maintainers#build-termux-app in the wiki, which is basically what I think I'm after

**Comment by agnostic-apollo** [comment]
Docs are already available at https://github.com/termux/termux-app#Forking

There are also some issue related to `build-bootstrap.sh` that need fixing like subpackages, etc.
