### ISSUE TITLE
[Bug]: Tidak bisa update pip

### ISSUE THREAD

**Issue by FSElzy** [termux/termux-app#3240]
### Problem description

Saya mengalami masalah di saat saya mau update pip muncul ERROR: Installing pip is forbidden, this will break the python-pip package (termux). Di saat saya ingin install tools metasploit saya juga mendapatkan masalah yang sama yaitu ERROR: Installing pip is forbidden, this will break the python-pip package (termux).

### Steps to reproduce the behavior.

Kode update pip. python3 -m pip install --upgrade pip silahkan di coba siapa tau di kalian juga mengalami hal yang sama seperti saya.
![Screenshot_2023-02-08-11-11-59-77](https://user-images.githubusercontent.com/124756341/217431602-d30cac1c-fd9f-429d-b11b-7baa17c369df.jpg)

### What is the expected behavior?

Saya berharap ada yang mengasih solusi atau perbaikan termux tentang masalah ini, jika ada yang punya solusi saya minta tolong untuk kasih tau saya Terima kasih.

### System information

* Termux application version: 0.118.0
* Android OS version: 8.1.0
* Device model: CPH1909

**Comment by Grimler91** [comment]
Update pip by updating the python-pip package through pkg(/apt)
