### ISSUE TITLE
[Bug]: Long holding keyboard in side panel not hiding buttons

### ISSUE THREAD

**Issue by parkerlreed** [termux/termux-app#3258]
### Problem description

When using the GitHub Actions builds, unable to hide the button bar. It still vibrates when you hold "Keyboard" but the button bar does not get toggled. 

### Steps to reproduce the behavior.

1. Install latest Actions builds
2. Swipe in from left to open the side panel
3. Long hold "Keyboard"

### What is the expected behavior?

Button bar hiding. 

### System information

* Termux application version: 0.118.0+2f5a6f7
* Android OS version: Android 12
* Device model: Samsung Note 10 Plus

**Comment by Paguiar735** [comment]
What build are you talking about? v0.118.0?

**Comment by parkerlreed** [comment]
Thank you!

**Comment by agnostic-apollo** [comment]
Welcome. Apologies for the delay.
