### ISSUE TITLE
Amazon App Store

### ISSUE THREAD

**Issue by ghost** [termux/termux-app#326]
Any chance that you can please get this app into the Amazon store for Fire tablets, please?

Thanks.

**Comment by fornwall** [comment]
@soaringowl2145 Would you be ok with installing from [F-Droid](https://f-droid.org/) where Termux is available?

**Comment by soaringowl2145** [comment]
Yes I would be.  However by adding it to the Amazon store we can reach more users that do not know about F-Droid.

**Comment by biazzotto** [comment]
It's not possible to install from F-Droid right now... it's broken...

**Comment by fornwall** [comment]
@biazzotto Installing from F-Droid should work now:

1. Make sure to update and install the latest version (0.50) as the previous version was broken in F-Droid.
2. If you have installed Termux or any Termux add-on through the Play Store, be sure to completely uninstall all them, as you cannot mix installs from the Play Store with those from F-Droid.
3. Note that the app requires Android 5.0 or later.

**Comment by lukeeey** [comment]
@fornwall While that's all well and good, it doesn't take that much effort to submit to the Amazon app store and it requires no changes to the app (https://developer.amazon.com/app-submission)

The app could later be optimised to work on the Fire TV and Fire TV Stick devices.

**Comment by lukeeey** [comment]
Same

**Comment by lukeeey** [comment]
This is not resolved as far as I am aware.
