### ISSUE TITLE
[Bug]: libssl.so.1.1 not found

### ISSUE THREAD

**Issue by mxtilx** [termux/termux-app#3264]
### Problem description

apt update
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found

### Steps to reproduce the behavior.

pkg install openssl
apt upgrade

### What is the expected behavior?

apt upgrade can work

### System information

* Termux application version:0.101
* Android OS version:10
* Device model:oppo

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

https://github.com/termux/termux-app#google-play-store-deprecated
