### ISSUE TITLE
[Bug]: libandroid-support.so android 5

### ISSUE THREAD

**Issue by M4Dev-code** [termux/termux-app#3269]
### Problem description

i am using termux 0.79 offline-bootstraps and i installed php package but when i try to run laravel project with php artisan serve it say cann't link excutable libandroid-support.so not found
i tried apt update && apt install tsu and the same error i installed the library again and the same error
also i try unistall the app and reinstall it but same error i try also export ld_library_path and same error

### Steps to reproduce the behavior.

php artisan serve

### What is the expected behavior?

give success build for the laravel project

### System information

* Termux application version: 0.79 offline bootsrapes
* Android OS version: 5.0
* Device model: samsung

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/wiki/Termux-on-android-5-or-6
