### ISSUE TITLE
"touch: file.jpg: Operation not permitted" when trying to modify timestamp via touch

### ISSUE THREAD

**Issue by neo0x3d** [termux/termux-app#327]
I have a script which changes the timestamp of a file accoring to it's filename: (works fine on linux)

#!/bin/bash
for file in *.jpg
do
    test -f "$file" || continue
    # cut out the section with the timestamp (fixed width) and remove all _
    ts=$(echo ${file:4:15} | sed 's/_//g')
	# insert . before seconds to put it into the format requested by touch ([[CC]YY]MMDDhhmm[.ss])
	ts=${ts:0:12}.${ts:12:14}
    touch -t $ts $file
done  

I'd like to use this to fix all the timestamps in my DCIM/Camera folder, since they're fucked up after I manually copied them over from my old device.
I enabled storage access, the images have following permissions (output from ls -la):
-rw-rw---- 1 root everybod ....

My user is u0_a150, but it is not member of the group everbod :(

Using a Moto G5, Android 7.0

I guess I can't edit the files because my user not being a group member of everybod. Is it possible to fix this or is this just the pain in the ass of an unrooted Android?

**Comment by neo0x3d** [comment]
tried it via adb shell on a demo txt file:

cedric:/sdcard/DCIM/Camera $ touch -t 05050505 testfile.txt                                                                     
touch: 'testfile.txt': Operation not permitted

Seems like an Android restriction to me :/

**Comment by its-pointless** [comment]
It is an android restriction. Doing same command in termux $HOME will work.

**Comment by fornwall** [comment]
As @its-pointless says, it is indeed a system limitation, so unfortunately nothing can be done from the Termux side on this.
