### ISSUE TITLE
[Feature]: Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [termux/termux-app#3271]
### Feature description

Please add support for the Android 13 "Themed Icons".

![Screenshot_2023-02-27-03-00-43-138_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/221444047-6950f1c7-aca0-4392-abca-6ba1f093dc90.jpg)

### Additional information

https://www.androidpolice.com/android-13-themed-icons-how-to-activate/

**Comment by 2096779623** [comment]
https://github.com/termux/termux-app/pull/2994
