### ISSUE TITLE
[Bug]: files permission denied

### ISSUE THREAD

**Issue by NaviTheCoderboi** [termux/termux-app#3280]
### Problem description

I am working on a next js site on my mobile using termux. But when i start it using 
```bash
yarn dev
```
It gives me this error 
![IMG_20230303_144452](https://user-images.githubusercontent.com/102732282/222680950-ad1e8488-3e1d-4eb8-b7d7-6c500b9a4e0c.jpg)
Even i have the given termux the  storage permission 

### Steps to reproduce the behavior.

1: open termux
2: install node js and yarn 
3: run yarn set version berry
4: go to any folder and run yarn dlx create-next-app test
5: run cd test && yarn dev

### What is the expected behavior?

The expected behaviour is that it should start my site and i am able to see it in my browser. 

### System information

* Termux application version: v0. 118.0
* Android OS version: 9
* Device model: mobile- OPPO A31 | CPH2015

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/Internal_and_external_storage

Don't run your code in the `/storage/emulated/0`, please move to `$HOME`  it maybe will works.

**Comment by NaviTheCoderboi** [comment]
@2096779623 what and where is $HOME?

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-packages/wiki/Termux-file-system-layout#home-directory
