### ISSUE TITLE
Keyboard Problems

### ISSUE THREAD

**Issue by zenstone2** [termux/termux-app#3294]
Hi, when i use the app with celiakeyboard ( the default keyboard for Huawei phones), this doesn't write, but when i hit the number row it does...
Disclaimer: this work well  on Microsoft's keyboard.

**Comment by agnostic-apollo** [comment]
Most likely need to enabled `enforce-char-based-input`

https://wiki.termux.com/wiki/Terminal_Settings#Workaround_issues_with_some_keyboards
