### ISSUE TITLE
termux pkg

### ISSUE THREAD

**Issue by Dwebb22** [termux/termux-app#3300]
### Problem description

Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://grimler.se/termux-packages-24
CANNOT LINK EXECUTABLE "apt": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libapt-pkg.so"...

what is this?

### Steps to reproduce the behavior.

h8h?

### What is the expected behavior?

pkg installation

### System information

* Termux application version:termux
* Android OS version: cricket
* Device model: idk

**Comment by TomJo2000** [comment]
You seem to be running the Google Playstore version of Termux, which is deprecated.
Please consider updating to the [F-Droid](https://f-droid.org/en/packages/com.termux) or [GitHub](https://github.com/termux/termux-app/actions) release.
For additional information please see the following (paraphrased from the [Termux Discord](https://discord.gg/termux-641256914684084234)'s PSA about the topic).
> Termux on Google Play store is OUTDATED!
> Termux and its plugins are no longer updated on Google Play due to Google Play now requires the target API to be ≥28 which causes some issues on Android ≥10 and have been deprecated.
> 
> Please switch to F-Droid version for stable release!
> https://f-droid.org/en/packages/com.termux
> 
> To avoid problems while switching:
> In Settings > Applications, Find all applications on your phone named Termux:
> - Termux:API
> - Termux:Styling
> - Termux:Widget
> - Termux:Task
> - Termux:Float
> - Termux:Boot
> Then uninstall all of them (yes, including paid ones)
> If you need help with backing up your current files:
> https://wiki.termux.com/wiki/Backing_up_Termux

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

https://github.com/termux/termux-app#google-play-store-deprecated
