### ISSUE TITLE
Submit to Galaxy Store?

### ISSUE THREAD

**Issue by finagolfin** [termux/termux-app#3303]
### Feature description

I have been moving away from the Play Store, given their increasingly silly requirements and political banning, and was surprised to find the Galaxy Store from Samsung has a lot of apps. While I use F-Droid for OSS apps, it only has a fraction of the users, so we should submit Termux to Galaxy too, especially since Termux is being phased out of the Play Store.

What do you think, @agnostic-apollo and @Grimler91, can we get a new release and submit Termux to the Galaxy Store?

**Comment by agnostic-apollo** [comment]
Grimler and I have already planned to release next update on samsung store. It might be a good idea to do it. Another signing key would be an issue, but I guess can keep it same as the one released on our site if that's done. Probably should host all apks somewhere.

**Comment by TehDomic** [comment]
> Grimler and I have already planned to release next update on samsung store. It might be a good idea to do it. Another signing key would be an issue, but I guess can keep it same as the one released on our site if that's done. Probably should host all apks somewhere.

I volonteer to host a mirror for anything necessary m

**Comment by gutierri** [comment]
This task seems to be very beneficial, mainly because it is another alternative to raw installation (via APK).

How can we organize ourselves to contribute to it? Maybe looking at CI/CD automation? Credentials? Any initial implementation and presentation on this task?

I believe this goes beyond code.

**Comment by finagolfin** [comment]
I don't think this is realistic anymore, as the Galaxy Store has [put in a minimum requirement of API 33 for global, ie non-Chinese, apps, starting November 1](https://seller.samsungapps.com/notice/getNoticeDetail.as?csNoticeID=0000008212). [The current requirement to submit or update an app for all countries is API 26](https://seller.samsungapps.com/notice/getNoticeDetail.as?csNoticeID=0000007234) best [I can tell](https://seller.samsungapps.com/notice/getNoticeDetail.as?csNoticeID=0000007772). So unless we can rush something in in the next 12 days, it's not going to happen.

**Comment by finagolfin** [comment]
Well, the deadline has passed and we do not support setting `TargetSDKVersion` 33, so closing this.

I have suggested to @agnostic-apollo that he produce a Termux Basic app with only a larger bootstrap, with downloading the non-bootstrap Termux packages from the network disabled. If we slightly change the app build so that it includes only the binaries, ie the executables and shared libraries, from the bootstrap packages and the apt package installation for this Termux Basic app simply adds symlinks in `$PREFIX` for the binaries and downloads the rest, ie text files, from a mirror like always, we could produce a Termux Basic app that works on the Play Store and other app stores targeting API 33. If someone tries to download a package not in the bootstrap, we'd have apt tell them to go install the full Termux from F-Droid or github.

That could be a way forward, let's see.

**Comment by agnostic-apollo** [comment]
Ooh nooo, I missed a deadline! Impossible!

**Comment by finagolfin** [comment]
To be clear, I never really cared that much if we got this in before the deadline, and didn't try to get you to get it in before.

**Comment by agnostic-apollo** [comment]
I didn't think you were. However, getting termux on samsung store at some point would be a good idea.
