### ISSUE TITLE
[Feature]: Implement accesibility support for Talkback users

### ISSUE THREAD

**Issue by humenda** [termux/termux-app#3305]
Termux currently is inaccessible for blind users using Talkback. It would be
great if accessibility support could be added.

IMHO, it may be possible to rework the view conditionally (if Talkback is
enable) to make each line being reported as a text area. This way, the talkback
user would e able to read each line individually, as in other apps using text
areas.

**Comment by Damaj301damaj-lol** [comment]
Q: how do blind linux users use the terminal?
Q2: how would it behave well with apps such as weechat/vim/apps that have a ncurses Ui?

**Comment by humenda** [comment]
>Q: how do blind linux users use the terminal?

That varies. Essentially there are two ways:

1.  Work from prompt to prompt, with the difference being read aloud. I.e.
    \`date\` → the date is read aloud + the next prompt.
2.  Line by line. This is much simpler to implement and essentially what I'm
    using. The focus is always positioned at the cursor and review happens by
    screen-reader-specific commands to navigate up/down from the cursor.

    Translating this to Android: to present text, it is usually sufficient to
    present text in textareas. However, if Termux would make a single text
    area, the screen reader Talkback would read the whole Terminal at once,
    hence the suggestion to make each line a text area. This would pretty much
    mimic  what is done for variant 2) for GNU/Linux.

>Q2: how would it behave well with apps such as weechat/vim/apps that have a ncurses Ui?

This depends. For Android, this might need trickery - not sure. For GNU/Linux,
2) is actually seamless. The focus is anyway at the cursor, and I can navigate
up/down, line by line, to navigate the screen. Whenever there is enough
context acquired, pressing a key anway changes the cursor, hence pulls the
focus back to the cursor. This is BTW how I'm writing this.

**Comment by agnostic-apollo** [comment]
Related #2543
