### ISSUE TITLE
Termux has different signing keys

### ISSUE THREAD

**Issue by yirod3721** [termux/termux-app#3311]
### Problem description

i used to have termux from the play store but then i decided to swtich to f-droid so i uninstalled termux and and downloaded the f-droid version but it says app not installed and SAI says the shared signatures do not match 

### Steps to reproduce the behavior.

download termux from play store 
uninstall
download from f-droid
then try to install it

### What is the expected behavior?

shouldnt have the same signing key as the other versions

### System information

* Termux application version:
* Android OS version: 8.1
* Device model:Redmi note 5

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

**Comment by yirod3721** [comment]
so what do i do now

**Comment by yirod3721** [comment]
i followed the instructions deleted everything termux related and it still wont work

**Comment by yirod3721** [comment]
@sylirre i followed those instructions and I even found a similar issue in the termux:gui page(https://github.com/termux/termux-gui/issues/4)(i think that it is the same problem)  and it still didnt work

**Comment by agnostic-apollo** [comment]
Provide output of `adb shell "pm list packages -u --user 0 | grep termux"` with an `adb` shell or `su -c "pm list packages -u --user 0 | grep termux"` with a `root` shell.

https://developer.android.com/studio/command-line/adb

**Comment by yirod3721** [comment]
i just tried it with adb and it says install failed shared user incompatible

**Comment by yirod3721** [comment]
@agnostic-apollo it says package:com.termux.api

**Comment by yirod3721** [comment]
it just worked
thanks a 1000

**Comment by yirod3721** [comment]
i had to uninstall com.termux.api

**Comment by yirod3721** [comment]
i dont have a laptop or pc so i use it for programming
