### ISSUE TITLE
[Bug]: Can't run `pm`

### ISSUE THREAD

**Issue by Rudxain** [termux/termux-app#3322]
### Problem description

This seems related to #1209 .

I get this error:
```
cmd: Failure calling service package: Failed transaction (2147483646)
```

### Steps to reproduce the behavior.

0. Open Termux, without root
1. Type the command `pm --help` (or any subcommand of `pm`)
2. See the printed error message

### What is the expected behavior?

It should run the command, just like Llamalab Automate does. No need for ADB

### System information

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: SM-A315G

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-packages/discussions/8292#discussioncomment-5102555

**Comment by xargscat** [comment]
solve whit this disscusion https://github.com/termux/termux-api/issues/354#issuecomment-3066346864
