### ISSUE TITLE
Nethunter url https://offs.ec/2MceZwr is not working[Bug]: 

### ISSUE THREAD

**Issue by Iph50** [termux/termux-app#3323]
### Problem description

The nethunter url https://offs.ec/2MceZwr is not working it's says 404 error not found

### Steps to reproduce the behavior.

wget -O install-nethunter-termux https://offs.ec/2MceZwr 

### What is the expected behavior?

It said 404 error not found :(

### System information

* Termux application version:
* Android OS version:
* Device model:
Samsung s8

**Comment by agnostic-apollo** [comment]
This is issuetracker for termux app, not nethunter. Also https://wiki.termux.com/wiki/Hacking
