### ISSUE TITLE
[Feature]: Themed icon support

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [termux/termux-app#3329]
### Feature description

Why not add support for the themed icon Android feature for a nice modern touch?

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

### Additional information

https://9to5google.com/2022/12/09/android-13-themed-icons/

**Comment by ctntt** [comment]
Duplicate of https://github.com/termux/termux-app/issues/3271
