### ISSUE TITLE
Choose architecture

### ISSUE THREAD

**Issue by John-Colvin** [termux/termux-app#333]
I have things I want to do in termux that need 32 bit libraries (that don't appear to support multilib), but I have an aarch64 device. I see there's an autodetect function to decide which architecture to install, it would be great to be able to let the user decide.

**Comment by xsacha** [comment]
You could add repositories (including 32-bit) from ~/../usr/etc/apt/sources.list

**Comment by xeffyr** [comment]
>  I see there's an autodetect function

Termux uses core libs from Android and we need to prevent architecture mismatching. That's why autodetect is required.

Another thing we do not support multiarch (multilib) installation. If you really need 32-bit packages, you can download them manually.
