### ISSUE TITLE
[Bug]: libudev: udev_monitor_new_from_netlink_fd: error getting socket: Permission denied

### ISSUE THREAD

**Issue by Android-PowerUser** [termux/termux-app#3330]
### Problem description

I'm trying to get Steam running with Box64 on Ubuntu in PRoot. Ptitseb, the developer of Box64 says it's probably because of `libudev: udev_monitor_new_from_netlink_fd: error getting socket: Permission denied.` https://github.com/ptitSeb/box86/issues/699#issuecomment-1492968015
Is there a workaround now?

### Steps to reproduce the behavior.

Compile and install Box64 and Box86 on Ubuntu with PRoot. Use bash of Box64 try Box64 steam.

### What is the expected behavior?

Steam should start.

### System information

* Termux application version: 0.118
* Android OS version: 11
* Device model: Galaxy A12

**Comment by twaik** [comment]
Termux is running in android's application sandbox. These sandboxes will never be allowed to connect netlink sockets.

**Comment by Android-PowerUser** [comment]
I was already aware that without root, the Android netlink socket will never be obtained. But perhaps PRoot can be used to simulate the socket, or Steam can be convinced not to use libudev. Maybe libudev could just give a standard response.

**Comment by twaik** [comment]
It is impossible without patching libudev inside proot-distro container.

**Comment by twaik** [comment]
@agnostic-apollo I think that issue can be closed.
