### ISSUE TITLE
[Feature]: Terminal customizing  

### ISSUE THREAD

**Issue by Starmania** [termux/termux-app#3331]
### Feature description

Hello!
Could we have some settings of to customize the size of the terminal and the line warping ?

I could find some discussion where `printf "\033[?7l"` is proposed in #58 but it seems to not work anymore...

I know you could zoom in the terminal but it's not enought...

**Comment by 2096779623** [comment]
![Screenshot_20230406-224301](https://user-images.githubusercontent.com/57583560/230414686-918ad657-ef04-4567-92c3-86d90cb775bd.png)

Disable line wrapping: `tput rmam` .
Enable line wrapping: `tput smam`.

**Comment by Starmania** [comment]
Thanks. A lot

**Comment by Paguiar735** [comment]
> Thanks. A lot
> 
> Ps: tput shrink the text

Since it's solved, do you mind closing this issue?
