### ISSUE TITLE
[Feature]: Share to Termux - Disable switching apps

### ISSUE THREAD

**Issue by Programming-Lynx** [termux/termux-app#3332]
### Feature description

Allow sharing links to Termux without switching over apps every time.

### Additional information

Currently when you click on a share link to share it with Termux, the Turmux application is opened and the app switches to Termux. I would like to propose the ability to open the link/file in the background and have whatever code you have set up run its magic. This would allow you to share multiple links in rapid succession without having to switch back from apps every single link.

This should probably have a setting in termux.properties or as a line in the code at the beginning of your termux-url-opener file.,

**Comment by Paguiar735** [comment]
What would the use case be?

I mean, do you want the text you shared via Android share intent to show up in Termux' terminal or the file you shared to appear in Termux's home folder?

**Comment by Anonymous2716** [comment]
@Paguiar735 I think it would be nice to have a  little pop up on share confirmation on file sharing instead of switching over yo the downloads folder and opening a new session every time. Which is limited to Max 8 (which I think is good to limit ).

**Comment by agnostic-apollo** [comment]
> do you want the text you shared via Android share intent to show up in Termux' terminal or the file you shared to appear in Termux's home folder?

They are talking about ` termux-url-opener`, not files.

https://wiki.termux.com/wiki/Intents_and_Hooks

>I would like to propose the ability to open the link/file in the background and have whatever code you have set up run its magic.

That is not possible, android only shares stuff with activities, so termux app would have to start and show its activity, even if the theme is used to make it translucent.

Secondly, any app having the ability to share a url with termux without even a confirmation dialog showing the url being shared and passing it to the receiver script is a huge security risk and I don't know why original author even did that. The url could be malicious, which the script could connect to, resulting in the device possibly getting hacked, or downloading a malicious file.

In my initial rewrite which is yet to be pushed, a dialog will show with the url shared before the receiver script is executed. When files are shared, the file being shared will also show in the dialog. I know some people may have specific requirements, so in future, users will be able to define a regex map for url/file paths against custom receiver scripts that should (automatically) be executed.

>I think it would be nice to have a little pop up on share confirmation on file sharing

A dialog already shows for file sharing.
