### ISSUE TITLE
Connection error 

### ISSUE THREAD

**Issue by Biswanath12** [termux/termux-app#3339]
### Problem description

Whenever I try to run any command for package installation it shows connection error 
![Screenshot_2023-04-10-23-06-02-16_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/50658399/230961824-cf3f72c0-b9b9-4dd6-8308-c61ae3381745.jpg)

### Steps to reproduce the behavior.

Run: apt-get update 

### System information

* Termux application version:0.101
* Android OS version:13
* Device model:CPH2401

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation

https://github.com/termux/termux-app#google-play-store-deprecated
