### ISSUE TITLE
Selection aid?

### ISSUE THREAD

**Issue by noncom** [termux/termux-app#334]
Working with a terminal often involves selecting some text, and it is not really comfortable when the terminal is fullscreen and the text touches the screen edges. Including the edge characters into the selection becomes a rather non-trivial task... Can't help, but the selection aid from JuiceSSH springs into mind by itself... could we have something like that in Termux?

I'd even pay for an addon to do that.. or even an addon that does some additional higher-level text and/or input history manipilation. Like, automatically extracting paths and numbers from the available text body would be super-useful on a touch-driven device...

**Comment by xeffyr** [comment]
Closing as already implemented.
