### ISSUE TITLE
[Feature]: Provide latest builds in a release

### ISSUE THREAD

**Issue by Biswa96** [termux/termux-app#3347]
### Feature description

It is asked many times how to download the latest apk files from GitHub. But all the CI artifacts can only be downloaded after logging in GitHub. Also, GitHub stores build logs and artifacts for 90 days maximum[^1]. Is it possible to provide the APKs from CI artifacts to a "nightly" or "beta" like release tag?

[^1]: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

### Additional information

I have tried to add this kind of workflow in the GitHub Actions debug_build.yml files. Here is a little overview about that workflow:

1. Download the artifacts.
2. Delete existing assets in nightly release.
3. Upload the CI artifacts to nightly release.

Would you like add that workflow? Previously asked in https://discord.com/channels/641256914684084234/641256914684084237/1095368238398972036

**Comment by agnostic-apollo** [comment]
Adding to official releases will likely confuse users. Its planned to host our APKs from different sources in a repo, so will add beta releases there.
