### ISSUE TITLE
[Bug]:  Andronix ubuntu doesnt even start.

### ISSUE THREAD

**Issue by Crossshield45** [termux/termux-app#3352]
### Problem description

Hi `Termux Team,`
I use `termux` for coding and networking.And I did have `Ubuntu20 by andronix` installed. All of a sudden the ubuntu20 no longer starts , I tryed a lot but nothing happened. The reason that I am posting an issue of an third party app is that I also have `ubuntu22` which works just fine. And even after deleting and reinstalling Ubuntu20 by andronix i cant get it to run. I dont think it is their fault. Maybe I did something wrong or the new update (`apt update`) did this?
Please fix this issue..

If this issue wasn't supposed to be posted here, please inform me.

### What steps will reproduce the bug?

I really don't know. 
It is not a bug I guess.

### What is the expected behavior?

It should have run the script and I should have gotten a ubuntu login screen

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11822
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://linux.domainesia.com/applications/termux/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
9
Kernel build information:
Linux localhost 3.18.91-15922581 termux/termux-packages#1 SMP PREEMPT Tue Dec 1 15:46:41 KST 2020 armv8l Android
Device manufacturer:
samsung
Device model:
SM-G611F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by agnostic-apollo** [comment]
>sudden the ubuntu20 no longer starts

Without an error message and you have installed/configured it, others likely can't guess what's wrong. And you should report to androidx for issues related to their projects and send them error reports/logs.

Until you have more proof that this is a termux-app issue, closing the issue.
