### ISSUE TITLE
Tsu works but no packages are available 

### ISSUE THREAD

**Issue by 0v3rfl00w** [termux/termux-app#336]
Running tsu command gives me this : bash-4.4#
But no commands from termux are available after that :
bash-4.4# apt
The program 'apt' is not installed. Install it by executing:
 packages install apt
bash-4.4#

**Comment by Efreak** [comment]
Use `tsu -e` to preserve environment variables. Also, root is unnecessary for apt under termux, the entire environment is under termux's user, in its own data folder.

**Comment by evildog1** [comment]
I'm getting the same issue. I want to use gdb which require root.

**Comment by Grimler91** [comment]
@evildog1 gdb doesn't require root normally.

**Comment by evildog1** [comment]
@Grimler91 but it says "operation not permitted" when i try to attach to a process `gdb -pid <pid>`. root is needed :(

**Comment by Grimler91** [comment]
@evildog1 right, so you are trying to attach to a system process? Attaching to processes launched (as none-root) in termux work fine. 

The environment setup by tsu seems to be faulty somehow, try setting PATH=/data/data/com.termux/files/usr/bin:$PATH and LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib in the root environment.

**Comment by evildog1** [comment]
@Grimler91 no i'm trying to attach to apps outside termux that's why it needs root. setting these did not work for me.

**Comment by JonasT** [comment]
@Grimler91 for what it's worth, I think this would be worth fixing - I just ran into the same issue, trying to debug an app not launched from inside termux (not a system app, but it runs separately). And setting the path manually is quite a lot to type on a touchscreen :cry: lol
