### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DaV1s007** [termux/termux-app#3383]
### Problem description

It doesn't run the nethunter kex passwd command

### Steps to reproduce the behavior.

~$ nethunter kex passwd

### What is the expected behavior?

It's supposed to ask me to enter a password 

### System information

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: Galaxy A02s

**Comment by agnostic-apollo** [comment]
This is termux app issue tracker, not nethunter. Also check https://wiki.termux.com/wiki/Hacking
