### ISSUE TITLE
[Bug]: termux-notification doesn't work

### ISSUE THREAD

**Issue by amokfa** [termux/termux-app#3390]
### Problem description

"termux-notification" hangs forever. I've read through https://github.com/termux/termux-app/issues/1925 and the fix mentioned there doesn't work for me

### Steps to reproduce the behavior.

1. Install termux
2. Install termux-api package
3. Run `echo your_content | termux-notification -c your_content_2`

### What is the expected behavior?

Notification should show

### System information

* Termux application version: 0.118.0
* Android OS version: 13
* Device model: pixel 7

**Comment by agnostic-apollo** [comment]
Install Termux:API app
