### ISSUE TITLE
[Feature]: Release a new Version on F-Droid & GitHub

### ISSUE THREAD

**Issue by KaeTuuN** [termux/termux-app#3394]
### Feature description

The last release is from January 2022. Since then there were, as of writing, 250 commits.

Is there any reason why there is no release for such a long time? (I know, more review of pending Pull requests is needed)

Greetings KaaTuuN

### Additional information

I think there is no more Information needed.

**Comment by agnostic-apollo** [comment]
Duplicate of #3213

https://github.com/termux/termux-app/discussions/3213#discussioncomment-5116479
