### ISSUE TITLE
FR:add mitmproxy and build-essentials.

### ISSUE THREAD

**Issue by irregularisnotrandom** [termux/termux-app#34]
Hi

It would be nice if these packages are in the repo. I tried to jnstall mimtoroxy using pip but getting errors, tgere are couple dependencies that i could not get ftom the trrmyx repo.

thanks

**Comment by fornwall** [comment]
Thanks - this has been added to the list of package suggestion at https://termux.com/package-suggestions.html!

**Comment by Craeckie** [comment]
ok and what about build-essentials? (see title of issue)
Would be really cool if I could build software on my phone!

**Comment by denzuko** [comment]
second the build-essentials. I do see gcc, make, and autoconf but most users only know to install build-essentials to get the full gnu/gcc stack. Plus once we have that in place then the community can contribute to your packages, (I for one would love to help out with a few nightly builds)

**Comment by Neo-Oli** [comment]
I reopened this issue at https://github.com/termux/termux-packages/issues/232

**Comment by Ashbuhrz** [comment]
pkg install unstable-repo
pkg install build-essential
