### ISSUE TITLE
Permission denied in subdirectory of home folder

### ISSUE THREAD

**Issue by abers** [termux/termux-app#341]
I am having an issue trying to get TaskWarrior to work on a new phone whereby no matter what I do any files in the /data/data/com.termux/files/home/.task can't be opened. The certificate and key files that TaskWarrior needs to sync were copied from the phone's Download folder to the .task directory. They copy fine using root browser, the user in Termux, and with su in Termux - however, once moved the copied files can't be opened. I have successfully setup TaskWarrior within Termux on my last phone and a tablet - and followed same steps with new phone so utterly baffled as to what the issue could be. Any help would be much appreciated.

**Comment by isrgish** [comment]
Take a look here this should help.

[https://wiki.termux.com/wiki/FAQ#I_updated_termux_packages_as_root_and_now_I.27m_getting_.27permission_denied.27_as_a_non-root_user.](url)

**Comment by xeffyr** [comment]
> They copy fine using root browser, the user in Termux, and with su in Termux - however, once moved the copied files can't be opened. 

On Android, don't forget about SELinux. There 2 solutions:

1. See comment by @isrgish 
2. Set SELinux to permissive mode (`setenforce 0`).

**Comment by xeffyr** [comment]
Closing as this is a common issue when using root on recent Android versions. Happens not only in Termux.

Solution is either to disable SELinux (some ROMs have it disabled by default) or manually restore SELinux labels by using `/system/bin/restorecon`.
