### ISSUE TITLE
Termux crash report 

### ISSUE THREAD

**Issue by randycolitz** [termux/termux-app#3416]
### Problem description

After I installed Termux I opened the app and the terminal screen just stayed black and it didn't even echo back anything after you typed it in. 

### Steps to reproduce the behavior.

Just do a normal install and run the app and it will occur. 

### What is the expected behavior?

To open and have no problems. 

### System information

* Termux application version:
* Android OS version:
* Device model:
I have a California LifeLine phone and I have a 128GB external SD card (San Disk) it's a KeeBoo phone with 4 cores and android 13 is the operating system. It's not rooted. #
/

**Comment by agnostic-apollo** [comment]
Already answered in https://github.com/termux/termux-app/discussions/3415

Don't open duplicates.
