### ISSUE TITLE
[Bug]: text duplicating when zooming in and zooming out off screen

### ISSUE THREAD

**Issue by Keni-Dev** [termux/termux-app#3418]
### Problem description

I'm installing using npm install and when I zoom out and zoom in, the text doubles. 
![Uploading Screenshot_20230523-161235.jpg…]()

### Steps to reproduce the behavior.

Zoom out and zoom in 

### System information

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: Infinix Hot 20S

**Comment by Rudxain** [comment]
I have the same problem on my SM-A315G
