### ISSUE TITLE
[Bug]: Can not install Termux Packages

### ISSUE THREAD

**Issue by naynaingoo2003** [termux/termux-app#3424]
### Problem description

Can not run pkg upgrade and can not install pkg

### Steps to reproduce the behavior.

n/a

### What is the expected behavior?

pkg upgrade
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: bad
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: bad
Using fallback mirror: https://termux.org/packages
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libcurl.so in namespace (default)
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libssl.so.1.1" not found: needed by /data/data/com.termux/files/usr/lib/libcurl.so in namespace (default)

### System information

* Termux application version: 0.101
* Android OS version: 12 SP1A.210812.016
* Device model: M2101K7BG
* Network : Good

**Comment by SowTag** [comment]
run `pkg update`

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

https://github.com/termux/termux-app#google-play-store-deprecated
