### ISSUE TITLE
[Bug]: su problem

### ISSUE THREAD

**Issue by UnkownPlayerX000** [termux/termux-app#3435]
### Problem description

Hello I wanted to elevate termux to superuser using su I granted it the superuser using magisk and when I want to install git it says inaccessible or not found.

### Steps to reproduce the behavior.

su
Apt install git

### What is the expected behavior?

Installing git on termux

### System information

* Termux application version:0.118.0
* Android OS version:12
* Device model:Galaxy Note10+

**Comment by 2096779623** [comment]
`su` does not include the termux environment, please use `tsu`, `apt` and `pkg` do not support running in the superuser environment.
