### ISSUE TITLE
[Feature]:   install  gnu gcc,g++

### ISSUE THREAD

**Issue by yazigegeda** [termux/termux-app#3437]
### Feature description

How to avoid using the clang provided by Termux? I would like to install gcc and g++using GNU, as some projects may encounter issues when using clang construction

### Additional information

none

**Comment by 2096779623** [comment]
```bash
pkg install tur-repo
pkg i gcc-11
```
The tur currently supports versions 9 to 12 of `gcc`.

**Comment by yazigegeda** [comment]
> ```shell
> pkg install tur-repo
> pkg i gcc-11
> ```
> 
> The tur currently supports versions 9 to 12 of `gcc`. https://github.com/termux-user-repository/tur

Thank you. I did install GNU's gcc according to your command, but what should I do if I want to install g++again?

**Comment by 2096779623** [comment]
> Thank you. I did install GNU's gcc according to your command, but what should I do if I want to install g++again?

If you install one of these versions of `gcc`, it will also install tools such as g++, example: `g++-9`

**Comment by yazigegeda** [comment]
> > Thank you. I did install GNU's gcc according to your command, but what should I do if I want to install g++again?
> 
> If you install one of these versions of , it will also install tools such as g++, example: .`gcc``g++-9`

Okay, thank you. That's it
