### ISSUE TITLE
[Bug]: `termux-open` doesn't work

### ISSUE THREAD

**Issue by amaramth** [termux/termux-app#3441]
### Problem description

When I run `termux-open` it opens the appropriate app for the file type, but that app does not recognize the file; e.g. the Music app says "Cannot play song".

Edit: I learned that this is fixed by setting `allow-external-apps = true` in the settings.

The release notes do not explain why this is necessary, and why is there not an option to allow only `termux-open` without `allow-external-apps` in general?

### System information

* Termux application version: 0.118.0
* Android OS version: 8.0.0
* Device model: F5321

**Comment by agnostic-apollo** [comment]
>~The release notes do not explain why this is necessary, and why is there not an option to allow only termux-open without allow-external-apps in general?

If an app can modify termux files, then it can get termux to run arbitrary code via login/rc files, etc, hence has same level of protection as `RUN_COMMAND` intent. In future, more granular control will be added.

**Comment by amaramth** [comment]
I see, thank you. I would be happy with an option to be able to only open files under `~/storage`.

**Comment by agnostic-apollo** [comment]
An app being able to access files on external storage like pictures/documents, etc via termux, without itself having storage permission is another huge privacy issue.

**Comment by amaramth** [comment]
Hm, that implies that `termux-open` behaves very differently than I expected; I thought it was just calling the usual Android file opener, whatever e.g. the Files app uses to open a file.

I mean, it is calling the usual file opener, but is it passing different information than the Files app would pass? And would it be difficult to provide a version of `termux-open` that functions the same as the Files app? (possibly only working on the contents of `~/storage`)

**Comment by Rudxain** [comment]
> would it be difficult to provide a version of `termux-open` that functions the same as the Files app?

I sometimes use [Acode](https://github.com/deadlyjack/Acode), which can **edit files with 0 storage access** thanks to SAF and AOSP Files. Basically, it opens the Files chooser, and Files passes file control back to Acode, which then has permission to edit that single file. I thought it needed Media access, but since it uses Share functionality it works kinda like Rust's borrow-system
