### ISSUE TITLE
possible to activate wake-lock from within termux

### ISSUE THREAD

**Issue by whoisterencelee** [termux/termux-app#345]
Is it possible to activate wake-lock from within termux terminal?

**Comment by vishalbiswas** [comment]
`apt install termux-tools; termux-wake-lock`

**Comment by fornwall** [comment]
.. and `termux-wake-unlock`. As the `termux-tools` package comes preinstalled this is available out of the box!

**Comment by mansurabbas** [comment]
Please how can i install wakeonlan in termux.
