### ISSUE TITLE
[Bug]: `termux-open-url` cannot take spaces

### ISSUE THREAD

**Issue by amaramth** [termux/termux-app#3451]
### Problem description

`termux-open-url 'https://duckduckgo.com/?q=a b'`
says
`Error: Activity not started, unable to resolve Intent`
whereas
`termux-open-url 'https://duckduckgo.com/?q=a%20b'`
works as expected

### System information

* Termux application version: 0.118.0
* Android OS version: 8.0.0
* Device model: F5321

**Comment by agnostic-apollo** [comment]
Urls don't have literal space characters and need to be escaped.

**Comment by amaramth** [comment]
Every browser I've used takes urls with spaces. Every other command-line tool I've used takes urls with spaces. The browser converts the spaces to %20, yes, but termux must have extra code to have an error in this situation. Is there a purpose for that?

**Comment by amaramth** [comment]
For anyone else with this issue, this code can allow `termux-open-url` to take multiple arguments with spaces.
```
alias see__=termux-open-url
see_(){ see__ "$1" ;for x in "${@:2}" ;do sleep 0.5 ;see__ "$x" ;done }
replace20(){ echo "${1// /%20}" ;}
alias _map='r=() ;for _x in "$@"; do r+=("$($f "$_x")") ;done'
see(){ f=replace20 ;_map ;see_ "${r[@]}" ;}
```
