### ISSUE TITLE
[Bug]: `termux-clipboard-set` is slow

### ISSUE THREAD

**Issue by amaramth** [termux/termux-app#3453]
### Problem description

I assumed that `termux-clipboard-set` is implemented in a way that is always slow. However this code calls `termux-clipboard-set` very rapidly. I have no idea why it works. (It does succesfully set the clipboard)
```
nanoecho(){ tee >(eval "$@") >(cat) >/dev/null }
echo text | nanoecho termux-clipboard-set
```

### System information

* Termux application version: 0.118.0

**Comment by Haiz14** [comment]
https://github.com/termux/termux-api/issues/552#issuecomment-1382722639

**Comment by Haiz14** [comment]
Maybe the am script should be updated, gonna submit an issue on package repo

**Comment by Haiz14** [comment]
When am script gets updated https://github.com/termux/termux-packages/issues/17039 it will automatically speed up termux-clipboard. For now you could follow update am script by following what agnostic said https://github.com/termux/termux-api/issues/552#issuecomment-1382722639

**Comment by agnostic-apollo** [comment]
Duplicate of termux/TermuxAm#9
