### ISSUE TITLE
[Bug]: i can't uninstall termux

### ISSUE THREAD

**Issue by flic420** [termux/termux-app#3456]
### Problem description

Every time i hit uninstall my device restarts without uninstalling the app (i have google play version and i want to install a newer version)

### What steps will reproduce the bug?

I try to uninstall termux from device settings
My device restarts without uninstalling the app

### System information

termux-info:

```
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost - aarch64 Android
Device manufacturer:
LENOVO
Device model:
Lenovo YT-J706F
```

**Comment by agnostic-apollo** [comment]
Closed by https://www.reddit.com/r/termux/comments/146yib0/problems_with_uninstalling_termux/jnt2t4f
