### ISSUE TITLE
Termux files directory not found

### ISSUE THREAD

**Issue by stephdgenius** [termux/termux-app#3458]
### Problem description

The app not have access to files directory 

### Steps to reproduce the behavior.

Install and launch the app

### System information

* Termux application version: 118
* Android OS version: 12
* Device model: `M2004J19C`

## Bootstrap Error

(150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".
TERMUX_FILES_DIR: `/data/data/com.termux/files`

## Termux Files Info

**TERMUX_REQUIRED_FILES_DIR_PATH ($PREFIX)**: `/data/data/com.termux/files`  
**ANDROID_ASSIGNED_FILES_DIR_PATH**: `/mnt/expand/8c33dc79-c65b-4e23-8ea6-5f592a7c2699/user/0/com.termux/files`  

```
$ echo 'ls info:'
/system/bin/ls -lhdZ '/data/data' '/data/user/0' '/data/data/com.termux' '/data/user/0/com.termux' '/data/data/com.termux/files' '/mnt/expand/8c33dc79-c65b-4e23-8ea6-5f592a7c2699/user/0/com.termux/files' '/data/user/0/com.termux/files' '/data/user/com.termux/files' '/data/data/com.termux/files/usr-staging' '/data/data/com.termux/files/usr' '/data/data/com.termux/files/home' '/data/data/com.termux/files/usr/bin/login' 2>&1
echo; echo 'mount info:'
/system/bin/grep -E '( /data )|( /data/data )|( /data/user/[0-9]+ )' /proc/self/mountinfo 2>&1 | /system/bin/grep -v '/data_mirror' 2>&1

ls info:
ls: /data/data/com.termux: No such file or directory
ls: /data/user/0/com.termux: No such file or directory
ls: /data/data/com.termux/files: No such file or directory
ls: /data/user/0/com.termux/files: No such file or directory
ls: /data/user/com.termux/files: No such file or directory
ls: /data/data/com.termux/files/usr-staging: No such file or directory
ls: /data/data/com.termux/files/usr: No such file or directory
ls: /data/data/com.termux/files/home: No such file or directory
ls: /data/data/com.termux/files/usr/bin/login: No such file or directory
drwxrwx--x 348 system  system  u:object_r:system_data_file:s0:c512,c768         28K 2023-05-29 02:45 /data/data
drwxrwx--x 348 system  system  u:object_r:system_data_file:s0:c512,c768         28K 2023-05-29 02:45 /data/user/0
drwxrwx--x   2 u0_a526 u0_a526 u:object_r:app_data_file:s0:c14,c258,c512,c768  4.0K 2023-06-13 06:14 /mnt/expand/8c33dc79-c65b-4e23-8ea6-5f592a7c2699/user/0/com.termux/files

mount info:
7597 7495 259:14 / /data rw,nosuid,nodev,noatime master:34 - ext4 /dev/block/platform/bootdevice/by-name/userdata rw,seclabel,nobarrier,noauto_da_alloc,inlinecrypt,resuid=10010,resgid=1065,errors=panic,data=ordered
7598 7597 259:14 /data /data/user/0 rw,nosuid,nodev,noatime master:34 - ext4 /dev/block/platform/bootdevice/by-name/userdata rw,seclabel,nobarrier,noauto_da_alloc,inlinecrypt,resuid=10010,resgid=1065,errors=panic,data=ordered

```
##

## 
## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**IS_INSTALLED_ON_EXTERNAL_STORAGE**: `true`  
**FILES_DIR**: `/mnt/expand/8c33dc79-c65b-4e23-8ea6-5f592a7c2699/user/0/com.termux/files`  
**TERMUX_FILES_DIR**: `/data/data/com.termux/files`  
**IS_TERMUX_FILES_DIR_ACCESSIBLE**: `false - (150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".`  
**APK_RELEASE**: `F-Droid`  
##

### Hardware

**MANUFACTURER**: `Xiaomi`  
**BRAND**: `Redmi`  
**MODEL**:   `M2004J19C`
**SUPPORTED_ABIS**: `armeabi-v7a, armeabi`  
##

**Comment by agnostic-apollo** [comment]
> ANDROID_ASSIGNED_FILES_DIR_PATH: /mnt/expand/8c33dc79-c65b-4e23-8ea6-5f592a7c2699/user/0/com.termux/files

Termux currently cannot be installed on external/adoptable storage.
