### ISSUE TITLE
python dynamic lib could not find symbol reference

### ISSUE THREAD

**Issue by fufufu2001** [termux/termux-app#346]
ImportError: dlopen failed: cannot locate symbol "log2" referenced by "/data/data/com.termux/files/usr/lib/python3.6/site-packages/brotlipy-0.7.0-py3.6-linux-aarch64.egg/brotli/_brotli.abi3.so"

log2 seems in libc?

**Comment by fufufu2001** [comment]
android version is 5.0.2
-bash-4.4$: ldd /data/data/com.termux/files/usr/lib/python3.6/site-packages/brotlipy-0.7.0-py3.6-linux-aarch64.egg/brotli/_brotli.abi3.so
libandroid-support.so
libgnustl_shared.so
libpython3.6m.so.1.0
libdl.so
libc.so

libc.so,libdl.so and libm.so can be found in /system/lib64/

**Comment by fufufu2001** [comment]
LD_LIBRARY_PATH="/system/lib64":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
it's useless

**Comment by Deathlive** [comment]
@fufufu2001 How did you solve this problem?

**Comment by fufufu2001** [comment]
just switch android version to 6.0+

**Comment by Hax4us** [comment]
Any progress ??

**Comment by Hax4us** [comment]
Why this issue is still open ...plz solve and closed
