### ISSUE TITLE
[Bug]: Too hard to access Termux files

### ISSUE THREAD

**Issue by frozen905** [termux/termux-app#3464]
### Problem description

App is beyond frustrating. Can't open the code saved in my Termux folder in regular editor apps. Getting sick and tired of fighting with this app to do extremely basic things. No wonder its abandoned

### Steps to reproduce the behavior.

Can't access Termux files in other apps

### What is the expected behavior?

Stop being so stupid and obtuse over basic functions. Get a grip

### System information

* Termux application version: latest
* Android OS version: 9
* Device model: Pixel 2

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/Internal_and_external_storage#Access_Termux_from_a_file_manager
