### ISSUE TITLE
Cannot install Termux (GitHub version) on my phone

### ISSUE THREAD

**Issue by Aridlvory** [termux/termux-app#3467]
### Problem description

I have used the fdroid version of termux (0.118.0) but in order to use termux-gui i tried to delete the fdroid version and install the GitHub version but the app fails to get installed

I am on Samsung Galaxy On6 (SM-J600GF)
ArmV8l
Android 10

### Steps to reproduce the behavior.

Install the universal apk
I tried armeabi-v7a

### System information

* Termux application version:0.118.0
* Android OS version:10
* Device model:SM-J600GF

**Comment by 2096779623** [comment]
Try `arm64-v8a` .

**Comment by Aridlvory** [comment]
@2096779623 

Tried failed

![Screenshot_20230619-104155_Package installer.jpg](https://github.com/termux/termux-app/assets/78092537/224a32ac-560c-4b0d-8833-3b061b211026)

The fdroid version installs without any problems

**Comment by twaik** [comment]
Delete all Termux applications (GUI, styler, boot, everything) and try again...

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

**Comment by nexusprime-here** [comment]
> @2096779623
> 
> Tried failed
> 
> ![Screenshot_20230619-104155_Package installer.jpg](https://private-user-images.githubusercontent.com/78092537/246731566-224a32ac-560c-4b0d-8833-3b061b211026.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMjUxNzksIm5iZiI6MTcwNDEyNDg3OSwicGF0aCI6Ii83ODA5MjUzNy8yNDY3MzE1NjYtMjI0YTMyYWMtNTYwYy00YjBkLTg4MzMtM2IwNjFiMjExMDI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE2MDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MjUzMmM4MTIxNjRkZDAzODA4YTQyNjA4ZWZiOGQ1ZTcwMTVjZWQyZjQzOTNkMzI4MWZjNDE1NjcyNDMxNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yfW-ufu5c2_7tUO6l1Ehj7rrOlC_0JxfIizQe92xGTU)
> 
> The fdroid version installs without any problems

fdroid fails to me

**Comment by nexusprime-here** [comment]
> https://github.com/termux/termux-app#Installation

idk what this means, i've already read these

**Comment by odyong** [comment]
Hi were you able to make it work

**Comment by odyong** [comment]
Am having same issues
