### ISSUE TITLE
[Bug]: I encountered this issue while install it Kali Linux nethunter  "[*] Configuring NetHunter for Termux ... ./install-nethunter-termux: line 363: kali-armhf/etc/sudoers.d/kali: No such file or directory" and I followed all the steps accurately. Is it because my device is not rooted

### ISSUE THREAD

**Issue by vams-spectra-code** [termux/termux-app#3468]
### Problem description

 [*] Configuring NetHunter for Termux ...
./install-nethunter-termux: line 363: kali-armhf/etc/sudoers.d/kali: No such file or directory

Same issue, I've tried many times yet same issue. Can you please help me with the accurate steps on installing Kali Linux nethunter on Infinix hot 10 lite

### Steps to reproduce the behavior.

kali-armhf/etc/sudoers.d/kali (folder not found)

### What is the expected behavior?

 [*] Configuring NetHunter for Termux ...
./install-nethunter-termux: line 363: kali-armhf/etc/sudoers.d/kali: No such file or directory

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking
