### ISSUE TITLE
the termux app cannot open

### ISSUE THREAD

**Issue by eggcaker** [termux/termux-app#347]
after I installed few packages with root user, i cannot start the termux app shell,  but with adb shell it still working. when start termux app shows error : 

CANNOT LINK EXECUTABLE "-bash ":  "libandroid-support.so" not found. 

do i need reinstall termux to fix the issue ?

**Comment by Grimler91** [comment]
Does it work if you run `export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib`?

**Comment by fornwall** [comment]
@eggcaker You should avoid installing packages as the root user (it shouldn't bring any benefits, and may cause various problems)!

You can force a re-installation of `$PREFIX` by removing it as root (`rm -Rf $PREFIX`), exit all terminal sessions and start Termux again. This will cause a clean install, just like re-installing the app, but keeping the `$HOME` directory intact.
