### ISSUE TITLE
termux-wake-lock/unlock issues

### ISSUE THREAD

**Issue by angelog0** [termux/termux-app#3472]
### Problem description

Running `termux-wake-lock` the first time opens a popup asking for consensus: this only the first time than it does not ask any more.

1. How can I revert this so that the next time I run that command it asks for consensus?

2. How can I know if the wake lock is active? Tried:

```
termux-notification-list | jq -r '.[] | select(.id == 1337).content' | grep -qF 'wake lock held' && locked="true" || locked="false"
```

but it seems to hang: I have to CTRL-C..

### Steps to reproduce the behavior.

.

### System information

* Termux application version: the current: 0.118.0
* Android OS version: 8.1 (but I think the same on 11)
* Device model: Phone Xiaomi Redmi 5/Tablet Samsung Tab Se5

**Comment by tareksander** [comment]
Normally the wake lock is a permission granted to apps without user conset IIRC. You can try searching Termux in your app list in the settings app and look for denied permissions.

**Comment by angelog0** [comment]
@tareksander, here it asked. There was a sort of warning about the usage of app in background consuming battery. I searched in Settings (Termux, Notifications, Battery) but found anything of useful.. and about my question n. 2?

**Comment by tareksander** [comment]
Do you have the Termux:API app installed?

**Comment by angelog0** [comment]
@tareksander, I installed the `termux-api` and `jq` packages..

**Comment by tareksander** [comment]
You have to install the app: https://github.com/termux/termux-api

**Comment by angelog0** [comment]
Ah, ok... and for my question n. 1? I would interested to revert consensus..

**Comment by tareksander** [comment]
I don't think that's possible.

**Comment by angelog0** [comment]
@sylirre, thanks for all your suggestion but here, Xiaomi with AOS 8.1, in `Settings - App-Termux-Energy saving`, Termux has `Save Battery (suggested)` enabled (the other would be Unrestricted, etc.)

instead in `Settings - Battery and performance - battery - save energy app` there are many app listed between which Termux and tapping on it it returns to what I have just described above... and `termux-wake-lock` does ask any more..

**Comment by agnostic-apollo** [comment]
Xiaomi phones and others have multiple battery related settings for apps, you will have to find on your own, check https://dontkillmyapp.com/xiaomi

1. Termux will not ask user for disabling battery optimizations if already granted by user, no point in that and it is working as intended. To disable battery optimizations with an android prompt yourself, run `am start --user 0 -a android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS -d "package:com.termux"` and select `Allow`. If optimizations are already disabled, then no prompt will be shown and
the battery optimizations settings for all apps will need to be opened with `am start --user 0 -a android.settings.IGNORE_BATTERY_OPTIMIZATION_SETTINGS`.

    - https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

    - https://developer.android.com/reference/android/provider/Settings#ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS

2. Use following after granting termux `DUMP` permission with `adb` or `root`. 356a442c

```shell
adb shell dumpsys power | grep -E 'PARTIAL_WAKE_LOCK.*termux:service-wakelock'
  PARTIAL_WAKE_LOCK              'termux:service-wakelock' ACQ=-1m48s379ms LONG (uid=10169 pid=15126)
```
