### ISSUE TITLE
$HOME/storage is not created

### ISSUE THREAD

**Issue by kr1shnas** [termux/termux-app#348]
device: ls-4001
os: android 5.1

i have installed termux 0.52 from f-droid app.

i have followed instructions given in "Internal and external storage help".

i have executed the following commands after installation is completed:

$ apt update && apt upgrade
$ termux-setup-storage

i closed app: exit

i have opened file explorer. the directory is not created.

$HOME/storage: does this mean the directory is created on /storage/emulated/0/.
is my assumption correct ?

please look into the issue.

**Comment by icebal** [comment]
thisis also an issue on a clean flash of stock android O.

**Comment by fornwall** [comment]
@kr1shnas The `$HOME/storage` folder is inside Termux, so not normally shown in a file explorer.

Inside Termux you can run `ls $HOME/storage` to see the contents there - does that work?

**Comment by kr1shnas** [comment]
the following directories are listing

dcim: sub folders listing
pictures: sub folders listing
music: no file or directory
movies: no file or directory
downloads: files listing
shared: sub folders listing

**Comment by fornwall** [comment]
Ok, that should be as intended then - the folders are just symlinks into folders in the shared storage directory, such as this in a device of mine:

```
dcim -> /storage/emulated/0/DCIM/
downloads -> /storage/emulated/0/Download/
external -> /storage/3364-3732/Android/data/com.termux/files/
movies -> /storage/emulated/0/Movies/
music -> /storage/emulated/0/Music/
pictures -> /storage/emulated/0/Pictures/
shared -> /storage/emulated/0/
```
If dcim, music and movies are empty that just means that you haven't put any files there.

You can chat at https://gitter.im/termux/termux or #termux on freenode if you want to discuss more!
