### ISSUE TITLE
[Feature]: How to Makeing TextColor?

### ISSUE THREAD

**Issue by moderGamer** [termux/termux-app#3483]
### Feature description

Hello, I use your library for my terminal, I wanted to know if there is a method to change the color of the text?

### Additional information

.

**Comment by moderGamer** [comment]
As if you didn't notice, I need a terminal for my Android project, not the Thermox program

**Comment by agnostic-apollo** [comment]
You can use `foreground` property of terminal color scheme by passing it to `TerminalColorScheme.updateWith()`. You should ideally pass full color scheme like termux-styling creates at `~/.termux/color.properties`. Note that colors can be changed dynamically by ANSI escape sequences.

- https://github.com/termux/termux-app/blob/9d308c23314375f9d2b9f022f31ca6d7459cda72/app/src/main/java/com/termux/app/terminal/TermuxTerminalSessionActivityClient.java#L506

- https://github.com/termux/termux-app/blob/9d308c23314375f9d2b9f022f31ca6d7459cda72/terminal-emulator/src/main/java/com/termux/terminal/TerminalColorScheme.java#L72

- https://github.com/termux/termux-styling/tree/master/app/src/main/assets/colors

- https://en.wikipedia.org/wiki/ANSI_escape_code

- https://askubuntu.com/questions/558280/changing-colour-of-text-and-background-of-terminal
