### ISSUE TITLE
Not clickable "pkg install"

### ISSUE THREAD

**Issue by garmoshka-mo** [termux/termux-app#349]
Guys, it possible to let pass such obvious inconvenience on desktop terminals, where it's not so huge deal to copy-paste text (or even type for geeks):

![screenshot_2017-06-25-12-36-27-083_com termux](https://user-images.githubusercontent.com/2452269/27515081-15fa1ce2-59a4-11e7-8d39-3d356b82ec18.png)

But on mobile device surely `pkg install mosh` must be clickable link.

I know, that people usually very hard percieve direct criticism, but this situation is so obviously absurd, that I will risk to write naked truth without excuses.

**Comment by OpnSrcConstruction** [comment]
why would you need the link to be click-able?

**Comment by garmoshka-mo** [comment]
@OpnSrcConstruction (I will be pretty sarcastic further, but you have to forgive me, because you act really funny asking this question)

Because usually link is clickable, and when I see a link, I, like everybody else will expect that it will be clickable 😉

Well, if you about why `pkg install mosh` should be clickable link - because it will let user to perform most probable next action in 1 click, instead of  typing 16 symbols

**Comment by wbrawner** [comment]
If this is something that the devs would consider to be helpful, I'd be happy to work on it myself. I agree that it would be nice for convenience's sake

**Comment by sdrausty** [comment]
+1 interesting idea: 1 tap = 16 symbols

**Comment by xeffyr** [comment]
It isn't possible to distinguish cases when pattern `pkg install <package name>` should be clickable and when not.

If people want quicker way to install package when it is not available, I'm suggesting to implement a prompt in `command-not-found` package. It can look like:
```
$ mosh
The program 'mosh' is not installed. Do you want to install it now ? (y/n):
```
So user can just enter `y` and package will be installed. That much better than messing terminal implementation and will solve problem with copy-pasting "pkg install" commands (at least partially).

Closing issue.
