### ISSUE TITLE
[Bug]: `su` not found despite the device being rooted and the `su` is accessible through the ADB shell.

### ISSUE THREAD

**Issue by oxou** [termux/termux-app#3509]
### Problem description

# Description

Despite having rooted the device using Magisk and ROM patching, Termux says `No su program found on this device` despite the `su` command working in the ADB Shell.

When trying to `ls /system/bin` via Termux it reports:
```
ls: cannot open directory '/system/bin': Permission denied
```

---

# Termux About

## Termux App Info
```
APP_NAME: Termux
PACKAGE_NAME: com.termux
VERSION_NAME: 0.1180
VERSION_CODE: 118
TARGET_SDK: 28
IS_DEBUGGABLE_BUILD: false
APK_RELEASE: F-Droid
```

### Software

```
OS_VERSION: 4.19.188-24113222-ab[REDACTED]
SDK_INT: 31
RELEASE: 12
SECURITY_PATCH: 2022-09-01
```

---

### Steps to reproduce the behavior.

Run `su` on a rooted device.

### What is the expected behavior?

Magisk asks to grant permissions, once granted root access is given.

### System information

* Termux application version: 0.1180
* Android OS version: 12
* Device model: [REDACTED]

**Comment by oxou** [comment]
@sylirre `which su` returns `/system/bin/su`

**Comment by oxou** [comment]
It does not work because the application can't access `/system/bin`, it can't list the directory, nor access any files within it by direct reference/path.

**Comment by agnostic-apollo** [comment]
Android does not allow listing files in `/system/bin` but it allows executing specific binaries depending on ownership and selinux file context of individual binaries. If your `su` binary can only be executed by `adb`, then it does not have correct ownership or context and/or magisk is not overlaying the binary with the system provided `su`. Run `su --version` and `/system/bin/ls -lZ /system/bin/su` from `adb`. Closing since not a termux issue.

```shell
~ $ /system/bin/ls -lZ /system/bin/sh
-rwxr-xr-x 1 root shell u:object_r:shell_exec:s0  310248 2009-01-01 05:00 /system/bin/sh
~ $ /system/bin/ls -lZ /system/bin/cat
lrwxrwxrwx 1 root root u:object_r:system_file:s0  6 1971-07-11 13:44 /system/bin/cat -> toybox
~ $ /system/bin/ls -lZ /system/bin/su
lrwxrwxrwx 1 root root u:object_r:system_file:s0  8 1971-07-11 13:44 /system/bin/su -> ./magisk
~ $ /system/bin/ls -lZ /system/bin/run-as
-rwxr-x--- 1 root shell u:object_r:runas_exec:s0  16000 2009-01-01 05:00 /system/bin/run-as
~ $ /system/bin/ls -lZ /system/bin
ls: /system/bin: Permission denied
```

**Comment by oxou** [comment]
Here's how I solved the issue.

I backed up my $HOME directory to a safe location, and uninstalled Termux completely.
Clearing the cache and data did not work thus why I needed to uninstall it.

After reinstalling and setting up the environment, running `su` now invoked the Magisk root confirmation dialog which upon confirming gave root permissions to the Termux.

Could this have been solved through an optional property in the Settings of Termux such as `Acquire Root Permissions`?

It seems that calling `su` did not invoke Magisk, and I know I didn't block Termux because if I did it would be listed in the Magisk list of apps that asked for the Super User, of course there was nothing listed.

An odd bug which only occured with Termux.

**Comment by agnostic-apollo** [comment]
You probably put termux in deny/hide list of termux.

**Comment by oxou** [comment]
Trust me, I checked everything, including DenyList.
This drove me nuts for the entire day, I guess I should've tried reinstalling but I couldn't bother with backing up my files... either way I'm happy It's solved, perhaps write this somewhere in the docs/wiki in case someone encounters a similar issue.
