### ISSUE TITLE
oot: sir Do you know how to fix this 

### ISSUE THREAD

**Issue by mozzaru** [termux/termux-app#3516]
### Problem description

I did git checkout but it's slow 
Please help 

### Steps to reproduce the behavior.

.

### What is the expected behavior?

.
![Screenshot_2023-07-21-08-31-59-12_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-app/assets/100791931/8b03e136-faca-4223-b385-c374633bde36)

### System information

* Termux application version: last
* Android OS version: android 11
* Device model: realme 7i

**Comment by TomJo2000** [comment]
We do not do support for third party projects and or infrastructure.

**Comment by mozzaru** [comment]
What about the speed of the device?
I mean I use termux then gitclone then switch branches and move slow branches.
What is the device that causes it to be slow, approx

**Comment by thunder-coding** [comment]
> I did git checkout but it's slow

Large checkouts can take a long time depending on the internet speed as @mozzaru has pointed out. And anyways this is in no way a problem with the Termux app, if you're unsure if it's a bug or just need help, you can post in any of our communities: https://wiki.termux.com/wiki/Community

**Comment by thunder-coding** [comment]
> @thunder-coding There is different issue. Checkout doesn't require Internet connection, only clone/push needs it.

Oh yeah thanks for the correction 👍
