### ISSUE TITLE
[Feature]: Ridiculous convoluted process to get FN keys to display 

### ISSUE THREAD

**Issue by frozen905** [termux/termux-app#3528]
### Feature description

I'm a novice user looking to use FN keys and the process for enabling these is downright idiotic. I'm not interested in issuing a bunch of weird commands and not interested in editing .profile files. There's simply no good reason to make this so difficult.

### Additional information

Yes

**Comment by agnostic-apollo** [comment]
You are using a terminal and you don't want to enter basic commands to edit a file? I don't think you are in the right place.

What keys are you trying to enable?
