### ISSUE TITLE
Not a real bug, but how to suspend a particular process ?

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#3538]
### Problem description

When using a Linux desktop under Termux (I use Andronix), I want to suspend the desktop, e.g. when not in use during night, without killing or closing it.
The reason is that some foreground processes like a Ubuntu web browser like Firefox or LibreOffice still eat CPU time in the background. I tried using `killall -SIGSTOP proot` but to no avail.
Normally that is a command to freeze Linux processes.
Is there a way that Termux can freeze processes within its environment ?

### Steps to reproduce the behavior.

See above.

### What is the expected behavior?

Allow freezing processes.

### System information

* Termux application version: 118
* Android OS version: 10 (OnePlus Oxygen OS)
* Device model: OnePlus 6

**Comment by twaik** [comment]
https://stackoverflow.com/questions/392022/whats-the-best-way-to-send-a-signal-to-all-members-of-a-process-group
