### ISSUE TITLE
Termux Serial IO

### ISSUE THREAD

**Issue by Eckehard** [termux/termux-app#355]
Node Red provides an Option to use Serial IO on Linux. 

On termux we have problems to get things working. It seems that android uses a special API usb-serial-for-android for USB OTG, that bypasses the Linux kernel. Maybe our analysis is not correct. Anyway using Node Red on an unrooted tablet would be a great option for many IoT applications.

Has anybody solved the problem?

Best regrads,
Eckehard

**Comment by Grimler91** [comment]
Some android programming would be needed for this, in particular a termux-api addon.

**Comment by xeffyr** [comment]
Closing as Termux:API has now support for USB (though, program must be `libusb` -based). https://wiki.termux.com/wiki/Termux-usb
