### ISSUE TITLE
[Bug]: Some valid URLs are not properly parsed by the URL detection

### ISSUE THREAD

**Issue by Soundtoxin** [termux/termux-app#3550]
### Problem description

https://xn--z7x.xn--6frz82g/tmp/
https://猫.移动/tmp/

This is a temporary filehost. Both URL formats go to the same place. The second one shows up properly in the URL opener I get on long-press in Termux. The first one is cut off after the .xn part, I guess it doesn't handle the hyphens well.

### Steps to reproduce the behavior.

* Copy the URLs into something in termux
** maybe vim or something
* long-press to get the URL open menu
* observe

### What is the expected behavior?

Both versions of the URL should be openable.

### System information

* Termux application version: 0.118.0 (source: F-Droid)
* Android OS version: Android 13 / LineageOS 20 (20-20230810-NIGHTLY-kebab)
* Device model: kebab / OnePlus 8T

**Comment by iyra** [comment]
Does it get cut off after the first or second 'xn' part? My hypothesis is that it doesn't class .xn--6frz82g alongside things like .com, .net, .eu, etc. if you're talking about the second 'xn' part. 

I also wonder why your LineageOS version is named 'kebab'. Slight concern.

**Comment by Soundtoxin** [comment]
![Screenshot_20230817-184908_Termux_1](https://github.com/termux/termux-app/assets/3146494/d308a4b8-54a3-443b-a848-fe3a04380ac6)

Second part, my bad, didn't notice "xn" was there twice.

**Comment by Soundtoxin** [comment]
I am running the latest Termux from F-Droid, which says "Updated 11 months ago". As far as I can tell, this issue is still not fixed. Are the relevant commits newer than the last release? I see it was closed originally in 2023 but that there were commits added to this issue in 2024, 2025, and 2026 also. Does that mean this will work on the next release?

**Comment by agnostic-apollo** [comment]
Install `0.119.0-beta.*`, not available in `0.118.*`.

**Comment by Soundtoxin** [comment]
Confirmed working on the beta. Thanks!
