### ISSUE TITLE
[Feature]: Play online audio stream

### ISSUE THREAD

**Issue by basncy** [termux/termux-app#3551]
### Feature description

play online audio stream with ffmpeg
crond supported(e.g. morning news auto-play, customize audio-alarm).
root permission might be needed to run tinyplay(any alternative?)
`tinymix "TERT_MI2S_RX Audio Mixer MultiMedia1" 1`
`tinyplay <(ffmpeg -i 'http://www.example.com/index.m3u8' -map 0:a -f wav -|sox -t wav - -t wav -)
`

### Additional information

-

**Comment by twaik** [comment]
Alsa audio is not supported, only pulseaudio is available.
@agnostic-apollo I think this issue can be closed.

**Comment by twaik** [comment]
@basncy you should take a look at pulseaudio's `pacat` and `paplay`.

**Comment by basncy** [comment]
tinyplay is the andoird OEM verdor specific build-in command.
pulseaudio use SLES interface, haven't tried this method as the complex data stream pipe.
