### ISSUE TITLE
[Feature]: 建议原生支持glibc

### ISSUE THREAD

**Issue by poisongod** [termux/termux-app#3558]
### Feature description

 glibc 的编译器（及其依赖项）和其他编译工具
建议参考[glibc-packages](https://github.com/termux-pacman/glibc-packages)

### Additional information

是的，一般的GNU/Linux发行版都拥有glibc,比如Debian，Ubuntu,ArchLinux..等等

**Comment by twaik** [comment]
Official language of all termux repos is English.

**Comment by Maxython** [comment]
https://github.com/termux/termux-packages/discussions/16692
