### ISSUE TITLE
[Bug]: Termux is closing even after running adb commands

### ISSUE THREAD

**Issue by WizardlyBump17** [termux/termux-app#3559]
### Problem description

I am aware of #2366 and I followed https://docs.andronix.app/android-12/andronix-on-android-12-and-beyond to stop the Phantom process. However, when trying to run an AI (ComfyUI, just for fun), the application closes after trying to load the checkpoint model.

### Steps to reproduce the behavior.

1. Install the ComfyUI
2. Run the `adb` commands to stop the Phantom process
3. Try to run the ComfyUI in CPU mode and queue a prompt
4. The application closes a few seconds later

### What is the expected behavior?

Even taking a long time, the application should not close and the model should be loaded

### System information

* Termux application version: 0.118.0 from F-Droid
* Android OS version: 13
* Device model: Samsung M52 5G - Not rooted

**Comment by agnostic-apollo** [comment]
Probably an `OutOfMemoryError`. Termux should have shown a notification for the crash or next startip, otherwise check logs with `adb logcat -d > /sdcard/logcat.txt`.

**Comment by romanovj** [comment]
adb shell dumpsys activity exit-info com.termux | grep reason

**Comment by WizardlyBump17** [comment]
> adb shell "dumpsys activity exit-info com.termux | grep reason"

![image](https://github.com/termux/termux-app/assets/38295327/b13f012a-a4bc-4c52-9c6c-c5840e545faa)



> Probably an `OutOfMemoryError`. Termux should have shown a notification for the crash on next startup, otherwise check logs with `adb logcat -d > /sdcard/logcat.txt`.

No notifications were shown so I needed to run the command. It generated a big file (21mb). I forgot to mention that I was using the `adb` inside the Termux and wasnt rooted, but I changed to the `shell` subcommand and the file name.

**Comment by agnostic-apollo** [comment]
Should be able `grep` the error from log file if crash was recent or clear log buffer with `adb logcat -c` first before attempting crash. However, exit info is already showing a `LOW_MEMORY` kill reason, so not an issue with  termux. You can try to see if there is a way for ComfyUI to use less memory, otherwise get a device with more RAM, although apps are still limited to few hundred MBs by default.

**Comment by WizardlyBump17** [comment]
> Should be able `grep` the error from log file if crash was recent or clear log buffer with `adb logcat -c` first before attempting crash. However, exit info is already showing a `LOW_MEMORY` kill reason, so not an issue with termux. You can try to see if there is a way for ComfyUI to use less memory, otherwise get a device with more RAM, although apps are still limited to few hundred MBs by default.

Alright, is it possible to bypass the RAM limit like we do with Phantom?
