### ISSUE TITLE
../dist/configure: not found - Error 127

### ISSUE THREAD

**Issue by sun2rise** [termux/termux-app#356]
I was trying to `npm install berkeleydb` but i got
```
../dist/configure: not found
make: *** [Makefile:12: config] Error 127
```

I am trying to install it on a folder in this path inside Termux:
`~/storage/projects/server`

![Alt text](https://cdn.pbrd.co/images/GzRQOtR.jpg "THE ERROR")

Any known solution to this kind of problem?
Thanks!

**Comment by vishalbiswas** [comment]
Install libdb (berkeleydb) package and try again. `apt install libdb`

**Comment by sun2rise** [comment]
thanks @vishalbiswas but the package was already installed:
`libdb/stable,now 6.2.32 arm`

**Comment by vishalbiswas** [comment]
seems like its ignoring the already installed one. you can run it under `termux-chroot` to get get around this.

**Comment by sun2rise** [comment]
Thanks @vishalbiswas `termux-chroot` was the solution!

**Comment by sun2rise** [comment]
@vishalbiswas I know this is probably NOT a problem with termux but maybe you know the answer:

when I try to start a little script using berkeleydb, after a complete install of all the libs:
`make` and `g++` with apt and `berkeleydb` with npm

i got this error:
`Error: dlopen failed: library "libdb-6.0.so" not found`
any idea?

**Comment by vishalbiswas** [comment]
You need to find where did npm install the compiled libdb (that .so file), and add that directory to `LD_LIBRARY_PATH`

**Comment by sun2rise** [comment]
I installed berkeleydb as global package because it seems "more right",
my project couldn't find node module so I wrote this on my .zshrc file:
`export NODE_PATH=/data/data/com.termux/files/usr/lib/node_modules`

This way I think it sees where berkeleydb module is but gives me the previous error: library `libdb-6.0.so` not found..

So I added the line you suggested to the .zshrc file and now it looks like this:
`export NODE_PATH=/data/data/com.termux/files/usr/lib/node_modules
export  LD_LIBRARY_PATH=/data/data/com.termux/usr/lib/node_modules/berkeleydb/lib/libdb-6.0.so`

With the .zshrc like this i got error on every commands because it seems it cannot find any library at all for everything, not even `nano` is working.
The only way to revert this situation is to remove the .zshrc file.

@vishalbiswas what am i missing?

**Comment by vishalbiswas** [comment]
`LD_LIBRARY_PATH` should contain directories, and you should add to it, not override it
Add this in your .zshrc
`LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PREFIX/lib/node_modules/berkeleydb/lib`
