### ISSUE TITLE
Why Termux exits switching to another app?

### ISSUE THREAD

**Issue by angelog0** [termux/termux-app#3566]
They are few weeks (months?) I notice this behavior:

- Start Termux and play something there (`ls -lrt`, `pkg upgrade` etc)
- Switch to another app (the browser, File manager and so on) via the Home page (the central box at the bottom)
- Now return to Termux via the three vertical lines on the bottom-left

Termux restart from scratch as if it had exited: if `pkg upgrade` was running it has been interrupted.

I can reproduce this on the device with android 11 but non with the one with android 8.1..

Any idea why this happens?

TIA

### System information

* Termux application version: 0.118
* Android OS version: 11
* Device model: Galaxy Tab S5E

Attached the output of `termux-info`
[info.tar.gz](https://github.com/termux/termux-app/files/12488092/info.tar.gz)

**Comment by agnostic-apollo** [comment]
Probably just samsung being samsung.

https://dontkillmyapp.com/samsung

You can run `adb shell "dumpsys activity exit-info com.termux"` or `adb logcat -d > /sdcard/logcat.txt` after app is restarted to find more info. Will need to run from pc or in termux with `adb` from `android-tools` package with wireless mode.

**Comment by angelog0** [comment]
Thanks. I think I have fixed it now. Thank you very much!!!

**Comment by agnostic-apollo** [comment]
You are welcome.
