### ISSUE TITLE
Hash sum mustaches

### ISSUE THREAD

**Issue by CowDink** [termux/termux-app#357]
Im trying to apt update, and i get
'''
Get:1 http://termux.net stable InRelease [1666 B]
Get:2 http://termux.net stable/main all Packages [3820 B]
Err:2 http://termux.net stable/main all Packages
  Hash Sum mismatch
Fetched 3820 B in 2s (1854 B/s)
Reading package lists... Done
E: Failed to fetch http://termux.net/dists/stable/main/binary-all/Packages.xz  Hash Sum mismatch
E: Failed to fetch http://termux.net/dists/stable/main/binary-arm/Packages.xz
E: Some index files failed to download. They have been ignored, or old ones used instead.
''"
I've been googling and some answers
* apt clean
* and some others way

and it's doesn't work.
i can't reinstall it because i love my current config

how can I fix that?

### Sorry for my bad English

**Comment by CowDink** [comment]
*mismatch

**Comment by sm4rk0** [comment]
Could this be recurrence of #174 and #289?
BTW, pkg update works for me.

**Comment by Neo-Oli** [comment]
> *mismatch

Leave it like that. Hash sum mustaches is so much better. 😄 

This is a recurring problem with Cloudflare. @fornwall usually does some cache purging or something to make it go away. Maybe it even fixes itself after a while. Just wait a day or so and it should be fixed. 
This is a problem with the network infrastructure of http://termux.net, nothing you can do. Even reinstalling won't help.

**Comment by CowDink** [comment]
it's work now!
thanks all
