### ISSUE TITLE
Xiaomi HW-Note 1 isn't compatible with termux

### ISSUE THREAD

**Issue by Jenusdy** [termux/termux-app#358]
I was trying to install termux, but there is nothing install button just, a information said "Your device is not compatible with this version"

**Comment by vishalbiswas** [comment]
Android 5.0 and above is the minimum system requirement

**Comment by Quasic** [comment]
There are terminal emulators for older versions, such as TermIDE, (which is one I've used, before. It doesn't support Android 5.0+. :p Some things changed between the versions that seem to make it difficult to support them all and still be powerful.)
