### ISSUE TITLE
[Feature]: Allow custom terminal margin

### ISSUE THREAD

**Issue by amaramth** [termux/termux-app#3580]
A setting for the width of the left margin would be especially helpful for some devices. When having 70-78 columns, which are common settings in portrait mode with the font Iosevka, an extra column would make a large difference for readability of existing material formatted for 80 columns.

The possibility of a (slightly) negative left margin and an option for a negative right margin width would also be helpful.

Conversely, larger margins would assist people whose screens are unreadable on the edges.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/commit/63504f0adc935977b662c7257464d1fc492b6374

**Comment by amaramth** [comment]
Thank you! With `terminal-margin-horizontal = 0` I get 72 or 80 columns up from 70 or 78.

**Comment by agnostic-apollo** [comment]
You are welcome.
