### ISSUE TITLE
Xposed is not compatible with android SDK version 23 (Libdvm not found)

### ISSUE THREAD

**Issue by ariefibis** [termux/termux-app#359]
Hello, Gm 　 just one concern while setting up a dynamic environment ...I tried setting up a VM using genymotion but our apk is compatible only with version 5 or above ...wherein dynamic mobsf it should be 4.0.3 to 4.4 I guess if I am not wrong ...Is there a chance it can be updated to compatible versions or any other alternative which could help.
![mobsf](https://user-images.githubusercontent.com/22467094/28102901-002a3a6a-66f0-11e7-91bd-dee0b8caebd1.PNG)
![mobsf2](https://user-images.githubusercontent.com/22467094/28102902-04c1388a-66f0-11e7-9f6a-a51a99359c83.PNG)

Please do the needful

Thanks and Regards,
Mohammed arief.A

**Comment by vishalbiswas** [comment]
Wrong Repository?

**Comment by ariefibis** [comment]
sorry posted by mistake
