### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by abuhabban** [termux/termux-app#3599]
### Problem description

whenever i try to download zip fule from drive it show this now able to download zip file why this pop appear everytime
![Screenshot_20230926_212740_Drive](https://github.com/termux/termux-app/assets/70461458/d1fef975-05d0-4be1-95a8-962f25effdb8)
how can i disable this popup 

### Steps to reproduce the behavior.

no idea

### System information

* Termux application version: latest
* Android OS version: 13
* Device model: samsung a14 5G

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/commit/af6ac30b if using github builds, otherwise wait for fdroid release. Or install an app that can open zip files.

**Comment by abuhabban** [comment]
> [af6ac30b](https://github.com/termux/termux-app/commit/af6ac30b) if using github builds, otherwise wait for fdroid release. Or install an app that can open zip files.

Sorry i asked wrong question actually i don't want "open with termux" popup because it is blocking my downloading. Files not getting download in chrome because termux popup block other......

**Comment by abuhabban** [comment]
> Read the commit message again, add `disable-file-view-receiver=true` entry to `termux.properties` file so that it doesn't show.

already done i think termux should release new version because i am using latest release which from 2022 January. If this not possible send me latest build for v8 apk or tell me how can i build apk from source using github.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

**Comment by abuhabban** [comment]
> https://github.com/termux/termux-app#Installation

Thanks for this link i understand lots of things but can you please give me safe and latest artifacts link

**Comment by abuhabban** [comment]
> > https://github.com/termux/termux-app#Installation
> 
> Thanks for this link i understand lots of things but can you please give me safe and latest artifacts apk link.

**Comment by twaik** [comment]
https://github.com/termux/termux-app/actions/workflows/debug_build.yml?query=branch%3Amaster+event%3Apush
As posted in readme. You should read it carefully.

**Comment by abuhabban** [comment]
i have done this by forking termux
https://github.com/abuhabban/termux-app/actions
