### ISSUE TITLE
programs that produce a lot of output freezes app.

### ISSUE THREAD

**Issue by cswl** [termux/termux-app#36]
I ran to this issue again today,
https://plus.google.com/u/0/105143408064070053742/posts/SckNbhF6RQY
I was busy with other stuffs so I had made a quick post there hoping someone would chime in..  great to know that issues I wanted to report with C++ linking and play-audio have been resolved already.

Anyways back to current issue, programs that write a lot of output to terminal freezes app. I investigated it a bit and it doesnt happen if the write is limited..

Here's a test case..
Run a program that writes to terminal
` find $PREFIX/lib`
The terminal will output until a new line and freeze until the command completes.

Now limit the output with pv.
` apt install pv`
 ` find $PREFIX/lib | pv -L 2048`
The output will be scrolled too fast to read in the terminal but it doesnt freeze the app.

**Comment by PwnicornDev** [comment]
I can't reproduce this at all. I just tried `find /` and it scrolls smoothly until I interrupt it.

**Comment by cswl** [comment]
This seems like an issue with tmp-mksh on OmniROM.  As I'm getting this on other term emulators too.

I guess I will close this as it is not related to Termux only.
