### ISSUE TITLE
[Bug]: stop "open with Termux" popup appearing

### ISSUE THREAD

**Issue by abuhabban** [termux/termux-app#3600]
### Problem description

(Edited) please read i described by problem
whenever i try to download zip file from drive it show this. I am not able to download zip file why this pop appear everytime.If this pop not appear then the file i am downloading from drive will get downloaded as usual.
![Screenshot_20230926_212740_Drive](https://github.com/termux/termux-app/assets/70461458/e9954f4e-f33c-4bbd-9e41-1deb1dec48e1)

### Steps to reproduce the behavior.

noidea

### System information

* Termux application version: latest github release
* Android OS version: 13
* Device model: samsung a14 5g

**Comment by agnostic-apollo** [comment]
Do not create duplicate issues.
