### ISSUE TITLE
wake lock doesn't work

### ISSUE THREAD

**Issue by netllama** [termux/termux-app#361]
When I enable a wake lock it fails to keep my phone's screen on after the default timeout period.  

I'm using a Nexus 5x running Android 6.0.1.  Let me know if additional data is needed.

**Comment by vishalbiswas** [comment]
@netllama wakelock doesn't mean that your screen will be on until you release it. Wakelock is for the CPU of the device. Taking a wakelock means keeping the CPU running even when you are not using it. Even with your screen turned off, the CPU will not go to sleep if you take a wake lock.

**Comment by netllama** [comment]
Sorry, I was lead to believe that the wakelock would keep the screen on:
https://plus.google.com/106768720324164717366/posts/bzXBXeza1HG

Is this possible via a different mechanism within Termux?

**Comment by vishalbiswas** [comment]
actually, it can keep the screen on, but in Termux we only have a partial wakelock, I think.
Let me check

**Comment by pawelotto** [comment]
I'm getting huge lags even if wake-lock is on but screen dims. Any ideas why?

**Comment by Quasic** [comment]
Are you using SSH or telnet? If so, #1193 may be related.

**Comment by pawelotto** [comment]
On my Samsung S5 I resolved the lags issue by running ping in the screen session back to my client IP. Seems that the WiFi going to sleep was the culprit here.
