### ISSUE TITLE
[Bug]: ':app:processDebugMainManifest'

### ISSUE THREAD

**Issue by hamedgayou-a11y** [termux/termux-app#3610]
### Problem description

FAILURE: Build failed with an exception.                                                                                    * What went wrong:                                            Execution failed for task ':app:processDebugMainManifest'.    > Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @3f6482d9

### Steps to reproduce the behavior.

FAILURE: Build failed with an exception.                                                                                    * What went wrong:                                            Execution failed for task ':app:processDebugMainManifest'.    > Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @3f6482d9

### What is the expected behavior?

Unnamed Module

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by agnostic-apollo** [comment]
Have you made changes to termux-app build source?

**Comment by Aayush1357** [comment]
I have fixed the issue kindly check?

**Comment by twaik** [comment]
Not enough data to make any assumptions. This issue may be closed in the case there will be no additional data that may be analyzed.
