### ISSUE TITLE
I Find an APP Called NeoTerm

### ISSUE THREAD

**Issue by YadominJinta** [termux/termux-app#362]
NeoTerm uses the source of Termux,but it's not open source.It violates GPL V3.
You can find the author here http://www.coolapk.com/apk/io.neoterm

**Comment by PwnicornDev** [comment]
The developer seems to be [zt515](https://github.com/zt515) on GitHub. **Please don't start a witch hunt and leave it for @fornwall  to decide how to proceed in this matter!**

**Comment by YadominJinta** [comment]
In additional,there two developers,one is [zt515](https://github.com/zt515),and another one called Lody,but I can't find the exactly one.

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fornwall** [comment]
The NeoTerm source code is now available at https://github.com/NeoTerm/NeoTerm/ under the GPL3 license (an attribution notice somewhere would have been nice, but the most important thing here is the license and source code availability).
