### ISSUE TITLE
[Bug]:  shift doesnt uppercase letters

### ISSUE THREAD

**Issue by therealolie** [termux/termux-app#3637]
### Problem description

when you toggle SHIFT and press letters they are still inputted as lowercase, instead of uppercase
https://github.com/termux/termux-app/assets/46534106/152772a6-f9e7-4cee-862c-e349348b0138

### Steps to reproduce the behavior.

set your extra-keys list using
`extra-keys=[[{key:"1",popup:"!",display:"1!"},{key:"2",popup:"@",display:"2@"},{key:"3",popup:"#",display:"3#"},{key:"4",popup:"$",display:"4$"},{key:"5",popup:"%",display:"5%"},{key:"6",popup:"^",display:"6^"},{key:"7",popup:"&",display:"7&"},{key:"8",popup:"*",display:"8*"},{key:"9",popup:"(",display:"9("},{key:"0",popup:")",display:"0)"}],[{key:"q",popup:"ESC"},{key:"w",popup:"UP",display:"w▲"},{key:"e",popup:"-",display:"e-"},{key:"r",popup:"+",display:"r+"},{key:"t",popup:'"',display:'t"'},{key:"y",popup:"'",display:"y'"},{key:"u",popup:":",display:"u:"},{key:"i",popup:"INS"},{key:"o",popup:"HOME"},{key:"p",popup:"PGUP"}],[{key:"a",popup:"LEFT",display:"a◀"},{key:"s",popup:"DOWN",display:"s▼"},{key:"d",popup:"RIGHT",display:"d▶"},{key:"f",popup:";",display:"f;"},{key:"g",popup:"?",display:"g?"},{key:"h",popup:",",display:"h,"},{key:"j",popup:"_",display:"j_"},{key:"k",popup:"DELETE"},{key:"l",popup:"END"},{key:"BACKSPACE",popup:"PGDN"}],[{display:"⧋\\\\",key:"SHIFT",popup:"BACKSLASH"},{key:"z",popup:"/",display:"z/"},{key:"x",popup:"~",display:"x~"},{key:"c",popup:"`",display:"c`"},{key:"v",popup:"|",display:"v|"},{key:"b",popup:"=",display:"b="},{key:"n",popup:"{",display:"n{"},{key:"m",popup:"}",display:"m}"},{key:",",popup:"<",display:",<"},{key:".",popup:">",display:".>"}],[{key:"CTRL",popup:""},{key:"FN",popup:""},{key:"ALT",popup:""},"TAB",{key:" ",popup:"KEYBOARD"},{key:" ",popup:"KEYBOARD"},{key:" ",popup:"KEYBOARD"},"[","]","ENTER"]]`
then toggle shift and try pressing the letters

### What is the expected behavior?

inputted letters are uppercase when shift is enabled

### System information

* Termux application version: latest - v0.118.0
* Android OS version: 10 aarch64
* Device model: HUAWEI CLT-L29

**Comment by rahul13agrawal** [comment]
Can I look into this?

**Comment by twaik** [comment]
Additional key bar sends symbols as it is configured, regardless of pressed key modifiers. This behaviour can not be overridden because it will break existing configurations.

**Comment by therealolie** [comment]
.
