### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by CowDink** [termux/termux-app#364]
how to do this in termux

ctrl + w + =

**Comment by Auxilus** [comment]
In termux , `ctrl` = `vol low button` , `Alt` = `vol up button` ( that's why you can't adjust volume when you are in termux ) 

So for Ctrl W , hold ` vol down button` and press `w`

**Comment by CowDink** [comment]
i know, but how to use 3 combination
(ctrl w =)
