### ISSUE TITLE
[Feature]: biild X11 window under termux

### ISSUE THREAD

**Issue by RimeOCRLIB** [termux/termux-app#3652]
### Feature description

Good day.

For OCR ANN training we need build x11 window in Termux, capture mouse and refresh pixel buffer in window.

For now one of the best option it is create X11 window and refresh it by CImg library.
Xfce4 work fine, GTK programs (Inkscape, fontforge) works fine.
For now we start build ncurses gui version with pixel block graphics. It is too slow and have 200x300  resolution only.

Problem it is we can not connect to X11 display from c.
in main.c
Display *d = XOpenDisplay(0);
failed with d==NULL

With SDL2 library we also have success build and run but no window.

Any help will be greatly appreciated.

Open Source Buddhism Library
Alexander Stroganov
gomde@mail.ru

### Additional information

Some terminals have support for Sixel graphic
https://en.m.wikipedia.org/wiki/Sixel but X11 pixel buffer will work faster.
May be make addition Android View in termux to give cpp programs pixelbuffer and mouse?

**Comment by twaik** [comment]
XOpenDisplay returns NULL because you are starting your program without DISPLAY environment variable...

**Comment by RimeOCRLIB** [comment]
thanks for reply.
in .bashrc
===
export DISPLAY=":1"
===
does it set environment variable for X11?
Fluffbox and Gtk programs work fine with export DISPLAY=":1" according this wiki
https://wiki.termux.com/wiki/Graphical_Environment

may by X11 code need direct instruction how connect to vncserver stream?
or addition permissions?

**Comment by twaik** [comment]
> may by X11 code need direct instruction how connect to vncserver stream?
> or addition permissions?

Wdym?

**Comment by RimeOCRLIB** [comment]
sometimes this problem exist after installation of x11vnc https://wiki.archlinux.org/title/x11vnc
https://stackoverflow.com/questions/43845316/x11vnc-xopendisplay-failed
and it is permission or firewall conflict

**Comment by RimeOCRLIB** [comment]
yes. you are right. So it is not understandable for now why XOpenDisplay failed.
we may try to check this code on UserLand distro.

**Comment by RimeOCRLIB** [comment]
yes.
putenv("DISPLAY=:1");
Display *d = XOpenDisplay(0);
failed also.

**Comment by twaik** [comment]
DISPLAY must be set outside a program. Because user may use any DISPLAY, even `:42`. Make sure you have started VNC server.

**Comment by RimeOCRLIB** [comment]
yes. checked. Xfce work fine and we are able start Inkscape from termux terminal or from Xfce.

**Comment by twaik** [comment]
Try to start your program from aterm or xfce4-terminal.

**Comment by RimeOCRLIB** [comment]
Thanks from my heart for yor kind help.
Program file and vncserver user need to have same permission. Program was compilled under sudo command. If build it as termux user, all worked.
Problem solved.
