### ISSUE TITLE
#Request Bluetooth

### ISSUE THREAD

**Issue by thenickvendetta** [termux/termux-app#367]
Can I use termux to connect to the Bluetooth device?

**Comment by sdrausty** [comment]
https://github.com/sdrausty/buildAPKsApps/tree/92c1d13a460db3f7b29565b1a58e5e9cf60f8742/BluetoothChatMulti builds on device in Termux. There are other Bluetooth APK projects that build and install on device (a smartphone). You can find them by running `ack Bluetooth` in ~/buildAPKs https://sdrausty.github.io/buildAPKs/setup

**Comment by dingausmwald** [comment]
Esp BLE would be awesome

**Comment by fornwall** [comment]
See https://github.com/termux/termux-api/issues/88 - it would probably come as an extension to termux-api.

**Comment by mjarvisal** [comment]
I will start working on this by the end of the week. I have a standalone bluetooth serial terminal application working. I will integrate it one way or the other.
