### ISSUE TITLE
Laggy backwards-scrolling in multiple applications

### ISSUE THREAD

**Issue by dredmorbius** [termux/termux-app#368]
I'm noticing that termux is very laggy when scrolling _backwards_ through applications.  This occurs both on local and remote (ssh'd _oot_ to other hosts) instances, which makes me suspect the issue is basic terminal functionality.

Example:

* Open Termux
* Open a large manpage using less as the pager.  The `bash` manpage is a good example.
* Skip to the end of the page (`G`).  From here:
* Single-line scrollback is relatively quick:  `k`
* Multi-line scrollback starts lagging:  `10k`
* A larger scrollback of 100 lines takes ~25 seconds:  `100k`
* Skipping to the top of the file sees a few seconds of lag, but not as much as the large scrollback:  `1G`

Vim noticeably _doesn't_ suffer from this (thankfully).  Pagers though do.

I'm looking to see if there's a way to access the Termux environment from another terminal to confirm my hunch.  The stock Android terminal environment cannot access the Termux files :(

**Termux Info**
```

Termux version:
<=0.48
Installed Termux apps:
package:com.termux.api  installer=com.android.vending
package:com.termux  installer=com.android.vending
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.49-5975984 #1 SMP PREEMPT Thu Oct 8 17:25:20 KST 2015 armv7l Android
Termux-packages arch:
arm
Android version:
5.0.2
Device manufacturer:
samsung
Device model:
SM-T550
```

**stty -g output**

    4100:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0

**Keywords**

terminal lag laggy scroll scrollback backscroll

**Comment by dredmorbius** [comment]
I've confirmed that this behaviour does _not_ exist when accessing termux via busybot's terminal:

* Launch sshd:  `sshd`
* Copy the public key from Connectbot into `~/.ssh/authorized_keys`
* Connect from Connectbot to localhost:8022.

Attempt viewing and scrolling forward and backward through the bash manpage as described above.

**Result:** No lag.

Again, I suspect terminal emulation is the fault.

**Comment by xeffyr** [comment]
Should be already fixed (or at least reduce lags) with https://github.com/termux/termux-app/pull/628. If not, ask to re-open issue.
