### ISSUE TITLE
[Bug]: Questions about phantom process killer

### ISSUE THREAD

**Issue by Dusk0531** [termux/termux-app#3682]
### Problem description

Sorry for asking irrelevant questions in the termux project. I am running Android 13, but I found that after using too many processes, they will be killed. After searching, I found that it is a phantom process killer function introduced in Android 12. In Android 13, you can use an adb command to directly close it. Function Android 12’s solution is to increase the number of processes. What should be the shutdown command?

### Steps to reproduce the behavior.

Android 13 has a command that can directly turn off the phantom process killer instead of raising the limit threshold like Android 12.

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
You have commands for different android versions in https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#commands-to-disable-phantom-process-killing-and-tldr. For android 13: https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#android-12l-13-and-higher-1
