### ISSUE TITLE
ChromeOS: Termux is unable to download bootstrap packages

### ISSUE THREAD

**Issue by jheiselman** [termux/termux-app#369]
Model: Lenovo N22
ChromeOS Version: 60.0.3112.72
Platform: 9592.66.0
Firmware: Google_Reks.7287.133.81
Channel: Beta
ARC Version: 4194258
Blink: 537.36
V8: 6.0.286.44

Steps to reproduce: 
1. Powerwash Chromebook
2. Setup account
3. Switch to beta channel
4. Update ChromeOS
5. Install Termux from Play Store
6. Launch Termux

Expected result:
App should launch like it does on Android, install the bootstrap packages, and complete setup

Actual result:
Termux has a pop-up error that states "Termux was unable to install the bootstrap packages. Check your network connection and try again."

The Play Store app works to browse and install apps, though no other apps have been tested. I don't believe this is an issue with my Chromebook's network connectivity.

**Comment by Schuk** [comment]
Same thing here on Acer R11

Chrome: 60.0.3112.50 
Platform: 9592.37.0 (Official Build) beta-channel cyan
Firmware: Google_Cyan.7287.57.100
ARC Version: 4127354
Blink: 537.36 (@)
V8: 6.0.286.23

**Comment by tydavis** [comment]
Same thing here on Samsung Chromebook Plus. Details on platform coming.

**Comment by thephilwells** [comment]
Same on Samsung CHromebook 3

Chrome: Version 60.0.3112.72 (Official Build) beta (64-bit)

Was able to install other app (lack) from Ply Store using same network connection.

**Comment by fornwall** [comment]
This should be fixed now - it was a problem after a web server migration for increased capacity. Does it work for you now?

**Comment by jheiselman** [comment]
All good now. Thanks @fornwall

**Comment by askvictor** [comment]
I'm getting the same issue on a Chromebook (Lenovo N23 Yoga). However, I suspect the issue relates to the network more than the device - our network uses a MITM transparent proxy to snoop on SSL connections. I've installed the root certificate in Chrome and normal websites work fine. I'm wondering if Termux honours the OS's SSL certificates, or if it relies purely on its own certs? I work in a school and was hoping to use this app with my students, but if it can't easily bootstrap itself I won't be able to.
