### ISSUE TITLE
I am stuck in Google's keyboard...

### ISSUE THREAD

**Issue by OpnSrcConstruction** [termux/termux-app#37]
This started about the time I bought the styling app, so I suppose there is a slight chance this is related. Google's keyboard lacks too many modifier, function, and arrow keys to be useful on a cli app like Termux. I have the hacker's keyboard set, and it works in all other apps; with the exception of Termux.

I am sorry for not reporting this sooner, but I've been setting up a new laptop. I am running on a 1st gen N7 rooted w/ cyanogenMod. 

I updated Termux/packages on an Identical N7 except 4 it's stock rooted, w/o the styling app; and it's Termux still picks up the Hacker's Keyboard just fine.

I am going to try w/o the styling app, and see if that helps. I might also try wiping the app cache 4 Termux. If these steps fail I will try a backup/reinstall of Termux.

I'll report back if anything I can come up w/ works.

btw This is Kevin Lausen from G+ & kjlw_99 on irc

**Comment by fornwall** [comment]
Ok, so on your N7, the hacker's keyboard does not show up even though you have selected it and it works in other apps?

A guess would be that the problem lies in the system (cyanogenmod) since the underlying handling of which keyboard to show is done by the system, not the app themselves...

**Comment by OpnSrcConstruction** [comment]
found the settings 4 input method  in the HK settings after re-inbstalling it. I wiped the apps cache first, accidentally emptying my packages....oops...lesson learned.

**Comment by fornwall** [comment]
@OpnSrcConstruction Great that you got it working!
