### ISSUE TITLE
Not able to SSH on 4G.

### ISSUE THREAD

**Issue by dwrz** [termux/termux-app#370]
I'm running into a strange problem SSH'ing into a home server from Termux on 4G. I get a connection time out and 100% packet loss on pings. Tracepath/route seem to get to my ISP, but then a bunch of no replies.

The issue seems to be limited to Termux only. If I setup a mobile hotspot and try to connect from another device, I'm able to access the server with no issues. There are also no problems browsing a webpage hosted on the same IP (but on a different server).

There are no problems SSHing from Termux on WiFi. 

I first ran into this issue last week. After running an update though, everything started working again.

I contacted my mobile provider, and they stated they were having no issues with their network.

Any suggestions on how to troubleshoot this issue?

**Comment by Neo-Oli** [comment]
> After running an update though

What did you update? Termux? Android?

>  browsing a webpage

Can you check this from Termux? E.g. `curl http://111.111.111.111/`

**Comment by dwrz** [comment]
> What did you update? Termux? Android?

Sorry -- Termux, with apt update. A few packages updated. I don't remember them all, but one was ca-certificates.

> Can you check this from Termux? E.g. curl http://111.111.111.111/

Nothing seems to happen. But same goes for my laptop.

**Comment by Neo-Oli** [comment]
> curl http://111.111.111.111/

Sorry if it wasn't clear enough. I meant use curl to browse whatever the IP address is that you're trying to reach 

> browsing a webpage hosted on the same IP (but on a different server).

**Comment by dwrz** [comment]
Sorry for my ignorance! I just tried it -- curl works with both the IP and hostname. Ping still fails.

--
dwrz|朱为文

**Comment by Neo-Oli** [comment]
Hmm... What is the output of `ssh [IP] -v`?

**Comment by dwrz** [comment]
Thank you -- now I know what to do next time. I'd misconfigured the hostname in my config, leaving it the same as for local. SSHing to the IP worked, so I tried to SSH with the hostname and noticed it was trying to use the local name. Thanks again and apologies!

**Comment by Noob1234556** [comment]
My problem is similar to that I think so 
I am using termux recently and for port forwarding I used

ssh -R (Desired_Port):localhost:(Desired_Port) serveo.net

And the result is 

ssh: connect to host serveo.net port 22: Connection timed out 

Plz help me to solve it

**Comment by xeffyr** [comment]
@Noob1234556 Have you read information on its site (http://serveo.net/) ? There written - `disabled`, i.e. Serveo is down now.

**Comment by Noob1234556** [comment]
Thanks for information xeffyr,
Can you please recommend me a similar website like that?

**Comment by Noob1234556** [comment]
> @Noob1234556 Have you read information on its site (http://serveo.net/) ? There written - `disabled`, i.e. Serveo is down now.

Thanks for information xeffyr,
Can you please recommend me a similar website like that?

**Comment by xeffyr** [comment]
@Noob1234556 You have such variants as Ngrok (https://ngrok.com/) or https://localhost.run/.

**Comment by Noob1234556** [comment]
Tq for help

**Comment by Noob1234556** [comment]
> @Noob1234556 You have such variants as Ngrok (https://ngrok.com/) or https://localhost.run/.

Tq for help xeffyr
