### ISSUE TITLE
[Bug]: php-fpm CANNOT LINK EXECUTABLE "php-fpm": library "libicuio.so.73" 

### ISSUE THREAD

**Issue by dalongxia2017** [termux/termux-app#3702]
### Problem description

~/termux/script $ php-fpm
CANNOT LINK EXECUTABLE "php-fpm": library "libicuio.so.73" not found: needed by main executable

### Steps to reproduce the behavior.

repo：mirrors.ustc.edu.cn
pkg install php*
php-fpm

### System information

* Termux application version:0.118.0
* Android OS version:13
* Device model:mix2s

**Comment by dalongxia2017** [comment]
我认为是软件包版本导致的，在我进行更新前，一直正常工作
translator：
I think it was caused by the software package version and it worked normally until `pkg upgrade`

**Comment by dalongxia2017** [comment]
我认为是软件包版本导致的，在我进行更新前，一直正常工作
translator:
I think it was caused by the software package version and it worked normally until `pkg upgrade`

**Comment by twaik** [comment]
Duplicate of termux/termux-packages#18482

**Comment by dalongxia2017** [comment]
Thank you for your answer
