### ISSUE TITLE
There's a bug when I install a package via npm 

### ISSUE THREAD

**Issue by andreJun1or** [termux/termux-app#3703]
### Problem description

When I try to install a package via npm or yarn return this message: "Segmentation fault"

### Steps to reproduce the behavior.

pkg install nodejs-lts
npm init -y
npm install fastify

### What is the expected behavior?

Install the package normally 

### System information

* Termux application version: 0.118.0
* Android OS version: Android 9
* Device model: Motorola moto e6s

**Comment by licy183** [comment]
Should be fixed by commit https://github.com/termux/termux-packages/commit/2a7aebbce1f49feffcb0bb26adcfefa72e8059c7.
