### ISSUE TITLE
[Bug]: Segmentation fault

### ISSUE THREAD

**Issue by andreJun1or** [termux/termux-app#3704]
### Problem description

When I try to install a package with npm or yarn it returns this message: "Segmentation fault", however it works normally on pc

### Steps to reproduce the behavior.

npm init -y
npm install fastify

### What is the expected behavior?

Install the package normally

### System information

* Termux application version: 0.118.0
* Android OS version: Android 9
* Device model: Motorola moto e6s

**Comment by licy183** [comment]
Duplicated of #3703
