### ISSUE TITLE
[Feature]: Persist Sessions Across Restarts - Save / Restore

### ISSUE THREAD

**Issue by Splizard** [termux/termux-app#3709]
### Feature description

It doesn't feel good to create a few sessions, name them for organisational purposes and then restart the app (or android restarts it) and they just go away. I understand anything running in those sessions would be terminated - and that's fine but I would like the history and session names to be somewhat preserved.

Since android goes to sleep often, it feels like an essential thing to address.

### Additional information

if you've ever used the terminal on a Mac for example you'll notice when you restart the computer with restore sessions on, it will include scrollable history and any tabs/windows will be preserved. I think the working directory is also preserved, which is helpful because it can be awkward to get back to the right directory in Termux rather than a "Open Terminal Here" often available on desktop/laptop platforms.

**Comment by agnostic-apollo** [comment]
If you use `exit` command or `Ctrl + D` to close the session, then your history should be saved by your shell.

If you use notification `Exit` button or android kills the app, then it won't be. Related https://github.com/termux/termux-app/issues/1988#issuecomment-812684788

Mac just stores the scrollback history, not process state.

https://apple.stackexchange.com/a/278381

**Comment by Splizard** [comment]
> Mac just stores the scrollback history, not process state.
Yes and this is very convenient. 

Even disregarding the history though, persisting session names and working directories across all types of restarts is very valuable, as effort towards organising these sessions for different purposes is not lost. 

Imagine if web browsers on Android just lose all of your tabs when they are restarted/killed. This would be incredibly frustrating. It doesn't really matter what signal you send to them, they'll happily open up the same locations where you left off.

**Comment by romanovj** [comment]
you can write your own scripts for termux, bash and tmux/screen

there are many examples https://github.com/alessandro-g89/bash-sessions

**Comment by twaik** [comment]
Not possible due to the nature of linux programs.
Unlike Mac or Android it is not possible to save or restore process state of running program. Even in the case if you dump process memory and then restore it nothing will work because we can not restore opened file descriptors, sockets and linked processes. 
As said above the only thing you can do is to close terminals with `exit` command or `Ctrl + D` to save shell history and write some scripts, shortcuts or aliases to open needed programs faster.

**Comment by Splizard** [comment]
Hi @twaik,

Nowhere did I mention saving or restoring process state. Only the working directory if possible and even better if you could see some of the history by scrolling to remember what you were doing.

The point is, if I create 5 different sessions in the Termux sidebar and name them all. I want these named tabs to persist so I can use them as markers for different activities.

![Screenshot_20231224_104514_Termux](https://github.com/termux/termux-app/assets/2015791/9d2cbc06-cd27-43cc-b31a-65ef2067323d)

The responses here are akin to asking a web browser on Android to persist open tabs on restart - this is a fairly standard user experience, and getting the response "its too hard to suspend/resume web state".

This has been a solved problem on browsers on all platforms, you simply reload the location of the page when you visit the tab again.

Im a bit disappointed this issue has been closed as completed, when the user experience issue has not been addressed.

I've been told that there this is scriptable, without any reference to a mechanism to list or open termux sessions via commands.

If tmux is the solution, why does Termux have a session sidebar?

**Comment by agnostic-apollo** [comment]
You can use `RUN_COMMAND` intent to start sessions.

If using github action builds (will be available in next release), you can also switch to a named session if it is already open. Check #2668
