### ISSUE TITLE
[Bug]: display is not refreshed or updated (custom termux-app)

### ISSUE THREAD

**Issue by craigcomstock** [termux/termux-app#3711]
### Problem description

I have been using a modified termux-app to which I added gesture-based typing on the screen itself. See https://github.com/craigcomstock/termux-app/tree/gesture-master. The basic operation works like this video:

https://unreasonablefarm.org/2023-05-17-unrznbl-gesture-demo.mp4

This app has been working great for me for a long time, years... until I tried to modify it to be the home app launcher.

The primary device I am using is a Timex FamilyConnect Senior watch FWIW.

When I install this home app version I can see orange lines trace as I draw characters as usual and I can type on the OSK and type on a bluetooth keyboard that is paired but no characters are updated on the screen. If I turn the device off then back on I can see the updates. Or if I press the back button to exit termux and then it re-enters because it is the home app, the updates are present.

I don't see this behavior in an emulator and don't see this behavior in my version of this app without the home app/launcher modification to the manifest: https://github.com/termux/termux-app/commit/fbf0599a85cb555224ef5e36d147062ba9e82af1

Thanks for any tips. I understand I am working on a custom version so support could be minimal but I do intend to eventually try and achieve these same results with a separate app like termux-styles if that's possible. :) And I am also trying to stay up-to-date with master.

If you have any tips/ideas on how to incorporate my gesture and home/launcher features upstream in an optional way or as separate apps let me know.

In further testing just now I noticed that screen updates on a reboot (termux-app is launched as home) but after one back or off/on button press the display stops working. Maybe my manifest changes are a bit "wrong" somehow to make termux-app the home app/launcher?

I still don't see anything "interesting" in logcat, but maybe someone knows of something to look for.

Thanks!

### Steps to reproduce the behavior.

Install my version on a device (I will try and find another android device to test with!)
write gestures, type on the OSK, type on a bluetooth keyboard

### What is the expected behavior?

see updates on the screen

### System information

* Termux application version: customized master (2 commits behind right now)
* Android OS version: 8.1.0
* Device model: msm8909w

**Comment by craigcomstock** [comment]
I did a bit more testing and it seems that only the back button causes the display to stop updating. Pressing power off/on multiple times doesn't affect termux-app's ability to display updates. I will test on another device to see if I can reproduce/debug there.

**Comment by craigcomstock** [comment]
Tested on a Lenovo TB-X104F tablet, Android 8.1.0 also and see a similar problem. Pressing home brings up termux-app and display is updated. As soon as I press the back button things get really weird on the tablet: I get nothing on the screen and pressing back several times doesn't get me to termux-app. The home button does bring up termux-app again but display updates don't work after that first back-button sequence.

**Comment by craigcomstock** [comment]
I experimented with making the gesture drawing layer smaller so that part of the normal termux view is visible/on-top. Still, when I type after hitting back-button I don't see updates until I drag to scroll up/down in the termux view.

Obviously this is not a bug in your code, but I would appreciate some feedback on how to add my gesture layer and the home/launcher functionality upstream as plugins/options/???

**Comment by 0-Whoami** [comment]
maybe focusing issue, are you running on wear os  3 or higher?

**Comment by craigcomstock** [comment]
> maybe focusing issue, are you running on wear os 3 or higher?

yes, thank you. As far as I can tell this device is Android 8.1.0, so not wear OS?

I hope to dig into this more soon.

**Comment by 0-Whoami** [comment]
Maybe you are using wear os 2 , you can use gboard with termux to type in the terminal (set input type to text)

**Comment by craigcomstock** [comment]
> Maybe you are using wear os 2 , you can use gboard with termux to type in the terminal (set input type to text)

Ah yeah, I am very focused on using my own gesture software which just draws on top of the whole screen of console text.

I am going to work on this soon so will report back any tips I find and then close the issue. Certainly not a Bug but more of a discussion/question/request for advice from the experts.

**Comment by craigcomstock** [comment]
Best I can figure so far is that many TermuxActivity and TermuxTerminalSessionActivityClient instances are created during the course of the app's lifetime and that at some point (after I press back button to get out of the termux app and then it is re-launched because it is the "home/launcher" app) the updates from the terminal are going to the wrong activity/client and so not updating the screen.

I will check this again when termux-app is NOT the home/launcher app.

**Comment by craigcomstock** [comment]
Yep, If I remove the intent-filter bits for DEFAULT and HOME, I only see one instance of activity and client :( so I will debug further.

```
                 <action android:name="android.intent.action.MAIN" />
                 <category android:name="android.intent.category.LAUNCHER" />
-                <category android:name="android.intent.category.DEFAULT" />
-                <category android:name="android.intent.category.HOME" />
+                <!-- category android:name="android.intent.category.DEFAULT" />
+                <category android:name="android.intent.category.HOME" /-->
             </intent-filter>
```

**Comment by craigcomstock** [comment]
If I revert to latest master of termux-app and only make the two manifest line changes I get the same behavior of no screen updates after the first back-back away from termux-app. Scrolling with a swipe updates the screen but typing does not.

I have been debugging and see some odd bits around the sessions so maybe something there maybe onTextChanged() isn't seeing the same sessions and so doesn't call updateScreen/invalidate() and such.

I did notice an odd behavior: in an emulator I go "back" from termux-app and I get to the home screen, another "back" takes me to termux-app again as the "home launcher".

When I do the first back on my phone I get an odd message:

```
01-14 17:31:05.047   866  1955 D WindowManager: need pass key code and activity is com.termux.app.TermuxActivity
```

Almost like there would be a lock screen there or something, but there isn't, just the termux screen still.

**Comment by craigcomstock** [comment]
ok! interstitial activity seems to fix the issue. I have been using https://github.com/SimpleMobileTools/Simple-SMS-Messenger for quite a while with a simple mod:

```
             <intent-filter>
                 <action android:name="android.intent.action.MAIN" />
                 <category android:name="android.intent.category.LAUNCHER" />
+                <category android:name="android.intent.category.DEFAULT" />
+                <category android:name="android.intent.category.HOME" />
             </intent-filter>
         </activity-alias>
```

and it works great.

My https://github.com/craigcomstock/termux-app/tree/gesture-master branch is a mess of debugging RN but I did manage to refactor most of the gesture code OUT of TermuxActivity.java so that's an improvement. :) I consider this not-a-bug resolved so will close. Next time I will be careful about opening it as a discussion or not-a-bug of some sort.

Much thanks to @0-Whoami for trying to help!
