### ISSUE TITLE
Keyboard emersion in tmux, neovim

### ISSUE THREAD

**Issue by Dlazder** [termux/termux-app#3729]
### Problem description

When I hide the keyboard and view the terminal in tmux, I can't get the keyboard back up by tapping on the screen. same problem in neovim. It’s inconvenient for me to open the sidebar in order to open the keyboard by pressing a button; it takes a very long time.

### Steps to reproduce the behavior.

Just open tmux, hide keyboard and try open keyboard by tapping on the screen. 
in a regular terminal, there are no such problems.

### What is the expected behavior?

I want to open the keyboard anywhere by tapping on the screen, or speed up the process of opening the keyboard by adding a button or something like that

### System information

* Termux application version: 0.118.0
* Android OS version: 13
* Device model: Poco m5

**Comment by agnostic-apollo** [comment]
Use `KEYBOARD` extra key.

https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by Dlazder** [comment]
> Use `KEYBOARD` extra key.
> 
> https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

Thank you!
