### ISSUE TITLE
pyenv won't run (/usr/bin/env error)

### ISSUE THREAD

**Issue by j-bennet** [termux/termux-app#373]
I'm using termux on a Chromebook (Samsung Chromebook Pro, Version 60.0.3112.80 (Official Build) beta (64-bit)).

After installing pyenv and adding it to path:

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
```

I have an error running pyenv.

```
$ pyenv
zsh: /data/data/com.termux/files/home/.pyenv/bin/pyenv: bad interpreter: /usr/bin/env: no such file or directory
```

I found a related issue https://github.com/termux/termux-app/issues/228, but I was not able to find a solution.

**Comment by its-pointless** [comment]
This issue belongs in [termux-packages](https://github.com/termux/termux-packages) regardless the error you are seeing concerns /usr/bin/env that doesn't exist in android. run the command `termux-fix-shebangs ~/.pyenv/bin/pyenv` and it should make the shebang execute a version of env that does exist...

**Comment by vishalbiswas** [comment]
`termux-fix-shebang`, without the trailing 's'

**Comment by j-bennet** [comment]
After fixing that with `termux-fix-shebang`, I have an error in a different place:

```
$ pyenv
/data/data/com.termux/files/home/.pyenv/bin/pyenv: /data/data/com.termux/files/home/.pyenv/libexec/pyenv---version: /usr/bin/env: bad interpreter: No such file or directory
```

Running `termux-fix-shebang` on `~/.pyenv/libexec/pyenv` doesn't fix the problem.

**Comment by Grimler91** [comment]
@j-bennet Then it's some other file called by `~/.pyenv/libexec/pyenv` that has a none-working shebang. Look through `~/.pyenv/libexec/pyenv` and try to find out which one. 

You could also grep for it: `grep -rl '^#!\s\?/usr/bin/env' ~` but then lots of hits might turn up.

**Comment by fornwall** [comment]
Note that there are two other solutions:

1. `pkg install termux-exec` which will make `/usr/bin` and `/bin` shebangs work (for new Termux sessions - quit the current one). See https://github.com/termux/termux-exec for more.

2. `pkg install proot` and run `termux-chroot`, which will set up a chroot-like jail.
