### ISSUE TITLE
[Bug]: Permission Denied on executables (except for those in /data/data/com.termux/files/usr/bin/)

### ISSUE THREAD

**Issue by 1nfameArts** [termux/termux-app#3750]
### Problem description

Was trying to host a minecraft server(-s) on two of my unused phones. I was not going to write that allat for Velocity to start.
Either Paper. The phone that I was working on wasn't rooted, so I expected that some stuff will fail because of me not having root permissions. I was right. This can't run executables ANYWHERE. Neither in the home folder, neither in the internal storage.
Either someone fix this, or help me bypass SELinux security.

### Steps to reproduce the behavior.

1. Have a non-rooted phone
2. Create/add a file that is an executable
3. ./executable.sh
4. **bash: ./executable.sh: Permission Denied**

### What is the expected behavior?

FOR THE FILE TO RUN.

### System information

* Termux application version: 0.118.0 (from F-Droid)
* Android OS version: 10 QKQ.1.90828.002
* Device model: Mi 9 SE
### Additional info
My personal phone is suffering the same problem.

**Comment by twaik** [comment]
`chmod +x ./executable.sh`...

**Comment by 1nfameArts** [comment]
Did that,
bash: ./executable.sh: Permission denied.

**Comment by twaik** [comment]
Most likely you are doing something wrong.
It is not possible to do that in any storage other than termux's folders. Do
```
cd ~
echo "#!/bin/sh" > ./executable.sh
echo "ls -la ." >> ./executable.sh
chmod +x ./executable.sh
./executable.sh
```

**Comment by TomJo2000** [comment]
Please make sure any executables you want to run are in Termux's directory structure (for example in the home directory) as SD cards lack the required file permissions system, and execution permissions are only granted to an app within it's own file tree.

Make sure the file(s) have executable permissions.
You can check this with:
`ls -l your/directory/or/file/path`

If it is missing executable permissions you can assign it these using :
`chmod +x your/directory/or/file/path`

**Comment by 1nfameArts** [comment]
> Please make sure any executables you want to run are in Termux's directory structure (for example in the home directory) as SD cards lack the required file permissions system, and execution permissions are only granted to an app within it's own file tree.
> 
> Make sure the file(s) have executable permissions. You can check this with: `ls -l your/directory/or/file/path`
> 
> ```shell
> # example output 
> ls -l example
> # -rw------- 1 u0_a294 u0_a294 0 Dec 21 13:02 example
> # executable permissions are denoted by an x in the permissions column
> ```
> 
> If it is missing executable permissions you can assign it these using : `chmod +x your/directory/or/file/path`
> 
> ```shell
> # chmod example
> chmod +x example
> ls -l example
> # -rwx------ 1 u0_a294 u0_a294 0 Dec 21 13:02 example
> ```

This actually works when tested. Thanks!
