### ISSUE TITLE
[Bug]: can't install packages as root

### ISSUE THREAD

**Issue by testman42** [termux/termux-app#3751]
### Problem description

when logged in as root, running any `pkg` command results in:
`sh :pkg: inaccessible or not found`
but while logged in as user, using the command and installing packages works fine

after some investigation, I figured out that this is because the `$PATH`  for root does not include the directory with binaries for commands which is included in `$PATH` for the user.
so not only `pkg`, but many other commands don't work for root but do work for user
Is that intentional? Is there any issue open about this already?

### Steps to reproduce the behavior.

1. have rooted Android device
2. open termux
3. run `su`
4. grant permissions
5. try running any `pkg` command
6. error
7. ???????????
8. PROFIT

### What is the expected behavior?

to be able to install packages
like on desktop Linux
allowing user to install packages but not allowing root is some bizarre reverse-Linux logic 

### System information

* Termux application version: 0.118.0, from F-Droid / NeoStore
* Android OS version: LineageOS 20 / Android 13
* Device model: Fairphone 4

**Comment by twaik** [comment]
> * run `su`

`su` opens regular Android root shell. If you want to use termux tools here use `sudo` or `tsu`.

> * try running any `pkg` command

Termux does not allow installing packages as `root` because it will definitely break the whole termux environment.
