### ISSUE TITLE
Commands related to am (like `termux-open`, or any `termux-api` command) stopped working suddenly.

### ISSUE THREAD

**Issue by JacobTDC** [termux/termux-app#3754]
### Problem description

Out of the blue one day, commands related to am, like `termux-open`, as well as all `termux-api` commands stopped functioning. `termux-open` just runs and does absolutely nothing, while `termux-toast`, `termux-fingerprint`, etc. just loop forever without doing anything. No error messages are generated in logcat in any case.

I imagine it's some kind of configuration issue on my end or something, but I have no clue where to start. I noticed the issue after messing with calling hidden Android APIs from within Termux using app_process, so maybe that's related?

Here's a pastebin with the kind of stuff I was messing with, in case either helps: https://pastebin.com/jaK9MNwt

### Steps to reproduce the behavior.

Using any command that uses termux-api, as well as `termux-open` and other commands that call `am`.

### What is the expected behavior?

Literally anything.

### System information

Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11802
TERMUX_IS_DEBUGGABLE_BUILD=0                                           TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.6
Android version:
14
Kernel build information:
Linux localhost 5.15.110-android14-11-gcc48824eebe8-ab10865596 #1 SMP PREEMPT Tue Sep 26 19:57:58 UTC 2023 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 8 Pro
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:31

**Comment by HusniMuhammad** [comment]
``apt update && apt upgrade`` Try again

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-api/issues/638#issuecomment-1868383070

**Comment by JacobTDC** [comment]
> Check https://github.com/termux/termux-api/issues/638#issuecomment-1868383070

Yup! All fixed! 👌
Glad it wasn't just something I messed up on my end.

**Comment by agnostic-apollo** [comment]
I may have saved you this time, but surely there are more opportunities in future waiting for you to mess up.
