### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE 

### ISSUE THREAD

**Issue by AnimeWaifuGirl** [termux/termux-app#3755]
### Problem description

Termux doesn't work when the data/data/com.termux folder is linked 
![Screenshot_20231223-082620_Root_Explorer](https://github.com/termux/termux-app/assets/132521364/9f9b6b46-a485-49b8-899c-9fa87c1af503)

### Steps to reproduce the behavior.

Not possible to reproduce this issue!
It'll happened automatically if you moved the on the external vfat storage (external micro SDcard)

See what I mean exactly 
![Screenshot_20231223-083132_Settings](https://github.com/termux/termux-app/assets/132521364/ba8c9c26-3277-496a-8e36-52ff26d99bc9)

### What is the expected behavior?

![Termux_Screenshot](https://github.com/termux/termux-app/assets/132521364/02e0b04e-c1e2-4208-ac6e-2a7da9152509)

### System information

![Screenshot_20231223-081949_App_Manager](https://github.com/termux/termux-app/assets/132521364/4da6a939-736c-44ed-8367-2ebf607d468d)
 
**System Information(s):**
Brand: samsung
Product: lineage_a5y17lte
Board: universal7880
Architecture: aarch64
Bootloader: A520FXXSGCTK1
Rooted: true
OS Version: REL 11 (SDK v30)
Memory Usage: 2.38/2.95GB (0.57GB / 19.25% free)
Uptime: 50:43:24

**Comment by twaik** [comment]
Most probably that is partial update problem. `pkg up` and try again.

**Comment by twaik** [comment]
Also it is not possible to run any programs from sdcard due to Android limitations. Do not move application to sdcard.

**Comment by twaik** [comment]
Moving to sdcard broke file permissions. You should reinstall termux. And do not try to move it to sdcard again, it will definitely break it again.

**Comment by romanovj** [comment]
path is hardcoded, so you can't move termux to sdcard, but you can move app with shared uid with termux(like termux:boot) and create soft link to sdcard

https://www.reddit.com/r/termux/comments/12hty88/comment/jfuv5mg/?utm_source=reddit&utm_medium=usertext&utm_name=termux&utm_content=t1_jsk95oy

**Comment by twaik** [comment]
> The App is too broken!

Please, elaborate.

**Comment by twaik** [comment]
As said above `/data/data/com.termux` path is hardcoded in all termux packages and it is not possible to change it. Do not move application to expandable storage.
