### ISSUE TITLE
Feature Request: `mount loopback device`

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-app#376]
Feature Request: `mount loopback device`

This issue is fairly simple in Linux: **create file of a specific GB size > format filesystem in file > mount filesystem in file via loop device nonroot.** This sequence is impossible today on external micro SD storage in Termux on Android. You might even be mounting a filesystem from a file via loop device nonroot on a notebook or desktop without knowing it when you mount a USB stick, CD, DVD or similar. 

![screenshot_20170804-125035](https://user-images.githubusercontent.com/27742457/28978377-c7cc71a2-7913-11e7-97ba-e6517e95b0e9.png)

Referenced issues:

Feature Request: `mount loopback device`
https://plus.google.com/109614420080028230010/posts/4JcKJuy4ATa

Is it possible to grant permission for Termux to use loop devices?
https://github.com/termux/termux-app/issues/375

Does Anyone Want to Have More Native Space on Device?
https://github.com/termux/termux-packages/issues/1176

https://github.com/termux/termux-app/issues?utf8=✓&q=OTG

https://github.com/termux/termux-packages/issues?utf8=✓&q=OTG

**Reedited 20170804 UTC.** Previous version @ https://sdrausty.github.io/pages/376tapp

Debian Noroot might have the source code to close this issue. It appears to mount an image from a file using https://github.com/pelya/fakechroot "The scripts for creating Debian images are located in directory "img". https://github.com/pelya/debian-noroot/tree/master/img To prepare image, run these scripts:" from https://github.com/pelya/debian-noroot/blob/master/README.md

https://play.google.com/store/apps/details?id=com.cuntubuntu Please check Debian Noroot out if you can. It uses 900MB at start. It has gimp https://www.gimp.org It has lots of goodies; But please remember, you will want a keyboard and mouse.

![screenshot_20170803-132456](https://user-images.githubusercontent.com/27742457/28934792-39d24264-7850-11e7-8ca3-dbb7bd1288e6.png)
Screenshot of Debian Noroot running on an Android smartphone. 

https://github.com/pelya/debian-noroot 

"Run Debian on top of Android with a single click. No root required! Should work on any high-end device! Unleash full unrestricted desktop environment onto your mobile device! Instant frustration guaranteed! (unless you're using mouse or stylus) [and keyboard]."

```
git clone https://github.com/pelya/debian-noroot
cd debian-noroot
git submodule init
git submodule update //doesn't work, requires passphrase!?
ack loop
ack mount 
ack device
ack img
```

**Comment by OpnSrcConstruction** [comment]
I thought about it, and I don't think I need this feature. My s3 is only KK, my N7 2012 tablet is 32gb of internal only, and an s7 I'm inheriting in the fall has a 256gb ext. sd card(but I'm going to want to keep it free for photos of traveling). is MySQL the onl reason you need to run Debian? As I understand it mariadb which forked from MySQL; when it was bought by Oracle a few years back, is dedicated to being backwards compatible w/ MySQL.
As I understand it(and I reserve the right to be wrong/learn) MariaDB is the continuation of the Community MySQL, that you used for years b4 the project was swallowed by Oracle.
I've included some links as food for thought
https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/
https://mariadb.com/kb/en/mariadb/mariadb-vs-mysql-features/

**Comment by sdrausty** [comment]
@OpnSrcConstruction Are you referring to "request MySQL" https://github.com/termux/termux-packages/issues/1177 or "Feature Request: `mount loopback device`" https://github.com/termux/termux-app/issues/376 when you state, "this feature."

**Comment by sdrausty** [comment]
__Evidently, we can launch activities without root by passing the --user 0 flag to am start:__ from https://github.com/termux/termux-app/issues/206

**Comment by sdrausty** [comment]
@xeffyr suggests porting a kernel subsystem to Termux to accomplish mount in Termux userspace.  This appears to be a valuable doable suggestion.

**Comment by gordol** [comment]
Why was this closed without explanation?

**Comment by xeffyr** [comment]
@gordol To mount loopback device you need a root.

**Comment by SDRausty** [comment]
> To mount loopback device you need a root.

Can mounting loopback devices be made possible in our humanmade Android environment @xeffyr?

**Comment by xeffyr** [comment]
@SDRausty Look my answers above. No one here will bother to implememt a tool for userspace image mounting. Please understand that possibilities of Termux maintainers are *finite*.

Those who really needs mounting as non-root can use QEMU system-mode.
