### ISSUE TITLE
[Bug]: Can't install Termux on Android 9

### ISSUE THREAD

**Issue by CrazycatASG** [termux/termux-app#3762]
### Problem description

Trying to install Termux on Android 9 wields the "App not installed" error. There's no other clarification, just "App not installed". There shouldn't be any traces of Termux as the phone had just been factory reset a few weeks ago.

### Steps to reproduce the behavior.

Attempt to install the latest version of Termux from Github Releases

### What is the expected behavior?

App should install and run normally

### System information

* Termux application version: v0.118.0
* Android OS version: EMUI 9
* Device model: Huawei Y6 2019

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation
