### ISSUE TITLE
[Feature]: grant `RUN_COMMAND` permission in termux instead of the calling app

### ISSUE THREAD

**Issue by bilogic** [termux/termux-app#3766]
### Feature description

We don't always have control over apps that are used to call `RUN_COMMAND`.

It would be helpful if the permission can be controlled and granted within termux itself instead of requiring the other APP to request for permission.

### Additional information

N/A

**Comment by agnostic-apollo** [comment]
Use `adb shell` or `su` to run `pm grant` command. Android doesn't allow apps to grant themselves or others permissions without user approval.

**Comment by bilogic** [comment]
ok thanks, but `pm grant` can't grant a permission that the app did not request for.

**Comment by agnostic-apollo** [comment]
Then why is it calling termux APIs? Ask developer to add it.

**Comment by bilogic** [comment]
It is calling the API because I want it to, only to realize there is a permission blocking it. 

As I tried to explain in the OP, we don't always have control and they might not be willing to listen and I don't have any other choice.

Anyway I understand the security implications, I was just hoping there might be a way out of this. Thank you.

**Comment by twaik** [comment]
> I was just hoping there might be a way out of this. Thank you.

You can write some proxy appication which requests Termux's permission and forwards requests to termux. And ofc use it with your application. There is no other option.

**Comment by agnostic-apollo** [comment]
You can decompile the secondary app apk with `apktool` and add the permission yourself and recompile and sign it with your own key. That may not succeed due to bugs in recompiling though and you will have to do it for each app update.

Otherwise compile termux app yourself with the permission removed, which would then allow any app to run termux commands so would be security issue.
