### ISSUE TITLE
[Feature]: multi-language support 多语言支持

### ISSUE THREAD

**Issue by LY-Xiang** [termux/termux-app#3768]
### Feature description

Can we use any other languages in termux?
It can be like 'locale' in Linux.

有没有可能在termux中用更多语言？
就像linux的locale一样

### Additional information

Linux:locale

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/issues/546#issuecomment-258998944

The app can achieve multi-language support, but the terminal and package content cannot be achieved unless Google uses glibc on Android :p .
