### ISSUE TITLE
[Bug]: Missing binding to file editor

### ISSUE THREAD

**Issue by mdziczkowski** [termux/termux-app#3770]
### Problem description

There is missing a binding to the installed file editor.

When trying to open (for example) a preview of a text file in a archive, it's beeing tryed to become opened thru termux-file-editor, with doesn't exist.

### Steps to reproduce the behavior.

Install a archiver (for example: ZArchiver) and try to preview using it a text file inside a archive.

Important:

* OS need be Abdroid 13
* Whole termux package (all packages starting from "termux-") must be installed to make this become able to become reproduced

### System information

1. Termux application version:

* termux-tools: 1.40.1
* termux-services: 0.13-1

2. Android OS version: 13

**Comment by agnostic-apollo** [comment]
https://wiki.termux.com/wiki/Intents_and_Hooks
