### ISSUE TITLE
[Bug]: Sudo issues

### ISSUE THREAD

**Issue by mdziczkowski** [termux/termux-app#3771]
### Problem description

Even if the "sudo" is inside of termux "bin" folder, I'm unable to use it.

### Steps to reproduce the behavior.

Try to use sudo inside of Termux bin folder.

**Important**: Phone must not be rooted

### System information

* Termux application version: 1.40.1
* Android OS version: 13

**Comment by twaik** [comment]
Termux's `sudo` is a wrapper around `su`. It `must` be installed on your device.

**Comment by mdziczkowski** [comment]
The problem is that on most devices the existing in system su is normally set unexecutable. Thereof, it would be great if termux could bypass that

**Comment by twaik** [comment]
Termux is not a magic bullet. It uses resources only if they are available to be used...

**Comment by mdziczkowski** [comment]
> Termux is not a magic bullet. It uses resources only if they are available to be used...

I know, but it's a conmon practice by the producers of phones to limit the devices as much as possible that the owner couldn't prevent any privacy and security violation done either by them or someone who indirectly gained unauthorized administrative qccess thru them
