### ISSUE TITLE
[Feature]: Access shared file name/path

### ISSUE THREAD

**Issue by criztovyl** [termux/termux-app#3774]
### Feature description

Would it be possible to put the name/path a shared file was saved to inthe the shells environment?

I often share files with special characters (mainly parentheis) in the name, which are complicated to type/autocomplete. i also run a script on them, so if i have an env variable, i can just run the commabd/script without any arguments, saving even more typing. ^^

### Additional information

While I am new to Android app developement, with some pointers I might be able to prepare a PR. :)

**Comment by TomJo2000** [comment]
Would you be so kind as to go over a typical situation where you might encounter this?
It doesn't really sound like a situation that needs to be addressed in the core app itself,
more so just a matter of setting up a script hook to automatically provide the information you want here.

**Comment by agnostic-apollo** [comment]
If you are talking about `termux-file-editor`, then file path is already passed as first arg.

https://github.com/termux/termux-app/blob/8e3a8980a849046adbd4156741e1d84047ee1df6/app/src/main/java/com/termux/app/api/file/FileReceiverActivity.java#L181

**Comment by criztovyl** [comment]
hmm, if set my script as file editor, then i can only share files that script can process to tmux, but not do generic stuff with them

ah, but i can make a generic script that can redirect to other scripts.

sorry for the noise, thx for the file editor hint!
