### ISSUE TITLE
[request] Run command from T UI

### ISSUE THREAD

**Issue by indmind** [termux/termux-app#378]
it will be cool if I can run termux command directly from T UI

**Comment by fornwall** [comment]
Sorry, what is `T UI`? Could you explain a bit more?

**Comment by poutros** [comment]
@fornwall I know t-ui is an a terminal app that serves as a home launcher but I'm not sure that's what they're talking about.

**Comment by Haxk20** [comment]
Yeah would be cool to lunch command for this apps from TUI like that:
You type command that exist in here and TUI would be able to lunch it from his app

**Comment by moldabekov** [comment]
@fornwall yeah, for sure! I think issue author forgot to reply you.

T-UI is a CLI like Android Launcher. It shares the spirit of Termux, so it'd be really nice to invoke termux env command from T-UI.

Some links to quick start:
Play: https://play.google.com/store/apps/details?id=ohi.andre.consolelauncher
Github: https://github.com/Andre1299/TUI-ConsoleLauncher

**Comment by xeffyr** [comment]
I'm closing issue because Termux already provides the interface for third-party applications for command execution.

Details about implementation and usage - https://github.com/termux/termux-app/blob/9e7029b76ad63091a5920fbec0d08fe94c1f5785/app/src/main/java/com/termux/app/RunCommandService.java#L17-L44

**Comment by Artnoc1** [comment]
@indmind, 
@fornwall, 
@Haxk20, 
@moldabekov, 
@xeffyr, 
@artnoc1

**Comment by Artnoc1** [comment]
https://myaccount.google.com/profile/email/edit?index=0
