### ISSUE TITLE
[Bug]: Android 14 cannot grant root permission.

### ISSUE THREAD

**Issue by zzhongshengxiang** [termux/termux-app#3784]
### Problem description

![Screenshot_2024-01-13-00-42-44-536_com termux](https://github.com/termux/termux-app/assets/123443222/2b8ba5e0-ebc6-4efd-bce2-29ba99cc11e5)

### Steps to reproduce the behavior.

su

### System information

* Termux application version:0.118
* Android OS version:14
* Device model:xiaomi 12t pro

**Comment by agnostic-apollo** [comment]
Have you actually rooted the device?

You may also want to run `apt install termux-tools` if using kitsune.

**Comment by zzhongshengxiang** [comment]
> Have you actually rooted the device?
> 
> You may also want to run `apt install termux-tools` if using kitsune.

**Comment by zzhongshengxiang** [comment]
> Have you actually rooted the device?
> 
> You may also want to run `apt install termux-tools` if using kitsune.

I tried, but it didn't work

**Comment by zzhongshengxiang** [comment]
I use kitsune 26404

**Comment by zzhongshengxiang** [comment]
I have solved it, thank you.
