### ISSUE TITLE
[Bug]: Something keeps on deleting the content in Termux cache directory

### ISSUE THREAD

**Issue by mrtianjin829** [termux/termux-app#3787]
### Problem description

I cannot upgrade my packages (either by apt, pkg, or apt-get and dpkg) because the contents inside /data/data/com.termux/cache are being contionously deleted.
How do I fix? Please tell me.
Device - Samsung

### Steps to reproduce the behavior.

$ pkg update
$ pkg upgrade -y

### What is the expected behavior?

Upgrade works correctly without any related errors.

### System information

* Termux application version: 0.118.0
* Android OS version: 13
* Device model: SM-T225

**Comment by agnostic-apollo** [comment]
Android does that when only few hundred mbs remain free. Either free more storage required for all package debs to be downloaded for upgrade or manually update few packages at a time.

**Comment by mrtianjin829** [comment]
Do you know the minimum free space for Android to not clear cache

**Comment by agnostic-apollo** [comment]
~300-600MB if I remember correctly.

**Comment by agnostic-apollo** [comment]
Run `dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n` to find which packages would likely require more space. You can `apt-mark hold` such packages so that they are not upgraded when `pkg upgrade` is run, and later after upgrade, `apt-mark unhold` them and upgrade them separately.
