### ISSUE TITLE
Error occurs when Termux runs Alist service

### ISSUE THREAD

**Issue by wolffy1998** [termux/termux-app#3788]
### Problem description

Could you please help me find out what the error message in this terminal is：

goroutine 74 [syscall]:
syscall.Syscall6(0x4000a24c08?, 0x63fcfe74fc?, 0x400029e4c0?, 0x8?, 0x4000a24c00?, 0x400029e4c0?, 0x8?)
        /home/builder/.termux-build/_cache/go1.21.5/src/syscall/syscall_linux.go:91 +0x2c fp=0x4000a24bc0 sp=0x4000a24b30 pc=0x63fcd4c41c
syscall.Syscall6(0x123, 0xffffffffffffff9c, 0x400029e4f0, 0x0, 0x8e0, 0x4000aaa200, 0x0)
        <autogenerated>:1 +0x2c fp=0x4000a24c10 sp=0x4000a24bc0 pc=0x63fcd4d07c
golang.org/x/sys/unix.Statx(0x4000d06338?, {0x400029e4c0?, 0x4000a24d18?}, 0x63fcd83b10?, 0x4000a24d18?, 0x4000aaa200)
        /home/builder/go/pkg/mod/golang.org/x/sys@v0.15.0/unix/zsyscall_linux.go:1593 +0xa8 fp=0x4000a24cb0 sp=0x4000a24c10 pc=0x63fcfe7568
github.com/djherbis/times.statX({0x400029e4c0, 0x8})
        /home/builder/go/pkg/mod/github.com/djherbis/times@v1.6.0/times_linux.go:76 +0x5c fp=0x4000a24d00 sp=0x4000a24cb0 pc=0x63fdc338fc
github.com/djherbis/times.Stat({0x400029e4c0, 0x8})
        /home/builder/go/pkg/mod/github.com/djherbis/times@v1.6.0/times_linux.go:61 +0x3c fp=0x4000a24d40 sp=0x4000a24d00 pc=0x63fdc337ec
github.com/alist-org/alist/v3/drivers/local.(*Local).Get(0x63fb821fed?, {0x63fe420950?, 0x4000164000?}, {0x63fb821fed?, 0x4000a24fd8?})
        /home/builder/.termux-build/alist/src/drivers/local/driver.go:160 +0x124 fp=0x4000a24e90 sp=0x4000a24d40 pc=0x63fdc74c14
github.com/alist-org/alist/v3/internal/op.Get({0x63fe4175e8, 0x4000d04100}, {0x63fe420950?, 0x4000164000?}, {0x63fb821fed?, 0x63fd147308?})
        /home/builder/.termux-build/alist/src/internal/op/fs.go:171 +0xc4 fp=0x4000a24ff0 sp=0x4000a24e90 pc=0x63fd147f94
github.com/alist-org/alist/v3/internal/op.GetUnwrap({0x63fe4175e8?, 0x4000d04100?}, {0x63fe420950?, 0x4000164000?}, {0x63fb821fed?, 0x0?})
        /home/builder/.termux-build/alist/src/internal/op/fs.go:233 +0x30 fp=0x4000a25050 sp=0x4000a24ff0 pc=0x63fd148670
github.com/alist-org/alist/v3/internal/op.List({0x63fe4175e8?, 0x4000d04100}, {0x63fe420950, 0x4000164000}, {0x63fb821fed, 0x1}, {{0x400029e368?, 0x1?}, 0xe8?}, {0x4000a252e7, ...})
        /home/builder/.termux-build/alist/src/internal/op/fs.go:116 +0x1d8 fp=0x4000a25270 sp=0x4000a25050 pc=0x63fd147328
github.com/alist-org/alist/v3/internal/fs.list({0x63fe4175e8, 0x4000d04100}, {0x400029e368, 0x6}, 0x4000a25456)
        /home/builder/.termux-build/alist/src/internal/fs/list.go:25 +0x1a4 fp=0x4000a25380 sp=0x4000a25270 pc=0x63fd5969c4
github.com/alist-org/alist/v3/internal/fs.List({0x63fe4175e8?, 0x4000d04100?}, {0x400029e368, 0x6}, 0x4000a25456)
        /home/builder/.termux-build/alist/src/internal/fs/fs.go:22 +0x30 fp=0x4000a25400 sp=0x4000a25380 pc=0x63fd595590
github.com/alist-org/alist/v3/server/handles.FsList(0x4000d04100?)
        /home/builder/.termux-build/alist/src/server/handles/fsread.go:86 +0x278 fp=0x4000a25570 sp=0x4000a25400 pc=0x63fddd8f98
github.com/gin-gonic/gin.(*Context).Next(...)
        /home/builder/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth(0x4000d04100)
        /home/builder/.termux-build/alist/src/server/middlewares/auth.go:73 +0x4bc fp=0x4000a25680 sp=0x4000a25570 pc=0x63fdd9633c
github.com/gin-gonic/gin.(*Context).Next(...)
        /home/builder/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded(0x4000d04100)
        /home/builder/.termux-build/alist/src/server/middlewares/check.go:14 +0xa8 fp=0x4000a25760 sp=0x4000a25680 pc=0x63fdd96b88
github.com/gin-gonic/gin.(*Context).Next(...)
        /home/builder/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0x4000d04100)
        /home/builder/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 +0x80 fp=0x4000a257b0 sp=0x4000a25760 pc=0x63fd588450
github.com/gin-gonic/gin.(*Context).Next(...)
        /home/builder/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1(0x4000d04100)
        /home/builder/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 +0xb0 fp=0x4000a25960 sp=0x4000a257b0 pc=0x63fd5877f0
github.com/gin-gonic/gin.(*Context).Next(...)
        /home/builder/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0x40001b1860, 0x4000d04100)
        /home/builder/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x524 fp=0x4000a25af0 sp=0x4000a25960 pc=0x63fd586924
github.com/gin-

**environment:**
Android 9
![c8ce139759714d8124ad9ed77da66051](https://github.com/termux/termux-app/assets/45293057/132bee84-aa5c-426d-b692-550297de741d)

### Steps to reproduce the behavior.

After running the Alist service in Termux, the local storage directory of the mobile phone is mounted normally, and Termux permission has been granted. However, an error occurs in the terminal after accessing the Alist service through http.

### What is the expected behavior?

Please help me to see if there is any lack of environment dependency.

### System information

* Termux application version:
* Android OS version:Android 9
* Device model:
![c8ce139759714d8124ad9ed77da66051](https://github.com/termux/termux-app/assets/45293057/b064a097-ff18-4ae8-84a9-0d00878e8776)

**Comment by Grimler91** [comment]
Kinda impossible to read what you pasted since there is no formatting. Also looks like you haven't pasted all of it, it is truncated

**Comment by 2096779623** [comment]
![Screenshot_20240114-172807_Pixel ](https://github.com/termux/termux-app/assets/57583560/33771c17-174a-43be-8bb3-d7fd1dc88210)
Work fine on my device.
What command can reproduce this bug?
May be an upstream issues.

**Comment by wolffy1998** [comment]
点击挂载的local文件夹后，termux终端立刻就报错，具体的报错截图晚点回家后贴一下。
After clicking on the mounted local folder, the termux terminal immediately reported an error. I will post a screenshot of the specific error report when I get home later.
![image](https://github.com/termux/termux-app/assets/45293057/069ae1ab-51b5-4764-ba03-4cc980eebe29)

**Comment by 2096779623** [comment]
>  After clicking on the mounted local folder, the termux terminal immediately reported an error. I will post a screenshot of the specific error report when I get home later. 

What is the value of your Root folder path?
![Screenshot_20240114-184637_Pixel 启动器](https://github.com/termux/termux-app/assets/57583560/55266f2a-39ed-4689-923b-1736a1e48683)

**Comment by wolffy1998** [comment]
> > 点击挂载的本地文件夹后，termux立即报错。稍后我回家后将具体错误报告的截图贴出来。
> 
> 您的根文件夹路径的值为多少？ ![截图_20240114-184637_Pixel启动器](https://private-user-images.githubusercontent.com/57583560/296544501-55266f2a-39ed-4689-923b-1736a1e48683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzA0OTgsIm5iZiI6MTcwNTIzMDE5OCwicGF0aCI6Ii81NzU4MzU2MC8yOTY1NDQ1MDEtNTUyNjZmMmEtMzllZC00Njg5LTkyM2ItMTczNmExZTQ4NjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDExMDMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMTEwNWMzMDcwNTgxNTI0ODVhMGE5NTAxMzZhNTUzYWMzOTZiNTkyNzg2NDBmYjA3NzFmNjFkMTViOThhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFpTb1_028D59hmcTNAHl2D4Z5eohVL94t7OZ4tEQtY)
The local storage directory /storage/emulated/0, the memory card directory /sdcard, and the termux home directory have all been tested. This problem will occur when termux has been granted access to the local directory.

**Comment by wolffy1998** [comment]
@2096779623 
termux has been authorized to access the local storage. This problem will occur if /storage/emulated/0, /sdcard, and the home directory of termux are mounted in tests.

**Comment by wolffy1998** [comment]
@2096779623 
termux has been authorized to access the local storage. We have tested mounting /storage/emulated/0, /sdcard, and the home directory of termux, and this problem will occur.

**Comment by 2096779623** [comment]
> @2096779623 termux has been authorized to access the local storage. We have tested mounting /storage/emulated/0, /sdcard, and the home directory of termux, and this problem will occur.

Try `termux-setup-storage`, work fine on my device.

**Comment by wolffy1998** [comment]
After executing the termux-setup-storage command, a pop-up window will appear. I have clicked "Allow" and a stored soft link appears in the termux home directory.

**Comment by 2096779623** [comment]
> After executing the termux-setup-storage command, a pop-up window will appear. I have clicked "Allow" and a stored soft link appears in the termux home directory.

Try again in the alist now.

**Comment by wolffy1998** [comment]
Okay, I will try again later and write a more detailed description of the problem. Thank you for your advice.
