### ISSUE TITLE
[Bug]: Termux Storage Error

### ISSUE THREAD

**Issue by mjain234** [termux/termux-app#3793]
### Problem description

I suddenly faced this issue when I was giving Termux storage permission by typing command "termux-setup-storage". 

It displayed me the error **"/data/data/com.termux/files/usr/bin/termux-setup-storage: line 29: 28254 Aborted                 am broadcast --user 0 --es com.termux.app.reload_style storage -a com.termux.app.reload_style com.termux > /dev/null"**

Before this, I have never faced such issue, I was easily able to give Termux storage permission. 

Here is the screenshot:
![Screenshot_20240117-142853](https://github.com/termux/termux-app/assets/70900505/96c504b9-2406-4625-a106-177f2ff89884)

### Steps to reproduce the behavior.

NIL

### What is the expected behavior?

NIL

### System information

* Termux application version: 0.118.0
* Android OS version: Android 14
* Device model: Nothing A063

**Comment by agnostic-apollo** [comment]
`pkg install termux-tools`

**Comment by mjain234** [comment]
The issue didn't get solved though 
https://github.com/termux/termux-app/assets/70900505/2bba38b5-709e-471c-88d8-00f4febda03f

**Comment by agnostic-apollo** [comment]
Sorry, need to update `termux-am` as well.
