### ISSUE TITLE
Termux 150 eror (unable to install bootstrap)

### ISSUE THREAD

**Issue by szerrahim** [termux/termux-app#3797]
### Problem description

![Screenshot_20240123-130322~2](https://github.com/termux/termux-app/assets/157469456/4bd8c2ae-c583-4749-8dcc-472505479b74)

                                    ==========

## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxInstaller`  
**Report Timestamp**: `2024-01-23 10:13:34.584 UTC`  
##

## Bootstrap Error

(150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".
TERMUX_FILES_DIR: `/data/data/com.termux/files`

## Termux Files Info

**TERMUX_REQUIRED_FILES_DIR_PATH ($PREFIX)**: `/data/data/com.termux/files`  
**ANDROID_ASSIGNED_FILES_DIR_PATH**: `/data/user/0/com.termux/files`  

```
$ echo 'ls info:'
/system/bin/ls -lhdZ '/data/data' '/data/user/0' '/data/data/com.termux' '/data/user/0/com.termux' '/data/data/com.termux/files' '/data/user/0/com.termux/files' '/data/user/0/com.termux/files' '/data/user/com.termux/files' '/data/data/com.termux/files/usr-staging' '/data/data/com.termux/files/usr' '/data/data/com.termux/files/home' '/data/data/com.termux/files/usr/bin/login' 2>&1
echo; echo 'mount info:'
/system/bin/grep -E '( /data )|( /data/data )|( /data/user/[0-9]+ )' /proc/self/mountinfo 2>&1 | /system/bin/grep -v '/data_mirror' 2>&1

ls info:
ls: /data/data/com.termux: Permission denied
ls: /data/user/0/com.termux: Permission denied
ls: /data/data/com.termux/files: Permission denied
ls: /data/user/0/com.termux/files: Permission denied
ls: /data/user/0/com.termux/files: Permission denied
ls: /data/user/com.termux/files: No such file or directory
ls: /data/data/com.termux/files/usr-staging: Permission denied
ls: /data/data/com.termux/files/usr: Permission denied
ls: /data/data/com.termux/files/home: Permission denied
ls: /data/data/com.termux/files/usr/bin/login: Permission denied
drwxrwx--x 295 system system u:object_r:system_data_file:s0:c512,c768  20K 2024-01-23 11:09 /data/data
drwxrwx--x 295 system system u:object_r:system_data_file:s0:c512,c768  20K 2024-01-23 11:09 /data/user/0

mount info:
9998 9901 252:6 / /data rw,nosuid,nodev,noatime master:34 - ext4 /dev/block/dm-6 rw,seclabel,noauto_da_alloc,inlinecrypt,resgid=1065,errors=panic
9999 9998 252:6 /data /data/user/0 rw,nosuid,nodev,noatime master:34 - ext4 /dev/block/dm-6 rw,seclabel,noauto_da_alloc,inlinecrypt,resgid=1065,errors=panic

```
##

## Logcat Dump

````
$ /system/bin/logcat -d -t 3000 2>&1
--------- beginning of system
01-23 12:45:03.441  6052  6095 D OpenMsyncAppList: loadTunerAppList + 
01-23 12:45:03.458  6052  6095 D OpenMsyncAppList: loadTunerAppList - 
--------- beginning of main
01-23 13:13:34.150  6052  6052 W ContextImpl: Failed to ensure /data/user/0/com.termux/shared_prefs: mkdir failed: EACCES (Permission denied)
01-23 13:13:34.153  6052 15750 E Termux  : Failed to get file type for file at path "/data/data/com.termux/files/home/crash_log.md": Failed to run Os.lstat() on file at path "/data/data/com.termux/files/home/crash_log.md": lstat failed: EACCES (Permission denied)
01-23 13:13:34.153  6052 15751 W ContextImpl: Failed to ensure /data/user/0/com.termux/cache: mkdir failed: EACCES (Permission denied)
01-23 13:13:34.153  6052 15751 W ContextImpl: Failed to update user.inode_cache: stat failed: EACCES (Permission denied)
01-23 13:13:34.154  6052  6052 W Termux:SharedProperties: Not loading properties since file is null
01-23 13:13:34.148  6052  6052 W Thread-10: type=1400 audit(0.0:13313): avc: denied { getattr } for path="/data/user/0/com.termux" dev="dm-6" ino=3900883 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c219,c256,c512,c768 tclass=dir permissive=0 app=com.termux
01-23 13:13:34.157  6052 15751 E Termux  : Failed to get file type for file at path "/data/user/0/com.termux/cache/report_activity": Failed to run Os.lstat() on file at path "/data/user/0/com.termux/cache/report_activity": lstat failed: EACCES (Permission denied)
01-23 13:13:34.180  6052  6052 W ContextImpl: Failed to ensure /data/user/0/com.termux/shared_prefs: mkdir failed: EACCES (Permission denied)
01-23 13:13:34.246  6052  6096 I libPerfCtl: fbcNotifySbeRescue ret=-1
01-23 13:13:34.250  6052  6052 W ContextImpl: Failed to ensure /data/user/0/com.termux/files: mkdir failed: EACCES (Permission denied)
01-23 13:13:34.251  6052  6052 E Termux  : Failed to get file type for file at path "/data/data/com.termux/files": Failed to run Os.stat() on file at path "/data/data/com.termux/files": stat failed: EACCES (Permission denied)
01-23 13:13:34.252  6052  6052 E Termux:TermuxInstaller: (150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".
01-23 13:13:34.252  6052  6052 E Termux:TermuxInstaller: TERMUX_FILES_DIR: `/data/data/com.termux/files`
01-23 13:13:34.248  6052  6052 W com.termux: type=1400 audit(0.0:13314): avc: denied { getattr } for path="/data/data/com.termux" dev="dm-6" ino=3900883 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c219,c256,c512,c768 tclass=dir permissive=0 app=com.termux
01-23 13:13:34.248  6052  6052 W com.termux: type=1400 audit(0.0:13315): avc: denied { getattr } for path="/data/data/com.termux" dev="dm-6" ino=3900883 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c219,c256,c512,c768 tclass=dir permissive=0 app=com.termux
01-23 13:13:34.253  6052  6052 W ContextImpl: Failed to ensure /data/user/0/com.termux/files: mkdir failed: EACCES (Permission denied)
01-23 13:13:34.344 15757 15757 W ls      : type=1400 audit(0.0:13316): avc: denied { getattr } for path="/data/data/com.termux" dev="dm-6" ino=3900883 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c219,c256,c512,c768 tclass=dir permissive=0 app=com.termux
01-23 13:13:34.344 15757 15757 W ls      : type=1400 audit(0.0:13317): avc: denied { getattr } for path="/data/user/0/com.termux" dev="dm-6" ino=3900883 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c219,c256,c512,c768 tclass=dir permissive=0 app=com.termux
01-23 13:13:34.360  6052 15758 I CCodec  : setting up 'default' as default (vendor) store
01-23 13:13:34.380  6052  6052 W com.termux: type=1400 audit(0.0:13318): avc: denied { getattr } for path="/data/data/com.termux" dev="dm-6" ino=3900883 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c219,c256,c512,c768 tclass=dir permissive=0 app=com.termux
01-23 13:13:34.380  6052  6052 W com.termux: type=1400 audit(0.0:13319): avc: denied { getattr } for path="/data/data/com.termux" dev="dm-6" ino=3900883 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c219,c256,c512,c768 tclass=dir permissive=0 app=com.termux
01-23 13:13:34.431  6052 15758 I CCodec  : Created component [c2.android.vorbis.decoder]
01-23 13:13:34.439  6052 15758 I CCodecConfig: query failed after returning 7 values (BAD_INDEX)
01-23 13:13:34.444  6052 15758 W Codec2Client: query -- param skipped: index = 1107298332.
01-23 13:13:34.444  6052 15758 I CCodecConfig: query failed after returning 7 values (BAD_INDEX)
01-23 13:13:34.446  6052 15758 W Codec2Client: query -- param skipped: index = 1342179345.
01-23 13:13:34.446  6052 15758 W Codec2Client: query -- param skipped: index = 2415921170.
01-23 13:13:34.451  6052 15758 I CCodecBufferChannel: [c2.android.vorbis.decoder#767] Created output block pool with allocatorID 16 => poolID 38 - OK

````
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**TERMUX_FILES_DIR**: `/data/data/com.termux/files`  
**IS_TERMUX_FILES_DIR_ACCESSIBLE**: `false - (150) FileUtils Error: The termux files directory not found at path "/data/data/com.termux/files".`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.19.191`  
**SDK_INT**: `31`  
**RELEASE**: `12`  
**ID**: -  
**DISPLAY**: -  
**INCREMENTAL**: `-`  
**SECURITY_PATCH**: `2023-12-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `OMIX`  
**BRAND**: `OMIX`  
**MODEL**: `X5`  
**PRODUCT**: `X5`  
**BOARD**: `X5`  
**HARDWARE**: `mt6765`  
**DEVICE**: `X5`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

.

### What is the expected behavior?

.

### System information

* Termux application version:0.118.0
* Android OS version:12
* Device model:Omix X5

**Comment by agnostic-apollo** [comment]
>avc: denied { getattr } for path="/data/data/com.termux" dev="dm-6" ino=3900883 scontext=u:r:untrusted_app_27:s0:c215,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c219,c256,c512,c768 tclass=dir permissive=0 app=com.termux

You have left over directory from previous installation, if you have root, then run `rm -rf /data/data/com.termux` from an `su` shell and then uninstall and reinstall the app or try running `pm uninstall --user 0 com.termux` from an `adb` shell if you do not have root.

https://github.com/agnostic-apollo/Android-Docs/blob/master/site/pages/en/projects/docs/os/selinux/security-context.md#categories

**Comment by szerrahim** [comment]
bro ı dont have pc. Is there any way to solve this problem without rooting and without a pc?

**Comment by agnostic-apollo** [comment]
There are apps that can support adb wireless debugging, like LADB.

**Comment by ChiefMikeK** [comment]
backup your device and factory reset but beware you'll have to reinstall all your apps🥺

**Comment by szerrahim** [comment]
> There are apps that support adb wireless debugging, like LADB.

Bro, I tried this, but I'm getting an error;

![Screenshot_20240124-143858~2.png](https://github.com/termux/termux-app/assets/157469456/2201db05-5c8b-4235-a8de-db8ec186ff9f)

**Comment by agnostic-apollo** [comment]
There's a `pm ` before `uninstall`.

**Comment by szerrahim** [comment]
> There's a `pm ` before `uninstall`.

bro please watch this video

https://drive.google.com/drive/folders/1NOKg4wWth4GHsbWrpQwyXoYAfiOyHxcS

**Comment by agnostic-apollo** [comment]
Read my comment above, `rm` command requires root access.

However, `pm uninstall` with `adb` should be able to remove the directory even if it has wrong ownership/secontext. It is working for me on android 12/14 avd.

Assuming termux app is currently installed, from `adb shell`, run `ls -ldZ /data/data/com.termux`, then `pm uninstall --user 0 com.termux`, then `ls -ldZ /data/data/com.termux`, then quickly `logcat -d /sdcard/logcat.txt`. Post the text output you get in terminal/shell and also upload or email me the `logcat.txt` file after removing any private info.


Do not post videos! Or even screenshots unless complete output can be seen.

**Comment by szerrahim** [comment]
> Read my comment above, `rm` command requires root access.
> 
> However, `pm uninstall` with `adb` should be able to remove the directory even if it has wrong ownership/secontext. It is working for me on android 12/14 avd.
> 
> Assuming termux app is currently installed, from `adb shell`, run `pm uninstall --user 0 com.termux` and then quickly `logcat -d /sdcard/logcat.txt`. Post the text output you get in terminal/shell and also upload or email me the `logcat.txt` file after removing any private info.
> 
> Do not post videos! Or even screenshots unless complete output can be seen.
> 
> Edit:  `ls -ldZ /data/data/com.termux` will not work from `adb` `shell` user, requires root. Uninstalling from `App Info` UI also works, even with root owned files.
> 

ok bro check ur email

**Comment by agnostic-apollo** [comment]
There is something wrong with your `/data/user_de/0/com.termux` directory at least, although Termux app by default doesn't create files under it. No idea what the issue is since don't see anything else in logs, and likely ownership is different as well for Termux app to be able to access it to investigate, and would require root to list its files or delete it manually. There could be some file corruption preventing deletion, others have reported similar issues. I don't see any other way than factory reset since you are not rooted, Sorry.

```
W PackageManager: Adding duplicate app id: 10272 name=com.termux
I PackageManager: Permission ownership changed. Updating all permissions.
W PackageManager: Failed to create app data for com.termux, but trying to recover: com.android.server.pm.Installer$InstallerException: Failed to prepare /data/data/com.termux
W PackageManager: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to delete /data/user_de/0/com.termux (code 2)
E ArtManagerService: Failed to prepare profile for com.termux:/data/app/~~gcOHDpTa2Cq0PFs_TXn__Q==/com.termux-WNubzRE1U5zo-sPTcCeq1Q==/base.apk
```

- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/pm/AppDataHelper.java;l=236
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/pm/AppDataHelper.java;l=620
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/pm/DeletePackageHelper.java;l=535
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/base/services/core/java/com/android/server/pm/Installer.java;l=450
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r1:frameworks/native/cmds/installd/InstalldNativeService.cpp;l=1221

**Comment by szerrahim** [comment]
thank you for everything. have a nice day
