### ISSUE TITLE
Executing the "su" command in the Kitsune Mask environment is ineffective.

### ISSUE THREAD

**Issue by QJAG1024** [termux/termux-app#3805]
### Problem description

My Kitsune Mask version is 26404, and when I attempt to execute "su," Termux reports the following message:
> No su program found on this device. Termux
does not supply tools for rooting, see e.g.
http://www.androidcentral.com/root for
information about rooting Android.

However, I have already installed Kitsune Mask and have granted root permissions to Termux through it.
I am using a translator, so my expression may not be accurate.
![Screenshot_2024-01-27-13-06-53-401_com termux](https://github.com/termux/termux-app/assets/123146382/fc79d550-7b6a-459a-b84a-5e1f120b09ef)
![Screenshot_2024-01-27-13-14-30-987_io github huskydg magisk](https://github.com/termux/termux-app/assets/123146382/6b1880dd-dc5c-441b-9998-deb0ed44592c)

### Steps to reproduce the behavior.

1. install kitsune mask
2. input "su" in termux

### What is the expected behavior?

termux returns:
> No su program found on this device. Termux
does not supply tools for rooting, see e.g.
http://www.androidcentral.com/root for
information about rooting Android.

### System information

* Termux application version:0.118.0
* Android OS version:14
* Device model:Redmi Note 12 Pro Speed (redwood)

**Comment by 2096779623** [comment]
Try `apt upgrade`.

**Comment by QJAG1024** [comment]
> Try `apt upgrade`.

doesn't work
![Screenshot_2024-01-27-14-52-10-509_com termux](https://github.com/termux/termux-app/assets/123146382/526f76d4-218a-4a1e-be84-4fd3b0d9a04c)

**Comment by agnostic-apollo** [comment]
Run `apt update` and then `apt upgrade`. If that doesn't work, post output of `apt show termux-tools`.

**Comment by 2096779623** [comment]
[termux-tools_1.40.5-2_all.zip](https://github.com/termux/termux-app/files/14071449/termux-tools_1.40.5-2_all.zip)
```bash
termux-setup-storage
cd ~/storage/downloads
pkg i ./termux-tools_1.40.5-2_all.zip
```
**Download the file first.**
