### ISSUE TITLE
Ubuntu proot issue

### ISSUE THREAD

**Issue by themastersunil** [termux/termux-app#381]

**Comment by themastersunil** [comment]
https://imgur.com/gallery/BivL2

**Comment by themastersunil** [comment]
$ cd termux-ubuntu
$ ls
README.md  start.sh  ubuntu-fs  ubuntu.sh  ubuntu.tar.gz
$ ./start.ah
bash: ./start.ah: No such file or directory
$ ./start.sh
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$

**Comment by fornwall** [comment]
I think you should open an issue at https://github.com/Neo-Oli/termux-ubuntu

**Comment by goldengragon** [comment]
i have the same error tried to uninstall and reinstall many times but failed and different type of updates for proot but the same problem happen

**Comment by Ahmedroid** [comment]
**I HAVA THIS PROBLEM PLS HEALP??????**


./start.sh
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by sdrausty** [comment]
@Ahmedroid @goldengragon This repo is for packages available in Termux. Termux-ubuntu isn't available from this official repository.  This thread is marked closed for this reason.  You might have more luck if you open  this issue at the termux-ubuntu github page.

**Comment by sumit-prgmr** [comment]
same problem here
 ./start-ubuntu.sh: line 29: exec: proot: not found 
error is there and i have tried many times but not working

**Comment by xeffyr** [comment]
> proot: not found

@sumit-prgmr Haven't tried `pkg install proot` ? It tolds you that proot is not installed.

**Comment by lunatic389** [comment]
installed proot still getting this error

**Comment by Antracot** [comment]
guys!!! This repo works!!
https://github.com/Neo-Oli/termux-ubuntu.git
just follow step-by-step ☻

**Comment by Antracot** [comment]
that repo works!!!
that help me fixed error above

Update termux: apt-get update && apt-get upgrade -y
Install wget: apt-get install wget -y
Install proot: apt-get install proot -y
Install git: apt-get install git -y
Go to HOME folder: cd ~
Download script: git clone https://github.com/MFDGaming/ubuntu-in-termux.git
Go to script folder: cd ubuntu-in-termux
Give execution permission: chmod +x ubuntu.sh
Run the script: ./ubuntu.sh -y
Now just start ubuntu: ./startubuntu.sh

**Comment by psychocarder** [comment]
When i try to install Git or any other pkg it shows this....how to solve??

root@localhost:~# apt install git
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package git

**Comment by xeffyr** [comment]
@psychocarder Run `apt update` before installing package.

**Comment by psychocarder** [comment]
installing wifite tool but seeing this error

root@localhost:~/wifite2# python wifite.py
python: can't open file 'wifite.py': [Errno 2] No such file or directory

**Comment by Tulasinathreddy** [comment]
> that repo works!!!
> that help me fixed error above
> 
> Update termux: apt-get update && apt-get upgrade -y
> Install wget: `apt-get install wget -y`
> Install proot: `apt-get install proot -y`
> Install git: `apt-get install git -y`
> Go to HOME folder: `cd ~`
> Download script: `git clone https://github.com/MFDGaming/ubuntu-in-termux.git`
> Go to script folder: `cd ubuntu-in-termux`
> Give execution permission: `chmod +x ubuntu.sh`
> Run the script: `./ubuntu.sh -y`
> Now just start ubuntu: `./startubuntu.sh`

Thank you this works 
My Ubuntu works bot 
`./startubuntu.sh` is working

**Comment by SpiderMBZ** [comment]
> that repo works!!!
> that help me fixed error above
> 
> Update termux: apt-get update && apt-get upgrade -y
> Install wget: apt-get install wget -y
> Install proot: apt-get install proot -y
> Install git: apt-get install git -y
> Go to HOME folder: cd ~
> Download script: git clone https://github.com/MFDGaming/ubuntu-in-termux.git
> Go to script folder: cd ubuntu-in-termux
> Give execution permission: chmod +x ubuntu.sh
> Run the script: ./ubuntu.sh -y
> Now just start ubuntu: ./startubuntu.sh

Thank you bro 😘😘

**Comment by dcstar27** [comment]
> > that repo works!!!
> > that help me fixed error above
> > Update termux: apt-get update && apt-get upgrade -y
> > Install wget: `apt-get install wget -y`
> > Install proot: `apt-get install proot -y`
> > Install git: `apt-get install git -y`
> > Go to HOME folder: `cd ~`
> > Download script: `git clone https://github.com/MFDGaming/ubuntu-in-termux.git`
> > Go to script folder: `cd ubuntu-in-termux`
> > Give execution permission: `chmod +x ubuntu.sh`
> > Run the script: `./ubuntu.sh -y`
> > Now just start ubuntu: `./startubuntu.sh`
> 
> Thank you this works
> My Ubuntu works fine
> `./startubuntu.sh` is working

**Comment by dcstar27** [comment]
thank you bro it's working 👍

**Comment by ohnewdev** [comment]
> that repo works!!!
> that help me fixed error above
> 
> Update termux: apt-get update && apt-get upgrade -y
> Install wget: apt-get install wget -y
> Install proot: apt-get install proot -y
> Install git: apt-get install git -y
> Go to HOME folder: cd ~
> Download script: git clone https://github.com/MFDGaming/ubuntu-in-termux.git
> Go to script folder: cd ubuntu-in-termux
> Give execution permission: chmod +x ubuntu.sh
> Run the script: ./ubuntu.sh -y
> Now just start ubuntu: ./startubuntu.sh

I've also installed it on my termux-Note9.
Thank you~*

**Comment by Smarty10** [comment]
> **I HAVA THIS PROBLEM PLS HEALP??????**
> 
> ./start.sh
> proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
> proot info: default working directory is now "/"
> proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs, cwd = /, $PATH=(null))
> fatal error: see `proot --help`.

Having the same problem...helpppp

**Comment by liuqi00** [comment]
> that repo works!!!
> that help me fixed error above
> 
> Update termux: apt-get update && apt-get upgrade -y
> Install wget: apt-get install wget -y
> Install proot: apt-get install proot -y
> Install git: apt-get install git -y
> Go to HOME folder: cd ~
> Download script: git clone https://github.com/MFDGaming/ubuntu-in-termux.git
> Go to script folder: cd ubuntu-in-termux
> Give execution permission: chmod +x ubuntu.sh
> Run the script: ./ubuntu.sh -y
> Now just start ubuntu: ./startubuntu.sh

Thanks a lot. It works!!!

**Comment by DhakadRachit** [comment]
> termux

This will work bro. Thanks a lot

**Comment by sumit-prgmr** [comment]
It works
