### ISSUE TITLE
[Bug]: PHP 8.3 not supported yet ?

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#3817]
### Problem description

Not a big deal, but it appears that PHP is not updated anymore.

When I do `apt update && apt upgrade`, Termux updates all packages without a problem, but PHP (which works fine) sticks to 8.2.8.
On an Ubuntu system I get 8.2.12 or 8.3.1.

### Steps to reproduce the behavior.

`apt update && apt upgrade`
PHP is not up(dat|grad)etd.

### System information

* Termux application version: 118
* Android OS version: 10
* Device model: OnePlus 6

**Comment by twaik** [comment]
No need to open issues about updating packages in repos. We know about every package that has outdated version but have no enough people to update packages. Be patient.
