### ISSUE TITLE
[Feature]: Enable access to `/storage/emulated/0/Android/*/*` via `adb` workaround?

### ISSUE THREAD

**Issue by navid-zamani** [termux/termux-app#3819]
### Feature description

I noticed this while using `adb`:  
I can `adb push` anything to `/data/local/tmp/`, even executables, and run it. And it has full access to `/storage/emulated/0/Android/*/*`, unlike apps like Termux. Without root.  
I used this to run `ssh` and `unison`, and was able to sync the data in the `Android` directory for offline backup reasons, just fine.  

That gave me the idea if Termux could gain full access like that too, by accessing a program or daemon running from `/data/local/tmp/` under those different permissions. Even if just a sshd or FUSE something.  
Depending on how Android is set up, any other executable run in `/data/local/tmp/` would have to
* Either run constantly (being asleep mostly), or triggerable. (Does the NDK offer an interface for registering such programs as background services or for intents?)
* manage wakelocks to prevent being halted by the kernel going to sleep or using up the battery. In my case it wasn’t necessary though, as unison is so well-programmed, it can always recover and will never cause data corruption in any case. So unlocking the phone again did suffice.

The challenges I’ve yet to overcome:
* Termux cannot access `/data/local/tmp/` itself.
* `adb` allows to be switched to TCP mode, where Termux could access it and do everything itself, but that switch can only be triggered by attaching it to a cable first. (How would a phone without an USB port do that? Was `adb` changed in more recent Android versions?)
* A reboot can clear `/data/local/tmp/`.
* If not triggerable from Android’s facilities, it may use up a bit of battery for no legitimate reason.

I see the previous bug about this devolved into chaos and had to be locked down. I hope this one will be more fruitful. :)

I also hope it made you curious. Maybe you know more about Android’s internals, and how to make this easier. :)  
If this is not feasible, or not worth it, then it’s fine if you just go and close the bug. In that case, this serves as a tombstone for others to find, who complain why this directory cannot be accessed. (Alternative solution: Don’t pay for things that you won’t actually own, if you have any choice at all. #get_boot_get_root)

### Additional information

(See above)

**Comment by agnostic-apollo** [comment]
Termux already provides `adb` with `android-tools` package, so nothing more needs to be done or can be done.
The `Android/data` access is restricted for Android `>= 11` and android provides `adb` wireless mode to connect directly from device over `localhost` wifi with pairing while in split screen on Android `>= 11`,  and does not require usb method.

https://www.reddit.com/r/termux/s/bKbtOWDqAu

**Comment by navid-zamani** [comment]
That is nice.  

Who still uses social ~media~ malware like Reddit though? ^^  
I had to alter my home server’s firewall and name server (and my browser settings) to take out the block temporarily.  

_Get your own site. Discover freedom. Become a person.™_ 😁
