### ISSUE TITLE
How to install Twisted.web?

### ISSUE THREAD

**Issue by Deathlive** [termux/termux-app#382]
Tried to install sslstrip,  was an error.

`ImportError: No module named twisted.web.`

Twisted installed across command
`$ pip install twisted`

But error has occurred.

https://prnt.sc/g500rg

What is the problem, How can fix this problem?

**Comment by Grimler91** [comment]
Do you have clang installed? `pkg install clang`

**Comment by Deathlive** [comment]
@Grimler91 Installed clang → `pkg install clang` 
Did not work,  https://prnt.sc/g50l2t

**Comment by Grimler91** [comment]
Well, obviously it worked cause now you get another error. 

Now it instead says that Python.h is missing. This file is provided by the package python-dev so do `pkg install python-dev`

**Comment by Deathlive** [comment]
@Grimler91 Thanks, It worked.

**Comment by Grimler91** [comment]
@Deathlive Great! Could you then close the issue?
