### ISSUE TITLE
[Bug]: After the screen turns off, the process freezes

### ISSUE THREAD

**Issue by gustaapereira** [termux/termux-app#3824]
### Problem description

When I use a process that is emulated simultaneously, and the cell phone screen turns off, after a few moments process it freezes.

### Steps to reproduce the behavior.

1 - Start a QEMU instance;
2 - Turn off your cell phone screen;

### What is the expected behavior?

Continue the process.

### System information

* Termux application version: release
* Android OS version: 13
* Device model: S20 FE (G780G)

**Comment by Grimler91** [comment]
Sounds like battery saving features of your device at work.
Try setting a wake lock with termux-wakelock and disabling all battery optimisations, see for example https://dontkillmyapp.com/samsung

**Comment by Ieida** [comment]
This is still an issue. On a Samsung Android 15 with Adaptive Battery disabled and wakelock enabled things like ssh disconnect or becomes unresponsive.

**Comment by agnostic-apollo** [comment]
Possibly related to https://github.com/termux/termux-app/issues/4824#issuecomment-3702427137
