### ISSUE TITLE
[Bug]: qBittorrent-nox not downloading on termux anymore?

### ISSUE THREAD

**Issue by erickyun** [termux/termux-app#3833]
### Problem description

Hi,

I Installed qBittorrent-nox on proot-distro ubuntu it worked fine before but now it won't start downloading torrents anymore?

also gived permission with chmod u+x

### Steps to reproduce the behavior.

$ uname -m
aarch64

```
wget -qO /usr/bin/qbittorrent-nox https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/aarch64-qbittorrent-nox
chmod 700 /usr/bin/qbittorrent-nox


### What is the expected behavior?

qbittorrent-nox status is always on stalled!
The status won't change to downloading anymore?

### System information

* Termux application version: 0.118.0
* Android OS version: Android 11 
* Device model: Xiaomi Redmi Note 8 Pro

**Comment by twaik** [comment]
qBittorrent-nox is 3rd party software we offer zero support for. 
Probably the reason for this is your wireless connection or router setup.

**Comment by erickyun** [comment]
> qBittorrent-nox is 3rd party software we offer zero support for. Probably the reason for this is your wireless connection or router setup.

İt works fine on my raspberrypi though!
I would appreciate if you could please help me sir?

**Comment by twaik** [comment]
Again.
qBittorrent-nox is 3rd party software we offer zero support for.

**Comment by twaik** [comment]
You should open issue in https://github.com/userdocs/qbittorrent-nox-static, not here.

**Comment by erickyun** [comment]
> You should open issue in https://github.com/userdocs/qbittorrent-nox-static, not here.

Thank you for your reply sir.
I opened an issue there https://github.com/userdocs/qbittorrent-nox-static/issues/133 but still it worked fine before on the previous termux versions but after reinstalling termux it didn't work anymore?
