### ISSUE TITLE
[Bug]: unable to run startdesktop in termux after successful installation. How to restart termux?

### ISSUE THREAD

**Issue by Sail1boat** [termux/termux-app#3836]
### Problem description

I originally had the google play version on the phone. Android did an update and I could no longer have a debian desktop in vlc. I deleted both termux and the viewer and installed termux from f-droid and followed the termux wiki directions exactly. This is verbatum from the phone:
[] Termux installed successfully
[] Restart termux and enter startdesktop command to start the vnc server.
[*] In vnc client, enter 127.0.0.1:5901 as address and password you created to connect.

~/termux-desktop/termux-desktop $ startdesktop
startdesktop: command not found

From the above information, can someone explain how to restart termux and why startdesktop is not found?

Thank you for responding

### Steps to reproduce the behavior.

execute startdesktop

### What is the expected behavior?

to have a graphic desktop in vlc

### System information

* Termux application version: 0.8
* Android OS version: latest
* Device model: Samsung galixy a14 5g

**Comment by twaik** [comment]
1. Playstore version is deprecated. Read this. https://github.com/termux/termux-app?tab=readme-ov-file#google-play-store-deprecated
2. Vlc? Did you mean VNC? 
3. Probably `startdesktop` is some script. There is no such file in our repos, I think you downloaded it from somewhere.

**Comment by Sail1boat** [comment]
Yes, it is VNC. Is there another command to start desktop?

**Comment by twaik** [comment]
I have no idea what exactly you need. You mentioned debian desktop so probably you installed proot container with debian from somewhere. Take a look at `proot-distro`.

**Comment by Sail1boat** [comment]
When termux is installed, the desktop server is started in termux as I
listed in github. a connection is sent via localhost 127.0.0.1:5901 to vnc
viewer on the phone. A Debian desktop is produced in vnc.

**Comment by twaik** [comment]
You did not post any single piece of new information...

**Comment by Sail1boat** [comment]
It now works. I had to use force stop, then restart and now have a desktop
in VNC.
