### ISSUE TITLE
[Bug]: Esc exit from the app

### ISSUE THREAD

**Issue by Raffa064** [termux/termux-app#3849]
### Problem description

I bought a new physical keyboard and it's ESC key exits frrom the app... how can I fix it? I neeed the esc key to change neovim's modes.  

### Steps to reproduce the behavior.

My keyboard is changed to English US, internatitional layout. I didn't known what is happening...

### What is the expected behavior?

In my old keyboard it just sends the esc key to the console.

### System information

* Termux application version: 0.118.0
* Android OS version: 10
* Device model: xiaomi poco f1

**Comment by 1OSA** [comment]
i think esc key is in the FN layer if you want to use esc press FN+esc, while not holding FN its a "Home" button you can try to remap it.

**Comment by GR3YH4TT3R93** [comment]
.termux/termux.properties under the Back Key section. Change to back-key = escape

**Comment by Raffa064** [comment]
I managed to solve it, the new keyboard actually used FN to enable the esc, however, I managed to remap the keyboard with this project called [exkeymo](https://github.com/ris58h/exkeymo-web).

(I had to run their website using termux, but there were no complications)
