### ISSUE TITLE
[Bug]: Stuck on root user when opening termux .. can't use it

### ISSUE THREAD

**Issue by ghost** [termux/termux-app#3863]
### Problem description

I have android 7.1.2 and use SuperSu or other root ability. Upon opening termux, it opens as root user. Running whoami returns root. Typing id returns user id 0 and root user. Can't use pkg or apt... Please help.

### Steps to reproduce the behavior.

Well I just rooted and open app, it runs as root user

### What is the expected behavior?

Login as non root user, allows me to pkg and apt commands.

### System information

* Termux application version: unsure, obtained from Google play
* Android OS version: 7.1.2
* Device model: Samsung S10+ Snapdragon

**Comment by nicklamn1** [comment]
Lmfao not completed. Installed and it is like this… there’s no other user
account that I know of.
