### ISSUE TITLE
[Bug]: Side drawer is not opening 

### ISSUE THREAD

**Issue by purnchndr** [termux/termux-app#3865]
### Problem description

Side drawer is not opening on swiping right from left edge when gesture navigation option is enable, it trigger back button.

### Steps to reproduce the behavior.

Please increase the margin of swiping right from left edge area

### System information

* Termux application version: 0.118.0
* Android OS version: 13
* Device model: vivo v23 5g (128 GB)

**Comment by Jesse205** [comment]
@twaik  I think it's possible to extend the touch range to full screen, which would indirectly solve this problem. Someone has a library for this, and you can use it directly : https://github.com/PureWriter/FullDraggableDrawer

**Comment by Jesse205** [comment]
> #3798 (comment)

I can't do this on some systems where the back gesture responds at the entire screen height, so I can't open the side drawer on those systems.

**Comment by robertkirkman** [comment]
If you just install the version 0.119 beta and touch the hamburger button instead, does that work for what you need?

https://github.com/termux/termux-app/releases/tag/v0.119.0-beta.3

**Comment by sabamdarif** [comment]
@purnchndr  You shouldn't swipe left in a straight line, Instead move your finger upward as you slide, this should work
