### ISSUE TITLE
ERROR while pip install qianfan

### ISSUE THREAD

**Issue by MonkiFantasy** [termux/termux-app#3867]
### Problem description

here are the logs
[errorlog.txt](https://github.com/termux/termux-app/files/14470759/errorlog.txt)

### Steps to reproduce the behavior.

pip install qianfan

### What is the expected behavior?

install successully

### System information

* Termux application version:0.118.1
* Android OS version:14
* Device model:Redmi K70

**Comment by twaik** [comment]
I think you should install numpy first.
`pkg install python-numpy`

**Comment by MonkiFantasy** [comment]
> I think you should install numpy first. `pkg install python-numpy`
I had installed it yet
![Uploading Screenshot_2024-03-03-05-11-40-564_com.termux.jpg…]()

**Comment by MonkiFantasy** [comment]
https://github.com/baidubce/bce-qianfan-sdk/issues/308#issuecomment-1975646206
