### ISSUE TITLE
[Feature]: Enable/Disable Accessibility Mode

### ISSUE THREAD

**Issue by whjou** [termux/termux-app#3869]
### Feature description

My mobile banking app detected that Termux has Accessibility enabled and refused to run and advised me to disable Accessibility mode for Termux. However I do not see Termux listed under Accessibility / Installed apps. I'm loath to uninstalling Termux or the mobile banking app...

Is it possible to include such a feature to enable/disable Accessibility mode for Termux?

### Additional information

Applications that uses Accessibility are listed but not Termux, will be nice if Termux has it.

I'm on a Samsung Galaxy S24, if that information helps.

**Comment by agnostic-apollo** [comment]
Termux app does not use accessibility service. Issue is with your bank app, not with termux. Report to their support instead.
