### ISSUE TITLE
[Bug]: Issue while termux-setup-storage

### ISSUE THREAD

**Issue by vrnsoma** [termux/termux-app#3872]
### Problem description

The command outputs the following 
/data/data/com.termux/files/usr/bin/termux-setup-storage: line 29: 30926 Aborted                 am broadcast --user 0 --es com.termux.app.reload_style storage -a com.termux.app.reload_style com.termux > /dev/null

### Steps to reproduce the behavior.

Run the termux-setup-storage command. I  am runing it on crdroid 10.2 

### What is the expected behavior?

Should promt for storage perms

### System information

* Termux application version:118
* Android OS version:14 (crDroid 10.2)
* Device model:Pad6

**Comment by twaik** [comment]
Can you please run 
```
logcat -c
termux-setup-storage
logcat > log.txt
```
and post here the `log.txt`?
You can access the file with https://wiki.termux.com/wiki/Internal_and_external_storage (Read `Access Termux from a file manager`)

**Comment by agnostic-apollo** [comment]
`pkg install termux-am`
