### ISSUE TITLE
Termux 

### ISSUE THREAD

**Issue by Maxtyson2148** [termux/termux-app#3882]
![Screenshot_2024-03-11-16-30-57-989_com.termux.jpg](https://github.com/termux/termux-app/assets/145702117/10c8e8f7-e7eb-418e-bc18-48533ca6a8ab)

When I try to use the command pkg install tsu and click yes it is showing these repeated y can anyone explain?!

**Comment by minnesjay** [comment]
That is the output of the command `yes`, press CTRL + C to exit.
Yes will repeat y forever.
