### ISSUE TITLE
[Bug]:  need help

### ISSUE THREAD

**Issue by YashSoPro** [termux/termux-app#3889]
### Problem description

Comments
YashSoPro commented 4 minutes ago
at sh path to ur rish file I typed this sh /sdcard/Download/files/rish and it gave me error to type package name blah blah i asked chat gpt it said use this
export RISH_APPLICATION_ID="your_package_name"
it gave me this error
Request timeout. The connection between the current app (com.lol.ok) and Shizuku app may be blocked by your system. Please disable all battery optimization features for both current app (com.lol.ok) and Shizuku app.
we edited rish file to
#!/system/bin/sh
BASEDIR=$(dirname "$0")
DEX="$BASEDIR"/rish_shizuku.dex

if [ ! -f "$DEX" ]; then
echo "Cannot find $DEX, please check the tutorial in Shizuku app"
exit 1
fi

if [ $(getprop ro.build.version.sdk) -ge 34 ]; then
if [ -w $DEX ]; then
echo "On Android 14+, app_process cannot load writable dex."
echo "Attempting to remove the write permission..."
chmod 400 $DEX
fi
if [ -w $DEX ]; then
echo "Cannot remove the write permission of $DEX."
echo "You can copy to file to terminal app's private directory (/data/data/, so that remove write permission is possible"
exit 1
fi
fi

Replace "PKG" with the application id of your terminal app
[ -z "$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="com.lol.ok"
/system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
replaced pkg name it gave same error how do i fix pls help

### Steps to reproduce the behavior.

idk

### What is the expected behavior?

idk

### System information

* Termux application version: 118
* Android OS version: 11
* Device model: RMX3269

**Comment by twaik** [comment]
1. Not a bug of termux. You should fix your setup.
2. Do not store script or dex on sdcard. Use termux's home folder.
3. Make sure Shizuku is installed and works.
