### ISSUE TITLE
Upgrading ncurses version breaks mc display

### ISSUE THREAD

**Issue by nshram** [termux/termux-app#389]
Updating ncurses version from 20170722 to 20170729 distorts the display of midnight commander. Had to backup and re-install termux. Current ncurses version is at 20170812.
Don't know if Fredrik has fixed the bug. Had mailed him.

**Comment by sdrausty** [comment]
I also noticed that mc was a little bit off before 20170812. There were problems https://github.com/termux/termux-packages/issues/1252 with weechat, and https://github.com/termux/termux-packages/commit/1770bbac20b3bfcad335d89009a92af9d26b8b71 seems to have fixed it. Flickering is still annoying in weechat at times, and one time the screen was a little bit garbled in weechat too with 20170812. 

Midnight Commander, `mc` seems fine though. Try updating @nshram 
![screenshot_20170814-224859](https://user-images.githubusercontent.com/27742457/29300547-0515e98e-8144-11e7-917f-7946a2d3c935.png)

**Comment by nshram** [comment]
You're right! It's fixed now. I udated ncurses to 20170812 and no issues found with mc display.
Will close issue.
