### ISSUE TITLE
[Bug]: Termux terminate vnc

### ISSUE THREAD

**Issue by shhimoggedyou** [termux/termux-app#3891]
### Problem description

I am encountering an issue with my Ubuntu Cmd setup where the Xtightvnc process is unexpectedly terminated after approximately 10 seconds of use upon switching to the VNC app within Termux. The error message states 'successfully killed Xtightvnc process <randomnumber>'. I am seeking assistance to resolve this issue promptly. Any guidance or troubleshooting steps would be greatly appreciated. Thank you.

### Steps to reproduce the behavior.

ubuntu
--2024-03-23 02:44:20--  https://raw.githubusercontent.com/TecnicalBot/modded-distro/main/theme/theme.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1907 (1.9K) [text/plain]
Saving to: ‘theme.sh.13’

theme.sh.13          100%[====================>]   1.86K  --.-KB/s    in 0.004s

2024-03-23 02:44:22 (479 KB/s) - ‘theme.sh.13’ saved [1907/1907]

[sudo] password for ubuntu:
Hit:1 http://ports.ubuntu.com/ubuntu-ports mantic InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports mantic-updates InRelease [109 kB]
Hit:3 http://ports.ubuntu.com/ubuntu-ports mantic-security InRelease
Fetched 109 kB in 4s (29.9 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
6 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
yaru-theme-gtk is already the newest version (23.10.0-0ubuntu2).
yaru-theme-icon is already the newest version (23.10.0-0ubuntu2).
ubuntu-wallpapers is already the newest version (23.10.4).
ubuntu-wallpapers-jammy is already the newest version (23.10.4).
ubuntu-wallpapers-impish is already the newest version (23.10.4).
plank is already the newest version (0.11.89-4ubuntu1).
dconf-cli is already the newest version (0.40.0-4).
xfce4-panel-profiles is already the newest version (1.0.14-1).
xfce4-appmenu-plugin is already the newest version (0.7.6+dfsg1-4).
git is already the newest version (1:2.40.1-1ubuntu1).
The following packages were automatically installed and are no longer required:
  libunity-gtk2-parser0 libunity-gtk3-parser0 unity-gtk-module-common
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Cloning into 'modded-distro'...
remote: Enumerating objects: 282, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 282 (delta 28), reused 17 (delta 17), pack-reused 245
Receiving objects: 100% (282/282), 2.58 MiB | 479.00 KiB/s, done.
Resolving deltas: 100% (106/106), done.
config.txt
mv: cannot move '/home/ubuntu/modded-distro/theme/plank/launchers' to '/home/ubuntu/.config/plank/dock1/launchers': Directory not empty
mv: cannot move '/home/ubuntu/modded-distro/theme/plank/Azeny' to '/home/ubuntu/.local/share/plank/themes/Azeny': Directory not empty

Create Your VNC Password

New Xtigervnc server 'localhost.localdomain:1 (ubuntu)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /tmp/tigervnc.v86NZL/passwd :1 to connect to the VNC server.

Killing Xtigervnc process ID 27833... success!

### What is the expected behavior?

it shouldn't kill that process by himself 

### System information

* Termux application version: letest f-droid version
* Android OS version: 13
* Device model: v2249 ( vivo y27 )

**Comment by twaik** [comment]
Not a bug of termux or proot-distro. Probably VNC process is getting killed because of phantom process killer or incorrect environment setup.
Probably the problem is the script mentioned in your log. 
We are not responsible for every single command or script you find on the Internet.
Fix your setup.

**Comment by shhimoggedyou** [comment]
> Not a bug of termux or proot-distro. Probably VNC process is getting killed because of phantom process killer or incorrect environment setup. Probably the problem is the script mentioned in your log. We are not responsible for every single command or script you find on the Internet. Fix your setup.

no I did completed the panthom process but this error is different this killed the vnc only only the vnc as you can see

**Comment by twaik** [comment]
Phantom process killer is not the only possible reason I mentioned.
Fix your setup.

**Comment by twaik** [comment]
The script contains these lines.
```
vncstart
sleep 60
vncstop
```
Which means starting VNC server and killing it after a minute. 
The problem is this script.

**Comment by shhimoggedyou** [comment]
> Phantom process killer is not the only possible reason I mentioned. Fix your setup.

alr sir, cloud you please give me tutorial hownto install Ubuntu so I can use Android studio you know

**Comment by shhimoggedyou** [comment]
> The script contains these lines.
> 
> ```
> vncstart
> sleep 60
> vncstop
> ```
> 
> Which means starting VNC server and killing it after a minute. The problem is this script.

ah i see, can I change that?

**Comment by twaik** [comment]
> alr sir, cloud you please give me tutorial hownto install Ubuntu

No.

> so I can use Android studio

Not very wise. Android devices do not have CPU or RAM for this. And Android Studio is x86_64 only, running it on android device will mean emulation with qemu or box64 and that will be VERY slow even in the case if you succeed launching it.
Consider using AIDE.

> ah i see, can I change that?

As far as I can see the script is created to be used only once to setup environment.
Use `vncstart` to start VNC server and `vncstop` to stop it.

**Comment by shhimoggedyou** [comment]
> > alr sir, cloud you please give me tutorial hownto install Ubuntu
> 
> No.
> 
> > so I can use Android studio
> 
> Not very wise. Android devices do not have CPU or RAM for this. And Android Studio is x86_64 only, running it on android device will mean emulation with qemu or box64 and that will be VERY slow even in the case if you succeed launching it. Consider using AIDE.
> 
> > ah i see, can I change that?
> 
> As far as I can see the script is created to be used only once to setup environment. Use `vncstart` to start VNC server and `vncstop` to stop it.

like just normally starting whithout running the Ubuntu cmd First?

**Comment by twaik** [comment]
You should start `vncstart` from **within** your environment.

**Comment by shhimoggedyou** [comment]
> You should start `vncstart` from **within** your environment.


Uploading az_recorder_20240323_014503 (1).mp4…

**Comment by shhimoggedyou** [comment]
https://github.com/termux/termux-app/assets/164514835/5041d5a3-8c02-4bd1-a9dc-2edb57d14132

**Comment by twaik** [comment]
This repo is not a Linux kindergarten. We can help with some stuff but we are not going to spoonfeed you.

**Comment by twaik** [comment]
If you have troubles with some random script you get from Internet you should contact author of this script, and should not create issue in termux repo.
Again. We are not responsible for every program or script you get from Internet.

**Comment by shhimoggedyou** [comment]
> This repo is not a Linux kindergarten. We can help with some stuff but we are not going to spoonfeed you.

sorry 😔

**Comment by shhimoggedyou** [comment]
> If you have troubles with some random script you get from Internet you should contact author of this script, and should not create issue in termux repo. Again. We are not responsible for every program or script you get from Internet.

sorry 😔😐
