### ISSUE TITLE
D

### ISSUE THREAD

**Issue by Jhon24921010** [termux/termux-app#3895]
/storage/emulated/10/Android/data/ru.iiec.pydroid3/files $ root
sh: root: not found
/storage/emulated/10/Android/data/ru.iiec.pydroid3/files $ ome
sh: ome: not found
/storage/emulated/10/Android/data/ru.iiec.pydroid3/files $ home
sh: home: not found
/storage/emulated/10/Android/data/ru.iiec.pydroid3/files $

**Comment by TomJo2000** [comment]
None of those are commands.
Perhaps you should review Shell usage.
https://linuxjourney.com/lesson/the-shell
