### ISSUE TITLE
Android 14 Ghost keyboard

### ISSUE THREAD

**Issue by Jetrom17** [termux/termux-app#3897]
### Problem description

What I type simply doesn't appear on Android 14 in the Termux app version: 0.118.0

https://github.com/termux/termux-app/assets/72875404/b20dc0a6-d75c-4f09-a8bd-c39419964269

### Steps to reproduce the behavior.

Simply type.

### System information

* Termux application version: 0.118.0
* Android OS version: Android 14
* Device model: Motorola g⁷³

**Comment by Grimler91** [comment]
Does setting `enforce-char-based-input = true` in ~/.termux/termux.properties help? (See https://wiki.termux.com/wiki/Terminal_Settings#Workaround_issues_with_some_keyboards)

**Comment by Jetrom17** [comment]
Very thanks 🙏
