### ISSUE TITLE
Sonic-Pi on Termux

### ISSUE THREAD

**Issue by savolla** [termux/termux-app#391]
Hi guys,
I'm a sound engineer and wondering if it is possible to install sonic-pi onto Termux? For those guys who don't know about sonic-pi please check the link: https://www.youtube.com/watch?v=a1RxpJkvqpY

When I try to install with "apt install sonic-pi" it gives me a repository error. I need to add custom repository on Termux. how can I do it?

**Comment by fornwall** [comment]
Hello! I think you are more likely to get help asking the question at https://plus.google.com/communities/101692629528551299417 or https://groups.io/g/termux/.

**Comment by segodimo** [comment]
yet i'm waiting to use sonic pi on android...
