### ISSUE TITLE
 Incorrect permissions after upgrading to PHP 8.3

### ISSUE THREAD

**Issue by omegacms** [termux/termux-app#3913]
### Problem description

I wanted to start porting my framework from php 8.2 to php 8.3, but I had a problem with termux.

Practically termux is unable to manage the permissions needed to start **apache2** after upgrading to **PHP 8.3**.

Nothing is recorded in the log files other than this warning located in the file `/var/log/apache2/error.log`

```php
Mon Apr 8 18:43:45 2024 (6346): Error Cannot create lock - Permission denied (13)
```

This error means that the `apache2.pid` file cannot be created in `/var/run/apache2`.

I would like to point out that up to PHP8.2 everything worked without problems.

### Steps to reproduce the behavior.

**Step 1**
Install a Linux distribution via proot-distro, manually or via any app present in F-Droid or Google Play.

Install apache2, change the port `/etc/apache2/ports.conf` from **80** to **8080** and start apache2 to test correct operation.

**Step 2**
Install php 8.3 from the packages of your distribution, stop and restarting Apache to see that after waiting 20 seconds Apache does not start and the message I wrote above appears in the `/var/log/apache2/error.log` file.

### What is the expected behavior?

I expect Apache and PHP to work fine.

### System information

* Termux application version: Last versione in F-Droid (0.118.0)
* Android OS version: 13
* Device model: Galaxy Tab S9 Ultra

**Comment by TomJo2000** [comment]
This sounds like an issue with your distribution of choice in proot-distro.
Please file an issue in the proot-distro repository instead.
https://github.com/termux/proot-distro/issues/new/choose
