### ISSUE TITLE
[Bug]: Termux SAF cannot delete non-empty directory 

### ISSUE THREAD

**Issue by zavocc** [termux/termux-app#3916]
### Problem description

When trying to delete a folder recursively either using DocumentsUI (Google Files) app or third party apps like FX, it doesn't delete folders that is not empty whether if it's hidden or not.

### Steps to reproduce the behavior.

1. Create a directory with a file or folder (nested folder without a file would do)
2. Open DocumentsUI or third party file management apps that support SAF browsing 
3. Delete a non-empty directory, compared to deleting a file or empty directory 

### What is the expected behavior?

it should delete

### System information

* Termux application version: v0.118 fdroid
* Android OS version: 11
* Device model: OPPO A5 2020

**Comment by agnostic-apollo** [comment]
That is currently not supported among some other operations, will be available in next main `0.119.0` release.
