### ISSUE TITLE
Allow access

### ISSUE THREAD

**Issue by appt2** [termux/termux-app#3923]
### Feature description

Hello dear Termux developer, I want to use the entire Termux resource in my program, the name of my program is Ghost web ide, I need to implement the entire Termux in my program so that my user can install the required packages, and I have another question, if  Should I add the entire Termux source in my program, do I not need a special api to install all kinds of packages?

### Additional information

  .

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#forking

**Comment by agnostic-apollo** [comment]
Direct integration will also require releasing your app as open source under GPLv3. Allowing users to install packages at runtime will require hosting your own packages repo as well.

https://github.com/termux/termux-app/blob/master/LICENSE.md

**Comment by agnostic-apollo** [comment]
>exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

As expected. You need to compile all packages including the bootstrap for you app package name and make appropriate changes in java code as well. Read the forking docs linked above, especially `TermuxConstants` class javadocs. Not easy to do it.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent

**Comment by agnostic-apollo** [comment]
That code is tested and does work, tonne of people use it.

If you are facing issues, read its setup instructions again and check both system and app package `logcat` output.

**Comment by twaik** [comment]
Github has special syntax for code blocks. 
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
Consider using it please.

**Comment by agnostic-apollo** [comment]
> `intent.putExtra("com.termux.RUN_COMMAND_BACKGROUND", true);`

If you run it in background, of course Termux is not gonna open in foreground. Also check https://github.com/termux/termux-app?tab=readme-ov-file#debugging for how to see what commands are received and run.

> `intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/usr/bin/pkg");`
> `intent.putExtra("com.termux.RUN_COMMAND_ARGUMENTS", new String[]{"-c", "pkg install python3 -y jq gettext curl openssh; curl -s url; command 3;"});`

You are passing `pkg` as `RUN_COMMAND_PATH` and passing it the `-c` argument and additional `pkg` arguments. You need to use `bash`.

**Comment by twaik** [comment]
You are executing `pkg` with arguments `-c` and some command in bash format. `pkg` is not a shell to parse it.

**Comment by twaik** [comment]
@agnostic-apollo already told you what exactly you should do.

**Comment by agnostic-apollo** [comment]
Are you testing on Android 15?

**Comment by riccardogabellone** [comment]
> Are you testing on Android 15?

both 15 and 10

**Comment by agnostic-apollo** [comment]
>android.content.ActivityNotFoundException

You need to use sending intent to a service and not an activity. Use `startService()` calls.

Also check https://github.com/termux/termux-app/wiki/Termux-Libraries#target-sdk-30-package-visibility

**Comment by agnostic-apollo** [comment]
`registerForActivityResult` is not gonna work either. Register a broadcast receiver in your activity and receive result with it after sending it as a PendingIntent to termux, check advanced examples.

**Comment by riccardogabellone** [comment]
> `registerForActivityResult` is not gonna work either. Register a broadcast receiver in your activity and receive result with it after sending it as a PendingIntent to termux, check advanced examples.

perfect, was about to do that! thanks for the fast reply 💪

**Comment by riccardogabellone** [comment]
one more thing, how to manage process terminations? just sending another intent on app exit with manual process kill or is there a better and documented example of yours?
(I have to start a background localhost server from shell when app starts but need to stop that when app is killed 🙃)

**Comment by agnostic-apollo** [comment]
Welcome.

Note that if activity is stopped, you will need to unregister the receiver and you won't be able to receive the result, I am pretty sure an exception will be raised in termux app for that.

If you use a service to receive result, you can bind your activity to it, and unbind will need to be done on activity destroy instead on stop, and you should still be able to receive the result and process it in the service without activity being active.

Check related for receiver register and service bind 

https://github.com/termux/termux-app/blob/52da00e5c270a9049c37d46d42899eeffc27da1f/app/src/main/java/com/termux/app/TermuxActivity.java#L918

**Comment by agnostic-apollo** [comment]
Manual process kill intent is what will be needed, you can use `pgrep -f` to match the process name and kill its returned pid. Additionally, you should also check if server is already running before starting it again in case kill intent wasn't sent from last time.
