### ISSUE TITLE
[Bug]: nodejs Dependencies

### ISSUE THREAD

**Issue by Vanillma** [termux/termux-app#3925]
### Problem description

Hi there,

After updating libicu, I noticed that nodejs is complaining about missing softlinks from the previous version. :)
![Screenshot_20240421-110530_Termux](https://github.com/termux/termux-app/assets/95992420/e6d0d470-a26b-46d2-88bf-531786bdcc28)
![Screenshot_20240421-110628_Termux](https://github.com/termux/termux-app/assets/95992420/92d7e605-eae5-4151-8f6b-ace9789a1b8c)

Should I create them myself?
Use the previous version of libicu?
(Since it's still available in the repository)
Or will there be an update for nodejs?

Thanks,

### Steps to reproduce the behavior.

apt update libicu
npm ls -gt or Any command

### System information
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=22282
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
sources.list
deb https://packages.termux.dev/apt/termux-main stable main
root-repo (sources.list.d/root.list)
deb https://packages.termux.dev/apt/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
9
Kernel build information:
Linux localhost 3.4.113 armv7l Android
Device manufacturer:
samsung
Device model:
SM-G7102
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51

**Comment by Biswa96** [comment]
libicu dependencies are being rebuilt. Please wait until those are completed. The pending pull requests can be found here https://github.com/termux/termux-packages/pulls

**Comment by Vanillma** [comment]
> libicu dependencies are being rebuilt. Please wait until those are completed. The pending pull requests can be found here https://github.com/termux/termux-packages/pulls

Thanks for the explanation...so I'll close this issue...and wait...until then I'll use the previous version :)

**Comment by TomJo2000** [comment]
> If anyone had a similar problem pkg i libicu=74.2-1

Termux uses a "rolling release" model.
We don't keep or support older versions of packages, please just do a ***full*** package upgrade.
Using: `pkg up`

**Comment by Vanillma** [comment]
> > If anyone had a similar problem pkg i libicu=74.2-1
> 
> Termux uses a "rolling release" model. We don't keep or support older versions of packages, please just do a _**full**_ package upgrade. Using: `pkg up`

I know...but for now...maybe at least for today...there are two versions of the libicu in the repository...and since NodeJS isn't compatible yet...I'm using it for now...I'll edit the above message later...thanks👍

**Comment by TomJo2000** [comment]
NodeJS is [rebuilding right now](https://github.com/termux/termux-packages/actions/runs/8771455783/job/24069245547?pr=19865), I'm sorry that got delayed,
PHP in the same batch was having some issues, it's been moved to a separate rebuild batch now.
We should have it updated within 4-5 hours, not accounting for mirror sync delays.

This same song and dance happens every new `libicu` version.
And building out specific backward compatibility for the usually 6 to 12 hour period of interruptions caused by it is not worth the effort and overhead required.

**Comment by TomJo2000** [comment]
If you absolutely need NodeJS as soon as possible,
(i.e like 3 hours earlier than when it's gonna be updated on the repos)

You can grab it from the build artifacts of the CI run linked above once that finishes.

---

<sup>(This is a pre-written, saved reply.)</sup>
If you want to test this PR please download the appropriate DEB package(s)
from the build artifacts of the [associated PR's latest CI run](https://github.com/termux/termux-packages/pull/19865/checks).
![image](https://github.com/termux/termux-packages/assets/43716232/c13f4982-8fcf-47fb-8725-dd0dcdde2731)


After downloading the build artifact, make sure to `unzip` and un-`tar` it.
<details><summary>Detailed instructions, if needed.</summary>
<p>

```bash
# finding out what architecture you need
# architecture is just below the TERMUX_VERSION
termux-info

# e.g.
# [...]
# TERMUX_MAIN_PACKAGE_FORMAT=debian
# TERMUX_VERSION=0.118.0
# TERMUX__USER_ID=0
# Packages CPU architecture:
# aarch64
# [...]

# =======================

# make sure `unzip` and `tar` are installed using
pkg install unzip tar

# unzip the artifact (if you have a different architecture this might be arm, i686 or x86_64 instead)
unzip debs-aarch64-*.zip

# untar the artifact
tar xf debs-aarch64-*.tar

# You should now have a debs/ directory in your current working directory
# Install the packages from the local source using
pkg install -- ./debs/*.deb

# to clean up, you can remove the debs/ directory, .tar file and .zip file
rm -rfi debs debs-aarch64-*.zip debs-aarch64-*.tar
```

</p>
</details>

**Comment by Vanillma** [comment]
> If you absolutely need NodeJS as soon as possible, (i.e like 3 hours earlier than when it's gonna be updated on the repos)
> 
> You can grab it from the build artifacts of the CI run linked above once that finishes.
> 
> (This is a pre-written, saved reply.) If you want to test this PR please download the appropriate DEB package(s) from the build artifacts of the [associated PR's latest CI run](https://github.com/termux/termux-packages/pull/19865/checks). ![image](https://private-user-images.githubusercontent.com/43716232/323908848-c13f4982-8fcf-47fb-8725-dd0dcdde2731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTE3NjYsIm5iZiI6MTcxMzY5MTQ2NiwicGF0aCI6Ii80MzcxNjIzMi8zMjM5MDg4NDgtYzEzZjQ5ODItOGZjZi00N2ZiLTg3MjUtZGQwZGNkZGUyNzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA5MjQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNzAzZDQ1Y2VmMTk2NjA3MmE3ZGExZWNiNDI0MzU5YmExZGQzMzcyNjE4NTI5ZDc2ZTRhMmE0OWMyYjk5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eRchIWk5-mOoaK19QPzDM4ITIvDfR_HqXDfhb3hcBCM)
> 
> After downloading the build artifact, make sure to `unzip` and un-`tar` it.
> 
> Detailed instructions, if needed.

Thank you very much...now I saw that the previous version of the library is no longer available...so I edited the above message...thanks again for your quick support :)

**Comment by TomJo2000** [comment]
For anyone just coming across this issue now.

---

This is a known issue caused by the `libicu` update to 75.1 we're working on getting all packages that depend on it rebuilt, but that does take a while.
We apologize for any inconvenience please direct any further questions towards the PSA issue over at the packages repo.
- termux/termux-packages#19879
