### ISSUE TITLE
[Bug]: Can't run Nodejs, libicu version incompatible

### ISSUE THREAD

**Issue by dr3nn** [termux/termux-app#3926]
### Problem description

Nodejs requires libicu version 74, but termux only has version 75 available.

> pkg install nodejs
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://packages-cf.termux.dev/apt/termux-main/: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  c-ares libicu
Suggested packages:
  clang make pkg-config python
The following NEW packages will be installed:
  c-ares libicu nodejs
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/20.4 MB of archives.
After this operation, 109 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package c-ares.
(Reading database ... 6699 files and directories currently installed.)
Preparing to unpack .../c-ares_1.28.1_aarch64.deb ...
Unpacking c-ares (1.28.1) ...
Selecting previously unselected package libicu.
Preparing to unpack .../libicu_75.1_aarch64.deb ...
Unpacking libicu (75.1) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_21.6.2-1_aarch64.deb ...
Unpacking nodejs (21.6.2-1) ...
Setting up libicu (75.1) ...
Setting up c-ares (1.28.1) ...
Setting up nodejs (21.6.2-1) ...
CANNOT LINK EXECUTABLE "node": library "libicui18n.so.74" not found: needed by main executable
dpkg: error processing package nodejs (--configure):
 installed nodejs package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

Is there a way to get the older version? I've tried, but failed.

### Steps to reproduce the behavior.

Fresh install Termux
apt update
apt upgrade
pkg install nodejs

### System information

* Termux application version: latest
* Android OS version: 12

**Comment by 2096779623** [comment]
https://github.com/termux/termux-app/issues/3925#issuecomment-2067973819

**Comment by dr3nn** [comment]
> [#3925 (comment)](https://github.com/termux/termux-app/issues/3925#issuecomment-2067973819)

Oh, good to see it will be fixed shortly. Thanks for the quick answer.

**Comment by TomJo2000** [comment]
This is a known issue caused by the `libicu` update to 75.1 we're working on getting all packages that depend on it rebuilt, but that does take a while.
We apologize for any inconvenience please direct any further questions towards the PSA issue over at the packages repo.
- termux/termux-packages#19879
