### ISSUE TITLE
[Bug]: error on package PHP 

### ISSUE THREAD

**Issue by TUNBudi06** [termux/termux-app#3927]
### Problem description

Since upgrading package the PHP cant find simbol of libicu

`CANNOT LINK EXECUTABLE "php": cannot locate symbol "ubrk_next_74" referenced by "/data/data/com.termux/files/usr/bin/php"...`

### Steps to reproduce the behavior.

pkg upgrade -y

### What is the expected behavior?

To upgrading the latest package

### System information

Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12952
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
12
Kernel build information:
Linux localhost 4.14.282-liquid-OSS-RUI2/b16a01e50f #3 SMP PREEMPT Sat Mar 23 03:37:30 WIB 2024 aarch64 Android
Device manufacturer:
Sony
Device model:
realme C25 Series
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by TomJo2000** [comment]
This is a known issue caused by the `libicu` update to 75.1 we're working on getting all packages that depend on it rebuilt, but that does take a while.
We apologize for any inconvenience please direct any further questions towards the PSA issue over at the packages repo.
- termux/termux-packages#19879
