### ISSUE TITLE
[Bug]: Memory

### ISSUE THREAD

**Issue by 1liuzhongyi** [termux/termux-app#3939]
### Problem description

每打开一次 termux，内存就会增加 1mb
可在“设置/开发者选项/正在运行的服务”里看到内存使用情况
Memory increases by 1mb each time termux is opened
Memory usage can be seen in "Settings / Developer Options / Running Services"see

### Steps to reproduce the behavior.

打开termux并退出界面回到桌面，不要将termux的后台给清了，重复执行此操作，termux的内存会增加.
Open the termux and exit the interface back to the desktop, do not clean the termux background, repeat this operation, termux memory will increase.

### System information

android13

**Comment by agnostic-apollo** [comment]
Where did you install termux and what version are you on?

**Comment by 1liuzhongyi** [comment]
I wonder if there will be any garbled characters when I communicate with you in Chinese?

**Comment by agnostic-apollo** [comment]
I personally cannot reproduce it with my local changes (not 0.118.0), you may be running some commands that is using memory.

**Comment by Mazhari34** [comment]
Please this is use in version 10

**Comment by diehard88** [comment]
does termux slowdown to a crawl after the memory consumption increases?
