### ISSUE TITLE
launching termux scrolls indefinitely after the first launch

### ISSUE THREAD

**Issue by robolange** [termux/termux-app#395]
Running termux in ChromeOS 60 on an Asus C301 (stable). The first time I launch termux after booting, it launches normally. However, each subsequent time I launch termux, the command prompt scrolls downward infintely, as if someone were holding down the Enter key. It does this indefinitely until I press a key.

**Comment by j-bennet** [comment]
I have the same issue. I have to press Ctrl + C to stop that.

**Comment by gordol** [comment]
I too have this issue, on a Chromebook Pixel LS.

**Comment by Pommersche92** [comment]
Same on Acer R13

**Comment by robolange** [comment]
I haven't seen this issue on my termux for a while now, so I'm closing it.
