### ISSUE TITLE
[Feature]: tremux integration on my app

### ISSUE THREAD

**Issue by ohari5336** [termux/termux-app#3956]
### Feature description

I want to use termux as a library in my application, how I do this?

### Additional information

I want run my command line software in background on my app via termux integration, but I want simple setup no need to install termux first.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#forking

>but I want simple setup no need to install termux first.

That will require compiling all the termux packages and bootstrap for your app package name and hosting your own repos if you want users to install packages at runtime. You also cannot distribute your app on playstore with current design.

Easier would be to install termux and use `RUN_COMMAND` intent in background from your app.

https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent
