### ISSUE TITLE
[Bug]: termux-reload-settings fails

### ISSUE THREAD

**Issue by maxrademacher** [termux/termux-app#3959]
### Problem description

After a fresh install of termux, I run `termux-reload-settings` (without making any changes to the properties file - this is literally the first command I run after install), and the command fails with exit code 134 and prints "Aborted".

I've tried installing from the GitHub install page and from F-Droid and this is always the behavior I see.

### Steps to reproduce the behavior.

1. Install termux
2. Run `termux-reload-settings`

```
~ $ termux-reload-settings
Aborted
~ $ echo $?
134
```

### What is the expected behavior?

I would expect this to have a successful exit code and not print "Aborted"

### System information

* Termux application version: 0.118.0
* Android OS version: 14
* Device model: Pixel 6

**Comment by agnostic-apollo** [comment]
`pkg install termux-am termux-tools`

**Comment by maxrademacher** [comment]
Oh perfect that fixed it. Thank you!

Was there some documentation on this I missed? I googled around a bunch before submitting this issue and couldn't find anything.

**Comment by agnostic-apollo** [comment]
Welcome. No documentation for it, next termux app will already have a fixed package in its bootstrap. It's recommended to run `pkg upgrade` on fresh install to fix issues. But searching in the issues here should have reveled it.

https://github.com/termux/termux-app/issues?q=is%3Aissue+Aborted+Android+14
