### ISSUE TITLE
[Feature]: How to change Background of Extra Keys Toolbar ?

### ISSUE THREAD

**Issue by blogmangit** [termux/termux-app#3962]
### Feature description

Hi Everyone,
I just want to change the color of items in extra keys toolbar like transparency or individual button color.
![24_05_2024_23_03_55](https://github.com/termux/termux-app/assets/92579403/d9d60467-24c3-4be8-b7d5-0f2b6c721ced)

### Additional information

No

**Comment by agnostic-apollo** [comment]
Not possible currently.

**Comment by blogmangit** [comment]
> Not possible currently with a setting.

Actually I have moved to Termux Monet and I think I don't need it anymore closing it.
Thanks.

**Comment by blogmangit** [comment]
Not needed anymore.
