### ISSUE TITLE
[Bug]: Widgets/shortcuts are not silent enough

### ISSUE THREAD

**Issue by tremby** [termux/termux-app#3965]
### Problem description

I discovered the widget plugin today and set up a few shortcuts. It's really nice to have. 

I wish, however, that it were more silent. I wish it wouldn't flash a turmux window, and I wish that the termux window wouldn't then remain in my task switcher. 

### Steps to reproduce the behavior.

Right now if I'm in the middle of something and want to run a shortcut then go back to what I was doing, I swipe from bottom to go to my home screen, find the right workspace, tap the shortcut, then swipe from bottom left to the right to go back to previous app (or from bottom up and hold, then select the window), but the previous app is now termux (in what seems to be a dormant but not totally killed state), and so what that actually does is launch a brand new termux.

Here's a video showing the issue. 

https://github.com/termux/termux-app/assets/199635/293dfcd8-5a1a-4d51-9567-5ab119c9ebb9

### What is the expected behavior?

- No flash of termux window (or the option per shortcut not to show it; maybe overridden on nonzero exit? Getting ahead of myself) 
- No "dead" entry in the task switcher

### System information

* Termux application version: 0.118.0
* Android OS version: 14
* Device model: pixel 5

**Comment by agnostic-apollo** [comment]
Read the widget documentation and try to guess what you are doing wrong.

https://github.com/termux/termux-widget?tab=readme-ov-file#script-directories-mandatory

Flash disabling option will be available in next version.

**Comment by tremby** [comment]
Oof that's embarrassing. I guess I need to put them in tasks. Though the docs read like tasks are meant to be ongoing things, not short lived ("will show as running tasks in Termux app notification")

In my case .shortcuts already existed. Might I suggest automatically adding the other subdirectories by default too (and maybe a readme file too) so there's at least a clue for idiots like me who didn't read the docs?

**Comment by agnostic-apollo** [comment]
They will show in notification as long as the script is running.

widget app has been rewritten, ui will be provided to select shell type.
