### ISSUE TITLE
Java binaries?

### ISSUE THREAD

**Issue by v0idst4r** [termux/termux-app#397]

**Comment by fornwall** [comment]
Track https://github.com/termux/termux-packages/issues/45 for progress in packaging openjdk.

**Comment by sdrausty** [comment]
@v0idst4r    Java is available through:
# [TermuxArch](https://github.com/sdrausty/TermuxArch)

Now you can install Arch Linux in Termux 📲 on your smartphone and tablet. More information at https://sdrausty.github.io/TermuxArch

Java is available through https://sdrausty.github.io/TermuxArch/ Just follow the easy install instructions at https://sdrausty.github.io/TermuxArch/docs/docs/install or simply copy and paste the following into your Termux window:

```
cd && git clone https://github.com/sdrausty/TermuxArch
./TermuxArch/setupTermuxArch.sh
```
Read more about the Arch Linux package manager at [duckduckgo arch+linux+install+java+pacman.](https://duckduckgo.com/?q=arch+linux+install+java+pacman&atb=v90-2__&t=cros&ia=qa)

To install java run `pacman -Syy; pacman -Su; pacman -S jdk8-openjdk`


![screenshot_20171109-220204](https://user-images.githubusercontent.com/27742457/32641053-cedfdcfe-c599-11e7-9c73-b185e70e9c6a.png)
