### ISSUE TITLE
[Bug]: adding termux depedency

### ISSUE THREAD

**Issue by MrmaderatorYT** [termux/termux-app#3970]
### Problem description

I want to add termux depedency in 'android studio' project. 
I added:
`implementation 'com.github.termux.termux-app:211340781b'
implementation "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"`
But i have an error: 
`Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.termux.termux
app:termux-shared:211340781b.`

Also i trydet to use: **com.termux:0.114**, **com.termux:termux-shared:0.114**, but it has the same error

### Steps to reproduce the behavior.

I added in **settings.gradle**: this:
```
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://jitpack.io" }

    }
}
```

### What is the expected behavior?

I want to added termux depedency to use classes for my development

**Comment by twaik** [comment]
Why do you need termux-app as a dependency? It will not allow you to use packages. They are built exclusively for `com.termux` package (architecture restriction).

**Comment by MrmaderatorYT** [comment]
> Why do you need termux-app as a dependency? It will not allow you to use packages. They are built exclusively for `com.termux` package (architecture restriction).

I wan to make intent to termux to launch command automaticly, using this example:
https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#advance-examples

**Comment by twaik** [comment]
This code is for using with `termux-shared` library.
But you are not forced to use it. Simply use constants you see in basic example.
I mean 
```
TermuxConstants.TERMUX_PACKAGE_NAME = "com.termux";
TermuxConstants.TERMUX_APP.RUN_COMMAND_SERVICE_NAME = "com.termux.app.RunCommandService";
RUN_COMMAND_SERVICE.ACTION_RUN_COMMAND = "com.termux.RUN_COMMAND";
RUN_COMMAND_SERVICE.EXTRA_COMMAND_PATH = "com.termux.RUN_COMMAND_PATH";
// etc.
```

**Comment by MrmaderatorYT** [comment]
> This code is for using with `termux-shared` library. But you are not forced to use it. Simply use constants you see in basic example. I mean
> 
> ```
> TermuxConstants.TERMUX_PACKAGE_NAME = "com.termux";
> TermuxConstants.TERMUX_APP.RUN_COMMAND_SERVICE_NAME = "com.termux.app.RunCommandService";
> RUN_COMMAND_SERVICE.ACTION_RUN_COMMAND = "com.termux.RUN_COMMAND";
> RUN_COMMAND_SERVICE.EXTRA_COMMAND_PATH = "com.termux.RUN_COMMAND_PATH";
> // etc.
> ```

How u used **RUN_COMMAND_SERVICE.EXTRA_COMMAND_PATH**?
I added in manifest **<uses-permission android:name="com.termux.permission.RUN_COMMAND" />** and **        <service android:name=".PluginResultsService" /> **, but second one is highlighted like error

**Comment by twaik** [comment]
Just use the basic example, not advanced. And combine it with plugin result service example.
