### ISSUE TITLE
Unable to install bootstrap error[Bug]: 

### ISSUE THREAD

**Issue by f-o-r-t** [termux/termux-app#3973]
### Problem description

Shows: Termux can only be run as the primary user. Bootstrap binaries compiled for Termux have hardcoded $PREFIX path and cannot be installed under any path other than '/data/data/com.termux/files/usr'

### Steps to reproduce the behavior.

I dont know I am a beginner

### System information

* Termux application version:0.118.0
* Android OS version:13
* Device model:redmi note 11 pro+

**Comment by twaik** [comment]
Duplicate of #2291

**Comment by twaik** [comment]
Duplicate of #2765

**Comment by kqp7526-cmd** [comment]
Termux Bootstrap Error

Termux can only be run as the primary user.

Bootstrap binaries compiled for Termux have hardcoded $PREFIX path and cannot be installed under any path other than:

`/data/data/com.termux/files/usr`.

agree

PGUP

**Comment by kqp7526-cmd** [comment]
Termux Bootstrap Error

Termux can only be run as the primary user.

Bootstrap binaries compiled for Termux have hardcoded $PREFIX path and cannot be installed under any path other than:

`/data/data/com.termux/files/usr`.

agree

PGUP
``
