### ISSUE TITLE
Android N: sudo error

### ISSUE THREAD

**Issue by DCMMC** [termux/termux-app#398]
termux version is 0.53 via F-droid, Android version is AOSP 7.1.2, using Magisk SU.

And my device is Nexux 4 using custom ROM Pixel Dust (based on AOSP).

When I install termux-sudo then type sudo su, I get this error:

```
$ sudo su
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7153 Aborted                 $SU -c "$MOUNT_RW"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7155 Aborted                 $SU -c "mkdir $ROOT_HOME"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7158 Aborted                 $SU -c "chmod 700 $ROOT_HOME"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7161 Aborted                 $SU -c "echo -e $BASHRC > $ROOT_HOME/.bashrc"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7164 Aborted                 $SU -c "chmod 700 $ROOT_HOME/.bashrc"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7167 Aborted                 $SU -c "$MOUNT_RO"
```

**Comment by icebal** [comment]
this is happening on stock 7.1.2 and 8.0.0 with magisk systemless root, as well as regular supersu.

**Comment by DCMMC** [comment]
what can i do to fix it?

**Comment by icebal** [comment]
no clue, was just updating the issue that it isn't just custom roms, but stock ones too :)

**Comment by DCMMC** [comment]
oops, anyway, thank you 👍

**Comment by infernix** [comment]
this works:
```
LD_LIBRARY_PATH=/system/lib64:$LD_LIBRARY_PATH sudo su
```
might be fixable in termux-sudo

**Comment by salmantp** [comment]
Working sudo on android n . flash super su then uninstall magisk

**Comment by cdfa** [comment]
Same problem here. Please fix @st42

**Comment by mcurotto** [comment]
The problem apparently is with Magisk. See: [https://github.com/termux/termux-app/issues/423](url)

This sould also work (line 84 and 86 in sudo code):
`env -i $SU -c "$CMDLINE"`

You might have to set any variables needed, for example TERM (line 32 in sudo code):
`CMDLINE="PATH=$PATH:$SYSXBIN:$SYSBIN;$LDLP;HOME=$ROOT_HOME;export TERM=$TERM;cd $PWD"`

**Comment by QXR9** [comment]
I have this problem and i using mtk easy su. What I should?
