### ISSUE TITLE
[Feature]: Want to be able to use termux's built-in commands in rish

### ISSUE THREAD

**Issue by Tridays** [termux/termux-app#3988]
### Feature description

The new features suggest that you want to integrate the features of shizuku, such as soflinking the / proc and / dev directories to termux, Provider uses the。and Want to be able to use termux's built-in commands in rish。We hope to improve the interactivity between shizuku and termux.

Finally thanks to the termux team for their contribution

### Additional information

https://github.com/RikkaApps/Shizuku

**Comment by twaik** [comment]
Do you mean with adb privilegies?

**Comment by Tridays** [comment]
> Do you mean with adb privilegies?你是说 adb 特权吗？

Yes, shizuku can continue to provide adb privileges, I was wondering if there was a way to have adb permissions and use termux's commands and access $ HOME.

**Comment by twaik** [comment]
There is no way to access termux's filesystem with adb. 
It is android restriction. ADB can not access application sandbox of apps.

**Comment by agnostic-apollo** [comment]
If you are using Termux GitHub action builds, then you can run `adb run-as com.termux` command and then run `. /data/data/com.termux/files/usr/etc/termux/termux.env` to source the termux env, then `cd $HOME` and start a `bash` shell if needed.

https://github.com/termux/termux-app#github
