### ISSUE TITLE
The repository has an invalid certificate [Bug]: 

### ISSUE THREAD

**Issue by lp85d** [termux/termux-app#3996]
### Problem description

Не работают команды 

### Steps to reproduce the behavior.

Welcome to Termux

Docs:       https://termux.dev/docs
Community:  https://termux.dev/community

Working with packages:

 - Search:  pkg search <query>
 - Install: pkg install <package>
 - Upgrade: pkg upgrade

Report issues at https://termux.dev/issues
~ $ pkg update && pkg upgrade
Get:1 https://termux.net stable InRelease [1077 B]
Err:1 https://termux.net stable InRelease
  Couldn't execute /data/data/com.termux/files/usr/bin/apt-key to check /data/data/com.termux/files/usr/var/lib/apt/lists/partial/termux.net_dists_stable_InRelease
Warning: GPG error: https://termux.net stable InRelease: Couldn't execute /data/data/com.termux/files/usr/bin/apt-key to check /data/data/com.termux/files/usr/var/lib/apt/lists/partial/termux.net_dists_stable_InRelease
Error: The repository 'https://termux.net stable InRelease' is not signed.
Notice: Metadata integrity can't be verified, repository is disabled now.
Notice: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
Notice: Please note that all hosting problems or other serious issues we announce on our social media pages.

### What is the expected behavior?

Надеюсь решится 

### System information

* Termux application version:0.120
* Android OS version:11
* Device model: Xiaomi redmi 8 pro

**Comment by agnostic-apollo** [comment]
@fornwall

Let the issues begin...

**Comment by lp85d** [comment]
> @fornwall
> 
> Пусть начнутся проблемы...

termux-app_v0.118.0+github-debug_arm64-v8a.apk
С этой версией проблем нет.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-community/blob/site/site/pages/en/rules/index.md#2-only-english

**Comment by lp85d** [comment]
Sory

**Comment by agnostic-apollo** [comment]
An official response regarding the Google PlayStore app updates including `termux-app` `v0.120` has been made at https://github.com/termux/termux-app/discussions/4000

Open issue in respective repositories as we cannot fix such issues.

**Comment by fornwall** [comment]
> @fornwall
>
> Let the issues begin...

@agnostic-apollo Sorry about that - I've now updated the Google Play build to no longer point users at https://termux.dev/issues for reporting issues, but instead to an Google Play specific issue tracker at https://github.com/termux-play-store/termux-issues. Hopefully that will fix most issues like these!

**Comment by agnostic-apollo** [comment]
Thanks, that should help a bit.
