### ISSUE TITLE
[Bug]: Cant Access su with KernelSU

### ISSUE THREAD

**Issue by xifutang** [termux/termux-app#3997]
### Problem description

![Screenshot_2024-06-08-00-19-53-337_com termux](https://github.com/termux/termux-app/assets/104130103/fa701ce1-b277-48d0-99aa-af1403d7e4fd)

### Steps to reproduce the behavior.

1. Enable Superuser permission for Termux in KSU app
2. Open Termux
3. Type 'su' and enter

### System information

* Termux application version: 0.120
* Android OS version: 14
* Device model: Xiaomi Poco F5 global

**Comment by xifutang** [comment]
Reverting to 0.118 and it's just fine...
![Screenshot_2024-06-08-00-37-06-327_com termux](https://github.com/termux/termux-app/assets/104130103/127490b5-11a6-4e88-86a8-515ee5430ae4)

**Comment by TomJo2000** [comment]
0.120 is an experimental testing release for packaging on the Playstore again.
It should not be considered stable, and the Playstore version of Termux ***remains deprecated*** for the time being.

**Comment by agnostic-apollo** [comment]
An official response regarding the Google PlayStore app updates including `termux-app` `v0.120` has been made at https://github.com/termux/termux-app/discussions/4000

Open issue in respective repositories as we cannot fix such issues.

**Comment by HvTcCore** [comment]
Termux 0.118/0.119, KernelSU, Bliss OS 15
"No su program found on this device"
KernelSU app is installed, su permission allowed. Tried to reset termux data, also tried to reboot the system. Does not work
Other apps works correctly

**Comment by xmicro** [comment]
Same issue for me

**Comment by DCFUKSURMOM** [comment]
Same issue, I tried 0.118, 0.118.3 and the latest dev version. Bliss OS 16.9.7

**Comment by agnostic-apollo** [comment]
Run `pkg remove tsu; pkg install sudo` and then run `sudo su`.

**Comment by DCFUKSURMOM** [comment]
su does not exist for sudo to run it 🤦🏻‍♂️

**Comment by agnostic-apollo** [comment]
If you have granted termux root access, then it should. `tsu` will not find it.

https://www.reddit.com/r/termux/s/tROAnclKRT

**Comment by DCFUKSURMOM** [comment]
Weird. I will try it later, I'm about to go to the store.

**Comment by agnostic-apollo** [comment]
Cook going to the store, figures...

**Comment by DCFUKSURMOM** [comment]
Lol

**Comment by DCFUKSURMOM** [comment]
nope, termux 0.118.3 from github
<img width="1288" height="827" alt="Image" src="https://github.com/user-attachments/assets/b949a095-970d-4a02-a7d0-9598b7eac6e8" />

<img width="1288" height="827" alt="Image" src="https://github.com/user-attachments/assets/b12f4ca0-c5a2-4658-bad1-17cbe31014de" />

**Comment by DCFUKSURMOM** [comment]
same behavior in the latest beta

**Comment by agnostic-apollo** [comment]
Run `su -vvvv su`

**Comment by DCFUKSURMOM** [comment]
su does not exist, i cannot run a command that does not exist

**Comment by DCFUKSURMOM** [comment]
this is not magisk, this is kernelsu

**Comment by agnostic-apollo** [comment]
sorry, `sudo -vvvv su`

**Comment by DCFUKSURMOM** [comment]
No such file or directory

**Comment by agnostic-apollo** [comment]
You literally just ran `sudo su` above

**Comment by DCFUKSURMOM** [comment]
i think termux is having a stroke bc now its saying sudo isnt installed lol

**Comment by DCFUKSURMOM** [comment]
had to reinstall it, same error as above

**Comment by agnostic-apollo** [comment]
Send the output.

**Comment by DCFUKSURMOM** [comment]
<img width="1288" height="827" alt="Image" src="https://github.com/user-attachments/assets/b3586400-922b-4d4a-9df8-d9499fe48484" />

**Comment by DCFUKSURMOM** [comment]
this is 0.118.0, i tried downgrading lol

**Comment by agnostic-apollo** [comment]
Do you have any termux plugins installed? If yes, then try granting them access in kernel su.

**Comment by DCFUKSURMOM** [comment]
just a standard termux install, nothing extra. ive tried a few termux versions and ive tried updating the kernelsu app

**Comment by agnostic-apollo** [comment]
`sudo` already searches `/system/bin/su`, try running it with absolute path. If its not found, then termux app is not really the issue, and you should report to kernelsu support.

**Comment by DCFUKSURMOM** [comment]
that seems to work, weird

<img width="1288" height="827" alt="Image" src="https://github.com/user-attachments/assets/ddcfbd6c-ef88-404d-88ed-4d0f541fe9c5" />

**Comment by DCFUKSURMOM** [comment]
times like this i miss the old root methods...

**Comment by DCFUKSURMOM** [comment]
looks like there is an open issue already https://github.com/tiann/KernelSU/issues/2113

**Comment by DCFUKSURMOM** [comment]
interesting...
adding syscall_hardening=off to the kernel command line fixes this issue, i can run su directly now

<img width="1288" height="827" alt="Image" src="https://github.com/user-attachments/assets/d48c2294-1ea4-4fd6-a567-74ae236a183d" />

**Comment by DCFUKSURMOM** [comment]
sudo is also working now

**Comment by DCFUKSURMOM** [comment]
so not really a bug, but a config issue? mildly annoying but at least there is a workaround

**Comment by DCFUKSURMOM** [comment]
going to update termux just to sanity check, but i think this is resolved

**Comment by DCFUKSURMOM** [comment]
working in latest stable and latest beta :fire:

**Comment by agnostic-apollo** [comment]
Can you send output from outside root shell for:

```shell
[ -x /system/bin/su ] && echo exec
[ -f /system/bin/su ] && echo read
stat /system/bin/su
/system/bin/su --help
/system/bin/su --version
```

**Comment by DCFUKSURMOM** [comment]
<img width="1374" height="795" alt="Image" src="https://github.com/user-attachments/assets/0df6b504-16cd-4cbb-b61c-4f2813b4463a" />

**Comment by agnostic-apollo** [comment]
Sorry, forgot to mention to do this without the `syscall_hardening=off`.

**Comment by DCFUKSURMOM** [comment]
ok one sec, gotta tweak the grub config bc i already hardcoded the options lol

**Comment by agnostic-apollo** [comment]
Take your time, no hurry.

**Comment by DCFUKSURMOM** [comment]
lol my vm took "take your time" as a challenge. sometimes it takes a bit to get going, probably doesn't like being on an external hard drive. about to run the commands now

**Comment by DCFUKSURMOM** [comment]
<img width="429" height="185" alt="Image" src="https://github.com/user-attachments/assets/4ca97140-7f5e-479f-b672-34a6ff1250bb" />

**Comment by DCFUKSURMOM** [comment]
i was able to run /system/bin/su directly in 0.118, but not the latest beta, weird

**Comment by agnostic-apollo** [comment]
One more `/system/bin/su -c true && echo true`

**Comment by DCFUKSURMOM** [comment]
still not finding su like the previous output.

**Comment by agnostic-apollo** [comment]
What about running only `/system/bin/su`?

App versions should be irrelevant, just check termux is granted access again in kernel su.

**Comment by DCFUKSURMOM** [comment]
i cannot run it directly in the latest beta, i could in 0.118, it has root access granted. all versions ive tested work fine with the kernel option

**Comment by DCFUKSURMOM** [comment]
<img width="315" height="99" alt="Image" src="https://github.com/user-attachments/assets/fe0c4cfa-dffd-4fee-ba98-9600c02549af" />

**Comment by DCFUKSURMOM** [comment]
i can check the output of those commands in the older version if you want

**Comment by agnostic-apollo** [comment]
Maybe just reboot again.

**Comment by DCFUKSURMOM** [comment]
ok one sec

**Comment by DCFUKSURMOM** [comment]
no change
<img width="408" height="218" alt="Image" src="https://github.com/user-attachments/assets/2cefaad4-6958-4152-b43b-73da209178f5" />

**Comment by agnostic-apollo** [comment]
Disable the root permission for termux in kernelsu and grant it again, and check if other root apps have access.

**Comment by DCFUKSURMOM** [comment]
other apps have root access, im able to write to /system with totalcommander (i just changed the boot animation, nothing crazy). i can try the thing with termux though.

**Comment by DCFUKSURMOM** [comment]
no change

**Comment by agnostic-apollo** [comment]
`dpkg --print-architecture` and `(unset LD_PRELOAD LD_LIBRARY_PATH; /system/bin/su --help)`

**Comment by DCFUKSURMOM** [comment]
cannot access su at all without that kernel option in this termux version

<img width="409" height="121" alt="Image" src="https://github.com/user-attachments/assets/1ae360de-fa47-467f-b70a-3fa85118c867" />

**Comment by DCFUKSURMOM** [comment]
any command with su is going to return the same "No such file or directory", unless i downgrade to 118 or enable that kernel option

**Comment by agnostic-apollo** [comment]
Can you uninstall and reinstall the latest beta and use universal apk? You can test older versions too if you want.

https://github.com/termux/termux-app/releases/download/v0.119.0-beta.3/termux-app_v0.119.0-beta.3+apt-android-7-github-debug_universal.apk

**Comment by agnostic-apollo** [comment]
After reinstall, also send `dpkg --print-architecture`

**Comment by agnostic-apollo** [comment]
And what device are you using?

**Comment by DCFUKSURMOM** [comment]
its a qemu virtual machine running bliss os, which is x86_64 only

**Comment by DCFUKSURMOM** [comment]
> After reinstall, also send `dpkg --print-architecture`

just says x86_64, again this is an x86_64 build of android

**Comment by agnostic-apollo** [comment]
Also if you haven't uninstalled (or later), run `(unset LD_PRELOAD LD_LIBRARY_PATH; PATH=/system/bin /system/bin/su --help)`

**Comment by DCFUKSURMOM** [comment]
its just going to say it cant find su

**Comment by DCFUKSURMOM** [comment]
<img width="505" height="122" alt="Image" src="https://github.com/user-attachments/assets/582b1231-3384-46c0-afc9-5a8f3e528c62" />

**Comment by DCFUKSURMOM** [comment]
im about to try 118 again, we are just going in circles with this version.

**Comment by agnostic-apollo** [comment]
What about `(unset LD_PRELOAD LD_LIBRARY_PATH; PATH=/system/bin exec /system/bin/su --help)`

**Comment by DCFUKSURMOM** [comment]
i already uninstalled ☠️

**Comment by DCFUKSURMOM** [comment]
tried 0.118.3 rq, that cant /system/bin/su without the kernel option either

**Comment by DCFUKSURMOM** [comment]
but 0.118.0 can

<img width="335" height="340" alt="Image" src="https://github.com/user-attachments/assets/7f18be10-624f-4de8-a7b8-19a0bdab30cb" />

**Comment by agnostic-apollo** [comment]
You can run it after reinstalling. But run `(unset LD_PRELOAD LD_LIBRARY_PATH; (PATH=/system/bin /system/bin/su --help))`

**Comment by DCFUKSURMOM** [comment]
well im on a termux version that can actually see /system/bin/su now, so the commands should actually do something

**Comment by agnostic-apollo** [comment]
If you could please upgrade to beta, I think I know what the issue is.

**Comment by DCFUKSURMOM** [comment]
ok one sec

**Comment by DCFUKSURMOM** [comment]
ok im on the latest beta

**Comment by agnostic-apollo** [comment]
Also run `TERMUX_EXEC__LOG_LEVEL=4 /system/bin/su --help`

**Comment by DCFUKSURMOM** [comment]
<img width="809" height="190" alt="Image" src="https://github.com/user-attachments/assets/1db8d41a-bf1a-4085-b4bd-8a5bedcd4ecc" />

**Comment by agnostic-apollo** [comment]
This too `(unset LD_PRELOAD LD_LIBRARY_PATH; (PATH=/system/bin /system/bin/su --help))`

**Comment by DCFUKSURMOM** [comment]
same output as before, "No such file or directory"

**Comment by agnostic-apollo** [comment]
Just confirming, you ran su inside a second nested subshell, right?

**Comment by DCFUKSURMOM** [comment]
im just opening termux and copying the commands you sent

**Comment by agnostic-apollo** [comment]
```
(unset LD_PRELOAD LD_LIBRARY_PATH; (PATH=/system/bin/su /system/bin/su --help))
(unset LD_PRELOAD LD_LIBRARY_PATH; (PATH=/data/data/com.termux/files/usr/bin /system/bin/su --help))
(unset LD_PRELOAD LD_LIBRARY_PATH PATH; (/system/bin/su --help))
```

**Comment by DCFUKSURMOM** [comment]
<img width="688" height="145" alt="Image" src="https://github.com/user-attachments/assets/8567cc8e-8f0a-400b-a415-2e28bf3158de" />

**Comment by agnostic-apollo** [comment]
Seems like LD_PRELOAD does not get unset inside subshell. Try ` (unset LD_PRELOAD LD_LIBRARY_PATH; TERMUX_EXEC__LOG_LEVEL=4 PATH=/system/bin /system/bin/sh -c "/system/bin/su --help")`

**Comment by DCFUKSURMOM** [comment]
<img width="794" height="338" alt="Image" src="https://github.com/user-attachments/assets/352cce30-204f-4a62-8f78-56c0657778c1" />

**Comment by agnostic-apollo** [comment]
At least LD_PRELOAD got unset.

In https://github.com/tiann/KernelSU/issues/2113#issue-2562791363 its mentioned:

> Termux can only be able to go to su if using /system/bin/su, and when in su no $PATH is set other than Termux or KSU own path.

So try

```shell
(unset LD_PRELOAD LD_LIBRARY_PATH; PATH=/data/data/com.termux/files/usr/bin /system/bin/sh -c "/system/bin/su --help")
(unset LD_PRELOAD LD_LIBRARY_PATH PATH; /system/bin/sh -c "/system/bin/su --help")
```

**Comment by DCFUKSURMOM** [comment]
<img width="769" height="117" alt="Image" src="https://github.com/user-attachments/assets/e0f03e2e-f560-4f5b-8814-95fbf7beabda" />

**Comment by agnostic-apollo** [comment]
Well, this is getting ridiculous, there must be some difference in 0.118.0 that is allowing it. Try running su inside a failsafe session from long hold launcher icon.

**Comment by DCFUKSURMOM** [comment]
<img width="268" height="101" alt="Image" src="https://github.com/user-attachments/assets/b26bcb8c-bcab-4e9d-93fc-48dc5859000b" />

**Comment by agnostic-apollo** [comment]
Okay, one last, try 

```shell
(unset LD_PRELOAD LD_LIBRARY_PATH; PATH=/data/data/com.termux/files/usr/bin /system/bin/sh -c "exec /system/bin/su --help")
(unset LD_PRELOAD LD_LIBRARY_PATH PATH; /system/bin/sh -c "exec /system/bin/su --help")
```

**Comment by DCFUKSURMOM** [comment]
<img width="803" height="118" alt="Image" src="https://github.com/user-attachments/assets/f5152956-7724-49ca-86c2-1e0a85c37ae9" />

**Comment by DCFUKSURMOM** [comment]
same in failsafe

<img width="980" height="130" alt="Image" src="https://github.com/user-attachments/assets/7ff8fa0d-8a9c-40d7-a39e-b36b9f2d84bd" />

**Comment by agnostic-apollo** [comment]
Maybe the help command is an issue.

```
(unset LD_PRELOAD LD_LIBRARY_PATH; PATH=/data/data/com.termux/files/usr/bin /system/bin/sh -c "exec /system/bin/su -c true")
(unset LD_PRELOAD LD_LIBRARY_PATH PATH; /system/bin/sh -c "exec /system/bin/su -c true")
```

**Comment by DCFUKSURMOM** [comment]
<img width="824" height="144" alt="Image" src="https://github.com/user-attachments/assets/98229e5a-e2a5-4054-90a4-d2d5b0d1364c" />

**Comment by agnostic-apollo** [comment]
Damn. There are various issues reported in KernelSU for this, I have just been trying to figure out what configuration works.

- https://github.com/tiann/KernelSU/issues/1813
- https://github.com/tiann/KernelSU/issues/2647

**Comment by DCFUKSURMOM** [comment]
so far the only thing that works consistently is running /system/bin/su in 118 or enabling the kernel option

**Comment by DCFUKSURMOM** [comment]
with the kernel option i can just do su

**Comment by DCFUKSURMOM** [comment]
definitely something fucky going on lol

**Comment by agnostic-apollo** [comment]
Yeah, but why does 0.118.0 work, but not 0.118.3, there aren't any system env variable changes in 0.118.3 and only change would be `libtermux-exec.so`, which we are already unsetting since it fails `access(executablePath, X_OK)`.

https://github.com/termux/termux-exec-package/blob/4606100e0b4a33bf4a6cd4579e6cbd0be8cf02ee/lib/termux-exec_nos_c/tre/src/termux/api/termux_exec/service/ld_preload/direct/exec/ExecIntercept.c#L198

Similar change was done for playstore `su` wrapper to not hook exec for `su` calls.

https://github.com/termux-play-store/termux-tools/commit/9187cfa169cc64861a0fc7e98a01b9c78eb1634d

Maybe install 0.118.0 and then upgrade all packages with `pkg upgrade`, then RESTART termux and see if `su` still works after that.

**Comment by agnostic-apollo** [comment]
Run `(unset LD_PRELOAD LD_LIBRARY_PATH; PATH=/system/bin /system/bin/sh -c "exec su -c true")`

**Comment by DCFUKSURMOM** [comment]
118 installed, upgrading packages

**Comment by DCFUKSURMOM** [comment]
well damn, upgrading packages in 118 does stop /system/bin/su from working

**Comment by agnostic-apollo** [comment]
Try the above command.

**Comment by DCFUKSURMOM** [comment]
was already in the process of doing it lol
<img width="598" height="125" alt="Image" src="https://github.com/user-attachments/assets/38a174b5-7caa-4edd-bf48-a82af9174ddb" />

**Comment by DCFUKSURMOM** [comment]
<img width="867" height="356" alt="Image" src="https://github.com/user-attachments/assets/2a0996bf-d3dd-4092-a1a9-55c805029a34" />

**Comment by agnostic-apollo** [comment]
At least its a package issue and not app. But then again why would a package issue affect execution if running from inside `/system/bin/sh` and without termux-exec in `LD_PRELOAD`.

**Comment by agnostic-apollo** [comment]
You can clear Termux app data and reinstall bootstrap for 0.118.0, and then run `pkg install termux-tools`, restart termux, then try `su`. If it still succeeds, run `pkg install termux-exec`, restart termux, and try `su`.

**Comment by DCFUKSURMOM** [comment]
looks like termux-exec breaks su

**Comment by DCFUKSURMOM** [comment]
a reminder that i cannot run su directly even on unupdated 118, i have to type /system/bin/su.
i can only do su normally with the kernel option

**Comment by DCFUKSURMOM** [comment]
> looks like termux-exec breaks su

i wonder, if i update the packages but downgrade or uninstall termux-exec would su work?

**Comment by DCFUKSURMOM** [comment]
can termux even downgrade packages?

**Comment by DCFUKSURMOM** [comment]
looks like that would cause dependency issues anyways ☠️

**Comment by agnostic-apollo** [comment]
Without the kernel option, there is no real `su` file at `/system/bin/su`, and `access()` calls like with `-x` will fail, so will `stat()`, only `execve()` works as kernel su overloads it and manually executes su.


The reason typing only `su` does not work is that termux `su` wrapper in `$PREFIX/bin/su` fails the `-x /system/bin/su` check. You should probably be able to do `PATH=/system/bin su` with default packages.

https://github.com/termux/termux-tools/blob/b9eafe3aa3b31af9a340104e5b38dbdb96a6bcc8/scripts/su.in#L7

You can run `apt-mark hold termux-exec` and upgrade all packages so that termux-exec doesn't get updated.

**Comment by DCFUKSURMOM** [comment]
upgraded the packages with termux-exec held, /system/bin/su works like that

**Comment by DCFUKSURMOM** [comment]
with default packages PATH=/system/bin su says termux-tools isnt intalled, even after updating that package

**Comment by agnostic-apollo** [comment]
At least that's confirmed, unhold termux-exec and then update it. Then run:

```shell
unset LD_PRELOAD
PATH=/system/bin /system/bin/sh
/system/bin/su
```

**Comment by DCFUKSURMOM** [comment]
<img width="551" height="355" alt="Image" src="https://github.com/user-attachments/assets/c353baea-bca0-4a8a-8e63-35a9389b1125" />

**Comment by agnostic-apollo** [comment]
> with default packages PATH=/system/bin su says termux-tools isnt intalled, even after updating that package

Ah sorry, that would internally fail access() calls too in execve().

**Comment by agnostic-apollo** [comment]
By any chance have you angered any local witches in your area?

**Comment by DCFUKSURMOM** [comment]
you joke but im not far from the bell witch cave 🤣

**Comment by agnostic-apollo** [comment]
I KNEW IT!!! I think its best you go make peace with them first :p

**Comment by agnostic-apollo** [comment]
Inside `/system/bin/sh`, run `/system/bin/sh` again and then `/system/bin/su`.

**Comment by DCFUKSURMOM** [comment]
<img width="553" height="366" alt="Image" src="https://github.com/user-attachments/assets/042d7ba2-a662-4420-85b6-8d85e10bcef4" />

**Comment by agnostic-apollo** [comment]
You were supposed to unset LD_PRELOAD AND set PATH like above first.

**Comment by DCFUKSURMOM** [comment]
ah, one sec lol

**Comment by agnostic-apollo** [comment]
```
unset LD_PRELOAD
PATH=/system/bin /system/bin/sh
/system/bin/sh
/system/bin/su
```

**Comment by DCFUKSURMOM** [comment]
<img width="554" height="369" alt="Image" src="https://github.com/user-attachments/assets/fbeaa6e7-4003-4629-9a12-7462e0493600" />

**Comment by agnostic-apollo** [comment]
What about `exec /system/bin/su` or `exec -a su /system/bin/su`

**Comment by DCFUKSURMOM** [comment]
<img width="502" height="446" alt="Image" src="https://github.com/user-attachments/assets/70a475c4-df8b-4afd-bdd0-fcd714b355de" />

**Comment by agnostic-apollo** [comment]
Alas. Maybe @tiann or @aviraxp have some ideas that I am missing.

**Comment by robertkirkman** [comment]
I have a KernelSU device which currently has KernelSU 11510, Termux 0.119.0-beta.3 from GitHub release, `sudo` 1.2.0, `termux-exec` 2.4.0-1, and BlissOS 16.9.4 which is also a 64-bit Android-x86 13 (like BlissOS 16.9.7 is), and `sudo su` and `su` are both working for me,

<img width="1275" height="799" alt="Image" src="https://github.com/user-attachments/assets/df363f72-6792-4cbd-b0ea-ceb44c3d5e5d" />

as far as I can tell the only relevant difference between my device and the other user's device seems like it might be that my BlissOS version is 16.9.4, but the other user's device is version 16.9.7. My device doesn't work with BlissOS 16.9.7, only 16.9.4 (the problem with 16.9.7 on my device is a black screen or bootloop or something like that), so I am waiting until the next versions of BlissOS in the future are finished before upgrading. Maybe the difference about `su` is a difference between the slightly different BlissOS versions, but I don't know.

I'm not using the `syscall_hardening=off` kernel argument and I didn't need to in order for `sudo` and `su` to work. Here are my kernel arguments:

<img width="705" height="114" alt="Image" src="https://github.com/user-attachments/assets/f5a8f39f-1767-4d93-8782-fa6872921e3c" />

**Comment by agnostic-apollo** [comment]
Thanks a lot for the info. However, even with their 16.9.7, su does work for 0.118.0/old termux-exec, so why not new. Another variant to test....

```shell
unset LD_PRELOAD
/system/bin/sh
exec -c /system/bin/sh
/system/bin/su
```

**Comment by DCFUKSURMOM** [comment]
<img width="642" height="372" alt="Image" src="https://github.com/user-attachments/assets/494357dc-bf61-47ae-a864-71809c514880" />

**Comment by hastpanha-droid** [comment]
Guy I think we can use su in Termux another way. Try using Shizuku (root works for me)  and activate it using root. After that Click Use Shizuku in terminal apps then chose import file which you'll have to make a folder to contain the file. (the files are `rish` and `rish_shizuku.dex`). Now edit the "rish" file using any editing tool. change the `"PKG"` to `"com.termux"` and save it. (The `"PKG"` is in the last 2nd line). after that in Termux and go to your folder that contain the files and use `sh rish`. Shizuku will ask to give access to termux. Just allow it. Then you can run as root using ex: `/bin/mount --bind folder1 folder2` **NOTE: use normal `mount` doesn't work** . You can also use command that installed on Termux (Ex: `/data/data/com.termux/files/usr/bin/mount --bind a b`). (sorry for my bad English though)

**Comment by robertkirkman** [comment]
Update: between my last post and now I installed BlissOS 16.9.7 bare metal on a different device, and at least for me, I noticed:

- **I wasn't able to update its KernelSU to the latest version of KernelSU because of the app saying something that seemed to mean that the part of KernelSU in the kernel wasn't compatible with the part of KernelSU in the newest KernelSU app**, and I don't know how to update the part of KernelSU in the kernel of BlissOS, so I had to stay on the old version.
- I was also able to reproduce the problem described in this thread of `su` not working with `inaccessible or not found` only when using a recent Termux App or when using version 0.118.0 and upgrading it to the newest packages and then restarting it, not when using Termux App version 0.118.0 and _not_ upgrading it (consistent with symptoms described in this thread)
- Because of my inability to upgrade KernelSU to the newest version, and the consistency of what I observed with previous observation, **my impression is that the issue experienced by @DCFUKSURMOM is most likely a manifestation of this issue**: https://github.com/tiann/KernelSU/issues/2523
 
 
- I did not try the `syscall_hardening=off` workaround. Actually, instead, I came up with a different workaround that _does_ work for me instead, which I use to achieve my root needs in BlissOS 16.9.7 without needing to somehow successfully update KernelSU:

> [!NOTE]
> 
> to get root in fully-up-to-date Termux in BlissOS version 16.9.7,
> first grant Termux root permission in KernelSU app, then unset `LD_PRELOAD`,
> then launch a new bash session, then directly invoke
> `/system/bin/su` (with absolute path), then set `LD_PRELOAD` again
>
> ```bash
> unset LD_PRELOAD
> bash
> /system/bin/su
> export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so
> ```

- I assume that whenever BlissOS releases a new stable version in the future, it will probably come with an updated KernelSU, which will have the fix for the issue https://github.com/tiann/KernelSU/issues/2523 in it, so, assuming that the issue discussed here is a manifestation of that issue, will probably work with newer Termux `termux-exec` without workarounds

**Comment by agnostic-apollo** [comment]
termux-exec newer versions hook entire exec family, and uses different files in LD_PRELOAD, that's the only difference.

Once issue is that during upgrade from default 0.118.0, the `libtermux-exec.so` file used by current shell set in LD_PRELOAD will be replaced with a symlink to `libtermux-exec-ld-preload.so` and will require starting a new shell to for updated LD_PRELOAD to be exported by login script . Starting a new shell wouldn't be required if install 0.118.3 or beta 3.

However, why should LD_PRELOAD have an effect when it has already been unset and multiple nested processes have been started before calling `su`, that shouldn't be happening and looks to be a kernel issue.

**Comment by robertkirkman** [comment]
unsetting `LD_PRELOAD` and using the command `bash` and then using `/system/bin/su` is definitely what worked around this problem in BlissOS 16.9.7 for me in any Termux with `termux-exec` updated past a certain point (I remember now that I did confirm that it's `termux-exec` that makes the difference by saving an old `termux-exec` from the old bootstrap inside Termux App 0.118.0 and swapping between it and the newest `termux-exec` in the updated Termux App while restarting Termux in between), if I didn't use `bash` in between `unset LD_PRELOAD` and `/system/bin/su`, then it would never work with the newer `termux-exec` installed no matter how many times I tried, but I agree it's strange.

It seemed to me to be similar to the problem reported and fixed previously in the KernelSU repo, but if you are curious about what really causes this and want to check for yourself to make sure whether it really is related to that or not, I suggest you could download and install BlissOS 16.9.7 and run any analysis you can think of, but this might not be worth spending time on, since there are now multiple workarounds reported and I assume it might be fixed in a future release of KernelSU in BlissOS.

**Comment by agnostic-apollo** [comment]
unsetting LD_PRELOAD and running a command still executes new command with ld preload hooks as parent process already has it loaded in memory. The second exec done in child process will run without ld preload as child process no longer has ld preload loaded. That's why running bash or /system/bin/sh in between is necessary before running any new commands.

Yeah, I don't have a spare device or the time.

**Comment by mrahmadusama** [comment]
[SOLVED]: Just by removing termux from tricky store target list and then again giving root access
