### ISSUE TITLE
[Bug]:  Certificate verification failed

### ISSUE THREAD

**Issue by mrsrimar22** [termux/termux-app#3998]
### Problem description

Certificate verification failed when acessing apt repo from Indonesian network ( Axiata & Telkom )

### Steps to reproduce the behavior.

![Screenshot_20240608-005523_Termux](https://github.com/termux/termux-app/assets/98408993/5fec2bfb-5f6e-4897-b049-3c9c7a5feebb)

### System information

* Termux application version: 0.120 playstore
* Android OS version: 13
* Device model: -

**Comment by twaik** [comment]
https://github.com/termux/termux-app/issues/3997#issuecomment-2155277090
