### ISSUE TITLE
Incompatible w/ Galaxy Tab GT-P1000

### ISSUE THREAD

**Issue by xrat** [termux/termux-app#400]
I got a Samsung Galaxy Tab GT-P1000 running CyangenMod 11/Android 4.4. I'd love to try Termux but Google Play says "This app is incompatible with your device." What are the requirements?

**Comment by sdrausty** [comment]
@xrat Android 5+ or Chrome OS

**Comment by xrat** [comment]
@sdrausty haven't found that anywhere. Thanks for the quick reply.
