### ISSUE TITLE
App crash on new `Google Play Store` update

### ISSUE THREAD

**Issue by onchere** [termux/termux-app#4004]
### Problem description

App crashes whenever I run `termux-setup-storage` with the new app update on Google Play Store.

### Steps to reproduce the behavior.

Install termux from Google Play Store (latest update).
Open termux.
Run `termux-setup-storage`.
App crashes.

### System information

* Termux application version: Latest
* Android OS version: 13
* Device model: Samsung

**Comment by Grimler91** [comment]
Please open an issue in https://github.com/termux-play-store/termux-apps. See https://github.com/termux/termux-app/discussions/4000 for differences between playstore version and F-Droid version.

Closing since we cannot fix issues with playstore apps.

**Comment by caliban511** [comment]
所以为什么 Google Play Store 上有更新，而 F-Droid 上还是两年前的旧版本？😳😳😳😳😳
