### ISSUE TITLE
120.0

### ISSUE THREAD

**Issue by Feuerswut** [termux/termux-app#4006]
### Problem description

The release is available via Google Play, but 120.0 is not available via F-Droid.

-> Google Play cant update over the App installed by F-Droid.
-> Google Play will retry indefinitely and the Update list won't get cleared so other app updates are not installed (in time)

### Steps to reproduce the behavior.

have the F-Droid version installed and go to Play Store -> Updates

### What is the expected behavior?

the same version number being available on every platform at the same time. (F-Droid should get it a day early or 2)

### System information

* Termux application version: 118.0
* Android OS version: 14
* Device model: oriole

**Comment by LinuxOpa** [comment]
same prob me too!

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/discussions/4000
