### ISSUE TITLE
[Bug]: Google Play offers Termux update 

### ISSUE THREAD

**Issue by gladykov** [termux/termux-app#4008]
### Problem description

Dates 7 of June with version 122. This should not happen as per description of project, devs do not have access to Play Store anymore. So is it some fraud which should be reported to Google?

### Steps to reproduce the behavior.

https://play.google.com/store/apps/details?id=com.termux

![Screenshot_20240610-142900_Google_Play_Store](https://github.com/termux/termux-app/assets/24669884/f14f887d-69c8-4dce-b67f-cc2052a2d192)

PS. This version will not install when trying to update Termux from FDroid. Attempt will result in error.

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/discussions/4000
