### ISSUE TITLE
[Feature]: Fdroid release per architecture instead of universal

### ISSUE THREAD

**Issue by indrastorms** [termux/termux-app#4011]
### Feature description

FDroid supports per architecture release, so instead of releasing universal apk release apk per architecture.

### Additional information

Benefits: 
1. Faster download 
2. Less user space occupied
3. Less interenet data consumption

**Comment by Anonymous2716** [comment]
In addition to that if anyone for any reason needs to use a different supported architecture installation instead of the default architecture this would help.

**Comment by RokeJulianLockhart** [comment]
Why instead, rather than in addition to?

**Comment by agnostic-apollo** [comment]
Read the README

https://github.com/termux/termux-app#f-droid

> F-Droid does support architecture specific APKs.

https://github.com/termux/termux-app/pull/1904

**Comment by agnostic-apollo** [comment]
Seems like it does now, but requires different version code schemes.

https://gitlab.com/fdroid/fdroiddata/-/issues/2809

https://github.com/termux/termux-app/issues/4012#issuecomment-2166478308 may not have enough bits for 4 different abis, unless `release_variant` gets used, but that would decrease max possible version codes per variant as pairs wouldn't be possible.

**Comment by licaon-kter** [comment]
Yeah, it does for years....

**Comment by agnostic-apollo** [comment]
Maybe can be considered in future.
