### ISSUE TITLE
[Bug]: Popup with extra keys wastes space with SW keyboard disabled (have hardware keyboard; bluetooth, wireless)

### ISSUE THREAD

**Issue by SwuduSusuwu** [termux/termux-app#4017]
### Problem description

![HW + extra row](https://github.com/termux/termux-app/assets/168943815/0e1879b6-1845-42be-b790-1e8cb4460b24)
![SW + extra row](https://github.com/termux/termux-app/assets/168943815/21f0fd35-18f4-404e-9572-9df49b8fa4bb)
![Termux Settings](https://github.com/termux/termux-app/assets/168943815/14011a44-b92e-4946-a98d-3df87025cd65)

### Steps to reproduce the behavior.

Launch Termux

### What is the expected behavior?

Should just show this if keyboard is SW

### System information

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=30205
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
Updatable packages:
gh/stable 2.51.0 aarch64 [upgradable from: 2.50.0]
libxml2/stable 2.13.0 aarch64 [upgradable from: 2.12.7]
termux-tools version:
1.42.4
Android version:
14
Kernel build information:
Linux localhost 5.10.189-android13-4-00012-g1217bb583cc5-ab11174560 #1 SMP PREEMPT Mon Dec 4 18:59:42 UTC 2023 aarch64 Android
Device manufacturer:
Google
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
~/SubStack $
```

**Comment by finagolfin** [comment]
Press `Volume Up` and `Q` to hide those extra keys, as [documented on the wiki](https://wiki.termux.com/wiki/Touch_Keyboard), which is also accessible from the `Help` button if you long-press the app and choose `More...`.
