### ISSUE TITLE
[Bug]: pygame is not installing 

### ISSUE THREAD

**Issue by SHIRDI222** [termux/termux-app#4021]
### Problem description

pkg install pygame
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://md.mirrors.hacktegic.com/termux/termux-main: ok
Get:1 https://md.mirrors.hacktegic.com/termux/termux-main stable InRelease [14.0 kB]
Get:2 https://md.mirrors.hacktegic.com/termux/termux-main stable/main aarch64 Packages [511 kB]
Fetched 525 kB in 4s (127 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package pygame

### Steps to reproduce the behavior.

Try giving pkg install pygame 

### What is the expected behavior?

Pygame  and gTTS library is not installing 

### System information

* Termux application version: latest version 
* Android OS version: 13
* Device model: oppo f19 pro plus

**Comment by twaik** [comment]
```
pkg up
pkg i tur-repo
pkg up
pkg i python-pygame
```
