### ISSUE TITLE
[Bug]: Can't Install v0.118.1 on Android 11

### ISSUE THREAD

**Issue by mitexleo** [termux/termux-app#4023]
### Problem description

Install is failing for some reason. I tried both universal and arm64 releases. 

### Steps to reproduce the behavior.

Download the apk from GitHub Releases and Install.

### What is the expected behavior?

Installed successfully 

### System information

* Termux application version: 0.118.1
* Android OS version: 11
* Device model: SM-M40F

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

**Comment by mitexleo** [comment]
> https://github.com/termux/termux-app#Installation

It was a fresh install.

**Comment by mitexleo** [comment]
v0.118.0 is working fine ..

**Comment by agnostic-apollo** [comment]
No other reports have been received. Install with `adb` and you should be able to get exact error, `adb install -r termux.apk`.
