### ISSUE TITLE
[Bug]: Can't update Termux because Signature is different

### ISSUE THREAD

**Issue by superbonaci** [termux/termux-app#4027]
### Problem description

Termux version installed in my phone is:

```
Signer #1 certificate DN: CN=FDroid, OU=FDroid, O=fdroid.org, L=ORG, ST=ORG, C=UK
Signer #1 certificate SHA-256 digest: 228fb2cfe90831c1499ec3ccaf61e96e8e1ce70766b9474672ce427334d41c42
Signer #1 certificate SHA-1 digest: e8754a2c614392071d27021bbcdfb8dda7e0711c
Signer #1 certificate MD5 digest: bd0f4d846b76723a98d977339500fcf0
```

version I want termux-app_v0.118.0+57e4ef4-apt-android-7-github-debug_universal.apk

```
Signer #1 certificate DN: CN=APK Signer, OU=Earth, O=Earth
Signer #1 certificate SHA-256 digest: b6da01480eefd5fbf2cd3771b8d1021ec791304bdd6c4bf41d3faabad48ee5e1
Signer #1 certificate SHA-1 digest: 517955eabf69fc057c41c7d379dbbcef20ad85f2
Signer #1 certificate MD5 digest: 31d49355a0cb585498aab40be822c3be
```

Can somebody help upgrade the program?

### Steps to reproduce the behavior.

Download termux

### System information

* Termux application version: 0
* Android OS version: 0
* Device model: 0

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

**Comment by superbonaci** [comment]
F-Droid updated Termux to 0.118.1 so the update doesn't show anymore in Play Store.
