### ISSUE TITLE
[Bug]: v0.119.0-beta.1 termux-setup-storage Aborted error

### ISSUE THREAD

**Issue by username-is-not** [termux/termux-app#4030]
### Problem description

Running termux-setup-storage returns: Aborted

termux-app_v0.119.0-beta.1+apt-android-5-github-debug_arm64-v8a

### Steps to reproduce the behavior.

termux-setup-storage

### What is the expected behavior?

Storage setup launches, but nothing happens.

```
$ termux-setup-storage
Aborted
$ ls ~/storage/shared
ls: cannot access '/data/data/com.termux/files/home/storage/shared': No such file or directory
$
```

### System information

* Termux application version: termux-app_v0.119.0-beta.1+apt-android-5-github-debug_arm64-v8a
* Android OS version: 14, LineageOS 
* Device model: Xiaomi Poco F3 alioth, M2012K11AG

**Comment by username-is-not** [comment]
Note: it is NOT this issue, and termux-setup-storage works normally otherwise in previous Termux version, https://github.com/termux/termux-app/issues/3647

**Comment by agnostic-apollo** [comment]
>apt-android-5

Use `apt-android-7` on Android 14. Read the bolded instructions on release.

**Comment by username-is-not** [comment]
Apologies! TYVM
