### ISSUE TITLE
Issues after upgrading to 119-beta.1

### ISSUE THREAD

**Issue by angelog0** [termux/termux-app#4033]
### Problem description

Starting Termux after the upgrading prints `/data/.../profile.d/java.sh is a directory`. Indeed `java.sh` is a symlink to a folder: `$PREFIX/etc/alternatives/java-profile`

I upgraded from FDROID, exactly from this package: https://f-droid.org/repo/com.termux_1020.apk. 

Another issue is that I have lost some keys in the status bar: now after `ESC` key the keys `/` and `-` are substituted with a key which shows the `new session` menu and another key, a sort of UP/DOWN arrow, which does not seem to work or I do not understand its usefulness.

All this on a tablet with android-11 os.

On a phone with android 8, the same apk does not produce issues!

**Comment by angelog0** [comment]
How can I restore the lost keys?

**Comment by agnostic-apollo** [comment]
>Starting Termux after the upgrading prints /data/.../profile.d/java.sh is a directory. Indeed java.sh is a symlink to a folder: $PREFIX/etc/alternatives/java-profile

That should be reported in termux-packages repo, and best upgrade all packages first with `pkg upgrade` and check.

>a sort of UP/DOWN arrow

The default extra keys have been changed, you can change them.

Its meant to toggle autoscroll of command output.

https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by angelog0** [comment]
There are other issues with this release 119:

```
ls -lrt storage/downloads/
Permission denied!

ls -lrt /sdcard/Download/
Permission denied!
```

**Comment by angelog0** [comment]
Ho can I revert to 0.118?

**Comment by agnostic-apollo** [comment]
For android 11, disable storage permission and enable again in Termux app info in android settings, it's a bug in android.

F-Droid builds cannot be downgraded. For github builds, use `adb install -r -d termux.apk`.

**Comment by angelog0** [comment]
Thanks!
