### ISSUE TITLE
[Bug]: Version 0.119 beta 1 for Android 7+ no available in F-Droid

### ISSUE THREAD

**Issue by isrgish** [termux/termux-app#4036]
### Problem description

I just got a notification from F-Droid that there is an update to Termux. Going to F-Droid I see 2 new versions 0.118.1 which is available for Android 7+ and 0.119 beta 1 which is available for Android 5+ but not for 7+.
Why isn't it available for 7+?

I understand this has with F-Droid rather than Termux but since I have seen many times stated here to only download from "official" places which are git-hub and F-droid, that is why I'm asking this here.

### Steps to reproduce the behavior.

NA

### What is the expected behavior?

To have an update available for Android 7+

### System information

* Termux application version: Currently 0.118.1
* Android OS version: 13
* Device model: Phh-Treble GSI

Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=6359
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
# sources.list.d/game.list
deb https://packages.termux.org/apt/termux-games games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# sources.list.d/science.list
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
libdrm/stable 2.4.122 aarch64 [upgradable from: 2.4.121]
sensible-utils/stable 0.0.24 all [upgradable from: 0.0.23]
termux-tools version:
1.42.4
Android version:
13
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Fri Aug 18 23:04:47 CST 2023 aarch64 Android
Device manufacturer:
unknown
Device model:
Phh-Treble GSI
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.window versionCode:15
com.termux.widget versionCode:13
com.termux.api versionCode:51
com.termux.boot versionCode:8
com.termux.styling versionCode:32

**Comment by isrgish** [comment]
> All latest F-Droid versions are only compatible with Android `>= 7` (`apt.android-7`) variant. It showing up for Android 5 needs to be fixed.

That is why I was most surprised to see that the 0.119 version was only available for Android 5+.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/issues/4032#issuecomment-2186735787

**Comment by isrgish** [comment]
Let me try to clarify more.

I'm looking to install for Android 13 (which is 7+)
Looking at the information for the 0.119 beta 1 version it shows that it is for Android 5+. I was questioning why is this one available for Android 5+ and will I be losing any capabilities if I update with this version?

**Comment by agnostic-apollo** [comment]
F-Droid saying Android 5+ is dependent on minSdkVersion, and it will work for android 7-14. However, it should technically say 7+ instead of 5+ as app on F-Droid is not compatible with android 5/6. Check apks in release, F-Droid supplies the `termux-app_v0.119.0-beta.1+apt-android-7-github-debug_universal.apk` variant only.

https://github.com/termux/termux-app/releases/tag/v0.119.0-beta.1

**Comment by isrgish** [comment]
Thanks.
