### ISSUE TITLE
[Bug]: [Y/n] malfunction

### ISSUE THREAD

**Issue by ProCoder1199X** [termux/termux-app#4038]
### Problem description

While downloading packages or cloning github repositors, the termux app displays "continue?" and two options, [Y/n]
As we know, Y for YES and n for NO
But entering Y is aborting the process, functioning opposite.
But, pressing just "ENTER" button on keyboard, it works fine. 

### Steps to reproduce the behavior.

Fix the bug.

### What is the expected behavior?

While pressing Y, it should continue the process. 

### System information

* Termux application version: 0.117 (Latest)
* Android OS version: 12 
* Device model: Samsung Galaxy M11

**Comment by Biswa96** [comment]
> * Termux application version: 0.117 (Latest)

It isn't latest. Please follow the installation instruction from README file.
