### ISSUE TITLE
Accept user-trusted ca-certificates

### ISSUE THREAD

**Issue by aetherfaerber** [termux/termux-app#404]
Hi,

As the title already says: termux currently seems to ignore certificates imported via android system settings or e.g. cadroid. 

It would be nice if these could be used or other means were available inside termux to keep a repository of trusted certificates. Otherwise scripts can't connect to services on a server with a self-signed certificate using a secure connection.

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#1546
