### ISSUE TITLE
[Bug]: After update to 1.129, `<Ctrl>-<alt>-#` now covers the bottom half of the window with a box that just has "#" (such as "2"), for several seconds after each tab switch

### ISSUE THREAD

**Issue by SwuduSusuwu** [termux/termux-app#4042]
### Problem description

If you use tabs, this makes it almost impossible to use Termux,
because the huge box (which just has the number `#`) covers the bottom half the window (the most important space where you input text) for several seconds whenever you switch tabs.

### Steps to reproduce the behavior.

Launch Termux
Press `<Ctrl>+c` to spawn new tabs
Press `<Ctrl>+#` to switch to tab `#`

### What is the expected behavior?

Just as the old Termux, new Termux should show a small box with the number `#`.

### System information

```
~/SubStack $ termux-info
Termux Variables:
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=0.129
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
All packages up to date
termux-tools version:
3.0.7
Android version:
14
Device manufacturer:
Google
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
~/SubStack $
```

**Comment by SwuduSusuwu** [comment]
![Termux ctrl-alt-2](https://github.com/termux/termux-app/assets/168943815/f8dd9d3b-b1ac-4c0f-92bc-8889d15258d1)
How to have this small (or move to top)? If it was at the top, it would not cover the text input.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#google-play-store-experimental-branch

**Comment by fornwall** [comment]
@SwuduSusuwu This should be fixed in the `googleplay.2024.06.27` update that's out on Google Play - update to that!

And as seen in the link above, please report issues for Termux installed from Google Play [here](https://github.com/termux-play-store/termux-issues/issues/new/choose) for now.

**Comment by SwuduSusuwu** [comment]
https://github.com/termux-play-store/termux-issues/issues/27#issuecomment-2199531928 success
![Screenshot_20240701-024518](https://github.com/termux/termux-app/assets/168943815/9910d491-9fb5-4c74-9f3c-07f515dd015c)
