### ISSUE TITLE
Cannot bind netlink socket: Permission denied

### ISSUE THREAD

**Issue by meroitachi** [termux/termux-app#4048]
### Problem description
Hi,
I installed kali linux nthunter on termux But when trying to run any program in sudo su it shows me an error ('Netlink cannot bind socket: permission denied') / ('route_dst_netlink: AF_NETLINK cannot bind socket: permission denied'). My android version is 13. I have heard that every Android 13 based device is showing this error.Please help me to solve it🥲.

[Screenshot_2024-07-09-11-57-01-71_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-app/assets/91469640/726b8680-2e6e-41b0-8f44-7fb1ef4e5e35)

### System information

* Termux application version:  0.119.0-beta.1
* Android OS version: 13
* Device Name: Realme 9i
* Device model: RMX3491

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-community/blob/site/site/pages/en/rules/hacking.md
