### ISSUE TITLE
[REQ] Option to open a noprofile shell

### ISSUE THREAD

**Issue by RivenSkaye** [termux/termux-app#4051]
### Feature description

I'd like the more options context menu to include the option to open a clean shell that does not load the user profile or rc. Alternatively being able to run a oneshot command that bypasses these files from being loaded would be a great help.

### Additional information

Due to stupidity on my part, I've managed to end up with an unusable shell - a script from my dotfiles is being sourced which leaves the prompt command and pre-exec calling inexistent binaries, which in turn makes it so I can't run any command. Including the single command that'd fix my problem.

**Comment by Biswa96** [comment]
> I've managed to end up with an unusable shell - a script from my dotfiles

There is a failsafe mode which can be used to fix dotfiles https://wiki.termux.com/wiki/Recover_a_broken_environment

**Comment by RivenSkaye** [comment]
Oh wow, did not manage to find that wiki page myself. Thanks a lot, this saved my hide!
