### ISSUE TITLE
[Feature]: access /sdcard on a termux shell started with adb and run-as

### ISSUE THREAD

**Issue by masavini** [termux/termux-app#4052]
### Feature description

i can open a termux shell via adb using the following command:
```
cmd='export HOME=/data/data/com.termux/files/home; cd $HOME;'
cmd+=' export LANG=en_US.UTF-8;'
cmd+=' export PATH=/data/data/com.termux/files/usr/bin:$PATH;'
cmd+=' export PREFIX=/data/data/com.termux/files/usr;'
cmd+=' export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so;'
cmd+=' bash'

run-as com.termux files/usr/bin/bash -li -c "${cmd}"
```

it works fine with one exception: in this shell i am not able to access /sdcard (i can using the app). is this something that could be implemented?

### Additional information

i know i can open termux with ssh but sshd gets often killed by android scheduler and it's not doing well in my use case.

**Comment by agnostic-apollo** [comment]
sdcard access is not available on all Android versions with `run-as` and cannot be fixed by termux. You can start a `RUN_COMMAND` intent from `run-as` if you really need access.

https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent

**Comment by masavini** [comment]
thank you for your answer. is there any way to start an interactive shell with adb and `RUN.COMMAND` intent?
