### ISSUE TITLE
the command does not appear on the screen

### ISSUE THREAD

**Issue by IzdadTyz** [termux/termux-app#4054]
### Problem description

Uploading Screenrecording_20240720_153243.mp4…

when I enter the cd command, the command does not appear on the screen, if you want the cd command to appear you have to press the space key.

### Steps to reproduce the behavior.

open the app and type something

### System information

* Termux application version:version 0.119.0-beta.1
* Android OS version:android 14
* Device model:V2332

**Comment by liuzhongyi2** [comment]
Problems with Input Method, try another input method

**Comment by IzdadTyz** [comment]
https://github.com/user-attachments/assets/883c7060-a98b-46a0-af00-44a2bff3ad7b

**Comment by liuzhongyi2** [comment]
https://z.weixin.qq.com/
This is the IME I use now, but it seems to have only been developed for Chinese

**Comment by 2096779623** [comment]
> https://z.weixin.qq.com/ This is the IME I use now, but it seems to have only been developed for Chinese

Don't use that s**t IME.

**Comment by 2096779623** [comment]
This is usually because it turns on "word mode" by default. Switching to AlphaBet will not have this problem.

**Comment by liuzhongyi2** [comment]
> > https://z.weixin.qq.com/这是我现在使用的 IME，但它似乎只为中文开发
> 
> 不要使用那个 s**t IME。

那用什么输入法

**Comment by 2096779623** [comment]
> What input method do you use?

Use english in here.
Baidu, iFlytek, and Sogou are all OK. After the configuration is completed, it is best to disable the Internet access permission because they will upload privacy. The recommend one is fcitx5 on android.

**Comment by liuzhongyi2** [comment]
> > What input method do you use?
> 
> Use english in here. Baidu, iFlytek, and Sogou are all OK. After the configuration is completed, it is best to disable the Internet access permission because they will upload privacy. The recommend one is fcitx5 on android.

https://blog.utermux.dev
You wrote that?

**Comment by agnostic-apollo** [comment]
`enforce-char-based-input = true`

https://wiki.termux.com/wiki/Terminal_Settings#Workaround_issues_with_some_keyboards
