### ISSUE TITLE
[Bug]: ifconfig not work : ACCESS DENIED. 

### ISSUE THREAD

**Issue by C4ssif3r** [termux/termux-app#4069]
### Problem description

Why ???
I cant run "**ifconfig**" command 

It used to do this.

Error: ifconfig: No file /proc/net/dev: Permission denied

~$ which ifconfig
- Respond: /system/bin/ifconfig

But not work
How i can fix this ?? 

### Steps to reproduce the behavior.

**ifconfig** not work

Access Denied err. 

### System information

* Termux application version: google play 2024/07/07 
* Android OS version: 11
* Device model: poco m3 pro

**Comment by twaik** [comment]
Modern Android versions restrict access to subsystems used in `ifconfig`. Not going to be fixed. Still works with root.

**Comment by C4ssif3r** [comment]
Why closed ???

**Comment by twaik** [comment]
Because it is not going to be fixed.

**Comment by C4ssif3r** [comment]
In the previous versions of Thermox, this bug was used.

**Comment by twaik** [comment]
Again. Termux can not override system restrictions.
Also we do not process google play version issues. 
Report to https://github.com/termux-play-store.

**Comment by C4ssif3r** [comment]
Ok, no problem.

**Comment by RalfWerner** [comment]
to get wlan **IP** you can try:
```
[~]$ which ifconfig
/data/data/com.termux/files/usr/bin/ifconfig
[~]$ ls -l ../usr/bin/ifconfig
-rwx------ 1 u0_a245 u0_a245 52404 Jan 17  2024 ../usr/bin/ifconfig
[~]$ ifconfig
Warning: cannot open /proc/net/dev (Permission denied). Limited output.
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1  (UNSPEC)

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.3.0.245  netmask 255.255.252.0  broadcast 10.3.3.255
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)

```
or `/system/bin/ip a|grep wlan` or `termux-wifi-connectioninfo`, if **api** is installed.
