### ISSUE TITLE
Terminal doesnt work correctly with kingroot's su binary.

### ISSUE THREAD

**Issue by Harshiv-Patel** [termux/termux-app#407]
I have rooted device running Android Lollipop 5.1.1 rooted with Kingroot.
When I do `su` ( it sucks by the way, kingroot's `su` binary doesn't even have `--preserve-environment` option implemented.)  anyway, I do `su` and when I am done : `exit` the su'shell( `/system/bin/sh` I guess) , after that, Terminal stops printing characters that I type, output of other commands such as `ls` etc. work. But have to restart it in order to get normal behavior. I do not understand if it's because of crappy implementation of su or a bug in Termux or because of that android sh shell.

**Comment by sdrausty** [comment]
Try on an nonrooted device. Kingroot brought my 🐕 smartphone into live brickdom. https://sdrausty.github.io/pages/su

**Comment by Harshiv-Patel** [comment]
Thank you for sharing your experience.
 Perhaps I didn't describe my problem accurately:

The terminal Emulator can get the input and run appropriate command after existing the `su` shell. It just won't display whatever character I'm typing. Also echo doesn't work in that state too. it'll just display ">" until I do ctrl+c.
So I think there might be something to do the way Termux handles shell changes,  especially su<-->bash changes.

**Comment by KOLANICH** [comment]
You should never use kingroot. As far as I remember they were caugt on  doing mal9cious activity - sending device data to webservers in China. Taking in account that PRC is a totalitarian state and that enterprises there are actually ruled by the stzte, you should neither use this app nor advise anyone to do it.

**Comment by sdrausty** [comment]
@KOLANICH 
> Kingroot brought one of my 🐕 smartphones to live brickdom. https://sdrausty.github.io/pages/su

This version was installed from GPlaystore Gore. .

**Comment by Harshiv-Patel** [comment]
I'm closing this issue as I've switched to magisk.
