### ISSUE TITLE
[Bug]: crash report for termux app

### ISSUE THREAD

**Issue by itxmafiasana** [termux/termux-app#4073]
### Problem description

When I open Termux, a crash report notification appears, and then it doesn’t stay on; only show black screen and then it shuts down and goes back off. I am running this Termux app in BlueStacks.

Email:sanashamim891@gmail.com
![Capture](https://github.com/user-attachments/assets/edd2fff4-0f15-4b16-b1ad-7abd65e478f3)

### Steps to reproduce the behavior.

show the black screen and then it of.

### What is the expected behavior?

So that it gets fixed."

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by twaik** [comment]
We do not support emulator related issues except AVD. 
In most cases these virtual machines are not fully featured Android hosts, missing (or have broken) some (actually a lot of) Linux subsystems related stuff.

**Comment by agnostic-apollo** [comment]
In addition to what twaik said, are we supposed to guess why it crashed as you haven't posted the crash report text itself?

I suggest you also read https://github.com/termux/termux-community/blob/site/site/pages/en/rules/how-to-ask-report-and-request.md

**Comment by itxmafiasana** [comment]
I have told you everything I know; there's nothing more I have.
