### ISSUE TITLE
when I tried to run the utility through Termux, it asked me to download folium, pip/pip3 install folium. at the beginning everything went well until...

### ISSUE THREAD

**Issue by sxgphIre** [termux/termux-app#4074]
### Problem description

Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
        Building wheel for ninja (pyproject.toml): started
        Building wheel for ninja (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for ninja (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            /data/data/com.termux/files/usr/tmp/pip-build-env-cxz8dal4/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:312: UserWarning: git archive did not support describe output
              warnings.warn("git archive did not support describe output")
            /data/data/com.termux/files/usr/tmp/pip-build-env-cxz8dal4/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:331: UserWarning: unprocessed git archival found (no export subst applied)
              warnings.warn("unprocessed git archival found (no export subst applied)")
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-cxz8dal4/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 643, in setup
                cmkr = cmaker.CMaker(cmake_executable)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-cxz8dal4/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 145, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-cxz8dal4/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version
                raise SKBuildError(msg) from err

            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for ninja
      Failed to build patchelf ninja
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (patchelf, ninja)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Steps to reproduce the behavior.

I tried to write: pip install folium, nothing happened. I tried writing pip 3 versions, it didn’t help either.

### System information

* Termux application version:0.118.0
* Android OS version:14
* Device model:Redmi note 13

**Comment by Biswa96** [comment]
Try to install python-numpy package first.

**Comment by sxgphIre** [comment]
> Try to install python-numpy package first.
thank you so much!!! very helpful.

**Comment by sxgphIre** [comment]
Пенис

чт, 1 авг. 2024 г., 17:34 agnostic-apollo ***@***.***>:
