### ISSUE TITLE
[Feature]: Why termux do not support framebuffer?

### ISSUE THREAD

**Issue by yingshaoxo** [termux/termux-app#4078]
### Feature description

In a normal linux server, if we write rgb picture to a file called "/dev/fb0", the picture will show immediately in the screen.

That is how those desktop envinoment like x11 uses, they draw graphic to "/dev/fb0"

How hard it would be to simulate normal linux "/dev" folder behivior? (GooglePlay permission system is a trap, do not care it) (In "/dev" folder, we also can control usb, microphone, speaker directly)

### Additional information

No, just try to say a remand.

**Comment by twaik** [comment]
Android is not a "normal linux server". And it does not give access to /dev folder to regular apps. Termux is regular Android application and runs in regular Android application sandbox, it does not emulate anything. All programs running under termux are cross compiled and patched for running in this application sandbox, environment is not emulated.
Not going to be implemented.
