### ISSUE TITLE
[Feature]: is it possible to auto-start termux if i reboot the phone ? 

### ISSUE THREAD

**Issue by gokyuzugokturk** [termux/termux-app#4079]
### Feature description

I have to run Termux app if i reboot the phone.

Is it possible to auto-start Temux app if I reboot the phone ?

### Additional information

I have to run Termux app if i reboot the phone.

Is it possible to auto-start Temux app if I reboot the phone ?

**Comment by ChiefMikeK** [comment]
https://www.reddit.com/r/tasker/

**Comment by agnostic-apollo** [comment]
Use `termux-boot` to run commands at boot. You can even execute `$PREFIX/bin/login` with `RUN_COMMAND` intent from inside a boot script to start a login shell with required session action.

- https://github.com/termux/termux-boot
- https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#run_command-intent-command-extras
- https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#top-command-with-am-startservice-command
