### ISSUE TITLE
[Feature]: Follow GTK/Qt color scheme for frame and background and text

### ISSUE THREAD

**Issue by bphd** [termux/termux-app#4080]
### Feature description

Follow GTK/Qt color scheme for frame and background and text

### Additional information

Follow GTK/Qt color scheme for frame and background and text

**Comment by bphd** [comment]
@twaik What is invalid?

**Comment by twaik** [comment]
Invalid feature request...

**Comment by bphd** [comment]
What is invalid into it?

**Comment by twaik** [comment]
It is filed as feature request instead of bug report.
It does not have any information to be reproduced.

**Comment by bphd** [comment]
> 1. It should rather match theme of Android OS

Right
