### ISSUE TITLE
[Bug]: python virtualenv

### ISSUE THREAD

**Issue by user-11150** [termux/termux-app#4089]
### Problem description

python virtualenv cannot create in external storage

### Steps to reproduce the behavior.

Use virtualenv:
```
PermissionError: [Errno 1] Operation not permitted: '/data/data/com.termux/files/usr/bin/python3.11' -> '/storage/emulated/0/My_file/projects/puel/env/bin/python'
```

Use venv:
```
Error: [Errno 1] Operation not permitted: 'lib' -> '/storage/emulated/0/My_file/projects/puel/venv/lib64'
```

### What is the expected behavior?

Successful to create virtualenv

### System information

* Termux application version: 0.119.1
* Android OS version: 9
* Device model:

**Comment by twaik** [comment]
Do not try to put virtualenv or any executable code to sdcard. Sdcardfs has restrictions and does not allow executables or symlinks.

**Comment by user-11150** [comment]
Use conda?

**Comment by twaik** [comment]
It does not matter what you use to create virtualenv. Do not use sdcard or shared storage for this.

**Comment by user-11150** [comment]
Why I can run c extensions(like viztracer) in external storage

**Comment by twaik** [comment]
Scripts can be used. But not executables. 
I mean if you do something like `python3 ./somescript.py` it will run fine, but `./somescript.py` will not work. And many python stuff uses the latter option.

**Comment by user-11150** [comment]
Is not /bin/xxx external storage?

Why I can run like `/bin/ls`

**Comment by twaik** [comment]
/bin is a part of core OS.

**Comment by user-11150** [comment]
Is external storage just `/storage/emulated/0/` and SD cards?

**Comment by twaik** [comment]
You should not use anything under `/storage` and `/mnt`.

**Comment by user-11150** [comment]
Do you have VM can run tsu

**Comment by twaik** [comment]
Termux does not run in VMs properly. They do not have proper implementations for some subsystems required by Termux.

**Comment by user-11150** [comment]
Is kali not a VM?
