### ISSUE TITLE
Proot is giving errors in some devices ,  why ????

### ISSUE THREAD

**Issue by Hax4us** [termux/termux-app#409]
proot --link2symlink tar xvf filename.tar.gz 
It is giving error while extraction.... Why it is working properly in some devices and not in some devices..
Proot errors are different in different devices 👎
1.) proot error signal 7 
2) signal 11
3) etc....

**Comment by fornwall** [comment]
Could you report the issue against https://github.com/termux/proot, and write down more information in an issue created there:

- Which devices do you see the problem on?
- Which Android versions and ROM:s do they run?
