### ISSUE TITLE
[Bug]: completely disappears from apps

### ISSUE THREAD

**Issue by threefatkids** [termux/termux-app#4102]
### Problem description

restart phone app disappears but remains in app list 
![Screenshot_20240814-002121_Settings~2](https://github.com/user-attachments/assets/73beeed6-2868-4f50-9e69-841d1a6b5886)

### Steps to reproduce the behavior.

i use ashell you to kill terrmux and uninstall then im able to reinstall, issue happens upon reboot of phone. i looked for a reason or solution as to why unable to find one. so hopefully someone here knows.

### System information

* Termux application version: v0.118.1+ debug and or fdroid 
* Android OS version:
![Screenshot_20240814-002540_Settings](https://github.com/user-attachments/assets/c286c801-9972-4051-9e6b-57cd5d8a1a03)

* Device model: op8t

**Comment by agnostic-apollo** [comment]
Seems to be a oneplus issue, Termux has no control over it getting uninstalled. Check security/antivirus software in your phone, maybe that is causing it.

https://community.oneplus.com/thread/1107568

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/issues/4127#issuecomment-2313686228
