### ISSUE TITLE
SSH on 22 port

### ISSUE THREAD

**Issue by vovcacik** [termux/termux-app#411]
Hi,
how can I run `sshd` on port `22` instead of the default `8022`? I have tried and failed to use capabilities for this, see #410

**Comment by fornwall** [comment]
AFAIK it's not possible without root.

**Comment by Zach-15803** [comment]
Im guessing you would have to be rooted as @fornwall so rudely put it, and you would have to manually edit/tell it to use that port

**Comment by SarKaa** [comment]
Even with root, how would you do it

**Comment by xeffyr** [comment]
@SarKaa Set option `Port 22` in `$PREFIX/etc/ssh/sshd_config`. However running sshd as root is not recommended as we made it single-user only for compatibility with Android & non-rooted devices, privilege separation is broken.

**Comment by araczkowski** [comment]
there is other way -> iptables 
still only as root
```
su -c "/system/bin/iptables -t nat -A PREROUTING -p tcp --dport 22 -j REDIRECT --to-port 8022"
```
now you have ssh on 22 and 8022

**Comment by ibnusaja** [comment]
> there is other way -> iptables
> still only as root
> 
> ```
> su -c "/system/bin/iptables -t nat -A PREROUTING -p tcp --dport 22 -j REDIRECT --to-port 8022"
> ```
> 
> now you have ssh on 22 and 8022

Not working for me, only 8022 active
