### ISSUE TITLE
[Bug]: exec("/data/data/com.termux/files/usr/bin/login"): Permission denied  [Process completed (code 1) - press Enter]

### ISSUE THREAD

**Issue by samir717le** [termux/termux-app#4111]
### Problem description

hello dear sir i got a bug on termux first time my termux are not launching than i reinstall no it show
exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

i clear storage and allow storage access it not working 

### Steps to reproduce the behavior.

exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

### What is the expected behavior?

must open the terminal

### System information

* Termux application version: 0.118.0
* Android OS version: 10
* Device model: itel L6502

**Comment by samir717le** [comment]
no

**Comment by agnostic-apollo** [comment]
Generate an error report with debug info enabled and upload file here.

https://github.com/termux/termux-packages/blob/site/site/pages/en/projects/docs/repos/main/packages/termux-tools/logcat/index.md#to-get-logs-of-termux-apps

**Comment by samir717le** [comment]
i don't know how to do

**Comment by samir717le** [comment]
[termux-report_issue_from_transcript.log](https://github.com/user-attachments/files/16668598/termux-report_issue_from_transcript.log)
