### ISSUE TITLE
[Bug]: Termux cannot run

### ISSUE THREAD

**Issue by user-11150** [termux/termux-app#4112]
### Problem description

Termux does not function properly in small window

### Steps to reproduce the behavior.

Open termux in small window

### System information

* Termux application version:0.118.1
* Android OS version:14
* Device model:vivo Y100

**Comment by Grimler91** [comment]
> Termux does not function properly

In what way?

> Open termux in small window

How small?

Please share a screenshot or picture of the problem.

**Comment by user-11150** [comment]
https://github.com/user-attachments/assets/cbd84b53-a8fd-4254-ad28-8cd5fe88932d

**Comment by agnostic-apollo** [comment]
Try disabling margin adjustment in termux app settings and restart app.

**Comment by user-11150** [comment]
![Screenshot_20240819_152440](https://github.com/user-attachments/assets/76f5fe99-1520-4138-9ee7-4ea6208bac79)

where

**Comment by agnostic-apollo** [comment]
Maybe try going inside the menus...

**Comment by user-11150** [comment]
thanks
