### ISSUE TITLE
[Feature]: We need ARM

### ISSUE THREAD

**Issue by user-11150** [termux/termux-app#4116]
### Feature description

We need arm

### Additional information

Termux just support aarch64 now

**Comment by twaik** [comment]
Termux supports aarch64, armeabi-v7a, x86 and amd64. Why did you think arm is not supported?

**Comment by user-11150** [comment]
By default. Termux is aarch64

**Comment by user-11150** [comment]
How change to ARM

**Comment by user-11150** [comment]
How change to ARM

**Comment by twaik** [comment]
It is aarch64 if you are installing aarch64 version. Install the armeabi-v7a or universal apk.
![image](https://github.com/user-attachments/assets/b9b4f6bd-3fbe-49ee-b487-79f09f3bce6a)
