### ISSUE TITLE
[Bug]: pip doesn't work

### ISSUE THREAD

**Issue by user-11150** [termux/termux-app#4118]
### Problem description

Cannot upgrade pip

```console
ERROR: Installing pip is forbidden, this will break the python-pip package (termux).
```

### Steps to reproduce the behavior.

```shell
pip install --upgrade pip
```

### What is the expected behavior?

Don't fail

### System information

* Termux application version:0.118.1
* Android OS version:14
* Device model:vivo y100

**Comment by agnostic-apollo** [comment]
Run `pkg install python-pip`. `pip` is not allowed to upgrade itself in termux.

**Comment by user-11150** [comment]
Is I need use `ensurepip`?
