### ISSUE TITLE
[Feature]: Convert text navigation to arrow keys

### ISSUE THREAD

**Issue by MichaAI** [termux/termux-app#4124]
### Feature description

In gborard, you can navigate through the text using a special menu. It is also possible to navigate through the text by swiping the space bar. It would be nice if these movements through the text turned into pressing the arrow keys.
![Screenshot_2024_0826_222235](https://github.com/user-attachments/assets/e994edbb-039e-4f1c-a917-0df4b5d5b966)

### Additional information

-

**Comment by MichaAI** [comment]
> Terminal doesn't support such gestures as it is not a text field, characters are like pixels in an image, use text input view.
> 
> https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View

Termux doesn't even get a move attempt from gborard?

**Comment by agnostic-apollo** [comment]
No. Terminal input view uses a special input view for which the gboard keyboard does not show the toolbar that has the text editing button, nor does send space bar motion events. If terminal uses `InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_NORMAL`, then toolbar does show and editing works, but space bar movement still does not, but its not useful as extra keys already shows all the 4 dpad keys anyways and would be much faster, then switching to text editing view and back. You can use hackers keyboard if you want arrow keys inside the keyboard itself.

https://github.com/termux/termux-app/blob/v0.118.0/terminal-view/src/main/java/com/termux/view/TerminalView.java#L265-L283
