### ISSUE TITLE
Termux 'tsu' not work with Magisk 13.3

### ISSUE THREAD

**Issue by C4droid** [termux/termux-app#413]
I get root by Magisk(version 13.3).But when I type 'tsu', there is not any effect.

>I would say it's a termux issue, because "su" itself works fine.
And it definitely works with the "su" from termux not any other probably in path (dircetly called with "/data/data/com.termux/files/usr/bin/su".
But "tsu" searches for "su" only in two hardcoded paths ("/system/xbin/su" and "/su/bin/su") instead using its own su, which searches in "/system/xbin/su", "/system/bin/su", "/su/bin/su", "/sbin/su" and "/magisk/.core/bin/su".

**Comment by fornwall** [comment]
Report the issue against https://github.com/cswl/tsu (and look at the `tsu` script to investigate).
