### ISSUE TITLE
[Bug]: netstat: No file /proc/net/tcp: Permission denied

### ISSUE THREAD

**Issue by Sahil-pixel** [termux/termux-app#4138]
### Problem description

netstat: No file /proc/net/tcp: Permission denied

### Steps to reproduce the behavior.

netstat: No file /proc/net/tcp: Permission denied

### What is the expected behavior?

We should get normal output 

### System information

* Termux application version: Google.play.2024.07.07
* Android OS version:13
* Device model:Realme 8

**Comment by twaik** [comment]
Same problem as in #2993 .
