### ISSUE TITLE
Oreo issues with Termux, to mount /proc at book you need an /etc/fstab line

### ISSUE THREAD

**Issue by h6y3** [termux/termux-app#414]
I am using rvm and as part of its usage, it sources a script which calls ps.  It seems now every time the `ps` command is run we see this:

```
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like: 
       proc /proc proc defaults

In the meantime, run "mount  proc /proc -t proc"
```

Incidentally, I'm not sure if my /proc permissions are correct.  They are:

`dr-xr-xr-x`

**Comment by fornwall** [comment]
Closing this in favour of https://github.com/termux/termux-app/issues/299
