### ISSUE TITLE
Please add phantomjs for python webdriver

### ISSUE THREAD

**Issue by maddalakum** [termux/termux-app#415]
Hi Fedrik 
Could you please add phantomjs to termux packages 

I have installed kali linux in my mobile 

Below Link is arm architecture Working well and could you please add arch64 for that it will be very helpfull

Thanks in advance  

https://github.com/fg2it/phantomjs-on-raspberry/tree/master/rpi-1-2-3/wheezy-jessie/v2.1.1

**Comment by fornwall** [comment]
Thanks for the suggestion - you can track https://github.com/termux/termux-packages/issues/908 that already exists for phantomjs.
