### ISSUE TITLE
[Bug]: openjdk-21-jdk can't run minecraft server 1.21.1

### ISSUE THREAD

**Issue by Kydg08** [termux/termux-app#4162]
### Problem description

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=6642, tid=12408
#
# JRE version: OpenJDK Runtime Environment (21.0.4+7) (build 21.0.4+7-Ubuntu-1ubuntu222.04)
# Java VM: OpenJDK 64-Bit Server VM (21.0.4+7-Ubuntu-1ubuntu222.04, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
# Problematic frame:
# C  [spark-989754dbf99c-libasyncProfiler.so.tmp+0x24c74]  VMThread::nativeThreadId(JNIEnv_*, _jobject*)+0x5c
#
# Core dump will be written. Default location: core.6642 (may not exist)
#
# An error report file with more information is saved as:
# /root/hs_err_pid6642.log
[thread 12409 also had an error]
[thread 12348 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-21
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

### Steps to reproduce the behavior.

java -Xmx3G -Xms3G -jar server.jar nogui

### What is the expected behavior?

smooth run

### System information

* Termux application version: lastest version
* Android OS version:13
* Device model:ALLDOCUBE iplay50 mini

**Comment by twaik** [comment]
1. Termux does not offer openjdk in its repositories. 
2. Most likely you installed it inside proot-distro. We offer only proot-distro as an instrument for installing non-android distros, but we are not responsible for anything you run there.
3. You installed java from launchpad which is 3rd party source we offer zero support for.

**Comment by twaik** [comment]
Yeah, you are correct. I forgot to add version number to package name. My bad.
