### ISSUE TITLE
Root disabled for termux

### ISSUE THREAD

**Issue by mjain234** [termux/termux-app#4171]
### Problem description

Today, I was trying to install this command "apt install -y python-is-python3 python3-pip" and then faced an error "Unable to locate package python3" and after some research I found I have to run that command using "SUDO". But when I tried to run command using SUDO, it comes with this ![error](https://github.com/user-attachments/assets/22823047-73c5-4ae6-be6c-ee326f454e00). What should I do in such case?

### Steps to reproduce the behavior.

NIL

### What is the expected behavior?

NIL

### System information

* Termux application version: 0.118.1
* Android OS version: Android 14
* Device model: Nothing Phone 1 A063

**Comment by twaik** [comment]
Termux is not Ubuntu or Debian.
1. Do not use `sudo`. Termux is a single user environment, installing packages as root will break your termux system and not supported.
2. Install regular `python` and `python-pip` packages. 
3. Use `pkg` instead of `apt` please.

**Comment by mjain234** [comment]
![Screenshot_20240926-174950.png](https://github.com/user-attachments/assets/b526883c-4bab-498e-a785-8265e8eded0a)

Still says this error

**Comment by agnostic-apollo** [comment]
Neither of those packages are provided by termux, just install `python` and `python-pip` packages as already suggested.
