### ISSUE TITLE
[Bug]: "cp -a" fails on symbolic links

### ISSUE THREAD

**Issue by gerdolf** [termux/termux-app#4174]
### Problem description

'cp' with "-a" on a symbolic link gives:

cp: failed to restore the default file creation context: Permission denied

### Steps to reproduce the behavior.

$ ln -s x a
$ cp -a a b

### What is the expected behavior?

Should succeed

### System information

* Termux application version: coreutils/stable,now 9.5-2 aarch64
* Android OS version: 14
* Device model: Pixel Fold

**Comment by TomJo2000** [comment]
Yep, can replicate the issue on my end as well.

<h1><em></em></h1> 

This is a packaging issue, not an issue with the main Termux app.
Please transfer the issue to the termux-packages repo:
https://github.com/termux/termux-packages/issues/new/choose

**Comment by gerdolf** [comment]
Yes, sorry! But I don't know how to transfer it.
Can you do it?

**Comment by kyufie** [comment]
Ah, it seems my pr have caused some undesirable effects. I'll try to fix this.

**Comment by TomJo2000** [comment]
> Yes, sorry! But I don't know how to transfer it. Can you do it?

Sorry, should have just said "please open an issue on the packages repo".
I unfortunately don't have the option to take an issue from one repository and move it to another one.

**Comment by gerdolf** [comment]
OK, thanks anyway :)

**Comment by gerdolf** [comment]
Filed in termux-packages, will thus close this one here

**Comment by TomJo2000** [comment]
I'm gonna re-close this as "not planned".
Not in the sense that we're not going to fix it,
but in the sense that this is a package issue, not a App issue.
