### ISSUE TITLE
Launch any application

### ISSUE THREAD

**Issue by bit-garden** [termux/termux-app#418]
I'm currently looking for a way to arbitrarily launch android applications without having to open a file. For example, a game or settings. 

I found a few commands that should work, but one is hanging up the process. `PM` doesn't have list on android 7. It refers to using `cmd` but cmd isn't found. 

Ultimately I want something like `run Chrome` or `termux-open Chrome` without needing to supply a file or something to open it with.

**Comment by thewisenerd** [comment]
hello,

please have a look at https://github.com/termux/termux-app/issues/206 ; the comment by xelxebar should get you started on how to start activities.

**Comment by bit-garden** [comment]
Awesome. I hope that gets patched in officially. But it is enough to make my own for now. Thanks.
