### ISSUE TITLE
[Bug]: Termux su default PATH is incomplete

### ISSUE THREAD

**Issue by Xtr126** [termux/termux-app#4186]
### Problem description

Termux doesn't export paths like /system_ext/bin when running su. 
Although they are defined in https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/include/paths.h#50 
Some custom ROM includes binaries like htop in /system_ext/bin, in that case we have to run them with absolute path instead.
Thank you.

### Steps to reproduce the behavior.

Open termux app, run su command and try to run htop which is in /system_ext/bin/, it will fail saying that no command found.

### System information

* Termux application version: v0.119.0-beta.1
* Android OS version: 14

**Comment by agnostic-apollo** [comment]
Termux provided `su` is just a wrapper for `su` binary found in the system, it does not set up any environment. Use https://github.com/agnostic-apollo/sudo or install `tsu` package and they will set it up including `PATH` variable. `htop` is provided by termux `htop` package, so install it first. The `/system_ext/bin` path is not exported by either of them currently, but will be my mine in future, or you can run `sudo --export-paths=/system_ext/bin su` if you want that for now.

https://github.com/agnostic-apollo/sudo#path-and-ld_library_path-priorities

**Comment by Xtr126** [comment]
> Termux provided `su` is just a wrapper for `su` binary found in the system, it does not set up any environment. Use https://github.com/agnostic-apollo/sudo or install `tsu` package and they will set it up including `PATH` variable. `htop` is provided by termux `htop` package, so install it first. The `/system_ext/bin` path is not exported by either of them currently, but will be my mine in future, or you can run `sudo --export-paths=/system_ext/bin su` if you want that for now.
> 
> https://github.com/agnostic-apollo/sudo#path-and-ld_library_path-priorities

Well I saw that the wrapper does already set up the PATH environment https://github.com/termux/termux-tools/blob/57c4adf65069cf17567330d7c00adc5b98e15419/scripts/su.in#L9 so I asked.
Anyway thank you I will run `sudo --export-paths=/system_ext/bin su` it's just convenient to use the system binaries instead of installing tsu, htop everytime. 
For context it is in Bliss OS where they have Termux pre-installed to provide a root shell when su is executed.

**Comment by agnostic-apollo** [comment]
Welcome. Cool.
