### ISSUE TITLE
[Bug]: All `/proc/*/exe` became `/apex/com.android.runtime/bin/linker64` cause oh my tmux break after tmux 3.5 released

### ISSUE THREAD

**Issue by XyLyXyRR** [termux/termux-app#4188]
### Problem description

Recently tmux released 3.5 and `oh my tmux` broken.

gpakosz/.tmux#761

After some patches it's worked on my pc, but not my android.

gpakosz/.tmux#765

Our investigation found this and may need your help.
https://github.com/gpakosz/.tmux/issues/765#issuecomment-2396650934

### Steps to reproduce the behavior.

- install tmux & oh my tmux
- run `tmux new`
And then we noticed that oh my  tmux is not working.

### What is the expected behavior?

oh my tmux theme should working fine.

### System information

* Termux application version: Termux googleplay.2024.08.29
* Android OS version:Android REL 12 aarch64
* Device model: Xiaomi Redmi K30 5G

fastfetch output:

```
u0_a767@localhost
-----------------
OS: Android REL 12 aarch64
Host: Xiaomi Redmi K30 5G
Kernel: Linux 4.19.113-perf-ga1b60ef832fb
Uptime: 5 days, 18 hours, 54 mins
Packages: 132 (dpkg)
Shell: fish 3.7.1
WM: Window Manager
Terminal: Termux googleplay.2024.08.29
CPU: SM7250 (8) @ 2.40 GHz
Memory: 4.19 GiB / 7.25 GiB (58%)
Swap: 2.16 GiB / 6.00 GiB (36%)
Disk (/): 2.75 GiB / 3.01 GiB (91%) - ext4 [Read-only]
Disk (/storage/emulated): 77.97 GiB / 107.04 GiB (73%) - fuse
Local IP (tun0): 172.19.0.1/30
Local IP (wlan0): 192.168.123.5/24
Locale: en_US.UTF-8
```

**Comment by gpakosz** [comment]
The issue is that Oh my tmux! tries to locate the tmux program on the filesystem.
It does so by issuing a call to `readink /proc/$(tmux display -p '#{pid}')/exe` and the output is `/apex/com.android.runtime/bin/linker64` instead of `/data/data/com.termux/files/usr/bin/tmux`.

**Comment by fornwall** [comment]
Thanks for reporting! This issue is specific to Termux on Google Play (see https://github.com/termux-play-store) - moving the issue to https://github.com/termux-play-store/termux-issues/issues/149, will look at it later.
