### ISSUE TITLE
Does Termux encode the keyboard/console output as UTF-8 or latin? And how can I change this?

### ISSUE THREAD

**Issue by SparkyCola** [termux/termux-app#419]
When I type an Umlaut like ä,ö,ü Termux does display the right character in the console, emacs however will display the latin-1 encoding mistake, when setting to set-terminal-coding-system to utf-x which is really useful because I can use the full unicode. However since changing keyboard-coding-system in emacs does not resolve this issue, only setting the terminal-coding to latin-1 does, but then I don't have unicode.
So how do I set termux to uft-8, or is already in utf-8 and emacs is set up wrong (I checked emacs' encoding it's utf-16-unix)? I tried `export LANG=en_GB.UTF-8`, that didn't change anything.

**Comment by Grimler91** [comment]
Might not be a related issue, but this issue reminded me of https://github.com/termux/termux-packages/issues/1088.

This question might be better suited for the termux-packages repo.

**Comment by SparkyCola** [comment]
I changed the question to express what I think is probably the source of the actual issue.

**Comment by fornwall** [comment]
Termux uses utf-8 in the app, it really seems to be a problem with the emacs package - subscribe to https://github.com/termux/termux-packages/issues/1088 for that one!
