### ISSUE TITLE
Bootstrap over Tor fails due to Cloudflare captcha

### ISSUE THREAD

**Issue by infozsoda** [termux/termux-app#42]
It's not possible for the app to download the https://termux.net bootstrap zip over Tor (Orbot), because Cloudflare will serve a HTML page with a captcha instead of the zip file.

Maybe the zip files could be checked into a Github blob repository?

**Comment by fornwall** [comment]
I modified the cloudflare setting to lower the chance of getting a captcha page to the lowest possible. Does it work now or do you still get a captcha?

**Comment by infozsoda** [comment]
Now it works, thanks!
