### ISSUE TITLE
FTP Empty or not functioning. 

### ISSUE THREAD

**Issue by bit-garden** [termux/termux-app#420]
When running `tcpsvd -vE 0.0.0.0 8024 ftpd /sdcard` to attempt to start an ftp server, I cannot see, to connect from other devices or the host device. Am I missing a step?

In this example, I have used Midnight commander and X-plore and both show an empty folder with no ability to create or upload files. 

https://drive.google.com/open?id=0B_bkxTZXrpqwd19BalpaRGlyX0U

edit:
A screenshot of the info page. It looks like it is connecting, but has no permissions. 

https://drive.google.com/open?id=0B_bkxTZXrpqwUG5aUFlXY2NHcms

**Comment by Quasic** [comment]
To be able to create or modify files, you need the w switch: `tcpsvd -vE 0.0.0.0 8024 ftpd -w /sdcard`

**Comment by bit-garden** [comment]
I found the problem actually. The command to host the ftp server seems to ignore the path. When connecting, I have to specify /sdcard on the client.
