### ISSUE TITLE
[Bug]: Typing problem with Microsoft Swift Keyboard 

### ISSUE THREAD

**Issue by PrinceParshia** [termux/termux-app#4212]
### Problem description

I use Microsoft Swift Keyboard. With it in termux text doesn't echo. I thought it was my software problem. But when i changed my keyboard to Gboard text was entering normally 

### Steps to reproduce the behavior.

If u use Microsoft Swift Keyboard and getting the same problem, changing it maybe fix it. 

### System information

* Termux application version: 1.118.1

**Comment by rezainet** [comment]
I have this problem too.

**Comment by PrincParshia** [comment]
> I have this problem too.

If you have multiple languages installed in Microsoft SwiftKey, try deleting all of them except English. In the recent update, SwiftKey no longer allows you to turn languages off — you have to delete them instead. If that bothers you, you can use Google Keyboard instead, as it has a better system for managing languages.

I don't wanna explain the reason behind this, it's kinda complicated.
