### ISSUE TITLE
[Bug]: Failed to get bootstrap file

### ISSUE THREAD

**Issue by Gamerperson3419lol** [termux/termux-app#4227]
### Problem description
Not installing bootstrap
(https://github.com/user-attachments/files/17483803/crashlog.txt)

### Steps to reproduce the behavior.

Idk

### What is the expected behavior?

Saying it can't get bootstrap file

### System information

* Termux application version:v0.118.1
* Android OS version:11
* Device model:Fire HD 10(13th gen)

**Comment by agnostic-apollo** [comment]
>ls: /data/data/com.termux/files/usr: No such file or directory
>avc: denied { execute_no_trans } for path="/data/data/com.termux/files/usr/etc/termux/bootstrap/termux-bootstrap-second-stage.sh" dev="dm-4" ino=1526718 scontext=u:r:untrusted_app:s0:c11,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c11,c257,c512,c768 tclass=file permissive=0 app=com.termux

Uninstall all termux apps, then restart phone and then reinstall.

**Comment by Gamerperson3419lol** [comment]
> > ls: /data/data/com.termux/files/usr: No such file or directory
> > avc: denied { execute_no_trans } for path="/data/data/com.termux/files/usr/etc/termux/bootstrap/termux-bootstrap-second-stage.sh" dev="dm-4" ino=1526718 scontext=u:r:untrusted_app:s0:c11,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c11,c257,c512,c768 tclass=file permissive=0 app=com.termux
> 
> Uninstall all termux apps, then restart phone and then reinstall.

I did
