### ISSUE TITLE
[Bug]: Wording in the F-Droid section of the README is questionable

### ISSUE THREAD

**Issue by janexner** [termux/termux-app#4228]
### Problem description

The "F-Droid" section of the README.md file contains some language that could be seen as wrong or misleading. Specifically:

"Moreover, the Termux maintainers also do not have access to the APK signing keys of F-Droid releases, so we cannot release an APK ourselves on GitHub that would be compatible with F-Droid releases."

Building Termux as a "[Reproducible Build](https://f-droid.org/en/docs/Reproducible_Builds/)" would address that.

### Steps to reproduce the behavior.

N/A

### What is the expected behavior?

Language that lists the reason why builds are not compatible more along the lines of "Termux builds are currently not reproducible builds".

This language change could also apply in the "Installation" section, in the paragraph starting with "The APK files of different sources are signed with different signature keys."

### System information

N/A

**Comment by agnostic-apollo** [comment]
Seems pretty clear to me, as APKs with different signing keys are not compatible with each other, and GitHub and F-Droid keys are different and we don't have access to F-Droid keys, means we can't release compatible APKs ourselves for both.

Even if unsigned APKs are reproducible for both sources, app is not going to update on device unless signed with same key of current installation. And as soon as you sign, APK hashes change too.

**Comment by janexner** [comment]
You can publish builds on github that are signed with the same keys as those on F-Droid. I am doing that with my apps, and they can be upgraded interchangeably.

I thought that was the whole point of reproducible builds?

**Comment by janexner** [comment]
(I can totally understand why you wouldn't want to do that, btw. It is not the easiest thing to do. I just thought the phrasing in the README.md wasn't quite right.)

**Comment by agnostic-apollo** [comment]
F-Droid takes 5-7 days to build APKs after a release. APKs built on GitHub are immediately uploaded to release. There is no point in uploading F-Droid ones to GitHub as well, especially since they aren't compatible, different arch/apt variants are already confusing enough on github releases, uploading fdroid ones would cause even more confusion. F-Droid builds should be directly downloaded from F-Droid, not github, but we may host F-Droid APKs ourselves on our site, along with other builds in future. Reproducible builds are not the reason at all and is a separate thing completely.

**Comment by agnostic-apollo** [comment]
>You can publish builds on github that are signed with the same keys as those on F-Droid. 

Do you have a custom fdroid server?

**Comment by janexner** [comment]
Example https://github.com/janexner/FotoTimerAndroid

The setup is so that the F-Droid build system and my local Android Studio build APKs that are signed with the same keys. I then upload my APKs to github.

You can update from, say,  v1.0.1 loaded from github to v1.1.0 loaded from F-Droid and vice versa.

No custom F-Droid server, just their normal build process.

**Comment by janexner** [comment]
I didn't think so. I can see it build, and compare APKs and keys.

**Comment by janexner** [comment]
Just to clarify: I'm not saying you should go the reproducible build path. It is a PITA. No pressure from me there!

But the language in the README.md is technically not correct. It IS possible.

**Comment by janexner** [comment]
I think the different keys in your case is bcs when you originally published, you decided to NOT do reproducible builds, or maybe that wasn't even possible at that point.

I really do not mind the way you're doing it. Non-reproducible is so much easier. If I had known, I would not have down reproducible builds either :-)

**Comment by agnostic-apollo** [comment]
And even if we were to make reproducible builds possible, changing the key on F-Droid to ours would mean that all existing F-Droid users will need to uninstall all their Termux apps and that is not a possibility. Moreover, Termux is a complex app with multiple java and native libraries and if reproducible builds ever fail, updating on F-Droid would halt until that is fixed, assuming it can be fixed, going with that design is very risky.

**Comment by janexner** [comment]
Agreed.

My bug was not a feature request for reproducible builds. Only an update of the wording in the README.md.

**Comment by agnostic-apollo** [comment]
Yeah, I understand, but reproducible builds are not the reason signing keys are different. Playstore builds had their own key, we plan to publish release APKs with our custom key on our site as well, reproducible builds are not the reason for it, they are different because they are built in different build environments (where keys are also kept private) and different sources may have different features.

**Comment by janexner** [comment]
I beg to differ, but no worries.
