### ISSUE TITLE
[Bug]: Termux doesn't keep wavelock

### ISSUE THREAD

**Issue by Ottaviocr** [termux/termux-app#4235]
### Problem description

I have a Huawei Y5 2019 with Android 9 and the latest version of Termux from the Aurora Store ( a mirror of Google Store).

Despite the steps reproduced below, and after making sure powerlock is acquired, when I download a file with yt-dlp and I switch to another app, if I go back to Termux, 2 times out of three the Termux app is reset and I have to start the download again.

### Steps to reproduce the behavior.

 I have 

`termux-wave-lock`

in my .bashrc, this is supposed to activate wave.lock by default.

I excluded Termux from the automanaged apps in Battery > Power Settings.

I launch the download of a file, for example:

$ yt-dlp https://www.rts.ch/play/tv/12h45/video/12h45?urn=urn:rts:video:15250225

See problem above

### What is the expected behavior?

I expect to switch back to the app and see the progress of my download.

### System information

* Termux application version: 1.4.21
* Android OS version: 9
* Device model: HUAWEI AMN.LX9

**Comment by agnostic-apollo** [comment]
Wakelock will not prevent app getting killed. Not a Termux or Android issue if battery optimizations have been disabled. Likely huawei specific killer.

https://dontkillmyapp.com/huawei
