### ISSUE TITLE
[Question]: How to manually connect to networks in termux

### ISSUE THREAD

**Issue by mast3rz3ro** [termux/termux-app#4237]
### Problem description

Hi there,

I have tried `termux-enable-wifi` from `termux-api` but it's doesn't returns any output. The WiFi I'm trying to connect with are open network.

What do I'm missing here? Maybe Termux are missing the corresponding WiFi permissions?

### Steps to reproduce the behavior.

```Bash
~ $ sudo iw dev wlan0 link
 Not connected.
~ $ sudo iw dev wlan0 connect "ssid"
~ $ sudo iw dev wlan0 link
Connected to 00:00:00:00:00:00 (on wlan0)
	SSID: my-network
	freq: 2422.0
	RX: 480 bytes (4 packets)
	TX: 0 bytes (0 packets)
	signal: -83 dBm
	rx bitrate: 6.0 MBit/s
	tx bitrate: 130.0 MBit/s
~ $ ping github.com
ping: unknown host github.com
~ $ sudo iw dev wlan0 connect "ssid"
command failed: Operation already in progress (-114)
```

```Bash
~ $ wpa_cli
Interactive mode
Could not connect to wpa_supplicant: (nil) - re-trying
C^Z
```

### What is the expected behavior?

Getting connected to the network.

### System information

```Bash
Termux Variables:
unsupported
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.sunred.org/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirror.sunred.org/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://mirror.sunred.org/termux/termux-x11 x11 main
Updatable packages:
Running as root. Cannot check package updates.
termux-tools version:
1.42.4
Android version:
34
Kernel build information:
Linux localhost 4.14.336-perf-gbd8f1c4cdb06-dirty #2 SMP PREEMPT Tue Mar 12 13:01:34 UTC 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Unknown
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by mast3rz3ro** [comment]
> You need to manually set up networking using ip utility.

Trying to manually configure the routing didn't help.

```Bash
~ $ iw dev wlan0 link
Connected to 00:00:00:00:00:00 (on wlan0)
	SSID: my-network
	freq: 2422.0
	RX: 2584 bytes (25 packets)
	TX: 0 bytes (0 packets)
	signal: -76 dBm
	rx bitrate: 6.0 MBit/s
	tx bitrate: 78.0 MBit/s
~ $ ip r
~ $ ip n
~ $ sudo ip addr add 192.168.1.0/24 dev wlan0
~ $ sudo ip n add 192.168.1.1 dev wlan0 lladdr 00:00:00:00:00:00
~ $ ip n
192.168.1.1 dev wlan0 lladdr 00:00:00:00:00:00 PERMANENT
~ $ ip r
192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.6
~ $ ping github.com
ping: unknown host guthub.com
```

**Comment by mast3rz3ro** [comment]
I think the issue isn't about missing default routing or DNS configuration,
it's about getting the device first connect to the network.

When device is connected to the network via Settings:
```Bash
~ $ ip n
192.168.1.1 dev wlan0 lladdr 00:00:00:00:00:01 REACHABLE

~ $ ip r
192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.7

~ $ iw dev wlan0 link
Connected to 00:00:00:00:00:00 (on wlan0)
	SSID: my-network
	freq: 2422.0
	RX: 26207 bytes (288 packets)
	TX: 52892 bytes (297 packets)
	signal: -85 dBm
	rx bitrate: 7.2 MBit/s
	tx bitrate: 6.5 MBit/s

~ $ iw dev wlan0 info
Interface wlan0
	ifindex 32
	wdev 0x1
	addr 00:00:00:00:00:02
	ssid my-network
	type managed
	wiphy 0

~ $ ip addr show wlan0 info
32: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
    link/ether 00:00:00:00:00:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.7/24 brd 192.168.1.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::0000:0000:0000:0002/64 scope link 
       valid_lft forever preferred_lft forever
```

When device is connected to the network via `iw`:
```Bash
~ $ ip n

~ $ ip r

~ $ iw dev wlan0 info
Interface wlan0
	ifindex 32
	wdev 0x1
	addr 00:00:00:00:00:02
	ssid my-network
	type managed
	wiphy 0

~ $ iw dev wlan0 link
Connected to 00:00:00:00:00:00 (on wlan0)
	SSID: my-network
	freq: 2422.0
	RX: 428 bytes (5 packets)
	TX: 0 bytes (0 packets)
	signal: -86 dBm
	rx bitrate: 6.0 MBit/s
	tx bitrate: 130.0 MBit/s

~ $ ip addr show wlan0 info
32: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state DORMANT group default qlen 3000
    link/ether 00:00:00:00:00:02 brd ff:ff:ff:ff:ff:ff
```

Trying to add default route:
```Bash
~ $ sudo ip addr add 192.168.1.0/24 dev wlan0
~ $ ip r
192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.0
~$ ping 192.168.1.1
connect: Network is unreachable

~ $ sudo ip n add 192.168.1.1 dev wlan0 lladdr 00:00:00:00:00:01
~ $ ip n
192.168.1.1 dev wlan0 lladdr 00:00:00:00:00:01 PERMANENT
~$ ping 192.168.1.1
connect: Network is unreachable

~$ sudo ip r add 192.168.1.0/24 via 192.168.1.7 dev wlan0
RTNETLINK answers: Network is unreachable
~ $ ip r
192.168.1.0/24 dev wlan0 proto kernel scope link src 192.168.1.0
```

Please note that, connecting via `iw` indicates that device isn't connected to any networks.
 i.e when entering Wi-Fi settings the device appears to be not connected to target network or any other networks.

**Comment by mast3rz3ro** [comment]
> Try using other IP address. For example 192.168.1.7/24 from other outputs above.

I tried it but it's still produces the same issue:
```Bash
~ $ sudo ip addr add 192.168.1.12/24 dev wlan0
```

> suggests that 192.168.1.7 is IP address of your device, not of the router. Fix it and use default gateway config.

I'm not sure of this, but this is was the output when I have manually connected to the network via settings.

> You can try using Android cmd utility to connect to wifi under root shell

The service manager utility are working just fine, I can even connect to unsaved networks. I was about to mention `cmd wifi` in my next reply. I'm going to leave some links in this post, just for feature causes.

Resources:
https://stackoverflow.com/questions/8708886/connecting-to-wifi-using-adb-shell
https://github.com/steinwurf/adb-join-wifi
https://android.stackexchange.com/questions/200285/connecting-to-wifi-via-adb-shell
https://stackoverflow.com/questions/6461769/enable-disable-wifi-via-bash-scripting-on-android
https://github.com/mnalis/android-wifi-upgrade/issues/7
https://xdaforums.com/t/how-to-reload-wificonfigstore-xml.4545053/post-88082341
https://xdaforums.com/t/guide-how-to-configure-the-wifi-in-android-via-script.4548489/

**Comment by mast3rz3ro** [comment]
`ip addr show wlan0 info` is a typo correct one is: `ip addr show dev wlan0` please correct my quote so I can remove this line later.

Please note that, the previous output are manually organised by me and thus because `termux` output are getting mixed when it's copied directly also I had to sensor my devices addresses.

**Comment by mast3rz3ro** [comment]
Alright, I think it's time to close this issue, the system service CLI `cmd` is more than enough to manage the Wi-Fi settings within the `termux` shell.

Please feel free to add any notes.
Thanks you!

**Comment by bekialvpncesaro-ux** [comment]
El que visto
