### ISSUE TITLE
[Bug]: sd-card appears empty but contains files

### ISSUE THREAD

**Issue by ftirapelle** [termux/termux-app#4249]
### Problem description

Hi,

if I try to access to my SD-CARD this is empty even if it contains several files. Instead, I can browse the contents of the internal storage. 

~/storage $ ls -la
total 68
drwx------. 2 u0_a303 u0_a303 4096 Nov  9 20:33 .
drwx------. 5 u0_a303 u0_a303 4096 Nov  9 01:55 ..
lrwxrwxrwx. 1 u0_a303 u0_a303   34 Nov  9 20:33 audiobooks -> /storage/emulated/0/Audiobooks
lrwxrwxrwx. 1 u0_a303 u0_a303   26 Nov  9 20:33 dcim -> /storage/emulated/0/DCIM
lrwxrwxrwx. 1 u0_a303 u0_a303   34 Nov  9 20:33 documents -> /storage/emulated/0/Documents
lrwxrwxrwx. 1 u0_a303 u0_a303   30 Nov  9 20:33 downloads -> /storage/emulated/0/Download
lrwxrwxrwx. 1 u0_a303 u0_a303   54 Nov  9 20:33 external-0 -> /storage/emulated/0/Android/data/com.termux/files
lrwxrwxrwx. 1 u0_a303 u0_a303   50 Nov  9 20:33 external-1 -> /storage/6E3E-8BFE/Android/data/com.termux/files
lrwxrwxrwx. 1 u0_a303 u0_a303   46 Nov  9 20:33 media-0 -> /storage/emulated/0/Android/media/com.termux
lrwxrwxrwx. 1 u0_a303 u0_a303   46 Nov  9 20:33 media-1 -> /storage/6E3E-8BFE/Android/media/com.termux
lrwxrwxrwx. 1 u0_a303 u0_a303   30 Nov  9 20:33 movies -> /storage/emulated/0/Movies
lrwxrwxrwx. 1 u0_a303 u0_a303   30 Nov  9 20:33 music -> /storage/emulated/0/Music
lrwxrwxrwx. 1 u0_a303 u0_a303   30 Nov  9 20:33 pictures -> /storage/emulated/0/Pictures
lrwxrwxrwx. 1 u0_a303 u0_a303   30 Nov  9 20:33 podcasts -> /storage/emulated/0/Podcasts
lrwxrwxrwx. 1 u0_a303 u0_a303   22 Nov  9 20:33 shared -> /storage/emulated/0
~/storage $ cd external-1
~/storage/external-1 $ ls -la
total 0
~/storage $ cd dcim
~/storage/dcim $ ls -la
total 47328
drwxrwx---. 2 root everybody    4096 May 28  2023  Camera
drwxrwx---. 2 root everybody   20480 Nov  6 08:16  Screenshots
-rw-rw----. 1 root everybody 2789827 May 19  1975  m_1.jpg
-rw-rw----. 1 root everybody 4565142 May 19  1975  m_10.jpg
-rw-rw----. 1 root everybody 3097869 May 19  1975  m_11.jpg

Can you help me?
Thanks

### Steps to reproduce the behavior.

I have uninstalled and reinstalled the Termux application but the result is still the same.

### System information

* Termux application version: googleplay.2024.10.30
* Android OS version: 11
* Device model: Samsung A50

**Comment by twaik** [comment]
Issues of github version should be reported to the corresponding github repo. https://github.com/termux-play-store/termux-apps
