### ISSUE TITLE
What is the license of code under terminal-view and terminal-emulator?

### ISSUE THREAD

**Issue by MohammedKHC0** [termux/termux-app#4257]
I know that it uses jackpal's Terminal Emulator code which is licensed under apache 2.0, But what is the license for the modifications that termux has made to the code? Is it GPL Or Apache 2.0?

**Comment by MohammedKHC0** [comment]
I realized that I had send a feature request instead of opening a discussion, please forgive me :>

**Comment by TomJo2000** [comment]
The licensing is outlined in the [LICENSE.md](https://github.com/termux/termux-app/blob/master/LICENSE.md) file.

- The [`terminal-view`](https://github.com/termux/termux-app/tree/master/terminal-view) and [`terminal-emulator`](https://github.com/termux/termux-app/tree/master/terminal-emulator) directories, which contain some code initially from the jackpal terminal are licensed under Apache-2.0, like the original jackpal terminal.
- The rest of the code is licensed under GPL-3.0
- For exceptions see the [termux-shared](https://github.com/termux/termux-app/blob/master/termux-shared/LICENSE.md) license file.

**Comment by MohammedKHC0** [comment]
@TomJo2000 Thanks very much for that fast reply.

I don't mean to argue with your point, but the LICENSE.md file states that all code in the repository is licensed under GPL only.

> The termux/termux-app repository is released under GPLv3 only license.

After that It said there is exceptions to that, but didn't say that the code is licensed under Apache 2.0 it only said that the code uses code that is licensed under Apache 2.0

> Exceptions
> Terminal Emulator for Android code is used *which* is released under Apache 2.0 license. Check terminal-view and terminal-emulator libraries.

I believe that *which* refers to Terminal Emulator for Android license.

Can @agnostic-apollo clarify what exactly he meant, (because he was the person who wrote that file)?

**Comment by TomJo2000** [comment]
> I don't mean to argue with your point, but the LICENSE.md file states that all code in the repository is licensed under GPL only.

`GPL-3.0-only` here is in reference to the GPL licensed code being licensed under specifically the GNU Public License 3.0, not any hypothetical later version.
As opposed to GPL-3.0-or-later which would be GPL 3.0, or any later revisions of the GPL if such a revision were to be published in the future.

**Comment by agnostic-apollo** [comment]
The `only` refers to `GPL-3.0-only` as @TomJo2000 has said.

>I believe that which refers to Terminal Emulator for Android license.

Yes. Termux app uses  Terminal Emulator for Android. Original license of Terminal Emulator for Android is kept, we maintain a fork of it under termux-view and terminal-emulator.

License file will be updated to a new format in future so I will make it more clearer.
