### ISSUE TITLE
termux-clipboard-set/get does not work after Android Oreo upgrade

### ISSUE THREAD

**Issue by cscullion** [termux/termux-app#426]
After upgrading my Google Pixel C to Oreo, I found that termux-clipboard-set is not working.  I entered a command "cat file.txt | termux-clipboard-set", but got a line "cmd: Can't find service: activity", and needed Ctrl-C to get back to the shell prompt.  The clipboard did not get set.

I get the same result with termux-clipboard-get with known good text in the clipboard (via Android "copy" feature).

**Comment by fornwall** [comment]
Will look into it - subscribe to https://github.com/termux/termux-api/issues/105 to be notified of progress!
