### ISSUE TITLE
[Feature]: setting background in termux

### ISSUE THREAD

**Issue by melsiir** [termux/termux-app#4260]
### Feature description

Today while I was searching in Google For a way Sit a transparent background In termax I found  complicated Methods Involves termux api And as adviced by the publisher of the Answer It's quite resource Hungry and could drain battery So I keep searching  and I stumbled upon Reddit thread That's claim that There are application called termux monet a fork of termux application So for the first time I thought it will be a hoax And I'll give it a shot And it's honestly was a quiet impressive the a performance was very good and sleek And I was able to set the background To the termux Very simply it's even has material design. But the fork is seem To be deprecated  Unfortunately And have some small bugs here and there So I  suggest to the maintenancers of termux To try merge this Fork into termux In the next update and here some screenahot
![Screenshot_20241118-220924_TermuxMonet](https://github.com/user-attachments/assets/506efe44-c41a-4023-9e29-19bb4dd41cd7)
![Screenshot_20241118-214057_TermuxMonet](https://github.com/user-attachments/assets/256485d3-f9a9-4487-ad31-64745f510ec8)
![Screenshot_20241118-214048_TermuxMonet](https://github.com/user-attachments/assets/c62fc318-6f15-453d-b490-f19168b01e36)

### Additional information

Virtually every other terminal emulator have this feature like wizterm

**Comment by twaik** [comment]
`termux-monet` is 3rd party project we offer zero support for.
