### ISSUE TITLE
[Bug]: Nodejs Installation failed

### ISSUE THREAD

**Issue by JelLee11** [termux/termux-app#4270]
### Problem description

When installing nodejs, it failed dew to incompatible 

CANNOT LINK EXECUTABLE "node": library "libicui18n.so.75" not found: needed by main executable
dpkg: error processing package nodejs-lts (--configure):
 installed nodejs-lts package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 nodejs-lts
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

since termux provide 76.1 version of libicu

### Steps to reproduce the behavior.

Should uses libicu 75 to match Nodejs

### What is the expected behavior?

Complete installation for nodejs

### System information

* Termux application version: 0.118.1
* Android OS version: 13
* Device model: Infinix X6528

**Comment by TomJo2000** [comment]
That is expected since we just updated `libicu`.
The rebuild is already underway and will be finished shortly.
https://github.com/termux/termux-packages/commit/96d5d0a1a31db747b78867b2a023ba4aaea347f6
