### ISSUE TITLE
[Feature]: Will Termux be compatible with HarmonyOS 5.0

### ISSUE THREAD

**Issue by mscg-ssxd** [termux/termux-app#4277]
### Feature description

Will Termux be compatible with HarmonyOS 5.0

### Additional information

Will Termux be compatible with HarmonyOS 5.0

**Comment by finagolfin** [comment]
Technically, we could do it, as [the new Harmony OS 5 microkernel comes with support for running linux apps](https://www.usenix.org/conference/osdi24/presentation/chen-haibo), see the linked pdf for a bit more info. However, the other big issue is that we primarily support the Bionic C library and that isn't planned to be part of HOS5, as they are stopping Android support.
