### ISSUE TITLE
[Bug]: Termux itself crashes, when trying to build Rustic, from Crate

### ISSUE THREAD

**Issue by vmlemon** [termux/termux-app#4288]
### Problem description

Using Termux, from the Google Play Store, on a Samsung Galaxy S22, with additional testing, under BlueStacks, on Windows 11. Ubuntu 22.04.5 installed, from Andronix, in a chroot.

### Steps to reproduce the behavior.

Install Andronix, from Google Play Store, along with Termux. Use instructions, from Andronix app, to create a new Ubuntu instance installation script, and run in Termux. Install rustc-1.80, and cargo-1.80, from Termux/Ubuntu repositories, and try to run ```cargo install --debug rustic-rs --locked```, as mentioned in https://github.com/rustic-rs/rustic_core/issues/377.

Several hundred packages will compile, and install, but towards the end, Termux will exhaust memory, and eventually crash. I have tried several attempts to install this package, in debugging mode, including by SSHing into my phone, with OpenSSHD running inside Termux, directly running the command on the handset, with the screen unlocked, and with it unlocked, and also by testing Android, on BlueStacks, and can reliably reproduce the crash.

Attaching GZip-compressed Android crash report.
[Untitled.txt.gz](https://github.com/user-attachments/files/17995025/Untitled.txt.gz)

### What is the expected behavior?

I would expect that Termux wouldn't crash, in this scenario, despite having several GB of RAM to play with. 

### System information

* Termux application version: Termux 0.118.0 (Google Play Store)
* Android OS version: Android 14, Samsung OneUI 6.0 (```uname -a``` reports ```Linux localhost 5.10.177-android12-9-27763393-abS901BXXU8DXD6 rustic-rs/rustic#1 SMP PREEMPT Fri Apr 5 16:00:39 KST 2024 aarch64 aarch64 aarch64 GNU/Linux```)
* Device model:
Samsung Galaxy S22 (SM-S901B/DS), BlueStacks Player 5.21.630.1018 P64

**Comment by twaik** [comment]
Play store version issues must be reported to https://github.com/termux-play-store/ .
