### ISSUE TITLE
[Feature]: support fingerprint sensor in ssh-agent

### ISSUE THREAD

**Issue by finch71** [termux/termux-app#4289]
### Feature description

support fingerprint sensor in ssh-agent

### Additional information

https://support.termius.com/hc/en-us/articles/4402191210009-Biometric-Keys-Touch-ID-Face-ID-Windows-Hello-Keystore

**Comment by TomJo2000** [comment]
As far as I am able to tell there is no support for using a fingerprint sensor as a backing for a `*-sk` type SSH key in OpenSSH.

OpenSSH does support FIDO/U2F keys for the types `ed25519-sk` and `ecdsa-sk`[^1].
However these only provide authentication for FIPS 140-2[^2] compliant authenticators,
e.g Yubikey, etc.
Via either USB or NFC.
Fingerprint sensors found on smartphones do not meet these requirements and are as such not supported as authentication sources.

Adding support for fingerprint sensors would likely have to be handled on a per-device basis, is not within the scope of what the Termux project aims to provide, and potentially exposes users to additional security concerns when using FIDO/U2F based keys with Termux.

If you are able to use a regular `ed25519` or `ecdsa` key for use with termius, please do so.

[^1]: OpenSSH 8.2 Release notes: https://www.openssh.com/txt/release-8.2#:~:text=FIDO/U2F%20Support
[^2]: https://en.wikipedia.org/wiki/FIPS_140
