### ISSUE TITLE
Fatal issue

### ISSUE THREAD

**Issue by Shadowhack0419** [termux/termux-app#429]
when I login shell it keeps showing coreutils: invalid option -- 'l',and it just exit the app! How can I save this?

_Sent from my Mi 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fornwall** [comment]
When you are standing looking at the failed shell session:

1. Pull out the navigation drawer by swiping in your finger from the left.
2. Long press the `NEW SESSION` button.
3. Press the `FAILSAFE` button in the resulting dialog.

This leaves you with a basic session using the built-in Android shell. Try moving away your dotfiles (perhaps `./profile` or `/.bashrc`) and start up a new session!
