### ISSUE TITLE
No su program found

### ISSUE THREAD

**Issue by acrocephalus** [termux/termux-app#430]
Hi!
I have read in a previous post that updating and upgrading termux-tools should give me su access. I've done it but whenever I try to use su I get a program not found message. Can anyone help?
Thanks!

**Comment by Grimler91** [comment]
Could you link to where you read that? 

Termux can't provide a su binary in a package, it's impossible with androids security model.

**Comment by acrocephalus** [comment]
https://github.com/termux/termux-packages/issues/723

Maybe I need a rooted phone? I've also tried tsu but I don't seem to be
able to make it work.
Thanks!

**Comment by Grimler91** [comment]
Ah, no, sorry, you're correct, there's a su-file in termux-tools called su. However it is basically just a wrapper around a su binary that you have installed through other means, it won't give you superuser rights

**Comment by acrocephalus** [comment]
Is there a way to run a command with su? I'd like to run su nmap - sn to
scan a network and retrieve the hostnames.

**Comment by Grimler91** [comment]
@acrocephalus `nmap -sn` should work without su, all (almost?) termux binaries are set up to work without root.

**Comment by acrocephalus** [comment]
It works, but it requires su to retrieve the hostnames. I wonder if other
binaries require su for some options.
Thanks!

On 20 Sep 2017 21:23, "Henrik Grimler" <notifications@github.com> wrote:

@acrocephalus <https://github.com/acrocephalus> nmap -sn should work
without su, all (almost?) termux binaries are set up to work without root.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-app/issues/430#issuecomment-330954887>,
or mute the thread
