### ISSUE TITLE
[Bug]: Termux won't connect to the internet! 

### ISSUE THREAD

**Issue by LucaTorre2010** [termux/termux-app#4303]
### Problem description

https://github.com/user-attachments/assets/12705fd6-0718-4213-928d-45926c1353da

Termux (F-Droid) doesn't connect to the internet

### Steps to reproduce the behavior.

1. Uninstall Termux (F-Droid) and all related packages (Boot, Api, Float, Tasker and the other ones)
2. Install GitHub version (0.119. 0 Beta 1) and Termux:GUI
3. Uninstall both and reinstallo Termux from F-Droid and the related packages (the same ones that were uninstalled in the first step) 

### What is the expected behavior?

Termux working fine, with network and all. Without it, I can't install packages. 

### System information

* Termux application version: 0.118.1 F-Droid
* Android OS version: 15 (Rooted LineageOS 22)
* Device model: 2201117TG

**Comment by twaik** [comment]
Are you using VPN or something similar?

**Comment by TRA80r** [comment]
There is not much information to work with in the video. Run this and share the output.
```
curl -v ifconfig.me
```

**Comment by LucaTorre2010** [comment]
The dumbass I was, I accidentally turned off mobile data for termux (the data use option for the apps).

**Comment by TRA80r** [comment]
> The dumbass I was, I accidentally turned off mobile data for termux (the data use option for the apps).

So you're going to try to hack your neighbor's wifi now?
