### ISSUE TITLE
[Bug]: Termux SAF crashes for invalid UTF-8 filenames

### ISSUE THREAD

**Issue by Xtr126** [termux/termux-app#4314]
### Problem description

Somehow a file with a weird filename was made in termux /home when I was playing around with commands, and then whenever I tried to access /home from Android DocumentsUI or other file manager, Termux would crash and cannot access home directory.

### Steps to reproduce the behavior.

1. In Termux (bash)
```bash
touch ''$'\001\006\207''@'$'\220\302\a''@8'
```
2. Try to access Termux /home from DocumentsUI (Can't load content at the moment) and Termux app crashes 

### What is the expected behavior?

Termux should not crash but handle it gracefully.

### System information

* Termux application version: v0.119.0-beta.1

**Comment by agnostic-apollo** [comment]
This is expected due to android bug, should be fixed in 0.119.0 main release.

**Comment by Biswa96** [comment]
Out of curiosity, Which commit did fix it if you can remember? GitHub search did not work.

**Comment by agnostic-apollo** [comment]
Not pushed yet, my port of jdk filesystem libraries isn't complete yet.

**Comment by agnostic-apollo** [comment]
There are other issues open for this.
