### ISSUE TITLE
[Feature]: Make bash into "libbash.so"

### ISSUE THREAD

**Issue by 1q23lyc45** [termux/termux-app#4315]
### Feature description

Make bash so and use it to install bootstrap instead of the system's built-in /system/bin/sh.

Just for VMOS Pro compatibility. VMOS Pro 3.0.7's Android 9 VM is now perfect for Termux! However, the only bug is that bootstrap cannot be installed, and can only be restored from the backup usr directory of the real machine.

### Additional information

It doesn't affect apt's bash package, this so is just used to install bootstrap.
This allows you to use Termux directly in the latest version of VMOS Pro.

**Comment by 1q23lyc45** [comment]
I found that the reason is that VMOS's /system/bin/sh does not fully support if statements.

**Comment by twaik** [comment]
VMOS is not a real android device and it bash incompatibility is not the only problem of it. Not going to be implemented.

**Comment by TomJo2000** [comment]
Bash cannot be compiled into a shared object library.
You cannot make a "libbash.so"

**Comment by 1q23lyc45** [comment]
> VMOS is not a real android device and bash incompatibility is not the only problem of it. Not going to be implemented.

Now VMOS Pro has no bugs at all, except for the bug that I said that bootstrap doesn't install automatically.

APT, PKG, Python, OpenJDK can all be used.

**Comment by twaik** [comment]
> Now VMOS Pro has no bugs at all, except for the bug that I said that bootstrap doesn't install automatically.

Wrong. It is not compatible with termux by design. And running all executables with proot or proot-like software (I mean the part of VMOS) which makes these programs think they run as root user does not help with it.

**Comment by 1q23lyc45** [comment]
> > Now VMOS Pro has no bugs at all, except for the bug that I said that bootstrap doesn't install automatically.
> 
> Wrong. It is not compatible with termux by design. And running all executables with proot or proot-like software (I mean the part of VMOS) which makes these programs think they run as root user does not help with it.

Your knowledge is out of date.
VMOS Pro 3.0.7 has fixed this issue.

**Comment by TomJo2000** [comment]
In any case we offer no official support for VMOS and if their shell implementation is broken that is not a bug in Termux.

**Comment by twaik** [comment]
> Your knowledge is out of date.
> VMOS Pro 3.0.7 has fixed this issue.

It is not an issue. It is a restriction of a technology. They can not bypass host device's application sandbox. They can not manage uids, gids, selinux contexts or mountpoints, all of them work in `/data/data/<app_name>` and use proot or proot-like software to make underlying programs think they work on a real phone. 
**It can not be bypassed by design.**

There is no official support to any VM running on top of termux or other OS except AVD. Nor for vmos, nor for vphonegaga, nor for bluestacks. 
AVD is supported because it is created by Google and designed to be as close to real hardware as possible.

**Comment by 1q23lyc45** [comment]
OK
