### ISSUE TITLE
[Bug]: font is weird on fresh installs android 13

### ISSUE THREAD

**Issue by Electrenator** [termux/termux-app#4318]
### Problem description

The teminal choses a non-monospace font by default and renders it as a monospace one, making it all look weird. Have been having this problem since my phone updated to android 13 and reinstalling didn't seem to fix it.

![Screenshot_20241225-155018~2](https://github.com/user-attachments/assets/014660ca-d74c-4b04-a8b8-b7cd14beaf76)

### Steps to reproduce the behavior.

Install the latest stable release from F-droid and open the application.

### What is the expected behavior?

The terminal using a font my default that works with its monospace rendering 

### System information

* Termux application version: 0.118.1
* Android OS version: 13
* Device model: motorola edge 20 lite (XT2139-1)

**Comment by Biswa96** [comment]
That's default font. Please use termux styling to change font https://wiki.termux.com/wiki/Termux:Styling

**Comment by TomJo2000** [comment]
Termux just uses the system monospace font by default.
Most phones ship a broken monospace font.

**Comment by Electrenator** [comment]
> Termux just uses the system monospace font by default. Most phones ship a broken monospace font.

Ah, had no idea about that.



> That's default font. Please use termux styling to change font https://wiki.termux.com/wiki/Termux:Styling

Will go and try that

**Comment by Electrenator** [comment]
Indeed seems to indeed be fixed by [downloading a monospace font](https://fonts.google.com/?categoryFilters=Appearance:%2FMonospace%2FMonospace) and moving it to `~/.termux/font.ttf`. Interesting how system mono fonts are sometimes just shipped broken like that.
