### ISSUE TITLE
[Bug]: Failed to install bootstrap packages

### ISSUE THREAD

**Issue by natsie** [termux/termux-app#4323]
### Problem description

Good day, I recently installed Termux v0.118.1 however the app failed it's initial installation of bootstrap packages. Then I tried with v0.119.0-beta.1 and still, the same error occured.

I would really appreciate some assistance with this issue.

Thanks in advance.
PS: This Android device runs in a VM on an Android phone (if that helps).

## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxInstaller`  
**Report Timestamp**: `2024-12-24 06:34:43.719 UTC`  
##

## Termux Bootstrap Error

``````
(-1) Termux Bootstrap Second Stage Command:
Previous State: `Executing`
Current State: `Failed`

Stdout: -
Stderr: -
Exit Code: -

Error Code: `2`
Error Message:
```
Failed to execute "(-1) Termux Bootstrap Second Stage Command" app shell command
```

StackTraces:
```
java.io.IOException: Cannot run program "/data/data/com.termux/files/usr/etc/termux/bootstrap/termux-bootstrap-second-stage.sh" (in directory "/data/data/com.termux/files/home"): error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
at java.lang.Runtime.exec(Runtime.java:691)
at com.termux.shared.shell.command.runner.app.AppShell.execute(AppShell.java:131)
at com.termux.app.TermuxInstaller$1.run(TermuxInstaller.java:231)
Caused by: java.io.IOException: error=2, No such file or directory
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
at java.lang.ProcessImpl.start(ProcessImpl.java:128)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
... 3 more

```

``````

## Termux Files Info

**TERMUX_REQUIRED_FILES_DIR_PATH ($PREFIX)**: `/data/data/com.termux/files`  
**ANDROID_ASSIGNED_FILES_DIR_PATH**: `/data/user/0/com.termux/files`  

```
$ echo 'ls info:'
/system/bin/ls -lhdZ '/data/data' '/data/user/0' '/data/data/com.termux' '/data/user/0/com.termux' '/data/data/com.termux/files' '/data/user/0/com.termux/files' '/data/user/0/com.termux/files' '/data/user/com.termux/files' '/data/data/com.termux/files/usr-staging' '/data/data/com.termux/files/usr' '/data/data/com.termux/files/home' '/data/data/com.termux/files/usr/bin/login' 2>&1
echo; echo 'mount info:'
/system/bin/grep -E '( /data )|( /data/data )|( /data/user/[0-9]+ )' /proc/self/mountinfo 2>&1 | /system/bin/grep -v '/data_mirror' 2>&1


exit code: 139
```
##

## Logcat Dump

```
$ /system/bin/logcat -d -t 3000 2>&1

exit code: 139
```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.119.0-beta.1`  
**VERSION_CODE**: `1020`  
**UID**: `10053`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**SE_PROCESS_CONTEXT**: -  
**SE_FILE_CONTEXT**: -  
**SE_INFO**: `default`  
**TERMUX_APP_PACKAGE_MANAGER**: `APT`  
**TERMUX_APP_PACKAGE_VARIANT**: `APT_ANDROID_7`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

## Termux:Styling App Info

**APP_NAME**: `Termux:Styling`  
**PACKAGE_NAME**: `com.termux.styling`  
**VERSION_NAME**: `0.32.1`  
**VERSION_CODE**: `1000`  
**UID**: `10053`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**SE_PROCESS_CONTEXT**: -  
**SE_FILE_CONTEXT**: -  
**SE_INFO**: `default`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.9.117+`  
**SDK_INT**: `25`  
**RELEASE**: `7.1.2`  
**ID**: `RQ3A.211001.001`  
**DISPLAY**: `RQ3A.211001.001 release-keys`  
**INCREMENTAL**: `eng.virtua.20241121.033248`  
**SECURITY_PATCH**: `2017-10-01`  
**IS_DEBUGGABLE**: `0`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `Google`  
**BRAND**: `google`  
**MODEL**: `Pixel 4`  
**PRODUCT**: `marlin`  
**BOARD**: `smdk6400`  
**HARDWARE**: `smdk6400`  
**DEVICE**: `marlin`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

Install Termux from FDroid on Android 7.

### System information

* Termux application version: v0.118.1 and v0.119.0-beta.1
* Android OS version: Android 7.1.2
* Device model: Google Pixel 4 (VM on Tecno Camon 12)

**Comment by twaik** [comment]
We do not support virtual machine setup on PC or other android phones (except AVD).


About Android VMs running on top of Android.
These environments are not supported by Termux. They are not true Android OS VMs like they claim, but rather container with highly modified Android versions with proprietary nature, which makes it impossible to support. Furthermore, issue with VMOS and F1VM look like rather their flaw because they could not properly manage emulated UIDs.

If you decided to use it, please report issues to their support and not here.

**Comment by hercules9x** [comment]
Don't message me again

**Comment by twaik** [comment]
Unsubscribe...

**Comment by natsie** [comment]
> We do not support virtual machine setup on PC or other android phones (except AVD).
> 
> About Android VMs running on top of Android. These environments are not supported by Termux. They are not true Android OS VMs like they claim, but rather container with highly modified Android versions with proprietary nature, which makes it impossible to support. Furthermore, issue with VMOS and F1VM look like rather their flaw because they could not properly manage emulated UIDs.
> 
> If you decided to use it, please report issues to their support and not here.

I guess less than 300mb to download a ROM was a bit suspicious, and I've also observed issues with the "VM" and other apps. I'll probably just run Termux directly on the main device (outside the VM). Anyway, I really appreciate your explanation.
