### ISSUE TITLE
SDcard

### ISSUE THREAD

**Issue by octavo** [termux/termux-app#4325]
The user would like access to the internal sdcard.

**Comment by twaik** [comment]
`termux-setup-storage`.

**Comment by octavo** [comment]
> `termux-setup-storage`.

It doesn't setup the sdcard.

**Comment by twaik** [comment]
There is no such thing as "internal sdcard". Sdcard is removable by definition and can not be "internal".
Probably you mean "internal storage" and it is being linked by `termux-setup-storage`.

**Comment by octavo** [comment]
The internal sdcard is the sdcard in the sdcard slot next to the sim.

**Comment by twaik** [comment]
Removable = external.

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app/issues/71#issuecomment-1869222653

**Comment by octavo** [comment]
The user found the sdcard /storage/0000-0000/.
