### ISSUE TITLE
allow termux to access to microphone

### ISSUE THREAD

**Issue by juha-h** [termux/termux-app#435]
I had to add 

`<uses-permission` android:name="android.permission.RECORD_AUDIO" />

to manifest in order to make baresip (https://github.com/alfredh/baresip-android) cli based SIP client audio to work both ways.
Without the line, I got error
audio: start_source failed (.): No such device
and baresip was not able to record audio.
Would it be possible to add the line also to official termux-app?
-- Juha

**Comment by sdrausty** [comment]
👍☺♣♦❤♠☀😀👈

**Comment by its-pointless** [comment]
that permission is in termux-api. Is that not enough?

**Comment by juha-h** [comment]
I don't know about termux-api.  I'm running baresip from termux console.  After I added RECORD_AUDIO permission to termux-app AndroidManifest.xml, Microphone appeared in Termux App permissions.  Then I activated the Microphone permission and baresip audio started to work both ways (recording and play).  Without that baresip didn't get access to audio source.

**Comment by Quasic** [comment]
I think many users would prefer to leave that permission in termux-api to keep the number of permissions the main app uses to a minimum. Microphone is one people question more.

**Comment by juha-h** [comment]
Quasic writes:

> I think many users would prefer to leave that permission in termux-api
> to keep the number of permissions the main app uses to a
> minimum. Microphone is one people question more.

It should be OK, since I had to explicitly turn the microphone
permission on,  It was not on by default after installation.

-- Juha

**Comment by Grimler91** [comment]
@juha-h have you installed the app "termux-api"? Try installing it instead of adding the microphone permission to termux-app

**Comment by juha-h** [comment]
Henrik Grimler writes:

> @juha-h have you installed the app "termux-api"? Try installing it
> instead of adding the microphone permission to termux-app

Thanks, I got it.  Installed termux-api from Play store and turned on
for it microphone permission.  Then I gave command

apt install termux-api

After that I stared baresip, which now was able to access microphone.

I'll clean the git entries that I created.

-- Juha

**Comment by juha-h** [comment]
See last comment from juha-h.
