### ISSUE TITLE
Nmap run error

### ISSUE THREAD

**Issue by wangmu0579** [termux/termux-app#437]

**Comment by wangmu0579** [comment]
Nmap can execute termux but  will failed with Root privilege

nmap -sP 192.168.1.1

Starting Nmap 7.60 ( https://nmap.org ) at 2017-09-25 21:54 CST
Nmap scan report for 192.168.1.1
Host is up (0.0038s latency).
Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds
 ~  nmap -sO 192.168.1.1
You requested a scan type which requires root privileges.
QUITTING!
 
Nmap run error on  termux-feroda
termux@fedora sslstrip]$ nmap -sP 192.168.1.1

Starting Nmap 7.40 ( https://nmap.org ) at 2017-09-25 12:58 UTC
nmap: netutil.cc:3285: int route_dst_netlink(const sockaddr_storage*, route_nfo*, const char*, const sockaddr_storage*): Assertion `p != NULL' failed.
Aborted

Any solution?

**Comment by fornwall** [comment]
I think the best way forward is asking for help on a nmap forum!

**Comment by johnnyboy1988** [comment]
I have the same error, on Gnuroot (debian).. I can't solve this
