### ISSUE TITLE
Allow other apps to run programs within termux

### ISSUE THREAD

**Issue by ShadowJonathan** [termux/termux-app#440]
I am currently making an app that splits the processing between termux and itself, termux for the background capabilities and "native" linux filesystem, and app for a customised view and JS interface.

I was about to test my app, by sending an Intent to termux's Service, which i noticed, and studied, till i got an uncaught JS-java error, and looking into logcat, i got this stack trace:

```
java.lang.SecurityException: Not allowed to start service Intent { act=com.termux.service_execute dat=com.termux.file:/data/data/com.termux/files/usr/bin/node cmp=com.termux/.app.TermuxService launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) } without permission not exported from uid 10205
     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1434)
     at android.app.ContextImpl.startService(ContextImpl.java:1387)
     at android.content.ContextWrapper.startService(ContextWrapper.java:656)
     at com.github.shadowjonathan.automatia.MainActivity.launchRobot(MainActivity.java:107)
     at com.github.shadowjonathan.automatia.MainActivity$WebAppInterface.StartRobot(MainActivity.java:82)
     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:154)
     at android.os.HandlerThread.run(HandlerThread.java:61)
```

`Not allowed to start service Intent ... without permission not exported from uid 10205`

Does this mean that script starting is not implemented, not allowed due to security reasons, or something else?

It is no problem to prompt the user to launch the robot manually, but i like simplicity, and most of the users wont be terminal-heads, and this seemed a very good solution.

(launching code)
```java
    public void launchRobot() {
        File file = new File("/data/data/com.termux/files/usr/bin/node");
        Uri scriptUri = new Uri.Builder().scheme("com.termux.file").path(file.getAbsolutePath()).build();

        Intent executeIntent = new Intent(ACTION_EXECUTE, scriptUri);
        executeIntent.setClassName("com.termux", TERMUX_SERVICE);
        executeIntent.putExtra(EXTRA_EXECUTE_IN_BACKGROUND, true);
        executeIntent.putExtra(EXTRA_CURRENT_WORKING_DIRECTORY, "/data/data/com.termux/files/home/robot/");
        executeIntent.putExtra(EXTRA_ARGUMENTS, new String[]{"main.js"});

        Intent wakeLockIntent = new Intent("com.termux.service_wake_lock");
        wakeLockIntent.setClassName("com.termux", TERMUX_SERVICE);

        startService(executeIntent);
        startService(wakeLockIntent);
    }
```

(possible duplicate of #371)

**Comment by ShadowJonathan** [comment]
Looking more into this, i can see how some apps can run malicious scripts and binaries, so if this indeed is a security issue, maybe the other app needs to request special permission from termux to run apps, which requires a user prompt agreement, and then the app is allowed to run services, unless the user revokes that permission.

I don't see a problem with this.

**Comment by lukeeey** [comment]
It would be nice to have this for compiler and IDE apps too.

**Comment by ShadowJonathan** [comment]
Issue #302 seems to have this same idea, btw

**Comment by lukeeey** [comment]
I know but still. @fornwall never seems to reply anyway so why does it matter.

**Comment by Quasic** [comment]
There are Termux add-ons for specific cases (see #236)

**Comment by xeffyr** [comment]
Closing in favor of https://github.com/termux/termux-app/issues/804.
