### ISSUE TITLE
Pkg install 

### ISSUE THREAD

**Issue by unsuccesssss** [termux/termux-app#441]
Pls help me.

**Comment by unsuccesssss** [comment]
$ pkg install phython2
Get:1 http://termux.net stable InRelease [1687 B]
Get:2 http://termux.net stable/main all Packages [4308 B]
Get:3 http://termux.net stable/main arm Packages [57.9 kB]
Fetched 63.9 kB in 1s (58.3 kB/s)
Reading package lists... Done
Building dependency tree... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package phython2
$

**Comment by sdrausty** [comment]
https://wiki.termux.com/wiki/Pkg
