### ISSUE TITLE
Fails to install scikit learn

### ISSUE THREAD

**Issue by Fahim-Ferdous** [termux/termux-app#443]
Hi there, I was trying to install scikit learn, but can't. I tried changing the compilers by every solutions I could find online but nothing helps.
Error:
error: Command "aarch64-linux-android-clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Oz -Oz -fPIC -I/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.13.1-py3.6-linux-aarch64.egg/numpy/core/include -c sklearn/svm/src/libsvm/libsvm_template.cpp -o build/temp.linux-aarch64-3.6/sklearn/svm/src/libsvm/libsvm_template.o -MMD -MF build/temp.linux-aarch64-3.6/sklearn/svm/src/libsvm/libsvm_template.o.d" failed with exit status 127

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-xapcx9ye/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-bvt23boh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-xapcx9ye/scikit-learn/

**Comment by fornwall** [comment]
I'm closing this in favour of continued discussion in https://github.com/termux/termux-packages/issues/1618
