### ISSUE TITLE
Permision denied after editing a file over root/adb

### ISSUE THREAD

**Issue by Mannshoch** [termux/termux-app#445]
If I transfer Files with ADB or open a file as root. The files change their Owner to  root:sdcard_rw
even i change User with `chown` termux get a permission denied. I tried it with `restorecon` ( #198 ) but was also not able to get access.

**Comment by xeffyr** [comment]
1. Get user id of Termux app:
```
id -u
```
2. Change owner of file (replace {id} with id got in previous step):
```
chown {id}:{id} filename
```
3. Set permissions (i guess that this may be not necessary):
```
chmod 600 filename
```

After this your file should be accessible from termux without root, if not, you can try restorecon.
