### ISSUE TITLE
"Method https has died unexpectedly" on Acer Chromebook R11

### ISSUE THREAD

**Issue by valmar** [termux/termux-app#447]
After I have been installing a few packages, every time I perform a pkg operation on my Chromebook R11 I get this error.

For example:

$ pkg update
Get:1 http://termux.net stable InRelease [1687 B]
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received a segmentation fault

If I uninstall and install Termux again the error disappears (although of course this resets the environment)

**Comment by fornwall** [comment]
What is the output of `uname -m`?

> Sub-process https received a segmentation fault

If so, could you try disable all https repos, run `pkg update` once to receive the latest updates, and then enable the https repos again and see if that improves things?

**Comment by valmar** [comment]
Thank you for the very quick answer.

The result of uname -m is:

$ uname -m
i686

I removed all https from the apt entries and I still get the error. However, if I comment out the its-pointless repo, the error disappears. So it could be related to the its-pointless extra repo and its availability.

Is the main termux repo in sources.list supposed to be used with http or with https?

**Comment by its-pointless** [comment]
Its because my repo doesn't have an "all" section.

**Comment by valmar** [comment]
Thanks its-pointless. It's there a workaround? I *depend* on your work now.... :-)

Seriously, thank you all for all your work

**Comment by its-pointless** [comment]
i will sort it out tommorow.

**Comment by valmar** [comment]
Thank you so much! 

Valerio

**Comment by valmar** [comment]
@its-pointless Please do not think that I am pushy, but are there any news about this bug? I am still getting the error....

**Comment by its-pointless** [comment]
I honestly have no idea. I can't reproduce it.

**Comment by its-pointless** [comment]
Wait i just had an idea.  i will upload a newer version of apt see if it fails or i might even have to ask you to use gdb. Brb

**Comment by valmar** [comment]
Sure, no problem. I am a scientific software developer so gdb does not
scare me.

Just be aware that I don't have the Chromebook with me here at work and I
can only test stuff in the evening...

Thanks for all your help

Valerio

**Comment by its-pointless** [comment]
https://github.com/its-pointless/its-pointless.github.io/raw/master/apt_1.4.7_i686.deb
Test that and if that doesn't work
https://github.com/its-pointless/its-pointless.github.io/raw/master/apt_1.5_i686.deb

**Comment by valmar** [comment]
@its-pointless 

I tried both. 1.4.7 gives me the same error

1.5 does not seem to link to the correct libraries: I get this error:

CANNOT LINK EXECUTABLE: library "libgnutls.so" not found
page record for 0xf06d604c was not found (block_size=64)
CANNOT LINK EXECUTABLE: library "libgnutls.so" not found
page record for 0xe9a1204c was not found (block_size=64)
Reading package lists... Done
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (1)
E: Method /data/data/com.termux/files/usr/lib/apt/methods/http did not start correctly
E: Method https has died unexpectedly!
E: Sub-process https returned an error code (1)
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch http://termux.net/dists/stable/InRelease
E: Failed to fetch https://its-pointless.github.io/files/dists/termux/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.

I stand available for further tests....

Thank you again for your help!

**Comment by its-pointless** [comment]
try installing libgnutls so apt 1.5 works. Using a different encryption library may fix it.

**Comment by valmar** [comment]
Ok I will. Where can I find the repo, to download the packages?

**Comment by valmar** [comment]
Never mind, I figured out how to install gnutls.

As you expected, this fixed the problem and I don't get any more segfault error. However, no key for any repository seems to be available:

pkg update
Hit:1 http://termux.net stable InRelease
Get:2 https://its-pointless.github.io/files termux InRelease [2058 B]
Err:1 http://termux.net stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6700B77E6D8D0AE7
Ign:2 https://its-pointless.github.io/files termux InRelease
Fetched 2058 B in 0s (3059 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://termux.net stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6700B77E6D8D0AE7
W: GPG error: https://its-pointless.github.io/files termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 906F5AFA9A32C72D
W: Failed to fetch http://termux.net/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6700B77E6D8D0AE7
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by its-pointless** [comment]
you have to re add my key apt-key add pointless.gpg

**Comment by valmar** [comment]
@its-pointless It worked. I readded your key and then termux's key.

For termux's key I did:

pkg install dirmngr
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 6700B77E6D8D0AE7

Everything seems fine now. Is there something I can do to help upstream this solution?

Thanks once more

**Comment by its-pointless** [comment]
You are literally the only person with this issue i have seen. i will have a chat with fornwall about it though.

**Comment by valmar** [comment]
Ok! Maybe it has to do with my network setup or something. It also happened that sometimes I turn the Chromebook back on after a while and pkg update succeed. It could really be a problem on my side

**Comment by valmar** [comment]
I just would like to report that I updated the Acer R11 Chromebook to ChromeOS 61 (and to Nougat on the Android side). In updating I did a powerwash to fix a firmware vulnerability. After that, I haven't experienced this bug any more

**Comment by valmar** [comment]
@its-pointless @fornwall On my side, we could close this issue. The problem solved itself with an update. I haven't seen the problem in two days now!
