### ISSUE TITLE
termux-setup-storage broken on Android 8

### ISSUE THREAD

**Issue by plattfot** [termux/termux-app#449]
Using a Nexus 5x and recently updated to Android 8.
After the upgrade termux no longer worked, when open it just showed a black screen.
Reinstalled it and it was back to normal. 

However I cannot get access to the internal storage.
I followed the guide on the wiki: [internal and external storage](https://wiki.termux.com/wiki/Internal_and_external_storage). Running termux-setup-storage doesn't create $HOME/shared. The status code after running it is 2.

I tried granting it permission to the storage before running the command and same thing. This worked fine in 7.

Thanks

**Comment by pcmoore** [comment]
I'm seeing a similar problem; granting the storage permission and then running `termux-setup-storage` has no effect (exits with 2/ENOENT).

**Comment by jpravetz** [comment]
Same problem for me on Android 8 and Nexus 5x.

**Comment by leocomitale** [comment]
Just hit this problem on my Pixel 2.  Manually granting storage permission to the app doesn't help, termux-setup-storage still fails.

**Comment by sowbug** [comment]
Same, Pixel C, Android 8.0. Tried manually granting storage and then force-stopping. `termux-setup-storage` then `echo $?` prints `2`

**Comment by txoof** [comment]
It's possible to create the symlink to storage manually:
`$ ln -s /storage/emulated/0 storage`

**Comment by plattfot** [comment]
That worked for me.

Thanks

**Comment by sowbug** [comment]
That workaround is worrying, because it confirms that something in `termux-setup-storage` is dying before the symlink creation, but we don't know what it is.

Ideally, `termux-setup-storage` consists of exactly two operations: asking for storage permission, and creating the symlinks. If that's all it does, then obviously it's dying when requesting the permission, so manually granting and symlinking is a valid workaround.

But my fear is that it's actually at least three steps: (1) ask for permission, (2) _something very important that you won't notice is missing right away_, (3) create the symlinks. If that's the case, then people using the workarounds in this issue will eventually get bitten by not having done #2.

**Comment by TheWithz** [comment]
Just came to say this is also the case with my Pixel C running android 8.0.0. The manual workaround works for now.

**Comment by fornwall** [comment]
The problem is that `/system/bin/am`, which termux-setup-storage uses to launch android intents from the command line, doesn't seem to work from apps in android 8. Subscribe to https://github.com/termux/termux-packages/issues/1578 to be notified about progress.

**Comment by trusktr** [comment]
I tried the symlinl workaround, but no luck:

```
$ ls /storage/emulated/0
ls: can't open '/storage/emulated/0': Permission denied
$ ln -s /storage/emulated/0 storage
$ ls storage
ls: can't open 'storage': Permission denied
```

Any thoughts?

**Comment by plattfot** [comment]
Have you given the app permission to access the storage? I.e go to the app
in the settings menu and enable the it manually.

Den 28 dec. 2017 21:12 skrev "Joe Pea" <notifications@github.com>:

**Comment by trusktr** [comment]
Ah, that was it. Thanks!

**Comment by spikerola** [comment]
@sowbug
`cmd: Failure calling service activity: Failed transaction (2147483646)`

**Comment by bhardwaj869922** [comment]
to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ ls

[1]+  Stopped                 ls

[1]+  Stopped                 ls
$ ls
[1]   Segmentation fault      ls
try to 100 tym reinstall termux bt its work for only 1 tym when i open next tym termux i face error like that 
anyone hve any solution this fucking error when i put any cmd this error will come
