### ISSUE TITLE
"apt update" hangs with "93% [Working]" on CM13 (One Plus One)

### ISSUE THREAD

**Issue by inducer** [termux/termux-app#45]
Subject says it--it doesn't seem to actually ever finish. Not sure what it's up to. Strace is inconclusive, insofar as it seems to be hanging in a `select()` loop.

**Comment by fornwall** [comment]
Hi,

there was a critical bug in the apt package. There is a new build of apt available which adds the missing methods/store. Please execute the following commands to install the new apt version manually:

wget http://termux.net/dists/stable/main/binary-arm/apt_1.2.1-1_arm.deb
dpkg -i apt_1.2.1-1_arm.deb

Replace "arm" with "i686" above if running a device with an intel cpu:

wget http://termux.net/dists/stable/main/binary-i686/apt_1.2.1-1_i686.deb
dpkg -i apt_1.2.1-1_i686.deb﻿

**Comment by fornwall** [comment]
Normally you just need to run `apt update && apt upgrade` to install the latest packages, but since this was a bug in the apt tool itself one must do the manual installation above.

**Comment by inducer** [comment]
Thx, fixed!
