### ISSUE TITLE
About FFmpeg

### ISSUE THREAD

**Issue by EricInCD** [termux/termux-app#450]
I tried to use ffmpeg to convert photos into a movie.
I used a command below.
ffmpeg -framerate 10 -pattern_type glob -i '*.jpg' -c:v libx264 -pix_fmt yuv420p out.mp4

but it didn't work, it said "Pattern type 'glob' was selected but globbing is not supported by this libavformat build"
it looks like termux doesn't support glob, how to implement it?

**Comment by its-pointless** [comment]
No termux has a lib libandroid-glob which implements that. Its just not enabled in ffmpeg.

**Comment by EricInCD** [comment]
@its-pointless Hi, thank you for your kind answer. Could you tell me how to enable it in ffmpeg?

**Comment by its-pointless** [comment]
it would require recompiling ffmpeg and figuring out how to enable it. I don't how to enable it so for now you are out of luck.

**Comment by sdrausty** [comment]
A workaround is to write an enormous input file for ffmpeg; Good luck.

**Comment by EricInCD** [comment]
@its-pointless Thank you all the same

**Comment by fornwall** [comment]
An updated ffmpeg package which includes glob functionality is now available at version 3.3.4-2!

**Comment by EricInCD** [comment]
@fornwall OK, I will check it out, thanks!
