### ISSUE TITLE
Problem with svn

### ISSUE THREAD

**Issue by pablomancera** [termux/termux-app#451]
Trying to do a checkout I get svn: E175003: Attempt to fetch capability 'depth' resulted in 'yes'

**Comment by jsainzvela** [comment]
Same here!

**Comment by fornwall** [comment]
Does the command

    svn checkout http://svn.apache.org/repos/asf/spamassassin/trunk spamassassin

work for you?

Which arch are you running (output of running `uname -m`) and which android version?

**Comment by jsainzvela** [comment]
Hi Fredrik,

here you have:

u0_a193@localhost:~/tmp  $ svn checkout
http://svn.apache.org/repos/asf/spamassassin/trunk spamassassin
svn: E175003: Attempt to fetch capability 'depth' resulted in 'yes'
u0_a193@localhost:~/tmp  $ uname -m
armv7l

Running LineageOS (Android 7.1.2) on a Galaxy Note 3

Hope this helps!

Jorge

**Comment by nuxnik** [comment]
Hi Folks, 

I'm having the same issue and I have almost the same set up:

$ svn checkout http://svn.apache.org/repos/asf/spamassassin/trunk spamassassin 
svn: E175003: Attempt to fetch capability 'depth' resulted in 'yes' 

$ uname -m 
armv7l 

I'm also running LineageOS (Android 7.1.2) but on a Galaxy Tab SM-T520

Cheers! :)

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#1897
