### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by BearChavez** [termux/termux-app#453]
For some reason, I'm unable to run this tool on my device. It's running Android Oreo if this helps 

python2 sniffer.py
posix
Traceback (most recent call last):
  File "sniffer.py", line 14, in <module>
    sniffer = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket_protocol)
  File "/data/data/com.termux/files/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 1] Operation not permitted

That is what I get when trying to run the program. If needed, I can post the code as well

**Comment by xeffyr** [comment]
Device is rooted ?

**Comment by fornwall** [comment]
Raw sockets is just not allowed without rooting - nothing we can do in Termux unfortunately.
