### ISSUE TITLE
ssh won't connect

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-app#456]
Hello, i'm trying o setup a ssh server on termux.
I've run on termux
`ssh -d `
and on windows cygwin i ran
`ssh -p 8022 -i id_rsa user@ip`
where id_rsa is the files with my private key and i got connection timeout error
On termux, the server its listening to port 8022, but nothing happens.
I can connect on termux running the same command.

Any ideas are appreciated!

**Comment by Quasic** [comment]
I expect you meant sshd -d, to log debug info. I recently set up ssh over USB, and had this problem. I would check firewalls and routers to make sure the port is allowed, ping termux, try omitting the user@ (just the bare ip, as that's how I use another port of ssh, though it shouldn't matter) and also note that only the first connection is allowed when using sshd's -d switch, and others will be refused.



 recently set up ssh for USB, but I used to use Wi-fi. In both clientermux runs sshd. I've used several clients, and had trouble setting up each. I haven't tried cygwin, yet, but I plan to set up cygwin64 client. In general, make sure the Public key is in .ssh/authenticated_keys, and the user part may or may not be needed, depending on the client. (I don't use it in git's msys on Windows, just the ip and port, as it knows my keys.) Other clients require it, or add their own, such as anonymous.

**Comment by Quasic** [comment]
I don't know if this will help, but I found it helpful to go over: https://glow.li/tech/2015/11/06/run-an-ssh-server-on-your-android-with-termux.html

Sorry my previous post wasn't quite done, but I think I'll leave it...

**Comment by kurokirasama** [comment]
thanks. The link from your second post i where i get the info to install the server xD. I'll try what you describe on your first post...

**Comment by Grimler91** [comment]
I'll close this as it seems to be solved.

**Comment by MaxLaumeister** [comment]
Updated permalink to above tutorial: https://glow.li/technology/2015/11/06/run-an-ssh-server-on-your-android-with-termux/

**Comment by mohitbajroliya** [comment]
ssh -R 4564:localhost:4564 serveo.net
ssh: connect to host serveo.net port 22: Connection refused
Cannot connect help me out

**Comment by xeffyr** [comment]
@mohitbajroliya `serveo.net` no longer exists.
