### ISSUE TITLE
Tmux - lines redraw incorrectly when scrolling in vim/neovim

### ISSUE THREAD

**Issue by justinkelly** [termux/termux-app#457]
Hi Termux - thanks so much for the awesome app - has totally changed how I use my chromebook!!!

1 issue I'm having at the moment is that in tmux if i have vim or neovim open and are scrolling/editing around in the file i notice that the screen/lines are incorrect. Its hard to explain and doesn't always happen but i'll try and show an example below

example file after opening

```
# Read settings from .termuxrc if existing
test -f $HOME/.termuxrc && . $HOME/.termuxrc
: ${TERMUX_TOPDIR:="$HOME/.termux-build"}
: ${TERMUX_ARCH:="aarch64"}

_show_usage () {
	echo "Usage: ./build-all.sh [-a ARCH]"
	echo "Build all packages. ARCH is one of aarch64 (default), arm, i686 or x86_64."
	exit 1
}
```
now scrolling up and down and/or some minimal edits elsewhere in the file i'll look at the same section of code and it might something look like
```
# Read settings from .termuxrc if existing
test -f $HOME/.termuxrc && . $HOME/.termuxrc
: { }

 w_usage () {
	echo "Usage: ./build-all.sh [-a ARCH]"
	echo "Build all packages. ARCH is one of aarch64 (default), arm, i686 or x86_64."
	exit 1
}
```
it i do git diff in another tab it wont show any of these changes - but if i keep the file open for viewing has incorrect or missing lines of code ???????

i doesnt always happen - but seems to only happen in tmux

if i used abduco as a terminal multiplexer i do not get this issue
* https://github.com/termux/termux-packages/tree/master/packages/abduco

I had assumed it was related to this issue: https://github.com/termux/termux-packages/issues/1252
- but i'm still experiencing the issue even those this one is fixed

Thanks so much 

Justin

**Comment by fornwall** [comment]
Could you check if updating to the latest version 0.54 of the Termux app fixes the issue? It has just been released so should be available as an update shortly.

**Comment by justinkelly** [comment]
thanks @fornwall  - i'll test with the update and let you know

**Comment by fornwall** [comment]
@justinkelly Have you tried the update?

**Comment by justinkelly** [comment]
@fornwall - have just tmux and i'm not getting the redraw issues anymore!!!

thanks so much!! - termux is awesome!!!

i'll close this issue now
