### ISSUE TITLE
Run Docker on Android via Termux?

### ISSUE THREAD

**Issue by larskluge** [termux/termux-app#459]
Is there any way possible to get a Docker container to run on Android via Termux? Perhaps via using `chroot`?

Thanks!

**Comment by sdrausty** [comment]
@larskluge have you tried using https://wiki.termux.com/wiki/PRoot to run docker in a Linux distro in Termux? I have tried several times unsuccessfully.

**Comment by fornwall** [comment]
Thanks for the interest! Note that github issues is not the best forum for this, try any of the following channels instead:

- Google+ community: https://termux.com/community
- Mailing list: https://groups.io/g/termux/
- Gitter: https://gitter.im/termux/termux
- IRC: #termux on freendoe

**Comment by larskluge** [comment]
@sdrausty Thanks for pointing me to Proot. I spent a bunch of hours on it over the weekend, but not success either. Ran into weird errors; it seems on an Android platform some kernel modules are missing. And then it might be possible to emulate the missing ones, but this is beyond my current understanding. Hope somebody else will push this forward, would be great to have Docker available!

**Comment by sdrausty** [comment]
Maybe if there was a way to run `containerd` in non-deamon mode, `docker` might work? Just a thought.

**Comment by larskluge** [comment]
Good thought. I'm personally mainly interested in `docker-compose` (or perhaps swarm) to launch many containers easily and w/ networking.. Not getting there with the lower levels. 

`runc` is the other option for a single container.

**Comment by hash-pile** [comment]
Can someone give me a step by step to get docker on termux?
I'm new to programming and i can't find any guides  that have words I can understand

**Comment by Grimler91** [comment]
@hash-pile docker doesn't work in termux so no such guides exist

**Comment by SDRausty** [comment]
@larskluge there is an alternative to docker that runs in Termux PRoot.  It is called udocker: https://www.google.com/search?q=TermuxArch+udocker
