### ISSUE TITLE
add directory to path

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-app#460]
Hello,
i'm trying to add a directory to path using:
```
PATH=$PATH:~/folder
export PATH
```
that works (but scripts in folder aren't recognized) and it gets undone when restarting the app...

Regards,

**Comment by Auxilus** [comment]
You need to add `PATH=$PATH:~/folder` to your shell's rc file ( bashrc or zshrc ) which will execute the export command everytime new session starts

**Comment by kurokirasama** [comment]
Ok thank!, but how do i do that?

**Comment by sdrausty** [comment]
@kurokirasama use your favorite editor to edit `~/.bashrc` if you are using bash. Then start a new session for your changes to take effect.

**Comment by kurokirasama** [comment]
thanks a lot!

**Comment by mcurotto** [comment]
@fornwall changing path in ~/.profile or ~/.bashrc does not work when executing scripts through shortcuts or tasker. Is it some issue or am I missing something?
Thanks

**Comment by nsdevaraj** [comment]
/data/data/com.termux/files/usr/bin/bash cp your executable files to that location

**Comment by shdbwa** [comment]
> /data/data/com.termux/files/usr/bin/bash cp your executable files to that location

**If you do this you will overwrite your bash executable (= binary / ELF) and run into some issues...**

Copy instead in : 
`/data/data/com.termux/files/usr/bin/ `
OR 
`/data/data/com.termux/files/home/.local/bin/`
AND, add this to your ~/.zshrc 
`export PATH=/data/data/com.termux/files/home/.local/bin:$PATH`
this will sort ~/.local/bin before termux /bin, and before android /bin
So you can create custom bin with options: 

```cat /data/data/com.termux/files/home/.local/bin/ncdu```
OR
```cat $(which ncdu)```
```
#!/data/data/com.termux/files/usr/bin/sh
/data/data/com.termux/files/usr/bin/ncdu --color dark
```
![image](https://user-images.githubusercontent.com/47036017/119238086-b130d280-bb40-11eb-89a6-5f6e4fb4a727.png)
