### ISSUE TITLE
problem running bash scripts

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-app#461]
Hello, i have problem executing scripts. For instance, let's consider the following one (`getip`):
```
#!/usr/bin/bash
 
ifconfig | awk '/inet addr/{print substr($2,6)}'
```
i can't execute it using
`./getip`
but i can using
`sh getip`
on the first one, i get the error:
`bash: ./getip: /usr/bin/bash: bad interpreter: Permission denied`
I have `termux-exec` and `proot` installed, an i already did `termux-chroot`

Am i doing something wrong? or is the second option the only way to execute it?
Regards,

**Comment by Auxilus** [comment]
It's the shebang problem, you can fix the shebang using `termux-fix-shebang <script_name>`

**Comment by kurokirasama** [comment]
but shouldn't `termux-exec` overcome that problem?

**Comment by Auxilus** [comment]
Have you restarted termux after installing `termux-exec`?

**Comment by kurokirasama** [comment]
yup, several times...

**Comment by sp4rkie** [comment]
are you logged in via `ssh`? Did you eventually not terminate the `sshd` daemon after the package install? What does

        echo $LD_PRELOAD
say?

**Comment by kurokirasama** [comment]
nop, nop and
`/data/data/com.termux/files/usr/lib/libtermux-exec.so`

**Comment by fornwall** [comment]
@kurokirasama Hm, even `#!/data/data/com.termux/files/usr/bin/bash` doesn't work?

Is something wrong with your bash binary? Does running `bash` work?

**Comment by kurokirasama** [comment]
Yes.
Running `bash` works without error nor output...

**Comment by kurokirasama** [comment]
I think I figure out. I had the script on extSdCard. I move it to home and I had to rewrite it using nano (i previously used an android text editor)

**Comment by sdrausty** [comment]
@kurokirasama it is good to hear that you figured out your issue. Here is more important information regarding storage https://wiki.termux.com/wiki/Internal_and_external_storage

**Comment by fornwall** [comment]
@kurokirasama Aha, great that you got it figured out!

**Comment by oxlynx** [comment]
./ngrok 
( bash: ./ngrok: Permission denied ) Why?
