### ISSUE TITLE
Error after starting (libunwind.so is loaded, which references other version of liblzma)

### ISSUE THREAD

**Issue by KaMyKaSii** [termux/termux-app#462]
I'm running Android AOSP 7.1.1 on Elephone P8000

![screenshot_20171031-133202](https://user-images.githubusercontent.com/17092335/32233834-7f31dd1e-be42-11e7-9e5f-43922cfd9c40.png)
[Log_2017-10-31_13-31-09.txt](https://github.com/termux/termux-app/files/1431321/Log_2017-10-31_13-31-09.txt)
[libunwind.so.zip](https://github.com/termux/termux-app/files/1431333/libunwind.so.zip)

**Comment by xeffyr** [comment]
Closing as this shouldn't happen on latest Termux versions (Android 7+ only).
