### ISSUE TITLE
pkg upgrade fails with "var/cache/apt/archives/partial is missing"

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-app#463]
Hello, when running `pkg upgrade` I got the following error: `E: Archives directory /data/data/com.termux/files/usr/var/cache/apt/archives/partial is missing. - Acquire (13: Permission denied)` and it doesn't upgrade... I checked and the directory doesn't exists... I created it and try to upgrade again but got the same error. After restarting termux, the directory disappeared...

**Comment by fornwall** [comment]
Just a wild shot, but does running `apt clean` fix anything?

**Comment by kurokirasama** [comment]
Nop, still the same...

**Comment by kurokirasama** [comment]
And I got the same error when trying to install any package...

**Comment by dg28gadhavi** [comment]
In termux,

mkdir -p /data/data/com.termux/files/usr/var/cache/apt/archives/partial

apt-get autoclean


This works :)

**Comment by mabelisle** [comment]
Why is this closed? I'm still having this issue over and over. I'm on the Android. I can install a package once but if I try the day after it stops working again. dg28gadhavi solution works but it's a pain to have to do it everytime.

**Comment by suryabh4** [comment]
@mabelisle - Were you able to fix the issue ?

**Comment by xeffyr** [comment]
> but it's a pain to have to do it everytime.

Just don't mess with stuff in $PREFIX and you won't have to do it everytime.
