### ISSUE TITLE
CANNOT LINK EXECUTABLE "-bash":

### ISSUE THREAD

**Issue by eliiik** [termux/termux-app#467]
It works perfectly fine before. But now every time I run it, just display this error: 

```
CANNOT LINK EXECUTABLE "-bash": library "libncursesw.so.6" not found

[Process completed (signal 6) - press Enter]
```

And I can't input any command as well. The only thing I can do is 'press Enter' and the app will exit automatically.

So what's wrong? I believe I never delete any **lib** files. All I remember some "dangerous" command I run just before was something like
```
sudo pkg update
```
I have used this app for several months. There's one time I got some error kinda like this, I just moved it from internal storage to SD card and moved back, and somehow it was back to normal. But not this time.

_BTW, I'm running on Lineage OS with Android 7.1.2 rooted on RedMi Note 4x._

**Comment by fornwall** [comment]
I think the easiest way to restore functionality is to use a failsafe session (see https://wiki.termux.com/wiki/Recover_a_broken_environment) to remove every installed package (by running `rm -rf $PREFIX`), exiting all sessions and restarting Termux again.

This will cause a new setup of packages, and you have to install everything but the non-essential packages again. But the data in `$HOME` is not affected.

Let me know if there is any problem!
