### ISSUE TITLE
Can't run script on termux-notification 

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-app#468]
Hello,
I have this script 
```
#!/usr/bin/bash

for file in *.$2 ; do
	rm -f "$(basename "$file" .$2).$1"
done
```
on a directory added to PATH. When I run it on the cli, it works just fine. 
```
rmeq ext1 ext2
```
But when I try to run it through termux-notification on another script, its actions are not executed:
```
remove='cd ~/aDirectoryPath;rmeq ext1 ext2;mv *.ext2 ~/otherDirectoryPath/;termux-toast -s done;termux-notification-remove 999'
content='some text' 
termux-notification --title "a title" --vibrate 500,1000 --content "$content" --id 999 --button1 "remove ext1's" --button1-action "$remove"
```
All actions on `$remove` are executed except for `rmeq ext1 ext2`. Any idea of what I'm doing wrong?

**Comment by LyraLover228** [comment]
I couldn't find anything about rmeq in both Termux (it says it couldn't find the command) and Duckduckgo (nothing showed up on the first page). What does it do?

**Comment by LyraLover228** [comment]
Damn, rmeq is your own script? I'm sorry :'D

**Comment by xeffyr** [comment]
> But when I try to run it through termux-notification on another script, its actions are not executed:

`termux-notification` uses a standard value for PATH, so `rmeq` won't be available. That's expected behaviour since all Termux:API commands are not executed within the current shell (doing so isn't possible).
