### ISSUE TITLE
Files in external sd card all have the same mode 

### ISSUE THREAD

**Issue by yuyueshihaoren** [termux/termux-app#469]
$ chmod 111 ringtest2.c  
$ ls -l  
total 48  
-rwxrwx---    1 u0_a32   sdcard_r      6876 Nov  6 01:12 ringtest  
-rwxrwx---    1 u0_a32   sdcard_r        69 Nov  6 01:12 ringtest.c  
-rwxrwx---    1 u0_a32   sdcard_r        69 Nov  6 15:46 ringtest2.c

**Comment by sdrausty** [comment]
@yuyueshihaoren See https://wiki.termux.com/wiki/Internal_and_external_storage for an explanation.
