### ISSUE TITLE
Possibility of Termux bundle

### ISSUE THREAD

**Issue by parkerlreed** [termux/termux-app#47]
I have a device that doesn't have any user facing Internet connection (Android Wear smartwatch) 

I was wondering is there a way to transfer a pre-setup environment along with the application on install or maybe placing the environment in the right place after install? It's unable to download the initial environment due to no Internet access directly on the watch. (Termux actually launches and tries but just continues to spin on the setup screen)

**Comment by parkerlreed** [comment]
Managed to get it working. Turns out you can turn on WiFi on the watch and then disable Bluetooth on the phone side.

![apt-get](http://i.imgur.com/9IO9jfW.jpg)
![cmatrix](http://i.imgur.com/aMQcJV0.jpg)
https://www.youtube.com/watch?v=mBnCzslrJUE

**Comment by fornwall** [comment]
Cool :)!

**Comment by parkerlreed** [comment]
Thanks for all the work put into this. Termux has been by far my favorite terminal on Android. It working on a watch is even more testament to the beauty of Android. 

A couple more actions shots. I think I went full circle running aclock and tty-clock on a watch.

![aclock](http://i.imgur.com/H1fp8Uf.jpg)
![tty-clock](http://i.imgur.com/dWzYmrS.jpg)

**Comment by tristan-k** [comment]
How did you send text input to the termux interface with adb? Which commands?

**Comment by parkerlreed** [comment]
`adb shell input text blah`

`adb shell input keyevent SPACE`

`adb shell input keyevent ENTER`

etc :)
