### ISSUE TITLE
Termux on Android 8.0 couldn't use system function

### ISSUE THREAD

**Issue by HrOice** [termux/termux-app#471]
Termux on my XZP(Android 8.0) cannot use npm to install packages.I learnt that I couldn't use command 'top' to show info.It returned : can't open 'stat': Permission denied.So how can i solve this permission to use termux freely.Thanks.

**Comment by fornwall** [comment]
See https://github.com/termux/termux-app/issues/299 - it's basically a limitation of android 8.0.
