### ISSUE TITLE
Failure calling service activity

### ISSUE THREAD

**Issue by Dmole** [termux/termux-app#472]
$  termux-setup-storage
cmd: Failure calling service activity: Failed transaction (2147483646)
$ uname -a
Linux localhost 4.4.56-g845c8307ee66 #1 SMP PREEMPT Tue Aug 29 04:45:06 UTC 2017 aarch64 Android

device is walleye

command was
```bash
am broadcast --user 0 \
                 --es com.termux.app.reload_style storage \
                 -a com.termux.app.reload_style com.termux
```

Workaround;
Enable rights in settings then use the real path
/storage/emulated/0/DCIM/Camera/
etc

**Comment by fornwall** [comment]
Thanks - this is an issue when running Termux under Android 8. Subscribe to https://github.com/termux/termux-packages/issues/1578 for progress!

**Comment by Dmole** [comment]
Please edit the documentation to mention the workaround.

**Comment by gsf** [comment]
In the meantime see [this workaround](https://github.com/termux/termux-app/issues/449#issuecomment-341228760) at termux/termux-app#449.
