### ISSUE TITLE
Changing package name

### ISSUE THREAD

**Issue by F0RIS** [termux/termux-app#479]
Hi, I'm working on project which use termux environment (actually I need only console, git and nodejs). 
The issue is, that when I change package name all environment  stops working.
At first bootstrap didn't want install, I changed paths in its scripts and now have this:

![image](https://user-images.githubusercontent.com/10178982/32849673-84306b1c-ca38-11e7-8c86-b1000161f50c.png)

Can somebody help and write where placed paths with hardcoded termux package name?
Thanks.

**Comment by sdrausty** [comment]
https://wiki.termux.com/wiki/Recover_a_broken_environment

**Comment by F0RIS** [comment]
@sdrausty I want publish my app in Google Play, as I understand I can do it with current licence. But I must share my chanes, is it right?

**Comment by fornwall** [comment]
@F0RIS I think it's easier to chat about this than discuss it on a github issue - join https://gitter.im/termux/termux or contact me directly on gitter!

**Comment by isaacdarcilla** [comment]
Was this resolved?

**Comment by isaacdarcilla** [comment]
> @F0RIS I think it's easier to chat about this than discuss it on a github issue - join https://gitter.im/termux/termux or contact me directly on gitter!

Was this resolved?

**Comment by F0RIS** [comment]
@isaacdarcilla no
