### ISSUE TITLE
PyTables- unable to install

### ISSUE THREAD

**Issue by abbazs** [termux/termux-app#480]
I need to install PyTables an when I say 'pip install tales' I get the following error, how to install tables?

Collecting tables
  Using cached tables-3.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    /data/data/com.termux/files/usr/tmp/H5close_at1xx0s.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
    main (int argc, char **argv) {
    ^
    /data/data/com.termux/files/usr/tmp/H5close_at1xx0s.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]
        H5close();
        ^
    2 warnings generated.
    /data/data/com.termux/files/usr/bin/ld: cannot find -lhdf5
    clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
    * Using Python 3.6.3 (default, Oct  6 2017, 07:46:32)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-kqdo1l36/tables/

**Comment by Grimler91** [comment]
> /data/data/com.termux/files/usr/bin/ld: cannot find -lhdf5

This means that the compiler is trying to link against libhdf5.so but is unable to find that file. 
It isn't available in any of the termux repositories as far as I know but you can always compile it yourself on device. It seems to be a bit cumbersome to cross-compile it unfortunately.

I tried compiling it on my device and it was pretty straight forward, here's a small script:
```
# Not entirely sure what dependecies we have, here's some guesses:
apt install clang libtool make

# From some folder in $HOME:
curl -L -O https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.19.tar
tar -xf hdf5-1.8.19.tar
cd hdf5-1.8.19

# Need a working TMPDIR, it isn't set properly in a ssh shell
export TMPDIR=$PREFIX/tmp

# Need to replace config.guess script:
cp $PREFIX/share/libtool/build-aux/config.guess bin/config.guess

# Replace /bin/sh with /data/data/com.termux/files/usr/bin/sh
find . -type f -exec sed -i \
  's%    /bin/mv%    /data/data/com.termux/files/usr/bin/mv%g' {} +
find . -type f -exec sed -i \
  's%SHELL = /bin/sh%SHELL = /data/data/com.termux/files/usr/bin/sh%g' {} +
find . -type f -exec sed -i \
  's%CONFIG_SHELL-/bin/sh%CONFIG_SHELL-/data/data/com.termux/files/usr/bin/sh%g' {} +
mkdir build && cd build

termux-fix-shebang ../configure
# configure to install in /data/data/com.termux/files/usr/
../configure --prefix=$PREFIX
make

# make some directories that aren't automatically created for some reason:
mkdir -p /data/data/com.termux/files/usr/share/hdf5_examples/{,hl}/c

make install

# We need to tell python to look for HDF5 in /data/data/com.termux/files/usr
HDF5_DIR=$PREFIX pip install tables
```

**Comment by abbazs** [comment]
I'm sorry I still could not get it work. I've the following error now. 

termux-fix-shebang ../configure                $ make                                           Making all in src                                make[1]: Entering directory '/data/data/com.termux/files/home/hdf5-1.8.19/build/src'              cd .. && make  am--refresh                       cd .. && /data/data/com.termux/files/usr/bin/sh ./config.status src/H5config.h                    config.status: creating src/H5config.h           config.status: src/H5config.h is unchanged       make  all-am                                     make[2]: Entering directory '/data/data/com.termux/files/home/hdf5-1.8.19/build/src'              cd .. && make  am--refresh                         CC       H5.lo                                 In file included from ../../src/H5.c:22:         In file included from ../../src/H5private.h:27:  ../../src/H5public.h:29:10: fatal error:               'H5pubconf.h' file not found               #include "H5pubconf.h"          /*from co...              ^~~~~~~~~~~~~                           1 error generated.

**Comment by abbazs** [comment]
I still could not get it work. I've the following error now.
[config.txt](https://github.com/termux/termux-app/files/1481196/config.txt)
[install.txt](https://github.com/termux/termux-app/files/1481246/install.txt)

**Comment by Grimler91** [comment]
@abbazs which arch are you on? This error doesn't seem to occur on arm or aarch64.

**Comment by abbazs** [comment]
![screenshot_2017-11-17-16-32-07-330_com termux](https://user-images.githubusercontent.com/758268/32944278-02b486bc-cbb5-11e7-9c22-bdfeaaf75e57.png)

It is aarch64.

![screenshot_2017-11-17-15-43-37-480_com termux](https://user-images.githubusercontent.com/758268/32944320-2a1dfa76-cbb5-11e7-9a04-051f83f6260c.png)
