### ISSUE TITLE
[Feature Request]Termux as home app

### ISSUE THREAD

**Issue by rubikitch** [termux/termux-app#482]
I use Termux almost all time.
So I want Termux as home app.

**Comment by trusktr** [comment]
That'd be interesting. Can we launch other apps from Termux?

**Comment by Grimler91** [comment]
It looks like https://github.com/termux/termux-app/issues/206 is asking for the same thing (correct me if I am wrong).

**Comment by trusktr** [comment]
Looks like it is, and the solution may near!
