### ISSUE TITLE
How to keep sshd alive

### ISSUE THREAD

**Issue by rubikitch** [termux/termux-app#483]
I use sshd in Termux and sshfs in GNU/Linux computer.
So I can access termux files from computer, very useful.

But Android occasionally kills processes even when termux holds wake lock.
When sshd is killed by Android, I cannot access files from computer.
It is VERY VERY FRUSTRATING.

So I create a shell script `ssh-keep-alive' and it is automatically invoked when I USB-connect to computer.

    #!/data/data/com.termux/files/usr/bin/sh
    if ! ssh -p 8022 localhost date +1 | grep 1 > /dev/null; then
        echo $(date) pkill sshd
        pkill sshd
    fi
    if ! pgrep sshd > /dev/null; then
        echo $(date) restart sshd
        sshd
    fi
    sleep 3
    # `adb reverse tcp:9022 tcp:22' is issued in computer
    if ssh rubikitch@localhost -p 9022 date +1 | grep 1 > /dev/null; then
        exec $0
    fi

`ssh-keep-alive' is pseudo URL handler of `termux-url-opener'.

    #!/data/data/com.termux/files/usr/bin/fish
    function invoke-sshd-keep-alive
            echo Invoke ssh-keep-alive
            ssh-keep-alive
    end

    ## stripped

    function _main
            if string match -q http://www.example.com/sshd-keep-alive $argv[1]
                    invoke-sshd-keep-alive
            end
    end

    _main $argv

I execute the following when connect to computer.
Virtually I can execute any command in termux from adb by using `termux-url-opener'.

    $ adb shell am start -a android.intent.action.SEND -t text/plain --es android.intent.extra.TEXT 'http://www.example.com/sshd-keep-alive' -p com.termux

I previously tried to run `ssh-keep-alive' as background process, but Android killed it.
Running `ssh-keep-alive' as foreground process (termux-url-opener), Android does not kill it.

I have rooted my phone.
What is better solution to keep sshd alive?

**Comment by tumashu** [comment]
Have you by chance enabled some development options? There are some settings that will do exactly this. Also certain "power saving options" may be doing this.

**Comment by sp4rkie** [comment]
never got the problem of killed 'sshd' before. But 'sshd' (for me) is laggy without this workaround: https://github.com/termux/termux-packages/issues/1193#issuecomment-333140664

**Comment by rubikitch** [comment]
I forgot to show `termux-info`.

    Termux version:
    <=0.48
    Installed Termux apps:
    package:com.termux.api  installer=null
    package:com.termux  installer=null
    Updatable packages:
    clang/stable 5.0.0-1 aarch64 [upgradable from: 5.0.0]
    libllvm/stable 5.0.0-1 aarch64 [upgradable from: 5.0.0]
    tsu/stable 0.3 all [upgradable from: 0.2]
    System information:
    Linux localhost 3.10.49-g9ddf6de #1 SMP PREEMPT Tue Sep 13 05:39:30 CST 2016 aarch64 Android
    Termux-packages arch:
    aarch64
    Android version:
    5.1.1
    Device manufacturer:
    HUAWEI
    Device model:
    PLE-701L

**Comment by rubikitch** [comment]
@tumashu I opened development options panel. But I do not figure out settings. Please tell me them in Android 5.1.1.

**Comment by tumashu** [comment]
高级设置 > 电池管理 > 省电模式 >  第一个选项

**Comment by tumashu** [comment]
选择 性能模式
