### ISSUE TITLE
Notification not shown

### ISSUE THREAD

**Issue by lauhayden** [termux/termux-app#484]
No notification from the Termux app is showing up when I launch the app. The only notification is 'termux is running in the background' from Android OS when the Termux app is not in focus.

As a result, I am unable to close any terminal sessions and am forced to force close the app.

Termux 0.54 installed via the Play store
Android 8.0.0
Nexus 5x stock

**Comment by sdrausty** [comment]
Try uninstalling, then reinstalling Termux 0.54. This might not seem like it can help, but it might. Alternatively, install the same app again (twice). Good Luck.

**Comment by lauhayden** [comment]
I uninstalled and reinstalled Termux via the Play store, no change. Thanks for the quick response, by the way.

**Comment by fornwall** [comment]
Thanks for reporting! This was an issue when running Termux under Android 8 which has been fixed in the newly released version 0.55, which should be availalbe as an update within a few hours max!

Let me know if the problem remains after v0.55.
