### ISSUE TITLE
Strongly recommend adding Chinese language support

### ISSUE THREAD

**Issue by chenjiageng** [termux/termux-app#485]
I am a Chinese, there may be a language barrier。
Your application is really great, but I encountered a tricky problem, the Chinese file shows garbled open, I checked the wiki and found that does not support Chinese, but I rely on Chinese, request support in the next version.
Best wishes to you

**Comment by Grimler91** [comment]
@chenjiageng Which program are you using to open the files? Is it the same with other editors?

I guess this might be an issue with the various packages available (or ncurses?) and perhaps not really with termux-app.

**Comment by chenjiageng** [comment]
@Grimler91 I am using vim editor, do I need to change its settings? Or for another editor? Thank you for your attention!

**Comment by Grimler91** [comment]
I did some testing and copied some random characters into a file and were opened them with emacs and vim without it looking weird:
![screenshot_2017-11-21-01-32-23](https://user-images.githubusercontent.com/18900601/33048634-35ede010-ce5c-11e7-9360-c558fa8a46a7.png)
It even looked correct when cat'ing the file.

Could you explain in more detail how to reproduce the problem you're experiencing?

**Comment by tumashu** [comment]
termux'emacs can show Chinese properly

**Comment by chenjiageng** [comment]
@Grimler91 ok, demonstrated below
![image](https://user-images.githubusercontent.com/26062629/33052000-a298246e-cea7-11e7-8dcb-8f7fc0787370.png)
![image](https://user-images.githubusercontent.com/26062629/33051895-277a5cd4-cea7-11e7-939b-96b4865cc07d.png)

**Comment by chenjiageng** [comment]
Well, forgive me for being stupid, a beginner's mistake.
I did something
touch ~ / .vimrc
cd ~
vim .vimrc
``set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,latin1
set termencoding=gb18030
set expandtab
set ts=4
set shiftwidth=4
set nu
syntax on

if has('mouse')
set mouse-=a
endif
``
Got the perfect solution
I am very sorry to take up your precious time.
In addition, the best wishes to you.

**Comment by chenjiageng** [comment]
@tumashu Sorry, I only learned vim now
