### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Sk8793** [termux/termux-app#487]
mv: cannot move '/data/data/com.termux/files/home/Tmux-Bunch/binder/is.apk' to '/data/data/com.termux/files/home/metasploit-framework/is.apk': Permission denied

how can I fix this? I can't even copy or move any file

**Comment by Grimler91** [comment]
Are you root? Have you created the files as root? 
What are the permission of the file and folders?

**Comment by Sk8793** [comment]
how to create files as root?

**Comment by Grimler91** [comment]
If you have to ask then that's probably not the problem here.

Could you please run 
`ls -l /data/data/com.termux/files/home/Tmux-Bunch/binder/is.apk` 
and `ls -l /data/data/com.termux/files/home/metasploit-framework/` and post the results here?
