### ISSUE TITLE
Need help about emacs-async

### ISSUE THREAD

**Issue by tumashu** [termux/termux-app#488]
Hello

I have faced a problem that "emacs-async package can not work well in termux's emacs.",  https://github.com/jwiegley/emacs-async/issues/90#issuecomment-346260368 ,  and I can not verify this is a emacs-async's bug or termux-emacs's bug,  so I wish the friends who have installed the emacs in termux to test the below code, and feed back its work status, thanks:

```
(require 'async)
(async-start
   ;; What to do in the child process
   (lambda ()
     (message "This is a test")
     (sleep-for 3)
     222)

   ;; What to do when it finishes
   (lambda (result)
     (message "Async process done, result should be 222: %s" result)))
```

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#1896
