### ISSUE TITLE
Working on BluetoothAPI 

### ISSUE THREAD

**Issue by raymerta** [termux/termux-app#489]
Hi, 

I'm currently working on creating Bluetooth API for Termux, I managed to show bluetooth information (name, address, etc) and paired devices but got problem when trying to pass text message via parameter, the parameter always gets null result when I check the intent in TermuxReceiver. 

Could you advise me on this? 

Extra information: 

I ran termux api by making termux-api-package with my bluetooth script inside it and run './termux-api Bluetooth'. I'm trying to run the other API using this way (for example: ./termux-api BatteryStatus works well, but ./termux-api Share file_name also got null parameter)

**Comment by Grimler91** [comment]
Sounds interesting. Do you have the sources available somewhere?

**Comment by raymerta** [comment]
Hi @Grimler91 here's my repository (https://github.com/raymerta/node-android-app). It's for my school project to create node js android app that can send message via bluetooth. 

Right now I'm using ugly hack to pass the text (not pushed in this repo)

**Comment by raymerta** [comment]
I managed to get the parameters and send the message via bluetooth. It was a stupid mistake, should run 'make install'  instead of only 'make'
