### ISSUE TITLE
trigger reboot when i try use /nick myname in weechat

### ISSUE THREAD

**Issue by jacktsui** [termux/termux-app#490]
trigger reboot when i try use "/nick myname" in weechat, i try two times, it happened again.

**Comment by jacktsui** [comment]
where can i find some logs about this?
i have try search  both in "/data/data/com.termux/" and "/data/data/com.termux/files/home/.weechat" nothing log about this.

**Comment by Neo-Oli** [comment]
Duplicate of https://github.com/termux/termux-app/issues/490#issuecomment-346769130

**Comment by Neo-Oli** [comment]
Sorry, Duplcate of https://github.com/termux/termux-app/issues/129
