### ISSUE TITLE
Overabundance  of text in shared URL. 

### ISSUE THREAD

**Issue by ofgowtham** [termux/termux-app#491]
Sometimes if I share a URL from an app or a webpage to Termux, instead of passing it to termux-url-opener, it prompts to save as text file. Any idea of extracting the URL from it and pass it to t-u-o?

**Comment by sdrausty** [comment]
@ofgowtham can you change your title to something pleasant like, "Overabundance of text in shared URL". Also, more information about your topic is requested.  Post information regarding your machine. Use `termux-info` and share this output with us.

What is your sequence of commands?  You posted some information. More is needed for us to help you find a resolution. What is the sequence of commands you are using?  Where are you using the commands? Describe your topic in more detail.  You mentioned two methods. Describe each method separately. 

It looks like your topic wants more than just one screenshot for clarification. Include as many as you think are necessary to explain your issue clearly.  To take a screenshot in Android, press and hold power + volume down simultaneously.  Hold these buttons down momentarily. 

![screenshot_20171128-062125](https://user-images.githubusercontent.com/27742457/33317164-62cb1b18-d404-11e7-9d28-f49b6c9940eb.png)

**Comment by ofgowtham** [comment]
So I use this app called 'Saavn' which is basically a music streaming application. Whenever I try to share a song or an album, the output of shared URL will be something like 'Listen to the album 'I Know You' on Saavn at https://www.saavn.com/p/album/english/I-Know-You-2017/2tiaiKZb3k0_?referrer=svn_source=share&svn_medium=com.android.mms&utm_source=share&utm_medium=com.android.mms' 
So when I shared this via Termux, instead of opening the URL, it prompts to this:
![screenshot_20171130-164837](https://user-images.githubusercontent.com/24489435/33428348-75aa66da-d5ee-11e7-922e-a16f8d5ed207.png)
May be there's too much of text beside the URL or may be the string starts with a text instead of protocol id or 'www' for that matter. Termux treats it as Text. Is there anyway to grab the URL from the whole string and open it via termux-url-opener instead of prompting to save it as Text?
termux-info:
![screenshot_20171130-163517](https://user-images.githubusercontent.com/24489435/33428647-9ce73d8a-d5ef-11e7-8a5f-63f1b85f325f.png)

**Comment by ofgowtham** [comment]
![screenshot_20171130-170318](https://user-images.githubusercontent.com/24489435/33429030-2e0b3202-d5f1-11e7-908b-eecbcd76b69e.png)

**Comment by ofgowtham** [comment]
Sorry accidentally closed it. My bad..

**Comment by xeffyr** [comment]
Unreproducible with recent Termux app versions.

Tested with URL from https://github.com/termux/termux-app/issues/491#issuecomment-348162273.
