### ISSUE TITLE
Issues with latest neovim and background color erase?

### ISSUE THREAD

**Issue by fornwall** [termux/termux-app#492]
Reported on IRC, there may be an issue with BCE in Termux. 

Neovim was recently updated to use BCE, see https://github.com/neovim/neovim/pull/7624.

Can someone write down a minimal neovim configuration and steps to reprodce (@Neo-Oli perhaps)?

**Comment by Neo-Oli** [comment]
I eliminated my config file line by line and found the line that causes this.

Minimal settings
~/.config/nvim/init.vim
```
hi StatusLine ctermfg=15 ctermbg=8 cterm=NONE
```
(setting it with `:hi ... won't cause the problem`)

I experienced this in Termux App, and connected via ssh with `st` and `mintty`, both inside and outside of Termux, so I am not sure it's a Terminal Emulator problem.

**Comment by sdrausty** [comment]
When you open vim with a file previously edited, vim remembers where you last were, but neovim doesn't.  Is there a way to set neovim to behave like vim regarding remembering cursor position from previous editing session?

**Comment by mklein994** [comment]
@sdrausty please keep this issue on topic. Literally the first google hit for [vim jump to last position when opening a file](https://stackoverflow.com/questions/774560/in-vim-how-do-i-get-a-file-to-open-at-the-same-line-number-i-closed-it-at-last).

**Comment by justinmk** [comment]
> Neovim was recently updated to use BCE, see neovim/neovim#7624.

Just to be clear, https://github.com/neovim/neovim/pull/7624 _disables_ BCE for almost all cases. 

- Nvim 0.2.0 did not implement BCE. 
- Nvim 0.2.1 enabled BCE aggressively.
- Nvim HEAD (after https://github.com/neovim/neovim/pull/7624 ) disables BCE (like 0.2.0) in all cases except when the `$XTERM_VERSION` env var is defined.

**Comment by sdrausty** [comment]
@mklein994 post sensible constructive posts please. Or don't post to me.

**Comment by sdrausty** [comment]
@mklein994 post sensible constructive posts please or don't post to me.  And stop sicking your IRC bots at me through Gitter. I am fairly sure you are capable of answering a simple yes or no question. But you prefer to flame me with your bots at Gitter utilizing your bots from the IRC. How constructive is abusing me @mklein994 ?  Stop! Descist!

**Comment by sdrausty** [comment]
@mklein994 post sensible constructive posts please or don't post to me.  And stop sicking your IRC bots at me through Gitter. I am fairly sure you are capable of answering a simple yes or no question. But you prefer to flame me with your bots at Gitter utilizing your bots from the IRC. How constructive is abusing me @mklein994 ?  Stop! Descist!

**Comment by sdrausty** [comment]
Nice. Thank you @fornwall   Going back to my simple multiple choice question.l from Gitter.  Which is most important for Termux and our community in your opinion?

**Comment by sdrausty** [comment]
@Neo-Oli it seems that @justinmk confirms your suggestion to use the release branches, not the developer ones. Thank you for your information @justinmk ⛵🦄

**Comment by fornwall** [comment]
Right, we should really start using the last stable release and stop building from master. I leave this issue open, as it may still be a problem with the terminal emulation in Termux exposed by recent neovim updates.

**Comment by fornwall** [comment]
Updating to the latest git master (in version `0.2.3~2017.11.29` of the package, which is now available) fixed the problem.

@Neo-Oli Let's switch to released versions starting with 0.2.3 when that is final!

**Comment by Neo-Oli** [comment]
Thanks

> @Neo-Oli Let's switch to released versions starting with 0.2.3 when that is final!

That's great.
