### ISSUE TITLE
termux-setup-storage doesn't do anything.

### ISSUE THREAD

**Issue by trusktr** [termux/termux-app#493]
I'm on a new Pixel 2. Running `termux-setup-storage` doesn't do anything. There's no `$HOME/storage` folder after running the command.

**Comment by fornwall** [comment]
Thanks! This is an issue when running on Android 8 which will soon be addressed - subscribe to https://github.com/termux/termux-packages/issues/1578 for progress!

**Comment by gsf** [comment]
In the meantime see [this workaround](https://github.com/termux/termux-app/issues/449#issuecomment-341228760) at termux/termux-app#449.
