### ISSUE TITLE
Optionally disable font change on pinch zoom gesture

### ISSUE THREAD

**Issue by tigran123** [termux/termux-app#495]
Among many other usages Termux is excellent for reading manpages or browsing the source code using vim. For this purpose I get rid of the onscreen keyboard and use a finger to scroll the text up. However, sometimes for some unknown reason the movement of the finger is interpreted as "pinch zoom" gesture and the font size is increased or decreased. This is very annoying as one has to bring it back to how it was and it is never exactly that, the difference in font sizes causing eye strain (this is the same reason, btw, why you can't use "auto-crop margins" function in a pdf/djvu document reader if your book has stuff in the margins, because then the font size of text will change from page to page and your eyes will become tired very quickly).

So, if there was a way to disable "pinch zoom" i.e. ignore such gestures in Termux, it would be very useful. Then, such "misinterpreted scroll up attempt" would simply be ignored and one would have to scroll it again, without having to pinch-resize the screen. Thank you.

**Comment by fornwall** [comment]
> However, sometimes for some unknown reason the movement of the finger is interpreted as "pinch zoom" gesture and the font size is increased or decreased.

Hm, I would guess that is when double tapping - Android translates "double tap and move finger up or down" to zooming (try e.g. in the browser).

**Comment by tigran123** [comment]
Yes, probably that is the case. So, is it possible to have a setting in Termux to "lock" the screen, i.e. ignore all such gestures which can disturb the console font size.

**Comment by sdrausty** [comment]
@tigran123 it looks as though you have stumbled upon a feature request.  Congratulations!  Locking the ability to change font size is a very good idea.  It might be possible to add this feature as a button to the top keyboard row (Ctrl+Q) along with arrow keys through popup features.  Possibly through one arrow, that pops up to four.  Just like by combining "- / |" into a fly out menu.

**Comment by fornwall** [comment]
@tigran123 In version 0.57 of the Termux app, which has been released and should be available as an update on Google Play within an hour or so (and on F-Droid within a day or so), the interpretation of "double tap and swipe finger" as zoom has been disabled.

While really a standard Android behaviour, most users seem to hit it by mistake.

Thanks a lot for the feedback!

**Comment by tigran123** [comment]
Thank you very much. Yes, it works as I expect it now :)
