### ISSUE TITLE
Packages upgrade fails with dpkg unpack needs at least one argument

### ISSUE THREAD

**Issue by edi9999** [termux/termux-app#496]
Here is the output

Apt upgrade has the same behaviour

```
Do you want to continue? [Y/n]
dpkg: error: --unpack needs at least one package archive file argument

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;
```

**Comment by Grimler91** [comment]
Which package(s) are you trying to upgrade?

**Comment by edi9999** [comment]
Many :-)


```
The following NEW packages will be installed:
  coreutils gnupg2 grep libassuan libc++ libedit
  libgcrypt libgpg-error libksba libnpth pinentry
  sed
The following packages will be upgraded:
  apt apt-transport-https automake binutils
  busybox c-ares ca-certificates clang cmake
  command-not-found curl dos2unix dpkg elfutils
  file fontconfig freetype fzf git glib gnuchess
  gnupg golang gpgv htop inotify-tools jsoncpp
  ldns less libandroid-glob libandroid-support
  libandroid-support-dev libarchive libbz2
  libcurl libevent libevent-dev libexpat libgc
  libgd libgmime libjpeg-turbo libllvm libltdl
  liblua libmsgpack libnghttp2 libpng librhash
  libsqlite libtalloc libtiff libtool
  libunibilium libutil libuv libvterm libxapian
  libxml2 libxml2-dev ltrace lynx ncurses
  ncurses-ui-libs ndk-stl ndk-sysroot neovim
  nginx nodejs notmuch openssh openssl p7zip pass
  pcre perl php proot python python-dev readline
  silversearcher-ag strace termux-tools tig tmux
  vim vim-runtime w3m
```

**Comment by edi9999** [comment]
I just tested 

```
apt install vim
apt install fzf
```

Both produce that same error, so I guess there is something wrong with apt in general on my install

**Comment by edi9999** [comment]
If I write

packages remove vim

I get this error :

dpkg: error: --remove needs at least one package name argument

**Comment by Grimler91** [comment]
Interesting. I would try to reinstall apt (and maybe dpkg) manually. You can download the .debs with wget or curl from `http://termux.net/dists/stable/main/binary-ARCH/apt_1.2.12-3_ARCH.deb` and `http://termux.net/dists/stable/main/binary-ARCH/dpkg_1.18.24_ARCH.deb` (replace ARCH with your architecture). Try installing apt with `dpkg -i ./apt_1.2.12-3_ARCH.deb` and similar for dpkg. 

Hopefully that fixes it and you can then afterwards upgrade all packages from the repository.

**Comment by edi9999** [comment]
Ok, strangely this doesn't fix the issue. Both installs went well and I think it was new versions of the packages.

**Comment by edi9999** [comment]
Here are the md5sums of the binaries:

md5sum $(which dpkg) $(which apt)
0ba08dd29c1e5dcfbb37d2172abe4ffb  /data/data/com.termux/files/usr/bin/dpkg
d35b4add9b2e3e7f4edcbcb7b572babf  /data/data/com.termux/files/usr/bin/apt

Do you have the same?

**Comment by edi9999** [comment]
This link seems to be describing a similar error :

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825034

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#1895
