### ISSUE TITLE
Ansi sequence for clicks sometime out of range

### ISSUE THREAD

**Issue by Lindydancer** [termux/termux-app#501]
Hi!

I noticed that the ANSI escape sequences that Termux send to applications that corresponds to clicks sometimes are out of range. This happens when clicking between the display and the keyboard. This has the unfortunate consequence that it confuses applications like Emacs.

Background:

When touching the Termux screen, the following escape sequence is emitted:

    ESC [ < 0 ; COL ; LINE M ESC [ < 0 ; COL ; LINE m

Where COL and LINE represent the column and the line if the click, encoded as ascii strings.

When clicking on the first line, the LINE is "1". When clicking on the last line of, say, a display ten lines high, it is "10".

The problem occurs if you tap the screen a little bit below the display, but above the keyboard. Then LINE will be "11", which is out of range. This, unfortunately, triggers Emacs into believing that you clicked on the menu bar.

I haven't checked if the same problem exists for COL, but presumably it does.

If you want to check the escape sequences that Termux emits, you can start Emacs. Click on various locations and then type C-h l (which runs the command `view-lossage`). You will also note that if you tap very low on the screen, the text "Menu Bar (up/down ..." appears in the minibuffer, which it shouldn't.

This doesn't appear to be a problem when the keyboard is hidden.

    -- Anders Lindgren

**Comment by sdrausty** [comment]
Much more information about your device is requested.  Use `termux-info` for the information requested.  Include relevant screenshots to encourage potential developers.  Suggest a solution, if possible.  Thank you for posting this issue and for addressing it at the correct wiki.  Nice title. 😀💎

**Comment by Lindydancer** [comment]
Hi!

On Fri, Dec 8, 2017 at 1:19 AM, S D Rausty <notifications@github.com> wrote:

> Much more information about your device is requested. Use termux-info for
> the information requested.
>
I'm using a Samsung S7. The following is from `termux-info`:

    ...
    Android version:
    7.0
    Device manufacturer:
    samsung
    Device model:
    SM-G930F

The problem occurs both when using the built-in keyboard and Hackers
Keyboard.

Include relevant screenshots to encourage potential developers.
>
I'll post it if you really need it. (I'm new to Android and Termux, so it
would require some work om my part.)


> Suggest a solution, if possible.
>

I see two possible solutions to this:

1) Limit the LINES value, so that it's never higher than the number of
visible lines, as in `line = min(line, number_of_lines)`.

2) Ignore clicks in this area. One scenario is that the user is typing on
the keyboard and touches the keys a little bit too high.

Thank you for posting this issue and for addressing it at the correct wiki.
> Nice title. 😀💎
>
You're welcome.

    -- Anders

**Comment by fornwall** [comment]
> 1) Limit the LINES value, so that it's never higher than the number of
visible lines, as in `line = min(line, number_of_lines)`.
> 2) Ignore clicks in this area. One scenario is that the user is typing on
the keyboard and touches the keys a little bit too high.

Thanks! I went for (1) now, so that click on the terminal-coloured area are always sent to the terminal. The change will be out in a v0.59 update of the app, which will be available within an hour or so on Google Play and within a day or so on F-Droid.

**Comment by Lindydancer** [comment]
Hi!

I just tested the updated Termux application, and the patch seems to work
perfectly! Thanks!

    -- Anders
