### ISSUE TITLE
sshd error

### ISSUE THREAD

**Issue by pierreraby** [termux/termux-app#502]
Termux run on my tablet with lineage OS (android 6.0.1) and and I just installed openssh.
I generated my ssh keys and put my public key in authorized_keys file.
I run sshd and connect with my linux desktop with the classic command : 
`ssh 192.168.1.X -i .ssh/my_key -p 8022`
but after entering my passphrase -> Connection to 192.168.1.X closed by remote host
In logs with logcat -s 'syslog:*' , there is : 
` Accepted publickey for ...` 
key seems OK

But after there is : 
`../....../sshd - fatal: chown(dev/pts/1, 1078, 1078) failed: permission denied`

I've googled and and I couldn't find anything.
Any idea ?

thanks in advance.

**Comment by fornwall** [comment]
You seem to be hitting this block in pty_setowner() from sshpty.c:

```c
if (st.st_uid != pw->pw_uid || st.st_gid != gid) {
        if (chown(tty, pw->pw_uid, gid) < 0) {
                if (errno == EROFS &&
                    (st.st_uid == pw->pw_uid || st.st_uid == 0))
                        debug("chown(%.100s, %u, %u) failed: %.100s",
                            tty, (u_int)pw->pw_uid, (u_int)gid,
                            strerror(errno));
                else
                        fatal("chown(%.100s, %u, %u) failed: %.100s",
                            tty, (u_int)pw->pw_uid, (u_int)gid,
                            strerror(errno));
        }
}
```

- Which arch is this on (what is the output of `uname -m`)?
- What is the output of running `ls -la $(tty)` and `whoami` in your normal Termux terminal?
- You didn't run sshd as root, right?

**Comment by pierreraby** [comment]
here are the results of the different commands : 
`uname -a
Linux localhost 3.0.101-gcf8656e #1 SMP PREEMPT Sat Aug 5 10:28:45 CEST 2017 armv71 Android`
and
`ls -la $(tty)
crw-------   1       u0_a78     136,     0Dec     11 10:32      /dev/pts/0`
and
`whoami
u0_a78`

NB: Sorry , I don't know why but after checking it out, sshd was running as root ... Sorry
There are no problems!
