### ISSUE TITLE
how to set LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by tel13908519494** [termux/termux-app#504]
i need to use dalvikvm in /data/data/com.termux/files/usr/bin to run java code。HOW TO SET the LD_LIBRARY_PATH when i need to load the /system/lib。THANKS

**Comment by xeffyr** [comment]
Why you need LD_LIBRARY_PATH ? **Dalvikvm** script in $PREFIX/bin/dalvikvm disabled LD_LIBRARY_PATH by doing ```unset LD_LIBRARY_PATH```. After that linker will use hardcoded path to /system/lib.
