### ISSUE TITLE
Erase sequences should not be affected by current coloring

### ISSUE THREAD

**Issue by xiaq** [termux/termux-app#51]
This will color the whole termux terminal red: `echo -e '\033[41m\033[J'`. No other terminal emulators that I know of exhibit this behavior.

This is because termux fill the affected area with the current foreground and background coloring when it receives the erase area sequence `\033[J`.

The erase line sequence, `\033[K`, is also affected.

**Comment by fornwall** [comment]
Thanks, will look into this!

When I test default (1) the OS X Terminal.app, (2) iTerm and (3) xterm they all seem to do the same thing as Termux here.

This seems to come from these terminals supporting the `background color erase` functionality. See e.g. [this bug](https://dev.haiku-os.org/ticket/6143) about this behaviour where it was added to another terminal emulator.

Which terminal emulators have you tested with that does not use the the current fg and bg colors when clearing?

**Comment by xiaq** [comment]
I don't have access to a real computer at this moment, will check a bit later.

**Comment by fornwall** [comment]
@xiaq Have you been able to check the issue? 

I think for `\033[J` and `\033[K` the background color should be used as argued above, but the original problem you had with Termux could be another issue perhaps?

**Comment by xiaq** [comment]
Hmm, I checked and it seems that every emulator but tmux fills the background color. My mistake.
