### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by Basti922** [termux/termux-app#512]
Can someone write a "how to connect my PC using putty to my phone via SSH"? 

All i found got me into errors over errors and pages which could be help full are offline e.g.

https://glow.li/tech/2015/11/06/run-an-ssh-server-on-your-android-with-termux.html

**Comment by Neo-Oli** [comment]
@Basti922 That page has a new link. https://glow.li/technology/2015/11/06/run-an-ssh-server-on-your-android-with-termux/
Sorry about that.
