### ISSUE TITLE
Is it possible to make work symlinks on mounted internal storage?

### ISSUE THREAD

**Issue by imShara** [termux/termux-app#513]
I want to make my project directory accessible from termux and other android application (e.g Syncthing). I made symlink from storage to termux home `ln -s ~/storage/shared/Projects/MyProject ~/MyProject`. It works until I need to make symlink in my project directory (e.g nodejs npm module requires it).

```bash
cd ~/MyProject
ln -s test.txt test2.txt
ln: test2.txt: Operation not permitted
```

Android disallows symlinks in /storage/emulated, but can termux workaround this?

**Comment by xeffyr** [comment]
> Android disallows symlinks in /storage/emulated, but can termux workaround this?

There only one workaround - put your files into Termux home ($HOME), this is limitation of Android.

**Comment by ExtremeNerd** [comment]
If it was binary, you had a workaround using shell script...

**Comment by apolbox** [comment]
is my problem too.
i want to create symlink myproject to default-site Apache.

for editing with application Our code editor not editor from termux, ex: micro, nano.

**Comment by eliaspizarro** [comment]
Maybe can be done with similar termux-setup-storage script method?

**Comment by xeffyr** [comment]
> Maybe can be done with similar termux-setup-storage script method?

**Symlinks are not possible under /storage/emulated/0. It is not possible to use features that is not implemented in FS.**

If you want symlinks - do this on **EXT4** or **F2FS** file system which is typically /data partition, i.e. $HOME.

**Comment by Quasic** [comment]
Some other systems have the same problem. There are sometimes ways around this, such as in nodejs code, making a file that includes the target. If the file is static, and not too large, it is often simply copied.

**Comment by xeffyr** [comment]
Closing because of https://github.com/termux/termux-app/issues/513#issuecomment-425093840.

**Comment by S1mple-x** [comment]
> is my problem too.
> i want to create symlink myproject to default-site Apache.
> 
> for editing with application Our code editor not editor from termux, ex: micro, nano.

> just change the default-site to your project
> edit `httpd.conf` in `/data/data/com.termux/files/usr/etc/apache2/httpd.conf`
> edit the `DocumentRoot` option:
> `DocumentRoot /path/to/your/project`

**Comment by S1mple-x** [comment]
@apolbox 

> just change the default-site to your project

> edit `httpd.conf`: 
> `/data/data/com.termux/files/usr/etc/apache2/httpd.conf`

> edit the `DocumentRoot` option:

> `DocumentRoot /path/to/your/project`
