### ISSUE TITLE
Termux crashed after npm package install (--unsafe-param)

### ISSUE THREAD

**Issue by ParkourKarthik** [termux/termux-app#514]
Termux was working properly.
I had installed many packages.

I recently installed `@angular/cli`  using `npm` .

After many unsuccessful attempts, i had to use `--unsafe-param` while installing the `@angular/cli`  since i was using termux as root (as shell had problems with permissions)

It almost got installed(ng commands were working). Finally, when restarting Termux, the following error is thrown:

```
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": library "libncursesw.so.6" not found

[Process completed (signal 6) - press Enter]
```

- On custom ROM
- Rooted (Magisk)

P.S: all the newly installed `npm packages`  are working fine in the stock terminal after setting the respective environment variables.

Update: The `symlink` for the library `libncursesw.so.6` exists in `lib`  folder pointing to itself.

**Comment by Grimler91** [comment]
So that error is thrown but you are able to check for the libncursew.so.6 lib? 
How? Fail-safe session? 

It shouldn't be necessary to use termux as root, permission errors indicate that some other problem. Did you installing @angular/cli in the shared storage?

Sounds like you have messed up your environment. 
> after setting the respective environment variables.

Which env vars have you been playing around with? 

> CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": library "libncursesw.so.6" not found

Most likely mean that LD_LIBRARY_PATH isn't set correctly, so try making sure that it is set to `/data/data/com.termux/files/usr/lib`, maybe by exporting it in the .bashrc.

**Comment by ParkourKarthik** [comment]
@Grimler91 You're right I've messed up the environment. As you said, I also thought of the same LD_LIBRARY_PATH variable being not set. But i had no idea from where i have to set it such that termux picks it up in the app startup.

But currently, I've considered uninstalling and reinstalling the whole termux including the packages.

But this time, I'm using everything without root. Even when I face some errors, I'm changing the ownership of the files such that they are usable by termux shell.

Finally, I've recreated the setups back properly :relaxed:.

Thanks for your response @Grimler91. I'd be happy if I have some info on how the environment variables are set by termux app while initializing the app.

**Comment by Grimler91** [comment]
> But this time, I'm using everything without root

Sounds wise!

The environment variables that are termux specific are exported by the app: https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/BackgroundJob.java#L114

After that, everything happens as on a normal Linux distribution, profile, .bashrc and other files are sourced (I'm not really an expert on when or which files are sourced).

**Comment by Muhaiminkp** [comment]
@ParkourKarthik   i am faceing this proplem how change all ownership [iam face permission denide because this file is installed with sudo) help me

**Comment by its-pointless** [comment]
if you have moved files around with root this triggers selinux security.
The way around it is to copy files that aren't working (can be done as root) to a directory /sdcard/.
This is the the shared storage that all android apps can use and see. When you copy it there android will change date and ownership etc.
Once that is done copy it back from that directory to your termux directory and it will be fine.
