### ISSUE TITLE
Termux didn't start with libncursesw.so.6 error

### ISSUE THREAD

**Issue by blowUA** [termux/termux-app#515]
Termux start with next notification:

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": library "libncursesw.so.6" not found

[Process completed (signal 6) - press Enter]

Impossible to send any command. Is there any chance to save the environment?

**Comment by Quasic** [comment]
This resembles #514. Is your phone rooted? Have you changed environment variables?

**Comment by blowUA** [comment]
phone is root. mediapad m3. android 7
thanks didn't know about failesaife mode. Usually if it happened I use ES explorer.

**Comment by fornwall** [comment]
If you cannot repair the system easily, I think the best course of action is to start a failsafe session as noted above, and then run

    rm -Rf $PREFIX

Then exit the session and restart Termux, after which a new system installation will be done.

You will loose all installed packages (but you can of course just reinstall them with `pkg install ...`, but your $HOME dir will be left intact, so you shouldn't loose any important data.

**Comment by blowUA** [comment]
After "rm -rf $PREFIX" Termux env wan't to start. Situation repeat twice in last few days. At this time was absent "libtermux-exec".
Probably its happens after I put yarn's repo in sourses list.

**Comment by bhagwandassony1** [comment]
![Screenshot_20200805-054516](https://user-images.githubusercontent.com/69147279/89374043-ca63b200-d6d9-11ea-872c-d62222ce31b6.png)

**Comment by bhagwandassony1** [comment]
Not even a single command working.

**Comment by Grimler91** [comment]
@bhagwandassony1 Have you tried reinstalling the app? Have you messed up the termux environment by for example trying to use the android 7 repositories on an android 5 or 6 device?

I guess you are on android 5 or 6 considering the warnings, note that we no longer support android 5 or 6.
