### ISSUE TITLE
[Package request] samefile

### ISSUE THREAD

**Issue by Wolfram-Wolf** [termux/termux-app#519]
http://www.schweikhardt.net/samefile/

**Comment by Wolfram-Wolf** [comment]
I've even made a termux compatible .deb package based on samefile(2.14).

**Comment by Atavic** [comment]
Both fine packages, but requests to into https://github.com/termux/termux-packages

**Comment by Wolfram-Wolf** [comment]
Closing issue in favour of termux-packages repo
