### ISSUE TITLE
[Package request] potrace

### ISSUE THREAD

**Issue by Wolfram-Wolf** [termux/termux-app#520]
http://potrace.sourceforge.net/

**Comment by Wolfram-Wolf** [comment]
I've even made a termux compatible .deb package based on potrace(1.15).

**Comment by Atavic** [comment]
Packages can be requested at https://github.com/termux/termux-packages/issues

**Comment by Atavic** [comment]
Packages can be requested at https://github.com/termux/termux-packages/issues
Same for #519

**Comment by Wolfram-Wolf** [comment]
Closing issue in favour of termux-packages repo
