### ISSUE TITLE
su is not working anymore 

### ISSUE THREAD

**Issue by Hamza-Megahed** [termux/termux-app#527]
I'm trying to use su on termux but it's not working anymore

![1](https://user-images.githubusercontent.com/2940656/34468021-c70c48d6-ef07-11e7-8e34-75aea22951b2.jpg)

**Comment by Grimler91** [comment]
This is most likely not a termux problem but rather a problem with your su. 
What does the logs of your su app say?

**Comment by Hamza-Megahed** [comment]
got blocked by SuperSU Free, i need SuperSU pro
