### ISSUE TITLE
INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES

### ISSUE THREAD

**Issue by dg41510** [termux/termux-app#531]
Application fails to install on brand new Android device running kernel version 3.10.49 (jenkins@80b25755b68d #1 Fri Aug 18 23:17:19 JST 2017)

adb install C:\com.termux_59.apk
C:\com.termux_59.apk: 1 file pushed. 2.4 MB/s (223374 bytes in 0.089s)
        pkg: /data/local/tmp/com.termux_59.apk
Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]

Application is not installed so cannot be uninstalled (already know about that solution from google - doesn't work)

Unknown sources are enabled

Device is a Kyocera DuraXE flip phone

**Comment by xeffyr** [comment]
> Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]

If you have installed Termux with Termux addons (sich as Termux:API, Termux:Widget, etc), and want to install a custom Termux app, make sure that **all apps (termux and addons) signed with the same key**.
