### ISSUE TITLE
termux error on update

### ISSUE THREAD

**Issue by macerg** [termux/termux-app#532]
3 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1067 kB of archives.
After this operation, 905 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/libnghttp2_1.29.0_aarch64.deb (--unpack):
 subprocess dpkg-split returned error exit status 11
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg

**Comment by Grimler91** [comment]
What did you run?

**Comment by macerg** [comment]
Any pkg update or pkg install I run gives a similar result. Eg, pkg install autossh

**Comment by Grimler91** [comment]
Which arch and so on are you on? `uname -a`
Which device is it on?
What were you doing before it stopped working?

**Comment by macerg** [comment]
uname -a
Linux localhost 3.18.19+ #1 SMP PREEMPT Sat Dec 10 21:57:17 CST 2016 aarch64 Android

Doing nothing different, just been using phone as normal. Just though "haven't done an 'apt update' for a while" So I did and got the error.
