### ISSUE TITLE
use rsync will get this error tip:rsync: failed to set times on “xxxx”: Operation not permitted

### ISSUE THREAD

**Issue by candrwow** [termux/termux-app#533]
when i use it with command:
"rsync -av root@45.76.186.26:/testPoo /storage/emulated/0/testpic",
it will tip this error(rsync: failed to set times on “xxxx”: Operation not permitted),but the files under testPoo are all sync into testpic successfully.the termux also tip "rsync erro :some files/attrs were not transferred(see previous errors)(code 23)at /home/fornwall/.termux-build/rsync/src/main.c(1650)[generator=3.1.2]"
this is transfer file from ubuntu to android,but file from android to ubuntu is no this error tip and successfully.
I search with google ,it tells me can chown to fix this,but on android /etc/rsync.conf is read-only.how to fix this error (transfer file from android to ubuntu)?
Thank U.

**Comment by Grimler91** [comment]
It's because you're syncing into shared storage and android doesn't allow certain properties there for security reasons.

Either rsync to a folder in $HOME or ignore the error/warning.

**Comment by trygveaa** [comment]
Or don't use the `-a` flag, so rsync won't try to set those properties.

**Comment by candrwow** [comment]
Thank U，I try use $HOME on android is success,but it's data/data/,maybe cause other app can't open the file that sync success.I change the option -av to -rvz or -rv,the termux will not tip this error,google tells that -rvz dont get the file attribute.
you say ignore the error/waring but i dont know which option can ignore these error tip,i try  --ignore-existing   --ignore-missing-args     --ignore-errors  and other,but not work.

**Comment by Quasic** [comment]
That's right. The -a option won't get the file attributes; but few of these attributes can be set without error outside of termux space, anyway.

To ignore the errors means to not alter the command, let them come, and then filter them out, which could be done through a pipe, I suppose, if you really don't want to see them. I just filter in my head, because I like the reminder that the time and attributes will be different.
