### ISSUE TITLE
Patch for "sticky" Ctrl and Fn (when using volume keys)

### ISSUE THREAD

**Issue by vit1-irk** [termux/termux-app#54]
This feature is very important and useful, but Termux doesn't have it now (but Connectbot and some other terminals have).
It's very tediously to hold, for example, "VolumeDown+C" **together** to close app.

I have done the patch for it. Apply to `TerminalView.java` please. Thanks in advance.

```
88a89,91
>   boolean wasControl=false;
>   boolean wasFn=false;
> 
317a321
>                   resetVirtualKeys();
579a584
> 
630c635
<       if (controlDownFromEvent || mVirtualControlKeyDown) {

---
>       if (controlDownFromEvent || mVirtualControlKeyDown || wasControl) {
654c659
<       } else if (mVirtualFnKeyDown) {

---
>       } else if (mVirtualFnKeyDown || wasFn) {
770a776,778
>           if (down) {
>               wasControl=true;
>           }
774a783,785
>           if (down) {
>               wasFn=true;
>           }
777a789,793
>   }
> 
>   private void resetVirtualKeys() {
>       wasControl=false;
>       wasFn=false;
```

**Comment by xeffyr** [comment]
Closing since Termux has [Extra Keys Row](https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row) for keys like CTRL. They are sticky here.

VolumeDown won't be sticky since doesn't have state indication.
