### ISSUE TITLE
grep only greps visible characters - screen width dependent

### ISSUE THREAD

**Issue by AngharadH** [termux/termux-app#540]
Strange behaviour noticed when writing a bash script which grepped for a command in ps x
The command was long, and if typed at the terminal would go off the screen when vertical, but not when horizontal.
Result, even in the script where no ps screen output was generated, the bash script failed in vertical orientation, but succeeded in horizontal orientation.
This suggests that grep is ignoring all characters in an output which are beyond the screen width.
Steps to reproduce:
Start playing something using mpv
Then type:
ps x | grep mpv
Observe how this succeeds if screen is horizontal, but fails if vertical

**Comment by fornwall** [comment]
I'm unable to reproduce it, and it sounds really strange.

Could it be something else? The mpv was perhaps not running when in landscape mode?

**Comment by trygveaa** [comment]
`ps` limits the output to the terminal width, so it cuts of long lines. Though, this should only happen when it prints directly to a terminal, and not when you pipe the result to something. This works for me, so I can't reproduce the problem either. But I would guess that it's more likely a problem with this detection in `ps`, than a problem with `grep`. You could check if the result from `ps x | cat` is cut off to confirm it.

**Comment by AngharadH** [comment]
See attached two screenshots. The alias "rsc" which plays the stream shown in the shots via mpv is started. I then grep for mpv with phone vertical (it fails), then with phone horizontal (it succeeds). 
Clearly it is running in the first instance - (a) the screen shows it has started, (b) I can hear it.
In the horizontal image, you can see the output from the first run of the command still. I simply rotated, and re-ran the command.
![screenshot_2018-01-13-22-57-08](https://user-images.githubusercontent.com/35385240/34910888-e6a9808e-f8b5-11e7-811a-8ed8b32cc4ad.png)
![screenshot_2018-01-13-22-57-36](https://user-images.githubusercontent.com/35385240/34910889-e6e27a88-f8b5-11e7-8bd0-3b3d43c54def.png)

**Comment by sdrausty** [comment]
@AngharadH Thank you for the screenshots.  What is the name of your keyboard?

**Comment by sdrausty** [comment]
@AngharadH Thank you for the screenshots.  What is the name of your keyboard?  Do you think this keyboard might be causing the error?  If the keyboard is open source, can you post the link?

**Comment by AngharadH** [comment]
I'm using the Huawei Swype keyboard on an Honor 7

**Comment by Quasic** [comment]
These are apparently the build settings, for reference from https://github.com/termux/termux-packages/blob/master/packages/busybox/busybox.config:
`````
CONFIG_PS=y
# CONFIG_FEATURE_PS_WIDE is not set
# CONFIG_FEATURE_PS_LONG is not set
CONFIG_FEATURE_PS_TIME=y
CONFIG_FEATURE_PS_ADDITIONAL_COLUMNS=y
# CONFIG_FEATURE_PS_UNUSUAL_SYSTEMS is not set
`````

**Comment by f3flight** [comment]
@AngharadH I think that the problem is in ps, not grep, ps in termux limits output to screen width, and you're not handling that. I recommend to use pgrep instead of ps, it has a flag for full command line search, and you'll only need 1 command instead of 2. I think this can be closed.

**Comment by Grimler91** [comment]
@f3flight Thanks.
