### ISSUE TITLE
nokogiri -v 1.8.1 need help 

### ISSUE THREAD

**Issue by chemostafa** [termux/termux-app#541]
Hi 
I need help plz 

gem install nokogiri -v 1.8.1
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.1/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20180115-2217-sb3png.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:407:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/nokogiri-1.8.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.1 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/nokogiri-1.8.1/gem_make.out
$ gem install nokogiri -v 1.8.1
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.1/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20180115-2321-1fgcb4h.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:407:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/nokogiri-1.8.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.1 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/nokogiri-1.8.1/gem_make.out
$

**Comment by Atavic** [comment]
Related: https://github.com/termux/termux-packages/issues/2021

**Comment by sdrausty** [comment]
Try `gem install nokogiri -- --use-system-libraries`.

**Comment by chemostafa** [comment]
Thanks you very much its solved 

apt install ruby-dev libxml2-dev libxslt-dev pkg-config make clang

gem cleanup
gem install nokogiri -v 1.8.1

**Comment by Atavic** [comment]
Close this, @chemostafa

**Comment by chemostafa** [comment]
OK and thanks for help in
https://github.com/termux/termux-packages/issues/2042

**Comment by pro-src** [comment]
I had an issue with this as well.

```sh
NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install nokogiri:1.6.8.1 -- --use-system-libraries --with-xml2-include=/data/data/com.termux/files/usr/include/libxml2 --with-exslt-include=/data/data/com.termux/files/usr/include/libexslt
```

Solved it for me. The environment variable may not be necessary. It seems like I've had problems installing nokogiri on every version of Termux. What keeps causing this breakage?

**Comment by mansurabbas** [comment]
pls i install beef-xss normal procedure and it installed.But when i try to run it by "beef" it shows the following error :

 Could not find nokogiri-1.8.1 in any of the sources
Run `bundle install` to install missing gems.

I saw answer to the solution in this wonderful and helping forum ( gem install nokogiri-1.8.1 and bundler -v and bundle install). It install nokogiri-1.8.1 and clone Gemfile in my /$HOME but still when i try to run by "beef" it still shows :

Could not find nokogiri-1.8.1 in any of the sources
Run `bundle install` to install missing gems.

                                             pls help me, Thanks in advance.

**Comment by sabarish7** [comment]
this may clear all the errors in the metasploit and install a fresh version without any gem error including nokogiri .etc


pkg install unstable-repo
pkg install metasploit 
msfconsole

it takes long time to install❤❤

**Comment by fahadali32** [comment]
> Related: [termux/termux-packages#2021](https://github.com/termux/termux-packages/issues/2021)

Bro i get again erorr what i do now
