### ISSUE TITLE
Running pkg as root breaks pkg for non-root users

### ISSUE THREAD

**Issue by yeahnope** [termux/termux-app#542]
After accidentaly running "pkg upgrade" on a root bash, I can no longer use pkg from a non-root bash:
```
$ pkg list-installed
E:_ can not open /data/data/com.termux/files/usr/var/lib/apt/lists/termux.net_dists_stable_InRelease - fopen (13: Permission denied)
E: The package lists or status file could not be parsed or opened.
$
```
Is there any easy way to fix this besides reinstalling everything?
Even though it's obviously user-error, maybe a check in pkg would be nice to prevent this?

**Comment by Grimler91** [comment]
Try fixing what it complains about, chown /data/data/com.termux/files/usr/var/lib/apt/lists/termux.net_dists_stable_InRelease to your termux UID. 

A small check in pkg is a good idea.

**Comment by Quasic** [comment]
If termux commands don't fix it, you can then try restorecon (see #335)

A check in apt or pkg would be good, maybe with a switch to override. (I think someone posted they purposely used apt as root, but I don't remember why.)

**Comment by Justsoos** [comment]
I've got similar issue, first, **sshd was broken**, the ssh client can not log on with correct certificate, although the sshd port is active, and `pkg` **got a few errors**:
```
 $ pkg update
Hit:1 https://termux.net stable InRelease
Reading package lists... Error!
W: Problem unlinking the file /data/data/com.termux/files/usr/var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /data/data/com.termux/files/usr/var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
E: Problem renaming the file /data/data/com.termux/files/usr/var/cache/apt/srcpkgcache.bin.DSBfNN to /data/data/com.termux/files/usr/var/cache/apt/srcpkgcache.bin - rename (13: Permission denied)
E: Could not open file /data/data/com.termux/files/usr/var/lib/dpkg/status - open (13: Permission denied)
E: Problem opening /data/data/com.termux/files/usr/var/lib/dpkg/status
E: The package lists or status file could not be parsed or opened.
```
and then I check all bad owner files with `find -user root` and change all the files to `u0_a364:u0_a364` which is my own termux's user id.

but sshd not work by that time.
I run `restorecon` to every file referred from above. 
Now, seems all has been back to right way...

**Comment by fornwall** [comment]
Thanks to @l-jonas the latest version of `pkg` now bails out with an error when run as root!
