### ISSUE TITLE
"su" never returns

### ISSUE THREAD

**Issue by cfaber** [termux/termux-app#543]
After upgrading to Android 8.0 on a Oneplus 3, running the latest SuperSU, the "su" command now fails as it locks up. ctrl+c / ctrl+z have no affect. It may be a problem with SuperSU, however the version of SuperSU worked in earlier versions of Android so I suspect the problem is an incompatibility with Oreo.

**Comment by Grimler91** [comment]
It's probably an issue with the su binary your using (and hence not related to termux). 
Check the logs of the superuser app. See this quite recent issue: https://github.com/termux/termux-app/issues/527.

**Comment by cfaber** [comment]
I do have SuperSU pro, and there is no logged requests indicated. When I look at the su binary it's

/data/data/com.termux/files/user/bin/su is calling /sbin/su. On Oreo it's systemless setup. 

Any suggestions? Other apps requesting SU seem to work just fine.

**Comment by Grimler91** [comment]
Try running `tsu` or the `/sbin/su` and see if that gives another behaviour.

**Comment by cfaber** [comment]
/sbin/su is what com.termux/files/user/bin/su is calling now and it locks up, tsu locks up as well.

**Comment by robsmith11** [comment]
I have the same issue after installing LineageOS 15.1 on my Redmi Note 4.

Have you found a solution?

**Comment by robsmith11** [comment]
FYI, my workaround is to just start sshd using su.  I then ssh to root@localhost and have a working root shell.

**Comment by xeffyr** [comment]
Closing since `su` binaries are not managed by Termux. If `su` binary is buggy, nothing can be done on Termux side.

The only suggestion can be is to install package `tsu` which is a wrapper for su binary and call `tsu` instead of `su`. May help in case if `su` binary doesn't work due to some environment variables.
