### ISSUE TITLE
How to access AWS server using termux

### ISSUE THREAD

**Issue by Ankur008** [termux/termux-app#546]
Is there any I can access aws server through termux. To access aws server through ssh , I need to login via pem file but I am not able to get how will I pass pem file in termux console?

**Comment by Quasic** [comment]
You've tried ```ssh -i path\to\file.pem aws.hostname``` with parameters replaced as appropriate? Ideally, I think the file should be in ~/.ssh with the other ssh keys. I don't know if chmod 400 is necessary, but it wouldn't hurt.

**Comment by fornwall** [comment]
See https://wiki.termux.com/wiki/Community for where to get possible help!
