### ISSUE TITLE
More python, please!

### ISSUE THREAD

**Issue by Almtesh** [termux/termux-app#55]
Would that be possible to have more Python libraries and Python3? I would like to code some projects for my phone.
Thanks.

**Comment by fornwall** [comment]
The `python` package is Python3, and the `python2` package is Python2. You can use `pip` to install more python libraries - re-open this issue if there is anything special you need packaged in Termux!

**Comment by Almtesh** [comment]
Indeed, I missed that, sorry. Thanks for the fast answer.
