### ISSUE TITLE
libtermux-exec.so is broken in 64bit arm

### ISSUE THREAD

**Issue by asynio** [termux/termux-app#551]
Fresh install on the new Fire 8" rev 5.

blackhole:~ $ ping www.google.com
CANNOT LINK EXECUTABLE DEPENDENCIES: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit
blackhole:~ $ uname -a
Linux localhost 3.18.19-gfdf437d4d32 #1 SMP PREEMPT Fri Jan 5 02:28:16 UTC 2018 armv8l Android

**Comment by xeffyr** [comment]
For me it is not broken, but I'm on Android:
```
bash-4.4$ echo $LD_PRELOAD
/data/data/com.termux/files/usr/lib/libtermux-exec.so
bash-4.4$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=46 time=41.8 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=46 time=44.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=46 time=43.9 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 41.806/43.300/44.136/1.058 ms
bash-4.4$ uname -a
Linux localhost 3.18.92+ #1 SMP Fri Jan 19 15:00:37 UTC 2018 aarch64 Android
```

**Comment by xeffyr** [comment]
Can you do `pkg install file` and then post output of command `file $PREFIX/bin/busybox`. This is needed to check architecture of installed binaries.

On aarch64 output should be like:
```
/data/data/com.termux/files/usr/bin/busybox: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped
```

**Comment by fornwall** [comment]
`$PREFIX/bin/ping` is just a wrapper for calling `/system/bin/ping`. This system binary seems to be 32-bit even on some 64-bit systems, so I think we should `unset LD_PRELOAD` before calling a system binary here. I've done that it in https://github.com/termux/termux-packages/commit/6b54ba3b69f4db1a7ba850e5459bfac08b275c46 now, in version 0.50 of termux-tools.

@asynio Can you verify that updating to the latest termux-tools package version (0.50) with `pkg up` fixes the problem?

**Comment by asynio** [comment]
@fornwall updating does correct.  Thanks!
