### ISSUE TITLE
termux-ubuntu

### ISSUE THREAD

**Issue by adricen** [termux/termux-app#554]
Hi, 

I can't manage to run ubuntu after install it with termux. I am on samsung galaxy j3 android 5.1.1

When I run `./start.sh`
I have this error message :
```
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
```

I do have thoses packages :

```
termux-api/stable,now 0.24 arm [installed]
  Termux API commands (install also the Termux:API app)

termux-apt-repo/stable 0.2 all
  Script to create Termux apt repositories

termux-create-package/stable 0.4 all
  Utility to create Termux packages

termux-elf-cleaner/stable 1.2 arm
  Cleaner of ELF files for Android

termux-exec/stable,now 0.3 arm [installed]
  An execve() wrapper to make /bin and /usr/bin shebangs work

termux-tools/stable,now 0.50 all [installed]
  Basic system tools for Termux

tsu/stable 1.1 all
  A su wrapper for Termux

```
Thx!

**Comment by Neo-Oli** [comment]
Can you please delete it and install it again. And post the output of the installation script. There might be errors in there.

**Comment by adricen** [comment]
Ok, 

So I deleted every content from the ubuntu package. 
Then :

```
wget https://raw.githubusercontent.com/Neo-Oli/termux-ubuntu/master/ubuntu.sh
--2018-01-26 10:40:51--  https://raw.githubusercontent.com/Neo-Oli/termux-ubuntu/master/ubuntu.sh
Resolving raw.githubusercontent.com... 151.101.60.133
Connecting to raw.githubusercontent.com|151.101.60.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2671 (2.6K) [text/plain]
Saving to: ‘ubuntu.sh’

ubuntu.sh    100%   2.61K  --.-KB/s    in 0s

2018-01-26 10:40:51 (9.27 MB/s) - ‘ubuntu.sh’ saved [2671/2671]

bash ubuntu.sh
downloading ubuntu-image
--2018-01-26 10:43:18--  https://partner-images.canonical.com/core/artful/current/ubuntu-artful-core-cloudimg-armhf-root.tar.gz
Resolving partner-images.canonical.com... 91.189.88.147
Connecting to partner-images.canonical.com|91.189.88.147|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34840365 (33M) [application/x-gzip]
Saving to: ‘ubuntu.tar.gz’

ubuntu.tar.gz          100%[===========================>]  33.23M  1.73MB/s    in 23s

2018-01-26 10:43:41 (1.46 MB/s) - ‘ubuntu.tar.gz’ saved [34840365/34840365]

decompressing ubuntu image
fixing nameserver, otherwise it can't connect to the internet
writing launch script
fixing shebang of start.sh
making start.sh executable
```

Now I have another error message :

```
./start.sh
groups: cannot find name for group ID 1015
groups: cannot find name for group ID 1028
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 50122
mesg: change /dev/pts/0 mode failed: Permission denied
```
Another issue but different this time.

**Comment by Neo-Oli** [comment]
Well then the first time there was probably a network error or something like that. The second error (can be tracked here: https://github.com/Neo-Oli/termux-ubuntu/issues/2) is normal for now. You can still use Ubuntu like this.

**Comment by zMaurizio00** [comment]
In one of my phones with lineage 14.1 the error: kernel too old.
In another newer one with the same software (always lineage 14.1) it works .... why does it say that the kernel is old?

**Comment by Neo-Oli** [comment]
@zMaurizio00 Excerpt from the proot manual:
>   -k *string*, --kernel-release=*string*
        Make current kernel appear as kernel release *string*.
        If a program is run on a kernel older than the one expected by its
        GNU C library, the following error is reported: "FATAL: kernel too
        old".  To be able to run such programs, PRoot can emulate some of
        the features that are available in the kernel release specified by
        *string* but that are missing in the current kernel.

So I'd suggest trying to play with that. 

(Porting a linux kernel to an android phone is really hard. So custom roms generally don't bother and just use whatever kernel the manufacturer supplies and build the rom ontop of it. So old phones will have old kernels, even if they run the same version of the rom)
