### ISSUE TITLE
Feature request: Option to (temporarily) hide the row with special on-screen keys, e.g., when a bluetooth keyboard is attached

### ISSUE THREAD

**Issue by tomtom** [termux/termux-app#556]
Users can long-press on the "keyboard" button in the sidebar to show a row of special on-screen keys. This makes termux much more accessible when users use non-specialized on-screen keyboards.

If users connect to a bluetooth/usb keyboard, the on-screen keyboard is hidden but the extra row is still being displayed and wastes screen space. While users could of course switch the row with special keys off by long-pressing on the "keyboard" button, I think this is unnecessarily cumbersome.

I would like to suggest to implement either one of the following changes:

1. Hide the row, when the on-screen keyboard is hidden.
2. Hide the row, when a hardware keyboard (bluetooth or usb) is being used.

I think this would improve the usability of termux.

**Comment by vganyn** [comment]
+

**Comment by Grimler91** [comment]
Similar to https://github.com/termux/termux-app/issues/556, let's track it there

**Comment by tomtom** [comment]
Are you saying issue #556 is similar to #556 which is why you close #556?

**Comment by Grimler91** [comment]
Ops, meant to paste https://github.com/termux/termux-app/issues/140
