### ISSUE TITLE
i cant open msfconsole terminal

### ISSUE THREAD

**Issue by loveablefellow007** [termux/termux-app#557]
I have downloaded all the necessory files aftwr i start the terminal error showing like values....etc.. like that

**Comment by Grimler91** [comment]
You will need to provide a more thorough report than this if we are to be able to help.

1. What did you run/how did you install?
2. What output do you get?

**Comment by loveablefellow007** [comment]
I exactly did like this screen shot.then all the files have
been.installed.the showing type msfconsole to start the program.so i did
then error msg like the last screenshot.
Help me with this!!
If i did anything wrong msg me the correct procedures step by step plzzz

On Jan 28, 2018 5:33 AM, "Henrik Grimler" <notifications@github.com> wrote:

You will need to provide a more thorough report than this if we are to be
able to help.

   1. What did you run/how did you install?
   2. What output do you get?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-app/issues/557#issuecomment-361026274>,
or mute the thread
