### ISSUE TITLE
Cannot close session with hardware keyboard

### ISSUE THREAD

**Issue by PhilippWoelfel** [termux/termux-app#560]
After ending a termux session (exit) it says to press enter. But doing so on a Bluetooth keyboard does nothing. Only way to close the session is to switch to the software keyboard.

**Comment by Grimler91** [comment]
Works fine for me, and has done so on the 3 or 4 different keyboards I've used. What kind of keyboard are you using?

**Comment by l-jonas** [comment]
@Phil11W If you don't reply (because it works?), please close this. If it still does not work, answer the question about the used keyboard.

**Comment by xeffyr** [comment]
Closing since Termux no longer requires to "press enter" in order to close session.
