### ISSUE TITLE
execute cling on termux  error

### ISSUE THREAD

**Issue by wangmu0579** [termux/termux-app#562]
I have built the cling on termux and make install.
All file installed at ~/tmp
Now execute cling can success but will premote some errors, Could someone help?
WARNING: linker: /data/data/com.termux/files/home/tmp/bin/cling: unused DT entry: type 0xf arg 0x275d2e
input_line_2:5:16: error: exception specification in declaration does not match previous declaration
extern "C" int atexit(void(f)()) throw () { return __cxa_atexit((void()(void*))f, 0, __dso_handle); }
^
/data/data/com.termux/files/usr/include/stdlib.h:53:5: note: previous declaration is here
int atexit(void (__fn)(void));
^
input_line_2:6:18: error: exception specification in declaration does not match previous declaration
extern "C++" int at_quick_exit(void(f)()) throw () { return __cxa_atexit((void()(void))f, 0, __dso...
^
/data/data/com.termux/files/usr/include/stdlib.h:57:5: note: previous declaration is here
int at_quick_exit(void (*__fn)());
^

****************** CLING ******************

Type C++ code and press enter to run it *
        Type .q to exit

**Comment by Quasic** [comment]
```termux-elf-cleaner``` can fix these errors: https://github.com/termux/termux-packages/blob/master/README.md#android-dynamic-linker
