### ISSUE TITLE
Proportional glyphs are stretched to match monospaced width

### ISSUE THREAD

**Issue by neoslaughter** [termux/termux-app#564]
First image is using Input Mono, and second is using Input Sans
![img_20180131_040111](https://user-images.githubusercontent.com/35081235/35609320-9a5684d2-063b-11e8-8031-e9dfcedb77a7.jpg)
![img_20180131_040127](https://user-images.githubusercontent.com/35081235/35609321-9a889760-063b-11e8-9705-64b1aa9bd137.jpg)

**Comment by Quasic** [comment]
If the characters are not all the same size, some displays that depend on this will look bad.

**Comment by fornwall** [comment]
Terminals just won't work with non-monospaced fonts, they are designed to expect a uniform grid.

Termux tries to stretch non-monospace fonts to equal width for all characters. It will work if there is only an occasional glyph that needs to be stretched, but with a fully non-monospaced font it will just look ugly as shown above. The only solution is to use a monospaced font.
