### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sadsouler** [termux/termux-app#570]
I can't instell jekyll using ruby

**Comment by Auxilus** [comment]
You are supposed to provide the errors and steps you used..

**Comment by Auxilus** [comment]
Also you have to move this issue to https://github.com/termux/termux-packages

**Comment by sadsouler** [comment]
Here is the error
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20180204-4805-1e2s5hd.rb extconf.rb
mkmf.rb can't find header files for ruby at /data/data/com.termux/files/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/http_parser.rb-0.6.0/gem_make.out
[gem_make.out.zip](https://github.com/termux/termux-app/files/1692493/gem_make.out.zip)

**Comment by Auxilus** [comment]
`ruby.h` is missing, install it by `apt install ruby-dev`

**Comment by Grimler91** [comment]
Closing since https://github.com/termux/termux-packages/issues/2095 was opened.

**Comment by sdrausty** [comment]
@Grimler9 can we add something similar like:
```
pacman -S base
pacman -S base-devel
```
in [Arch Linux in Termux PRoot](https://sdrausty.github.io/TermuxArch/) to `pkg`? For example:
```
pkg install base
pkg install base-devel
```
The first option would install `coreutils`, `findutils` and similar. Ditto for option two plus developers packages.
