### ISSUE TITLE
Add arrow keys

### ISSUE THREAD

**Issue by grayalias** [termux/termux-app#571]
Hi there, 

It will be very useful to have arrow keys in Termux similar to [TWRP]( https://twrp.me)'s terminal.
Thanks.

![screenshot_2018-02-04-00-05-18](https://user-images.githubusercontent.com/21147895/35774844-dec8b23a-09a5-11e8-8380-b69a4c2162e8.png)

**Comment by FuckDoctors** [comment]
UP and DOWN are really needed.
Hope the extra keys can be configurable.
or， swipe right to show more keys.

**Comment by xqdoo00o** [comment]
because of the lack of arraw keys, I have to use `JuiceSSH` to edit files.
 if arraw keys could be added, `JuiceSSH` is no longer needed.

**Comment by sdrausty** [comment]
Volume up + w = up arrow
Volume up + s = down arrow

*From https://termux.com/touch-keyboard.html*

**Comment by miho** [comment]
Or use something like the *CodeBoard* keyboard:

![screenshot_20180228-191936](https://user-images.githubusercontent.com/225266/36805036-9cf5d8e0-1cbc-11e8-9630-a38055ee2271.jpg)

**Comment by FuckDoctors** [comment]
@sdrausty yes，but not convenient。

**Comment by 4oo4** [comment]
Really surprised no one's mentioned Hacker's Keyboard yet:

https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en

**Comment by FuckDoctors** [comment]
@miho @4oo4 thx. but when i write something mixed with Chinese，i have to switch the en keyboard and Chinese keyboard witch each other。
while the Chinese keyboard can easily change to English mode by tapping a key, but doesn't have arrow keys.

**Comment by xqdoo00o** [comment]
@sdrausty on my pad, I have to use both hands to Volume up + w, it's too far to use single hand. 😅

**Comment by xqdoo00o** [comment]
I pull some code In #605, seems work fine on my phone.

**Comment by FuckDoctors** [comment]
@xqdoo00o well done. hope it will be merged later.

**Comment by sdrausty** [comment]
@FuckDoctors 
> but not convenient

On most smartphones this feature is very convenient.  I can see how this feature might be cumbersome as @xqdoo00o states on large tablet, and I have run into a couple of smartphone models where I must agree with you.  These models have the volume button(s) at the back of the unit.  After getting used to it, it's not as bad as at first.  The bending the device's shape effect isn't too pleasant when pressure to the button is applied.  As stated, on most devices volume + key is a beautiful shortcut.

**Comment by xqdoo00o** [comment]
@sdrausty yeah, but when editing files, sometimes need to move to big column, you have to pressed down `Volume up` then press `d` for many times. 
In #605 , just need to  long press `right arrow` key.

**Comment by sdrausty** [comment]
@xqdoo00o thanks for your time and attention.  Volume buttons at the back of the device make the volume+key feature cumbersome, clunky to use.  

> pressed down Volume up then press d for many times.

Volume buttons at the side of the device don't need to be pressure pressed down.  They  are simply held in palm of hand along with device.  

* Pressing a key many times while holding a device along with the volume button down at the edge of the device is not tiresome.  
* Pressing a key many times while holding a device along with pressure pressing the volume button down from the back is tiresome.  

Are there any ideas as to why CTRL+w doesn't work, but volume button up + w which is bound to CTRL+w does work for scrolling back through BASH history?

**Comment by l-jonas** [comment]
Wouldn't it be possible to add arrow keys to the "extended keyboard" (the thing that appears when you long-press the keyboard button in the menu)? Or event better, to make it customize able (e.g. adding a ":" for vim-users)?

**Comment by daemondev** [comment]
Hacker keyboard is better for any keyboard (anysoftkeyboard, codeboard, terminalide)

**Comment by dov** [comment]
I just got myself an android e-ink tablet that has neither volume buttons nor left drawer and I can't find any way of turning on the extended keyboard. Why isn't this setting available in the long press settings menu?
