### ISSUE TITLE
`am start` via ssh only works when Termux is in foreground 

### ISSUE THREAD

**Issue by agguser** [termux/termux-app#573]
While Termux is in foreground, running e.g. `am start --user 0 -a android.settings.SETTINGS` through `ssh` (on laptop, with Termux's `sshd` running on mobile) works; but if Termux is in background, nothing happens. While termux-api e.g. `termux-open` through `ssh` works in both cases.

(I use a Xiaomi phone, with MIUI 9.2 (Android 7))

**Comment by Quasic** [comment]
I think this may be why I have trouble controlling the wakelock over ssh after a while. I'll try to do some testing when I have time.

**Comment by agguser** [comment]
It seems that after (automatically) installing new `termux-am`, this problem is solved now. Thanks!
