### ISSUE TITLE
su or tsu not working

### ISSUE THREAD

**Issue by tgc12** [termux/termux-app#574]
After updating to 0.6.0 neither su nor tsu are working, they don't give any feedback.
They simply do nothing.

**Comment by fornwall** [comment]
@tgc12 Thanks for reporting! Try opening an issue at https://github.com/cswl/tsu to get help!

**Comment by tgc12** [comment]
It isn't su or tsu fault, even running the su binary directly from magisksu path does nothing, not even asks for permission.
With every other app even terminal emulator it works as intended.
It must be termux problem, it's the only thing that has changed in my system before the bug.

**Comment by Grimler91** [comment]
@tgc12 check the logs in the su app and see if they say something.

**Comment by tgc12** [comment]
The logs in the su app (magisk) say nothing about termux, every other app is logged as usual.
If I use magisk hide to hide su for termux and run su again I get feedback as expected.

`$ su
No su program found on this device. Termux
does not supply tools for rooting, see e.g.
http://www.androidcentral.com/root for
information about rooting Android.`

If su is enabled nothing happens, it is not logged nor runs anything.

`$ su
$ su -c 'top'
$ su -c 'uname -r'`

When I run that same commands in Terminal Emulator (From F-Droid) they work.

`helium:/ $ su -c 'top -n 1 -m 2'
User 12%, System 18%, IOW 3%, IRQ 0%
User 8 + Nice 0 + Sys 12 + Idle 42 + IOW 2 + IRQ 0 + SIRQ 0 = 64

  PID USER     PR  NI CPU% S  #THR     VSS     RSS PCY Name
16198 root     20   0  12% R     1   9108K   1884K  fg top
16200 root     20   0   9% R     1  59940K  10448K  fg /system/bin/app_process
helium:/ $ su -c 'uname -r'
3.10.84-perf-gd0ca7ea-00494-g328b870`

**Comment by tgc12** [comment]
I don't know what the problem was, there must be something wrong with my configuration (termux).
A fresh install of termux did the trick.
Thank you.
