### ISSUE TITLE
Optional line wrapping

### ISSUE THREAD

**Issue by AidanRB** [termux/termux-app#58]
Certain commands, such as "curl http://wttr\.in/Munich" , only work correctly without line wrap on smaller screens.  An option to disable line wrap would be amazing.

**Comment by fornwall** [comment]
You can disable line wrapping by using terminal escape codes ([DECAWM—Autowrap Mode](http://vt100.net/docs/vt510-rm/DECAWM)), which works in any terminal! Use

    printf "\033[?7l"

to disable line wrapping, and then

    printf "\033[?7h"

to enable them again. So you can e.g. do the following:

    printf "\033[?7l"; curl http://wttr.in/Munich; printf "\033[?7h"
