### ISSUE TITLE
Error when launching msfconsole

### ISSUE THREAD

**Issue by Ublimjo** [termux/termux-app#580]
$ msfconsole
/data/data/com.termux/files/usr/lib/ruby/2.4.0/psych.rb:377:in `parse': (/data/data/com.termux/files/home/metasploit-framework/config/database.yml): mapping values are not allowed in this context at line 9 column 25 (Psych::SyntaxError)
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/psych.rb:325:in `parse'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/psych.rb:252:in `load'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/psych.rb:472:in `open'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/psych.rb:472:in `load_file'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/ui/console/driver.rb:179:in `initialize'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /data/data/com.termux/files/usr/bin/msfconsole:48:in `<main>'

**Comment by Auxilus** [comment]
This issue should be in github.com/termux/termux-packages

Can you try
```
wget https://Auxilus.github.io/auxilus.key
apt-key add auxilus.key
echo "deb [trusted=yes,arch=all] https://Auxilus.github.io/ termux extras" >> $PREFIX/etc/apt/sources.list
pkg update
pkg install metasploit-framework
```

**Comment by Ublimjo** [comment]
$ msfconsole
/data/data/com.termux/files/usr/bin/msfconsole:50: unknown regexp options - data
