### ISSUE TITLE
[feature request] at command

### ISSUE THREAD

**Issue by amunizp** [termux/termux-app#582]
This would reduce dependence on the external tasking app.

Man page:https://linux.die.net/man/1/at

**Comment by Quasic** [comment]
See termux/termux-packages#2031

**Comment by amunizp** [comment]
Thank you. "At" is also hard to find as an issue. Please close and or label es duplicate of #2031

Sorry for your time.

**Comment by Quasic** [comment]
No problem, completely understandable. ;-)

I expect someone will be along to close this shortly.
