### ISSUE TITLE
Notification lets someone close Termux, or aqcuire / release wakelock when screen is locked

### ISSUE THREAD

**Issue by raphj** [termux/termux-app#584]
Termux notification has an "exit" button  and an "acquire (release) wakelock" button. These buttons are displayed in the notification even while the screen is locked.

This might allow unwanted closing of Termux (or wakelock release, or battery drain).

Should these buttons be disabled when the screen is locked?

**Comment by l-jonas** [comment]
@raphj The buttons are locked (tested at Android 7). Which Android version are you using?

**Comment by raphj** [comment]
I tested on Nougat (AICP) and it is the same thing on Oreo (Lineage) on 
a Lenovo P2 phone.

Not locked here ;-)

**Comment by l-jonas** [comment]
@raphj It's related to your system settings.

1. You can select globally if notifications should appear at the lock screen, should appear at the lockscreen with sensitive things hidden or should not appear at the lock screen.
2. You can select the same thing per App (but only more secure or equal to the global setting).

If you chose to hide sensitive contents (which is in general a good idea if you setup a lockscreen and you are asked about that when you setup one), then the buttons are not shown until you authenticate.

**Comment by raphj** [comment]
All right, thanks!
