### ISSUE TITLE
Almost all executables inside a newly installed termux app SEGFAULTS 

### ISSUE THREAD

**Issue by Eskender-B** [termux/termux-app#585]
- First I built a debug version from source n installed it worked fine.
- After 2 or 3 weeks i reinstalled the same apk and executables such as ls or pkg segfaults all the time
- I have not upgraded my phone or installed a different apk.
- Termux downloads and sets up things when first opening. Could there be something different you have added in the last month that causes this?
- Any help would be appreciated

**Comment by Grimler91** [comment]
Sounds like https://github.com/termux/termux-packages/issues/2066. There's an issue with some ROMs (on aarch64 and android 6?) and libtermux-exec.so. Workaround for now: `rm $PREFIX/lib/libtermux-exec.so`.

**Comment by Eskender-B** [comment]
how do you remove libtermux-exec.so when the rm command itself segfaults?

**Comment by Grimler91** [comment]
Ah yes, you might need to start a fail-safe session: https://wiki.termux.com/wiki/Recover_a_broken_environment#Launching_a_Failsafe_Session

**Comment by Eskender-B** [comment]
Thanks it works fine now.
