### ISSUE TITLE
How to fix this problem with deeplink in npm install find-remove?

### ISSUE THREAD

**Issue by mht-rhn** [termux/termux-app#587]
When I execute

<code>$ npm install find-remove</code>

it returns with this.

<code>
npm ERR! path ../rimraf/bin.js
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink
npm ERR! Error: EACCES: permission denied, symlink '../rimraf/bin.js' -> '/storage/emulated/0/COCWarA/node_modules/.bin/rimraf'
npm ERR!  { Error: EACCES: permission denied, symlink '../rimraf/bin.js' -> '/storage/emulated/0/COCWarA/node_modules/.bin/rimraf'
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, symlink '../rimraf/bin.js' -> '/storage/emulated/0/COCWarA/node_modules/.bin/rimraf'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'symlink',
npm ERR!      path: '../rimraf/bin.js',
npm ERR!      dest: '/storage/emulated/0/COCWarA/node_modules/.bin/rimraf' },
npm ERR!   stack: 'Error: EACCES: permission denied, symlink \'../rimraf/bin.js\' -> \'/storage/emulated/0/COCWarA/node_modules/.bin/rimraf\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../rimraf/bin.js',
npm ERR!   dest: '/storage/emulated/0/COCWarA/node_modules/.bin/rimraf',
npm ERR!   parent: 'discord-coc-war-announcer' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2018-02-14T10_16_13_680Z-debug.log
</code>

Any solution for this issue?

**Comment by Grimler91** [comment]
You need to install the modules in $HOME, Android doesn't allow it in shared storage. See for example https://github.com/termux/termux-packages/issues/43 and https://github.com/termux/termux-packages/issues/1979.

**Comment by qwertzguy** [comment]
@Grimler91 how do you do that?

**Comment by qwertzguy** [comment]
For others having this issue, you can use yarn install --no-bin-links (should also work with Mom)
