### ISSUE TITLE
Error while installing bufferutil

### ISSUE THREAD

**Issue by mht-rhn** [termux/termux-app#589]
When I execute this code

<code>$ npm install bufferutill</code>

This shows up

<code>
> bufferutil@3.0.3 install /data/data/com.termux/files/home/node_modules/bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/bufferutil-v3.0.3-node-v59-android-arm.tar.gz
prebuild-install info looking for cached prebuild @ /data/data/com.termux/files/home/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.3-bufferutil-v3.0.3-node-v59-android-arm.tar.gz
prebuild-install http request GET https://github.com/websockets/bufferutil/releases/download/v3.0.3/bufferutil-v3.0.3-node-v59-android-arm.tar.gz
prebuild-install http 404 https://github.com/websockets/bufferutil/releases/download/v3.0.3/bufferutil-v3.0.3-node-v59-android-arm.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.5.0 runtime=node arch=arm platform=android)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Linux 3.18.19
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/home/node_modules/bufferutil
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN discord.js@11.3.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of libsodium-wrappers@^0.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN home@1.0.0 No description
npm WARN home@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.3 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2018-02-14T14_57_44_037Z-debug.log
</code>

Any solution for this issue?

**Comment by fornwall** [comment]
> stack Error: Can't find Python executable "python", you can set the PYTHON env variable

Try `pkg install python` to install the python package. You will probably need to install some -dev packages as well.

The issue tracker is probably not the best forum for this - see https://wiki.termux.com/wiki/Community for where you can ask around for help!
