### ISSUE TITLE
How can I re-view my files from the sd card?

### ISSUE THREAD

**Issue by Alexjh16** [termux/termux-app#590]
Hello guys, is that I wrote in termux' termux-setup-storge' and this generated as a kind of direct access from the home folder to the sd called' storage', and now that I want to enter through the file manager in the sd nothing appears 
and if I search for it by termux they appear as some types of symbols as if they were folders. 
What solution can there be?

thx for your help!

![28191444_1579980765424455_1972783105_n](https://user-images.githubusercontent.com/36542326/36317737-ec09d8d8-130b-11e8-9dbc-732acaeca0d8.png)

![28117440_1579980652091133_2082469688_n](https://user-images.githubusercontent.com/36542326/36317746-f09747f0-130b-11e8-8116-5d6495043b15.png)

![28108977_1579980505424481_1212299839_n](https://user-images.githubusercontent.com/36542326/36317750-f3d3198a-130b-11e8-96ac-03d59a7f1d0a.png)

 @fornwall  
@Auxilus

**Comment by empjustine** [comment]
Isn't the folder generated by `termux-setup-storage` `~/storage`? Can you see any data in the storage folder?

Are you using Android unified storage?

Did you upgrade Android/file manager app? Do this file manager have the storage/sd card permisions?

Your SD card is almost empty; Did you try list the contents on another device?

**Comment by empjustine** [comment]
Are the file names written in English?

Do you know what character set you use, if not?

**Comment by Alexjh16** [comment]
If that's the folder that generates termux for me.

I don't think my android is 5.1 and so I read a little bit, and that option is like for higher android. 

That file manager is the one that brings the phone by default, that manager does not have permissions, besides that use root files as an alternate app.

If in fact I entered it to a pc and the content as such but I couldn't change the attributes to the folders, that is to say they left the folders and when I opened them I didn't allow it.

Translated with www.DeepL.com/Translator

**Comment by Alexjh16** [comment]
If that's the folder that generates termux for me.

I don't think my android is 5.1 and so I read a little bit, and that option is like for higher android.

That file manager is the one that brings the phone by default, that manager does not have permissions, besides that use root files as an alternate app.

If in fact I entered it to a pc and the content as such but I couldn't change the attributes to the folders, that is to say they left the folders and when I opened them I didn't allow it.

**Comment by Alexjh16** [comment]
No, the folders are created in Spanish, but the language of the cell phone is in English.

I suppose it should be the UTF-8, but because it's or is in the Colombian region, do you think it's the ISO-8859-1?
Or do you think that matters at all?

**Comment by Grimler91** [comment]
/sdcard points to the standard internal storage (same as /storage/emulated/0), it doesn't point to the actual sdcard that you can insert/remove, so the two screenshots doesn't show the same folder. 

The I/O error is still weird though.

**Comment by Alexjh16** [comment]
No! on my cell phone when I type cd /sdcard directly it will show me everything I have in the external sdcard, i. e. the one that has 15GB.

Very different when typing cd--> /storage/sdcard1 && ls
It's gonna list the internal memory as such, which you refer to.

or typing $cd --->/storage/emulted/1.... In my case, of course.

Yes!... in both captures I wanted to show the external storage that I chose in termux 

Translated with

**Comment by dixonnixon** [comment]
Hello I couldnt write to my work dir 
Also i cant access from my filemanager to  
/data/data/com.termux/files/home

 
https://ibb.co/iacjp9
https://ibb.co/kxOw2U

**Comment by dixonnixon** [comment]
ref2solve 


https://github.com/termux/termux-app/issues/157

**Comment by xeffyr** [comment]
> Also i cant access from my filemanager to
/data/data/com.termux/files/home

@dixonnixon You can't access your $HOME with file manager. Even if all your files will have rwxrwxrwx permissions, SELinux will still block read or write access from other applications (on most ROMs), however there is an exception for applications that have **shared user id** between each other.

If you still want to do this - **your device should be rooted**.

> https://ibb.co/iacjp9
https://ibb.co/kxOw2U

Forget about doing `chmod +x` on shared storage (/sdcard). This will not work, just limitation of file system.

**Comment by xeffyr** [comment]
Closing since it is possible to access Termux home only from file managers properly using Storage Access Framework or if device is rooted.
