### ISSUE TITLE
unzip: can't Set permissions of Directory

### ISSUE THREAD

**Issue by mskian** [termux/termux-app#591]
How to fix this error?

while downloading a zip file from wget Method (bash script)
it will display the error Message while it unzipping the files/folders

```
unzip: can't set permissions of directory 'FOLERNAME/' Operation not permitted
```

PS: File unzipped successfully But I got this error while unzipping

**Comment by Grimler91** [comment]
Looks like you are downloading it into the shared internal storage. Android doesn't allow certain properties for files there for security reasons so unzip and many other programs output warnings/information like that when operating in shared storage. 

If you would download into $HOME instead then that message isn't shown.

**Comment by mskian** [comment]
@Grimler91 Let me Try & Update

**Comment by mskian** [comment]
@Grimler91  Perfect so we can view that error while installing the files via wget, git, cURL on Device Storage & SDcard right?

**Comment by Grimler91** [comment]
Yes, you get that warning/message in device storage/sdcard. 

Try for example: 
```
cd $HOME 
touch testfile
chmod u+x testfile 
# no message
cd /storage/emulated/0
touch testfile
chmod u+x testfile
# you get something like: chmod: changing permissions of 'testfile': Operation not permitted
```

**Comment by Taiwodivine** [comment]
How do I install the ngrok it doesn't work when I use chmod +x ngrok-stable-linux-arm.zip
