### ISSUE TITLE
Can't change default shell (Permission denied)

### ISSUE THREAD

**Issue by AtakanErmis** [termux/termux-app#592]
When I try changing the shell `chsh -s fish` I take the error message:

`ln: /data/data/com.termux/files/home/.termux/shell: Permission denied`

**Comment by aswinmohanme** [comment]
Can cofirm, same issue with fosh shell

**Comment by aswinmohanme** [comment]
Found a fix too

chmod 777 /usr/bin/fish

chsh -s /usr/bin/fish
