### ISSUE TITLE
Segmentation fault with non builtin shell commands

### ISSUE THREAD

**Issue by Samir-ouchene** [termux/termux-app#593]
I installed Termux on my Android phone. it was working well but now whenever I try to execute non-builtin shell commands I get a segmentation fault. I tried to uninstall and reinstall it, but that does not solve the problem
Here is a screenshot:
![segfault](https://user-images.githubusercontent.com/17838489/36344632-c2139ac4-141d-11e8-8cc1-7c5d84164321.png)

**Comment by its-pointless** [comment]
Known issue. 
https://github.com/termux/termux-packages/issues/2066

**Comment by Samir-ouchene** [comment]
Thank you very much. problem solved.
The steps (As you mentioned):
- Start a Failsafe session
- Remove the file libtermux-exec.so: `rm $PREFIX/lib/libtermux-exec.so`
- Restart Termux.
