### ISSUE TITLE
segmentation violation on typing any command

### ISSUE THREAD

**Issue by mayureshw** [termux/termux-app#597]
Just installed termux from Play Store on Android 6.0. I find that typing any command just results in segmentation violation.

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/2066, work around is to start a [fail-safe session](https://wiki.termux.com/wiki/Recover_a_broken_environment#Launching_a_Failsafe_Session) and remove `$PREFIX/lib/libtermux-exec.so`. This should be fixed in updated version of termux-exec though.

**Comment by mayureshw** [comment]
I have seen these instructions through web search, though no such option (fail safe) opens for me. If I long press it just shows "Copy" and "More" and in "More" there is no failsafe option.

**Comment by Grimler91** [comment]
@mayureshw You need to long press the "new session" button, not in the terminal.

**Comment by mayureshw** [comment]
Got it. It starts fine now. Thanks.
