### ISSUE TITLE
Android 8 proot info: pid xxx: terminated with signal 11

### ISSUE THREAD

**Issue by useruser456** [termux/termux-app#599]
Hi

I'm using proot on Android 8, 

proot: ELF executable, 32-bit LSB arm, static,
proot Version: v5.0.0-dirty
built-in accelerators: process_vm = no, seccomp_filter = no

I get this error:
Android 8 proot info: pid xxx: terminated with signal 11
Verbose output error:

proot error: can't create temporary file: No such file or directory
proot error: execve("/bin/bash"): No such file or directory

**Comment by Neo-Oli** [comment]
Run `unset LD_PRELOAD` before running proot to clear `/data/data/com.termux/files/usr/lib/libtermux-exec.so` which isn't available in whatever your proot jail is.

**Comment by useruser456** [comment]
Hi

did not help

I run this command:
./proot -r container/ -b /dev -b /sdcard -b /proc /bin/bash

now I get this error:
proot info: pid xxxxx: terminated with signal 11

**Comment by Neo-Oli** [comment]
Well does /bin/bash exist in the container?

**Comment by useruser456** [comment]
Yes,

-rwxrwxrwx 1 u0_a174 u0_a174 666864 2010-11-04 22:23 container/bin/bash

**Comment by Neo-Oli** [comment]
Ah, now you don't get the "No such file..." error anymore? 
```
terminated with signal 11
```
Probably means you're trying to run a binary that doesn't match your phone's architecture.

**Comment by useruser456** [comment]
Yes, you're right. 
/bin /bash is a 32 bit version.

Is there a way to run a 32-bit Linux container on a 64-bit host-architecture with proot ?

**Comment by xeffyr** [comment]
> Is there a way to run a 32-bit Linux container on a 64-bit host-architecture with proot ?

There probably no way because proot uses it's own loader for ELF binaries. It always compiled for the same architecture as a 'proot' binary.
