### ISSUE TITLE
bash | zsh scripts

### ISSUE THREAD

**Issue by stefanlendl** [termux/termux-app#60]
Hi I have a couple of bash and zsh cripts I wanted to use in termux.
with the shebang #!/bin/bash or /usr/bin/env bash it dosn't work because the the path /bin and so on is not present.
Is it possible to symlink it default linux location so the scripts can find it properly?

thank you

**Comment by stefanlendl** [comment]
ok.. i found the answer already..

**Comment by mholt** [comment]
... and the answer is...

**Comment by stefanlendl** [comment]
https://termux.com/linux.html

**Comment by mholt** [comment]
Ooooh, got it! Thanks.

Gonna quote the relevant parts here in case it changes or disappears:

> - Termux installs its packages in a folder exposed through the $PREFIX environment variable (with e.g. binaries in $PREFIX/bin, and configuration in $PREFIX/etc).
> - The normal #!/usr/bin/... she-bangs will not work. Use the termux-fix-shebang script to modify these files before executing.

**Comment by Stabledog** [comment]
That's a pretty ugly solution, since it makes scripts non-portable.  I have scripts that run in multiple environments, and the only place that they cannot run is Termux.

**Comment by Grimler91** [comment]
@Stabledog `termux-chroot` solves that for you!

**Comment by Stabledog** [comment]
Sounds promising... but I can't find any description of termux-chroot... is it a built-in package? what does it do, etc?  Seems like every reference to the /usr/bin/env problem recommends the termux-fix-shebang script, which I find rather horrifying!

**Comment by fornwall** [comment]
@Stabledog `termux-chroot` is a script provided by the `proot` package.

[PRoot](https://wiki.archlinux.org/index.php/Proot) is an implementation using ptrace to fake a chroot without requiring root privileges.

**Comment by Stabledog** [comment]
@fornwall, @Grimler91 : thanks... glad to have a new path to explore :)
