### ISSUE TITLE
rounding errors in python

### ISSUE THREAD

**Issue by meeuw** [termux/termux-app#604]
When I convert a float to string I get weird rounding errors using Python 3.6.4:
```
$ python3
Python 3.6.4 (default, Jan  7 2018, 03:53:53)
[GCC 4.2.1 Compatible Android Clang 5.0.300080 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> str(0.1)
'0.10000000000000001'
```
According to the documentation it should display 0.1:
https://docs.python.org/3/tutorial/floatingpoint.html

I'm running termux on a Asus C101P Chromebook (ARMv8 processor).

**Comment by iRomanyshyn** [comment]
Oops, I made duplicate bug #617 with same problem.

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#2236
