### ISSUE TITLE
Need some help..

### ISSUE THREAD

**Issue by dAtiuy** [termux/termux-app#606]
What is this?
apt unpdate
E: Invalid operation unpdate
$ apt update
Hit:1 https://termux.net stable InRelease
Err:2 https://Auxilus.github.io termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
Reading package lists... Done
W: GPG error: https://Auxilus.github.io termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
E: The repository 'https://Auxilus.github.io termux InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (extras/binary-arm/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list:4
W: Target Packages (extras/binary-all/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list:4
W: Target Packages (extras/binary-arm/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list:5
W: Target Packages (extras/binary-all/Packages) is configured multiple times in /data/data/com.termux/files/usr/etc/apt/sources.list:3 and /data/data/com.termux/files/usr/etc/apt/sources.list:5

**Comment by dAtiuy** [comment]
How can I fix it

**Comment by Auxilus** [comment]
Can you try
```
pkg install dirmngr
gpg --keyserver pgpkeys.mit.edu - MIT PGP Key Server --recv-key  A02DAB86B7A6E4BE
gpg -a --export A02DAB86B7A6E4BE | apt-key add
echo "deb [trusted=yes,arch=all] https://Auxilus.github.io/ termux extras" >> $PREFIX/etc/apt/sources.list
pkg update
pkg install metasploit-framework
```

**Comment by dAtiuy** [comment]
Same

**Comment by dAtiuy** [comment]
It also happens when I try any type of command like apt update pkg install

**Comment by Auxilus** [comment]
You'd have to use the script then, until I figure out what's wrong

https://Auxilus.github.io/metasploit.sh

**Comment by Auxilus** [comment]
Also remove lines from sources.list which point to my repo

**Comment by dAtiuy** [comment]
.... I'm lost lol

**Comment by dAtiuy** [comment]
Update 
Hit:1 https://termux.net stable InRelease
Err:2 https://Auxilus.github.io termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
Reading package lists... Done
W: GPG error: https://Auxilus.github.io termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A02DAB86B7A6E4BE
E: The repository 'https://Auxilus.github.io termux InRelease' is not signed.

**Comment by dAtiuy** [comment]
Same shit again

**Comment by Grimler91** [comment]
Every update of apt resets trusted.gpg meaning all imported gpg keys are lost. In your case you lost Auxilus key and apt could then no longer if packages were trustworthy. Real solution would havr been to reimport the public key with apt-key.

**Comment by barre121** [comment]
Same error.
 i can't  reinstall the app Cause i have alot in it.
What should i do?

**Comment by barre121** [comment]
thanks!
Solved by removing
The 2 lines from the sources.list
i was getting close to be crzy!
Thankz again.

**Comment by Seliniux777** [comment]
======================================================================: command not found

     //|___  ____  ____  ____  ______       __          //|___
   _|/|/ _ \/ __ )( __ )/ __ \/ ____/ ___  / /______  _|/|/ _ \
  / _ / // / __  / __  / / / /___ \  / _ \/ //_/ __ \/ _ / // /
 / __ \___/ /_/ / /_/ / /_/ /___/ /_/  __/ ,< / /_/ / __ \___/
/_/ |_|  /_____/\____/\____/_____/(_)___/_/|_|\____/_/ |_|


======================================================================: command not found

 Hostname :  localhost °https://sdrausty.github.io/TermuxArch°
 Username :  °B805.eko°
 Date :  18.03.2018
 Time :  19:33
 tput cup 15 1
Linux #1 SMP PREEMPT Fri Jan 12 21:17:25 CST 2018 aarch64
 tput setaf 1
bash: /data/data/com.termux/files/home/.bashrc: line 30: unexpected EOF while looking for matching ``'
bash: /data/data/com.termux/files/home/.bashrc: line 31: syntax error: unexpected end of file
%n@%m:%~%#

**Comment by mansurabbas** [comment]
pls, i remove "termux-exec" it started giving /data/data/com.termux/files/usr/bin/pkg: 28: /data/data/com.termux/files/usr/bin/pkg: apt: not found error 

please help me.

i'm looking forward to hearing from you.
Thank you....

**Comment by Neo-Oli** [comment]
@mansurabbas So you removed apt (because it depends on termux-exec)? Apt screams bloody murder when you're trying to remove it. You had to type "Yes, do as I say!" or something and you still did it? **Why?!**

Well, now you don't have a package manager. Your best bet is to download apt and termux-exec from http://termux.net and try to reinstall it.
```
wget http://termux.net/dists/stable/main/binary-`dpkg --print-architecture`/termux-exec_0.3_aarch64.deb
wget http://termux.net/dists/stable/main/binary-`dpkg --print-architecture`/apt_1.4.8-2_aarch64.deb
dpkg -i termux-exec_0.3_aarch64.deb
dpkg -i apt_1.4.8-2_aarch64.deb
```

Other solutions:
Completely reinstalling Termux or running `rm -rf $PREFIX` and restarting Termux to wipe all non-user data and reinstall everything.

**Comment by MonaLiu421** [comment]
i have the same error ,when i install R ，it happens，what should i do？？？

**Comment by xeffyr** [comment]
@MonaLiu421 Remove repository `https://Auxilus.github.io` - it's broken.

**Comment by philipjuma97** [comment]
bash: termux-packages/packages/bash/etc-bash.bashrc: No such file or directory
usage: command-not-found <command>
bash: /data/data/com.termux/files/usr/etc/bash.bashrc: line 4: syntax error near unexpected token `}'
bash: /data/data/com.termux/files/usr/etc/bash.bashrc: line 4: `}'
bash-5.0$

**Comment by c34d57** [comment]
$ pgk search double
No command pgk found, did you mean:
 Command ack in package ack-grep
 Command pr in package coreutils
 Command pub in package dart
 Command duk in package duktape
 Command awk in package gawk
 Command gh in package gh
 Command gs in package ghostscript
 Command gpg in package gnupg
 Command go in package golang
 Command gpgv in package gpgv
 Command gm in package graphicsmagick
 Command gc in package graphviz
 Command kak in package kakoune
 Command k in package kona
 Command psl in package libpsl
 Command mg in package mg
 Command pee in package moreutils
 Command tgz in package mtools
 Command pick in package nmh
 Command php in package php
 Command pick in package pick
 Command pil in package picolisp
 Command pigz in package pigz
 Command ps in package procps
 Command pup in package pup
 Command pv in package pv
 Command rg in package ripgrep
 Command psc in package sc
 Command ag in package silversearcher-ag
 Command pkg in package termux-tools
 Command wg in package wireguard-tools
 Command wrk in package wrk
$ unstable: pgk install unstable-repo
unstable:: command not found
$ install a package: package install<penghubbung apk>-[A
bash: penghubbung: No such file or directory
$ upgrade packages: pgk upgrade
No command upgrade found, did you mean:
 Command cf-upgrade in package cfengine
 Command db_upgrade in package db
 Command ppmfade in package netpbm
 Command pg_upgrade in package postgresql
 Command uftrace in package uftrace
$ command selesai aku ingin langkah-langkah selanjutnya/untuk aplikasi penghubung wallet ke game
selesai: command not found
$ command selesai aku ingin langkah-langkah selanjutnya/untuk aplikasi penghubung wallet ke game124588
selesai: command not found
$ command in now free                             No command in found, did you mean:                 Command id in package coreutils
 Command i3 in package i3 from the x11-repo repository
 Command iw in package iw from the root-repo repository
 Command inc in package nmh
 Command ip in package termux-tools
 Command sn in package tin-summer
$ #termux on freenode
$ command in now free                             No command in found, did you mean:                 Command id in package coreutils
 Command i3 in package i3 from the x11-repo repository
 Command iw in package iw from the root-repo repository
 Command inc in package nmh
 Command ip in package termux-tools
 Command sn in package tin-summer
$ pengarang
pengarang: command not found
$ https://pengubung game dengan wallet wd
bash: https://pengubung: No such file or directory
$ recueasee
recueasee: command not found
$ buat aktif
No command buat found, did you mean:
 Command bat in package bat
$
$
$ pgk install x11-repo
No command pgk found, did you mean:
 Command ack in package ack-grep
 Command pr in package coreutils
 Command pub in package dart
 Command duk in package duktape
 Command awk in package gawk
 Command gh in package gh
 Command gs in package ghostscript
 Command gpg in package gnupg
 Command go in package golang
 Command gpgv in package gpgv
 Command gm in package graphicsmagick
 Command gc in package graphviz
 Command kak in package kakoune
 Command k in package kona
 Command psl in package libpsl
 Command mg in package mg
 Command pee in package moreutils
 Command tgz in package mtools
 Command pick in package nmh
 Command php in package php
 Command pick in package pick
 Command pil in package picolisp
 Command pigz in package pigz
 Command ps in package procps
 Command pup in package pup
 Command pv in package pv
 Command rg in package ripgrep
 Command psc in package sc
 Command ag in package silversearcher-ag
 Command pkg in package termux-tools
 Command wg in package wireguard-tools
 Command wrk in package wrk
$ alamat addreess
No command alamat found, did you mean:
 Command aapt in package aapt
 Command clambc in package clamav
 Command animate in package imagemagick
 Command lame in package lame
 Command slapcat in package openldap
 Command pacat in package pulseaudio
 Command blkcat in package sleuthkit
 Command arara in package texlive-bin
 Command lzcat in package xz-utils
$ alamat situs
No command alamat found, did you mean:
 Command aapt in package aapt
 Command clambc in package clamav
 Command animate in package imagemagick
 Command lame in package lame
 Command slapcat in package openldap
 Command pacat in package pulseaudio
 Command blkcat in package sleuthkit
 Command arara in package texlive-bin
 Command lzcat in package xz-utils
$ log-up
No command log-up found, did you mean:
 Command nohup in package coreutils
 Command logger in package inetutils
 Command loqui in package loqui from the x11-repo repository
 Command logcat in package termux-tools
 Command losetup in package util-linux
 Command lzgrep in package xz-utils
$
$
$
$ command apk
No command apk found, did you mean:
 Command ack in package ack-grep
 Command apt in package apt
 Command awk in package gawk

**Comment by philipjuma97** [comment]
Pkg or apt not pgk

**Comment by andanesia** [comment]
Hello World
