### ISSUE TITLE
Xidel not working, cannot find the OpenSSL library

### ISSUE THREAD

**Issue by Invictaz** [termux/termux-app#607]
Hello,

I installed OpenSSL-tool and OpenSSL-dev but still this error when I try to run Xidel.
And yes I know that Freepascal is 32 bit based and my phone (Samsung Galaxy A3) is 64 bit based. But you cannot install a 32 bit i686 version of openSSL in Termux.
My phone is not rooted. 

If I type find / -name libssl.so i get only "permission denied" types of messages.

![sidesync_capture_20180304145910_1](https://user-images.githubusercontent.com/20338545/36946433-4d34a814-1fbd-11e8-83c8-b7ce36929c12.jpg)

**Comment by Invictaz** [comment]
Open SSL 1.0.2n ARM is installed

**Comment by Invictaz** [comment]
This is the error I get when trying to run Xidel 

![sidesync_capture_20180304152802_1](https://user-images.githubusercontent.com/20338545/36946721-9dc339c2-1fc1-11e8-971a-362571fe693f.jpg)

I tried with LD_PRELOAD but dit not work

**Comment by Grimler91** [comment]
From where did you install xidel?

**Comment by Invictaz** [comment]
@Grimler91 No just the normal apt install openssl 

Where to check if it is arm64/aarch64? 

Xidel was just unpacked from 

https://sourceforge.net/projects/videlibri/files/Xidel/Xidel%20development/

And then xidel-0.9.7.20180212.6044.d4409b959988.androidarm.tar.gz

**Comment by Invictaz** [comment]
When setting the LD Library path to LD_LIBRARY_PATH=/data/data/com.termux/files/usr/etc/tls
It does not work

![sidesync_capture_20180304174334_1](https://user-images.githubusercontent.com/20338545/36947967-c80b88f8-1fd3-11e8-84a7-f4a3c37a4bd2.jpg)

**Comment by Grimler91** [comment]
Right, your phone is arm 32bit then.

I'm guessing that the xidel binary you are trying to run was built against another version of openssl. Try compiling xidel from source instead of running the downloaded binary.

**Comment by Grimler91** [comment]
Alright, my mistake.

**Comment by Invictaz** [comment]
Xidel needs to be placed in /data/data/com.termux/files/home/

And then it works :)

Many thanks to @zpimp for all the help

![screenshot_20180310-221308](https://user-images.githubusercontent.com/20338545/37315003-172a203a-264f-11e8-93e2-249741571495.png)
