### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by SuperOP535** [termux/termux-app#609]
Sorry, I'm not used to Linux commands so I forgot about using `chown`, problem solved

**Comment by sdrausty** [comment]
@SuperOP535 https://duckduckgo.com/&q=beginner+linux+site%3Atldp.org

> not used to Linux commands



The learning curve for Linux is steep and quick, if you devoted the effort into reading, doing and learning.  With Termux and its' complementary programming, we are no longer chained to buildings and rooms with computers.  We have freedom with Termux; Linux on the go!
