### ISSUE TITLE
Reverting termux-setup-storage?

### ISSUE THREAD

**Issue by SuperOP535** [termux/termux-app#610]
I want to do an action on all files and folders (recursively) on the $HOME folder and I don't want my `storage` to get affected

**Comment by Neo-Oli** [comment]
`rm -r storage`. 
This will remove the symlinks in your home directory. This will suffice for your use.
If you want to truly revert all `termux-setup-storage` did you'll also have to open the app settings and remove the storage permission.

**Comment by SuperOP535** [comment]
Thanks
