### ISSUE TITLE
Cannot execute 32-bit binary on 64-bit device

### ISSUE THREAD

**Issue by ViRb3** [termux/termux-app#611]
My device is running Android 8.1, arm64v8. I have a binary compiled for arm32v7. Whenever I try to execute it via Termux, it gives me this error:
```
CANNOT LINK EXECUTABLE "/path/to/targetBinary": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
```

This works on other terminal emulators, since 32-bit is fully compatible with 64-bit.
Thanks!

**Comment by Grimler91** [comment]
libtermux-exec.so is 32bit, it is loaded through LD_PRELOAD. 
Unset LD_PRELOAD before running your binary and it will succeed.

**Comment by ViRb3** [comment]
Thanks! Is there any way to unset the variable automatically/every time I start a terminal?

**Comment by sdrausty** [comment]
Edit your `.bash_profile` is the default answer.  If your 🐚 shell isn't default, edit the appropriate dot file.

**Comment by ViRb3** [comment]
@sdrausty Cheers! If anyone is wondering, the default home directory `/data/data/com.termux/files/home` works perfectly.
