### ISSUE TITLE
37296/100=372.95999999999998

### ISSUE THREAD

**Issue by iRomanyshyn** [termux/termux-app#617]
python3 -c "print(37296/100)"                           372.95999999999998

Why?

Termux on Xiaomi Redmi Note 4X 3/32, Python 3.6.4. Python on PC doesn't steal 0.00000000000002.

**Comment by iRomanyshyn** [comment]
Checked it on GNURoot at same device and it works as expected. This problem is found only with Python on Termux.

**Comment by Grimler91** [comment]
Let's track this in the other issue.
