### ISSUE TITLE
suggestion: coreutils by default

### ISSUE THREAD

**Issue by InsideBall** [termux/termux-app#62]
I suggest that this app installs coreutils by default, and sets path correctly so they are used by default, by default.

I suggest this because the default shell is bash. This is pretty awesome. If you set coreutils by default, most bash scripts scripts written for GNU + Linux will run. Also, because, why not. These are Ghz+ multi-core devices we run on, with gigabytes of internal storage, no need for busybox.

I also suggest adding the net-tools package for networking.

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#178
