### ISSUE TITLE
pm2 and termux-boot

### ISSUE THREAD

**Issue by davemccrea** [termux/termux-app#621]
My termux-boot script is:

```
#!/data/data/com.termux/files/usr/bin/bash

termux-wake-lock
sshd
pm2 resurrect
```

`sshd` starts fine, but the `pm2 resurrect` command doesn't run - it works fine when I run it manually. Why is this?

**Comment by icew4y** [comment]
echo 'termux-wake-lock' > .bashrc
echo 'sshd' > .bashrc
echo 'ps -fe|grep pm2 |grep -v grep' >> .bashrc
echo 'if [ $? -ne 0 ]' >> .bashrc
echo 'then' >> .bashrc
echo '    pm2 resurrect' >> .bashrc
echo 'fi' >> .bashrc

**Comment by l-jonas** [comment]
Eventually related to https://github.com/termux/termux-app/issues/642

**Comment by eh2k** [comment]
```node /data/data/com.termux/files/usr/bin/pm2 resurrect``` seems to work.

**Comment by ortegafernando** [comment]
Hi, i have installed termux and termux:boot and I can run script at phone start up.
But I want also to start a new termux session that it has the ".bashrc" file like:

`pm2 resurrect`

But it is impossible for me. I want to see my phone at start up with 1 termux session in notification bar, so I could asure that it is working.

Do I need autostart program or similar? or could I use termux:boot and any kind of command to start a new termux session?

Thanks

**Comment by Grimler91** [comment]
@ortegafernando use a shebang that exists, change `#!/bin/sh` to `#!/data/data/com.termux/files/usr/bin/sh`

**Comment by ortegafernando** [comment]
Thanks, that way, when I reboot my mobile, I see in the notificacion bar: 0 session, 1 task.

Is there any posibility to run at script at boot that open 1 session so I can  open it when i restart my phone ?

Thanks

**Comment by ortegafernando** [comment]
Hi, sorry about, i have try this command directly in Termux

`am start --user 0 -n com.termux/com.termux.app.TermuxActivity`

And this is the command line answer: "Warning: activity not started, its current task has been brought to the front".

So may my only posibility is to use an like:
[https://play.google.com/store/apps/details?id=com.autostart](https://play.google.com/store/apps/details?id=com.autostart) ?

Is there any posibility to start a real Texmux session with Termux Boot ?

**Comment by Akszyn** [comment]
If I have an Android 6 phone, what should the a file that runs pm2 when run termux? because once i tried without pm2 and it didn't work either https://discourse.nodered.org/t/problem-in-installing-node-red-on-android/638/35?u=akszyn_pl
