### ISSUE TITLE
Add metadata for F-Droid

### ISSUE THREAD

**Issue by mueller-ma** [termux/termux-app#622]
The description in fdroid still says termux uses apt.
You might want to move the description in this repo and add screenshots, feature graphic and have the description translatable: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by xeffyr** [comment]
> The description in fdroid still says termux uses apt.

What's wrong with this ? Yes, Termux sill uses apt and *.deb package format, script 'pkg' is only a wrapper around apt.

**Comment by mueller-ma** [comment]
> script 'pkg' is only a wrapper around apt

I didn't know that. The name `pkg` is confusing as the FreeBSD package manger's name is also `pkg`.

**Comment by l-jonas** [comment]
@mueller-ma As this is resolved, could you close this issue please?

**Comment by mueller-ma** [comment]
> You might want to move the description in this repo and add screenshots, feature graphic and have the description translatable: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

I cannot see any fastlane files in this repo, so this is still open.

**Comment by l-jonas** [comment]
@mueller-ma 

> I cannot see any fastlane files in this repo, so this is still open.

That's a good description for the issue. But ```Description in fdroid outdated``` is not good. Please rename it to e.g. ```Add metadata for F-Droid``` (or create a new issue and close this one if that's not possible).
