### ISSUE TITLE
Failed to Install Nest on Termux

### ISSUE THREAD

**Issue by Richardn2002** [termux/termux-app#626]
I'm doing some AI project on my tablet.I find that there's a brain simulator called Nest(built from 1994).Now all libraries needed installed , Python ,Python,GCC going well,cmake config ran successfully
(but:
![screenshot_20180316-194746](https://user-images.githubusercontent.com/8529852/37553462-91743ddc-2a03-11e8-99ea-4806cad06043.png)
)
![screenshot_20180316-123339](https://user-images.githubusercontent.com/8529852/37553470-e6502578-2a03-11e8-9d26-ecea474870a4.png)

make started
![screenshot_20180316-123506](https://user-images.githubusercontent.com/8529852/37553473-f613ae80-2a03-11e8-8405-067b4be918e3.png)

then
my heart sank
![screenshot_20180316-123749](https://user-images.githubusercontent.com/8529852/37553468-d4a7af1c-2a03-11e8-9667-8a65a06361fb.png)

I tried multiple times and tried older versions of Nest but the error msgs were all the same.(tried disabling all optional functions of Nest)

I once suspected that it was the missing mach-o.h .....but Google results of mach-o.h were all about OSX dev...?

then I suspected that I was Missing some glibc
but ./configure in the glibc-2.9 didn't work for lack of permission(and I guess that termux have already set up c for us because no one was complaining about c right?)

what's wrong?

**Comment by Grimler91** [comment]
ˋ/sdcard/Python/The Project/nest-simulator-2.14.0/...ˋ
Move the code to your home directory and try again.

**Comment by richard20020815** [comment]
@Grimler91 not helping...everything was the same
(i'm thinking of buying a small Linux server...losing hope in termux.no.......)
any other ideas?
does it have something to do with permissions and why there are 2error says missing"("?

**Comment by richard20020815** [comment]
@Grimler91 
![screenshot_20180317-195257](https://user-images.githubusercontent.com/8529852/37555098-328444e2-2a1d-11e8-885e-5a1242e7a751.png)

**Comment by Grimler91** [comment]
> (i'm thinking of buying a small Linux server...losing hope in termux.no.......)

You have a bit too much faith in termux perhaps, it's a terminal emulator running on android, not a gnu/linux system. Many software requires some patching to work and that seems to be the case in this case.


Did you download the sources from http://www.nest-simulator.org/download/? 
I can have a quick look.

**Comment by richard20020815** [comment]
@Grimler91 yes I do

**Comment by Grimler91** [comment]
@richard20020815 It compiles without errors for me after I've installed dependencies, both on aarch64 and arm. Maybe you're missing some dependency, hard to tell without a full log.

**Comment by richard20020815** [comment]
@Grimler91 you mean you installed the dependencies listed on the site?
but many packages do not exist in termux's apt search
their name changed or something?

OK,suppose I have none of the packages listed on the site(except Python related)
what should I install?

(sorry for wasting your time...many questions may sound silly because I'm very new to termux)

full error log:
[CMakeError.log](https://github.com/termux/termux-app/files/1822151/CMakeError.log)

**Comment by Grimler91** [comment]
Please run `cmake . &> cmake.log` and post that log. 

I installed the dependencies that the cmake configuration said were necessary.
Python related packages, like cython, can be installed through pip: `pip install cython`.

**Comment by richard20020815** [comment]
maybe it's just because I don't know the names of the dependencies I need in termux xD

[cmake.log](https://github.com/termux/termux-app/files/1822617/cmake.log)

**Comment by richard20020815** [comment]
Lenovo TB-8703F

Linux localhost 3.18.24-perf-g29ace07 #1 SMP PREEMPT Wed Jun 28 14:54:18 CST 2017 aarch64 Android

(if you are still confused...that's OK.i am used to this tablet.Everything of this tablet is perfect except that it has an special os made for PRC with Google removed , bootloader locked and additional permission restrictions.For example,normal Google service installer fails on this device for lack of permission.Maybe it refused termux to access preinstalled c library or something like that.If so,i'm going to rent a cloud service instead to do my project.)

**Comment by twaik** [comment]
Closing this because it is not related to terminal-emulator and most probably dependency related.
