### ISSUE TITLE
When exiting Termux, pressing enter doesn't work on 8.0 on Galaxy S9+

### ISSUE THREAD

**Issue by Root-voidX** [termux/termux-app#627]
I dont know if this is a bug or a known issue, but on Galaxy S9+ running Android 8.0 when exiting termux by entering exit. You get the message to press enter when closing, but pressing enter doesn't work. I have to exit via notification from drop down menu.

**Comment by xeffyr** [comment]
Same problem on Samsung Galaxy S7 with Android 8.0. But it doen't happens always and I still able to close session after waiting some time.

**Comment by l-jonas** [comment]
@Root-voidX Is it like https://github.com/termux/termux-app/issues/126 (caused by the word prediction feature of Samsung virtual keyboard)?

**Comment by MickeyLane** [comment]
S9+ here - Go to Google Play (store) and select Gboard. In my case it was already installed. Open, push two buttons to enable and the termux character problem goes away. I don't recall if I restarted the phone or not.

**Comment by drunkwcodes** [comment]
Termux won't stop even with exit button in notification bar after SamSung upgrading devices to Android 9!

**Comment by xeffyr** [comment]
@drunkwcodes Solution is in https://github.com/termux/termux-app/issues/1094#issuecomment-486050462.
This cannot be solved from Termux's side. Also problem is Samsung-specific.

**Comment by xeffyr** [comment]
Sessions are now auto-closeable so issue shouldn't be significant now. Keyboard switching seems fixes problem too.

**Comment by drunkwcodes** [comment]
@xeffyr  Thanks!
