### ISSUE TITLE
Termux app for Android < 5 without packages

### ISSUE THREAD

**Issue by kaztost** [termux/termux-app#629]
Could you please port the Termux terminal emulator app for Android < 5 with /system/bin/sh as default shell (or different shell as an option).

I want to have the Termux app with its great touch support for midnight commander compiled by myself (people can use mc from Entware, Linux distributions, etc). 

I tried to port the Termux app by myself cloning the project and simply setting minSdk=17, but the Android Studio's code inspector found a lot of classes and methods not supported for  SDK < 21.

> [https://github.com/termux/termux-app/issues/6](https://github.com/termux/termux-app/issues/6) Would the app itself (without many packages) be interesting in itself for older versions, running just as a terminal emulator?

Yes, this would be great!

**Comment by sdrausty** [comment]
What about a coreutils+proot+curl package that can be used in Terminal Emulator as an alternative?  There is a youtube video of Arch Linux in [Terminal Emulator](https://github.com/jackpal/Android-Terminal-Emulator), but that method requires a cracked/rooted device.  A package that can sprout into a Linux on Android KitKat is desired by many of us.  This does not need to be in Termux app; It just needs to work on potentially tens of millions of Android devices.

From https://play.google.com/store/apps/details?id=jackpal.androidterm
```
Installs
10,000,000 - 50,000,000
 
Requires Android
1.6 and up
 ```

**Comment by kaztost** [comment]
My post is not about Termux packages for old devices. I just is asking to port the Termux emulator for them. As I understand the main reason why Termux is not running on Android 4.4 and earlier, is incompatible /system/bin/linker, so the port of the emulator only is generally  possible.

I know how to get binaries for these platforms. Also I know about Terminal Emulator, and I have used it (as well as ConnectBot too). But I like Termux emulator much more. Only Termux sends touches on the screen as mouse events for ncurses/slang. On big screens Midnight Commander  in such console  becomes very powerfull, fast and convenient in comparison with existsting Android file managers. Again, I am asking the terminal emulator for Android < 5, but not the binaries.

**Comment by sdrausty** [comment]
@kaztost Termux with binaries would be best.  It's not just the touches, which are great.  It is also the keyboard addition that makes Termux cool.  I undersood what you asked in you first comment.  Are you familiar with these https://github.com/termux/termux-app/issues?&q=kitkat issues; All the Android < 5 requests are closed and unresolved.

**Comment by ExtremeNerd** [comment]
Some binaries are portable across UNIX Systems by nature. Such as BusyBox, Toy box, and many packaged as tar.gz ....

What about creating a fake root system yourself using a shell script, with essential libraries & then implementing __dpkg__? 
I think it is a decent hack to get the thing done..

Or if you want to install some specific package, you may check out Debian Noroot on Google Play. Seems like there is a similar app on F-droid too..

**Comment by DoktorStein** [comment]
Indeed I think it would be useful to have **Termux app** (*with no packages*, maybe with **Termux:Styling**, **Termux:Float** etc) for **Android < 5** even though *there's plenty of terminal emulators for Android*, because Termux **has very useful unique features** (*sane copy/paste*, `Ctrl/Fn` shortcuts works with default keyboard, *pinch to change font size*, *customization through **Termux: Styling** *, *italic text* etc). This is specially true when running text editors like `vim` or `nano` because Termux handles **potrait/landscape** modes correctly (*all* other terminal apps I tried forces me to issue a `^L` to **redraw** after a **screen orientation change**).

**Comment by sdrausty** [comment]
I'd be useful to have control over Android (out of box) in palm of hand, correct?

**Comment by xeffyr** [comment]
Closing as no work for Android <7.0 is going to be done.
