### ISSUE TITLE
Random system freezes when starting new session via sidebar

### ISSUE THREAD

**Issue by DMSalesman** [termux/termux-app#630]
## Description

Sometimes, when starting a new session through the apposite button in the left sidebar, the whole system freezes after the session has started, in the midst of the bar hiding animation, prompting the need for a reboot by means of holding the `Power` button.

-----

## System info

OS: LineageOS 14.1
Android version: 7.1.2

Device: Samsung S4 Mini
Variant: I9195

Kernel: custom
Xposed installed: yes
Root: yes

`uname -a`: `Linux localhost 3.4.113-Remix-CM14-v.19-g63edfc9 #1 SMP PREEMPT Thu Oct 26 10:57:57 EDT 2017 armv7l Android`

-----

## Footnotes

It doesn't seem possible to trigger this apparent bug at will. Sometimes, it happens right after starting Termux; other times, it manifests when doing other work in the background. I was not able to capture it in a logcat yet.

As of now, it happened both with and without Xposed installed, and both on Marshmallow and Nougat.

If in need of more info, ask away.

**Comment by l-jonas** [comment]
@DMSalesman ```Kernel: custom```. Is it the Kernel of the official Lineage OS build for your device or something different?

**Comment by DMSalesman** [comment]
@l-jonas No, it's a kernel based on the official LineageOS one.

For now, the issue appears to have disappeared. If no freeze manifests in a day, I'll close the issue.

**Comment by DMSalesman** [comment]
Closing for now as the issue seems to be solved.

**Comment by DMSalesman** [comment]
@l-jonas The issue just reappeared. I'm afraid that, due to its sudden nature, a log cannot be captured. Still, if you need more info, feel free to ask.

**Comment by DMSalesman** [comment]
Now running Oreo, and the issue seems to be solved. Closing.
