### ISSUE TITLE
Unable to use irssi to send files grabbed by dcc to sdcard

### ISSUE THREAD

**Issue by cleon456** [termux/termux-app#637]
I've tried setting the dcc_download_path to /storage/shared/Download but it says operation not permitted.

**Comment by Grimler91** [comment]
Have you run termux-setup-storage?

**Comment by cleon456** [comment]
Yes, i have.

**Comment by Grimler91** [comment]
Might be nothing we can do then. Android doesn't allow some files in the shared storage for security reasons.

**Comment by cleon456** [comment]
I have figured out a workaround by creating a folder in the $HOME directory and sending files to it.

Then using the mv command to move it to the sdcard

**Comment by sdrausty** [comment]
@cleon456 can you?
```
$ touch storage/shared/Android/data/com.termux/file
$ l /storage/emulated/0/Android/data/com.termux/file
-rw-rw---- 1 everybody 0 Mar 29 02:02 /storage/emulated/0/Android/data/com.termux/file
```
Notice the difference between the two paths.  Your paths should be similar.

**Comment by cleon456** [comment]
It says:

    No command 'l' found, did you mean:
    Command 'ld' from package 'binutils'
    Command '[' from package 'coreutils'
    Command 'ln' from package 'coreutils'
    Command 'ls' from package 'coreutils'
    Command 'nl' from package 'coreutils'
    Command 'k' from package 'kona'
    Command 'lz' from package 'mtools'
    Command 'w' from package 'procps'
    Command 'sl' from package 'sl'
    Command 'ul' from package 'util-linux'

**Comment by sdrausty** [comment]
```
$ cat ~/.bashrc |grep ls
alias l='ls -alG'
alias lr='ls -alR'
alias ls='ls --color=always'
```
Use `ls -al` then to see.  If `touch` didn't complain like this:
```
touch: cannot touch 'no/path/to/file': No such file or directory
```
Your storage should be setup correctly; @cleon456 are you familiar with these links?

**Comment by sdrausty** [comment]
```
$ cat ~/.bashrc |grep ls
alias l='ls -alG'
alias lr='ls -alR'
alias ls='ls --color=always'
```
Use `ls -al` then to see.  If `touch` didn't complain like this:
```
touch: cannot touch 'no/path/to/file': No such file or directory
```
Your storage should be setup correctly; @cleon456 are you familiar with [these links?](https://duckduckgo.com/?q=.bashrc+.bash_profile+site%3Atldp.org)
