### ISSUE TITLE
Unable to save to sdcard

### ISSUE THREAD

**Issue by exquisitearcaneevenstar** [termux/termux-app#638]
So i can't make any file in sdcard using termux 
Nor with touch aaa.txt
Nor with youtube-dl
Nor with youtube-dl --external-downloader aria2c

Well it's a big deal for me btw i have setted up storage access in options and i can save to internal memory but not to external

**Comment by exquisitearcaneevenstar** [comment]
Btw I'm using oreo 8.1 custom rom if that matters

**Comment by Grimler91** [comment]
Have you run termux-setup-storage?

**Comment by exquisitearcaneevenstar** [comment]
Yes i did. 3 times

**Comment by Grimler91** [comment]
Nothing we can do then, android doesn't allow some file types in the shared storage. See also similar issue in https://github.com/termux/termux-app/issues/637 (and many other).

**Comment by sdrausty** [comment]
@exquisitearcaneevenstar can you?
```
$ touch storage/shared/Android/data/com.termux/file
$ l /storage/emulated/0/Android/data/com.termux/file
-rw-rw---- 1 everybody 0 Mar 29 02:02 /storage/emulated/0/Android/data/com.termux/file
```
Notice the difference between the two paths.  Your paths should be similar.

**Comment by exquisitearcaneevenstar** [comment]
touch storage/shared/Android/data/com.termux/file

l doesent work.. 
U probably mean ls -lah

ls -lah /storage/emulated/0/Android/data/com.termux/file
-rw-rw---- 1 u0_a182 everybody 0 Mar 29 09:44 /storage/emulated/0/Android/data/com.termux/file
