### ISSUE TITLE
Error installing fing using dpkg

### ISSUE THREAD

**Issue by kurokirasama** [termux/termux-app#640]
Hello,

I'm trying to install fing deb package but I got this error:
```
dpkg: error processing archive overlook-fing-3.0.deb (--install):
unable to clean up mess surrounding './usr' before installing another version: Read-only file system
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
overlook-fing-3.0.deb
```
I got the file from
https://www.fing.io/download-free-ip-scanner-desktop-linux-windows-osx/

**Comment by Grimler91** [comment]
You can't install packages that aren't compiled for termux. You could try it in termux-chroot but it probably won't work anyways. See https://wiki.termux.com/wiki/Differences_from_Linux.

**Comment by sdrausty** [comment]
This **is* SPAM afaict; Possible phishing link too.

**Comment by Grimler91** [comment]
@sdrausty Doesn't look like it to me.

**Comment by kurokirasama** [comment]
Thanks, I could install with chroot, but it doesn't execute.
Regards,

**Comment by sdrausty** [comment]
@kurokirasama is https://duckduckgo.com/?q=fing+github one of the fings you mentioned on this list?  If so, which one?  Ten hours have gone by, and I still have not a clue what this topic is about.  Without source code, there is not much that can be done.  Linux is not Windows™.

**Comment by kurokirasama** [comment]
Long story: I'm trying to get devices connected to a wifi network, like what android app fing does. Googling, i found that fing has windows and linux packages (rpm, deb ang pgz). I tried installing the deb package and i encounter the error. I have installed other not compiled for termux deb packages before (i don't remember which one now) so i give it a try... This one didn't work so i'll have to try something else.
Thanks for your comments.

**Comment by sdrausty** [comment]
Do you like riddles that can be answered?

**Answer 1.**
https://www.fing.io/fing-executable-license-agreement/ this link might be spear phishing?  Scripts to off before viewing recommended!

**Answer 2.**
https://play.google.com/store/apps/details?id=com.overlook.android.fing&hl=en_GB
Additional information
Updated
28 March 2018
Size
10M
Installs
10,000,000+
Current Version
6.7.1
Requires Android
4.1 and up
Content Rating
Everyone
Learn More
Permission
View details
Fing - Network Tools
Domotz Ltd
This app has access to:
Contacts
read your contacts
Location
precise location (GPS and network-based)
Photos / Media / Files
read the contents of your USB storage
modify or delete the contents of your USB storage
Storage
read the contents of your USB storage
modify or delete the contents of your USB storage
Camera
take pictures and videos
Wi-Fi connection information
view Wi-Fi connections
Other
receive data from Internet
view network connections
allow Wi-Fi Multicast reception
full network access
control vibration
prevent device from sleeping
Updates to Fing - Network Tools may automatically add additional capabilities within each group. Find out more

Q1 **Why does an IP scanning app want access to 📷 camera, contacts, location, microphone, photos and video?  Looks even more like phishing for information than it did before I took a closer look, doesn't it?**
Q2 **This is an Android app available on Google Play.  What is the reason behind this, and like issues?**

**Comment by kurokirasama** [comment]
Ok. Certainly, the app looks suspicious. 

I'm trying to do some things afterwards with the devices info. But now i have more reasons for not using fing to get the devices info. Thanks.

**Comment by sdrausty** [comment]
There are many tools available in Termux today.  Good luck in finding the ones that you want.  https://gitter.im/termux/termux/ and http://termux.com/community should be good places to ask, but first check to see if you might already have what you are seeking in Termux:
```
$ pkg list-all |grep net

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

inetutils/stable 1.9.4-5 aarch64
libnettle/stable,now 3.4 aarch64 [installed,automatic]
libnettle-dev/stable 3.4 aarch64
net-tools/stable 1.60.2017.02.21-1 aarch64
netcat/stable 7.70 aarch64
netpbm/stable 3094 aarch64
netpbm-dev/stable 3094 aarch64
nettle/stable 3.4 aarch64
```
With PRoot in Termux, the possibilities are almost endless!  https://sdrausty.github.io/TermuxArch/docs/install has more information about pentesting distributions that also do IP scanning.
