### ISSUE TITLE
Metasploit-framework error

### ISSUE THREAD

**Issue by JohnTa15** [termux/termux-app#641]
Hello,
So I Have this issue with my termux and I searched this issue on here but nothing... I need some help 
![screenshot_2018-03-29-09-42-52](https://user-images.githubusercontent.com/37906374/38095125-530e1012-3378-11e8-83e6-881ae81e649c.png)

**Comment by Auxilus** [comment]
I think tru building the gem locally

**Comment by JohnTa15** [comment]
how ?

**Comment by Auxilus** [comment]
```
gem unpack thin
cd thin<version>
wget https://github.com/macournoyer/thin/raw/master/thin.gemspec
gem build thin.gemspec
gem install thin-1.7.1.gem
```

**Comment by JohnTa15** [comment]
![screenshot_2018-03-29-18-15-10](https://user-images.githubusercontent.com/37906374/38097179-5a376d5c-337d-11e8-952a-cbbda4b1f283.png)
I had this issue when I execute gem install thin-1.7.2.gem

**Comment by Auxilus** [comment]
A lot of gems for msf have their own dependencies,

Just repeat the process I gave above for  eventmachine and then for thin

**Comment by JohnTa15** [comment]
thank you so much m8 thanks a lot..i will try to fix it and then i will send a reply

**Comment by JohnTa15** [comment]
![screenshot_2018-03-29-20-40-36-1](https://user-images.githubusercontent.com/37906374/38104396-a4f13bb6-3391-11e8-8caa-287ab8452847.png)
 hello again @Auxilus ,
i have another issue now..can you help me ?
