### ISSUE TITLE
Boot and shortcut not working with node red

### ISSUE THREAD

**Issue by AtomProgramer** [termux/termux-app#645]
Hey, 
I installed node-red on my phone. I can run it with the command `node-red`. Now I want to start it by a widget or after booting. I created a file which says `node-red` in the .shortcuts directory but after I tabed on the widget this error message popped up
 `exec("/data/data/com.termux/files/home/.shortcuts/node-red"): Permission denied
[Process completed (code 1) - press Enter]`
The programming mosquitto worked with this method, whiteout problems.
Where is the problem and how can I solve it? Or is there another way to run node red after booting?
Sorry for my bad English, I am a student from Germany...

**Comment by Grimler91** [comment]
Don't open [duplicate issues](https://github.com/termux/termux-exec/issues/10).
