### ISSUE TITLE
HTTPS Connection to termux.net

### ISSUE THREAD

**Issue by earboxer** [termux/termux-app#646]
Presently, it uses http to download packages, https should be forced.

**Comment by xeffyr** [comment]
Default sources.list for **fresh** Termux installation:
```
# The main termux repository:
deb [arch=all,aarch64] https://termux.net stable main
```
So, it uses https for packages.

**Comment by fornwall** [comment]
As @xeffyr says the current apt package uses https.

@earboxer: Try updating to latest package versions (run `pkg up`) and see if that replaces http with https? If not you may have modified sources.list manually, in which you need to manually replace http with https.

**Comment by earboxer** [comment]
Manually updating the file worked. (`pkg up` didn't switch it).

Thank you!
