### ISSUE TITLE
LLVM C Headers not installed

### ISSUE THREAD

**Issue by iamsubhranil** [termux/termux-app#651]
Installed LLVM using
```
pkg install llvm
```
But while compilation, the compiler showed that headers were missing.
![Compiling My Project](https://i.imgur.com/jGKuV1I.png)
I then navigated to 
```
/data/data/com.termux/files/usr/include
```
And saw that the files were indeed missing.
![No llvm-c Folder](https://i.imgur.com/jmwvVTO.png)
Hope it will be fixed soon.

Termux version : 0.60

**Comment by Grimler91** [comment]
Install libllvm-dev. Termux splits out headers to a -dev package, as many other distros do.

**Comment by iamsubhranil** [comment]
Thanks.
I don't know if I should open a new issue or not, and it may not even be related to termux, but JITed function is giving segfault in invocation. Somehow, it's address is not getting resolved.
Any hints?

**Comment by Grimler91** [comment]
@iamsubhranil Please open a new issue and provide code that reproduces the issue.

**Comment by its-pointless** [comment]
https://github.com/termux/termux-packages/pull/2299
will fix it
