### ISSUE TITLE
LLVM Compilation Fails Due to Unknown Target Triple

### ISSUE THREAD

**Issue by iamsubhranil** [termux/termux-app#652]
So here's my repo [Algi](https://github.com/iamsubhranil/Algi). It compiles correctly both on x86_64 Linux and on Android. But the ExecutionEngine creation fails on Android due to 
![](https://i.imgur.com/8u0nJxc.png)

Code used to build my project :

![](https://i.imgur.com/G3oUwX1.png)  

Running the program to actually show the segfault and save the bytecode to "algi.bc" :

![](https://i.imgur.com/9AS1Wrm.png)
![](https://i.imgur.com/KLzMiik.png)

**Comment by its-pointless** [comment]
works here but that is because im running clang with https://github.com/termux/termux-packages/pull/2299 merged.

**Comment by iamsubhranil** [comment]
Can you give the screenshot of the output?

**Comment by its-pointless** [comment]
https://asciinema.org/a/LKk5by3MiB9wzblTb0JeYjpZA

**Comment by fornwall** [comment]
https://github.com/termux/termux-packages/pull/2299 have now been merged and the updated version `6.0.0-1` will be available shortly (as soon as it's done building), so I'm closing this.

Great work @its-pointless !

**Comment by iamsubhranil** [comment]
Cheers mate @its-pointless!
