### ISSUE TITLE
EDITED: Perl modules with CPAN not working.

### ISSUE THREAD

**Issue by Edu4rdSHL** [termux/termux-app#654]
Hi all, today i was developing a version of my app for Termux and i found the following problem: Perl is installe normally but when i choose the "automatic configuration" for CPAN and tried to install local::lib i got errors and can't continue.

![sechacklabs-2018-04-08-16 29 56](https://user-images.githubusercontent.com/32582878/38472791-edfac802-3b4a-11e8-9818-7bb8e7a3e7d1.png)

It was solved removing gzip from the system.

**Comment by Grimler91** [comment]
It seems that gzip is broken on i686 (but it works on arm and aarch64, haven't tested x86_64). 
Thanks for reporting!

To work around it, uninstall gzip and use the busybox version instead:
`apt remove gzip`. You might need to open a new terminal to make perl aware that $PREFIX/bin/gzip doesn't exist anymore.

**Comment by Edu4rdSHL** [comment]
Hi, Grimler91. That's a weird issue, if was re-testing and the gzip problem is only for local::lib, after that it's installed i can install gzip and install modules with CPAN without problems, then i only change the instalation order in my own app https://github.com/SecHackLabs/webhackshl/commit/c7c31c5c4308401047ca09b15580fb5e73e52b3e. Thank you for reply :+1:

**Comment by Edu4rdSHL** [comment]
You've reason, thanks. Im removing it from dependences.

**Comment by fornwall** [comment]
Thanks! The gzip package for i686 has been fixed in https://github.com/termux/termux-packages/commit/f2e379953db76d37227e9e9e519ee0c49a3d9a11 (version `1.9-2`)!
