### ISSUE TITLE
Metasploit issues.....HELP

### ISSUE THREAD

**Issue by freemindingme** [termux/termux-app#658]
lit':l https://termux.net stable InRelease 
:gn:3 https://sdrausty.github.io/repo termux InRelease 
iit:4 https://its-pointless.github.io/files termux InRel 
ase 
iit:S https://sdrausty.github.io/repo termux Release 
gn:6 https://sdrausty.github.io/repo termux Release.gpg 
rr:2 https://Auxilus.github.io termux InRelease 

The following signatures couldn't be verified because 

he public key is not available: NO_PUBKEY A02DAB86B7A6E 
.BE 
.eading package lists . . . Done 
1: Skipping acquire of configured file 'extras/binary-aa 
ch64/Packages' as repository 'https://sdrausty.github.i 
/repo termux InRelease ' doesn't support architecture 'a 
rch64' 
1: GPG error: https://Auxilus.github.io termux InRelease 
: The following signatures couldn't be verified because 
he public key is not available: NO_PUBKEY A02DAB86B7A6E 
.BE 
: The repository 'https://Auxilus.github.io termux InRe 
ease ' is not signed. 
1: Updating from such a repository can't be done securel 
and is therefore disabled by default. 
1: See apt-secure(8) manpage for repository creation and 
user configuration details. 
git clone https://github/termux-app/issues/121 
cloning into '121 ' 
atal: unable to access 'https://github/termux-app/issue 
/121/': Failed to connect to github port 443: Connectio 
refused 

pkg install dirmngr 
lit:2 https://termux.net stable InRelease 
iit:3 https://its-pointless.github.io/files termux InRel 

ase 
gn:4 https://sdrausty.github.io/repo termux InRelease 
lit:5 https://sdrausty.github.io/repo termux Release 
gn:6 https://sdrausty.github.io/repo termux Release.gpg 
rr:l https://Auxilus.github.io termux InRelease 
The following signatures couldn't be verified because 

he public key is not available: NO_PUBKEY A02DAB86B7A6E 
.BE 
.eading package lists . . . Done 
1: Skipping acquire of configured file 'extras/binary-aa 
ch64/Packages as repository 'https://sdrausty.github.i 
/repo termux InRelease ' doesn't support architecture 'a 
rch64' 

1: GPG error: https://Auxilus.github.io termux InRelease 
: The following signatures couldn't be verified because 

he public key is not available: NO_PUBKEY A02DAB86B7A6E 
.BE 
: The repository 'https://Auxilus.github.io termux InRe 
ease ' is not signed. 1: Updating I'rom such a repository can't be done secure 

and is therefore disabled by default. 
1: See apt-secure(8) manpage for repository creation an 
user configuration details. 
gpg --keyserver pgpkeys.mit.edu - MIT PGP Key Server 
recv-key A02DAB86B7A6E4BE 
fhe program 'gpg ' is not installed. Install it by execu 

Lng: 
pkg install gnupg 
gpg -a --export A02DAB86B7A6E4BE I apt-key add 
fhe program 'gpg ' is not installed. Install it by execu 
Lng: 
pkg install gnupg 
!pg: no valid OpenPGP data found. 
echo "deb ttrusted:yes,arch:dll https://Auxilus.goth 
).io/ termux extras" )) $PREFIX/etc/apt/sources.list 

pkg update 
gn:l https://sdrausty.github.io/repo termux InRelease 
lit:3 https://termux.net stable InRelease 
lit:4 https://sdrausty.github.io/repo termux Releaseli 
t:5 https://its-pointless.github.io/files termux InRe 
base 
gn:6 https://sdrausty.github.io/repo termux Release.gp 
:rr:2 https://Auxilus.github.io termux InRelease 

The following signatures couldn't be verified because 
he public key is not available: NO_PUBKEY A02DAB86B7A6 
.BE 
leading package lists . . . Done 
1: Skipping acquire of configured file 'extras/binary-a 
ch64/Packages' as repository 'https://sdrausty.github. 
)/repo termux InRelease ' doesn't support architecture ' 
irch64' 
1: GPG error: https://Auxilus.github.io termux InReleas 
: The following signatures couldn't be verified because 
he public key is not available: NO_PUBKEY A02DAB86B7A6 
.BE 
:: The repository 'https://Auxilus.github.io termux InR 
ease ' is not signed. 
1: Updating from such a repository can't be done secure 
and is therefore disabled by default. 
1: See apt-secure(8) manpage for repository creation an 
user configuration details. 
f: Target Packages (extras/binary-aarch64/Packages) is 
)nfigured multiple times in /data/data/com.termux/files 
isr/etc/apt/sources.list:3 and /data/data/com.termux/fi 
:s/usr/etc/apt/sources .list : S 
f: Target Packages (extras/binary-all/Packages) is conf 
;ured multiple times in /data/data/com.termux/files/usr 
:tc/apt/sources.list:3 and /data/data/com.termux/files/ 
; r/etc/apt/sou rces . list : 5 
pkg install metasploit-framework 
gn:l https://sdrausty.github.io/repo termux InRelease 
apt update gn:l https://sarausty.gitnun.io/repo termux lnRelease 
lit:2 https://termux.net stable InRelease 
lit:4 https://its-pointless.github.io/files termux InRel 
use 
lit:5 https://sdrausty.github.io/repo termux Release 
gn:6 https://sdrausty.github.io/repo termux Release.gpg 
rr:3 https://Auxilus.github.io termux InRelease 
The following signatures couldn't be verified because 

he public key is not available: NO_PUBKEY A02DAB86B7A6E 
.BE 
.eading package lists . . . Done 
: Skipping acquire of configured file 'extras/binary-aa 
ch64/Packages' as repository 'https://sdrausty.github.i 

/repo termux InRelease ' doesn't support architecture 'a 
rch64' 

1: GPG error: https://Auxilus.github.io termux InRelease 
The following signatures couldn't be verified because 
he public key is not available: NO_PUBKEY A02DAB86B7A6E 
.BE 
: The repository 'https://Auxilus.github.io termux InRe 

ease ' is not signed. 
: Updating from such a repository can't be done securel 

, and is therefore disabled by default. 
: See apt-secure(8) manpage for repository creation and 
user configuration details. 
1: Target Packages (extras/binary-aarch64/Packages) is c 
nfigured multiple times in /data/data/com.termux/files/ 
sr/etc/apt/sources.list:3 and /data/data/com.termux/fil 
!s/usr/etc/apt/sources . list :5 
1: Target Packages (extras/binary-all/Packages) is confi 
lured multiple times in /data/data/com.termux/files/usr/ 
tc/apt/sources.list:3 and /data/data/com.termux/files/u 
r/etc/apt/sources .list : 5

**Comment by Auxilus** [comment]
kindly use script or manual installation given on wiki.termux.com/wiki/Metasploit_Framework

the repo is currently broken, will fix it soon

**Comment by mansurabbas** [comment]
s://hax4us.github.io/termux-tools termux/extras arm Packages
Ign:6 https://hax4us.github.io/termux-tools termux/extras all Packages
Ign:7 https://hax4us.github.io/termux-tools termux/extras arm Packages
Ign:6 https://hax4us.github.io/termux-tools termux/extras all Packages
Ign:7 https://hax4us.github.io/termux-tools termux/extras arm Packages
Err:6 https://hax4us.github.io/termux-tools termux/extras all Packages
  404  Not Found
Ign:7 https://hax4us.github.io/termux-tools termux/extras arm Packages
Reading package lists... Done
E: The repository 'https://gitub.com/termux.net stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
bash-4.4$

            Pls help me

**Comment by xeffyr** [comment]
> Err:6 https://hax4us.github.io/termux-tools termux/extras all Packages
404 Not Found

Support of **third-party** repositores is out of our scope. We can do nothing with these third-party repositories. This is also duplicate of https://github.com/Hax4us/termux-tools/issues/1

> https://gitub.com/termux.net

What is this ? Change this url to `https://termux.net/`.
