### ISSUE TITLE
Problem in installing lxml in termux app ?

### ISSUE THREAD

**Issue by omdev420** [termux/termux-app#659]
I am getting this : 
unable to execute 'arm-linux-androideabi-clang': No such file or directory
    Compile failed: command 'arm-linux-androideabi-clang' failed with exit status 1
    creating data
    creating data/data
    creating data/data/com.termux
    creating data/data/com.termux/files
    creating data/data/com.termux/files/usr
    creating data/data/com.termux/files/usr/tmp
    cc -I/usr/include/libxml2 -c /data/data/com.termux/files/usr/tmp/xmlXPathInit1k06helf.c -o data/data/com.termux/files/usr/tmp/xmlXPathInit1k06helf.o
    unable to execute 'cc': No such file or directory
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-gorz5o6z/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-dzlc8b7s-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-gorz5o6z/lxml/
$

**Comment by Grimler91** [comment]
You don't have a c-compiler installed as evident by *unable to execute 'cc': No such file or directory*.
Run pkg install clang.

**Comment by omdev420** [comment]
Not working !
I had clang installed 
This is what I am getting :

arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.6m -c src/lxml/etree.c -o build/temp.linux-armv7l-3.6/src/lxml/etree.o -w
    In file included from src/lxml/etree.c:97:
    /data/data/com.termux/files/usr/include/python3.6m/Python.h:39:10: fatal error: 'crypt.h' file not found
    #include <crypt.h>
             ^~~~~~~~~
    1 error generated.
    Compile failed: command 'arm-linux-androideabi-clang' failed with exit status 1
    creating data
    creating data/data
    creating data/data/com.termux
    creating data/data/com.termux/files
    creating data/data/com.termux/files/usr
    creating data/data/com.termux/files/usr/tmp
    cc -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/include/libxml2 -I/usr/include/libxml2 -c /data/data/com.termux/files/usr/tmp/xmlXPathInitqjw4nkt3.c -o data/data/com.termux/files/usr/tmp/xmlXPathInitqjw4nkt3.o
    /data/data/com.termux/files/usr/tmp/xmlXPathInitqjw4nkt3.c:2:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
    main (int argc, char **argv) {
    ^
    1 warning generated.
    cc data/data/com.termux/files/usr/tmp/xmlXPathInitqjw4nkt3.o -L/data/data/com.termux/files/usr/lib -lxml2 -o a.out
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-_hrh75gt/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-qi32ma9b-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-_hrh75gt/lxml/

And i had also installed libcrypt

**Comment by Grimler91** [comment]
Clearly it worked since you get another error now. Header files, like crypt.h, are found in the -dev packages. In this case install libcrypt-dev.

**Comment by MarcoAP1** [comment]
What was then the solution?

**Comment by sschepis** [comment]
@omdev420 omdev420 a solution would have been nice as I havev been banging head against wall on this

**Comment by cbenz** [comment]
The solution is in a previous comment :

```
pkg install libcrypt-dev
```

**Comment by a092devs** [comment]
@cbenz The solution doesn't work now!

**Comment by medram** [comment]
hey there,
I solved this problem using
`pkg install clang`
`pkg install libxml2 libxslt`
`pip install cython`
`pip install lxml`
have a good day :-)
