### ISSUE TITLE
how to install hashcat in termux?

### ISSUE THREAD

**Issue by huitc** [termux/termux-app#663]
How to install "hashcat" in terminal (termux)?

$ uname -a
Linux localhost 4.4.78-perf-gc4c4293 #1 SMP PREEMPT Thu Apr 19 03:06:23 CST 2018 aarch64 Android

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by huitc** [comment]
I hope...can provide a detailed installation tutorial

**Comment by xeffyr** [comment]
@huitc why you are posting duplicate issues ?
Replied here: https://github.com/termux/termux-packages/issues/2361

**Comment by huitc** [comment]
$ hashcat -b
hashcat (v4.0.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

clGetPlatformIDs(): CL_INVALID_VALUE

Started: Wed Apr 25 19:03:46 2018
Stopped: Wed Apr 25 19:03:46 2018

**Comment by huitc** [comment]
$ hashcat -b
hashcat (v5.1.0) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

clGetPlatformIDs(): CL_INVALID_VALUE

Started: Sat Feb 23 00:20:08 2019
Stopped: Sat Feb 23 00:20:08 2019

....................

**Comment by xeffyr** [comment]
Hashcat WILL NOT WORK on many/most devices ! Is that not understandable ?
