### ISSUE TITLE
Add cursor movement and previous entered commands

### ISSUE THREAD

**Issue by mdevspot** [termux/termux-app#665]
1> Add double finger swipe(left ti right) for cursor movements, for flexibility in writing commands. Because i once command was entered wrong have to delete it all and rewrite again.
2> Add double finger swipe(up to down) to auto write previous entered commands.

You can take this as request or suggestion. Thank you.

**Comment by l-jonas** [comment]
@AVS9G You can use the arrow keys (if you e.g. https://f-droid.org/packages/org.pocketworkstation.pckeyboard/) or you use the combination of letters and the volume key: https://wiki.termux.com/wiki/Touch_Keyboard (```
Volume Up+W → Up arrow key
Volume Up+A → Left arrow key
Volume Up+S → Down arrow key
Volume Up+D → Right arrow key
```). You can use previously entered commands by using arrow up and down.

**Comment by Quasic** [comment]
I use Ctrl+p, which is same as Volume Down+p, instead of the up arrow, just to mention another option...
