### ISSUE TITLE
Node.js binary won't execute, "No such file or directory"

### ISSUE THREAD

**Issue by tomatopeel** [termux/termux-app#669]
Hello,

If I curl and extract the latest LTS tarball from the Node.js official site, when I run it I get this behaviour:
```
bash-4.4$ node-v8.11.1-linux-arm64/bin/node -v
bash: node-v8.11.1-linux-arm64/bin/node: No such file or directory
```
Yet:
```
bash-4.4$ stat node-v8.11.1-linux-arm64/bin/node
  File: node-v8.11.1-linux-arm64/bin/node
  Size: 35259920  	Blocks: 68880      IO Block: 4096   regular file
Device: fd02h/64770d	Inode: 670445      Links: 1
Access: (0700/-rwx------)  Uid: (10142/ u0_a142)   Gid: (10142/ u0_a142)
Access: 2018-03-30 12:39:25.000000000 +0545
Modify: 2018-03-30 12:39:25.000000000 +0545
Change: 2018-04-28 17:23:31.705363872 +0545
 Birth: -
```
I'm aware that Node.js is packaged in the apt repo's, but would like to be able to use Node.js this way also (so then one could use Node Version Manager).

**Comment by tomatopeel** [comment]
Ah I wasn't aware that one could still run `npm i -g [pkg]` with the packaged Node.js. Still, it would be nice to be able to use NVM and to be able to run compiled binaries.

**Comment by Grimler91** [comment]
Alright, it's the right architecture at least. 

It probably won't work though, the precompiled binary is compiled fora normal gnu/linux system and assumes that shared libraries are in /usr/lib and an awful lot of other things, see https://wiki.termux.com/wiki/Differences_from_Linux. 

All packages for termux are ported and compiled specifically for termux/android. Only gnu/linux binaries that are statically linked have a chance to work out of the box.
