### ISSUE TITLE
Allow Termux to use SD card as general storage.

### ISSUE THREAD

**Issue by timoc** [termux/termux-app#67]
I currently use foldersync, to sync files, but it would be nice to use rsync+ssh and foldersync to fill in the blanks automatically.
the problem is that anything outside of the applications context/container is read only. Folder sync has a mechanism to allow you to give it permissions to use the SD card. I would like that to be available to termux. I would be willing to pay for that.

**Comment by fornwall** [comment]
Termux needs to have permissions to access the SD card - execute `termus-setup-storage` to do that and read the details at https://termux.com/storage.html (and re-open the issue if there are any problems)!

**Comment by timoc** [comment]
foldersync has a mechanism to get permission for the SD card not the emulated SD card. The mechanism is similar to the Android 6 thing you describe, except you ask for SD permissions from the user for the application.

**Comment by secripttermux** [comment]
Bdbsbd
