### ISSUE TITLE
Nokogiri 1.8.0 is not getting installed even though the dependencies are complete... 

### ISSUE THREAD

**Issue by NeoX404** [termux/termux-app#671]
I wanted to install metasploit in my termux which requires nokogiri 1.8.0 so i used the command

"gem install nokogiri -v'1.8.0' -- --use-system-libraries"

after which it installed miniportile 2.2.0 then it started to download nokogiri but when it started the installation it gave this error :

$ gem install nokogiri -v'1.8.0' -- --use-system-libraries
Fetching: mini_portile2-2.2.0.gem (100%)
Successfully installed mini_portile2-2.2.0
Fetching: nokogiri-1.8.0.gem (100%)
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20180430-14732-ylb9iz.rb extconf.rb --use-system-libraries
mkmf.rb can't find header files for ruby at /data/data/com.termux/files/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/arm-linux/2.5.0/nokogiri-1.8.0/gem_make.out
$

i just recently uninstalled and reinstalled my termux, and before that it used to download and run this version of metasploit really easily, but why is it happening now?

this is the script that installs metasploit :

https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh

and this error is really wierd...

**Comment by NeoX404** [comment]
Also, my phone's architecture is armv7 and i use the beta version 0.60 of termux

**Comment by Auxilus** [comment]
it says `mkmf.rb can't find header files for ruby at
/data/data/com.termux/files/usr/lib/ruby/include/ruby.h`

looks like *ruby-dev *is missing, install it by *apt install ruby-dev*

**Comment by Auxilus** [comment]
okay, the error is diff now..
can you please send data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/
extensions/arm-linux/2.5.0/nokogiri-1.8.0/mkmf.log  ?

**Comment by NeoX404** [comment]
Here 👇



$ cat mkmf.log
"arm-linux-androideabi-gcc -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.5.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.5.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.5.0 -I. -I/data/data/com.termux/files/usr/include -isystem /data/data/com.termux/files/usr/include/libandroid-support    -specs=/home/builder/termux-packages/termux.spec -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC  conftest.c  -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -specs=/home/builder/termux-packages/termux.spec -march=armv7-a -landroid-support -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby  -lgmp -ldl -lm   -lc "
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

$

**Comment by NeoX404** [comment]
Grimler91 yes, i do have clang installed

**Comment by shaheem007** [comment]
ies'
This could take a while...
Successfully installed nokogiri-1.10.3
Parsing documentation for nokogiri-1.10.3
Done installing documentation for nokogiri after 13 seconds
1 gem installed
$ msfconsole                                         Could not find nokogiri-1.8.0 in any of the sources
Run `bundle install` to install missing gems.
 
this is on termux

**Comment by Jauza24** [comment]
>>> bundle install
Fetching gem metadata from https://rubygems.org/................
.
.
.
.
Downloading nokogiri-1.8.0 revealed dependencies not in the API or the lockfile
(mini_portile2 (~> 2.2.0)).
Either installing with `--full-index` or running `bundle update nokogiri` should fix the
problem.

😣😣
