### ISSUE TITLE
su failed with magisk 16.4

### ISSUE THREAD

**Issue by fhoshino** [termux/termux-app#672]
`WARNING: linker: dlopen failed: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit, retry
CANNOT LINK EXECUTABLE "/sbin/su": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
[1]    11024 abort (core dumped)  su`

**Comment by fhoshino** [comment]
underlying cause might be removed of 64 bit bin of magisk image
https://forum.xda-developers.com/showpost.php?p=76371726&postcount=42
any workaround?

**Comment by TheComputerGuy96** [comment]
@fhoshino 
```
unset LD_PRELOAD
```

**Comment by Neo-Oli** [comment]
Can you try if running unset LD_PRLOAD before su works? If it does maybe we can add it to the su wrapper script.

**Comment by TheComputerGuy96** [comment]
@Neo-Oli Yes:
![su works](https://i.imgur.com/lxhPp2R.png)

**Comment by fhoshino** [comment]
confirming workaround works.
![conemu64_2018-05-01_16-36-45](https://user-images.githubusercontent.com/771955/39466912-de0073aa-4d5d-11e8-8f0d-9d7b804b342e.png)

**Comment by Neo-Oli** [comment]
https://github.com/termux/termux-packages/pull/2394 should fix this.

**Comment by 5auth** [comment]
A temporary solution for users with Magisk 16.4 (1642) is to install a modified 16.4 with the 32 bit changes reverted. ` unset LD_PRLOAD` works, but I had issues with other apps as well. (Given this change in Magisk messes up apps without proper 32 bit library searchpoints.)

**Comment by lazerl0rd** [comment]
@Grimler91 @cswl Magisk 18.X (18.1 or 18.2) has added back 64-bit binaries.
