### ISSUE TITLE
are the commands same as linux  terminal?

### ISSUE THREAD

**Issue by HACKER097** [termux/termux-app#676]
i have been using the android app for a while,and it works perfectly, but on the internet when i look for termux most videos are about linux terminal ,i tried it to run tools like nmap and red hawk and it works and because i have zero experience of using any form or linux , i just want to make sure if the commands are same as linux terminal.please reply ,thank you :-)

**Comment by Grimler91** [comment]
https://github.com/termux/termux.github.io/issues/37.
