### ISSUE TITLE
Docs on how to write keyboard events to the session

### ISSUE THREAD

**Issue by RangerMauve** [termux/termux-app#677]
Hi, I'm working on creating a Unity plugin that will allow Termux to render to a texture.

I'm having trouble figuring out what the format is for specifying modifiers and special keys like `backspace` for [TerminalOutput.write](https://github.com/termux/termux-app/blob/master/terminal-emulator/src/main/java/com/termux/terminal/TerminalOutput.java#L15).

I've got regular keys working and the keyboard handles shifting to uppercase, but everything else seems like a mystery at the moment.

I found the [KeyHandler](https://github.com/termux/termux-app/blob/master/terminal-emulator/src/main/java/com/termux/terminal/KeyHandler.java) class, but there doesn't seem to be any documentation on how it works or what the arguments really mean.

Could you give me a pointer for explaining how I could process an Android [KeyEvent](https://developer.android.com/reference/android/view/KeyEvent) being emitted when the backspace is pressed so that I can get the general gist of how this works?

**Comment by mageApprentissage** [comment]
Not certain this is exactly what you are looking for but the vtutils package in Termux' main repo has a <code>vtshowkeys</code> command that prints key sequences out to the terminal.

**Comment by RangerMauve** [comment]
I think that's only useful when I actually have a terminal open. I'm trying to figure out how to get keyboard input into an instance of  `TerminalSession` using the Java API.

I think I've kinda got it. The `KeyHandler.getCode` takes the value from Android's `KeyEvent.getKeyCode`, then it takes an int that contains the flags for which modifier keys are currently pressed, then I'm not sure what `cursorApp` does, and finally I'll always want `keypadApplication` to be false so that I can use the numpad normally.

This should be enough to process key commands. I'll just need to figure out how to convert keyCodes from whatever Unity gives me to whatever Android expects.
