### ISSUE TITLE
Pasting via long press causes issues in some programs

### ISSUE THREAD

**Issue by easyaspi314** [termux/termux-app#678]
Newlines when pasting have strange effects.

This is most noticeable and reproducable in nano.

Steps to reproduce with nano:
Put this into a file:
```
This
Is
A
Test
```
Copy the file contents to the clipboard:
```
cat file | termux-clipboard-set
```
Open that same file in `nano -w`, put the cursor to the beginning, long press, paste.
```
ThisThis Is A Test Is A
Test
```
Should be:
```
This
Is
A
Test
This
Is
A
Test
```
or similar. The same version of `nano` on iTerm2 has no issue, so it is likely a Termux issue.

`cat` also has this issue:
Manually:
```
$ cat
This
This
Is
Is
A
A
Test
Test^D
$
```
With clipboard:
```
$ cat
This
Is
A
TestThis
Is
A^D
Test^D$
```
Upon the first `^D`, Test is shown, and then the second finishes the `cat` without an ending newline.

**Comment by easyaspi314** [comment]
This issue still doesn't seem to be fixed.

**Comment by easyaspi314** [comment]
I found that this seems to occur because the `\n` characters are being interpreted as `\n` instead of `\r` or something like that.

**Comment by Grimler91** [comment]
Piping termux-clipboard-get to cat seem to work, but not long press pasting, as you said. 
Emacs and vim both handle the clipboard correctly, but not nano.

There are no \r characters in the data I tested with (verified with hexdump), so not sure that's related to the issue.

**Comment by easyaspi314** [comment]
Well, that is supposed to happen.

To the terminal, `\r` is a special character that flushes and outputs a `\n`. It is kind of like a `<br/>` in HTML.

[This](https://unix.stackexchange.com/a/349219) explains it well.

On the flip side, copying some raw `\r` characters seems to have the correct result.
