### ISSUE TITLE
Opentasks/dmfs crashes when termux 0.31 is installed

### ISSUE THREAD

**Issue by rudi123** [termux/termux-app#68]
The chrash occures when trying to edit a task. With version 0.30 everything is fine. There is also an error report at the opentasks/dmfs project.

**Comment by fornwall** [comment]
Could you link to the issue created at opentask/dmfs?

**Comment by rudi123** [comment]
Here is the link to Opentasks.

https://github.com/dmfs/opentasks/issues/228

**Comment by fornwall** [comment]
Can you check if this has been fixed in the latest update (version 0.32) of Termux?

**Comment by rudi123** [comment]
Hello

Wow, you realy take care of your apps, sadly i get an error 505 during installation. Can you take the app to fdroid, please. From there i am ablw ti install it.

Thank you very much for handling this problem.

**Comment by fornwall** [comment]
The 505 is probably due to trying to mix app installs from fdroid and google play.

The version will be available as an update in fdroid shortly (there is a slight delay before fdroid detects the new release and builds it from source).

**Comment by rudi123** [comment]
Ok, i will wait for the fdroid version.

Thank you!

**Comment by rudi123** [comment]
Hello

The problem os gone with version 0.32. Thanks for your fast help.

Happy easter!!

**Comment by dmfs** [comment]
May I ask what the problem was?

**Comment by fornwall** [comment]
@dmfs The problem was that the Termux app matched too many intents, which in this case probably caused Termux to be launched by mistake by an intent from OpenTasks and crashed due to this intent not being expected.

**Comment by dmfs** [comment]
I see. I think we've already addressed this issue with the upcoming version. The problem was that a specific Intent might contain a custom `Parcelable` that's unparcelled by the system when a chooser is required (because multiple apps accept that specific `Intent`). Since the system doesn't know about that custom class, the chooser crashes and OpenTasks with it.
