### ISSUE TITLE
Cannot run Sudo

### ISSUE THREAD

**Issue by rootkittt** [termux/termux-app#681]
Hey when i try to run sudo ill get this error.

“Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ sudo
CANNOT LINK EXECUTABLE "/system/bin/mount": cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib64/libselinux.so"...“

Then ive tried to use tsu but i get this error....

“Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ tsu
# apt-get
bash: /data/data/com.termux/files/usr/bin/apt-get: Permission denied“

My device is rooted with super user and it works fine with other apps.
Only on termux im not able to run a program with super user Rights.

Can someone help me?

**Comment by Grimler91** [comment]
You shouldn't use apt with su/sudo/tsu, there's no need for it and that will cause all sorts of trouble.

Sudo isn't provided by termux so open an issue at the right repo about that if needed.

Use `tsu -a` to get rid of the permission denied error, but again: don't run apt as root!

**Comment by rootkittt** [comment]
Ive tried it like u said but i always get this error..

“bash: ./hakku: /usr/bin/env: bad interpreter: Permission denied“

Any other ideas?

**Comment by Grimler91** [comment]
Termux is a prefixed system so all binaries are in /data/data/com.termux/files/usr/bin, there is no /usr/bin folder. You therefore need to change the shebang in the script.

**Comment by rootkittt** [comment]
could u tell me what i have to do to make it work? that would be nice.
