### ISSUE TITLE
apt update error

### ISSUE THREAD

**Issue by ancientzords** [termux/termux-app#687]
$ apt update
Ign:1 https://hax4us.github.io/termux-tools termux InRelease
Hit:2 https://termux.net stable InRelease
Hit:4 https://hax4us.github.io/termux-tools termux Release
Ign:5 https://hax4us.github.io/termux-tools termux Release.gpg
Err:3 https://xeffyr.github.io/termux-x-repository termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 45F2964132545795
Reading package lists... Done
W: GPG error: https://xeffyr.github.io/termux-x-repository termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 45F2964132545795
E: The repository 'https://xeffyr.github.io/termux-x-repository termux InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Anyone can help me?
I'm so confused.

**Comment by Grimler91** [comment]
You need to reimport Xeffyr's key:

```
wget https://xeffyr.github.io/termux-x-repository/pubkey.gpg
apt-key add pubkey.gpg
```

**Comment by Ghost-of-tea** [comment]
after executing
`wget https://xeffyr.github.io/termux-x-repository/pubkey.gpg`
i get
`HTTP request sent, awaiting response... 404 Not Found
2018-11-09 23:58:40 ERROR 404: Not Found.`

**Comment by xeffyr** [comment]
> seems like it is deleted by now.
any help on this?

Just don't use things that were deleted.

**Comment by Bryann4DM** [comment]
@Ghost-of-tea any solution for this?

**Comment by xeffyr** [comment]
@Bryann4DM **There no solution for this!** I have shutted down repository.

**Comment by ronin1234** [comment]
Same problem
HTTP request sent, awaiting response... 404 Not Found
2019-02-11 00:41:40 ERROR 404: Not Found.

**Comment by Quasic** [comment]
pkg install x11-repo

**Comment by AnriReno** [comment]
error update ?
pkg update
N: See apt-secure(8) manpage for repository creation and user configuration details
