### ISSUE TITLE
I already connected otg keyboard, But still show the number virtual keyboard.

### ISSUE THREAD

**Issue by xTpx** [termux/termux-app#690]
![numberkey](https://wx4.sinaimg.cn/large/006qViiMly1frnevpcu14j31kw0w0wf7.jpg)
I use otg keyboard already. And i know use ctrl+alt+k can be hide it, But if i switch another app, It will show again.

**Comment by l-jonas** [comment]
@xTpx Does this happen only in Termux or in other Apps (e.g. Browser) too?
