### ISSUE TITLE
Problem with ffmpeg when joining two video streams

### ISSUE THREAD

**Issue by denialplando** [termux/termux-app#691]
I've tried to join two video streams using the "join" filter of ffmpeg 3.4.2 but I get a message saying: "Assertion !s->input_frames[i] Failed at scr/libavfilter/af_join.c:93". It seems a fail in the filter conde but I don't know.

**Comment by denialplando** [comment]
Sorry, where says "conde" replace for "code".

**Comment by Grimler91** [comment]
Can you give the command you used when you got this error?

**Comment by denialplando** [comment]
Sure Grimler91. The command is simple:
ffmpeg -i video1.mp4 -i video2.mp4 -f mp4 -q:v 0 -q:a 0 -filter_complex join=2 -profile:v baseline -c:v h264 -c:a aac vídeo.mp4

**Comment by Grimler91** [comment]
This upstream bug report seem to report this: https://trac.ffmpeg.org/ticket/6780, it was solved last year. I'll see if updating to the latest ffmpeg version solves it.

**Comment by Grimler91** [comment]
Ffmpeg 40 seem to work, could you try this deb: https://grimler.se/dists/testing/misc/binary-aarch64/ffmpeg_4.0_aarch64.deb and confirm? I have only built it for aarch64 so far, and need to bump all packages who depend on ffmpeg before I can open a PR.

**Comment by denialplando** [comment]
Thank you for your fast assitance. The problem is solved. I didnt need to built the last versión.

**Comment by Grimler91** [comment]
@denialplando how did you solve the problem?
