### ISSUE TITLE
i can't run the tools with root access on android oreo 8.1 , in 2-3 minute my phone get stuck

### ISSUE THREAD

**Issue by Destoyevsky** [termux/termux-app#692]
sudo tsu
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib64/libunwind.so"...

**Comment by Grimler91** [comment]
Why `sudo tsu`? 
That's like running `sudo su`, it makes no sense.
Do you get the same error with only `tsu`? Try `tsu -a` in that case.

**Comment by Destoyevsky** [comment]
Yups, still showing same problems

**Comment by Destoyevsky** [comment]
Still like that bro

**Comment by Grimler91** [comment]
...

Closing due to lack of information.
