### ISSUE TITLE
touch keyboard shortcuts not working

### ISSUE THREAD

**Issue by dot-gov** [termux/termux-app#694]
Following this guide: https://termux.com/touch-keyboard.html
Trying to use volume-up/down causes ^[[C or ^[[D to be sent to the console. Pressing keys on the soft keyboard only causes the regular keys to be inputed.

![screenshot](https://user-images.githubusercontent.com/13226759/40590503-c0e36bd6-61cd-11e8-8568-6484073c807b.png)

This is happening on LineageOS 15.1

**Comment by l-jonas** [comment]
@dot-gov Official Lineage OS? Which device?
