### ISSUE TITLE
Correct mistake on 'touch-keyboard' documentation page

### ISSUE THREAD

**Issue by javascriptonian** [termux/termux-app#695]
The 'Using a touch keyboard' [documentation page](https://termux.com/touch-keyboard.html) contains an error.
This:
```
Volume Up+P → Page Up
Volume Up+N → Page Down
```
should be:
```
Volume Down+P → Page Up
Volume Down+N → Page Down
```

**Comment by Grimler91** [comment]
On my device the documentation is correct, Volume Up+P → Page Up and Volume Up+N → Page Down. 
What device do you have?

**Comment by xeffyr** [comment]
@javascriptonian Checked on my device - documentation is correct.

**Comment by javascriptonian** [comment]
oh that's weird. I'm on Oneplus 3, and it worked with volume down.

**Comment by bokuno** [comment]
I am using oneplus 3T and volume up +p is pageup.

**Comment by javascriptonian** [comment]
Pressing `volume up + p` doesn't do anything on my phone. `volume down + p` shows me the previous command I used (and that's how I assume it's working as 'page up').

**Comment by Quasic** [comment]
It's actually Previous and Next.
Those are bash key commands.
