### ISSUE TITLE
CANNOT LINK EXECUTABLE DEPENDENCIES: "libmp3lame.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by Substancia** [termux/termux-app#696]
Hi, I am trying to run mpv in my termux session, I have installed termux and mpv last night, updated and upgraded my termux-tools (`apt update && apt upgrade`), but when I try to play a music (`mpv 5_326271957372952.mp3`) it shows `CANNOT LINK EXECUTABLE DEPENDENCIES: "libmp3lame.so" is 32-bit instead of 64-bit`.

I tried running `file usr/lib/libmp3lame.so`, and output is
`usr/lib/libmp3lame.so: ELF 64-bit LSB pie executable ARM aarch64, version 1 (SYSV), dynamically linked, stripped`

`dpkg --print-architecture` gives `aarch64`

`uname -a` gives `Linux localhost 3.10.49-perf-svn5973 #1 SMP PREEMPT Tue Sep 27 22:07:47 CST 2016 aarch64 Android`

So, even though the executable dependency `libmp3lame.so` is 64-bit, why is mpv saying otherwise and not linking?

Thanks in advance.

**Comment by Grimler91** [comment]
Do you have a libmp3lame.so in /system/lib?

**Comment by Substancia** [comment]
I cannot find a /system. All I have is a /home and a /usr. I found libmp3lame.so in /usr/lib.

**Comment by Grimler91** [comment]
Termux is a [prefixed environment](https://wiki.termux.com/wiki/Differences_from_Linux) so it's impossible that you have /usr and /home. 

Unless you are running the commands in a chroot environment or something like that, though /system should still be accessible then (I think).

**Comment by Substancia** [comment]
Sorry, my bad, I did have a /system, didn't notice it *facepalm*, but I still have a /home and a /usr (though that is not relevant here I get it). I checked file info on /system/lib/libmp3lame.so and /system/lib64/libmp3lame.so, both being 32-bit. But `apt update && apt upgrade` is not doing any help.

**Comment by Grimler91** [comment]
Alright, that explains the issue then, mpv picks up /system/lib(64)/libmp3lame.so instead of /data/data/com.termux/files/usr/lib/libmp3lame.so.

An ugly work around until we can fix it properly would probably be to run mpv as 
`LD_PRELOAD=/data/data/com.termux/files/usr/lib/libmp3lame.so mpv some_mp3.mp3`

Your particular android variant apparently ships a libmp3lame.so which conflicts with termux' libmp3lame.so.

**Comment by Substancia** [comment]
Apparently the problem persists, showing the same error message. `file /data/data/com.termux/files/usr/lib/libmp3lame.so` shows it is 64-bit.

**Comment by Substancia** [comment]
Not sure if this is relevant, but I installed tsu for root access, but when I run tsu, it says `Permission denied`.

**Comment by Grimler91** [comment]
Maybe you need to change LD_LIBRARY_PATH as well.

The tsu error is probably not related. To not get that error, run `tsu -a` instead of just `tsu`.

**Comment by Substancia** [comment]
I'm sorry, I'm not good at library linking and sort. What command am I looking at?

**Comment by Grimler91** [comment]
I don't know, have to research it. There are a couple of packages who deals with similar issues, for example [gst-plugins-base](https://github.com/termux/termux-packages/blob/8270069f23f7c6cfd164defcc549621634e05cd6/packages/gst-plugins-base/build.sh#L38).

**Comment by Grimler91** [comment]
Which error do yuo get with play-audio? 

I use cmus.

**Comment by Grimler91** [comment]
@Substancia ah, actually, try editing $PREFIX/bin/mpv and add /data/data/com.termux/files/usr/lib/libmp3lame.so to the LD_PRELOAD line there, that probably solves this.

**Comment by Substancia** [comment]
I edited $PREFIX/bin/mpv and added /data/data/com.termux/files/usr/lib/libmp3lame.so to LD_PRELOAD, but that didn't solve anything apparently.
I'll give cmus a shot now.

P.S.:$PREFIX/bin/mpv is /data/data/com.termux/files/usr/bin/mpv right?

**Comment by Substancia** [comment]
I understand my intentions were not mentioned. I was planning to play music over ssh from a remote linux machine. So I guess cmus is not what I am looking for since it is just a remote control which will play music at my remote machine side?

**Comment by xeffyr** [comment]
Is this issue still actual ?
Mpv was rebuilt several times from May 30. There also no any activity from this time.
