### ISSUE TITLE
Unable to install express ( of node.js) in Android termux using sdcard0 as directory

### ISSUE THREAD

**Issue by AJ-Creations** [termux/termux-app#697]
I'm unable to install express in Android termux. I have latest nodejs installed. It is working perfectly when I use Private storage but I'm using cd /storage/sdcard0/NodeJS/Test/ and getting **permission denied** error. I saw the word symlink repeatedly in the terminal's error message. Here's what I saw after commanding **npm install express --save**:

```
$ npm install express --save
npm WARN test-lab@1.0.0 No description
npm WARN test-lab@1.0.0 No repository field.

npm ERR! path ../mime/cli.js
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink
npm ERR! Error: EACCES: permission denied, symlink '../mime/cli.js' -> '/storage/sdcard0/NodeJS/Test/3/node_modules/.bin/mime'
npm ERR!  { Error: EACCES: permission denied, symlink '../mime/cli.js' -> '/storage/sdcard0/NodeJS/Test/3/node_modules/.bin/mime'
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, symlink '../mime/cli.js' -> '/storage/sdcard0/NodeJS/Test/3/node_modules/.bin/mime'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'symlink',
npm ERR!      path: '../mime/cli.js',
npm ERR!      dest: '/storage/sdcard0/NodeJS/Test/3/node_modules/.bin/mime' },
npm ERR!   stack: 'Error: EACCES: permission denied, symlink \'../mime/cli.js\' -> \'/storage/sdcard0/NodeJS/Test/3/node_modules/.bin/mime\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../mime/cli.js',
npm ERR!   dest: '/storage/sdcard0/NodeJS/Test/3/node_modules/.bin/mime',
npm ERR!   parent: 'test-lab' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2018-05-29T13_09_20_748Z-debug.log
```
Is it really possible to install express while current storage is something like /storage/sdcard0/....... ?

**Comment by Grimler91** [comment]
It's not possible in shared storage due to Android's security features. See for example https://github.com/termux/termux-packages/issues/2459, https://github.com/termux/termux.github.io/issues/35, https://github.com/termux/termux-packages/issues/2076 for more information.

**Comment by AJ-Creations** [comment]
I would recommend Termux developers to add an inbuilt file explorer and text editor for Termux(Which can have three storage options 1: App-Private, 2: Internal memory 3: External memory) because thousands of Termux users are using vim like(not only vim) text editors because they don't have any other choice.
- the greatest terminal
- inbuilt file explorer for both App-Private files, sdcard0 files and sdcard1 files
-  Inbuilt text editor.
It will be really awesome.
What do you think?
Comment it out...

**Comment by Grimler91** [comment]
I suggest that you open a new issue and provide the commands you ran as well as the error you get.
