### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by nico202** [termux/termux-app#7]
Hi, I've not found a donate button, paypal addres nor bitcoin address on the website.
How do I donate? :D

**Comment by jarrettgilliam** [comment]
You could buys some of the various [add-ons](https://play.google.com/store/search?q=Fredrik%20Fornwall%20Termux&c=apps&hl=en). Just a thought.

**Comment by fornwall** [comment]
@nico202 Thanks for the offer, but I'm not planning to setup donations at the moment! Buy the add-ons as @jarrettgilliam says if you like them, or perhaps donate to a worthwhile charity :).
