### ISSUE TITLE
Can you add an inapp purchase to donate?

### ISSUE THREAD

**Issue by JanHelbling** [termux/termux-app#701]
Can you add an inapp purchase to donate? or something similar?

**Comment by xeffyr** [comment]
See this about donating: https://termux.com/donate.html

**Comment by JanHelbling** [comment]
yes I know that. but I want to donate over my phone bill. not Patreon, not PayPal and not Bitcoin

**Comment by l-jonas** [comment]
@JanHelbling You would "donate" to Google when you use an In App Purchase. Google takes 30 percent of it (additionally to the taxes). Are you sure that this feature would be an good idea?

**Comment by JanHelbling** [comment]
yes

**Comment by JanHelbling** [comment]
or just a Donate-Version with an other Icon...

**Comment by l-jonas** [comment]
I personally hate such Donate-Apps. I will create a Pull Request for an In-App-Purchase.

**Comment by l-jonas** [comment]
This would be only easily possible with a library like https://github.com/serso/android-checkout, but this project uses (nearly) no libraries.

@fornwall Would you accept a pull request for that which uses such a library?

**Comment by fornwall** [comment]
Sorry for the late reply here! I don't want to add in-app purchase to the app, it feels wrong for this kind of app. Feel free to donate to a charity instead :).
