### ISSUE TITLE
Touch keyboard weird behavior on Samsung Note 8

### ISSUE THREAD

**Issue by AndriusWild** [termux/termux-app#706]
When I type anything in Termux installed on my Note8 no letters show up until I press . or , or - etc.
Also, very often when "Process completed - press Enter" tapping on Enter does not work.

**Comment by l-jonas** [comment]
@AndriusWild Is this a duplicate of https://github.com/termux/termux-app/issues/126 (issues with Samsungs Keyboard "predictive text" feature)?

**Comment by Grimler91** [comment]
Duplicate of https://github.com/termux/termux-app/issues/686
