### ISSUE TITLE
How to monitor HDD, RAM, load with Termux video - where to share?

### ISSUE THREAD

**Issue by liesislukas** [termux/termux-app#708]
Hi, created a video how to monitor things using Termux and https://trafikito.com/ Wanted to share it with Termux community, where is the correct place to do it?

Here is video itself:

https://www.youtube.com/watch?v=cwQGDNTSyqM

**Comment by Neo-Oli** [comment]
Cool. The best place would probably be the Google Plus community http://termux.com/community
