### ISSUE TITLE
Ability to use usb otg storage in termux

### ISSUE THREAD

**Issue by fbartels** [termux/termux-app#71]
Hi,

I am using Android 6 (cm13.0) and I have formatted my sd card as internal storage. I have already found https://termux.com/storage.html and when running termux-setup-storage I can acess my internal storage.

I also want to access a usb thumbdrive, which is visible in es explorer and the android storage settings, but will not be displayed beneath ~/storage (the folder external is missing as well).

Is this expected behaviour or is there something wrong on my device?

PS: the drive does show up in /storage btw. But trying to create a file on it will give a "permission denied"

**Comment by Neo-Oli** [comment]
I am on Android 5 and I can write to /storage/usbdisk without getting a "permission denied" error. Can you write to the usbdisk with other apps?

**Comment by fbartels** [comment]
Yes, the behaviour changed in Android 6 a bit for external storage as far as i know. With the first Builds the drive could only be accessed from the storage settings, but starting with an update of es Explorer itmcould be opened directly as well.

**Comment by Neo-Oli** [comment]
@fornwall Is there anything that can be done here?

**Comment by fornwall** [comment]
@Neo-Oli I'm not sure, need to test with a usb otg storage.

Perhaps direct file system access is not possible, and an api method could be added instead.

**Comment by fornwall** [comment]
It seems that direct file system access is not possible - from [Android USB media support documentation](https://source.android.com/devices/storage/traditional.html#support_usb_media), as mentioned [in this stackoverflow answer](http://stackoverflow.com/questions/32201169/how-app-can-access-files-on-usb-otg-storages-in-android-6-0-api-level-23-witho):

```
Starting in Android 4.4, multiple external storage devices are surfaced to developers
through Context.getExternalFilesDirs(), Context.getExternalCacheDirs(),
and Context.getObbDirs().

External storage devices surfaced through these APIs must be a semi-permanent
part of the device (such as an SD card slot in a battery compartment).
Developers expect data stored in these locations to be available over long periods
of time. For this reason, transient storage devices (such as USB mass storage
drives) should not be surfaced through these APIs.

The WRITE_EXTERNAL_STORAGE permission must only grant write access to the
primary external storage on a device. Apps must not be allowed to write to
secondary external storage devices, except in their package-specific directories
as allowed by synthesized permissions. Restricting writes in this way ensures the
system can clean up files when applications are uninstalled.
```

However, a command could be created which requests a file from the system and puts in a Termux-accessible dir.

I don't know if it's possible to create a put command, which would put a Termux-accessible file on the USB storage.

**Comment by omilu** [comment]
The termux-storage-getfile mechanism gives no way to preserve the original filename.  Is it possible to implement something to preserve the filename??  For example, I call termux-storage-getfile without a destination filename, and the scripts creates a file with the same name of the file I select from the usb drive, and copies into it.

**Comment by zhanglongqi** [comment]
My thumb drive is mounted in `/data/system/scsi/Disk1`. It's owned by `system`, but I can read/write on it without error.

**Comment by wulvyrn** [comment]
would this be of use:
https://github.com/magnusja/libaums

having access to a usb drive for backup or additional storage would be nice.

**Comment by Konard** [comment]
I need access to the OTG usb drive.

**Comment by locuturus** [comment]
This should be fixable by requesting the new permission known as "all files access" or "manage_external_storage" available from Android 11. USB drives would be available under /mnt/media_rw/abcd-1234

**Comment by analoginterface0** [comment]
Greetings,

I've just tried-out my external SSD (NTFS formatted, one among total of two partitions, the other one is FAT16 ESP) manually linked to `~/storage/media-0` (an arbitrary folder) from termux 0.118.0 on my Xiaomi sweet MIUI 13 (Redmi Note 10 Pro global). Before doing that, I've allowed "All files access" from the Security app as @locuturus suggested: Privacy Protection => Special Permissions => All Files Access => Termux => toggle permission. And it works!

**Comment by locuturus** [comment]
@sylirre I don't think you have that quite right. The documentation clearly states that All Files Access provides raw file path to apps with that permission. It is not just an escape from Scoped Storage restrictions it actually for the first time in modern Android history grants real file path to any directory you can reach with SAF and that includes USB. AOSP and Pixels and the like work just fine. 

There is another app, Syncthing Fork, which cannot use SAF because the real work is done in Go and that cannot use the SAF API so there was no way to access USB drives without root. But now that the app has All Files Access you can manually give it file paths to any USB directory and it works.

I'm a little confused by @analoginterface0 situation, it reads to me like MIUI 13 can grant All Files Access to apps below the API level normally required. But for the rest of us AOSP folks I stand by what I wrote. Test it for yourself with Syncthing Fork, use the web interface, determine the real path to the USB you're testing and type it in there.

**Comment by agnostic-apollo** [comment]
The `MANAGE_EXTERNAL_STORAGE` is not engaged or grantable unless app is targeting android `11+` (api `30+`) and is the same as if  legacy `WRITE_EXTERNAL_STORAGE` permission is granted. Termux already requests both in current github actions builds but its not being used since termux official builds use `targetSdkVersion` `28`. As for whether removable sd or USB drives are accessible (both internally different, former is considered persistent storage by android), it depends on the build/vendor, some allow, some don't. Android 13 avd allows access to removable sd if  `WRITE_EXTERNAL_STORAGE` is granted with termux using `targetSdkVersion` `28` and if `MANAGE_EXTERNAL_STORAGE` is granted with termux using `targetSdkVersion` `33`. Termux cannot do anything more. If removable sd or USB access is required and storage permission does not allow it, then `termux-api` `SAF` apis will need to be used.

https://github.com/termux/termux-app/commit/9eeb2babd7638f8b2967ebd93020e7e37d19cc2b

**Comment by agnostic-apollo** [comment]
Quoting https://developer.android.com/training/data-storage/manage-all-files

> The MANAGE_EXTERNAL_STORAGE permission grants the following:

> - Read and write access to all files within [shared storage](https://developer.android.com/training/data-storage/shared).
    Note: The /sdcard/Android/media⁠ directory is part of shared storage.

> - Access to the contents of the [MediaStore.Files](https://developer.android.com/reference/android/provider/MediaStore.Files) table.

> - Access to the root directory of both the USB on-the-go (OTG) drive and the SD card.
    
>- Write access to all internal storage directories⁠, except for /Android/data/, /sdcard/Android, and most subdirectories of /sdcard/Android. This write access includes [direct file path](https://developer.android.com/training/data-storage/shared/media#direct-file-paths) access.

Note that it **ONLY** says "direct file path access" for internal storages.

**Comment by locuturus** [comment]
> Quoting https://developer.android.com/training/data-storage/manage-all-files
> 
> > The MANAGE_EXTERNAL_STORAGE permission grants the following:
> 
> > * Read and write access to all files within [shared storage](https://developer.android.com/training/data-storage/shared).
> >   Note: The /sdcard/Android/media⁠ directory is part of shared storage.
> 
> > * Access to the contents of the [MediaStore.Files](https://developer.android.com/reference/android/provider/MediaStore.Files) table.
> 
> > * Access to the root directory of both the USB on-the-go (OTG) drive and the SD card.
> 
> > * Write access to all internal storage directories⁠, except for /Android/data/, /sdcard/Android, and most subdirectories of /sdcard/Android. This write access includes [direct file path](https://developer.android.com/training/data-storage/shared/media#direct-file-paths) access.
> 
> Note that it **ONLY** says "direct file path access" for internal storages.

There are many features of the various file access methods not detailed in that paragraph. You can get file path from media store DATA column but that is not mentioned either. I would not read very far into every omission. Using TermOne Plus I demonstrate on Sony Xperia 5 iii Android 13 stock ROM how to discover and read and write USB attached storage. This is what MANAGE_EXTERNAL_STORAGE permission makes possible in AOSP:
![Screenshot_20230222-141054](https://user-images.githubusercontent.com/19397973/220771340-10aa8a7a-66ed-45d2-92e9-8f880209a00f.png)

I understand the other factors keeping Termux on API 28 but I want to set the record straight -- All Files Access is what every dev has been wanting all these years:  real file paths to user accessable storage (aside from *Android/data).

**Comment by elvisisvan** [comment]
> > Quoting https://developer.android.com/training/data-storage/manage-all-files
> > > The MANAGE_EXTERNAL_STORAGE permission grants the following:
> > 
> > 
> > > * Read and write access to all files within [shared storage](https://developer.android.com/training/data-storage/shared).
> > >   Note: The /sdcard/Android/media⁠ directory is part of shared storage.
> > 
> > 
> > > * Access to the contents of the [MediaStore.Files](https://developer.android.com/reference/android/provider/MediaStore.Files) table.
> > 
> > 
> > > * Access to the root directory of both the USB on-the-go (OTG) drive and the SD card.
> > 
> > 
> > > * Write access to all internal storage directories⁠, except for /Android/data/, /sdcard/Android, and most subdirectories of /sdcard/Android. This write access includes [direct file path](https://developer.android.com/training/data-storage/shared/media#direct-file-paths) access.
> > 
> > 
> > Note that it **ONLY** says "direct file path access" for internal storages.
> 
> There are many features of the various file access methods not detailed in that paragraph. You can get file path from media store DATA column but that is not mentioned either. I would not read very far into every omission. Using TermOne Plus I demonstrate on Sony Xperia 5 iii Android 13 stock ROM how to discover and read and write USB attached storage. This is what MANAGE_EXTERNAL_STORAGE permission makes possible in AOSP: ![Screenshot_20230222-141054](https://user-images.githubusercontent.com/19397973/220771340-10aa8a7a-66ed-45d2-92e9-8f880209a00f.png)
> 
> I understand the other factors keeping Termux on API 28 but I want to set the record straight -- All Files Access is what every dev has been wanting all these years: real file paths to user accessable storage (aside from *Android/data).

how do you allow this MANAGE_EXTERNAL_STORAGE permission for termux?

**Comment by agnostic-apollo** [comment]
After further investigation for changes in Android `>= 12`...

`MANAGE_EXTERNAL_STORAGE` permission is declared in `AndroidManifest.xml` of the Termux app for `v0.119.0*` release builds on F-Droid and GitHub, and in `master` branch for GitHub action builds, and will show both `Files` and `All fIles access`. The `<= v0.118.2` release builds on F-Droid and GitHub do not have `MANAGE_EXTERNAL_STORAGE` permission and will not show `All files access` . Currently, termux uses `targetSdkVersion` `28`. 

#### WRITE_EXTERNAL_STORAGE vs MANAGE_EXTERNAL_STORAGE

Enabling `Android Settings` -> `Apps` -> `Termux` -> `Permissions` -> `Files` will only grant legacy `WRITE_EXTERNAL_STROAGE` permission and enabling `Android Settings` -> `Apps` -> `Special app access` -> `All files access` -> `Termux` will only grant `MANAGE_EXTERNAL_STORAGE` permission. **They are two different permissions**, but access to primary external storage permission should still be available with either under the `/storage/emulated/<user_id>` or `/sdcard` paths.

**However, granting `MANAGE_EXTERNAL_STORAGE` should additionally grant access to unreliable/removable volumes like USB OTG devices under the `/mnt/media_rw/XXXX-XXXX` paths on Android `>= 12`, check below.** The `termux-setup-storage` command only requests the `WRITE_EXTERNAL_STROAGE` for GitHub action builds of `master` branch.

##### Storage Permissions Visibility

Assuming `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions and `requestLegacyExternalStorage="true"` attributes are declared in `AndroidManifest.xml` of the app like Termux app does and app is running on Android `12` (older versions have different (broken) logic), then permissions will show as per following logic.

- If `targetSdkVersion` `<= 29` and `MANAGE_EXTERNAL_STORAGE` is declared, then `WRITE_EXTERNAL_STORAGE` will show in app `Permissions` and `MANAGE_EXTERNAL_STORAGE` in `Special app access`.
- If `targetSdkVersion` `<= 29` and `MANAGE_EXTERNAL_STORAGE` is not declared, then only `WRITE_EXTERNAL_STORAGE` will show in app `Permissions`.
- If `targetSdkVersion` `> 29` and `MANAGE_EXTERNAL_STORAGE` is declared, then only `MANAGE_EXTERNAL_STORAGE` will show in `Special app access`.
- If `targetSdkVersion` `> 29` and `MANAGE_EXTERNAL_STORAGE` is not declared, then neither `WRITE_EXTERNAL_STORAGE` or `MANAGE_EXTERNAL_STORAGE` will be shown.

- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:packages/modules/Permission/PermissionController/src/com/android/permissioncontroller/permission/data/FullStoragePermissionAppsLiveData.kt;l=82
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:packages/modules/Permission/PermissionController/res/values/strings.xml;l=152
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:packages/modules/Permission/PermissionController/src/com/android/permissioncontroller/permission/ui/model/AppPermissionViewModel.kt;l=425;bpv=0
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:packages/modules/Permission/PermissionController/src/com/android/permissioncontroller/permission/ui/handheld/AppPermissionFragment.java;l=490;bpv=0
- https://cs.android.com/android/_/android/platform/packages/modules/Permission/+/e56d7772ee01ad16c2d4646f0ca57e97395c94b3

- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:packages/apps/Settings/src/com/android/settings/applications/appinfo/ManageExternalStorageDetails.java
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:packages/apps/Settings/src/com/android/settings/applications/AppStateManageExternalStorageBridge.java;l=90
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:packages/apps/Settings/res/values/strings.xml;l=9246
- https://cs.android.com/android/_/android/platform/packages/modules/Permission/+/23b818c74ba235c3b228301034affa4a8f98a469

##### How does MANAGE_EXTERNAL_STORAGE grant unreliable/removable volume access?

Access is granted based on DAC and not SeLinux itself despite the `search` access given to app domains.

- Unreliable/Removable volumes like USB OTG devices that are only available on the `/mnt/media_rw` paths with their own filesystem (`vfat`/`exfat`) are assigned the `root` (`0`) owner and `external_storage` (`1077`) group.
- The reliable/adoptable volumes like SD cards that are backed with `FUSE` or `sdcardfs` filesystems for normal apps to access that are bind mounted under `/storage` from their initial `/mnt/media_rw` mount path are assigned the `root` (`0`) owner and `media_rw` (`1023`) group.

If an app has been granted the `MANAGE_EXTERNAL_STORAGE` permission, then the `external_storage` (`1077`) group is added to list of groups that are assigned to the app process when its forked from zygote, allowing it to access unreliable/removable volumes with the `external_storage` (`1077`) group, but not the `media_rw` (`1023`) group.

App process groups can be checked with `cat /proc/self/status | grep ^Groups:`. Path group can be checked with `stat /mnt/media/XXXX-XXXX`, where `XXXX-XXXX` is the volume UUID.

- https://cs.android.com/android/_/android/platform/system/core/+/bdeaf57da3a6a98c958b1ee7e125a4df3e3cdc8b
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:system/core/libcutils/include/private/android_filesystem_config.h;l=128
- https://cs.android.com/android/_/android/platform/system/vold/+/c9a2be4e3fb102bfb56f6384121d01b674b4f375
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:system/vold/model/PublicVolume.cpp;l=145
- https://cs.android.com/android/_/android/platform/frameworks/base/+/782dc19e95a2bfde833a0803c1d8ab77d047c11c
- https://cs.android.com/android/_/android/platform/frameworks/base/+/refs/tags/android-14.0.0_r18:services/core/java/com/android/server/am/ProcessList.java;l=1708
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:frameworks/base/core/java/android/os/Process.java;l=228
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:frameworks/base/core/jni/com_android_internal_os_Zygote.cpp;l=537
- https://cs.android.com/android/platform/superproject/+/android-14.0.0_r18:system/sepolicy/private/app.te;l=78

**Comment by KurtGokhan** [comment]
@agnostic-apollo  I installed the Termux from Github Actions build. "All files access" permission did finally appear for Termux and I granted it. But when I check for groups in Termux, I still don't have `external_storage` group and I can't access external storage. Am I missing something?

**Comment by agnostic-apollo** [comment]
>However, granting MANAGE_EXTERNAL_STORAGE should additionally grant access to unreliable/removable volumes like USB OTG devices under the /mnt/media_rw/XXXX-XXXX paths on **Android >= 12**, check below

**Comment by KurtGokhan** [comment]
Indeed. I installed an Android 14 ROM and after rooting, termux seems to have `external_storage` group. To make the external storage access work better, I had to enable FUSE passthrough as in [these instructions](https://source.android.com/docs/core/storage/fuse-passthrough#implementing-fuse-passthrough). It seems to work well so far (although feels a bit slow but maybe that is related to my OTG cable).

**Comment by agnostic-apollo** [comment]
cool, although fuse passthrough would not apply to otg as that won't be emulated...

**Comment by ED4free** [comment]
On Android 12, I plug an OTG USB C dongIe formated exFat.
Installed the Termux from Github Actions build. After launching it, I called termux-setup-storage and grant the access. I verified in setting menu that "Manage all files" was granted.
Nevertheless,  if I make : ls -l /mnt/media_rw/  or ls -l /mnt/media_rw/8678-0073/ I  get permission denies.

With another app, having the same right MANAGE_EXTERNAL_STORAGE, this command works. It is with this app that I know that 8678-0073 is the identifier of my USB Key.

**Comment by ED4free** [comment]
Thank you @agnostic-apollo , it works.
Another question : I have the right on /mnt/media_rw/XXXX-XXXX , but not on /mnt/media_rw/
So do you know how to know the value of XXXX-XXXX ?
Thierry

**Comment by ED4free** [comment]
And thanks for telling me in which file are manage permission.
I think I'll add something link this,which work on my other app : 
```
        if (ContextCompat.checkSelfPermission(this, MANAGE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
            Log.d("Thierry", "Request MANAGE_EXTERNAL_STORAGE");
            ActivityCompat.requestPermissions(this, new String[]{MANAGE_EXTERNAL_STORAGE}, 1);
        } 
```

**Comment by agnostic-apollo** [comment]
Following should probably work, i haven't tested, check if it returns `/mnt/media_rw` path. You may need to check primary/emulated/removable state. I am not sure what external sd card that's inserted into sd card slot would return, it probably returns `/storage` path instead. You could probably also use `mount` command if it needs to be done in shell, but checking for `/mnt/media_rw` mount will also return the initial mount of external sd card if user has inserted that and you will then have to check if there is no mount for it's uuid under `/storage` as well, as usb otg should not.

https://developer.android.com/reference/android/os/storage/StorageManager#getStorageVolumes()

https://developer.android.com/reference/android/os/storage/StorageVolume#getDirectory()

As for requesting permission, check following, should only call it for Android `>= 12`.

https://github.com/termux/termux-app/blob/8e3a8980a849046adbd4156741e1d84047ee1df6/termux-shared/src/main/java/com/termux/shared/android/PermissionUtils.java#L342

**Comment by ED4free** [comment]
Good idea mount for finding the path of USB storage, this works fine : 
`mount | grep -ho '/mnt/media_rw/[0-9]{2}'`

**Comment by agnostic-apollo** [comment]
Best use `grep -E "^[^ ]+ /mnt/media_rw/[A-Z0-9]{4}-[A-Z0-9]{4} " /proc/mounts | cut -d' ' -f2` instead.

`/proc/mounts` format is specified by the kernel, `mount` command is a user space utility and has a different format.

We match the first two fields in the regex and then get the second one with `cut`. The space character before and after the second `/mnt` field ensures we are matching a mount destination and on the directory itself and not a mount on a subdirectory, the space character in paths itself is replaced with `\040` octal value in `/proc/mounts` file so that it does not interfere with space field separator. Your regex would also match entries where the mount source is under `/mnt`, like for a loop `ext4` image in sd card mounted at some other path. My regex starts with `^` to ensure that start of line, i.e first field is matched.

However, like I said, this will still return more that one entry if both a usb drive and an external sd card is mounted. You will then have to find for which entry `grep -qE "^[^ ]+ /storage/$(basename "$entry") " /proc/mounts` does not exit with exit code `0`.

**Comment by locuturus** [comment]
If I'm in the shell already I like ```df | grep vold``` to quickly find USB drive paths.

**Comment by ED4free** [comment]
Thanks a lot @agnostic-apollo , this command works perfectly, and it is surely more reliable than mine. You are rignt, on my device their are only number, but it can  be A-Z letter also. I keep your command for my initialization script. It search for external storage (SD or USB), if it found one it search on it  the configuration script with a `find`.
You are right @locuturus , the USB storage also appears in `df `command.  For SD cards I use : `df | grep -e '.*storage/[0-9A-Z].*' | sed 's#.*/storage#/storage#'`

**Comment by ED4free** [comment]
@agnostic-apollo , about the permission "Manage all files", I apologize because I have made something probably very dirty, but which ake what I need : 
```
    class TermuxActivityBroadcastReceiver extends BroadcastReceiver {
        @Override
        public void onReceive(Context context, Intent intent) {
            if (intent == null) return;

            if (mIsVisible) {
                fixTermuxActivityBroadcastReceiverIntent(intent);

                switch (intent.getAction()) {
                    case TERMUX_ACTIVITY.ACTION_NOTIFY_APP_CRASH:
                        Logger.logDebug(LOG_TAG, "Received intent to notify app crash");
                        TermuxCrashUtils.notifyAppCrashFromCrashLogFile(context, LOG_TAG);
                        return;
                    case TERMUX_ACTIVITY.ACTION_RELOAD_STYLE:
                        Logger.logDebug(LOG_TAG, "Received intent to reload styling");
                        reloadActivityStyling(intent.getBooleanExtra(TERMUX_ACTIVITY.EXTRA_RECREATE_ACTIVITY, true));
                        return;
                    case TERMUX_ACTIVITY.ACTION_REQUEST_PERMISSIONS:
                        Logger.logDebug(LOG_TAG, "Received intent to request storage permissions");
                        requestStoragePermission(false);

                        /// Ajout Thierry

                        if (ContextCompat.checkSelfPermission(TermuxActivity.this, MANAGE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
                            Log.d("Thierry", "Request MANAGE_EXTERNAL_STORAGE");
                            ActivityCompat.requestPermissions(TermuxActivity.this, new String[]{MANAGE_EXTERNAL_STORAGE}, 1);
                        }

                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                            if (!Environment.isExternalStorageManager()) {
                                //      if (true) {
                                //request for the permission
                                Log.d("Thierry", "Request ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION");
                                Intent intent2 = new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION);
                                String name = getPackageName();
                                Log.d("Thierry", "Package Name = "+name);
                                Uri uri = Uri.fromParts("package", name, null);
                                // Uri uri = Uri.fromParts("package", "eu.", null);
                                intent2.setData(uri);
                                startActivity(intent2);
                            }
                        }
                        ///// Fin ajouts Thierry

                        return;
                    default:
                }
            }
        }
    }
```

**Comment by locuturus** [comment]
> @locuturus , on my Android 12 device, the USB storage SOMETIMES also appears in `df `command. But sometimes not.

Ok, good to know it's not reliable across devices and/or OS versions. A little strange though - I picked this for myself a while ago because it actually does work on an A13 Samsung Tab S6 tablet and I was having trouble with that device.

**Comment by agnostic-apollo** [comment]
You can use this function in `bash` shell to find the most recently connected usb otg drive on Android `>= 11`. For Android `7`, there is a mount on both `/mnt` and `/storage` paths for usb otg, so cannot distinguish between usb otg (unreliable) and external sd card (reliable). I don't know which android version removed mounting at `/storage` path for usb otg, but its likely android 11 as it added `MANAGE_EXTERNAL_STORAGE` too, so possibly related. Note that if multiple usb otg drives are attached like with a usb hub or possibly multiple partitions exist in the same usb, then only the latest mount will be returned. This is done by checking matched entries of `/proc/mounts` in reverse order, as latest mount would come in the end.

You can paste the function in terminal or add to `~/.bashrc` or your scripts, etc.

```shell
find_most_recent_unreliable_storage_mount() {

    local return_value

    local i
    local storage_mounts_string
    local storage_mount
    local storage_mount_basename
    local unreliable_storage_mount
    local android_build_version_sdk
    local valid_number_regex='^[0-9]+$'

    local -a storage_mounts_array=()

    # Find android sdk/os version
    # Termux app exports ANDROID__BUILD_VERSION_SDK for `>= v0.119.0`
    if [[ ! "$ANDROID__BUILD_VERSION_SDK" =~ $valid_number_regex ]]; then
        android_build_version_sdk="$(unset LD_LIBRARY_PATH; unset LD_PRELOAD; getprop "ro.build.version.sdk")"
        return_value=$?
        if [ $return_value -ne 0 ] || [[ ! "$android_build_version_sdk" =~ $valid_number_regex ]]; then
            echo "Failure while finding \"ro.build.version.sdk\" property" 1>&2
            echo "ANDROID__BUILD_VERSION_SDK = \"$android_build_version_sdk\"" 1>&2
            if [ $return_value -eq 0 ]; then
                return_value=1
            fi
            return $return_value
        fi
    else
        android_build_version_sdk="$ANDROID__BUILD_VERSION_SDK"
    fi

    # If on Android `< 11`
    if [ "$android_build_version_sdk" -lt 30 ]; then
        echo "Cannot find unreliable storage mounts on Android sdk version '< 30'. Current sdk version is '$android_build_version_sdk'." 1>&2
        return 1
    fi

    storage_mounts_string="$(grep -E "^[^ ]+ /mnt/media_rw/[A-Z0-9]{4}-[A-Z0-9]{4} " /proc/mounts | cut -d' ' -f2)"
    return_value=$?
    if [ $return_value -ne 0 ]; then
        echo "Failure while finding most recent unreliable storage mount" 1>&2
        return $return_value
    fi

    if [ -z "$storage_mounts_string" ]; then
        echo "Failed to find any reliable or unreliable storage mounts" 1>&2
        return 1
    fi

    IFS=$'\n' read -r -d '' -a storage_mounts_array <<< "$storage_mounts_string"

    for (( i=${#storage_mounts_array[@]} - 1; i >= 0; i-- )) ; do
        storage_mount="${storage_mounts_array[i]}"
        storage_mount_basename="${storage_mount##*/}"

        grep -qE "^[^ ]+ /storage/$storage_mount_basename " /proc/mounts
        return_value=$?
        if [ $return_value -eq 1 ]; then
            unreliable_storage_mount="$storage_mount"
            break
        elif [ $return_value -ne 0 ]; then
            echo "Failure while finding if storage mount is unreliable" 1>&2
            return $return_value
        fi
    done

    if [ -z "$unreliable_storage_mount" ]; then
        echo "Failed to find any unreliable storage mounts" 1>&2
        return 1
    fi

    echo "$unreliable_storage_mount"

}
```

> Greate news : it works both for SD card and USB dongle !

The the `/mnt` grep should work for both. Really depends on what you are trying to do, your use case was usb otg only if I remember correctly.

>df | grep vold

`/dev/block/vold` entry would also exist for external sd cards (reliable) as vold mounts them too. Moreover, usb otg entry is not shown in `df` output on Android 11, but does on Android 14. Not really reliable to use `df` and `/proc/mount` should be preferred for utilities.

**Comment by agnostic-apollo** [comment]
>I tried to add this piece of code in requestStoragePermission() but in this case it was called twice, I didn't understand why.

You are calling `requestStoragePermission()`, then `requestPermissions()`, and then `startActivity()`, so of course there will be repeats. Moreover, `requestStoragePermission()` is already called by `TermuxActivity` twice in `master` branch, when requesting permission and when result is received. It's best to not mess with that logic. If you want to always request `MANAGE_EXTERNAL_STORAGE` permission on Android `>= 11`, it would be better to add following to start of `PermissionUtils.checkAndRequestLegacyOrManageExternalStoragePermission()` instead.

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
    if (Environment.isExternalStorageManager())
        return true;

    errmsg = context.getString(R.string.msg_storage_permission_not_granted);
    Logger.logError(LOG_TAG, errmsg);
    if (showErrorMessage)
        Logger.showToast(context, errmsg, false);

    if (requestCode >= 0)
        requestManageStorageExternalPermission(context, requestCode);

    return false;
}
```

>the authorization require a restart of Termux-app to be taken into account.

You can run `kill "$TERMUX_APP__PID"` to kill termux app, but it will not restart it, there are ways to trigger a restart from java code with some hacks.

- https://stackoverflow.com/questions/6609414/how-do-i-programmatically-restart-an-android-app
- https://stackoverflow.com/questions/17795189/how-to-programmatically-force-a-full-app-restart-e-g-kill-then-start

If you just want to kill from java, then can use following. Note the import, `java.lang.Process` is different and will be used by default.

```java
import android.os.Process;

try {
    finishAffinity();
} catch (Exception e) {
    // Ignore
}

Process.killProcess(Process.myPid());
```

**Comment by ED4free** [comment]
> it would be better to add following to start of PermissionUtils.checkAndRequestLegacyOrManageExternalStoragePermission() instead.
It works fine, I keep it instead of my changes, thank you.

**Comment by ED4free** [comment]
@agnostic-apollo 

> The the /mnt grep should work for both. Really depends on what you are trying to do, your use case was usb otg only if I remember correctly.

My use case is : I am looking for existing script called "Eduphone_initTX.sh", I first search in SD card or USB if exists, then in /sdcard in not. If I find this sh I execute it. This task is in a small sh put in profile.d of bootstrap, it does nothing if application directory already exists. The SD card or otg USB contains the whole data for Eduphone installation ( mainly tar.gz of the the working environment, and some apk). Eduphone_initTX.sh make the installation : install the apk (termux-api, termux-widget, a wifi hot-spot for old smartphone, my apk for managing the configuration) and restore the tar.gz
So for me SD card or otg USB is the same.

**Comment by agnostic-apollo** [comment]
You are welcome.

By sd card do you mean, "sd card that gets inserted into sd card slot of phone" or "sd card connected with usb otg cable and external sd card reader"?

**Comment by ED4free** [comment]
By sd card I mean "sd card that gets inserted into sd card slot of phone". 
I manage in the same way "sd card that gets inserted into sd card slot of phone" and "anything connected with usb otg".

```
# Search in external storage SD or USB
SEARCH="Eduphone_initTX.sh"
FILE=""
LEXTST=$( grep -E "^[^ ]+ /mnt/media_rw/[A-Z0-9]{4}-[A-Z0-9]{4} " /proc/mounts | cut -d' ' -f2)
    FILE=""
    for EXTST in $(echo "$LEXTST"); do
    CMD="TMPFILE=\$(find $EXTST -maxdepth 3 -type f 2>$LOGFILE | grep -e '.*$SEARCH')"
    if  [ "$EXTST" != "" ]; then eval "$CMD"; fi;
    if [ "$TMPFILE" != "" ]; then FILE="$TMPFILE"; fi;
    echo "FILE=$FILE"
    done
```
nb : sorry for my poor bash :)

**Comment by agnostic-apollo** [comment]
Can you send output for `stat /mnt/media_rw/XXXX-XXXX` and `stat /storage/XXXX-XXXX` for the sd card UUID paths? And which phone are you testing on?

Also can you access the sd card with `/storage` path?

**Comment by ED4free** [comment]
On SD card : 
```
~ $ stat /mnt/media_rw/0B99-1B07
  File: /mnt/media_rw/0B99-1B07
  Size: 32768           Blocks: 64         IO Block: 32768  directory
Device: 179,1   Inode: 1           Links: 19
Access: (0770/drwxrwx---)  Uid: (    0/    root)   Gid: ( 1023/media_rw)
Access: 2024-03-29 22:20:00.000000000 +0100
Modify: 2024-03-29 22:20:00.000000000 +0100
Change: 2024-03-29 22:20:00.000000000 +0100
 Birth: -

~ $ stat /storage/0B99-1B07
  File: /storage/0B99-1B07
  Size: 32768           Blocks: 64         IO Block: 32768  directory
Device: 0,89    Inode: 1           Links: 19
Access: (0770/drwxrwx---)  Uid: (    0/    root)   Gid: ( 9997/everybody)
Access: 2024-03-29 22:20:00.000000000 +0100
Modify: 2024-03-29 22:20:00.000000000 +0100
Change: 2024-03-29 22:20:00.000000000 +0100
 Birth: -
~ $
```
On otg 
```
~ $ stat /mnt/media_rw/8678-0073
  File: /mnt/media_rw/8678-0073
  Size: 131072          Blocks: 256        IO Block: 131072 directory
Device: 8,49    Inode: 1           Links: 6
Access: (0770/drwxrwx---)  Uid: (    0/    root)   Gid: ( 1077/external_storage)
Access: 2024-03-29 22:22:06.000000000 +0100
Modify: 2024-03-29 22:22:06.000000000 +0100
Change: 2024-03-29 22:22:06.000000000 +0100
 Birth: -
```
Notice that this point works fine.

**Comment by agnostic-apollo** [comment]
Thanks and what's the output of `cat /proc/self/status | grep ^Groups:`?

**Comment by ED4free** [comment]
```
~ $ cat /proc/self/status | grep ^Groups:
Groups: 1077 3003 9997 20396 50396

```

**Comment by agnostic-apollo** [comment]
Are you on Android 12 on this device as stated before?

**Comment by ED4free** [comment]
Android 12
