### ISSUE TITLE
how to start codiad ?

### ISSUE THREAD

**Issue by msh2050** [termux/termux-app#710]
I install codiad from @rnauber script how do I can start it?!
the script run without any issue (after installing ### wget and ### git pkg)
I'm using fresh install of termux is there any other required pkg? 
but how I start the web server?! so can navigate to 127.0.0.1:9876

**Comment by msh2050** [comment]
worked after restart the device...

**Comment by rayfoss** [comment]
it starts for me after installing the readline package. However, no files show up under termux_home.

**Comment by rnauber** [comment]
This should be fixed now:
https://gist.github.com/rnauber/9f579d1480db4cc5a9a3c97c00c52fb9
