### ISSUE TITLE
documents provider: mime type map fails with .JPG

### ISSUE THREAD

**Issue by chrysn** [termux/termux-app#721]
The mime type for .JPG files exported to the Storage Access Framework via the documents provider is the fallback application/octet-stream; thus, image viewers won't open it.

Given that file extensions are usually case insensitive and the library appears to only recognize lower-case variants (tried .html, .doc and .txt), and that digital cameras often store uppercase letters, I suggest that lowercasing the extension before [here](https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/filepicker/TermuxDocumentsProvider.java#L199) as a mitigation.

(I can't tell whether there might be better ways than using webkit's mimetypemap (maybe libmagic?) -- but lowercasing would mitigate the immediate issue).

Thank you for maintaining termux and the documents provider; it makes [dealing with the android file system limitations](http://git-annex.branchable.com/forum/Dealing_with_crippled_Android_file_system/) much better!

**Comment by fornwall** [comment]
Thanks! This should now be fixed in version 0.61 of the app, which has now been released and should be available in Google Play within a few hours (and on F-Droid within a day or so)!
