### ISSUE TITLE
Termux SSH Google cloud Not Connected

### ISSUE THREAD

**Issue by mskian** [termux/termux-app#724]
I try to connect my google cloud VM Machine via Terminal OpenSSH by creating SSH Keys '

`ssh-keygen -t rsa -f ~/.ssh/my-keyfilename -C username`

I add the pub key on Google VM 

```
ssh user@ip
```
got this -  `permission denied (publickey)`

**Comment by xeffyr** [comment]
@mskian Try to explicitly set ssh key name: `ssh -i ~/.ssh/my-keyfilename user@ip`

**Comment by mskian** [comment]
@xeffyr  Perfect its working :100:

**Comment by buguniaogu** [comment]
@xeffyr . Still got got "permission denied" on termux. But it works well on juicessh or putty. . ssh -i ~/.ssh/id_rsa usr@ip -p 222 😶

**Comment by xeffyr** [comment]
@buguniaogu Make sure that you have added correct keys, if not sure - add all your keys: from putty, juicessh and Termux. And make sure that public key lines **are not truncated**.

Why not to troubleshoot this issue by using `ssh -v -i {your key} {user@host}` or looking sshd logs on server side to troubleshoot authentication issues ? Or we should know what/where configured and which keys exactly were used in your connection ?

**Comment by buguniaogu** [comment]
@xeffyr thanks, it works now. Wrong pair keys before.
