### ISSUE TITLE
Update breaks: The method driver 'xz' could not be found.

### ISSUE THREAD

**Issue by 5chdn** [termux/termux-app#73]
![photo_2016-04-01_10-42-02](https://cloud.githubusercontent.com/assets/15729797/14202104/72b4dd8e-f7f6-11e5-8205-0a1282dd5ea5.jpg)

- Termux version 0.32
- Android version 6.0.1
- Kernel 3.4.0
- LG Nexus 5

**Comment by fornwall** [comment]
What is the output of `apt --version`?

**Comment by 5chdn** [comment]
$ apt --version
    apt 1.0.10.2 for arm compiled on Aug 25 2015 17:40:58

**Comment by Neo-Oli** [comment]
You're using a very old version of apt. I think you have the same issue as https://github.com/termux/termux-app/issues/64. Can you try manually updating apt and liblzma with 
```
wget http://termux.net/dists/stable/main/binary-arm/liblzma-5.2.2_arm.deb
dpkg -i liblzma-5.2.2_arm.deb
wget http://termux.net/dists/stable/main/binary-arm/apt_1.2.4_arm.deb
dpkg -i apt_1.2.4_arm.deb
```
after that you should be able to run `apt update && apt upgrade` again.

**Comment by fornwall** [comment]
@Neo-Oli Thanks! This is probably the reason.

@5chdn Do the manual steps above as a one-time workaround for your old apt version and re-open the issue if any problem remains!

**Comment by 5chdn** [comment]
updated `apt` manually and everything works now. thanks so much.
