### ISSUE TITLE
help after reboot .. permission denied all files

### ISSUE THREAD

**Issue by Dj-jom2x** [termux/termux-app#730]
afrer reboot I cant now edit or read files

even

lua test.lua

will throw permission denied..

how to fix it???

Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> os.exit()

$ cd ob
$ lua ob.lua
lua: cannot open ob.lua: Permission denied
$

**Comment by xeffyr** [comment]
After reboot, or after root ? If root - `/system/bin/restorecon -R /data/data/com.termux`.

**Comment by Dj-jom2x** [comment]
after reboot.. my phone is already rooted long time ago.. i just installed this yesterday..

everything when fine.. then I tried to restart my phone then boom hehe.. all permission is messup.. but thanks for this :)
