### ISSUE TITLE
Home and End on a hardware keyboard do not seem to work, likewise SHIFT+PAGEUP/DOWN

### ISSUE THREAD

**Issue by felagund** [termux/termux-app#731]
I have a hardware keyboard on my phone (Gemini PDA) that has Home, End and PgUp and PgDn keys that are entered by pressing fn+left/right/up/down arrows respectively. While ctrl+left jumps to previous word correctly, these keys behave as if I was not pressing the fn key at all (so while I am issueing "home", Termux thinks I am pressing the left key ignoring me also pressing "Fn" at the same time).

I will be happy to provide additional debugging, tried running xev but that is missing due to Android not running X.

**Comment by zevv** [comment]
Thanks for figuring that out!

Would this do? 

https://github.com/zevv/termux-app/commit/e71ed7b2923caa770423c5687f0bb6d7b9718521

**Comment by fornwall** [comment]
The fix by @zevv in #794 has been released in version 0.65 of the app and should be available as an update shortly.

Thanks for all the work here, let us know if anything can be improved!
