### ISSUE TITLE
Extra Keys overlay not working on every phone.

### ISSUE THREAD

**Issue by BorhnN** [termux/termux-app#739]
The only reason I wasn't using Termux daily was not being able to press the up arrow button. I didn't wanna use other keyboards because they weren't so accurate. 

I was watching #12 regularly over email and was so happy when I finally got that email.

Guess who didn't have his up arrow key?

On my phone there's only the bottom row taking as much space as two rows.

I've tried cleaning data, re-installing, switching to stable channel. It didn't work, Tried on another phone, it was working.

|   | My phone   (One row)  | Another phone (Two Rows)  | Comment |
| -------------: |:-------------| :-----|:----:|
| Model | Redmi Note 2 (hermes) | Redmi 3S prime |
| Android Version | 5.0 | 6.0 | Probable cause (didn't test it) | 
| ROM  | MIUI | MIUI |
| Root| Yes | No | 
| Installation | Updated (Google Play) | Installed (Google Play) | Not probably (had a complete reinstall on my phone too |
| Termux version | 0.63 | 0.63 |
| Google Play channel | Beta | Stable | Not likely (Switched my channel to stable too) |
| Scr | ![Screenshot Redmi Note 2](https://i.imgur.com/3ND7xeIm.png) <br/> [Full size](https://i.imgur.com/3ND7xeI.png) | ![Screenshot Redmi 3A](https://i.imgur.com/PyYPd71m.png) <br/> [Full size](https://i.imgur.com/PyYPd71.png) | Yeah my bad luck |
| Res | 1080p | 720p | not likely (There are too many 1080p phones now-a-days) |

**Comment by xeffyr** [comment]
@BorhnN Did you checked if it works on v0.62 ?

**Comment by BorhnN** [comment]
@xeffyr how do I get it?

GitHub releases don't have any apks
Can't downgrade on Google Play.

Plus, on both phones it's on version 0.63

**Comment by BorhnN** [comment]
@xeffyr Not working on 0.62 either.

**Comment by BorhnN** [comment]
Thanks, @xqdoo00o for the fix. I've tried to work out a generic solution. But yours was quick and nice.

Waiting for the release.

**Comment by quite** [comment]
I'm missing the overlay keys on Lineage 14.1, android 7.1.2 on a nexus 5. Termux 0.65.

**Comment by quite** [comment]
Really, how?

**Comment by xeffyr** [comment]
> @quite Tap Volume Up + q and extra keys should appear.

**Comment by BorhnN** [comment]
Or, swipe from left (left navigation drawer)> long press on "KEYBOARD"

**Comment by quite** [comment]
Ah, that worked! Thanks. Volume Up + q did nothing.
