### ISSUE TITLE
Can't use ping, ping6 breaks with: raw socket operation not permitted

### ISSUE THREAD

**Issue by 5chdn** [termux/termux-app#74]
![photo_2016-04-01_10-42-07](https://cloud.githubusercontent.com/assets/15729797/14202103/72b2d3b8-f7f6-11e5-8690-1a05093e10bc.jpg)

- Termux version 0.32
- Android version 6.0.1
- Kernel 3.4.0
- LG Nexus 5

**Comment by Neo-Oli** [comment]
`ping` is normally part of `termux-tools` (which just executes /system/bin/ping). Is that package installed?

**Comment by 5chdn** [comment]
![photo_2016-04-01_11-08-28](https://cloud.githubusercontent.com/assets/15729797/14202755/1b086110-f7fa-11e5-941f-1c18532a9d11.jpg)

Yes `termux-tools` seems to be installed. It looks like a lot is broken here. Should I try reinstalling all termux apps?

**Comment by Neo-Oli** [comment]
Does `$PREFIX/bin/ping` exist? 
If you launch `sh` so no user configuration is made can you then use `ping`?
Can you do `/system/bin/ping localhost`?

**Comment by 5chdn** [comment]
`/system/bin/ping localhost` works. cool.

`$PREFIX/bin/ping` does not exist.

However, `$PREFIX/bin/ping6` does exist.

**Comment by Neo-Oli** [comment]
I think you need to update termux-tools. Prior to Termux version 0.31 `/system/bin/` was in the $PATH variable. It has then be removed and important system tools like ping have been added to `termux-tools` (as a short script, which just launches `/system/bin/ping`). Can you try `apt update && apt upgrade` once #73 has been resolved for you?

**Comment by fornwall** [comment]
The `ping6` tool has been removed from inetutils (since it requires root/setuid) and has been added to termux-tools as a shortcut to the system one (as already done for `ping`).

**Comment by 5chdn** [comment]
#74 also fixed this issue. thanks again for this awesome terminal app.
