### ISSUE TITLE
Combinatorial key on the Extra key overlay seems not work

### ISSUE THREAD

**Issue by uurun** [termux/termux-app#745]
I replaced bash with fish shell and found that it did not work by pressing the composite key on the extra key overlay, like ctrl+ right ..

**Comment by tomty89** [comment]
Did you just release the ctrl press before you press right? Since long press on ctrl and alt stopped working since the new two-bar thing is introduced. I wish that would get fixed.

**Comment by Auxilus** [comment]
not just CTRL, all the buttons are getting highlighted on the first press in the session

**Comment by xqdoo00o** [comment]
I had the feature included in the previous commit, but I'm not sure the code logic is correct, so I just move it(ce2d1c0).
