### ISSUE TITLE
New keybar (VolumeUp+q)

### ISSUE THREAD

**Issue by Chaformbintrano** [termux/termux-app#749]
It is much less functional and needlessly big. Could you give the old one back or give an option to switch to it?

**Comment by jayesh-bhoot** [comment]
The 2 rows of extra keys is indeed a hindrance. Not a lot of phones have a huge display to compensate for the resulting loss of the screen estate.

In my own case, I cant enable the rows because the full keyboard eats most of my screen estate. But disabling the rows robs me of one-handed use of ctrl and alt keys.

![screenshot_20180702-171049](https://user-images.githubusercontent.com/1915507/42162172-599aa592-7e1b-11e8-98ba-f46af46be715.png)


An ideal, but admittedly more effortful way out could be to eschew the idea of multiple rows in favour of a config where the user could specify the keys and their order of display in a single row. That should cover the needs of the most.

**Comment by kosovo0275** [comment]
Please revert this change. It seems almost careless that this design was implemented, considering there's no real purpose or practicality backing it. Theres also a few insanely obvious and more preferable ways that this change could have been approached.

**Comment by daemondev** [comment]
When using Hacker Keyboard, the extra keys are useless, it should be the user's choice "no extra keys -> old extra keys -> extended extra keys", I already had my environment very well configured, but this change made me lose everything, Now I have to do a downgrade at 0.61.

**Comment by porasjeet** [comment]
I think this should be configurable because I really like the new arrow keys but don't necessarily need the other keys besides TAB, CTRL and ALT.

Or the extra keys view can be changed to a horizontally scrollable list like how QuickEdit implements extra keys.

**Comment by xeffyr** [comment]
> can be changed to a horizontally scrollable list like how QuickEdit

Can't be changed. Scrolling left activates alternative text field which allows text autocorrection/prediction and swype input.

> I think this should be configurable

There is a pull request but it seems that it's author forgot about it: https://github.com/termux/termux-app/pull/650.

**Comment by porasjeet** [comment]
We can shift the text input field to the left side, so swiping right shows the text field and scrolling left scrolls the extra keys.

**Comment by robertvandeneynde** [comment]
Hey guys, the first version of the configurable is almost done in #788, new ideas or critics for configuration are welcome!

**Comment by neo-expert** [comment]
Please bring the two rows solution back again.
For me it was the best solution until now. I used all the keys. Especially the "left and right -arrow keys"
Can we have it configurable?

**Comment by robertvandeneynde** [comment]
Yes it's configurable (create .termux/termux.properties)

and I also think the two row solution is a best default, I changed the default and that was not a good idea.

That's easily changeable in the source code as seen here : https://github.com/termux/termux-app/commit/3693e3c1b6da04398cbd73a28b44a764abc9bc3e

**Comment by trygveaa** [comment]
It is configurable now, so this issue can be closed. Seems like it isn't documented yet though.

You can configure it by setting `extra-keys` in `~/.termux/termux.properties`. For the old keys, set this:

```
extra-keys = [["ESC", "/", "-", "HOME", "UP", "END", "PGUP"], ["TAB", "CTRL", "ALT", "LEFT", "DOWN", "RIGHT", "PGDN"]]
```
