### ISSUE TITLE
Install from source

### ISSUE THREAD

**Issue by Drakesinger** [termux/termux-app#75]
Greetings, the help does not say anything regarding installing applications from source. 

During my attempts, the problems I have encountered are:
* Shebangs in generated intermediary configuration files fail due to wrong location. 
    Any way to fix this, make a symbolic link or something ? 
* Application headers are located in different places than expected: 
```bash
$ gem install rails - v 4.2.0
```
The configuration can't find the Ruby header:
```bash
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/json-1.8.3/ext/json/ext/generator
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20160401-9883-kd0wjv.rb extconf.rb
mkmf.rb can't find header files for ruby at /data/data/com.termux/files/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1
```
The header is located here :

/data/data/com.termux/files/usr/include/ruby-2.3.0

Think there are any solutions?

**Comment by fornwall** [comment]
> Shebangs in generated intermediary configuration files fail due to wrong location. Any way to fix this, make a symbolic link or something ?

To fix shebangs pointing to `/bin/` and `/usr/bin` you could create symlinks for these folders if you have root access.

You could also `apt install chroot` and run the `termux-chroot` utility in that package which sets up a chroot without requiring root.

> The configuration can't find the Ruby header: [...]

Do you still have this problem (re-open this issue if so)? What is the output of `ruby -e 'p RbConfig::CONFIG["rubyhdrdir"]'`?
