### ISSUE TITLE
Termux won't load binaries.

### ISSUE THREAD

**Issue by Bholuvilla** [termux/termux-app#761]
After installing Termux from Play Store and opening, it just install till infinity and some times shows an error, unable to load binaries, please try after some time. No network problem though.

**Comment by Grimler91** [comment]
Are you trying to install termux on the external sdcard or something like that?

**Comment by Grimler91** [comment]
Yeah, what it does during that pop-up is to download a bootstrap zip from http://termux.net/bootstrap/ and then extract it. Your android logs might show more information about what goes wrong.
Which android version and which device are you using?

**Comment by tomty89** [comment]
Can you successfully access this site with your browser: http://termux.net/bootstrap/

**Comment by Bholuvilla** [comment]
Xiaomi Mi A1

**Comment by Bholuvilla** [comment]
Yes I can access it.

**Comment by Grimler91** [comment]
@Bholuvilla So it works now? How did you fix it?

**Comment by Bholuvilla** [comment]
Used DNS network to fresh download termux app

**Comment by Bholuvilla** [comment]
@Grimler91 can you help me with my new issue.
