### ISSUE TITLE
how to run x86 programs?

### ISSUE THREAD

**Issue by Dj-jom2x** [termux/termux-app#764]
I was wondering if i can run x86 on termux...I have 64 bit system. is there 86_64 version of termux?

**Comment by xeffyr** [comment]
@Dj-jom2x Which CPU architecture on your device ? Post output of `uname -m`.

**Comment by Dj-jom2x** [comment]
Linux localhost 3.18.22+ #1 SMP PREEMPT Wed Dec 20 22:32:29 CST 2017 aarch64 Android

I really wanted to execute 32bit on this thing instead of installing on limbo :(

**Comment by xeffyr** [comment]
@Dj-jom2x You need a QEMU to run x86 programs which is available in my repository currently.

If your program is not complex (e.g. statically compiled binary), you can use qemu in user-mode:
1. qemu-user-i386: https://termux.xeffyr.ml/dists/extra/main/binary-aarch64/qemu-user-i386_2.12.0-2_aarch64.deb
2. qemu-user-x86_64: https://termux.xeffyr.ml/dists/extra/main/binary-aarch64/qemu-user-x86_64_2.12.0-2_aarch64.deb

I have used them to make `fasm` and `pandoc` available for Termux:
* https://termux.xeffyr.ml/dists/extra/main/binary-all/fasm_1.73.04_all.deb
* https://termux.xeffyr.ml/dists/extra/main/binary-all/pandoc_2.2.1_all.deb

If your program is complex - use a qemu-system* packages, Limbo, or you need different device. Termux can't execute programs for different architectures.

**Comment by Dj-jom2x** [comment]
yes its static

btw i install it inside termux how to run it ?
using qemu?

**Comment by xeffyr** [comment]
For x86_64: ```qemu-x86_64 ./path/to/binary```
For x86 (32bit): ```qemu-i386 ./path/to/binary```

As shown, just prefix it with qemu executable.

**Comment by Dj-jom2x** [comment]
omg your the best man... 10/10 thanks thanks.. you save me a lot of space.

**Comment by tigran123** [comment]
Are those qemu binaries still available (or newer versions of them)? I can't access them.

**Comment by xeffyr** [comment]
qemu is available in `unstable-repo`.

**Comment by tigran123** [comment]
@xeffyr Thank you. I knew that, but I wasn't sure if it contains your fixed. I assumed it was "plain vanilla" version :)

**Comment by xeffyr** [comment]
There no "plain vanilla" version for Termux. It just can't be compiled.
For vanilla version you will need to setup a chroot environment of Ubuntu/Debian/etc...

**Comment by tigran123** [comment]
Thanks. I compiled statically a hello world program in C on x86_64 and then run `qemu-x86_64 hello` and it is still consuming CPU cycles (5 minutes already) but no sign of "Hello, world!" output yet...

**Comment by tigran123** [comment]
strace shows a loop like this:

```
futex(0x58ba03ef00, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x58ba03eecc, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x58ba03ef00, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x58ba03eecc, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x58ba03ef00, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x58ba03eecc, FUTEX_WAKE_PRIVATE, 2147483647) = 0

```

**Comment by xeffyr** [comment]
That why qemu is in "unstable packages". It works differently on different devices.
The most stable qemu packages are only that compiled for aarch64.

Probably I will need to downgrade qemu to 3.1.0 like was done for X11 packages, as v4.0.0 has really strange behaviour. Or try the newer 4.1.0 rc.

**Comment by xeffyr** [comment]
I have following:
```
(process:21183): GLib-CRITICAL **: 22:38:17.366: g_tree_ref: assertion 'tree != NULL' failed

(process:21183): GLib-CRITICAL **: 22:38:17.366: g_tree_destroy: assertion 'tree != NULL' failed
```

Didn't observed this previously...

**Comment by ByRussX** [comment]
Qemu is not running my 32 bits code

**Comment by Rhythm113** [comment]
@xeffyr I'm getting Memory Allocation Error Any Solution?
