### ISSUE TITLE
Persistent Home Directory

### ISSUE THREAD

**Issue by mrjpaxton** [termux/termux-app#770]
What I'm looking for is a nice, convenient way to store configuration settings for externally running applications in Termux. For example, when I install Midnight Commander (mc) or `pip install youtube-dl` or edit my `~/.vimrc` or `~/.bashrc`, etc... I would like my settings to still exist even when I remove Termux, even by accident (somehow).

Let's say, I give Termux storage permissions (now possible starting with Nougat). So then, somewhere in `/sdcard/` directory, I should then be able to make a directory where I can store dotfiles and settings for applications, like a "second home folder" if you will.

Is it as simple as using a home directory symlink, or appending something to $PATH, or is this more complex?

Something more of a streamlined solution would be great to add to Termux!

**Comment by mrjpaxton** [comment]
Okay, so far using a symlink works.

Here's what I did:
1. Make sure storage permissions are enabled
2. Enter `cd ..`
3. Move/create home directory to a destination such as `/sdcard/Android/data/com.termux/home`
4. Enter `ln -s /sdcard/Android/data/com.termux/home home`
5. Restart Termux and run again

Should work just fine.

**Comment by Grimler91** [comment]
You can keep the in a git project. After installing termux you can then do `git clone smth` and run a script/make/w/e to cp or ln them to HOME.

Just be sure to not put sensitive information in them (if you use github or other public git site).

There's also the [vcsh](https://github.com/RichiH/vcsh) (available in termux) which aims at simplifying/improving this further. I haven't tested it though.

**Comment by mrjpaxton** [comment]
I don't really like using Git to sync home directories like that. Besides, the home directory that I use on my desktop is way significantly more bloated than I need it to be. Likely the case for most people.

I've just added this to my .bashrc for now:

```
alias termux-backup-home="tar czf /sdcard/Termux-home.tar.gz -C ~ ."
alias termux-restore-home="tar xf /sdcard/Termux-home.tar.gz -C ~"
```

**Comment by xeffyr** [comment]
Closing as implementable on "user level" - use either symlinks, backups via git, tar or other solutions.

Implementing "backup" feature in terminal application is overkill - shell provided by Termux gives user enough freedom to do this in preferred way.

**Comment by sampathsabhi** [comment]
Please give a video

**Comment by thecipherx** [comment]
I'm Using a Simple Shortcut

Just edit the bash.bashrc file
and add the needed lines 

HOME=/path/you/need
cd $HOME


give the path to your Folder in Internal Storage to the variable. That's all.

It'll Permanently Make the Changes

**Comment by KMohZaid** [comment]
> Okay, so far using a symlink works.
> 
> Here's what I did:
> 1. Make sure storage permissions are enabled
> 2. Enter `cd ~/..`
> 3. Move/create home directory to a destination such as `/sdcard/Android/data/com.termux/home`, make sure to `rm -rf home/` if creating one.
> 4. Enter `ln -s /sdcard/Android/data/com.termux/home home`
> 5. Restart Termux and run again
> 
> EDIT: Never mind. Doesn't work very well since the /sdcard directory has no execute permissions, and doesn't support symbolic links inside this directory...

Thanks

**Comment by artisticfox8** [comment]
> Closing as implementable on "user level" - use either symlinks, backups via git, tar or other solutions.
> 
> Implementing "backup" feature in terminal application is overkill - shell provided by Termux gives user enough freedom to do this in preferred way.

There should be a way that is not a third party hack or that doesn't require deleting your home directory first. I think this should be reopened. It does not matter there is a workaround, it is a valid feature request.

**Comment by artisticfox8** [comment]
> I'm Using a Simple Shortcut
> 
> Just edit the bash.bashrc file
> and add the needed lines
> 
> HOME=/path/you/need
> cd $HOME
> 
> give the path to your Folder in Internal Storage to the variable. That's all.
> 
> It'll Permanently Make the Changes

What is the file location?
