### ISSUE TITLE
Unable to use termux to reboot an Android device

### ISSUE THREAD

**Issue by DeviousPenguin** [termux/termux-app#773]
Hi, I'm getting started with Termux but I'm a little stuck, I'd like to reboot my phone from a script.

When I try the 'reboot' command I get this error:

error code: 127
message: "Command failed: reboot
/data/data/com.termux/files/usr/bin/sh: 1: reboot: not found↵"

I've tried the `reboot` command using ADB and it works, so I need to copy the 'reboot' command to the /data/data/com.termux/files/usr/bin/ folder or is there a better way? 

I tried searching through the additional packages but nothing seems to allow rebooting.

**Comment by Grimler91** [comment]
Have you tried `/system/bin/reboot` or `/system/bin/sh /system/bin/reboot`?

**Comment by DeviousPenguin** [comment]
Hi, thanks I seem to be getting somewhere, `/system/bin/reboot` gives:

`reboot: permission denied` so it looks like I may need to be rooted for this command to work, I'll have to see if this is possible.

`/system/bin/sh /system/bin/reboot` gives an odd error message however:
`/system/bin/reboot[1]: syntax error: '4?14' unexpected`

I'll see if I can get `su` on to my device and try `/system/bin/reboot` again. :)

**Comment by Grimler91** [comment]
`reboot` probably isn't a shell script so `/system/bin/sh /system/bin/reboot` was a bad suggestion..
It works without root on my particular rom, android 8.0. I'm surprised it does though, feels kinda bad that apps can reboot the device at will.

**Comment by mikroskeem** [comment]
Rebooting an Android device requires usually root (heck - `reboot(2)` function can't be run without root at all) and Termux does not add `/system/bin` into PATH environment variable - hence the "command not found" at first place.

Why would you want to reboot your phone from Termux? Automation?

**Comment by duttaditya18** [comment]
`/system/bin/reboot` works when running termux with root priviledges

**Comment by sp3cred** [comment]
you have to run this command to reboot android from termux
`su -c "reboot"`
ore create a script to run with crontab
vim reboot.sh
insert inside the file
#!/bin/bash
su -c "reboot"
save
chmod +x reboot.sh

and this script insert on crontab -e
