### ISSUE TITLE
Node.js 8 NPM Error on Android – 8.0 Oreo

### ISSUE THREAD

**Issue by mskian** [termux/termux-app#778]
> **Node.js 8 NPM Error on Android – 8.0 Oreo**

While try to Install Node packages via `npm` I got this Below error

### Example

```
$ npm i -g npm

npm ERR! Cannot read property 'length' of undefined
npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2018-07-14T07_55_29_568Z-debug.log
```

Any Solution to fix this?

**Comment by Grimler91** [comment]
The mentioned log in the error message sould be useful to see what's going on.

**Comment by mini-web** [comment]
I modified /usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js to set maxConcurrentWorkers to 4.

**Comment by mskian** [comment]
@mini-web is this Safe method?

**Comment by aadilayub** [comment]
I am experiencing this issue as well.

**Comment by Quasic** [comment]
I was testing different methods of fixing it. I think it is safe to guess the number; a bad guess should only affect speed, not accuracy, for npm. If you want to try my script in https://github.com/Quasic/cpuinfo, it tries various methods of aquiring the number. Some are more reliable than others.

**Comment by F0RIS** [comment]
Galaxy S7 with Oreo. Same thing :/

**Comment by F0RIS** [comment]
any updates on this?

**Comment by fornwall** [comment]
Closed in favour of https://github.com/termux/termux-packages/issues/1798, track that issue!
