### ISSUE TITLE
Extra keys accessibility and theme

### ISSUE THREAD

**Issue by clragon** [termux/termux-app#779]
It would be nice if the extra keys would adapt themselves to the used theme.

I would also appreciate a setting or possibility to show and hide the keys by a simple tap of the console itself; it appears to increase workflow because swiping up the menu and long-pressing isn't required.

**Comment by empjustine** [comment]
The extra keys do adapt to the current Termux::Style color scheme. Using 0.64.

You don't need to long press the menu if you have a software touch keyboard, Volume up+Q does the same thing.

**Comment by clragon** [comment]
hmm... Is there a list of all these shortcuts anywhere?

Also, weird; The extra keys are black on my device, I'm using the solarized theme though. Is that intended?
