### ISSUE TITLE
All files created by me(root) denied permission read this for more info

### ISSUE THREAD

**Issue by Dj-jom2x** [termux/termux-app#784]
well if i created a new folder using a file manager as a root. I used fx file manager.

When you type cd folder_name
it says : permission denied..

unless u run this 

restorecon -R /data/data/com.termux

each files i have to execute that 😢😢😢😢.

this only happens to me when u install termux then restarted your phone..

but if i reinstalled this termux and never restart my phone. it will work just fine even if i created any files as a root.

but that doesn't count as a solution only a workaround :(.. I don't want to resetup over and over again :(

**Comment by empjustine** [comment]
Default SELinux settings prevent applications from reading and writing other applications files even as root. Once a file or folder has been written by an app, it's considered that app folder.

Can't you use symlinks to shared storage instead? Shared storage (if done correctly using AOSP APIs) should have the correct SELinux ACL and uid/gid out of the box.

**Comment by its-pointless** [comment]
Yeah other work around is copying files to /sdcard then copying back using termux.

**Comment by Dj-jom2x** [comment]
nah it's fine now..

setup storage

then put on auto execute on start up.
cd location to my sd card/termux files.

so i dont have to deal with selinux anymore.
