### ISSUE TITLE
Expose files to external editors using Storage Access Framework

### ISSUE THREAD

**Issue by johnmellor** [termux/termux-app#79]
I'd like to use Termux for git/compiling/executing, but prefer external Android editors for editing source code.

The obvious approach, of doing `git init` or `git clone` in `/sdcard` fails with:
```error: chmod on /storage/emulated/0/reponame/.git/config.lock failed: Operation not permitted```
(see https://plus.google.com/+LarsStokholm/posts/eZqMLNmKX1n and similar issue https://github.com/corbinlc/gnuroot/issues/55). It would be great to find a workaround for that, but it seems tricky.

So instead, how about making Termux's app-private storage available to other apps via a Storage Access Framework DocumentsProvider? For example with [Turbo Editor](https://play.google.com/store/apps/details?id=com.maskyn.fileeditor) you can enable "Use the Storage Access Framework" from the right hand drawer, and then it uses the SAF to open files, and can subsequently save them to the same location. Not quite as flexible as making files available via the sdcard, but perhaps better than nothing?

**Comment by fornwall** [comment]
Thanks for the suggestion! For the git issue, there may be a solution - see https://github.com/termux/termux-packages/issues/227 and comment there what you think about the proposed patch!

However, adding a document provider for the Storage Access Framework seems like a good idea in general, not only to work around the git issue, so let's leave this issue open while I'm looking at it!

**Comment by fornwall** [comment]
The v0.34 update of the Termux app, which should be available as an update shortly, now implements the Storage Access Framework to expose files under `$HOME` for e.g. editing with Turbo Editor.

Try it out and let me know if there is any problem!

**Comment by johnmellor** [comment]
This works really nicely - I can open and save files fine, it works even when the Termux session isn't running, and the files stay open (and saveable) in Turbo Editor even after force stopping both Termux and Turbo Editor!

Just one thing - I noticed that you omitted files where `file.getName().startsWith(".")`). Presumably this is to avoid clutter, but it means you can't edit dotfiles like .bash_profile or .gitconfig, which is a shame. Given that Termux is aimed at relatively technical users, perhaps it would be better to include these?

**Comment by dancinglightning** [comment]
Hi 
Came here  via Google when normal editing didn't work. 
This does work very well, with TurboEdit

I did read the help, but couldn't find anything about how to edit ones files there. And not knowing the first thing about Android and its permissions I was a bit stumped. 
So I just wanted to suggest to put a paragraph into the docs. 

Otherwise I must say, this is amazing work, what with the apt integration. Almost like a normal computer. 

Thanks Torsten

**Comment by milky2028** [comment]
I recently got into the beauty of Termux as well, the only issue being the one first brought up here. I can't access any of Termux's files from outside editors, and I always get a syslink permissions failure when performing CLI commands on files in /sdcard. I'm currently on Android 8.1 Oreo. Also, Termux is now the default option for many for performing programming tasks on Chromebooks, so this might help there as well. Thanks!

**Comment by Quasic** [comment]
The only options available are for viewing, AFAIK: termux-open <file> and on Android 7, I can open some termux files from the Downloads app. No modifications allowed that I have found so far... I tried to use this to keep some files app-private, but found them in Downloads. :P I haven't been able to edit them yet, but haven't tried very powerful apps.

**Comment by mvasi90** [comment]
How can I disable this option?
All private files are shared with all Android Apps.

**Comment by xeffyr** [comment]
> All private files are shared with all Android Apps.

Shared but only at time when you opening it through file chooser.
Application has no automatic access to your Termux files.

**Comment by mvasi90** [comment]
This can be done programmatically without user interaction.
![saf](https://user-images.githubusercontent.com/33942577/71644869-48388880-2cc7-11ea-972f-b73c0180d03d.png)

**Comment by xeffyr** [comment]
> This can be done programmatically without user interaction.

Files can be accessed only through SAF manager. This is OS-level thing and can be manipulated **only** (!) by user.

**Comment by xeffyr** [comment]
Third-party application will not have access to Termux files unless you **select** them.

**Comment by mvasi90** [comment]
Okay, thanks. 
Where is this documentation in the Android Developer docs?
