### ISSUE TITLE
chmod +x <script>.sh problem

### ISSUE THREAD

**Issue by termuxer** [termux/termux-app#791]
everytime i try to run chmod +x command i get operation not permitted
$chmod +x <script>.sh
chmod: <script>.sh: operation not permitted
pls help

**Comment by xeffyr** [comment]
The script is located in /sdcard ?

**Comment by termuxer** [comment]
Yes

**Comment by Grimler91** [comment]
Can't have executable stuff in shared storage, move it to home instead.

**Comment by termuxer** [comment]
ok thanx for the help
