### ISSUE TITLE
Run A script when the app is opened

### ISSUE THREAD

**Issue by misaalanshori** [termux/termux-app#796]
Is it possible automatically run a script when the app is opened? I installed Ubuntu on termux and I want to run the script start-ubuntu.sh Everytime the app opens. 
I usually use gnuroot to run full Linux but it stopped working after update Oreo, so I'm trying to use termux

**Comment by xeffyr** [comment]
Try to add necessary commands into ~/.bashrc

**Comment by misaalanshori** [comment]
Thank you! It worked. That was very fast!
