### ISSUE TITLE
Install python lxml

### ISSUE THREAD

**Issue by nico202** [termux/termux-app#8]
Hi, I'd like to install lxml.
I installed python2, and pip2 works for many packages, but not for lxml (pyconfig.h not found)
Anybody had success installing it?
Thanks :)

**Comment by fornwall** [comment]
Hi, pyconfig.h can be installed from the `python2-dev` package! Does installing lxml work for you after that?

**Comment by nico202** [comment]
installed the package, now fails including libxml/xmlversion.h
thanks

**Comment by fornwall** [comment]
I reproduced the problem:

    In file included from src/lxml/lxml.etree.c:239:0:
    /data/data/com.termux/files/usr/tmp/pip-build-Vw5Hjr/lxml/src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
    #include "libxml/xmlversion.h"

The file `$PREFIX/include/libxml2/libxml/xmlversion.h` exists after installing `libxml2-dev`, but is not found since `-I$PREFIX/include/libxml2` is not used when compiling for some reason...

**Comment by fornwall** [comment]
Hi, the issue was that the `libxml2-dev` package lacked the `xml2-config` utility which lxml needs to build.

This has now been fixed, run `apt update && apt upgrade` and try to install lxml again.

Re-open the issue if it still doesn't work for you!

**Comment by Jim-Zenn** [comment]
The problem seems to be unsolved.

```
/data/data/com.termux/files/usr/tmp/xmlXPathInit0mNYHx.c:1:10: fatal error: 'libxml/xpath.h' file not found       #include "libxml/xpath.h"                                         ^                                               1 error generated.                                       *********************************************************************************                                 Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?                                 *********************************************************************************                                 error: command 'aarch64-linux-android-gcc' failed with exit status 1                                                                                                       ----------------------------------------
```

Here's what I got.

**Comment by fornwall** [comment]
@Jim-Zenn Have you installed libxml2-dev with `apt install libxml2-dev`?

**Comment by Jim-Zenn** [comment]
Yes, I have.

**Comment by Jim-Zenn** [comment]
It seems I succeeded to install after installing libxml2-utils, thanks!

**Comment by rafi16jan** [comment]
hey @fornwall I still got this issue even though I already install libxml2 libxml2-dev and libxml2-utils, how can I found a workaround?

**Comment by Grimler91** [comment]
@rafi16jan What error do you get?

**Comment by rafi16jan** [comment]
@Grimler91 I already got a workaround, I install libxslt1 and it worked

**Comment by Deathlive** [comment]
@Grimler91 How did you install `libxslt1` ?

**Comment by Grimler91** [comment]
@Deathlive `apt search xslt` shows me the packages libxslt and libxslt-dev so those are the ones you're after

**Comment by pigeonflight** [comment]
After install libxml2-dev, libxml2-utils and libxslt
```
pip2 install lxml
```
still fails with the following output:
```
unable to execute 'cc': No such file or directory
....
error: command 'i686-linux-clang' failed with exit status 1
```

**Comment by pigeonflight** [comment]
It seems I was missing 'clang'.
```
pkg install clang
```
did the trick, so I'm back on track. Now to go figure out how to cut and paste from termux.

**Comment by cy3erGh0sT** [comment]
I still have error installing lxml with ('Python.h' file not found).Anybody have any solution?.Thank you.

**Comment by xeffyr** [comment]
@cy3erGh0sT `libcrypt-dev` needed

**Comment by cy3erGh0sT** [comment]
Thank you very much.The problem has been fixed after installing libcrypt-dev.

**Comment by dpshelio** [comment]
This may help:
```shell
pip install --global-option=build_ext --global-option="-I$PREFIX/include/libxml2" lxml
```

**Comment by unsuitable001** [comment]
Hey buddies, looks like there's too much mess (& dependencies) to figure out.
So, I just compiled it & uploaded the wheel file.
Now, you don't have to have the headache. Just install the wheel.
Wheels are in my repository :
https://github.com/unsuitable001/pip-arm-wheel/tree/master/aarch64/lxml

**Comment by medram** [comment]
hey there,
I solved this problem using
`pkg install clang`
`pkg install libxml2 libxslt`
`pip install cython`
`pip install lxml`
have a good day :-)

**Comment by ajitjadhav28** [comment]
> @Grimler91 I already got a workaround, I install libxslt1 and it worked

Working(python3): 
`apt install clang libxml2 libxslt` 
then install lxml by `pip install lxml`

**Comment by dyaus2613** [comment]
it solved my problem
I use these
pip install wheel
pkg install libxml2 libxslt

**Comment by sk8heidong** [comment]
ok 
now ihave lxml 
so exciting ~
