### ISSUE TITLE
Cannot browse the storage subfolders with ssh

### ISSUE THREAD

**Issue by flongo82** [termux/termux-app#80]
I installed Termux on a Samsung Galaxy S II with CyanogenMod 13 nightly. Everything works fine but it seems I cannot browse the filesystem within the storage folder while accessing from ssh. I can browse every folder from within Termux but while accessing from ssh I get: 

`$ cd storage/shared/`
`$ ls`
`ls: cannot open directory '.': Permission denied`

This happens with all the subfolders within /storage/.

What I am doing wrong?

**Comment by fornwall** [comment]
Can you go to

Settings > Apps > Termux > Permissions

and see if the Storage permission is granted to the app?

**Comment by fornwall** [comment]
If it is (which I guess it is since it works from within Termux):

You are running sshd from Termux and not a separate one? Can you check if running `whoami` shows the same user when running from within Termux as it is when running over ssh?

**Comment by flongo82** [comment]
Yes, the storage permission is granted (android asked me to grant it when I launched termux-setup-storage). 

I checked the user and it is the same from within Termux and over ssh: u0_a72.

**Comment by flongo82** [comment]
It seems like I only needed to kill sshd, reboot and start sshd again. Now I can navigate the folders over ssh. 

However, I have another question that seems somehow related. 

I'm downloading a zip archive and then unzipping it in storage/shared/DCIM/myfolder and it gives me the following errors: 

`unzip: can't set permissions of directory 's4t-lightning-rod-master/utils/v1/': Operation not permitted`

So it seems to be again a permission problems. 

Similarly, I'm installing some node packages with npm and it seems to me that I can install only global packages. If I try to install anything in a specific folder I have errors like: 

`EPERM: operation not permitted, chmod '/storage/9107-17E7/DCIM/stack4things/s4t-lightning-rod-master/node_modules/.staging/wrap-ansi-a10b7039/package.json'`

**Comment by fornwall** [comment]
Great that ssh is working now!

About access denied: The shared file system does not allow chmod (or symlink operations), and there is nothing Termux can do about that. You are probably better of using an app-private folder under $HOME/ somewhere!
