### ISSUE TITLE
Cannot reach the settings menu

### ISSUE THREAD

**Issue by notorand-it** [termux/termux-app#800]
ASUS Zenpads don't have an onscreen "menu" key and the application hasn't an alternative way to reach the settings.
I suspect this can affect also other OEM variants of android.
I'd suggest to add the settings menu to the "long press on screen" context menu.

P.S.
I tried to get suggestioons on [Google+](https://plus.google.com/u/0/116177031097991583893/posts/5gd1ncwjs4q) for a workaround. No luck.

**Comment by notorand-it** [comment]
That is the context menu.
There used to be a settings menu as well. Is it gone?

Il giorno mer 22 ago 2018 alle ore 12:19 Leonid Plyushch
<notifications@github.com> ha scritto:
>
> @notorand-it Termux doesn't have settings menu. It use a 'Context Menu' instead.
>
> Even if you tap a such 'menu button', the context menu will be shown anyway because of this (snippet of TermuxActivity.java):
>
>     /** Hook system menu to show context menu instead. */
>     @Override
>     public boolean onCreateOptionsMenu(Menu menu) {
>         mTerminalView.showContextMenu();
>         return false;
> }
>
> To open a context menu, just do a long tap somewhere on screen and you will see something like this:
>
> If you tap button 'more...':
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Vincenzo Romano - NotOrAnd.IT
Information Technologies
--
NON QVIETIS MARIBVS NAVTA PERITVS

**Comment by Neo-Oli** [comment]
Do you mean the left drawer menu? You can open it by swiping from the left side of the screen.

**Comment by notorand-it** [comment]
Il giorno mer 22 ago 2018 alle ore 13:40 Oliver Schmidhauser
<notifications@github.com> ha scritto:
>
> Do you mean the left drawer menu? You can open it by swiping from the left side of the screen.

Yes, that one. Thanks.
I fear the application help is not mentioning this, though.

**Comment by Neo-Oli** [comment]
It's mentioned under user-interface in the help menu. https://wiki.termux.com/wiki/User_Interface
