### ISSUE TITLE
can't install ruby-nokogiri

### ISSUE THREAD

**Issue by myfreess** [termux/termux-app#802]
but clang pkg-config libraries all installed
and I enter gem install nokogiri  -- --use-system-libraries to install it,any thing wrong?

**Comment by myfreess** [comment]
version 1.8.4

**Comment by Grimler91** [comment]
We have no idea what's wrong on your system since you haven't even shared the error message

**Comment by empjustine** [comment]
My educated guess without a error message is that you didn't install libxslt-dev or ruby-dev.

**Comment by Grimler91** [comment]
Closing since we don't have enough information.
