### ISSUE TITLE
su fails on Android 9

### ISSUE THREAD

**Issue by yangzhaofeng** [termux/termux-app#803]
After upgrading to Android 9, su does not work and outputs 
No su program found on this device. Termux
does not supply tools for rooting, see e.g.
http://www.androidcentral.com/root for
information about rooting Android.
and /sbin/su says
bash: /sbin/su: Permission denied

However, in terminal emulator and connectbox(connecting to local), running /sbin/su works well.

**Comment by xeffyr** [comment]
Maybe this is issue of termux-exec. Try to `unset LD_PRELOAD` and check if you can execute /sbin/su.

**Comment by yangzhaofeng** [comment]
No.
still Permission denied

**Comment by Grimler91** [comment]
See if `tsu` works, just `tsu` or `tsu -a`.

**Comment by yangzhaofeng** [comment]
tsu -a says
/data/data/com.termux/files/usr/bin/tsu: 139: exec: : Permission denied

**Comment by yangzhaofeng** [comment]
and same output after unset LD_PRELOAD

**Comment by yangzhaofeng** [comment]
The problem is solved after I updated my Magisk to 16.7
