### ISSUE TITLE
can't build a c++ app statically with clang++ 

### ISSUE THREAD

**Issue by adevelopcr** [termux/termux-app#805]
I wrote a simple app in c++ on an android phone and now went to compile it with clang++ on termux
I could compile it dinamically successfully
But I want to compile it statically so I added -static to the compiler command line but I got these errors

bash-4.4$ clang++ -static -s -o ptst /sdcard/CppDroid/projects/ptest/ptest.cpp
/data/data/com.termux/files/usr/bin/ld: cannot find -lc++_shared /data/data/com.termux/files/usr/bin/ld: cannot find -lm /data/data/com.termux/files/usr/bin/ld: cannot find -lc
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xeffyr** [comment]
Static libraries are not provided. Even if they will be available, the `-static` option won't work (at least in your case) since we are relying on C library provided by Android (/system/lib*/libc.so).

**Comment by adevelopcr** [comment]
but will the app built with clang++ work with another versions of libc on different android mobiles ? On windows msvcrt is available with every windows installation .

And how can I chip the c++ library for earlier android versions when I use c++11 features and later c++ features ?

**Comment by fornwall** [comment]
Closing as supporting static linking inside Termux is currently out of scope.

> but will the app built with clang++ work with another versions of libc on different android mobiles ? On windows msvcrt is available with every windows installation .

libc provides a stable API. By default the compiler in Termux currently targets API level 21 (Android 5.0), so you may use symbols not available on earlier versions. Compile with e.g. `-D__ANDROID_API__=16` to target an earlier API version.

> And how can I chip the c++ library for earlier android versions when I use c++11 features and later c++ features ?

See https://developer.android.com/ndk/guides/cpp-support to read up on the C++ situation on Android!
