### ISSUE TITLE
beef-xss

### ISSUE THREAD

**Issue by mansurabbas** [termux/termux-app#808]
pls i install beef-xss normal procedure and it installed.But when i try to run it by "beef" it shows the following error :

 Could not find nokogiri-1.8.1 in any of the sources
Run `bundle install` to install missing gems.

I saw answer to the solution in this wonderful and helping forum ( gem install nokogiri-1.8.1 and bundler -v and bundle install). It install nokogiri-1.8.1 and clone Gemfile in my /$HOME but still when i try to run by "beef" it still shows :

Could not find nokogiri-1.8.1 in any of the sources
Run `bundle install` to install missing gems.

                                             pls help me, Thanks in advance.

**Comment by Grimler91** [comment]
Closing since the issue doesn't seem to be termux-specific. 
Looks like you need(ed) to install nokogiri through gem.
