### ISSUE TITLE
Lost write access on sdcard after Android 7->8 upgrade

### ISSUE THREAD

**Issue by brumwald** [termux/termux-app#812]
When I updated my phone (Moto Z) from Android 7 to Android 8 termux lost write-access to the sdcard. I do still have read+write access to the internal storage at /storage/emulated/0 and I still have read access on the sdcard. But writing/deleting files is met with a permission-denied error. 

I don't have root (and never has had on this phone). 

Snippets of ls reveals that _everybody_ lacks the write permission for the sdcard.
```
$ ls -l /storage/emulated/0
drwxrwx---    6 root     everybod      4096 Sep  2  2017 DCIM
[...]

$ ls -l /storage/30303030-2d30-3030-3000-020000000000/
drwxr-x---    5 root     everybod    131072 Jan  5  2017 Android
drwxr-xr-x    3 root     everybod    131072 Dec 28  2016 DCIM
[...]
```

I do have write access to the termux-directory on the sdcard (/storage/30303030-2d30-3030-3000-020000000000/Android/data/com.termux/files), where the user-owner is set to u0_a94.

Not sure if it matters but I the sdcard was previously (in android 7) mounted at
/storage/00000000-0000-0000-0000-000000000000 (which I thought was weird)
whereas in Android 8 it is
/storage/30303030-2d30-3030-3000-020000000000

All other applications that I use can still access and create files on the sdcard as ususal (and not just their own _Android/data_ directory). I've ran termux-setup-storage again and although it fixed the symlinks to the new sdcard mount it didn't do anything for the permissions. Also tried to reinstall termux but the behavior is the same. 

```
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.71-perf-g259b8d6 #1 SMP PREEMPT Fri Jun 29 08:01:20 CDT 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
motorola
Device model:
XT1650
```

**Comment by brumwald** [comment]
Why would only termux be subject to such an limitation?

**Comment by xeffyr** [comment]
> When I updated my phone (Moto Z) from Android 7 to Android 8 termux lost write-access to the sdcard.

> Why would only termux be subject to such an limitation?

1. The good question is why you had write access to external sdcard on Android 7. Google introduced restriction for sdcard write access from Android 4.4 (kitkat).

2. Other applications may use [Storage access framework](https://developer.android.com/guide/topics/providers/document-provider?hl=en) for accessing external sdcards but it is not possible tell Termux's binaries to use this framework.

3. As workarond, Termux provides tool `termux-setup-storage` which will setup all necessary symlinks in dir `~/storage`.

Some links about sdcard issue:
* https://www.xda-developers.com/android-l-may-change-sd-card-access-rules/
* https://www.androidpit.com/how-to-fix-sd-card-problem-on-kitkat

**Comment by xeffyr** [comment]
> Snippets of ls reveals that everybody lacks the write permission for the sdcard.

On my device too (Samsung Galaxy S7):
![screenshot_20180817-200519_termux](https://user-images.githubusercontent.com/25881154/44279154-08e7d400-a259-11e8-8ea3-b438207cb18a.jpg)

**Comment by brumwald** [comment]
Thanks! Starting to understand why it has been so difficult to find others in the same situation as me. I probably just don't know enough to know this is futile, but some desperate thoughts:

It would be neat if one could ask for the permission to use the sdcard, via ACTION_OPEN_DOCUMENT_TREE or something, on behalf of another application. If I could manually grant, say, rsync the ability to write+delete on the sdcard I'd be quite happy! 

Another (ugly!) workaround would be to manually open up the permissions on the termux directory on the sdcard (_/storage/30303030-2d30-3030-3000-020000000000/Android/data/com.termux/files_). That way I could redirect other applications to dump their data in a directory that termux binaries can work with.

Even more crazy would be some termux FUSE-ish filesystem that redirects the writes to the termux directory on the sdcard (or even the root if termux would make use of the required APIs). Hmm, since it wouldn't be readable for any other applications outside termux the usefulness would perhaps be limited...

I realize that it is quite likely none of the above can work, maybe a 7.0 downgrade and some luck could work.

**Comment by matcool** [comment]
I now have the same issue from upgrading to android 7 to android 8.1
The sdcard directory stayed the same (`storage/6637-3733` for me).
One thing i also noticed is that the `/sdcard` directory is the internal storage, instead of the sdcard

**Comment by xeffyr** [comment]
> I now have the same issue from upgrading to android 7 to android 8.1

This is Android's issue, not Termux's. We can't do anything here: permission for accessing external sdcard is provided via Storage Access Framework which can't be used by command line applications for obvious reason.

> One thing i also noticed is that the /sdcard directory is the internal storage, instead of the sdcard

On typical Android devices /sdcard is internal (shared) storage regardless of which Android version is used, exception is here only when device is either old or vendor use a custom design of Android OS instead of suggested by Google.
