### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by myfreess** [termux/termux-app#816]
debootstrap --arch=armv7l stable debian http://ftp2.cn.debian.org/debian
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg
I: Retrieving InRelease
I: Retrieving Release
E: Invalid Release file, no entry for main/binary-armv7l/Packages

**Comment by xeffyr** [comment]
>  --arch=armv7l stable debian

@myfreess Use **armhf** or **armel** instead. Check this: https://www.debian.org/releases/jessie/mips/ch02s01.html.en
