### ISSUE TITLE
Permission denied when trying to add entry to routing table with $ ip route add

### ISSUE THREAD

**Issue by maxogden** [termux/termux-app#817]
I am trying to add a default gateway route for a VPN app I'm testing but get this error:

```
$ ip route add default via 192.168.1.76 dev tun0
Cannot talk to rtnetlink: Permission denied
```

I noticed Termux doesn't request the `CHANGE_NETWORK_STATE` android permission, but I'm not sure if that's even the correct permission. Maybe there's another way to get past this error?

**Comment by Grimler91** [comment]
You can do it if you are rooted. Doing it without root would require going through androids API, by extending termux-api. It isn't as simple as just adding a line to the manifest unfortunately
