### ISSUE TITLE
uptime/htop don't actually work

### ISSUE THREAD

**Issue by ttrash** [termux/termux-app#819]
`uptime
 09:31:48 up 0 min,  0 users,  load average: 0.00, 0.00, 0.00`

hour is right, uptime is not, load is not, this one was in termux

in terminal emulator, same command (which is executed from /system/bin/uptime) I get all the relevant information (how much uptime, and the 3 numbers of system load)

also, this is a library problem, not this command explicitly problem be cause, htop behave the same, I have 0.00 all 3 load numbers and no processor load to show in left top corner (graphic show)

my phone is S8+ ... NOT ROOTED WHATSOEVER ...

and again, just to be sure
**in terminal emulator this is working, with no problems, in the very same time with termux, therefore is not my system/phone to blame**

please fix, thank you !

**Comment by ttrash** [comment]
nice, I don't want to ask you about busybox, both apps from store require root, or do absolutely nothing
I would like to have this feature anyway, therefore:

help me with this workaround:
`/system/bin/uptime
CANNOT LINK EXECUTABLE "/system/bin/uptime": cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib64/libselinux.so"...
Aborted
`

**Comment by Grimler91** [comment]
@ttrash termux provides busybox, you don't need to get another app from play store.

```bash
$ which busybox
/data/data/com.termux/files/usr/bin/busybox
```

**Comment by xeffyr** [comment]
@ttrash This linking error is Samsung-specific (same on my Samsung Galaxy S7, but not on other devices), so you have to do this:
```
LIBRARY_PATH= /system/bin/uptime
 12:44:16 up 10 days, 21:31,  0 users,  load average: 5.66, 5.70, 5.92
```

For me, just `uptime` works as well:
```
$ uptime
 12:45:43 up 10 days, 21:32,  load average: 5.72, 5.69, 5.89
```

**Comment by ttrash** [comment]
LIBRARY_PATH= /system/bin/uptime
CANNOT LINK EXECUTABLE "/system/bin/uptime": cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib64/libselinux.so"...

**Comment by xeffyr** [comment]
@ttrash Sorry, my mistake =). Just copied/pasted only part of text.

It should be `LD_LIBRARY_PATH= /system/bin/uptime`.

**Comment by fornwall** [comment]
@ttrash Thanks for reporting!

`uptime` has now been removed from the latest `3.3.15-1`version of the procps package, so Termux users should always get the working `uptime` from busybox in the PATH.

**Comment by ttrash** [comment]
thank you, now both are working:
busybox uptime
and
LD_LIBRARY_PATH= /system/bin/uptime

I don't really like workarounds, but is better than nothing, again

Thank You ! :)
