### ISSUE TITLE
Keyboard textarea for using swipe, predictions and corrections

### ISSUE THREAD

**Issue by ailin-nemui** [termux/termux-app#82]
A textarea input mode which can be toggled with a key would be awesome, especially for typing longer texts with a soft keyboard.  Something like https://github.com/connectbot/connectbot/pull/289

Thanks

**Comment by hifi** [comment]
Unlike in ConnectBot, the input field should take space above the keyboard and below the terminal while also looking as much like the terminal font and color scheme if possible.

At best, the input field could be overlayed on the terminal at the current cursor position making it seem like native input with prediction if colors and font can be adjusted for that.

Alternatively opening the input field could push the terminal up (hiding some top rows) to get the space but not actually resize. This allows you to input text with correction and keeping your context which is usually at the bottom of a terminal window.

**Comment by Neo-Oli** [comment]
This was added in version 0.35 recently. It can be enabled by long pressing on the keyboard button in the left drawer and swiping the extra keys row that appeared.

**Comment by hifi** [comment]
Better late than never to give feedback. It works well and doesn't make terminal resize all the time, many thanks!
