### ISSUE TITLE
gpg-agent via OpenKeychain

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [termux/termux-app#823]
It will be cool to have gnupg agent that will use OpenKeychain.
(or ssh agent, but gnupg agent can emulate ssh agent so gnupg agent is better)

Like termbot does.

**Comment by Grimler91** [comment]
Such a feature would probably go into termux-api, might be more appropriate to open the feature request there. Looking at the [termbot](https://github.com/open-keychain/termbot) sources seems like a good start for an implementation
