### ISSUE TITLE
library "libnghttp2.so" not found

### ISSUE THREAD

**Issue by huitc** [termux/termux-app#824]
$ pkg update
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libnghttp2.so" not found
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/apt/methods/https": library "libnghttp2.so" not found
0% [Working]
And then I got stuck in there

Before that, I updated a few things
$ pkg update
and
$ pkg upgrade

I've forgotten where I got stuck.........

Anyway, after that, I can't do anything

**Comment by xeffyr** [comment]
@huitc What you did to make libnghttp2.so missing ?

It can't be removed since it is a dependency of libcurl:
```
TERMUX_PKG_DESCRIPTION="Easy-to-use client-side URL transfer library"
TERMUX_PKG_DEPENDS="openssl, libnghttp2"
TERMUX_PKG_VERSION=7.61.0
```

and libcurl is dependency of apt:
```
TERMUX_PKG_DESCRIPTION="Front-end for the dpkg package manager"
TERMUX_PKG_DEPENDS="libcurl, liblzma, dpkg, gpgv, libc++, termux-exec"
TERMUX_PKG_VERSION=1.4.8
```

**Comment by huitc** [comment]
Still can't

**Comment by xeffyr** [comment]
If you messed up Termux environment, then just reinstall it: go to android settings and clear app data for Termux.

**Comment by huitc** [comment]
But I don't want to delete it
Is there any other way

**Comment by huitc** [comment]
close it, I reinstalled.... 😅😭😭
