### ISSUE TITLE
termux.properties key mapping

### ISSUE THREAD

**Issue by jpclouduk** [termux/termux-app#825]
If this isn't possible right now, please can I make it a suggestion ?
Using a bluetooth keyboard but the biggest issue is it's missing the "|" key.
Strangely it has the "¦" key. I've already mapped my "back" key to escape in termux.props but is there a way to map the "¦" to "|".

**Comment by haarp** [comment]
Mappable keys would be wonderful.

**Comment by pulketo** [comment]
What ??? 
Are n't "¦" to "|" the same key ?
i've been using them for years  as the same key...

**Comment by jpclouduk** [comment]
So in certain environments such as busybox which I think Termux uses, the broken bar is interpreted as the standard pipe. For example, grep in busybox can accept the broken bar and pipe as the same function. However, if you try the same character in a standard unix/linux env, the shell will tell you the command is garbled.
Right now i'm trying to figure out how to map the broken bar to the pipe via android but most of those apps look dodgy to me and capture everything you type and really don't want to root my device. I checked a load of keyboards built in to cases recently and noticed most of them don't have the pipe key.

**Comment by jpclouduk** [comment]
ooooo.... a long time since  I commented on here but is it possible to provide an option in termux.properties to map  the "broken pipe" key to the "pipe" key? Something like;
pipe-key=['¦']
No idea why all the bluetooth keyboards don't have a pipe key !!!!

**Comment by jpclouduk** [comment]
closing to open an enhancement for mappable keys
