### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Egrak** [termux/termux-app#828]
su executable not found
sudo requires su

**Comment by Grimler91** [comment]
You ned to root your phone.
Check for a guide on xda

**Comment by sdrausty** [comment]
@Egrak, with your batting record, you will probably break it as soon as it is rooted.  Learn Linux well first @Egrak.  Then concider alternatives to cracking an Android.  Termux chroot and proot **are** alternatives to rooting in many cases.  Building apps with escalated permissions is a choice to concider too.   A great alternative to rooting is building a custom ROM for the device.  Is your Android 8 rooted @Grimler91?
