### ISSUE TITLE
Adaptive icon don't work on devices with circle/round as default icon shape

### ISSUE THREAD

**Issue by rodrigoswz** [termux/termux-app#830]
I noted that the on Android 8+ devices with round as default shape, Termux uses the non-adaptive round icon which is intended for devices running Android 7.1.

So if I try to change the shape with launcher that allows this (Launcher3, Nova, Pixel etc...), Termux icon will always be round.

But if the default shape of the icons is square for example, the Termux adaptive icon works perfectly.

**Comment by fornwall** [comment]
Perhaps we should just remove the round non-adaptive icons?

**Comment by nakedpwr** [comment]
I have a question for Rodrigo... I'm new to this and desperately wishing to learn. I've seen other posts by you and examples you leave for the ability for changes to be made and can see where your line of reasoning comes from and goes. I have several questions I would like to ask with more simplistic arenas such as and and wireless things as well as theming. How do I send messages directly here? My email is nakedpwr@gmail.com and I use that for work.

**Comment by nakedpwr** [comment]
Actually anyone wishing to become a mentor I would love to hear from. I work very long hours in surgery but I'm dedicated. :)

**Comment by trygveaa** [comment]
This works fine now (at least for me on Pixel 3), so this can probably be closed.

**Comment by rodrigoswz** [comment]
Yes, I can confirm that this works fine now
