### ISSUE TITLE
sudo executing commands not working on termux .help me

### ISSUE THREAD

**Issue by siduck0007** [termux/termux-app#831]
when i execute the command of cat sudo > /data/data/com.termux/files/usr/bin/sudo then it shows cat : sudo no such file or directory ......i have rooted phone with magisk lastest version.

**Comment by Neo-Oli** [comment]
> `cat sudo > /data/data/com.termux/files/usr/bin/sudo`

What? What are you expecting this command to do? It doesn't make sense at all.

Also there is no `sudo`, only `su`.

**Comment by xeffyr** [comment]
> Also there is no sudo, only su.

@Neo-Oli There is command **tsudo** from package **tsu**.
