### ISSUE TITLE
VOL UP & Q - Cmds Popup - HOME Does Nothing?

### ISSUE THREAD

**Issue by 0pLuS0** [termux/termux-app#832]
Hello,

First let me say thanks for Termux, great app!

Specs
---------
Essential PH-1
Stock - Oreo 8.1.0
Termux - 0.65 - Installed from F-Droid
---------

Sorry if I'm ignorant here, but I thought/assumed, that no matter what /path I was in, and I wanted to get back to my $HOME, that is what this was for?

```ESC / - HOME```

Am I missing the point here of this HOME?

I press it, it does nothing... :(

Hmm

Thanks

**Comment by Grimler91** [comment]
To get back to home just write "cd" in your terminal. We don't have a short key for it.

**Comment by xeffyr** [comment]
> Am I missing the point here of this HOME?

Yes, you are missing the point of HOME button:

> In Linux, the Home key has basically the same functionality as it does on Windows. It returns the cursor to the beginning of the line in editable text, and otherwise scrolls a scrollable document to the beginning. -Wikipedia

**Comment by 0pLuS0** [comment]
@Grimler91 & @xeffyr ok thank you both...
