### ISSUE TITLE
w command not working just be cuz

### ISSUE THREAD

**Issue by ttrash** [termux/termux-app#833]
until yesterday (I think) this was working, I didn't updated/upgraded anything but:

> w
> The program 'w' is not installed. Install it by executing:
>  pkg install procps
> u0_a395@localhost:$ pkg install procps
> Hit:1 https://termux.net stable InRelease
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> procps is already the newest version (3.3.15-1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> u0_a395@localhost:$ pkg install --reinstall procps
> Hit:1 https://termux.net stable InRelease
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> 0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
> Need to get 166 kB of archives.
> After this operation, 0 B of additional disk space will be used.
> Get:1 https://termux.net stable/main aarch64 procps aarch64 3.3.15-1 [166 kB]
> Fetched 166 kB in 0s (643 kB/s)
> (Reading database ... 6990 files and directories currently installed.)
> Preparing to unpack .../procps_3.3.15-1_aarch64.deb ...
> Unpacking procps (3.3.15-1) over (3.3.15-1) ...
> Setting up procps (3.3.15-1) ...
> u0_a395@localhost:$ w
> The program 'w' is not installed. Install it by executing:
>  pkg install procps
> 

please fix ! ... thank you !

**Comment by xeffyr** [comment]
@ttrash Command **w** is disabled since it is not working properly:

![screenshot_20180911-112817_termux](https://user-images.githubusercontent.com/25881154/45347960-048fac00-b5b6-11e8-89cb-bef0a4fef0a0.jpg)

It also useless in single-user environments.

**Comment by ttrash** [comment]
thank you for your answer, now, I do NOT want to swear, but this is kinda BULLPOOP
try to be a human being and NOT MIRCOSOFT !!!! PLEASE !!!!!

what is the difference, the difference is simple: I come all over here, open a topic, point at a bug be cause:
YOU DID **NOT** HAD THE **MINIMUM DECENCY** to put an explanation instead a ... BULLPOOP ERROR: "use that command to install procps" which has ABSOLUTELY AND TOTALLY **NOTHING** TO DO WITH THE REAL PROBLEM

that IS MIRCOSOFT STYLE

all caps are intended as, I lose time for nothing be cause ppl think that if something is free then BULLPOOP is in order, who cares about any decency ! and this is the usual ... "smell" every time, EVERY TIME when I hear about open source !

**WHATEVER**

**Comment by ttrash** [comment]
thank you for your answer, now, I do NOT want to swear, but this is kinda BULLPOOP
try to be a human being and NOT MIRCOSOFT !!!! PLEASE !!!!!

what is the difference, the difference is simple: I come all over here, open a topic, point at a bug be cause:
YOU DID **NOT** HAD THE **MINIMUM DECENCY** to put an explanation instead a ... BULLPOOP ERROR: "use that command to install procps" which has ABSOLUTELY AND TOTALLY **NOTHING** TO DO WITH THE REAL PROBLEM

that IS MIRCOSOFT STYLE

all caps are intended as, I lose time for nothing be cause ppl think that if something is free then BULLPOOP is in order, who cares about any decency ! and this is the usual ... "smell" every time, EVERY TIME when I hear about open source !

**WHATEVER**

**Comment by Grimler91** [comment]
@ttrash `w` was removed two weeks ago, see https://github.com/termux/termux-packages/commit/d3b91dd27feacce39fb594286be054952dc019fe 

The command-not-found isn't updated very regularly though so the program is still listed there. After your issue here @xeffyr opened https://github.com/termux/termux-packages/pull/2824 to remove it from the list.

So thanks for pointing out that it is erroneously listed in command-not-found.

**Comment by ttrash** [comment]
every SINGLE EXCUSE is smaller than the one before
replacing a very used UNIX command (not just Linux) with a brief explanation like "command removed be cuz ... QUOTE: "@ttrash w was removed two weeks ago, see termux/termux-packages@d3b91dd" or "@ttrash Command w is disabled since it is not working properly" would make you HUMAN ... NOT BULLPOOP MIRCOSOFT (please, PLEASE, FEEL THE "MIRCOSOFT" WORD, I REALLY FIGHT AGAINST BAD WORDS THAT DON'T BELONG HERE ... but ... YOU CAN IMAGINE !!!! )

all this instead a REALLY RETARDED MESSAGE: "install procps and then that command will work" ... 

therefore 

QED

thans A LOT for proving my point ! 


**TURN THE POWER ON OPEN SOURCE, REALLY, TURN THE POWER ON**
