### ISSUE TITLE
Disable zoom on android application

### ISSUE THREAD

**Issue by Arthur38000** [termux/termux-app#834]
Hi,
I would like to disable zoom on the mobile android application.
Is it possible?
Thank you in advance.
Regards.

**Comment by pulketo** [comment]
please don't, if it's necessary, put a checkbox somewhere to disable it, it's a nice feature !

**Comment by xeffyr** [comment]
> I would like to disable zoom on the mobile android application.
Is it possible?

Not possible as this is core functionality.

**Comment by Quasic** [comment]
Zoom has been restricted to pinch-zoom to avoid problems with double-tap zooming accidentally. There is currently no way to turn it off completely.
