### ISSUE TITLE
Feature Request : Ability to change default app path

### ISSUE THREAD

**Issue by CaiMiao** [termux/termux-app#836]

**Comment by CaiMiao** [comment]
Sorry that I was using mobile device to open this.

I tried to use Termux inside VirtualApp environment, and the inital login was failed.
`exec("/data/data/com.termux/files/usr/bin/login"): No such file or directory`
No doubt that problem occurs due to the hardcoded path of app data.
In my case, actuall app data path is located at `/data/data/io.va.exposed/virtual/data/user/0/com.termux/files`... .
I'll be appreciate if anyone can solve this. You can do more bizzare things since you have full rwx access inside VA environment, which is precious for a non-root system.

**Comment by tomty89** [comment]
Just build your own Termux app with a different `FILES_PATH`?

https://github.com/termux/termux-app/blob/beb8a004e6ea64e2b3795fc9320da8c8b2e0a871/app/src/main/java/com/termux/app/TermuxService.java#L49

Not sure how this can be dynamic...

**Comment by xeffyr** [comment]
PREFIX can be obtained in this way:
``` .java
public static String getEnvironmentPrefix(final Activity activity) {
    return activity.getApplicationContext().getFilesDir().getAbsolutePath() + "/usr";
}
```

To make packages use dynamic prefix, you will have to patch them all. Example for ncurses (other patches are not shown):
``` .diff
diff -uNr ncurses-6.1-20180707/ncurses/tinfo/db_iterator.c ncurses-6.1-20180707.mod/ncurses/tinfo/db_iterator.c
--- ncurses-6.1-20180707/ncurses/tinfo/db_iterator.c	2017-07-02 01:54:42.000000000 +0300
+++ ncurses-6.1-20180707.mod/ncurses/tinfo/db_iterator.c	2018-08-14 15:06:21.592743385 +0300
@@ -302,6 +302,28 @@
 
 #if NCURSES_USE_DATABASE
 #ifdef TERMINFO_DIRS
+#undef TERMINFO_DIRS
+
+#ifndef ANDROID_PREPEND_PREFIX
+#define ANDROID_PREPEND_PREFIX 1
+int  asprintf(char** __s_ptr, const char* __fmt, ...);
+char* getenv(const char* __name);
+static __inline__ char *__prepend_prefix(char *path) {
+        char *_new_path;
+        char *_env_prefix = getenv("PREFIX");
+
+        if (_env_prefix) {
+                asprintf(&_new_path, "%s%s", _env_prefix, path);
+                return _new_path;
+        } else {
+                asprintf(&_new_path, "%s%s", "@TERMUX_PREFIX@", path);
+                return _new_path;
+        }
+}
+#endif
+
+#define TERMINFO_DIRS __prepend_prefix("/share/terminfo")
+
 	values[dbdCfgList] = TERMINFO_DIRS;
 #endif
 #ifdef TERMINFO
```

I used these tricks for my application ([Alpine Term](https://github.com/xeffyr/Alpine-Term), based on Termux). However, I found some issues that those modifications may cause:

1. Memory leaks. Not critical as it is less than 1 KB (usually less than 200 bytes).

2. Some programs may not work with long prefixes (like `/data/data/io.va.exposed/virtual/data/user/0/com.termux/files`). Program will just print error or crash.

In other cases, like using application as secondary users no major issues found.

**Comment by tomty89** [comment]
> you will have to patch them all

Why not just rebuild all packages with the needed PREFIX then? *shrug*

**Comment by xeffyr** [comment]
@tomty89 Yes, rebuilding with needed PREFIX is optimal solution for this issue, but maybe it is not flexible as @CaiMiao want.

**Comment by CaiMiao** [comment]
It'd be more flexible if it can configured as dynamic one. Not only VA's sandboxies.

**Comment by xeffyr** [comment]
@CaiMiao The only solution is do to something as shown here: https://github.com/termux/termux-app/issues/836#issuecomment-420634954, but this won't be used in Termux so probably you have to do this on your own. **There are no usable solutions other than patching to get dynamic prefix.**
