### ISSUE TITLE
 Segmentation fault after Executing $ gem -h

### ISSUE THREAD

**Issue by pubsubhubbusb** [termux/termux-app#839]
Please Help 
getting a Segmentation fault after Executing $ gem -h

**Comment by Grimler91** [comment]
Closing in favour of https://github.com/termux/termux-packages/issues/2845

**Comment by RyanGarccia** [comment]
Please give this error while typing gem -h, you are not installing the gems

**Comment by RyanGarccia** [comment]
Still giving the wrong time to use the
