### ISSUE TITLE
Ctrl+Space with external hardware keyboard does not give any input

### ISSUE THREAD

**Issue by fornwall** [termux/termux-app#84]
Ctrl+Space seems to be used at least in emacs, but is not possible to enter.

This may be an issue with the android system so impossible to work around, but worth investigating.

**Comment by kaushalmodi** [comment]
Ctrl+Space works using [Hacker's Keyboard][1] but not through [Logitech K380][2].

Do you work with bluetooth keyboards? .. and have had to customize the mappings?

[1]: https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en
[2]: http://www.logitech.com/en-us/product/multi-device-keyboard-k380

**Comment by kaushalmodi** [comment]
Probably unrelated, but even using Hacker's Keyboard, Ctrl+6, Ctrl+` and few more Ctrl+symbol/number bindings either don't work or are mis-mapped. For example, Ctrl+6 is seen as Ctrl+_ by emacs.

Is there some Locale setting that needs to be done on my end? I am using the English-US keyboard.

**Comment by kaushalmodi** [comment]
Here are few of the bindings compared between what I hit on the bluetooth keyboard and what they are detected as in emacs:

- <kbd>C-SPC</kbd> -- not detected
- <kbd>C-\`</kbd> -- <kbd>\`</kbd>
- <kbd>C-1</kbd> -- <kbd>1</kbd>
- <kbd>C-2</kbd> -- <kbd>C-@</kbd>
- <kbd>C-3</kbd> -- <kbd>Esc</kbd>
- <kbd>C-4</kbd> -- <kbd>C-\</kbd>
- <kbd>C-5</kbd> -- <kbd>C-]</kbd>
- <kbd>C-6</kbd> -- <kbd>C-^</kbd>
- <kbd>C-7</kbd> -- <kbd>C-_</kbd>
- <kbd>C-8</kbd> -- <kbd>DEL/BKSPC</kbd>
- <kbd>C-9</kbd> -- <kbd>F11</kbd>
- <kbd>C-0</kbd> -- <kbd>F12</kbd>
- <kbd>C--</kbd> -- <kbd>-</kbd>
- <kbd>C-=</kbd> -- <kbd>=</kbd>
- <kbd>C-]</kbd> -- <kbd>C-]</kbd> **works! :)**
- <kbd>C-\\</kbd> -- <kbd>C-\\</kbd> **works! :)**
- <kbd>C-;</kbd> -- <kbd>;</kbd>
- <kbd>C-'</kbd> -- <kbd>'</kbd>
- <kbd>C-.</kbd> -- <kbd>.</kbd>
- <kbd>C-,</kbd> -- <kbd>,</kbd>
- <kbd>C-/</kbd> -- <kbd>/</kbd>

**Comment by ginabythebay** [comment]
fwiw I  am running into this (control space  not being seen  by emacs) using the pixel c hardware keyboard

**Comment by fornwall** [comment]
I tested on Android 7 and the issue seems to be solved there - Ctrl+Space works when using external keyboards, so I'm closing this issue.

For previous Android versions there is unfortunately nothing to do about it, as the key event is not sent to apps.

**Comment by cdfa** [comment]
I ran into this key mismatch on my Oneplus 5 running Oxygen Os 5.1.3 (Android 8.1.0). First thing I noticed was modifier keys not being send on DEL, but trying out a few of the above (C-1, C-2, C-3) don't send the correct keys either. C-SPACE send sends C-@ for me for some weird reason.

I tried with both the extra keys overlay and Hacker's keyboard.

**Comment by tulth** [comment]
I have this problem on android pie, s10+ and logitech k380.
I even edited the kcm file to not fallback to language with no luck. 
i see the same problem in bvnc and linux on dex.  
Any ideas appreciated

**Comment by johanvts** [comment]
I'm on Android 9 and c-<space> in Termux emacs does not register.

**Comment by mhofert** [comment]
Same problem here with Logitech Keys-to-Go and Apple's wireless keyboard on a Samsung Note 9.

**Comment by Trisk3lion** [comment]
I have the same problem with Keychron K2 bluetooth keyboard and Samsung Note 8.

**Comment by aadcg** [comment]
This issue should be re-opened. #1333 is also related.

I have no idea how to solve this but I found the following information [here](https://en.wikipedia.org/wiki/Control_character#How_control_characters_map_to_keyboards).

> The NULL character (code 0) is represented by Ctrl-@, "@" being the code immediately before "A" in the ASCII character set. For convenience, a lot of terminals accept Ctrl-Space as an alias for Ctrl-@.
