### ISSUE TITLE
Unsupported flags & ruby segmentation fault

### ISSUE THREAD

**Issue by Shubhamvis98** [termux/termux-app#840]
After an "**apt update and upgrade**"  when I use apt or pkg this error showing "**WARNING: linker: Unsupported flags DT_FLAGS_1=0x8**" and when I use ruby or gem then only showing "**segmentation fault**"
I'm using Samsung j2 version 5.1.1 stock rom
Please solve the problem
I tried to reinstall termux but this problem is still same

**IMAGE 1: UNSUPPORTED FLAGS**
![screenshot_2018-09-17-14-29-27](https://user-images.githubusercontent.com/43336210/45614610-b718b080-ba87-11e8-83f4-44e9a0075e6c.png)

**IMAGE 2: SEGMENTATION FAULT**
![screenshot_2018-09-17-14-45-08](https://user-images.githubusercontent.com/43336210/45614812-52aa2100-ba88-11e8-81c2-1536a5220903.png)

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/2846 and https://github.com/termux/termux-packages/issues/2845

**Comment by profionaldhim** [comment]
Please help I have this error my device Android 5.1 
But I have got Android 6 the update and upgrade it work on it

**Comment by Shubhamvis98** [comment]
I think termux doesn't support android 5.1
I hope it will fix in next update

**Comment by Shubhamvis98** [comment]
Thanks Sir

**Comment by Shubhamvis98** [comment]
And what for this error - WARNING: linker: Unsupported flags DT_FLAGS_1=0x8

**Comment by profionaldhim** [comment]
OK thanx Termux but quickly please
😍😍😍😘😘😘
بتاريخ ١٧‏/٠٩‏/٢٠١٨ ٥:٥٦ م، كتب "Shubham Vishwakarma" <
notifications@github.com>:

**Comment by Shubhamvis98** [comment]
Problem is still same after updating ruby
![screenshot_2018-09-17-21-23-15](https://user-images.githubusercontent.com/43336210/45634563-4fcb2280-bac0-11e8-8977-41226f2ad210.png)

**Comment by Quasic** [comment]
I think it was fixed in 2.5.1-4, right?
