### ISSUE TITLE
No completion or cursor movement when in `su`

### ISSUE THREAD

**Issue by monnier** [termux/termux-app#843]
For some reason, when I'm root (i.e. after running `su`), all the control chars are taken literally (as if the shell was not interactive) rather than as commands to manipulate the input.
More specifically, TAB just inserts a TAB character rather than displaying completions, `C-a` inserts a character of ASCII code 1 (displayed as `^A`), ...

Along the same lines, after hitting RET to send the command, the command is echoed back before the actual command's output.  I tried `tsu`, but it suffers from the same problem.

One odd detail I noticed along the way is that while `tty` responds `/dev/pts/0` when I'm not within `su`, it switches to `/dev/pts/1` when I'm in `su`.

These problems do not affect `su` in `adb shell`, so apparently there's some way to "make it work right".

This is under LineageOS-15.1, using LineageOS's standard "su addon" and running the latest Termux package from F-Droid.

**Comment by Grimler91** [comment]
I think we've seen this problem before, and that the reporter solved it by re-rooting/rooting with another su variant. 

That doesn't explain why it happens though

**Comment by monnier** [comment]
Oh, that made me look for issues in the bug tracker of LineageOS's `su` and I see they have a bug opened for this issue ([BUGBASH-1825](https://jira.lineageos.org/browse/BUGBASH-1825)), which seems to be a problem on their side.

Apparently, this can be circumvented temporarily by executing `setenforce 0` (under `su`) before running `su`.  Thanks.
