### ISSUE TITLE
WARNING: Linker......unused DT entry: type 0x1d arg 0x1694

### ISSUE THREAD

**Issue by Shubhamvis98** [termux/termux-app#844]
I upgraded my phone unofficially to 6.0 and the last issue gone but here I got net problem of linker.
Can anyone please help me...
![screenshot_20180919-224702](https://user-images.githubusercontent.com/43336210/45769688-fa2c7c80-bc5d-11e8-8db8-22d5b22743a1.png)

**Comment by Grimler91** [comment]
Run ˋtermux-elf-cleanerˋ on the library that gives the warning, i.e. in your case ˋtermux-elf-cleaner $PREFIX/lib/ruby/gems/2.5.0/gems/pg-0.20.0/lib/pg_ext.soˋ.

See also https://github.com/termux/termux-packages#android-dynamic-linker and https://github.com/termux/termux-packages/issues/2846.
