### ISSUE TITLE
New error 😡 segmentation fault

### ISSUE THREAD

**Issue by Shubhamvis98** [termux/termux-app#846]
Now when I try to open Metasploit then it shows segmentation fault
**Last line in image**
👇
![screenshot_20180920-061225](https://user-images.githubusercontent.com/43336210/45789368-ef450c80-bc9c-11e8-80bf-264a8b5dd215.png)
**Please update installing msf script**

**Comment by Grimler91** [comment]
Metasploit isn't a package from termux-packages so report it to the person you got the script from
