### ISSUE TITLE
Problems in apt-update

### ISSUE THREAD

**Issue by Gamekiller17** [termux/termux-app#848]
![screenshot_2018-09-21-12-16-24](https://user-images.githubusercontent.com/37091901/45863528-585d7a80-bd98-11e8-9b45-4a1a25dfb6e5.png)

**Why this is happening? I tried to remove other repository's instead to its own in the sources.list file but still same problem. Please Help me!**

**Comment by Grimler91** [comment]
The warning says that line 2 and 5 in sources.list are duplicates. 
What's the content of `sources.list`?

**Comment by xeffyr** [comment]
@Gamekiller17 Try this:

1. Restore original **sources.list**:
```
echo "deb https://termux.net stable main" > ${PREFIX}/etc/apt/sources.list
```

2. Remove **sources.list.d** (just in case). Make sure that you copied command **correctly**:
```
rm -rf ${PREFIX}/etc/apt/sources.list.d
```

**Comment by vishal-chaudhary30** [comment]
> @Gamekiller17 Try this:
> 
> 1. Restore original **sources.list**:
> 
> ```
> echo "deb https://termux.net stable main" > ${PREFIX}/etc/apt/sources.list
> ```
> 
> 1. Remove **sources.list.d** (just in case). Make sure that you copied command **correctly**:
> 
> ```
> rm -rf ${PREFIX}/etc/apt/sources.list.d
> ```

thanks brother 👍

**Comment by vishal-chaudhary30** [comment]
have a nice day:)
