### ISSUE TITLE
Volume keys not suppressed in app

### ISSUE THREAD

**Issue by TwoLeaves** [termux/termux-app#85]
The volume changes using the volume keys on my Galaxy S7 are not suppressed when using the Termux app (i.e. they still change the volume when held down as key modifiers and display the standard volume change overlay). On stock firmware this didn't happen. Since installing a custom ROM (and root, and a number of Xposed modules), the volume keys are no longer suppressed. I realise it might be hard to track down the reason for the trouble considering all the after-market modification on my phone, but I thought I would report it in case it's a bug in the Termux app. Terminal Emulator for Android does not exhibit this issue with the same setup. Thanks.

**Comment by PwnicornDev** [comment]
It's probably one of the Xposed modules, I had the same problem.
If you have GravityBox, make sure to not change anything in "Navigation keys actions > Volume keys".
If you have Xposed Additions, completely disable button remapping.
These modules break applications that try to use the keys themselves.

**Comment by TwoLeaves** [comment]
Yes the issue was Xposed Additions. Thanks PwnicornDev. I have found alternatives modules which achieve the same thing without the issue Xposed Additions has.

**Comment by fornwall** [comment]
Great! Closing this issue.
