### ISSUE TITLE
Can't access Bluetooth

### ISSUE THREAD

**Issue by Anonymous1p** [termux/termux-app#850]
I am a student of cse 1st year.
I can't afford a laptop due to of not having enough money so when i hear that i can learn programming
with termux app then it becomes a God Gift for me beacuse now i am able to run linux in my Android.
thanks for this..

My issue is that i want to learn so many other things like vaulnerability testing of other smartphones
but for this work i need bluetooth enabling machine and this feature is not yet supported in this app.
i want to use BlueBorne also but it can't access bluetooth .

My request to the Termux team is that plz make it able to use of Android bluetooth.
    it will be a great work.
Thank you Termux Team.

**Comment by Grimler91** [comment]
Hi, there's a couple of open feature requests regarding Bluetooth, see for example #235 and https://github.com/termux/termux-api/issues/88.

Regarding blueborne see https://github.com/termux/termux-packages/issues/2081

**Comment by Anonymous1p** [comment]
Thanks for your reply  #Grimler91  
plz put effort for this...
