### ISSUE TITLE
External storage(SD card) not sensitive with capital and lower case

### ISSUE THREAD

**Issue by rush3** [termux/termux-app#852]
Dear Sir
   If there exits file A.txt , and we want to create  a.txt , it will fail at external storage. But it successes if we create both A.txt and a.txt at the home folder of Termux.
   
Thanks

**Comment by Grimler91** [comment]
Hi, see https://android.stackexchange.com/questions/57328/should-the-sdcard-support-case-sensitive-files.
This is due to how android works, nothing we can do about it
