### ISSUE TITLE
Can it be used in 4.4.2 devices?

### ISSUE THREAD

**Issue by zaoqi-unsafe** [termux/termux-app#854]

**Comment by hyperpallium** [comment]
No.

Have a look at terminal IDE.  It's a great effort, and comes with several tools - but binaries are not adapted to the android filesystem, so e.g. domain name lookups don't work automatically. There's (clumsy) workarounds.

Maybe, you could copy specific execuables across, from termux installed on a later device?  I don't know how different 4.4.2 is, for whether this would work...
