### ISSUE TITLE
How to connect Quoda Text Editor with Termux ?

### ISSUE THREAD

**Issue by AJ-Creations** [termux/termux-app#855]
As we know that Termux is the greatest terminal app for Android, I was using it for making NodeJS projects. Now I need to use the Termux App-Private folder as the project directory. But I can't access that folder through my Text Editor (Quoda Android App). Using vim or nano is an absolute no as it has no programing related tools and it is very hard to make huge NodeJS projects vim/nano. Quoda has ftp client feature but It can't connect anonymously to any ftp server and I can't start Termux ftp server using Access control either. Quoda has FTP, FTPS, FTPES, SFTP client features but it forces me to enter username and password. How could I connect Quoda Text Editor with Termux App-Private folder ? Rooting is also not a good idea....

**Comment by Grimler91** [comment]
You could just `cp -r node_project_folder /sdcard/`, do the editting and then copy it back when you want to test it

**Comment by AJ-Creations** [comment]
Found the way: You can just enter any username like ABCD and any password like XYZ and it will login successfully.
