### ISSUE TITLE
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "r_mem_memzero" referenced by "libr_hash.so"

### ISSUE THREAD

**Issue by Cvar1984** [termux/termux-app#856]
$ export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
But return same error.

$ env
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
LANG=en_US.UTF-8
PREFIX=/data/data/com.termux/files/usr                                  PWD=/data/data/com.termux/files/home
HOME=/data/data/com.termux/files/home
TMPDIR=/data/data/com.termux/files/usr/tmp
SHELL=/data/data/com.termux/files/usr/bin/bash
TERM=xterm-256color
SHLVL=1                                                                 ANDROID_ROOT=/system
ANDROID_DATA=/data
EXTERNAL_STORAGE=/storage/emulated/0
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
_=/data/data/com.termux/files/usr/bin/env
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.49-g987e9cc #1 SMP PREEMPT Tue Oct 27 18:35:37 IST 2015 armv7l Android
Termux-packages arch:                                                   arm                                                                     Android version:
5.1.1                                                                   Device manufacturer:
HUAWEI
Device model:
HUAWEI SCL-U31

**Comment by Grimler91** [comment]
What are you running to get this error? I guess it's related to R from its-pointless repo so you should probably open an issue there instead

**Comment by its-pointless** [comment]
That symbol is in libr_util.so.2.9.0 which is part of radare2.

**Comment by Grimler91** [comment]
Ah, right, thanks

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#2923
