### ISSUE TITLE
FTP Client has only read access.

### ISSUE THREAD

**Issue by AJ-Creations** [termux/termux-app#857]
Today, I tried connecting ES File Explorer and Quoda Text Editor apps as FTP Client with Termux. I ran below command:
`tcpsvd -vE 0.0.0.0 1024 ftpd /`
And the apps logged in successfully. But when I tried creating new files, deleting files, renaming or modifying files, two of those apps are showing errors. Should I do any extra steps to solve this error?
![screenshot_2018-10-02-14-01-54](https://user-images.githubusercontent.com/38273300/46338371-a18db400-c64d-11e8-96a4-443267476f71.png)
--Error while tried creating a new folder in ES File Explorer.
![screenshot_2018-10-02-14-09-30](https://user-images.githubusercontent.com/38273300/46338416-c1bd7300-c64d-11e8-9493-d1285c45523c.png)
--Error while creating a new file in Quoda Text Editor.
Please somebody help me on solving this error.

**Comment by AJ-Creations** [comment]
I've also tried `chmod -R 777 .` command in that folder. Still not working. I have no root access.

**Comment by xeffyr** [comment]
@AJ-Creations Seems it can't understand some commands. I tried to connect from my PC via ftp utility:
```
xeffyr@archlinux:~:$ ftp 192.168.1.170 1024
Connected to 192.168.1.170.
220 Operation successful
Name (192.168.1.170:xeffyr): 
230 Operation successful
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> put libmylib.so
200 Operation successful
500 Unknown command
ftp> ls libmylib.so
200 Operation successful
150 Directory listing
226 Operation successful
ftp> get shlib.c
200 Operation successful
150 Opening BINARY connection for shlib.c (532 bytes)
226 Operation successful
532 bytes received in 0,00519 seconds (100 kbytes/s)
ftp>
```

The commands `put`, `delete`, `chmod`, `rename` are not working, but `dir` and `get` some few others work. That's why FTP is read-only for you. There something wrong with busybox's ftpd.

**Comment by AJ-Creations** [comment]
@xeffyr thanks a lot BRO....
it worked out!
Wow!

**Comment by ardyfeb** [comment]
How to access with quoda ? I have trying to connect them but no luck

**Comment by xeffyr** [comment]
@ardyfeb busybox's ftp server is very limited in functionality.

**Comment by xeffyr** [comment]
@ardyfeb Make sure that you entering correct port.

**Comment by ardyfeb** [comment]
> @ardyfeb Make sure that you entering correct port.

The ftp connection are successfully, but when i navigating to file picker the file not showing and ftp server throw error log `cannot open /. permission denied` While a have to set the ftp root as /sdcard

**Comment by xeffyr** [comment]
Have you tried `termux-setup-storage` before starting ftp server ? Is `ls /sdcard/` or `touch /sdcard/myfile` works ?

**Comment by ardyfeb** [comment]
![screenshot_peluncur_pixel_20181107-203135](https://user-images.githubusercontent.com/30074366/48134366-485c1480-e2cc-11e8-80df-f036156f1479.png)
Everything works if i use pc terminal the ftp works correctly, but no quoda, quick edit, others

**Comment by AJ-Creations** [comment]
Complete step for connecting termux app private directory with Quoda text editor is given below:<hr>


Step.1: Open Termix and run this command - `tcpsvd -vE 0.0.0.0 1024 ftpd /`
Step.2: Open Quoda, go to it's settings/Cloud & Servers/Add Server
Step.3: Select server type as FTP, and fill below credentials to the input fields that are seen in that settings page -

Name: Any name as you wish(I gave it the name "Termux-App-Private"
Address: 0.0.0.0
Username: any name as you wish(The FTP server is started without specifying any username or password. So any username and password will work.
Password: Anything as you wish
Base URL: /data/data/com.termux/files/
Initial folder: /data/data/com.termux/files/
Port: 1024
<hr>
Then below that form, you can see a button saying "test". Click over it to check whether the credentials are correct. If so, click over the "Save" button and start accessing termux's app private folder on your Quoda text editor.

<hr>
For Node,js users, I have made a nodejs global module that will help you on starting the FTP server quickly and easily.
For nodejs users, install tap2p (Termux-App-Private Two Public) by running below command:
`npm i -g tap2p` and then run this command - `tap2p`
And continue to above 2<sup>nd</sup> step.
Then later on whenever you want to access your termux's app-private-folder in Quoda Text Editor, just open termux and run `tap2p`  then open Quoda Text Editor and enjoy!

if you use tap2p, you don't have run `tcpsvd -vE 0.0.0.0 1024 ftpd /` instead you just need to run `tap2p`.

**Comment by xeffyr** [comment]
@AJ-Creations Why you prefer `0.0.0.0` over `127.0.0.1` ?

**Comment by AJ-Creations** [comment]
> > Complete step for connecting termux app private directory with Quoda text editor is given below:
> > Step.1: Open Termix and run this command - `tcpsvd -vE 0.0.0.0 1024 ftpd /`
> > Step.2: Open Quoda, go to it's settings/Cloud & Servers/Add Server
> > Step.3: Select server type as FTP, and fill below credentials to the input fields that are seen in that settings page -
> > Name: Any name as you wish(I gave it the name "Termux-App-Private")
> > Address: **0.0.0.0**
> > Username: any name as you wish(The FTP server is started without specifying any username or password. So any username and password will work.
> > Password: Anything as you wish
> > Base URL: **/data/data/com.termux/files/**
> > Initial folder: **/data/data/com.termux/files/**
> > Port: **1024**
> > Then below that form, you can see a button saying "test". Click over it to check whether the credentials are correct. If so, click over the "Save" button and start accessing termux's app private folder on your Quoda text editor.
> > For Node,js users, I have made a nodejs global module that will help you on starting the FTP server quickly and easily. For nodejs users, install tap2p (Termux-App-Private Two Public) by running below command: `npm i -g tap2p` and then run this command - `tap2p` And continue to above 2nd step. Then later on whenever you want to access your termux's app-private-folder in Quoda Text Editor, just open termux and run `tap2p `then open Quoda Text Editor and enjoy!
> > if you use tap2p, you don't have run `tcpsvd -vE 0.0.0.0 1024 ftpd /` instead you just need to run **tap2p**.
> > I thing I could help...
> 
> Thanks for you to very good tutorial, but i no luck at this feature
> 
> Se video below : https://streamable.com/vz723

From where have you downoaded Termux app ?
I mean from play store or from f-droid ?

**Comment by fahadali32** [comment]
I can't understand please make full video for noob

**Comment by aryankh71** [comment]
Ftp is not connected in my termux how can i fix it?
