### ISSUE TITLE
NodeJS create-react-app says npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AJ-Creations** [termux/termux-app#858]
When I ran create-react-app ninja-club, I got below result:
![screenshot_2018-10-02-21-33-15](https://user-images.githubusercontent.com/38273300/46361456-57c3be80-c68b-11e8-80b2-d0bb369adccc.png)
![screenshot_2018-10-02-21-33-06](https://user-images.githubusercontent.com/38273300/46361458-57c3be80-c68b-11e8-9263-cbac529bed31.png)
The project directory is `/data/data/com.termux/files/home/ninja-club`.
What is the problem here and how can I solve it ?

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#2922

**Comment by AJ-Creations** [comment]
Another problem found: when I tried installing an older version of NodeJS using the following command: `nvm install 8.9`
