### ISSUE TITLE
Add margin to the app on phone?

### ISSUE THREAD

**Issue by verboze** [termux/termux-app#859]
This may be related to [issue 272](https://github.com/termux/termux-app/issues/272). I use a Oneplus 6 phone, and due to the lack of margin, the text is slightly cut off on both the left and right sides of the screen, probably due to the glass layout of the OP6. I would be awesome if you could add a slight margin (or even better, make it configurable) all around the screen to prevent this issue.

![image](https://user-images.githubusercontent.com/461698/46441274-0e7b7980-c734-11e8-9183-162774386241.png)

**Comment by xeffyr** [comment]
@verboze This is already done in https://github.com/termux/termux-app/pull/792. Just application with these changes (and many other) is not released.

**Comment by verboze** [comment]
Already resolved in https://github.com/termux/termux-app/pull/792. Closing.
