### ISSUE TITLE
It is a bug?

### ISSUE THREAD

**Issue by myfreess** [termux/termux-app#860]
[~/workdir]$ apt remove coreutils
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  coreutils
0 upgraded, 0 newly installed, 1 to remove and 4 not upgraded.
After this operation, 1384 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 13721 files and directories currently installed.)
Removing coreutils (8.30-1) ...
Processing triggers for man (1.14.4) ...
[~/workdir]$ ls
bash: /data/data/com.termux/files/usr/bin/ls: No such file or directory
[~/workdir]$ cd oh-my-termux/
[~/workdir/oh-my-termux]$ ls
bash: /data/data/com.termux/files/usr/bin/ls: No such file or directory

**Comment by pulketo** [comment]
do not remove anything that has a core in its name ;)

**Comment by xeffyr** [comment]
@myfreess Just a behaviour of bash - binary path caching. Run `hash -r` to fix.

@pulketo coreutils can be safely removed as this is non-default package on Termux, initial utilities are provided by busybox.

**Comment by myfreess** [comment]
@xeffyr thanks，i use `ln -s busybox ls`fix this problem
