### ISSUE TITLE
Ping Failure

### ISSUE THREAD

**Issue by DeMack** [termux/termux-app#862]
I have a fresh install of Termux and when I try to ping I get an invalid host name exception. I have to assume this is a DNS issue, but I can't figure out how to fix it. I am on a non rooted galaxy s9+.

**Comment by fornwall** [comment]
Do you get it for all host or just a specific one?

Try out using ping from inside .e.g [Terminal Emulator for Android](https://play.google.com/store/apps/details?id=jackpal.androidterm&hl=en) - if the problem is the same there this is a general issue with your phone and not Termux specific.

**Comment by DeMack** [comment]
I hadn't tried since then, but it seems to be working now. Not sure what changed, but thanks for the help anyway.
