### ISSUE TITLE
failed to connect with openssh after apt upgrade of yesterday

### ISSUE THREAD

**Issue by fracalhub** [termux/termux-app#863]
Hi all, 

I upgraded termux with apt update&&upgrade and installed MariaDb on yesterday.

Today, when I try to connect with openssh to my smartphone I get this errors on sshd -d console:

`sshd -d
debug1: sshd version OpenSSH_7.8, OpenSSL 1.1.1  11 Sep 2018
debug1: private host key #0: ssh-rsa SHA256:NfHD3bDak8jDnrZTVf37FqlGiPsMsllk7jZuaEgasCw
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:7Cu1KmHt7KLiJPP3bgjrctjrrpruxWvmtu4L0yJp590
debug1: private host key #2: ssh-ed25519 SHA256:NK1c2LjCLrmYNfZQlwlMb3tdvKaRHWErQ/rhen45U1s
debug1: rexec_argv[0]='/data/data/com.termux/files/usr/bin/sshd'
debug1: rexec_argv[1]='-d'
debug1: Bind to port 8022 on ::.
Server listening on :: port 8022.
debug1: Bind to port 8022 on 0.0.0.0.
Server listening on 0.0.0.0 port 8022.
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 7 out 7 newsock 7 pipe -1 sock 10
debug1: inetd sockets after dupping: 5, 5
Connection from 176.100.211.205 port 53445 on 192.168.1.208 p
Connection from 176.100.211.205 port 53445 on 192.168.1.208 port 8022
debug1: Client protocol version 2.0; client software version OpenSSH_7.1
debug1: match: OpenSSH_7.1 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Local version string SSH-2.0-OpenSSH_7.8
debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_INIT
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: KEX done
debug1: KEX done
debug1: userauth-request for user Freddie service ssh-connection method none
debug1: attempt 0 failures 0
Failed none for Freddie from 176.100.211.205 port 53445 ssh2
debug1: userauth-request for user Freddie service ssh-connection method publickey
debug1: attempt 1 failures 0
debug1: userauth_pubkey: test pkalg ssh-rsa pkblob RSA SHA256:bry9ShjsZoQ8+Vb+orFelIEF8GO1/VtDXjuTxo9SuUY
debug1: temporarily_use_uid: 10230/10230 (e=10230/10230)
debug1: trying public key file /data/data/com.termux/files/home/.ssh/authorized_keys
debug1: fd 8 clearing O_NONBLOCK
debug1: restore_uid: (unprivileged)
debug1: temporarily_use_uid: 10230/10230 (e=10230/10230)
debug1: trying public key file /data/data/com.termux/files/home/.ssh/authorized_keys2
debug1: Could not open authorized keys '/data/data/com.termux/files/home/.ssh/authorized_keys2': No such file or directory
debug1: restore_uid: (unprivileged)
Failed publickey for Freddie from 176.100.211.205 port 53445 ssh2
debug1: userauth-request for user Freddie service ssh-connection method keyboard-interactive
debug1: attempt 2 failures 1
debug1: keyboard-interactive d
debug1: attempt 2 failures 1
debug1: keyboard-interactive devs
debug1: auth2_challenge: user=Freddie devs=
debug1: kbdint_alloc: devices ''
Failed keyboard-interactive for Freddie from 176.100.211.205 port 53445 ssh2
Connection closed by authenticating user Freddie 176.100.211.205 port 53445
debug1: do_cleanup`

the authorizing file in /data/data/com.termux/files/home/.ssh/authorized_keys is not empty

Please help

**Comment by xeffyr** [comment]
@fracalhub sshd is running as root ?

**Comment by fracalhub** [comment]
> > debug1: restore_uid: (unprivileged) Failed publickey for Freddie from 176.100.211.205 port 53445 ssh2
> 
> @fracalhub At least what I see from your log - you are trying to login with invalid key. Check file `authorized_keys` and make sure that key is not truncated or split on multiple lines.

I have two keys (I use two different pc to connect to termux) with no lines between them. I checked authorized_keys with cat and micro text editor and it seems ok..

**Comment by xeffyr** [comment]
For me both OpenSSH and Dropbear are working without problems. I can login to Termux with all supported SSH keys.

If you are adding keys via editing (copy and paste) with text editor, the common problem is missing some symbols at the end or beginning of key line.

**Comment by fracalhub** [comment]
a little update. I have no problem to connect with the other pc. 
Maybe the problem is with the first pc that I use to connect to my smartphone with termux?
I'll try to regenerate the key in the first pc..

**Comment by fornwall** [comment]
I'm closing this as it seems to not be a Termux issue. Let us know if you find out otherwise @fracalhub !
