### ISSUE TITLE
Shift-PageUp/Down to scroll through the terminal

### ISSUE THREAD

**Issue by arno01** [termux/termux-app#867]
I am using a physical keyboard and would like to scroll through the terminal output using Shift-PageUp/PageDown combination.

Ctrl-LeftArrow/RightArrow is working for jumping between the words. Home & End buttons working too.
PageUp/PageDown is working in vim/less/... fine.

Let me know if I could help debugging this.

**Comment by Grimler91** [comment]
You can use tmux as a workaround, you can then use ctrl + b followed by pgup or pgdn to scroll

**Comment by randomqhacker** [comment]
Also interested in this. Just bought a BT keyboard for Termux and realized FN-Shift-UpArrow (which should send Shift-PageUp) did not scroll. I'm using the F-Droid version of Termux.

**Comment by Norcoen** [comment]
i have the same problem with a small bluetooth keyboard

**Comment by hebo6** [comment]
This is an amazing and desirable feature

**Comment by ah-dagdelen** [comment]
As a workaround, one can start shell in emacs. Page up and page down keys work there.

**Comment by amaramth** [comment]
This feature is greatly needed. What kind of terminal has a scroll buffer that can't be scrolled with a keyboard.

**Comment by agnostic-apollo** [comment]
Fixed locally, will be available in next release.

**Comment by agnostic-apollo** [comment]
Check 66a9495d and 33295de. If using github builds, you can download apk from https://github.com/termux/termux-app/actions/runs/5035491694

**Comment by ristomatti** [comment]
@agnostic-apollo Could you give an estimate when the fix will be released? I don't want to uninstall all the addons to get this working. Thank you!

**Comment by ristomatti** [comment]
I know the feeling. Thank you for the quick reply!

**Comment by agnostic-apollo** [comment]
You are welcome. Thanks for understanding.
