### ISSUE TITLE
DNS issues with terraform

### ISSUE THREAD

**Issue by jbrockett** [termux/termux-app#869]
I am trying to use terraform within termux to provision AWS infrastructure.  I have a basic tf file that just tries to use the aws provisioner.  When I run `terraform init` on my mac or ubuntu hosts, it downloads the plugin without issue.  When I try on termux, I get the following error:

`Error installing provider "aws": Get https://releases.hashicorp.com/terraform-provider-aws/: dial tcp: lookup releases.hashicorp.com on [::1]:53: read udp [::1]:37606->[::1]:53: read: connection refused`

I have read that there are possible issues with the go dns resolver that may cause this, but I'm unsure of how to correct it.  I am able to perform a nslookup on the domain above and get the proper DNS entries returned.

#210 looks to be a similar issue, but they were running go code and terraform is a precompiled binary for linux 64bit.  I am running this on a chromebook with an intel processor.  `dpkg --print-architecture` shows i686.  I was able to install golang and run the sample code from #210 and that worked fine.

**Comment by JCutty** [comment]
I'm having the exact same issue. Any progress?

**Comment by jbrockett** [comment]
I ended up having to run [ubuntu under proot](https://wiki.termux.com/wiki/PRoot) in order to use terraform.  I tried alpine, but ran into [other issues getting it to run there](https://github.com/Hax4us/TermuxAlpine/issues/7).  I've read other people have been able to run terraform successfully under termux, so I hope it's something easily fixed and I can go back to stock termux.

**Comment by xeffyr** [comment]
> so I hope it's something easily fixed and I can go back to stock termux.

Easy fix is to recompile terraform for Termux with `GOOS=android`.

**Comment by jbrockett** [comment]
I had tried to get this to work previously with termux-chroot, but was missing the resolv-conf package.  After installing that, terraform works from termux without recompiling.  Thanks for the tip!
