### ISSUE TITLE
Google Keyboard 5 layout issue

### ISSUE THREAD

**Issue by licaon-kter** [termux/termux-app#87]
I tested the new [Google Keyboard 5](http://www.xda-developers.com/google-keyboard-5-0-update-brings-one-handed-mode-adjustable-height-key-borders-and-more/) and something is not right.

While Firefox shows the layout as I want (no numbers row; secondary chars on long press), Termux does not

Pic ([KISS has the same issue](https://github.com/Neamar/KISS/issues/454)): https://i.imgur.com/UFLNXFR.jpg

Now, looking at them side by side I see one more difference: the Enter/Search key.
So, it might be a different activity/intent, that is called in Termux, that changed since Google Keyboard version 4?

**Comment by fornwall** [comment]
Thanks, I'm awaiting the version 5 update to reach me so that I can test!

**Comment by licaon-kter** [comment]
[Do it](https://www.apkmirror.com/apk/google-inc/google-keyboard/google-keyboard-5-0-20-121473290-release/)!

**Comment by licaon-kter** [comment]
Are you asking for [a password field](https://github.com/Neamar/KISS/issues/454#issuecomment-221612287) actually?

**Comment by licaon-kter** [comment]
Maybe you can add a `show suggestion` option like KISS does.

**Comment by fornwall** [comment]
Ok, so the workarounds didn't work across keyboards and the numbers row are back in the latest version (`v0.38`). But using the [TYPE_NULL](https://developer.android.com/reference/android/text/InputType.html#TYPE_NULL) input type is the most correct thing to do and hopefully works best across keyboards, so this is probably something we have to live with.
