### ISSUE TITLE
Dropbear package can not be installed

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-app#871]
Dear specialists,
I AM using latest compiled Termux release from Github. And I Am helplessto install dropbear successfully. I Am getting info, that 81 % is installed but system hang and package can not be installed till The end. I want to use Dropbear SSH server. Does somebody of us know, why thispackage can not be installed? I AM using Samsung Galaxy chat with Android 6.0.1. And app is installed on internal storage. May be, that it would be A good idea to install busybox first. My phone uses ARM 32 bit CPU. Ihave been able to install openbox and many other APPS.

**Comment by xeffyr** [comment]
> Does somebody of us know, why thispackage can not be installed?

No one know this. Maybe problem with your network.

> May be, that it would be A good idea to install busybox first.

Termux does not have busybox installed by default ? Thats something strange... Make sure that you have original Termux from FDroid or Google Play.

> Ihave been able to install openbox and many other APPS.

How you was able to install packages if you wrote that busybox is not installed ?

***

I suggest you to try again do `pkg install dropbear`. If this not working, you can try to download *.deb file with `apt download` and install with `dpkg -i *.deb`.
