### ISSUE TITLE
Please add READ_LOGS to list of requested permissions

### ISSUE THREAD

**Issue by jidanni** [termux/termux-app#873]
Please add android.permission.READ_LOGS to app's list of requested permissions.

That way (non-root) users could do (just once after getting their phone)
$ adb shell pm grant com.turmux android.permission.READ_LOGS

Enabling then in the app doing e.g.,
$ logcat -d -b radio | grep OPERATOR
etc. things that were formerly impossible.

One could now run shell scripts that could precisely pluck data from
logcat and post-process it, much more pinpoint than any bulky logcat
app... Or GPS app... or cell tower id app... !

**Comment by xeffyr** [comment]
No, this may not be added. See https://stackoverflow.com/a/45270606.

**Comment by jidanni** [comment]
All I know is for https://github.com/plusCubed/matlog
here in Android 8.0 non-root, all I need to do is the same
adb shell pm grant permission I mentioned above, and it works fine.

**Comment by jidanni** [comment]
I am saying you first need to put it in the manifest.
Only then can I come along and do
adb shell pm grant permission.

**Comment by jidanni** [comment]
If it is not already in the manifest, then
adb shell pm grant permission
won't work.

**Comment by xeffyr** [comment]
> I am saying you first need to put it in the manifest.
Only then can I come along and do
adb shell pm grant permission.

Now it will definitely not be added.

**Comment by Grimler91** [comment]
See also https://github.com/termux/termux-api/issues/211.
