### ISSUE TITLE
could you create package which would allow users to conect to Termux by using Putty client for Windows?

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-app#878]
Dear core developers,
I Am sad, that I do not know how to create RSA key or other authorisation key, which will allow Me to connect to Termux Bash shellby using Putty for Windows. I have tried Openssh and Dropbear, but I had no success.
Does somebody of you could create little .deb package with shell script which would allow user to create SSH connection to Dropbear, which will be usable from Putty for WIndows? Port can be 8022.
I have tried to create RSA key, but I Am getting error from Putty. Any help will be very appreciated.

**Comment by Grimler91** [comment]
Well it is possible to connect from putty, you just need to fix whatever error you're getting. 

You can generate a ssh key-pair in putty with `ssh-keygen` and then you need to put the generated public key in `˜/.ssh/authorized_keys` in termux, that's really all there is to it

**Comment by xeffyr** [comment]
Putty by default uses a custom key format. Example:
```
$ puttygen -O public keyfile 
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20181017"
AAAAB3NzaC1yc2EAAAABJQAAAQEAnivWpQQj8qs8m2Ew5o4M8c6LJYV7PZ5evanh
ipyrrfpyx4ioXLUftsLAEWhwK8PC2S866te2N1aVb2cNCH3306OChvvamMoaRZ7H
3XZddajKdUl7Y7H5aGrcw4lCvfPf3q+cG7h9TyDRu2J+Sx1wSmiLXIUuAb+XxYEH
qMFCf3OhCILUmL6EVfxhYlAhQWQiWNaYErFtevD/+EY5ahbeYnsQtmdNr+isuwdd
WN6tnF0OkYqG7b48LPtpn3MpeJS4xxkNciY7MKmSScIz9HiIdlVytKYoMi7wjJES
Fk1NXyESuavWTPNesQnwHp6y7KBD/WqcpzD9MTI27Z080pnfkQ==
```

You have to convert it to OpenSSH format by doing this:
```
$ puttygen -O public-openssh keyfile
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnivWpQQj8qs8m2Ew5o4M8c6LJYV7PZ5evanhipyrrfpyx4ioXLUftsLAEWhwK8PC2S866te2N1aVb2cNCH3306OChvvamMoaRZ7H3XZddajKdUl7Y7H5aGrcw4lCvfPf3q+cG7h9TyDRu2J+Sx1wSmiLXIUuAb+XxYEHqMFCf3OhCILUmL6EVfxhYlAhQWQiWNaYErFtevD/+EY5ahbeYnsQtmdNr+isuwddWN6tnF0OkYqG7b48LPtpn3MpeJS4xxkNciY7MKmSScIz9HiIdlVytKYoMi7wjJESFk1NXyESuavWTPNesQnwHp6y7KBD/WqcpzD9MTI27Z080pnfkQ== rsa-key-20181017
```

**Comment by Grimler91** [comment]
Closing this then since connecting from putty works, no new package needed
