### ISSUE TITLE
Termux can not access SD cart or other external media connectedby using USB andcompatiblewith Android kernel and USB OTG APIS

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-app#879]
Dear specialists,
I Am wondering, why is it not possible to allow users to access external storage from Termux at least when creating new Chroot container by using Proot.
I Am aware, that SD card is not so fast like build in chips which are The internal part of every Android device. I also know, that there is no USB HUB, which can power external harddisk and power also connected Android device at The same time. Unfortunately, this HUB donot exist thanks to strange facts.
But why Termux do not allow users to store or access data from external SD card? Or from external harddisk?
Could this make system unstable?
I AM aware, that Android 7.0 and newer do not allow users to store application package to external SD card. And even Android 6.0 allowed this, applications data have been stored in The internal device storage, if application programmer did not make his app so all data were really stored to SD card.
But I think, that developer have freedom to store application data to SD card. If not all, at least big files would be stored on externalSD card.
Thank you very much for yours explanation.

**Comment by Grimler91** [comment]
It's only possible (on newer android versions) to access the usb otg using androids API, and no one has done the programming needed for that yet. See https://github.com/termux/termux-app/issues/71 for an older discussion/feature request
