### ISSUE TITLE
Hacker's Keyboard overlaps terminal in 5-row mode

### ISSUE THREAD

**Issue by sryze** [termux/termux-app#88]
If you use Termux together with [Hacker's Keyboard](https://github.com/klausw/hackerskeyboard) in landscape mode, or more generally in 5-row mode (which is the default for landscape), the keyboard will hide the last couple of lines at the bottom and you basically won't see what you're typing.

As a workaround, you can set the height of the keyboard in Hacker's Keyboard options to < 40% height of the screen but this obviously makes it harder to type in 5-row mode.

Android version: 6.0.1 (CyanogenMod 13.0)
Termux: 0.34
Hacker's Keyboard: 1.38.2

I think this might be the same problem as in #87 but I wasn't entirely sure hence a new issue. Feel free to close if it's a duplicate.

**Comment by fornwall** [comment]
I'm unfortunately not able to reproduce it directly, will try on more devices. Meanwhile, could you provide a screenshot of the whole screen while you are having the issue?

**Comment by sryze** [comment]
Here is a screenshot:

![screenshot_20160504-145403](https://cloud.githubusercontent.com/assets/4525736/15009536/11d0db32-1211-11e6-9fbc-5548bd5ce5d3.png)

**Comment by fornwall** [comment]
This was actually a problem with the terminal refusing to resize to lower than 8 rows.

I've changed that for the upcoming update to 4, so it should fix the situation shown in your screenshot (it's probably not worth going lower than 4 since programs and terminal emulation starts to misbehave in that case).

Thanks a lot for reporting!

**Comment by sids4ru** [comment]
Hi this is happening on my mobile as well .... samsung galaxy a7

**Comment by sids4ru** [comment]
both termux and keyboard are updated
