### ISSUE TITLE
Is it not possible to set file permissions to 644 on the SD Card?

### ISSUE THREAD

**Issue by nstgc** [termux/termux-app#881]
I'm mostly just trying to confirm this, but I can't seem to set file permissions to 644 for files on the SD Card.

I used `termux-setup-storage`, `cd storage/eternal-1/`, `touch test`, `chmod 644 test`, and the `ls -l test` to see that its 755.

I'm guessing this is normal?

**Comment by Grimler91** [comment]
Yes, you can't change permissions in the shared storage

**Comment by nstgc** [comment]
> Yes, you can't change permissions in the shared storage

Thanks
