### ISSUE TITLE
Can't install app Error code: -504

### ISSUE THREAD

**Issue by ghost** [termux/termux-app#882]
Please help me. When I am trying to install termux app from play store it download but it can't install and it says Can't install the app wit Error code: -504. I try clearing and force stoping google play services, google framework and playstore and rebooting my device but no luck. And I also tried hard resetting my device but then again can't install with error code: -504. Please help.

**Comment by xeffyr** [comment]
@Gabriel0001 

This can be caused by:

1. Android wasn't able to delete files that you created with `sudo`.
2. Google Play or it's services were updated on your device and something was broken (**likely**).

As I wrote before:
> We can't do anything with Google Play or Your Device for obvious reasons.

**Comment by Gabriel0001** [comment]
@xeffyr

Oh I see. Thanks. I'll look on google or in somewhere to fix it. But please if I can't find anything to fix my device can you help me?

**Comment by Gabriel0001** [comment]
@xeffyr

I fixed it 😁. I go to the system files /data/data/ and delete com.termux. I wonder why it is there if I uninstalled termux but it has no file only folder name ".suroot". By the way thank you very much for your help 👌
