### ISSUE TITLE
Error reporting for termux link

### ISSUE THREAD

**Issue by zccusergit** [termux/termux-app#885]
The problem：WARNING: linker: Unsupported flags DT_FLAGS_1=0x8.
This error will not occur when I change the source address from HTTPS to HTTP .
Student: if I don't change that and make it error reporting has an effect on usage?

**Comment by Grimler91** [comment]
It doesn't affect anything, it's a warning and not an error.

See https://github.com/termux/termux-packages/issues/2846 for more information
