### ISSUE TITLE
command '' found, did you mean:  Command '[' from package 'coreutils'  Command 'k' from package 'kona' bash: /data/data/com.termux/files/usr/etc/bash.bashrc: line 4: syntax error near unexpected token `}' bash: /data/data/com.termux/files/usr/etc/bash.bashrc: line 4: `}'

### ISSUE THREAD

**Issue by uyu717** [termux/termux-app#887]
pls Help . How to fix this

**Comment by xeffyr** [comment]
@uyu717 What you did to get this error ?

**Comment by uyu717** [comment]
in Home screen and command change bash 4-4 $ 

Pls how to fix this

**Comment by pulketo** [comment]
I don't get it, could you attach a screenshot?

**Comment by xeffyr** [comment]
Yes, screenshot is needed and output of `cat /data/data/com.termux/files/usr/etc/bash.bashrc`.

**Comment by uyu717** [comment]
Screensot can see in my profl pic ...im sorry

**Comment by uyu717** [comment]
i change my prof pic xeffyr .. pls look

**Comment by Grimler91** [comment]
ˋrm -rf $PREFIXˋ and restarting termux seems like the easiest way to fix this..

**Comment by MUNEER461** [comment]
Help me

**Comment by MUNEER461** [comment]
![Screenshot_2020-02-21-16-20-17-37_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/60612345/75028394-2f2da600-54c6-11ea-83c8-797b57aeded7.png)

**Comment by uyu717** [comment]
rm -rf $PREFIX


u can reset ur termux

**Comment by xeffyr** [comment]
@uyu717 In case which happened for @MUNEER461, Termux reset is not needed. Just rm, rename or fix syntax errors in the `~/.bashrc` file.
