### ISSUE TITLE
Allow user to use shells outside of Termux' data directory.

### ISSUE THREAD

**Issue by pthfdr-42** [termux/termux-app#888]
Android comes with `mksh`, which can be configured in `/system/etc/mkshrc`.
However, `chsh` do not allow me to use it (`/system/bin/sh`).
Even worse, `chsh` prepends `/data/data/com.termux/files/usr/bin/` to all pathes.

**Comment by xeffyr** [comment]
The /system/etc/mkshrc can be edited only by root users while Termux is primarily designed for non-rooed.
