### ISSUE TITLE
To build a terminal apk just contains an executable file

### ISSUE THREAD

**Issue by caweed** [termux/termux-app#89]
Hello! I'm a student and I'm very interested in programming but not allowed to use computer.  :(
One day I found an app [c4droid](https://play.google.com/store/apps/details?id=com.n0n3m4.droidc) and I used it to do my programmings.  :) It has a nice option called export, which you can put your executable file into an apk and share it with your friends. I ever made a term-2048 game using ncurses. But the terminal doesn't support 256-color.  It doesn't support init_color(). That's to say, I can just use about eight standard colors. Later, I found [termux](https://play.google.com/store/apps/details?id=com.termux). Yes, it supports. But how could I export an apk just like [c4droid](https://play.google.com/store/apps/details?id=com.n0n3m4.droidc). Could you add this fantastic feature or is there any other solution? Thank you.

**Comment by fornwall** [comment]
It's not possible, but something like this is planned in the medium term!

**Comment by caweed** [comment]
Ok, I'm looking forward to !

**Comment by fornwall** [comment]
Track the issue at https://github.com/termux/termux-packages/issues/63 for progress in this - so I'm closing this issue to avoid duplication.
