### ISSUE TITLE
is it possible to share folder between distribution executed in Proot and Termux?

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-app#891]
Dear specialists,
I have The dream. Sharing folder between Termux environment and Linux distribution which would be executed by using Proot.
Why AM I dreaming about this unusual think?
It is possible to run Speech-dispatcher from Linux distribution and it is even possible to use Pulseaudio from Termux to play sounds from distribution, which have been executed by using Proot. Arch Linux can perform this task thanks to is perfect package pulseaudio-alsa. 
Speech-dispatcher speech server allow communication by using Inet sockets or Unix sockets.
And if it would be possible to share folder between Proot and Termux environment, may be, that speech-dispatcher could communicate with Pulseaudio by using Unix sockets. Perhaps, those sockets are much more faster, than Inet sockets.
Thank you very much for yours answer and for yours future debate.

**Comment by Grimler91** [comment]
What are you actually asking here? 

The linux distribution folder you're login into with proot is accessible from termux and all termux folders you've binded when starting proot are accessible to proot

**Comment by xeffyr** [comment]
> And if it would be possible to share folder between Proot and Termux environment, may be, that speech-dispatcher could communicate with Pulseaudio by using Unix sockets.

Proot supports *binding*, with option '-b'.
