### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by empt1xo** [termux/termux-app#893]
I just opened termux app and got this, I have no idea what's wrong with it, any ideas ? !

https://i.imgur.com/5mbtzTA.png

**Comment by xeffyr** [comment]
What you did before ? Do you edited profile or bashrc files ? Maybe you downloaded a suspicious script from the Internet and executed it ?

What I see from your screenshot is that your environment is broken and this is not done by Termux.

**Comment by empt1xo** [comment]
@xeffyr hey thanks for replying, I'm kinda a beginner
i just checked  and I'mre this issue happened after running this command ```chown -R u0_a133:u0_a133 ../usr```

**Comment by xeffyr** [comment]
> I'm kinda a beginner
> chown -R u0_a133:u0_a133 ../usr

@empt1xo Ohh, in this way it will be easier for you to reinstall Termux.

**Comment by empt1xo** [comment]
@xeffyr if there is any other way to fix this please let me know I have a lot installed on termux, reinstalling everything will be a pain in the ass,
thanks man
