### ISSUE TITLE
[feature request] Selectively allow termux to keep screen on

### ISSUE THREAD

**Issue by arooni** [termux/termux-app#897]
So I often am running something that I'd like to just keep running in the background as a second screen.  Issue is once the android timeout period is reached the tablet turns off.  Anyway to force termux to keep the screen on?  

Ideally the setting would persist between termux sessions.  

I know juicessh has this feature (but after using termux how could I go back there? lol :) )

**Comment by its-pointless** [comment]
termux-wake-lock doesn't work?

**Comment by hyperpallium** [comment]
(not OP) `termux-wake-lock` doesn't work (nor sliding down on the termux notification to reveal the `exit` and `acquire wakelock` buttons).

To be clear, the display turns off, but termux seems to keep running. e.g. set (android settings) display sleep to 15sec, the following starts just as the display turns off, and and keeps running (e.g. if I turn it back on after 20sec, it's printed 20 lines)

```
$ sleep 15; for i in {1..60} ; do echo $i; sleep 1; done
```

It might just be android 5.1 (or Huawei EMUI), that the display timeout overrides any wakelock.

It would be nice if termux could keep the display on.  
A workaround is to just set sleep at max (30 minutes). I usually have it at 5.

**Comment by xeffyr** [comment]
Implemented in v0.66.
Long tap on screen, then toggle checkbox "Keep screen on".

**Comment by GrpeApple** [comment]
How do I run this with a command?
No need to just go through more settings.

**Comment by WMCB-Tech** [comment]
You don't need to enter a command, there's no such script to keep screen on unless Termux implements that

**Comment by GrpeApple** [comment]
> You don't need to enter a command, there's no such script to keep screen on unless Termux implements that

That’s what I said.
