### ISSUE TITLE
wkhtmltopdf. 

### ISSUE THREAD

**Issue by nedz14** [termux/termux-app#898]
I tried to install wkhtmltopdf on termux, but I got:
Unable to locate package wkhtmltopdf.

**Comment by Kaosxlinus** [comment]
Just clone a repository; https://github.com/wkhtmltopdf/wkhtmltopdf

**Comment by Grimler91** [comment]
Requires qt? In that case this PR should be at https://github.com/termux/x11-packages

**Comment by xeffyr** [comment]
Yes, requires Qt.

**Comment by Grimler91** [comment]
Closing in favor of https://github.com/termux/termux-packages/issues/3183
