### ISSUE TITLE
Package request: mono

### ISSUE THREAD

**Issue by archanox** [termux/termux-app#9]
It would be fantastic if mono support was included in termux to at least run cli applications.

**Comment by fornwall** [comment]
Thanks for the suggestion! Will look into trying a cross compile soon, for future reference when looking into this:

- [Mono on ARM information](http://www.mono-project.com/docs/about-mono/supported-platforms/arm/)
- [Stackoverflow post about cross compiling to Android ARM](http://stackoverflow.com/questions/17941856/compile-mono-for-android-arm7)
- [Stackoverflow post about cross compiling to Android x86](http://stackoverflow.com/questions/27438837/how-to-cross-compile-mono-for-x86-android)

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#40
