### ISSUE TITLE
feature request: support accessing files stored in google drive

### ISSUE THREAD

**Issue by ginabythebay** [termux/termux-app#90]
I'm not quite sure this is practical, but I am imagning a feature compareble to the google drive sync provided for the mac (and windows?).  Anyway, I would like to be able to treat a some  files within google drive as if they were local files from within termux.

**Comment by Neo-Oli** [comment]
Normally on Linux Grive2 would be used to sync a local folder with Google Drive. https://github.com/vitalif/grive2. Maybe it could be added to Termux. Would that suit your needs?

**Comment by xeffyr** [comment]
> treat a some files within google drive as if they were local files from within termux.

Various "cloud sync" tools are not a problem.
But mountable gdrive directories (FUSE ??) in Termux is kind of root-based features and can't be implemented at Android API level.
