### ISSUE TITLE
 bad adaptive icon on 8.1.0 (LNGOS 15.1)

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [termux/termux-app#900]
![termux](https://user-images.githubusercontent.com/14617699/47883068-bae87280-de3c-11e8-9003-7c1fb794801c.png)

Android version 8.1.0
LineageOS version: 15.1-201810

**Comment by c-e-p-x-u-o** [comment]
same bug for Termux:Boot

**Comment by c-e-p-x-u-o** [comment]
you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by c-e-p-x-u-o** [comment]
> I've recently found a launcher that uses "Round Icons" if you enable to.

If you enable what?


There no "Use Round Icons" or "Preferred Icon Style" in trebuchet (com.cyanogenmod.trebuchet)
The only one setting is ```Icons shape = Squircle```

**Comment by fbarda** [comment]
### The Setting
![screenshot_20181223-154148_niagara launcher](https://user-images.githubusercontent.com/30421526/50383917-6dff7a80-06ce-11e9-8af8-079d2e07c949.jpg)
### Original Adaptive icon
![screenshot_20181223-154154_niagara launcher](https://user-images.githubusercontent.com/30421526/50383918-6dff7a80-06ce-11e9-9080-749d4a48acea.jpg)
### Circular icon, but yeah I noticed it doesn't use squircicle like others
![screenshot_20181223-154208_niagara launcher](https://user-images.githubusercontent.com/30421526/50383919-6dff7a80-06ce-11e9-9031-311773bc1600.jpg)

**Comment by c-e-p-x-u-o** [comment]
![img_20181223_170319](https://user-images.githubusercontent.com/14617699/50384343-bf126d00-06d4-11e9-9685-a7c7c94a32f5.jpg)

**Comment by fbarda** [comment]
Have you tried forcing adaptive icons?

**Comment by c-e-p-x-u-o** [comment]
It's for app that has no adaptive icons. Yes, I've tried it.

**Comment by c-e-p-x-u-o** [comment]
Forcing adaptive icons off:
![img_20181224_013941](https://user-images.githubusercontent.com/14617699/50388075-fa388e80-071c-11e9-9230-83ca73b7cd95.jpg)

Forcing adaptive icons on:
![img_20181224_014016](https://user-images.githubusercontent.com/14617699/50388076-fefd4280-071c-11e9-9c15-4d96601a8790.jpg)

**Comment by brunelli** [comment]
Same issue with Nova Launcher on a Sony Xperia X running 8.0.

**Comment by fornwall** [comment]
Could you try out if this works better in version 0.66 of the app, which has just been released and should be available on Google Play within an hour or so, and on F-Droid within a day or two?

**Comment by brunelli** [comment]
@fornwall It's fixed for me.

**Comment by fornwall** [comment]
@brunelli Great, thanks! The other Termux apps will be updated the coming week to have adaptive icons as well on more devices.
