### ISSUE TITLE
Improve UI by adding Bar for CTRL, TAB, Arrows, ...

### ISSUE THREAD

**Issue by KenA91** [termux/termux-app#903]
See how the app #JuiceSSH solved this:
[JuiceSSH Screenshot](https://abload.de/img/screenshot_2018-04-1742itx.png)

**Comment by trygveaa** [comment]
Termux already has this. Press Volume up + q to enable it.

**Comment by Grimler91** [comment]
Yeah, sounds like what we already have. See https://wiki.termux.com/wiki/Touch_Keyboard
