### ISSUE TITLE
[Th3inspector]:# perl Th3inspect                            Can't locate HTTP/Request.pm in @INC (you may need to install the HTTP::Request module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.0/i686-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.28.0 /data/data/com.termux/files/usr/lib/perl5/5.28.0/i686-android /data/data/com.termux/files/usr/lib/perl5/5.28.0 .) at Th3inspector.pl line 5. BEGIN failed--compilation aborted at Th3inspector.pl line 5.

### ISSUE THREAD

**Issue by uyu717** [termux/termux-app#904]
Hello Best Regards :helpme to fix this

**Comment by Grimler91** [comment]
Install the HTTP::Request module through cpan(m). See for example https://stackoverflow.com/questions/65865/whats-the-easiest-way-to-install-a-missing-perl-module.

**Comment by 1uffyD9** [comment]
I used `apt-get install libwww-perl` and it worked.

**Comment by COMBAT-OFFICIAL** [comment]
Can't locate HTTP/Request.pm in @INC (you may need to install the HTTP::Request module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.30.1 /data/data/com.termux/files/usr/lib/perl5/5.30.1/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.30.1 .) at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.                        BEGIN failed--compilation aborted at /data/data/com.termux/files/usr/share/Th3inspector/Th3inspector.pl line 5.

**Comment by xKaliDragonx** [comment]
1-)pkg install perl
2-) cpan App::cpanminus
3-)cpan HTTP::Request

**Comment by malekw** [comment]
How can I install http request on termux please help lol

**Comment by vaibhav-rm** [comment]
> How can I install http request on termux on my android device please help lol

Do "cpan HTTP::Request" command

**Comment by pgr224** [comment]
> > How can I install http request on termux on my android device please help lol
> 
> Do "cpan HTTP::Request" command

No such directory

**Comment by xeffyr** [comment]
@pgr224 Execute it **without quotes**.

**Comment by isuruwa** [comment]
Type Command 'cpan HTTP::Request'
