### ISSUE TITLE
Error while install Nokogiri 1.8.0 

### ISSUE THREAD

**Issue by XSecr3t** [termux/termux-app#906]
Hello sir greetings

I have some problem can anybody help me?

I want install Nokogiri 1.8.0 but cant cause have error like this

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/nokogiri-1.8.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/extensions/aarch64-linux/2.5.0/nokogiri-1.8.0/gem_make.out

I have already run any command that i see like

gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]
Or

bundle config build.nokogiri --use-system-libraries
    bundle install

But the result still same, exit  ode 1

So what should i do?
I already uninstalled and installed again my termux 10times since 2 day ago
And Rebuild Package but the result still same,error code 1
It sucks for me can anyone help me sir?

It would be pleasure if somebody help me for guide me how to fix this problems.
First time i use termux looks good and everything is fine,but after 3 or 4 month everything has change,i already update every second every files and package but the result still same.

Somebody please help me🙁🙁

Because this problem i cannot run my metasploit again.
Thanks for reply.

**Comment by Grimler91** [comment]
We can't help you without seeing the actual error message, which is probably in the mkmf.log or gem_make.out mentioned above.

**Comment by XSecr3t** [comment]
@grimler91 here's the result error :

http://i67.tinypic.com/343maoh.png
http://i67.tinypic.com/2ahz9f9.png
http://i66.tinypic.com/23w08yr.png
http://i67.tinypic.com/4uyk1y.png
http://i65.tinypic.com/2w7ph12.png
http://i68.tinypic.com/2vjph6r.png
http://i67.tinypic.com/20shis5.png

I think you can help me for solve this,i dont what i want to do again,,,
I'll do everything but still same

Thanks for the reply sir.

**Comment by Grimler91** [comment]
Looks like it can't find the glob function, so you could try installing libandroid-glob and then run `LDFLAGS=" -lglob" gem install nokogiri -- --use-system-libraries`.

Also make sure you have libxml2, libxml2-dev, libxslt, libxslt-dev installed.

**Comment by XSecr3t** [comment]
@grimler91

But the result said i installed nokogiri 1.8.5 not 1.8.0 versions,my metasploit needs nokogiri 1.8.0 not 1.8.5

**Comment by XSecr3t** [comment]
root@Mr.XSecr3t:~#LDFLAGS=" -lglob" gem install nokogiri -- --use-system-libraries
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Building native extensions with: '--use-system-libraries'
This could take a while...
Successfully installed nokogiri-1.8.5
Parsing documentation for nokogiri-1.8.5
Done installing documentation for nokogiri after 10 seconds
1 gem installed
root@Mr.XSecr3t:~#

**Comment by XSecr3t** [comment]
When i run msfconsole result said 

root@Mr.XSecr3t:~#msfconsole
Could not find nokogiri-1.8.0 in any of the sources
Run `bundle install` to install missing gems.
root@Mr.XSecr3t:~#

And when i run bundle install the result said

root@Mr.XSecr3t:~#bundle install
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Could not locate Gemfile
root@Mr.XSecr3t:~#

**Comment by Grimler91** [comment]
> But the result said i installed nokogiri 1.8.5 not 1.8.0 versions,my metasploit needs nokogiri 1.8.0 not 1.8.5

I'm not a ruby/gem expert, but that sounds like something your favorite search engine can help you with, for example:
http://lmgtfy.com/?q=install+specific+version+of+gem

**Comment by XSecr3t** [comment]
Thank you for take some time!

**Comment by termux-69** [comment]
Please any one help me? 
uld not find nokogiri-1.8.0 in any of the sources
Run `bundle install` to install missing gems.
$ pkg install libandroid-glob
E: Type 'Ign:1' is not known on line 1 in source list /data/data/com.termux/files/usr/etc/apt/sources.list.d/pointless.list
E: The list of sources could not be read.

**Comment by PradeepKothariCA** [comment]
if you are on MAC 
try this 
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
sudo xcodebuild -license accept
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by kothari4u** [comment]
For Mac-
I was facing same issues. tried all means to resolve nokogiri-1.8.0 but no success 
Then I reinstall all command-line tools and this resolved my problem 
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
sudo xcodebuild -license accept
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

Hope this helps .
