### ISSUE TITLE
Feature request: auto default session name

### ISSUE THREAD

**Issue by KelvinShadewing** [termux/termux-app#908]
I thought instead of sessions being numbered, they could have a default name that either matches the current working directory, or if a command is running and has focus, such as vim, show the command's name and arguments. Like, if you run `vim myfile.txt`, it'll change the title to that, and if you close or suspend vim, the title returns to the CWD. Then when you name a session, you'd also have the option to clear the name and restore defaults.

I think this would help keep track of what's being done with each session without having to name them. What do you guys think?

**Comment by xeffyr** [comment]
> I thought instead of sessions being numbered, they could have a default name that either matches the current working directory,

And automatically overwrite a value that was set by user. That's shouldn't be implemented on application's side.

>  Like, if you run vim myfile.txt, it'll change the title to that, 

This done easily, e.g. with Bash:
```
trap 'printf "\e]0;%s\a" "${BASH_COMMAND//[^[:print:]]/}"' DEBUG
```

> I think this would help keep track of what's being done with each session without having to name them. What do you guys think?

The best way to achieve this, is to edit your bashrc. *Terminal application never should do something on it's own.*

This even can be put to default bashrc or similar, so this feature will be available immediately. Or it can be commented out.

**Comment by KelvinShadewing** [comment]
I didn't know this could be done with bashrc. Sorry.

**Comment by xeffyr** [comment]
With Zsh (and I guess other shells) this can be done too.

**Comment by xeffyr** [comment]
Closing since question purely about shell scripts/config. Answer in https://github.com/termux/termux-app/issues/908#issuecomment-436070526, also information about this topic searchable on the Internet.
