### ISSUE TITLE
Why can't the terminal install the mod_wsgi or uWSGI of the django deployment server

### ISSUE THREAD

**Issue by zccusergit** [termux/termux-app#909]
91% |█████████████████████████████▍  | 450kB     94% |██████████████████████████████  | 460kB     96% |██████████████████████████████▊ | 471kB     98% |███████████████████████████████▍| 481kB     100% |████████████████████████████████| 491kB 1.3MB/s
    Complete output from command python setup.py egg_info:
    WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
    WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-e2thyg5u/mod-wsgi/setup.py", line 168, in <module>
        'missing Apache httpd server packages.' % APXS)
    RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-e2thyg5u/mod-wsgi/

**Comment by Grimler91** [comment]
> RuntimeError: The 'apxs' command appears not to be installed or is not executable.

You don't have apxs, typing "apxs" in the terminal gives 
```
The program 'apxs' is not installed. Install it by executing:
 pkg install apache2
```

So you haven't installed apache2.
