### ISSUE TITLE
Add ability to edit, view, delete file on $HOME folder with external apps

### ISSUE THREAD

**Issue by ardyfeb** [termux/termux-app#911]
I currently development reactjs on my phone, cause on /sdcard npm cannot link global package i move my project to $HOME directory

Using vim so hard to me, cannot open multiple files, show line number or other

So what i can do with external app to edit files on $HOME files ?

**Comment by Grimler91** [comment]
If you are rooted and the editor app supports "root mode" then editing files in /data/data/com.termux/files are no problem.

Making everything in /data/data/com.termux editable to (all) external apps sounds like a very bad thing from a security perspective (and I'm not even sure it's possible in android)

**Comment by ardyfeb** [comment]
Thats right, i have root access and directly edit to com.termux directory
![screenshot_quickedit_pro_20181107-174338](https://user-images.githubusercontent.com/30074366/48126820-c44a6280-e2b4-11e8-8c05-05af599f7607.png)

But, are there other solutions for simpify my life ? Because not all code editor on android support root

**Comment by xeffyr** [comment]
> But, are there other solutions for simpify my life ?

No, it is not possible to have direct access to the application's private directory. On Android, each application is *sandboxed*, has own user/group id and protected by SELinux.

But, since you are using `QuickEdit Pro`, it is possible to have access to Termux via SFTP.

P.S. I use `QuickEdit Pro` too.

**Comment by JacobTDC** [comment]
@xeffyr said:
> No, it is not possible to have direct access to the application's private directory. On Android, each application is _sandboxed_, has own user/group id and protected by SELinux.

Actually, Termux is already able to allow other apps into it's files. Try using the `termux-open` utility on a png file, for example. It does this via. `com.termux/.app.TermuxOpenReceiver`.

**Comment by xeffyr** [comment]
Closing.

Some applications (including QuickEdit) are able to freely access Termux home folder through Storage Access Framework.

![Screenshot_20190906-182105_Files](https://user-images.githubusercontent.com/25881154/64439686-3a854480-d0d3-11e9-8e13-9f8ad3f459e9.png)

**Comment by ugale-deepak3010** [comment]
> I currently development reactjs on my phone, cause on /sdcard npm cannot link global package i move my project to $HOME directory
> 
> Using vim so hard to me, cannot open multiple files, show line number or other
> 
> So what i can do with external app to edit files on $HOME files ?





Same problem bro I am working on react but it is very difficult

**Comment by ugale-deepak3010** [comment]
Problem shared, thanks

**Comment by moud449** [comment]
you can use Acode app and access termux $HOME files easy - en'sha Allah - by this way ( yes i am using it to develop laravel project) 
![IMG_٢٠٢١٠٢١٠_١٩٠٦١٦](https://user-images.githubusercontent.com/31566070/107544916-60215200-6bd3-11eb-89a0-c2ac8c5a20da.jpg)
![IMG_٢٠٢١٠٢١٠_١٩٠٦٤٦](https://user-images.githubusercontent.com/31566070/107544928-6283ac00-6bd3-11eb-805b-c8547f5e29c2.jpg)
![Screenshot_2021-02-10-19-06-54-38](https://user-images.githubusercontent.com/31566070/107544935-63b4d900-6bd3-11eb-8b10-6de16c02e556.jpg)
![IMG_٢٠٢١٠٢١٠_١٩٠٧٠٤](https://user-images.githubusercontent.com/31566070/107544939-64e60600-6bd3-11eb-9d1f-889bf0891b7c.jpg)
![Screenshot_2021-02-10-19-07-11-55](https://user-images.githubusercontent.com/31566070/107544949-66afc980-6bd3-11eb-9bd8-96e44f88a629.jpg)
![IMG_٢٠٢١٠٢١٠_١٩٠٧١٩](https://user-images.githubusercontent.com/31566070/107544957-67486000-6bd3-11eb-96cf-b1ac70aa03fe.jpg)
