### ISSUE TITLE
Apache imported the mod_wsgi.so module and got WARNING: linker

### ISSUE THREAD

**Issue by zccusergit** [termux/termux-app#913]
$ apachectl start
WARNING: linker: /data/data/com.termux/files/usr/libexec/apache2/mod_wsgi.so: unused DT entry: type 0x6ffffef5 arg 0xd38
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
$
--------------------------------------------------
Please help me  Thank you very much!

**Comment by xeffyr** [comment]
Forget about linker warning. They are common on Android 5.

**Comment by zccusergit** [comment]
It's a system problem and not a software problem that's causing these errors, right?

**Comment by Grimler91** [comment]
Seems you have two warnings there. **Warnings**, not errors, so you don't really have any problems
