### ISSUE TITLE
Gpg not accepted

### ISSUE THREAD

**Issue by ShadyGaDa** [termux/termux-app#915]
$pkg install coreutils gnupg2 apt-transport-https wget
Hit:2 https://termux.net stable InRelease
Hit:3 https://grimler.se root InRelease
Err:1 https://its-pointless.github.io/files termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 906F5AFA9A32C72D
Reading package lists... Done
W: GPG error: https://its-pointless.github.io/files termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 906F5AFA9A32C72D
E: The repository 'https://its-pointless.github.io/files termux InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details

Have looked for solution, still at a loss.

**Comment by Grimler91** [comment]
You haven't imported its-pointless key (or overwritten trusted.gpg and thereby removed it). You can re-import it with `apt-key adv --recv 906F5AFA9A32C72D`, after installing dirmngr

**Comment by ShadyGaDa** [comment]
Thank you I removed pointless.list from etc installed gnupg and dirmngr and apt-key adv
