### ISSUE TITLE
"UI Tabs" addons request

### ISSUE THREAD

**Issue by kamathln** [termux/termux-app#917]
(Just throwing in an idea I got, before I forget it) UI tabs. 

Instead of just a terminal, Termux could also have 

1. An X11 terminal tab, 
1.  A Webview control, whose javascript has all the permissions and capabilities that the termux user gets (access to its files, running command line, notifications, etc.)
1.  A regular Android Fragment with APIs for Python, C++, Ruby, etc. 
1. Python-Kivy with it's UI contained in the tab

**Comment by kamathln** [comment]
Elaborating a bit on WebView control: This is so that people can build quick UIs like file managers, graphing applications, etc. that can use underlying libraries, commands etc.

**Comment by xeffyr** [comment]
For X11 we have https://github.com/termux/termux-x11, but it didn't went from pre-alpha state and is unmaintained now.

Regarding everything else - that's beyond the scope of Termux application (terminal emulator).
