### ISSUE TITLE
make executables and libs accessible to other apps

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-app#918]
Currently, the installed binaries and libs/folders are not readable/executable for other app user IDs. 

We can have an option to config apt to install packages to be accessible to other apps.

**Comment by Grimler91** [comment]
This has been asked a couple of times before in different forms. It isn't possible for various reasons. If you want to use a binary in another app then you need to recompile it and statically link it aginst dependencies and move it to the other app's directory.

**Comment by hyperpallium** [comment]
Couldn't you also put it on an sdcard?

**Comment by torappinfo** [comment]
Can I ask what is the underlying reason for impossibility?

I manually chmod files/folders, and it seems fine. The only problem is that new installed package is still not accessible to other apps.

Maybe I did not test enough binaries?

**Comment by Grimler91** [comment]
Again, it has been asked before so I encourage you to search for older issues. See for example https://github.com/termux/termux-packages/issues/616, https://github.com/termux/termux-app/issues/440 and more.

It would be a severe security issue if different apps could access each others data so android doesn't allow it. Chmodding won't help

**Comment by xeffyr** [comment]
> I manually chmod files/folders, and it seems fine.

@torappinfo Chmod doesn't change SELinux contexts, btw. For users with recent Android versions (assume 6.0+) and stock ROMs `chmod 777 {file or directory}` isn't working.

If this works for you, the best way to chmod something that you need or `chmod 777 -R $PREFIX`. But this **shouldn't be done** for package manager.
