### ISSUE TITLE
24bit True Color Support

### ISSUE THREAD

**Issue by ngroup** [termux/termux-app#92]
Hi, is there any way to enable the 24bit true color support in Termux?
As I see it now, only 256 color palatte is displayed.

**Comment by fornwall** [comment]
It's not possible yet, but probably will be soon. Let's leave this issue open to track this.

**Comment by ngroup** [comment]
Cool! Looking forward to the true color support.

**Comment by caesar** [comment]
This would be great!

**Comment by YPetremann** [comment]
Also looking for 24-bit color support, would be really interesting.

**Comment by fornwall** [comment]
24-bit color is now supported as of the 0.40 version!
