### ISSUE TITLE
Termux installation ussu

### ISSUE THREAD

**Issue by rahulsikdar224** [termux/termux-app#921]
Segmentation fault

**Comment by kamathln** [comment]
Rahul: Are you trying to install Termux? Or are you trying to install a package in Termux?

**Comment by jusdepatate** [comment]
@rahulsikdar224 what are you doing ? We are not mentalist..

**Comment by xeffyr** [comment]
@Grimler91 Why not to just close this issue ? This will motivate people to clearly describe the problem.

We don't have package `ussu` anyway, I even unsure that this thing exist... If `su` binary segfaults, then this anyway not Termux's problem and solution in this case to try a different version of Magisk/SuperSU.

**Comment by Grimler91** [comment]
@xeffyr I was planning on waiting a few days, but I guess it won't help (we really ought to fix a issue template for the main repo, like you have over at x11-packages)
