### ISSUE TITLE
When using Samsung DeX, there is no equivalent to pull out the drawer to start a new session

### ISSUE THREAD

**Issue by coreyreichle** [termux/termux-app#923]
The drawer that pulls out with a side swipe to get the "Keyboard" and "New Session", along with the session picker is inaccessible when using Termux in Dex (Samsung's DE).

There may already be a work-around, but if not, it would be great to add a way to access the menu.

**Comment by Grimler91** [comment]
There is a partial workaround that doesn't fix the problem entirely (a failsafe session can't be accessed). You should be able to open a new terminal and switch between them using key combinations: https://wiki.termux.com/wiki/Hardware_Keyboard

**Comment by laem** [comment]
Using the mouse to mimick the left pull works for me on the S10.

**Comment by coreyreichle** [comment]
> Using the mouse to mimick the left pull works for me on the S10.

With this and Grimler91's response, I think this is good to close.  PEBKAC.
