### ISSUE TITLE
Can't find the definition of S_BLKSIZE

### ISSUE THREAD

**Issue by jarun** [termux/termux-app#925]
Hi,

Not sure if this is the correct project, if not please redirect me.

I am not finding the macro `S_BLKSIZE` defined in any of the include files in the termux environment. It should probably be in `sys/stat.h`.

Can you please update the header to define this macro?

**Comment by xeffyr** [comment]
Android NDK doesn't define S_BLKSIZE.

**Comment by jarun** [comment]
Thanks for the info!
