### ISSUE TITLE
Gcc installation

### ISSUE THREAD

**Issue by playRoblox** [termux/termux-app#927]
Can not install gcc via apt install gcc

**Comment by xeffyr** [comment]
> Can not install gcc via apt install gcc

GCC was replaced by clang. See https://github.com/termux/termux-packages/issues/2511, https://github.com/termux/termux-packages/issues/369, https://github.com/termux/termux-packages/issues/407.
```
pkg install clang
```

**Comment by playRoblox** [comment]
Thanks!
