### ISSUE TITLE
ffmpeg 

### ISSUE THREAD

**Issue by paulsavo1** [termux/termux-app#932]
what is the command to start ffmpeg?

i have it installed but it is not running when i use shortcuts

**Comment by xeffyr** [comment]
> what is the command to start ffmpeg?

It's `ffmpeg`, isn't it ?

Use `dpkg -L` to see what's available in package:
```
$ dpkg -L ffmpeg | grep /bin/
/data/data/com.termux/files/usr/bin/ffmpeg
/data/data/com.termux/files/usr/bin/ffprobe
```
