### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by MrNobodyTharusha** [termux/termux-app#936]
I moved the startarch file to  /data/data/data/com.termux/files/usr/bin/env 
Now, in every new session display this error -

data/data/data/com.termux/files/home/.oh-my-zsh/oh-my-zsh.sh:14: /data/data/com.termux/files/usr/bin/env: bad interpreter: /bin/env: no such file or directory
env_default:1: /data/data/com.termux/files/usr/bin/env: bad interpreter: /bin/env: no such file or directory
env_default:1: /data/data/com.termux/files/usr/bin/env: bad interpreter: /bin/env: no such file or directory
 ~ 

What can I do for fix it ?  Please help me.....

**Comment by xeffyr** [comment]
> I moved the startarch file to /data/data/data/com.termux/files/usr/bin/env

This is a Termux's problem that you overwrote file ? I don't think so...
Reinstall Termux and never do this again.

**Comment by its-pointless** [comment]
Don't need to reinstall there is a failsafe option.

**Comment by xeffyr** [comment]
`failsafe option` + 
```
cd $PREFIX/bin
ln -sf busybox env
```

**Comment by MrNobodyTharusha** [comment]
Oh thank you boys...

**Comment by forliuyifei** [comment]
> `failsafe option` +
> 
> ```
> cd $PREFIX/bin
> ln -sf busybox env
> ```

It doesn't work for Android 11😭

**Comment by xeffyr** [comment]
@forliuyifei Issue is 2 years as outdated. Termux is no longer based on busybox. Link with coreutils instead.
