### ISSUE TITLE
pipe button | for button panel

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [termux/termux-app#937]
Could you add the pipe `|` to the panel with `ESC / - HOME ...`

**Comment by Grimler91** [comment]
Swipe up from "-" to get it. 
![screenshot_20181201-081243](https://user-images.githubusercontent.com/18900601/49325338-fad86d80-f540-11e8-9787-4273c9cb4bea.png)

**Comment by c-e-p-x-u-o** [comment]
It's impossible to find it and there a lot of space around  `/` and `-` to put `|` and `\`.

**Comment by Grimler91** [comment]
@c-e-p-x-u-o it will also be possible to configure the extra keys on the next release, see https://github.com/termux/termux-app/pull/788

**Comment by xeffyr** [comment]
> there are lot of space around / and - to put | and \.

Only on tablets.

**Comment by xeffyr** [comment]
There possible to add 1 extra key, but this may be useless because on next release Extra Key Row will be *configurable*.
>it will also be possible to configure the extra keys on the next release, see #788
