### ISSUE TITLE
(Feature Request) Orbot integration

### ISSUE THREAD

**Issue by pycadelic** [termux/termux-app#943]
Would it be possible to provide Orbot integration from the app?

The VPN mode present in the non-root versions of orbot is broken on many builds for whatever reason, there are open PRs in both LineageOS and orbot app that go unanswered for many months.

Therefore it's not possible to use Termux transparently through Tor, access onion services, etc.

Could Termux be made to connect to Orbot, like for instance Conversations or F-droid already do?

**Comment by xeffyr** [comment]
> Would it be possible to provide Orbot integration from the app?

`pkg install tor torsocks` ?

Or you mean transparently redirect traffic from command line tools ? This is not possible. F-Droid does it over Android API. But command line tools are completely independent, even if they running from application.
Orbot's VPN is the only variant here.

**Comment by pycadelic** [comment]
Re torsocks, just gave it a go and I believe it's not working because of - https://github.com/termux/termux-packages/issues/2711

I meant connecting the Termux app to Orbot via the localhost proxy; but if I understand you correctly, this is not possible because the processes that termux will spawn will not be using that connection?

Sorry I don't understand how it works under the hood so maybe a dumb question..

**Comment by xeffyr** [comment]
torsocks is the only way to make "transparent" proxying in Termux. Another variant is to try some environment variables:
1. This should work for libcurl-based programs:
```
export all_proxy="socks5://127.0.0.1:9050"
```

2. These commands may work for other programs, but likely that not:
```
export http_proxy="socks5://127.0.0.1:9050"
export https_proxy=$http_proxy
```

Again, it is not possible to setup network redirect widely if torsocks is not working. Termux is just application that executes command line programs, it's **not** OS and can't have own network stack.

You can try to setup a transparent proxy with package `tor`, if you have rooted device. But you will probably mess up the Android's iptables.

**Comment by denialplando** [comment]
The easiest way to torify an application inside Termux is by using the _torify_ wrapper, but you want to run all the network traffic through TOR as possible. However, this is not possible whith some applications. You may probe _tsocks_, which is a simple way to make transparent SOCKS proxying inside Termux.

**Comment by xeffyr** [comment]
Closing since following options available:

* Orbot VPN (it also available as per-app option).

* `torsocks`.

* `proxychains-ng`.

Strong reference to third-party application to use some feature is something that won't be implemented.
