### ISSUE TITLE
YouCompleteMe on Termux - lost cause?

### ISSUE THREAD

**Issue by pycadelic** [termux/termux-app#944]
https://github.com/Valloric/YouCompleteMe/issues/3262

Seems that in the past it was the case that YCM didn't even build on Android, but that's been fixed for awhile.

I experienced the problems described in that PR upon compiling YCM on Termux.

Is it a lost cause because there is no librt in android (apparently) ? Or did I do something wrong?

What do you guys use for autocompletion ?

**Comment by xeffyr** [comment]
> Is it a lost cause because there is no librt in android (apparently) ?

Yes, librt is not available on Android. Just patch YCM sources to remove linking to librt.

**Comment by pycadelic** [comment]
FYI, and any future readers, it works if you pass --system-libclang to install.py when compiling YCM.
