### ISSUE TITLE
Whether GUI programs can be executed

### ISSUE THREAD

**Issue by zccusergit** [termux/termux-app#947]
I'm in the installation python GUImodule error: error: command 'aarch64-linux-android-clang' failed with exit status 1, Please help me out thank you

**Comment by Grimler91** [comment]
Probably means that clang isn't installed.

**Comment by zccusergit** [comment]
1 error generated.                                           error: command 'aarch64-linux-android-clang' failed with exit status 1                                                                                                             ----------------------------------------                Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-crvc7zdr/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-9oxxr0zg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-crvc7zdr/kivy/             $

**Comment by Grimler91** [comment]
Still isn't the full error message

**Comment by zccusergit** [comment]
After checking the installation details, I found that there was a little installation error,I put quotation marks around the mistake:/data/data/com.termux/files/usr/tmp/pip-install-crvc7zdr/kivy/kivy/weakproxy.c:2796:12: warning: unused function '__pyx_pw_4kivy_9weakproxy_9WeakProxy_23__bool__' [-Wunused-function]                                                          "static int __pyx_pw_4kivy_9weakproxy_9WeakProxy_23__bool__(PyObject *__pyx_v_self) "{                                               ^                                                1 warning generated.                                        aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -landroid-support -L/home/builder/.termux-build/_cache/18-aarch64-21-v1/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -landroid-support -L/home/builder/.termux-build/_cache/18-aarch64-21-v1/sysroot/usr/lib build/temp.linux-aarch64-3.7/data/data/com.termux/files/usr/tmp/pip-install-crvc7zdr/kivy/kivy/weakproxy.o -L/data/data/com.termux/files/usr/lib -lpython3.7m -o build/lib.linux-aarch64-3.7/kivy/weakproxy.cpython-37m.so -lm

**Comment by Grimler91** [comment]
That's a warning, not an error (`warning: unused function`)
