### ISSUE TITLE
How to do this ? Plz help ./ngrok runtime: this CPU has no floating point hardware, so it cannot run this GOARM=6 binary. Recompile using GOARM=5.

### ISSUE THREAD

**Issue by uyu717** [termux/termux-app#948]

**Comment by xeffyr** [comment]
I don't see any problem with Termux here.
If your CPU doesn't support *hardware floating point*, you are out of luck - this is not fixable. Use a different device.

P.S. What device you use ?

**Comment by uyu717** [comment]
omg -- im use x86

**Comment by xeffyr** [comment]
Use x86 binary then =).

**Comment by uyu717** [comment]
How to get it :dancing_men:

**Comment by xeffyr** [comment]
You didn't check Ngrok's site ?
https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip

**Comment by uyu717** [comment]
im still trying it xeffyr
