### ISSUE TITLE
Feature Request: Support in Travis-CI

### ISSUE THREAD

**Issue by gwpl** [termux/termux-app#95]
Feature Request / Platform Request.
I'd like to test on Travis-CI ( https://github.com/travis-ci/travis-ci / http://travis-ci.org ) if my projects build successfully on https://github.com/termux/termux-app / https://termux.com Linux platform. (It's "Linux in your pocket" for android).

As issue relates to two projects, I've allowed myself to add request to Travis-CI project: https://github.com/travis-ci/travis-ci/issues/6087 as well to this project.

**Comment by gwpl** [comment]
It would be cool to see Termux-App being continuously tested on Travis CI using their Android support.

It would be even cooler to be able to see if projects we want to run on a top of Termux compile and run !

As I've asked [there](https://github.com/travis-ci/travis-ci/issues/6087), they pointed to their Android support: https://docs.travis-ci.com/user/languages/android . Is it possible to mariage those two? So Termux would become great target for Linux developers?

**Comment by Rudloff** [comment]
@gwpl I am working on something that might help you, a Docker image running Termux: https://hub.docker.com/r/rudloff/termux/
You can't use it directly in Travis (although you can use their [Docker support](https://docs.travis-ci.com/user/docker/) to pull the image) but you can easily use it in other CI tools like Gitlab CI.

**Comment by sdrausty** [comment]
What should the .travis.yml like like for https://sdrausty.github.io/buildAPKs/ and submodules? Advice regarding how to setup Travis builds inside the Termux environment are very welcome.

**Comment by ebraminio** [comment]
Hey there. Instead Travis CI, you can use CircleCI using @Rudloff Docker image.

Put something like this on `.circleci/config.yml` on your repo:

```yml
version: 2

jobs:
  termux:
    docker:
      - image: rudloff/termux
    steps:
      - checkout
      - run: ls # your test here

workflows:
  version: 2
  build:
    jobs:
      - termux
```

And enable CircleCI for you repo. And CricleCI offers SSH connecting to Docker images for debugging.

(no affiliation with CircleCI here)

No reason to keep this issue still open as it can be tested using a different and easy to use CI.

**Comment by gwpl** [comment]
Thank you! I didn't know earlier about CircleCl !

**Comment by ebraminio** [comment]
No Docker support also at the time :)

**Comment by xeffyr** [comment]
If someone is interested to try Termux environment on CI or cloud, check https://github.com/termux/termux-docker. Supports only i686 or x86_64.

Other variants are unavailable, except if you decide to bring up Android emulator and run Termux from it.
