### ISSUE TITLE
Termux Boot doesn't work

### ISSUE THREAD

**Issue by shagarah** [termux/termux-app#956]
I've purchased Termux Boot today but it doesn't seem to work. It claims it launches scripts at device boot, but it doesn't in my case.

I've lauched the app and made the directories .termux and boot as docs advised, added the script, tested it manually, and it works (just launches lighttpd server). But when I restarted my device the server wasn't working!

I must say I have little knowledge in linux in general so maybe I'm missing something.

Please help!

**Comment by Grimler91** [comment]
Closing since duplicate issue https://github.com/termux/termux-boot/issues/28 is solved
