### ISSUE TITLE
root repo doesn't work anymore

### ISSUE THREAD

**Issue by feklee** [termux/termux-app#958]
Here's what I get:

    $ pkg upgrade
    Hit:1 https://grimler.se root InRelease
    Hit:2 https://termux.net stable InRelease
    Hit:3 https://xeffyr.ttm.sh/termux x11 InRelease
    Err:1 https://grimler.se root InRelease
      The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    All packages are up to date.
    W: An error occurred during the signature verification. The repository is not updated and the 
previous index files will be used. GPG error: https://grimler.se root InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
    W: Failed to fetch https://grimler.se/dists/root/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
    W: Some index files failed to download. They have been ignored, or old ones used instead.
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Calculating upgrade... Done
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

How do I now update the packages installed from the root repo?

**Comment by Grimler91** [comment]
You need to re-download the key it seems, maybe because trusted.gpg was overwritten in an update. You can re-download the key with 
`apt-key adv --recv 5AAAC9E0A46BE53C`

**Comment by feklee** [comment]
Thanks, that solved it!

(Upgrade to Pie broke lots of things. Worst part is that WiFi cannot be enabled anymore. Using Termux to debug that.)
