### ISSUE TITLE
What happen with this ?? 

### ISSUE THREAD

**Issue by uyu717** [termux/termux-app#959]
kali-arm64/dev/urandom: Can't create 'kali-arm64/dev/urandom'
kali-arm64/dev/full: Can't create 'kali-arm64/dev/full'
kali-arm64/dev/random: Can't create 'kali-arm64/dev/random'
kali-arm64/dev/zero: Can't create 'kali-arm64/dev/zero'
kali-arm64/dev/tty: Can't create 'kali-arm64/dev/tty'
kali-arm64/dev/null: Can't create 'kali-arm64/dev/null'
kali-arm64/dev/ptmx: Can't create 'kali-arm64/dev/ptmx'

**Comment by xeffyr** [comment]
It is not possible to create device nodes without root, if /data was mounted with `nodev` option then it won't work even with root.

It's general Android/Linux permission denial error, it has nothing to do with Termux itself.
