### ISSUE TITLE
Mosh does not connect because of US-ASCII

### ISSUE THREAD

**Issue by sodoku** [termux/termux-app#96]
When trying to connect to my mosh sever, I get the following:

```
$ mosh sodoku@host
sodoku@host's password:
mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",

The client-supplied environment ([no charset variables]) specifies
the character set "US-ASCII".

LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
Connection to host closed.
mosh: Did not find mosh server startup message.
```

**Comment by fornwall** [comment]
Does connecting with mosh to the same server work from a computer (to see if the problem is not Termux-specific)?

If it works from another environment but not from Termux, can you check the environment variables by running `env` and pasting them here?

**Comment by sodoku** [comment]
@fornwall thanks for the quick answer.

I can remember having similar problems first on my computer which uses the `de_DE.utf8` locale. It worked after uncommenting that locale on the server in `/etc/locale.gen` and running `locale-gen`. Both server and laptop are Arch Linux. As I understand, termux runs with `US-ASCII` (mosh error message).

Relevant envs on laptop:

```
LANG=de_DE.utf8
LC_PAPER=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_TIME=en_US.UTF-8
```

on server:

```
LANG=en_US.UTF-8
LC_MESSAGES=C
```

Let me know, if you need anything else.

**Comment by sodoku** [comment]
I was researching a bit and found this workaround, which seems to work:

`mosh remotehost --server="LANG=$LANG mosh-server"`

**Comment by fornwall** [comment]
@sodoku Termux by default runs with `en_US.UTF-8`, not `US-ASCII`. Can you check envs in Termux to ensure that you haven't modified them yourself by mistake?

**Comment by sodoku** [comment]
@fornwall you are right, my Termux does show `LANG=en_US.UTF-8` in env. (I didn't change anything in Termux other than installing pacakges so far). 

I am starting to think, that is a mosh (or ssh) issue. I will continue investigating and let you know, if I find a solution. Thank you very much for all your help so far!

**Comment by fornwall** [comment]
@sodoku One thing you can try out: install perl with `apt install perl`, then run `mosh.pl sodoku@host` - that is, run `mosh.pl` instead of `mosh`. Does that make a difference?

**Comment by sodoku** [comment]
@fornwall wow, that indeed works!

**Comment by fornwall** [comment]
@sodoku Ok, interesting! It's a problem with the `mosh` wrapper used in the Termux package to avoid depending on perl.. Will look into it.

**Comment by sodoku** [comment]
@fornwall Thank you so much!

What's the best way to donate? Buy the extensions in the play store?

**Comment by its-pointless** [comment]
Fornwall should set up a patreon or something. But yeah buying the extentions is the only way at the moment.

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#288

**Comment by fornwall** [comment]
This is now fix in the latest version of the mosh package, to which you can update to with:

    apt update && apt upgrade

**Comment by sodoku** [comment]
@fornwall Thank you so much. I really appreciate the quick help!

**Comment by smemsh** [comment]
you could also have just:
```
Host *
SendEnv LANG
```
see more detailed comment in the canonical ticket #288
