### ISSUE TITLE
Can't update any thing

### ISSUE THREAD

**Issue by MrNobodyTharusha** [termux/termux-app#962]
I cant use upgrade commands and apt install comands...  always this error... please help me..

~  apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: The package kali-archive-keyring needs to be reinstalled, but I can't find an archive for it.
 ✘  ~  apt install python2-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: The package kali-archive-keyring needs to be reinstalled, but I can't find an archive for it.
 ✘  ~ 

what can I do for it ?

**Comment by xeffyr** [comment]
>  kali-archive-keyring

And how "kali-archive-keyring" is related to Termux ? This is not Termux's error **at all**!

**Comment by Grimler91** [comment]
@MrNobodyTharusha run `rm -rf $PREFIX` and restart the app. That will remove all installed packages and give you a fresh install (but keep $HOME intact).

**Comment by MrNobodyTharusha** [comment]
~  rm -rf $PREFIX
command_not_found_handler:1: no such file or directory: /data/data/com.termux/files/usr/libexec/termux/command-not-found
command_not_found_handler:1: no such file or directory: /data/data/com.termux/files/usr/libexec/termux/command-not-found
 ✘  ~ 

What happened...??

**Comment by MrNobodyTharusha** [comment]
Hey Grimler...  there is another issuse. I tried to install arch linux. But it did'nt work. So I deleted the arch file. But etc file is not deleting... 
$ rm -rf arch
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/d7746a63.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/4f316efb.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/3a3b02ce.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/Buypass_Class_3_Root_CA.pem': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/0b1b94ef.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/1eb37bdf.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/7aaf71c0.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/ca6e4ad9.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/TrustCor_ECA-1.pem': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/749e9e03.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/244b5494.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/bc3f2570.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/b7a5b843.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/4a6481c9.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/DigiCert_Trusted_Root_G4.pem': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/8d86cdd1.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/Deutsche_Telekom_Root_CA_2.pem': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/LuxTrust_Global_Root_2.pem': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/SwissSign_Silver_CA_-_G2.pem': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/2fa87019.0': Permission denied
rm: can't remove 'arch/etc/ca-certificates/extracted/cadir/7a7c655d.0': Permission denied


$ cd arch
$ ls
etc
$

Cloud you help me...?
