### ISSUE TITLE
 can i make the app run emacs automatically at after launch?

### ISSUE THREAD

**Issue by longlu** [termux/termux-app#964]
can i make the app run emacs automatically at after launch?

**Comment by Grimler91** [comment]
Well you can add `emacs` or  `emacs &` to the your `.bashrc`.

You could also put something like `emacs --bg-daemon` in your .profile. This starts a daemon that you can later connect to with `emacsclient`, with no startup time whatsoever.

The proper answer depends on what you actually want to achieve
