### ISSUE TITLE
The library of '-lstdc++fs' existing?

### ISSUE THREAD

**Issue by seisdr** [termux/termux-app#968]
``g++ tiv.o -o tiv -lstdc++fs -pthread -s                                                               /data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: cannot find -lstdc++fs                  clang-7: error: linker command failed with exit code 1 (use -v to see invocation)                     make: *** [Makefile:9: tiv] Error 1``

**Comment by fornwall** [comment]
Hello and thanks for reporting the issue!

Support for libstdc++fs will be added when the Android NDK adds it (Termux pulls in standard C++ libraries from there). See https://github.com/android-ndk/ndk for progress there.

**Comment by seisdr** [comment]
@fornwall I was compiled it and it was works fine , now I can't and got this error,why?
