### ISSUE TITLE
anyway to launch termux thru http link in android?  

### ISSUE THREAD

**Issue by longlu** [termux/termux-app#969]
anyway to launch termux thru http link in android?

that way it will be easier to jump from different apps.

**Comment by xeffyr** [comment]
There no way to launch Termux with http link.

**Comment by fornwall** [comment]
It could always be added if useful enough :).

@longlu Could you describe your use case, how you would use it?

**Comment by xeffyr** [comment]
Closing as this feature unlikely to be implemented.

**Comment by xeffyr** [comment]
@fornwall I guess intents much better to `jump from different apps`. Otherwise which app use URL for jumping into Termux ?
