### ISSUE TITLE
keep getting ”integer overflow” with many termux apps

### ISSUE THREAD

**Issue by smemsh** [termux/termux-app#97]
cannot figure out what is generating this error, is it specific to termux, is a warning or error.  however execution appears to halt:
```
$ mosh myserver
internal error: integer overflow 2147483647 * 4 prevented
mosh: Can't count colors: 22

$ su -l; id -un
internal error: integer overflow 2147483647 * 4 prevented
u0_a39

$ uname -a
Linux localhost 3.4.42-g7f4d949-00002-gb042f2b #1 SMP PREEMPT Tue Jan 6 10:06:17 CST 2015 armv7l Android
```

same issue appears to prevent `pip install pycrypto` from successfully running `configure`:
```
[...snip]
creating build/lib.linux-armv7l-3.5/Crypto/Signature
    copying lib/Crypto/Signature/__init__.py -> build/lib.linux-armv7l-3.5/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.linux-armv7l-3.5/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.linux-armv7l-3.5/Crypto/Signature
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    running build_configure
    internal error: integer overflow 2147483647 * 4 prevented
    internal error: integer overflow 2147483647 * 4 prevented
    error: [Errno 2] No such file or directory: 'src/config.h'
```
I have a Moto G 2014 (”titan” board model) with a stock ROM.  I traced the processes doing the write(2) of the integer overflow error and it's indeed the actual processes themselves (such as `mosh` above after the shell script wrapper has `execve()`'d `mosh` itself), so it's almost like it's coming from libc or something.  I cannot find these error substrings anywhere in Google searches so I am very puzzled where this is coming from, but unfortunately it makes termux rather unusable.

**Comment by smemsh** [comment]
P.S. I will be happy to know if anyone else can successfully complete `pip install pycrypto`.

**Comment by fornwall** [comment]
Interesting! Haven't seen that one before, will look around. Let me know if you (or anyone else) finds out anything more here!

**Comment by fornwall** [comment]
This issue was moved to termux/termux-packages#287
