### ISSUE TITLE
Cannot play video via termux-open (xdg-open)

### ISSUE THREAD

**Issue by rubikitch** [termux/termux-app#973]
Suddenly, termux cannot play any videos.

    $ xdg-open foo.mp4

or

    $ am broadcast --user 0 -a android.intent.action.VIEW -n com.termux/com.termux.app.TermuxOpenReceiver -d "/storage/emulated/0/Download/foo.mp4"

I failed to play videos with all video players.

- HUAWEI Video
- MX Player
- VLC

I have HUAWEI MediaPad M5 (SHT-AL09 8.0.0.193(C636)) / Android 8.0 EMUI 8.0.0
I manage all media files in termux by my script.

What can I do to play videos via termux?

**Comment by rubikitch** [comment]
Meanwhile I use darkhttpd to make a HTTP url.

/storage/emulated/0/Download/foo.mp4 -> http://localhost:8080/foo.mp4

$ darkhttpd /storage/emulated/0/Download --daemon --addr 127.0.0.1
$ termux-open http://localhost:8080/foo.mp4

I can play videos with MX Player.

**Comment by rubikitch** [comment]
Meanwhile I use darkhttpd to make a HTTP url.

/storage/emulated/0/Download/foo.mp4 -> http://localhost:8080/foo.mp4

$ darkhttpd /storage/emulated/0/Download --daemon --addr 127.0.0.1
$ termux-open http://localhost:8080/foo.mp4

I can play videos with MX Player.

**Comment by seisdr** [comment]
does the file ok?
probably you are on ```/sdcard/``` path

**Comment by rubikitch** [comment]
I do not have /sdcard/ path.

**Comment by seisdr** [comment]
Yea it's storage ..
Move the video into $HOME and try again

**Comment by seisdr** [comment]
and 
```
termux-open --content-type video http://localhost:8080/foo.mp4
```

**Comment by xeffyr** [comment]
> Move the video into $HOME and try again

> and
termux-open --content-type video http://localhost:8080/foo.mp4

@seisdr Before copypasting commands and confusing other people, understand what these commands doing. Your example (move to home then calling termux-open on URL) will not work without running server.

See what @rubikitch did https://github.com/termux/termux-app/issues/973#issuecomment-451630518.
![screenshot_20190112-193249_android system](https://user-images.githubusercontent.com/25881154/51076433-fc996300-16a0-11e9-83fe-363977563496.jpg)

**Comment by seisdr** [comment]
@xeffyr I edited the comment

**Comment by myfreess** [comment]
try 
```shell
termux-open-url http://localhost:8080/1.mp4
```

**Comment by djaman** [comment]
> Try this:-
`termux-open content-type video path.mp4`

**Comment by xeffyr** [comment]
Closing as issue is not reproducible (anymore?).
```
termux-open /sdcard/file.mp4
```
works as it should - opens a video player. Tested with MX Player.

**Comment by mySaYo** [comment]
The open command of fish shell may be possible.
