### ISSUE TITLE
What is the accepted way of testing for a Termux environment?

### ISSUE THREAD

**Issue by alxpettit** [termux/termux-app#976]
It's often the case that Unixlike systems have some standard scriptable method for testing for different environments, for if a routine is environment-specific -- e.g., differentiating between Debian, Fedora, Arch... So, what is the standard method on Termux?

**Comment by cswl** [comment]
You can check for Termux environment variables which are set on  a base install

```
PREFIX=/data/data/com.termux/files/usr`
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

Termux doesnt have a normal`/etc/`

**Comment by alxpettit** [comment]
So... there is no generally accepted flag or file specifically for detecting this? I ask because I have concerns about the value of the PREFIX flag changing and etc, so I wanted to know if there was a standard method. Can I assume that the path specified by `PREFIX` will never ever change in any future Termux version?

**Comment by cswl** [comment]
I think there was discussion about ability to change prefix.. aka dynamic prefix
Even then you can check if the said PREFIX has a termux enviroment.. 
A script/program to check this would be nice I guess

**Comment by Grimler91** [comment]
You could also check if the directory `/data/data/com.termux/files/` exists (and is readable). The PREFIX env var might be unset but the folder should be there.

The PREFIX won't be changed. It would only be changed if the project is forked.

**Comment by alxpettit** [comment]
Thanks!

If the file structure and PREFIX are never changing, then that's easy. The most robust and simple way seems to be to just check if the file path exists.

Actually, that's already what I was doing with my code -- but I wanted to get in touch with the devs to make sure it wasn't too stupid. Anyway, cheers!
