### ISSUE TITLE
Document provider support to make files accessible for third-party apps

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-app#977]
Thus, we have no need to keep files in public accessible locations. It also means symbolic links will work for third-party apps.

This single feature will make termux easier to cooperate with third-party apps, and now we can keep all files under termux private storages.

**Comment by xeffyr** [comment]
> Document provider support to make files accessible for third-party apps

Hmm. It is not implemented already ?

I just was able to select files from Termux internal storage:
![screenshot_20190111-131156_files](https://user-images.githubusercontent.com/25881154/51030573-8f9fa380-15a2-11e9-9446-67935b6294a5.jpg)

**Comment by xeffyr** [comment]
Closing as DocumentProvider already implemented and works.
Applications just have to use Storage Access Framework as direct file system access is not allowed by Android.
