### ISSUE TITLE
seting of navigation drawer

### ISSUE THREAD

**Issue by RalfWerner** [termux/termux-app#978]
I've a question relates to the management of several bash displays. **Is this an API function?** Is it possible to edit and change the **_navigation drawer_** (white) via a **script** e.g. in _.bashrc_ or another (here I did it by hand) and **how?**
![grafik](https://user-images.githubusercontent.com/45426380/51075945-99a0cf80-1692-11e9-8449-de9ec1f02942.png)

This question (issue) is also in https://github.com/termux/termux-api-package/issues/44 together with a _**/app-process**_ bug.

**Comment by Grimler91** [comment]
No, this is currently not possible. 

You can [define a combination of keys](https://wiki.termux.com/wiki/Terminal_Settings) to open the name-prompt but you can't set it from CLI.

**Comment by RalfWerner** [comment]
Addendum to the **shortcuts above**. With logcat I get **E termux** messages. Does that help with the error analysis?
```
$ logcat -s termux:* termux-api:*
--------- beginning of crash
--------- beginning of system
--------- beginning of main
01-15 14:40:44.293  8703  8703 E termux  : Keyboard shortcut 'shortcut.next-session' is not Ctrl+<something>
01-15 14:40:44.293  8703  8703 E termux  : Keyboard shortcut 'shortcut.rename-session' is not Ctrl+<something>
```
As an alternative to the flawed _**app process**_, I also tried following **api** function **play**. Unfortunately with a bug too:
```
$ termux-media-player play check.jpg
Prepare failed.: status=0x1
```
With the gallery and fotos apps the file **check.jpg** is displayed without problem. Can I get an **_answer from you_** or should I ask someone else or open a new **issue?**

**Comment by xeffyr** [comment]
> With logcat I get E termux messages.

Usage of *Ctrl+something* is blocked because this will interfere with bash/readline key shortcuts.
``` .java
if (!(parts.length == 2 && parts[0].trim().equals("ctrl")) || input.isEmpty() || input.length() > 2) {
    Log.e("termux", "Keyboard shortcut '" + name + "' is not Ctrl+<something>");
    return;
}
```

> Unfortunately with a bug too:
termux-media-player play check.jpg

This is not a bug. Media player can't be used on images.
Use something like `termux-open`.

**Comment by Grimler91** [comment]
@ralfwerner and also, you have spelled control "crtl" instead of "ctrl"

**Comment by RalfWerner** [comment]
Thank you both
and sorry - I need new glasses. with **_ctrl_** shortcut works as expected. The Termux-open function gives me the same error as described in: https://github.com/termux/termux-api-package/issues/44 (above) 
![grafik](https://user-images.githubusercontent.com/45426380/51193234-ad457380-18e8-11e9-889f-14b163601bd8.png)

and with _termux-media-player play sd/ip/check.mp4_ the sound but **_not the video_** is played.
With the appropriate **_mc_** function I get the message (**_app-process_**) :
![grafik](https://user-images.githubusercontent.com/45426380/51193662-acf9a800-18e9-11e9-9adb-90ac3c88c8f2.png)
(could be used successfully before Nov. 2018)
You said nothing to ".. planned" (above) - **is'nt it?** When not this issue can closed and I hope to get a little bit help to https://github.com/termux/termux-api-package/issues/44 there.

**Comment by RalfWerner** [comment]
could you possibly find the _bug_ in the following **log output?**
```
01-23 19:58:08.905 11053 11053 I appproc : Command=/system/bin/app_process / com.example.termuxam.Am broadcast --user 0 -a android.intent.action.VIEW -n com.termux/com.termux.app.TermuxOpenReceiver -d /data/data/com.termux/files/home/check.jpg 
01-23 19:58:09.394 10893 10926 W ContentProvider: Normalized content://com.termux.files//data/data/com.termux/files/home/check.jpg to content://com.termux.files/data/data/com.termux/files/home/check.jpg to avoid possible security issues
01-23 19:58:09.421 10893 10926 W ContentProvider: Normalized content://com.termux.files//data/data/com.termux/files/home/check.jpg to content://com.termux.files/data/data/com.termux/files/home/check.jpg to avoid possible security issues
01-23 19:58:09.426 10893 10926 W System.err: java.lang.SecurityException: Permission Denial: reading com.termux.app.TermuxOpenReceiver$ContentProvider uri content://com.termux.files/data/data/com.termux/files/home/check.jpg from pid=6452, uid=10023 requires android.permission.permRead, or grantUriPermission()
01-23 19:58:09.427 10893 10926 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.termux.app.TermuxOpenReceiver$ContentProvider uri content://com.termux.files/data/data/com.termux/files/home/check.jpg from pid=6452, uid=10023 requires android.permission.permRead, or grantUriPermission()
01-23 19:58:09.446 10893 10926 W ContentProvider: Normalized content://com.termux.files//data/data/com.termux/files/home/check.jpg to content://com.termux.files/data/data/com.termux/files/home/check.jpg to avoid possible security issues
01-23 19:58:09.447 10893 10926 W System.err: java.lang.SecurityException: Permission Denial: reading com.termux.app.TermuxOpenReceiver$ContentProvider uri content://com.termux.files/data/data/com.termux/files/home/check.jpg from pid=6452, uid=10023 requires android.permission.permRead, or grantUriPermission()
01-23 19:58:09.448 10893 10926 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.termux.app.TermuxOpenReceiver$ContentProvider uri content://com.termux.files/data/data/com.termux/files/home/check.jpg from pid=6452, uid=10023 requires android.permission.permRead, or grantUriPermission()
```

**Comment by xeffyr** [comment]
Closing in favor of **https://github.com/termux/termux-app/issues/995** - there problem described much cleaner.
