### ISSUE TITLE
Useless Gboard Number Row 

### ISSUE THREAD

**Issue by adi1090x** [termux/termux-app#985]
Is this a termux issue or google keyboard issue?
The  unwanted number row is really annoying and useless, how to hide it.
![s90116-112436](https://user-images.githubusercontent.com/26059688/51427611-edc22b80-1c1f-11e9-8362-96e56a321fe8.jpg)

**Comment by fornwall** [comment]
Hello and thanks for reporting! This is basically something that needs to be solved on the keyboard end, and not something that the Termux app itself has control over. You may want to try another keyboard if the issue is important for you.
