### ISSUE TITLE
keyboard on newest version

### ISSUE THREAD

**Issue by Hamishcn** [termux/termux-app#986]
thx for developing. I found that PGUP PGDN left and right navigation key have been removed on newest version. I think those keys are useful sometimes. may u pls let it back on next version?

**Comment by YuMu233** [comment]
+1

**Comment by kfangf** [comment]
I think so.I need  left and right keys to move the cursor when I want to change my codes.

**Comment by xeffyr** [comment]
See https://www.reddit.com/r/termux/comments/ai44cj/version_066_of_the_termux_app_has_been_released/.

Extra keyboard keys are now **configurable** and it is possible to add all needed keys manually.
