### ISSUE TITLE
Add option to hide extra key roww

### ISSUE THREAD

**Issue by Jim-Zenn** [termux/termux-app#987]
**Feature description**
I always use my tablet with a physical keyboard. I understand the extra key row must be a valuable feature for the phone users, but I have no need for it. Please add an option to disable it. Thank you.

**Reference implementation**
Does another app/terminal emulator have this feature?
Provide links to more background information

**Comment by trygveaa** [comment]
There already is an option to disable it: https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by no-mercy** [comment]
I can't disable extra keys on gemini pda. What i need to put into .termux/termux.properties to disable them?

**Comment by xeffyr** [comment]
> I can't disable extra keys on gemini pda.

Long tap on button "keyboard" at the **drawer** hidden at the left screen side.

**Comment by no-mercy** [comment]
Yep, works for me, BIG THANKS.
This should be in doc, imho.

**Comment by trygveaa** [comment]
It is in the docs. From the page I linked to:

> To enable the extra keys view you have to long tap on the keyboard button in the left drawer menu. You can also press Volume Up+Q or Volume Up+K.

**Comment by no-mercy** [comment]
@trygveaa btw, i can't use Volume + something on gemini, because volume keys are already mapped there as hotkeys.
