### ISSUE TITLE
Hostname matching in URL copy (Ctrl-Shift-U) requires dot

### ISSUE THREAD

**Issue by gscholt** [termux/termux-app#99]
Hi,

The termux URL copy (Ctrl-Shift-U) fails to match the following urls:
  http://localhost:8080/
  http://non-fqd/path

It appears the hostname must have at least one dot (.) in it to be found.

**Comment by xeffyr** [comment]
Closing in favor of https://github.com/termux/termux-app/issues/317.
*Agree that we need more powerful URL matcher.*
