### ISSUE TITLE
termux-open and termux-share broken after minor Android 8.1 security upgrade

### ISSUE THREAD

**Issue by consultron** [termux/termux-app#995]
**Problem description**
After upgrading my Asus Zenfone Max Pro M1 (ASUS_X00TD) with the latest security fix (January 1, 2019), neither termux-open nor termux-share are able to exchange files with other applications.

The error message presented depending on application varies, but is usually along the lines "Error copying <filename>" (AquaMail) or "File could not be scheduled for upload" (Google drive).

An excerpt from  "logcat -d" from after a termux-open invocation, full content in the attached "logcat.txt", [logcat.txt](https://github.com/termux/termux-app/files/2796788/logcat.txt)

01-25 16:39:10.541 20935 20935 W ADebug  : Failed to get property persist.sys.media.traces
01-25 16:39:10.571 20935 20935 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10115 <<<<<<
01-25 16:39:10.709 20935 20935 I /system/bin/app_process: The ClassLoaderContext is a special shared library.
01-25 16:39:10.771 20935 20935 D AndroidRuntime: Calling main entry com.example.termuxam.Am
01-25 16:39:10.868 20935 20935 D AndroidRuntime: Shutting down VM
01-25 16:39:11.241  6257  8443 W ContentProvider: Normalized content://com.termux.files//data/data/com.termux/files/home/1548312079.png to content://com.termux.files/data/data/com.termux/files/home/1548312079.png to avoid possible security issues
01-25 16:39:11.254  6257  8443 W ContentProvider: Normalized content://com.termux.files//data/data/com.termux/files/home/1548312079.png to content://com.termux.files/data/data/com.termux/files/home/1548312079.png to avoid possible security issues
01-25 16:39:11.256  6257  8443 E DatabaseUtils: Writing exception to parcel
01-25 16:39:11.256  6257  8443 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.termux.app.TermuxOpenReceiver$ContentProvider uri content://com.termux.files/data/data/com.termux/files/home/1548312079.png from pid=19689, uid=10083 requires android.permission.permRead, or grantUriPermission()
01-25 16:39:11.256  6257  8443 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:633)
01-25 16:39:11.256  6257  8443 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:503)
01-25 16:39:11.256  6257  8443 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:214)
01-25 16:39:11.256  6257  8443 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
01-25 16:39:11.256  6257  8443 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:697)

**Steps to reproduce**
1. Verify that termux-open works as expected.
2. Upgrade Android 8.1 with said Android minor upgrade.
3. termux-open will now have stopped working.

**Expected behavior**
Unchanged behavior of termux-open and termux-share before and after the security upgrade. :)

**Additional information**
termux-info:
Updatable packages:
All packages up to date
System information:
Linux localhost 4.4.78-perf+ #1 SMP PREEMPT Tue Jan 8 13:27:12 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.1.0
Device manufacturer:
asus
Device model:
ASUS_X00TD

**Steps attempted to rectify error condition**

1. Turning off and on storage permission in the termux-app
2. Clearing the cache of the termux-app
3. Re-running termux-setup-storage
4. Clearing the cache of the termux-api
5. Removing and re-installing termux-api
6. pkg uninstall / install of termux-api

Happy to act as a guinea pig if I can contribute to solving this one!

**Comment by consultron** [comment]
Update: Uninstalled every termux packages, restarted phone, re-installed termux and ran termux-setup-storage and granted storage privilege. The problem still remains.

Next step is to restore phone to factory settings (which has cleared up this issue on an earlier occasion on my Zenfone Max 3) but holding out on that for a while to have a test setup should anyone want to take a stab on the issue.

Rsyncing back data for the NAS again - my local cpio backup onto the Termux area on the sdcard got scrapped when re-installing, for some reason I had believed that it would've been persistent. :)

**Comment by consultron** [comment]
I've been able to work around the problem, hopefully this can shed some light to the root cause and a potential "real" fix down the line.

I got a bit suspicious of the "normalizing" action in the logfile:

`01-25 16:39:11.241 6257 8443 W ContentProvider: Normalized content://com.termux.files//data/data/com.termux/files/home/1548312079.png to content://com.termux.files/data/data/com.termux/files/home/1548312079.png to avoid possible security issues`

Thus, I patched termux-open [patch1](https://github.com/termux/termux-app/files/2800066/termux-open.patch.txt) and 
termux-share [patch2](https://github.com/termux/termux-app/files/2800067/termux-share.patch.txt) which get rids of the initial slash in the filename in the am invocation, going from:

`broadcast --user 0 -a android.intent.action.VIEW -n com.termux/com.termux.app.TermuxOpenReceiver -d /data/data/com.termux/files/home/1548312079.png`

to

`broadcast --user 0 -a android.intent.action.VIEW -n com.termux/com.termux.app.TermuxOpenReceiver -d data/data/com.termux/files/home/1548312079.png
`

and this actually made things work again - no errors, just:

```
01-27 14:25:18.948 15048 15048 W ADebug  : Failed to get property persist.sys.media.traces
01-27 14:25:18.969 15048 15048 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10115 <<<<<<
01-27 14:25:19.070 15048 15048 I /system/bin/app_process: The ClassLoaderContext is a special shared library.
01-27 14:25:19.109 15048 15048 D AndroidRuntime: Calling main entry com.example.termuxam.Am
01-27 14:25:19.152 15048 15048 D AndroidRuntime: Shutting down VM
```
Now, how this problem surfaced only after the Android minor upgrade I have no clue - but the patches solves things for me at least.

**Comment by xeffyr** [comment]
@consultron I guess the "security issue" was in specifying paths that pretend to be absolute, though I can be wrong...

**Comment by fornwall** [comment]
@consultron Thanks a lot for the detailed information!

Both `termux-open` and `termux-share` has been changed to avoid this problem - does it work fine after updating packages with `pkg up`?

**Comment by consultron** [comment]
@fornwall I'm just happy to get the opportunity to help out in the smallest way to one of favourite projects - and wow, you're quick! :)

Indeed, after a package upgrade things works just fine on both of my 8.1 devices (and no regression on my trusty 6.0.1 tablet) so from my end the issue can be closed as fixed. Many thanks!
