### ISSUE TITLE
i still can't write to the sdcard but someone closed the issue

### ISSUE THREAD

**Issue by D4rkH0rs3** [termux/termux-app#996]
i still can't write to the sdcard but someone closed the issue, apparently because there was abtechnical discussion of potential ways to implement a solution.  Still broke, reopening.

**Comment by xeffyr** [comment]
a. **Android prohibits filesystem level access to the EXTERNAL sdcards**.
b. **It is not possible to use Storage Access Framework with CLI programs.**
c. **FUSE on Android is allowed only for root.**
d. **We are not going to bloat application with various "hacks".**

I should continue ??

**Comment by xeffyr** [comment]
BTW, there is still partial access to the external sdcard. Use tool "termux-setup-storage" - it will create necessary dirs/symlinks, e.g. ~/storage/external-1 which is private Termux directory on external sdcard.
