### ISSUE TITLE
After updating 0.66, the 0.3 version of termux:tasker could not be installed.

### ISSUE THREAD

**Issue by snakwu** [termux/termux-app#998]
After updating 0.66, the 0.3 version of termux:tasker could not be installed.

**Comment by xeffyr** [comment]
Closing as I can't understand what is requested/reported here.
![2019-01-26 15-42-00](https://user-images.githubusercontent.com/25881154/51787991-2498c400-2181-11e9-8412-754c5db243b5.png)

Next time please use "Google Translate" (or similar) to translate the text to english.

**Comment by snakwu** [comment]
ok.
